### ISSUE TITLE
挂IDM下载油管视频的问题

### ISSUE THREAD

**Issue by lon91ong** [XX-net/XX-Net#10013]
下载速度一开始满速，逐渐下降，而后彻底没速度，这时网页代理也失败了，刷新状态页显示“请检查浏览器代理设置”，SwitchyOmega提示*.deja.com加载失败，这个网站之前应该设置过走代理的，现在再次添加条件依然无效。右键退出XX-net也没反应，必须用任务管理器关闭pythonw.exe再次开启才能恢复。
再次下载，毛病依然！

**Comment by nbwxbo** [comment]
也是这个问题的，求解？

**Comment by gjbg1989** [comment]
试试：结束进程 pythonw.exe，
data\gae_proxy\config.ini 添加：
[system]
fake_host = deja.com
data\gae_proxy\manual.ini 添加：
[hosts]
.deja.com = gae

**Comment by gjbg1989** [comment]
不时：http://127.0.0.1:8085/?module=gae_proxy&menu=advanced 检查 IP——开始？或：保持运行以下bat（内容）？
:loop
netsh int teredo show state
ping 127.0.0.1 > null
goto loop

**Comment by HustCoderHu** [comment]
我用IDM下Gdrive文件也遇到类似的情况，日志里面瞟到红字的一行 "can't start new thread"，然后xxnet就崩了，程序直接没了。。。。。。

**Comment by HustCoderHu** [comment]
Mar 15 15:07:10.268 - [DEBUG] RangeFetch [2404:6800:400c:5::9] 94% length:548576 range:bytes 486422952-486971527/1031933430 https://doc-0k-2k-docs.googleusercontent.com/docs/securesc/4r9unea4d5hcu26aohtg7l4v423g8koe/s39sim329k6bqqm1nkdk7caehm3depul/1521093600000/08324123372396130280/01233824902523283533/0B2AvWp2gRW0QSVEtWW1razhtc1k?e=download&nonce=gdjo14p89g1gi&user=01233824902523283533&hash=a9j6gtbqo47dosbu9t0h2fqm18hiojmo 1:start_request,1953:get_task,4:get_worker:2607:f8b0:4000:35::b,0:h1_req,0:retry,1881:get_task,172:get_worker:2404:6800:400c:5::9,0:h1_req,3307:h1_get_head,0:get_response,5299:h1_finish[SP:103793],:0

Mar 15 15:07:10.279 - [WARNING] server app return fail, status:502

Mar 15 15:07:10.280 - [DEBUG] 2a00:1450:401c:16::b worker close:range get gae status:502

Mar 15 15:07:10.513 - [WARNING] server app return fail, status:502

Mar 15 15:07:10.513 - [DEBUG] 2607:f8b0:401a:6::8 worker close:range get gae status:502

Mar 15 15:07:10.513 - [WARNING] 2607:f8b0:401a:6::8 h1_request:https://doc-0k-2k-docs.googleusercontent.com/docs/securesc/4r9unea4d5hcu26aohtg7l4v423g8koe/s39sim329k6bqqm1nkdk7caehm3depul/1521093600000/08324123372396130280/01233824902523283533/0B2AvWp2gRW0QSVEtWW1razhtc1k?e=download&nonce=gdjo14p89g1gi&user=01233824902523283533&hash=a9j6gtbqo47dosbu9t0h2fqm18hiojmo error(9, 'Bad file descriptor') time_cost:0 inactive:0

Mar 15 15:07:10.513 - [DEBUG] 2607:f8b0:401a:6::8 close:request_fail

Mar 15 15:07:10.513 - [DEBUG] 2607:f8b0:401a:6::8 worker close:request fail

Mar 15 15:07:10.584 - [WARNING] server app return fail, status:502

**Comment by HustCoderHu** [comment]
然后红字
Mar 15 15:07:21.359 - [ERROR] ssl_timeout_cb except:error("can't start new thread",)

Mar 15 15:07:21.362 - [ERROR] Except stack:Traceback (most recent call last): File "D:\BrkGFW\XX-Net-3.3.1\code\3.10.4\gae_proxy\local\connect_manager.py", line 230, in keep_alive_thread self.ssl_timeout_cb(ssl_sock) File "D:\BrkGFW\XX-Net-3.3.1\code\3.10.4\gae_proxy\local\http_dispatcher.py", line 82, in on_ssl_created_cb worker = HTTP1_worker(ssl_sock, self.close_cb, self.retry_task_cb, self._on_worker_idle_cb, self.log_debug_data) File "D:\BrkGFW\XX-Net-3.3.1\code\3.10.4\gae_proxy\local\http1.py", line 28, in __init__ threading.Thread(target=self.work_loop).start() File "D:\BrkGFW\XX-Net-3.3.1\code\3.10.4\python27\1.0\lib\threading.py", line 736, in start _start_new_thread(self.__bootstrap, ()) error: can't start new thread

Mar 15 15:07:21.365 - [ERROR] ssl_timeout_cb except:error("can't start new thread",)

Mar 15 15:07:21.367 - [ERROR] Except stack:Traceback (most recent call last): File "D:\BrkGFW\XX-Net-3.3.1\code\3.10.4\gae_proxy\local\connect_manager.py", line 230, in keep_alive_thread self.ssl_timeout_cb(ssl_sock) File "D:\BrkGFW\XX-Net-3.3.1\code\3.10.4\gae_proxy\local\http_dispatcher.py", line 82, in on_ssl_created_cb worker = HTTP1_worker(ssl_sock, self.close_cb, self.retry_task_cb, self._on_worker_idle_cb, self.log_debug_data) File "D:\BrkGFW\XX-Net-3.3.1\code\3.10.4\gae_proxy\local\http1.py", line 28, in __init__ threading.Thread(target=self.work_loop).start() File "D:\BrkGFW\XX-Net-3.3.1\code\3.10.4\python27\1.0\lib\threading.py", line 736, in start _start_new_thread(self.__bootstrap, ()) error: can't start new thread

**Comment by HustCoderHu** [comment]
@xxnet  IDM 8线程下载

**Comment by xxnet** [comment]
​can't start new thread，线程数超过系统限制。


试试下载线程调小，从1个线程开始。

**Comment by HustCoderHu** [comment]
线程试过2和4，不过2的速度上不去，下载一定量之后xxnet还是会崩。。。。
....xxnet(GoAgent那块?)的py代码里面没有用future的线程池的吗。。。不停的起线程？0.0

**Comment by xxnet** [comment]
​是的，没有用线程池。
本来想等python3 推广开了，全面升级到python3，用协程来写，不过这一步还没到。

**Comment by gjbg1989** [comment]
😱原来 IP 延迟一直只增不减，一定时间后几乎工作不正常。。。

**Comment by xxnet** [comment]
​这个问题要解决的，只需要限制启动的任务数就好了，下周试试

**Comment by gjbg1989** [comment]
#10048 😱
