### ISSUE TITLE
config.json 修改完成后 XX-Net不能启动

### ISSUE THREAD

**Issue by zz309** [XX-net/XX-Net#10059]
RT
为其他设备提供代理，在config.json里添加listen_port后保存以后，XX-Net再也启动不了了
-------------------------------------------------------------------------------------------------
Mar 17 20:44:48.353 [launcher][INFO] use build-in openssl lib
Mar 17 20:44:48.355 [launcher][INFO] start XX-Net 3.11.1
Mar 17 20:44:48.355 [launcher][DEBUG] start confirm_xxnet_exit
Mar 17 20:44:49.363 [launcher][DEBUG] good, xxnet:8085 clear!
Mar 17 20:44:49.364 [launcher][DEBUG] finished confirm_xxnet_exit
Mar 17 20:44:49.376 [launcher][ERROR] start module gae_proxy fail:Expecting , delimiter: line 3 column 3 (char 29)
Mar 17 20:44:49.381 [launcher][ERROR] Except stack:Traceback (most recent call last):
  File "D:\XX-Net-3.11.1\code\default\launcher\module_init.py", line 40, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "D:\XX-Net-3.11.1\code\default\gae_proxy\local\__init__.py", line 2, in <module>
    import apis
  File "D:\XX-Net-3.11.1\code\default\gae_proxy\local\apis.py", line 2, in <module>
    from front import front, direct_front
  File "D:\XX-Net-3.11.1\code\default\gae_proxy\local\front.py", line 7, in <module>
    import check_local_network
  File "D:\XX-Net-3.11.1\code\default\gae_proxy\local\check_local_network.py", line 28, in <module>
    from config import config
  File "D:\XX-Net-3.11.1\code\default\gae_proxy\local\config.py", line 184, in <module>
    config = Config(config_path)
  File "D:\XX-Net-3.11.1\code\default\gae_proxy\local\config.py", line 142, in __init__
    self.load()
  File "D:\XX-Net-3.11.1\code\default\gae_proxy\local\config.py", line 145, in load
    super(Config, self).load()
  File "D:\XX-Net-3.11.1\code\default\python27\1.0\lib\noarch\front_base\config.py", line 83, in load
    super(ConfigBase, self).load()
  File "D:\XX-Net-3.11.1\code\default\python27\1.0\lib\noarch\xconfig.py", line 22, in load
    self.file_config = json.loads(content)
  File "D:\XX-Net-3.11.1\code\default\python27\1.0\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "D:\XX-Net-3.11.1\code\default\python27\1.0\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\XX-Net-3.11.1\code\default\python27\1.0\lib\json\decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting , delimiter: line 3 column 3 (char 29)

Mar 17 20:44:49.384 [launcher][ERROR] launcher except:ValueError('Expecting , delimiter: line 3 column 3 (char 29)',)
Mar 17 20:44:49.387 [launcher][ERROR] Except stack:Traceback (most recent call last):
  File "D:\XX-Net-3.11.1\code\default\launcher\start.py", line 244, in <module>
    main()
  File "D:\XX-Net-3.11.1\code\default\launcher\start.py", line 221, in main
    module_init.start_all_auto()
  File "D:\XX-Net-3.11.1\code\default\launcher\module_init.py", line 113, in start_all_auto
    start(module)
  File "D:\XX-Net-3.11.1\code\default\launcher\module_init.py", line 40, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "D:\XX-Net-3.11.1\code\default\gae_proxy\local\__init__.py", line 2, in <module>
    import apis
  File "D:\XX-Net-3.11.1\code\default\gae_proxy\local\apis.py", line 2, in <module>
    from front import front, direct_front
  File "D:\XX-Net-3.11.1\code\default\gae_proxy\local\front.py", line 7, in <module>
    import check_local_network
  File "D:\XX-Net-3.11.1\code\default\gae_proxy\local\check_local_network.py", line 28, in <module>
    from config import config
  File "D:\XX-Net-3.11.1\code\default\gae_proxy\local\config.py", line 184, in <module>
    config = Config(config_path)
  File "D:\XX-Net-3.11.1\code\default\gae_proxy\local\config.py", line 142, in __init__
    self.load()
  File "D:\XX-Net-3.11.1\code\default\gae_proxy\local\config.py", line 145, in load
    super(Config, self).load()
  File "D:\XX-Net-3.11.1\code\default\python27\1.0\lib\noarch\front_base\config.py", line 83, in load
    super(ConfigBase, self).load()
  File "D:\XX-Net-3.11.1\code\default\python27\1.0\lib\noarch\xconfig.py", line 22, in load
    self.file_config = json.loads(content)
  File "D:\XX-Net-3.11.1\code\default\python27\1.0\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "D:\XX-Net-3.11.1\code\default\python27\1.0\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\XX-Net-3.11.1\code\default\python27\1.0\lib\json\decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting , delimiter: line 3 column 3 (char 29)

Press Enter to continue...

**Comment by gjbg1989** [comment]
九成 config.json 有错误，参考：#10056

**Comment by xxnet** [comment]
​在系统->设置， 打开 “远程访问”就好了，不用自己修改json

**Comment by caichy** [comment]
没有打开 “远程访问”这个设置怎么办

**Comment by gjbg1989** [comment]
没有打开想打开就打开，需要打开而没有打开就自打 PP 😂
找不到更直接明了😱
http://127.0.0.1:8085/?module=launcher&menu=config 允许远程访问控制页(帮助)
