### ISSUE TITLE
google相关网站总是提示要认证，快给个过滤*.google.com网站的json配置

### ISSUE THREAD

**Issue by mtgitnerd** [XX-net/XX-Net#10052]
RT
[hosts]
appengine.google.com = direct
*.googlevideo.com = direct
www.google.com = direct
www.youtube.com = direct
www.vevo.com = direct
www.gogotunnel.com = direct
www.skype.com = direct
.google.com = direct
google.com = direct
photos.google.com = direct
这个是以前的配置

求对应版本的json配置，不会写json格式的，要疯了

**Comment by gjbg1989** [comment]
貌似参照 "GAE_APPIDS" 格式？

**Comment by xxnet** [comment]
{
  "hosts_direct": [
            "scholar.google.com",
            "scholar.google.com.hk",
            "www.youtube.com",
            "photos.google.com"
 ],
  "hosts_direct_endswith": [
            ".appspot.com",
    ".google.com"
  ]
}

**Comment by mtgitnerd** [comment]
反馈错误，报以下错误
Mar 17 21:12:22.735 - [ERROR] Except stack:Traceback (most recent call last): File "D:\Programs\XX-Net\code\3.11.1\gae_proxy\local\direct_handler.py", line 58, in handler direct_front.ip_manager.report_connect_fail(response.ssl_sock.ip, force_remove=True) AttributeError: 'DirectFront' object has no attribute 'ip_manager'

**Comment by xxnet** [comment]
​注意，只有google 的域名能direct，你列出的几个域名是不能direct的：
 vevo.com
gogotunnel.com
skype.com

可以考虑通过smart-router访问，把上面需要direct的域名放入smart-router的直连列表中。

**Comment by mtgitnerd** [comment]
大神们，不行啊，还是去掉了那几个还是报，在我进行google查询的时候

Mar 18 09:57:44.802 - [ERROR] direct_handler.handler AttributeError("'DirectFront' object has no attribute 'ip_manager'",) ipv4.google.com /sorry/index?continue=https://encrypted.google.com/search%3Fq%3DRevenge%2Bon%2Ba%2BGold%2BDigging%2BSlut%2Btorrent%26ei%3DZ5vUWYzyO8ycjwS334eADw%26start%3D10%26sa%3DN%26biw%3D1391%26bih%3D672&q=EgRrssIzGNmTg88FIhkA8aeDS5KHKEGduZ5qZ8CLxrb5yjs_J132MgFy , retry...

Mar 18 09:57:44.802 - [ERROR] Except stack:Traceback (most recent call last): File "D:\Programs\XX-Net\code\3.11.1\gae_proxy\local\direct_handler.py", line 58, in handler direct_front.ip_manager.report_connect_fail(response.ssl_sock.ip, force_remove=True) AttributeError: 'DirectFront' object has no attribute 'ip_manager'

Mar 18 09:57:45.101 - [WARNING] IP:2607:f8b0:401c:2::a host:ipv4.google.com not support GAE, server type:HTTP server (unknown) status:503

**Comment by mtgitnerd** [comment]
我原来设置了两个google入口
1. https://www.google.com/ncr 作为搜索标签入口
2.默认搜索引擎入口
  关键字:encrypted.google.com
  网址: https://encrypted.google.com/search?{google:acceptedSuggestion} {google:originalQueryForSuggestion}sourceid=chrome& ie={inputEncoding}&q=%s

在按照X大给的配置后，全都报上述错误............

**Comment by mtgitnerd** [comment]
我的具体配置如下:

{
  "max_scan_ip_thread_num": 50, 
  "hosts_direct": [
    "www.youtube.com", 
    "photos.google.com", 
    "appengine.google.com", 
    "www.google.com", 
    "www.youtube.com", 
    "photos.google.com"
  ], 
  "hosts_direct_endswith": [
    ".google.com", 
    ".appspot.com", 
    ".googlevideo.com"
  ]
}

**Comment by mtgitnerd** [comment]
Mar 18 10:11:24.950 - [WARNING] 2607:f8b0:400a:5::15 h1_request:Exception('time out',) inactive_time:109 task.timeout:30

Mar 18 10:11:24.950 - [WARNING] 2607:f8b0:400a:5::15 trace: 0:connect, 1363:init, 83643:request,:30001, processed:0, transfered:0, sni:

Mar 18 10:11:24.950 - [DEBUG] GET encrypted.google.com/search?{google:acceptedSuggestion}%20oq=ncr&sourceid=chrome&%20ie=UTF-8&q=ncr response_fail:retry timeout:30

Mar 18 10:11:24.951 - [ERROR] direct_handler.handler AttributeError("'BaseResponse' object has no attribute 'ssl_sock'",) encrypted.google.com /search?{google:acceptedSuggestion}%20oq=ncr&sourceid=chrome&%20ie=UTF-8&q=ncr , retry...

Mar 18 10:11:24.951 - [DEBUG] 2607:f8b0:400a:5::15 worker close:down fail

Mar 18 10:11:24.951 - [DEBUG] 2607:f8b0:400a:5::15 close:down fail

Mar 18 10:11:24.952 - [ERROR] Except stack:Traceback (most recent call last): File "D:\Programs\XX-Net\code\3.11.1\gae_proxy\local\direct_handler.py", line 57, in handler response.ssl_sock.ip, host, server_type, response.status) AttributeError: 'BaseResponse' object has no attribute 'ssl_sock'

Mar 18 10:11:24.953 - [WARNING] send response fail

Mar 18 10:11:31.937 - [INFO] GAE CONNECT www.google.com:443

Mar 18 10:11:31.962 - [DEBUG] GAE CONNECT Direct GET https://www.google.com/ncr

Mar 18 10:11:32.415 - [WARNING] send response fail

**Comment by gjbg1989** [comment]
按大佬的设置，https://www.google.com/ncr
![image](https://user-images.githubusercontent.com/13290970/37561980-d135110a-2a97-11e8-9990-23213baf99f5.png)
https://encrypted.google.com/search?{google:acceptedSuggestion}
![image](https://user-images.githubusercontent.com/13290970/37561987-f39a2ffa-2a97-11e8-908f-dc253b105100.png)
😂正常不？

**Comment by gjbg1989** [comment]
其它2自动切换都能正常打开，也有：连接超时，先休息一会再来！尤其是 https://www.google.com/ncr

**Comment by mtgitnerd** [comment]
可我这里就是死活过不去了...

**Comment by gjbg1989** [comment]
请问，你。。。
😱约2小时测试：强烈建议用回 3.10.8，按 #10048 修改 target_handshake_time 后，正常到你无法想象😱

**Comment by gjbg1989** [comment]
请问：2.默认搜索引擎入口
关键字:encrypted.google.com
网址: https://encrypted.google.com/search?{google:acceptedSuggestion} {google:originalQueryForSuggestion}sourceid=chrome& ie={inputEncoding}&q=%s
![image](https://user-images.githubusercontent.com/13290970/37562154-d4425066-2a9b-11e8-9df9-431f268676e1.png)
3行怎么填？

**Comment by gjbg1989** [comment]
请问，以下填写
![image](https://user-images.githubusercontent.com/13290970/37562224-51393af6-2a9e-11e8-9567-eaaebf9409ce.png)
第一行名称，可随意
第二行关键字：encrypted.google.com
第三行网址： https://encrypted.google.com/search?{google:acceptedSuggestion} {google:originalQueryForSuggestion}sourceid=chrome& ie={inputEncoding}&q=%s
作为默认搜索引擎后，新开空白页，不见如本贴第1图式的输入窗口？

**Comment by mtgitnerd** [comment]
是这么设置的，现在的问题是，使用3.10.8版本依然在使用https://www.google.com/ncr的时候报ipv4机器人验证页面.......

**Comment by gjbg1989** [comment]
试试：把浏览器代理插件里的 *.google.com 走 GAE 规则删除

**Comment by mtgitnerd** [comment]
试了，不管用

**Comment by gjbg1989** [comment]
貌似刷新或重来也行，或
修改过 target_handshake_time 的3.10.8调整扫描线程到100，
http://127.0.0.1:8085/?module=gae_proxy&menu=advanced 检查 IP，速度提升或扫描完后再 https://www.google.com/ncr

**Comment by gggccc44** [comment]
感觉这个新格式没以前方便啊，以前可以注释掉一行，需要了再改回来

不过貌似可以用smart-router暂时解决，但是貌似目前还不完善，smart-router会造成cpu占用高

**Comment by gjbg1989** [comment]
感觉这个新格式没以前方便啊——😂与程序语言相关、配套？非程序员。。。
cpu占用高——使用 3.111.0/1 ？#100118

**Comment by gggccc44** [comment]
@gjbg1989 换了3.10了，cpu下来了，3.11.1不用smart-router占用也很高，试了几个版本，好在现在换版本比较方便，本来我是想换3.8.5的，但是直接在设置里面换了以后有问题

**Comment by gjbg1989** [comment]
貌似 3.8.5 无法正常😂

**Comment by gggccc44** [comment]
@gjbg1989 可能手工从新设置可以，我从3.11.1降级失败，可能是配置文件问题

**Comment by gjbg1989** [comment]
貌似从3.8.6-3.11.1都可以共用设置（除了CPU）。。。
http://127.0.0.1:8085/?module=gae_proxy&menu=advanced 检查 IP，稍侯。。。

**Comment by gggccc44** [comment]
@gjbg1989 看说明是3.10.6才开始的新格式设置

有点想换个华硕路由器刷梅林

**Comment by gjbg1989** [comment]
3.10.5开始的 config.json，以前 manual.ini + config.ini

**Comment by lon91ong** [comment]
{
  "hosts_direct": [
            "scholar.google.com",
            "scholar.google.com.hk",
            "www.youtube.com",
            "photos.google.com"
 ],
  "hosts_direct_endswith": [
            ".appspot.com",
    ".google.com"
  ]
}
上面的两个部分分别是什么意思？ *.deja.com要怎么填？

**Comment by xxnet** [comment]
​hosts_direct
  是明确的域名，

hosts_direct_endswith
  是域名后缀模式

deja 不在这里设置。

**Comment by gjbg1989** [comment]
deja 不在这里设置——😱不是：
{
"hosts_gae": [
    "deja.com", 
    "twimg.com", 
    "twitter.com"
  ]
}

**Comment by xxnet** [comment]
​不是的，hosts_gae的意思是，要通过GAE进行代理。

而deja.com 只是用来探测浏览器有没有设置代理到XX-Net上。

如果设置对了，状态页会访问deja.com/xxnet， 而XX-Net会返回一个特定的结果，以此来判断浏览器代理设置是否正确。
之前用twitter.com，但是发现Chrome浏览器会自动把 http://twitter.com
的请求，转成https的请求，导致如果证书没有导入，
也判断为代理没有设置好。

deja.com 这个域名是老的黑名单，目前这个网站已经不存在了，所以拿来作为判断用。
