### ISSUE TITLE
Mac下部署失败（提示ValidationError），求大佬！！

### ISSUE THREAD

**Issue by Kyxy** [XX-net/XX-Net#10062]
* 简单描述遇到的问题：mac下部署appid一直失败

* 做过哪些尝试：尝试了ss部署，还是失败，ValidationError: Value '600' for response_code is out of range 100 - 599。在win下成功部署，就是mac下不行。

* 请贴出对应模块的状态页

* 请贴出相关的日志
2018-03-17 21:52:10,182 - root - INFO - Retry 2 time...
2018-03-17 21:52:11,204 - root - INFO - Send: /api/appversion/rollback, params={'version': '1', 'app_id': 'xxnetkyxy'}
2018-03-17 21:52:11,204 - google.appengine.tools.appengine_rpc - DEBUG - _Authenticate skipped auth; needs_auth=False
2018-03-17 21:52:11,204 - google.appengine.tools.appengine_rpc - DEBUG - Sending request to https://appengine.google.com/api/appversion/rollback?app_id=xxnetkyxy&force_rollback=0&version=1 headers={'X-appcfg-api-version': '1', 'content-length': '0', 'Content-Type': 'application/octet-stream'} body=
2018-03-17 21:52:41,377 - google.appengine.tools.appengine_rpc - DEBUG - Got http error 600.
2018-03-17 21:52:41,377 - google.appengine.tools.appengine_rpc - DEBUG - Unexpected results: {'status': '600', 'content-length': '135', 'connection': 'close'}
2018-03-17 21:52:41,377 - root - ERROR - upload fail:ValidationError("Value '600' for response_code is out of range 100 - 599",)
Traceback (most recent call last):
File "/Users/kyxy/Downloads/XX-Net-3.11.1/code/default/gae_proxy/server/uploader.py", line 70, in upload
result = appcfg.AppCfgApp(['appcfg', 'rollback', dirname ]).Run()
File "/Users/kyxy/Downloads/XX-Net-3.11.1/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 2951, in Run
self.action(self)
File "/Users/kyxy/Downloads/XX-Net-3.11.1/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 5044, in __call__
return method()
File "/Users/kyxy/Downloads/XX-Net-3.11.1/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 4397, in Rollback
self._Rollback()
File "/Users/kyxy/Downloads/XX-Net-3.11.1/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 4442, in _Rollback
appversion.Rollback(force_rollback)
File "/Users/kyxy/Downloads/XX-Net-3.11.1/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 2362, in Rollback
force_rollback='1' if force_rollback else '0')
File "/Users/kyxy/Downloads/XX-Net-3.11.1/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 1702, in Send
request_size_bytes)
File "/Users/kyxy/Downloads/XX-Net-3.11.1/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 1723, in _RegisterReqestForLogging
request_size_bytes=request_size_bytes))
File "/Users/kyxy/Downloads/XX-Net-3.11.1/code/default/gae_proxy/server/lib/google/appengine/api/validation.py", line 273, in __init__
self.SetMultiple(attributes)
File "/Users/kyxy/Downloads/XX-Net-3.11.1/code/default/gae_proxy/server/lib/google/appengine/api/validation.py", line 177, in SetMultiple
self.Set(key, value)
File "/Users/kyxy/Downloads/XX-Net-3.11.1/code/default/gae_proxy/server/lib/google/appengine/api/validation.py", line 305, in Set
setattr(self, key, value)
File "/Users/kyxy/Downloads/XX-Net-3.11.1/code/default/gae_proxy/server/lib/google/appengine/api/validation.py", line 361, in __setattr__
value = self.GetValidator(key)(value, key)
File "/Users/kyxy/Downloads/XX-Net-3.11.1/code/default/gae_proxy/server/lib/google/appengine/api/validation.py", line 599, in __call__
return self.Validate(value, key)
File "/Users/kyxy/Downloads/XX-Net-3.11.1/code/default/gae_proxy/server/lib/google/appengine/api/validation.py", line 1157, in Validate
% (value, key, self.minimum, self.maximum))
ValidationError: Value '600' for response_code is out of range 100 - 599
2018-03-17 21:52:41,378 - root - INFO - Retry 3 time...
2018-03-17 21:52:43,384 - root - INFO - =======================
2018-03-17 21:52:43,384 - root - INFO - Deploy failed appid list:
2018-03-17 21:52:43,384 - root - INFO - - xxnetkyxy
2018-03-17 21:52:43,384 - root - INFO - == END ==

**Comment by Kyxy** [comment]
开启IPV6即可解决...
