### ISSUE TITLE
状态页一片空白，按要求检测了

### ISSUE THREAD

**Issue by kuromai** [XX-net/XX-Net#1013]
我是win864位系统，按指引说的点开start.bat看了看，如下，求帮忙看看。。。
今天突然变成这样的，昨天还用的好好的。
————————————————————————————————
D:\XX-Net-2.0.7>SET PYTHONPATH=

D:\XX-Net-2.0.7>"D:\XX-Net-2.0.7\python27/1.0/python.exe" "D:\XX-Net-2.0.7\launc
her/start.py"
Sep 14 12:51:23 - [DEBUG] start confirm_xxnet_exit
Sep 14 12:51:24 - [INFO] load manual.ini success
Sep 14 12:51:24 - [ERROR] start module gae_proxy fail:No option 'connect_interva
l' in section: 'connect_manager'
Traceback (most recent call last):
  File "D:\XX-Net-2.0.7\launcher\module_init.py", line 36, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['loca
l', 'start'], -1)
  File "D:\XX-Net-2.0.7\gae_proxy\start.py", line 13, in <module>
    import local.proxy as client
  File "D:\XX-Net-2.0.7\gae_proxy\local\proxy.py", line 77, in <module>
    from cert_util import CertUtil
  File "D:\XX-Net-2.0.7\gae_proxy\local\cert_util.py", line 44, in <module>
    from config import config
  File "D:\XX-Net-2.0.7\gae_proxy\local\config.py", line 151, in <module>
    config.load()
  File "D:\XX-Net-2.0.7\gae_proxy\local\config.py", line 125, in load
    self.connect_interval = config.CONFIG.getint("connect_manager", "connect_int
erval")
  File "D:\XX-Net-2.0.7\python27\1.0\lib\ConfigParser.py", line 359, in getint
    return self._get(section, int, option)
  File "D:\XX-Net-2.0.7\python27\1.0\lib\ConfigParser.py", line 356, in _get
    return conv(self.get(section, option))
  File "D:\XX-Net-2.0.7\python27\1.0\lib\ConfigParser.py", line 618, in get
    raise NoOptionError(option, section)
NoOptionError: No option 'connect_interval' in section: 'connect_manager'

Sep 14 12:51:24 - [INFO] start gae_proxy time cost 62
Sep 14 12:51:25 - [INFO] get uuid:759f873f-eab5-4292-b765-ddf3e3dfbe92
Sep 14 12:51:26 - [WARNING] check_update fail:URLError(error(10061, ''),)
Sep 14 12:51:26 - [INFO] download https://raw.githubusercontent.com/XX-net/XX-Ne
t/master/README.md to D:\XX-Net-2.0.7\data\downloads\README.md
Sep 14 12:51:27 - [ERROR] download https://raw.githubusercontent.com/XX-net/XX-N
et/master/README.md to D:\XX-Net-2.0.7\data\downloads\README.md fail:URLError(er
ror(10061, ''),)
Traceback (most recent call last):
  File "D:\XX-Net-2.0.7\launcher\update_from_github.py", line 64, in download_fi
le
    req = opener.open(url)
  File "D:\XX-Net-2.0.7\python27\1.0\lib\urllib2.py", line 404, in open
    response = self._open(req, data)
  File "D:\XX-Net-2.0.7\python27\1.0\lib\urllib2.py", line 422, in _open
    '_open', req)
  File "D:\XX-Net-2.0.7\python27\1.0\lib\urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "D:\XX-Net-2.0.7\python27\1.0\lib\urllib2.py", line 1222, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "D:\XX-Net-2.0.7\python27\1.0\lib\urllib2.py", line 1184, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 10061] >

Sep 14 12:51:27 - [ERROR] check_update fail:IOError('get README https://raw.gith
ubusercontent.com/XX-net/XX-Net/master/README.md fail:',)
Traceback (most recent call last):
  File "D:\XX-Net-2.0.7\launcher\update.py", line 241, in check_update
    versions = update_from_github.get_github_versions()
  File "D:\XX-Net-2.0.7\launcher\update_from_github.py", line 106, in get_github
_versions
    raise IOError("get README %s fail:" % readme_url)
IOError: get README https://raw.githubusercontent.com/XX-net/XX-Net/master/READM
E.md fail:

**Comment by xxnet** [comment]
怀疑你的安装包不完整，请重新下载，确认大小

2015-09-14 12:57 GMT+08:00 kuromai <notifications@github.com>:
