### ISSUE TITLE
3.11.3 error

### ISSUE THREAD

**Issue by lxeridium** [XX-net/XX-Net#10157]
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/xai/proxy/XX-Net/code/3.11.3/gae_proxy/start.py", line 18, in main
    client.main(args)
  File "/home/xai/proxy/XX-Net/code/3.11.3/gae_proxy/local/proxy.py", line 116, in main
    log_info()
  File "/home/xai/proxy/XX-Net/code/3.11.3/gae_proxy/local/proxy.py", line 105, in log_info
    xlog.info('GAE APPID          : %s', '|'.join(front.config.GAE_APPIDS))
  File "/home/xai/proxy/XX-Net/code/3.11.3/python27/1.0/lib/noarch/xlog.py", line 166, in info
    self.log('INFO', self.reset_color, '000000', fmt, *args)
  File "/home/xai/proxy/XX-Net/code/3.11.3/python27/1.0/lib/noarch/xlog.py", line 116, in log
    string = '%s - [%s] %s\n' % (time_str, level, fmt % args)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 1: ordinal not in range(128)

**Comment by slimwang** [comment]
## 解决字符集编码错误  
打开`/XX-Net/code/3.11.3/python27/1.0/lib/noarch/xlog.py`
插入以下代码
```python
import sys
reload(sys)
sys.setdefaultencoding('utf8')
```

**Comment by xxnet** [comment]
@​lxeridium
试试上面的方法，看看能否解决

**Comment by yyy123zc** [comment]
在linux系统(deepin15.5、archlinux、fedora27、openSUSE Tumbleweed)中3.11.3插入#10157指定代码后正常运行。

**Comment by xxnet** [comment]
​好的， 3.11.4 已经包含这个修复
