### ISSUE TITLE
状态栏空白

### ISSUE THREAD

**Issue by z563721** [XX-net/XX-Net#1017]
D:\GoAgent\XX-Net-2.0.5>SET PYTHONPATH=

D:\GoAgent\XX-Net-2.0.5>"D:\GoAgent\XX-Net-2.0.5\python27/1.0/python.exe" "D:\Go
Agent\XX-Net-2.0.5\launcher/start.py"
Sep 14 19:11:01 - [DEBUG] start confirm_xxnet_exit
Sep 14 19:11:02 - [ERROR] start module gae_proxy fail:No option 'connect_interva
l' in section: 'connect_manager'
Traceback (most recent call last):
  File "D:\GoAgent\XX-Net-2.0.5\launcher\module_init.py", line 34, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['loca
l', 'start'], -1)
  File "D:\GoAgent\XX-Net-2.0.5\gae_proxy\start.py", line 13, in <module>
    import local.proxy as client
  File "D:\GoAgent\XX-Net-2.0.5\gae_proxy\local\proxy.py", line 77, in <module>
    from cert_util import CertUtil
  File "D:\GoAgent\XX-Net-2.0.5\gae_proxy\local\cert_util.py", line 44, in <modu
le>
    from config import config
  File "D:\GoAgent\XX-Net-2.0.5\gae_proxy\local\config.py", line 151, in <module
>
    config.load()
  File "D:\GoAgent\XX-Net-2.0.5\gae_proxy\local\config.py", line 125, in load
    self.connect_interval = config.CONFIG.getint("connect_manager", "connect_int
erval")
  File "D:\GoAgent\XX-Net-2.0.5\python27\1.0\lib\ConfigParser.py", line 359, in
getint
    return self._get(section, int, option)
  File "D:\GoAgent\XX-Net-2.0.5\python27\1.0\lib\ConfigParser.py", line 356, in
_get
    return conv(self.get(section, option))
  File "D:\GoAgent\XX-Net-2.0.5\python27\1.0\lib\ConfigParser.py", line 618, in
get
    raise NoOptionError(option, section)
NoOptionError: No option 'connect_interval' in section: 'connect_manager'

Sep 14 19:11:02 - [INFO] start gae_proxy time cost 62
Sep 14 19:11:03 - [INFO] get uuid:d09ae70e-e2bb-42b6-b55b-ac1d666258c6
Sep 14 19:11:04 - [WARNING] check_update fail:URLError(error(10061, ''),)
Sep 14 19:11:04 - [INFO] download https://raw.githubusercontent.com/XX-net/XX-Ne
t/master/README.md to D:\GoAgent\XX-Net-2.0.5\data\downloads\README.md
Sep 14 19:11:05 - [ERROR] download https://raw.githubusercontent.com/XX-net/XX-N
et/master/README.md to D:\GoAgent\XX-Net-2.0.5\data\downloads\README.md fail:URL
Error(error(10061, ''),)
Traceback (most recent call last):
  File "D:\GoAgent\XX-Net-2.0.5\launcher\update_from_github.py", line 64, in dow
nload_file
    req = opener.open(url)
  File "D:\GoAgent\XX-Net-2.0.5\python27\1.0\lib\urllib2.py", line 404, in open
    response = self._open(req, data)
  File "D:\GoAgent\XX-Net-2.0.5\python27\1.0\lib\urllib2.py", line 422, in _open

    '_open', req)
  File "D:\GoAgent\XX-Net-2.0.5\python27\1.0\lib\urllib2.py", line 382, in _call
_chain
    result = func(*args)
  File "D:\GoAgent\XX-Net-2.0.5\python27\1.0\lib\urllib2.py", line 1222, in http
s_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "D:\GoAgent\XX-Net-2.0.5\python27\1.0\lib\urllib2.py", line 1184, in do_o
pen
    raise URLError(err)
URLError: <urlopen error [Errno 10061] >

Sep 14 19:11:05 - [ERROR] check_update fail:IOError('get README https://raw.gith
ubusercontent.com/XX-net/XX-Net/master/README.md fail:',)
Traceback (most recent call last):
  File "D:\GoAgent\XX-Net-2.0.5\launcher\update.py", line 241, in check_update
    versions = update_from_github.get_github_versions()
  File "D:\GoAgent\XX-Net-2.0.5\launcher\update_from_github.py", line 106, in ge
t_github_versions
    raise IOError("get README %s fail:" % readme_url)
IOError: get README https://raw.githubusercontent.com/XX-net/XX-Net/master/READM
E.md fail:

**Comment by xxnet** [comment]
看看 gae_proxy/local/proxy.ini 的内容，里面有没有 connect_interval ?

不行就重新下载一个，或者试试2.4.0 版本

2015-09-14 19:22 GMT+08:00 z563721 <notifications@github.com>:

**Comment by matrixirtam** [comment]
任务管理器里查看是否有 python.exe 或者pythonw.exe 都关掉再开

**Comment by z563721** [comment]
已重新下载部署

在 2015年9月14日 下午8:13，matrixirtam <notifications@github.com>写道：
