### ISSUE TITLE
今天开始状态栏是空白的。昨天晚上还能正常使用。

### ISSUE THREAD

**Issue by KeymanLai** [XX-net/XX-Net#1018]
![qq 20150914202112](https://cloud.githubusercontent.com/assets/12146207/9849548/841998f0-5b1e-11e5-8fc4-dc50377d51e0.jpg)

**Comment by KeymanLai** [comment]
重新下载的beat版2.1.2状态栏也是空白页。

**Comment by Cat7373** [comment]
打开任务管理器，检查有无python或者pythonw的进程，有则结束掉，即可解决这个问题。

**Comment by S-Aoi** [comment]
解决不了，我也同样空白
```
D:\Portable_Apps\XX-Net>SET PYTHONPATH=

D:\Portable_Apps\XX-Net>"D:\Portable_Apps\XX-Net\python27/1.0/python.exe" "D:\Portable_Apps\XX-Net\launcher/start.py"
Sep 15 00:27:43 - [DEBUG] start confirm_xxnet_exit
Sep 15 00:27:44 - [ERROR] start module gae_proxy fail:No option 'connect_interval' in section: 'connect_manager'
Traceback (most recent call last):
  File "D:\Portable_Apps\XX-Net\launcher\module_init.py", line 36, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "D:\Portable_Apps\XX-Net\gae_proxy\start.py", line 13, in <module>
    import local.proxy as client
  File "D:\Portable_Apps\XX-Net\gae_proxy\local\proxy.py", line 77, in <module>
    from cert_util import CertUtil
  File "D:\Portable_Apps\XX-Net\gae_proxy\local\cert_util.py", line 44, in <module>
    from config import config
  File "D:\Portable_Apps\XX-Net\gae_proxy\local\config.py", line 151, in <module>
    config.load()
  File "D:\Portable_Apps\XX-Net\gae_proxy\local\config.py", line 125, in load
    self.connect_interval = config.CONFIG.getint("connect_manager", "connect_interval")
  File "D:\Portable_Apps\XX-Net\python27\1.0\lib\ConfigParser.py", line 359, in getint
    return self._get(section, int, option)
  File "D:\Portable_Apps\XX-Net\python27\1.0\lib\ConfigParser.py", line 356, in _get
    return conv(self.get(section, option))
  File "D:\Portable_Apps\XX-Net\python27\1.0\lib\ConfigParser.py", line 618, in get
    raise NoOptionError(option, section)
NoOptionError: No option 'connect_interval' in section: 'connect_manager'

Sep 15 00:27:44 - [INFO] start gae_proxy time cost 78
Sep 15 00:27:45 - [INFO] get uuid:1025649b-cf5c-4877-b48d-858b679be047
Sep 15 00:27:46 - [WARNING] check_update fail:URLError(error(10061, ''),)
Sep 15 00:27:46 - [INFO] download https://raw.githubusercontent.com/XX-net/XX-Net/master/README.md to D:\Portable_Apps\XX-Net\data\downloads\README.md
Sep 15 00:27:47 - [ERROR] download https://raw.githubusercontent.com/XX-net/XX-Net/master/README.md to D:\Portable_Apps\XX-Net\data\downloads\README.md fail:URLError(error(10061, ''),)
Traceback (most recent call last):
  File "D:\Portable_Apps\XX-Net\launcher\update_from_github.py", line 64, in download_file
    req = opener.open(url)
  File "D:\Portable_Apps\XX-Net\python27\1.0\lib\urllib2.py", line 404, in open
    response = self._open(req, data)
  File "D:\Portable_Apps\XX-Net\python27\1.0\lib\urllib2.py", line 422, in _open
    '_open', req)
  File "D:\Portable_Apps\XX-Net\python27\1.0\lib\urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "D:\Portable_Apps\XX-Net\python27\1.0\lib\urllib2.py", line 1222, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "D:\Portable_Apps\XX-Net\python27\1.0\lib\urllib2.py", line 1184, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 10061] >

Sep 15 00:27:47 - [ERROR] check_update fail:IOError('get README https://raw.githubusercontent.com/XX-net/XX-Net/master/README.md fail:',)
Traceback (most recent call last):
  File "D:\Portable_Apps\XX-Net\launcher\update.py", line 241, in check_update
    versions = update_from_github.get_github_versions()
  File "D:\Portable_Apps\XX-Net\launcher\update_from_github.py", line 106, in get_github_versions
    raise IOError("get README %s fail:" % readme_url)
IOError: get README https://raw.githubusercontent.com/XX-net/XX-Net/master/README.md fail:
```

**Comment by UltraDWS** [comment]
Cat7373提供的解决方案同样有效。

**Comment by pnjgyl** [comment]
我昨天从2.3.0升级到2.4.0后正常使用, 后来退了xx-net再启动就空白了. 杀pythonw也没有用, 最后下个新的2.4.0从新开start就好了. 麻烦作者考虑一下是否自动升级的功能有问题吧, 需要的话我重新用2.3.0自动升级一个贴日志.

**Comment by Cat7373** [comment]
现在已知的有两个问题
1、进程退不出去需手动结束
2、connect_interval的设置问题
一般状态页空白检查这两部分都能解决

**Comment by pnjgyl** [comment]
1 进程没退出, 这个问题以前发生过的确会导致状态页空白, 需要进任务管理器杀pythonw.exe.(这次不是这个原因)
2 看了一下, 我原来的版本是2.1.2自动升级到2.3.0, 昨天升级到2.4.0. 查看2.1.2\gae_proxy\local\proxy.ini, 发现相对于data\2.4.0\gae_proxy\local\proxy.ini, 缺少以下内容. 是不是就是这个的原因了?
------------------------------以下是2.1.2的ini比2.4.0少的内容-------------
forward_max_connect_thread = 10
; limit interval for two tcp connect try.
; too frequently connect to google ip may make GFW block all google ip for you.
connect_interval = 40

**Comment by xxnet** [comment]
从早期1.x.x 版本，升级到 2.x.x 本身结构是不兼容的，不过没有做好升级处理，大家手动下载升级吧。
  可以保留之前扫描到的ip： 拷贝 data/gae_proxy/good_ip.txt 过去

最近还怀疑升级XX-Net存在被阻断，导致下载更新的文件不完整，升级机制需要加入完整性检查。

2015-09-15 9:19 GMT+08:00 pnjgyl <notifications@github.com>:

**Comment by mtvktvcn** [comment]
我也是这样.一启动就空白页

**Comment by lbrant** [comment]
同样遇到这个问题，更新后就是这样

**Comment by xxnet** [comment]
更新失败，请重新下载新版

2015-09-15 13:57 GMT+08:00 Brant <notifications@github.com>:

**Comment by aOJzQT** [comment]
从GitHub上下载文件速度时好时坏，不光是GitHub，所有https的下载共匪都在试图限速或中途掐断连接
