### ISSUE TITLE
XX-NET打开失败了

### ISSUE THREAD

**Issue by MrSong0607** [XX-net/XX-Net#1020]
C:\Users\Administrator\Desktop\XX-Net-2.0.5>SET PYTHONPATH=

C:\Users\Administrator\Desktop\XX-Net-2.0.5>"C:\Users\Administrator\Desktop\XX-N
et-2.0.5\python27/1.0/python.exe" "C:\Users\Administrator\Desktop\XX-Net-2.0.5\l
auncher/start.py"
Sep 15 08:24:24 - [DEBUG] start confirm_xxnet_exit
Sep 15 08:24:25 - [ERROR] start module gae_proxy fail:No option 'connect_interva
l' in section: 'connect_manager'
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\XX-Net-2.0.5\launcher\module_init.py", li
ne 34, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['loca
l', 'start'], -1)
  File "C:\Users\Administrator\Desktop\XX-Net-2.0.5\gae_proxy\start.py", line 13
, in <module>
    import local.proxy as client
  File "C:\Users\Administrator\Desktop\XX-Net-2.0.5\gae_proxy\local\proxy.py", l
ine 77, in <module>
    from cert_util import CertUtil
  File "C:\Users\Administrator\Desktop\XX-Net-2.0.5\gae_proxy\local\cert_util.py
", line 44, in <module>
    from config import config
  File "C:\Users\Administrator\Desktop\XX-Net-2.0.5\gae_proxy\local\config.py",
line 151, in <module>
    config.load()
  File "C:\Users\Administrator\Desktop\XX-Net-2.0.5\gae_proxy\local\config.py",
line 125, in load
    self.connect_interval = config.CONFIG.getint("connect_manager", "connect_int
erval")
  File "C:\Users\Administrator\Desktop\XX-Net-2.0.5\python27\1.0\lib\ConfigParse
r.py", line 359, in getint
    return self._get(section, int, option)
  File "C:\Users\Administrator\Desktop\XX-Net-2.0.5\python27\1.0\lib\ConfigParse
r.py", line 356, in _get
    return conv(self.get(section, option))
  File "C:\Users\Administrator\Desktop\XX-Net-2.0.5\python27\1.0\lib\ConfigParse
r.py", line 618, in get
    raise NoOptionError(option, section)
NoOptionError: No option 'connect_interval' in section: 'connect_manager'

Sep 15 08:24:25 - [INFO] start gae_proxy time cost 26
Sep 15 08:24:26 - [INFO] get uuid:37fbe90a-03c9-4283-8792-f926313e4d0c
Sep 15 08:24:27 - [WARNING] check_update fail:URLError(error(10061, ''),)
Sep 15 08:24:27 - [INFO] download https://raw.githubusercontent.com/XX-net/XX-Ne
t/master/README.md to C:\Users\Administrator\Desktop\XX-Net-2.0.5\data\downloads
\README.md
Sep 15 08:24:28 - [ERROR] download https://raw.githubusercontent.com/XX-net/XX-N
et/master/README.md to C:\Users\Administrator\Desktop\XX-Net-2.0.5\data\download
s\README.md fail:URLError(error(10061, ''),)
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\XX-Net-2.0.5\launcher\update_from_github.
py", line 64, in download_file
    req = opener.open(url)
  File "C:\Users\Administrator\Desktop\XX-Net-2.0.5\python27\1.0\lib\urllib2.py"
, line 404, in open
    response = self._open(req, data)
  File "C:\Users\Administrator\Desktop\XX-Net-2.0.5\python27\1.0\lib\urllib2.py"
, line 422, in _open
    '_open', req)
  File "C:\Users\Administrator\Desktop\XX-Net-2.0.5\python27\1.0\lib\urllib2.py"
, line 382, in _call_chain
    result = func(*args)
  File "C:\Users\Administrator\Desktop\XX-Net-2.0.5\python27\1.0\lib\urllib2.py"
, line 1222, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "C:\Users\Administrator\Desktop\XX-Net-2.0.5\python27\1.0\lib\urllib2.py"
, line 1184, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 10061] >

Sep 15 08:24:28 - [ERROR] check_update fail:IOError('get README https://raw.gith
ubusercontent.com/XX-net/XX-Net/master/README.md fail:',)
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\XX-Net-2.0.5\launcher\update.py", line 24
1, in check_update
    versions = update_from_github.get_github_versions()
  File "C:\Users\Administrator\Desktop\XX-Net-2.0.5\launcher\update_from_github.
py", line 106, in get_github_versions
    raise IOError("get README %s fail:" % readme_url)
IOError: get README https://raw.githubusercontent.com/XX-net/XX-Net/master/READM
E.md fail:

**Comment by xxnet** [comment]
怀疑升级到中间失败了，请重新下载一个新版的重新安装。

升级要加完整性检查了。

2015-09-15 8:25 GMT+08:00 MrSong0607 <notifications@github.com>:

**Comment by Dannywanxyz** [comment]
![image](https://cloud.githubusercontent.com/assets/13790928/9866461/3471a44c-5b95-11e5-801b-90faa6d78e86.png)
状态栏显示空白

**Comment by MrSong0607** [comment]
下了测试版重装了，能用

**Comment by Dannywanxyz** [comment]
可以使用了，谢谢

MrSong0607 <notifications@github.com>于2015-9-15 10:39 周二写道：
