### ISSUE TITLE
2.4.0启动空白，求帮助

### ISSUE THREAD

**Issue by eta01** [XX-net/XX-Net#1023]
现在用2.4.0版本，昨天还能用，今天就启动不起来了：“状态页显示空白, 很可能GAEProxy启动失败, 请按指引查找问题原因.”
求指导！

日志如下：

F:\XX-Net-2.0.2>SET PYTHONPATH=

F:\XX-Net-2.0.2>"F:\XX-Net-2.0.2\python27/1.0/python.exe" "F:\XX-Net-2.0.2\launc
her/start.py"
Sep 15 10:29:59 - [DEBUG] start confirm_xxnet_exit
Sep 15 10:30:00 - [INFO] load manual.ini success
Sep 15 10:30:00 - [ERROR] start module gae_proxy fail:No module named env_info
Traceback (most recent call last):
  File "F:\XX-Net-2.0.2\launcher\module_init.py", line 36, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['loca
l', 'start'], -1)
  File "F:\XX-Net-2.0.2\gae_proxy\start.py", line 13, in <module>
    import local.proxy as client
  File "F:\XX-Net-2.0.2\gae_proxy\local\proxy.py", line 83, in <module>
    import proxy_handler
  File "F:\XX-Net-2.0.2\gae_proxy\local\proxy_handler.py", line 24, in <module>
    from connect_manager import https_manager,forwork_manager
  File "F:\XX-Net-2.0.2\gae_proxy\local\connect_manager.py", line 42, in <module
>
    from google_ip import google_ip
  File "F:\XX-Net-2.0.2\gae_proxy\local\google_ip.py", line 28, in <module>
    import check_ip
  File "F:\XX-Net-2.0.2\gae_proxy\local\check_ip.py", line 35, in <module>
    from connect_control import scan_sleep
  File "F:\XX-Net-2.0.2\gae_proxy\local\connect_control.py", line 8, in <module>

    import env_info
ImportError: No module named env_info

Sep 15 10:30:00 - [INFO] start gae_proxy time cost 70
Sep 15 10:30:01 - [INFO] get uuid:87b5a18d-8cbd-47d4-bb9d-526246d6d506
Sep 15 10:30:02 - [WARNING] check_update fail:URLError(error(10061, ''),)
Sep 15 10:30:02 - [INFO] download https://raw.githubusercontent.com/XX-net/XX-Ne
t/master/README.md to F:\XX-Net-2.0.2\data\downloads\README.md

**Comment by xxnet** [comment]
应该是升级出问题了，github 下载文件被截断。请重新下载2.4.0 版本解压。

2015-09-15 10:31 GMT+08:00 eta01 <notifications@github.com>:

**Comment by eta01** [comment]
好使了，谢谢大神！！！
