### ISSUE TITLE
部署失败 409

### ISSUE THREAD

**Issue by 4what2do** [XX-net/XX-Net#10259]
2018-03-29 13:29:39,555 - root - INFO - set proxy to http://127.0.0.1:8087
2018-03-29 13:29:39,559 - root - INFO - ============ Begin upload ============
2018-03-29 13:29:39,559 - root - INFO - appid:xixi47572
2018-03-29 13:29:39,578 - root - INFO - Send: /api/appversion/rollback, params={'version': '1', 'app_id': 'xixi47572'}
2018-03-29 13:29:48,611 - root - ERROR - upload fail:ValidationError("Value '600' for response_code is out of range 100 - 599",)
Traceback (most recent call last):
File "C:\Users\Administrator\Downloads\XX-Net-3.11.6\code\default\gae_proxy\server\uploader.py", line 70, in upload
result = appcfg.AppCfgApp(['appcfg', 'rollback', dirname ]).Run()
File "C:\Users\Administrator\Downloads\XX-Net-3.11.6\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 2951, in Run
self.action(self)
File "C:\Users\Administrator\Downloads\XX-Net-3.11.6\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 5044, in __call__
return method()
File "C:\Users\Administrator\Downloads\XX-Net-3.11.6\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 4397, in Rollback
self._Rollback()
File "C:\Users\Administrator\Downloads\XX-Net-3.11.6\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 4442, in _Rollback
appversion.Rollback(force_rollback)
File "C:\Users\Administrator\Downloads\XX-Net-3.11.6\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 2362, in Rollback
force_rollback='1' if force_rollback else '0')
File "C:\Users\Administrator\Downloads\XX-Net-3.11.6\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 1702, in Send
request_size_bytes)
File "C:\Users\Administrator\Downloads\XX-Net-3.11.6\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 1723, in _RegisterReqestForLogging
request_size_bytes=request_size_bytes))
File "C:\Users\Administrator\Downloads\XX-Net-3.11.6\code\default\gae_proxy\server\lib\google\appengine\api\validation.py", line 273, in __init__
self.SetMultiple(attributes)
File "C:\Users\Administrator\Downloads\XX-Net-3.11.6\code\default\gae_proxy\server\lib\google\appengine\api\validation.py", line 177, in SetMultiple
self.Set(key, value)
File "C:\Users\Administrator\Downloads\XX-Net-3.11.6\code\default\gae_proxy\server\lib\google\appengine\api\validation.py", line 305, in Set
setattr(self, key, value)
File "C:\Users\Administrator\Downloads\XX-Net-3.11.6\code\default\gae_proxy\server\lib\google\appengine\api\validation.py", line 361, in __setattr__
value = self.GetValidator(key)(value, key)
File "C:\Users\Administrator\Downloads\XX-Net-3.11.6\code\default\gae_proxy\server\lib\google\appengine\api\validation.py", line 599, in __call__
return self.Validate(value, key)
File "C:\Users\Administrator\Downloads\XX-Net-3.11.6\code\default\gae_proxy\server\lib\google\appengine\api\validation.py", line 1157, in Validate
% (value, key, self.minimum, self.maximum))
ValidationError: Value '600' for response_code is out of range 100 - 599
2018-03-29 13:29:48,614 - root - INFO - Retry 1 time...
2018-03-29 13:29:48,631 - root - INFO - Send: /api/appversion/rollback, params={'version': '1', 'app_id': 'xixi47572'}
2018-03-29 13:31:41,161 - oauth2client.client - INFO - Successfully retrieved access token
2018-03-29 13:31:42,062 - root - INFO - Checking for updates to the SDK.
2018-03-29 13:31:42,997 - root - INFO - Update check failed: HTTP Error 403: OK Unexpected HTTP status 403
2018-03-29 13:31:43,000 - root - INFO - Reading app configuration.
2018-03-29 13:31:43,000 - root - INFO - Send: /api/appversion/getresourcelimits, params={'version': '1', 'app_id': 'xixi47572'}
2018-03-29 13:31:43,775 - root - INFO - Processing file 'app.template.yaml'
2018-03-29 13:31:43,775 - root - INFO - Processing file 'app.yaml'
2018-03-29 13:31:43,776 - root - INFO - Processing file 'gae.py'
2018-03-29 13:31:43,776 - root - INFO - Processing file 'legacy.py'
2018-03-29 13:31:43,776 - root - INFO - Processing file 'wsgi.py'
2018-03-29 13:31:43,780 - root - INFO - Send: /api/appversion/create, params={'version': '1', 'app_id': 'xixi47572'}
2018-03-29 13:31:45,710 - root - INFO - Send: /api/appversion/clonefiles, params={'version': '1', 'app_id': 'xixi47572'}
2018-03-29 13:31:46,614 - root - INFO - Adding file app.yaml (391 bytes, type=application/octet-stream) to batch.
2018-03-29 13:31:46,615 - root - INFO - Uploading batch of 1 files to /api/appversion/addfiles with boundary="boundary".
2018-03-29 13:31:46,617 - root - INFO - Send: /api/appversion/addfiles, params={'version': '1', 'app_id': 'xixi47572'}
2018-03-29 13:31:47,848 - root - INFO - Send: /api/appversion/precompile, params={'version': '1', 'app_id': 'xixi47572'}
2018-03-29 13:31:48,661 - root - INFO - Send: /api/appversion/deploy, params={'version': '1', 'app_id': 'xixi47572'}
2018-03-29 13:33:23,683 - root - INFO - Too many retries for url https://appengine.google.com/api/appversion/deploy?app_id=xixi47572&version=1
2018-03-29 13:33:23,684 - root - INFO - HTTP Error (HTTP Error 409: OK)
2018-03-29 13:33:23,687 - root - INFO - Send: /api/appversion/rollback, params={'version': '1', 'app_id': 'xixi47572'}
2018-03-29 13:33:25,003 - root - INFO - Send: /api/appversion/rollback, params={'version': '1', 'app_id': 'xixi47572'}
2018-03-29 13:33:25,987 - root - INFO - Checking for updates to the SDK.
2018-03-29 13:33:27,484 - root - INFO - Update check failed: HTTP Error 403: OK Unexpected HTTP status 403
2018-03-29 13:33:27,486 - root - INFO - Reading app configuration.
2018-03-29 13:33:27,486 - root - INFO - Send: /api/appversion/getresourcelimits, params={'version': '1', 'app_id': 'xixi47572'}
2018-03-29 13:33:29,233 - root - INFO - Processing file 'app.template.yaml'
2018-03-29 13:33:29,236 - root - INFO - Processing file 'app.yaml'
2018-03-29 13:33:29,239 - root - INFO - Processing file 'gae.py'
2018-03-29 13:33:29,242 - root - INFO - Processing file 'legacy.py'
2018-03-29 13:33:29,243 - root - INFO - Processing file 'wsgi.py'
2018-03-29 13:33:29,259 - root - INFO - Send: /api/appversion/create, params={'version': '1', 'app_id': 'xixi47572'}
2018-03-29 13:33:30,861 - root - INFO - Send: /api/appversion/clonefiles, params={'version': '1', 'app_id': 'xixi47572'}
2018-03-29 13:33:32,601 - root - INFO - Send: /api/appversion/precompile, params={'version': '1', 'app_id': 'xixi47572'}
2018-03-29 13:33:33,628 - root - INFO - Send: /api/appversion/deploy, params={'version': '1', 'app_id': 'xixi47572'}
2018-03-29 13:34:40,063 - root - INFO - Too many retries for url https://appengine.google.com/api/appversion/deploy?app_id=xixi47572&version=1
2018-03-29 13:34:40,065 - root - INFO - HTTP Error (HTTP Error 409: OK)
2018-03-29 13:34:40,065 - root - INFO - Send: /api/appversion/rollback, params={'version': '1', 'app_id': 'xixi47572'}
2018-03-29 13:34:41,263 - root - INFO - =======================
2018-03-29 13:34:41,263 - root - INFO - Deploy failed appid list:
2018-03-29 13:34:41,263 - root - INFO - - xixi47572
2018-03-29 13:34:41,265 - root - INFO - == END ==

**Comment by Zhoudf** [comment]
同问，409
