### ISSUE TITLE
启动后日志状态也都是空白，

### ISSUE THREAD

**Issue by rainman09** [XX-net/XX-Net#1028]
启动后日志和状态页都是空白。
双击start.bat后内容如下
Sep 15 13:17:25 - [ERROR] check_update fail:IOError('get README https://raw.gith
ubusercontent.com/XX-net/XX-Net/master/README.md fail:',)
Traceback (most recent call last):
  File "D:\XX-Net-2.0.5\launcher\update.py", line 241, in check_update
    versions = update_from_github.get_github_versions()
  File "D:\XX-Net-2.0.5\launcher\update_from_github.py", line 106, in get_github
_versions
    raise IOError("get README %s fail:" % readme_url)
IOError: get README https://raw.githubusercontent.com/XX-net/XX-Net/master/READM
E.md fail:

**Comment by xxnet** [comment]
这是检查更新失败，不影响使用，2.4.0 开始已经改为警告而不是错误

2015-09-15 13:23 GMT+08:00 rainman09 <notifications@github.com>:

**Comment by rainman09** [comment]
谢谢，我升级到2.4.0可以用了
