### ISSUE TITLE
注册APPID失败，参考了4720

### ISSUE THREAD

**Issue by shpherd** [XX-net/XX-Net#10302]
本人多次按>-连接cloud shell失败（没有信用卡，不能注册 Google Cloud Platform免费使用）。使用Deploy_XXNET_Server报错。
=============================================================== 
 XXNET 服务端部署程序, 开始上传 gae 应用文件夹
 Linux/Mac 用户, 请使用 python uploader.py 来上传应用
===============================================================

请输入您的appid, 多个appid请用|号隔开
注意：appid 请勿包含 ios/android/mobile 等字样，否则可能被某些网站识别成移动设备
。
APPID:orange
Traceback (most recent call last):
  File "python27.py", line 95, in <module>
  File "G:\Deploy_XXNET_Server\uploader.py", line 141, in <module>
    main()
  File "G:\Deploy_XXNET_Server\uploader.py", line 127, in main
    upload('gae', appid)
  File "G:\Deploy_XXNET_Server\uploader.py", line 111, in upload
    appcfg.main(['appcfg', 'rollback', dirname])
  File "G:\Deploy_XXNET_Server\google_appengine\google\appengine\tools\appcfg.py
", line 5388, in main
    result = AppCfgApp(argv).Run()
  File "G:\Deploy_XXNET_Server\google_appengine\google\appengine\tools\appcfg.py
", line 2951, in Run
    self.action(self)
  File "G:\Deploy_XXNET_Server\google_appengine\google\appengine\tools\appcfg.py
", line 5044, in __call__
    return method()
  File "G:\Deploy_XXNET_Server\google_appengine\google\appengine\tools\appcfg.py
", line 4397, in Rollback
    self._Rollback()
  File "G:\Deploy_XXNET_Server\google_appengine\google\appengine\tools\appcfg.py
", line 4419, in _Rollback
    module_yaml = self._ParseAppInfoFromYaml(self.basepath)
  File "G:\Deploy_XXNET_Server\google_appengine\google\appengine\tools\appcfg.py
", line 3313, in _ParseAppInfoFromYaml
    appyaml = self._ParseYamlFile(basepath, basename, appinfo_includes.Parse)
  File "G:\Deploy_XXNET_Server\google_appengine\google\appengine\tools\appcfg.py
", line 3393, in _ParseYamlFile
    defns = parser(fh, open_fn=self.opener)
  File "google_appengine\google\appengine\api\appinfo_includes.py", line 57, in
Parse
    appyaml, _ = ParseAndReturnIncludePaths(appinfo_file, open_fn)
  File "google_appengine\google\appengine\api\appinfo_includes.py", line 82, in
ParseAndReturnIncludePaths
    appyaml = appinfo.LoadSingleAppInfo(appinfo_file)
  File "google_appengine\google\appengine\api\appinfo.py", line 2200, in LoadSin
gleAppInfo
    raise appinfo_errors.EmptyConfigurationFile()
google.appengine.api.appinfo_errors.EmptyConfigurationFile

**Comment by lucifinilsu** [comment]
信用卡？为啥我注册谷歌云申请appid啥也没要

**Comment by shpherd** [comment]
估计cloud shell有什么问题所以连接不上，也无法安装cloudsdk

**Comment by SeaHOH** [comment]
orange 你也照搬？

**Comment by shpherd** [comment]
我的APPID用orange代替。不是说Deploy_XXNET_Server肯定能搞定吗？我用XX-NET上的。

**Comment by SeaHOH** [comment]
建议直接从网页 UI 中启动部署。

**Comment by shpherd** [comment]
由于客户端网络错误，无法连接到 Cloud Shell。请确保您已连接到互联网，并且您的网络代理设置允许连接到 Cloud Shell。 关闭

**Comment by SeaHOH** [comment]
https://github.com/XX-net/XX-Net/wiki/“部署服务端”页面

**Comment by shpherd** [comment]
我申请的APPID是无效ID，参考4720的办法不成功。不是部署问题。

**Comment by SeaHOH** [comment]
那你贴这一堆部署日志是干嘛。。。
解决方法：
1. 申请 AppID 时不要在互动教程进行部署。
1. 使用网页 UI 部署。
1. 如果部署了互动教程 App，进入 https://console.cloud.google.com ，先把流量拆分到另一个没有流量的版本，即 XX-Net 服务端，然后删除先前有流量的哪个版本，即互动教程版本。

**Comment by shpherd** [comment]
申请APPID总转到“hello world”教程。即生成了空ID。没有实例。
![default](https://user-images.githubusercontent.com/33240748/38252254-3c7a755e-3786-11e8-8998-123d3aa24245.png)

按4720有2个解决方案。
1启动google cloud shell。我启动从来不能连接成功。
2Deploy_XXNET_Server从本机部署appid到服务器端。我报了一堆错。

**Comment by SeaHOH** [comment]
使用网页 UI 部署。
