### ISSUE TITLE
fail:No option 'connect_interval' in section: 'connect_manager'

### ISSUE THREAD

**Issue by getGitxxx** [XX-net/XX-Net#1032]
Sep 15 16:20:01 - [ERROR] start module gae_proxy fail:No option 'connect_interval' in section: 'connect_manager'
Traceback (most recent call last):
  File "D:\XX-Net-2.0.5\launcher\module_init.py", line 34, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "D:\XX-Net-2.0.5\gae_proxy\start.py", line 13, in <module>
    import local.proxy as client
  File "D:\XX-Net-2.0.5\gae_proxy\local\proxy.py", line 77, in <module>
    from cert_util import CertUtil
  File "D:\XX-Net-2.0.5\gae_proxy\local\cert_util.py", line 44, in <module>
    from config import config
  File "D:\XX-Net-2.0.5\gae_proxy\local\config.py", line 151, in <module>
    config.load()
  File "D:\XX-Net-2.0.5\gae_proxy\local\config.py", line 125, in load
    self.connect_interval = config.CONFIG.getint("connect_manager", "connect_interval")
  File "D:\XX-Net-2.0.5\python27\1.0\lib\ConfigParser.py", line 359, in getint
    return self._get(section, int, option)
  File "D:\XX-Net-2.0.5\python27\1.0\lib\ConfigParser.py", line 356, in _get
    return conv(self.get(section, option))
  File "D:\XX-Net-2.0.5\python27\1.0\lib\ConfigParser.py", line 618, in get
    raise NoOptionError(option, section)
NoOptionError: No option 'connect_interval' in section: 'connect_manager'

**Comment by xxnet** [comment]
请重新下载安装包解压

2015-09-15 16:21 GMT+08:00 getGitxxx <notifications@github.com>:
