### ISSUE TITLE
Teredo 检测&筛选脚本 [pteredor]

### ISSUE THREAD

**Issue by SeaHOH** [XX-net/XX-Net#10328]
https://github.com/SeaHOH/pteredor

1. 运行环境：Python 2 + win_inet_pton & Python 3
1. 采用符合 teredo 标准的路由请求进行初始化检测并统计耗时
1. Windows 下可选择是否设置成脚本推荐的服务器

本人没有使用 teredo 隧道，只是做了简单测试，麻烦大家测试一下 @beiking

**Comment by YuzhouZhang** [comment]
很赞！

**Comment by beiking** [comment]
好，，我测试下

**Comment by chendaihang** [comment]
@SeaHOH 这玩意能不能做成linux或openwrt的teredo客户端

**Comment by chendaihang** [comment]
@SeaHOH IPv4连不上没有IPV6，teredo能替代ipv6，特别是在openwrt等嵌入式路由器上 这个要是能搞成类似teredo上时，感觉用处很大啊。
--- 
运行py文件出现以下提示
其他文件调用
try bind local port: 4944
Starting probe NAT type...
Traceback (most recent call last):
  File "pteredor.py", line 531, in <module>
    recommend = main(*args, local_port=local_port, remote_port=remote_port)
  File "pteredor.py", line 408, in main
    if not self.qualified:
NameError: name 'self' is not defined

**Comment by SeaHOH** [comment]
呃，最后一次改出了个 bug。。。
已修复

**Comment by AnyWAT** [comment]
增加一个使用 XX-Net 自带 Python 启动的 bat，解压到 XX-Net 根目录即可运行。
pteredor.zip
![default](https://user-images.githubusercontent.com/37962734/38476904-ad99e02a-3be2-11e8-9327-4651d3b3e9b9.png)

**Comment by kapans** [comment]
这啥意思？？？

  File "E:\SOFTWARE\NET\PROXY\XX-Net\pteredor.py", line 397
    def main(*args, local_port=None, remote_port=None):
                             ^
SyntaxError: invalid syntax
请按任意键继续. . .

**Comment by SeaHOH** [comment]
好吧，只在之前测试了 Pyton2，等我改一下。

**Comment by SeaHOH** [comment]
OK，改好了。

**Comment by AnyWAT** [comment]
😱海GG的 pteredor.zip 对我机器下毒🤣
![default](https://user-images.githubusercontent.com/37962734/38478378-e0b1f13e-3bea-11e8-8d3c-bbe323359374.PNG)
![1](https://user-images.githubusercontent.com/37962734/38478385-f4a99908-3bea-11e8-9928-ca54d92ade19.PNG)
![3](https://user-images.githubusercontent.com/37962734/38478409-1fb49d50-3beb-11e8-9806-9c210c1b7cf9.PNG)

**Comment by SeaHOH** [comment]
@AnyWAT 不要搞这么夸张，你能正常使用就不要捣乱了。
之前就说过 symmetric（对称）NAT 的问题，如果侦测到是 symmetric 就不会改动。

**Comment by SeaHOH** [comment]
算了，我再加一点选择，是否强制测试并设定。

**Comment by SeaHOH** [comment]
搜了半天还是没搞懂 natawareclient（启用 Teredo 客户端并标识 NAT 类型） 的意思。
@AnyWAT 所以问一下你的本地网络环境大概是怎样的结构？

**Comment by SeaHOH** [comment]
嗯，enterpriseclient 知道是什么意思，但是 natawareclient 就不懂了，所以想知道你的网络环境来推断一下。
路由器拨号？本机拨号？ISP NAT？等等

**Comment by AnyWAT** [comment]
路由器拨号
英文系统会否清晰些？
![default](https://user-images.githubusercontent.com/37962734/38480713-a28cdef0-3bf9-11e8-9dff-dc427ad5d00d.png)

**Comment by SeaHOH** [comment]
你贴的这个我知道，上面不是说了，只是想知道你的网络结构，又不要你家地址。。。

**Comment by SeaHOH** [comment]
路由器拨号？本机拨号？ISP NAT？

**Comment by AnyWAT** [comment]
😂爬。。。

**Comment by SeaHOH** [comment]
爬？

**Comment by AnyWAT** [comment]
楼上已回：路由器拨号，😂ISP NAT 怎知、怎回？移动
本机自动获取（路由设各用网设备静态IP）

**Comment by SeaHOH** [comment]
了解，谢谢。 :smiley_cat:

**Comment by SeaHOH** [comment]
改好了，就等 Win10 来测试了。

**Comment by AnyWAT** [comment]
😜还让我来？

**Comment by SeaHOH** [comment]
现在你也可以用了，不会再像之前那样。 @AnyWAT

**Comment by AnyWAT** [comment]
![default](https://user-images.githubusercontent.com/37962734/38482056-4f7009de-3c00-11e8-9891-cbe878e44e1f.png)
😋神逻辑：
The recommend server is ['teredo.iks-jena.de'].
Do you want to set recommend teredo server, Y/N? y
。。。
服务器名称 : win1710.ipv6.microsoft.com.

**Comment by SeaHOH** [comment]
:trollface: 我看看怎么回事

**Comment by SeaHOH** [comment]
@AnyWAT 弹权限申请没有？

**Comment by AnyWAT** [comment]
有？。。。允许更改计算机。。。

**Comment by SeaHOH** [comment]
感觉不像，是不是没点对，再试一次？ @AnyWAT

**Comment by AnyWAT** [comment]
弹权限申请，点的“是”1+1=2次
貌似这次对了，运行前 win1711.ipv6.microsoft.com. 运行后 win1710.ipv6.microsoft.com. （原来也带尾巴，只是窗口显示内容没尾巴） 
The recommend server is ['win10.ipv6.microsoft.com', 'win1710.ipv6.microsoft.com', 'win1711.ipv6.microsoft.com'].
![default](https://user-images.githubusercontent.com/37962734/38483570-facf1310-3c05-11e8-81e6-12c7271a17e5.png)

**Comment by SeaHOH** [comment]
不对，应该是第一个。

**Comment by AnyWAT** [comment]
那就更神奇了，先改用（不带尾巴） netsh int ipv6 set teredo enterpriseclient win1710.ipv6.microsoft.com
![default](https://user-images.githubusercontent.com/37962734/38483850-f0cc151a-3c06-11e8-89bc-d544fa0818bc.png)

**Comment by AnyWAT** [comment]
Win10系统默认 win1710.ipv6.microsoft.com.

**Comment by SeaHOH** [comment]
好奇怪，你这个，难道权限不对？

**Comment by SeaHOH** [comment]
我重新写了下获取权限部分。

**Comment by SeaHOH** [comment]
就是说设置没有改变啰

**Comment by AnyWAT** [comment]
上面：类型、服务器名称及客户端端口都变了（图略）
类型 enterpriseclient 变成 natawareclient
服务器名称 win1711.ipv6.microsoft.com 变成 win1710.ipv6.microsoft.com.
客户端端口 3544 变成 default（未定义）

**Comment by AnyWAT** [comment]
恢复系统默认服务器及参数，管理权限运行（结果最后带尾巴）
netsh int ipv6 set teredo default default default default

**Comment by SeaHOH** [comment]
是带尾巴的，只是不显示在输出中。

**Comment by whhxmwhh** [comment]
404: Not Found

**Comment by whhxmwhh** [comment]
去你的项目下载了，可是出错
![default](https://user-images.githubusercontent.com/7959854/38656135-2902c686-3e4b-11e8-9bf9-1547631d015f.JPG)

**Comment by AnyWAT** [comment]
对于 offline 或 disable，优先：管理权限运行 netsh int ipv6 set teredo default default default default
貌似Win7的默认服务器不行，用 win10.ipv6.microsoft.com. 或 win1710.ipv6.microsoft.com. 或   win1711.ipv6.microsoft.com.default. 替代第一个 default

**Comment by SeaHOH** [comment]
@AnyWAT 看脚本输出就能发现，微软这几个服务器域名，有时会解析出同一个 IP，反正总共就那么几个。
重启电脑后，解析到的 IP 可能就跟上次不一样了。

**Comment by whhxmwhh** [comment]
可是我操作一遍后，ipv6 有是能用了。。神奇。

**Comment by whhxmwhh** [comment]
XX-Net Status:

sys-platform: x86, Windows-10-10.0.15063
os-system: Windows
os-version: 10.0.15063
os-release: 10
os-detail: Version:10-0; Build:15063; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
xxnet-version: 3.11.9
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:1000 ipv4:0 ipv6:1001
ipv4-status: OK
ipv6-status: OK
connected-link: new:1
worker: h1:53 h2:0
scan-ip-thread-num: 40
ip-quality: 313
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by beiking** [comment]
![20180503125855](https://user-images.githubusercontent.com/12060194/39560617-23b020a6-4ed2-11e8-8dcc-7149b7bf1fa6.png)

检测后的推荐服务器，与最终设置的服务器不一致。
@SeaHOH

**Comment by SeaHOH** [comment]
是很奇怪，上面出现过一次 https://github.com/XX-net/XX-Net/issues/10328#issuecomment-379644996 ，没发现哪里的问题。
怀疑和脚本无关，因为设置前后服务器无变化。

**Comment by beiking** [comment]
设置前后服务器有变化，，我这是多次测试了，所以前后服务器都是win1711.ipv6.mircrosoft.com。
如果你原服务器不是 win1711.ipv6.mircrosoft.com，新设置的服务器就会变成win1711.ipv6.mircrosoft.com。

我之前没发现是因为我检测出来的推荐服务器就是 win1711.ipv6.mircrosoft.com
而这次我换了个网络测试，才发现这问题。

**Comment by SeaHOH** [comment]
我实在想象不出是怎么回事。。。
因为引用的是同一个变量，中间并无任何其它赋值操作。

**Comment by beiking** [comment]
@SeaHOH 
原因找到了
pteredor.py 596行，，要改为 cmd += ' refreshinterval=default'
漏了一个空格

**Comment by SeaHOH** [comment]
还是你眼神好使，自己写的怎么都看不出来。

**Comment by caitianzhu** [comment]
win10.ipv6.microsoft.com
teredo-debian.remlab.net
出现问题就互换服务器，我只用这两个，再到所有控制面板项\网络连接（禁用/启用）在用的连接。- -我是这样解决抽风的

**Comment by nlpsuge** [comment]
支持Linux?

**Comment by SeaHOH** [comment]
Linux 支持检测，不支持设置。
