### ISSUE TITLE
2.1.2状态页无显示

### ISSUE THREAD

**Issue by davidkunlamwong** [XX-net/XX-Net#1036]
图片发不了我码字吧
Exception happened during process of request from ('127.0.0.1', 54579)
Traceback (most recent call last):
 File "C:\XX-Net-2.1.2\python27\1.0\lib\SocketServer.py", line 593 in process_ request_thread
   self.finish_request(request, client_address)
 File "C:\XX-Net-2.1.2\launcher\web_control.py", line 48, in finish_request
   self.RequestHandlerClass(request, client_address, self)
 File "C:\XX-Net-2.1.2\python27\1.0\lib\SocketServer.py", line 649, in **init**

   self.handle()
 File "C:\XX-Net-2.1.2\python27\1.0\lib\BaseHTTPServer.py", line 340, in handle

   self.handle_one_request
 File "C:\XX-Net-2.1.2\python27\1.0\lib\BaseHTTPServer.py", line 328, in handle_one_request
   method()
 File "C:\XX-Net-2.1.2\python27\1.0\lib\web_control.py", line 143, in do_GET
   controler=module_init.proc_handler[module]["imp"].local.web_control.ControlHandler(self.client_address, self.headers, self.command, path, self.rfile, self.wfile)
KeyError:'imp'

**Comment by xxnet** [comment]
启动有问题，要看启动的异常。
可以用start.bat 启动看看。

另外最近自动升级有问题，试试下载新版重新执行看看效果

2015-09-15 20:17 GMT+08:00 david10208 <notifications@github.com>:

**Comment by david10208** [comment]
用start.bat启动的
开头显示：
C:\WINDOWS\system32>SET PYTHONPATH=

C:\WINDOWS\system32>"C:\XX-Net-2.1.2\python/1.0/python.exe" "C:\XX-Net-2.1.2\launcher/start.py"
Sep 17 00:01:46 - [DEBUG] start confirm_xxnet_exit
Sep 17 00:01:47 - [ERROR] start module gae_proxy fail:No option ' connect_interval' in section: ' connect_manager'
不知道是不是ERROR这段红字呢

**Comment by xxnet** [comment]
试试重新下载一个，应该是自动升级，下载包被墙截断了导致

2015-09-17 0:08 GMT+08:00 david10208 <notifications@github.com>:

**Comment by david10208** [comment]
原来如此 谢谢
