### ISSUE TITLE
3.11.9 好像启动不了

### ISSUE THREAD

**Issue by abigbone** [XX-net/XX-Net#10408]
* 做过哪些尝试：
1、重启电脑
2、切换到3.10.4正常。

**Comment by abigbone** [comment]
好像是10.4以上的都启动失败~~

日志如下`decode(s)
  File "D:\XX-Net-3.8.7\code\3.10.4\python27\1.0\lib\json\decoder.py", line 367, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 19 column 1 - line 34 column 2 (char 339 - 614)

Apr 10 13:13:47.741 - [ERROR] launcher except:ValueError('Extra data: line 19 column 1 - line 34 column 2 (char 339 - 614)',)
Apr 10 13:13:47.743 - [ERROR] Except stack:Traceback (most recent call last):
  File "D:\XX-Net-3.8.7\code\3.11.9\launcher\start.py", line 247, in <module>
    main()
  File "D:\XX-Net-3.8.7\code\3.11.9\launcher\start.py", line 226, in main
    module_init.start_all_auto()
  File "D:\XX-Net-3.8.7\code\3.11.9\launcher\module_init.py", line 113, in start_all_auto
    start(module)
  File "D:\XX-Net-3.8.7\code\3.11.9\launcher\module_init.py", line 40, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "D:\XX-Net-3.8.7\code\3.11.9\gae_proxy\local\__init__.py", line 2, in <module>
    import apis
  File "D:\XX-Net-3.8.7\code\3.11.9\gae_proxy\local\apis.py", line 2, in <module>
    from front import front, direct_front
  File "D:\XX-Net-3.8.7\code\3.11.9\gae_proxy\local\front.py", line 7, in <module>
    import check_local_network
  File "D:\XX-Net-3.8.7\code\3.11.9\gae_proxy\local\check_local_network.py", line 28, in <module>
    from config import config
  File "D:\XX-Net-3.8.7\code\3.11.9\gae_proxy\local\config.py", line 221, in <module>
    config = Config(config_path)
  File "D:\XX-Net-3.8.7\code\3.11.9\gae_proxy\local\config.py", line 169, in __init__
    self.load()
  File "D:\XX-Net-3.8.7\code\3.11.9\gae_proxy\local\config.py", line 172, in load
    super(Config, self).load()
  File "D:\XX-Net-3.8.7\code\3.11.9\python27\1.0\lib\noarch\front_base\config.py", line 87, in load
    super(ConfigBase, self).load()
  File "D:\XX-Net-3.8.7\code\3.11.9\python27\1.0\lib\noarch\xconfig.py", line 22, in load
    self.file_config = json.loads(content)
  File "D:\XX-Net-3.8.7\code\3.10.4\python27\1.0\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "D:\XX-Net-3.8.7\code\3.10.4\python27\1.0\lib\json\decoder.py", line 367, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 19 column 1 - line 34 column 2 (char 339 - 614)

Apr 10 13:17:42.793 - [ERROR] stop module gae_proxy fail:'imp'
Apr 10 13:17:42.794 - [ERROR] Except stack:Traceback (most recent call last):
  File "D:\XX-Net-3.8.7\code\3.11.9\launcher\module_init.py", line 74, in stop
    _start = proc_handler[module]["imp"].start
KeyError: 'imp'

Apr 10 13:17:42.796 - [INFO] begin to exit web control
Apr 10 13:17:42.864 - [ERROR] uncaught Exception, type=<type 'exceptions.AttributeError'> value='NoneType' object has no attribute 'shutdown' traceback:<traceback object at 0x03638AF8>
Apr 10 13:17:51.295 - [DEBUG] no_mess_system
Apr 10 13:17:51.554 - [INFO] use build-in openssl lib
Apr 10 13:17:51.556 - [INFO] start XX-Net 3.11.9
Apr 10 13:17:51.557 - [DEBUG] start confirm_xxnet_exit
Apr 10 13:17:52.561 - [DEBUG] good, xxnet:8085 clear!
Apr 10 13:17:52.562 - [DEBUG] finished confirm_xxnet_exit
Apr 10 13:17:52.597 - [ERROR] start module gae_proxy fail:Extra data: line 19 column 1 - line 34 column 2 (char 339 - 614)
Apr 10 13:17:52.602 - [ERROR] Except stack:Traceback (most recent call last):
  File "D:\XX-Net-3.8.7\code\3.11.9\launcher\module_init.py", line 40, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "D:\XX-Net-3.8.7\code\3.11.9\gae_proxy\local\__init__.py", line 2, in <module>
    import apis
  File "D:\XX-Net-3.8.7\code\3.11.9\gae_proxy\local\apis.py", line 2, in <module>
    from front import front, direct_front
  File "D:\XX-Net-3.8.7\code\3.11.9\gae_proxy\local\front.py", line 7, in <module>
    import check_local_network
  File "D:\XX-Net-3.8.7\code\3.11.9\gae_proxy\local\check_local_network.py", line 28, in <module>
    from config import config
  File "D:\XX-Net-3.8.7\code\3.11.9\gae_proxy\local\config.py", line 221, in <module>
    config = Config(config_path)
  File "D:\XX-Net-3.8.7\code\3.11.9\gae_proxy\local\config.py", line 169, in __init__
    self.load()
  File "D:\XX-Net-3.8.7\code\3.11.9\gae_proxy\local\config.py", line 172, in load
    super(Config, self).load()
  File "D:\XX-Net-3.8.7\code\3.11.9\python27\1.0\lib\noarch\front_base\config.py", line 87, in load
    super(ConfigBase, self).load()
  File "D:\XX-Net-3.8.7\code\3.11.9\python27\1.0\lib\noarch\xconfig.py", line 22, in load
    self.file_config = json.loads(content)
  File "D:\XX-Net-3.8.7\code\3.11.9\python27\1.0\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "D:\XX-Net-3.8.7\code\3.11.9\python27\1.0\lib\json\decoder.py", line 367, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 19 column 1 - line 34 column 2 (char 339 - 614)

Apr 10 13:17:52.604 - [ERROR] launcher except:ValueError('Extra data: line 19 column 1 - line 34 column 2 (char 339 - 614)',)
Apr 10 13:17:52.608 - [ERROR] Except stack:Traceback (most recent call last):
  File "D:\XX-Net-3.8.7\code\3.11.9\launcher\start.py", line 247, in <module>
    main()
  File "D:\XX-Net-3.8.7\code\3.11.9\launcher\start.py", line 226, in main
    module_init.start_all_auto()
  File "D:\XX-Net-3.8.7\code\3.11.9\launcher\module_init.py", line 113, in start_all_auto
    start(module)
  File "D:\XX-Net-3.8.7\code\3.11.9\launcher\module_init.py", line 40, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "D:\XX-Net-3.8.7\code\3.11.9\gae_proxy\local\__init__.py", line 2, in <module>
    import apis
  File "D:\XX-Net-3.8.7\code\3.11.9\gae_proxy\local\apis.py", line 2, in <module>
    from front import front, direct_front
  File "D:\XX-Net-3.8.7\code\3.11.9\gae_proxy\local\front.py", line 7, in <module>
    import check_local_network
  File "D:\XX-Net-3.8.7\code\3.11.9\gae_proxy\local\check_local_network.py", line 28, in <module>
    from config import config
  File "D:\XX-Net-3.8.7\code\3.11.9\gae_proxy\local\config.py", line 221, in <module>
    config = Config(config_path)
  File "D:\XX-Net-3.8.7\code\3.11.9\gae_proxy\local\config.py", line 169, in __init__
    self.load()
  File "D:\XX-Net-3.8.7\code\3.11.9\gae_proxy\local\config.py", line 172, in load
    super(Config, self).load()
  File "D:\XX-Net-3.8.7\code\3.11.9\python27\1.0\lib\noarch\front_base\config.py", line 87, in load
    super(ConfigBase, self).load()
  File "D:\XX-Net-3.8.7\code\3.11.9\python27\1.0\lib\noarch\xconfig.py", line 22, in load
    self.file_config = json.loads(content)
  File "D:\XX-Net-3.8.7\code\3.11.9\python27\1.0\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "D:\XX-Net-3.8.7\code\3.11.9\python27\1.0\lib\json\decoder.py", line 367, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 19 column 1 - line 34 column 2 (char 339 - 614)

Apr 10 13:17:56.664 - [ERROR] stop module gae_proxy fail:'imp'
Apr 10 13:17:56.665 - [ERROR] Except stack:Traceback (most recent call last):
  File "D:\XX-Net-3.8.7\code\3.11.9\launcher\module_init.py", line 74, in stop
    _start = proc_handler[module]["imp"].start
KeyError: 'imp'

Apr 10 13:17:56.667 - [INFO] begin to exit web control
Apr 10 13:17:56.679 - [ERROR] uncaught Exception, type=<type 'exceptions.AttributeError'> value='NoneType' object has no attribute 'shutdown' traceback:<traceback object at 0x0353BD00>
Apr 10 13:18:11.861 - [DEBUG] no_mess_system
Apr 10 13:18:11.982 - [INFO] use build-in openssl lib
Apr 10 13:18:11.984 - [INFO] start XX-Net 3.11.7
Apr 10 13:18:11.985 - [DEBUG] start confirm_xxnet_exit
Apr 10 13:18:12.999 - [DEBUG] good, xxnet:8085 clear!
Apr 10 13:18:13.000 - [DEBUG] finished confirm_xxnet_exit
Apr 10 13:18:13.061 - [ERROR] start module gae_proxy fail:Extra data: line 19 column 1 - line 34 column 2 (char 339 - 614)
Apr 10 13:18:13.067 - [ERROR] Except stack:Traceback (most recent call last):
  File "D:\XX-Net-3.8.7\code\3.11.7\launcher\module_init.py", line 40, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "D:\XX-Net-3.8.7\code\3.11.7\gae_proxy\local\__init__.py", line 2, in <module>
    import apis
  File "D:\XX-Net-3.8.7\code\3.11.7\gae_proxy\local\apis.py", line 2, in <module>
    from front import front, direct_front
  File "D:\XX-Net-3.8.7\code\3.11.7\gae_proxy\local\front.py", line 7, in <module>
    import check_local_network
  File "D:\XX-Net-3.8.7\code\3.11.7\gae_proxy\local\check_local_network.py", line 28, in <module>
    from config import config
  File "D:\XX-Net-3.8.7\code\3.11.7\gae_proxy\local\config.py", line 213, in <module>
    config = Config(config_path)
  File "D:\XX-Net-3.8.7\code\3.11.7\gae_proxy\local\config.py", line 170, in __init__
    self.load()
  File "D:\XX-Net-3.8.7\code\3.11.7\gae_proxy\local\config.py", line 173, in load
    super(Config, self).load()
  File "D:\XX-Net-3.8.7\code\3.11.7\python27\1.0\lib\noarch\front_base\config.py", line 87, in load
    super(ConfigBase, self).load()
  File "D:\XX-Net-3.8.7\code\3.11.7\python27\1.0\lib\noarch\xconfig.py", line 22, in load
    self.file_config = json.loads(content)
  File "D:\XX-Net-3.8.7\code\3.11.7\python27\1.0\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "D:\XX-Net-3.8.7\code\3.11.7\python27\1.0\lib\json\decoder.py", line 367, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 19 column 1 - line 34 column 2 (char 339 - 614)

Apr 10 13:18:13.069 - [ERROR] launcher except:ValueError('Extra data: line 19 column 1 - line 34 column 2 (char 339 - 614)',)
Apr 10 13:18:13.071 - [ERROR] Except stack:Traceback (most recent call last):
  File "D:\XX-Net-3.8.7\code\3.11.7\launcher\start.py", line 247, in <module>
    main()
  File "D:\XX-Net-3.8.7\code\3.11.7\launcher\start.py", line 226, in main
    module_init.start_all_auto()
  File "D:\XX-Net-3.8.7\code\3.11.7\launcher\module_init.py", line 113, in start_all_auto
    start(module)
  File "D:\XX-Net-3.8.7\code\3.11.7\launcher\module_init.py", line 40, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "D:\XX-Net-3.8.7\code\3.11.7\gae_proxy\local\__init__.py", line 2, in <module>
    import apis
  File "D:\XX-Net-3.8.7\code\3.11.7\gae_proxy\local\apis.py", line 2, in <module>
    from front import front, direct_front
  File "D:\XX-Net-3.8.7\code\3.11.7\gae_proxy\local\front.py", line 7, in <module>
    import check_local_network
  File "D:\XX-Net-3.8.7\code\3.11.7\gae_proxy\local\check_local_network.py", line 28, in <module>
    from config import config
  File "D:\XX-Net-3.8.7\code\3.11.7\gae_proxy\local\config.py", line 213, in <module>
    config = Config(config_path)
  File "D:\XX-Net-3.8.7\code\3.11.7\gae_proxy\local\config.py", line 170, in __init__
    self.load()
  File "D:\XX-Net-3.8.7\code\3.11.7\gae_proxy\local\config.py", line 173, in load
    super(Config, self).load()
  File "D:\XX-Net-3.8.7\code\3.11.7\python27\1.0\lib\noarch\front_base\config.py", line 87, in load
    super(ConfigBase, self).load()
  File "D:\XX-Net-3.8.7\code\3.11.7\python27\1.0\lib\noarch\xconfig.py", line 22, in load
    self.file_config = json.loads(content)
  File "D:\XX-Net-3.8.7\code\3.11.7\python27\1.0\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "D:\XX-Net-3.8.7\code\3.11.7\python27\1.0\lib\json\decoder.py", line 367, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 19 column 1 - line 34 column 2 (char 339 - 614)

Apr 10 13:19:17.547 - [DEBUG] no_mess_system
Apr 10 13:19:17.687 - [INFO] use build-in openssl lib
Apr 10 13:19:17.688 - [INFO] start XX-Net 3.10.4
Apr 10 13:19:17.689 - [DEBUG] start confirm_xxnet_exit
Apr 10 13:19:18.705 - [DEBUG] good, xxnet:8085 clear!
Apr 10 13:19:18.706 - [DEBUG] finished confirm_xxnet_exit
Apr 10 13:19:19.744 - [INFO] module gae_proxy started
Apr 10 13:19:19.745 - [INFO] start gae_proxy time cost:1021 ms
Apr 10 13:19:19.746 - [INFO] begin to start web control
Apr 10 13:19:19.747 - [INFO] server 127.0.0.1:8085 started.
Apr 10 13:19:19.748 - [INFO] launcher web control started.
Apr 10 13:19:20.261 - [DEBUG] launcher web_control 127.0.0.1:51783 GET /config?cmd=get_version 
Apr 10 13:19:20.263 - [DEBUG] launcher web_control 127.0.0.1:51792 GET /config?cmd=get_config 
Apr 10 13:19:20.315 - [DEBUG] launcher web_control 127.0.0.1:51793 GET /update?cmd=get_progress 
Apr 10 13:19:20.315 - [DEBUG] launcher web_control 127.0.0.1:51783 GET /config?cmd=get_config 
Apr 10 13:19:20.330 - [DEBUG] launcher web_control 127.0.0.1:51783 GET /config?cmd=get_config 
Apr 10 13:19:20.345 - [DEBUG] launcher web_control 127.0.0.1:51783 GET /config?cmd=set_config&postUpdateStat=noChange 
Apr 10 13:19:20.846 - [INFO] get uuid:08e63439-e7e0-4e3c-921c-812e9614b555
Apr 10 13:19:21.028 - [DEBUG] launcher web_control 127.0.0.1:51783 GET /update?cmd=get_progress 
Apr 10 13:19:21.319 - [DEBUG] launcher web_control 127.0.0.1:51783 GET /update?cmd=get_info 
Apr 10 13:19:27.171 - [INFO] download https://raw.githubusercontent.com/XX-net/XX-Net/master/code/default/update_version.txt to D:\XX-Net-3.8.7\data\downloads\version.txt, retry:0
Apr 10 13:19:27.743 - [INFO] checked new stable version 3.11.7
Apr 10 13:21:35.131 - [DEBUG] launcher web_control 127.0.0.1:51783 GET /config?cmd=get_version 
Apr 10 13:21:35.135 - [DEBUG] launcher web_control 127.0.0.1:51793 GET /config?cmd=get_config 
Apr 10 13:21:35.137 - [DEBUG] launcher web_control 127.0.0.1:51783 GET /config?cmd=get_version 
Apr 10 13:21:35.158 - [DEBUG] launcher web_control 127.0.0.1:51793 GET /update?cmd=get_progress 
Apr 10 13:21:35.170 - [DEBUG] launcher web_control 127.0.0.1:51793 GET /config?cmd=get_config 
Apr 10 13:21:36.174 - [DEBUG] launcher web_control 127.0.0.1:51793 GET /update?cmd=get_info 
Apr 10 13:21:36.628 - [DEBUG] launcher web_control 127.0.0.1:51793 GET /config?cmd=get_version 
Apr 10 13:21:36.632 - [DEBUG] launcher web_control 127.0.0.1:51783 GET /config?cmd=get_config 
Apr 10 13:21:36.654 - [DEBUG] launcher web_control 127.0.0.1:51783 GET /update?cmd=get_progress 
Apr 10 13:21:36.677 - [DEBUG] launcher web_control 127.0.0.1:51783 GET /config?cmd=get_config 
Apr 10 13:21:36.685 - [DEBUG] launcher web_control 127.0.0.1:51783 GET /config?cmd=get_config 
Apr 10 13:21:37.667 - [DEBUG] launcher web_control 127.0.0.1:51783 GET /update?cmd=get_info 
Apr 10 13:21:39.809 - [DEBUG] launcher web_control 127.0.0.1:51783 GET /config?cmd=get_version 
Apr 10 13:21:39.811 - [DEBUG] launcher web_control 127.0.0.1:51793 GET /config?cmd=get_config 
Apr 10 13:21:39.836 - [DEBUG] launcher web_control 127.0.0.1:51793 GET /config?cmd=get_version 
Apr 10 13:21:39.838 - [DEBUG] launcher web_control 127.0.0.1:51783 GET /config?cmd=get_config 
Apr 10 13:21:39.844 - [DEBUG] launcher web_control 127.0.0.1:51793 GET /update?cmd=get_progress 
Apr 10 13:21:39.855 - [DEBUG] launcher web_control 127.0.0.1:51783 GET /config?cmd=get_config 
Apr 10 13:21:40.860 - [DEBUG] launcher web_control 127.0.0.1:51783 GET /update?cmd=get_info 
Apr 10 13:21:50.027 - [DEBUG] launcher web_control 127.0.0.1:51783 GET /update?cmd=get_info 
Apr 10 13:22:14.934 - [DEBUG] start to terminate gae_proxy module
Apr 10 13:22:14.937 - [DEBUG] module gae_proxy stopping
Apr 10 13:22:16.844 - [INFO] module gae_proxy stopped
Apr 10 13:22:34.744 - [DEBUG] no_mess_system
Apr 10 13:22:34.879 - [INFO] use build-in openssl lib
Apr 10 13:22:34.881 - [INFO] start XX-Net 3.11.9
Apr 10 13:22:34.881 - [DEBUG] start confirm_xxnet_exit
Apr 10 13:22:35.887 - [DEBUG] good, xxnet:8085 clear!
Apr 10 13:22:35.888 - [DEBUG] finished confirm_xxnet_exit
Apr 10 13:22:35.933 - [ERROR] start module gae_proxy fail:Extra data: line 19 column 1 - line 34 column 2 (char 339 - 614)
Apr 10 13:22:35.938 - [ERROR] Except stack:Traceback (most recent call last):
  File "D:\XX-Net-3.8.7\code\3.11.9\launcher\module_init.py", line 40, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "D:\XX-Net-3.8.7\code\3.11.9\gae_proxy\local\__init__.py", line 2, in <module>
    import apis
  File "D:\XX-Net-3.8.7\code\3.11.9\gae_proxy\local\apis.py", line 2, in <module>
    from front import front, direct_front
  File "D:\XX-Net-3.8.7\code\3.11.9\gae_proxy\local\front.py", line 7, in <module>
    import check_local_network
  File "D:\XX-Net-3.8.7\code\3.11.9\gae_proxy\local\check_local_network.py", line 28, in <module>
    from config import config
  File "D:\XX-Net-3.8.7\code\3.11.9\gae_proxy\local\config.py", line 221, in <module>
    config = Config(config_path)
  File "D:\XX-Net-3.8.7\code\3.11.9\gae_proxy\local\config.py", line 169, in __init__
    self.load()
  File "D:\XX-Net-3.8.7\code\3.11.9\gae_proxy\local\config.py", line 172, in load
    super(Config, self).load()
  File "D:\XX-Net-3.8.7\code\3.11.9\python27\1.0\lib\noarch\front_base\config.py", line 87, in load
    super(ConfigBase, self).load()
  File "D:\XX-Net-3.8.7\code\3.11.9\python27\1.0\lib\noarch\xconfig.py", line 22, in load
    self.file_config = json.loads(content)
  File "D:\XX-Net-3.8.7\code\3.11.9\python27\1.0\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "D:\XX-Net-3.8.7\code\3.11.9\python27\1.0\lib\json\decoder.py", line 367, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 19 column 1 - line 34 column 2 (char 339 - 614)

Apr 10 13:22:35.942 - [ERROR] launcher except:ValueError('Extra data: line 19 column 1 - line 34 column 2 (char 339 - 614)',)
Apr 10 13:22:35.945 - [ERROR] Except stack:Traceback (most recent call last):
  File "D:\XX-Net-3.8.7\code\3.11.9\launcher\start.py", line 247, in <module>
    main()
  File "D:\XX-Net-3.8.7\code\3.11.9\launcher\start.py", line 226, in main
    module_init.start_all_auto()
  File "D:\XX-Net-3.8.7\code\3.11.9\launcher\module_init.py", line 113, in start_all_auto
    start(module)
  File "D:\XX-Net-3.8.7\code\3.11.9\launcher\module_init.py", line 40, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "D:\XX-Net-3.8.7\code\3.11.9\gae_proxy\local\__init__.py", line 2, in <module>
    import apis
  File "D:\XX-Net-3.8.7\code\3.11.9\gae_proxy\local\apis.py", line 2, in <module>
    from front import front, direct_front
  File "D:\XX-Net-3.8.7\code\3.11.9\gae_proxy\local\front.py", line 7, in <module>
    import check_local_network
  File "D:\XX-Net-3.8.7\code\3.11.9\gae_proxy\local\check_local_network.py", line 28, in <module>
    from config import config
  File "D:\XX-Net-3.8.7\code\3.11.9\gae_proxy\local\config.py", line 221, in <module>
    config = Config(config_path)
  File "D:\XX-Net-3.8.7\code\3.11.9\gae_proxy\local\config.py", line 169, in __init__
    self.load()
  File "D:\XX-Net-3.8.7\code\3.11.9\gae_proxy\local\config.py", line 172, in load
    super(Config, self).load()
  File "D:\XX-Net-3.8.7\code\3.11.9\python27\1.0\lib\noarch\front_base\config.py", line 87, in load
    super(ConfigBase, self).load()
  File "D:\XX-Net-3.8.7\code\3.11.9\python27\1.0\lib\noarch\xconfig.py", line 22, in load
    self.file_config = json.loads(content)
  File "D:\XX-Net-3.8.7\code\3.11.9\python27\1.0\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "D:\XX-Net-3.8.7\code\3.11.9\python27\1.0\lib\json\decoder.py", line 367, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 19 column 1 - line 34 column 2 (char 339 - 614)`

**Comment by abigbone** [comment]
> Dec 25 10:59:21.502 type:<type 'exceptions.IOError'> value=[Errno 0] Error traceback:<traceback object at 0x04FE7F80>Mar 02 20:03:24.618 type:<type 'exceptions.IOError'> value=[Errno 9] Bad file descriptor traceback:<traceback object at 0x58C66328>Mar 03 15:40:04.240 type:<type 'exceptions.IOError'> value=[Errno 9] Bad file descriptor traceback:<traceback object at 0x05295800>Apr 10 09:53:52.054 type:<type 'exceptions.EOFError'> value=EOF when reading a line traceback:<traceback object at 0x03CC0E40>Apr 10 09:53:52.073 type:<type 'exceptions.AttributeError'> value='NoneType' object has no attribute 'shutdown' traceback:<traceback object at 0x03C93E90>Apr 10 09:55:56.924 type:<type 'exceptions.AttributeError'> value='NoneType' object has no attribute 'shutdown' traceback:<traceback object at 0x03708AF8>Apr 10 09:56:21.348 type:<type 'exceptions.AttributeError'> value='NoneType' object has no attribute 'shutdown' traceback:<traceback object at 0x02D78AF8>Apr 10 09:56:32.669 type:<type 'exceptions.EOFError'> value=EOF when reading a line traceback:<traceback object at 0x03FF3E40>Apr 10 09:56:32.670 type:<type 'exceptions.AttributeError'> value='NoneType' object has no attribute 'shutdown' traceback:<traceback object at 0x03FB4E90>Apr 10 09:58:14.972 type:<type 'exceptions.AttributeError'> value='NoneType' object has no attribute 'shutdown' traceback:<traceback object at 0x030F8AF8>Apr 10 10:52:47.349 type:<type 'exceptions.AttributeError'> value='NoneType' object has no attribute 'shutdown' traceback:<traceback object at 0x031B8AF8>Apr 10 10:55:49.411 type:<type 'exceptions.AttributeError'> value='NoneType' object has no attribute 'shutdown' traceback:<traceback object at 0x02D08AF8>Apr 10 10:55:55.627 type:<type 'exceptions.EOFError'> value=EOF when reading a line traceback:<traceback object at 0x0394FE68>Apr 10 10:55:55.630 type:<type 'exceptions.AttributeError'> value='NoneType' object has no attribute 'shutdown' traceback:<traceback object at 0x03924EB8>Apr 10 11:08:37.519 type:<type 'exceptions.AttributeError'> value='NoneType' object has no attribute 'shutdown' traceback:<traceback object at 0x02DD8AF8>Apr 10 11:08:46.574 type:<type 'exceptions.EOFError'> value=EOF when reading a line traceback:<traceback object at 0x03921E68>Apr 10 11:08:46.575 type:<type 'exceptions.AttributeError'> value='NoneType' object has no attribute 'shutdown' traceback:<traceback object at 0x038F4EB8>Apr 10 11:10:43.117 type:<type 'exceptions.AttributeError'> value='NoneType' object has no attribute 'shutdown' traceback:<traceback object at 0x02F88AF8>Apr 10 11:10:49.640 type:<type 'exceptions.EOFError'> value=EOF when reading a line traceback:<traceback object at 0x036D9A80>Apr 10 11:10:49.654 type:<type 'exceptions.AttributeError'> value='NoneType' object has no attribute 'shutdown' traceback:<traceback object at 0x03686A80>Apr 10 11:11:24.605 type:<type 'exceptions.AttributeError'> value='NoneType' object has no attribute 'shutdown' traceback:<traceback object at 0x037F8918>Apr 10 12:43:51.322 type:<type 'exceptions.EOFError'> value=EOF when reading a line traceback:<traceback object at 0x03FF9198>Apr 10 12:43:51.324 type:<type 'exceptions.AttributeError'> value='NoneType' object has no attribute 'shutdown' traceback:<traceback object at 0x03FE7CB0>Apr 10 13:02:22.977 type:<type 'exceptions.EOFError'> value=EOF when reading a line traceback:<traceback object at 0x03A7AE40>Apr 10 13:02:22.979 type:<type 'exceptions.AttributeError'> value='NoneType' object has no attribute 'shutdown' traceback:<traceback object at 0x03A40E90>Apr 10 13:04:06.622 type:<type 'exceptions.AttributeError'> value='NoneType' object has no attribute 'shutdown' traceback:<traceback object at 0x02EBCAD0>Apr 10 13:09:10.032 type:<type 'exceptions.AttributeError'> value='NoneType' object has no attribute 'shutdown' traceback:<traceback object at 0x02F4FAF8>Apr 10 13:17:42.864 type:<type 'exceptions.AttributeError'> value='NoneType' object has no attribute 'shutdown' traceback:<traceback object at 0x03638AF8>Apr 10 13:17:56.679 type:<type 'exceptions.AttributeError'> value='NoneType' object has no attribute 'shutdown' traceback:<traceback object at 0x0353BD00>
这个是error日志

**Comment by SeaHOH** [comment]
似乎是设置文件格式损坏，你是不是改过某个 json 文件？

**Comment by AnyWAT** [comment]
一般是猛加大IP上限😝 一统好、大、全作怪 https://github.com/XX-net/XX-Net/issues/10407#issuecomment-379979519

**Comment by SeaHOH** [comment]
@AnyWAT 你怎么又来了，这是启动不了好不好？

**Comment by AnyWAT** [comment]
为猛加大IP上限，没修改 json 文件，启动不了😂

**Comment by SeaHOH** [comment]
还不是你宣传的，这个根本不用改好不好。。。

**Comment by AnyWAT** [comment]
😜为了切换XX版本而统一到合适值：3.10.4默认6000太大，默认500的大家嫌小
![default](https://user-images.githubusercontent.com/37962734/38538557-f82a2052-3cc6-11e8-9059-99dd6412a908.png)
不受 config.json 控制的 3.10.4正常就是明证

**Comment by abigbone** [comment]
@AnyWAT   我就喜欢这样的石锤，  是改过config.json

**Comment by AnyWAT** [comment]
楼主贴 config.json （马赛克AppID）

**Comment by abigbone** [comment]
来了~~
![image](https://user-images.githubusercontent.com/4329020/38538764-d1749bd0-3cc7-11e8-840d-b1a87bcde180.png)

**Comment by AnyWAT** [comment]
重贴，不能看不出行首、行尾的英文标点😂
我就喜欢这样的石锤：神马意思？

**Comment by abigbone** [comment]
1. 
![image](https://user-images.githubusercontent.com/4329020/38538866-370b9642-3cc8-11e8-8386-2317aea000cf.png)
2.  输入法错误，夸大牛，要求锤得锤找出无可反驳的事实。

**Comment by AnyWAT** [comment]
1、日还是曰是神马多余？
2、整个文件只能是一组大括号
3、全部必须英文标点
4、17行末。。。因现在2大括号。。。
5、21行与24及其它位置冒号后不同，存疑
![default](https://user-images.githubusercontent.com/37962734/38539161-85be78ee-3cc9-11e8-9770-5fb261d9f4a7.png)

**Comment by AnyWAT** [comment]
修改后还不行，继续贴 config.json

**Comment by abigbone** [comment]
1. 我是古典互联网用户，用的是editplus  ，那个是折叠符号不是日也不是曰

2. 只能有一组大括号啊，我以为可以随意呢，当成类似nginx配置了，我改。

其他的标点符号没有问题，我去试试

**Comment by abigbone** [comment]
大表哥你赢了，成功启动~~
![image](https://user-images.githubusercontent.com/4329020/38540241-eed54818-3ccd-11e8-95ab-dea1e7b8689b.png)

**Comment by AnyWAT** [comment]
😜只用Windows，不知其它如nginx，表示。。。
