### ISSUE TITLE
状态页显示空白, 很可能GAEProxy启动失败, 请按指引

### ISSUE THREAD

**Issue by fankanfan** [XX-net/XX-Net#1043]
Exception happened during processing of request from ('127.0.0.1', 53201)
Traceback (most recent call last):
  File "D:\xxnet\python27\1.0\lib\SocketServer.py", line 593, in process_request
_thread
    self.finish_request(request, client_address)
  File "D:\xxnet\launcher\web_control.py", line 48, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "D:\xxnet\python27\1.0\lib\SocketServer.py", line 649, in __init__
    self.handle()
  File "D:\xxnet\python27\1.0\lib\BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "D:\xxnet\python27\1.0\lib\BaseHTTPServer.py", line 328, in handle_one_re
quest
    method()
  File "D:\xxnet\launcher\web_control.py", line 143, in do_GET
    controler = module_init.proc_handler[module]["imp"].local.web_control.Contro
lHandler(self.client_address, self.headers, self.command, path, self.rfile, self
.wfile)
KeyError: 'imp'

**Comment by fankanfan** [comment]
又换了个错误
D:\xxnet>"D:\xxnet\python27/1.0/python.exe" "D:\xxnet\launcher/start.py"
Sep 16 11:28:25 - [DEBUG] start confirm_xxnet_exit
Sep 16 11:28:26 - [INFO] load manual.ini success
Sep 16 11:28:26 - [ERROR] start module gae_proxy fail:No option 'connect_interva
l' in section: 'connect_manager'
Traceback (most recent call last):
  File "D:\xxnet\launcher\module_init.py", line 36, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['loca
l', 'start'], -1)
  File "D:\xxnet\gae_proxy\start.py", line 13, in <module>
    import local.proxy as client
  File "D:\xxnet\gae_proxy\local\proxy.py", line 77, in <module>
    from cert_util import CertUtil
  File "D:\xxnet\gae_proxy\local\cert_util.py", line 44, in <module>
    from config import config
  File "D:\xxnet\gae_proxy\local\config.py", line 151, in <module>
    config.load()
  File "D:\xxnet\gae_proxy\local\config.py", line 125, in load
    self.connect_interval = config.CONFIG.getint("connect_manager", "connect_int
erval")
  File "D:\xxnet\python27\1.0\lib\ConfigParser.py", line 359, in getint
    return self._get(section, int, option)
  File "D:\xxnet\python27\1.0\lib\ConfigParser.py", line 356, in _get
    return conv(self.get(section, option))
  File "D:\xxnet\python27\1.0\lib\ConfigParser.py", line 618, in get
    raise NoOptionError(option, section)
NoOptionError: No option 'connect_interval' in section: 'connect_manager'

Sep 16 11:28:26 - [INFO] start gae_proxy time cost 52
Sep 16 11:28:27 - [INFO] get uuid:4777bb24-3b72-4e06-b0da-6a056d15430e
Sep 16 11:28:28 - [WARNING] check_update fail:URLError(error(10061, ''),)
Sep 16 11:28:28 - [INFO] download https://raw.githubusercontent.com/XX-net/XX-Ne
t/master/README.md to D:\xxnet\data\downloads\README.md
Sep 16 11:28:29 - [ERROR] download https://raw.githubusercontent.com/XX-net/XX-N
et/master/README.md to D:\xxnet\data\downloads\README.md fail:URLError(error(100
61, ''),)
Traceback (most recent call last):
  File "D:\xxnet\launcher\update_from_github.py", line 64, in download_file
    req = opener.open(url)
  File "D:\xxnet\python27\1.0\lib\urllib2.py", line 404, in open
    response = self._open(req, data)
  File "D:\xxnet\python27\1.0\lib\urllib2.py", line 422, in _open
    '_open', req)
  File "D:\xxnet\python27\1.0\lib\urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "D:\xxnet\python27\1.0\lib\urllib2.py", line 1222, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "D:\xxnet\python27\1.0\lib\urllib2.py", line 1184, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 10061] >

Sep 16 11:28:29 - [ERROR] check_update fail:IOError('get README https://raw.gith
ubusercontent.com/XX-net/XX-Net/master/README.md fail:',)
Traceback (most recent call last):
  File "D:\xxnet\launcher\update.py", line 241, in check_update
    versions = update_from_github.get_github_versions()
  File "D:\xxnet\launcher\update_from_github.py", line 106, in get_github_versio
ns
    raise IOError("get README %s fail:" % readme_url)
IOError: get README https://raw.githubusercontent.com/XX-net/XX-Net/master/READM
E.md fail:

**Comment by xxnet** [comment]
请重新下载一个版本解压试试

2015-09-16 11:31 GMT+08:00 fankanfan <notifications@github.com>:

**Comment by ashtse** [comment]
今天用2.0.5打开显示状态页显示空白, 很可能GAEProxy启动失败, 请按指引查找问题原因.

**Comment by fankanfan** [comment]
你起了几次，多起几次

**Comment by ashtse** [comment]
连续试都不行，重启后也不行~~~
Sep 16 15:14:24 - [DEBUG] start confirm_xxnet_exit
Sep 16 15:14:26 - [ERROR] start module gae_proxy fail:cannot import name __versi
on__
Traceback (most recent call last):
  File "D:\Software\XX-Net-2.3.0\launcher\module_init.py", line 36, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['loca
l', 'start'], -1)
  File "D:\Software\XX-Net-2.3.0\gae_proxy\start.py", line 13, in <module>
    import local.proxy as client
  File "D:\Software\XX-Net-2.3.0\gae_proxy\local\proxy.py", line 77, in <module>

    from cert_util import CertUtil
  File "D:\Software\XX-Net-2.3.0\gae_proxy\local\cert_util.py", line 41, in <mod
ule>
    from pyasn1.codec.der.decoder import decode
  File "D:\Software\XX-Net-2.3.0\python27\1.0\lib\noarch\pyasn1\codec\der\decode
r.py", line 3, in <module>
    from pyasn1.codec.cer import decoder
  File "D:\Software\XX-Net-2.3.0\python27\1.0\lib\noarch\pyasn1\codec\cer\decode
r.py", line 3, in <module>
    from pyasn1.codec.ber import decoder
  File "D:\Software\XX-Net-2.3.0\python27\1.0\lib\noarch\pyasn1\codec\ber\decode
r.py", line 5, in <module>
    from pyasn1 import debug, error
  File "D:\Software\XX-Net-2.3.0\python27\1.0\lib\noarch\pyasn1\debug.py", line
4, in <module>
    from pyasn1 import __version__
ImportError: cannot import name __version__

Sep 16 15:14:26 - [INFO] start gae_proxy time cost 984
Sep 16 15:14:28 - [INFO] get uuid:e192e0c1-9f0c-4b72-8e71-d0ba96839e17
Sep 16 15:14:29 - [WARNING] check_update fail:URLError(error(10061, ''),)
Sep 16 15:14:29 - [INFO] download https://raw.githubusercontent.com/XX-net/XX-Ne
t/master/README.md to D:\Software\XX-Net-2.3.0\data\downloads\README.md

**Comment by fankanfan** [comment]
2.3.0的也报错吗

**Comment by ashtse** [comment]
对啊 ，gae_proxy fail:cannot import name version

**Comment by fankanfan** [comment]
在解压一个，重试，或者换个版本再试试，感觉的你的问题确实不一样。实在不行你自己在提问，官方会回你的

**Comment by ashtse** [comment]
好的
