### ISSUE TITLE
Help,3Q   状态页显示空白, 很可能GAEProxy启动失败

### ISSUE THREAD

**Issue by ashtse** [XX-net/XX-Net#1050]
具体信息，昨天2.0.5打开出现的问题，后重新下载2.3.0还是同样的问题~~~电脑重启后也不行，今天试还是~~~~帮忙看看，每次都是start module gae_proxy fail:cannot import name __version__
谢谢！

Sep 17 07:35:57 - [DEBUG] start confirm_xxnet_exit
Sep 17 07:36:00 - [ERROR] start module gae_proxy fail:cannot import name __versi
on__
Traceback (most recent call last):
  File "D:\Software\XX-Net-2.3.0\launcher\module_init.py", line 36, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['loca
l', 'start'], -1)
  File "D:\Software\XX-Net-2.3.0\gae_proxy\start.py", line 13, in <module>
    import local.proxy as client
  File "D:\Software\XX-Net-2.3.0\gae_proxy\local\proxy.py", line 77, in <module>

    from cert_util import CertUtil
  File "D:\Software\XX-Net-2.3.0\gae_proxy\local\cert_util.py", line 41, in <mod
ule>
    from pyasn1.codec.der.decoder import decode
  File "D:\Software\XX-Net-2.3.0\python27\1.0\lib\noarch\pyasn1\codec\der\decode
r.py", line 3, in <module>
    from pyasn1.codec.cer import decoder
  File "D:\Software\XX-Net-2.3.0\python27\1.0\lib\noarch\pyasn1\codec\cer\decode
r.py", line 3, in <module>
    from pyasn1.codec.ber import decoder
  File "D:\Software\XX-Net-2.3.0\python27\1.0\lib\noarch\pyasn1\codec\ber\decode
r.py", line 5, in <module>
    from pyasn1 import debug, error
  File "D:\Software\XX-Net-2.3.0\python27\1.0\lib\noarch\pyasn1\debug.py", line
4, in <module>
    from pyasn1 import __version__
ImportError: cannot import name __version__

Sep 17 07:36:00 - [INFO] start gae_proxy time cost 2187
Sep 17 07:36:02 - [INFO] get uuid:e192e0c1-9f0c-4b72-8e71-d0ba96839e17
Sep 17 07:36:03 - [WARNING] check_update fail:URLError(error(10061, ''),)
Sep 17 07:36:03 - [INFO] download https://raw.githubusercontent.com/XX-net/XX-Ne
t/master/README.md to D:\Software\XX-Net-2.3.0\data\downloads\README.md

**Comment by condywl** [comment]
是不是你的配置出错了？

**Comment by xxnet** [comment]
重新下载一个安装包试试

2015-09-17 9:48 GMT+08:00 condywl <notifications@github.com>:
