### ISSUE TITLE
mac Xx-Net 开机无法自启动，点击start之后会有命令行显示成功，没有图标，也无法打开配置页

### ISSUE THREAD

**Issue by Howill-Li** [XX-net/XX-Net#10540]
* 是否试过最新的测试版本？
  很多问题在最新测试版中已解决。
  

* 是否看过webUI `系统` - `状态` - `公告`？
  无法打开配置页
  

* 是否看过Issues区最近的讨论？
  请在 (https://github.com/XX-net/XX-Net/issues) 搜索有无类似的问题。
  

* 是否查看过Wiki（https://github.com/XX-net/XX-Net/wiki）
  请阅读[故障速查手册](https://github.com/XX-net/XX-Net/wiki/故障速查手册)，大部分问题都能在这里找到答案。

* 简单描述遇到的问题：
macac Xx-Net 开机无法自启动，点击start之后会有命令行显示成功，没有图标，也无法打开配置页

* 做过哪些尝试：

尝试不同的版本，关机重启

* 请贴出对应模块的状态页
无法进入配置页

* 请贴出相关的日志

Last login: Tue Apr 24 14:28:34 on ttys000
You have mail.
/Users/huawei/Downloads/XX-Net-master/start ; exit;
bogon:~ huawei$ /Users/huawei/Downloads/XX-Net-master/start ; exit;
XX-Net version:3.11.9
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

## 常见问题：  
* 扫描不到GAE的ip  
   请尝试启用IPv6，参考  
   https://github.com/XX-net/XX-Net/wiki/%E5%A6%82%E4%BD%95%E5%BC%80%E5%90%AFIPv6    
   
   或者试试X-Tunnel 模块  
   https://github.com/XX-net/XX-Net/wiki/x-tunnel%E4%BD%BF%E7%94%A8%E6%95%99%E7%A8%8B  
   
* X-tunnel 无法连接  
  如果能够登录，请确认代理端口为1080.
  如果速度不稳定或无法登录，请贴出X-Tunnel 的Status页面。

**Comment by windend** [comment]
安装Python2  pyobjc-framwork的组件，然后重启就行了

**Comment by iamqk** [comment]
暂时 可以把start 添加到 设置 用户与群组 登录项 来完成开机启动

**Comment by Howill-Li** [comment]
@iamqk 无效

**Comment by Howill-Li** [comment]
@windend 试了，无效

**Comment by SeaHOH** [comment]
@Howill-Li 请贴出 data 文件夹内的日志

**Comment by SeaHOH** [comment]
你这个启动时间不对，启动并没有完成。
尝试以下方案：
1. 移除 data 文件夹
1. 或全新下载 XX-Net

**Comment by Howill-Li** [comment]
@SeaHOH 

1.启动成功，自动跳出了配置页面，可以正常使用，但是任务栏没有图标

2.之前也试过重新下载Xx_Net，但是也存在此无法启动的问题

**Comment by SeaHOH** [comment]
1. 这个是能正常使用代理？那么在配置页面中选择显示托盘图标。
完成后，config.yaml 中应该有 `show_systray: 1`字样。

2. 重新下载后是直接解压就运行吗？没有放入旧 data 吧。

**Comment by Howill-Li** [comment]
@SeaHOH 
问题又出现了，刚才想在配置页面设置显示托盘图标，但是点击页面左侧的菜单无法切换，发现配置页面无响应

1. 使用Start重启服务，无效，
2. 删除data之后，点击Start重启服务，无效
3. 重新下载Xx_Net，点击Start启动服务，无效

重新下载之后的log

May 03 15:22:51.734 - [INFO] use build-in openssl lib
May 03 15:22:51.735 - [INFO] start XX-Net 3.11.10
May 03 15:22:51.735 - [DEBUG] start confirm_xxnet_exit
May 03 15:22:51.737 - [DEBUG] good, xxnet:8085 clear!
May 03 15:22:51.737 - [DEBUG] finished confirm_xxnet_exit
May 03 15:25:32.800 - [INFO] use build-in openssl lib
May 03 15:25:32.801 - [INFO] start XX-Net 3.11.10
May 03 15:25:32.801 - [DEBUG] start confirm_xxnet_exit
May 03 15:25:32.803 - [DEBUG] good, xxnet:8085 clear!
May 03 15:25:32.803 - [DEBUG] finished confirm_xxnet_exit

**Comment by SeaHOH** [comment]
查看 8085 端口是否被其它程序占用

**Comment by Howill-Li** [comment]
@SeaHOH 

8085没有被其他程序占用

Last login: Thu May  3 15:49:28 on ttys001
You have mail.
localhost:~ huawei$ lsof -i:8085
localhost:~ huawei$

**Comment by SeaHOH** [comment]
你这个好诡异，Mac 搞不懂。。。 @xxnet

**Comment by Howill-Li** [comment]
@SeaHOH 心累，之前用的好好地，后来因为不是私密链接的，买了X-Tunnel之后，就出一直出这个bug

**Comment by SeaHOH** [comment]
既然提到了，data/launcher/config.yaml 手动设置成关闭 X-Tunnel 试试。
```
modules:
  gae_proxy: {auto_start: 1, show_detail: 1}
  launcher: {allow_remote_connect: 0, control_port: 8085, last_run_version: 3.11.9,
    popup_webui: 1, proxy: smart_router, show_systray: 1}
  smart_router: {auto_start: 1}
  x_tunnel: {auto_start: 0}
```

**Comment by windend** [comment]
@Howill-Li 我的mac也出过这个问题，代理可以正常使用，但是导航栏不显示，后来看了下源码，里面需要安装pyobjc,mac的导航栏依赖这个objc的包。我安装后重启就解决了。你这个具体的代理不能用就很奇怪了
![image](https://user-images.githubusercontent.com/5136318/39573625-98504600-4f06-11e8-86c4-e977b7ea284c.png)

**Comment by Howill-Li** [comment]
@windend 这个包我装了，重启 之后，还是启动不起来

**Comment by SeaHOH** [comment]
手动关闭 X-Tunnel 后能启动吗？

**Comment by Howill-Li** [comment]
@SeaHOH 试过了，不行

**Comment by Howill-Li** [comment]
使用python start.py启动，报错

May 08 10:58:13.574 [launcher][ERROR] start module gae_proxy fail:unknown locale: UTF-8
May 08 10:58:13.577 [launcher][ERROR] Except stack:Traceback (most recent call last):
  File "/Users/huawei/Downloads/XX-Net-master/code/default/launcher/module_init.py", line 40, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "/Users/huawei/Downloads/XX-Net-master/code/default/gae_proxy/start.py", line 13, in <module>
    import local.proxy as client
  File "/Users/huawei/Downloads/XX-Net-master/code/default/gae_proxy/local/proxy.py", line 86, in <module>
    import proxy_handler
  File "/Users/huawei/Downloads/XX-Net-master/code/default/gae_proxy/local/proxy_handler.py", line 53, in <module>
    import web_control
  File "/Users/huawei/Downloads/XX-Net-master/code/default/gae_proxy/local/web_control.py", line 32, in <module>
    import ipv6_tunnel
  File "/Users/huawei/Downloads/XX-Net-master/code/default/gae_proxy/local/ipv6_tunnel/__init__.py", line 14, in <module>
    from .darwin import state, enable, disable, set_best_server
  File "/Users/huawei/Downloads/XX-Net-master/code/default/gae_proxy/local/ipv6_tunnel/darwin.py", line 6, in <module>
    from .common import *
  File "/Users/huawei/Downloads/XX-Net-master/code/default/gae_proxy/local/ipv6_tunnel/common.py", line 4, in <module>
    from .pteredor import teredo_prober
  File "/Users/huawei/Downloads/XX-Net-master/code/default/gae_proxy/local/ipv6_tunnel/pteredor.py", line 428, in <module>
    if locale.getdefaultlocale()[0] == 'zh_CN':
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 543, in getdefaultlocale
    return _parse_localename(localename)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 475, in _parse_localename
    raise ValueError, 'unknown locale: %s' % localename
ValueError: unknown locale: UTF-8

May 08 10:58:13.577 [launcher][ERROR] launcher except:ValueError('unknown locale: UTF-8',)
May 08 10:58:13.578 [launcher][ERROR] Except stack:Traceback (most recent call last):
  File "start.py", line 247, in <module>
    main()
  File "start.py", line 226, in main
    module_init.start_all_auto()
  File "/Users/huawei/Downloads/XX-Net-master/code/default/launcher/module_init.py", line 113, in start_all_auto
    start(module)
  File "/Users/huawei/Downloads/XX-Net-master/code/default/launcher/module_init.py", line 40, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "/Users/huawei/Downloads/XX-Net-master/code/default/gae_proxy/start.py", line 13, in <module>
    import local.proxy as client
  File "/Users/huawei/Downloads/XX-Net-master/code/default/gae_proxy/local/proxy.py", line 86, in <module>
    import proxy_handler
  File "/Users/huawei/Downloads/XX-Net-master/code/default/gae_proxy/local/proxy_handler.py", line 53, in <module>
    import web_control
  File "/Users/huawei/Downloads/XX-Net-master/code/default/gae_proxy/local/web_control.py", line 32, in <module>
    import ipv6_tunnel
  File "/Users/huawei/Downloads/XX-Net-master/code/default/gae_proxy/local/ipv6_tunnel/__init__.py", line 14, in <module>
    from .darwin import state, enable, disable, set_best_server
  File "/Users/huawei/Downloads/XX-Net-master/code/default/gae_proxy/local/ipv6_tunnel/darwin.py", line 6, in <module>
    from .common import *
  File "/Users/huawei/Downloads/XX-Net-master/code/default/gae_proxy/local/ipv6_tunnel/common.py", line 4, in <module>
    from .pteredor import teredo_prober
  File "/Users/huawei/Downloads/XX-Net-master/code/default/gae_proxy/local/ipv6_tunnel/pteredor.py", line 428, in <module>
    if locale.getdefaultlocale()[0] == 'zh_CN':
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 543, in getdefaultlocale
    return _parse_localename(localename)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 475, in _parse_localename
    raise ValueError, 'unknown locale: %s' % localename
ValueError: unknown locale: UTF-8

**Comment by Howill-Li** [comment]
搞定了，

参照：http://ju.outofmemory.cn/entry/107663

**Comment by SeaHOH** [comment]
@Howill-Li 
谢谢你，提供了这些信息。

@xxnet 
我不太懂，这些导入似乎可以加入启动脚本。

**Comment by Howill-Li** [comment]
@然而重启之后，又启动不了了，看来我应该抹盘重装系统了

**Comment by xxnet** [comment]
@SeaHOH
​此处判断可以用Web界面的系统环境语言判断代码

https://github.com/XX-net/XX-Net/blob/5166ae6e61c7914260ddacc3bde2a8b450b56516/code/default/launcher/simple_i18n.py#L17



MacOS 上用了特殊处理
