### ISSUE TITLE
XX-Net 3.11.14 开不起来

### ISSUE THREAD

**Issue by beiking** [XX-net/XX-Net#10708]
在一台腾讯云服务器上，
测了3个版本 3.11.10 正常开启
3.11.13 和 3.11.14 都开不起来

data\launcher\error.log
May 17 17:37:54.904 type:<type 'exceptions.EOFError'> value=EOF when reading a line traceback:<traceback object at 0x05351238>May 17 17:37:54.998 type:<type 'exceptions.IOError'> value=[Errno 9] Bad file descriptor traceback:<traceback object at 0x051608F0>

data\launcher\launcher.log
May 17 17:37:52.091 - [INFO] use build-in openssl lib
May 17 17:37:52.107 - [INFO] start XX-Net 3.11.14
May 17 17:37:52.107 - [DEBUG] start confirm_xxnet_exit
May 17 17:37:53.185 - [DEBUG] good, xxnet:8085 clear!
May 17 17:37:53.185 - [DEBUG] finished confirm_xxnet_exit
May 17 17:37:54.904 - [ERROR] start module gae_proxy fail:invalid literal for float(): 2008ServerR2
May 17 17:37:54.904 - [ERROR] Except stack:Traceback (most recent call last):
  File "C:\MyFile\SOFTWARE\XX-Net\code\default\launcher\module_init.py", line 40, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "C:\MyFile\SOFTWARE\XX-Net\code\default\gae_proxy\start.py", line 13, in <module>
    import local.proxy as client
  File "C:\MyFile\SOFTWARE\XX-Net\code\default\gae_proxy\local\proxy.py", line 86, in <module>
    import proxy_handler
  File "C:\MyFile\SOFTWARE\XX-Net\code\default\gae_proxy\local\proxy_handler.py", line 53, in <module>
    import web_control
  File "C:\MyFile\SOFTWARE\XX-Net\code\default\gae_proxy\local\web_control.py", line 32, in <module>
    import ipv6_tunnel
  File "C:\MyFile\SOFTWARE\XX-Net\code\default\gae_proxy\local\ipv6_tunnel\__init__.py", line 12, in <module>
    from .win10 import state, enable, disable, set_best_server
  File "C:\MyFile\SOFTWARE\XX-Net\code\default\gae_proxy\local\ipv6_tunnel\win10.py", line 166, in <module>
    client_ext = 'natawareclient' if float(platform.win32_ver()[0]) > 7 else 'enterpriseclient'
ValueError: invalid literal for float(): 2008ServerR2

May 17 17:37:54.904 - [ERROR] launcher except:ValueError('invalid literal for float(): 2008ServerR2',)
May 17 17:37:54.904 - [ERROR] Except stack:Traceback (most recent call last):
  File "C:\MyFile\SOFTWARE\XX-Net\code\default\launcher\start.py", line 247, in <module>
    main()
  File "C:\MyFile\SOFTWARE\XX-Net\code\default\launcher\start.py", line 226, in main
    module_init.start_all_auto()
  File "C:\MyFile\SOFTWARE\XX-Net\code\default\launcher\module_init.py", line 113, in start_all_auto
    start(module)
  File "C:\MyFile\SOFTWARE\XX-Net\code\default\launcher\module_init.py", line 40, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "C:\MyFile\SOFTWARE\XX-Net\code\default\gae_proxy\start.py", line 13, in <module>
    import local.proxy as client
  File "C:\MyFile\SOFTWARE\XX-Net\code\default\gae_proxy\local\proxy.py", line 86, in <module>
    import proxy_handler
  File "C:\MyFile\SOFTWARE\XX-Net\code\default\gae_proxy\local\proxy_handler.py", line 53, in <module>
    import web_control
  File "C:\MyFile\SOFTWARE\XX-Net\code\default\gae_proxy\local\web_control.py", line 32, in <module>
    import ipv6_tunnel
  File "C:\MyFile\SOFTWARE\XX-Net\code\default\gae_proxy\local\ipv6_tunnel\__init__.py", line 12, in <module>
    from .win10 import state, enable, disable, set_best_server
  File "C:\MyFile\SOFTWARE\XX-Net\code\default\gae_proxy\local\ipv6_tunnel\win10.py", line 166, in <module>
    client_ext = 'natawareclient' if float(platform.win32_ver()[0]) > 7 else 'enterpriseclient'
ValueError: invalid literal for float(): 2008ServerR2

May 17 17:37:54.919 - [ERROR] uncaught Exception, type=<type 'exceptions.EOFError'> value=EOF when reading a line traceback:<traceback object at 0x05351238>
May 17 17:37:54.998 - [ERROR] stop module gae_proxy fail:'imp'
May 17 17:37:54.998 - [ERROR] Except stack:Traceback (most recent call last):
  File "C:\MyFile\SOFTWARE\XX-Net\code\default\launcher\module_init.py", line 74, in stop
    _start = proc_handler[module]["imp"].start
KeyError: 'imp'

May 17 17:37:54.998 - [INFO] begin to exit web control
May 17 17:37:54.998 - [ERROR] uncaught Exception, type=<type 'exceptions.IOError'> value=[Errno 9] Bad file descriptor traceback:<traceback object at 0x051608F0>

**Comment by xxnet** [comment]
​@SeaHOH
  这代码应该加上try except，防止遇上什么环境问题影响正常启动。

**Comment by beiking** [comment]
还有一个问题
3.11.14 谷歌在线翻译网页链接提示
![qq 20180517215623](https://user-images.githubusercontent.com/12060194/40182209-7624c034-5a1d-11e8-9473-7e5da9d9968f.png)

3.11.13 不会这样

**Comment by SeaHOH** [comment]
已修复，改用字符串比较。

@beiking 比较了一下，没有发现原因，这好像是 3.11.13 也有的那个翻译 bug？

**Comment by xxnet** [comment]
​明天发个新版吧，google翻译用的人挺多的，也累计了几个修复了。
