### ISSUE TITLE
XP系统启动不了，用的最新版本

### ISSUE THREAD

**Issue by PI3141592653589** [XX-net/XX-Net#10755]

**Comment by SeaHOH** [comment]
尝试重新下载，
再不行，data 文件夹是否有 log 文件？双击 start.bat 是否有错误输出？

**Comment by PI3141592653589** [comment]
May 23 18:53:26.328 - [INFO] use build-in openssl lib
May 23 18:53:26.328 - [INFO] start XX-Net 3.11.14
May 23 18:53:26.328 - [DEBUG] start confirm_xxnet_exit
May 23 18:53:27.281 - [DEBUG] good, xxnet:8085 clear!
May 23 18:53:27.281 - [DEBUG] finished confirm_xxnet_exit
May 23 18:53:28.000 - [ERROR] start module gae_proxy fail:function 'OpenProcessToken' not found
May 23 18:53:28.000 - [ERROR] Except stack:Traceback (most recent call last):
  File "D:\Tools\XX-Net-3.11.14\code\default\launcher\module_init.py", line 40, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "D:\Tools\XX-Net-3.11.14\code\default\gae_proxy\start.py", line 13, in <module>
    import local.proxy as client
  File "D:\Tools\XX-Net-3.11.14\code\default\gae_proxy\local\proxy.py", line 86, in <module>
    import proxy_handler
  File "D:\Tools\XX-Net-3.11.14\code\default\gae_proxy\local\proxy_handler.py", line 53, in <module>
    import web_control
  File "D:\Tools\XX-Net-3.11.14\code\default\gae_proxy\local\web_control.py", line 32, in <module>
    import ipv6_tunnel
  File "D:\Tools\XX-Net-3.11.14\code\default\gae_proxy\local\ipv6_tunnel\__init__.py", line 10, in <module>
    from .win10 import state, enable, disable, test_teredo, set_best_server
  File "D:\Tools\XX-Net-3.11.14\code\default\gae_proxy\local\ipv6_tunnel\win10.py", line 10, in <module>
    import win32elevate
  File "D:\Tools\XX-Net-3.11.14\code\default\python27\1.0\lib\win32\win32elevate.py", line 37, in <module>
    OpenProcessToken = ctypes.windll.kernel32.OpenProcessToken
  File "D:\Tools\XX-Net-3.11.14\code\default\python27\1.0\lib\ctypes\__init__.py", line 301, in __getattr__
    func = self.__getitem__(name)
  File "D:\Tools\XX-Net-3.11.14\code\default\python27\1.0\lib\ctypes\__init__.py", line 306, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'OpenProcessToken' not found

**Comment by PI3141592653589** [comment]
没有log文件

**Comment by SeaHOH** [comment]
[win32elevate.zip](https://github.com/XX-net/XX-Net/files/2031000/win32elevate.zip)
帮忙测试下，替换这个 win32elevate.py 能否启动。

**Comment by whhxmwhh** [comment]
由于GFW昨天部署TCP阻断，又有一大批人翻不出来了，这次只封目标ip的tcp入墙连接，没有封icmp，导致你的主机能ping通但是ssh连不上，也无法访问基于tcp的其它服务：web、ssr等等。让你的主机变成植物人。

**Comment by PI3141592653589** [comment]
换了win32elevate.py 也不行

May 24 09:08:45.234 - [INFO] use build-in openssl lib
May 24 09:08:45.250 - [INFO] start XX-Net 3.11.14
May 24 09:08:45.250 - [DEBUG] start confirm_xxnet_exit
May 24 09:08:46.234 - [DEBUG] good, xxnet:8085 clear!
May 24 09:08:46.234 - [DEBUG] finished confirm_xxnet_exit
May 24 09:08:49.218 - [ERROR] start module gae_proxy fail:[Error 87] 参数不正确。
May 24 09:08:49.281 - [ERROR] Except stack:Traceback (most recent call last):
  File "D:\Tools\XX-Net-3.11.14\code\default\launcher\module_init.py", line 40, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "D:\Tools\XX-Net-3.11.14\code\default\gae_proxy\start.py", line 13, in <module>
    import local.proxy as client
  File "D:\Tools\XX-Net-3.11.14\code\default\gae_proxy\local\proxy.py", line 86, in <module>
    import proxy_handler
  File "D:\Tools\XX-Net-3.11.14\code\default\gae_proxy\local\proxy_handler.py", line 53, in <module>
    import web_control
  File "D:\Tools\XX-Net-3.11.14\code\default\gae_proxy\local\web_control.py", line 32, in <module>
    import ipv6_tunnel
  File "D:\Tools\XX-Net-3.11.14\code\default\gae_proxy\local\ipv6_tunnel\__init__.py", line 10, in <module>
    from .win10 import state, enable, disable, test_teredo, set_best_server
  File "D:\Tools\XX-Net-3.11.14\code\default\gae_proxy\local\ipv6_tunnel\win10.py", line 138, in <module>
    has_admin = win32elevate.areAdminRightsElevated()
  File "D:\Tools\XX-Net-3.11.14\code\default\python27\1.0\lib\win32\win32elevate.py", line 113, in areAdminRightsElevated
    raise ctypes.WinError()
WindowsError: [Error 87] 参数不正确。

**Comment by xxnet** [comment]
​请下载 3.12.0版本
