### ISSUE TITLE
Fedora下运行start脚本报错

### ISSUE THREAD

**Issue by serverLua** [XX-net/XX-Net#10784]
日志：XX-Net version:3.12.0
Installing pyOpenSSL for your system... Please type in your password if requested
May 27 07:46:00.734 [launcher][INFO] import build-in openssl fail:ImportError('No module named pycparser',)
May 27 07:46:00.741 [launcher][ERROR] import system python-OpenSSL fail:ImportError('No module named pycparser',)
May 27 07:46:00.741 [launcher][ERROR] Except stack:Traceback (most recent call last):
  File "code/default/launcher/start.py", line 175, in <module>
    import OpenSSL
  File "/home/andyc/XX-Net-3.12.0/code/default/python27/1.0/lib/noarch/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/home/andyc/XX-Net-3.12.0/code/default/python27/1.0/lib/noarch/OpenSSL/rand.py", line 12, in <module>
    from OpenSSL._util import (
  File "/home/andyc/XX-Net-3.12.0/code/default/python27/1.0/lib/noarch/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/home/andyc/XX-Net-3.12.0/code/default/python27/1.0/lib/linux/cryptography/hazmat/bindings/openssl/binding.py", line 60, in <module>
    class Binding(object):
  File "/home/andyc/XX-Net-3.12.0/code/default/python27/1.0/lib/linux/cryptography/hazmat/bindings/openssl/binding.py", line 109, in Binding
    libraries=_get_libraries(sys.platform)
  File "/home/andyc/XX-Net-3.12.0/code/default/python27/1.0/lib/linux/cryptography/hazmat/bindings/utils.py", line 97, in build_ffi_for_binding
    extra_link_args=extra_link_args,
  File "/home/andyc/XX-Net-3.12.0/code/default/python27/1.0/lib/linux/cryptography/hazmat/bindings/utils.py", line 105, in build_ffi
    ffi = FFI()
  File "/home/andyc/XX-Net-3.12.0/code/default/python27/1.0/lib/linux/cffi/api.py", line 52, in __init__
    from . import cparser, model
  File "/home/andyc/XX-Net-3.12.0/code/default/python27/1.0/lib/linux/cffi/cparser.py", line 6, in <module>
    import pycparser
ImportError: No module named pycparser

Try install python-openssl

**Comment by serverLua** [comment]
[andyc@localhost XX-Net-3.12.0]$ sudo dnf install python-openssl
上次元数据过期检查：0:18:17 前，执行于 2018年05月27日 星期日 07时28分59秒。
未找到匹配的参数： python-openssl
错误：没有任何匹配

**Comment by bdtbbylzy** [comment]
试试到pkgs.org，下载可用的rpm包，手动安装。 （不保证成功，只是提供一个思路）

**Comment by serverLua** [comment]
谢谢

**Comment by tbbrave** [comment]
fedora 30  下复现。


解决办法：
1. pip install --user cryptography
2. pip2 install --user pyopenssl


done

**Comment by tbbrave** [comment]
建议加一个requirement，readme里写明白用之前run下
pip install -r req.txt
要不包依赖问题很麻烦。
