### ISSUE TITLE
XX-NET 3.12.0无法启动

### ISSUE THREAD

**Issue by mjwang1010** [XX-net/XX-Net#10823]
* 是否试过最新的版本(https://github.com/XX-net/XX-Net/releases)？
checked

* 是否查看过Wiki（https://github.com/XX-net/XX-Net/wiki）
checked

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：
mac Sierra 10.13.4 
打开"start"后弹出terminal，内容如下：
“/Applications/XX-Net-3.12.0/start ; exit;
XX-Net version:3.12.0
Run XX-Net in background.
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]”
但没有XX-NET图标出现，系统也无python进程

launcher log如下：
"Jun 01 10:21:03.032 - [INFO] use build-in openssl lib
Jun 01 10:21:03.033 - [INFO] start XX-Net 3.12.0
Jun 01 10:21:03.033 - [DEBUG] start confirm_xxnet_exit
Jun 01 10:21:03.035 - [DEBUG] good, xxnet:8085 clear!
Jun 01 10:21:03.035 - [DEBUG] finished confirm_xxnet_exit
Jun 01 10:21:03.389 - [ERROR] start module gae_proxy fail:unknown locale: UTF-8
Jun 01 10:21:03.391 - [ERROR] Except stack:Traceback (most recent call last):
  File "/Applications/XX-Net-3.12.0/code/default/launcher/module_init.py", line 40, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "/Applications/XX-Net-3.12.0/code/default/gae_proxy/start.py", line 13, in <module>
    import local.proxy as client
  File "/Applications/XX-Net-3.12.0/code/default/gae_proxy/local/proxy.py", line 86, in <module>
    import proxy_handler
  File "/Applications/XX-Net-3.12.0/code/default/gae_proxy/local/proxy_handler.py", line 53, in <module>
    import web_control
  File "/Applications/XX-Net-3.12.0/code/default/gae_proxy/local/web_control.py", line 32, in <module>
    import ipv6_tunnel
  File "/Applications/XX-Net-3.12.0/code/default/gae_proxy/local/ipv6_tunnel/__init__.py", line 5, in <module>
    from .common import test_teredo
  File "/Applications/XX-Net-3.12.0/code/default/gae_proxy/local/ipv6_tunnel/common.py", line 4, in <module>
    from .pteredor import teredo_prober
  File "/Applications/XX-Net-3.12.0/code/default/gae_proxy/local/ipv6_tunnel/pteredor.py", line 428, in <module>
    if locale.getdefaultlocale()[0] == 'zh_CN':
  File "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 545, in getdefaultlocale
    return _parse_localename(localename)
  File "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 477, in _parse_localename
    raise ValueError, 'unknown locale: %s' % localename
ValueError: unknown locale: UTF-8

Jun 01 10:21:03.391 - [ERROR] launcher except:ValueError('unknown locale: UTF-8',)
Jun 01 10:21:03.392 - [ERROR] Except stack:Traceback (most recent call last):
  File "code/default/launcher/start.py", line 247, in <module>
  File "code/default/launcher/start.py", line 226, in main
  File "/Applications/XX-Net-3.12.0/code/default/launcher/module_init.py", line 113, in start_all_auto
    start(module)
  File "/Applications/XX-Net-3.12.0/code/default/launcher/module_init.py", line 40, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "/Applications/XX-Net-3.12.0/code/default/gae_proxy/start.py", line 13, in <module>
    import local.proxy as client
  File "/Applications/XX-Net-3.12.0/code/default/gae_proxy/local/proxy.py", line 86, in <module>
    import proxy_handler
  File "/Applications/XX-Net-3.12.0/code/default/gae_proxy/local/proxy_handler.py", line 53, in <module>
    import web_control
  File "/Applications/XX-Net-3.12.0/code/default/gae_proxy/local/web_control.py", line 32, in <module>
    import ipv6_tunnel
  File "/Applications/XX-Net-3.12.0/code/default/gae_proxy/local/ipv6_tunnel/__init__.py", line 5, in <module>
    from .common import test_teredo
  File "/Applications/XX-Net-3.12.0/code/default/gae_proxy/local/ipv6_tunnel/common.py", line 4, in <module>
    from .pteredor import teredo_prober
  File "/Applications/XX-Net-3.12.0/code/default/gae_proxy/local/ipv6_tunnel/pteredor.py", line 428, in <module>
    if locale.getdefaultlocale()[0] == 'zh_CN':
  File "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 545, in getdefaultlocale
    return _parse_localename(localename)
  File "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 477, in _parse_localename
    raise ValueError, 'unknown locale: %s' % localename
ValueError: unknown locale: UTF-8

Jun 01 10:21:03.393 - [ERROR] uncaught Exception, type=<type 'exceptions.EOFError'> value=EOF when reading a line traceback:<traceback object at 0x106744fc8>
Jun 01 10:21:07.112 - [ERROR] stop module gae_proxy fail:'imp'
Jun 01 10:21:07.112 - [ERROR] Except stack:Traceback (most recent call last):
  File "/Applications/XX-Net-3.12.0/code/default/launcher/module_init.py", line 74, in stop
    _start = proc_handler[module]["imp"].start
KeyError: 'imp'

Jun 01 10:21:07.112 - [INFO] begin to exit web control
Jun 01 10:21:07.114 - [ERROR] uncaught Exception, type=<type 'exceptions.AttributeError'> value='NoneType' object has no attribute 'shutdown' traceback:<traceback object at 0x108bcacf8>
"
error log 如下：
"Jun 01 10:21:03.393 type:<type 'exceptions.EOFError'> value=EOF when reading a line traceback:<traceback object at 0x106744fc8>Jun 01 10:21:07.114 type:<type 'exceptions.AttributeError'> value='NoneType' object has no attribute 'shutdown' traceback:<traceback object at 0x108bcacf8>
"
谢谢！

**Comment by SeaHOH** [comment]
https://github.com/XX-net/XX-Net/issues/10540#issuecomment-387273699
#10794

**Comment by SeaHOH** [comment]
先前误以为跟 10540 是一样的状况，已修正。

不过虽然具体触发位置不同，但是解决的方法是一样的。
因为之前那个触发位置还没找到，估计你还是要按上面的方法处理一下。

**Comment by mjwang1010** [comment]
@SeaHOH 
非常感谢！ 现在退回到版本3.8.5，还能用ipv4的通道，就是x-tunnel用不了。等会儿试试这个最新版本。
另外，希望x-tunnel早日畅通。

**Comment by SeaHOH** [comment]
对了，这个修改还没包含到发布版本，你可以先使用 master 分支。
