### ISSUE TITLE
3.11.11版本 今天突然点击图标之后没反应 浏览器也没有弹出配置页 更新3.11.15之后一样

### ISSUE THREAD

**Issue by lanmanpop** [XX-net/XX-Net#10841]
* 是否试过最新的版本(https://github.com/XX-net/XX-Net/releases)？
  

* 是否查看过Wiki（https://github.com/XX-net/XX-Net/wiki）

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：

之前用好好的 今天突然打不开了 后台进程里有个pythonw.exe
我搜索过发现有人和我一样的问题 #10540 (comment)  #10794 
但是我看不懂解决办法  
什么叫【原因最后找到了。。是因为设置的LANG 变量位UTF-8，换成zh_CN.UTF-8就好了。】
是指lang文件夹么？

**Comment by lanmanpop** [comment]
Jun 02 14:38:07.886 [launcher][INFO] use build-in openssl lib
Jun 02 14:38:07.890 [launcher][INFO] start XX-Net 3.11.15
Jun 02 14:38:07.890 [launcher][DEBUG] start confirm_xxnet_exit
Jun 02 14:38:08.906 [launcher][DEBUG] good, xxnet:8085 clear!
Jun 02 14:38:08.908 [launcher][DEBUG] finished confirm_xxnet_exit
Jun 02 14:38:09.237 [gae_proxy][INFO] ------------------------------------------------------
Jun 02 14:38:09.238 [gae_proxy][INFO] Python Version     : 2.7.13
Jun 02 14:38:09.240 [gae_proxy][INFO] OS                 : Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
Jun 02 14:38:09.240 [gae_proxy][INFO] Listen Address     : 127.0.0.1:8087
Jun 02 14:38:09.240 [gae_proxy][INFO] Using public APPID
Jun 02 14:38:09.240 [gae_proxy][INFO] ------------------------------------------------------
Jun 02 14:38:09.256 [gae_proxy][DEBUG] Importing CA
Jun 02 14:38:09.256 [gae_proxy][DEBUG] Removing windows CA
Jun 02 14:38:09.302 [gae_proxy][DEBUG] Begin to import Windows CA
Jun 02 14:38:09.309 [gae_proxy][INFO] SSL use version:TLSv1_2
Jun 02 14:38:09.445 [gae_proxy][DEBUG] network IPv4 is ok, cost:511 ms
Jun 02 14:38:09.722 [gae_proxy][INFO] OpenSSL support alpn
Jun 02 14:38:09.723 [gae_proxy][INFO] load ip range file:H:\XX-Net-3.11.15\code\default\gae_proxy\local\ip_range.txt
Jun 02 14:38:09.725 [gae_proxy][INFO] load ip_list num:35, target num:35
Jun 02 14:38:09.730 [gae_proxy][INFO] SSL use version:TLSv1_2
Jun 02 14:38:09.731 [gae_proxy][ERROR] bind to 127.0.0.1:8087 fail:error(10013, '')
Exception in thread Thread-3:
Traceback (most recent call last):
  File "H:\XX-Net-3.11.15\code\default\python27\1.0\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "H:\XX-Net-3.11.15\code\default\python27\1.0\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "H:\XX-Net-3.11.15\code\default\gae_proxy\start.py", line 18, in main
    client.main(args)
  File "H:\XX-Net-3.11.15\code\default\gae_proxy\local\proxy.py", line 130, in main
    (listen_ip, front.config.listen_port), proxy_handler.GAEProxyHandler, logger=xlog)
  File "H:\XX-Net-3.11.15\code\default\python27\1.0\lib\noarch\simple_http_server.py", line 410, in __init__
    self.init_socket()
  File "H:\XX-Net-3.11.15\code\default\python27\1.0\lib\noarch\simple_http_server.py", line 420, in init_socket
    self.add_listen(addr)
  File "H:\XX-Net-3.11.15\code\default\python27\1.0\lib\noarch\simple_http_server.py", line 434, in add_listen
    raise Exception(err_string)
Exception: bind to 127.0.0.1:8087 fail:error(10013, '')

Jun 02 14:38:09.794 [gae_proxy][DEBUG] network IPv6 is ok, cost:859 ms
Jun 02 14:38:14.732 [gae_proxy][DEBUG] report_connect_fail:2600:5:100:1::d
Jun 02 14:38:14.735 [gae_proxy][DEBUG] connect 2600:5:100:1::d fail:error("conn fail, sni:xxnet-234-1q.appspot.com, top:xxnet-234-1q.appspot.com e:timeout('timed out',)",)
Jun 02 14:38:14.735 [gae_proxy][DEBUG] report_connect_fail:2001:578:2a:203::d
Jun 02 14:38:14.738 [gae_proxy][DEBUG] connect 2001:578:2a:203::d fail:error("conn fail, sni:shoe-wait-reading.org, top: e:timeout('timed out',)",)
Jun 02 14:38:21.750 [gae_proxy][DEBUG] report_connect_fail:2001:1970:1:2053::10
Jun 02 14:38:21.751 [gae_proxy][DEBUG] connect 2001:1970:1:2053::10 fail:error("conn fail, sni:makelshadow3cfde6a.appspot.com, top:makelshadow3cfde6a.appspot.com e:timeout('timed out',)",)
Jun 02 14:38:21.753 [gae_proxy][DEBUG] report_connect_fail:2001:4958:300:500::11
Jun 02 14:38:21.753 [gae_proxy][DEBUG] connect 2001:4958:300:500::11 fail:error("conn fail, sni:expressionleading.us, top: e:timeout('timed out',)",)
Jun 02 14:38:28.760 [gae_proxy][DEBUG] report_connect_fail:2a00:1450:4003:d::18
Jun 02 14:38:28.761 [gae_proxy][DEBUG] connect 2a00:1450:4003:d::18 fail:error("conn fail, sni:female-number-airline.us, top: e:timeout('timed out',)",)
Jun 02 14:38:29.447 [gae_proxy][DEBUG] report_connect_fail:2a00:1450:4003:10::7
Jun 02 14:38:29.449 [gae_proxy][DEBUG] connect 2a00:1450:4003:10::7 fail:error('certificate is none, sni:xxnet-stan3.appspot.com',)
Jun 02 14:38:31.747 [gae_proxy][DEBUG] create_ssl update ip:2001:660:302a:1::d time:980 h2:0 sni:salad-salad-requirement.net, host:
Jun 02 14:38:36.457 [gae_proxy][DEBUG] report_connect_fail:2804:d40:82:e001::c
Jun 02 14:38:36.459 [gae_proxy][DEBUG] connect 2804:d40:82:e001::c fail:error("conn fail, sni:xxnet-iceliquid30.appspot.com, top:xxnet-iceliquid30.appspot.com e:timeout('timed out',)",)
Jun 02 14:38:38.742 [gae_proxy][DEBUG] create_ssl update ip:2001:660:302a:1::d time:986 h2:0 sni:shirtwing.us, host:
Jun 02 14:38:39.524 [gae_proxy][DEBUG] create_ssl update ip:2001:b032:5d00::f time:1059 h2:0 sni:makelshadow3103d46.appspot.com, host:makelshadow3103d46.appspot.com
Jun 02 14:38:45.726 [gae_proxy][DEBUG] create_ssl update ip:2001:660:302a:1::d time:977 h2:0 sni:program-analysis-passenger.net, host:
Jun 02 14:38:46.584 [gae_proxy][DEBUG] create_ssl update ip:2001:b032:101:1::10 time:1053 h2:0 sni:xxnet-kimdonate3.appspot.com, host:xxnet-kimdonate3.appspot.com
Jun 02 14:38:51.964 [gae_proxy][INFO] scan_ip add ip:2a00:1450:4003:10::b time:420 h2:0
Jun 02 14:38:52.716 [gae_proxy][DEBUG] create_ssl update ip:2001:660:302a:1::d time:982 h2:0 sni:permitaffair.ml, host:
Jun 02 14:38:53.713 [gae_proxy][DEBUG] create_ssl update ip:2001:b032:5d01::11 time:1120 h2:0 sni:xxnet-1470566028726.appspot.com, host:xxnet-1470566028726.appspot.com
Jun 02 14:39:00.379 [gae_proxy][DEBUG] create_ssl update ip:2001:660:302a:1::d time:1654 h2:0 sni:inspection.special.situation.us, host:
Jun 02 14:39:00.722 [gae_proxy][DEBUG] create_ssl update ip:2001:b000:1e0:c101::12 time:1004 h2:0 sni:xx-net-boom1.appspot.com, host:xx-net-boom1.appspot.com
Jun 02 14:39:05.373 [gae_proxy][INFO] scan_ip add ip:2800:3f0:4001:1b::9 time:565 h2:0
Jun 02 14:39:11.389 [gae_proxy][DEBUG] report_connect_fail:2a00:1450:4003:10::b
Jun 02 14:39:11.390 [gae_proxy][DEBUG] connect 2a00:1450:4003:10::b fail:error("conn fail, sni:salesweet.net, top: e:timeout('timed out',)",)
Jun 02 14:39:11.730 [gae_proxy][DEBUG] report_connect_fail:2800:3f0:4001:1b::9
Jun 02 14:39:11.732 [gae_proxy][DEBUG] connect 2800:3f0:4001:1b::9 fail:error("conn fail, sni:xxnet-110.appspot.com, top:xxnet-110.appspot.com e:timeout('timed out',)",)
Jun 02 14:39:12.097 [gae_proxy][INFO] scan_ip add ip:2a00:1450:4003:e::12 time:427 h2:0
Jun 02 14:39:15.286 [gae_proxy][DEBUG] create_ssl update ip:2001:b032:8101::d time:1884 h2:0 sni:process.rip.us, host:
Jun 02 14:39:18.739 [gae_proxy][DEBUG] report_connect_fail:2804:d50:81:9001::c
Jun 02 14:39:18.741 [gae_proxy][DEBUG] connect 2804:d50:81:9001::c fail:error("conn fail, sni:animated-scope-189703.appspot.com, top:animated-scope-189703.appspot.com e:timeout('timed out',)",)
Jun 02 14:39:22.840 [gae_proxy][DEBUG] create_ssl update ip:2001:d08:10:207::f time:1544 h2:0 sni:bite-store-classroom.net, host:
Jun 02 14:39:24.682 [gae_proxy][INFO] scan_ip add ip:2a00:1450:4003:12::15 time:419 h2:0
Jun 02 14:39:25.748 [gae_proxy][DEBUG] report_connect_fail:2a00:1450:4003:e::12
Jun 02 14:39:25.753 [gae_proxy][DEBUG] connect 2a00:1450:4003:e::12 fail:error("conn fail, sni:leonproject10.appspot.com, top:leonproject10.appspot.com e:timeout('timed out',)",)
Jun 02 14:39:29.240 [gae_proxy][DEBUG] create_ssl update ip:2001:d08:10:207::f time:1483 h2:0 sni:xxnet-57.appspot.com, host:xxnet-57.appspot.com
Jun 02 14:39:30.085 [gae_proxy][DEBUG] create_ssl update ip:2610:28:42c:100::c time:1236 h2:0 sni:college-lady.us, host:
Jun 02 14:39:36.159 [gae_proxy][DEBUG] create_ssl update ip:2a00:1450:4003:12::15 time:905 h2:0 sni:xxnet-wich03.appspot.com, host:xxnet-wich03.appspot.com
Jun 02 14:39:37.337 [gae_proxy][DEBUG] create_ssl update ip:2610:28:42c:100::c time:1241 h2:0 sni:tree-target-pitch.org, host:
Jun 02 14:39:43.399 [gae_proxy][DEBUG] create_ssl update ip:2610:28:42c:100::c time:1230 h2:0 sni:xxnet-ian07.appspot.com, host:xxnet-ian07.appspot.com
Jun 02 14:39:44.813 [gae_proxy][DEBUG] create_ssl update ip:2001:d08:12:a003::13 time:1469 h2:0 sni:hourelevatorexercise.us, host:
Jun 02 14:39:46.161 [gae_proxy][INFO] scan_ip add ip:2404:6800:400e:8::7 time:1848 h2:0
Jun 02 14:39:52.807 [gae_proxy][DEBUG] create_ssl update ip:2001:818:e4f2:1::f time:3391 h2:0 sni:linear-axle-186502.appspot.com, host:linear-axle-186502.appspot.com
Jun 02 14:39:55.824 [gae_proxy][DEBUG] report_connect_fail:2a00:1450:4020:19::c
Jun 02 14:39:55.827 [gae_proxy][DEBUG] connect 2a00:1450:4020:19::c fail:error("conn fail, sni:releasepaper.com, top: e:timeout('timed out',)",)
Jun 02 14:40:02.700 [gae_proxy][DEBUG] create_ssl update ip:2620:11a:a01a::19 time:3885 h2:0 sni:appid-5-192801.appspot.com, host:appid-5-192801.appspot.com
Jun 02 14:40:02.836 [gae_proxy][DEBUG] report_connect_fail:2607:f798:1e:400::13
Jun 02 14:40:02.841 [gae_proxy][DEBUG] connect 2607:f798:1e:400::13 fail:error("conn fail, sni:passenger-hearing-phase.com, top: e:timeout('timed out',)",)
Jun 02 14:40:09.850 [gae_proxy][DEBUG] report_connect_fail:2804:214:800f:4::e
Jun 02 14:40:09.856 [gae_proxy][DEBUG] connect 2804:214:800f:4::e fail:error("conn fail, sni:rockhousingreflection.org, top: e:timeout('timed out',)",)
Jun 02 14:40:10.674 [gae_proxy][WARNING] h1 2620:11a:a01a::19 HEAD keep alive request fail:Exception('time out',)
Jun 02 14:40:10.676 [gae_proxy][WARNING] 2620:11a:a01a::19 trace: 0:connect, 6042:init, 2:head,:5819, processed:0, transfered:0, sni:appid-5-192801.appspot.com
Jun 02 14:40:10.677 [gae_proxy][DEBUG] 2620:11a:a01a::19 worker close:down fail
Jun 02 14:40:10.679 [gae_proxy][DEBUG] report_connect_fail:2620:11a:a01a::19
Jun 02 14:40:13.709 [gae_proxy][DEBUG] report_connect_fail:2001:d08:12:a003::13
Jun 02 14:40:13.711 [gae_proxy][DEBUG] connect 2001:d08:12:a003::13 fail:error("conn fail, sni:xxnet-stan6.appspot.com, top:xxnet-stan6.appspot.com e:timeout('timed out',)",)
Jun 02 14:40:15.684 [gae_proxy][DEBUG] 2620:11a:a01a::19 worker close:keep alive
Jun 02 14:40:16.863 [gae_proxy][DEBUG] report_connect_fail:2001:660:302a:1::d
Jun 02 14:40:16.866 [gae_proxy][DEBUG] connect 2001:660:302a:1::d fail:error("conn fail, sni:signature-fuel.us, top: e:timeout('timed out',)",)
Jun 02 14:40:20.718 [gae_proxy][DEBUG] report_connect_fail:2001:d08:11:204::c
Jun 02 14:40:20.721 [gae_proxy][DEBUG] connect 2001:d08:11:204::c fail:error("conn fail, sni:xxnet-16091703.appspot.com, top:xxnet-16091703.appspot.com e:timeout('timed out',)",)
Jun 02 14:40:23.874 [gae_proxy][DEBUG] report_connect_fail:2604:d600:0:4::e
Jun 02 14:40:23.875 [gae_proxy][DEBUG] connect 2604:d600:0:4::e fail:error("conn fail, sni:attack-child-excitement.us, top: e:timeout('timed out',)",)
Jun 02 14:40:27.728 [gae_proxy][DEBUG] report_connect_fail:2001:b032:8101::d
Jun 02 14:40:27.730 [gae_proxy][DEBUG] connect 2001:b032:8101::d fail:error("conn fail, sni:liyuankai90.appspot.com, top:liyuankai90.appspot.com e:timeout('timed out',)",)
Jun 02 14:40:30.883 [gae_proxy][DEBUG] report_connect_fail:2607:fa48:70:9::13
Jun 02 14:40:30.886 [gae_proxy][DEBUG] connect 2607:fa48:70:9::13 fail:error("conn fail, sni:failure-effort-growth.net, top: e:timeout('timed out',)",)
Jun 02 14:40:34.737 [gae_proxy][DEBUG] report_connect_fail:2a00:1450:4007:7::a
Jun 02 14:40:34.741 [gae_proxy][DEBUG] connect 2a00:1450:4007:7::a fail:error("conn fail, sni:black-abode-187110.appspot.com, top:black-abode-187110.appspot.com e:timeout('timed out',)",)
Jun 02 14:40:37.893 [gae_proxy][DEBUG] report_connect_fail IPv6 continue_fail_count:11
Jun 02 14:40:37.897 [gae_proxy][DEBUG] report_connect_fail:2404:6800:400e:8::7
Jun 02 14:40:37.898 [gae_proxy][DEBUG] connect 2404:6800:400e:8::7 fail:error("conn fail, sni:power-miss.ml, top: e:timeout('timed out',)",)
Jun 02 14:40:41.749 [gae_proxy][DEBUG] report_connect_fail IPv6 continue_fail_count:12
Jun 02 14:40:41.750 [gae_proxy][DEBUG] report_connect_fail:2a00:1450:4003:10::9
Jun 02 14:40:41.751 [gae_proxy][DEBUG] connect 2a00:1450:4003:10::9 fail:error("conn fail, sni:wooden4-179903.appspot.com, top:wooden4-179903.appspot.com e:timeout('timed out',)",)
Jun 02 14:40:44.905 [gae_proxy][DEBUG] report_connect_fail IPv6 continue_fail_count:13
Jun 02 14:40:44.908 [gae_proxy][DEBUG] report_connect_fail:2404:4408:5:5100::11
Jun 02 14:40:44.911 [gae_proxy][DEBUG] connect 2404:4408:5:5100::11 fail:error("conn fail, sni:teamproposal.ml, top: e:timeout('timed out',)",)
Jun 02 14:40:48.758 [gae_proxy][DEBUG] report_connect_fail IPv6 continue_fail_count:14
Jun 02 14:40:48.760 [gae_proxy][DEBUG] report_connect_fail:2a00:1450:4003:d::c
Jun 02 14:40:48.762 [gae_proxy][DEBUG] connect 2a00:1450:4003:d::c fail:error("conn fail, sni:xxnet-1028.appspot.com, top:xxnet-1028.appspot.com e:timeout('timed out',)",)
Jun 02 14:40:51.918 [gae_proxy][DEBUG] report_connect_fail IPv6 continue_fail_count:15
Jun 02 14:40:51.922 [gae_proxy][DEBUG] report_connect_fail:2001:4220:0:1::e
Jun 02 14:40:51.923 [gae_proxy][DEBUG] connect 2001:4220:0:1::e fail:error("conn fail, sni:professionalpaintingdrawing.com, top: e:timeout('timed out',)",)
Jun 02 14:40:55.770 [gae_proxy][DEBUG] report_connect_fail IPv6 continue_fail_count:16
Jun 02 14:40:55.773 [gae_proxy][DEBUG] report_connect_fail:2804:7f7:f000:cace::d
Jun 02 14:40:55.775 [gae_proxy][DEBUG] connect 2804:7f7:f000:cace::d fail:error("conn fail, sni:xxnet-38584.appspot.com, top:xxnet-38584.appspot.com e:timeout('timed out',)",)
Jun 02 14:40:58.931 [gae_proxy][DEBUG] report_connect_fail IPv6 continue_fail_count:17
Jun 02 14:40:58.934 [gae_proxy][DEBUG] report_connect_fail:2001:d08:12:a003::13
Jun 02 14:40:58.938 [gae_proxy][DEBUG] connect 2001:d08:12:a003::13 fail:error("conn fail, sni:affair.database.ladder.ml, top: e:timeout('timed out',)",)
Jun 02 14:41:02.785 [gae_proxy][DEBUG] report_connect_fail IPv6 continue_fail_count:18
Jun 02 14:41:02.786 [gae_proxy][DEBUG] report_connect_fail:2001:660:302a:1::d
Jun 02 14:41:02.788 [gae_proxy][DEBUG] connect 2001:660:302a:1::d fail:error("conn fail, sni:xxnet-enaihei-c.appspot.com, top:xxnet-enaihei-c.appspot.com e:timeout('timed out',)",)
Jun 02 14:41:05.946 [gae_proxy][DEBUG] report_connect_fail IPv6 continue_fail_count:19
Jun 02 14:41:05.949 [gae_proxy][DEBUG] report_connect_fail:2001:b032:8101::d
Jun 02 14:41:05.952 [gae_proxy][DEBUG] connect 2001:b032:8101::d fail:error("conn fail, sni:money.hope.preparation.com, top: e:timeout('timed out',)",)
Jun 02 14:41:09.794 [gae_proxy][DEBUG] report_connect_fail IPv6 continue_fail_count:20
Jun 02 14:41:09.796 [gae_proxy][DEBUG] report_connect_fail:2607:f798:14:41::f
Jun 02 14:41:09.797 [gae_proxy][DEBUG] connect 2607:f798:14:41::f fail:error("conn fail, sni:weipo1998.appspot.com, top:weipo1998.appspot.com e:timeout('timed out',)",)
Jun 02 14:41:12.962 [gae_proxy][DEBUG] report_connect_fail IPv6 continue_fail_count:21
Jun 02 14:41:12.963 [gae_proxy][DEBUG] report_connect_fail:2620:11a:a012:2::12
Jun 02 14:41:12.963 [gae_proxy][DEBUG] connect 2620:11a:a012:2::12 fail:error("conn fail, sni:whereas.union.bonus.org, top: e:timeout('timed out',)",)
Jun 02 14:41:16.805 [gae_proxy][DEBUG] report_connect_fail IPv6 continue_fail_count:22
Jun 02 14:41:16.808 [gae_proxy][DEBUG] report_connect_fail:2620:11a:a01a::19
Jun 02 14:41:16.809 [gae_proxy][DEBUG] connect 2620:11a:a01a::19 fail:error("conn fail, sni:ringed-spot-132123.appspot.com, top:ringed-spot-132123.appspot.com e:timeout('timed out',)",)
Jun 02 14:41:19.969 [gae_proxy][DEBUG] report_connect_fail IPv6 continue_fail_count:23
Jun 02 14:41:19.970 [gae_proxy][DEBUG] report_connect_fail:2600:5:100:1::d
Jun 02 14:41:19.971 [gae_proxy][DEBUG] connect 2600:5:100:1::d fail:error("conn fail, sni:response-disaster.net, top: e:timeout('timed out',)",)
Jun 02 14:41:23.816 [gae_proxy][DEBUG] report_connect_fail IPv6 continue_fail_count:24
Jun 02 14:41:23.818 [gae_proxy][DEBUG] report_connect_fail:2001:578:2a:203::d
Jun 02 14:41:23.820 [gae_proxy][DEBUG] connect 2001:578:2a:203::d fail:error("conn fail, sni:xxnet-xy-2.appspot.com, top:xxnet-xy-2.appspot.com e:timeout('timed out',)",)
Jun 02 14:41:26.978 [gae_proxy][DEBUG] report_connect_fail IPv6 continue_fail_count:25
Jun 02 14:41:26.983 [gae_proxy][DEBUG] report_connect_fail:2001:1970:1:2053::10
Jun 02 14:41:26.984 [gae_proxy][DEBUG] connect 2001:1970:1:2053::10 fail:error("conn fail, sni:choice.traffic.ml, top: e:timeout('timed out',)",)
Jun 02 14:41:30.826 [gae_proxy][DEBUG] report_connect_fail IPv6 continue_fail_count:26
Jun 02 14:41:30.830 [gae_proxy][DEBUG] report_connect_fail:2001:4958:300:500::11
Jun 02 14:41:30.832 [gae_proxy][DEBUG] connect 2001:4958:300:500::11 fail:error("conn fail, sni:my-project-14-1332.appspot.com, top:my-project-14-1332.appspot.com e:timeout('timed out',)",)
Jun 02 14:41:33.991 [gae_proxy][DEBUG] report_connect_fail IPv6 continue_fail_count:27
Jun 02 14:41:33.994 [gae_proxy][DEBUG] report_connect_fail:2a00:1450:4003:d::18
Jun 02 14:41:33.995 [gae_proxy][DEBUG] connect 2a00:1450:4003:d::18 fail:error("conn fail, sni:time-response-reveal.us, top: e:timeout('timed out',)",)
Jun 02 14:41:37.841 [gae_proxy][DEBUG] report_connect_fail IPv6 continue_fail_count:28
Jun 02 14:41:37.843 [gae_proxy][DEBUG] report_connect_fail:2a00:1450:4003:10::7
Jun 02 14:41:37.844 [gae_proxy][DEBUG] connect 2a00:1450:4003:10::7 fail:error("conn fail, sni:xxxnet-6.appspot.com, top:xxxnet-6.appspot.com e:timeout('timed out',)",)
Jun 02 14:41:41.003 [gae_proxy][DEBUG] report_connect_fail IPv6 continue_fail_count:29
Jun 02 14:41:41.006 [gae_proxy][DEBUG] report_connect_fail:2001:d08:12:a003::13
Jun 02 14:41:41.008 [gae_proxy][DEBUG] connect 2001:d08:12:a003::13 fail:error("conn fail, sni:hopeactioncampaign.ml, top: e:timeout('timed out',)",)
Jun 02 14:41:44.851 [gae_proxy][DEBUG] report_connect_fail IPv6 continue_fail_count:30
Jun 02 14:41:44.853 [gae_proxy][DEBUG] report_connect_fail:2804:d40:82:e001::c
Jun 02 14:41:44.853 [gae_proxy][DEBUG] connect 2804:d40:82:e001::c fail:error("conn fail, sni:xxnet-foshan5.appspot.com, top:xxnet-foshan5.appspot.com e:timeout('timed out',)",)
Jun 02 14:41:48.015 [gae_proxy][DEBUG] report_connect_fail IPv6 continue_fail_count:31
Jun 02 14:41:48.022 [gae_proxy][DEBUG] report_connect_fail:2001:660:302a:1::d
Jun 02 14:41:48.023 [gae_proxy][DEBUG] connect 2001:660:302a:1::d fail:error("conn fail, sni:mealput.ml, top: e:timeout('timed out',)",)
Jun 02 14:41:51.859 [gae_proxy][DEBUG] report_connect_fail IPv6 continue_fail_count:32
Jun 02 14:41:51.866 [gae_proxy][DEBUG] report_connect_fail:2001:b032:8101::d
Jun 02 14:41:51.866 [gae_proxy][DEBUG] connect 2001:b032:8101::d fail:error("conn fail, sni:xxnet-iceliquid3.appspot.com, top:xxnet-iceliquid3.appspot.com e:timeout('timed out',)",)
Jun 02 14:41:55.031 [gae_proxy][DEBUG] report_connect_fail IPv6 continue_fail_count:33
Jun 02 14:41:55.034 [gae_proxy][DEBUG] report_connect_fail:2620:11a:a01a::19
Jun 02 14:41:55.036 [gae_proxy][DEBUG] connect 2620:11a:a01a::19 fail:error("conn fail, sni:section.review.org, top: e:timeout('timed out',)",)
Jun 02 14:41:58.883 [gae_proxy][DEBUG] report_connect_fail IPv6 continue_fail_count:34
Jun 02 14:41:58.885 [gae_proxy][DEBUG] report_connect_fail:2001:d08:12:a003::13

**Comment by SeaHOH** [comment]
你这个情况跟 mac 的不一样。
把所有包含 python 的进程全部杀掉，再重新运行即可。

**Comment by lanmanpop** [comment]
谢谢 可以打开了
