### ISSUE TITLE
关于php模块无法连接的问题

### ISSUE THREAD

**Issue by forver8023** [XX-net/XX-Net#1094]
我在一个日本的免费空间上面上传了服务端，用xxnet连接一切正常速度很快，可是我的笔记本重启之后却再也无法连接，但是可以使用我的另一个美国收费空间。
探针：jiangxin.webcrow.jp/tz.php
下面是xxnet日志的红色错误部分
Sep 22 18:48:52 - [ERROR] ssl.wrap_socket(connection=) failed: [Errno 8] _ssl.c:507: EOF occurred in violation of protocol
Sep 22 18:48:52 - [ERROR] Except stack:Traceback (most recent call last):
File "C:\Users\jx\Documents\XX-Net-2.3.0\php_proxy\local\proxylib.py", line 726, in handle
self.do_ssl_handshake(handler)
File "C:\Users\jx\Documents\XX-Net-2.3.0\php_proxy\local\proxylib.py", line 713, in do_ssl_handshake
ssl_sock = ssl.wrap_socket(handler.connection, keyfile=certfile, certfile=certfile, server_side=True, ssl_version=self.ssl_method, ciphers=self.ciphers)
File "C:\Users\jx\Documents\XX-Net-2.3.0\python27\1.0\lib\win32\gevent\ssl.py", line 383, in wrap_socket
ciphers=ciphers)
File "C:\Users\jx\Documents\XX-Net-2.3.0\python27\1.0\lib\win32\gevent\ssl.py", line 94, in __init__
self.do_handshake()
File "C:\Users\jx\Documents\XX-Net-2.3.0\python27\1.0\lib\win32\gevent\ssl.py", line 305, in do_handshake
return self._sslobj.do_handshake()
SSLError: [Errno 8] _ssl.c:507: EOF occurred in violation of protocol

Sep 22 18:48:52 - [INFO] 127.0.0.1:64235 "STRIP CONNECT www.google.com.hk:443 HTTP/1.1" - -
Sep 22 18:48:54 - [ERROR]LOG_EXCEPT: ssl.wrap_socket(connection=) failed: [Errno 8] _ssl.c:507: EOF occurred in violation of protocol, Except:[Errno 9] Bad file descriptor
Sep 22 18:48:54 - [ERROR] Except stack:Traceback (most recent call last):
File "C:\Users\jx\Documents\XX-Net-2.3.0\php_proxy\local\proxylib.py", line 726, in handle
self.do_ssl_handshake(handler)
File "C:\Users\jx\Documents\XX-Net-2.3.0\php_proxy\local\proxylib.py", line 713, in do_ssl_handshake
ssl_sock = ssl.wrap_socket(handler.connection, keyfile=certfile, certfile=certfile, server_side=True, ssl_version=self.ssl_method, ciphers=self.ciphers)
File "C:\Users\jx\Documents\XX-Net-2.3.0\python27\1.0\lib\win32\gevent\ssl.py", line 383, in wrap_socket
ciphers=ciphers)
File "C:\Users\jx\Documents\XX-Net-2.3.0\python27\1.0\lib\win32\gevent\ssl.py", line 94, in __init__
self.do_handshake()
File "C:\Users\jx\Documents\XX-Net-2.3.0\python27\1.0\lib\win32\gevent\ssl.py", line 305, in do_handshake
return self._sslobj.do_handshake()
SSLError: [Errno 8] _ssl.c:507: EOF occurred in violation of protocol

Sep 22 18:48:55 - [ERROR] ssl.wrap_socket(connection=) failed: [Errno 8] _ssl.c:507: EOF occurred in violation of protocol
Sep 22 18:48:55 - [ERROR] Except stack:Traceback (most recent call last):
File "C:\Users\jx\Documents\XX-Net-2.3.0\php_proxy\local\proxylib.py", line 726, in handle
self.do_ssl_handshake(handler)
File "C:\Users\jx\Documents\XX-Net-2.3.0\php_proxy\local\proxylib.py", line 713, in do_ssl_handshake
ssl_sock = ssl.wrap_socket(handler.connection, keyfile=certfile, certfile=certfile, server_side=True, ssl_version=self.ssl_method, ciphers=self.ciphers)
File "C:\Users\jx\Documents\XX-Net-2.3.0\python27\1.0\lib\win32\gevent\ssl.py", line 383, in wrap_socket

**Comment by xxnet** [comment]
似乎是 php模块的证书没有倒入
  data/php_proxy/CA.crt

2015-09-22 18:52 GMT+08:00 forver8023 <notifications@github.com>:

**Comment by forver8023** [comment]
我已经导入了，然而并没有效果。刚安装好的时候是能正常连接的，现在chrome下方提示正在连接到代理隧道，然后什么都加载不出来。

如果是证书问题我觉得还是能加载出类似“访问的网站不安全”之类的内容

**Comment by xxnet** [comment]
试试换个浏览器，排查是不是浏览器对ssl的要求不同

在 2015年9月25日 下午6:14，forver8023 <notifications@github.com>写道：
