### ISSUE TITLE
启动的时候 提示有全局变量trycrypt32 未定义

### ISSUE THREAD

**Issue by wry-bill** [XX-net/XX-Net#10979]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases)？

没有
* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki)？

有
* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：
启动的时候 提示有全局变量trycrypt32 未定义
Exception in thread Thread-3:
Traceback (most recent call last):
  File "D:\xxnet\XX-Net\code\default\python27\1.0\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "D:\xxnet\XX-Net\code\default\python27\1.0\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "D:\xxnet\XX-Net\code\default\gae_proxy\start.py", line 18, in main
    client.main(args)
  File "D:\xxnet\XX-Net\code\default\gae_proxy\local\proxy.py", line 118, in main
    CertUtil.init_ca()
  File "D:\xxnet\XX-Net\code\default\gae_proxy\local\cert_util.py", line 565, in init_ca
    CertUtil.import_ca(CertUtil.ca_keyfile)
  File "D:\xxnet\XX-Net\code\default\gae_proxy\local\cert_util.py", line 469, in import_ca
    CertUtil.import_windows_ca(certfile)
  File "D:\xxnet\XX-Net\code\default\gae_proxy\local\cert_util.py", line 287, in import_windows_ca
    trycrypt32.CertFreeCertificateContext(pCertCtx)
NameError: global name 'trycrypt32' is not defined

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by SeaHOH** [comment]
已修复
