### ISSUE TITLE
智能路由代理会导致QQ邮箱上传附件失败

### ISSUE THREAD

**Issue by imba-tjd** [XX-net/XX-Net#10998]
![default](https://user-images.githubusercontent.com/24759802/41817099-d10b6464-77c6-11e8-841f-9417d132b945.png)

全局和关闭都可以成功，智能路由失败并且我个人可复现，上一个稳定版也有此现象。

状态：
```
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.17134
os-system: Windows
os-version: 10.0.17134
os-release: 10
os-detail: Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0
xxnet-version: 3.12.2
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:500 ipv4:0 ipv6:83
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:undefined
worker: h1:47 h2:0
scan-ip-thread-num: 5
ip-quality: 973
is-idle: 0
block-stat: undefined
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false
```
智能路由的日志：
```
Jun 24 15:59:10.439 - [ERROR] Except stack:Traceback (most recent call last): File "C:\Users\省略\AppData\Roaming\XX-Net\code\3.12.2\smart_router\local\smart_route.py", line 374, in try_loop do_gae(sock, host, port, client_address, left_buf) File "C:\Users\省略\AppData\Roaming\XX-Net\code\3.12.2\smart_router\local\smart_route.py", line 295, in do_gae leadbyte = sock.recv(1, socket.MSG_PEEK) File "C:\Users\imbat\AppData\Roaming\XX-Net\code\3.12.2\smart_router\local\socket_wrap.py", line 36, in recv d = self._sock.recv(bufsiz, flags) error: [Errno 10053] 
```
GAEProxy的日志太复杂，跟扫ip的混在一起……我看不出哪里是重点，就不发了。

**Comment by SeaHOH** [comment]
@xxnet 
怎么看都没发现毛病，最后想到 IP 解析可能不对。
直连是不是该使用 direct_query ？
https://github.com/XX-net/XX-Net/blob/bdc8be07ef97bf3beb00faa4e375fb4aae0e6694/code/default/smart_router/local/smart_route.py#L351-L361

**Comment by yeezylife** [comment]
不光是QQ邮箱啦 我优酷 bili传视频  百度盘传文件，只要是智能路由模式就会失败 中断

**Comment by SeaHOH** [comment]
收到，我再看看。

**Comment by xxnet** [comment]
​

智能路由的日志：

Jun 24 15:59:10.439 - [ERROR] Except stack:Traceback (most recent call
last): File "C:\Users\省略\AppData\Roaming\XX-Net\code\3.12.2\smart_router\local\smart_route.py",
line 374, in try_loop do_gae(sock, host, port, client_address,
left_buf) File "C:\Users\省略\AppData\Roaming\XX-Net\code\3.12.2\smart_router\local\smart_route.py",
line 295, in do_gae leadbyte = sock.recv(1, socket.MSG_PEEK) File
"C:\Users\imbat\AppData\Roaming\XX-Net\code\3.12.2\smart_router\local\socket_wrap.py",
line 36, in recv d = self._sock.recv(bufsiz, flags) error: [Errno
10053]


这段日志说明跑到GAE模式去了。

而且读取第一个字符时出错，还没有try。

先加个try上去好了

**Comment by SeaHOH** [comment]
客户端断开这个错误忽略不了吧，后面还会继续触发。
而且已经断开了，原因肯定不在这里。

**Comment by xxnet** [comment]
​@谭九鼎
可以在浏览器里按F12，找到异常的请求。
对比智能路由的日志。

**Comment by imba-tjd** [comment]
嗯……pip也不能用

**Comment by SeaHOH** [comment]
不支持通配符，而且还没修复。
