### ISSUE TITLE
XXnet启动不了

### ISSUE THREAD

**Issue by 102464** [XX-net/XX-Net#11000]
ubuntu@ubuntu-iMac:~/桌面$ /etc/rc.local
XX-Net version:3.12.2
ubuntu@ubuntu-iMac:~/桌面$ Gtk-Message: 17:40:31.987: Failed to load module "canberra-gtk-module"
6月 24 17:40:32.00 [launcher][INFO] Using PyGTK as the GUI Backend.
6月 24 17:40:32.03 [launcher][INFO] Gtk.StatusIcon used.
6月 24 17:40:32.04 [launcher][INFO] import build-in openssl fail:AttributeError("'module' object has no attribute 'SSL_ST_INIT'",)
6月 24 17:40:32.08 [launcher][INFO] start XX-Net 3.12.2
6月 24 17:40:32.08 [launcher][DEBUG] start confirm_xxnet_exit
6月 24 17:40:32.08 [launcher][DEBUG] good, xxnet:8085 clear!
6月 24 17:40:32.08 [launcher][DEBUG] finished confirm_xxnet_exit
6月 24 17:40:32.11 [gae_proxy][INFO] ------------------------------------------------------
6月 24 17:40:32.11 [gae_proxy][INFO] Python Version     : 2.7.15rc1
6月 24 17:40:32.11 [gae_proxy][INFO] OS                 : Dist:Ubuntu; Version:18.04; ID:bionic
6月 24 17:40:32.11 [gae_proxy][INFO] Listen Address     : 127.0.0.1:8087
6月 24 17:40:32.11 [gae_proxy][INFO] Using public APPID
6月 24 17:40:32.11 [gae_proxy][INFO] ------------------------------------------------------
6月 24 17:40:32.11 [gae_proxy][DEBUG] Importing CA
6月 24 17:40:32.12 [gae_proxy][INFO] Database $HOME/.pki/nssdb cert exist
6月 24 17:40:32.12 [gae_proxy][DEBUG] Begin importing CA to Firefox
6月 24 17:40:32.12 [gae_proxy][INFO] Removing old cert to Firefox in /home/ubuntu/.mozilla/firefox/4e6elacg.default
GoAgent XX-Net - GoAgent                                     C,,  
6月 24 17:40:32.13 [gae_proxy][INFO] Add new cert to Firefox in /home/ubuntu/.mozilla/firefox/4e6elacg.default
6月 24 17:40:32.14 [gae_proxy][INFO] SSL use version:TLSv1_2
6月 24 17:40:32.14 [gae_proxy][INFO] OpenSSL support alpn
6月 24 17:40:32.14 [gae_proxy][INFO] load ip range file:/home/ubuntu/桌面/XX-Net-3.12.2/code/default/gae_proxy/local/ip_range.txt
6月 24 17:40:32.14 [gae_proxy][INFO] SSL use version:TLSv1_2
6月 24 17:40:32.14 [gae_proxy][INFO] server 127.0.0.1:8087 started.
6月 24 17:40:32.21 [launcher][INFO] module gae_proxy started
6月 24 17:40:32.21 [launcher][INFO] start gae_proxy time cost:133 ms
6月 24 17:40:32.23 [launcher][ERROR] start module x_tunnel fail:version mismatch, 1.11.5 != 1.4.2
6月 24 17:40:32.23 [launcher][ERROR] Except stack:Traceback (most recent call last):
  File "/home/ubuntu/桌面/XX-Net-3.12.2/code/default/launcher/module_init.py", line 40, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "/home/ubuntu/桌面/XX-Net-3.12.2/code/default/x_tunnel/start.py", line 14, in <module>
    import local.client as client
  File "/home/ubuntu/桌面/XX-Net-3.12.2/code/default/x_tunnel/local/client.py", line 38, in <module>
    from proxy_handler import Socks5Server
  File "/home/ubuntu/桌面/XX-Net-3.12.2/code/default/x_tunnel/local/proxy_handler.py", line 12, in <module>
    import proxy_session
  File "/home/ubuntu/桌面/XX-Net-3.12.2/code/default/x_tunnel/local/proxy_session.py", line 11, in <module>
    import encrypt
  File "/home/ubuntu/桌面/XX-Net-3.12.2/code/default/python27/1.0/lib/noarch/encrypt.py", line 169, in <module>
    from Crypto.Cipher.ARC4 import new as RC4Cipher
  File "/usr/local/lib/python2.7/dist-packages/Crypto/Cipher/__init__.py", line 27, in <module>
    from Crypto.Cipher._mode_ecb import _create_ecb_cipher
  File "/usr/local/lib/python2.7/dist-packages/Crypto/Cipher/_mode_ecb.py", line 29, in <module>
    from Crypto.Util._raw_api import (load_pycryptodome_raw_lib,
  File "/usr/local/lib/python2.7/dist-packages/Crypto/Util/_raw_api.py", line 61, in <module>
    ffi = FFI()
  File "/home/ubuntu/桌面/XX-Net-3.12.2/code/default/python27/1.0/lib/linux/cffi/api.py", line 59, in __init__
    "version mismatch, %s != %s" % (backend.__version__, __version__)
AssertionError: version mismatch, 1.11.5 != 1.4.2

6月 24 17:40:32.23 [launcher][ERROR] launcher except:AssertionError('version mismatch, 1.11.5 != 1.4.2',)
6月 24 17:40:32.23 [launcher][ERROR] Except stack:Traceback (most recent call last):
  File "code/default/launcher/start.py", line 247, in <module>
  File "code/default/launcher/start.py", line 226, in main
  File "/home/ubuntu/桌面/XX-Net-3.12.2/code/default/launcher/module_init.py", line 113, in start_all_auto
    start(module)
  File "/home/ubuntu/桌面/XX-Net-3.12.2/code/default/launcher/module_init.py", line 40, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "/home/ubuntu/桌面/XX-Net-3.12.2/code/default/x_tunnel/start.py", line 14, in <module>
    import local.client as client
  File "/home/ubuntu/桌面/XX-Net-3.12.2/code/default/x_tunnel/local/client.py", line 38, in <module>
    from proxy_handler import Socks5Server
  File "/home/ubuntu/桌面/XX-Net-3.12.2/code/default/x_tunnel/local/proxy_handler.py", line 12, in <module>
    import proxy_session
  File "/home/ubuntu/桌面/XX-Net-3.12.2/code/default/x_tunnel/local/proxy_session.py", line 11, in <module>
    import encrypt
  File "/home/ubuntu/桌面/XX-Net-3.12.2/code/default/python27/1.0/lib/noarch/encrypt.py", line 169, in <module>
    from Crypto.Cipher.ARC4 import new as RC4Cipher
  File "/usr/local/lib/python2.7/dist-packages/Crypto/Cipher/__init__.py", line 27, in <module>
    from Crypto.Cipher._mode_ecb import _create_ecb_cipher
  File "/usr/local/lib/python2.7/dist-packages/Crypto/Cipher/_mode_ecb.py", line 29, in <module>
    from Crypto.Util._raw_api import (load_pycryptodome_raw_lib,
  File "/usr/local/lib/python2.7/dist-packages/Crypto/Util/_raw_api.py", line 61, in <module>
    ffi = FFI()
  File "/home/ubuntu/桌面/XX-Net-3.12.2/code/default/python27/1.0/lib/linux/cffi/api.py", line 59, in __init__
    "version mismatch, %s != %s" % (backend.__version__, __version__)
AssertionError: version mismatch, 1.11.5 != 1.4.2

Press Enter to continue...('uncaught Exception:', <type 'exceptions.EOFError'>, EOFError('EOF when reading a line',), <traceback object at 0x7fb350c0d050>)
6月 24 17:40:32.23 [launcher][ERROR] uncaught Exception, type=<type 'exceptions.EOFError'> value=EOF when reading a line traceback:<traceback object at 0x7fb350c0d050>
6月 24 17:40:32.28 [gae_proxy][DEBUG] network IPv4 is ok, cost:196 ms
6月 24 17:40:33.14 [gae_proxy][WARNING] not enough ip
6月 24 17:40:33.42 [gae_proxy][DEBUG] network IPv6 is ok, cost:1343 ms
Stopping all modules before exit!
6月 24 17:40:33.42 [launcher][DEBUG] start to terminate gae_proxy module
6月 24 17:40:33.42 [gae_proxy][INFO] start to terminate GAE_Proxy
6月 24 17:40:33.42 [gae_proxy][INFO] terminate
6月 24 17:40:33.42 [gae_proxy][INFO] terminate
6月 24 17:40:33.42 [launcher][DEBUG] module gae_proxy stopping
6月 24 17:40:33.42 [launcher][INFO] module gae_proxy stopped
6月 24 17:40:33.42 [launcher][ERROR] stop module x_tunnel fail:'imp'
6月 24 17:40:33.42 [launcher][ERROR] Except stack:Traceback (most recent call last):
  File "/home/ubuntu/桌面/XX-Net-3.12.2/code/default/launcher/module_init.py", line 74, in stop
    _start = proc_handler[module]["imp"].start
KeyError: 'imp'

6月 24 17:40:33.42 [launcher][INFO] begin to exit web control
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "code/default/launcher/start.py", line 194, in exit_handler
  File "/home/ubuntu/桌面/XX-Net-3.12.2/code/default/launcher/web_control.py", line 702, in stop
    server.shutdown()
AttributeError: 'NoneType' object has no attribute 'shutdown'
Error in sys.exitfunc:
('uncaught Exception:', <type 'exceptions.AttributeError'>, AttributeError("'NoneType' object has no attribute 'shutdown'",), <traceback object at 0x7fb350c6cbd8>)
6月 24 17:40:33.43 [launcher][ERROR] uncaught Exception, type=<type 'exceptions.AttributeError'> value='NoneType' object has no attribute 'shutdown' traceback:<traceback object at 0x7fb350c6cbd8>

**Comment by 102464** [comment]
没有用啊，还是老样子
root@ubuntu-iMac:/home/ubuntu/桌面# wget https://codeload.github.com/XX-net/XX-Net/zip/3.12.2
--2018-06-25 20:01:11--  https://codeload.github.com/XX-net/XX-Net/zip/3.12.2
Resolving codeload.github.com (codeload.github.com)... 13.229.189.0, 13.250.162.133, 54.251.140.56
Connecting to codeload.github.com (codeload.github.com)|13.229.189.0|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 13478138 (13M) [application/zip]
Saving to: ‘3.12.2’

3.12.2              100%[===================>]  12.85M  1.22MB/s    in 12s     

2018-06-25 20:01:25 (1.09 MB/s) - ‘3.12.2’ saved [13478138/13478138]

root@ubuntu-iMac:/home/ubuntu/桌面# rm -rf XX-Net-3.12.2/
root@ubuntu-iMac:/home/ubuntu/桌面# unzip 3.12.2 
Archive:  3.12.2
2d1b7fe74996b8badeed548eef4ce14f543b109e
   creating: XX-Net-3.12.2/
   creating: XX-Net-3.12.2/.github/
  inflating: XX-Net-3.12.2/.github/ISSUE_TEMPLATE.md  
  inflating: XX-Net-3.12.2/.gitignore  
  inflating: XX-Net-3.12.2/README.md  
   creating: XX-Net-3.12.2/SwitchyOmega/
  inflating: XX-Net-3.12.2/SwitchyOmega/AutoProxy.xpi  
  inflating: XX-Net-3.12.2/SwitchyOmega/OmegaOptions.bak  
  inflating: XX-Net-3.12.2/SwitchyOmega/SwitchyOmega.crx  
 extracting: XX-Net-3.12.2/SwitchyOmega/download SwitchyOmega for Chromium & Firefox.url  
   creating: XX-Net-3.12.2/code/
......
  inflating: XX-Net-3.12.2/code/default/x_tunnel/web_ui/tls_relay_front_logging.html  
 extracting: XX-Net-3.12.2/code/version.txt  
  inflating: XX-Net-3.12.2/start     
 extracting: XX-Net-3.12.2/start.bat  
  inflating: XX-Net-3.12.2/start.vbs  
  inflating: XX-Net-3.12.2/xx_net.sh  
root@ubuntu-iMac:/home/ubuntu/桌面# /etc/rc.local 
XX-Net version:3.12.2
root@ubuntu-iMac:/home/ubuntu/桌面# Gtk-Message: 20:02:02.910: Failed to load module "canberra-gtk-module"
6月 25 20:02:02.93 [launcher][INFO] Using PyGTK as the GUI Backend.
6月 25 20:02:03.01 [launcher][INFO] Gtk.StatusIcon used.
6月 25 20:02:03.05 [launcher][INFO] import build-in openssl fail:AttributeError("'module' object has no attribute 'SSL_ST_INIT'",)
6月 25 20:02:03.08 [launcher][INFO] start XX-Net 3.12.2
6月 25 20:02:03.08 [launcher][DEBUG] start confirm_xxnet_exit
6月 25 20:02:03.08 [launcher][DEBUG] good, xxnet:8085 clear!
6月 25 20:02:03.08 [launcher][DEBUG] finished confirm_xxnet_exit
6月 25 20:02:03.20 [gae_proxy][INFO] ------------------------------------------------------
6月 25 20:02:03.20 [gae_proxy][INFO] Python Version     : 2.7.15rc1
6月 25 20:02:03.20 [gae_proxy][INFO] OS                 : Dist:Ubuntu; Version:18.04; ID:bionic
6月 25 20:02:03.20 [gae_proxy][INFO] Listen Address     : 127.0.0.1:8087
6月 25 20:02:03.20 [gae_proxy][INFO] Using public APPID
6月 25 20:02:03.20 [gae_proxy][INFO] ------------------------------------------------------
6月 25 20:02:03.20 [gae_proxy][INFO] no GAE CA file exist in XX-Net data dir
6月 25 20:02:03.21 [gae_proxy][INFO] clean old site certs in XX-Net cert dir
6月 25 20:02:03.21 [gae_proxy][INFO] generate CA file:/home/ubuntu/桌面/XX-Net-3.12.2/data/gae_proxy/CAkey.pem
6月 25 20:02:03.23 [gae_proxy][INFO] create CA
6月 25 20:02:03.23 [gae_proxy][INFO] generate certs's key file:/home/ubuntu/桌面/XX-Net-3.12.2/data/gae_proxy/Certkey.pem
6月 25 20:02:03.33 [gae_proxy][DEBUG] network IPv4 is ok, cost:236 ms
6月 25 20:02:03.33 [gae_proxy][DEBUG] Importing CA
6月 25 20:02:03.33 [gae_proxy][DEBUG] Begin importing CA to Firefox
6月 25 20:02:03.33 [gae_proxy][INFO] SSL use version:TLSv1_2
6月 25 20:02:03.33 [gae_proxy][INFO] OpenSSL support alpn
6月 25 20:02:03.33 [gae_proxy][INFO] load ip range file:/home/ubuntu/桌面/XX-Net-3.12.2/code/default/gae_proxy/local/ip_range.txt
6月 25 20:02:03.34 [gae_proxy][INFO] SSL use version:TLSv1_2
6月 25 20:02:03.34 [gae_proxy][INFO] server 127.0.0.1:8087 started.
6月 25 20:02:03.40 [launcher][INFO] module gae_proxy started
6月 25 20:02:03.41 [launcher][INFO] start gae_proxy time cost:318 ms
6月 25 20:02:03.45 [launcher][ERROR] start module x_tunnel fail:version mismatch, 1.11.5 != 1.4.2
6月 25 20:02:03.45 [launcher][ERROR] Except stack:Traceback (most recent call last):
  File "/home/ubuntu/桌面/XX-Net-3.12.2/code/default/launcher/module_init.py", line 40, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "/home/ubuntu/桌面/XX-Net-3.12.2/code/default/x_tunnel/start.py", line 14, in <module>
    import local.client as client
  File "/home/ubuntu/桌面/XX-Net-3.12.2/code/default/x_tunnel/local/client.py", line 38, in <module>
    from proxy_handler import Socks5Server
  File "/home/ubuntu/桌面/XX-Net-3.12.2/code/default/x_tunnel/local/proxy_handler.py", line 12, in <module>
    import proxy_session
  File "/home/ubuntu/桌面/XX-Net-3.12.2/code/default/x_tunnel/local/proxy_session.py", line 11, in <module>
    import encrypt
  File "/home/ubuntu/桌面/XX-Net-3.12.2/code/default/python27/1.0/lib/noarch/encrypt.py", line 169, in <module>
    from Crypto.Cipher.ARC4 import new as RC4Cipher
  File "/usr/local/lib/python2.7/dist-packages/Crypto/Cipher/__init__.py", line 27, in <module>
    from Crypto.Cipher._mode_ecb import _create_ecb_cipher
  File "/usr/local/lib/python2.7/dist-packages/Crypto/Cipher/_mode_ecb.py", line 29, in <module>
    from Crypto.Util._raw_api import (load_pycryptodome_raw_lib,
  File "/usr/local/lib/python2.7/dist-packages/Crypto/Util/_raw_api.py", line 61, in <module>
    ffi = FFI()
  File "/home/ubuntu/桌面/XX-Net-3.12.2/code/default/python27/1.0/lib/linux/cffi/api.py", line 59, in __init__
    "version mismatch, %s != %s" % (backend.__version__, __version__)
AssertionError: version mismatch, 1.11.5 != 1.4.2

6月 25 20:02:03.45 [launcher][ERROR] launcher except:AssertionError('version mismatch, 1.11.5 != 1.4.2',)
6月 25 20:02:03.45 [launcher][ERROR] Except stack:Traceback (most recent call last):
  File "code/default/launcher/start.py", line 247, in <module>
  File "code/default/launcher/start.py", line 226, in main
  File "/home/ubuntu/桌面/XX-Net-3.12.2/code/default/launcher/module_init.py", line 113, in start_all_auto
    start(module)
  File "/home/ubuntu/桌面/XX-Net-3.12.2/code/default/launcher/module_init.py", line 40, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "/home/ubuntu/桌面/XX-Net-3.12.2/code/default/x_tunnel/start.py", line 14, in <module>
    import local.client as client
  File "/home/ubuntu/桌面/XX-Net-3.12.2/code/default/x_tunnel/local/client.py", line 38, in <module>
    from proxy_handler import Socks5Server
  File "/home/ubuntu/桌面/XX-Net-3.12.2/code/default/x_tunnel/local/proxy_handler.py", line 12, in <module>
    import proxy_session
  File "/home/ubuntu/桌面/XX-Net-3.12.2/code/default/x_tunnel/local/proxy_session.py", line 11, in <module>
    import encrypt
  File "/home/ubuntu/桌面/XX-Net-3.12.2/code/default/python27/1.0/lib/noarch/encrypt.py", line 169, in <module>
    from Crypto.Cipher.ARC4 import new as RC4Cipher
  File "/usr/local/lib/python2.7/dist-packages/Crypto/Cipher/__init__.py", line 27, in <module>
    from Crypto.Cipher._mode_ecb import _create_ecb_cipher
  File "/usr/local/lib/python2.7/dist-packages/Crypto/Cipher/_mode_ecb.py", line 29, in <module>
    from Crypto.Util._raw_api import (load_pycryptodome_raw_lib,
  File "/usr/local/lib/python2.7/dist-packages/Crypto/Util/_raw_api.py", line 61, in <module>
    ffi = FFI()
  File "/home/ubuntu/桌面/XX-Net-3.12.2/code/default/python27/1.0/lib/linux/cffi/api.py", line 59, in __init__
    "version mismatch, %s != %s" % (backend.__version__, __version__)
AssertionError: version mismatch, 1.11.5 != 1.4.2

Press Enter to continue...('uncaught Exception:', <type 'exceptions.EOFError'>, EOFError('EOF when reading a line',), <traceback object at 0x7f9f834bd8c0>)
6月 25 20:02:03.45 [launcher][ERROR] uncaught Exception, type=<type 'exceptions.EOFError'> value=EOF when reading a line traceback:<traceback object at 0x7f9f834bd8c0>
6月 25 20:02:04.34 [gae_proxy][WARNING] not enough ip
6月 25 20:02:05.34 [gae_proxy][WARNING] not enough ip
6月 25 20:02:07.14 [gae_proxy][WARNING] network IPv6 fail
Stopping all modules before exit!
6月 25 20:02:07.14 [launcher][DEBUG] start to terminate gae_proxy module
6月 25 20:02:07.14 [gae_proxy][INFO] start to terminate GAE_Proxy
6月 25 20:02:07.14 [gae_proxy][INFO] terminate
6月 25 20:02:07.14 [gae_proxy][INFO] terminate
6月 25 20:02:07.14 [launcher][DEBUG] module gae_proxy stopping
6月 25 20:02:07.14 [launcher][INFO] module gae_proxy stopped
6月 25 20:02:07.14 [launcher][ERROR] stop module x_tunnel fail:'imp'
6月 25 20:02:07.14 [launcher][ERROR] Except stack:Traceback (most recent call last):
  File "/home/ubuntu/桌面/XX-Net-3.12.2/code/default/launcher/module_init.py", line 74, in stop
    _start = proc_handler[module]["imp"].start
KeyError: 'imp'

6月 25 20:02:07.14 [launcher][INFO] begin to exit web control
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "code/default/launcher/start.py", line 194, in exit_handler
  File "/home/ubuntu/桌面/XX-Net-3.12.2/code/default/launcher/web_control.py", line 702, in stop
    server.shutdown()
AttributeError: 'NoneType' object has no attribute 'shutdown'
Error in sys.exitfunc:
('uncaught Exception:', <type 'exceptions.AttributeError'>, AttributeError("'NoneType' object has no attribute 'shutdown'",), <traceback object at 0x7f9f816ab128>)
6月 25 20:02:07.14 [launcher][ERROR] uncaught Exception, type=<type 'exceptions.AttributeError'> value='NoneType' object has no attribute 'shutdown' traceback:<traceback object at 0x7f9f816ab128>

**Comment by 102464** [comment]
rc.local文件内容：
#!/bin/sh
/home/ubuntu/桌面/XX-Net-3.12.2/start &

**Comment by SeaHOH** [comment]
你下载的还是原来的错误版本，修复版本等会儿发布。

**Comment by xxnet** [comment]
​试试
rm -rf /home/ubuntu/桌面/XX-Net-3.12.2/code/default/python27/1.0/
lib/linux/cffi

或者
sudo apt install python-cffi

**Comment by SeaHOH** [comment]
cffi 最新版本也不一致，感觉上面那样修改就没啥毛病了，反正也用不到这个函数。

**Comment by SeaHOH** [comment]
你的模块路径是不是有啥特殊的设置？

**Comment by 102464** [comment]
谢谢，可以用了。
