### ISSUE TITLE
运行12.5 打开YOUTUBE提示无法访问此网站

### ISSUE THREAD

**Issue by tcwilliy** [XX-net/XX-Net#11063]
Jul 06 10:55:12.903 [gae_proxy][WARNING] DIRECT GET www.youtube.com/ except:error(10053, '')
Jul 06 10:55:12.904 [simple_http_server][ERROR] handler:NameError("global name 'errno' is not defined",) cmd:GET path:/ from:127.0.0.1:3255
Jul 06 10:55:12.905 [simple_http_server][ERROR] Except stack:Traceback (most recent call last):
  File "F:\Free\XX-Net\XX-Net-3.11.11\code\3.12.5\python27\1.0\lib\noarch\simple_http_server.py", line 166, in handle_one_request
    self.do_GET()
  File "F:\Free\XX-Net\XX-Net-3.11.11\code\3.12.5\gae_proxy\local\proxy_handler.py", line 238, in do_METHOD
    return self.go_DIRECT()
  File "F:\Free\XX-Net\XX-Net-3.11.11\code\3.12.5\gae_proxy\local\proxy_handler.py", line 273, in go_DIRECT
    if direct_handler.handler(self.command, self.host, self.path, request_headers, payload, self.wfile) != "ok":
  File "F:\Free\XX-Net\XX-Net-3.11.11\code\3.12.5\gae_proxy\local\direct_handler.py", line 101, in handler
    if e.args[0] not in (errno.ECONNABORTED, errno.ETIMEDOUT, errno.EPIPE):
NameError: global name 'errno' is not defined

**Comment by tcwilliy** [comment]
无法访问此网站
网址为 https://www.youtube.com/ 的网页可能暂时无法连接，或者它已永久性地移动到了新网址。
ERR_CONTENT_DECODING_FAILED

**Comment by tcwilliy** [comment]
google 和其他网站都没问题，就youtube 打开出现这个

**Comment by SeaHOH** [comment]
是的，忘记导入了。

**Comment by SeaHOH** [comment]
不过不应该都出错。

**Comment by SeaHOH** [comment]
先从你的自定义配置中移除`www.youtube.com`，下个版本会修复。

**Comment by 308901951** [comment]
3.12.5版用了3个小时左右出现连接池为0显示尚未连接，退出XX重新打开就恢复了，7小时内出现了2次了，估计是BUG
