### ISSUE TITLE
3.12.X mac无法运行

### ISSUE THREAD

**Issue by XueyangXu** [XX-net/XX-Net#11158]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases)？
- 是

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki)？
- 是

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：
- macos 10.13.6。XX-Net 3.11.X版本一切正常，3.12.X版本无法启动，运行start之后Python进程闪退

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by SeaHOH** [comment]
具体哪个版本开始的，是 3.12.0 吗？
把启动失败时 data\launcher 文件夹的 log 文件贴出来。

**Comment by 211Yang** [comment]
Jul 19 01:38:33.454 - [DEBUG] report_connect_fail IPv6 continue_fail_count:11

Jul 19 01:38:33.454 - [DEBUG] report_connect_fail:2607:f8b0:4012:c::c

Jul 19 01:38:33.953 - [DEBUG] connect 2607:f8b0:4012:f::f fail:timeout('timed out',)

Jul 19 01:38:33.953 - [DEBUG] report_connect_fail IPv6 continue_fail_count:12

Jul 19 01:38:33.953 - [DEBUG] report_connect_fail:2607:f8b0:4012:f::f

Jul 19 01:38:34.023 - [WARNING] network IPv6 fail

Jul 19 01:38:34.459 - [DEBUG] connect 2607:f8b0:4012:b::b fail:timeout('timed out',)

Jul 19 01:38:34.459 - [DEBUG] report_connect_fail network fail

Jul 19 01:38:34.964 - [DEBUG] connect 2607:f8b0:4012:b::e fail:timeout('timed out',)

Jul 19 01:38:35.469 - [DEBUG] connect 2404:6800:4005:11::7 fail:timeout('timed out',)

Jul 19 01:38:35.621 - [DEBUG] ip:2607:f8b0:401a:6::8 real fail

Jul 19 01:38:35.976 - [DEBUG] connect 2607:f8b0:4016:1::12 fail:timeout('timed out',)

Jul 19 01:38:36.371 - [DEBUG] connect 2607:f8b0:4012:b::15 fail:timeout('timed out',)

Jul 19 01:38:36.445 - [DEBUG] connect 2607:f8b0:4012:a::13 fail:timeout('timed out',)

Jul 19 01:38:36.949 - [DEBUG] connect 2607:f8b0:4009:37::7 fail:timeout('timed out',)

Jul 19 01:38:37.452 - [DEBUG] connect 2607:f8b0:4012:a::a fail:timeout('timed out',)

Jul 19 01:38:37.460 - [DEBUG] report_connect_fail network fail

Jul 19 01:38:37.952 - [DEBUG] connect 2607:f8b0:4016:13::9 fail:timeout('timed out',)

Jul 19 01:38:39.171 - [DEBUG] connect 2607:f8b0:4012:d::b fail:timeout('timed out',)

Jul 19 01:38:40.463 - [DEBUG] report_connect_fail network fail

Jul 19 01:38:40.627 - [DEBUG] ip:197.155.95.56 real fail

**Comment by 211Yang** [comment]
Jul 19 01:42:20.787 - [DEBUG] report_connect_fail network fail

Jul 19 01:42:23.791 - [DEBUG] report_connect_fail network fail

Jul 19 01:42:28.900 - [DEBUG] GAEProxy web_control 127.0.0.1:50078 POST /config?cmd=get_config

Jul 19 01:42:30.144 - [DEBUG] POST http://deja.com/xxnet

Jul 19 01:42:30.145 - [DEBUG] POST http://deja.com/xxnet

Jul 19 01:42:34.200 - [DEBUG] GAEProxy web_control 127.0.0.1:50078 POST /config?cmd=get_config

Jul 19 01:42:34.202 - [DEBUG] GAEProxy Web_control 127.0.0.1:50078 GET /scan_ip?cmd=get_range

Jul 19 01:42:34.202 - [INFO] load ip range file:/Users/yanglin/Downloads/XX-Net-master/code/default/gae_proxy/local/ip_range.txt

Jul 19 01:42:34.506 - [DEBUG] GAE POST https://clients1.google.com/tbproxy/af/query?client=Google%20Chrome

Jul 19 01:42:37.831 - [DEBUG] POST http://deja.com/xxnet

Jul 19 01:42:37.835 - [DEBUG] POST http://deja.com/xxnet

Jul 19 01:42:38.643 - [DEBUG] connect 2607:f8b0:4012:b::b fail:timeout('timed out',)

Jul 19 01:42:38.644 - [DEBUG] report_connect_fail network fail

Jul 19 01:42:38.747 - [DEBUG] connect 2607:f8b0:4012:b::e fail:timeout('timed out',)

Jul 19 01:42:38.844 - [DEBUG] connect 2607:f8b0:4016:1::12 fail:timeout('timed out',)

Jul 19 01:42:38.949 - [DEBUG] connect 2607:f8b0:4012:b::15 fail:timeout('timed out',)

Jul 19 01:42:39.056 - [DEBUG] connect 2404:6800:4005:11::7 fail:timeout('timed out',)

Jul 19 01:42:39.159 - [DEBUG] connect 2607:f8b0:4012:a::13 fail:timeout('timed out',)

Jul 19 01:42:39.261 - [DEBUG] connect 2607:f8b0:4009:37::7 fail:timeout('timed out',)

Jul 19 01:42:39.364 - [DEBUG] connect 2607:f8b0:4012:a::a fail:timeout('timed out',)

Jul 19 01:42:39.466 - [DEBUG] connect 2607:f8b0:4016:13::9 fail:timeout('timed out',)

Jul 19 01:42:39.569 - [DEBUG] connect 2607:f8b0:4012:d::b fail:timeout('timed out',)

Jul 19 01:42:40.900 - [DEBUG] connect 2607:f8b0:4012:c::7 fail:timeout('timed out',)

Jul 19 01:42:41.646 - [DEBUG] report_connect_fail network fail

Jul 19 01:42:44.646 - [DEBUG] report_connect_fail network fail

Jul 19 01:42:47.651 - [DEBUG] report_connect_fail network fail

Jul 19 01:42:50.654 - [DEBUG] report_connect_fail network fail

Jul 19 01:42:53.657 - [DEBUG] report_connect_fail network fail

Jul 19 01:42:56.203 - [DEBUG] create ssl timeout fail.

Jul 19 01:42:56.661 - [DEBUG] report_connect_fail network fail

Jul 19 01:42:59.661 - [DEBUG] report_connect_fail network fail

**Comment by thertno** [comment]
升级macOS最新系统后不可用了！！
XX-Net 3.12.10

Jul 19 09:59:13.174 - [INFO] use build-in openssl lib
Jul 19 09:59:13.175 - [INFO] start XX-Net 3.12.10
Jul 19 09:59:13.175 - [DEBUG] start confirm_xxnet_exit
Jul 19 09:59:13.176 - [DEBUG] good, xxnet:8085 clear!
Jul 19 09:59:13.176 - [DEBUG] finished confirm_xxnet_exit

**Comment by SeaHOH** [comment]
https://github.com/XX-net/XX-Net/issues?utf8=✓&q=is%3Aissue+mac+无法运行

**Comment by mioo** [comment]
同无法启动。

macos 10.13.6
xx-net 3.12.10

launcher log：
[ERROR] uncaught Exception, type=<type 'exceptions.EOFError'> value=EOF when reading a line traceback:<traceback object at 0x1109c4c20>

**Comment by SeaHOH** [comment]
https://github.com/XX-net/XX-Net/issues/10908#issuecomment-395627182

**Comment by mioo** [comment]
我更新一下状态描述：
重启系统可以正常启动 xx-net 并且能正常使用；状态栏手动退出 xx-net 后，无法再次启动，终端提示进程已完成，但是状态栏没有 xx-net，活动监视器里没有 xx-net 和 python 进程。
本地 py 版本 2.7.15。以下是日志。
系统重启后，跟随系统启动时的日志：

```log
Jul 19 13:04:51.863 - [INFO] use build-in openssl lib
Jul 19 13:04:51.877 - [INFO] start XX-Net 3.12.10
Jul 19 13:04:51.877 - [DEBUG] start confirm_xxnet_exit
Jul 19 13:04:51.884 - [DEBUG] good, xxnet:8085 clear!
Jul 19 13:04:51.885 - [DEBUG] finished confirm_xxnet_exit
Jul 19 13:04:51.897 - [INFO] command args:-hungup
Jul 19 13:04:56.197 - [INFO] module gae_proxy started
Jul 19 13:04:56.197 - [INFO] start gae_proxy time cost:4299 ms
Jul 19 13:04:57.657 - [INFO] module smart_router started
Jul 19 13:04:57.658 - [INFO] start smart_router time cost:1460 ms
Jul 19 13:04:57.658 - [INFO] begin to start web control
Jul 19 13:04:57.658 - [INFO] server 127.0.0.1:8085 started.
Jul 19 13:04:57.659 - [INFO] launcher web control started.
Jul 19 13:04:59.803 - [INFO] get uuid:e9824bee-7d74-41f8-a13b-1435b2d5431f
Jul 19 13:05:03.369 - [WARNING] check_update fail:BadStatusLine("''",)
Jul 19 13:05:03.370 - [INFO] download https://raw.githubusercontent.com/XX-net/XX-Net/master/code/default/update_version.txt to /Users/Messi/XX-Net/data/downloads/version.txt, retry:0
Jul 19 13:05:10.132 - [INFO] import build-in openssl fail:AttributeError("'module' object has no attribute 'SSL_ST_INIT'",)
Jul 19 13:05:10.147 - [ERROR] import system python-OpenSSL fail:AttributeError("'module' object has no attribute 'SSL_ST_INIT'",)
Jul 19 13:05:10.149 - [ERROR] Except stack:Traceback (most recent call last):
  File "code/3.12.10/launcher/start.py", line 175, in <module>
    import OpenSSL
  File "/Users/Messi/XX-Net/code/3.12.10/python27/1.0/lib/noarch/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/Users/Messi/XX-Net/code/3.12.10/python27/1.0/lib/noarch/OpenSSL/SSL.py", line 124, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'

Jul 19 13:05:10.150 - [ERROR] uncaught Exception, type=<type 'exceptions.EOFError'> value=EOF when reading a line traceback:<traceback object at 0x112537c20>
Jul 19 13:05:21.957 - [DEBUG] launcher web_control 127.0.0.1:49448 GET /config?cmd=get_version 
Jul 19 13:05:21.961 - [DEBUG] launcher web_control 127.0.0.1:49449 GET /config?cmd=get_config 
Jul 19 13:05:23.099 - [DEBUG] launcher web_control 127.0.0.1:49453 GET /update?cmd=get_progress 
Jul 19 13:05:23.101 - [DEBUG] launcher web_control 127.0.0.1:49448 GET /config?cmd=get_config 
Jul 19 13:05:23.176 - [DEBUG] launcher web_control 127.0.0.1:49449 GET /config?cmd=get_config 
Jul 19 13:05:50.112 - [DEBUG] launcher web_control 127.0.0.1:49449 GET /update?cmd=get_info 
```

手动结束 xx-net ，在终端运行 `sudo open strat` 时的日志：

```log
Jul 19 13:08:46.752 - [DEBUG] start to terminate gae_proxy module
Jul 19 13:08:46.766 - [DEBUG] module gae_proxy stopping
Jul 19 13:08:46.777 - [INFO] module gae_proxy stopped
Jul 19 13:08:46.777 - [DEBUG] start to terminate smart_router module
Jul 19 13:08:46.800 - [DEBUG] module smart_router stopping
Jul 19 13:08:46.801 - [INFO] module smart_router stopped
Jul 19 13:09:20.930 - [INFO] import build-in openssl fail:AttributeError("'module' object has no attribute 'SSL_ST_INIT'",)
Jul 19 13:09:20.938 - [ERROR] import system python-OpenSSL fail:AttributeError("'module' object has no attribute 'SSL_ST_INIT'",)
Jul 19 13:09:20.939 - [ERROR] Except stack:Traceback (most recent call last):
  File "code/3.12.10/launcher/start.py", line 175, in <module>
    import OpenSSL
  File "/Users/Messi/XX-Net/code/3.12.10/python27/1.0/lib/noarch/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/Users/Messi/XX-Net/code/3.12.10/python27/1.0/lib/noarch/OpenSSL/SSL.py", line 124, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'

Jul 19 13:09:20.940 - [ERROR] uncaught Exception, type=<type 'exceptions.EOFError'> value=EOF when reading a line traceback:<traceback object at 0x104918c20>
```

以上，希望有帮助。

**Comment by SeaHOH** [comment]
从 [cryptography 最新版](https://pypi.org/project/cryptography/#files)看到 mac 只有有 10_6 的版本了。
现在使用的是 [cryptography 1.3.1](https://pypi.org/project/cryptography/1.3.1/#files) 10_10 的版本，你们换成 10_6 试试。

**Comment by XueyangXu** [comment]
我能用了，我的解决方法是，删除全部文件保留data，下载3.11.x版本之后自动更新。

**Comment by l6270789** [comment]
任务管理器中终止所有python进程，再运行start。我就是这么解决的
