### ISSUE TITLE
Windows Server  2008系统上无法启动

### ISSUE THREAD

**Issue by xiaofanshiwo** [XX-net/XX-Net#11170]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases)？
是，已经用的最新版V 3.12.10

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki)？
是

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：

**问题：**不能启动。
**操作系统：**Windows Server  2008 标准版 SP2 32位中文版
**环境：**阿里云ECS服务器
**依赖安装：**根据安装说明，已经安装了 Visual C++ 2008 Redistributable - x86。
**现象：**双击运行start.vbs没有反应。
          双击运行start.bat，有错误打印，如下：

Jul 21 11:42:01.890 - [INFO] use build-in openssl lib
Jul 21 11:42:01.906 - [INFO] start XX-Net 3.12.10
Jul 21 11:42:01.906 - [DEBUG] start confirm_xxnet_exit
Jul 21 11:42:02.906 - [DEBUG] good, xxnet:8085 clear!
Jul 21 11:42:02.906 - [DEBUG] finished confirm_xxnet_exit
Jul 21 11:42:03.999 - [ERROR] start module gae_proxy fail:function 'OpenProcessToken' not found
Jul 21 11:42:03.999 - [ERROR] Except stack:Traceback (most recent call last):
  File "D:\XX-Net-3.12.10\code\default\launcher\module_init.py", line 40, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "D:\XX-Net-3.12.10\code\default\gae_proxy\start.py", line 13, in <module>
    import local.proxy as client
  File "D:\XX-Net-3.12.10\code\default\gae_proxy\local\proxy.py", line 86, in <module>
    import proxy_handler
  File "D:\XX-Net-3.12.10\code\default\gae_proxy\local\proxy_handler.py", line 53, in <module>
    import web_control
  File "D:\XX-Net-3.12.10\code\default\gae_proxy\local\web_control.py", line 32, in <module>
    import ipv6_tunnel
  File "D:\XX-Net-3.12.10\code\default\gae_proxy\local\ipv6_tunnel\__init__.py", line 10, in <module>
    from .win10 import state, state_pp, switch_pp, enable, disable, set_best_server
  File "D:\XX-Net-3.12.10\code\default\gae_proxy\local\ipv6_tunnel\win10.py", line 10, in <module>
    import win32elevate
  File "D:\XX-Net-3.12.10\code\default\python27\1.0\lib\win32\win32elevate.py", line 37, in <module>
    OpenProcessToken = ctypes.windll.kernel32.OpenProcessToken
  File "D:\XX-Net-3.12.10\code\default\python27\1.0\lib\ctypes\__init__.py", line 301, in __getattr__
    func = self.__getitem__(name)
  File "D:\XX-Net-3.12.10\code\default\python27\1.0\lib\ctypes\__init__.py", line 306, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'OpenProcessToken' not found

Jul 21 11:42:03.999 - [ERROR] launcher except:AttributeError("function 'OpenProcessToken' not found",)
Jul 21 11:42:03.999 - [ERROR] Except stack:Traceback (most recent call last):
  File "D:\XX-Net-3.12.10\code\default\launcher\start.py", line 251, in <module>
    main()
  File "D:\XX-Net-3.12.10\code\default\launcher\start.py", line 230, in main
    module_init.start_all_auto()
  File "D:\XX-Net-3.12.10\code\default\launcher\module_init.py", line 113, in start_all_auto
    start(module)
  File "D:\XX-Net-3.12.10\code\default\launcher\module_init.py", line 40, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "D:\XX-Net-3.12.10\code\default\gae_proxy\start.py", line 13, in <module>
    import local.proxy as client
  File "D:\XX-Net-3.12.10\code\default\gae_proxy\local\proxy.py", line 86, in <module>
    import proxy_handler
  File "D:\XX-Net-3.12.10\code\default\gae_proxy\local\proxy_handler.py", line 53, in <module>
    import web_control
  File "D:\XX-Net-3.12.10\code\default\gae_proxy\local\web_control.py", line 32, in <module>
    import ipv6_tunnel
  File "D:\XX-Net-3.12.10\code\default\gae_proxy\local\ipv6_tunnel\__init__.py", line 10, in <module>
    from .win10 import state, state_pp, switch_pp, enable, disable, set_best_server
  File "D:\XX-Net-3.12.10\code\default\gae_proxy\local\ipv6_tunnel\win10.py", line 10, in <module>
    import win32elevate
  File "D:\XX-Net-3.12.10\code\default\python27\1.0\lib\win32\win32elevate.py", line 37, in <module>
    OpenProcessToken = ctypes.windll.kernel32.OpenProcessToken
  File "D:\XX-Net-3.12.10\code\default\python27\1.0\lib\ctypes\__init__.py", line 301, in __getattr__
    func = self.__getitem__(name)
  File "D:\XX-Net-3.12.10\code\default\python27\1.0\lib\ctypes\__init__.py", line 306, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'OpenProcessToken' not found

Jul 21 11:42:08.000 - [ERROR] stop module gae_proxy fail:'imp'
Jul 21 11:42:08.000 - [ERROR] Except stack:Traceback (most recent call last):
  File "D:\XX-Net-3.12.10\code\default\launcher\module_init.py", line 74, in stop
    _start = proc_handler[module]["imp"].start
KeyError: 'imp'

Jul 21 11:42:08.000 - [INFO] begin to exit web control
Jul 21 11:42:08.000 - [ERROR] uncaught Exception, type=<type 'exceptions.AttributeError'> value='NoneType' object has no attribute 'shutdown' traceback:<traceback object at 0x01AE7AA8>

**Comment by SeaHOH** [comment]
谢谢反馈，确实没法正常运行。
不过建议你安装其它工具更方便，XX-Net 更适合于本地使用。
