### ISSUE TITLE
Mac 10.10.2 xx-net 1.7.1 ImportError: No module named Foundation

### ISSUE THREAD

**Issue by koalaroot** [XX-net/XX-Net#112]
俺不懂程序，请教如何解决，好像每个版本的xxnet在俺的Mac上都是类似的报错

launcher version: 1.2.0
Traceback (most recent call last):
  File "launcher/start.py", line 61, in <module>
    main()
  File "launcher/start.py", line 56, in main
    from start import main as launcher_main
  File "/Volumes/Macintosh HD 2/Program Files/XX-Net-1.7.1/launcher/1.2.0/start.py", line 25, in <module>
    from mac_tray import sys_tray
  File "/Volumes/Macintosh HD 2/Program Files/XX-Net-1.7.1/launcher/1.2.0/mac_tray.py", line 17, in <module>
    import rumps
  File "/Volumes/Macintosh HD 2/Program Files/XX-Net-1.7.1/python27/1.0/lib/darwin/rumps/__init__.py", line 25, in <module>
    from .rumps import (separator, debug_mode, alert, notification, application_support, timers, quit_application, timer,
  File "/Volumes/Macintosh HD 2/Program Files/XX-Net-1.7.1/python27/1.0/lib/darwin/rumps/rumps.py", line 15, in <module>
    from Foundation import (NSDate, NSTimer, NSRunLoop, NSDefaultRunLoopMode, NSSearchPathForDirectoriesInDomains,
ImportError: No module named Foundation
logout

**Comment by xxnet** [comment]
试试：
方案1：
试试 find
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python
|grep Foundation
 看看有没有存在这样一个目录，有的话试试：
export
PYTHONPATH="/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/"
再启动XX-Net
cd XX-Net
./start.sh

方案2：
sudo pip install pyobjc

2015-04-05 10:48 GMT-04:00 koalaroot <notifications@github.com>:

**Comment by laozhu999** [comment]
经过无数次的尝试，我这个门外汉用了最笨的方法搞定了。。
其实那些module都在PyObjc的文件夹里，不知道为什么没有在应该的地方，我也不懂pip，装不了，就直接copy，paste到应该的地方，少哪个就复制哪个， 搞了好几个，总算成功了。 真不知道为什么引用那些module的路径会错呢？还是module放错地方了？反正好了。 现在的问题时速度太慢。。。可以用自己的ip就好了。

**Comment by xxnet** [comment]
还记得拷贝、粘帖了哪些文件吗？
请提供更多信息

在 2015年4月7日 上午3:56，laozhu999 <notifications@github.com>写道：

**Comment by xxnet** [comment]
有遇到同样问题未解决的朋友，请帮忙提供以下信息：
find /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/ 
把信息发出来，帮助分析。

如果内容太多，可以：
find /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/ > ~/ lib.txt
让后把用户目录下的lib.txt作为附件贴上来，或发我邮箱： xxnet.dev@gmail.com
谢谢

**Comment by laozhu999** [comment]
还好有记忆，Foundation, CoreFoundation, objc, PyObjCtools. 希望别漏了。

**Comment by laozhu999** [comment]
还好有记忆，Foundation, CoreFoundation, objc, PyObjCtools. 希望别漏了。

**Comment by xxnet** [comment]
这些目录在哪里能找到？

**Comment by laozhu999** [comment]
我说过了“其实那些module都在PyObjc的文件夹里” 而这个PyObjc就在那些modue应该在的路径下。

**Comment by xxnet** [comment]
好的，谢谢

2015-04-07 5:24 GMT-04:00 laozhu999 <notifications@github.com>:

**Comment by xxnet** [comment]
1.8.1 发布
重构了Mac下的托盘实现，不再依赖 Foundation模块

请测试
