### ISSUE TITLE
windows 32位，最新版安装不能

### ISSUE THREAD

**Issue by hydramr** [XX-net/XX-Net#11269]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases)？
是

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki)？
是

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：
Aug 06 21:25:45.359 - [INFO] use build-in openssl lib
Aug 06 21:25:45.375 - [INFO] start XX-Net 3.12.10
Aug 06 21:25:45.375 - [DEBUG] start confirm_xxnet_exit
Aug 06 21:25:46.390 - [DEBUG] good, xxnet:8085 clear!
Aug 06 21:25:46.390 - [DEBUG] finished confirm_xxnet_exit
Aug 06 21:25:47.875 - [ERROR] start module gae_proxy fail:提供了一个无效的参数。
Aug 06 21:25:47.875 - [ERROR] Except stack:Traceback (most recent call last):
  File "D:\XXNet\code\default\launcher\module_init.py", line 40, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "D:\XXNet\code\default\gae_proxy\start.py", line 13, in <module>
    import local.proxy as client
  File "D:\XXNet\code\default\gae_proxy\local\proxy.py", line 86, in <module>
    import proxy_handler
  File "D:\XXNet\code\default\gae_proxy\local\proxy_handler.py", line 53, in <module>
    import web_control
  File "D:\XXNet\code\default\gae_proxy\local\web_control.py", line 32, in <module>
    import ipv6_tunnel
  File "D:\XXNet\code\default\gae_proxy\local\ipv6_tunnel\__init__.py", line 5, in <module>
    from .common import test_teredo
  File "D:\XXNet\code\default\gae_proxy\local\ipv6_tunnel\common.py", line 4, in <module>
    from .pteredor import teredo_prober
  File "D:\XXNet\code\default\gae_proxy\local\ipv6_tunnel\pteredor.py", line 96, in <module>
    class teredo_rs_packet(object):
  File "D:\XXNet\code\default\gae_proxy\local\ipv6_tunnel\pteredor.py", line 98, in teredo_rs_packet
    rs_src = socket.inet_pton(socket.AF_INET6, link_local_addr)
  File "D:\XXNet\code\default\python27\1.0\lib\win32\win_inet_pton.py", line 42, in inet_pton
    raise socket.error(ctypes.FormatError())
error: 提供了一个无效的参数。

Aug 06 21:25:47.890 - [ERROR] launcher except:error('\xcc\xe1\xb9\xa9\xc1\xcb\xd2\xbb\xb8\xf6\xce\xde\xd0\xa7\xb5\xc4\xb2\xce\xca\xfd\xa1\xa3',)
Aug 06 21:25:47.906 - [ERROR] Except stack:Traceback (most recent call last):
  File "D:\XXNet\code\default\launcher\start.py", line 251, in <module>
    main()
  File "D:\XXNet\code\default\launcher\start.py", line 230, in main
    module_init.start_all_auto()
  File "D:\XXNet\code\default\launcher\module_init.py", line 113, in start_all_auto
    start(module)
  File "D:\XXNet\code\default\launcher\module_init.py", line 40, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "D:\XXNet\code\default\gae_proxy\start.py", line 13, in <module>
    import local.proxy as client
  File "D:\XXNet\code\default\gae_proxy\local\proxy.py", line 86, in <module>
    import proxy_handler
  File "D:\XXNet\code\default\gae_proxy\local\proxy_handler.py", line 53, in <module>
    import web_control
  File "D:\XXNet\code\default\gae_proxy\local\web_control.py", line 32, in <module>
    import ipv6_tunnel
  File "D:\XXNet\code\default\gae_proxy\local\ipv6_tunnel\__init__.py", line 5, in <module>
    from .common import test_teredo
  File "D:\XXNet\code\default\gae_proxy\local\ipv6_tunnel\common.py", line 4, in <module>
    from .pteredor import teredo_prober
  File "D:\XXNet\code\default\gae_proxy\local\ipv6_tunnel\pteredor.py", line 96, in <module>
    class teredo_rs_packet(object):
  File "D:\XXNet\code\default\gae_proxy\local\ipv6_tunnel\pteredor.py", line 98, in teredo_rs_packet
    rs_src = socket.inet_pton(socket.AF_INET6, link_local_addr)
  File "D:\XXNet\code\default\python27\1.0\lib\win32\win_inet_pton.py", line 42, in inet_pton
    raise socket.error(ctypes.FormatError())
error: 提供了一个无效的参数。

Aug 06 21:25:51.406 - [ERROR] stop module gae_proxy fail:'imp'
Aug 06 21:25:51.406 - [ERROR] Except stack:Traceback (most recent call last):
  File "D:\XXNet\code\default\launcher\module_init.py", line 74, in stop
    _start = proc_handler[module]["imp"].start
KeyError: 'imp'

Aug 06 21:25:51.406 - [INFO] begin to exit web control
Aug 06 21:25:51.421 - [ERROR] uncaught Exception, type=<type 'exceptions.AttributeError'> value='NoneType' object has no attribute 'shutdown' traceback:<traceback object at 0x00CD7940>

希望能得到解答，感谢

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by AnyWAT** [comment]
问题描述不清，想得到完美解答——不能😂

**Comment by hydramr** [comment]
应该说启动不能吧，搜过百度，也装了vc运行库，但是还是这个提示

**Comment by AnyWAT** [comment]
netsh int ipv6 show teredo 贴运行结果（无需IP地址的2行）及XX-Net诊断信息

**Comment by 821938089** [comment]
https://github.com/XX-net/XX-Net/releases/download/3.12.10/XX-Net-3.12.10.7z
下载这个最新版解压打开看看能不能用。

**Comment by hydramr** [comment]
Teredo 参数
---------------------------------------------
类型                    : default
服务器名称              : default
客户端刷新间隔          :default
客户端口                : default

诊断信息是error.log吗？
Aug 06 21:40:33.046 type:<type 'exceptions.AttributeError'> value='NoneType' object has no attribute 'shutdown' traceback:<traceback object at 0x00CB8A08>Aug 06 21:43:37.765 type:<type 'exceptions.AttributeError'> value='NoneType' object has no attribute 'shutdown' traceback:<traceback object at 0x02195238>

**Comment by AnyWAT** [comment]
http://127.0.0.1:8085/?module=gae_proxy&menu=status 页底“诊断信息”

**Comment by hydramr** [comment]
是的，首次使用，start.bat启动不成功，无法打开
http://127.0.0.1:8085/?module=gae_proxy&menu=status 
3.12.10.7z和3.12.10.zip我都试过了，一样的错误提示
感谢大家的解答

**Comment by AnyWAT** [comment]
貌似不是 start.bat，而是 start.vbs
管理权限运行XX-Net目录内 enable_ipv6.bat 即可正常开启、使用ipv6隧道？

**Comment by hydramr** [comment]
感谢，是xp默认没有ipv6惹的锅，现在可以用了

**Comment by AnyWAT** [comment]
😜首次使用，参考 #10919 臭大街法则
