### ISSUE TITLE
无法使用appids部署服务端

### ISSUE THREAD

**Issue by lianbo2006** [XX-net/XX-Net#11392]
2018-08-31 10:55:13,888 - root - INFO - set proxy to http://127.0.0.1:8087
2018-08-31 10:55:13,891 - root - INFO - ============ Begin upload ============
2018-08-31 10:55:13,891 - root - INFO - appid:xxnet-001-215002
2018-08-31 10:55:13,911 - root - INFO - Send: /api/appversion/rollback, params={'version': '1', 'app_id': 'xxnet-001-215002'}
2018-08-31 10:55:14,207 - root - ERROR - upload fail:BadStatusLine("''",)
Traceback (most recent call last):
File "D:\Desktop\XX-Net-3.12.11\XX-Net-3.12.11\code\default\gae_proxy\server\uploader.py", line 72, in upload
result = appcfg.AppCfgApp(['appcfg', 'rollback', '--oauth2_credential_file', cookie_file, dirname]).Run()
File "D:\Desktop\XX-Net-3.12.11\XX-Net-3.12.11\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 2951, in Run
self.action(self)
File "D:\Desktop\XX-Net-3.12.11\XX-Net-3.12.11\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 5044, in __call__
return method()
File "D:\Desktop\XX-Net-3.12.11\XX-Net-3.12.11\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 4397, in Rollback
self._Rollback()
File "D:\Desktop\XX-Net-3.12.11\XX-Net-3.12.11\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 4442, in _Rollback
appversion.Rollback(force_rollback)
File "D:\Desktop\XX-Net-3.12.11\XX-Net-3.12.11\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 2362, in Rollback
force_rollback='1' if force_rollback else '0')
File "D:\Desktop\XX-Net-3.12.11\XX-Net-3.12.11\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 1696, in Send
result = self.rpcserver.Send(url, payload=payload, **kwargs)
File "D:\Desktop\XX-Net-3.12.11\XX-Net-3.12.11\code\default\gae_proxy\server\lib\google\appengine\tools\appengine_rpc_httplib2.py", line 247, in Send
url, method=method, body=payload, headers=headers)
File "D:\Desktop\XX-Net-3.12.11\XX-Net-3.12.11\code\default\gae_proxy\server\lib\httplib2\__init__.py", line 1593, in request
(response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
File "D:\Desktop\XX-Net-3.12.11\XX-Net-3.12.11\code\default\gae_proxy\server\lib\httplib2\__init__.py", line 1341, in _request
(response, content) = self._conn_request(conn, request_uri, method, body, headers)
File "D:\Desktop\XX-Net-3.12.11\XX-Net-3.12.11\code\default\gae_proxy\server\lib\httplib2\__init__.py", line 1311, in _conn_request
response = conn.getresponse()
File "D:\Desktop\XX-Net-3.12.11\XX-Net-3.12.11\code\default\python27\1.0\lib\httplib.py", line 1121, in getresponse
response.begin()
File "D:\Desktop\XX-Net-3.12.11\XX-Net-3.12.11\code\default\python27\1.0\lib\httplib.py", line 438, in begin
version, status, reason = self._read_status()
File "D:\Desktop\XX-Net-3.12.11\XX-Net-3.12.11\code\default\python27\1.0\lib\httplib.py", line 402, in _read_status
raise BadStatusLine(line)
BadStatusLine: ''
2018-08-31 10:55:14,210 - root - INFO - Retry 1 time...
2018-08-31 10:55:14,223 - root - INFO - Send: /api/appversion/rollback, params={'version': '1', 'app_id': 'xxnet-001-215002'}
2018-08-31 10:55:14,249 - root - ERROR - upload fail:BadStatusLine("''",)
Traceback (most recent call last):
File "D:\Desktop\XX-Net-3.12.11\XX-Net-3.12.11\code\default\gae_proxy\server\uploader.py", line 72, in upload
result = appcfg.AppCfgApp(['appcfg', 'rollback', '--oauth2_credential_file', cookie_file, dirname]).Run()
File "D:\Desktop\XX-Net-3.12.11\XX-Net-3.12.11\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 2951, in Run
self.action(self)
File "D:\Desktop\XX-Net-3.12.11\XX-Net-3.12.11\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 5044, in __call__
return method()
File "D:\Desktop\XX-Net-3.12.11\XX-Net-3.12.11\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 4397, in Rollback
self._Rollback()
File "D:\Desktop\XX-Net-3.12.11\XX-Net-3.12.11\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 4442, in _Rollback
appversion.Rollback(force_rollback)
File "D:\Desktop\XX-Net-3.12.11\XX-Net-3.12.11\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 2362, in Rollback
force_rollback='1' if force_rollback else '0')
File "D:\Desktop\XX-Net-3.12.11\XX-Net-3.12.11\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 1696, in Send
result = self.rpcserver.Send(url, payload=payload, **kwargs)
File "D:\Desktop\XX-Net-3.12.11\XX-Net-3.12.11\code\default\gae_proxy\server\lib\google\appengine\tools\appengine_rpc_httplib2.py", line 247, in Send
url, method=method, body=payload, headers=headers)
File "D:\Desktop\XX-Net-3.12.11\XX-Net-3.12.11\code\default\gae_proxy\server\lib\httplib2\__init__.py", line 1593, in request
(response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
File "D:\Desktop\XX-Net-3.12.11\XX-Net-3.12.11\code\default\gae_proxy\server\lib\httplib2\__init__.py", line 1341, in _request
(response, content) = self._conn_request(conn, request_uri, method, body, headers)
File "D:\Desktop\XX-Net-3.12.11\XX-Net-3.12.11\code\default\gae_proxy\server\lib\httplib2\__init__.py", line 1311, in _conn_request
response = conn.getresponse()
File "D:\Desktop\XX-Net-3.12.11\XX-Net-3.12.11\code\default\python27\1.0\lib\httplib.py", line 1121, in getresponse
response.begin()
File "D:\Desktop\XX-Net-3.12.11\XX-Net-3.12.11\code\default\python27\1.0\lib\httplib.py", line 438, in begin
version, status, reason = self._read_status()
File "D:\Desktop\XX-Net-3.12.11\XX-Net-3.12.11\code\default\python27\1.0\lib\httplib.py", line 402, in _read_status
raise BadStatusLine(line)
BadStatusLine: ''
2018-08-31 10:55:14,250 - root - INFO - Retry 2 time...
2018-08-31 10:55:15,263 - root - INFO - Send: /api/appversion/rollback, params={'version': '1', 'app_id': 'xxnet-001-215002'}
2018-08-31 10:55:15,289 - root - ERROR - upload fail:BadStatusLine("''",)
Traceback (most recent call last):
File "D:\Desktop\XX-Net-3.12.11\XX-Net-3.12.11\code\default\gae_proxy\server\uploader.py", line 72, in upload
result = appcfg.AppCfgApp(['appcfg', 'rollback', '--oauth2_credential_file', cookie_file, dirname]).Run()
File "D:\Desktop\XX-Net-3.12.11\XX-Net-3.12.11\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 2951, in Run
self.action(self)
File "D:\Desktop\XX-Net-3.12.11\XX-Net-3.12.11\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 5044, in __call__
return method()
File "D:\Desktop\XX-Net-3.12.11\XX-Net-3.12.11\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 4397, in Rollback
self._Rollback()
File "D:\Desktop\XX-Net-3.12.11\XX-Net-3.12.11\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 4442, in _Rollback
appversion.Rollback(force_rollback)
File "D:\Desktop\XX-Net-3.12.11\XX-Net-3.12.11\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 2362, in Rollback
force_rollback='1' if force_rollback else '0')
File "D:\Desktop\XX-Net-3.12.11\XX-Net-3.12.11\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 1696, in Send
result = self.rpcserver.Send(url, payload=payload, **kwargs)
File "D:\Desktop\XX-Net-3.12.11\XX-Net-3.12.11\code\default\gae_proxy\server\lib\google\appengine\tools\appengine_rpc_httplib2.py", line 247, in Send
url, method=method, body=payload, headers=headers)
File "D:\Desktop\XX-Net-3.12.11\XX-Net-3.12.11\code\default\gae_proxy\server\lib\httplib2\__init__.py", line 1593, in request
(response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
File "D:\Desktop\XX-Net-3.12.11\XX-Net-3.12.11\code\default\gae_proxy\server\lib\httplib2\__init__.py", line 1341, in _request
(response, content) = self._conn_request(conn, request_uri, method, body, headers)
File "D:\Desktop\XX-Net-3.12.11\XX-Net-3.12.11\code\default\gae_proxy\server\lib\httplib2\__init__.py", line 1311, in _conn_request
response = conn.getresponse()
File "D:\Desktop\XX-Net-3.12.11\XX-Net-3.12.11\code\default\python27\1.0\lib\httplib.py", line 1121, in getresponse
response.begin()
File "D:\Desktop\XX-Net-3.12.11\XX-Net-3.12.11\code\default\python27\1.0\lib\httplib.py", line 438, in begin
version, status, reason = self._read_status()
File "D:\Desktop\XX-Net-3.12.11\XX-Net-3.12.11\code\default\python27\1.0\lib\httplib.py", line 402, in _read_status
raise BadStatusLine(line)
BadStatusLine: ''
2018-08-31 10:55:15,289 - root - INFO - Retry 3 time...
2018-08-31 10:55:17,290 - root - INFO - =======================
2018-08-31 10:55:17,290 - root - INFO - Deploy failed appid list:
2018-08-31 10:55:17,290 - root - INFO - - xxnet-001-215002
2018-08-31 10:55:17,292 - root - INFO - == END ==

**Comment by 1721970914** [comment]
wiki    https://github.com/XX-net/XX-Net/wiki/how-to-create-my-appids
你是新建APPID吗，有选择区域吗
可以看配额的话，我不知道
不能看就从2开始搞

**Comment by 1721970914** [comment]
设置AppID的App引擎 试试

**Comment by xxnet** [comment]
先不要设置APPID，确认能够上google再部署

**Comment by lianbo2006** [comment]
应该是找到原因了，部署时ipv6失效；现在ipv6恢复后就可以部署成功了
