### ISSUE TITLE
部署APPID时，没有弹出授权窗口

### ISSUE THREAD

**Issue by 1813195468** [XX-net/XX-Net#11465]
如题，在部署时没有授权窗口
访问 我的appid.appspot.com 时访问失败

**Comment by zanewayne78** [comment]
部署要先挂代理，毕竟是访问谷歌的网站

**Comment by AnyWAT** [comment]
或在系统默认浏览器内弹窗，复制链接到能代理的浏览器再继续。。。

**Comment by SeaHOH** [comment]
https://github.com/XX-net/XX-Net/issues/11454#issuecomment-420541088

**Comment by 1813195468** [comment]
> [#11454 (comment)](https://github.com/XX-net/XX-Net/issues/11454#issuecomment-420541088)

还是没有弹出窗口，日志是
2018-09-15 08:47:22,084 - root - INFO - enable debug logging
2018-09-15 08:47:22,085 - root - INFO - set proxy to http://127.0.0.1:8087
2018-09-15 08:47:22,088 - root - INFO - ============ Begin upload ============
2018-09-15 08:47:22,089 - root - INFO - appid:xx-net-216414
2018-09-15 08:47:22,147 - root - INFO - Send: /api/appversion/rollback, params={'version': '1', 'app_id': 'xx-net-216414'}
2018-09-15 08:47:22,148 - google.appengine.tools.appengine_rpc - DEBUG - _Authenticate skipped auth; needs_auth=False
2018-09-15 08:47:22,148 - google.appengine.tools.appengine_rpc - DEBUG - Sending request to https://appengine.google.com/api/appversion/rollback?app_id=xx-net-216414&force_rollback=0&version=1 headers={'X-appcfg-api-version': '1', 'content-length': '0', 'Content-Type': 'application/octet-stream'} body=
2018-09-15 08:47:22,842 - root - ERROR - upload fail:BadStatusLine("''",)
Traceback (most recent call last):
 File "E:\XX-Net-3.12.11\code\default\gae_proxy\server\uploader.py", line 72, in upload
 result = appcfg.AppCfgApp(['appcfg', 'rollback', '--oauth2_credential_file', cookie_file, dirname]).Run()
 File "E:\XX-Net-3.12.11\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 2951, in Run
 self.action(self)
 File "E:\XX-Net-3.12.11\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 5044, in __call__
 return method()
 File "E:\XX-Net-3.12.11\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 4397, in Rollback
 self._Rollback()
 File "E:\XX-Net-3.12.11\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 4442, in _Rollback
 appversion.Rollback(force_rollback)
 File "E:\XX-Net-3.12.11\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 2362, in Rollback
 force_rollback='1' if force_rollback else '0')
 File "E:\XX-Net-3.12.11\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 1696, in Send
 result = self.rpcserver.Send(url, payload=payload, **kwargs)
 File "E:\XX-Net-3.12.11\code\default\gae_proxy\server\lib\google\appengine\tools\appengine_rpc_httplib2.py", line 247, in Send
 url, method=method, body=payload, headers=headers)
 File "E:\XX-Net-3.12.11\code\default\gae_proxy\server\lib\httplib2\__init__.py", line 1593, in request
 (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
 File "E:\XX-Net-3.12.11\code\default\gae_proxy\server\lib\httplib2\__init__.py", line 1341, in _request
 (response, content) = self._conn_request(conn, request_uri, method, body, headers)
 File "E:\XX-Net-3.12.11\code\default\gae_proxy\server\lib\httplib2\__init__.py", line 1311, in _conn_request
 response = conn.getresponse()
 File "E:\XX-Net-3.12.11\code\default\python27\1.0\lib\httplib.py", line 1121, in getresponse
 response.begin()
 File "E:\XX-Net-3.12.11\code\default\python27\1.0\lib\httplib.py", line 438, in begin
 version, status, reason = self._read_status()
 File "E:\XX-Net-3.12.11\code\default\python27\1.0\lib\httplib.py", line 402, in _read_status
 raise BadStatusLine(line)
BadStatusLine: ''
2018-09-15 08:47:22,851 - root - INFO - Retry 1 time...
2018-09-15 08:47:22,885 - root - INFO - Send: /api/appversion/rollback, params={'version': '1', 'app_id': 'xx-net-216414'}
2018-09-15 08:47:22,885 - google.appengine.tools.appengine_rpc - DEBUG - _Authenticate skipped auth; needs_auth=False
2018-09-15 08:47:22,887 - google.appengine.tools.appengine_rpc - DEBUG - Sending request to https://appengine.google.com/api/appversion/rollback?app_id=xx-net-216414&force_rollback=0&version=1 headers={'X-appcfg-api-version': '1', 'content-length': '0', 'Content-Type': 'application/octet-stream'} body=
2018-09-15 08:47:22,937 - root - ERROR - upload fail:BadStatusLine("''",)
Traceback (most recent call last):
 File "E:\XX-Net-3.12.11\code\default\gae_proxy\server\uploader.py", line 72, in upload
 result = appcfg.AppCfgApp(['appcfg', 'rollback', '--oauth2_credential_file', cookie_file, dirname]).Run()
 File "E:\XX-Net-3.12.11\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 2951, in Run
 self.action(self)
 File "E:\XX-Net-3.12.11\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 5044, in __call__
 return method()
 File "E:\XX-Net-3.12.11\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 4397, in Rollback
 self._Rollback()
 File "E:\XX-Net-3.12.11\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 4442, in _Rollback
 appversion.Rollback(force_rollback)
 File "E:\XX-Net-3.12.11\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 2362, in Rollback
 force_rollback='1' if force_rollback else '0')
 File "E:\XX-Net-3.12.11\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 1696, in Send
 result = self.rpcserver.Send(url, payload=payload, **kwargs)
 File "E:\XX-Net-3.12.11\code\default\gae_proxy\server\lib\google\appengine\tools\appengine_rpc_httplib2.py", line 247, in Send
 url, method=method, body=payload, headers=headers)
 File "E:\XX-Net-3.12.11\code\default\gae_proxy\server\lib\httplib2\__init__.py", line 1593, in request
 (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
 File "E:\XX-Net-3.12.11\code\default\gae_proxy\server\lib\httplib2\__init__.py", line 1341, in _request
 (response, content) = self._conn_request(conn, request_uri, method, body, headers)
 File "E:\XX-Net-3.12.11\code\default\gae_proxy\server\lib\httplib2\__init__.py", line 1311, in _conn_request
 response = conn.getresponse()
 File "E:\XX-Net-3.12.11\code\default\python27\1.0\lib\httplib.py", line 1121, in getresponse
 response.begin()
 File "E:\XX-Net-3.12.11\code\default\python27\1.0\lib\httplib.py", line 438, in begin
 version, status, reason = self._read_status()
 File "E:\XX-Net-3.12.11\code\default\python27\1.0\lib\httplib.py", line 402, in _read_status
 raise BadStatusLine(line)
BadStatusLine: ''
2018-09-15 08:47:22,938 - root - INFO - Retry 2 time...
2018-09-15 08:47:23,973 - root - INFO - Send: /api/appversion/rollback, params={'version': '1', 'app_id': 'xx-net-216414'}
2018-09-15 08:47:23,973 - google.appengine.tools.appengine_rpc - DEBUG - _Authenticate skipped auth; needs_auth=False
2018-09-15 08:47:23,973 - google.appengine.tools.appengine_rpc - DEBUG - Sending request to https://appengine.google.com/api/appversion/rollback?app_id=xx-net-216414&force_rollback=0&version=1 headers={'X-appcfg-api-version': '1', 'content-length': '0', 'Content-Type': 'application/octet-stream'} body=
2018-09-15 08:47:24,023 - root - ERROR - upload fail:BadStatusLine("''",)
Traceback (most recent call last):
 File "E:\XX-Net-3.12.11\code\default\gae_proxy\server\uploader.py", line 72, in upload
 result = appcfg.AppCfgApp(['appcfg', 'rollback', '--oauth2_credential_file', cookie_file, dirname]).Run()
 File "E:\XX-Net-3.12.11\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 2951, in Run
 self.action(self)
 File "E:\XX-Net-3.12.11\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 5044, in __call__
 return method()
 File "E:\XX-Net-3.12.11\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 4397, in Rollback
 self._Rollback()
 File "E:\XX-Net-3.12.11\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 4442, in _Rollback
 appversion.Rollback(force_rollback)
 File "E:\XX-Net-3.12.11\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 2362, in Rollback
 force_rollback='1' if force_rollback else '0')
 File "E:\XX-Net-3.12.11\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 1696, in Send
 result = self.rpcserver.Send(url, payload=payload, **kwargs)
 File "E:\XX-Net-3.12.11\code\default\gae_proxy\server\lib\google\appengine\tools\appengine_rpc_httplib2.py", line 247, in Send
 url, method=method, body=payload, headers=headers)
 File "E:\XX-Net-3.12.11\code\default\gae_proxy\server\lib\httplib2\__init__.py", line 1593, in request
 (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
 File "E:\XX-Net-3.12.11\code\default\gae_proxy\server\lib\httplib2\__init__.py", line 1341, in _request
 (response, content) = self._conn_request(conn, request_uri, method, body, headers)
 File "E:\XX-Net-3.12.11\code\default\gae_proxy\server\lib\httplib2\__init__.py", line 1311, in _conn_request
 response = conn.getresponse()
 File "E:\XX-Net-3.12.11\code\default\python27\1.0\lib\httplib.py", line 1121, in getresponse
 response.begin()
 File "E:\XX-Net-3.12.11\code\default\python27\1.0\lib\httplib.py", line 438, in begin
 version, status, reason = self._read_status()
 File "E:\XX-Net-3.12.11\code\default\python27\1.0\lib\httplib.py", line 402, in _read_status
 raise BadStatusLine(line)
BadStatusLine: ''
2018-09-15 08:47:24,025 - root - INFO - Retry 3 time...
2018-09-15 08:47:26,026 - root - INFO - =======================
2018-09-15 08:47:26,026 - root - INFO - Deploy failed appid list:
2018-09-15 08:47:26,028 - root - INFO - - xx-net-216414
2018-09-15 08:47:26,028 - root - INFO - == END ==

**Comment by AnyWAT** [comment]
部署要先挂代理——如用XX-Net，尽管“XX-Net 3.12.11，一切正常，你可以访问真正的互联网了。”得查看下：如果连接池才几个或IP延时较大，点击“检查IP”，同时打开或刷新需代理的网页。。。#11291
