### ISSUE TITLE
XX-Net-3.11.10用起来很正常 XX-Net-3.12却是全灭

### ISSUE THREAD

**Issue by zx09** [XX-net/XX-Net#11527]
XX-Net-3.11.10用起来很正常 XX-Net-3.12却是全灭

自从XX-Net-3.12推出以后我不管是下哪一版都无法运行 相比之下老的3.11用起来完全没问题 
我是vista系统用ipv6的teredo隧道
appid是几年前goagent时期部署的 
不过xx-net时代一直可以用今天还用来上youtube看了视频
我就想知道怎么回事3.12版以来我一直用不了

下面是XX-Net-3.12.X\data\launcher\error.log 文件的内容

Oct 06 03:39:46.960 type:<type 'exceptions.AttributeError'> value='NoneType' object has no attribute 'shutdown' traceback:<traceback object at 0x02276FA8>Oct 06 07:12:34.869 type:<type 'exceptions.AttributeError'> value='NoneType' object has no attribute 'shutdown' traceback:<traceback object at 0x02248990>

------------------------------------------------------

下面是XX-Net-3.12.X\data\launcher\launcher.log 文件的内容

Oct 06 03:39:39.307 - [INFO] use build-in openssl lib
Oct 06 03:39:39.313 - [INFO] start XX-Net 3.12.5
Oct 06 03:39:39.314 - [DEBUG] start confirm_xxnet_exit
Oct 06 03:39:40.313 - [DEBUG] good, xxnet:8085 clear!
Oct 06 03:39:40.313 - [DEBUG] finished confirm_xxnet_exit
Oct 06 03:39:44.190 - [ERROR] start module gae_proxy fail:function 'OpenProcessToken' not found
Oct 06 03:39:44.192 - [ERROR] Except stack:Traceback (most recent call last):
  File "D:\proxy\XX-Net-3.12.5\code\default\launcher\module_init.py", line 40, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "D:\proxy\XX-Net-3.12.5\code\default\gae_proxy\start.py", line 13, in <module>
    import local.proxy as client
  File "D:\proxy\XX-Net-3.12.5\code\default\gae_proxy\local\proxy.py", line 86, in <module>
    import proxy_handler
  File "D:\proxy\XX-Net-3.12.5\code\default\gae_proxy\local\proxy_handler.py", line 53, in <module>
    import web_control
  File "D:\proxy\XX-Net-3.12.5\code\default\gae_proxy\local\web_control.py", line 32, in <module>
    import ipv6_tunnel
  File "D:\proxy\XX-Net-3.12.5\code\default\gae_proxy\local\ipv6_tunnel\__init__.py", line 10, in <module>
    from .win10 import state, state_pp, switch_pp, enable, disable, set_best_server
  File "D:\proxy\XX-Net-3.12.5\code\default\gae_proxy\local\ipv6_tunnel\win10.py", line 10, in <module>
    import win32elevate
  File "D:\proxy\XX-Net-3.12.5\code\default\python27\1.0\lib\win32\win32elevate.py", line 37, in <module>
    OpenProcessToken = ctypes.windll.kernel32.OpenProcessToken
  File "D:\proxy\XX-Net-3.12.5\code\default\python27\1.0\lib\ctypes\__init__.py", line 301, in __getattr__
    func = self.__getitem__(name)
  File "D:\proxy\XX-Net-3.12.5\code\default\python27\1.0\lib\ctypes\__init__.py", line 306, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'OpenProcessToken' not found

Oct 06 03:39:44.199 - [ERROR] launcher except:AttributeError("function 'OpenProcessToken' not found",)
Oct 06 03:39:44.200 - [ERROR] Except stack:Traceback (most recent call last):
  File "D:\proxy\XX-Net-3.12.5\code\default\launcher\start.py", line 247, in <module>
    main()
  File "D:\proxy\XX-Net-3.12.5\code\default\launcher\start.py", line 226, in main
    module_init.start_all_auto()
  File "D:\proxy\XX-Net-3.12.5\code\default\launcher\module_init.py", line 113, in start_all_auto
    start(module)
  File "D:\proxy\XX-Net-3.12.5\code\default\launcher\module_init.py", line 40, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "D:\proxy\XX-Net-3.12.5\code\default\gae_proxy\start.py", line 13, in <module>
    import local.proxy as client
  File "D:\proxy\XX-Net-3.12.5\code\default\gae_proxy\local\proxy.py", line 86, in <module>
    import proxy_handler
  File "D:\proxy\XX-Net-3.12.5\code\default\gae_proxy\local\proxy_handler.py", line 53, in <module>
    import web_control
  File "D:\proxy\XX-Net-3.12.5\code\default\gae_proxy\local\web_control.py", line 32, in <module>
    import ipv6_tunnel
  File "D:\proxy\XX-Net-3.12.5\code\default\gae_proxy\local\ipv6_tunnel\__init__.py", line 10, in <module>
    from .win10 import state, state_pp, switch_pp, enable, disable, set_best_server
  File "D:\proxy\XX-Net-3.12.5\code\default\gae_proxy\local\ipv6_tunnel\win10.py", line 10, in <module>
    import win32elevate
  File "D:\proxy\XX-Net-3.12.5\code\default\python27\1.0\lib\win32\win32elevate.py", line 37, in <module>
    OpenProcessToken = ctypes.windll.kernel32.OpenProcessToken
  File "D:\proxy\XX-Net-3.12.5\code\default\python27\1.0\lib\ctypes\__init__.py", line 301, in __getattr__
    func = self.__getitem__(name)
  File "D:\proxy\XX-Net-3.12.5\code\default\python27\1.0\lib\ctypes\__init__.py", line 306, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'OpenProcessToken' not found

Oct 06 03:39:46.946 - [ERROR] stop module gae_proxy fail:'imp'
Oct 06 03:39:46.947 - [ERROR] Except stack:Traceback (most recent call last):
  File "D:\proxy\XX-Net-3.12.5\code\default\launcher\module_init.py", line 74, in stop
    _start = proc_handler[module]["imp"].start
KeyError: 'imp'

Oct 06 03:39:46.949 - [INFO] begin to exit web control
Oct 06 03:39:46.960 - [ERROR] uncaught Exception, type=<type 'exceptions.AttributeError'> value='NoneType' object has no attribute 'shutdown' traceback:<traceback object at 0x02276FA8>
Oct 06 07:01:05.293 - [INFO] use build-in openssl lib
Oct 06 07:01:05.309 - [INFO] start XX-Net 3.12.5
Oct 06 07:01:05.309 - [DEBUG] start confirm_xxnet_exit
Oct 06 07:01:06.323 - [DEBUG] good, xxnet:8085 clear!
Oct 06 07:01:06.323 - [DEBUG] finished confirm_xxnet_exit
Oct 06 07:01:10.646 - [ERROR] start module gae_proxy fail:function 'OpenProcessToken' not found
Oct 06 07:01:10.724 - [ERROR] Except stack:Traceback (most recent call last):
  File "D:\proxy\XX-Net-3.12.5\code\default\launcher\module_init.py", line 40, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "D:\proxy\XX-Net-3.12.5\code\default\gae_proxy\start.py", line 13, in <module>
    import local.proxy as client
  File "D:\proxy\XX-Net-3.12.5\code\default\gae_proxy\local\proxy.py", line 86, in <module>
    import proxy_handler
  File "D:\proxy\XX-Net-3.12.5\code\default\gae_proxy\local\proxy_handler.py", line 53, in <module>
    import web_control
  File "D:\proxy\XX-Net-3.12.5\code\default\gae_proxy\local\web_control.py", line 32, in <module>
    import ipv6_tunnel
  File "D:\proxy\XX-Net-3.12.5\code\default\gae_proxy\local\ipv6_tunnel\__init__.py", line 10, in <module>
    from .win10 import state, state_pp, switch_pp, enable, disable, set_best_server
  File "D:\proxy\XX-Net-3.12.5\code\default\gae_proxy\local\ipv6_tunnel\win10.py", line 10, in <module>
    import win32elevate
  File "D:\proxy\XX-Net-3.12.5\code\default\python27\1.0\lib\win32\win32elevate.py", line 37, in <module>
    OpenProcessToken = ctypes.windll.kernel32.OpenProcessToken
  File "D:\proxy\XX-Net-3.12.5\code\default\python27\1.0\lib\ctypes\__init__.py", line 301, in __getattr__
    func = self.__getitem__(name)
  File "D:\proxy\XX-Net-3.12.5\code\default\python27\1.0\lib\ctypes\__init__.py", line 306, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'OpenProcessToken' not found

Oct 06 07:01:10.740 - [ERROR] launcher except:AttributeError("function 'OpenProcessToken' not found",)
Oct 06 07:01:10.740 - [ERROR] Except stack:Traceback (most recent call last):
  File "D:\proxy\XX-Net-3.12.5\code\default\launcher\start.py", line 247, in <module>
    main()
  File "D:\proxy\XX-Net-3.12.5\code\default\launcher\start.py", line 226, in main
    module_init.start_all_auto()
  File "D:\proxy\XX-Net-3.12.5\code\default\launcher\module_init.py", line 113, in start_all_auto
    start(module)
  File "D:\proxy\XX-Net-3.12.5\code\default\launcher\module_init.py", line 40, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "D:\proxy\XX-Net-3.12.5\code\default\gae_proxy\start.py", line 13, in <module>
    import local.proxy as client
  File "D:\proxy\XX-Net-3.12.5\code\default\gae_proxy\local\proxy.py", line 86, in <module>
    import proxy_handler
  File "D:\proxy\XX-Net-3.12.5\code\default\gae_proxy\local\proxy_handler.py", line 53, in <module>
    import web_control
  File "D:\proxy\XX-Net-3.12.5\code\default\gae_proxy\local\web_control.py", line 32, in <module>
    import ipv6_tunnel
  File "D:\proxy\XX-Net-3.12.5\code\default\gae_proxy\local\ipv6_tunnel\__init__.py", line 10, in <module>
    from .win10 import state, state_pp, switch_pp, enable, disable, set_best_server
  File "D:\proxy\XX-Net-3.12.5\code\default\gae_proxy\local\ipv6_tunnel\win10.py", line 10, in <module>
    import win32elevate
  File "D:\proxy\XX-Net-3.12.5\code\default\python27\1.0\lib\win32\win32elevate.py", line 37, in <module>
    OpenProcessToken = ctypes.windll.kernel32.OpenProcessToken
  File "D:\proxy\XX-Net-3.12.5\code\default\python27\1.0\lib\ctypes\__init__.py", line 301, in __getattr__
    func = self.__getitem__(name)
  File "D:\proxy\XX-Net-3.12.5\code\default\python27\1.0\lib\ctypes\__init__.py", line 306, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'OpenProcessToken' not found

Oct 06 07:01:45.841 - [INFO] use build-in openssl lib
Oct 06 07:01:45.841 - [INFO] start XX-Net 3.12.5
Oct 06 07:01:45.841 - [DEBUG] start confirm_xxnet_exit
Oct 06 07:01:46.840 - [DEBUG] good, xxnet:8085 clear!
Oct 06 07:01:46.840 - [DEBUG] finished confirm_xxnet_exit
Oct 06 07:01:48.337 - [ERROR] start module gae_proxy fail:function 'OpenProcessToken' not found
Oct 06 07:01:48.337 - [ERROR] Except stack:Traceback (most recent call last):
  File "D:\proxy\XX-Net-3.12.5\code\default\launcher\module_init.py", line 40, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "D:\proxy\XX-Net-3.12.5\code\default\gae_proxy\start.py", line 13, in <module>
    import local.proxy as client
  File "D:\proxy\XX-Net-3.12.5\code\default\gae_proxy\local\proxy.py", line 86, in <module>
    import proxy_handler
  File "D:\proxy\XX-Net-3.12.5\code\default\gae_proxy\local\proxy_handler.py", line 53, in <module>
    import web_control
  File "D:\proxy\XX-Net-3.12.5\code\default\gae_proxy\local\web_control.py", line 32, in <module>
    import ipv6_tunnel
  File "D:\proxy\XX-Net-3.12.5\code\default\gae_proxy\local\ipv6_tunnel\__init__.py", line 10, in <module>
    from .win10 import state, state_pp, switch_pp, enable, disable, set_best_server
  File "D:\proxy\XX-Net-3.12.5\code\default\gae_proxy\local\ipv6_tunnel\win10.py", line 10, in <module>
    import win32elevate
  File "D:\proxy\XX-Net-3.12.5\code\default\python27\1.0\lib\win32\win32elevate.py", line 37, in <module>
    OpenProcessToken = ctypes.windll.kernel32.OpenProcessToken
  File "D:\proxy\XX-Net-3.12.5\code\default\python27\1.0\lib\ctypes\__init__.py", line 301, in __getattr__
    func = self.__getitem__(name)
  File "D:\proxy\XX-Net-3.12.5\code\default\python27\1.0\lib\ctypes\__init__.py", line 306, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'OpenProcessToken' not found

Oct 06 07:01:48.353 - [ERROR] launcher except:AttributeError("function 'OpenProcessToken' not found",)
Oct 06 07:01:48.353 - [ERROR] Except stack:Traceback (most recent call last):
  File "D:\proxy\XX-Net-3.12.5\code\default\launcher\start.py", line 247, in <module>
    main()
  File "D:\proxy\XX-Net-3.12.5\code\default\launcher\start.py", line 226, in main
    module_init.start_all_auto()
  File "D:\proxy\XX-Net-3.12.5\code\default\launcher\module_init.py", line 113, in start_all_auto
    start(module)
  File "D:\proxy\XX-Net-3.12.5\code\default\launcher\module_init.py", line 40, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "D:\proxy\XX-Net-3.12.5\code\default\gae_proxy\start.py", line 13, in <module>
    import local.proxy as client
  File "D:\proxy\XX-Net-3.12.5\code\default\gae_proxy\local\proxy.py", line 86, in <module>
    import proxy_handler
  File "D:\proxy\XX-Net-3.12.5\code\default\gae_proxy\local\proxy_handler.py", line 53, in <module>
    import web_control
  File "D:\proxy\XX-Net-3.12.5\code\default\gae_proxy\local\web_control.py", line 32, in <module>
    import ipv6_tunnel
  File "D:\proxy\XX-Net-3.12.5\code\default\gae_proxy\local\ipv6_tunnel\__init__.py", line 10, in <module>
    from .win10 import state, state_pp, switch_pp, enable, disable, set_best_server
  File "D:\proxy\XX-Net-3.12.5\code\default\gae_proxy\local\ipv6_tunnel\win10.py", line 10, in <module>
    import win32elevate
  File "D:\proxy\XX-Net-3.12.5\code\default\python27\1.0\lib\win32\win32elevate.py", line 37, in <module>
    OpenProcessToken = ctypes.windll.kernel32.OpenProcessToken
  File "D:\proxy\XX-Net-3.12.5\code\default\python27\1.0\lib\ctypes\__init__.py", line 301, in __getattr__
    func = self.__getitem__(name)
  File "D:\proxy\XX-Net-3.12.5\code\default\python27\1.0\lib\ctypes\__init__.py", line 306, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'OpenProcessToken' not found

Oct 06 07:12:29.440 - [INFO] use build-in openssl lib
Oct 06 07:12:29.440 - [INFO] start XX-Net 3.12.5
Oct 06 07:12:29.440 - [DEBUG] start confirm_xxnet_exit
Oct 06 07:12:30.439 - [DEBUG] good, xxnet:8085 clear!
Oct 06 07:12:30.439 - [DEBUG] finished confirm_xxnet_exit
Oct 06 07:12:31.593 - [ERROR] start module gae_proxy fail:function 'OpenProcessToken' not found
Oct 06 07:12:31.593 - [ERROR] Except stack:Traceback (most recent call last):
  File "D:\proxy\XX-Net-3.12.5\code\default\launcher\module_init.py", line 40, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "D:\proxy\XX-Net-3.12.5\code\default\gae_proxy\start.py", line 13, in <module>
    import local.proxy as client
  File "D:\proxy\XX-Net-3.12.5\code\default\gae_proxy\local\proxy.py", line 86, in <module>
    import proxy_handler
  File "D:\proxy\XX-Net-3.12.5\code\default\gae_proxy\local\proxy_handler.py", line 53, in <module>
    import web_control
  File "D:\proxy\XX-Net-3.12.5\code\default\gae_proxy\local\web_control.py", line 32, in <module>
    import ipv6_tunnel
  File "D:\proxy\XX-Net-3.12.5\code\default\gae_proxy\local\ipv6_tunnel\__init__.py", line 10, in <module>
    from .win10 import state, state_pp, switch_pp, enable, disable, set_best_server
  File "D:\proxy\XX-Net-3.12.5\code\default\gae_proxy\local\ipv6_tunnel\win10.py", line 10, in <module>
    import win32elevate
  File "D:\proxy\XX-Net-3.12.5\code\default\python27\1.0\lib\win32\win32elevate.py", line 37, in <module>
    OpenProcessToken = ctypes.windll.kernel32.OpenProcessToken
  File "D:\proxy\XX-Net-3.12.5\code\default\python27\1.0\lib\ctypes\__init__.py", line 301, in __getattr__
    func = self.__getitem__(name)
  File "D:\proxy\XX-Net-3.12.5\code\default\python27\1.0\lib\ctypes\__init__.py", line 306, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'OpenProcessToken' not found

Oct 06 07:12:31.593 - [ERROR] launcher except:AttributeError("function 'OpenProcessToken' not found",)
Oct 06 07:12:31.593 - [ERROR] Except stack:Traceback (most recent call last):
  File "D:\proxy\XX-Net-3.12.5\code\default\launcher\start.py", line 247, in <module>
    main()
  File "D:\proxy\XX-Net-3.12.5\code\default\launcher\start.py", line 226, in main
    module_init.start_all_auto()
  File "D:\proxy\XX-Net-3.12.5\code\default\launcher\module_init.py", line 113, in start_all_auto
    start(module)
  File "D:\proxy\XX-Net-3.12.5\code\default\launcher\module_init.py", line 40, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "D:\proxy\XX-Net-3.12.5\code\default\gae_proxy\start.py", line 13, in <module>
    import local.proxy as client
  File "D:\proxy\XX-Net-3.12.5\code\default\gae_proxy\local\proxy.py", line 86, in <module>
    import proxy_handler
  File "D:\proxy\XX-Net-3.12.5\code\default\gae_proxy\local\proxy_handler.py", line 53, in <module>
    import web_control
  File "D:\proxy\XX-Net-3.12.5\code\default\gae_proxy\local\web_control.py", line 32, in <module>
    import ipv6_tunnel
  File "D:\proxy\XX-Net-3.12.5\code\default\gae_proxy\local\ipv6_tunnel\__init__.py", line 10, in <module>
    from .win10 import state, state_pp, switch_pp, enable, disable, set_best_server
  File "D:\proxy\XX-Net-3.12.5\code\default\gae_proxy\local\ipv6_tunnel\win10.py", line 10, in <module>
    import win32elevate
  File "D:\proxy\XX-Net-3.12.5\code\default\python27\1.0\lib\win32\win32elevate.py", line 37, in <module>
    OpenProcessToken = ctypes.windll.kernel32.OpenProcessToken
  File "D:\proxy\XX-Net-3.12.5\code\default\python27\1.0\lib\ctypes\__init__.py", line 301, in __getattr__
    func = self.__getitem__(name)
  File "D:\proxy\XX-Net-3.12.5\code\default\python27\1.0\lib\ctypes\__init__.py", line 306, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'OpenProcessToken' not found

Oct 06 07:12:34.776 - [ERROR] stop module gae_proxy fail:'imp'
Oct 06 07:12:34.776 - [ERROR] Except stack:Traceback (most recent call last):
  File "D:\proxy\XX-Net-3.12.5\code\default\launcher\module_init.py", line 74, in stop
    _start = proc_handler[module]["imp"].start
KeyError: 'imp'

Oct 06 07:12:34.776 - [INFO] begin to exit web control
Oct 06 07:12:34.869 - [ERROR] uncaught Exception, type=<type 'exceptions.AttributeError'> value='NoneType' object has no attribute 'shutdown' traceback:<traceback object at 0x02248990>

----------------------------------------------

github的界面全英文的看不懂 有些高级编辑功能不会用还请见谅
日志文件应该是这两个了 如果还缺什么信息请在下方留言
希望有人能告诉我是出了什么问题

**Comment by AnyWAT** [comment]
没在公告内：https://github.com/XX-net/XX-Net/releases V3.12.1 新版改进：客户端 3.11.12 及以上和服务器 3.3.2 及以上需要更新（服务端）
https://github.com/XX-net/XX-Net/issues/11010 替换新的 code/x.xx.xx/gae_proxy/local/cacert.pem 文件。实在想用旧版本的用户，可以替换新的 gae_proxy/local/cacert.pem 文件——用3.12.2（及以后版本）的 cacert.pem 替换掉想运行的（3.12.2以前的任何）旧版

**Comment by SeaHOH** [comment]
[win32elevate.zip](https://github.com/XX-net/XX-Net/files/2452607/win32elevate.zip)
用这个替换上面日志中的同名文件试试

**Comment by SeaHOH** [comment]
@zx09 替换文件有用吗？给个回信。

**Comment by zx09** [comment]
没用啊一样的退出

**Comment by SeaHOH** [comment]
你现在这个错误是配置文件格式不对，你自己编辑过 config.json 吧？

另外，上面那个文件可以启动，但是有个地方没改完，
你可以下载 https://github.com/XX-net/XX-Net/archive/master.zip 来使用。

**Comment by SeaHOH** [comment]
@kiki008 你的也是 Vista？直接下载楼上的。
