### ISSUE TITLE
无法启动程序

### ISSUE THREAD

**Issue by HeviLUO** [XX-net/XX-Net#11534]
操作系统：Windows10 1809（17763.1）

托盘图标不显示，配置页也打不开。

Oct 06 21:51:18.903 [cloudfront_front][INFO] load ip_list num:100, target num:100
Oct 06 21:51:18.919 [tls_relay][INFO] SSL use version:TLSv1_2
Oct 06 21:51:18.919 [tls_relay][INFO] OpenSSL support alpn
Oct 06 21:51:18.934 [heroku_front][INFO] SSL use version:TLSv1_2
Oct 06 21:51:18.950 [heroku_front][INFO] OpenSSL support alpn
Oct 06 21:51:18.950 [heroku_front][INFO] load ip_list num:75, target num:75
Oct 06 21:51:18.950 [x_tunnel][INFO] use config_path:D:\XX-Net-3.12.11\data\x_tunnel\client.json
Oct 06 21:51:18.950 [x_tunnel][INFO] X-Tunnel window:16777216
Oct 06 21:51:18.966 [x_tunnel][INFO] xxnet_version:3.12.11
Oct 06 21:51:18.966 [x_tunnel][ERROR] bind to 127.0.0.1:1080 fail:error(10013, '')
Exception in thread Thread-50:
Traceback (most recent call last):
  File "D:\XX-Net-3.12.11\code\default\python27\1.0\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "D:\XX-Net-3.12.11\code\default\python27\1.0\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "D:\XX-Net-3.12.11\code\default\x_tunnel\start.py", line 19, in main
    client.main(args)
  File "D:\XX-Net-3.12.11\code\default\x_tunnel\local\client.py", line 172, in main
    g.socks5_server = simple_http_server.HTTPServer((listen_ip, g.config.socks_port), Socks5Server, logger=xlog)
  File "D:\XX-Net-3.12.11\code\default\python27\1.0\lib\noarch\simple_http_server.py", line 412, in __init__
    self.init_socket()
  File "D:\XX-Net-3.12.11\code\default\python27\1.0\lib\noarch\simple_http_server.py", line 422, in init_socket
    self.add_listen(addr)
  File "D:\XX-Net-3.12.11\code\default\python27\1.0\lib\noarch\simple_http_server.py", line 436, in add_listen
    raise Exception(err_string)
Exception: bind to 127.0.0.1:1080 fail:error(10013, '')

Oct 06 21:51:21.626 [gae_proxy][WARNING] network IPv6 fail

**Comment by SeaHOH** [comment]
1080 端口被占用，请检查。

**Comment by HeviLUO** [comment]
netstat -ano 没发现有占用

**Comment by HeviLUO** [comment]
netstat -ano

活动连接

  协议  本地地址          外部地址        状态           PID
  TCP    0.0.0.0:135            0.0.0.0:0              LISTENING       1016
  TCP    0.0.0.0:445            0.0.0.0:0              LISTENING       4
  TCP    0.0.0.0:1025           0.0.0.0:0              LISTENING       752
  TCP    0.0.0.0:1027           0.0.0.0:0              LISTENING       3536
  TCP    0.0.0.0:1063           0.0.0.0:0              LISTENING       780
  TCP    0.0.0.0:2179           0.0.0.0:0              LISTENING       4656
  TCP    0.0.0.0:5040           0.0.0.0:0              LISTENING       6684
  TCP    0.0.0.0:7680           0.0.0.0:0              LISTENING       3140
  TCP    0.0.0.0:34642          0.0.0.0:0              LISTENING       3572
  TCP    0.0.0.0:49664          0.0.0.0:0              LISTENING       680
  TCP    0.0.0.0:49665          0.0.0.0:0              LISTENING       1676
  TCP    0.0.0.0:49666          0.0.0.0:0              LISTENING       1376
  TCP    0.0.0.0:49667          0.0.0.0:0              LISTENING       3888
  TCP    127.0.0.1:8087         0.0.0.0:0              LISTENING       6584
  TCP    127.0.0.1:23403        0.0.0.0:0              LISTENING       10952
  TCP    127.0.0.1:28317        0.0.0.0:0              LISTENING       4628
  TCP    172.17.102.193:139     0.0.0.0:0              LISTENING       4
  TCP    192.168.1.176:139      0.0.0.0:0              LISTENING       4
  TCP    192.168.1.176:6317     52.230.7.59:443        ESTABLISHED     4616
  TCP    192.168.1.176:6318     52.230.7.59:443        ESTABLISHED     4616
  TCP    192.168.1.176:6329     52.98.64.242:443       ESTABLISHED     8404
  TCP    192.168.1.176:6337     117.18.237.29:80       TIME_WAIT       0
  TCP    192.168.1.176:6341     211.103.25.221:80      ESTABLISHED     3572
  TCP    192.168.1.176:6358     192.30.253.124:443     ESTABLISHED     11088
  TCP    192.168.1.176:6408     202.89.233.100:443     TIME_WAIT       0
  TCP    192.168.1.176:6414     40.81.31.55:443        TIME_WAIT       0
  TCP    192.168.1.176:6415     202.89.233.100:443     TIME_WAIT       0
  TCP    192.168.1.176:6416     204.79.197.200:443     TIME_WAIT       0
  TCP    192.168.1.176:6417     202.89.233.96:443      TIME_WAIT       0
  TCP    192.168.1.176:6418     202.89.233.96:443      TIME_WAIT       0
  TCP    192.168.1.176:6429     40.77.226.13:443       ESTABLISHED     10132
  TCP    192.168.1.176:6431     40.77.226.13:443       ESTABLISHED     10132
  TCP    192.168.1.176:6463     183.232.231.172:443    TIME_WAIT       0
  TCP    192.168.1.176:6487     27.151.12.39:443       ESTABLISHED     13308
  TCP    192.168.1.176:6488     27.151.12.39:443       ESTABLISHED     13308
  TCP    192.168.1.176:6489     27.151.12.39:443       ESTABLISHED     13308
  TCP    192.168.1.176:6490     45.116.82.64:80        CLOSE_WAIT      13308
  TCP    192.168.1.176:6491     45.116.82.64:80        CLOSE_WAIT      13308
  TCP    192.168.1.176:6492     45.116.82.64:80        CLOSE_WAIT      13308
  TCP    192.168.1.176:6493     45.116.82.64:80        CLOSE_WAIT      13308
  TCP    192.168.1.176:6495     45.116.82.64:80        CLOSE_WAIT      13308
  TCP    192.168.1.176:6496     45.116.82.64:80        CLOSE_WAIT      13308
  TCP    192.168.1.176:6505     111.59.124.188:443     TIME_WAIT       0
  TCP    192.168.1.176:6506     111.59.124.188:443     TIME_WAIT       0
  TCP    192.168.1.176:6507     223.119.50.203:80      ESTABLISHED     9668
  TCP    192.168.1.176:6509     184.84.60.234:443      ESTABLISHED     10436
  TCP    192.168.1.176:6510     52.175.112.16:443      ESTABLISHED     10436
  TCP    192.168.1.176:6516     13.67.66.198:443       ESTABLISHED     3448
  TCP    192.168.1.176:6518     23.198.135.250:443     ESTABLISHED     13308
  TCP    192.168.1.176:6537     117.18.237.29:80       ESTABLISHED     9668
  TCP    192.168.1.176:6542     202.89.233.101:443     TIME_WAIT       0
  TCP    192.168.1.176:6543     202.89.233.101:443     TIME_WAIT       0
  TCP    192.168.1.176:6544     202.89.233.100:443     TIME_WAIT       0
  TCP    192.168.1.176:6557     183.232.231.172:443    TIME_WAIT       0
  TCP    192.168.1.176:6560     183.232.121.188:993    TIME_WAIT       0
  TCP    192.168.1.176:6563     183.232.121.188:993    TIME_WAIT       0
  TCP    192.168.1.176:6583     120.55.226.122:443     TIME_WAIT       0
  TCP    192.168.1.176:6586     117.18.237.29:80       ESTABLISHED     9668
  TCP    192.168.1.176:6598     120.55.226.122:443     TIME_WAIT       0
  TCP    192.168.1.176:6604     117.18.237.29:80       ESTABLISHED     9668
  TCP    192.168.1.176:6615     211.151.242.150:443    TIME_WAIT       0
  TCP    192.168.1.176:6616     211.151.242.150:443    TIME_WAIT       0
  TCP    192.168.1.176:6632     52.229.171.202:443     TIME_WAIT       0
  TCP    192.168.1.176:6633     52.229.171.202:443     TIME_WAIT       0
  TCP    192.168.1.176:6635     52.229.171.202:443     TIME_WAIT       0
  TCP    192.168.1.176:6641     52.114.88.20:443       TIME_WAIT       0
  TCP    192.168.1.176:6642     52.138.216.83:443      TIME_WAIT       0
  TCP    192.168.1.176:6643     52.138.216.83:443      TIME_WAIT       0
  TCP    192.168.1.176:6644     52.138.216.83:443      TIME_WAIT       0
  TCP    192.168.1.176:6645     52.138.216.83:443      TIME_WAIT       0
  TCP    192.168.1.176:6646     111.221.29.40:443      TIME_WAIT       0
  TCP    192.168.1.176:6647     52.114.88.20:443       TIME_WAIT       0
  TCP    192.168.1.176:6649     52.138.216.83:443      TIME_WAIT       0
  TCP    192.168.1.176:6650     52.138.216.83:443      TIME_WAIT       0
  TCP    192.168.1.176:6652     52.138.216.83:443      TIME_WAIT       0
  TCP    192.168.1.176:6654     52.138.216.83:443      TIME_WAIT       0
  TCP    192.168.1.176:6655     52.114.88.20:443       TIME_WAIT       0
  TCP    192.168.1.176:6656     52.229.171.202:443     TIME_WAIT       0
  TCP    192.168.1.176:6657     111.221.29.40:443      TIME_WAIT       0
  TCP    192.168.1.176:6658     52.114.88.20:443       TIME_WAIT       0
  TCP    192.168.1.176:6659     191.234.72.188:443     TIME_WAIT       0
  TCP    192.168.1.176:6660     52.114.88.20:443       TIME_WAIT       0
  TCP    192.168.1.176:6661     111.21.66.148:80       TIME_WAIT       0
  TCP    192.168.1.176:6666     222.52.39.97:80        TIME_WAIT       0
  TCP    192.168.1.176:6667     36.159.127.251:80      TIME_WAIT       0
  TCP    192.168.1.176:6668     52.114.88.20:443       TIME_WAIT       0
  TCP    192.168.1.176:6670     52.229.174.233:443     ESTABLISHED     3140
  TCP    192.168.1.176:6672     52.229.170.224:443     ESTABLISHED     3140
  TCP    192.168.1.176:6673     52.229.172.222:443     ESTABLISHED     3140
  TCP    192.168.1.176:6674     52.229.172.155:443     ESTABLISHED     3140
  TCP    192.168.1.176:6675     52.114.132.21:443      TIME_WAIT       0
  TCP    192.168.1.176:6676     52.114.132.21:443      TIME_WAIT       0
  TCP    192.168.1.176:6677     192.30.253.113:443     ESTABLISHED     11088
  TCP    192.168.1.176:6678     192.30.253.113:443     CLOSE_WAIT      11088
  TCP    192.168.1.176:6682     183.232.121.188:993    ESTABLISHED     72
  TCP    192.168.1.176:6689     151.101.188.133:443    ESTABLISHED     6584
  TCP    192.168.1.176:6691     74.125.204.113:443     SYN_SENT        6560
  TCP    192.168.1.176:6697     74.125.23.101:443      SYN_SENT        10024
  TCP    [::]:135               [::]:0                 LISTENING       1016
  TCP    [::]:445               [::]:0                 LISTENING       4
  TCP    [::]:1025              [::]:0                 LISTENING       752
  TCP    [::]:1027              [::]:0                 LISTENING       3536
  TCP    [::]:1063              [::]:0                 LISTENING       780
  TCP    [::]:2179              [::]:0                 LISTENING       4656
  TCP    [::]:7680              [::]:0                 LISTENING       3140
  TCP    [::]:49664             [::]:0                 LISTENING       680
  TCP    [::]:49665             [::]:0                 LISTENING       1676
  TCP    [::]:49666             [::]:0                 LISTENING       1376
  TCP    [::]:49667             [::]:0                 LISTENING       3888
  UDP    0.0.0.0:53             *:*                                    7380
  UDP    0.0.0.0:500            *:*                                    3544
  UDP    0.0.0.0:4500           *:*                                    3544
  UDP    0.0.0.0:5050           *:*                                    6684
  UDP    0.0.0.0:5353           *:*                                    2240
  UDP    0.0.0.0:5355           *:*                                    2240
  UDP    0.0.0.0:49460          *:*                                    7380
  UDP    0.0.0.0:49461          *:*                                    7380
  UDP    0.0.0.0:49938          *:*                                    4508
  UDP    0.0.0.0:50265          *:*                                    4508
  UDP    127.0.0.1:1900         *:*                                    6744
  UDP    127.0.0.1:48400        *:*                                    10952
  UDP    127.0.0.1:48401        *:*                                    3612
  UDP    127.0.0.1:51174        *:*                                    3520
  UDP    127.0.0.1:58663        *:*                                    6744
  UDP    172.17.102.193:67      *:*                                    7380
  UDP    172.17.102.193:68      *:*                                    7380
  UDP    172.17.102.193:137     *:*                                    4
  UDP    172.17.102.193:138     *:*                                    4
  UDP    172.17.102.193:1900    *:*                                    6744
  UDP    172.17.102.193:58664   *:*                                    6744
  UDP    192.168.1.176:137      *:*                                    4
  UDP    192.168.1.176:138      *:*                                    4
  UDP    192.168.1.176:1900     *:*                                    6744
  UDP    192.168.1.176:58662    *:*                                    6744
  UDP    [::]:500               *:*                                    3544
  UDP    [::]:4500              *:*                                    3544
  UDP    [::]:5353              *:*                                    2240
  UDP    [::]:5355              *:*                                    2240
  UDP    [::]:49462             *:*                                    7380
  UDP    [::1]:1900             *:*                                    6744
  UDP    [::1]:58660            *:*                                    6744
  UDP    [fe80::5859:1a10:6493:f899%21]:1900  *:*                                    6744
  UDP    [fe80::5859:1a10:6493:f899%21]:58661  *:*                                    6744
  UDP    [fe80::899d:bdc8:315f:4efc%6]:1900  *:*                                    6744
  UDP    [fe80::899d:bdc8:315f:4efc%6]:58659  *:*                                    6744

**Comment by SeaHOH** [comment]
你现在运行肯定发现不了，你需要在出现 bind 失败时再运行。
`netstat -ano | findstr "1080"`

**Comment by HeviLUO** [comment]
![image](https://user-images.githubusercontent.com/13272362/46589658-c4511a00-cade-11e8-9b30-d5df3bd2a836.png)

**Comment by SeaHOH** [comment]
10013 是被拒绝，也可能是权限不够，虽然我没听说过有这种问题，但是你可以尝试用管理员权限运行。
或者有没有可能是被安全软件阻止？

**Comment by HeviLUO** [comment]
关闭防火墙，管理员权限运行，仍然如此

**Comment by SeaHOH** [comment]
不好意思，我对此无能为力。
你是否有运行国产软件？也许可以试试停用它们。

**Comment by en-one** [comment]
请问解决了吗。我也遇到了这个问题‘

**Comment by AnyWAT** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/2035#issuecomment-432512293
https://github.com/shadowsocks/shadowsocks-windows/issues/1835#issuecomment-386521869
https://github.com/shadowsocks/shadowsocks-windows/issues/1835#issuecomment-453528715

**Comment by ezineo** [comment]
原因是在win10最近的系统更新中将1080端口保留, x-tunnel由于无法bind 1080端口而启动失败,从而导致xx-net启动失败. 需要改动`xx-net/code/default/x_tunnel/local/client.py`, 打开此文件然后搜索`1080`, 然后改成未被占用的端口即可, 例如`10800`或者`10801`之类.

**Comment by AnyWAT** [comment]
> 原因是在win10最近的系统更新中将1080端口保留

![image](https://user-images.githubusercontent.com/37962734/58470666-c272be80-8174-11e9-8f9c-9ace22ea2f6e.png)

1080依旧正常
