### ISSUE TITLE
Manjaro 无法启动

### ISSUE THREAD

**Issue by Zhangxxl** [XX-net/XX-Net#11667]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？
是

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？
是

* 是否以相关关键词搜索过类似 issues？
是

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：
执行 `sudo ./start` 无法启动，但是程序通知区会空出来一个，里面没有图标无法点击，浏览器访问`http://127.0.0.1:8085`拒绝连接，此时终端扔有持续的扫描IP记录
`
下面是终端输出
➜ zhang@zhang-pc  /opt/XX-net  sudo ./start        
XX-Net version:3.12.10
11月 15 21:51:45.2 [launcher][INFO] Using PyGTK as the GUI Backend.
/opt/XX-net/code/default/launcher/gtk_tray.py:112: GtkWarning: 无法在模块路径中找到主题引擎：“murrine”，
  trayicon = gtk.StatusIcon()
11月 15 21:51:45.2 [launcher][INFO] Gtk.StatusIcon used.
11月 15 21:51:45.2 [launcher][INFO] import build-in openssl fail:AttributeError("'module' object has no attribute 'SSL_ST_INIT'",)
11月 15 21:51:45.2 [launcher][INFO] start XX-Net 3.12.10
11月 15 21:51:45.2 [launcher][DEBUG] start confirm_xxnet_exit
11月 15 21:51:45.2 [launcher][DEBUG] good, xxnet:8085 clear!
11月 15 21:51:45.2 [launcher][DEBUG] finished confirm_xxnet_exit
11月 15 21:51:45.3 [gae_proxy][INFO] ------------------------------------------------------
11月 15 21:51:45.3 [gae_proxy][INFO] Python Version     : 2.7.15
11月 15 21:51:45.3 [gae_proxy][INFO] OS                 : Dist:; Version:; ID:
11月 15 21:51:45.3 [gae_proxy][INFO] Listen Address     : 127.0.0.1:8087
11月 15 21:51:45.3 [gae_proxy][INFO] Using public APPID
11月 15 21:51:45.3 [gae_proxy][INFO] ------------------------------------------------------
11月 15 21:51:45.3 [gae_proxy][DEBUG] Importing CA
11月 15 21:51:45.3 [gae_proxy][DEBUG] Begin importing CA to Firefox
11月 15 21:51:45.3 [gae_proxy][INFO] Removing old cert to Firefox in /root/.mozilla/firefox/manjaro.default
GoAgent XX-Net - GoAgent                                     C,,  
11月 15 21:51:45.3 [gae_proxy][INFO] Add new cert to Firefox in /root/.mozilla/firefox/manjaro.default
11月 15 21:51:45.3 [gae_proxy][INFO] SSL use version:TLSv1_2
11月 15 21:51:45.3 [gae_proxy][INFO] OpenSSL support alpn
11月 15 21:51:45.3 [gae_proxy][INFO] load ip range file:/opt/XX-net/code/default/gae_proxy/local/ip_range.txt
11月 15 21:51:45.3 [gae_proxy][INFO] load ip_list num:54, target num:54
11月 15 21:51:45.3 [gae_proxy][INFO] SSL use version:TLSv1_2
11月 15 21:51:45.3 [gae_proxy][ERROR] bind to 127.0.0.1:8087 fail:error(98, '\xe5\x9c\xb0\xe5\x9d\x80\xe5\xb7\xb2\xe5\x9c\xa8\xe4\xbd\xbf\xe7\x94\xa8')
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/XX-net/code/default/gae_proxy/start.py", line 18, in main
    client.main(args)
  File "/opt/XX-net/code/default/gae_proxy/local/proxy.py", line 130, in main
    (listen_ip, front.config.listen_port), proxy_handler.GAEProxyHandler, logger=xlog)
  File "/opt/XX-net/code/default/python27/1.0/lib/noarch/simple_http_server.py", line 410, in __init__
    self.init_socket()
  File "/opt/XX-net/code/default/python27/1.0/lib/noarch/simple_http_server.py", line 420, in init_socket
    self.add_listen(addr)
  File "/opt/XX-net/code/default/python27/1.0/lib/noarch/simple_http_server.py", line 434, in add_listen
    raise Exception(err_string)
Exception: bind to 127.0.0.1:8087 fail:error(98, '\xe5\x9c\xb0\xe5\x9d\x80\xe5\xb7\xb2\xe5\x9c\xa8\xe4\xbd\xbf\xe7\x94\xa8')

11月 15 21:51:45.4 [gae_proxy][DEBUG] network IPv4 is ok, cost:187 ms
11月 15 21:51:46.6 [gae_proxy][DEBUG] network IPv6 is ok, cost:1389 ms
11月 15 21:51:55.1 [gae_proxy][INFO] scan_ip add ip:2402:800:6350:17::d time:1279 h2:0
11月 15 21:52:00.6 [gae_proxy][INFO] scan_ip add ip:2402:800:6350:f::e time:757 h2:0
11月 15 21:52:05.5 [gae_proxy][INFO] scan_ip add ip:2001:ee0:3201:10::f time:1063 h2:0
11月 15 21:52:05.9 [gae_proxy][INFO] scan_ip add ip:2404:6800:400e:4::7 time:527 h2:0
11月 15 21:52:10.7 [gae_proxy][INFO] scan_ip add ip:2405:4800:100:30::10 time:672 h2:0
11月 15 21:52:26.4 [gae_proxy][INFO] scan_ip add ip:2001:ee0:3202:6::13 time:661 h2:0
11月 15 21:52:29.3 [gae_proxy][INFO] scan_ip add ip:2001:ee0:3204:2::f time:785 h2:0
11月 15 21:52:32.3 [gae_proxy][INFO] scan_ip add ip:2001:ee0:3204::d time:789 h2:0

`
如果执行`ps -ef|grep python`
能看到如下进程(可能包含我电脑上的其他Python进程)：
`
root      7072  7057  0 21:51 pts/0    00:00:01 python2 code/default/launcher/start.py
zhang     7754  7731  0 21:57 pts/1    00:00:00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn python
zhang    11615 10336  0 21:30 ?        00:00:00 /usr/bin/python3 /usr/share/system-config-printer/applet.py
root     14359     1  0 21:43 ?        00:00:00 /usr/bin/python2 /usr/bin/supervisord -c /etc/supervisord.conf
root     14380 14365  0 21:43 ?        00:00:03 python2 code/default/launcher/start.py

`
* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by SeaHOH** [comment]
把两个 python2 进程结束掉，再运行一次。

**Comment by Zhangxxl** [comment]
可能是aur仓库的，重新从github下载了一份，没问题了
