### ISSUE TITLE
[Solved] 3.13.0  bind to 0.0.0.0:8085 fail:error(98, 'Address already in use')

### ISSUE THREAD

**Issue by cicite** [XX-net/XX-Net#11689]
我的Linux服务器没有显示器，也没有安装 X, Console 状态下也没有支持javacript的浏览器，所以需要手动设置。

更新了 git 库之后，需要首先打开8085的管理界面远程设置，我是在 data/launcher/config.yaml 中首先更改为 allow_remote_connect: 1， 然后启动start脚本，远程通过8085端口访问。

以前的版本正常，但是3.13.0 这样做后，出现  bind to 0.0.0.0:8085 fail:error(98, 'Address already in use')错误。（我确认8085端口没有被占用）。

请问，除了修改config.yaml中的allow_remote_connect: 1，还有其他地方需要同时也修改，才能在启动时直接打开0.0.0.0:8085吗？

BTW：8087端口远程访问没有问题。

2018-11-23 15:44:21.397 [smart_router][DEBUG] use local DNS server:192.168.0.1
2018-11-23 15:44:21.397 [smart_router][INFO] server 127.0.0.1:8086 started.
2018-11-23 15:44:21.398 [smart_router][INFO] Proxy server listen:127.0.0.1:8086.
2018-11-23 15:44:21.398 [smart_router][WARNING] bind DNS 127.0.0.1:53 fail
2018-11-23 15:44:21.398 [smart_router][INFO] start DNS server at 127.0.0.1:8053
2018-11-23 15:44:21.489 [launcher][INFO] module smart_router started
2018-11-23 15:44:21.489 [launcher][INFO] start smart_router time cost:111 ms
2018-11-23 15:44:21.490 [launcher][INFO] allow remote access WebUI
2018-11-23 15:44:21.490 [launcher][INFO] begin to start web control
2018-11-23 15:44:21.491 [launcher][INFO] server 127.0.0.1:8085 started.
2018-11-23 15:44:21.491 [launcher][ERROR] bind to 0.0.0.0:8085 fail:error(98, 'A                                       ddress already in use')
2018-11-23 15:44:21.491 [launcher][ERROR] launcher except:Exception("bind to 0.0                                       .0.0:8085 fail:error(98, 'Address already in use')",)
2018-11-23 15:44:21.496 [launcher][ERROR] Except stack:Traceback (most recent ca                                       ll last):
  File "code/default/launcher/start.py", line 251, in <module>
  File "code/default/launcher/start.py", line 231, in main
  File "/home/user/tmp/xx-net/code/default/launcher/web_control.py", line 709,                                        in start
    server = simple_http_server.HTTPServer(addresses, Http_Handler, logger=xlog)
  File "/home/user/tmp/xx-net/code/default/python27/1.0/lib/noarch/simple_http                                       _server.py", line 412, in __init__
    self.init_socket()
  File "/home/user/tmp/xx-net/code/default/python27/1.0/lib/noarch/simple_http                                       _server.py", line 422, in init_socket
    self.add_listen(addr)
  File "/home/user/tmp/xx-net/code/default/python27/1.0/lib/noarch/simple_http                                       _server.py", line 436, in add_listen
    raise Exception(err_string)
Exception: bind to 0.0.0.0:8085 fail:error(98, 'Address already in use')

Press Enter to continue...2018-11-23 15:44:22.341 [gae_proxy][DEBUG] network IPv                                       6 is ok, cost:1258 ms

**Comment by AnyWAT** [comment]
貌似 config.json 内得有 "listen_ip": "0.0.0.0"

**Comment by cicite** [comment]
我明确端口8085没有被占用。

因为我在本地没有X，没有支持JavaScript的浏览器，无法访问  http://127.0.0.1:8085/?module=launcher&menu=config， 必须先打开远程管理功能，才能进一步设置，以前的版本通过该config_yaml的参数是没有问题的。

**Comment by cicite** [comment]
> 
> 
> https://github.com/XX-net/XX-Net/wiki/AllowRemoteConnectToWebControl


我明确端口8085没有被占用。 因为我在本地没有X，没有支持JavaScript的浏览器，无法访问  http://127.0.0.1:8085/?module=launcher&menu=config， 必须先打开远程管理功能，才能进一步设置，以前的版本通过该config_yaml的参数是没有问题的。
--

**Comment by AnyWAT** [comment]
data/launcher/config.yaml
data/gae_proxy/config.json
在版本 code 之外，以前的版本正常，版本升级后理应还是正常😂

**Comment by cicite** [comment]
> 
> 
> data/launcher/config.yaml
> data/gae_proxy/config.json
> 在版本 code 之外，以前的版本正常，版本升级后理应还是正常😂

我是首先在原来的版本上直接git更新版本库后，出现上述问题，才另外单独测试了一下，出现了同样的问题，才在这里寻求帮助的。

**Comment by Cat7373** [comment]
试下`lsof -nPi:8005`看看是什么在占用？

**Comment by SeaHOH** [comment]
#11644 是这个没改好

@cicite 你试试替换上面这个修改到你的本地文件。

**Comment by cicite** [comment]
@SeaHOH 谢谢，在data/launcher/config.yaml 中 添加：

launcher: {control_ip: 0.0.0.0} 正常了。

谢谢！

**Comment by SeaHOH** [comment]
不是这个意思，我是说请你试试 9dce7659135d9c862947d408fde0f53158562f74 这个修复，就用`allow_remote`参数。

**Comment by styrenes** [comment]
楼主，8087在哪里？

**Comment by yichangshengwu** [comment]
Kernel: 4.19.8-2-MANJARO,
DE: Xfce,
同样的问题，

3.12.11下可以开启远程控制，3.13.0下则不行，
会提示：
2018-12-19 17:46:10.864 [launcher][ERROR] bind to 0.0.0.0:8085 fail:error(98, '\xe5\x9c\xb0\xe5\x9d\x80\xe5\xb7\xb2\xe5\x9c\xa8\xe4\xbd\xbf\xe7\x94\xa8')
2018-12-19 17:46:10.865 [launcher][ERROR] launcher except:Exception("bind to 0.0.0.0:8085 fail:error(98, '\\xe5\\x9c\\xb0\\xe5\\x9d\\x80\\xe5\\xb7\\xb2\\xe5\\x9c\\xa8\\xe4\\xbd\\xbf\\xe7\\x94\\xa8')",)
2018-12-19 17:46:10.867 [launcher][ERROR] Except stack:Traceback (most recent call last):
  File "code/3.13.0/launcher/start.py", line 251, in <module>
  File "code/3.13.0/launcher/start.py", line 231, in main
  File "/opt/xx-net/code/3.13.0/launcher/web_control.py", line 709, in start
    server = simple_http_server.HTTPServer(addresses, Http_Handler, logger=xlog)
  File "/opt/xx-net/code/3.13.0/python27/1.0/lib/noarch/simple_http_server.py", line 412, in __init__
    self.init_socket()
  File "/opt/xx-net/code/3.13.0/python27/1.0/lib/noarch/simple_http_server.py", line 422, in init_socket
    self.add_listen(addr)
  File "/opt/xx-net/code/3.13.0/python27/1.0/lib/noarch/simple_http_server.py", line 436, in add_listen
    raise Exception(err_string)
Exception: bind to 0.0.0.0:8085 fail:error(98, '\xe5\x9c\xb0\xe5\x9d\x80\xe5\xb7\xb2\xe5\x9c\xa8\xe4\xbd\xbf\xe7\x94\xa8')
Press Enter to continue...

试过 [9dce765](https://github.com/XX-net/XX-Net/commit/9dce7659135d9c862947d408fde0f53158562f74) 的修复，无效。
试过 @cicite 的方法，在 launcher: {} 中添加 control_ip: 0.0.0.0 ，无效。

**Comment by SeaHOH** [comment]
8a87c9e2029b32e5f8ee5b0f5c244207df66e3d2 修复 http sever
192bc18750c7e9edf9fe9f321608e639e2de5939 修复 smart_router dns sever

**Comment by yichangshengwu** [comment]
按照 [8a87c9e](https://github.com/XX-net/XX-Net/commit/8a87c9e2029b32e5f8ee5b0f5c244207df66e3d2) 的代码，可以了，
3.13.0 已经可以正常开启远程控制。
谢谢。
