### ISSUE TITLE
xx-net 安裝报错 ImportError: No module named pycparser

### ISSUE THREAD

**Issue by yehonghao** [XX-net/XX-Net#11687]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？

是
* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？
是

* 是否以相关关键词搜索过类似 issues？
是

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志：

* 如果问题得到解决，请务必回复相关情况，谢谢。

11月 22 22:39:40.0 - [INFO] Using PyGObject as the GUI Backend.
11月 22 22:39:40.1 - [INFO] Gtk.StatusIcon used.
11月 22 22:39:40.1 - [INFO] import build-in openssl fail:ImportError('No module named pycparser',)
11月 22 22:39:40.1 - [ERROR] import system python-OpenSSL fail:ImportError('No module named pycparser',)
11月 22 22:39:40.1 - [ERROR] Except stack:Traceback (most recent call last):
  File "code/default/launcher/start.py", line 175, in <module>
    import OpenSSL
  File "/home/yehoha/XX-Net-3.12.11/code/default/python27/1.0/lib/noarch/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/home/yehoha/XX-Net-3.12.11/code/default/python27/1.0/lib/noarch/OpenSSL/rand.py", line 12, in <module>
    from OpenSSL._util import (
  File "/home/yehoha/XX-Net-3.12.11/code/default/python27/1.0/lib/noarch/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/home/yehoha/XX-Net-3.12.11/code/default/python27/1.0/lib/linux/cryptography/hazmat/bindings/openssl/binding.py", line 60, in <module>
    class Binding(object):
  File "/home/yehoha/XX-Net-3.12.11/code/default/python27/1.0/lib/linux/cryptography/hazmat/bindings/openssl/binding.py", line 109, in Binding
    libraries=_get_libraries(sys.platform)
  File "/home/yehoha/XX-Net-3.12.11/code/default/python27/1.0/lib/linux/cryptography/hazmat/bindings/utils.py", line 97, in build_ffi_for_binding
    extra_link_args=extra_link_args,
  File "/home/yehoha/XX-Net-3.12.11/code/default/python27/1.0/lib/linux/cryptography/hazmat/bindings/utils.py", line 105, in build_ffi
    ffi = FFI()
  File "/home/yehoha/XX-Net-3.12.11/code/default/python27/1.0/lib/linux/cffi/api.py", line 52, in __init__
    from . import cparser, model
  File "/home/yehoha/XX-Net-3.12.11/code/default/python27/1.0/lib/linux/cffi/cparser.py", line 6, in <module>
    import pycparser
ImportError: No module named pycparser

看过issues同类问题，系统版本 Linux manjaro 4.19.2-1-MANJARO #1 SMP PREEMPT Tue Nov 13 22:35:25 UTC 2018 x86_64 GNU/Linux

[yehoha@manjaro XX-Net-3.12.11]$ pip install pyopenssl
Requirement already satisfied: pyopenssl in /usr/lib/python3.7/site-packages (18.0.0)
Requirement already satisfied: cryptography>=2.2.1 in /usr/lib/python3.7/site-packages (from pyopenssl) (2.4.2)
Requirement already satisfied: six>=1.5.2 in /usr/lib/python3.7/site-packages (from pyopenssl) (1.11.0)
Requirement already satisfied: cffi!=1.11.3,>=1.7 in /usr/lib/python3.7/site-packages (from cryptography>=2.2.1->pyopenssl) (1.11.5)
Requirement already satisfied: asn1crypto>=0.21.0 in /usr/lib/python3.7/site-packages (from cryptography>=2.2.1->pyopenssl) (0.24.0)
Requirement already satisfied: idna>=2.1 in /usr/lib/python3.7/site-packages (from cryptography>=2.2.1->pyopenssl) (2.7)
Requirement already satisfied: pycparser in /usr/lib/python3.7/site-packages (from cffi!=1.11.3,>=1.7->cryptography>=2.2.1->pyopenssl) (2.19)

**Comment by SeaHOH** [comment]
不支持 Python 3

**Comment by zhmars** [comment]
目前 XX-Net 只支持 Python2，Arch/Manjaro 默认 `python & pip`  使用的是 Python3

XX-net 在 Arch 下运行安装两个包 `pacman -S python2-pycparser python2-pyopenssl`，建议安装后再试试

**Comment by yehonghao** [comment]
@SeaHOH @zhmars  感谢两位回复 已解决
