### ISSUE TITLE
upload fail:BadStatusLine("''",)

### ISSUE THREAD

**Issue by jasonzhouu** [XX-net/XX-Net#11695]
2018-07-21 23:07:16,763 - root - INFO - set proxy to http://127.0.0.1:8087
2018-07-21 23:07:16,764 - root - INFO - ============ Begin upload ============
2018-07-21 23:07:16,764 - root - INFO - appid:xnet52156
2018-07-21 23:07:16,777 - root - INFO - Send: /api/appversion/rollback, params={'version': '1', 'app_id': 'xnet52156'}
2018-07-21 23:07:16,800 - root - ERROR - upload fail:BadStatusLine("''",)
Traceback (most recent call last):
File "/Users/caochenghua/Downloads/XX-Net-3.12.10/code/default/gae_proxy/server/uploader.py", line 72, in upload
result = appcfg.AppCfgApp(['appcfg', 'rollback', '--oauth2_credential_file', cookie_file, dirname]).Run()
File "/Users/caochenghua/Downloads/XX-Net-3.12.10/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 2951, in Run
self.action(self)
File "/Users/caochenghua/Downloads/XX-Net-3.12.10/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 5044, in __call__
return method()
File "/Users/caochenghua/Downloads/XX-Net-3.12.10/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 4397, in Rollback
self._Rollback()
File "/Users/caochenghua/Downloads/XX-Net-3.12.10/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 4442, in _Rollback
appversion.Rollback(force_rollback)
File "/Users/caochenghua/Downloads/XX-Net-3.12.10/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 2362, in Rollback
force_rollback='1' if force_rollback else '0')
File "/Users/caochenghua/Downloads/XX-Net-3.12.10/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 1696, in Send
result = self.rpcserver.Send(url, payload=payload, **kwargs)
File "/Users/caochenghua/Downloads/XX-Net-3.12.10/code/default/gae_proxy/server/lib/google/appengine/tools/appengine_rpc_httplib2.py", line 247, in Send
url, method=method, body=payload, headers=headers)
File "/Users/caochenghua/Downloads/XX-Net-3.12.10/code/default/gae_proxy/server/lib/httplib2/__init__.py", line 1593, in request
(response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
File "/Users/caochenghua/Downloads/XX-Net-3.12.10/code/default/gae_proxy/server/lib/httplib2/__init__.py", line 1341, in _request
(response, content) = self._conn_request(conn, request_uri, method, body, headers)
File "/Users/caochenghua/Downloads/XX-Net-3.12.10/code/default/gae_proxy/server/lib/httplib2/__init__.py", line 1311, in _conn_request
response = conn.getresponse()
File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1121, in getresponse
response.begin()
File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 438, in begin
version, status, reason = self._read_status()
File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 402, in _read_status
raise BadStatusLine(line)
BadStatusLine: ''
2018-07-21 23:07:16,802 - root - INFO - Retry 1 time...
2018-07-21 23:07:16,814 - root - INFO - Send: /api/appversion/rollback, params={'version': '1', 'app_id': 'xnet52156'}
2018-07-21 23:07:16,836 - root - ERROR - upload fail:BadStatusLine("''",)
Traceback (most recent call last):
File "/Users/caochenghua/Downloads/XX-Net-3.12.10/code/default/gae_proxy/server/uploader.py", line 72, in upload
result = appcfg.AppCfgApp(['appcfg', 'rollback', '--oauth2_credential_file', cookie_file, dirname]).Run()
File "/Users/caochenghua/Downloads/XX-Net-3.12.10/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 2951, in Run
self.action(self)
File "/Users/caochenghua/Downloads/XX-Net-3.12.10/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 5044, in __call__
return method()
File "/Users/caochenghua/Downloads/XX-Net-3.12.10/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 4397, in Rollback
self._Rollback()
File "/Users/caochenghua/Downloads/XX-Net-3.12.10/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 4442, in _Rollback
appversion.Rollback(force_rollback)
File "/Users/caochenghua/Downloads/XX-Net-3.12.10/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 2362, in Rollback
force_rollback='1' if force_rollback else '0')
File "/Users/caochenghua/Downloads/XX-Net-3.12.10/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 1696, in Send
result = self.rpcserver.Send(url, payload=payload, **kwargs)
File "/Users/caochenghua/Downloads/XX-Net-3.12.10/code/default/gae_proxy/server/lib/google/appengine/tools/appengine_rpc_httplib2.py", line 247, in Send
url, method=method, body=payload, headers=headers)
File "/Users/caochenghua/Downloads/XX-Net-3.12.10/code/default/gae_proxy/server/lib/httplib2/__init__.py", line 1593, in request
(response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
File "/Users/caochenghua/Downloads/XX-Net-3.12.10/code/default/gae_proxy/server/lib/httplib2/__init__.py", line 1341, in _request
(response, content) = self._conn_request(conn, request_uri, method, body, headers)
File "/Users/caochenghua/Downloads/XX-Net-3.12.10/code/default/gae_proxy/server/lib/httplib2/__init__.py", line 1311, in _conn_request
response = conn.getresponse()
File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1121, in getresponse
response.begin()
File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 438, in begin
version, status, reason = self._read_status()
File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 402, in _read_status
raise BadStatusLine(line)
BadStatusLine: ''
2018-07-21 23:07:16,836 - root - INFO - Retry 2 time...
2018-07-21 23:07:17,857 - root - INFO - Send: /api/appversion/rollback, params={'version': '1', 'app_id': 'xnet52156'}
2018-07-21 23:07:17,878 - root - ERROR - upload fail:BadStatusLine("''",)
Traceback (most recent call last):
File "/Users/caochenghua/Downloads/XX-Net-3.12.10/code/default/gae_proxy/server/uploader.py", line 72, in upload
result = appcfg.AppCfgApp(['appcfg', 'rollback', '--oauth2_credential_file', cookie_file, dirname]).Run()
File "/Users/caochenghua/Downloads/XX-Net-3.12.10/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 2951, in Run
self.action(self)
File "/Users/caochenghua/Downloads/XX-Net-3.12.10/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 5044, in __call__
return method()
File "/Users/caochenghua/Downloads/XX-Net-3.12.10/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 4397, in Rollback
self._Rollback()
File "/Users/caochenghua/Downloads/XX-Net-3.12.10/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 4442, in _Rollback
appversion.Rollback(force_rollback)
File "/Users/caochenghua/Downloads/XX-Net-3.12.10/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 2362, in Rollback
force_rollback='1' if force_rollback else '0')
File "/Users/caochenghua/Downloads/XX-Net-3.12.10/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 1696, in Send
result = self.rpcserver.Send(url, payload=payload, **kwargs)
File "/Users/caochenghua/Downloads/XX-Net-3.12.10/code/default/gae_proxy/server/lib/google/appengine/tools/appengine_rpc_httplib2.py", line 247, in Send
url, method=method, body=payload, headers=headers)
File "/Users/caochenghua/Downloads/XX-Net-3.12.10/code/default/gae_proxy/server/lib/httplib2/__init__.py", line 1593, in request
(response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
File "/Users/caochenghua/Downloads/XX-Net-3.12.10/code/default/gae_proxy/server/lib/httplib2/__init__.py", line 1341, in _request
(response, content) = self._conn_request(conn, request_uri, method, body, headers)
File "/Users/caochenghua/Downloads/XX-Net-3.12.10/code/default/gae_proxy/server/lib/httplib2/__init__.py", line 1311, in _conn_request
response = conn.getresponse()
File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1121, in getresponse
response.begin()
File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 438, in begin
version, status, reason = self._read_status()
File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 402, in _read_status
raise BadStatusLine(line)
BadStatusLine: ''
2018-07-21 23:07:17,879 - root - INFO - Retry 3 time...
2018-07-21 23:07:19,884 - root - INFO - =======================
2018-07-21 23:07:19,884 - root - INFO - Deploy failed appid list:
2018-07-21 23:07:19,884 - root - INFO - - xnet52156
2018-07-21 23:07:19,885 - root - INFO - == END ==

_Originally posted by @hopesala in https://github.com/XX-net/XX-Net/issues/521#issuecomment-406803245_

**Comment by jasonzhouu** [comment]
日志中我觉得最重要的内容是：

```
2018-11-27 00:21:31,645 - google.appengine.tools.appengine_rpc - DEBUG - Sending request to
https://appengine.google.com/api/appversion/rollback?app_id=************&force_rollback=0&version=1
headers={'X-appcfg-api-version': '1', 'content-length': '0', 'Content-Type': 'application/octet-stream'} body=

2018-11-27 00:21:32,016 - root - ERROR - upload fail:BadStatusLine("''",)
ERROR - upload fail:BadStatusLine("''",)
```

表示给 https://appengine.google.com/api/appversion/rollback 上传数据的时候失败
之后自动重试3次，然后停止。

背景：
- 部署时我开着shadowsocks，可以正常访问谷歌
- 并且在 https://myaccount.google.com/security 设置了`Allow less secure apps: ON`

**Comment by SeaHOH** [comment]
如果要用 shadowsocks 上传部署，需要设置代理端口为 1080。
然后关闭 XX-Net 的情况下，进入 gae_proxy/server 目录执行上传，方法此目录下有介绍。

**Comment by binghust** [comment]
遇到了和楼主相同的问题，原因可能是浏览器部署时无法访问Google，所以不能打开账户Google登录界面，导致无法部署。后来尝试了以下步骤得到解决：
1. 查看翻墙软件的代理端口，我使用的是赛风:https://s3.amazonaws.com/psiphon/web/u1dy-me41-s9yv/psiphon3.exe，在设置界面里，我设置本地代理端口为52008，然后启动翻墙软件。
2. 在xx-net的安装目录下找到文件夹：XX-Net-3.13.3\code\default\gae_proxy\server，打开uploader.py文件，文末有2处端口号8087，改成52008，保存。
3. 打开README.md文件，根据说明文件输入命令行，开始部署。稍候即可见到Google账户登录界面。登录后，等待cmd程序运行结束，即可完成部署。
