### ISSUE TITLE
xx-net运行过程中的错误error日志

### ISSUE THREAD

**Issue by muxideweidao** [XX-net/XX-Net#11708]
2018-12-01 14:51:43.409 [simple_http_server][ERROR] handler:'Req command format fail:)\x02\xe0\x01' cmd:None path:mtalk.google.com:443 from:127.0.0.1:1971
2018-12-01 14:51:43.413 [simple_http_server][ERROR] Except stack:Traceback (most recent call last):
  File "C:\Users\Admin\Documents\XX-Net-3.13.0\code\default\python27\1.0\lib\noarch\simple_http_server.py", line 159, in handle_one_request
    self.parse_request()
  File "C:\Users\Admin\Documents\XX-Net-3.13.0\code\default\python27\1.0\lib\noarch\simple_http_server.py", line 140, in parse_request
    raise ParseReqFail("Req command format fail:%s" % requestline)
ParseReqFail: 'Req command format fail:)\x02\xe0\x01'

**Comment by SeaHOH** [comment]
mtalk 这个我记得端口不是 433，而且 gae_proxy 也不支持代理这种流量，你可能哪里**强制**设置错误了。

这个域名可以使用 X-Tunnel。
