### ISSUE TITLE
Linux Memory Leak ?

### ISSUE THREAD

**Issue by Anudorannador** [XX-net/XX-Net#11729]
Linux 系统，我试过，包括 Ubuntu 18.04, Arch 以及 CentOS 7，长时间运行，内存使用会暴增：

```
[root@Anudor-OfficeServer ~]# systemctl status xx-net
● xx-net.service - XX-Net
   Loaded: loaded (/etc/systemd/system/xx-net.service; disabled; vendor preset: disabled)
   Active: active (running) since 五 2018-12-07 17:55:33 CST; 2 days ago
 Main PID: 21251 (start)
    Tasks: 515
   Memory: 11.6G
   CGroup: /system.slice/xx-net.service
           ├─21251 /bin/sh /opt/XX-Net/start
           └─21265 python code/default/launcher/start.py
```

周五开的，然后星期一过来就占用 11.6G 了……

**Comment by SeaHOH** [comment]
是不是使用了智能代理？ #11340 
顺便报下 XX-Net 版本。

**Comment by Anudorannador** [comment]
没有使用智能代理，就只开了 gae, 另外，版本 3.13.0 (a58f3b7feca132d33c0af26e38eae1c67cc61cf9)，之前的版本都有，貌似，3.10 就开始了，我一直没太关注，每次都重启，但是一直有，以前是我个人机器无所谓，而且我把 XX-Net 放到我的服务器上了，次影响到我整个服务器了，我才提交……

**Comment by SeaHOH** [comment]
Python 多少位的？如果是 64，试试 32。
还有试试不要作为服务运行。

**Comment by SeaHOH** [comment]
还有，把 XX-Net 安装到内网服务器还好，如果是在公网上，实在不是一个好选择。
公网上的服务器可以使用其它更合适的工具，不论是墙内还墙外。

**Comment by Anudorannador** [comment]
32位的我没试，不想在服务器上做 multi-lib。不作为服务运行，依然会内存暴涨，这个我之前有印象。我这台服务器就在我旁边，我自己私人网络用的。

**Comment by SeaHOH** [comment]
用容器打包试试，可以隔离系统环境。

**Comment by Anudorannador** [comment]
给个 Dockerfile 或者 docker-compose.yml 咯，我这个 docker-compose.yml 失败了。

```
version: "3.7"

services:
  xx-net:
    image: python:2.7
    volumes:
      - ./:/opt/XX-Net
    command: bash -c "apt-get update && apt-get install -y python-openssl python-pycparser && /opt/XX-Net/start"
    container_name: xx-net
    ports:
      - "8087:8087"
      - "8085:8085"
```

日志：

```
# docker logs -f  xx-net   
Get:1 http://security.debian.org/debian-security stretch/updates InRelease [94.3 kB]
Ign:2 http://deb.debian.org/debian stretch InRelease
Get:3 http://deb.debian.org/debian stretch-updates InRelease [91.0 kB]
Get:4 http://deb.debian.org/debian stretch Release [118 kB]
# .... 省略一大堆安装信息
Setting up python-setuptools (33.1.1-1) ...
Setting up python-pycparser (2.17-2) ...
Setting up python-cryptography (1.7.1-3) ...
Setting up python-openssl (16.2.0-1) ...
XX-Net version:3.13.0
Installing pyOpenSSL for your system... Please type in your password if requested
/opt/XX-Net/start: 89: /opt/XX-Net/start: sudo: not found
2018-12-11 07:05:19.183 [launcher][INFO] import build-in openssl fail:ImportError('No module named pycparser',)
2018-12-11 07:05:19.187 [launcher][ERROR] import system python-OpenSSL fail:ImportError('No module named pycparser',)
2018-12-11 07:05:19.188 [launcher][ERROR] Except stack:Traceback (most recent call last):
  File "code/default/launcher/start.py", line 175, in <module>
    import OpenSSL
  File "/opt/XX-Net/code/default/python27/1.0/lib/noarch/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/opt/XX-Net/code/default/python27/1.0/lib/noarch/OpenSSL/rand.py", line 12, in <module>
    from OpenSSL._util import (
  File "/opt/XX-Net/code/default/python27/1.0/lib/noarch/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/opt/XX-Net/code/default/python27/1.0/lib/linux/cryptography/hazmat/bindings/openssl/binding.py", line 60, in <module>
    class Binding(object):
  File "/opt/XX-Net/code/default/python27/1.0/lib/linux/cryptography/hazmat/bindings/openssl/binding.py", line 109, in Binding
    libraries=_get_libraries(sys.platform)
  File "/opt/XX-Net/code/default/python27/1.0/lib/linux/cryptography/hazmat/bindings/utils.py", line 97, in build_ffi_for_binding
    extra_link_args=extra_link_args,
  File "/opt/XX-Net/code/default/python27/1.0/lib/linux/cryptography/hazmat/bindings/utils.py", line 105, in build_ffi
    ffi = FFI()
  File "/opt/XX-Net/code/default/python27/1.0/lib/linux/cffi/api.py", line 52, in __init__
    from . import cparser, model
  File "/opt/XX-Net/code/default/python27/1.0/lib/linux/cffi/cparser.py", line 6, in <module>
    import pycparser
ImportError: No module named pycparser

2018-12-11 07:05:19.188 [launcher][ERROR] uncaught Exception, type=<type 'exceptions.EOFError'> value=EOF when reading a line traceback:<traceback object at 0x7f49ee271878>
Try install python-openssl

Press Enter to continue...('uncaught Exception:', <type 'exceptions.EOFError'>, EOFError('EOF when reading a line',), <traceback object at 0x7f49ee271878>)
```

**Comment by SeaHOH** [comment]
估计还需要`pip install pyopenssl`。

我也没用过，如果你实在也搞不定就算了。
32 bit 的应该没有问题，毕竟这么久了也没见谁报过 gae_proxy 模块有内存泄漏。
