### ISSUE TITLE
关于2.5.1稳定版的问题

### ISSUE THREAD

**Issue by northleafup** [XX-net/XX-Net#1177]
我之前用的2.3.0稳定版，发现有更新，手动下载了2.5.1稳定版，下载后，启动，部署后（部署没有问题），以下为版本信息：
Property	Value
XX-Net Version	2.5.1
Python Version	2.7.10
Sys Platform	x86_64, Darwin-15.0.0-x86_64-i386-64bit
OS System	Darwin
但一直ping不通google,偶尔可以Ping通一下
Request timeout for icmp_seq 872
Request timeout for icmp_seq 873
Request timeout for icmp_seq 874
Request timeout for icmp_seq 875
Request timeout for icmp_seq 876
Request timeout for icmp_seq 877
Request timeout for icmp_seq 878
Request timeout for icmp_seq 879
Request timeout for icmp_seq 880
Request timeout for icmp_seq 881
Request timeout for icmp_seq 882
日志报出以下错误：
Oct  9 16:27:23 - [WARNING] socket error:SSLError(1, u'[SSL: SSLV3_ALERT_BAD_CERTIFICATE] sslv3 alert bad certificate (_ssl.c:1752)')
Oct  9 16:27:23 - [WARNING] socket error:SSLError(1, u'[SSL: SSLV3_ALERT_BAD_CERTIFICATE] sslv3 alert bad certificate (_ssl.c:1752)')
Oct  9 16:27:24 - [INFO] GAE CONNECT www.google-analytics.com:443 
Oct  9 16:27:24 - [INFO] GAE CONNECT www.google-analytics.com:443 
Oct  9 16:27:24 - [ERROR] ssl.wrap_socket(self.connection=<ssl.SSLSocket object at 0x10b646230>) failed: [SSL: SSLV3_ALERT_BAD_CERTIFICATE] sslv3 alert bad certificate (_ssl.c:1752) path:www.google-analytics.com:443, errno:1
Oct  9 16:27:24 - [ERROR] Except stack:Traceback (most recent call last):
  File "/Users/hanyimin/Documents/tool/e_Net/XX-Net-2.5.1/gae_proxy/local/proxy_handler.py", line 214, in do_CONNECT_AGENT
    self.raw_requestline = self.rfile.readline(65537)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 734, in recv
    return self.read(buflen)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 621, in read
    v = self._sslobj.read(len or 1024)
SSLError: [SSL: SSLV3_ALERT_BAD_CERTIFICATE] sslv3 alert bad certificate (_ssl.c:1752)

Oct  9 16:27:24 - [ERROR] ssl.wrap_socket(self.connection=<ssl.SSLSocket object at 0x10d607578>) failed: [SSL: SSLV3_ALERT_BAD_CERTIFICATE] sslv3 alert bad certificate (_ssl.c:1752) path:www.google-analytics.com:443, errno:1
Oct  9 16:27:24 - [WARNING] socket error:SSLError(1, u'[SSL: SSLV3_ALERT_BAD_CERTIFICATE] sslv3 alert bad certificate (_ssl.c:1752)')
Oct  9 16:27:24 - [ERROR] Except stack:Traceback (most recent call last):
  File "/Users/hanyimin/Documents/tool/e_Net/XX-Net-2.5.1/gae_proxy/local/proxy_handler.py", line 214, in do_CONNECT_AGENT
    self.raw_requestline = self.rfile.readline(65537)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 734, in recv
    return self.read(buflen)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 621, in read
    v = self._sslobj.read(len or 1024)
SSLError: [SSL: SSLV3_ALERT_BAD_CERTIFICATE] sslv3 alert bad certificate (_ssl.c:1752)

还请协助解决，谢谢。

**Comment by xxnet** [comment]
这提示是证书问题，请确认证书正确导入

2015-10-09 16:32 GMT+08:00 northleafup <notifications@github.com>:

**Comment by northleafup** [comment]
谢谢，重新导入证书后，问题解决。
