### ISSUE TITLE
无法监听`::`

### ISSUE THREAD

**Issue by wooowooo** [XX-net/XX-Net#11817]
3.13.1
智能路由
`  "proxy_bind_ip": ["::", "0.0.0.0"], ` 不监听`::`，也没有报错。`::1`却可以

**Comment by SeaHOH** [comment]
怎么判断的？监听`::`会显示为`0:0:0:0:0:0:0:0`。

**Comment by wooowooo** [comment]
从系统中看，（linux的ss命令）

**Comment by wooowooo** [comment]
`ss -tln|grep 8086`


```
"proxy_bind_ip": ["::"], 

2018-12-23 10:47:19.241 [smart_router][INFO] Proxy server listen::::8086.

无
```


```
"proxy_bind_ip": ["::0"], 

2018-12-23 10:48:24.785 [smart_router][INFO] server ::0:8086 started.
2018-12-23 10:48:24.785 [smart_router][INFO] Proxy server listen:::0:8086.

LISTEN     0      128          *:8086                     *:*
```
这样能用了


```
"proxy_bind_ip": ["::0", "0.0.0.0"],

2018-12-23 10:50:53.792 [smart_router][INFO] server 0.0.0.0:8086 started.
2018-12-23 10:50:53.792 [smart_router][ERROR] bind to ::0:8086 fail:error(98, '\xe5\x9c\xb0\xe5\x9d\x80\xe5\xb7\xb2\xe5\x9c\xa8\xe4\xbd\xbf\xe7\x94\xa8')
Exception in thread Thread-78:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "XX-Net/code/3.13.1/smart_router/start.py", line 19, in main
    client.run(args)
  File "XX-Net/code/3.13.1/smart_router/local/__init__.py", line 134, in run
    proxy_handler.ProxyServer, logger=xlog)
  File "XX-Net/code/3.13.1/python27/1.0/lib/noarch/simple_http_server.py", line 412, in __init__
    self.init_socket()
  File "XX-Net/code/3.13.1/python27/1.0/lib/noarch/simple_http_server.py", line 430, in init_socket
    self.add_listen((ip, port))
  File "XX-Net/code/3.13.1/python27/1.0/lib/noarch/simple_http_server.py", line 444, in add_listen
    raise Exception(err_string)
Exception: bind to ::0:8086 fail:error(98, '\xe5\x9c\xb0\xe5\x9d\x80\xe5\xb7\xb2\xe5\x9c\xa8\xe4\xbd\xbf\xe7\x94\xa8')
```


```
"proxy_bind_ip": ["::", "0.0.0.0"], 

2018-12-23 10:53:17.100 [smart_router][INFO] server 0.0.0.0:8086 started.
2018-12-23 10:53:17.101 [smart_router][INFO] Proxy server listen:0.0.0.0:8086.

LISTEN     0      128    0.0.0.0:8086               0.0.0.0:*
```

`::`被忽略，`::0`包含4和6
