### ISSUE TITLE
突然无法正常启动。

### ISSUE THREAD

**Issue by qq938403611** [XX-net/XX-Net#1184]
打开后状态页空白
cmd不断刷新如下提示。。
Exception happened during processing of request from ('127.0.0.1', 49908)
Traceback (most recent call last):
  File "D:\XX-Net-2.4.0\python27\1.0\lib\SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "D:\XX-Net-2.4.0\launcher\web_control.py", line 48, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "D:\XX-Net-2.4.0\python27\1.0\lib\SocketServer.py", line 649, in __init__
    self.handle()
  File "D:\XX-Net-2.4.0\python27\1.0\lib\BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "D:\XX-Net-2.4.0\python27\1.0\lib\BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "D:\XX-Net-2.4.0\launcher\web_control.py", line 143, in do_GET
    controler = module_init.proc_handler[module]["imp"].local.web_control.ControlHandler(self.client_address, self.headers, self.command, path, self.rfile, self.wfile)
KeyError: 'imp'
----------------------------------------
哪出问题了？

**Comment by Lrevor** [comment]
重新下载

**Comment by simonasd** [comment]
事发前是刚刚升级过吗？好像原先的自动升级算法有点问题，不知道是否与此相关，尝试重新下载，然后把data目录拷过去。

**Comment by qq938403611** [comment]
OTL，原来那个自动升级真的有用？，，从来没自己更新过，好不容易自动一次还出错，，

**Comment by simonasd** [comment]
@qq938403611 哈哈，我也只是这么推测。

**Comment by meitianxiaoxu** [comment]
@qq938403611 我也是这个问题，我重装后还是这个问题，不知道咋办

**Comment by xxnet** [comment]
用start.bat 启动，看刚启动的日志，一开始异常了，后面就无法工作

在 2015年10月11日 下午9:34，meitianxiaoxu <notifications@github.com>写道：
