### ISSUE TITLE
昨天开始就上不去了，XXNET信息里全空了，怎么回事？

### ISSUE THREAD

**Issue by tq01o3n** [XX-net/XX-Net#1191]
之前好好的呢

D:\My Documents\soft\XX-Net-2.3.0>SET PYTHONPATH=

D:\My Documents\soft\XX-Net-2.3.0>"D:\My Documents\soft\XX-Net-2.3.0\python27/1.
0/python.exe" "D:\My Documents\soft\XX-Net-2.3.0\launcher/start.py"
Oct 10 21:01:12 - [DEBUG] start confirm_xxnet_exit
Oct 10 21:01:13 - [ERROR] start module gae_proxy fail:No option 'ip_traffic_quot
a' in section: 'google_ip'
Traceback (most recent call last):
  File "D:\My Documents\soft\XX-Net-2.3.0\launcher\module_init.py", line 36, in
start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['loca
l', 'start'], -1)
  File "D:\My Documents\soft\XX-Net-2.3.0\gae_proxy\start.py", line 14, in <modu
le>
    import local.proxy as client
  File "D:\My Documents\soft\XX-Net-2.3.0\gae_proxy\local\proxy.py", line 77, in
 <module>
    from cert_util import CertUtil
  File "D:\My Documents\soft\XX-Net-2.3.0\gae_proxy\local\cert_util.py", line 44
, in <module>
    from config import config
  File "D:\My Documents\soft\XX-Net-2.3.0\gae_proxy\local\config.py", line 129,
in <module>
    config.load()
  File "D:\My Documents\soft\XX-Net-2.3.0\gae_proxy\local\config.py", line 116,
in load
    self.ip_traffic_quota = self.CONFIG.getint('google_ip', 'ip_traffic_quota')
  File "D:\My Documents\soft\XX-Net-2.3.0\python27\1.0\lib\ConfigParser.py", lin
e 359, in getint
    return self._get(section, int, option)
  File "D:\My Documents\soft\XX-Net-2.3.0\python27\1.0\lib\ConfigParser.py", lin
e 356, in _get
    return conv(self.get(section, option))
  File "D:\My Documents\soft\XX-Net-2.3.0\python27\1.0\lib\ConfigParser.py", lin
e 618, in get
    raise NoOptionError(option, section)
NoOptionError: No option 'ip_traffic_quota' in section: 'google_ip'

Oct 10 21:01:13 - [INFO] start gae_proxy time cost 88
Oct 10 21:01:14 - [INFO] get uuid:270d29d6-5b26-43db-bc4b-434c0551daea
Oct 10 21:01:15 - [WARNING] check_update fail:URLError(error(10061, ''),)
Oct 10 21:01:15 - [INFO] download https://raw.githubusercontent.com/XX-net/XX-Ne
t/master/README.md to D:\My Documents\soft\XX-Net-2.3.0\data\downloads\README.md

**Comment by xxnet** [comment]
估计升级部分失败，请手动下载覆盖

2015-10-10 21:06 GMT+08:00 tq01o3n <notifications@github.com>:

**Comment by panzer1313208** [comment]
感觉这个升级有点问题，我一般都是导出IP，然后删了电脑里的XXNET，重新下载最新的，然后直接配置Appid然后导入IP即可。

**Comment by tq01o3n** [comment]
谢谢大家，怎么不能引用楼上这些答复

**Comment by tq01o3n** [comment]
@panzer1313208 我看了下，导出IP那页空框里是空的，怎么导出IP？

**Comment by simonasd** [comment]
@tq01o3n 你可以直接把旧版的data文件夹复制到新版本中，所有的设置和扫描到的IP都会保留。

**Comment by tq01o3n** [comment]
@simonasd thks，很遗憾，我已经删除了，但遇到新问题，总是提示找不到pythonw.exe，怎么回事？

**Comment by tq01o3n** [comment]
问下，我试图把QQ群里下载的IP包导入到新版本里，提示“成功导入0个IP.”怎么回事？这个IP在老版本里能成功导入的

**Comment by tq01o3n** [comment]
@simonasd 晕死~搞反了，我是新版本覆盖旧版本，重新来过！幸亏有备份
