### ISSUE TITLE
NoOptionError

### ISSUE THREAD

**Issue by GITHUBAbelard** [XX-net/XX-Net#1193]
Traceback (most recent call last):
  File "D:\XX-Net-2.4.0\launcher\module_init.py", line 36, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "D:\XX-Net-2.4.0\gae_proxy\start.py", line 14, in <module>
    import local.proxy as client
  File "D:\XX-Net-2.4.0\gae_proxy\local\proxy.py", line 77, in <module>
    from cert_util import CertUtil
  File "D:\XX-Net-2.4.0\gae_proxy\local\cert_util.py", line 44, in <module>
    from config import config
  File "D:\XX-Net-2.4.0\gae_proxy\local\config.py", line 129, in <module>
    config.load()
  File "D:\XX-Net-2.4.0\gae_proxy\local\config.py", line 116, in load
    self.ip_traffic_quota = self.CONFIG.getint('google_ip', 'ip_traffic_quota')
  File "D:\XX-Net-2.4.0\python27\1.0\lib\ConfigParser.py", line 359, in getint
    return self._get(section, int, option)
  File "D:\XX-Net-2.4.0\python27\1.0\lib\ConfigParser.py", line 356, in _get
    return conv(self.get(section, option))
  File "D:\XX-Net-2.4.0\python27\1.0\lib\ConfigParser.py", line 618, in get
    raise NoOptionError(option, section)
NoOptionError: No option 'ip_traffic_quota' in section: 'google_ip'

**Comment by xxnet** [comment]
一般是升级不完全，请重新下载新版覆盖

2015-10-10 23:01 GMT+08:00 GITHUBAbelard <notifications@github.com>:
