### ISSUE TITLE
反馈3.13.1 程序报错 gae_handler.handler AttributeError("'BaseResponse' object has no attribute 'ssl_sock'"

### ISSUE THREAD

**Issue by mtgitnerd** [XX-net/XX-Net#11943]
2018-12-30 12:16:18.037 - [ERROR] gae_handler.handler AttributeError("'BaseResponse' object has no attribute 'ssl_sock'",) https://www.google.com/ , retry...

2018-12-30 12:16:18.038 - [ERROR] Except stack:Traceback (most recent call last): File "D:\Programs\XX-Net\code\default\gae_proxy\local\gae_handler.py", line 406, in request_gae_proxy response = request_gae_server(request_headers, request_body, url, timeout) File "D:\Programs\XX-Net\code\default\gae_proxy\local\gae_handler.py", line 351, in request_gae_server front.ip_manager.recheck_ip(response.ssl_sock.ip, first_report=False) AttributeError: 'BaseResponse' object has no attribute 'ssl_sock'

**Comment by AnyWAT** [comment]
> 
> 
> 这几天完全连不上去啊。。。。
> 可以退回原来的软件版本吗？

试试：https://github.com/XX-net/XX-Net/issues/11920 Teredo 隧道用服务器 IP地址的远远稳定于用域名。

**Comment by mtgitnerd** [comment]
哦，现在用的就是服务器ip了.........

**Comment by AnyWAT** [comment]
> 
> 
> 哦，现在用的就是服务器ip了.........

提升性能：https://github.com/XX-net/XX-Net/issues/11892
