### ISSUE TITLE
3.13.1使用请况和申请ID无效新情况

### ISSUE THREAD

**Issue by shpherd** [XX-net/XX-Net#11961]
申请ID失败！按照步骤有选取地区并通过，但是*.appspot.com无法连接成功。
gcloud app describe能够看到地区ID已存在。使用gcloud beta app create --region us-central告知已存在地区appengine。
但是在https://console.cloud.google.com/debug?repo=appengine:%3Fservice%3Ddefault%26version%3D1&fp=%2Fgae.py&dlv=4&project=shepherd&app=GAE:default@1  即stackdriver debugger中没有app engine:/app.template.yaml  app.yaml gae.py  legacy.py  wsgi.py等文件。
gcloud app create   gcloud app deploy都不能输送app engine给自己新建立之ID project。
可以看到，GAE的使用应当升级了，之前成功的*.appspot.com3.3.1，现在3.3.5
使用3.13.1以来有可能是墙壁增高，但是出现python出错的情况应当是google有库或python升级到3以上。
这几天家里网络出现问题，被迫使用手机网络，虽然延迟1300左右，油管等可正常观看。

**Comment by xinyan3** [comment]
貌似我也是报错。python的问题

2019-01-01 18:49:48.282 - [ERROR] scan_ip_worker except:ValueError('empty range for randrange() (0,0, 0)',)

2019-01-01 18:49:48.282 - [ERROR] Except stack:Traceback (most recent call last): File "/home/chenglong/文档/XX-Net-master/code/default/python27/1.0/lib/noarch/front_base/ip_manager.py", line 705, in scan_ip_worker ip = self.ip_source.get_ip() File "/home/chenglong/文档/XX-Net-master/code/default/python27/1.0/lib/noarch/front_base/ip_source.py", line 225, in get_ip return self.ipv4_source.get_ip() File "/home/chenglong/文档/XX-Net-master/code/default/python27/1.0/lib/noarch/front_base/ip_source.py", line 103, in get_ip index = random.randint(0, len(self.ip_range_list) - 1) File "/usr/lib/python2.7/random.py", line 242, in randint return self.randrange(a, b+1) File "/usr/lib/python2.7/random.py", line 218, in randrange raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width) ValueError: empty range for randrange() (0,0, 0)

**Comment by shpherd** [comment]
在网页打开控制台console，然后打开gcloud shell
git clone https://www.xxxxxx.com/xxxxxxx/xxxx.git
cd xxxx
cp app.template.yaml app.yaml
vi app.yaml
删除application:和version: 1 这两行
gcloud app deploy app.yaml
可是不知道哪个文件夹？

**Comment by shpherd** [comment]
@seahoh
