### ISSUE TITLE
这是部署失败还是成功？

### ISSUE THREAD

**Issue by mochen91** [XX-net/XX-Net#11968]
请问，这是 部署失败吧？页面显示部署完成，还让填到配置里面去，怎么看着像部署失败呢？也没让登陆啊。
------------------------------------以下是部署日志------------------------------------
2019-01-02 19:42:58,552 - root - INFO - set proxy to http://127.0.0.1:8087
2019-01-02 19:42:58,568 - root - INFO - ============ Begin upload ============
2019-01-02 19:42:58,568 - root - INFO - appid:mmttmm
2019-01-02 19:42:58,584 - root - INFO - Send: /api/appversion/rollback, params={'version': '1', 'app_id': 'mmttmm'}
2019-01-02 19:44:59,012 - root - ERROR - upload fail:BadStatusLine("''",)
Traceback (most recent call last):
File "D:\XX-Net\code\default\gae_proxy\server\uploader.py", line 72, in upload
result = appcfg.AppCfgApp(['appcfg', 'rollback', '--oauth2_credential_file', cookie_file, dirname]).Run()
File "D:\XX-Net\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 2951, in Run
self.action(self)
File "D:\XX-Net\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 5044, in __call__
return method()
File "D:\XX-Net\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 4397, in Rollback
self._Rollback()
File "D:\XX-Net\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 4442, in _Rollback
appversion.Rollback(force_rollback)
File "D:\XX-Net\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 2362, in Rollback
force_rollback='1' if force_rollback else '0')
File "D:\XX-Net\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 1696, in Send
result = self.rpcserver.Send(url, payload=payload, **kwargs)
File "D:\XX-Net\code\default\gae_proxy\server\lib\google\appengine\tools\appengine_rpc_httplib2.py", line 247, in Send
url, method=method, body=payload, headers=headers)
File "D:\XX-Net\code\default\gae_proxy\server\lib\httplib2\__init__.py", line 1593, in request
(response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
File "D:\XX-Net\code\default\gae_proxy\server\lib\httplib2\__init__.py", line 1341, in _request
(response, content) = self._conn_request(conn, request_uri, method, body, headers)
File "D:\XX-Net\code\default\gae_proxy\server\lib\httplib2\__init__.py", line 1311, in _conn_request
response = conn.getresponse()
File "D:\XX-Net\code\default\python27\1.0\lib\httplib.py", line 1121, in getresponse
response.begin()
File "D:\XX-Net\code\default\python27\1.0\lib\httplib.py", line 438, in begin
version, status, reason = self._read_status()
File "D:\XX-Net\code\default\python27\1.0\lib\httplib.py", line 402, in _read_status
raise BadStatusLine(line)
BadStatusLine: ''
2019-01-02 19:44:59,012 - root - INFO - Retry 1 time...
2019-01-02 19:44:59,028 - root - INFO - Send: /api/appversion/rollback, params={'version': '1', 'app_id': 'mmttmm'}
2019-01-02 19:44:59,059 - root - ERROR - upload fail:BadStatusLine("''",)
Traceback (most recent call last):
File "D:\XX-Net\code\default\gae_proxy\server\uploader.py", line 72, in upload
result = appcfg.AppCfgApp(['appcfg', 'rollback', '--oauth2_credential_file', cookie_file, dirname]).Run()
File "D:\XX-Net\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 2951, in Run
self.action(self)
File "D:\XX-Net\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 5044, in __call__
return method()
File "D:\XX-Net\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 4397, in Rollback
self._Rollback()
File "D:\XX-Net\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 4442, in _Rollback
appversion.Rollback(force_rollback)
File "D:\XX-Net\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 2362, in Rollback
force_rollback='1' if force_rollback else '0')
File "D:\XX-Net\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 1696, in Send
result = self.rpcserver.Send(url, payload=payload, **kwargs)
File "D:\XX-Net\code\default\gae_proxy\server\lib\google\appengine\tools\appengine_rpc_httplib2.py", line 247, in Send
url, method=method, body=payload, headers=headers)
File "D:\XX-Net\code\default\gae_proxy\server\lib\httplib2\__init__.py", line 1593, in request
(response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
File "D:\XX-Net\code\default\gae_proxy\server\lib\httplib2\__init__.py", line 1341, in _request
(response, content) = self._conn_request(conn, request_uri, method, body, headers)
File "D:\XX-Net\code\default\gae_proxy\server\lib\httplib2\__init__.py", line 1311, in _conn_request
response = conn.getresponse()
File "D:\XX-Net\code\default\python27\1.0\lib\httplib.py", line 1121, in getresponse
response.begin()
File "D:\XX-Net\code\default\python27\1.0\lib\httplib.py", line 438, in begin
version, status, reason = self._read_status()
File "D:\XX-Net\code\default\python27\1.0\lib\httplib.py", line 402, in _read_status
raise BadStatusLine(line)
BadStatusLine: ''
2019-01-02 19:44:59,059 - root - INFO - Retry 2 time...
2019-01-02 19:45:00,081 - root - INFO - Send: /api/appversion/rollback, params={'version': '1', 'app_id': 'mmttmm'}
2019-01-02 19:45:00,117 - root - ERROR - upload fail:BadStatusLine("''",)
Traceback (most recent call last):
File "D:\XX-Net\code\default\gae_proxy\server\uploader.py", line 72, in upload
result = appcfg.AppCfgApp(['appcfg', 'rollback', '--oauth2_credential_file', cookie_file, dirname]).Run()
File "D:\XX-Net\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 2951, in Run
self.action(self)
File "D:\XX-Net\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 5044, in __call__
return method()
File "D:\XX-Net\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 4397, in Rollback
self._Rollback()
File "D:\XX-Net\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 4442, in _Rollback
appversion.Rollback(force_rollback)
File "D:\XX-Net\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 2362, in Rollback
force_rollback='1' if force_rollback else '0')
File "D:\XX-Net\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 1696, in Send
result = self.rpcserver.Send(url, payload=payload, **kwargs)
File "D:\XX-Net\code\default\gae_proxy\server\lib\google\appengine\tools\appengine_rpc_httplib2.py", line 247, in Send
url, method=method, body=payload, headers=headers)
File "D:\XX-Net\code\default\gae_proxy\server\lib\httplib2\__init__.py", line 1593, in request
(response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
File "D:\XX-Net\code\default\gae_proxy\server\lib\httplib2\__init__.py", line 1341, in _request
(response, content) = self._conn_request(conn, request_uri, method, body, headers)
File "D:\XX-Net\code\default\gae_proxy\server\lib\httplib2\__init__.py", line 1311, in _conn_request
response = conn.getresponse()
File "D:\XX-Net\code\default\python27\1.0\lib\httplib.py", line 1121, in getresponse
response.begin()
File "D:\XX-Net\code\default\python27\1.0\lib\httplib.py", line 438, in begin
version, status, reason = self._read_status()
File "D:\XX-Net\code\default\python27\1.0\lib\httplib.py", line 402, in _read_status
raise BadStatusLine(line)
BadStatusLine: ''
2019-01-02 19:45:00,118 - root - INFO - Retry 3 time...
2019-01-02 19:45:02,119 - root - INFO - =======================
2019-01-02 19:45:02,119 - root - INFO - Deploy failed appid list:
2019-01-02 19:45:02,119 - root - INFO - - mmttmm
2019-01-02 19:45:02,121 - root - INFO - == END ==

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/issues/11892 附：2、如是已部署、成功使用过3.12.2（及后续版本）的，无需再次（上传）部署，除非更新服务端（3.13.1并无公告此要求）

**Comment by shpherd** [comment]
2019-01-02 19:45:02,119 - root - INFO - Deploy failed appid list:
2019-01-02 19:45:02,119 - root - INFO - - mmttmm

**Comment by ChenyangS** [comment]
没成功
看最后几行

如果你只是想重新部署xxnet的服务端，可以用第三方的梯子，把端口设为8087，然后手动用命令行部署，具体操作看server文件夹里面的说明

不过可以告诉你没多大用

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/issues/11695#issuecomment-441951702
