### ISSUE TITLE
我安装好XX-Net后可以正常使用，但是重启以后就不行了，老是启动失败，重装后也是这样

### ISSUE THREAD

**Issue by ikexu** [XX-net/XX-Net#1198]
状态页和日志都是打不开空白的。
start.bat里面的错误信息：
E:\恶趣味\工具\XX-Net\XX-Net-2.5.1>SET PYTHONPATH=

E:\恶趣味\工具\XX-Net\XX-Net-2.5.1>"E:\恶趣味\工具\XX-Net\XX-Net-2.5.1\python27/1.0/python.exe" "E:\恶趣味\工具\XX-Net\XX-Net-2.5.1\launcher/start.py"
Oct 11 11:24:38 - [INFO] start XX-Net 2.5.1
Oct 11 11:24:38 - [DEBUG] start confirm_xxnet_exit
Oct 11 11:24:39 - [DEBUG] good, xxnet:8087 cleared!
Oct 11 11:24:40 - [DEBUG] good, xxnet:8085 clear!
Oct 11 11:24:40 - [DEBUG] finished confirm_xxnet_exit
Oct 11 11:24:40 - [ERROR] start module gae_proxy fail:No module named _memimporter
Traceback (most recent call last):
  File "E:\恶趣味\工具\XX-Net\XX-Net-2.5.1\launcher\module_init.py", line 37, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "E:\恶趣味\工具\XX-Net\XX-Net-2.5.1\gae_proxy\start.py", line 14, in <module>
    import local.proxy as client
  File "E:\恶趣味\工具\XX-Net\XX-Net-2.5.1\gae_proxy\local\proxy.py", line 74, in <module>
    from cert_util import CertUtil
  File "E:\恶趣味\工具\XX-Net\XX-Net-2.5.1\gae_proxy\local\cert_util.py", line 37, in <module>
    import OpenSSL
  File "E:\恶趣味\工具\XX-Net\XX-Net-2.5.1\python27\1.0\lib\win32\OpenSSL__init__.py", line 26, in <module>
    from OpenSSL import crypto, rand, SSL
  File "E:\恶趣味\工具\XX-Net\XX-Net-2.5.1\python27\1.0\lib\win32\OpenSSL\crypto.py", line 11, in <module>
    **bootstrap**()
  File "E:\恶趣味\工具\XX-Net\XX-Net-2.5.1\python27\1.0\lib\win32\OpenSSL\crypto.py", line 3, in **bootstrap**
    import _memimporter, sys
ImportError: No module named _memimporter

Oct 11 11:24:40 - [INFO] start gae_proxy time cost 9
Oct 11 11:24:40 - [INFO] begin to start web control
## Oct 11 11:24:40 - [INFO] launcher web control started.

Exception happened during processing of request from ('127.0.0.1', 65332)
Traceback (most recent call last):
  File "E:\恶趣味\工具\XX-Net\XX-Net-2.5.1\python27\1.0\lib\SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "E:\恶趣味\工具\XX-Net\XX-Net-2.5.1\launcher\web_control.py", line 48, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "E:\恶趣味\工具\XX-Net\XX-Net-2.5.1\python27\1.0\lib\SocketServer.py", line 649, in **init**
    self.handle()
  File "E:\恶趣味\工具\XX-Net\XX-Net-2.5.1\python27\1.0\lib\BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "E:\恶趣味\工具\XX-Net\XX-Net-2.5.1\python27\1.0\lib\BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "E:\恶趣味\工具\XX-Net\XX-Net-2.5.1\launcher\web_control.py", line 143, in do_GET
    controler = module_init.proc_handler[module]["imp"].local.web_control.ControlHandler(self.client_address, self.headers, self.command, path, self.rfile, self.wfile)
## KeyError: 'imp'

---

Exception happened during processing of request from ('127.0.0.1', 65337)
Traceback (most recent call last):
  File "E:\恶趣味\工具\XX-Net\XX-Net-2.5.1\python27\1.0\lib\SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "E:\恶趣味\工具\XX-Net\XX-Net-2.5.1\launcher\web_control.py", line 48, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "E:\恶趣味\工具\XX-Net\XX-Net-2.5.1\python27\1.0\lib\SocketServer.py", line 649, in **init**
    self.handle()
  File "E:\恶趣味\工具\XX-Net\XX-Net-2.5.1\python27\1.0\lib\BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "E:\恶趣味\工具\XX-Net\XX-Net-2.5.1\python27\1.0\lib\BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "E:\恶趣味\工具\XX-Net\XX-Net-2.5.1\launcher\web_control.py", line 143, in do_GET
    controler = module_init.proc_handler[module]["imp"].local.web_control.ControlHandler(self.client_address, self.headers, self.command, path, self.rfile, self.wfile)
## KeyError: 'imp'

---

Exception happened during processing of request from ('127.0.0.1', 65336)
Traceback (most recent call last):
  File "E:\恶趣味\工具\XX-Net\XX-Net-2.5.1\python27\1.0\lib\SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "E:\恶趣味\工具\XX-Net\XX-Net-2.5.1\launcher\web_control.py", line 48, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "E:\恶趣味\工具\XX-Net\XX-Net-2.5.1\python27\1.0\lib\SocketServer.py", line 649, in **init**
    self.handle()
  File "E:\恶趣味\工具\XX-Net\XX-Net-2.5.1\python27\1.0\lib\BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "E:\恶趣味\工具\XX-Net\XX-Net-2.5.1\python27\1.0\lib\BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "E:\恶趣味\工具\XX-Net\XX-Net-2.5.1\launcher\web_control.py", line 143, in do_GET
    controler = module_init.proc_handler[module]["imp"].local.web_control.ControlHandler(self.client_address, self.headers, self.command, path, self.rfile, self.wfile)
KeyError: 'imp'

**Comment by meitianxiaoxu** [comment]
下了稳定版重装了几次，都是这样，安装时能用，重启后就不行了

**Comment by yangsaipp** [comment]
我今天也出现同样问题了，help！

**Comment by meitianxiaoxu** [comment]
@yangsaipp 你解决没

**Comment by xxnet** [comment]
会不会被杀毒软件删除了某个文件？

试试停掉杀毒软件，然后对比看看哪个文件不见了

2015-10-11 21:31 GMT+08:00 meitianxiaoxu <notifications@github.com>:

**Comment by yangsaipp** [comment]
我今天之前都使用正常，所以就保留了data文件夹 其他的全部删掉了然后把我之前备份的copy过来就可以正常运行了，不知道你情况是不是类似。

**Comment by meitianxiaoxu** [comment]
我是换了win10后重新弄的，开始配好后可以正常翻，但是有时候关掉重启后就不行了，然后我重装了一次，然后可以用了，重启后就又不能用了，不知道是什么原因

**Comment by xxnet** [comment]
可以下载一个Diff 工具，对比你现在不能工作的版本，和刚下载的版本，看看除了data目录，有哪些文件被改变了。
diff 工具有windiff, diffmerge，网上搜很多。

另一个思路，把无法工作的xx-net目录拷贝到别的机器上看看能否运行。

如果实在不会，可以把无法工作的xx-net 目录打包压缩后，发邮件给我分析，xxnet.dev@gmail.com

在 2015年10月11日 下午10:32，meitianxiaoxu <notifications@github.com>写道：

**Comment by meitianxiaoxu** [comment]
@xxnet 我把我朋友的XX-net拷过来了，现在可以用了，谢谢哈

**Comment by yeckham** [comment]
我也是同样的问题！win10

**Comment by cdmask** [comment]
win7 也出现这个问题。只装了一个 Microsoft security essentials

**Comment by xxnet** [comment]
@yeckham @cdmask

请按上面的提示进行分析：
可以下载一个Diff 工具，对比你现在不能工作的版本，和刚下载的版本，看看除了data目录，有哪些文件被改变了。
diff 工具有windiff, diffmerge，网上搜很多。

另一个思路，把无法工作的xx-net目录拷贝到别的机器上看看能否运行。

如果实在不会，可以把无法工作的xx-net 目录打包压缩后，发邮件给我分析，xxnet.dev@gmail.com

2015-10-13 8:41 GMT+08:00 cdmask <notifications@github.com>:
