### ISSUE TITLE
1.8.2在MAC下无法“关闭检查版本更新”功能

### ISSUE THREAD

**Issue by cobob** [XX-net/XX-Net#121]
Terminal error reports
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 56326)
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/Applications/XX-New/launcher/1.3.0/web_control.py", line 46, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/Applications/XX-New/launcher/1.3.0/web_control.py", line 127, in do_GET
    self.req_config_handler()
  File "/Applications/XX-New/launcher/1.3.0/web_control.py", line 207, in req_config_handler
    config.config["update"]["check_update"] = int(check_update)
KeyError: 'update'
----------------------------------------

**Comment by xxnet** [comment]
收到，下个版本修复

2015-04-09 22:36 GMT-04:00 cobob <notifications@github.com>:
