### ISSUE TITLE
centOS7 打开start.sh后出现下列问题

### ISSUE THREAD

**Issue by huianyi** [XX-net/XX-Net#1218]
Exception happened during processing of request from ('127.0.0.1', 40304)
Traceback (most recent call last):
  File "/usr/lib64/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/home/anhui/下载/XX-Net/launcher/web_control.py", line 48, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/lib64/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib64/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/home/anhui/下载/XX-Net/launcher/web_control.py", line 143, in do_GET
    controler = module_init.proc_handler[module]["imp"].local.web_control.ControlHandler(self.client_address, self.headers, self.command, path, self.rfile, self.wfile)
KeyError: 'imp'
--------------------------------------------------------------------------------------------------------------------------
然后xx-net页面显示空白

**Comment by xxnet** [comment]
把最前面的日志贴出来

2015-10-13 23:37 GMT+08:00 anhui <notifications@github.com>:

**Comment by huianyi** [comment]
这些就是所有的日志了啊，XX-Net打开后就全部都是空白

**Comment by xxnet** [comment]
Linux下启动XX-Net的日志，会显示版本信息之类，请拉滚动条向上看看。


另外，你把 data/launcher/log.log 删除，启动后看看，贴出来看看。

在 2015年10月18日 下午4:20，anhui <notifications@github.com>写道：

**Comment by huianyi** [comment]
[root@sutdy XX-Net]# sudo ./start.sh
Oct 23 22:05:02 - [WARNING] import pynotify fail, please install python-notify if possiable.
Oct 23 22:05:02 - [INFO] start XX-Net 2.5.2
Oct 23 22:05:02 - [DEBUG] start confirm_xxnet_exit
Oct 23 22:05:02 - [DEBUG] good, xxnet:8087 cleared!
Oct 23 22:05:02 - [DEBUG] good, xxnet:8085 clear!
Oct 23 22:05:02 - [DEBUG] finished confirm_xxnet_exit
Oct 23 22:05:02 - [ERROR] start module gae_proxy fail:libssl.so.1.0.0: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/anhui/Downloads/XX-Net/launcher/module_init.py", line 37, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "/home/anhui/Downloads/XX-Net/gae_proxy/start.py", line 14, in <module>
    import local.proxy as client
  File "/home/anhui/Downloads/XX-Net/gae_proxy/local/proxy.py", line 74, in <module>
    from cert_util import CertUtil
  File "/home/anhui/Downloads/XX-Net/gae_proxy/local/cert_util.py", line 37, in <module>
    import OpenSSL
  File "/home/anhui/Downloads/XX-Net/python27/1.0/lib/linux/OpenSSL/__init__.py", line 36, in <module>
    from OpenSSL import crypto
ImportError: libssl.so.1.0.0: cannot open shared object file: No such file or directory

Oct 23 22:05:02 - [INFO] start gae_proxy time cost 2
Oct 23 22:05:02 - [INFO] begin to start web control
Oct 23 22:05:02 - [INFO] launcher web control started.
Oct 23 22:05:03 - [INFO] get uuid:c3cee460-ef89-47e3-b59f-e5753d681c8f
Oct 23 22:05:03 - [WARNING] check_update fail:URLError(error(111, 'Connection refused'),)
Oct 23 22:05:03 - [INFO] download https://raw.githubusercontent.com/XX-net/XX-Net/master/README.md to /home/anhui/Downloads/XX-Net/data/downloads/README.md, retry:0
这就是所有的日志了，下边是log.log的内容：
Oct 23 22:05:02 - [WARNING] import pynotify fail, please install python-notify if possiable.
Oct 23 22:05:02 - [INFO] start XX-Net 2.5.2
Oct 23 22:05:02 - [DEBUG] start confirm_xxnet_exit
Oct 23 22:05:02 - [DEBUG] good, xxnet:8087 cleared!
Oct 23 22:05:02 - [DEBUG] good, xxnet:8085 clear!
Oct 23 22:05:02 - [DEBUG] finished confirm_xxnet_exit
Oct 23 22:05:02 - [ERROR] start module gae_proxy fail:libssl.so.1.0.0: cannot open shared object file: No such file or directory
Oct 23 22:05:02 - [INFO] start gae_proxy time cost 2
Oct 23 22:05:02 - [INFO] begin to start web control
Oct 23 22:05:02 - [INFO] launcher web control started.
Oct 23 22:05:03 - [INFO] get uuid:c3cee460-ef89-47e3-b59f-e5753d681c8f
Oct 23 22:05:03 - [WARNING] check_update fail:URLError(error(111, 'Connection refused'),)
Oct 23 22:05:03 - [INFO] download https://raw.githubusercontent.com/XX-net/XX-Net/master/README.md to /home/anhui/Downloads/XX-Net/data/downloads/README.md, retry:0

**Comment by xxnet** [comment]
难道系统没有安装ssl库？
  参考这个：

http://unix.stackexchange.com/questions/154286/importerror-libssl-so-1-0-0-cannot-open-shared-object-file-no-such-file-or-d

2015-10-23 22:13 GMT+08:00 anhui <notifications@github.com>:
