### ISSUE TITLE
ImportError: cannot import name Encoder

### ISSUE THREAD

**Issue by 102464** [XX-net/XX-Net#12242]
~/Desktop/XX-Net-master $ ./start
XX-Net version:3.13.1
2019-02-16 19:57:30.671 [launcher][INFO] import build-in openssl fail:AttributeError("'module' object has no attribute 'SSL_ST_INIT'",)
2019-02-16 19:57:30.676 [launcher][INFO] start XX-Net 3.13.1
2019-02-16 19:57:30.676 [launcher][DEBUG] start confirm_xxnet_exit
2019-02-16 19:57:30.678 [launcher][DEBUG] good, xxnet:8085 clear!
2019-02-16 19:57:30.678 [launcher][DEBUG] finished confirm_xxnet_exit
2019-02-16 19:57:30.746 [launcher][ERROR] start module gae_proxy fail:cannot import name Encoder
2019-02-16 19:57:30.747 [launcher][ERROR] Except stack:Traceback (most recent call last):
  File "/Users/osx/Desktop/XX-Net-master/code/3.13.1/launcher/module_init.py", line 40, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "/Users/osx/Desktop/XX-Net-master/code/3.13.1/gae_proxy/local/__init__.py", line 2, in <module>
    import apis
  File "/Users/osx/Desktop/XX-Net-master/code/3.13.1/gae_proxy/local/apis.py", line 2, in <module>
    from front import front, direct_front
  File "/Users/osx/Desktop/XX-Net-master/code/3.13.1/gae_proxy/local/front.py", line 15, in <module>
    from front_base.http_dispatcher import HttpsDispatcher
  File "/Users/osx/Desktop/XX-Net-master/code/3.13.1/python27/1.0/lib/noarch/front_base/http_dispatcher.py", line 32, in <module>
    from http2_connection import Http2Worker
  File "/Users/osx/Desktop/XX-Net-master/code/3.13.1/python27/1.0/lib/noarch/front_base/http2_connection.py", line 21, in <module>
    from hyper.packages.hpack import Encoder, Decoder
ImportError: cannot import name Encoder

2019-02-16 19:57:30.747 [launcher][ERROR] launcher except:ImportError('cannot import name Encoder',)
2019-02-16 19:57:30.748 [launcher][ERROR] Except stack:Traceback (most recent call last):
  File "code/3.13.1/launcher/start.py", line 251, in <module>
  File "code/3.13.1/launcher/start.py", line 230, in main
  File "/Users/osx/Desktop/XX-Net-master/code/3.13.1/launcher/module_init.py", line 113, in start_all_auto
    start(module)
  File "/Users/osx/Desktop/XX-Net-master/code/3.13.1/launcher/module_init.py", line 40, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "/Users/osx/Desktop/XX-Net-master/code/3.13.1/gae_proxy/local/__init__.py", line 2, in <module>
    import apis
  File "/Users/osx/Desktop/XX-Net-master/code/3.13.1/gae_proxy/local/apis.py", line 2, in <module>
    from front import front, direct_front
  File "/Users/osx/Desktop/XX-Net-master/code/3.13.1/gae_proxy/local/front.py", line 15, in <module>
    from front_base.http_dispatcher import HttpsDispatcher
  File "/Users/osx/Desktop/XX-Net-master/code/3.13.1/python27/1.0/lib/noarch/front_base/http_dispatcher.py", line 32, in <module>
    from http2_connection import Http2Worker
  File "/Users/osx/Desktop/XX-Net-master/code/3.13.1/python27/1.0/lib/noarch/front_base/http2_connection.py", line 21, in <module>
    from hyper.packages.hpack import Encoder, Decoder
ImportError: cannot import name Encoder

Press Enter to continue...2019-02-16 19:57:31.845 [gae_proxy][DEBUG] network IPv4 is ok, cost:1162 ms

**Comment by 6Shan** [comment]
运行 pip uninstall hyper 试试
