### ISSUE TITLE
win10 xx-net 启动报try to terminate xxnet:8085 版本为最新版本

### ISSUE THREAD

**Issue by wqiang1590** [XX-net/XX-Net#12265]
2019-02-22 11:20:25.161 [launcher][INFO] use build-in openssl lib
2019-02-22 11:20:25.238 [launcher][INFO] start XX-Net 3.13.1
2019-02-22 11:20:25.238 [launcher][DEBUG] start confirm_xxnet_exit
2019-02-22 11:20:25.241 [launcher][DEBUG] <0>: try to terminate xxnet:8085
2019-02-22 11:20:26.243 [launcher][DEBUG] <1>: try to terminate xxnet:8085
2019-02-22 11:20:27.246 [launcher][DEBUG] <2>: try to terminate xxnet:8085
2019-02-22 11:20:28.248 [launcher][DEBUG] <3>: try to terminate xxnet:8085
2019-02-22 11:20:29.251 [launcher][DEBUG] <4>: try to terminate xxnet:8085
2019-02-22 11:20:30.252 [launcher][DEBUG] <5>: try to terminate xxnet:8085
2019-02-22 11:20:31.254 [launcher][DEBUG] <6>: try to terminate xxnet:8085
2019-02-22 11:20:32.257 [launcher][DEBUG] <7>: try to terminate xxnet:8085
2019-02-22 11:20:33.259 [launcher][DEBUG] <8>: try to terminate xxnet:8085
2019-02-22 11:20:34.262 [launcher][DEBUG] <9>: try to terminate xxnet:8085
2019-02-22 11:20:35.264 [launcher][DEBUG] <10>: try to terminate xxnet:8085
2019-02-22 11:20:36.267 [launcher][DEBUG] <11>: try to terminate xxnet:8085
2019-02-22 11:20:37.270 [launcher][DEBUG] <12>: try to terminate xxnet:8085
2019-02-22 11:20:38.271 [launcher][DEBUG] <13>: try to terminate xxnet:8085
2019-02-22 11:20:39.273 [launcher][DEBUG] <14>: try to terminate xxnet:8085
2019-02-22 11:20:40.275 [launcher][DEBUG] <15>: try to terminate xxnet:8085
2019-02-22 11:20:41.278 [launcher][DEBUG] <16>: try to terminate xxnet:8085
2019-02-22 11:20:42.280 [launcher][DEBUG] <17>: try to terminate xxnet:8085
2019-02-22 11:20:43.283 [launcher][DEBUG] <18>: try to terminate xxnet:8085
2019-02-22 11:20:44.285 [launcher][DEBUG] <19>: try to terminate xxnet:8085
2019-02-22 11:20:45.288 [launcher][DEBUG] <20>: try to terminate xxnet:8085
2019-02-22 11:20:46.293 [launcher][DEBUG] <21>: try to terminate xxnet:8085
2019-02-22 11:20:47.298 [launcher][DEBUG] <22>: try to terminate xxnet:8085
2019-02-22 11:20:48.301 [launcher][DEBUG] <23>: try to terminate xxnet:8085
2019-02-22 11:20:49.304 [launcher][DEBUG] <24>: try to terminate xxnet:8085
2019-02-22 11:20:50.306 [launcher][DEBUG] <25>: try to terminate xxnet:8085
2019-02-22 11:20:51.309 [launcher][DEBUG] <26>: try to terminate xxnet:8085
2019-02-22 11:20:52.311 [launcher][DEBUG] <27>: try to terminate xxnet:8085
2019-02-22 11:20:53.315 [launcher][DEBUG] <28>: try to terminate xxnet:8085
2019-02-22 11:20:54.318 [launcher][DEBUG] <29>: try to terminate xxnet:8085
2019-02-22 11:20:55.321 [launcher][DEBUG] finished confirm_xxnet_exit
2019-02-22 11:20:57.255 [gae_proxy][INFO] ------------------------------------------------------
2019-02-22 11:20:57.257 [gae_proxy][INFO] Python Version     : 2.7.13
2019-02-22 11:20:57.257 [gae_proxy][INFO] OS                 : Version:10-0; Build:17134; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
2019-02-22 11:20:57.258 [gae_proxy][INFO] Listen Address     : 127.0.0.1:8087
2019-02-22 11:20:57.259 [gae_proxy][INFO] Using public APPID
2019-02-22 11:20:57.260 [gae_proxy][INFO] ------------------------------------------------------
2019-02-22 11:20:57.263 [gae_proxy][DEBUG] Importing CA
2019-02-22 11:20:57.264 [gae_proxy][DEBUG] Begin to import Windows CA
2019-02-22 11:20:57.285 [gae_proxy][DEBUG] network IPv4 is ok, cost:927 ms
2019-02-22 11:20:57.286 [gae_proxy][DEBUG] XX-Net CA already exists
2019-02-22 11:20:57.289 [gae_proxy][INFO] SSL use version:TLSv1_2
2019-02-22 11:20:57.970 [gae_proxy][INFO] OpenSSL support alpn
2019-02-22 11:20:57.973 [gae_proxy][INFO] load ip range file:D:\XX-Net-master\code\default\gae_proxy\local\ip_range.txt
2019-02-22 11:20:58.031 [gae_proxy][INFO] SSL use version:TLSv1_2
2019-02-22 11:20:58.036 [gae_proxy][INFO] server 127.0.0.1:8087 started.
2019-02-22 11:20:58.058 [launcher][INFO] module gae_proxy started
2019-02-22 11:20:58.059 [launcher][INFO] start gae_proxy time cost:2732 ms
WARNING:root:Load Crypto.Cipher.ARC4 Failed, Use Pure Python Instead.
2019-02-22 11:20:58.196 [cloudflare_front][INFO] load D:\XX-Net-master\data\x_tunnel\cloudflare_domains.json success
2019-02-22 11:20:58.198 [cloudflare_front][INFO] SSL use version:TLSv1_2
2019-02-22 11:20:58.199 [cloudflare_front][INFO] OpenSSL support alpn
2019-02-22 11:20:58.200 [cloudflare_front][INFO] load ip range file:D:\XX-Net-master\code\default\x_tunnel\local\cloudflare_front\ip_range.txt
2019-02-22 11:20:58.202 [cloudflare_front][INFO] load ip_list num:50, target num:50
2019-02-22 11:20:58.219 [cloudfront_front][INFO] SSL use version:TLSv1_2
2019-02-22 11:20:58.230 [cloudfront_front][INFO] OpenSSL support alpn
2019-02-22 11:20:58.231 [cloudfront_front][INFO] load ip range file:D:\XX-Net-master\code\default\x_tunnel\local\cloudfront_front\ip_range.txt
2019-02-22 11:20:58.233 [cloudfront_front][INFO] load ip_list num:89, target num:89
2019-02-22 11:20:58.250 [tls_relay][INFO] SSL use version:TLSv1_2
2019-02-22 11:20:58.251 [tls_relay][INFO] OpenSSL support alpn
2019-02-22 11:20:58.269 [heroku_front][INFO] SSL use version:TLSv1_2
2019-02-22 11:20:58.270 [heroku_front][INFO] OpenSSL support alpn
2019-02-22 11:20:58.272 [heroku_front][INFO] load ip_list num:75, target num:75
2019-02-22 11:20:58.279 [x_tunnel][INFO] use config_path:D:\XX-Net-master\data\x_tunnel\client.json
2019-02-22 11:20:58.280 [x_tunnel][INFO] X-Tunnel window:16777216
2019-02-22 11:20:58.285 [x_tunnel][INFO] xxnet_version:3.13.1
2019-02-22 11:20:58.286 [x_tunnel][INFO] server 127.0.0.1:1080 started.
2019-02-22 11:20:58.287 [x_tunnel][INFO] Socks5 server listen:127.0.0.1:1080.
2019-02-22 11:20:58.379 [launcher][INFO] module x_tunnel started
2019-02-22 11:20:58.379 [launcher][INFO] start x_tunnel time cost:319 ms
2019-02-22 11:20:58.491 [smart_router][INFO] Load file:D:\XX-Net-master\code\default\smart_router\local\gfw_black_list.txt
2019-02-22 11:20:58.494 [smart_router][INFO] Load file:D:\XX-Net-master\code\default\smart_router\local\gfw_white_list.txt
2019-02-22 11:20:58.496 [smart_router][INFO] Load file:D:\XX-Net-master\code\default\smart_router\local\advertisement_list.txt
2019-02-22 11:20:58.515 [smart_router][DEBUG] use local DNS server:192.168.5.131
2019-02-22 11:20:58.515 [smart_router][DEBUG] use local DNS server:192.168.5.132
2019-02-22 11:20:58.518 [smart_router][INFO] server 127.0.0.1:8086 started.
2019-02-22 11:20:58.519 [smart_router][INFO] Proxy server listen:127.0.0.1:8086.
2019-02-22 11:20:58.520 [smart_router][INFO] start DNS server at 127.0.0.1:53
2019-02-22 11:20:58.592 [launcher][INFO] module smart_router started
2019-02-22 11:20:58.594 [launcher][INFO] start smart_router time cost:213 ms
2019-02-22 11:20:58.598 [launcher][INFO] begin to start web control
2019-02-22 11:20:58.598 [launcher][ERROR] bind to 127.0.0.1:8085 fail:error(10013, '')
2019-02-22 11:20:58.600 [launcher][ERROR] launcher except:Exception("bind to 127.0.0.1:8085 fail:error(10013, '')",)
2019-02-22 11:20:58.602 [launcher][ERROR] Except stack:Traceback (most recent call last):
  File "D:\XX-Net-master\code\default\launcher\start.py", line 251, in <module>
    main()
  File "D:\XX-Net-master\code\default\launcher\start.py", line 231, in main
    web_control.start(allow_remote)
  File "D:\XX-Net-master\code\default\launcher\web_control.py", line 709, in start
    server = simple_http_server.HTTPServer(addresses, Http_Handler, logger=xlog)
  File "D:\XX-Net-master\code\default\python27\1.0\lib\noarch\simple_http_server.py", line 412, in __init__
    self.init_socket()
  File "D:\XX-Net-master\code\default\python27\1.0\lib\noarch\simple_http_server.py", line 430, in init_socket
    self.add_listen((ip, port))
  File "D:\XX-Net-master\code\default\python27\1.0\lib\noarch\simple_http_server.py", line 444, in add_listen
    raise Exception(err_string)
Exception: bind to 127.0.0.1:8085 fail:error(10013, '')

**Comment by wqiang1590** [comment]
端口冲突 已经解决
