### ISSUE TITLE
win10LTSB 长期支持版 安装XX-net无反应

### ISSUE THREAD

**Issue by lb8023lyy** [XX-net/XX-Net#1245]
win10LTSB 长期支持版 安装XX-net无反应，不管是lnk还是vbs点开都没有反应

**Comment by Antecer** [comment]
也许你需要右键管理员权限运行

在 2015年10月18日 下午1:46，lb8023lyy <notifications@github.com>写道：

**Comment by xxnet** [comment]
试试点bat 启动，看看输出什么

在 2015年10月18日 下午3:50，Antecer <notifications@github.com>写道：

**Comment by lb8023lyy** [comment]
用管理员运行提示Windows找不到'C:\Windows\system32\start.vbs'。请确定文件名是否正确后，再试一次（系统是win10企业版x64）

**Comment by lb8023lyy** [comment]
点bat出现结果
C:\Program Files (x86)\XX-Net-2.5.1>SET PYTHONPATH=
C:\Program Files (x86)\XX-Net-2.5.1>"C:\Program Files (x86)\XX-Net-2.5.1\python27/1.0/python.exe" "C:\Program Files (x86)\XX-Net-2.5.1\launcher/start.py"
Traceback (most recent call last):
  File "C:\Program Files (x86)\XX-Net-2.5.1\launcher/start.py", line 9, in <module>
    import launcher_log
  File "C:\Program Files (x86)\XX-Net-2.5.1\launcher\launcher_log.py", line 54, in <module>
    create_data_path()
  File "C:\Program Files (x86)\XX-Net-2.5.1\launcher\launcher_log.py", line 45, in create_data_path
    os.mkdir(data_path)
WindowsError: [Error 5] : 'C:\\Program Files (x86)\\XX-Net-2.5.1\\data'

C:\Program Files (x86)\XX-Net-2.5.1>pause
请按任意键继续. . .

**Comment by lb8023lyy** [comment]
但是可以使用cmd命令行安装

**Comment by xxnet** [comment]
无法建立 'C:\Program Files (x86)\XX-Net-2.5.1\data 目录：
  试试不要放在C盘，不要放在Program Files，这些地方是要高权限的。



2015-10-20 0:44 GMT+08:00 lb8023lyy <notifications@github.com>:
