### ISSUE TITLE
start.vbs运行失败

### ISSUE THREAD

**Issue by JorSean** [XX-net/XX-Net#12496]
* 是否试过最新的版本 (https://github.com/XX-net/XX-Net/releases )？
是的，同样的问题

* 是否查看过 Wiki (https://github.com/XX-net/XX-Net/wiki )？
看过

* 是否以相关关键词搜索过类似 issues？
搜过，没找到答案

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志，如包含大量文本时，请上传为 txt 文件：
2019-04-24 15:57:20.499 - [INFO] use build-in openssl lib
2019-04-24 15:57:20.511 - [INFO] start XX-Net 3.13.1
2019-04-24 15:57:20.511 - [DEBUG] start confirm_xxnet_exit
2019-04-24 15:57:21.523 - [DEBUG] good, xxnet:8085 clear!
2019-04-24 15:57:21.523 - [DEBUG] finished confirm_xxnet_exit
2019-04-24 15:57:21.547 - [ERROR] start module gae_proxy fail:'module' object has no attribute 'check_ip_valid4'
2019-04-24 15:57:21.550 - [ERROR] Except stack:Traceback (most recent call last):
  File "D:\Soft\翻墙工具及教程\XX-Net-3.13.1\code\default\launcher\module_init.py", line 40, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "D:\Soft\翻墙工具及教程\XX-Net-3.13.1\code\default\gae_proxy\local\__init__.py", line 2, in <module>
    import apis
  File "D:\Soft\翻墙工具及教程\XX-Net-3.13.1\code\default\gae_proxy\local\apis.py", line 2, in <module>
    from front import front, direct_front
  File "D:\Soft\翻墙工具及教程\XX-Net-3.13.1\code\default\gae_proxy\local\front.py", line 7, in <module>
    import check_local_network
  File "D:\Soft\翻墙工具及教程\XX-Net-3.13.1\code\default\gae_proxy\local\check_local_network.py", line 28, in <module>
    from config import config
  File "D:\Soft\翻墙工具及教程\XX-Net-3.13.1\code\default\gae_proxy\local\config.py", line 13, in <module>
    fqrouter = simple_http_client.request("GET", "http://127.0.0.1:2515/ping", headers=headers, timeout=0.5)
  File "D:\Soft\翻墙工具及教程\XX-Net-3.13.1\code\default\python27\1.0\lib\noarch\simple_http_client.py", line 515, in request
    return client.request(method, url, headers, body, read_payload)
  File "D:\Soft\翻墙工具及教程\XX-Net-3.13.1\code\default\python27\1.0\lib\noarch\simple_http_client.py", line 446, in request
    sock = self.connect(upl.hostname, port)
  File "D:\Soft\翻墙工具及教程\XX-Net-3.13.1\code\default\python27\1.0\lib\noarch\simple_http_client.py", line 397, in connect
    return self.direct_connect(host, port)
  File "D:\Soft\翻墙工具及教程\XX-Net-3.13.1\code\default\python27\1.0\lib\noarch\simple_http_client.py", line 366, in direct_connect
    elif utils.check_ip_valid4(host):
AttributeError: 'module' object has no attribute 'check_ip_valid4'

2019-04-24 15:57:21.550 - [ERROR] launcher except:AttributeError("'module' object has no attribute 'check_ip_valid4'",)
2019-04-24 15:57:21.551 - [ERROR] Except stack:Traceback (most recent call last):
  File "D:\Soft\翻墙工具及教程\XX-Net-3.13.1\code\default\launcher\start.py", line 251, in <module>
    main()
  File "D:\Soft\翻墙工具及教程\XX-Net-3.13.1\code\default\launcher\start.py", line 230, in main
    module_init.start_all_auto()
  File "D:\Soft\翻墙工具及教程\XX-Net-3.13.1\code\default\launcher\module_init.py", line 113, in start_all_auto
    start(module)
  File "D:\Soft\翻墙工具及教程\XX-Net-3.13.1\code\default\launcher\module_init.py", line 40, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "D:\Soft\翻墙工具及教程\XX-Net-3.13.1\code\default\gae_proxy\local\__init__.py", line 2, in <module>
    import apis
  File "D:\Soft\翻墙工具及教程\XX-Net-3.13.1\code\default\gae_proxy\local\apis.py", line 2, in <module>
    from front import front, direct_front
  File "D:\Soft\翻墙工具及教程\XX-Net-3.13.1\code\default\gae_proxy\local\front.py", line 7, in <module>
    import check_local_network
  File "D:\Soft\翻墙工具及教程\XX-Net-3.13.1\code\default\gae_proxy\local\check_local_network.py", line 28, in <module>
    from config import config
  File "D:\Soft\翻墙工具及教程\XX-Net-3.13.1\code\default\gae_proxy\local\config.py", line 13, in <module>
    fqrouter = simple_http_client.request("GET", "http://127.0.0.1:2515/ping", headers=headers, timeout=0.5)
  File "D:\Soft\翻墙工具及教程\XX-Net-3.13.1\code\default\python27\1.0\lib\noarch\simple_http_client.py", line 515, in request
    return client.request(method, url, headers, body, read_payload)
  File "D:\Soft\翻墙工具及教程\XX-Net-3.13.1\code\default\python27\1.0\lib\noarch\simple_http_client.py", line 446, in request
    sock = self.connect(upl.hostname, port)
  File "D:\Soft\翻墙工具及教程\XX-Net-3.13.1\code\default\python27\1.0\lib\noarch\simple_http_client.py", line 397, in connect
    return self.direct_connect(host, port)
  File "D:\Soft\翻墙工具及教程\XX-Net-3.13.1\code\default\python27\1.0\lib\noarch\simple_http_client.py", line 366, in direct_connect
    elif utils.check_ip_valid4(host):
AttributeError: 'module' object has no attribute 'check_ip_valid4'

2019-04-24 15:57:21.552 - [ERROR] uncaught Exception, type=<type 'exceptions.EOFError'> value=EOF when reading a line traceback:<traceback object at 0x0434AAD0>
2019-04-24 15:57:21.552 - [ERROR] stop module gae_proxy fail:'imp'
2019-04-24 15:57:21.552 - [ERROR] Except stack:Traceback (most recent call last):
  File "D:\Soft\翻墙工具及教程\XX-Net-3.13.1\code\default\launcher\module_init.py", line 74, in stop
    _start = proc_handler[module]["imp"].start
KeyError: 'imp'

2019-04-24 15:57:21.552 - [INFO] begin to exit web control
2019-04-24 15:57:21.554 - [ERROR] uncaught Exception, type=<type 'exceptions.AttributeError'> value='NoneType' object has no attribute 'shutdown' traceback:<traceback object at 0x04334148>

* 如果问题得到解决，请务必回复相关情况，谢谢。

**Comment by JorSean** [comment]
start.bat可以正常启动使用

**Comment by AnyWAT** [comment]
莫非洋（文）程序不识中文？复制到不含中文名称的路径下试试？

**Comment by JorSean** [comment]
> 莫非洋（文）程序不识中文？复制到不含中文名称的路径下试试？

试过的，不是中文路径的问题。以前是正常的，不知道最近为什么不能用了

**Comment by AnyWAT** [comment]
莫非报毒被干掉。。。#12485

**Comment by JorSean** [comment]
start.bat可以执行，打开发现这个文件中有环境变量PYTHONPATH的设置，想起来最近安装Tensorflow设置了该环境变量为python3的路径，和#10917 是同一个问题。
