### ISSUE TITLE
error Log

### ISSUE THREAD

**Issue by gpblg** [XX-net/XX-Net#12511]
2019-04-28 19:23:52,755 - root - INFO - enable debug logging
2019-04-28 19:23:52,755 - root - INFO - set proxy to http://127.0.0.1:8087
2019-04-28 19:23:52,757 - root - INFO - ============ Begin upload ============
2019-04-28 19:23:52,759 - root - INFO - appid:dzry-001
2019-04-28 19:23:52,789 - root - INFO - Send: /api/appversion/rollback, params={'version': '1', 'app_id': 'dzry-001'}
2019-04-28 19:23:52,790 - google.appengine.tools.appengine_rpc - DEBUG - _Authenticate skipped auth; needs_auth=False
2019-04-28 19:23:52,790 - google.appengine.tools.appengine_rpc - DEBUG - Sending request to https://appengine.google.com/api/appversion/rollback?app_id=dzry-001&force_rollback=0&version=1 headers={'X-appcfg-api-version': '1', 'content-length': '0', 'Content-Type': 'application/octet-stream'} body=
2019-04-28 19:23:53,303 - root - ERROR - upload fail:BadStatusLine("''",)
Traceback (most recent call last):
File "E:\soft\VPN\XX-Net\code\default\gae_proxy\server\uploader.py", line 72, in upload
result = appcfg.AppCfgApp(['appcfg', 'rollback', '--oauth2_credential_file', cookie_file, dirname]).Run()
File "E:\soft\VPN\XX-Net\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 2951, in Run
self.action(self)
File "E:\soft\VPN\XX-Net\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 5044, in __call__
return method()
File "E:\soft\VPN\XX-Net\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 4397, in Rollback
self._Rollback()
File "E:\soft\VPN\XX-Net\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 4442, in _Rollback
appversion.Rollback(force_rollback)
File "E:\soft\VPN\XX-Net\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 2362, in Rollback
force_rollback='1' if force_rollback else '0')
File "E:\soft\VPN\XX-Net\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 1696, in Send
result = self.rpcserver.Send(url, payload=payload, **kwargs)
File "E:\soft\VPN\XX-Net\code\default\gae_proxy\server\lib\google\appengine\tools\appengine_rpc_httplib2.py", line 247, in Send
url, method=method, body=payload, headers=headers)
File "E:\soft\VPN\XX-Net\code\default\gae_proxy\server\lib\httplib2\__init__.py", line 1593, in request
(response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
File "E:\soft\VPN\XX-Net\code\default\gae_proxy\server\lib\httplib2\__init__.py", line 1341, in _request
(response, content) = self._conn_request(conn, request_uri, method, body, headers)
File "E:\soft\VPN\XX-Net\code\default\gae_proxy\server\lib\httplib2\__init__.py", line 1311, in _conn_request
response = conn.getresponse()
File "E:\soft\VPN\XX-Net\code\default\python27\1.0\lib\httplib.py", line 1121, in getresponse
response.begin()
File "E:\soft\VPN\XX-Net\code\default\python27\1.0\lib\httplib.py", line 438, in begin
version, status, reason = self._read_status()
File "E:\soft\VPN\XX-Net\code\default\python27\1.0\lib\httplib.py", line 402, in _read_status
raise BadStatusLine(line)
BadStatusLine: ''
2019-04-28 19:23:53,312 - root - INFO - Retry 1 time...
2019-04-28 19:23:53,339 - root - INFO - Send: /api/appversion/rollback, params={'version': '1', 'app_id': 'dzry-001'}
2019-04-28 19:23:53,341 - google.appengine.tools.appengine_rpc - DEBUG - _Authenticate skipped auth; needs_auth=False
2019-04-28 19:23:53,341 - google.appengine.tools.appengine_rpc - DEBUG - Sending request to https://appengine.google.com/api/appversion/rollback?app_id=dzry-001&force_rollback=0&version=1 headers={'X-appcfg-api-version': '1', 'content-length': '0', 'Content-Type': 'application/octet-stream'} body=
2019-04-28 19:23:53,384 - root - ERROR - upload fail:BadStatusLine("''",)
Traceback (most recent call last):
File "E:\soft\VPN\XX-Net\code\default\gae_proxy\server\uploader.py", line 72, in upload
result = appcfg.AppCfgApp(['appcfg', 'rollback', '--oauth2_credential_file', cookie_file, dirname]).Run()
File "E:\soft\VPN\XX-Net\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 2951, in Run
self.action(self)
File "E:\soft\VPN\XX-Net\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 5044, in __call__
return method()
File "E:\soft\VPN\XX-Net\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 4397, in Rollback
self._Rollback()
File "E:\soft\VPN\XX-Net\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 4442, in _Rollback
appversion.Rollback(force_rollback)
File "E:\soft\VPN\XX-Net\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 2362, in Rollback
force_rollback='1' if force_rollback else '0')
File "E:\soft\VPN\XX-Net\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 1696, in Send
result = self.rpcserver.Send(url, payload=payload, **kwargs)
File "E:\soft\VPN\XX-Net\code\default\gae_proxy\server\lib\google\appengine\tools\appengine_rpc_httplib2.py", line 247, in Send
url, method=method, body=payload, headers=headers)
File "E:\soft\VPN\XX-Net\code\default\gae_proxy\server\lib\httplib2\__init__.py", line 1593, in request
(response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
File "E:\soft\VPN\XX-Net\code\default\gae_proxy\server\lib\httplib2\__init__.py", line 1341, in _request
(response, content) = self._conn_request(conn, request_uri, method, body, headers)
File "E:\soft\VPN\XX-Net\code\default\gae_proxy\server\lib\httplib2\__init__.py", line 1311, in _conn_request
response = conn.getresponse()
File "E:\soft\VPN\XX-Net\code\default\python27\1.0\lib\httplib.py", line 1121, in getresponse
response.begin()
File "E:\soft\VPN\XX-Net\code\default\python27\1.0\lib\httplib.py", line 438, in begin
version, status, reason = self._read_status()
File "E:\soft\VPN\XX-Net\code\default\python27\1.0\lib\httplib.py", line 402, in _read_status
raise BadStatusLine(line)
BadStatusLine: ''
2019-04-28 19:23:53,388 - root - INFO - Retry 2 time...
2019-04-28 19:23:54,443 - root - INFO - Send: /api/appversion/rollback, params={'version': '1', 'app_id': 'dzry-001'}
2019-04-28 19:23:54,444 - google.appengine.tools.appengine_rpc - DEBUG - _Authenticate skipped auth; needs_auth=False
2019-04-28 19:23:54,444 - google.appengine.tools.appengine_rpc - DEBUG - Sending request to https://appengine.google.com/api/appversion/rollback?app_id=dzry-001&force_rollback=0&version=1 headers={'X-appcfg-api-version': '1', 'content-length': '0', 'Content-Type': 'application/octet-stream'} body=
2019-04-28 19:23:54,494 - root - ERROR - upload fail:BadStatusLine("''",)
Traceback (most recent call last):
File "E:\soft\VPN\XX-Net\code\default\gae_proxy\server\uploader.py", line 72, in upload
result = appcfg.AppCfgApp(['appcfg', 'rollback', '--oauth2_credential_file', cookie_file, dirname]).Run()
File "E:\soft\VPN\XX-Net\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 2951, in Run
self.action(self)
File "E:\soft\VPN\XX-Net\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 5044, in __call__
return method()
File "E:\soft\VPN\XX-Net\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 4397, in Rollback
self._Rollback()
File "E:\soft\VPN\XX-Net\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 4442, in _Rollback
appversion.Rollback(force_rollback)
File "E:\soft\VPN\XX-Net\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 2362, in Rollback
force_rollback='1' if force_rollback else '0')
File "E:\soft\VPN\XX-Net\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 1696, in Send
result = self.rpcserver.Send(url, payload=payload, **kwargs)
File "E:\soft\VPN\XX-Net\code\default\gae_proxy\server\lib\google\appengine\tools\appengine_rpc_httplib2.py", line 247, in Send
url, method=method, body=payload, headers=headers)
File "E:\soft\VPN\XX-Net\code\default\gae_proxy\server\lib\httplib2\__init__.py", line 1593, in request
(response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
File "E:\soft\VPN\XX-Net\code\default\gae_proxy\server\lib\httplib2\__init__.py", line 1341, in _request
(response, content) = self._conn_request(conn, request_uri, method, body, headers)
File "E:\soft\VPN\XX-Net\code\default\gae_proxy\server\lib\httplib2\__init__.py", line 1311, in _conn_request
response = conn.getresponse()
File "E:\soft\VPN\XX-Net\code\default\python27\1.0\lib\httplib.py", line 1121, in getresponse
response.begin()
File "E:\soft\VPN\XX-Net\code\default\python27\1.0\lib\httplib.py", line 438, in begin
version, status, reason = self._read_status()
File "E:\soft\VPN\XX-Net\code\default\python27\1.0\lib\httplib.py", line 402, in _read_status
raise BadStatusLine(line)
BadStatusLine: ''
2019-04-28 19:23:54,500 - root - INFO - Retry 3 time...
2019-04-28 19:23:56,502 - root - INFO - =======================
2019-04-28 19:23:56,503 - root - INFO - Deploy failed appid list:
2019-04-28 19:23:56,505 - root - INFO - - dzry-001
2019-04-28 19:23:56,505 - root - INFO - == END ==

**Comment by AnyWAT** [comment]
如用XX-Net 作为代理，部署前提高代理性能貌似才能避免出错？#12455
