### ISSUE TITLE
稳定版2.5.1安装报错

### ISSUE THREAD

**Issue by Richard-Lucas** [XX-net/XX-Net#1253]
File "D:\迅雷下载\科学上网\XX-Net\gae_proxy\local\google_ip.py", line 562, in
scan_ip_worker
    xlog.exception("google_ip.runJob fail:%s", e)
AttributeError: 'NoneType' object has no attribute 'exception'

Exception in thread Thread-852:
Traceback (most recent call last):
  File "D:\迅雷下载\科学上网\XX-Net\python27\1.0\lib\threading.py", line 810, in
 __bootstrap_inner
    self.run()
  File "D:\迅雷下载\科学上网\XX-Net\python27\1.0\lib\threading.py", line 763, in
 run
    self.__target(*self.__args, **self.__kwargs)
  File "D:\迅雷下载\科学上网\XX-Net\gae_proxy\local\google_ip.py", line 562, in
scan_ip_worker
    xlog.exception("google_ip.runJob fail:%s", e)
AttributeError: 'NoneType' object has no attribute 'exception'

Exception in thread Thread-855:
Traceback (most recent call last):
  File "D:\迅雷下载\科学上网\XX-Net\python27\1.0\lib\threading.py", line 810, in
 __bootstrap_inner
    self.run()
  File "D:\迅雷下载\科学上网\XX-Net\python27\1.0\lib\threading.py", line 763, in
 run
    self.__target(*self.__args, **self.__kwargs)
  File "D:\迅雷下载\科学上网\XX-Net\gae_proxy\local\google_ip.py", line 562, in
scan_ip_worker
    xlog.exception("google_ip.runJob fail:%s", e)
AttributeError: 'NoneType' object has no attribute 'exception'

Exception in thread Thread-861:
Traceback (most recent call last):
  File "D:\迅雷下载\科学上网\XX-Net\python27\1.0\lib\threading.py", line 810, in
 __bootstrap_inner
    self.run()
  File "D:\迅雷下载\科学上网\XX-Net\python27\1.0\lib\threading.py", line 763, in
 run
    self.__target(*self.__args, **self.__kwargs)
  File "D:\迅雷下载\科学上网\XX-Net\gae_proxy\local\google_ip.py", line 562, in
scan_ip_worker
    xlog.exception("google_ip.runJob fail:%s", e)
AttributeError: 'NoneType' object has no attribute 'exception'

Exception in thread Thread-856:
Traceback (most recent call last):
  File "D:\迅雷下载\科学上网\XX-Net\python27\1.0\lib\threading.py", line 810, in
 __bootstrap_inner
    self.run()
  File "D:\迅雷下载\科学上网\XX-Net\python27\1.0\lib\threading.py", line 763, in
 run
    self.__target(*self.__args, **self.__kwargs)
  File "D:\迅雷下载\科学上网\XX-Net\gae_proxy\local\google_ip.py", line 562, in
scan_ip_worker
    xlog.exception("google_ip.runJob fail:%s", e)
AttributeError: 'NoneType' object has no attribute 'exception'

Exception in thread Thread-859:
Traceback (most recent call last):
  File "D:\迅雷下载\科学上网\XX-Net\python27\1.0\lib\threading.py", line 810, in
 __bootstrap_inner
    self.run()
  File "D:\迅雷下载\科学上网\XX-Net\python27\1.0\lib\threading.py", line 763, in
 run
    self.__target(*self.__args, **self.__kwargs)
  File "D:\迅雷下载\科学上网\XX-Net\gae_proxy\local\google_ip.py", line 562, in
scan_ip_worker
    xlog.exception("google_ip.runJob fail:%s", e)
AttributeError: 'NoneType' object has no attribute 'exception'

Exception in thread Thread-857:
Traceback (most recent call last):
  File "D:\迅雷下载\科学上网\XX-Net\python27\1.0\lib\threading.py", line 810, in
 __bootstrap_inner
    self.run()
  File "D:\迅雷下载\科学上网\XX-Net\python27\1.0\lib\threading.py", line 763, in
 run
    self.__target(*self.__args, **self.__kwargs)
  File "D:\迅雷下载\科学上网\XX-Net\gae_proxy\local\google_ip.py", line 562, in
scan_ip_worker
    xlog.exception("google_ip.runJob fail:%s", e)
AttributeError: 'NoneType' object has no attribute 'exception'

Exception in thread Thread-858:
Traceback (most recent call last):
  File "D:\迅雷下载\科学上网\XX-Net\python27\1.0\lib\threading.py", line 810, in
 __bootstrap_inner
    self.run()
  File "D:\迅雷下载\科学上网\XX-Net\python27\1.0\lib\threading.py", line 763, in
 run
    self.__target(*self.__args, **self.__kwargs)
  File "D:\迅雷下载\科学上网\XX-Net\gae_proxy\local\google_ip.py", line 562, in
scan_ip_worker
    xlog.exception("google_ip.runJob fail:%s", e)
AttributeError: 'NoneType' object has no attribute 'exception'

Exception in thread Thread-860:
Traceback (most recent call last):
  File "D:\迅雷下载\科学上网\XX-Net\python27\1.0\lib\threading.py", line 810, in
 __bootstrap_inner
    self.run()
  File "D:\迅雷下载\科学上网\XX-Net\python27\1.0\lib\threading.py", line 763, in
 run
    self.__target(*self.__args, **self.__kwargs)
  File "D:\迅雷下载\科学上网\XX-Net\gae_proxy\local\google_ip.py", line 562, in
scan_ip_worker
    xlog.exception("google_ip.runJob fail:%s", e)
AttributeError: 'NoneType' object has no attribute 'exception'

Exception in thread Thread-862:
Traceback (most recent call last):
  File "D:\迅雷下载\科学上网\XX-Net\python27\1.0\lib\threading.py", line 810, in
 __bootstrap_inner
    self.run()
  File "D:\迅雷下载\科学上网\XX-Net\python27\1.0\lib\threading.py", line 763, in
 run
    self.__target(*self.__args, **self.__kwargs)
  File "D:\迅雷下载\科学上网\XX-Net\gae_proxy\local\google_ip.py", line 562, in
scan_ip_worker
    xlog.exception("google_ip.runJob fail:%s", e)
AttributeError: 'NoneType' object has no attribute 'exception'

Exception in thread Thread-863:
Traceback (most recent call last):
  File "D:\迅雷下载\科学上网\XX-Net\python27\1.0\lib\threading.py", line 810, in
 __bootstrap_inner
    self.run()
  File "D:\迅雷下载\科学上网\XX-Net\python27\1.0\lib\threading.py", line 763, in
 run
    self.__target(*self.__args, **self.__kwargs)
  File "D:\迅雷下载\科学上网\XX-Net\gae_proxy\local\google_ip.py", line 562, in
scan_ip_worker
    xlog.exception("google_ip.runJob fail:%s", e)
AttributeError: 'NoneType' object has no attribute 'exception'

Exception in thread Thread-864:
Traceback (most recent call last):
  File "D:\迅雷下载\科学上网\XX-Net\python27\1.0\lib\threading.py", line 810, in
 __bootstrap_inner
    self.run()
  File "D:\迅雷下载\科学上网\XX-Net\python27\1.0\lib\threading.py", line 763, in
 run
    self.__target(*self.__args, **self.__kwargs)
  File "D:\迅雷下载\科学上网\XX-Net\gae_proxy\local\google_ip.py", line 562, in
scan_ip_worker
    xlog.exception("google_ip.runJob fail:%s", e)
AttributeError: 'NoneType' object has no attribute 'exception'

Exception in thread Thread-866:
Traceback (most recent call last):
  File "D:\迅雷下载\科学上网\XX-Net\python27\1.0\lib\threading.py", line 810, in
 __bootstrap_inner
    self.run()
  File "D:\迅雷下载\科学上网\XX-Net\python27\1.0\lib\threading.py", line 763, in
 run
    self.__target(*self.__args, **self.__kwargs)
  File "D:\迅雷下载\科学上网\XX-Net\gae_proxy\local\google_ip.py", line 562, in
scan_ip_worker
    xlog.exception("google_ip.runJob fail:%s", e)
AttributeError: 'NoneType' object has no attribute 'exception'

Exception in thread Thread-865:
Traceback (most recent call last):
  File "D:\迅雷下载\科学上网\XX-Net\python27\1.0\lib\threading.py", line 810, in
 __bootstrap_inner
    self.run()
  File "D:\迅雷下载\科学上网\XX-Net\python27\1.0\lib\threading.py", line 763, in
 run
    self.__target(*self.__args, **self.__kwargs)
  File "D:\迅雷下载\科学上网\XX-Net\gae_proxy\local\google_ip.py", line 562, in
scan_ip_worker
    xlog.exception("google_ip.runJob fail:%s", e)
AttributeError: 'NoneType' object has no attribute 'exception'

Exception in thread Thread-869:
Traceback (most recent call last):
  File "D:\迅雷下载\科学上网\XX-Net\python27\1.0\lib\threading.py", line 810, in
 __bootstrap_inner
    self.run()
  File "D:\迅雷下载\科学上网\XX-Net\python27\1.0\lib\threading.py", line 763, in
 run
    self.__target(*self.__args, **self.__kwargs)
  File "D:\迅雷下载\科学上网\XX-Net\gae_proxy\local\google_ip.py", line 562, in
scan_ip_worker
    xlog.exception("google_ip.runJob fail:%s", e)
AttributeError: 'NoneType' object has no attribute 'exception'

Exception in thread Thread-871:
Traceback (most recent call last):
  File "D:\迅雷下载\科学上网\XX-Net\python27\1.0\lib\threading.py", line 810, in
 __bootstrap_inner
    self.run()
  File "D:\迅雷下载\科学上网\XX-Net\python27\1.0\lib\threading.py", line 763, in
 run
    self.__target(*self.__args, **self.__kwargs)
  File "D:\迅雷下载\科学上网\XX-Net\gae_proxy\local\google_ip.py", line 562, in
scan_ip_worker
    xlog.exception("google_ip.runJob fail:%s", e)
AttributeError: 'NoneType' object has no attribute 'exception'

Exception in thread Thread-868:
Traceback (most recent call last):
  File "D:\迅雷下载\科学上网\XX-Net\python27\1.0\lib\threading.py", line 810, in
 __bootstrap_inner
    self.run()
  File "D:\迅雷下载\科学上网\XX-Net\python27\1.0\lib\threading.py", line 763, in
 run
    self.__target(*self.__args, **self.__kwargs)
  File "D:\迅雷下载\科学上网\XX-Net\gae_proxy\local\google_ip.py", line 562, in
scan_ip_worker
    xlog.exception("google_ip.runJob fail:%s", e)
AttributeError: 'NoneType' object has no attribute 'exception'

Exception in thread Thread-867:
Traceback (most recent call last):
  File "D:\迅雷下载\科学上网\XX-Net\python27\1.0\lib\threading.py", line 810, in
 __bootstrap_inner
    self.run()
  File "D:\迅雷下载\科学上网\XX-Net\python27\1.0\lib\threading.py", line 763, in
 run
    self.__target(*self.__args, **self.__kwargs)
  File "D:\迅雷下载\科学上网\XX-Net\gae_proxy\local\google_ip.py", line 562, in
scan_ip_worker
    xlog.exception("google_ip.runJob fail:%s", e)
AttributeError: 'NoneType' object has no attribute 'exception'

Exception in thread Thread-870:
Traceback (most recent call last):
  File "D:\迅雷下载\科学上网\XX-Net\python27\1.0\lib\threading.py", line 810, in
 __bootstrap_inner
    self.run()
  File "D:\迅雷下载\科学上网\XX-Net\python27\1.0\lib\threading.py", line 763, in
 run
    self.__target(*self.__args, **self.__kwargs)
  File "D:\迅雷下载\科学上网\XX-Net\gae_proxy\local\google_ip.py", line 562, in
scan_ip_worker
    xlog.exception("google_ip.runJob fail:%s", e)
AttributeError: 'NoneType' object has no attribute 'exception'

Exception in thread Thread-873:
Traceback (most recent call last):
  File "D:\迅雷下载\科学上网\XX-Net\python27\1.0\lib\threading.py", line 810, in
 __bootstrap_inner
    self.run()
  File "D:\迅雷下载\科学上网\XX-Net\python27\1.0\lib\threading.py", line 763, in
 run
    self.__target(*self.__args, **self.__kwargs)
  File "D:\迅雷下载\科学上网\XX-Net\gae_proxy\local\google_ip.py", line 562, in
scan_ip_worker
    xlog.exception("google_ip.runJob fail:%s", e)
AttributeError: 'NoneType' object has no attribute 'exception'

Exception in thread Thread-875:
Traceback (most recent call last):
  File "D:\迅雷下载\科学上网\XX-Net\python27\1.0\lib\threading.py", line 810, in
 __bootstrap_inner
    self.run()
  File "D:\迅雷下载\科学上网\XX-Net\python27\1.0\lib\threading.py", line 763, in
 run
    self.__target(*self.__args, **self.__kwargs)
  File "D:\迅雷下载\科学上网\XX-Net\gae_proxy\local\google_ip.py", line 562, in
scan_ip_worker
    xlog.exception("google_ip.runJob fail:%s", e)
AttributeError: 'NoneType' object has no attribute 'exception'

Exception in thread Thread-872:
Traceback (most recent call last):
  File "D:\迅雷下载\科学上网\XX-Net\python27\1.0\lib\threading.py", line 810, in
 __bootstrap_inner
    self.run()
  File "D:\迅雷下载\科学上网\XX-Net\python27\1.0\lib\threading.py", line 763, in
 run
    self.__target(*self.__args, **self.__kwargs)
  File "D:\迅雷下载\科学上网\XX-Net\gae_proxy\local\google_ip.py", line 562, in
scan_ip_worker
    xlog.exception("google_ip.runJob fail:%s", e)
AttributeError: 'NoneType' object has no attribute 'exception'

Exception in thread Thread-874:
Traceback (most recent call last):
  File "D:\迅雷下载\科学上网\XX-Net\python27\1.0\lib\threading.py", line 810, in
 __bootstrap_inner
    self.run()
  File "D:\迅雷下载\科学上网\XX-Net\python27\1.0\lib\threading.py", line 763, in
 run
    self.__target(*self.__args, **self.__kwargs)
  File "D:\迅雷下载\科学上网\XX-Net\gae_proxy\local\google_ip.py", line 562, in
scan_ip_worker
    xlog.exception("google_ip.runJob fail:%s", e)
AttributeError: 'NoneType' object has no attribute 'exception'

Stopping all modules before exit!
Oct 20 20:15:06 - [ERROR] stop module gae_proxy fail:'imp'
Traceback (most recent call last):
  File "D:\迅雷下载\科学上网\XX-Net\launcher\module_init.py", line 71, in stop
    _start = proc_handler[module]["imp"].start
KeyError: 'imp'

Oct 20 20:15:06 - [INFO] begin to exit web control

**Comment by xxnet** [comment]
gae_proxy\local\google_ip.py", line 562

改为：
xlog.exception("google_ip.runJob fail:%r", e)

试试

2015-10-20 20:31 GMT+08:00 Richard <notifications@github.com>:

**Comment by Richard-Lucas** [comment]
额
![qq 20151102185341](https://cloud.githubusercontent.com/assets/15213283/10880062/2117e072-8193-11e5-9b66-5f85606db805.png)
![qq 20151102185449](https://cloud.githubusercontent.com/assets/15213283/10880075/365cc024-8193-11e5-8d9d-22f1aa226091.png)

**Comment by xxnet** [comment]
试试把 exception 换成 error

不过不想折腾，可以试试2.5.5

2015-11-02 18:55 GMT+08:00 Richard <notifications@github.com>:

**Comment by Richard-Lucas** [comment]
非常感谢不断给出解决意见
