### ISSUE TITLE
【不懂就问】开着xx-net的时候不能push github？

### ISSUE THREAD

**Issue by Angelhand** [XX-net/XX-Net#12549]
开着xx-net的时候，push分支的话，输入github的账户密码-不管用，再输-不管用，push失败，报错。不知道是什么原理。。。
	Push failed
			Fatal: AggregateException encountered.
			Invocation failed Unexpected end of file from server
			java.lang.RuntimeException: Invocation failed Unexpected end of file from server
			at org.jetbrains.git4idea.http.GitAskPassXmlRpcClient.askUsername(GitAskPassXmlRpcClient.java:54)
			at org.jetbrains.git4idea.http.GitAskPassApp.main(GitAskPassApp.java:65)
			Caused by: java.net.SocketException: Unexpected end of file from server
			at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:792)
			at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:647)
			at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:789)
			at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:647)
			at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1569)
			at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
			at org.apache.xmlrpc.DefaultXmlRpcTransport.sendXmlRpc(DefaultXmlRpcTransport.java:87)
			at org.apache.xmlrpc.XmlRpcClientWorker.execute(XmlRpc... (show balloon)

**Comment by AnyWAT** [comment]
识代码的已自休长假。。。

**Comment by SeaHOH** [comment]
不要使用全局代理设置
