### ISSUE TITLE
斐讯 k2p刷padavan固件，安装XX-Net后，不能运行

### ISSUE THREAD

**Issue by lijianbest** [XX-net/XX-Net#12595]
[K2P /opt/home/admin]# opkg install python-pyopenssl
Package python-pyopenssl (19.0.0-2) installed in root is up to date.
[K2P /opt/home/admin]# /opt/app/XX-Net/start
XX-Net version:3.13.1
It is OpenWrt.
It is openwrt.
2019-06-18 01:13:44.928 [launcher][INFO] This is Android or IOS or router.
2019-06-18 01:13:46.352 [launcher][INFO] import build-in openssl fail:ImportError('libssl.so.1.1: cannot open shared object file: No such file or directory',)
2019-06-18 01:13:46.638 [launcher][ERROR] import system python-OpenSSL fail:ImportError('libssl.so.1.1: cannot open shared object file: No such file or directory',)
2019-06-18 01:13:46.642 [launcher][ERROR] Except stack:Traceback (most recent call last):
  File "code/default/launcher/start.py", line 175, in <module>
    import OpenSSL
  File "/opt/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
  File "/opt/lib/python2.7/site-packages/OpenSSL/crypto.py", line 16, in <module>
  File "/opt/lib/python2.7/site-packages/OpenSSL/_util.py", line 6, in <module>
  File "/opt/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 15, in <module>
ImportError: libssl.so.1.1: cannot open shared object file: No such file or directory

Try install python-openssl

Press Enter to continue...
[K2P /opt/home/admin]#

**Comment by SeaHOH** [comment]
> Try install python-openssl

**Comment by maoxt** [comment]
opkg update
opkg install libopenssl
opkg install python-pyopenssl
我已经解决

**Comment by xxnet** [comment]
试过不安装 libopenssl吗？
按之前的经验是不需要的
