### ISSUE TITLE
OSX10.10.5,Safari，XX-net 2.5.1，点“开机自动启动”后，出现错误提示：发生未知错误, 请刷新页面重试.

### ISSUE THREAD

**Issue by gansuly** [XX-net/XX-Net#1260]
日志页：
----------------------------------------
Oct 22 11:43:48 - [DEBUG] launcher web_control 127.0.0.1:56156 GET /config?cmd=set_config&auto_start=1 
Oct 22 11:43:48 - [INFO] create file:/Users/wwrgs/Library/LaunchAgents/com.xxnet.launcher.plist
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 56156)
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 599, in process_request_thread
    self.finish_request(request, client_address)
  File "/Users/wwrgs/Software4Mac/XX-Net-2.5.1/launcher/web_control.py", line 48, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/Users/wwrgs/Software4Mac/XX-Net-2.5.1/launcher/web_control.py", line 170, in do_GET
    self.req_config_handler()
  File "/Users/wwrgs/Software4Mac/XX-Net-2.5.1/launcher/web_control.py", line 319, in req_config_handler
    autorun.enable()
  File "/Users/wwrgs/Software4Mac/XX-Net-2.5.1/launcher/autorun.py", line 133, in enable
    add("XX-Net", run_cmd)
  File "/Users/wwrgs/Software4Mac/XX-Net-2.5.1/launcher/autorun.py", line 120, in add
    with open(plist_file_path, "w") as f:
IOError: [Errno 2] No such file or directory: '/Users/wwrgs/Library/LaunchAgents/com.xxnet.launcher.plist'
----------------------------------------

状态页：
GAEProxy状态信息

系统版本

Property	Value
XX-Net Version	2.5.1
Python Version	2.7.10
Sys Platform	x86_64, Darwin-14.5.0-x86_64-i386-64bit
OS System	Darwin
OS version	Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; root:xnu-2782.40.9~1/RELEASE_X86_64
OS release	14.5.0
OS detail	Release:10.10.5; Version:('', '', '') Machine:x86_64
language	zh_CN
architecture	64bit,
Browser	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/601.1.56 (KHTML, like Gecko) Version/9.0 Safari/601.1.56
设置

Property	Value
Proxy Listen	127.0.0.1:8087
PAC URL	http://127.0.0.1:8086/proxy.pac
IPv6	0
ip-connect-interval	10
状态

Property	Value
Google IP num	3000
100th IP handshake(ms)	400
connected link(帮助)	15,1
scaning ip thread num	41
block stat(帮助)	OK
Appid

Property	Value
working appids	【这里是我自己的ID】
Out of Quota appids	
Not Exist appids

**Comment by gansuly** [comment]
已解决：在Chrome里打开xx-net的配置，点“开机自动启动”就好了！在safari里就是不行。

**Comment by lele2010lele** [comment]
喔喔
