### ISSUE TITLE
电脑掉电，然后开机后，XX-Net没有随系统启动，下载最新版，并尝试了Wiki中的方法都不行，双击start.bat提示错误

### ISSUE THREAD

**Issue by Jing--Li** [XX-net/XX-Net#12608]
双击start.bat提示错误：
2019-06-26 20:03:25.987 [launcher][INFO] use build-in openssl lib
2019-06-26 20:03:33.838 [launcher][INFO] start XX-Net 3.13.1
2019-06-26 20:03:33.839 [launcher][DEBUG] start confirm_xxnet_exit
2019-06-26 20:03:34.844 [launcher][DEBUG] good, xxnet:8085 clear!
2019-06-26 20:03:34.844 [launcher][DEBUG] finished confirm_xxnet_exit
2019-06-26 20:03:35.851 [launcher][ERROR] start module gae_proxy fail:No JSON object could be decoded
2019-06-26 20:03:35.853 [launcher][ERROR] Except stack:Traceback (most recent call last):
  File "C:\Users\Jing Li\Downloads\XX-Net-master\code\3.13.1\launcher\module_init.py", line 40, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "C:\Users\Jing Li\Downloads\XX-Net-master\code\3.13.1\gae_proxy\local\__init__.py", line 2, in <module>
    import apis
  File "C:\Users\Jing Li\Downloads\XX-Net-master\code\3.13.1\gae_proxy\local\apis.py", line 2, in <module>
    from front import front, direct_front
  File "C:\Users\Jing Li\Downloads\XX-Net-master\code\3.13.1\gae_proxy\local\front.py", line 7, in <module>
    import check_local_network
  File "C:\Users\Jing Li\Downloads\XX-Net-master\code\3.13.1\gae_proxy\local\check_local_network.py", line 28, in <module>
    from config import config
  File "C:\Users\Jing Li\Downloads\XX-Net-master\code\3.13.1\gae_proxy\local\config.py", line 404, in <module>
    config = Config(config_path)
  File "C:\Users\Jing Li\Downloads\XX-Net-master\code\3.13.1\gae_proxy\local\config.py", line 190, in __init__
    self.load()
  File "C:\Users\Jing Li\Downloads\XX-Net-master\code\3.13.1\gae_proxy\local\config.py", line 193, in load
    super(Config, self).load()
  File "C:\Users\Jing Li\Downloads\XX-Net-master\code\3.13.1\python27\1.0\lib\noarch\front_base\config.py", line 89, in load
    super(ConfigBase, self).load()
  File "C:\Users\Jing Li\Downloads\XX-Net-master\code\3.13.1\python27\1.0\lib\noarch\xconfig.py", line 22, in load
    self.file_config = json.loads(content)
  File "C:\Users\Jing Li\Downloads\XX-Net-master\code\3.13.1\python27\1.0\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Jing Li\Downloads\XX-Net-master\code\3.13.1\python27\1.0\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Jing Li\Downloads\XX-Net-master\code\3.13.1\python27\1.0\lib\json\decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

2019-06-26 20:03:35.855 [launcher][ERROR] launcher except:ValueError('No JSON object could be decoded',)
2019-06-26 20:03:35.856 [launcher][ERROR] Except stack:Traceback (most recent call last):
  File "C:\Users\Jing Li\Downloads\XX-Net-master\code\3.13.1\launcher\start.py", line 251, in <module>
    main()
  File "C:\Users\Jing Li\Downloads\XX-Net-master\code\3.13.1\launcher\start.py", line 230, in main
    module_init.start_all_auto()
  File "C:\Users\Jing Li\Downloads\XX-Net-master\code\3.13.1\launcher\module_init.py", line 113, in start_all_auto
    start(module)
  File "C:\Users\Jing Li\Downloads\XX-Net-master\code\3.13.1\launcher\module_init.py", line 40, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "C:\Users\Jing Li\Downloads\XX-Net-master\code\3.13.1\gae_proxy\local\__init__.py", line 2, in <module>
    import apis
  File "C:\Users\Jing Li\Downloads\XX-Net-master\code\3.13.1\gae_proxy\local\apis.py", line 2, in <module>
    from front import front, direct_front
  File "C:\Users\Jing Li\Downloads\XX-Net-master\code\3.13.1\gae_proxy\local\front.py", line 7, in <module>
    import check_local_network
  File "C:\Users\Jing Li\Downloads\XX-Net-master\code\3.13.1\gae_proxy\local\check_local_network.py", line 28, in <module>
    from config import config
  File "C:\Users\Jing Li\Downloads\XX-Net-master\code\3.13.1\gae_proxy\local\config.py", line 404, in <module>
    config = Config(config_path)
  File "C:\Users\Jing Li\Downloads\XX-Net-master\code\3.13.1\gae_proxy\local\config.py", line 190, in __init__
    self.load()
  File "C:\Users\Jing Li\Downloads\XX-Net-master\code\3.13.1\gae_proxy\local\config.py", line 193, in load
    super(Config, self).load()
  File "C:\Users\Jing Li\Downloads\XX-Net-master\code\3.13.1\python27\1.0\lib\noarch\front_base\config.py", line 89, in load
    super(ConfigBase, self).load()
  File "C:\Users\Jing Li\Downloads\XX-Net-master\code\3.13.1\python27\1.0\lib\noarch\xconfig.py", line 22, in load
    self.file_config = json.loads(content)
  File "C:\Users\Jing Li\Downloads\XX-Net-master\code\3.13.1\python27\1.0\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Jing Li\Downloads\XX-Net-master\code\3.13.1\python27\1.0\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Jing Li\Downloads\XX-Net-master\code\3.13.1\python27\1.0\lib\json\decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

Press Enter to continue...

**Comment by SeaHOH** [comment]
备份 data 文件夹，然后删除里面所有的 *.json 文件。

**Comment by Jing--Li** [comment]
> 备份 data/gae_proxy 文件夹，然后删除里面所有的 *.json 文件。
按照您说的做了，完美解决！万分感谢！

**Comment by Jing--Li** [comment]
> 备份 data/gae_proxy 文件夹，然后删除里面所有的 *.json 文件。

按照您说的做了，完美解决！万分感谢！
