### ISSUE TITLE
求助，xx-net打不开了

### ISSUE THREAD

**Issue by coollman** [XX-net/XX-Net#12653]
今天想用XX-net的时候发现打不开了，怎么点都没反应，重下了也不行，然后打开start.bat之后出现了如下问题
2019-07-24 17:26:24.215 [launcher][INFO] use build-in openssl lib
2019-07-24 17:26:24.233 [launcher][INFO] start XX-Net 3.13.1
2019-07-24 17:26:24.234 [launcher][DEBUG] start confirm_xxnet_exit
2019-07-24 17:26:25.240 [launcher][DEBUG] good, xxnet:8085 clear!
2019-07-24 17:26:25.241 [launcher][DEBUG] finished confirm_xxnet_exit
2019-07-24 17:26:26.350 [launcher][ERROR] start module gae_proxy fail:提供了一个无效的参数。
2019-07-24 17:26:26.352 [launcher][ERROR] Except stack:Traceback (most recent call last):
  File "E:\XX-Net-3.13.1\code\default\launcher\module_init.py", line 40, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "E:\XX-Net-3.13.1\code\default\gae_proxy\start.py", line 13, in <module>
    import local.proxy as client
  File "E:\XX-Net-3.13.1\code\default\gae_proxy\local\proxy.py", line 86, in <module>
    import proxy_handler
  File "E:\XX-Net-3.13.1\code\default\gae_proxy\local\proxy_handler.py", line 53, in <module>
    import web_control
  File "E:\XX-Net-3.13.1\code\default\gae_proxy\local\web_control.py", line 32, in <module>
    import ipv6_tunnel
  File "E:\XX-Net-3.13.1\code\default\gae_proxy\local\ipv6_tunnel\__init__.py", line 5, in <module>
    from .common import test_teredo
  File "E:\XX-Net-3.13.1\code\default\gae_proxy\local\ipv6_tunnel\common.py", line 4, in <module>
    from .pteredor import teredo_prober
  File "E:\XX-Net-3.13.1\code\default\gae_proxy\local\ipv6_tunnel\pteredor.py", line 96, in <module>
    class teredo_rs_packet(object):
  File "E:\XX-Net-3.13.1\code\default\gae_proxy\local\ipv6_tunnel\pteredor.py", line 98, in teredo_rs_packet
    rs_src = socket.inet_pton(socket.AF_INET6, link_local_addr)
  File "E:\XX-Net-3.13.1\code\default\python27\1.0\lib\win32\win_inet_pton.py", line 42, in inet_pton
    raise socket.error(ctypes.FormatError())
error: 提供了一个无效的参数。
求各位大佬帮忙解决一下，谢谢！

**Comment by SeaHOH** [comment]
如果你修改过 py 文件，请重新下载；
如果没有，估计你的硬盘快坏掉了，建议检查确认。

**Comment by SeaHOH** [comment]
关闭后仍可回复
