### ISSUE TITLE
import build-in openssl fail:ImportError('No module named pycparser',)

### ISSUE THREAD

**Issue by yrong** [XX-net/XX-Net#12761]
* X-Tunnel 支付后流量未及时到帐请直接向 xxnet.dev@gmail.com 发邮件，并附上帐号、交易单号等详细信息。

* 是否试过[最新的版本](https://github.com/XX-net/XX-Net/releases )？
是

* 是否查看过 [Wiki](https://github.com/XX-net/XX-Net/wiki )？
是

* 是否以相关关键词搜索过类似 issues？
是

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志，如包含大量文本时，请上传为 txt 文件：

➜  XX-Net-3.13.3 lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic

➜  XX-Net-3.13.3 which python
/home/ronyang/.pyenv/shims/python
➜  XX-Net-3.13.3 python --version
Python 2.7.14

➜  XX-Net-3.13.3 ./start
XX-Net version:3.13.3
Installing pyOpenSSL for your system... Please type in your password if requested
正在读取软件包列表... 完成
正在分析软件包的依赖关系树       
正在读取状态信息... 完成       
python-openssl 已经是最新版 (17.5.0-1ubuntu1)。
python-pycparser 已经是最新版 (2.18-2)。
升级了 0 个软件包，新安装了 0 个软件包，要卸载 0 个软件包，有 10 个软件包未被升级。
2019-09-18 09:44:08.307 [launcher][INFO] import build-in openssl fail:ImportError('No module named pycparser',)
2019-09-18 09:44:08.310 [launcher][ERROR] import system python-OpenSSL fail:ImportError('No module named pycparser',)
2019-09-18 09:44:08.311 [launcher][ERROR] Except stack:Traceback (most recent call last):
  File "code/default/launcher/start.py", line 177, in <module>
    import OpenSSL
  File "/ssd/XX-Net-3.13.3/code/default/python27/1.0/lib/noarch/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/ssd/XX-Net-3.13.3/code/default/python27/1.0/lib/noarch/OpenSSL/rand.py", line 12, in <module>
    from OpenSSL._util import (
  File "/ssd/XX-Net-3.13.3/code/default/python27/1.0/lib/noarch/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/ssd/XX-Net-3.13.3/code/default/python27/1.0/lib/linux/cryptography/hazmat/bindings/openssl/binding.py", line 60, in <module>
    class Binding(object):
  File "/ssd/XX-Net-3.13.3/code/default/python27/1.0/lib/linux/cryptography/hazmat/bindings/openssl/binding.py", line 109, in Binding
    libraries=_get_libraries(sys.platform)
  File "/ssd/XX-Net-3.13.3/code/default/python27/1.0/lib/linux/cryptography/hazmat/bindings/utils.py", line 97, in build_ffi_for_binding
    extra_link_args=extra_link_args,
  File "/ssd/XX-Net-3.13.3/code/default/python27/1.0/lib/linux/cryptography/hazmat/bindings/utils.py", line 105, in build_ffi
    ffi = FFI()
  File "/ssd/XX-Net-3.13.3/code/default/python27/1.0/lib/linux/cffi/api.py", line 52, in __init__
    from . import cparser, model
  File "/ssd/XX-Net-3.13.3/code/default/python27/1.0/lib/linux/cffi/cparser.py", line 6, in <module>
    import pycparser
ImportError: No module named pycparser

Try install python-openssl

Press Enter to continue...

* 如果问题得到解决，请务必回复相关情况，谢谢。

* 即使最终无法解决你遇到的问题，这也是正常的，因为系统和网络环境千差万别。最终结果也能帮助到后来者，请保持正常交流，再寻它法。

* 请不要只写标题，不写内容，不遵守规则的提问会被自动关闭。

**Comment by yrong** [comment]
pip install pycparser

**Comment by SeaHOH** [comment]
你的日志顺序是不是有点问题，XX-Net 是运行了第二次吗？

**Comment by yrong** [comment]
啥问题，缺个依赖

**Comment by SeaHOH** [comment]
不，可能是加载顺序的问题，不过之前也没见有人提这个。

**Comment by yrong** [comment]
反正我这里加了依赖就好使了

**Comment by SeaHOH** [comment]
https://github.com/XX-net/XX-Net/blob/c6165214f91ec2ee7204b43d1256c101903f63be/code/default/launcher/start.py#L165-L182

我的意思是 L177 这里没有恢复 L166 改变的加载顺序，如果恢复了，按照提示安装 python-openssl 后**可能** (没条件测试) 就不需要 pycparser，但是现在它还是尝试加载内置模块。

**Comment by yrong** [comment]
https://github.com/XX-net/XX-Net/blob/c6165214f91ec2ee7204b43d1256c101903f63be/start#L76-L105

➜ XX-Net-3.13.3 which python
/home/ronyang/.pyenv/shims/python

**Comment by SeaHOH** [comment]
这个不是我考虑的事情，实际上现在可以说是无人维护了，只是有些时候实在看不惯才会改一些东西，或者是填自己以前挖的一些坑。

**Comment by yrong** [comment]
https://github.com/XX-net/XX-Net/pull/12772

**Comment by SeaHOH** [comment]
普通用户根本不会使用到 virtualenv，pyenv 还好，但是我对 linux 不熟悉，你这么修改的逻辑没看明白，感觉这不符合 @xxnet 原本的设计意图。
你没有试过在 L172 后面添加一句 `del sys.path[0]` 来移除内置模块的优先加载吗？然后按照提示执行 `install python-openssl` 后，如果能正常运行就不需要其它修复了。
