### ISSUE TITLE
 [x_tunnel][ERROR] bind to 127.0.0.1:1080 fail:error(10013, '')

### ISSUE THREAD

**Issue by squarefaceyao** [XX-net/XX-Net#12771]
2019-09-19 18:57:36.196 [launcher][INFO] use build-in openssl lib
2019-09-19 18:57:36.209 [launcher][INFO] start XX-Net 3.13.3
2019-09-19 18:57:36.209 [launcher][DEBUG] start confirm_xxnet_exit
2019-09-19 18:57:38.231 [launcher][DEBUG] good, xxnet:8085 clear!
2019-09-19 18:57:38.231 [launcher][DEBUG] finished confirm_xxnet_exit
2019-09-19 18:57:40.704 [gae_proxy][INFO] ------------------------------------------------------
2019-09-19 18:57:40.705 [gae_proxy][INFO] Python Version     : 2.7.13
2019-09-19 18:57:40.705 [gae_proxy][INFO] OS                 : Version:10-0; Build:18362; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
2019-09-19 18:57:40.705 [gae_proxy][INFO] Listen Address     : 127.0.0.1:8087
2019-09-19 18:57:40.706 [gae_proxy][INFO] Using public APPID
2019-09-19 18:57:40.706 [gae_proxy][INFO] ------------------------------------------------------
2019-09-19 18:57:40.706 [gae_proxy][INFO] no GAE CA file exist in XX-Net data dir
2019-09-19 18:57:40.706 [gae_proxy][INFO] clean old site certs in XX-Net cert dir
2019-09-19 18:57:40.709 [gae_proxy][INFO] generate CA file:C:\Users\SquareFace\Downloads\XX-Net-3.13.3\XX-Net-3.13.3\data\gae_proxy\CAkey.pem
2019-09-19 18:57:41.211 [gae_proxy][INFO] create CA
2019-09-19 18:57:41.214 [gae_proxy][INFO] generate certs's key file:C:\Users\SquareFace\Downloads\XX-Net-3.13.3\XX-Net-3.13.3\data\gae_proxy\Certkey.pem
2019-09-19 18:57:41.429 [gae_proxy][DEBUG] network IPv4 is ok, cost:1167 ms
2019-09-19 18:57:41.444 [gae_proxy][DEBUG] Importing CA
2019-09-19 18:57:41.445 [gae_proxy][DEBUG] Begin to import Windows CA
2019-09-19 18:57:53.144 [gae_proxy][DEBUG] Invalid Windows CA u'GoAgent XX-Net' has been removed
2019-09-19 18:57:57.639 [gae_proxy][INFO] SSL use version:TLSv1_2
2019-09-19 18:57:57.655 [gae_proxy][INFO] OpenSSL support alpn
2019-09-19 18:57:57.664 [gae_proxy][INFO] load ip range file:C:\Users\SquareFace\Downloads\XX-Net-3.13.3\XX-Net-3.13.3\code\default\gae_proxy\local\ip_range.txt
2019-09-19 18:57:57.706 [gae_proxy][INFO] SSL use version:TLSv1_2
2019-09-19 18:57:57.709 [gae_proxy][INFO] server 127.0.0.1:8087 started.
2019-09-19 18:57:57.787 [launcher][INFO] module gae_proxy started
2019-09-19 18:57:57.787 [launcher][INFO] start gae_proxy time cost:19552 ms
WARNING:root:Load Crypto.Cipher.ARC4 Failed, Use Pure Python Instead.
2019-09-19 18:57:57.946 [cloudflare_front][INFO] SSL use version:TLSv1_2
2019-09-19 18:57:57.957 [cloudflare_front][INFO] OpenSSL support alpn
2019-09-19 18:57:57.958 [cloudflare_front][INFO] load ip range file:C:\Users\SquareFace\Downloads\XX-Net-3.13.3\XX-Net-3.13.3\code\default\x_tunnel\local\cloudflare_front\ip_range.txt
2019-09-19 18:57:57.965 [cloudflare_front][INFO] load ip_list num:99, target num:99
2019-09-19 18:57:57.991 [cloudfront_front][INFO] SSL use version:TLSv1_2
2019-09-19 18:57:57.999 [cloudfront_front][INFO] OpenSSL support alpn
2019-09-19 18:57:58.000 [cloudfront_front][INFO] load ip range file:C:\Users\SquareFace\Downloads\XX-Net-3.13.3\XX-Net-3.13.3\code\default\x_tunnel\local\cloudfront_front\ip_range.txt
2019-09-19 18:57:58.002 [cloudfront_front][INFO] load ip_list num:100, target num:100
2019-09-19 18:57:58.012 [tls_relay][INFO] SSL use version:TLSv1_2
2019-09-19 18:57:58.013 [tls_relay][INFO] OpenSSL support alpn
2019-09-19 18:57:58.024 [heroku_front][INFO] SSL use version:TLSv1_2
2019-09-19 18:57:58.025 [heroku_front][INFO] OpenSSL support alpn
2019-09-19 18:57:58.026 [heroku_front][INFO] load ip_list num:75, target num:75
2019-09-19 18:57:58.031 [x_tunnel][INFO] use config_path:C:\Users\SquareFace\Downloads\XX-Net-3.13.3\XX-Net-3.13.3\data\x_tunnel\client.json
2019-09-19 18:57:58.032 [x_tunnel][INFO] X-Tunnel window:16777216
2019-09-19 18:57:58.034 [x_tunnel][INFO] xxnet_version:3.13.3

2019-09-19 18:57:58.035 [x_tunnel][ERROR] bind to 127.0.0.1:1080 fail:error(10013, '')
Exception in thread Thread-50:
Traceback (most recent call last):
  File "C:\Users\SquareFace\Downloads\XX-Net-3.13.3\XX-Net-3.13.3\code\default\python27\1.0\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Users\SquareFace\Downloads\XX-Net-3.13.3\XX-Net-3.13.3\code\default\python27\1.0\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Users\SquareFace\Downloads\XX-Net-3.13.3\XX-Net-3.13.3\code\default\x_tunnel\start.py", line 19, in main
    client.main(args)
  File "C:\Users\SquareFace\Downloads\XX-Net-3.13.3\XX-Net-3.13.3\code\default\x_tunnel\local\client.py", line 177, in main
    g.socks5_server = simple_http_server.HTTPServer(addresses, Socks5Server, logger=xlog)
  File "C:\Users\SquareFace\Downloads\XX-Net-3.13.3\XX-Net-3.13.3\code\default\python27\1.0\lib\noarch\simple_http_server.py", line 412, in __init__
    self.init_socket()
  File "C:\Users\SquareFace\Downloads\XX-Net-3.13.3\XX-Net-3.13.3\code\default\python27\1.0\lib\noarch\simple_http_server.py", line 430, in init_socket
    self.add_listen((ip, port))
  File "C:\Users\SquareFace\Downloads\XX-Net-3.13.3\XX-Net-3.13.3\code\default\python27\1.0\lib\noarch\simple_http_server.py", line 444, in add_listen
    raise Exception(err_string)
Exception: bind to 127.0.0.1:1080 fail:error(10013, '')

**Comment by SeaHOH** [comment]
请关闭其它代理，或者换一个不是 1080 的端口。
