### ISSUE TITLE
OpenWRT路由器上出现的诡异问题

### ISSUE THREAD

**Issue by erdcy** [XX-net/XX-Net#12879]
最近可能是因为路由器上的U盘有坏块，先发现正常运行很久的XX-Net不能启动了，启动的时候报错“Bus Error"。换了u盘，重刷了相同版本的OpenWRT，安装了python python-openssl和python-pyopenssl，运行XX-Net，报错”try install openssl"。以前在OpenWRT配置XX-Net一直是按照这个步骤来的，居然在相同版本的系统上不能运行了。难道是python和相关软件包升级了，不匹配XX-Net了？
附上launcher.log
2020-01-14 15:30:40.984 - [INFO] This is Android or IOS or router.
2020-01-14 15:30:41.651 - [INFO] import build-in openssl fail:ImportError('Error relocating /usr/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so: RSA_get0_crt_params: symbol not found',)
2020-01-14 15:30:41.816 - [ERROR] import system python-OpenSSL fail:ImportError('Error relocating /usr/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so: RSA_get0_crt_params: symbol not found',)
2020-01-14 15:30:41.820 - [ERROR] Except stack:Traceback (most recent call last):
  File "code/default/launcher/start.py", line 177, in <module>
    import OpenSSL
  File "/usr/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/lib/python2.7/site-packages/OpenSSL/crypto.py", line 16, in <module>
    from OpenSSL._util import (
  File "/usr/lib/python2.7/site-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/usr/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 13, in <module>
ImportError: Error relocating /usr/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so: RSA_get0_crt_params: symbol not found

**Comment by SeaHOH** [comment]
有可能，py2 要淘汰了。

**Comment by erdcy** [comment]
在路由器安装python3支持包，能用XX-Net吗？

**Comment by SeaHOH** [comment]
不兼容 python3

**Comment by erdcy** [comment]
OpenWRT更新到19.07.1，安装python，python-openssl，python-pyopenssl，XX-Net可以正常运行了。

**Comment by deckyue** [comment]
> OpenWRT更新到19.07.1，安装python，python-openssl，python-pyopenssl，XX-Net可以正常运行了。

朋友，有上面几个的离线ipk吗？在线的也行。

**Comment by erdcy** [comment]
没有专门下载ipk，直接putty ssh登入路由器，然后运行
opkg update
opkg install python python-openssl
就可以了，python-pyopenssl好像可以不装。
或者在luci界面的“软件”标签页，安装上述两个（不确定python-pyopenssl是否需要装）软件也可以。
