### ISSUE TITLE
XX-Net 3.14.2版本启动报错

### ISSUE THREAD

**Issue by Jeanferly** [XX-net/XX-Net#12924]
windows10下运行start.bat报错如下：

2020-02-10 17:38:00.139 [gae_proxy][ERROR] bind to 127.0.0.1:8087 fail:error(10013, '')
Exception in thread Thread-3:
Traceback (most recent call last):
  File "D:\software\network\XX-Net-3.14.2\code\default\python27\1.0\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "D:\software\network\XX-Net-3.14.2\code\default\python27\1.0\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "D:\software\network\XX-Net-3.14.2\code\default\gae_proxy\start.py", line 18, in main
    client.main(args)
  File "D:\software\network\XX-Net-3.14.2\code\default\gae_proxy\local\proxy.py", line 135, in main
    addresses, proxy_handler.GAEProxyHandler, logger=xlog)
  File "D:\software\network\XX-Net-3.14.2\code\default\python27\1.0\lib\noarch\simple_http_server.py", line 412, in __init__
    self.init_socket()
  File "D:\software\network\XX-Net-3.14.2\code\default\python27\1.0\lib\noarch\simple_http_server.py", line 430, in init_socket
    self.add_listen((ip, port))
  File "D:\software\network\XX-Net-3.14.2\code\default\python27\1.0\lib\noarch\simple_http_server.py", line 444, in add_listen
    raise Exception(err_string)
Exception: bind to 127.0.0.1:8087 fail:error(10013, '')

**Comment by Jeanferly** [comment]
检查端口也没有被占用，是操作系统不兼容吗

**Comment by xxnet** [comment]
一般还是端口被占用了

参考这里
https://stackoverflow.com/questions/48198/how-can-you-find-out-which-process-is-listening-on-a-port-on-windows

**Comment by Jeanferly** [comment]
> 一般还是端口被占用了 参考这里 https://stackoverflow.com/questions/48198/how-can-you-find-out-which-process-is-listening-on-a-port-on-windows

我使用netstat -abno命令检查过，确实没有查到这个端口的使用情况，可以修改这个端口号吗？

**Comment by xxnet** [comment]
可以修改端口的，参考这里：

https://github.com/XX-net/XX-Net/wiki/GoAgent-Config-file
