### ISSUE TITLE
MacOS 10.15.3 XX-Net 任何版本都无法启动

### ISSUE THREAD

**Issue by reinkin** [XX-net/XX-Net#12938]
从3.13.3自动升级至3.14.0之后使用正常

后重启，发觉无法启动，下载3.14.2，情况依旧。

具体表现
双击运行目录下start
/Applications/XX-Net/start ; exit;
XX-Net version:3.14.2
Run XX-Net in background.
zsh: failed to write history file /Users/Rein/.zsh_history: permission denied

任务栏没有图标，网页不弹出，8085也没有监听。看log感觉什么都没做就开始执行退出了，望解惑……

launcher.log只有如下内容
2020-02-14 17:21:31.779 - [INFO] use build-in openssl lib
2020-02-14 17:21:31.780 - [INFO] start XX-Net 3.14.2
2020-02-14 17:21:31.780 - [DEBUG] start confirm_xxnet_exit
2020-02-14 17:21:31.781 - [DEBUG] good, xxnet:8085 clear!
2020-02-14 17:21:31.781 - [DEBUG] finished confirm_xxnet_exit

**Comment by xxnet** [comment]
解决问题之前可以先回到 3.14.0，下载后运行，关闭自动升级。

**Comment by reinkin** [comment]
3.14.0 自动升级后未重启正常，重启了也不行。
回滚到3.13.3，结果发觉一样的情况，应该是哪里升级过程中被改掉了，具体哪里不是很清楚。
【更新】另一台机器的WIN10也不能启动了……

**Comment by reinkin** [comment]
试了3.15.1，情况在OSX/WIN10上依旧。

WIN错误

脚本：C:\XX-Net\start.vbs
行：78
字符：5
错误：系统未找到指定的资源

代码：800C0008
源：msxml3.dll

**Comment by reinkin** [comment]
【已解决】莫名其妙好了…… 不好意思麻烦了

**Comment by reinkin** [comment]
【更新log】
2020-02-16 19:45:13.633 - [INFO] use build-in openssl lib
2020-02-16 19:45:13.634 - [INFO] start XX-Net 3.14.2
2020-02-16 19:45:13.634 - [DEBUG] start confirm_xxnet_exit
2020-02-16 19:45:13.635 - [DEBUG] good, xxnet:8085 clear!
2020-02-16 19:45:13.635 - [DEBUG] finished confirm_xxnet_exit
2020-02-16 19:45:13.640 - [ERROR] start module gae_proxy fail:Extra data: line 31 column 1 - line 41 column 2 (char 618 - 724)
2020-02-16 19:45:13.641 - [ERROR] Except stack:Traceback (most recent call last):
  File "/Applications/XX-Net/code/default/launcher/module_init.py", line 40, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "/Applications/XX-Net/code/default/gae_proxy/local/__init__.py", line 2, in <module>
    import apis
  File "/Applications/XX-Net/code/default/gae_proxy/local/apis.py", line 2, in <module>
    from front import front, direct_front
  File "/Applications/XX-Net/code/default/gae_proxy/local/front.py", line 7, in <module>
    import check_local_network
  File "/Applications/XX-Net/code/default/gae_proxy/local/check_local_network.py", line 28, in <module>
    from config import config
  File "/Applications/XX-Net/code/default/gae_proxy/local/config.py", line 438, in <module>
    config = Config(config_path)
  File "/Applications/XX-Net/code/default/gae_proxy/local/config.py", line 224, in __init__
    self.load()
  File "/Applications/XX-Net/code/default/gae_proxy/local/config.py", line 227, in load
    super(Config, self).load()
  File "/Applications/XX-Net/code/default/python27/1.0/lib/noarch/front_base/config.py", line 89, in load
    super(ConfigBase, self).load()
  File "/Applications/XX-Net/code/default/python27/1.0/lib/noarch/xconfig.py", line 22, in load
    self.file_config = json.loads(content)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 367, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 31 column 1 - line 41 column 2 (char 618 - 724)

2020-02-16 19:45:13.641 - [ERROR] launcher except:ValueError('Extra data: line 31 column 1 - line 41 column 2 (char 618 - 724)',)
2020-02-16 19:45:13.642 - [ERROR] Except stack:Traceback (most recent call last):
  File "code/default/launcher/start.py", line 253, in <module>
  File "code/default/launcher/start.py", line 232, in main
  File "/Applications/XX-Net/code/default/launcher/module_init.py", line 113, in start_all_auto
    start(module)
  File "/Applications/XX-Net/code/default/launcher/module_init.py", line 40, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "/Applications/XX-Net/code/default/gae_proxy/local/__init__.py", line 2, in <module>
    import apis
  File "/Applications/XX-Net/code/default/gae_proxy/local/apis.py", line 2, in <module>
    from front import front, direct_front
  File "/Applications/XX-Net/code/default/gae_proxy/local/front.py", line 7, in <module>
    import check_local_network
  File "/Applications/XX-Net/code/default/gae_proxy/local/check_local_network.py", line 28, in <module>
    from config import config
  File "/Applications/XX-Net/code/default/gae_proxy/local/config.py", line 438, in <module>
    config = Config(config_path)
  File "/Applications/XX-Net/code/default/gae_proxy/local/config.py", line 224, in __init__
    self.load()
  File "/Applications/XX-Net/code/default/gae_proxy/local/config.py", line 227, in load
    super(Config, self).load()
  File "/Applications/XX-Net/code/default/python27/1.0/lib/noarch/front_base/config.py", line 89, in load
    super(ConfigBase, self).load()
  File "/Applications/XX-Net/code/default/python27/1.0/lib/noarch/xconfig.py", line 22, in load
    self.file_config = json.loads(content)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 367, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 31 column 1 - line 41 column 2 (char 618 - 724)

2020-02-16 19:45:13.642 - [ERROR] uncaught Exception, type=<type 'exceptions.EOFError'> value=EOF when reading a line traceback:Traceback (most recent call last):
  File "code/default/launcher/start.py", line 260, in <module>
EOFError: EOF when reading a line

2020-02-16 19:45:13.642 - [ERROR] stop module gae_proxy fail:'imp'
2020-02-16 19:45:13.642 - [ERROR] Except stack:Traceback (most recent call last):
  File "/Applications/XX-Net/code/default/launcher/module_init.py", line 74, in stop
    _start = proc_handler[module]["imp"].start
KeyError: 'imp'

2020-02-16 19:45:13.642 - [INFO] begin to exit web control
2020-02-16 19:45:13.643 - [ERROR] uncaught Exception, type=<type 'exceptions.AttributeError'> value='NoneType' object has no attribute 'shutdown' traceback:Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "code/default/launcher/start.py", line 196, in exit_handler
  File "/Applications/XX-Net/code/default/launcher/web_control.py", line 718, in stop
    server.shutdown()
AttributeError: 'NoneType' object has no attribute 'shutdown'

**Comment by reinkin** [comment]
【已解决】config.json 格式错误……

**Comment by EvenQAQ** [comment]
【求助】想问一下你是怎么解决问题的，我遇到了和你一样的问题，求助！ @reinkin

**Comment by reinkin** [comment]
【已解决】config.json 格式错误……
https://github.com/XX-net/XX-Net/wiki/GoAgent-Config-file

**Comment by EvenQAQ** [comment]
> 【已解决】config.json 格式错误……
> https://github.com/XX-net/XX-Net/wiki/GoAgent-Config-file

我发现我没有config.json，怕是凉了 @xxnet

**Comment by xxnet** [comment]
命令行启动看输出什么

**Comment by EvenQAQ** [comment]
> 命令行启动看输出什么

运行xx_net.sh后就是这种情况
-n Starting xx_net proxy server:
xx_net.
log信息和这位大兄弟的一样，好像还没做什么就直接exit了
但是我data/gae_proxy下没有config.json，怀疑是本地有什么问题
3.14.0 3.14.2 3.15.3都试过了

**Comment by xxnet** [comment]
执行 ./start呢？

**Comment by EvenQAQ** [comment]
> 执行 ./start呢？

XX-Net version:3.14.0
Run XX-Net in background.
但是并没有实际启动

**Comment by floatin** [comment]
@reinkin 请问在macos10.15下你是怎么解决miredo不可用的问题的？这个问题困扰我很久。

**Comment by xxnet** [comment]
试试 
python code/default/launcher/start.py
@EvenQAQ 


目前直接IPv4就可以了，不需要IPv6 @floatin

**Comment by reinkin** [comment]
@floatin 没解决。目前IPv4可以用，v6的话我申请了原生IPv6，自己扫不到IP，导入了@XXnet脚本扫的IP才有的。

**Comment by EvenQAQ** [comment]
> 试试
> python code/default/launcher/start.py
> @EvenQAQ
> 
> 目前直接IPv4就可以了，不需要IPv6 @floatin

2020-02-22 15:54:18.869 [gae_proxy][ERROR] bind to 127.0.0.1:8087 fail:error(48, 'Address already in use')
Exception: bind to 127.0.0.1:8087 fail:error(48, 'Address already in use')
说我地址已经被用了,是不是我之前关闭的时候有问题

**Comment by EvenQAQ** [comment]
> > 试试
> > python code/default/launcher/start.py
> > @EvenQAQ
> > 目前直接IPv4就可以了，不需要IPv6 @floatin
> 
> 2020-02-22 15:54:18.869 [gae_proxy][ERROR] bind to 127.0.0.1:8087 fail:error(48, 'Address already in use')
> Exception: bind to 127.0.0.1:8087 fail:error(48, 'Address already in use')
> 说我地址已经被用了,是不是我之前关闭的时候有问题

解决了呢,多谢! 我端口占用kill掉了
