### ISSUE TITLE
在manjaro(Arch linux分支的)上运行出现这个错误，按提示安装pyopenssl之后还是没有用

### ISSUE THREAD

**Issue by daungkf** [XX-net/XX-Net#12951]
XX-Net version:3.14.0
Installing pyOpenSSL for your system... Please type in your password if requested
2020-02-18 20:22:16.261 [launcher][INFO] import build-in openssl fail:ImportError('No module named pycparser',)
2020-02-18 20:22:16.265 [launcher][ERROR] import system python-OpenSSL fail:ImportError('No module named pycparser',)
2020-02-18 20:22:16.265 [launcher][ERROR] Except stack:Traceback (most recent call last):
  File "code/default/launcher/start.py", line 177, in <module>
    import OpenSSL
  File "/home/ykf/下载/XX-Net-3.14.0/code/default/python27/1.0/lib/noarch/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/home/ykf/下载/XX-Net-3.14.0/code/default/python27/1.0/lib/noarch/OpenSSL/rand.py", line 12, in <module>
    from OpenSSL._util import (
  File "/home/ykf/下载/XX-Net-3.14.0/code/default/python27/1.0/lib/noarch/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/home/ykf/下载/XX-Net-3.14.0/code/default/python27/1.0/lib/linux/cryptography/hazmat/bindings/openssl/binding.py", line 60, in <module>
    class Binding(object):
  File "/home/ykf/下载/XX-Net-3.14.0/code/default/python27/1.0/lib/linux/cryptography/hazmat/bindings/openssl/binding.py", line 109, in Binding
    libraries=_get_libraries(sys.platform)
  File "/home/ykf/下载/XX-Net-3.14.0/code/default/python27/1.0/lib/linux/cryptography/hazmat/bindings/utils.py", line 97, in build_ffi_for_binding
    extra_link_args=extra_link_args,
  File "/home/ykf/下载/XX-Net-3.14.0/code/default/python27/1.0/lib/linux/cryptography/hazmat/bindings/utils.py", line 105, in build_ffi
    ffi = FFI()
  File "/home/ykf/下载/XX-Net-3.14.0/code/default/python27/1.0/lib/linux/cffi/api.py", line 52, in __init__
    from . import cparser, model
  File "/home/ykf/下载/XX-Net-3.14.0/code/default/python27/1.0/lib/linux/cffi/cparser.py", line 6, in <module>
    import pycparser
ImportError: No module named pycparser

**Comment by xxnet** [comment]
试试
sudo pacman -s  openssl python2-pyopenssl python-pycparser

**Comment by haizhou37** [comment]
> 试试 sudo pacman -s openssl python2-pyopenssl python-pycparser

![图片](https://user-images.githubusercontent.com/33272474/75621409-d7322600-5bce-11ea-997d-80e0232ba6ab.png)

我也是在manjaro系统上无法运行

**Comment by xxnet** [comment]
应该是:

sudo pacman -S python2-pyopenssl

启动脚本问题下个版本改进
