### ISSUE TITLE
XX-Net 无法启动

### ISSUE THREAD

**Issue by qrsikno2** [XX-net/XX-Net#12961]
信息大概如下:
` XX-Net version:3.14.0
2020-02-21 21:05:16.908 [launcher][INFO] Using PyGTK as the GUI Backend.
2020-02-21 21:05:16.950 [launcher][WARNING] import pynotify fail, please install python-notify if possible.
2020-02-21 21:05:16.957 [launcher][INFO] Gtk.StatusIcon used.
2020-02-21 21:05:16.990 [launcher][INFO] import build-in openssl fail:AttributeError("'module' object has no attribute 'SSL_ST_INIT'",)
2020-02-21 21:05:17.033 [launcher][INFO] start XX-Net 3.14.0
2020-02-21 21:05:17.033 [launcher][DEBUG] start confirm_xxnet_exit

2020-02-21 21:05:47.046 [launcher][DEBUG] good, xxnet:8085 clear!
2020-02-21 21:05:47.047 [launcher][DEBUG] finished confirm_xxnet_exit
2020-02-21 21:06:17.483 [gae_proxy][INFO] ------------------------------------------------------
2020-02-21 21:06:17.483 [gae_proxy][INFO] Python Version     : 2.7.17
2020-02-21 21:06:17.484 [gae_proxy][INFO] OS                 : Dist:; Version:; ID:
2020-02-21 21:06:17.484 [gae_proxy][INFO] Listen Address     : 127.0.0.1:8087
2020-02-21 21:06:17.484 [gae_proxy][INFO] Using public APPID
2020-02-21 21:06:17.484 [gae_proxy][INFO] ------------------------------------------------------
2020-02-21 21:06:17.487 [gae_proxy][DEBUG] Importing CA
2020-02-21 21:06:17.562 [gae_proxy][INFO] Database $HOME/.pki/nssdb cert exist
2020-02-21 21:06:17.563 [gae_proxy][DEBUG] Begin importing CA to Firefox
2020-02-21 21:06:17.578 [gae_proxy][INFO] Removing old cert to Firefox in /home/qrsikno/.mozilla/firefox/04qxerxm.default
GoAgent XX-Net - GoAgent                                     C,,  
2020-02-21 21:06:18.213 [gae_proxy][INFO] Add new cert to Firefox in /home/qrsikno/.mozilla/firefox/04qxerxm.default
2020-02-21 21:06:18.421 [gae_proxy][INFO] SSL use version:TLSv1_2
2020-02-21 21:06:18.423 [gae_proxy][INFO] OpenSSL support alpn
2020-02-21 21:06:18.424 [gae_proxy][INFO] load ip range file:/home/qrsikno/XXNet/code/default/gae_proxy/local/ip_range.txt
2020-02-21 21:06:18.434 [gae_proxy][INFO] SSL use version:TLSv1_2
2020-02-21 21:06:18.437 [gae_proxy][ERROR] bind to 127.0.0.1:8087 fail:error(99, '\xe6\x97\xa0\xe6\xb3\x95\xe6\x8c\x87\xe5\xae\x9a\xe8\xa2\xab\xe8\xaf\xb7\xe6\xb1\x82\xe7\x9a\x84\xe5\x9c\xb0\xe5\x9d\x80')
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/qrsikno/XXNet/code/default/gae_proxy/start.py", line 18, in main
    client.main(args)
  File "/home/qrsikno/XXNet/code/default/gae_proxy/local/proxy.py", line 135, in main
    addresses, proxy_handler.GAEProxyHandler, logger=xlog)
  File "/home/qrsikno/XXNet/code/default/python27/1.0/lib/noarch/simple_http_server.py", line 412, in __init__
    self.init_socket()
  File "/home/qrsikno/XXNet/code/default/python27/1.0/lib/noarch/simple_http_server.py", line 430, in init_socket
    self.add_listen((ip, port))
  File "/home/qrsikno/XXNet/code/default/python27/1.0/lib/noarch/simple_http_server.py", line 444, in add_listen
    raise Exception(err_string)
Exception: bind to 127.0.0.1:8087 fail:error(99, '\xe6\x97\xa0\xe6\xb3\x95\xe6\x8c\x87\xe5\xae\x9a\xe8\xa2\xab\xe8\xaf\xb7\xe6\xb1\x82\xe7\x9a\x84\xe5\x9c\xb0\xe5\x9d\x80')

2020-02-21 21:06:18.760 [gae_proxy][DEBUG] network IPv4 is ok, cost:1706 ms
2020-02-21 21:07:07.846 [gae_proxy][INFO] scan_ip add ip:2607:f8b0:4008:802::2014 time:4640 h2:1
2020-02-21 21:07:15.393 [gae_proxy][INFO] scan_ip add ip:2607:f8b0:4002:c09::99 time:1859 h2:1
`
用了3.15.3也是这个样子, 访问127.0.0.1:8087和8085端口都不行.
系统: Archlinux

**Comment by latiaoer** [comment]
quora也不能正常显示

**Comment by qrsikno2** [comment]
现在修好了! miredo好像吧所有的端口都占用了. 我v2ray 都烂了
应该先开XXNET,再开miredo
