### ISSUE TITLE
[发布] 新版 3.15.10 改善智能路由域名解析性能

### ISSUE THREAD

**Issue by chinaniupai** [XX-net/XX-Net#12985]
新版 3.15.10 发布，主要改进智能路由域名解析性能。
https://github.com/XX-net/XX-Net/releases/tag/3.15.10

下载地址：
https://github.com/XX-net/XX-Net/archive/3.15.10.zip

**Comment by YUFUXUECHI** [comment]
为何用不了啊

**Comment by YUFUXUECHI** [comment]
启动不了

**Comment by pch9527** [comment]
作者辛苦了！
顺便问一下：zip是精简版  7z是完整版  对吗？

**Comment by AnyWAT** [comment]
@xxnet Cloudflare 前端许久以来各版本均出如下红色错误日志，是神马原因？
2020-03-01 14:07:58.913 - [INFO] load ip_list num:44, target num:44

2020-03-01 14:08:00.867 - [ERROR] updated cloudflare front domains from github fail:error(10054, '')
2020-03-01 14:08:00.867 - [ERROR] Except stack:Traceback (most recent call last): File "Z:\XX-Net\code\3.15.10\x_tunnel\local\cloudflare_front\host_manager.py", line 69, in update_front_domains response = client.request("GET", url) File "Z:\XX-Net\code\3.15.10\python27\1.0\lib\noarch\simple_http_client.py", line 454, in request sock = ssl.wrap_socket(sock) File "Z:\XX-Net\python27\2.0\lib\ssl.py", line 931, in wrap_socket ciphers=ciphers) File "Z:\XX-Net\python27\2.0\lib\ssl.py", line 599, in __init__ self.do_handshake() File "Z:\XX-Net\python27\2.0\lib\ssl.py", line 828, in do_handshake self._sslobj.do_handshake() error: [Errno 10054]

2020-03-01 14:10:29.948 - [DEBUG] create_ssl update ip:......

**Comment by xxnet** [comment]
@pch9527 
是的

**Comment by foho8080** [comment]
![0001](https://user-images.githubusercontent.com/17214241/75642572-eff61680-5c76-11ea-8c29-c96e7e52c395.jpg)

這個版本還會出現這個問題

**Comment by xxnet** [comment]
这个问题没有解决，只是临时绕过去了，异常退出会自动重启。

具体问题已经提交给python开发组了

**Comment by Litangren** [comment]
3.15.10更新失败，即使是人工下载覆盖，覆盖后无法启动。

**Comment by Litangren** [comment]
倡议书：有能力的请购买X-TUNNEL流量，以答谢开发者！

**Comment by Litangren** [comment]
还有啊，就是IDM下载U2视频卡得死死的！！！！不知道是谁的原因。。。。。。下载线程调到了4也不行。

**Comment by xxnet** [comment]
卡死是具体是电脑变得很慢，还是下载很慢，还是怎样的效果？

**Comment by zizicheng** [comment]
![image](https://user-images.githubusercontent.com/17800352/75781360-fdef8880-5d97-11ea-9b72-3ba5fbb935c6.png)
无法正常启动，前面的版本可以正常使用 ？？

**Comment by hdrafyy** [comment]
感觉还是3.15.4的连接速度要快一点。

**Comment by xxnet** [comment]
@zizicheng 请下载Windows版本

**Comment by Litangren** [comment]
> 卡死是具体是电脑变得很慢，还是下载很慢，还是怎样的效果？

电脑变得很慢，还不停黑屏，移动鼠标都很困难，下载也变慢。退出IDM下载之后便恢复流畅了。

**Comment by xxnet** [comment]
能看到是哪个进程CPU高吗？或者是内存占用太高了？
我这边没有重现这个现象

**Comment by Litangren** [comment]
> 能看到是哪个进程CPU高吗？或者是内存占用太高了？ 我这边没有重现这个现象

映像名称        CPU         内存（专用工作集）
System              65               60 K
pythonw.exe     13          117,384 K
System Idle ...    08               24 K 
IDMan.exe         04           17,12 K
chrome.exe        04          209,676 K
chrome.exe        02           15,868 K
...

CPU使用率：94%   物理内存：61%

电脑配置不高，但在其它代理软件下下载还可以接受。

**Comment by xxnet** [comment]
python 的CPU 13%不高，但是system 高达 65%
不知道系统在忙些什么。

你看看IO是否高，硬盘忙不忙

**Comment by xianyu1919810** [comment]
请问可以给一个云盘的下载链接吗？我在github上怎么下载都是损坏的

**Comment by 2handshake** [comment]
> python的CPU 13％不高，但是系统高达65％不知道系统在忙些什么。你看看IO是否高，硬盘忙不忙

Good ip 扫描出来之后存在本地，前几天可用IP有很多，今天就很少了，会不会GFW的人直接把goodip扫描出来直接墙掉了，不知道作者能不能把goodip这个文件进行加密，这样会不会扫描出来的节点就能安全一点。

**Comment by Rven71** [comment]
软件自动重启的频率很高

**Comment by SandroGong** [comment]
新版本智能路由似乎上国内网站没有问题了，但是对outlook还是有影响，我的outlook里面所有邮件的图片都显示不了，且无法收发邮件，只有关闭智能路由（切换到pac的话必须pac策略不是"全部-smartrouter),才可以。但是Pac策略的黑名单本身并不包括维基等网站，所以pac情况下我开不了维基看。

**Comment by myjlpt** [comment]
@xxnet  报告一下，我这边使用环境 是双Python ，因为有爬虫需求。所以安装有Python38，。。
XXNET默认是2.7吧。但我这边使用一直正常啊.

**Comment by xxnet** [comment]
> @xxnet <https://github.com/xxnet> 报告一下，我这边使用环境 是双Python
> ，因为有爬虫需求。所以安装有Python38，。。
> XXNET默认是2.7吧。但我这边使用一直正常啊.
>
Windows版本XX-Net 内置了python环境

**Comment by xxnet** [comment]
>
> 新版本智能路由似乎上国内网站没有问题了，但是对outlook还是有影响，我的outlook里面所有邮件的图片都显示不了，且无法收发邮件，只有关闭智能路由（切换到pac的话必须pac策略不是"全部-smartrouter),才可以。但是Pac策略的黑名单本身并不包括维基等网站，所以pac情况下我开不了维基看。
>
收到反馈谢谢。
outlook问题，你可以观察当outlook工作时，smart_router的日志里的内容，观察图片的地址被怎么处理了。
试试把这些域名放入smart_router的直连列表中

**Comment by SandroGong** [comment]
> 新版本智能路由似乎上国内网站没有问题了，但是对outlook还是有影响，我的outlook里面所有邮件的图片都显示不了，且无法收发邮件，只有关闭智能路由（切换到pac的话必须pac策略不是"全部-smartrouter),才可以。但是Pac策略的黑名单本身并不包括维基等网站，所以pac情况下我开不了维基看。
> 收到反馈谢谢。 outlook问题，你可以观察当outlook工作时，smart_router的日志里的内容，观察图片的地址被怎么处理了。 试试把这些域名放入smart_router的直连列表中

谢谢大佬解答，我有过这种尝试，但似乎我没法准确找到域名，所以放弃了，现在找到了另一种代替方法，就是通过规则把常用语言的维基加入gae代理，这样切回pac可以上维基，同时满足邮件正常的需求。但是貌似XX-net的pac不认“*.wikipedia.org"格式，所以我无法通过一个域名一劳永逸的保证所有维基下的语言站都能上，只能把常用语言的比如en.wikipedia都加一遍，这样就可以用了（反正还好像小语种比如越南语这种基本不用）。
