### ISSUE TITLE
倡议：请有能力的朋友购买X-TUNNEL流量，以答谢开发者！

### ISSUE THREAD

**Issue by Litangren** [XX-net/XX-Net#12996]
请有能力的朋友购买X-TUNNEL流量，以答谢开发者！

**Comment by xxnet** [comment]
感谢大家支持，我们会坚持下去的。

**Comment by immeman** [comment]
gop挂了后，没想到XXnet能坚持这么久，非常感谢！

**Comment by hrxgg520** [comment]
这个就厉害了。

**Comment by ino1988** [comment]
能不能开一些低流量的套餐，我的需求只是查资料，之前买了三个月的x-tunnel ，最终到过期时也只用了不到10G的流量！！

**Comment by ino1988** [comment]
> 感谢大家支持，我们会坚持下去的。

作者，你好，首先非常感谢提供了这个工具，另外能不能开一些低流量的套餐，我的需求只是查资料，之前买了三个月的x-tunnel ，最终到过期时也只用了不到10G的流量！！

**Comment by xxnet** [comment]
我想这个价格已经很低了，如果只是偶尔查文本资料，免费帐号是有每天100M流量使用的，只要少看点图片视频没有问题。
后面还会调高价格，所以要买的赶快买了。

**Comment by lmxin123** [comment]
多少钱啊，有什么样的套餐可选择，有没有购买链接或者界面

**Comment by xxnet** [comment]
注册后登录X-Tunnel，配置页面可以看到套餐列表

**Comment by ino1988** [comment]
> 我想这个价格已经很低了，如果只是偶尔查文本资料，免费帐号是有每天100M流量使用的，只要少看点图片视频没有问题。 后面还会调高价格，所以要买的赶快买了。

你不说都没发现每天有100M免费流量，但是一直开着x-tunnel，100M一天肯定不够用，来回切换GAE也麻烦，何不出点低流量的套餐，蚊子腿再小也是钱呀！！

**Comment by Zoeyan2018** [comment]
除了paypal 就没有其他付款方式了么

**Comment by xxnet** [comment]
安全原因，暂时只支持paypal。
注册paypal并不难，全球第一的网络支付平台。

**Comment by Jogiter** [comment]
> 安全原因，暂时只支持paypal。 注册paypal并不难，全球第一的网络支付平台。

V3.16.1。无法支付。提示 Uncaught ReferenceError: currentVer is not defined。可以赠与一点流量么，先救救急，谢谢。jogiter.g@gmail.com

**Comment by xxnet** [comment]
可能和i版本原因，我先给你转点流量先用着

**Comment by Jogiter** [comment]
已收到流量，非常感谢

Michael.X <notifications@github.com> 于2020年5月21日周四 下午2:14写道：

**Comment by y449329998** [comment]
能不能支持支付宝支付,不想用paypal支付,太麻烦了

**Comment by xxnet** [comment]
以后会努力的，但是暂时没有接通呢

**Comment by panjinhua** [comment]
> 安全原因，暂时只支持paypal。 注册paypal并不难，全球第一的网络支付平台



> 我想这个价格已经很低了，如果只是偶尔查文本资料，免费帐号是有每天100M流量使用的，只要少看点图片视频没有问题。 后面还会调高价格，所以要买的赶快买了。

oo

**Comment by invoker604** [comment]
请问购买的流量为什么消失了？现在只显示100M的免费流量。invoker604@gmai.com
@xxnet

**Comment by xxnet** [comment]
之前故障丢失了个别数据，现在已经帮你恢复流量了。

**Comment by invoker604** [comment]
> 之前故障丢失了个别数据，现在已经帮你恢复流量了。

收到了，感谢

**Comment by wang-peijun** [comment]
买了X-TUNNEL但是网络也太慢了吧

**Comment by xxnet** [comment]
可能是流量丢失了，请把 x-tunnel的账户发给 xxnet.dev@gmail.com 检查

**Comment by RollingIsland** [comment]
有什么办法可以使用人民币银联卡付款吗？我记得之前操作过一次不知道为啥这次不行了

**Comment by xxnet** [comment]
检查网上支付有没有关了

**Comment by 651332399** [comment]
去年七月份买了一年的。。。结果用了没一个月就各种不能用了，后来干脆放弃了，上个月发现又可以了，结果哈哈剩了1000多g直接过期了。难受

**Comment by s1297422520** [comment]
急！急！急！X-TUNNEL不能访问谷歌学术，怎么办？

**Comment by wang-peijun** [comment]
X-TUNNEL, 好不容易连上，YouTube 144p都卡的没法看，是我对这个VPN要求太高了吗？

**Comment by xxnet** [comment]
谷歌学术 已经可以访问了，因为google 封了部分ip，需要特定的ip才能访问，服务端做了优化。

X-Tunnel 部分地区的网络干扰严重，抱歉，后面会持续改进。

**Comment by liujiehaobang** [comment]
> 感谢大家支持，我们会坚持下去的。

邮箱忘记密码了，刚买了流量

**Comment by liujiehaobang** [comment]
X-Tunnel登录忘记密码了

**Comment by fanmingming** [comment]
买了3个月支持，目前无法正常使用。

**Comment by mochen91** [comment]
> 感谢大家支持，我们会坚持下去的。

X-Tunnel无法登陆了。

**Comment by shuangmuchenglin** [comment]
X-Tunnel登不进去了，咋回事啊

**Comment by xxnet** [comment]
服务器被攻击了，目前已经恢复服务

**Comment by xxnet** [comment]
为了补偿大家前天服务器受攻击的影响，所有流量延期5天。

**Comment by wang-peijun** [comment]
感觉被骗了

**Comment by mochen91** [comment]
不能这么说，现在VPN都管的特别严，很多倍查封了。XX-NET也会受到波及无法幸免，事实上，每个VPN都会遭到波及。
今天收到了火狐的VPN，但也仅限于英、美、加、新西兰、新加坡和马来西亚。https://vpn.mozilla.org/

wang-peijun <notifications@github.com> 于2020年7月23日周四 下午10:47写道：

**Comment by xxnet** [comment]
VPN 在中国是需要不断对抗GFW的升级，那是要跟国家级别的资金和技术团队进行对抗。
XX-Net能够坚持这么多年实属不易，也非常感谢大家的支持。
某些时候登录不上请大家多包容，把信息反馈出来，我们会努力改进的。
个别网络环境下实在不能使用可以在paypal上发起退款，我们都会尽快处理。

**Comment by snipertulip** [comment]
> > 我想这个价格已经很低了，如果只是偶尔查文本资料，免费帐号是有每天100M流量使用的，只要少看点图片视频没有问题。 后面还会调高价格，所以要买的赶快买了。
> 
> 你不说都没发现每天有100M免费流量，但是一直开着x-tunnel，100M一天肯定不够用，来回切换GAE也麻烦，何不出点低流量的套餐，蚊子腿再小也是钱呀！！

我是win10企业版用户，网络设置为 “按流量计费的连接”，后台程序就不会偷流量了

**Comment by wang-peijun** [comment]
我下载一个50M的文件，每次都是开始500kb，下载到一半变成0b，好搞人心态啊，啥原因呢

**Comment by ZT-GHub** [comment]
google scholar访问速度还可以，但是文献引用的bibtex 打不开。大佬能修复一下吗？
403 That’s an error.
Your client does not have permission to get URL /scholar.bib?q=...

**Comment by xxnet** [comment]
另一个帖子回了，建议用x-tunnel解决这类兼容性问题

**Comment by xxnet** [comment]
在客户端里，注册登录后可以看到购买套餐

**Comment by forsimple** [comment]
加一个虚拟货币的支付方式吧，比如说usdt

**Comment by fall0down** [comment]
买了流量，但是速度太慢，一个多月了才用了2G多点。

**Comment by s1297422520** [comment]
我支付了4.5美元购买了三个月的x-tunnel服务，但是流量没有到账？
I paid $4.50 for three months of x-tunnel service, but the traffic did not arrive, what should I do?

**Comment by s1297422520** [comment]
我支付了4.5美元购买了三个月的x-tunnel服务，但是流量没有到账？
I paid $4.50 for three months of x-tunnel service, but the traffic did not arrive, what should I do?

**Comment by love2157dream** [comment]
购买后x-tunnel服务，但是登陆不上了，没有购买前还能登录

**Comment by fx606** [comment]
又不能用了

**Comment by EricleFu** [comment]
时断时续的不敢买啊，买了之后大部分时间不能用，能用了又马上过期了，心塞

**Comment by longerli** [comment]
买了X-Tunnel的流量，当时未到帐，发了邮件，但是现在流量还是未到帐，这个处理大概要多长时间啊？

**Comment by ceexes** [comment]
是不是要废了。。。

**Comment by ZT-GHub** [comment]
老老实实用机场吧

**Comment by ceexes** [comment]
机场是啥？

**Comment by maruowen1** [comment]
> 又不能用了

登录不上显示错误603？

**Comment by snsnselaoyeye** [comment]
买了流量什么时候能到账啊

**Comment by fx606** [comment]
有流量也不能用。估计是废了
    On Sunday, January 17, 2021, 12:38:40 PM GMT+8, snsnselaoyeye <notifications@github.com> wrote:  
 
 


买了流量什么时候能到账啊

**Comment by snsnselaoyeye** [comment]
> 有流量也不能用。估计是废了 On Sunday, January 17, 2021, 12:38:40 PM GMT+8, snsnselaoyeye <notifications@github.com> wrote: 买了流量什么时候能到账啊 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

用到是能用，我这里没什么问题，三天了还没到，我现在靠每天100m撑着

**Comment by liujiehaobang** [comment]
> > 有流量也不能用。估计是废了 On Sunday, January 17, 2021, 12:38:40 PM GMT+8, snsnselaoyeye [notifications@github.com](mailto:notifications@github.com) wrote: 买了流量什么时候能到账啊 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> 用到是能用，我这里没什么问题，三天了还没到，我现在靠每天100m撑着

我也是三天了没到，每天100M,而且有效期都是当天

**Comment by fx606** [comment]
买了一年，账户流量剩余1000G+
最近一个多星期，基本无法登录或无流量，日志如下：

2021-01-18 11:44:22.090 - [DEBUG] start report_stat

2021-01-18 11:44:29.701 - [WARNING] front retry v15.xx-net.net/data

2021-01-18 11:44:30.711 - [WARNING] login session fail, status:602

2021-01-18 11:44:30.712 - [WARNING] x-tunnel login_session fail, session not start

2021-01-18 11:44:37.138 - [WARNING] front retry center.xx-net.net/report_stat

2021-01-18 11:44:50.786 - [WARNING] front retry v15.xx-net.net/data

2021-01-18 11:44:51.795 - [WARNING] login session fail, status:602

2021-01-18 11:44:54.267 - [WARNING] front retry center.xx-net.net/report_stat

2021-01-18 11:44:56.279 - [WARNING] api:/report_stat fail:status:602 t:34

2021-01-18 11:44:56.279 - [WARNING] report fail.

2021-01-18 11:45:11.836 - [WARNING] front retry v15.xx-net.net/data

2021-01-18 11:45:12.844 - [WARNING] login session fail, status:602

2021-01-18 11:45:12.844 - [WARNING] x-tunnel login_session fail, session not start

2021-01-18 11:45:32.922 - [WARNING] front retry v15.xx-net.net/data

2021-01-18 11:45:33.930 - [WARNING] login session fail, status:602

2021-01-18 11:45:54.007 - [WARNING] front retry v15.xx-net.net/data

2021-01-18 11:45:55.014 - [WARNING] login session fail, status:602

2021-01-18 11:45:55.014 - [WARNING] x-tunnel login_session fail, session not start

2021-01-18 11:45:56.280 - [DEBUG] start report_stat

2021-01-18 11:46:11.327 - [WARNING] front retry center.xx-net.net/report_stat

2021-01-18 11:46:15.046 - [WARNING] front retry v15.xx-net.net/data

2021-01-18 11:46:16.057 - [WARNING] login session fail, status:602

2021-01-18 11:46:28.384 - [WARNING] front retry center.xx-net.net/report_stat

2021-01-18 11:46:30.391 - [WARNING] api:/report_stat fail:status:602 t:34

2021-01-18 11:46:30.391 - [WARNING] report fail.

2021-01-18 11:46:36.153 - [WARNING] front retry v15.xx-net.net/data

2021-01-18 11:46:37.157 - [WARNING] login session fail, status:602

2021-01-18 11:46:37.157 - [WARNING] x-tunnel login_session fail, session not start

2021-01-18 11:46:57.176 - [WARNING] front retry v15.xx-net.net/data

2021-01-18 11:46:58.192 - [WARNING] login session fail, status:602

**Comment by xxnet** [comment]
请更新到 4.5.3版本，解决x-tunnel登录问题

**Comment by fx606** [comment]
升级后可以登录X-tunnnel，但是显示登陆成功以后要联网时仍然经常失败，或者无流量。

cloudflare 前端日志显示以下信息：


2021-01-22 13:16:36.034 - [ERROR] updated cloudflare front domains from github fail:ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)

2021-01-22 13:16:36.138 - [ERROR] Except stack:Traceback (most recent call last): File "D:\XX-net\code\4.5.3\x_tunnel\local\cloudflare_front\host_manager.py", line 69, in update_front_domains response = client.request("GET", url) File "D:\XX-net\code\4.5.3\lib\noarch\simple_http_client.py", line 469, in request sock = self.connect(upl.hostname, port, upl.scheme == b"https") File "D:\XX-net\code\4.5.3\lib\noarch\simple_http_client.py", line 437, in connect sock = ssl.wrap_socket(sock) File "D:\XX-net\python3.8.2\lib\ssl.py", line 1405, in wrap_socket return context.wrap_socket( File "D:\XX-net\python3.8.2\lib\ssl.py", line 500, in wrap_socket return self.sslsocket_class._create( File "D:\XX-net\python3.8.2\lib\ssl.py", line 1040, in _create self.do_handshake() File "D:\XX-net\python3.8.2\lib\ssl.py", line 1309, in do_handshake self._sslobj.do_handshake() ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

**Comment by hawyrihby** [comment]
兄弟，你这个时间能不能长一点，假如买12个月1200g，用不完，平时很多时候连不上，或者速度很慢，用不完。快的时候又很快，慢的时候则很慢。

假如用不完的流量可以换时间就好了，之间找个平衡点。大家都不吃亏。

**Comment by beckzf** [comment]
> 兄弟，你这个时间能不能长一点，假如买12个月1200g，用不完，平时很多时候连不上，或者速度很慢，用不完。快的时候又很快，慢的时候则很慢。
> 
> 假如用不完的流量可以换时间就好了，之间找个平衡点。大家都不吃亏。

是啊，我都点了n次购买，最后放弃了，好多时候连不上，手机端设置又麻烦，算下来一年也就用过1、2G。建议把购买套餐再细化，单价高点无所谓，设置个即时日套餐，1天50美分，给个1、2G的流量能够让我们的资讯和世外接轨，顺带更新下google play就行了。

**Comment by rilegoule** [comment]
能不能整个长时间小流量的便宜点的套餐,或者干脆整个不限时再贵点的套餐也行啊.我买的12个月1200g流量根本用不完,到现在要到期了只用了5g,到时间了剩的流量就都没了吧,好亏啊

**Comment by yuebe** [comment]
= =X-Tunnel 速度太慢了,已经连不上去了,看了那个帖子一样,买了2年的,还不知道真正能用多久....

**Comment by Phil-Chang** [comment]
已经买了有几年了，但最近速度太慢了，还请抓紧解决一下，只要速度能上来，我相信买得人会越来越多

**Comment by zhengyqy** [comment]
已经半年多没有更新了，还会有新的版本出来吗？

**Comment by bomeidesign** [comment]
今天早上开始，XX-NET无法登录。登录失败：status:602 #13570

**Comment by bomeidesign** [comment]
年会员呀，大哥

**Comment by ino1988** [comment]
求作者大大来解决一下

**Comment by csalhk** [comment]
希望作者能解决一下，毕竟习惯了

**Comment by ldyhero07** [comment]
X-Tunnel登不上去了，希望作者尽快解决

**Comment by juniorsang** [comment]
2021-09-06 00:03:39.144 - [INFO] xxnet_version:4.5.3

2021-09-06 00:03:39.144 - [DEBUG] SendBuffer reset

2021-09-06 00:03:39.145 - [INFO] server 127.0.0.1:1080 started.

2021-09-06 00:03:39.145 - [INFO] Socks5 server listen:127.0.0.1:1080.

2021-09-06 00:03:41.566 - [DEBUG] x-tunnel web_control 127.0.0.1:9915 POST /login

2021-09-06 00:03:47.388 - [WARNING] front retry center.xx-net.org/login

2021-09-06 00:03:52.667 - [WARNING] front retry center.xx-net.org/login

2021-09-06 00:03:56.786 - [WARNING] front retry center.xx-net.org/login

2021-09-06 00:04:02.558 - [WARNING] front retry center.xx-net.org/login

2021-09-06 00:04:06.667 - [WARNING] front retry center.xx-net.org/login

2021-09-06 00:04:16.220 - [WARNING] front retry center.xx-net.org/login

2021-09-06 00:04:18.226 - [WARNING] api:/login fail:status:602 t:36
