### ISSUE TITLE
近几版都无法使用

### ISSUE THREAD

**Issue by dapaowangdige** [XX-net/XX-Net#12997]
近几版的vbs文件打开无反应，后台可以见到python进程，且无法结束。bat文件可以打开，但是一直扫描IP，扫描结束也无法打开xxnet，同时python进程无法结束。系统win10企业版1909，上海电信500M光纤IP v6已开启。不知是哪里出了问题，希望大佬解答一下。

**Comment by dapaowangdige** [comment]
附上部分状态
2020-03-05 23:17:03.383 [launcher][INFO] use build-in openssl lib
2020-03-05 23:17:03.395 [launcher][INFO] start XX-Net 3.15.10
2020-03-05 23:17:03.395 [launcher][DEBUG] start confirm_xxnet_exit
2020-03-05 23:17:05.399 [launcher][DEBUG] good, xxnet:8085 clear!
2020-03-05 23:17:05.400 [launcher][DEBUG] finished confirm_xxnet_exit
2020-03-05 23:17:07.484 [gae_proxy][INFO] ------------------------------------------------------
2020-03-05 23:17:07.484 [gae_proxy][INFO] Python Version     : 2.7.17
2020-03-05 23:17:07.485 [gae_proxy][INFO] OS                 : Version:10-0; Build:18363; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
2020-03-05 23:17:07.485 [gae_proxy][INFO] Listen Address     : 127.0.0.1:8087
2020-03-05 23:17:07.485 [gae_proxy][INFO] Using public APPID
2020-03-05 23:17:07.486 [gae_proxy][INFO] ------------------------------------------------------
2020-03-05 23:17:07.487 [gae_proxy][DEBUG] Importing CA
2020-03-05 23:17:07.487 [gae_proxy][DEBUG] Begin to import Windows CA
2020-03-05 23:17:07.497 [gae_proxy][DEBUG] XX-Net CA already exists
2020-03-05 23:17:07.500 [gae_proxy][INFO] SSL use version:TLSv1_2
2020-03-05 23:17:07.502 [gae_proxy][INFO] OpenSSL support alpn
2020-03-05 23:17:07.503 [gae_proxy][INFO] load ip range file:D:\代理程序\GAE\XX-Net\code\default\gae_proxy\local\ip_range.txt
2020-03-05 23:17:07.505 [gae_proxy][INFO] load ip_list num:100, target num:100
2020-03-05 23:17:07.505 [gae_proxy][INFO] Adjust scan thread num from 10 to 7
2020-03-05 23:17:07.510 [gae_proxy][INFO] SSL use version:TLSv1_2
2020-03-05 23:17:07.513 [gae_proxy][INFO] server 127.0.0.1:8087 started.
2020-03-05 23:17:07.584 [launcher][INFO] module gae_proxy started
2020-03-05 23:17:07.585 [launcher][INFO] start gae_proxy time cost:2181 ms
WARNING:root:Load Crypto.Cipher.ARC4 Failed, Use Pure Python Instead.
2020-03-05 23:17:07.607 [cloudflare_front][INFO] SSL use version:TLSv1_2
2020-03-05 23:17:07.609 [cloudflare_front][INFO] OpenSSL support alpn
2020-03-05 23:17:07.609 [cloudflare_front][INFO] load ip range file:D:\代理程序\GAE\XX-Net\code\default\x_tunnel\local\cloudflare_front\ip_range.txt
2020-03-05 23:17:07.613 [cloudflare_front][INFO] load ip_list num:99, target num:99
2020-03-05 23:17:07.648 [cloudfront_front][INFO] SSL use version:TLSv1_2
2020-03-05 23:17:07.952 [cloudfront_front][INFO] OpenSSL support alpn
2020-03-05 23:17:07.953 [cloudfront_front][INFO] load ip range file:D:\代理程序\GAE\XX-Net\code\default\x_tunnel\local\cloudfront_front\ip_range.txt
2020-03-05 23:17:07.960 [cloudfront_front][INFO] load ip_list num:100, target num:100
2020-03-05 23:17:07.977 [tls_relay][INFO] SSL use version:TLSv1_2
2020-03-05 23:17:07.979 [tls_relay][INFO] OpenSSL support alpn
2020-03-05 23:17:08.012 [heroku_front][INFO] SSL use version:TLSv1_2
2020-03-05 23:17:08.019 [heroku_front][INFO] OpenSSL support alpn
2020-03-05 23:17:08.021 [heroku_front][INFO] load ip_list num:75, target num:75
2020-03-05 23:17:08.031 [x_tunnel][INFO] use config_path:D:\代理程序\GAE\XX-Net\data\x_tunnel\client.json
2020-03-05 23:17:08.032 [x_tunnel][INFO] X-Tunnel window:16777216
2020-03-05 23:17:08.037 [x_tunnel][INFO] xxnet_version:3.15.10

2020-03-05 23:17:08.040 [x_tunnel][ERROR] bind to 127.0.0.1:1080 fail:error(10013, '')
Exception in thread Thread-47:
Traceback (most recent call last):
  File "D:\代理程序\GAE\XX-Net\python27\2.0\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "D:\代理程序\GAE\XX-Net\python27\2.0\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "D:\代理程序\GAE\XX-Net\code\default\x_tunnel\start.py", line 19, in main
    client.main(args)
  File "D:\代理程序\GAE\XX-Net\code\default\x_tunnel\local\client.py", line 177, in main
    g.socks5_server = simple_http_server.HTTPServer(addresses, Socks5Server, logger=xlog)
  File "D:\代理程序\GAE\XX-Net\code\default\python27\1.0\lib\noarch\simple_http_server.py", line 412, in __init__
    self.init_socket()
  File "D:\代理程序\GAE\XX-Net\code\default\python27\1.0\lib\noarch\simple_http_server.py", line 430, in init_socket
    self.add_listen((ip, port))
  File "D:\代理程序\GAE\XX-Net\code\default\python27\1.0\lib\noarch\simple_http_server.py", line 444, in add_listen
    raise Exception(err_string)
Exception: bind to 127.0.0.1:1080 fail:error(10013, '')

2020-03-05 23:17:23.383 [gae_proxy][DEBUG] network IPv4 is ok, cost:15961 ms
2020-03-05 23:17:27.622 [cloudflare_front][INFO] remove ip:190.93.247.123 left amount:98 target_num:98
2020-03-05 23:17:27.627 [cloudflare_front][DEBUG] recheck_ip:190.93.247.123 real fail, removed.
2020-03-05 23:17:33.068 [gae_proxy][INFO] scan_ip add ip:172.217.212.98 time:5414 h2:1
2020-03-05 23:17:33.074 [gae_proxy][INFO] Adjust scan thread num from 7 to 6
2020-03-05 23:17:33.075 [gae_proxy][INFO] remove_slowest_ip:172.217.212.98 handshake_time:5414, fails:0
2020-03-05 23:17:35.633 [cloudflare_front][INFO] remove ip:104.19.128.160 left amount:97 target_num:97
2020-03-05 23:17:35.640 [cloudflare_front][DEBUG] recheck_ip:104.19.128.160 real fail, removed.

**Comment by xxnet** [comment]
端口1080 被占用，先退出其他代理工具试试。
修改1080端口可以参考这里：
https://github.com/XX-net/XX-Net/wiki/X-Tunnel-Config-file

**Comment by dapaowangdige** [comment]
> 端口1080 被占用，先退出其他代理工具试试。 修改1080端口可以参考这里： https://github.com/XX-net/XX-Net/wiki/X-Tunnel-Config-file

查看了，并没有程序占用1080端口，其他代理工具也都退出了，真的搞不清是哪里出了问题

**Comment by xxnet** [comment]
参考这个：
https://www.cnblogs.com/allenblogs/archive/2010/06/25/1765055.html

**Comment by dapaowangdige** [comment]
> 参考这个： https://www.cnblogs.com/allenblogs/archive/2010/06/25/1765055.html

就是这么查看的，没有发现有进程占用1080端口，所有代理软件都关闭了，奇了怪了

**Comment by xxnet** [comment]
那就先试试换端口，不行考虑先暂停各种安全软件

**Comment by dapaowangdige** [comment]
> 那就先试试换端口，不行考虑先暂停各种安全软件

试了多种办法，依然无济于事，放弃了
