### ISSUE TITLE
设置允许远程连接Web控制端(On)后出现错误

### ISSUE THREAD

**Issue by lgxnas** [XX-net/XX-Net#13095]
版本号：4.0.2
设置允许远程连接Web控制端(On)后出现错误
2020-04-02 15:26:26.371 [launcher][INFO] server 127.0.0.1:8085 started.

2020-04-02 15:26:26.372 [launcher][ERROR] bind to b'0.0.0.0':8085 fail:OSError(98, '地址已在使用')
2020-04-02 15:26:26.372 [simple_http_server][ERROR] handler:Exception("bind to b'0.0.0.0':8085 fail:OSError(98, '地址已在使用')") cmd:GET path:/config?cmd=set_config&allow_remote_switch=1 from:127.0.0.1:52966
2020-04-02 15:26:26.377 [simple_http_server][ERROR] Except stack:Traceback (most recent call last):
  File "/home/lgx/app/XX-Net-4.0.2/code/default/lib/noarch/simple_http_server.py", line 463, in add_listen
    sock.bind(addr)
OSError: [Errno 98] 地址已在使用

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lgx/app/XX-Net-4.0.2/code/default/lib/noarch/simple_http_server.py", line 172, in handle_one_request
    self.do_GET()
  File "/home/lgx/app/XX-Net-4.0.2/code/default/launcher/web_control.py", line 180, in do_GET
    self.req_config_handler()
  File "/home/lgx/app/XX-Net-4.0.2/code/default/launcher/web_control.py", line 358, in req_config_handler
    start()
  File "/home/lgx/app/XX-Net-4.0.2/code/default/launcher/web_control.py", line 728, in start
    server = simple_http_server.HTTPServer(addresses, Http_Handler, logger=xlog)
  File "/home/lgx/app/XX-Net-4.0.2/code/default/lib/noarch/simple_http_server.py", line 430, in __init__
    self.init_socket()
  File "/home/lgx/app/XX-Net-4.0.2/code/default/lib/noarch/simple_http_server.py", line 448, in init_socket
    self.add_listen((ip, port))
  File "/home/lgx/app/XX-Net-4.0.2/code/default/lib/noarch/simple_http_server.py", line 467, in add_listen
    raise Exception(err_string)
Exception: bind to b'0.0.0.0':8085 fail:OSError(98, '地址已在使用')

**Comment by xxnet** [comment]
收到，确实是bug，下个版本修复

**Comment by lgxnas** [comment]
请问如果我是想要在一台不含窗口的linux上用ssh设置远程访问，是不是只用在
data/gae_proxy中增加config.json文件,内容为：
{
  "listen_ip": "0.0.0.0"
}
data/smart_router中增加config.json文件，内容为：
{
  "dns_bind_ip": "0.0.0.0",
  "proxy_bind_ip": "0.0.0.0"
}
就可以远程访问ip:8085端口了？

**Comment by xxnet** [comment]
可以用  start -allow_remote 启动，就不用手动改配置了。

**Comment by xxnet** [comment]
#13097 
新版发布了，已经修复这个问题
