### ISSUE TITLE
4.0.4 在ubuntu19.10不能启动。

### ISSUE THREAD

**Issue by hawyrihby** [XX-net/XX-Net#13121]
ubuntu下xx-net 4.0.4 不能启动。

sudo ./xx_net.sh
Starting xx_net proxy server: xx_net.

**Comment by xxnet** [comment]
./start

**Comment by hawyrihby** [comment]
```./start
XX-Net version:4.0.4
2020-04-09 18:52:02.074 [launcher][INFO] Using PyGObject as the GUI Backend.
2020-04-09 18:52:02.278 [launcher][INFO] Gtk.StatusIcon used.
2020-04-09 18:52:02.389 [launcher][INFO] use build-in openssl lib
2020-04-09 18:52:02.390 [launcher][INFO] start XX-Net 4.0.4
2020-04-09 18:52:02.390 [launcher][DEBUG] start confirm_xxnet_exit
2020-04-09 18:52:02.392 [launcher][DEBUG] good, xxnet:8085 clear!
2020-04-09 18:52:02.393 [launcher][DEBUG] finished confirm_xxnet_exit
2020-04-09 18:52:02.538 [gae_proxy][INFO] ------------------------------------------------------
2020-04-09 18:52:02.538 [gae_proxy][INFO] Python Version     : 3.7.5
2020-04-09 18:52:02.538 [gae_proxy][INFO] OS                 : Ubuntu

2020-04-09 18:52:02.538 [gae_proxy][INFO] Listen Address     : 127.0.0.1:8087
2020-04-09 18:52:02.538 [gae_proxy][INFO] GAE APPID          : xxnet-mgx-1|xxnet-mgx-02|xxnet-mgx-3|xxnet-mgx-04|xxnet-mgx-05|xxnet-mgx-06|xxnet-mgx-7|xxnet-mgx-08|xxnet-mgx-09|xxnet-mgx-010|xxnet-mgx-011|xxnet-mgx-12
2020-04-09 18:52:02.539 [gae_proxy][INFO] ------------------------------------------------------
2020-04-09 18:52:02.541 [gae_proxy][DEBUG] Importing CA
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/stone/APP/XX-Net/code/4.0.4/gae_proxy/local/__init__.py", line 12, in start
    proxy.main(args)
  File "/home/stone/APP/XX-Net/code/4.0.4/gae_proxy/local/proxy.py", line 121, in main
    CertUtil.init_ca()
  File "/home/stone/APP/XX-Net/code/4.0.4/gae_proxy/local/cert_util.py", line 564, in init_ca
    CertUtil.import_ca(CertUtil.ca_keyfile)
  File "/home/stone/APP/XX-Net/code/4.0.4/gae_proxy/local/cert_util.py", line 472, in import_ca
    CertUtil.import_linux_ca(commonname, certfile)
  File "/home/stone/APP/XX-Net/code/4.0.4/gae_proxy/local/cert_util.py", line 379, in import_linux_ca
    sha1 = get_linux_ca_sha1(nss_path)
  File "/home/stone/APP/XX-Net/code/4.0.4/gae_proxy/local/cert_util.py", line 364, in get_linux_ca_sha1
    sha1 = sha1.replace(b' ', b'').replace(b':', b'').replace(b'\n', b'')
TypeError: replace() argument 1 must be str, not bytes

2020-04-09 18:52:02.691 [gae_proxy][DEBUG] network IPv4 is ok, cost:291 ms
2020-04-09 18:52:44.989 [gae_proxy][DEBUG] network IPv6 is ok, cost:42589 ms


```
日志是这样的：
```
2020-04-09 18:52:02.074 - [INFO] Using PyGObject as the GUI Backend.
2020-04-09 18:52:02.278 - [INFO] Gtk.StatusIcon used.
2020-04-09 18:52:02.389 - [INFO] use build-in openssl lib
2020-04-09 18:52:02.390 - [INFO] start XX-Net 4.0.4
2020-04-09 18:52:02.390 - [DEBUG] start confirm_xxnet_exit
2020-04-09 18:52:02.392 - [DEBUG] good, xxnet:8085 clear!
2020-04-09 18:52:02.393 - [DEBUG] finished confirm_xxnet_exit
```
第一次启动了，但是重启了一下电脑，就启动不了。

**Comment by hawyrihby** [comment]
```./start
XX-Net version:4.0.4
2020-04-09 18:52:02.074 [launcher][INFO] Using PyGObject as the GUI Backend.
2020-04-09 18:52:02.278 [launcher][INFO] Gtk.StatusIcon used.
2020-04-09 18:52:02.389 [launcher][INFO] use build-in openssl lib
2020-04-09 18:52:02.390 [launcher][INFO] start XX-Net 4.0.4
2020-04-09 18:52:02.390 [launcher][DEBUG] start confirm_xxnet_exit
2020-04-09 18:52:02.392 [launcher][DEBUG] good, xxnet:8085 clear!
2020-04-09 18:52:02.393 [launcher][DEBUG] finished confirm_xxnet_exit
2020-04-09 18:52:02.538 [gae_proxy][INFO] ------------------------------------------------------
2020-04-09 18:52:02.538 [gae_proxy][INFO] Python Version     : 3.7.5
2020-04-09 18:52:02.538 [gae_proxy][INFO] OS                 : Ubuntu

2020-04-09 18:52:02.538 [gae_proxy][INFO] Listen Address     : 127.0.0.1:8087
2020-04-09 18:52:02.538 [gae_proxy][INFO] GAE APPID          : xxnet-mgx-1|xxnet-mgx-02|xxnet-mgx-3|xxnet-mgx-04|xxnet-mgx-05|xxnet-mgx-06|xxnet-mgx-7|xxnet-mgx-08|xxnet-mgx-09|xxnet-mgx-010|xxnet-mgx-011|xxnet-mgx-12
2020-04-09 18:52:02.539 [gae_proxy][INFO] ------------------------------------------------------
2020-04-09 18:52:02.541 [gae_proxy][DEBUG] Importing CA
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/stone/APP/XX-Net/code/4.0.4/gae_proxy/local/__init__.py", line 12, in start
    proxy.main(args)
  File "/home/stone/APP/XX-Net/code/4.0.4/gae_proxy/local/proxy.py", line 121, in main
    CertUtil.init_ca()
  File "/home/stone/APP/XX-Net/code/4.0.4/gae_proxy/local/cert_util.py", line 564, in init_ca
    CertUtil.import_ca(CertUtil.ca_keyfile)
  File "/home/stone/APP/XX-Net/code/4.0.4/gae_proxy/local/cert_util.py", line 472, in import_ca
    CertUtil.import_linux_ca(commonname, certfile)
  File "/home/stone/APP/XX-Net/code/4.0.4/gae_proxy/local/cert_util.py", line 379, in import_linux_ca
    sha1 = get_linux_ca_sha1(nss_path)
  File "/home/stone/APP/XX-Net/code/4.0.4/gae_proxy/local/cert_util.py", line 364, in get_linux_ca_sha1
    sha1 = sha1.replace(b' ', b'').replace(b':', b'').replace(b'\n', b'')
TypeError: replace() argument 1 must be str, not bytes

2020-04-09 18:52:02.691 [gae_proxy][DEBUG] network IPv4 is ok, cost:291 ms
2020-04-09 18:52:44.989 [gae_proxy][DEBUG] network IPv6 is ok, cost:42589 ms


```
日志是这样的：
```
2020-04-09 18:52:02.074 - [INFO] Using PyGObject as the GUI Backend.
2020-04-09 18:52:02.278 - [INFO] Gtk.StatusIcon used.
2020-04-09 18:52:02.389 - [INFO] use build-in openssl lib
2020-04-09 18:52:02.390 - [INFO] start XX-Net 4.0.4
2020-04-09 18:52:02.390 - [DEBUG] start confirm_xxnet_exit
2020-04-09 18:52:02.392 - [DEBUG] good, xxnet:8085 clear!
2020-04-09 18:52:02.393 - [DEBUG] finished confirm_xxnet_exit
```
第一次启动了，但是重启了一下电脑，就启动不了。

**Comment by xxnet** [comment]
确认bug,  没有 certutil 会去检测前面的 ""，不是bytes

**Comment by hawyrihby** [comment]
好了，谢谢。
