### ISSUE TITLE
Centos 6.6 下无法运行

### ISSUE THREAD

**Issue by cqspirit** [XX-net/XX-Net#1313]
[root@se XX-Net-2.3.0]# ./start.sh 
Nov  2 20:30:20 - [INFO] start XX-Net 2.5.1
Nov  2 20:30:20 - [DEBUG] start confirm_xxnet_exit
Nov  2 20:30:20 - [DEBUG] good, xxnet:8087 cleared!
Nov  2 20:30:20 - [DEBUG] good, xxnet:8085 clear!
Nov  2 20:30:20 - [DEBUG] finished confirm_xxnet_exit
Nov  2 20:30:20 - [ERROR] start module gae_proxy fail:libssl.so.1.0.0: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/public/app/goagent/XX-Net-2.3.0/launcher/module_init.py", line 37, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "/public/app/goagent/XX-Net-2.3.0/gae_proxy/start.py", line 14, in <module>
    import local.proxy as client
  File "/public/app/goagent/XX-Net-2.3.0/gae_proxy/local/proxy.py", line 74, in <module>
    from cert_util import CertUtil
  File "/public/app/goagent/XX-Net-2.3.0/gae_proxy/local/cert_util.py", line 37, in <module>
    import OpenSSL
  File "/public/app/goagent/XX-Net-2.3.0/python27/1.0/lib/linux/OpenSSL/__init__.py", line 36, in <module>
    from OpenSSL import crypto
ImportError: libssl.so.1.0.0: cannot open shared object file: No such file or directory

Nov  2 20:30:20 - [INFO] start gae_proxy time cost 9
Nov  2 20:30:20 - [INFO] begin to start web control
Nov  2 20:30:20 - [INFO] launcher web control started.
Nov  2 20:30:21 - [INFO] get uuid:304b2650-fd91-49a3-aac3-e5e51340290f
Nov  2 20:30:21 - [WARNING] check_update fail:URLError(error(111, 'Connection refused'),)
Nov  2 20:30:21 - [INFO] download https://raw.githubusercontent.com/XX-net/XX-Net/master/README.md to /public/app/goagent/XX-Net-2.3.0/data/downloads/README.md, retry:0

**Comment by cqspirit** [comment]
ImportError: /usr/lib64/libssl.so.10: symbol EC_KEY_get0_group, version OPENSSL_1.0.1_EC not defined in file libcrypto.so.10 with link time reference

**Comment by KaiserY** [comment]
Fedora 23 也是这个错，目测OPENSSL版本的问题？可否升级一下？

**Comment by KaiserY** [comment]
可以临时自己编译一个 1.0.0 版本的 OPENSSL，然后将 libssl.so.1.0.0 和 libcrypto.so.1.0.0 拷贝到 /usr/lib(64) 救急

```bash
./config --prefix=/usr/ --openssldir=/etc/ssl shared
make
```
