### ISSUE TITLE
托盘始终不出来，Mac os High Sierra，Chrome+Switchyomega

### ISSUE THREAD

**Issue by PeterPung** [XX-net/XX-Net#13149]
[launcher.log](https://github.com/XX-net/XX-Net/files/4567572/launcher.log)
2020-05-01 22:41:14.169 - [INFO] import build-in openssl fail:ModuleNotFoundError("No module named 'OpenSSL'")
2020-05-01 22:41:14.173 - [ERROR] import system python-OpenSSL fail:ModuleNotFoundError("No module named 'OpenSSL'")
2020-05-01 22:41:14.175 - [ERROR] Except stack:Traceback (most recent call last):
  File "code/default/launcher/start.py", line 164, in <module>
    import OpenSSL as oss_test
ModuleNotFoundError: No module named 'OpenSSL'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "code/default/launcher/start.py", line 174, in <module>
    import OpenSSL
ModuleNotFoundError: No module named 'OpenSSL'

2020-05-01 22:44:11.953 - [INFO] use build-in openssl lib
2020-05-01 22:44:11.985 - [INFO] start XX-Net 4.0.5
2020-05-01 22:44:11.986 - [DEBUG] start confirm_xxnet_exit
2020-05-01 22:44:12.013 - [DEBUG] good, xxnet:8085 clear!
2020-05-01 22:44:12.014 - [DEBUG] finished confirm_xxnet_exit
2020-05-02 08:12:46.929 - [DEBUG] start to terminate gae_proxy module
2020-05-02 08:12:46.934 - [ERROR] stop module gae_proxy fail:'NoneType' object has no attribute 'shutdown'
2020-05-02 08:12:46.966 - [ERROR] Except stack:Traceback (most recent call last):
  File "code/default/launcher/start.py", line 253, in <module>
  File "code/default/launcher/start.py", line 232, in main
  File "/Users/selina/Downloads/XX-Net-4.0.5/code/default/launcher/module_init.py", line 121, in start_all_auto
    start(module)
  File "/Users/selina/Downloads/XX-Net-4.0.5/code/default/launcher/module_init.py", line 53, in start
    time.sleep(0.1)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/selina/Downloads/XX-Net-4.0.5/code/default/launcher/module_init.py", line 80, in stop
    _local.stop()
  File "/Users/selina/Downloads/XX-Net-4.0.5/code/default/gae_proxy/local/__init__.py", line 16, in stop
    proxy.terminate()
  File "/Users/selina/Downloads/XX-Net-4.0.5/code/default/gae_proxy/local/proxy.py", line 154, in terminate
    proxy_server.shutdown()
AttributeError: 'NoneType' object has no attribute 'shutdown'

2020-05-02 08:35:05.765 - [INFO] use build-in openssl lib
2020-05-02 08:35:05.772 - [INFO] start XX-Net 4.0.5
2020-05-02 08:35:05.772 - [DEBUG] start confirm_xxnet_exit
2020-05-02 08:35:05.800 - [DEBUG] good, xxnet:8085 clear!
2020-05-02 08:35:05.800 - [DEBUG] finished confirm_xxnet_exit
2020-05-02 08:35:15.271 - [INFO] module gae_proxy started
2020-05-02 08:35:15.273 - [INFO] start gae_proxy time cost:9467 ms
2020-05-02 17:06:12.000 - [DEBUG] start to terminate gae_proxy module
2020-05-02 17:06:12.031 - [DEBUG] module gae_proxy stopping
2020-05-02 17:06:12.036 - [INFO] module gae_proxy stopped
2020-05-02 17:06:12.037 - [DEBUG] start to terminate x_tunnel module
2020-05-02 17:06:12.067 - [DEBUG] module x_tunnel stopping
2020-05-02 17:06:12.071 - [INFO] module x_tunnel stopped
2020-05-02 17:06:25.890 - [INFO] use build-in openssl lib
2020-05-02 17:06:25.895 - [INFO] start XX-Net 4.0.5
2020-05-02 17:06:25.896 - [DEBUG] start confirm_xxnet_exit
2020-05-02 17:06:25.919 - [DEBUG] good, xxnet:8085 clear!
2020-05-02 17:06:25.919 - [DEBUG] finished confirm_xxnet_exit
2020-05-02 17:06:34.060 - [INFO] module gae_proxy started
2020-05-02 17:06:34.061 - [INFO] start gae_proxy time cost:8138 ms
2020-05-02 17:07:15.560 - [DEBUG] start to terminate gae_proxy module
2020-05-02 17:07:15.565 - [DEBUG] module gae_proxy stopping
2020-05-02 17:07:15.567 - [INFO] module gae_proxy stopped
2020-05-02 17:07:15.570 - [DEBUG] start to terminate x_tunnel module
2020-05-02 17:07:15.575 - [DEBUG] module x_tunnel stopping
2020-05-02 17:07:15.578 - [INFO] module x_tunnel stopped
2020-05-02 17:08:00.712 - [INFO] use build-in openssl lib
2020-05-02 17:08:00.720 - [INFO] start XX-Net 4.0.5
2020-05-02 17:08:00.721 - [DEBUG] start confirm_xxnet_exit
2020-05-02 17:08:00.754 - [DEBUG] good, xxnet:8085 clear!
2020-05-02 17:08:00.754 - [DEBUG] finished confirm_xxnet_exit
2020-05-02 17:08:06.959 - [INFO] module gae_proxy started
2020-05-02 17:08:06.960 - [INFO] start gae_proxy time cost:6201 ms
2020-05-02 17:11:13.310 - [DEBUG] start to terminate gae_proxy module
2020-05-02 17:11:13.315 - [DEBUG] module gae_proxy stopping
2020-05-02 17:11:13.318 - [INFO] module gae_proxy stopped
2020-05-02 17:11:13.320 - [DEBUG] start to terminate x_tunnel module
2020-05-02 17:11:13.326 - [DEBUG] module x_tunnel stopping
2020-05-02 17:11:13.329 - [INFO] module x_tunnel stopped
2020-05-02 17:15:56.458 - [INFO] use build-in openssl lib
2020-05-02 17:15:56.463 - [INFO] start XX-Net 4.0.5
2020-05-02 17:15:56.463 - [DEBUG] start confirm_xxnet_exit
2020-05-02 17:15:56.499 - [DEBUG] good, xxnet:8085 clear!
2020-05-02 17:15:56.499 - [DEBUG] finished confirm_xxnet_exit
2020-05-02 17:16:03.591 - [INFO] module gae_proxy started
2020-05-02 17:16:03.594 - [INFO] start gae_proxy time cost:7091 ms
2020-05-02 17:16:03.951 - [INFO] module x_tunnel started
2020-05-02 17:16:03.951 - [INFO] start x_tunnel time cost:356 ms
2020-05-02 17:16:05.335 - [INFO] module smart_router started
2020-05-02 17:16:05.335 - [INFO] start smart_router time cost:1383 ms
2020-05-02 17:16:05.336 - [INFO] begin to start web control
2020-05-02 17:16:05.336 - [INFO] server 127.0.0.1:8085 started.
2020-05-02 17:16:05.337 - [INFO] launcher web control started.
2020-05-02 17:16:05.545 - [INFO] generate desktop shortcut
2020-05-02 17:16:06.556 - [INFO] need_new_uuid: uuid is empty
2020-05-02 17:16:06.557 - [INFO] generate uuid:5d217f17-6aab-414f-953c-f4bceb5dcd80
2020-05-02 17:16:06.559 - [INFO] get uuid:5d217f17-6aab-414f-953c-f4bceb5dcd80
2020-05-02 17:16:07.275 - [DEBUG] launcher web_control 127.0.0.1:57394 GET /config?cmd=get_version 
2020-05-02 17:16:07.282 - [DEBUG] launcher web_control 127.0.0.1:57385 GET /config?cmd=get_config 
2020-05-02 17:16:07.347 - [DEBUG] launcher web_control 127.0.0.1:57394 GET /update?cmd=get_progress 
2020-05-02 17:16:07.452 - [DEBUG] launcher web_control 127.0.0.1:57394 GET /config?cmd=get_config 
2020-05-02 17:16:07.485 - [DEBUG] launcher web_control 127.0.0.1:57394 GET /config?cmd=set_config&postUpdateStat=noChange 
2020-05-02 17:16:08.352 - [DEBUG] launcher web_control 127.0.0.1:57394 GET /update?cmd=get_info 
2020-05-02 17:16:15.533 - [INFO] download https://github.com/XX-net/XX-Net/releases/download/3.15.0/SwitchyOmega.crx to /Users/selina/Downloads/XX-Net-4.0.5/SwitchyOmega/SwitchyOmega.crx, retry:0
2020-05-02 17:16:17.941 - [WARNING] download https://github.com/XX-net/XX-Net/releases/download/3.15.0/SwitchyOmega.crx to /Users/selina/Downloads/XX-Net-4.0.5/SwitchyOmega/SwitchyOmega.crx fail:KeyError('Location')
2020-05-02 17:16:17.941 - [INFO] download https://github.com/XX-net/XX-Net/releases/download/3.15.0/SwitchyOmega.crx to /Users/selina/Downloads/XX-Net-4.0.5/SwitchyOmega/SwitchyOmega.crx, retry:1
2020-05-02 17:17:06.954 - [ERROR] check_update fail:<HTTPError 504: ''>
2020-05-02 17:17:06.965 - [ERROR] Except stack:Traceback (most recent call last):
  File "/Users/selina/Downloads/XX-Net-4.0.5/code/default/launcher/update.py", line 285, in check_push_update
    update_content = opener.open(req_url).read()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 504: 

2020-05-02 17:17:06.966 - [INFO] download https://raw.githubusercontent.com/XX-net/XX-Net/master/code/default/update_version.txt to /Users/selina/Downloads/XX-Net-4.0.5/data/downloads/version.txt, retry:0
2020-05-02 17:17:23.135 - [INFO] download https://github.com/XX-net/XX-Net/releases/download/3.15.0/SwitchyOmega.crx to /Users/selina/Downloads/XX-Net-4.0.5/SwitchyOmega/SwitchyOmega.crx success.
2020-05-02 17:17:23.136 - [INFO] download https://github.com/XX-net/XX-Net/releases/download/3.15.0/AutoProxy.xpi to /Users/selina/Downloads/XX-Net-4.0.5/SwitchyOmega/AutoProxy.xpi, retry:0
2020-05-02 17:17:25.356 - [WARNING] download https://github.com/XX-net/XX-Net/releases/download/3.15.0/AutoProxy.xpi to /Users/selina/Downloads/XX-Net-4.0.5/SwitchyOmega/AutoProxy.xpi fail:KeyError('Location')
2020-05-02 17:17:25.357 - [INFO] download https://github.com/XX-net/XX-Net/releases/download/3.15.0/AutoProxy.xpi to /Users/selina/Downloads/XX-Net-4.0.5/SwitchyOmega/AutoProxy.xpi, retry:1
2020-05-02 17:18:30.552 - [INFO] download https://github.com/XX-net/XX-Net/releases/download/3.15.0/AutoProxy.xpi to /Users/selina/Downloads/XX-Net-4.0.5/SwitchyOmega/AutoProxy.xpi success.
2020-05-02 17:26:07.630 - [DEBUG] launcher web_control 127.0.0.1:58895 GET /update?cmd=get_info 
2020-05-02 17:36:08.298 - [DEBUG] launcher web_control 127.0.0.1:60336 GET /update?cmd=get_info 
2020-05-02 17:46:09.397 - [DEBUG] launcher web_control 127.0.0.1:60336 GET /update?cmd=get_info 
2020-05-02 17:56:09.466 - [DEBUG] launcher web_control 127.0.0.1:61867 GET /update?cmd=get_info 
2020-05-02 18:06:09.586 - [DEBUG] launcher web_control 127.0.0.1:61867 GET /update?cmd=get_info 
2020-05-02 18:16:10.635 - [DEBUG] launcher web_control 127.0.0.1:61867 GET /update?cmd=get_info 
2020-05-02 18:26:11.508 - [DEBUG] launcher web_control 127.0.0.1:51089 GET /update?cmd=get_info 
2020-05-02 18:36:12.347 - [DEBUG] launcher web_control 127.0.0.1:52542 GET /update?cmd=get_info 
2020-05-02 18:46:13.325 - [DEBUG] launcher web_control 127.0.0.1:52542 GET /update?cmd=get_info 
2020-05-02 18:56:13.393 - [DEBUG] launcher web_control 127.0.0.1:54028 GET /update?cmd=get_info 

* X-Tunnel 支付后流量未及时到帐请直接向 xxnet.dev@gmail.com 发邮件，并附上帐号、交易单号等详细信息。

* 是否试过[最新的版本](https://github.com/XX-net/XX-Net/releases )？

* 是否查看过 [Wiki](https://github.com/XX-net/XX-Net/wiki )？

* 是否以相关关键词搜索过类似 issues？

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志，如包含大量文本时，请上传为 txt 文件：

* 如果问题得到解决，请务必回复相关情况，谢谢。

* 即使最终无法解决你遇到的问题，这也是正常的，因为系统和网络环境千差万别。最终结果也能帮助到后来者，请保持正常交流，再寻它法。

* 请不要只写标题，不写内容，不遵守规则的提问会被自动关闭。

**Comment by PeterPung** [comment]
下载了pip、pyopenssl现在提示：
2020-05-02 22:16:26.974 - [ERROR] check_update fail:<HTTPError 504: ''>
2020-05-02 22:16:27.012 - [ERROR] Except stack:Traceback (most recent call last):
  File "/Users/selina/Downloads/XX-Net-4.0.5/code/default/launcher/update.py", line 285, in check_push_update
    update_content = opener.open(req_url).read()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 504:

**Comment by PeterPung** [comment]
请检查浏览器代理设置。
属性 | 值
-- | --
XX-Net 状态 | 空闲
浏览器代理设置 | Fail
CA 证书状态(下载) | Fail
系统代理 | 全局 PAC 代理
-----------------------------------------------
不管托盘图标，不管上面的提示，但是可以用了
