### ISSUE TITLE
4.0.5 smart route 和 dns 报错，direct 列表中的网址都不能访问，报错

### ISSUE THREAD

**Issue by m17design** [XX-net/XX-Net#13158]
direct 列表中的网址不能访问，X-Tunnel 列表中的网址可以访问，自动走 direct 的内网和国内网站也会报错不能访问。

日志 "Smart Router Log":

2020-05-06 09:58:27.108 - [INFO] domain user ['direct'] to 192.168.0.66:80 fail
2020-05-06 09:58:27.111 - [DEBUG] http ('192.168.0.43', 40581) connect to 192.168.0.66:80 GET /description.xml
2020-05-06 09:58:27.112 - [DEBUG] domain user direct to 192.168.0.66:80 except:TypeError("a bytes-like object is required, not 'str'",) 

2020-05-06 09:57:54.740 - [DEBUG] query:www.microsoft.com.lan type:28 from:('127.0.0.1', 43736), return ip num:0 cost:3409
2020-05-06 09:57:54.760 - [ERROR] Except stack:Traceback (most recent call last): File "/XX-Net/code/4.0.5/smart_router/local/dns_server.py", line 529, in on_udp_query reply.add_answer(RR(domain, ttl=60, rdata=A(ip))) File "/XX-Net/code/4.0.5/lib/noarch/dnslib/dns.py", line 979, in __init__ self.data = tuple(map(int,data.rstrip(".").split("."))) TypeError: a bytes-like object is required, not 'str'

2020-05-06 10:04:16.176 - [DEBUG] query:cdnjs.cloudflare.com.lan type:28 from:('127.0.0.1', 39505), return ip num:0 cost:2758
2020-05-06 10:04:16.187 - [DEBUG] DNS query:cdnjs.cloudflare.com.lan type:1 from ('127.0.0.1', 41999)
2020-05-06 10:04:16.188 - [ERROR] on_query except:TypeError("a bytes-like object is required, not 'str'",)
2020-05-06 10:04:16.192 - [DEBUG] DNS query:cdnjs.cloudflare.com.lan type:28 from ('127.0.0.1', 41999)
2020-05-06 10:04:16.194 - [DEBUG] query:cdnjs.cloudflare.com.lan type:28 from:('127.0.0.1', 41999), return ip num:0 cost:3
2020-05-06 10:04:16.196 - [ERROR] Except stack:Traceback (most recent call last): File "/XX-Net/code/4.0.5/smart_router/local/dns_server.py", line 529, in on_udp_query reply.add_answer(RR(domain, ttl=60, rdata=A(ip))) File "/XX-Net/code/4.0.5/lib/noarch/dnslib/dns.py", line 979, in __init__ self.data = tuple(map(int,data.rstrip(".").split("."))) TypeError: a bytes-like object is required, not 'str'

**Comment by m17design** [comment]
系统状态
XX-Net Status:

sys-platform: aarch64, Linux-4.4.132-1075-rockchip-ayufan-ga83beded8524-aarch64-with-Ubuntu-18.04-bionic
os-system: Linux
os-version: #1 SMP Thu Jul 26 08:22:22 UTC 2018
os-release: 4.4.132-1075-rockchip-ayufan-ga83beded8524
os-detail: Ubuntu

architecture: 64bit,ELF
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:75.0) Gecko/20100101 Firefox/75.0
xxnet-version: 4.0.5
python-version: 3.6.9
openssl-version: 17.5.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:undefined ipv4:0 ipv6:100
ipv4-status: Fail
ipv6-status: OK
connected-link: new:0 used:undefined
worker: h1:0 h2:37
scan-ip-thread-num: 8
ip-quality: 576
is-idle: 0
block-stat: undefined
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by snipertulip** [comment]
smart router 
smart_route/local/host_records.py
line 221:
           ipd=utils.to_str(ipd)
            ipl = ipd.split("|")

这边也是，用这个吧utils.to_str转换一下

**Comment by xxnet** [comment]
感谢反馈。

python3 这个转换太烦了，只能遇到问题解决问题

**Comment by snipertulip** [comment]
> 感谢反馈。 python3 这个转换太烦了，只能遇到问题解决问题

最近遇到类似问题，确实有点麻烦。大神们有问题及时反馈，有能力的给个方案。粉丝们感谢你们！！！

**Comment by xxnet** [comment]
修改的代码我先提交了，着急用的先自己看代码。
过两天再一起发版本。

**Comment by m17design** [comment]
> 
> 
> smart router
> smart_route/local/host_records.py
> line 221:
> ipd=utils.to_str(ipd)
> ipl = ipd.split("|")
> 
> 这边也是，用这个吧utils.to_str转换一下

谢谢，改了以后还有别的地方报错，试了试自己改不下去了，改完以后还有其它地方报错，太多了

**Comment by m17design** [comment]
> 
> 修改的代码我先提交了，着急用的先自己看代码。 过两天再一起发版本。

已经下载了新的 dns.py，其它地方還是繼續報錯，大陸網站自動 [direct] 的還是會有問題

`2020-05-10 23:02:14.176 - [ERROR] any err:TypeError("a bytes-like object is required, not 'str'",)

2020-05-10 23:02:14.179 - [ERROR] Except stack:Traceback (most recent call last): File "/XX-Net/code/4.0.5/smart_router/local/proxy_handler.py", line 75, in handle self.http_handler() File "/XX-Net/code/4.0.5/smart_router/local/proxy_handler.py", line 348, in http_handler handle_domain_proxy(sock, host, port, self.client_address) File "/XX-Net/code/4.0.5/smart_router/local/smart_route.py", line 555, in handle_domain_proxy ips = g.dns_srv.query(host) File "/XX-Net/code/4.0.5/smart_router/local/dns_server.py", line 476, in query ips = g.dns_client.query(domain, timeout=1) File "/XX-Net/code/4.0.5/smart_router/local/dns_server.py", line 366, in query g.domain_cache.set_ips(domain, ips) File "/XX-Net/code/4.0.5/smart_router/local/host_records.py", line 221, in set_ips ipl = ipd.split("|") TypeError: a bytes-like object is required, not 'str' `

**Comment by xxnet** [comment]
code/4.0.5/smart_router/local/host_records.py
这个文件也有更新的
