### ISSUE TITLE
跟什么进程冲突报了个错，就再也启动不了了

### ISSUE THREAD

**Issue by ronnie404** [XX-net/XX-Net#13167]
昨晚弹出个提示好像是说跟什么download冲突，就自己关闭了，我也没在意，以为重启一下电脑就好了，结果就再也不能启动了，覆盖安装也不行，启动时显示如下内容，求指点要如何解决？

2020-05-11 06:52:52.399 [launcher][INFO] use build-in openssl lib
2020-05-11 06:52:52.412 [launcher][INFO] start XX-Net 4.0.5
2020-05-11 06:52:52.412 [launcher][DEBUG] start confirm_xxnet_exit
2020-05-11 06:52:53.434 [launcher][DEBUG] good, xxnet:8085 clear!
2020-05-11 06:52:53.434 [launcher][DEBUG] finished confirm_xxnet_exit
2020-05-11 06:52:54.486 [launcher][ERROR] start module gae_proxy fail:Expecting value: line 1 column 1 (char 0)
2020-05-11 06:52:54.493 [launcher][ERROR] Except stack:Traceback (most recent call last):
  File "D:\XX-Net-3.1.19\code\default\launcher\module_init.py", line 44, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local'], 0)
  File "D:\XX-Net-3.1.19\code\default\gae_proxy\local\__init__.py", line 2, in <module>
    from . import apis
  File "D:\XX-Net-3.1.19\code\default\gae_proxy\local\apis.py", line 2, in <module>
    from .front import front, direct_front
  File "D:\XX-Net-3.1.19\code\default\gae_proxy\local\front.py", line 7, in <module>
    from . import check_local_network
  File "D:\XX-Net-3.1.19\code\default\gae_proxy\local\check_local_network.py", line 26, in <module>
    from gae_proxy.local.config import config
  File "D:\XX-Net-3.1.19\code\default\gae_proxy\local\config.py", line 442, in <module>
    config = Config(config_path)
  File "D:\XX-Net-3.1.19\code\default\gae_proxy\local\config.py", line 228, in __init__
    self.load()
  File "D:\XX-Net-3.1.19\code\default\gae_proxy\local\config.py", line 231, in load
    super(Config, self).load()
  File "D:\XX-Net-3.1.19\code\default\lib\noarch\front_base\config.py", line 90, in load
    super(ConfigBase, self).load()
  File "D:\XX-Net-3.1.19\code\default\lib\noarch\xconfig.py", line 29, in load
    self.file_config = json.loads(content)
  File "D:\XX-Net-3.1.19\python3.8.2\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "D:\XX-Net-3.1.19\python3.8.2\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\XX-Net-3.1.19\python3.8.2\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

2020-05-11 06:52:54.494 [launcher][ERROR] launcher except:JSONDecodeError('Expecting value: line 1 column 1 (char 0)')
2020-05-11 06:52:54.500 [launcher][ERROR] Except stack:Traceback (most recent call last):
  File "D:\XX-Net-3.1.19\code\default\launcher\start.py", line 253, in <module>
    main()
  File "D:\XX-Net-3.1.19\code\default\launcher\start.py", line 232, in main
    module_init.start_all_auto()
  File "D:\XX-Net-3.1.19\code\default\launcher\module_init.py", line 121, in start_all_auto
    start(module)
  File "D:\XX-Net-3.1.19\code\default\launcher\module_init.py", line 44, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local'], 0)
  File "D:\XX-Net-3.1.19\code\default\gae_proxy\local\__init__.py", line 2, in <module>
    from . import apis
  File "D:\XX-Net-3.1.19\code\default\gae_proxy\local\apis.py", line 2, in <module>
    from .front import front, direct_front
  File "D:\XX-Net-3.1.19\code\default\gae_proxy\local\front.py", line 7, in <module>
    from . import check_local_network
  File "D:\XX-Net-3.1.19\code\default\gae_proxy\local\check_local_network.py", line 26, in <module>
    from gae_proxy.local.config import config
  File "D:\XX-Net-3.1.19\code\default\gae_proxy\local\config.py", line 442, in <module>
    config = Config(config_path)
  File "D:\XX-Net-3.1.19\code\default\gae_proxy\local\config.py", line 228, in __init__
    self.load()
  File "D:\XX-Net-3.1.19\code\default\gae_proxy\local\config.py", line 231, in load
    super(Config, self).load()
  File "D:\XX-Net-3.1.19\code\default\lib\noarch\front_base\config.py", line 90, in load
    super(ConfigBase, self).load()
  File "D:\XX-Net-3.1.19\code\default\lib\noarch\xconfig.py", line 29, in load
    self.file_config = json.loads(content)
  File "D:\XX-Net-3.1.19\python3.8.2\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "D:\XX-Net-3.1.19\python3.8.2\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\XX-Net-3.1.19\python3.8.2\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Press Enter to continue...

**Comment by 2badao** [comment]
我也遇到过，好像是和迅雷冲突

**Comment by 2fdnkpj** [comment]
软件冲突或端口冲突

**Comment by xxnet** [comment]
配置文件 data/gae_proxy/config.json 格式错了。
如果不是自己修改的，先删除，再重新配置一遍
