### ISSUE TITLE
x-tunnel ,连接服务器失败：AttributeError("'Http1Worker' object has no attribute 'host'",)

### ISSUE THREAD

**Issue by dalaogan** [XX-net/XX-Net#13179]
2020-05-19 09:15:39.596 - [INFO] xxnet_version:3.16.1

2020-05-19 09:15:39.597 - [INFO] server 127.0.0.1:1080 started.

2020-05-19 09:15:39.597 - [INFO] Socks5 server listen:127.0.0.1:1080.

2020-05-19 09:15:40.403 - [DEBUG] x_tunnel force update info

2020-05-19 09:15:41.625 - [WARNING] front retry center.xx-net.net/login

2020-05-19 09:15:42.829 - [WARNING] front retry center.xx-net.net/login

2020-05-19 09:15:43.954 - [ERROR] order e:AttributeError("'Http1Worker' object has no attribute 'host'",)

2020-05-19 09:15:43.958 - [ERROR] Except stack:Traceback (most recent call last): File "/Users/manchm/toolbox/XX-Net-3.16.1/code/default/x_tunnel/local/proxy_session.py", line 751, in call_api data=upload_post_data, timeout=5) File "/Users/manchm/toolbox/XX-Net-3.16.1/code/default/x_tunnel/local/front_dispatcher.py", line 111, in request method, host=host, path=path, headers=dict(headers), data=data, timeout=timeout) File "/Users/manchm/toolbox/XX-Net-3.16.1/code/default/x_tunnel/local/cloudflare_front/front.py", line 91, in request self.logger.warn("undefined undefinedundefined status:%d trace:undefined", method, response.worker.host, path, status, AttributeError: 'Http1Worker' object has no attribute 'host'

2020-05-19 09:16:02.094 - [DEBUG] req_info in force

2020-05-19 09:16:02.094 - [DEBUG] x_tunnel force update info

2020-05-19 09:16:02.294 - [ERROR] order e:AttributeError("'Http1Worker' object has no attribute 'host'",)

2020-05-19 09:16:02.294 - [ERROR] Except stack:Traceback (most recent call last): File "/Users/manchm/toolbox/XX-Net-3.16.1/code/default/x_tunnel/local/proxy_session.py", line 751, in call_api data=upload_post_data, timeout=5) File "/Users/manchm/toolbox/XX-Net-3.16.1/code/default/x_tunnel/local/front_dispatcher.py", line 111, in request method, host=host, path=path, headers=dict(headers), data=data, timeout=timeout) File "/Users/manchm/toolbox/XX-Net-3.16.1/code/default/x_tunnel/local/cloudflare_front/front.py", line 91, in request self.logger.warn("undefined undefinedundefined status:%d trace:undefined", method, response.worker.host, path, status, AttributeError: 'Http1Worker' object has no attribute 'host'

**Comment by xxnet** [comment]
试试新版
