### ISSUE TITLE
新下载4.0.5 无法运行在Debian上。

### ISSUE THREAD

**Issue by isaac-yang1** [XX-net/XX-Net#13189]
./start: 103: pip: not found
2020-05-27 14:15:40.871 [launcher][INFO] import build-in openssl fail:ModuleNotFoundError("No module named '_cffi_backend'")
2020-05-27 14:15:40.887 [launcher][ERROR] import system python-OpenSSL fail:ModuleNotFoundError("No module named '_cffi_backend'")
2020-05-27 14:15:40.892 [launcher][ERROR] Except stack:Traceback (most recent call last):
  File "code/default/launcher/start.py", line 164, in <module>
    import OpenSSL as oss_test
  File "/usr/lib/python3/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 12, in <module>
    from cryptography import x509
  File "/usr/lib/python3/dist-packages/cryptography/x509/__init__.py", line 8, in <module>
    from cryptography.x509.base import (
  File "/usr/lib/python3/dist-packages/cryptography/x509/base.py", line 18, in <module>
    from cryptography.x509.extensions import Extension, ExtensionType
  File "/usr/lib/python3/dist-packages/cryptography/x509/extensions.py", line 20, in <module>
    from cryptography.hazmat.primitives import constant_time, serialization
  File "/usr/lib/python3/dist-packages/cryptography/hazmat/primitives/constant_time.py", line 11, in <module>
    from cryptography.hazmat.bindings._constant_time import lib
ModuleNotFoundError: No module named '_cffi_backend'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "code/default/launcher/start.py", line 174, in <module>
    import OpenSSL
  File "/usr/lib/python3/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 12, in <module>
    from cryptography import x509
  File "/usr/lib/python3/dist-packages/cryptography/x509/__init__.py", line 8, in <module>
    from cryptography.x509.base import (
  File "/usr/lib/python3/dist-packages/cryptography/x509/base.py", line 18, in <module>
    from cryptography.x509.extensions import Extension, ExtensionType
  File "/usr/lib/python3/dist-packages/cryptography/x509/extensions.py", line 20, in <module>
    from cryptography.hazmat.primitives import constant_time, serialization
  File "/usr/lib/python3/dist-packages/cryptography/hazmat/primitives/constant_time.py", line 11, in <module>
    from cryptography.hazmat.bindings._constant_time import lib
ModuleNotFoundError: No module named '_cffi_backend'

Try install python-openssl

Press Enter to continue...

**Comment by xxnet** [comment]
第一次启动估计要sudo 来安装python3-pyOpenSSL

**Comment by isaac-yang1** [comment]
> 第一次启动估计要sudo 来安装python3-pyOpenSSL

Requirement already satisfied: pyopenssl in /usr/lib/python3/dist-packages (19.1.0)

**Comment by xxnet** [comment]
试试

python3 -m pip install cffi


参考这里

https://stackoverflow.com/questions/34370962/no-module-named-cffi-backend

**Comment by isaac-yang1** [comment]
下班了。明天在试试

Isaac

Michael.X <notifications@github.com> 於 2020年5月27日 18:22 寫道：

﻿

试试

python3 -m pip install cffi


参考这里

https://stackoverflow.com/questions/34370962/no-module-named-cffi-backend

**Comment by isaac-yang1** [comment]
升级了 0 个软件包，新安装了 0 个软件包，要卸载 0 个软件包，有 287 个软件包未被升级。
./start: 103: pip: not found
2020-05-28 09:21:12.612 [launcher][INFO] import build-in openssl fail:ModuleNotFoundError("No module named '_cffi_backend'")
2020-05-28 09:21:12.632 [launcher][ERROR] import system python-OpenSSL fail:ModuleNotFoundError("No module named '_cffi_backend'")
2020-05-28 09:21:12.636 [launcher][ERROR] Except stack:Traceback (most recent call last):
  File "code/default/launcher/start.py", line 164, in <module>
    import OpenSSL as oss_test
  File "/usr/lib/python3/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 12, in <module>
    from cryptography import x509
  File "/usr/lib/python3/dist-packages/cryptography/x509/__init__.py", line 8, in <module>
    from cryptography.x509.base import (
  File "/usr/lib/python3/dist-packages/cryptography/x509/base.py", line 18, in <module>
    from cryptography.x509.extensions import Extension, ExtensionType
  File "/usr/lib/python3/dist-packages/cryptography/x509/extensions.py", line 20, in <module>
    from cryptography.hazmat.primitives import constant_time, serialization
  File "/usr/lib/python3/dist-packages/cryptography/hazmat/primitives/constant_time.py", line 11, in <module>
    from cryptography.hazmat.bindings._constant_time import lib
ModuleNotFoundError: No module named '_cffi_backend'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "code/default/launcher/start.py", line 174, in <module>
    import OpenSSL
  File "/usr/lib/python3/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 12, in <module>
    from cryptography import x509
  File "/usr/lib/python3/dist-packages/cryptography/x509/__init__.py", line 8, in <module>
    from cryptography.x509.base import (
  File "/usr/lib/python3/dist-packages/cryptography/x509/base.py", line 18, in <module>
    from cryptography.x509.extensions import Extension, ExtensionType
  File "/usr/lib/python3/dist-packages/cryptography/x509/extensions.py", line 20, in <module>
    from cryptography.hazmat.primitives import constant_time, serialization
  File "/usr/lib/python3/dist-packages/cryptography/hazmat/primitives/constant_time.py", line 11, in <module>
    from cryptography.hazmat.bindings._constant_time import lib
ModuleNotFoundError: No module named '_cffi_backend'

Try install python-openssl

Press Enter to continue...
@xxnet

**Comment by xxnet** [comment]
你的debian 是什么版本？

**Comment by isaac-yang1** [comment]
> 你的debian 是什么版本？

Debian 9.3.0-11

**Comment by xxnet** [comment]
不知道你的环境出了什么问题，建议按照一个镜像环境，可以是conda或者 virtualenv
参考这里：
https://problemsolvingwithpython.com/01-Orientation/01.05-Installing-Anaconda-on-Linux/
https://www.howtoing.com/how-to-install-the-anaconda-python-distribution-on-debian-9

或者：
https://linuxconfig.org/setting-up-the-python-virtualenv-development-environment-on-debian-linux
https://www.jianshu.com/p/d84950dd99a6

**Comment by isaac-yang1** [comment]
> 不知道你的环境出了什么问题，建议按照一个镜像环境，可以是conda或者 virtualenv 参考这里： https://problemsolvingwithpython.com/01-Orientation/01.05-Installing-Anaconda-on-Linux/ https://www.howtoing.com/how-to-install-the-anaconda-python-distribution-on-debian-9 或者： https://linuxconfig.org/setting-up-the-python-virtualenv-development-environment-on-debian-linux https://www.jianshu.com/p/d84950dd99a6

xxnet 是一定要调用python2吗？ 我现在强制把系统默认的python 设置成python3了

**Comment by xxnet** [comment]
4.x 版本是用python3

**Comment by isaac-yang1** [comment]
> 不知道你的环境出了什么问题，建议按照一个镜像环境，可以是conda或者 virtualenv 参考这里： https://problemsolvingwithpython.com/01-Orientation/01.05-Installing-Anaconda-on-Linux/ https://www.howtoing.com/how-to-install-the-anaconda-python-distribution-on-debian-9 或者： https://linuxconfig.org/setting-up-the-python-virtualenv-development-environment-on-debian-linux https://www.jianshu.com/p/d84950dd99a6

头痛。。。也不行

**Comment by isaac-yang1** [comment]
运行了一段命令之后就可以了。
sudo ln -sf /usr/bin/python2.5 /usr/bin/python
https://blog.csdn.net/pythoner/article/details/3845884

可能是我之前把python锁住了。 一定要运行我指定的版本。 @xxnet

**Comment by xxnet** [comment]
应该是你的系统问题，但是4.0.5是用python3的，你改的python2 ?

**Comment by xxnet** [comment]
能用就好，没有必要研究了
