### ISSUE TITLE
4.1.0 报错 [smart_router][ERROR]

### ISSUE THREAD

**Issue by m17design** [XX-net/XX-Net#13198]
May 28 18:32:33 rock64 start[11980]: 2020-05-28 18:32:28.432 [smart_router][DEBUG] http ('192.168.0.76', 52456) connect to deb.ayufan.eu:80 GET /orgs/ayufan-rock64/releases/InRelease
May 28 18:32:33 rock64 start[11980]: 2020-05-28 18:32:28.439 [smart_router][ERROR] Except stack:Traceback (most recent call last):
May 28 18:32:33 rock64 start[11980]:   File "/XX-Net/code/4.1.0/smart_router/local/smart_route.py", line 398, in try_loop
May 28 18:32:33 rock64 start[11980]:     do_gae(sock, host, port, client_address, left_buf)
May 28 18:32:33 rock64 start[11980]:   File "/XX-Net/code/4.1.0/smart_router/local/smart_route.py", line 295, in do_gae
May 28 18:32:33 rock64 start[11980]:     leadbyte = sock.recv(1, socket.MSG_PEEK)
May 28 18:32:33 rock64 start[11980]:   File "/XX-Net/code/4.1.0/smart_router/local/socket_wrap.py", line 37, in recv
May 28 18:32:33 rock64 start[11980]:     if self.replace_pattern and " HTTP/1.1\r\n" in d:
May 28 18:32:33 rock64 start[11980]: TypeError: a bytes-like object is required, not 'str'

----------------------------------------------------------------------------------

XX-Net Status:

sys-platform: aarch64, Linux-4.4.132-1075-rockchip-ayufan-ga83beded8524-aarch64-with-Ubuntu-18.04-bionic
os-system: Linux
os-version: #1 SMP Thu Jul 26 08:22:22 UTC 2018
os-release: 4.4.132-1075-rockchip-ayufan-ga83beded8524
os-detail: Ubuntu

architecture: 64bit,ELF
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:76.0) Gecko/20100101 Firefox/76.0
xxnet-version: 4.1.0
python-version: 3.6.9
openssl-version: 17.5.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:undefined ipv4:0 ipv6:200
ipv4-status: OK
ipv6-status: OK
connected-link: new:2 used:undefined
worker: h1:0 h2:117
scan-ip-thread-num: 1
ip-quality: 663
is-idle: 0
block-stat: undefined
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by xxnet** [comment]
收到，晚些发版本
