### ISSUE TITLE
arm环境下提示64位系统不能用。

### ISSUE THREAD

**Issue by yangkkokk** [XX-net/XX-Net#1320]
Nov  3 15:20:52 - [INFO] start XX-Net 2.5.5
Nov  3 15:20:52 - [DEBUG] start confirm_xxnet_exit
Nov  3 15:20:52 - [DEBUG] good, xxnet:8087 cleared!
Nov  3 15:20:52 - [DEBUG] good, xxnet:8085 clear!
Nov  3 15:20:52 - [DEBUG] finished confirm_xxnet_exit
Nov  3 15:20:52 - [ERROR] start module gae_proxy fail:/root/XX-Net-2.5.5/python27/1.0/lib/linux/OpenSSL/crypto.so: wrong ELF class: ELFCLASS64
Traceback (most recent call last):
  File "/root/XX-Net-2.5.5/launcher/module_init.py", line 37, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "/root/XX-Net-2.5.5/gae_proxy/start.py", line 14, in <module>
    import local.proxy as client
  File "/root/XX-Net-2.5.5/gae_proxy/local/proxy.py", line 74, in <module>
    from cert_util import CertUtil
  File "/root/XX-Net-2.5.5/gae_proxy/local/cert_util.py", line 37, in <module>
    import OpenSSL
  File "/root/XX-Net-2.5.5/python27/1.0/lib/linux/OpenSSL/__init__.py", line 36, in <module>
    from OpenSSL import crypto
ImportError: /root/XX-Net-2.5.5/python27/1.0/lib/linux/OpenSSL/crypto.so: wrong ELF class: ELFCLASS64

Nov  3 15:20:52 - [INFO] start gae_proxy time cost 23
Nov  3 15:20:52 - [INFO] begin to start web control
Nov  3 15:20:52 - [INFO] launcher web control started.
Nov  3 15:20:53 - [INFO] get uuid:7876e020-24e4-496a-ad15-973d6859ff7c
Nov  3 15:20:53 - [WARNING] check_update fail:URLError(error(111, 'Connection refused'),)
Nov  3 15:20:53 - [INFO] download https://raw.githubusercontent.com/XX-net/XX-Net/master/README.md to /root/XX-Net-2.5.5/data/downloads/README.md, retry:0

这个模块我可以自己编译一个吗？

**Comment by yangkkokk** [comment]
已经搞定.

**Comment by yangkkokk** [comment]
root@Qbee-X:~/XX-Net-2.5.5# ./start.sh 
Nov  3 15:34:39 - [INFO] start XX-Net 2.5.5
Nov  3 15:34:39 - [DEBUG] start confirm_xxnet_exit
Nov  3 15:34:39 - [DEBUG] good, xxnet:8087 cleared!
Nov  3 15:34:40 - [DEBUG] good, xxnet:8085 clear!
Nov  3 15:34:40 - [DEBUG] finished confirm_xxnet_exit
Nov  3 15:34:40 - [INFO] load ip range file:/root/XX-Net-2.5.5/gae_proxy/local/ip_range.txt
Nov  3 15:34:40 - [INFO] load google ip_list num:0, gws num:0
Nov  3 15:34:40 - [INFO] SSL use version:TLSv1
Nov  3 15:34:40 - [DEBUG] ## GAEProxy set keep_running: True
Nov  3 15:34:40 - [INFO] ------------------------------------------------------
Nov  3 15:34:40 - [INFO] Python Version     : 2.7.3
Nov  3 15:34:40 - [INFO] OS                 : Dist:Ubuntu; Version:12.04; ID:precise
Nov  3 15:34:40 - [INFO] Listen Address     : 127.0.0.1:8087
Nov  3 15:34:40 - [INFO] GAE APPID          : xxnet-1|xxnet-2|xxnet-3|xxnet-4|xxnet-5|xxnet-6|xxnet-7|xxnet-8|xxnet-9|xxnet-10|xxnet-11|xxnet-12|xxnet-13|xxnet-14|xxnet-15|xxnet-16|xxnet-17|xxnet-18|xxnet-19|xxnet-20|xxnet-21|xxnet-22|xxnet-23|xxnet-24|xxnet-25|xxnet-26|xxnet-27|xxnet-28|xxnet-29|xxnet-30|xxnet-31|xxnet-32|xxnet-33|xxnet-34|xxnet-35|xxnet-36|xxnet-37|xxnet-38|xxnet-39|xxnet-40|xxnet-41|xxnet-42|xxnet-43|xxnet-44|xxnet-45|xxnet-46|xxnet-47|xxnet-48|xxnet-49|xxnet-50|xxnet-51|xxnet-52|xxnet-53|xxnet-54|xxnet-55|xxnet-56|xxnet-57|xxnet-58|xxnet-59|xxnet-60|xxnet-61|xxnet-62|xxnet-63|xxnet-64|xxnet-65|xxnet-66|xxnet-67|xxnet-68|xxnet-69|xxnet-70|xxnet-71|xxnet-72|xxnet-72|xxnet-73|xxnet-74|xxnet-75|xxnet-76|xxnet-77|xxnet-78|xxnet-79|xxnet-80|xxnet-81|xxnet-82|xxnet-83|xxnet-84|xxnet-85|xxnet-86|xxnet-87|xxnet-88|xxnet-89|xxnet-90|xxnet-91|xxnet-92|xxnet-93|xxnet-94|xxnet-95|xxnet-96|xxnet-97|xxnet-98|xxnet-99|xxnet-100|xxnet-101|xxnet-102|xxnet-103|xxnet-104|xxnet-105|xxnet-106|xxnet-107|xxnet-108|xxnet-109|xxnet-110|xxnet-111|xxnet-112|xxnet-113|xxnet-114|xxnet-115|xxnet-116|xxnet-117|xxnet-118|xxnet-119|xxnet-120|xxnet-121|xxnet-122|xxnet-123|xxnet-124|xxnet-125|xxnet-126|xxnet-127|xxnet-128|xxnet-129|xxnet-130|xxnet-131|xxnet-132|xxnet-133|xxnet-134|xxnet-135|xxnet-136|xxnet-137|xxnet-138|xxnet-139|xxnet-140|xxnet-141|xxnet-142|xxnet-143|xxnet-144|xxnet-145|xxnet-146|xxnet-147|xxnet-148|xxnet-149|xxnet-150|xxnet-151|xxnet-152|xxnet-153|xxnet-154|xxnet-155|xxnet-156|xxnet-157|xxnet-158|xxnet-159
Nov  3 15:34:40 - [INFO] Pac Server         : http://127.0.0.1:8086/proxy.pac
Nov  3 15:34:40 - [INFO] ------------------------------------------------------
Nov  3 15:34:40 - [INFO] no CA file exist
Nov  3 15:34:40 - [INFO] clean old site certs
Nov  3 15:34:40 - [INFO] generate CA file:/root/XX-Net-2.5.5/data/gae_proxy/CA.crt
Nov  3 15:34:46 - [INFO] create ca
Nov  3 15:34:46 - [INFO] server 127.0.0.1:8087 started.
Nov  3 15:34:46 - [INFO] server 127.0.0.1:8086 started.
Nov  3 15:34:46 - [INFO] gae_proxy started
Nov  3 15:34:46 - [INFO] start gae_proxy time cost 6365
Nov  3 15:34:46 - [INFO] begin to start web control
Nov  3 15:34:46 - [INFO] launcher web control started.
Nov  3 15:34:47 - [INFO] get uuid:7876e020-24e4-496a-ad15-973d6859ff7c
Nov  3 15:34:48 - [INFO] GAE CONNECT xxnet-update.appspot.com:443 
Nov  3 15:34:48 - [DEBUG] GAE CONNECT GET https://xxnet-update.appspot.com/update.json?uuid=7876e020-24e4-496a-ad15-973d6859ff7c&version=2.5.5
Nov  3 15:34:58 - [WARNING] no gws ip
Nov  3 15:35:03 - [DEBUG] create ssl timeout fail.
Nov  3 15:35:03 - [DEBUG] create_ssl_connection fail
Nov  3 15:35:08 - [WARNING] no gws ip



Nov  3 15:35:18 - [DEBUG] create ssl timeout fail.
Nov  3 15:35:18 - [DEBUG] create_ssl_connection fail
Nov  3 15:35:18 - [WARNING] no gws ip
Nov  3 15:35:28 - [WARNING] no gws ip
Nov  3 15:35:33 - [DEBUG] create ssl timeout fail.
Nov  3 15:35:33 - [DEBUG] create_ssl_connection fail
Nov  3 15:35:33 - [DEBUG] GAE_Exception 2 'try max times'
Nov  3 15:35:33 - [WARNING] gae_exception:GAE_Exception() https://xxnet-update.appspot.com/update.json?uuid=7876e020-24e4-496a-ad15-973d6859ff7c&version=2.5.5
Nov  3 15:35:33 - [WARNING] check_update fail:HTTPError()
Nov  3 15:35:33 - [INFO] download https://raw.githubusercontent.com/XX-net/XX-Net/master/README.md to /root/XX-Net-2.5.5/data/downloads/README.md, retry:0
Nov  3 15:35:38 - [WARNING] no gws ip


Nov  3 15:35:48 - [WARNING] no gws ip
Nov  3 15:35:58 - [WARNING] no gws ip
Nov  3 15:36:08 - [WARNING] no gws ip
Nov  3 15:36:18 - [WARNING] no gws ip
Nov  3 15:36:28 - [WARNING] no gws ip
Nov  3 15:36:38 - [WARNING] no gws ip
Nov  3 15:36:38 - [DEBUG] sort ip time:9983ms
Nov  3 15:36:38 - [DEBUG] sort ip time:9983ms
Nov  3 15:36:38 - [DEBUG] sort ip time:9984ms
Nov  3 15:36:38 - [DEBUG] sort ip time:9984ms
Nov  3 15:36:38 - [DEBUG] sort ip time:9983ms
Nov  3 15:36:48 - [WARNING] no gws ip
Nov  3 15:36:48 - [DEBUG] sort ip time:9977ms
Nov  3 15:36:48 - [DEBUG] sort ip time:9977ms
Nov  3 15:36:58 - [WARNING] no gws ip
Nov  3 15:36:58 - [DEBUG] sort ip time:9970ms
Nov  3 15:37:08 - [WARNING] no gws ip

**Comment by xxnet** [comment]
先在PC上跑，扫描到ip后拷贝过去吧

解决了也把解决过程贴出来吧，后面的人可以参考

2015-11-03 23:40 GMT+08:00 yangkkokk <notifications@github.com>:

**Comment by ilofter** [comment]
请问怎么解决的，在Android上同样错误

**Comment by yangkkokk** [comment]
哪个错误

2015-11-11 0:39 GMT+08:00 shengyu <notifications@github.com>:

**Comment by mdj20130907** [comment]
apt-get install python-openssl
