### ISSUE TITLE
mac 10.15.4 启动 xx-net 4.0.5 No module named 'OpenSSL

### ISSUE THREAD

**Issue by shangkaixuan** [XX-net/XX-Net#13238]
XX-Net version:4.0.5
The directory '/Users/srh/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/srh/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting pyOpenSSL
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 500 Fail'))': /simple/pyopenssl/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 500 Fail'))': /simple/pyopenssl/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 500 Fail'))': /simple/pyopenssl/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 500 Fail'))': /simple/pyopenssl/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 500 Fail'))': /simple/pyopenssl/
  Could not find a version that satisfies the requirement pyOpenSSL (from versions: )
No matching distribution found for pyOpenSSL
2020-06-12 21:45:46.380 [launcher][INFO] import build-in openssl fail:ModuleNotFoundError("No module named 'OpenSSL'")
2020-06-12 21:45:46.381 [launcher][ERROR] import system python-OpenSSL fail:ModuleNotFoundError("No module named 'OpenSSL'")
2020-06-12 21:45:46.382 [launcher][ERROR] Except stack:Traceback (most recent call last):
  File "code/default/launcher/start.py", line 164, in <module>
    import OpenSSL as oss_test
ModuleNotFoundError: No module named 'OpenSSL'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "code/default/launcher/start.py", line 174, in <module>
    import OpenSSL
ModuleNotFoundError: No module named 'OpenSSL'

Try install python-openssl

Press Enter to continue...

**Comment by archlinux2020** [comment]
你是如何开启IPV6的呢

**Comment by miketwes** [comment]
不用开启IPV6

![2020-06-15_600x689](https://user-images.githubusercontent.com/6849681/84633314-cb226800-af22-11ea-950e-c6743cb5d562.png)

具体用法详见 [XX-Net-mini ](https://github.com/miketwes/XX-Net-mini)
