### ISSUE TITLE
xx-net 4.1.1 mac 启动报错

### ISSUE THREAD

**Issue by reclusegit** [XX-net/XX-Net#13230]
今天git clone 新版本，sudo ./start 后报错：

> $ sudo ./start
XX-Net version:4.1.1
WARNING: The directory '/Users/mac/Library/Caches/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Looking in indexes: http://mirrors.aliyun.com/pypi/simple/
Requirement already satisfied: pyOpenSSL in /Users/mac/Library/Python/3.7/lib/python/site-packages (19.1.0)
Requirement already satisfied: six>=1.5.2 in /Users/mac/Library/Python/3.7/lib/python/site-packages (from pyOpenSSL) (1.14.0)
Requirement already satisfied: cryptography>=2.8 in /Library/Python/3.7/site-packages (from pyOpenSSL) (2.9.2)
Requirement already satisfied: cffi!=1.11.3,>=1.8 in /Library/Python/3.7/site-packages (from cryptography>=2.8->pyOpenSSL) (1.14.0)
Requirement already satisfied: pycparser in /Library/Python/3.7/site-packages (from cffi!=1.11.3,>=1.8->cryptography>=2.8->pyOpenSSL) (2.20)
2020-06-08 15:37:13.113 [launcher][INFO] import build-in openssl fail:ModuleNotFoundError("No module named 'cryptography'")
2020-06-08 15:37:13.122 [launcher][ERROR] import system python-OpenSSL fail:ModuleNotFoundError("No module named 'cryptography'")
2020-06-08 15:37:13.125 [launcher][ERROR] Except stack:Traceback (most recent call last):
  File "code/default/launcher/start.py", line 164, in <module>
    import OpenSSL as oss_test
  File "/Users/mac/Library/Python/3.7/lib/python/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/Users/mac/Library/Python/3.7/lib/python/site-packages/OpenSSL/crypto.py", line 12, in <module>
    from cryptography import x509
ModuleNotFoundError: No module named 'cryptography'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "code/default/launcher/start.py", line 174, in <module>
    import OpenSSL
  File "/Users/mac/Library/Python/3.7/lib/python/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/Users/mac/Library/Python/3.7/lib/python/site-packages/OpenSSL/crypto.py", line 12, in <module>
    from cryptography import x509
ModuleNotFoundError: No module named 'cryptography'

Try install python-openssl

看提示是说少openssl相关的库，但是我查了机器的安装库是有的：

> $ openssl
OpenSSL> version
OpenSSL 1.1.1g  21 Apr 2020

> $ pip list
Package           Version
----------------- ----------
astroid           2.4.1
autopep8          1.5.2
bcrypt            3.1.7
certifi           2019.11.28
cffi              1.14.0
chardet           3.0.4
click             7.1.1
cryptography      2.9.2
cssselect         1.1.0
defusedxml        0.6.0
Flask             1.1.1
Flask-Login       0.5.0
idna              2.9
isort             4.3.21
itsdangerous      1.1.0
Jinja2            2.11.1
json5             0.9.4
lazy-object-proxy 1.4.3
lxml              4.5.0
MarkupSafe        1.1.1
mccabe            0.6.1
paramiko          2.7.1
pathlib           1.0.1
pip               20.1.1
pycodestyle       2.6.0
pycparser         2.20
pycurl            7.43.0.5
pygame            1.9.6
pylint            2.5.0
PyNaCl            1.4.0
pyOpenSSL         19.1.0
pyquery           1.4.1
pyspider          0.3.10
PyYAML            5.3.1
requests          2.23.0
selenium          3.141.0
setuptools        40.8.0
six               1.14.0
tblib             1.6.0
toml              0.10.0
tornado           4.5.3
typed-ast         1.4.1
u-msgpack-python  2.5.2
urllib3           1.25.8
Werkzeug          1.0.1
wheel             0.33.1
wrapt             1.12.1
WsgiDAV           3.0.3

请问一下，这个是什么情况？

**Comment by xxnet** [comment]
python2 和 python3是分开的。
所以要看python3的
pip3 list

**Comment by reclusegit** [comment]
不好意思回复晚了。

`$ pip3 list
Package           Version
----------------- ----------
astroid           2.4.1
autopep8          1.5.2
bcrypt            3.1.7
certifi           2019.11.28
cffi              1.14.0
chardet           3.0.4
click             7.1.1
cryptography      2.9.2
cssselect         1.1.0
defusedxml        0.6.0
Flask             1.1.1
Flask-Login       0.5.0
idna              2.9
isort             4.3.21
itsdangerous      1.1.0
Jinja2            2.11.1
json5             0.9.4
lazy-object-proxy 1.4.3
lxml              4.5.0
MarkupSafe        1.1.1
mccabe            0.6.1
paramiko          2.7.1
pathlib           1.0.1
pip               20.1.1
pycodestyle       2.6.0
pycparser         2.20
pycurl            7.43.0.5
pygame            1.9.6
pylint            2.5.0
PyNaCl            1.4.0
pyOpenSSL         19.1.0
pyquery           1.4.1
pyspider          0.3.10
PyYAML            5.3.1
requests          2.23.0
selenium          3.141.0
setuptools        40.8.0
six               1.14.0
tblib             1.6.0
toml              0.10.0
tornado           4.5.3
typed-ast         1.4.1
u-msgpack-python  2.5.2
urllib3           1.25.8
Werkzeug          1.0.1
wheel             0.33.1
wrapt             1.12.1
WsgiDAV           3.0.3
`

**Comment by archlinux2020** [comment]
你的mac catalina 10.15.5是如何安装成功miredo的，我安装后，在系统偏好设置里没有找到miredo，谢谢

**Comment by reclusegit** [comment]
抱歉，我mac还没安装miredo

**Comment by archlinux2020** [comment]
没有miredo，怎么能启动IPV6，那xx-net就没有办法用的

**Comment by archlinux2020** [comment]
那你之前 是怎么在mac上用xx-net上外网的呢

**Comment by xxnet** [comment]
@reclusegit 
不明白什么原因，你的python环境有没有动过？
前面一个debian的用户是锁定了python也导致了类似的问题。
最后自己找到了就好了
#13189

**Comment by archlinux2020** [comment]
哥们，你们是怎么在mac上用xx-net的，miredo都装不上

**Comment by archlinux2020** [comment]
各位帮帮忙，告诉怎么让mac上能用xx-net
