### ISSUE TITLE
新版本4.0  在openwrt软路由上如何运行？

### ISSUE THREAD

**Issue by zhujun99170** [XX-net/XX-Net#13246]
希望老大们能给个教程，安装python3始终有问题，运行XX-NET便提示要安装python openssl，明明已经安装了啊。

**Comment by zhujun99170** [comment]
2020-06-18 19:44:41.916 [launcher][ERROR] import system python-OpenSSL fail:ImportError('Error loading shared library libffi.so.7: No such file or directory (needed by /usr/lib/python3.8/site-packages/_cffi_backend.cpython-38.so)')
2020-06-18 19:44:41.921 [launcher][ERROR] Except stack:Traceback (most recent call last):
  File "code/default/launcher/start.py", line 164, in <module>
    import OpenSSL as oss_test
  File "/usr/lib/python3.8/site-packages/OpenSSL/__init__.py", line 8, in <module>
  File "/usr/lib/python3.8/site-packages/OpenSSL/crypto.py", line 12, in <module>
  File "/usr/lib/python3.8/site-packages/cryptography/x509/__init__.py", line 8, in <module>
  File "/usr/lib/python3.8/site-packages/cryptography/x509/base.py", line 18, in <module>
  File "/usr/lib/python3.8/site-packages/cryptography/x509/extensions.py", line 20, in <module>
  File "/usr/lib/python3.8/site-packages/cryptography/hazmat/primitives/constant_time.py", line 11, in <module>
ImportError: Error loading shared library libffi.so.7: No such file or directory (needed by /usr/lib/python3.8/site-packages/_cffi_backend.cpython-38.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "code/default/launcher/start.py", line 174, in <module>
    import OpenSSL
  File "/usr/lib/python3.8/site-packages/OpenSSL/__init__.py", line 8, in <module>
  File "/usr/lib/python3.8/site-packages/OpenSSL/crypto.py", line 12, in <module>
  File "/usr/lib/python3.8/site-packages/cryptography/x509/__init__.py", line 8, in <module>
  File "/usr/lib/python3.8/site-packages/cryptography/x509/base.py", line 18, in <module>
  File "/usr/lib/python3.8/site-packages/cryptography/x509/extensions.py", line 20, in <module>
  File "/usr/lib/python3.8/site-packages/cryptography/hazmat/primitives/constant_time.py", line 11, in <module>
ImportError: Error loading shared library libffi.so.7: No such file or directory (needed by /usr/lib/python3.8/site-packages/_cffi_backend.cpython-38.so)

Try install python-openssl

这是运行XX-NET的错误提示。

**Comment by 2378** [comment]
opkg install python3 or opkg install python3-openssl 

但版本是3.4.3  改目录名看能不能跑  不行就得自己编译3.8

其实要做全网代理，最好让旁路由处理，让nas干也行。你这想法几年前就干过，既不太安全也影响主路由性能。

**Comment by masktao** [comment]
不敢用路由跑这个,肯定会拖慢路由cpu,拖慢网速

**Comment by zhujun99170** [comment]
安装了python3 python3-openssl，运行还是出现如下错误：
root@OpenWrt:~# XX-Net version:4.0.5
2020-06-21 19:47:17.494 [launcher][INFO] use build-in openssl lib
2020-06-21 19:47:17.965 [launcher][INFO] start XX-Net 4.0.5
2020-06-21 19:47:17.965 [launcher][DEBUG] start confirm_xxnet_exit
2020-06-21 19:47:18.001 [launcher][DEBUG] good, xxnet:8085 clear!
2020-06-21 19:47:18.002 [launcher][DEBUG] finished confirm_xxnet_exit
2020-06-21 19:47:18.185 [gae_proxy][DEBUG] network IPv4 is ok, cost:154 ms
2020-06-21 19:47:18.239 [launcher][ERROR] start module gae_proxy fail:module 'OpenSSL' has no attribute 'SSL'
2020-06-21 19:47:18.246 [launcher][ERROR] Except stack:Traceback (most recent call last):
  File "/mnt/sda3/XX-Net-4.0.5/code/default/launcher/module_init.py", line 44, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local'], 0)
  File "/mnt/sda3/XX-Net-4.0.5/code/default/gae_proxy/local/__init__.py", line 2, in <module>
    from . import apis
  File "/mnt/sda3/XX-Net-4.0.5/code/default/gae_proxy/local/apis.py", line 2, in <module>
    from .front import front, direct_front
  File "/mnt/sda3/XX-Net-4.0.5/code/default/gae_proxy/local/front.py", line 12, in <module>
    from front_base.connect_creator import ConnectCreator
  File "/mnt/sda3/XX-Net-4.0.5/code/default/lib/noarch/front_base/connect_creator.py", line 7, in <module>
    SSLError = OpenSSL.SSL.WantReadError
AttributeError: module 'OpenSSL' has no attribute 'SSL'

2020-06-21 19:47:18.247 [launcher][ERROR] launcher except:AttributeError("module 'OpenSSL' has no attribute 'SSL'")
2020-06-21 19:47:18.251 [launcher][ERROR] Except stack:Traceback (most recent call last):
  File "code/default/launcher/start.py", line 253, in <module>
  File "code/default/launcher/start.py", line 232, in main
  File "/mnt/sda3/XX-Net-4.0.5/code/default/launcher/module_init.py", line 121, in start_all_auto
    start(module)
  File "/mnt/sda3/XX-Net-4.0.5/code/default/launcher/module_init.py", line 44, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local'], 0)
  File "/mnt/sda3/XX-Net-4.0.5/code/default/gae_proxy/local/__init__.py", line 2, in <module>
    from . import apis
  File "/mnt/sda3/XX-Net-4.0.5/code/default/gae_proxy/local/apis.py", line 2, in <module>
    from .front import front, direct_front
  File "/mnt/sda3/XX-Net-4.0.5/code/default/gae_proxy/local/front.py", line 12, in <module>
    from front_base.connect_creator import ConnectCreator
  File "/mnt/sda3/XX-Net-4.0.5/code/default/lib/noarch/front_base/connect_creator.py", line 7, in <module>
    SSLError = OpenSSL.SSL.WantReadError
AttributeError: module 'OpenSSL' has no attribute 'SSL'

**Comment by 2378** [comment]
查了，py3.4.3不支持openssl1.1 
不想自己编译lede，就搞个旁路由，方便，玩法还多

**Comment by zhujun99170** [comment]
> 查了，py3.4.3不支持openssl1.1
> 不想自己编译lede，就搞个分割由，方便，玩法还多

安装的python3是3.8.3版本。

**Comment by 2378** [comment]
这就得问X大了
我很久没升级lede，还在3.4，差事都叫nas干了

![捕获333](https://user-images.githubusercontent.com/24506320/85293480-f8958580-b4cf-11ea-901c-97489c747b13.PNG)

**Comment by zhujun99170** [comment]
解决了，安装了最新的libffi就好了。

**Comment by 2378** [comment]
跑起来卡不卡？ 当年拿Atom D2550带全网，2pc、2mobile，已经明显影响nat转发了

**Comment by zhujun99170** [comment]
> 跑起来卡不卡？ 当年拿Atom D2550带全网，2pc、2mobile，已经明显影响nat转发了

我是当旁路由用，目前运行稳定。

**Comment by 2badao** [comment]
> 解决了，安装了最新的libffi就好了。

朋友，给个教程吧，先谢了！

**Comment by zhujun99170** [comment]
> > 解决了，安装了最新的libffi就好了。
> 
> 朋友，给个教程吧，先谢了！

openwrt的安装参见https://github.com/XX-net/XX-Net/wiki/OpenWrt-Config；python3的安装我是运行opkg update;opkg install python3  python3-openssl python3-pyopenssl;安装后运行如果也出现类似我上面的错误提示，就运行update install libffi，我安装的libffi是3.3-2版本。

**Comment by 2badao** [comment]
> > > 解决了，安装了最新的libffi就好了。
> > 
> > 
> > 朋友，给个教程吧，先谢了！
> 
> openwrt下的安装参见https://github.com/XX-net/XX-Net/wiki/OpenWrt-Config ； python3的安装我是运行opkg update;opkg install python3 python3-openssl python3-pyopenssl;安装后运行如果也出现类似我上面的错误提示，就运行opkg install libffi，我安装的libffi是3.3-2版本。

谢谢指教，安装成功。但是
IP6状态Fail
CA 证书状态(下载) | Fail
这怎么解决？

**Comment by zhujun99170** [comment]
> > > > 解决了，安装了最新的libffi就好了。
> > > 
> > > 
> > > 朋友，给个教程吧，先谢了！
> > 
> > 
> > openwrt下的安装参见https://github.com/XX-net/XX-Net/wiki/OpenWrt-Config ； python3的安装我是运行opkg update;opkg install python3 python3-openssl python3-pyopenssl;安装后运行如果也出现类似我上面的错误提示，就运行opkg install libffi，我安装的libffi是3.3-2版本。
> 
> 谢谢指教，安装成功。但是
> IP6状态Fail
> CA 证书状态(下载) | Fail
> 这怎么解决？

是用chrome浏览器SwitchyOmega插件设置了吗？
