### ISSUE TITLE
X-tunnel登录失败

### ISSUE THREAD

**Issue by fx606** [XX-net/XX-Net#13253]
X-tunnel一直处于“登录中。。。”，无法进入
2020-06-20 08:03:12.516 - [INFO] load D:\XX-net\data\x_tunnel\cloudflare_domains.json success

2020-06-20 08:03:12.516 - [INFO] SSL use version:TLSv1_2

2020-06-20 08:03:12.516 - [INFO] OpenSSL support alpn

2020-06-20 08:03:12.516 - [INFO] load ip range file:D:\XX-net\code\default\x_tunnel\local\cloudflare_front\ip_range.txt

2020-06-20 08:03:12.516 - [INFO] load ip_list num:49, target num:49

2020-06-20 08:03:13.312 - [ERROR] updated cloudflare front domains from github fail:ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)

2020-06-20 08:03:13.453 - [ERROR] Except stack:Traceback (most recent call last): File "D:\XX-net\code\default\x_tunnel\local\cloudflare_front\host_manager.py", line 69, in update_front_domains response = client.request("GET", url) File "D:\XX-net\code\default\lib\noarch\simple_http_client.py", line 459, in request sock = ssl.wrap_socket(sock) File "D:\XX-net\python3.8.2\lib\ssl.py", line 1405, in wrap_socket return context.wrap_socket( File "D:\XX-net\python3.8.2\lib\ssl.py", line 500, in wrap_socket return self.sslsocket_class._create( File "D:\XX-net\python3.8.2\lib\ssl.py", line 1040, in _create self.do_handshake() File "D:\XX-net\python3.8.2\lib\ssl.py", line 1309, in do_handshake self._sslobj.do_handshake() ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

2020-06-20 08:03:14.163 - [DEBUG] create_ssl update ip:162.159.135.30 time:583 h2:1 sni:sacramen.tk, host:sacramen.tk

2020-06-20 08:03:19.631 - [WARNING] task POST center.xx-net.net /login timeout

2020-06-20 08:03:19.631 - [WARNING] req /login get response timeout

2020-06-20 08:03:23.841 - [WARNING] task POST center.xx-net.net /login timeout

2020-06-20 08:03:23.841 - [WARNING] POST center.sacramen.tk/login status:520 trace:0:start_request,0:get_task(7),0:get_worker(0):162.159.135.30,0:h2_req,0:start send header,0:start send left body,0:end send left body,2194:h2_get_head,0:get_response,:0

2020-06-20 08:03:29.875 - [WARNING] task POST center.xx-net.net /login timeout

2020-06-20 08:03:29.875 - [WARNING] req /login get response timeout

**Comment by kwwgh** [comment]
俺也一样！

**Comment by kwwgh** [comment]
楼主，我的好的，你把XXnet退出然后重启试一下。

**Comment by fx606** [comment]
升到4.1.2解决了

**Comment by odin1314** [comment]
x-tunnel 忘记密码怎么找回

**Comment by xxnet** [comment]
用x-tunnel的注册邮件给xxnet.dev@gmail.com 发邮件

**Comment by odin1314** [comment]
thanks

**Comment by fanmingming** [comment]
我也是，手机刷国外ROM了，必须验证Google然后开机有很多Play商店的应用需要更新，更新到一半就直接提示登录失败：status:602！问题是我是付了费的！

**Comment by xxnet** [comment]
看来墙又高了，我这几天做个改进
