### ISSUE TITLE
except errno.EAGAIN: TypeError: catching classes that do not inherit from BaseException is not allowed

### ISSUE THREAD

**Issue by cym104** [XX-net/XX-Net#13270]
2020-06-30 22:58:25.712 - [ERROR] 2404:6800:4009:80d::2014 _consume_single_frame:TypeError('catching classes that do not inherit from BaseException is not allowed'), inactive time:17

2020-06-30 22:58:25.721 - [ERROR] Except stack:Traceback (most recent call last): File "D:\Program Files (x86)\XX-Net\code\4.1.2\lib\noarch\front_base\openssl_wrap.py", line 270, in recv_into ret = self.__iowait(self._connection.recv_into, buf, nbytes) File "D:\Program Files (x86)\XX-Net\code\**4.1.2**\lib\noarch\front_base\openssl_wrap.py", line 207, in __iowait raise e File "D:\Program Files (x86)\XX-Net\code\4.1.2\lib\noarch\front_base\openssl_wrap.py", line 175, in __iowait return io_func(*args, **kwargs) File "D:\Program Files (x86)\XX-Net\python3.8.2\lib\OpenSSL\SSL.py", line 1840, in recv_into self._raise_ssl_error(self._ssl, result) File "D:\Program Files (x86)\XX-Net\python3.8.2\lib\OpenSSL\SSL.py", line 1671, in _raise_ssl_error _raise_current_error() File "D:\Program Files (x86)\XX-Net\python3.8.2\lib\OpenSSL\_util.py", line 54, in exception_from_error_queue raise exception_type(errors) OpenSSL.SSL.Error: [('SSL routines', 'ssl3_read_bytes', 'sslv3 alert bad record mac')] **During handling of the above exception, another exception occurred**: Traceback (most recent call last): File "D:\Program Files (x86)\XX-Net\code\4.1.2\lib\noarch\front_base\http2_connection.py", line 309, in _consume_single_frame header = self._sock.recv(9) File "D:\Program Files (x86)\XX-Net\code\4.1.2\lib\noarch\hyper\common\bufsocket.py", line 221, in recv count = self._sck.recv_into(self._buffer_view[self._buffer_end:]) File "D:\Program Files (x86)\XX-Net\code\4.1.2\lib\noarch\front_base\openssl_wrap.py", line 279, in recv_into except errno.EAGAIN: TypeError: catching classes that do not inherit from BaseException is not allowed

2020-06-30 22:58:25.721 - [WARNING] 2404:6800:4009:80d::2014 close, reason: ConnectionReset:TypeError('catching classes that do not inherit from BaseException is not allowed'), trace: continue_timeout:0, processed:0, h2.stream_num:0, sni:None, host:********.appspot.com

**Comment by xxnet** [comment]
收到
