### ISSUE TITLE
电脑断电重启后xx-net无法启动。

### ISSUE THREAD

**Issue by bohemianalfred** [XX-net/XX-Net#13288]
昨天停电导致用着一半关机。今天启动后发现xx-net无法运行了。查了一下加载的log，显示下列内容：

2020-07-13 22:32:50.282 - [ERROR] uncaught Exception, type=<class 'json.decoder.JSONDecodeError'> value=Expecting value: line 1 column 1 (char 0) traceback:Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\XX-Net\code\default\launcher\start.py", line 128, in <module>
    from  win_tray import sys_tray
  File "C:\Users\Administrator\Desktop\XX-Net\code\default\launcher\win_tray.py", line 19, in <module>
    import module_init
  File "C:\Users\Administrator\Desktop\XX-Net\code\default\launcher\module_init.py", line 5, in <module>
    from config import config
  File "C:\Users\Administrator\Desktop\XX-Net\code\default\launcher\config.py", line 73, in <module>
    config.load()
  File "C:\Users\Administrator\Desktop\XX-Net\code\default\lib\noarch\xconfig.py", line 29, in load
    self.file_config = json.loads(content)
  File "C:\Users\Administrator\Desktop\XX-Net\python3.8.2\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Administrator\Desktop\XX-Net\python3.8.2\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Administrator\Desktop\XX-Net\python3.8.2\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

哪位老大能帮忙分析一下是什么原因吗，多谢。

**Comment by bohemianalfred** [comment]
已经解决了，config文件损坏了。

**Comment by bohemianalfred** [comment]
已经解决了，config文件损坏了。
