### ISSUE TITLE
4.4版本设置全局通过智能路由代理或者智能pac代理，只能在chrome里面打开网页，在edge浏览器里面打不开网页

### ISSUE THREAD

**Issue by watershao** [XX-net/XX-Net#13325]
从4.0版本开始到4.4版本，设置全局通过智能路由代理或者智能pac代理，只能在chrome里面打开网页，在edge浏览器里面打不开网页，会报错，

当前无法使用此页面
fund.eastmoney.com 未发送任何数据。
ERR_EMPTY_RESPONSE

目前3.16.1版本设置智能路由代理可以在edge里面打开网页，或者是在4.0及以上版本里面取消全局代理和全局通过GAEProxy代理，可以在edge里面打开网页，希望能修复一下，谢谢

**Comment by xxnet** [comment]
Windows10 Pro 没有重现你遇到的问题

**Comment by watershao** [comment]
我的也是win10 的，那有什么办法恢复好吗？

**Comment by watershao** [comment]
2020-08-07 23:10:56.103 - [DEBUG] connect to newspush.sinajs.cn:443 from:127.0.0.1:57364

2020-08-07 23:10:56.104 - [INFO] block advertisement newspush.sinajs.cn:443

2020-08-07 23:10:56.105 - [DEBUG] connect to newspush.sinajs.cn:443 from:127.0.0.1:57365

2020-08-07 23:10:56.105 - [INFO] block advertisement newspush.sinajs.cn:443

2020-08-07 23:10:57.111 - [DEBUG] connect to newspush.sinajs.cn:443 from:127.0.0.1:57369

2020-08-07 23:10:57.111 - [INFO] block advertisement newspush.sinajs.cn:443

2020-08-07 23:10:57.113 - [DEBUG] connect to newspush.sinajs.cn:443 from:127.0.0.1:57371

2020-08-07 23:10:57.113 - [INFO] block advertisement newspush.sinajs.cn:443

2020-08-07 23:10:59.104 - [DEBUG] connect to newspush.sinajs.cn:443 from:127.0.0.1:57374

2020-08-07 23:10:59.104 - [INFO] block advertisement newspush.sinajs.cn:443

2020-08-07 23:10:59.107 - [DEBUG] connect to newspush.sinajs.cn:443 from:127.0.0.1:57375

2020-08-07 23:10:59.107 - [INFO] block advertisement newspush.sinajs.cn:443

2020-08-07 23:11:00.255 - [WARNING] DnsOverTlsQuery wrap_socket fail AttributeError("'NoneType' object has no attribute 'getsockopt'")

2020-08-07 23:11:00.255 - [WARNING] query_over_tcp webquotepic.trafficmanager.cn. type:1 connect fail.

2020-08-07 23:11:06.766 - [DEBUG] domain host:bdstatics.eastmoney.com:443 try gae, GetReqTimeout:65560

2020-08-07 23:11:06.770 - [DEBUG] http ('127.0.0.1', 57380) connect to fund.eastmoney.com:80 GET /daogou/

2020-08-07 23:11:06.770 - [DEBUG] connect to fund.eastmoney.com:80 from:127.0.0.1:57380

2020-08-07 23:11:06.773 - [DEBUG] connect to bdstatics.eastmoney.com:443 from:127.0.0.1:57383

2020-08-07 23:11:06.793 - [DEBUG] host:fund.eastmoney.com:80 direct connect fund.eastmoney.com.cdn.dnsv1.com. success

2020-08-07 23:11:06.793 - [INFO] domain fund.eastmoney.com:80 direct6

2020-08-07 23:11:06.852 - [DEBUG] Dns Tcp bdstatics.eastmoney.com return ['bdstatics.eastmoney.com.wsglb0.com.', '183.6.248.88', '183.6.248.87'] t:0.073950

2020-08-07 23:11:06.870 - [DEBUG] pipe close [127.0.0.1]:57380->b'fund.eastmoney.com'[b'fund.eastmoney.com.cdn.dnsv1.com.']:80 run_time:0 upload:0,0 download:0,0, by remote:0, left:0 e:'r'

2020-08-07 23:11:06.872 - [DEBUG] http ('127.0.0.1', 57381) connect to fund.eastmoney.com:80 GET /daogou/

2020-08-07 23:11:06.872 - [DEBUG] connect to fund.eastmoney.com:80 from:127.0.0.1:57381

2020-08-07 23:11:06.882 - [DEBUG] host:fund.eastmoney.com:80 direct connect fund.eastmoney.com.cdn.dnsv1.com. success

2020-08-07 23:11:06.882 - [INFO] domain fund.eastmoney.com:80 direct6

2020-08-07 23:11:06.978 - [DEBUG] pipe close [127.0.0.1]:57381->b'fund.eastmoney.com'[b'fund.eastmoney.com.cdn.dnsv1.com.']:80 run_time:0 upload:0,0 download:0,0, by remote:0, left:0 e:'r'

2020-08-07 23:11:06.982 - [DEBUG] http ('127.0.0.1', 57392) connect to fund.eastmoney.com:80 GET /daogou/

2020-08-07 23:11:06.982 - [DEBUG] connect to fund.eastmoney.com:80 from:127.0.0.1:57392

2020-08-07 23:11:07.010 - [DEBUG] host:fund.eastmoney.com:80 direct connect fund.eastmoney.com.cdn.dnsv1.com. success

2020-08-07 23:11:07.010 - [INFO] domain fund.eastmoney.com:80 direct6

2020-08-07 23:11:07.087 - [DEBUG] pipe close [127.0.0.1]:57392->b'fund.eastmoney.com'[b'fund.eastmoney.com.cdn.dnsv1.com.']:80 run_time:0 upload:0,0 download:0,0, by remote:0, left:0 e:'r'

2020-08-07 23:11:07.110 - [DEBUG] connect to newspush.sinajs.cn:443 from:127.0.0.1:57394

2020-08-07 23:11:07.111 - [INFO] block advertisement newspush.sinajs.cn:443

2020-08-07 23:11:07.113 - [DEBUG] connect to newspush.sinajs.cn:443 from:127.0.0.1:57395

2020-08-07 23:11:07.113 - [INFO] block advertisement newspush.sinajs.cn:443

2020-08-07 23:11:08.112 - [DEBUG] connect to newspush.sinajs.cn:443 from:127.0.0.1:57397

2020-08-07 23:11:08.112 - [INFO] block advertisement newspush.sinajs.cn:443

2020-08-07 23:11:08.118 - [DEBUG] connect to newspush.sinajs.cn:443 from:127.0.0.1:57398

2020-08-07 23:11:08.118 - [INFO] block advertisement newspush.sinajs.cn:443

2020-08-07 23:11:11.124 - [DEBUG] connect to newspush.sinajs.cn:443 from:127.0.0.1:57402

2020-08-07 23:11:11.124 - [INFO] block advertisement newspush.sinajs.cn:443

2020-08-07 23:11:11.126 - [DEBUG] connect to newspush.sinajs.cn:443 from:127.0.0.1:57403

2020-08-07 23:11:11.126 - [INFO] block advertisement newspush.sinajs.cn:443

2020-08-07 23:11:12.991 - [DEBUG] query by udp, bdstatics.eastmoney.com.wsglb0.com. cost:3.066974, return:[]

2020-08-07 23:11:13.090 - [DEBUG] Dns Tcp bdstatics.eastmoney.com return ['bdstatics.eastmoney.com.wsglb0.com.'] t:0.095624

2020-08-07 23:11:14.181 - [DEBUG] host:bdstatics.eastmoney.com:443 direct connect bdstatics.eastmoney.com.wsglb0.com. success

2020-08-07 23:11:14.182 - [INFO] domain bdstatics.eastmoney.com:443 direct6

2020-08-07 23:11:15.581 - [WARNING] DnsOverTlsQuery wrap_socket fail AttributeError("'NoneType' object has no attribute 'getsockopt'")

2020-08-07 23:11:15.582 - [WARNING] query_over_tcp bdstatics.eastmoney.com type:28 connect fail.

2020-08-07 23:11:18.113 - [DEBUG] connect to newspush.sinajs.cn:443 from:127.0.0.1:57412

2020-08-07 23:11:18.113 - [INFO] block advertisement newspush.sinajs.cn:443

2020-08-07 23:11:18.117 - [DEBUG] connect to newspush.sinajs.cn:443 from:127.0.0.1:57413

2020-08-07 23:11:18.117 - [INFO] block advertisement newspush.sinajs.cn:443

2020-08-07 23:11:19.908 - [ERROR] DnsOverHttpsQuery query fail:AttributeError("'NoneType' object has no attribute 'getsockopt'")

2020-08-07 23:11:19.911 - [ERROR] Except stack:Traceback (most recent call last): File "D:\Program Files (x86)\XX-Net\code\4.4.2\smart_router\local\dns_query.py", line 418, in query r = client.request("POST", url, headers={"accept": "application/dns-message", File "D:\Program Files (x86)\XX-Net\code\4.4.2\lib\noarch\simple_http_client.py", line 469, in request sock = self.connect(upl.hostname, port, upl.scheme == b"https") File "D:\Program Files (x86)\XX-Net\code\4.4.2\lib\noarch\simple_http_client.py", line 437, in connect sock = ssl.wrap_socket(sock) File "D:\Program Files (x86)\XX-Net\python3.8.2\lib\ssl.py", line 1405, in wrap_socket return context.wrap_socket( File "D:\Program Files (x86)\XX-Net\python3.8.2\lib\ssl.py", line 500, in wrap_socket return self.sslsocket_class._create( File "D:\Program Files (x86)\XX-Net\python3.8.2\lib\ssl.py", line 987, in _create if sock.getsockopt(SOL_SOCKET, SO_TYPE) != SOCK_STREAM: AttributeError: 'NoneType' object has no attribute 'getsockopt'

2020-08-07 23:11:19.971 - [WARNING] DnsOverTlsQuery wrap_socket fail AttributeError("'NoneType' object has no attribute 'getsockopt'")

2020-08-07 23:11:19.971 - [WARNING] query_over_tcp bdstatics.eastmoney.com.wsglb0.com. type:1 connect fail.

2020-08-07 23:11:20.116 - [DEBUG] connect to newspush.sinajs.cn:443 from:127.0.0.1:57417

2020-08-07 23:11:20.116 - [INFO] block advertisement newspush.sinajs.cn:443

2020-08-07 23:11:20.118 - [DEBUG] connect to newspush.sinajs.cn:443 from:127.0.0.1:57418

2020-08-07 23:11:20.118 - [INFO] block advertisement newspush.sinajs.cn:443

报错日志

版本信息


XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.19041-SP0
os-system: Windows
os-version: 10.0.19041
os-release: 10
os-detail: Version:10-0; Build:19041; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36
xxnet-version: 4.4.2
python-version: 3.8.2
openssl-version: OpenSSL 1.1.1d  10 Sep 2019 TLSv1_3 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:94 ipv4:0 ipv6:6
ipv4-status: OK
ipv6-status: OK
connected-link: new:0
worker: h1:0 h2:1
scan-ip-thread-num: 5
ip-quality: 1508
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by xxnet** [comment]
GFW把 DNS-over-https和DNS-over-TLS都封了，要改改才行。
你先用别的模式，Chrome能用最好用Chrome

**Comment by watershao** [comment]
> GFW把 DNS-over-https和DNS-over-TLS都封了，要改改才行。 你先用别的模式，Chrome能用最好用Chrome

好的，谢谢
