### ISSUE TITLE
【求助】XX-net无法启动

### ISSUE THREAD

**Issue by tennyee** [XX-net/XX-Net#13347]
XX-net无法启动；使用的是4.4.2的最新版本，之前4.2的时候就是这样，今天更新后一样还是不行启动软件
运行内容如下：
2020-08-18 10:26:34.876 [launcher][INFO] use build-in openssl lib
2020-08-18 10:26:35.146 [launcher][INFO] start XX-Net 4.4.2
2020-08-18 10:26:35.147 [launcher][DEBUG] start confirm_xxnet_exit
2020-08-18 10:26:37.220 [launcher][DEBUG] good, xxnet:8085 clear!
2020-08-18 10:26:37.222 [launcher][DEBUG] finished confirm_xxnet_exit
2020-08-18 10:26:39.570 [gae_proxy][DEBUG] network IPv4 is ok, cost:271 ms
2020-08-18 10:26:39.691 [gae_proxy][INFO] ------------------------------------------------------
2020-08-18 10:26:39.691 [gae_proxy][INFO] Python Version     : 3.8.2
2020-08-18 10:26:39.692 [gae_proxy][INFO] OS                 : Version:10-0; Build:18362; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
2020-08-18 10:26:39.692 [gae_proxy][INFO] Listen Address     : 127.0.0.1:8087
2020-08-18 10:26:39.693 [gae_proxy][INFO] GAE APPID          : tennyee01|tennyee02|tennyee03|tennyee11|tennyee12
2020-08-18 10:26:39.693 [gae_proxy][INFO] ------------------------------------------------------
2020-08-18 10:26:39.735 [gae_proxy][DEBUG] Importing CA
2020-08-18 10:26:39.736 [gae_proxy][DEBUG] Begin to import Windows CA
2020-08-18 10:26:39.748 [gae_proxy][DEBUG] XX-Net CA already exists
2020-08-18 10:26:39.750 [gae_proxy][INFO] SSL use version:TLSv1_3
2020-08-18 10:26:39.759 [gae_proxy][INFO] OpenSSL support alpn
2020-08-18 10:26:39.762 [gae_proxy][INFO] load ip range file:D:\Program Files\XX-Net-3.2.7\code\default\gae_proxy\local\ip_range.txt
2020-08-18 10:26:39.807 [gae_proxy][INFO] load ip_list num:1000, target num:1000
2020-08-18 10:26:39.838 [gae_proxy][INFO] SSL use version:TLSv1_3
2020-08-18 10:26:39.842 [gae_proxy][INFO] server 127.0.0.1:8087 started.
2020-08-18 10:26:39.897 [launcher][INFO] module gae_proxy started
2020-08-18 10:26:39.898 [launcher][INFO] start gae_proxy time cost:2653 ms
WARNING:root:Load Crypto.Cipher.ARC4 Failed, Use Pure Python Instead.
2020-08-18 10:26:39.952 [tls_relay][INFO] SSL use version:TLSv1_3
2020-08-18 10:26:39.953 [tls_relay][INFO] OpenSSL support alpn
2020-08-18 10:26:39.970 [x_tunnel][INFO] use config_path:D:\Program Files\XX-Net-3.2.7\data\x_tunnel\client.json
2020-08-18 10:26:39.971 [x_tunnel][INFO] X-Tunnel window:16777216
2020-08-18 10:26:39.986 [cloudflare_front][INFO] load D:\Program Files\XX-Net-3.2.7\data\x_tunnel\cloudflare_domains.json success
2020-08-18 10:26:39.991 [cloudflare_front][INFO] SSL use version:TLSv1_3
2020-08-18 10:26:40.000 [cloudflare_front][INFO] OpenSSL support alpn
2020-08-18 10:26:40.001 [cloudflare_front][INFO] load ip range file:D:\Program Files\XX-Net-3.2.7\code\default\x_tunnel\local\cloudflare_front\ip_range.txt
Exception in thread Thread-41:
Traceback (most recent call last):
  File "D:\Program Files\XX-Net-3.2.7\python3.8.2\lib\threading.py", line 932, in _bootstrap_inner
2020-08-18 10:26:40.013 [cloudflare_front][ERROR] updated cloudflare front domains from github fail:AttributeError("'NoneType' object has no attribute 'getsockopt'")
    self.run()
  File "D:\Program Files\XX-Net-3.2.7\python3.8.2\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Program Files\XX-Net-3.2.7\code\default\x_tunnel\local\__init__.py", line 14, in start
    client.main(args)
  File "D:\Program Files\XX-Net-3.2.7\code\default\x_tunnel\local\client.py", line 146, in main
    front_dispatcher.init()
  File "D:\Program Files\XX-Net-3.2.7\code\default\x_tunnel\local\front_dispatcher.py", line 23, in init
2020-08-18 10:26:40.060 [cloudflare_front][ERROR] Except stack:Traceback (most recent call last):
  File "D:\Program Files\XX-Net-3.2.7\code\default\x_tunnel\local\cloudflare_front\host_manager.py", line 69, in update_front_domains
    response = client.request("GET", url)
  File "D:\Program Files\XX-Net-3.2.7\code\default\lib\noarch\simple_http_client.py", line 469, in request
    sock = self.connect(upl.hostname, port, upl.scheme == b"https")
  File "D:\Program Files\XX-Net-3.2.7\code\default\lib\noarch\simple_http_client.py", line 437, in connect
    sock = ssl.wrap_socket(sock)
  File "D:\Program Files\XX-Net-3.2.7\python3.8.2\lib\ssl.py", line 1405, in wrap_socket
    return context.wrap_socket(
  File "D:\Program Files\XX-Net-3.2.7\python3.8.2\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "D:\Program Files\XX-Net-3.2.7\python3.8.2\lib\ssl.py", line 987, in _create
    if sock.getsockopt(SOL_SOCKET, SO_TYPE) != SOCK_STREAM:
AttributeError: 'NoneType' object has no attribute 'getsockopt'

    from .cloudflare_front.front import front as cloudflare_front
  File "D:\Program Files\XX-Net-3.2.7\code\default\x_tunnel\local\cloudflare_front\__init__.py", line 2, in <module>
    from .front import front
  File "D:\Program Files\XX-Net-3.2.7\code\default\x_tunnel\local\cloudflare_front\front.py", line 121, in <module>
    front = Front()
  File "D:\Program Files\XX-Net-3.2.7\code\default\x_tunnel\local\cloudflare_front\front.py", line 51, in __init__
    self.ip_manager = IpManager(
  File "D:\Program Files\XX-Net-3.2.7\code\default\lib\noarch\front_base\ip_manager.py", line 84, in __init__
    self.reset()
  File "D:\Program Files\XX-Net-3.2.7\code\default\lib\noarch\front_base\ip_manager.py", line 135, in reset
    self.load_ip()
  File "D:\Program Files\XX-Net-3.2.7\code\default\lib\noarch\front_base\ip_manager.py", line 164, in load_ip
    lines = fd.readlines()
UnicodeDecodeError: 'gbk' codec can't decode byte 0xf8 in position 0: illegal multibyte sequence
2020-08-18 10:28:07.349 [gae_proxy][WARNING] network IPv6 fail

* X-Tunnel 支付后流量未及时到帐请直接向 xxnet.dev@gmail.com 发邮件，并附上帐号、交易单号等详细信息。

* 是否试过[最新的版本](https://github.com/XX-net/XX-Net/releases )？

* 是否查看过 [Wiki](https://github.com/XX-net/XX-Net/wiki )？

* 是否以相关关键词搜索过类似 issues？

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志，如包含大量文本时，请上传为 txt 文件：

* 如果问题得到解决，请务必回复相关情况，谢谢。

* 即使最终无法解决你遇到的问题，这也是正常的，因为系统和网络环境千差万别。最终结果也能帮助到后来者，请保持正常交流，再寻它法。

* 请不要只写标题，不写内容，不遵守规则的提问会被自动关闭。

**Comment by xxnet** [comment]
可能之前导入的ip有中文符号，可以简单的删除 data目录重新扫描

**Comment by tennyee** [comment]
> 可能之前导入的ip有中文符号，可以简单的删除 data目录重新扫描

此问题已经解决！只是全部删除了IP清空了。。。
