### ISSUE TITLE
分享707个good ip

### ISSUE THREAD

**Issue by miketwes** [XX-net/XX-Net#13363]
其中大多数都是 @XX-Net 找出来的, 详见: [ good_ip.txt](https://github.com/miketwes/XX-Net-mini/blob/master/data/gae_proxy/good_ip.txt)

**Comment by duxingxia081** [comment]
怎么导入

**Comment by lefantian** [comment]
ip 倒是有，就是都坚持不了10分钟

**Comment by miketwes** [comment]
> 怎么导入

good_ip.txt  的路径: XX-Net/data/gae_proxy/good_ip.txt

**Comment by miketwes** [comment]
> ip 倒是有，就是都坚持不了10分钟

掉ip的问题, [mini版本的XX-Net](https://github.com/miketwes/XX-Net-mini)已解决, mini版去掉了扫描和删除ip的功能, 直接持久使用707个ip.

**Comment by qianniansha** [comment]
> 
> 
> > ip 倒是有，就是都坚持不了10分钟
> 
> 掉ip的问题, [mini版本的XX-Net](https://github.com/miketwes/XX-Net-mini)已解决, mini版去掉了扫描和删除ip的功能, 直接持久使用707个ip.

mini版下载地址在哪？没找着啊

**Comment by miketwes** [comment]
> > > ip 倒是有，就是都坚持不了10分钟
> > 
> > 
> > 掉ip的问题, [mini版本的XX-Net](https://github.com/miketwes/XX-Net-mini)已解决, mini版去掉了扫描和删除ip的功能, 直接持久使用707个ip.
> 
> mini版下载地址在哪？没找着啊

[https://github.com/miketwes/XX-Net-mini/archive/4.5.1.zip](https://github.com/miketwes/XX-Net-mini/archive/4.5.1.zip)

**Comment by 234jiao** [comment]
mini的 怎么用呀

**Comment by miketwes** [comment]
> mini的 怎么用呀

 1.  用pip安装相关模块
pip install hpack hyper cryptography pyasn1 dnslib hyperframe PySocks PyOpenSSL

 2. 下载或克隆XX-Net-mini

 3.  Linux用户: 
cd XX-Net-mini/code/default/launcher/ && python3 start.py
 Windows用户:
cd XX-Net-mini\code\default\launcher && python start.py

**Comment by 55kai-niubi** [comment]
说实话真的看不懂...我下载了Python，然后用cmd进入pip安装后显示

Using legacy 'setup.py install' for dnslib, since package 'wheel' is not installed.
Installing collected packages: hpack, enum34, hyperframe, h2, hyper, ipaddress, six, pycparser, cffi, cryptography, pyas
n1, dnslib, PySocks, PyOpenSSL
    Running setup.py install for dnslib ... done
ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will chang
e the way that it resolves dependency conflicts.

We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the defau
lt.

hyper 0.7.0 requires hyperframe<4.0,>=3.2, but you'll have hyperframe 5.2.0 which is incompatible.
Successfully installed PyOpenSSL-19.1.0 PySocks-1.7.1 cffi-1.14.2 cryptography-3.1 dnslib-0.9.14 enum34-1.1.10 h2-2.6.2
hpack-3.0.0 hyper-0.7.0 hyperframe-5.2.0 ipaddress-1.0.23 pyasn1-0.4.8 pycparser-2.20 six-1.15.0

头很大..看不懂

**Comment by miketwes** [comment]
> 说实话真的看不懂...我下载了Python，然后用cmd进入pip安装后显示
> 
> Using legacy 'setup.py install' for dnslib, since package 'wheel' is not installed.
> Installing collected packages: hpack, enum34, hyperframe, h2, hyper, ipaddress, six, pycparser, cffi, cryptography, pyas
> n1, dnslib, PySocks, PyOpenSSL
> Running setup.py install for dnslib ... done
> ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will chang
> e the way that it resolves dependency conflicts.
> 
> We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the defau
> lt.
> 
> hyper 0.7.0 requires hyperframe<4.0,>=3.2, but you'll have hyperframe 5.2.0 which is incompatible.
> Successfully installed PyOpenSSL-19.1.0 PySocks-1.7.1 cffi-1.14.2 cryptography-3.1 dnslib-0.9.14 enum34-1.1.10 h2-2.6.2
> hpack-3.0.0 hyper-0.7.0 hyperframe-5.2.0 ipaddress-1.0.23 pyasn1-0.4.8 pycparser-2.20 six-1.15.0
> 
> 头很大..看不懂

提示相关模块都已经安装好了

**Comment by 55kai-niubi** [comment]
> > 说实话真的看不懂...我下载了Python，然后用cmd进入pip安装后显示
> > 由于未安装软件包“ wheel”，因此对dnslib使用旧版“ setup.py install”。
> > 安装收集的软件包：hpack，enum34，hyperframe，h2，hyper，ipaddress，六个，pycparser，cffi，加密，pyas 
> > n1，dnslib，PySocks，PyOpenSSL正在
> > 运行setup.py为dnslib安装... 
> > 错误：2020年10月之后，您可能在安装或更新软件包时遇到错误。这是因为pip将改变
> > 解决依赖冲突的方式。
> > 我们建议您使用--use-feature = 2020-resolver在新的解析器成为默认版本之前测试您的软件包
> > 。
> > hyper 0.7.0需要hyperframe <4.0，> = 3.2，但是您将拥有不兼容的Hyperframe 5.2.0。
> > 成功安装PyOpenSSL-19.1.0 PySocks-1.7.1 cffi-1.14.2 cryptography-3.1 dnslib-0.9.14 enum34-1.1.10 h2-2.6.2 
> > hpack-3.0.0 hyper-0.7.0 hyperframe-5.2.0 ipaddress-1.0.23 pyasn1-0.4.8 pycparser-2.20六-1.15.0
> > 头很大..看不懂
> 
> 提示相关模块都已经安装好了

但是点击start.py，提示
Press Enter to continue...        Network is ok, you can start to surf the internet!
还是上不去网啊

**Comment by miketwes** [comment]
> > > 说实话真的看不懂...我下载了Python，然后用cmd进入pip安装后显示
> > > 由于未安装软件包“ wheel”，因此对dnslib使用旧版“ setup.py install”。
> > > 安装收集的软件包：hpack，enum34，hyperframe，h2，hyper，ipaddress，六个，pycparser，cffi，加密，pyas
> > > n1，dnslib，PySocks，PyOpenSSL正在
> > > 运行setup.py为dnslib安装...
> > > 错误：2020年10月之后，您可能在安装或更新软件包时遇到错误。这是因为pip将改变
> > > 解决依赖冲突的方式。
> > > 我们建议您使用--use-feature = 2020-resolver在新的解析器成为默认版本之前测试您的软件包
> > > 。
> > > hyper 0.7.0需要hyperframe <4.0，> = 3.2，但是您将拥有不兼容的Hyperframe 5.2.0。
> > > 成功安装PyOpenSSL-19.1.0 PySocks-1.7.1 cffi-1.14.2 cryptography-3.1 dnslib-0.9.14 enum34-1.1.10 h2-2.6.2
> > > hpack-3.0.0 hyper-0.7.0 hyperframe-5.2.0 ipaddress-1.0.23 pyasn1-0.4.8 pycparser-2.20六-1.15.0
> > > 头很大..看不懂
> > 
> > 
> > 提示相关模块都已经安装好了
> 
> 但是点击start.py，提示
> Press Enter to continue... Network is ok, you can start to surf the internet!
> 还是上不去网啊

Network is ok, you can start to surf the internet!  Ipv6网络没有问题

可以修改XX-Net/code/default/lib/noarch/xlog.py中的 self.min_level = FATAL 为 self.min_level = NOTSET,就可以看到详细错误信息

**Comment by retmania** [comment]
不会折腾这个，我把这些ip复制到good_ip.txt，然后把这个文件改成只读是不是就行了？要不然确实掉ip有点严重

**Comment by miketwes** [comment]
> 改成只读

没有试过, 应该是不行

**Comment by SophieHub** [comment]
> 不会折腾这个，我把这些ip复制到good_ip.txt，然后把这个文件改成只读是不是就行了？要不然确实掉ip有点严重

可以的，我直接替换XX-Net-4.4.0的good_ip.txt，就重启就可以了用了。

**Comment by SophieHub** [comment]
> > 改成只读
> 
> 没有试过, 应该是不行

谢谢，小白表示只能做到替换重启了，先用着再不行再来请教。

**Comment by tq01o3n** [comment]
XX-NET4.4.3版本,把这些ip复制到good_ip.txt，改成只读,重启,有效ip只有25个,一直"连接尚未建立。" 怎么破?我不会弄mini

**Comment by miketwes** [comment]
网友可试用XX-Net-mini 4.5.2

**Comment by xxnet** [comment]
@miketwes
XX-Net 加个开关，关闭扫描和删除ip的功能怎样？

**Comment by miketwes** [comment]
@xxnet 应该可行

**Comment by 55kai-niubi** [comment]
修改self.min_level = NOTSET过后
打开start.py，显示
2020-09-08 13:49:06.243 [launcher][ERROR] start module gae_proxy fail:No module named 'win_inet_pton'
2020-09-08 13:49:06.246 [launcher][ERROR] Except stack:Traceback (most recent call last):
  File "D:\WWWWWWWWWWWW\XX-Net-mini-4.5.1\code\default\launcher\module_init.py", line 37, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local'], 0)
  File "D:\WWWWWWWWWWWW\XX-Net-mini-4.5.1\code\default\gae_proxy\local\__init__.py", line 2, in <module>
    from . import apis
  File "D:\WWWWWWWWWWWW\XX-Net-mini-4.5.1\code\default\gae_proxy\local\apis.py", line 2, in <module>
    from .front import front, direct_front
  File "D:\WWWWWWWWWWWW\XX-Net-mini-4.5.1\code\default\gae_proxy\local\front.py", line 12, in <module>
    from front_base.connect_creator import ConnectCreator
  File "D:\WWWWWWWWWWWW\XX-Net-mini-4.5.1\code\default\lib\noarch\front_base\connect_creator.py", line 5, in <module>
    import socks
  File "D:\WWWWWWWWWWWW\XX-Net-mini-4.5.1\code\default\lib\noarch\socks.py", line 71, in <module>
    import win_inet_pton
ModuleNotFoundError: No module named 'win_inet_pton'

2020-09-08 13:49:06.247 [launcher][ERROR] launcher except:ModuleNotFoundError("No module named 'win_inet_pton'")
2020-09-08 13:49:06.248 [launcher][ERROR] Except stack:Traceback (most recent call last):
  File "D:\WWWWWWWWWWWW\XX-Net-mini-4.5.1\code\default\launcher\start.py", line 116, in <module>
    main()
  File "D:\WWWWWWWWWWWW\XX-Net-mini-4.5.1\code\default\launcher\start.py", line 108, in main
    module_init.start_all_auto()
  File "D:\WWWWWWWWWWWW\XX-Net-mini-4.5.1\code\default\launcher\module_init.py", line 110, in start_all_auto
    start(module)
  File "D:\WWWWWWWWWWWW\XX-Net-mini-4.5.1\code\default\launcher\module_init.py", line 37, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local'], 0)
  File "D:\WWWWWWWWWWWW\XX-Net-mini-4.5.1\code\default\gae_proxy\local\__init__.py", line 2, in <module>
    from . import apis
  File "D:\WWWWWWWWWWWW\XX-Net-mini-4.5.1\code\default\gae_proxy\local\apis.py", line 2, in <module>
    from .front import front, direct_front
  File "D:\WWWWWWWWWWWW\XX-Net-mini-4.5.1\code\default\gae_proxy\local\front.py", line 12, in <module>
    from front_base.connect_creator import ConnectCreator
  File "D:\WWWWWWWWWWWW\XX-Net-mini-4.5.1\code\default\lib\noarch\front_base\connect_creator.py", line 5, in <module>
    import socks
  File "D:\WWWWWWWWWWWW\XX-Net-mini-4.5.1\code\default\lib\noarch\socks.py", line 71, in <module>
    import win_inet_pton
ModuleNotFoundError: No module named 'win_inet_pton'

Press Enter to continue...        Network is ok, you can start to surf the internet!

**Comment by miketwes** [comment]
XX-Net-mini-4.5.1的版本在XX-Net-mini-4.5.1\code\default\lib\noarch\ 路径下没有socks.py这个文件, 你可试用XX-Net-mini-4.5.2

**Comment by lefantian** [comment]
> XX-Net-mini-4.5.1的版本在XX-Net-mini-4.5.1\code\default\lib\noarch\ 路径下没有socks.py这个文件, 你可试用XX-Net-mini-4.5.2

感谢分享，可这个好像需要点技术，试了半天小白还是很懵圈搞不出来

**Comment by retmania** [comment]
> @miketwes XX-Net 加个开关，关闭扫描和删除ip的功能怎样？

资瓷！

**Comment by ahhh111222** [comment]
> 不会折腾这个，我把这些ip复制到good_ip.txt，然后把这个文件改成只读是不是就行了？要不然确实掉ip有点严重

python3.85装好后，运行python3是3.85,运行python是2.7
不敢删python2.7因为有好多依赖，
不敢该python指向3.85,怕有问题
这样可行吗
图上所示
pip list 是python 2.7
python3 start.py,是3.85
这样可行吗
是否应该pip3 list对应起来

**Comment by ahhh111222** [comment]
> > 但是点击start.py，提示
> > Press Enter to continue... Network is ok, you can start to surf the internet!
> > 还是上不去网啊
> 
> Network is ok, you can start to surf the internet! Ipv6网络没有问题
> 
> 模块安装好以后是以下模块:
> 
> ```
>  pip install hyper PyOpenSSL dnslib PySocks     
>  pip list  
>  Package      Version
>  ------------ -------
>  cffi         1.14.2
>  cryptography 3.1
>  dnslib       0.9.14
>  h2           2.6.2
>  hpack        3.0.0
>  hyper        0.7.0
>  hyperframe   3.2.0
>  pip          20.2.2
>  pycparser    2.20
>  pyOpenSSL    19.1.0
>  PySocks      1.7.1
>  setuptools   47.1.0
>  six          1.15.0
> ```
> 
> 可以修改XX-Net/code/default/lib/noarch/xlog.py中的 self.min_level = FATAL 为 self.min_level = NOTSET,就可以看到详细错误信息
> 
> 正常运行截图:
> Linux:
> 
> ![l1](https://user-images.githubusercontent.com/6849681/91863827-1a667200-eca2-11ea-81cb-d899bed2394f.png)
> 
> Windows:
> 
> ![w1](https://user-images.githubusercontent.com/6849681/91863873-26eaca80-eca2-11ea-82d1-b1c847d0a18f.png)
python3.85装好后，运行python3是3.85,运行python是2.7
不敢删python2.7因为有好多依赖，
不敢该python指向3.85,怕有问题
这样可行吗
图上所示
pip list 是python 2.7
python3 start.py,是3.85
这样可行吗
是否应该pip3 list对应起来

**Comment by miketwes** [comment]
> python3 start.py,是3.85
> 这样可行吗

python3 start.py,是3.85 这样可行, 建议看一下更新的安装说明[https://github.com/miketwes/XX-Net-mini](https://github.com/miketwes/XX-Net-mini)

**Comment by ahhh111222** [comment]
> > python3 start.py,是3.85
> > 这样可行吗
> 
> python3 start.py,是3.85 这样可行, 建议看一下更新的安装说明https://github.com/miketwes/XX-Net-mini

安装好的模块是否也要python3的。pip3 list 符合以下
pip install hyper PyOpenSSL dnslib PySocks     
 pip list  
 Package      Version
 ------------ -------
 cffi         1.14.2
 cryptography 3.1
 dnslib       0.9.14
 h2           2.6.2
 hpack        3.0.0
 hyper        0.7.0
 hyperframe   3.2.0
 pip          20.2.2
 pycparser    2.20
 pyOpenSSL    19.1.0
 PySocks      1.7.1
 setuptools   47.1.0
 six          1.15.0

**Comment by miketwes** [comment]
> 安装好的模块是否也要python3的

[XX-Net-mini 4.5.2](https://github.com/miketwes/XX-Net-mini) 自带了相关模块, 不用再安装了

**Comment by yanxiaoguang** [comment]
谁可以帮忙分享下，打不开资源了。

**Comment by hellokkk4789** [comment]
> 其中大多数都是 @XX-net 找出来的, 详见: [ good_ip.txt](https://github.com/miketwes/XX-Net-mini/blob/master/data/gae_proxy/good_ip.txt)

链接消失了！！！

**Comment by dodois** [comment]
可以试试这个 https://github.com/dodois/dosvpn

**Comment by Chem2080** [comment]
> 其中大多数都是 @XX-net 找出来的, 详见: [ good_ip.txt](https://github.com/miketwes/XX-Net-mini/blob/master/data/gae_proxy/good_ip.txt)

这个没了😔希望再分享一个

**Comment by kangxier** [comment]
链接无了，求大佬再分享一下（现在有效ip无了......）

**Comment by miketwes** [comment]
> 链接无了，求大佬再分享一下（现在有效ip无了......）

https://github.com/miketwes/XX-Net-mini/blob/master/code/default/gae_proxy/local/good_ip.txt

**Comment by tq01o3n** [comment]
> > mini的 怎么用呀
> 
> 使用前请确保系统已经安装了最新版本的Python3.8.5, 命令行运行 python --version 查看是否已经安装Python
> 
> 1. 下载或克隆XX-Net-mini
>    [XX-Net-mini 4.5.2 zip](https://github.com/miketwes/XX-Net-mini/archive/4.5.2.zip)
>    ```
>     git clone https://github.com/miketwes/XX-Net-mini.git
>    ```
> 2. 安装openssl, 在命令行运行openssl version看是否已安装, 如果没有安装:
>    Linux:
>    ```
>     sudo aptitude install openssl
>    ```
>    
>    
>    Windows用户根据系统版本位数 32|64位系统选择下载安装
>    [Win64OpenSSL](https://slproweb.com/download/Win64OpenSSL_Light-1_1_1g.exe)
>    [Win32OpenSSL](https://slproweb.com/download/Win32OpenSSL_Light-1_1_1g.exe)
> 3. 运行XX-Net-mini
>    Linux:
>    ```
>     cd XX-Net-mini/code/default/launcher && python start.py
>    ```
>    
>    
>    Windows:
>    运行
>    ```
>     XX-Net-mini\start.bat 
>    ```
>    
>    
>    或者
>    ```
>     cd XX-Net-mini\code\default\launcher && python start.py
>    ```

[请问我这个是怎么回事？[](url)]([url](url))


> > mini的 怎么用呀
> 
> 使用前请确保系统已经安装了最新版本的Python3.8.5, 命令行运行 python --version 查看是否已经安装Python
> 
> 1. 下载或克隆XX-Net-mini
>    [XX-Net-mini 4.5.2 zip](https://github.com/miketwes/XX-Net-mini/archive/4.5.2.zip)
>    ```
>     git clone https://github.com/miketwes/XX-Net-mini.git
>    ```
> 2. 安装openssl, 在命令行运行openssl version看是否已安装, 如果没有安装:
>    Linux:
>    ```
>     sudo aptitude install openssl
>    ```
>    
>    
>    Windows用户根据系统版本位数 32|64位系统选择下载安装
>    [Win64OpenSSL](https://slproweb.com/download/Win64OpenSSL_Light-1_1_1g.exe)
>    [Win32OpenSSL](https://slproweb.com/download/Win32OpenSSL_Light-1_1_1g.exe)
> 3. 运行XX-Net-mini
>    Linux:
>    ```
>     cd XX-Net-mini/code/default/launcher && python start.py
>    ```
>    
>    
>    Windows:
>    运行
>    ```
>     XX-Net-mini\start.bat 
>    ```
>    
>    
>    或者
>    ```
>     cd XX-Net-mini\code\default\launcher && python start.py
>    ```

Microsoft Windows [版本 10.0.18363.1198]
(c) 2019 Microsoft Corporation。保留所有权利。

C:\Windows\system32>cd c:\\

c:\>python --version

c:\>openssl version
OpenSSL 1.1.1h  22 Sep 2020

c:\>XX-Net-mini\start.bat

c:\XX-Net-mini\code\default\launcher>cd XX-Net-mini\code\default\launcher && python start.py
系统找不到指定的路径。

c:\XX-Net-mini\code\default\launcher>cd c://

c:\>cd XX-Net-mini\code\default\launcher && python start.py

c:\XX-Net-mini\code\default\launcher>

请问我这个怎么启动不了了？
打python --version没动静
打openssl version出现版本号
打XX-Net-mini\start.bat或>cd XX-Net-mini\code\default\launcher && python start.py却出现XX-Net-mini\code\default\launcher>，没任何动静

**Comment by miketwes** [comment]
> 打python --version没动静

没有安装Python?

**Comment by tq01o3n** [comment]
装了,是最新版本的Python3.8.5
