### ISSUE TITLE
无法打开，闪退，没有报错日志

### ISSUE THREAD

**Issue by JoachimLaw** [XX-net/XX-Net#13365]
开机没有自启动，手动双击start.bat也是闪退，cmd打开start.py显示没有关联的应用程序

**Comment by xxnet** [comment]
参考这里：
https://github.com/XX-net/XX-Net/wiki/How-to-get-start-error-log

**Comment by JoachimLaw** [comment]
2020-09-01 23:39:30.150 [launcher][INFO] use build-in openssl lib
uncaught Exception:
Traceback (most recent call last):
  File "code\default\launcher\start.py", line 110, in <module>
    import sys_platform
  File "D:\XX-Net-3.3.1\code\default\launcher\sys_platform.py", line 62, in <module>
    from win_tray import sys_tray
  File "D:\XX-Net-3.3.1\code\default\launcher\win_tray.py", line 19, in <module>
    import module_init
  File "D:\XX-Net-3.3.1\code\default\launcher\module_init.py", line 5, in <module>
    from config import config
  File "D:\XX-Net-3.3.1\code\default\launcher\config.py", line 73, in <module>
    config.load()
  File "D:\XX-Net-3.3.1\code\default\lib\noarch\xconfig.py", line 33, in load
    self.file_config = json.loads(content)
  File "D:\XX-Net-3.3.1\python3.8.2\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "D:\XX-Net-3.3.1\python3.8.2\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\XX-Net-3.3.1\python3.8.2\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

2020-09-01 23:39:30.583 [launcher][ERROR] uncaught Exception, type=<class 'json.decoder.JSONDecodeError'> value=Expecting value: line 1 column 1 (char 0) traceback:Traceback (most recent call last):
  File "code\default\launcher\start.py", line 110, in <module>
    import sys_platform
  File "D:\XX-Net-3.3.1\code\default\launcher\sys_platform.py", line 62, in <module>
    from win_tray import sys_tray
  File "D:\XX-Net-3.3.1\code\default\launcher\win_tray.py", line 19, in <module>
    import module_init
  File "D:\XX-Net-3.3.1\code\default\launcher\module_init.py", line 5, in <module>
    from config import config
  File "D:\XX-Net-3.3.1\code\default\launcher\config.py", line 73, in <module>
    config.load()
  File "D:\XX-Net-3.3.1\code\default\lib\noarch\xconfig.py", line 33, in load
    self.file_config = json.loads(content)
  File "D:\XX-Net-3.3.1\python3.8.2\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "D:\XX-Net-3.3.1\python3.8.2\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\XX-Net-3.3.1\python3.8.2\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
日志

**Comment by xxnet** [comment]
配置文件格式出问题了，如果自己改过json文件，找个json检查工具或网站检查一下。
不懂就把data目录删除重新来

**Comment by JoachimLaw** [comment]
搞定了
