### ISSUE TITLE
今天开始不能启动到控制页

### ISSUE THREAD

**Issue by youngwater** [XX-net/XX-Net#13368]
今天开始xx-net启动不能完成，在网页上不能打开127.0.0.1:8085，从版本4.4.3升级互4.5.2也一样不行。
直接启动start.bat在python窗口内复制信息如下：
2020-09-04 22:03:30.903 [launcher][INFO] use build-in openssl lib
2020-09-04 22:03:35.555 [launcher][INFO] start XX-Net 4.5.2
2020-09-04 22:03:35.593 [launcher][DEBUG] start confirm_xxnet_exit
2020-09-04 22:03:37.707 [launcher][DEBUG] good, xxnet:8085 clear!
2020-09-04 22:03:37.710 [launcher][DEBUG] finished confirm_xxnet_exit
2020-09-04 22:03:40.466 [gae_proxy][INFO] ------------------------------------------------------
2020-09-04 22:03:40.467 [gae_proxy][INFO] Python Version     : 3.8.2
2020-09-04 22:03:40.469 [gae_proxy][INFO] OS                 : Version:10-0; Build:18363; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
2020-09-04 22:03:40.471 [gae_proxy][INFO] Listen Address     : 127.0.0.1:8087
2020-09-04 22:03:40.473 [gae_proxy][INFO] GAE APPID          : ******
2020-09-04 22:03:40.473 [gae_proxy][INFO] ------------------------------------------------------
2020-09-04 22:03:40.489 [gae_proxy][DEBUG] Importing CA
2020-09-04 22:03:40.490 [gae_proxy][DEBUG] Begin to import Windows CA
2020-09-04 22:03:40.576 [gae_proxy][DEBUG] XX-Net CA already exists
2020-09-04 22:03:40.591 [gae_proxy][INFO] SSL use version:TLSv1_3
2020-09-04 22:03:40.599 [gae_proxy][INFO] OpenSSL support alpn
2020-09-04 22:03:40.602 [gae_proxy][INFO] load ip range file:D:\Tools\XX-Net\code\default\gae_proxy\local\ip_range.txt
2020-09-04 22:03:40.623 [gae_proxy][INFO] load ip_list num:40, target num:40
2020-09-04 22:03:40.643 [gae_proxy][INFO] SSL use version:TLSv1_3
2020-09-04 22:03:40.652 [gae_proxy][INFO] server 127.0.0.1:8087 started.
2020-09-04 22:03:40.677 [launcher][INFO] module gae_proxy started
2020-09-04 22:03:40.678 [launcher][INFO] start gae_proxy time cost:2962 ms
WARNING:root:Load Crypto.Cipher.ARC4 Failed, Use Pure Python Instead.
2020-09-04 22:03:40.784 [tls_relay][INFO] SSL use version:TLSv1_3
2020-09-04 22:03:40.789 [tls_relay][INFO] OpenSSL support alpn
2020-09-04 22:03:40.814 [x_tunnel][INFO] use config_path:D:\Tools\XX-Net\data\x_tunnel\client.json
2020-09-04 22:03:40.819 [x_tunnel][INFO] X-Tunnel window:16777216
2020-09-04 22:03:40.851 [cloudflare_front][INFO] load D:\Tools\XX-Net\data\x_tunnel\cloudflare_domains.json success
2020-09-04 22:03:40.857 [cloudflare_front][INFO] SSL use version:TLSv1_3
2020-09-04 22:03:40.869 [cloudflare_front][ERROR] updated cloudflare front domains from github fail:AttributeError("'NoneType' object has no attribute 'getsockopt'")
2020-09-04 22:03:40.896 [cloudflare_front][ERROR] Except stack:Traceback (most recent call last):
  File "D:\Tools\XX-Net\code\default\x_tunnel\local\cloudflare_front\host_manager.py", line 69, in update_front_domains
    response = client.request("GET", url)
  File "D:\Tools\XX-Net\code\default\lib\noarch\simple_http_client.py", line 469, in request
    sock = self.connect(upl.hostname, port, upl.scheme == b"https")
  File "D:\Tools\XX-Net\code\default\lib\noarch\simple_http_client.py", line 437, in connect
    sock = ssl.wrap_socket(sock)
  File "D:\Tools\XX-Net\python3.8.2\lib\ssl.py", line 1405, in wrap_socket
    return context.wrap_socket(
  File "D:\Tools\XX-Net\python3.8.2\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "D:\Tools\XX-Net\python3.8.2\lib\ssl.py", line 987, in _create
    if sock.getsockopt(SOL_SOCKET, SO_TYPE) != SOCK_STREAM:
AttributeError: 'NoneType' object has no attribute 'getsockopt'

2020-09-04 22:03:40.908 [cloudflare_front][INFO] OpenSSL support alpn
2020-09-04 22:03:40.913 [cloudflare_front][INFO] load ip range file:D:\Tools\XX-Net\code\default\x_tunnel\local\cloudflare_front\ip_range.txt
2020-09-04 22:03:40.947 [cloudflare_front][INFO] load ip_list num:138, target num:138
2020-09-04 22:03:40.959 [x_tunnel][INFO] xxnet_version:4.5.2
2020-09-04 22:03:40.961 [x_tunnel][DEBUG] SendBuffer reset
2020-09-04 22:03:40.963 [x_tunnel][ERROR] bind to b'127.0.0.1':1080 fail:OSError(10013, '以一种访问权限不允许的方式做了 一个访问套接字的尝试。', None, 10013, None)
Exception in thread Thread-31:
Traceback (most recent call last):
  File "D:\Tools\XX-Net\code\default\lib\noarch\simple_http_server.py", line 466, in add_listen
    sock.bind(addr)
OSError: [WinError 10013] 以一种访问权限不允许的方式做了一个访问套接字的尝试。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Tools\XX-Net\python3.8.2\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "D:\Tools\XX-Net\python3.8.2\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Tools\XX-Net\code\default\x_tunnel\local\__init__.py", line 14, in start
    client.main(args)
  File "D:\Tools\XX-Net\code\default\x_tunnel\local\client.py", line 181, in main
    g.socks5_server = simple_http_server.HTTPServer(addresses, Socks5Server, logger=xlog)
  File "D:\Tools\XX-Net\code\default\lib\noarch\simple_http_server.py", line 430, in __init__
    self.init_socket()
  File "D:\Tools\XX-Net\code\default\lib\noarch\simple_http_server.py", line 449, in init_socket
    self.add_listen((ip, port))
  File "D:\Tools\XX-Net\code\default\lib\noarch\simple_http_server.py", line 470, in add_listen
    raise Exception(err_string)
Exception: bind to b'127.0.0.1':1080 fail:OSError(10013, '以一种访问权限不允许的方式做了一个访问套接字的尝试。', None, 10013, None)
2020-09-04 22:03:43.381 [gae_proxy][DEBUG] network IPv4 is ok, cost:3602 ms
2020-09-04 22:03:51.839 [gae_proxy][INFO] scan_ip add ip:2607:f8b0:4012:804::2014 time:1737 h2:1
2020-09-04 22:04:19.682 [cloudflare_front][INFO] remove ip:1.0.0.230 left amount:137 target_num:137
2020-09-04 22:04:19.687 [cloudflare_front][DEBUG] recheck_ip:1.0.0.230 real fail, removed.
2020-09-04 22:04:24.381 [gae_proxy][DEBUG] network IPv6 is ok, cost:44598 ms
2020-09-04 22:04:34.988 [gae_proxy][INFO] scan_ip add ip:2607:f8b0:4000:813::2014 time:289 h2:1

**Comment by xxnet** [comment]
1080 端口被占用了，请检查一下有什么代理软件在跑

**Comment by youngwater** [comment]
已解决，谢谢。

**Comment by tofu23** [comment]
请问是如何解决的 我按网上教程并没有查出1080端口被占用

**Comment by huhuime** [comment]
> 1080 端口被占用了，请检查一下有什么代理软件在跑

win10更新把1080回收给系统使用了
