### ISSUE TITLE
启动问题（无法启动，附日志）

### ISSUE THREAD

**Issue by starxjys** [XX-net/XX-Net#13387]
2020-09-29 19:30:07.388 [launcher][INFO] use build-in openssl lib
2020-09-29 19:30:20.353 [launcher][INFO] start XX-Net 4.4.3
2020-09-29 19:30:20.354 [launcher][DEBUG] start confirm_xxnet_exit
2020-09-29 19:30:22.584 [launcher][DEBUG] good, xxnet:8085 clear!
2020-09-29 19:30:22.585 [launcher][DEBUG] finished confirm_xxnet_exit
2020-09-29 19:30:26.727 [gae_proxy][INFO] ------------------------------------------------------
2020-09-29 19:30:26.728 [gae_proxy][INFO] Python Version     : 3.8.2
2020-09-29 19:30:26.729 [gae_proxy][INFO] OS                 : Version:10-0; Build:19041; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
2020-09-29 19:30:26.729 [gae_proxy][INFO] Listen Address     : 127.0.0.1:8087
2020-09-29 19:30:26.729 [gae_proxy][INFO] Using public APPID
2020-09-29 19:30:26.729 [gae_proxy][INFO] ------------------------------------------------------
2020-09-29 19:30:26.758 [gae_proxy][INFO] no GAE CA file exist in XX-Net data dir
2020-09-29 19:30:26.759 [gae_proxy][INFO] clean old site certs in XX-Net cert dir
2020-09-29 19:30:26.762 [gae_proxy][INFO] generate CA file:E:\软件\网络相关\XX-Net\data\gae_proxy\CAkey.pem
2020-09-29 19:30:27.286 [gae_proxy][INFO] create CA
2020-09-29 19:30:27.316 [gae_proxy][INFO] generate certs's key file:E:\软件\网络相关\XX-Net\data\gae_proxy\Certkey.pem
2020-09-29 19:30:27.750 [gae_proxy][DEBUG] Importing CA
2020-09-29 19:30:27.750 [gae_proxy][DEBUG] Begin to import Windows CA
2020-09-29 19:30:31.128 [gae_proxy][INFO] SSL use version:TLSv1_3
2020-09-29 19:30:31.134 [gae_proxy][INFO] OpenSSL support alpn
2020-09-29 19:30:31.136 [gae_proxy][INFO] load ip range file:E:\软件\网络相关\XX-Net\code\default\gae_proxy\local\ip_range.txt
2020-09-29 19:30:31.164 [gae_proxy][INFO] SSL use version:TLSv1_3
2020-09-29 19:30:31.167 [gae_proxy][INFO] server 127.0.0.1:8087 started.
2020-09-29 19:30:31.171 [launcher][INFO] module gae_proxy started
2020-09-29 19:30:31.172 [launcher][INFO] start gae_proxy time cost:8580 ms
WARNING:root:Load Crypto.Cipher.ARC4 Failed, Use Pure Python Instead.
2020-09-29 19:30:31.545 [tls_relay][INFO] SSL use version:TLSv1_3
2020-09-29 19:30:31.546 [tls_relay][INFO] OpenSSL support alpn
2020-09-29 19:30:31.609 [x_tunnel][INFO] use config_path:E:\软件\网络相关\XX-Net\data\x_tunnel\client.json
2020-09-29 19:30:31.611 [x_tunnel][INFO] X-Tunnel window:16777216
2020-09-29 19:30:31.652 [cloudflare_front][INFO] load E:\软件\网络相关\XX-Net\code\default\x_tunnel\local\cloudflare_front\front_domains.json success
2020-09-29 19:30:31.655 [cloudflare_front][INFO] SSL use version:TLSv1_3
2020-09-29 19:30:31.671 [cloudflare_front][INFO] OpenSSL support alpn
2020-09-29 19:30:31.672 [cloudflare_front][INFO] load ip range file:E:\软件\网络相关\XX-Net\code\default\x_tunnel\local\cloudflare_front\ip_range.txt
2020-09-29 19:30:31.682 [cloudflare_front][INFO] load ip_list num:99, target num:99
2020-09-29 19:30:31.689 [x_tunnel][INFO] xxnet_version:4.4.3
2020-09-29 19:30:31.692 [x_tunnel][ERROR] bind to b'127.0.0.1':1080 fail:OSError(10013, '以一种访问权限不允许的方式做了 一个访问套接字的尝试。', None, 10013, None)
Exception in thread Thread-31:
Traceback (most recent call last):
  File "E:\软件\网络相关\XX-Net\code\default\lib\noarch\simple_http_server.py", line 464, in add_listen
    sock.bind(addr)
OSError: [WinError 10013] 以一种访问权限不允许的方式做了一个访问套接字的尝试。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\软件\网络相关\XX-Net\python3.8.2\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "E:\软件\网络相关\XX-Net\python3.8.2\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "E:\软件\网络相关\XX-Net\code\default\x_tunnel\local\__init__.py", line 14, in start
    client.main(args)
  File "E:\软件\网络相关\XX-Net\code\default\x_tunnel\local\client.py", line 181, in main
    g.socks5_server = simple_http_server.HTTPServer(addresses, Socks5Server, logger=xlog)
  File "E:\软件\网络相关\XX-Net\code\default\lib\noarch\simple_http_server.py", line 430, in __init__
    self.init_socket()
  File "E:\软件\网络相关\XX-Net\code\default\lib\noarch\simple_http_server.py", line 449, in init_socket
    self.add_listen((ip, port))
  File "E:\软件\网络相关\XX-Net\code\default\lib\noarch\simple_http_server.py", line 468, in add_listen
    raise Exception(err_string)
Exception: bind to b'127.0.0.1':1080 fail:OSError(10013, '以一种访问权限不允许的方式做了一个访问套接字的尝试。', None, 10013, None)
2020-09-29 19:30:48.859 [cloudflare_front][ERROR] updated cloudflare front domains from github fail:AttributeError("'NoneType' object has no attribute 'getsockopt'")
2020-09-29 19:30:48.865 [cloudflare_front][ERROR] Except stack:Traceback (most recent call last):
  File "E:\软件\网络相关\XX-Net\code\default\x_tunnel\local\cloudflare_front\host_manager.py", line 69, in update_front_domains
    response = client.request("GET", url)
  File "E:\软件\网络相关\XX-Net\code\default\lib\noarch\simple_http_client.py", line 469, in request
    sock = self.connect(upl.hostname, port, upl.scheme == b"https")
  File "E:\软件\网络相关\XX-Net\code\default\lib\noarch\simple_http_client.py", line 437, in connect
    sock = ssl.wrap_socket(sock)
  File "E:\软件\网络相关\XX-Net\python3.8.2\lib\ssl.py", line 1405, in wrap_socket
    return context.wrap_socket(
  File "E:\软件\网络相关\XX-Net\python3.8.2\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "E:\软件\网络相关\XX-Net\python3.8.2\lib\ssl.py", line 987, in _create
    if sock.getsockopt(SOL_SOCKET, SO_TYPE) != SOCK_STREAM:
AttributeError: 'NoneType' object has no attribute 'getsockopt'

2020-09-29 19:30:53.879 [gae_proxy][WARNING] network IPv4 fail
2020-09-29 19:31:13.908 [gae_proxy][WARNING] network IPv6 fail

**Comment by xxnet** [comment]
1080 端口被占用了
