### ISSUE TITLE
feedback error.log

### ISSUE THREAD

**Issue by jkle112** [XX-net/XX-Net#13380]
版本4.5.2，运行在windows 10 64bit 最新版本，
出现错误提示，粘贴如下：
2020-09-19 14:23:04.735 - [INFO] get uuid:5f9319f4-4615-442a-95e5-14e4d3dc84c8
2020-09-19 14:24:04.839 - [ERROR] check_update fail:<HTTPError 504: ''>
2020-09-19 14:24:04.870 - [ERROR] Except stack:Traceback (most recent call last):
  File "C:\Users\Administrator\Downloads\XX-Net\code\default\launcher\update.py", line 285, in check_push_update
    update_content = opener.open(req_url).read()
  File "C:\Users\Administrator\Downloads\XX-Net\python3.8.2\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "C:\Users\Administrator\Downloads\XX-Net\python3.8.2\lib\urllib\request.py", line 640, in http_response
    response = self.parent.error(
  File "C:\Users\Administrator\Downloads\XX-Net\python3.8.2\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "C:\Users\Administrator\Downloads\XX-Net\python3.8.2\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)
  File "C:\Users\Administrator\Downloads\XX-Net\python3.8.2\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 504: 

目前完全无法使用。

**Comment by xxnet** [comment]
GAE 目前很多地区无法使用，先用X-Tunnel
