### ISSUE TITLE
GAE已经部署成功，登录myid.appspot.com返回500错误码

### ISSUE THREAD

**Issue by JungleKong** [XX-net/XX-Net#13391]
按照教程部署成功后
```
Updating service [default]...done.
Setting traffic split for service [default]...done.
Deployed service [default] to [https://javakong.uc.r.appspot.com]
```
但没办法访问myid.appspot.com，服务器会返回500错误码，与此同时，在GCP ErrorReporting处报错
```
Traceback (most recent call last):
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/4a2384f6b69cef45/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 238, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/4a2384f6b69cef45/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 309, in _LoadHandler
    handler, path, err = LoadObject(self._handler)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/4a2384f6b69cef45/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 83, in LoadObject
    obj = __import__(path[0])
ImportError: No module named legacy
```
猜测是缺少legacy库，但检查后并没有缺少，接连部署了三个项目都是同样的问题，是怎么回事啊

**Comment by xxnet** [comment]
legacy  是XX-Net GAE_proxy服务端模块里的一个文件。
会不会是文件没有部署上去
