### ISSUE TITLE
x-tunnel无法使用

### ISSUE THREAD

**Issue by niu541412** [XX-net/XX-Net#13401]
最新版和从github clone的版本都无法使用。大约从2天前开始。
系统 Mac OS 10.15.7。 python 3.8.6
Chrome 显示 ERR_CONNECTION_CLOSED
X-tunnel可以登录，但是Cloudflare 日志不停地有报错。
如下。
> 2020-10-17 17:34:28.684 - [ERROR] updated cloudflare front domains from github 
> fail:AttributeError("'NoneType' object has no attribute 'getsockopt'")
>2020-10-17 17:34:28.685 - [ERROR] Except stack:Traceback (most recent call last): File >"/Users/jomic/Documents/XX-Net/code/default/x_tunnel/local/cloudflare_front/host_manager.py", line 69, >in update_front_domains response = client.request("GET", url) File "/Users/jomic/Documents/XX->Net/code/default/lib/noarch/simple_http_client.py", line 469, in request sock = self.connect(upl.hostname, port, upl.scheme == b"https") File "/Users/jomic/Documents/XX-Net/code/default/lib/noarch/simple_http_client.py", line 437, in connect sock = ssl.wrap_socket(sock) File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 1405, in wrap_socket return context.wrap_socket( File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 500, in wrap_socket return self.sslsocket_class._create( File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 987, in _create if sock.getsockopt(SOL_SOCKET, SO_TYPE) != SOCK_STREAM: AttributeError: 'NoneType' object has no attribute 'getsockopt'

**Comment by niu541412** [comment]
今天似乎又能连上了
