### ISSUE TITLE
无法启动,请帮帮忙.

### ISSUE THREAD

**Issue by trident8134** [XX-net/XX-Net#13436]
自3.14升级至4.5.2后便无法启动.

     先是提示缺失 api-ms-win-crt-runtime-l1-1-0.dll 文件.

     网上查找解决方法后,安装Microsoft Visual C++ 2017解决.

     但依然无法启动.

     为搞清楚到底哪出问题,重装了win7系统,结果和上述相同.

     按xx-net解决启动问题使用说明,情况如下:

    

E:\XX-Net>python3.8.2\python.exe code\default\launcher\start.py
Traceback (most recent call last):
  File "code\default\launcher\start.py", line 49, in <module>
    from xlog import getLogger
  File "E:\XX-Net\code\default\lib\noarch\xlog.py", line 277, in <module>
    default_log = getLogger()
  File "E:\XX-Net\code\default\lib\noarch\xlog.py", line 271, in getLogger
    logger_instance = Logger(name, buffer_size, file_name, roll_num)
  File "E:\XX-Net\code\default\lib\noarch\xlog.py", line 35, in __init__
    self.set_color()
  File "E:\XX-Net\code\default\lib\noarch\xlog.py", line 78, in set_color
    import ctypes
  File "E:\XX-Net\python3.8.2\lib\ctypes\__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: DLL load failed while importing _ctypes: The parameter is incorrect
.

    网上搜看很多文章,不知该如何解决.
先行感谢.
    有请明白的网友帮忙看看,到底是怎么回事.

**Comment by miketwes** [comment]
在网上看了一下, 这是Python 3.8 与 Windows 7的问题

        选项1: 升级Windows 7
        选项2: 使用Python 3.7或Python 3.6

**Comment by fx606** [comment]
从XX-net客户端升级下载的内容不全，要到github直接下载完整的zip文件，解压覆盖原有文件夹。

**Comment by trident8134** [comment]
谢谢回复,两台电脑同样的问题,看来不是操作系统 的事.
