### ISSUE TITLE
[launcher][ERROR] launcher except:Exception("bind to b'127.0.0.1':8085 fail:OSError(10013, '以一种访问权限不允许的方式做了一个访问套接字的尝试。', None, 10013, None)")

### ISSUE THREAD

**Issue by cym104** [XX-net/XX-Net#13448]
2020-12-19 08:05:33.016 [gae_proxy][DEBUG] network IPv4 is ok, cost:293 ms
2020-12-19 08:05:33.054 [gae_proxy][DEBUG] Importing CA
2020-12-19 08:05:33.055 [gae_proxy][DEBUG] Begin to import Windows CA
2020-12-19 08:05:33.071 [gae_proxy][DEBUG] XX-Net CA already exists
2020-12-19 08:05:33.084 [gae_proxy][DEBUG] XX-Net CA already exists
2020-12-19 08:05:33.086 [gae_proxy][INFO] SSL use version:TLSv1_3
2020-12-19 08:05:33.088 [gae_proxy][INFO] OpenSSL support alpn
2020-12-19 08:05:33.089 [gae_proxy][INFO] load ip range file:D:\Program Files (x86)\XX-Net\code\4.5.2\gae_proxy\local\ip_range.txt
2020-12-19 08:05:33.111 [gae_proxy][INFO] load ip_list num:308, target num:308
2020-12-19 08:05:33.214 [gae_proxy][INFO] SSL use version:TLSv1_3
2020-12-19 08:05:33.218 [gae_proxy][INFO] server 0.0.0.0:18087 started.
2020-12-19 08:05:33.315 [launcher][INFO] module gae_proxy started
2020-12-19 08:05:33.316 [launcher][INFO] start gae_proxy time cost:2672 ms
2020-12-19 08:05:33.317 [launcher][INFO] begin to start web control
2020-12-19 08:05:33.318 [launcher][ERROR] bind to b'127.0.0.1':8085 fail:OSError(10013, '以一种访问权限不允许的方式做了一个访问套接字的尝试。', None, 10013, None)
2020-12-19 08:05:33.319 [launcher][ERROR] launcher except:Exception("bind to b'127.0.0.1':8085 fail:OSError(10013, '以一种访问权限不允许的方式做了一个访问套接字的尝试。', None, 10013, None)")
2020-12-19 08:05:33.324 [launcher][ERROR] Except stack:Traceback (most recent call last):
  File "D:\Program Files (x86)\XX-Net\code\4.5.2\lib\noarch\simple_http_server.py", line 466, in add_listen
    sock.bind(addr)
OSError: [WinError 10013] 以一种访问权限不允许的方式做了一个访问套接字的尝试。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Program Files (x86)\XX-Net\code\4.5.2\launcher\start.py", line 193, in <module>
    main()
  File "D:\Program Files (x86)\XX-Net\code\4.5.2\launcher\start.py", line 172, in main
    web_control.start(allow_remote)
  File "D:\Program Files (x86)\XX-Net\code\4.5.2\launcher\web_control.py", line 734, in start
    server = simple_http_server.HTTPServer(addresses, Http_Handler, logger=xlog)
  File "D:\Program Files (x86)\XX-Net\code\4.5.2\lib\noarch\simple_http_server.py", line 430, in __init__
    self.init_socket()
  File "D:\Program Files (x86)\XX-Net\code\4.5.2\lib\noarch\simple_http_server.py", line 449, in init_socket
    self.add_listen((ip, port))
  File "D:\Program Files (x86)\XX-Net\code\4.5.2\lib\noarch\simple_http_server.py", line 470, in add_listen
    raise Exception(err_string)
Exception: bind to b'127.0.0.1':8085 fail:OSError(10013, '以一种访问权限不允许的方式做了一个访问套接字的尝试。', None, 10013, None)

Press Enter to continue...2020-12-19 08:05:34.516 [gae_proxy][DEBUG] create_ssl update ip:2800:3f0:4003:c02::99 time:1289 h2:0 sni:None, host:
2020-12-19 08:05:36.554 [gae_proxy][DEBUG] create_ssl update ip:2607:f8b0:400d:c0f::99 time:1032 h2:0 sni:None, host:
2020-12-19 08:05:37.467 [gae_proxy][DEBUG] network IPv6 is ok, cost:4743 ms

**Comment by pinocc01** [comment]
same problem today

**Comment by tofu23** [comment]
我今天也这样 昨天还好好的 点击图标没有任何反应

**Comment by pinocc01** [comment]
我的情况是在监听1080的时候失败，没有图标出现

2021-01-03 21:49:57.421 [launcher][INFO] use build-in openssl lib
2021-01-03 21:49:57.636 [launcher][INFO] start XX-Net 4.5.2
2021-01-03 21:49:57.638 [launcher][DEBUG] start confirm_xxnet_exit
2021-01-03 21:49:59.714 [launcher][DEBUG] good, xxnet:8085 clear!
2021-01-03 21:49:59.716 [launcher][DEBUG] finished confirm_xxnet_exit
2021-01-03 21:50:02.024 [gae_proxy][DEBUG] network IPv4 is ok, cost:218 ms
2021-01-03 21:50:02.072 [gae_proxy][INFO] ------------------------------------------------------
2021-01-03 21:50:02.073 [gae_proxy][INFO] Python Version     : 3.8.2
2021-01-03 21:50:02.073 [gae_proxy][INFO] OS                 : Version:10-0; Build:19041; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
2021-01-03 21:50:02.074 [gae_proxy][INFO] Listen Address     : 0.0.0.0:8087
2021-01-03 21:50:02.074 [gae_proxy][INFO] GAE APPID          : xxxxxxxxx
2021-01-03 21:50:02.074 [gae_proxy][INFO] ------------------------------------------------------
2021-01-03 21:50:02.100 [gae_proxy][DEBUG] Importing CA
2021-01-03 21:50:02.101 [gae_proxy][DEBUG] Begin to import Windows CA
2021-01-03 21:50:02.126 [gae_proxy][DEBUG] XX-Net CA already exists
2021-01-03 21:50:02.129 [gae_proxy][INFO] SSL use version:TLSv1_3
2021-01-03 21:50:02.130 [gae_proxy][INFO] OpenSSL support alpn
2021-01-03 21:50:02.132 [gae_proxy][INFO] load ip range file:D:\Program Files\XX-Net\code\4.5.2\gae_proxy\local\ip_range.txt
2021-01-03 21:50:02.146 [gae_proxy][INFO] load ip_list num:200, target num:200
2021-01-03 21:50:02.191 [gae_proxy][INFO] SSL use version:TLSv1_3
2021-01-03 21:50:02.194 [gae_proxy][INFO] server 0.0.0.0:8087 started.
2021-01-03 21:50:02.289 [launcher][INFO] module gae_proxy started
2021-01-03 21:50:02.289 [launcher][INFO] start gae_proxy time cost:2567 ms
WARNING:root:Load Crypto.Cipher.ARC4 Failed, Use Pure Python Instead.
2021-01-03 21:50:02.329 [tls_relay][INFO] SSL use version:TLSv1_3
2021-01-03 21:50:02.329 [tls_relay][INFO] OpenSSL support alpn
2021-01-03 21:50:02.333 [tls_relay][INFO] load ip_list num:1, target num:1
2021-01-03 21:50:02.343 [x_tunnel][INFO] use config_path:D:\Program Files\XX-Net\data\x_tunnel\client.json
2021-01-03 21:50:02.344 [x_tunnel][INFO] X-Tunnel window:16777216
2021-01-03 21:50:02.355 [cloudflare_front][INFO] load D:\Program Files\XX-Net\data\x_tunnel\cloudflare_domains.json success
2021-01-03 21:50:02.356 [cloudflare_front][INFO] SSL use version:TLSv1_3
2021-01-03 21:50:02.357 [cloudflare_front][ERROR] updated cloudflare front domains from github fail:AttributeError("'NoneType' object has no attribute 'getsockopt'")
2021-01-03 21:50:02.363 [cloudflare_front][ERROR] Except stack:Traceback (most recent call last):
  File "D:\Program Files\XX-Net\code\4.5.2\x_tunnel\local\cloudflare_front\host_manager.py", line 69, in update_front_domains
    response = client.request("GET", url)
  File "D:\Program Files\XX-Net\code\4.5.2\lib\noarch\simple_http_client.py", line 469, in request
    sock = self.connect(upl.hostname, port, upl.scheme == b"https")
  File "D:\Program Files\XX-Net\code\4.5.2\lib\noarch\simple_http_client.py", line 437, in connect
    sock = ssl.wrap_socket(sock)
  File "D:\Program Files\XX-Net\python3.8.2\lib\ssl.py", line 1405, in wrap_socket
    return context.wrap_socket(
  File "D:\Program Files\XX-Net\python3.8.2\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "D:\Program Files\XX-Net\python3.8.2\lib\ssl.py", line 987, in _create
    if sock.getsockopt(SOL_SOCKET, SO_TYPE) != SOCK_STREAM:
AttributeError: 'NoneType' object has no attribute 'getsockopt'

2021-01-03 21:50:02.369 [cloudflare_front][INFO] OpenSSL support alpn
2021-01-03 21:50:02.375 [cloudflare_front][INFO] load ip range file:D:\Program Files\XX-Net\code\4.5.2\x_tunnel\local\cloudflare_front\ip_range.txt
2021-01-03 21:50:02.385 [cloudflare_front][INFO] load ip_list num:135, target num:135
2021-01-03 21:50:02.390 [x_tunnel][INFO] xxnet_version:4.5.2
2021-01-03 21:50:02.391 [x_tunnel][DEBUG] SendBuffer reset
2021-01-03 21:50:02.392 [x_tunnel][ERROR] bind to b'127.0.0.1':1080 fail:OSError(10013, '以一种访问权限不允许的方式做了 一个访问套接字的尝试。', None, 10013, None)

**Comment by pinocc01** [comment]
小结一下，最近多次出现上述问题，只要是异常关机，重启后一定会出现端口监听故障
如果再次重启，故障有可能自动消失

**Comment by jowenz** [comment]
现在换有线连接电脑也是会出现这样的情况，不定时不定界面的出现，还有，有时获取不到界面的全部信息，多次重复获取也不行。但是这个界面的元素信息有时又是可以获取到的，
