### ISSUE TITLE
asus AC86U 安装xxNet 4.5.2后，可以在局域网内访问https://路由器：8085，网页配置X-TUNNEL 时提示用户名或者密码错误

### ISSUE THREAD

**Issue by icichugo3188** [XX-net/XX-Net#13443]
asus AC86U 安装xxNet 4.5.2后，可以在局域网内访问https://路由器：8085，网页配置X-TUNNEL 时提示用户名或者密码错误

折腾了好久，总算把xxNet 在路由器上跑起来了，能够在局域网内访问web配置页面，登陆x-tunnel 提示用户名密码错误，请大神指点，怎么配置？
可以在xxnet配置文件里配置用户名密码？
日志如下：
admin@RT-AC86U-93B8:/tmp/home/root# sh /tmp/mnt/SDA1/xxnet/start -allow_remote
XX-Net version:4.5.2
2020-12-06 21:16:48.779 [launcher][INFO] use build-in openssl lib
2020-12-06 21:16:48.907 [launcher][INFO] This is Android or IOS or router.
2020-12-06 21:16:49.411 [launcher][INFO] start XX-Net 4.5.2
2020-12-06 21:16:49.412 [launcher][DEBUG] start confirm_xxnet_exit
2020-12-06 21:16:49.499 [launcher][DEBUG] good, xxnet:8085 clear!
2020-12-06 21:16:49.499 [launcher][DEBUG] finished confirm_xxnet_exit
2020-12-06 21:16:49.505 [launcher][INFO] command args:-allow_remote
2020-12-06 21:16:49.505 [launcher][INFO] start with allow remote connect.
2020-12-06 21:16:49.695 [gae_proxy][DEBUG] network IPv4 is ok, cost:135 ms
2020-12-06 21:16:50.474 [gae_proxy][INFO] ------------------------------------------------------
2020-12-06 21:16:50.475 [gae_proxy][INFO] Python Version     : 3.8.5
2020-12-06 21:16:50.480 [gae_proxy][INFO] OS                 : plat:Linux-4.1.27-aarch64-with-glibc2.4 release:4.1.27 ver:#2 SMP PREEMPT Fri Aug 14 16:38:14 EDT 2020
2020-12-06 21:16:50.480 [gae_proxy][INFO] Listen Address     : 127.0.0.1:8087
2020-12-06 21:16:50.480 [gae_proxy][INFO] GAE APPID          : zhangxu3188|zhangxu31880|zhangxu31881|zhangxu31882|zhangxu31883|zhangxu31884|zhangxu31886|zhangxu31887|zhangxu31888|zhangxu31889|zhangxu31880
2020-12-06 21:16:50.481 [gae_proxy][INFO] ------------------------------------------------------
2020-12-06 21:16:50.497 [gae_proxy][DEBUG] Importing CA
2020-12-06 21:16:50.498 [gae_proxy][DEBUG] Begin importing CA to Firefox
2020-12-06 21:16:50.499 [gae_proxy][INFO] SSL use version:TLSv1_3
2020-12-06 21:16:50.501 [gae_proxy][INFO] OpenSSL support alpn
2020-12-06 21:16:50.504 [gae_proxy][INFO] load ip range file:/tmp/mnt/SDA1/xxnet/code/default/gae_proxy/local/ip_range.txt
2020-12-06 21:16:50.552 [gae_proxy][INFO] SSL use version:TLSv1_3
2020-12-06 21:16:50.558 [gae_proxy][INFO] server 0.0.0.0:8087 started.
2020-12-06 21:16:50.584 [launcher][INFO] module gae_proxy started
2020-12-06 21:16:50.584 [launcher][INFO] start gae_proxy time cost:1070 ms
WARNING:root:Load Crypto.Cipher.ARC4 Failed, Use Pure Python Instead.
2020-12-06 21:16:50.726 [tls_relay][INFO] SSL use version:TLSv1_3
2020-12-06 21:16:50.727 [tls_relay][INFO] OpenSSL support alpn
2020-12-06 21:16:50.764 [x_tunnel][INFO] use config_path:/tmp/mnt/SDA1/xxnet/data/x_tunnel/client.json
2020-12-06 21:16:50.765 [x_tunnel][INFO] X-Tunnel window:16777216
2020-12-06 21:16:50.795 [cloudflare_front][INFO] load /tmp/mnt/SDA1/xxnet/code/default/x_tunnel/local/cloudflare_front/front_domains.json success
2020-12-06 21:16:50.798 [cloudflare_front][INFO] SSL use version:TLSv1_3
2020-12-06 21:16:50.811 [cloudflare_front][ERROR] updated cloudflare front domains from github fail:AttributeError("'NoneType' object has no attribute 'getsockopt'")
2020-12-06 21:16:50.820 [cloudflare_front][ERROR] Except stack:Traceback (most recent call last):
  File "/tmp/mnt/SDA1/xxnet/code/default/x_tunnel/local/cloudflare_front/host_manager.py", line 69, in update_front_domains
    response = client.request("GET", url)
  File "/tmp/mnt/SDA1/xxnet/code/default/lib/noarch/simple_http_client.py", line 469, in request
    sock = self.connect(upl.hostname, port, upl.scheme == b"https")
  File "/tmp/mnt/SDA1/xxnet/code/default/lib/noarch/simple_http_client.py", line 437, in connect
    sock = ssl.wrap_socket(sock)
  File "/opt/lib/python3.8/ssl.py", line 1405, in wrap_socket
  File "/opt/lib/python3.8/ssl.py", line 500, in wrap_socket
  File "/opt/lib/python3.8/ssl.py", line 987, in _create
AttributeError: 'NoneType' object has no attribute 'getsockopt'

2020-12-06 21:16:50.832 [cloudflare_front][INFO] OpenSSL support alpn
2020-12-06 21:16:50.833 [cloudflare_front][INFO] load ip range file:/tmp/mnt/SDA1/xxnet/code/default/x_tunnel/local/cloudflare_front/ip_range.txt
2020-12-06 21:16:50.879 [cloudflare_front][INFO] load ip_list num:121, target num:121
2020-12-06 21:16:50.891 [x_tunnel][INFO] xxnet_version:4.5.2
2020-12-06 21:16:50.892 [x_tunnel][DEBUG] SendBuffer reset
2020-12-06 21:16:50.895 [x_tunnel][INFO] server 0.0.0.0:1080 started.
2020-12-06 21:16:50.895 [x_tunnel][INFO] Socks5 server listen:127.0.0.1:1080.
2020-12-06 21:16:50.993 [launcher][INFO] module x_tunnel started
2020-12-06 21:16:50.994 [launcher][INFO] start x_tunnel time cost:408 ms
2020-12-06 21:16:51.217 [smart_router][INFO] Load file:/tmp/mnt/SDA1/xxnet/code/default/smart_router/local/gfw_black_list.txt
2020-12-06 21:16:51.376 [smart_router][INFO] Load file:/tmp/mnt/SDA1/xxnet/code/default/smart_router/local/gfw_white_list.txt
2020-12-06 21:16:51.385 [smart_router][INFO] Load file:/tmp/mnt/SDA1/xxnet/code/default/smart_router/local/advertisement_list.txt
2020-12-06 21:16:51.439 [smart_router][INFO] Local DNS server:192.168.1.1
2020-12-06 21:16:51.441 [smart_router][INFO] server 0.0.0.0:8086 started.
2020-12-06 21:16:51.442 [smart_router][INFO] Proxy server listen:['0.0.0.0']:8086.
2020-12-06 21:16:51.443 [smart_router][WARNING] bind DNS 0.0.0.0:53 fail
2020-12-06 21:16:51.444 [smart_router][INFO] start DNS server at 0.0.0.0:8053
2020-12-06 21:16:51.453 [launcher][INFO] module smart_router started
2020-12-06 21:16:51.454 [launcher][INFO] start smart_router time cost:459 ms
2020-12-06 21:16:51.454 [launcher][INFO] allow remote access WebUI
2020-12-06 21:16:51.455 [launcher][INFO] begin to start web control
2020-12-06 21:16:51.455 [launcher][INFO] server 0.0.0.0:8085 started.
2020-12-06 21:16:51.457 [launcher][INFO] launcher web control started.
2020-12-06 21:16:52.505 [launcher][INFO] get uuid:593d956d-c284-47c2-85ea-63d3a3df5f31
2020-12-06 21:16:52.558 [gae_proxy][DEBUG] DIRECT GET https://xxnet-update.appspot.com/update.json?uuid=593d956d-c284-47c2-85ea-63d3a3df5f31&version=4.5.2&platform=Linux-4.1.27-aarch64-with-glibc2.4 from:127.0.0.1:51239
2020-12-06 21:16:53.584 [gae_proxy][WARNING] not enough ip
2020-12-06 21:16:53.644 [gae_proxy][WARNING] network IPv6 fail

![image](https://user-images.githubusercontent.com/75571029/101281163-9378e680-3808-11eb-9ec3-4939bc856a19.png)
![image](https://user-images.githubusercontent.com/75571029/101281179-abe90100-3808-11eb-9633-2d9416690955.png)
![image](https://user-images.githubusercontent.com/75571029/101281190-b7d4c300-3808-11eb-8430-3ce7ce470b31.png)

**Comment by icichugo3188** [comment]
2020-12-06 21:57:55.844 [cloudflare_front][WARNING] not enough ip
2020-12-06 21:57:55.904 [gae_proxy][DEBUG] create ssl timeout fail.
2020-12-06 21:57:58.874 [gae_proxy][WARNING] not enough ip
2020-12-06 21:57:59.204 [gae_proxy][WARNING] task POST  /_gh/ timeout
2020-12-06 21:57:59.205 [gae_proxy][DEBUG] GAE_Exception 600 'fetch gae fail'
2020-12-06 21:57:59.205 [gae_proxy][WARNING] gae_exception:'600:fetch gae fail' https://raw.githubusercontent.com/XX-net/XX-Net/master/code/default/update_v4.txt
2020-12-06 21:57:59.206 [gae_proxy][DEBUG] GAE_Exception 600 "gae_exception:'600:fetch gae fail' b'https://raw.githubusercontent.com/XX-net/XX-Net/master/code/default/update_v4.txt'gae_exception:'600:fetch gae fail' b'https://raw.githubusercontent.com/XX-net/XX-Net/master/code/default/update_v4.txt'gae_exception:'600:fetch gae fail' b'https://raw.githubusercontent.com/XX-net/XX-Net/master/code/default/update_v4.txt'"
2020-12-06 21:57:59.206 [gae_proxy][WARNING] GAE GET https://raw.githubusercontent.com/XX-net/XX-Net/master/code/default/update_v4.txt request fail:"600:gae_exception:'600:fetch gae fail' b'https://raw.githubusercontent.com/XX-net/XX-Net/master/code/default/update_v4.txt'gae_exception:'600:fetch gae fail' b'https://raw.githubusercontent.com/XX-net/XX-Net/master/code/default/update_v4.txt'gae_exception:'600:fetch gae fail' b'https://raw.githubusercontent.com/XX-net/XX-Net/master/code/default/update_v4.txt'"
2020-12-06 21:58:00.103 [launcher][ERROR] check_update fail:Exception('get_version_fail:/tmp/mnt/SDA1/xxnet/data/downloads/version.txt')
2020-12-06 21:58:00.111 [launcher][ERROR] Except stack:Traceback (most recent call last):
  File "/tmp/mnt/SDA1/xxnet/code/default/launcher/update.py", line 246, in check_update
    versions = update_from_github.get_github_versions()
  File "/tmp/mnt/SDA1/xxnet/code/default/launcher/update_from_github.py", line 198, in get_github_versions
    versions = parse_update_versions(readme_target)
  File "/tmp/mnt/SDA1/xxnet/code/default/launcher/update_from_github.py", line 172, in parse_update_versions
    raise Exception("get_version_fail:%s" % readme_file)
Exception: get_version_fail:/tmp/mnt/SDA1/xxnet/data/downloads/version.txt

2020-12-06 21:58:01.054 [x_tunnel][WARNING] get_front fail
2020-12-06 21:58:05.364 [gae_proxy][WARNING] not enough ip
2020-12-06 21:58:06.875 [tls_relay][WARNING] not enough ip
2020-12-06 21:58:06.876 [cloudflare_front][WARNING] not enough ip
2020-12-06 21:58:07.144 [x_tunnel][WARNING] get_front fail
2020-12-06 21:58:08.894 [gae_proxy][WARNING] not enough ip
2020-12-06 21:58:13.234 [x_tunnel][WARNING] get_front fail
2020-12-06 21:58:14.254 [x_tunnel][WARNING] api:/login fail:status:602 t:30
2020-12-06 21:58:15.394 [gae_proxy][WARNING] not enough ip
2020-12-06 21:58:17.904 [tls_relay][WARNING] not enough ip
2020-12-06 21:58:17.904 [cloudflare_front][WARNING] not enough ip
2020-12-06 21:58:18.924 [gae_proxy][WARNING] not enough ip
2020-12-06 21:58:22.592 [x_tunnel][DEBUG] x-tunnel web_control 192.168.50.3:61892 POST /login 
2020-12-06 21:58:25.424 [gae_proxy][WARNING] not enough ip
2020-12-06 21:58:27.674 [x_tunnel][WARNING] get_front fail
2020-12-06 21:58:28.934 [tls_relay][WARNING] not enough ip
2020-12-06 21:58:28.934 [cloudflare_front][WARNING] not enough ip
2020-12-06 21:58:28.944 [gae_proxy][WARNING] not enough ip
2020-12-06 21:58:30.404 [gae_proxy][DEBUG] create ssl timeout fail.
2020-12-06 21:58:33.764 [x_tunnel][WARNING] get_front fail
2020-12-06 21:58:35.454 [gae_proxy][WARNING] not enough ip
2020-12-06 21:58:38.964 [gae_proxy][WARNING] not enough ip
2020-12-06 21:58:39.864 [x_tunnel][WARNING] get_front fail
2020-12-06 21:58:39.963 [tls_relay][WARNING] not enough ip
2020-12-06 21:58:39.964 [cloudflare_front][WARNING] not enough ip
2020-12-06 21:58:44.634 [cloudflare_front][DEBUG] create ssl timeout fail.
2020-12-06 21:58:44.744 [tls_relay][DEBUG] create ssl timeout fail.
2020-12-06 21:58:45.474 [gae_proxy][WARNING] not enough ip
2020-12-06 21:58:45.954 [x_tunnel][WARNING] get_front fail
2020-12-06 21:58:48.984 [gae_proxy][WARNING] not enough ip
2020-12-06 21:58:50.871 [launcher][DEBUG] launcher web_control 192.168.50.3:49534 GET /update?cmd=get_info 
2020-12-06 21:58:51.003 [tls_relay][WARNING] not enough ip
2020-12-06 21:58:51.004 [cloudflare_front][WARNING] not enough ip
2020-12-06 21:58:52.054 [x_tunnel][WARNING] get_front fail
2020-12-06 21:58:53.064 [x_tunnel][WARNING] api:/login fail:status:602 t:30
2020-12-06 21:58:54.663 [x_tunnel][DEBUG] x-tunnel web_control 192.168.50.3:61892 POST /login 
2020-12-06 21:58:55.494 [gae_proxy][WARNING] not enough ip
2020-12-06 21:58:56.824 [gae_proxy][DEBUG] create ssl timeout fail.
2020-12-06 21:58:59.004 [gae_proxy][WARNING] not enough ip

　登陆报　　602错误

**Comment by xxnet** [comment]
先在电脑上跑通了，再把整个目录拷贝到路由器上去
