### ISSUE TITLE
2021 年 xx-net 还能正常使用吗

### ISSUE THREAD

**Issue by note4** [XX-net/XX-Net#13452]
请问大家能正常使用吗？稳定吗？

**Comment by dylanleesky** [comment]
很不稳定，自设的teredo隧道，IP数量27，延迟一千五，连接网页全都出蓝条。
日志显示一个很奇怪的东西。
2021-01-10 23:40:53.492 - [WARNING] 2a00:1450:4002:807::2014 h1_request:ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None) inactive_time:133 task.timeout:60
2021-01-10 23:40:53.493 - [WARNING] 2a00:1450:4002:807::2014 trace: 0:connect, 1429:init, 9137:request,:128512,

**Comment by nly4lov** [comment]
周一开始，似乎不再受限，自由fq中

**Comment by miketwes** [comment]
一直以来正常使用
![2](https://user-images.githubusercontent.com/6849681/104595478-a3100880-56ad-11eb-838c-a15fd79abf00.png)

**Comment by tq01o3n** [comment]
> 一直以来正常使用
> ![2](https://user-images.githubusercontent.com/6849681/104595478-a3100880-56ad-11eb-838c-a15fd79abf00.png)

能否分享下xx-net-mini小白教程？

**Comment by miketwes** [comment]
> > 一直以来正常使用
> > ![2](https://user-images.githubusercontent.com/6849681/104595478-a3100880-56ad-11eb-838c-a15fd79abf00.png)
> 
> 能否分享下xx-net-mini小白教程？

https://github.com/miketwes/XX-Net-mini

**Comment by nly4lov** [comment]
收到谷歌邮件，不创建付款账户的话，1月31日之后就怎样怎样....

**Comment by tq01o3n** [comment]
> > > 一直以来正常使用
> > > ![2](https://user-images.githubusercontent.com/6849681/104595478-a3100880-56ad-11eb-838c-a15fd79abf00.png)
> > 
> > 
> > 能否分享下xx-net-mini小白教程？
> 
> https://github.com/miketwes/XX-Net-mini

万分感谢!

**Comment by tq01o3n** [comment]
> 收到谷歌邮件，不创建付款账户的话，1月31日之后就怎样怎样....

我也收到了,是网络硬盘要收费吗?

**Comment by miketwes** [comment]
> start.bat却秒闪退

![z2](https://user-images.githubusercontent.com/6849681/105275645-c7eb0b00-5bda-11eb-9840-7a722fbcf751.png)

**Comment by miketwes** [comment]
> start.bat却秒闪退

![z2](https://user-images.githubusercontent.com/6849681/105275645-c7eb0b00-5bda-11eb-9840-7a722fbcf751.png)

**Comment by miketwes** [comment]
> > 收到谷歌邮件，不创建付款账户的话，1月31日之后就怎样怎样....
> 
> 我也收到了,是网络硬盘要收费吗?

没有收到

**Comment by miketwes** [comment]
> > bat却秒闪退
> 
> 找不到闪退原因和解决办法

运行cmd
1.  cd /d f:\XX-Net-mini-master\code\default\launcher
2.  py;thon stary.py

**Comment by miketwes** [comment]
> > bat却秒闪退
> 
> 找不到闪退原因和解决办法

运行cmd
1.  cd /d f:\XX-Net-mini-master\code\default\launcher
2.  py;thon stary.py

**Comment by tq01o3n** [comment]
> > > bat却秒闪退
> > 
> > 
> > 找不到闪退原因和解决办法
> 
> 运行cmd
> 
> 1. cd /d f:\XX-Net-mini-master\code\default\launcher
> 2. python stary.py
找不到在哪里上传cmd截图,复制文字给你吧

Microsoft Windows [版本 10.0.19042.746]
(c) 2020 Microsoft Corporation. 保留所有权利。

C:\WINDOWS\system32>cd /d g:\xx-net-mini\code\default\launcher

g:\XX-Net-mini\code\default\launcher>python stary.py
'python' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

g:\XX-Net-mini\code\default\launcher>

**Comment by miketwes** [comment]
> 'python' 不是内部或外部命令，也不是可运行的程序
> 或批处理文件。

使用前请确保系统已经安装了最新版本的Python 和 openssl, 在命令行运行 python --version 和 openssl version查看是否已经安装

**Comment by tq01o3n** [comment]
> > 'python' 不是内部或外部命令，也不是可运行的程序
> > 或批处理文件。
> 
> 使用前请确保系统已经安装了最新版本的Python 和 openssl, 在命令行运行 python --version 和 openssl version查看是否已经安装

明明都装了,为什么都提示
c:\>python --version
'python' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

c:\>openssl version
'openssl' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

我看了说明(https://github.com/miketwes/XX-Net-mini),提到Python安装时选择添加Windows环境变量,请问怎么选择添加WIN环境变量?

**Comment by miketwes** [comment]
> > > 'python' 不是内部或外部命令，也不是可运行的程序
> > > 或批处理文件。
> > 
> > 
> > 使用前请确保系统已经安装了最新版本的Python 和 openssl, 在命令行运行 python --version 和 openssl version查看是否已经安装
> 
> 明明都装了,为什么都提示
> c:>python --version
> 'python' 不是内部或外部命令，也不是可运行的程序
> 或批处理文件。
> 
> c:>openssl version
> 'openssl' 不是内部或外部命令，也不是可运行的程序
> 或批处理文件。
> 
> 我看了说明([https://github.com/miketwes/XX-Net-mini),提到Python安装时选择添加Windows环境变量,请问怎么选择添加WIN环境变量](https://github.com/miketwes/XX-Net-mini),%E6%8F%90%E5%88%B0Python%E5%AE%89%E8%A3%85%E6%97%B6%E9%80%89%E6%8B%A9%E6%B7%BB%E5%8A%A0Windows%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F,%E8%AF%B7%E9%97%AE%E6%80%8E%E4%B9%88%E9%80%89%E6%8B%A9%E6%B7%BB%E5%8A%A0WIN%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F)?

[XX-Net-mini-win10_x64.zip](https://github.com/miketwes/miketwes.github.io/blob/main/file/XX-Net-mini-win10_x64.zip)
集成了最新版本的Python 和 openssl
Win10_x64用户解压后运行start.bat

**Comment by tq01o3n** [comment]
> > > > 'python' 不是内部或外部命令，也不是可运行的程序
> > > > 或批处理文件。
> > > 
> > > 
> > > 使用前请确保系统已经安装了最新版本的Python 和 openssl, 在命令行运行 python --version 和 openssl version查看是否已经安装
> > 
> > 
> > 明明都装了,为什么都提示
> > c:>python --version
> > 'python' 不是内部或外部命令，也不是可运行的程序
> > 或批处理文件。
> > c:>openssl version
> > 'openssl' 不是内部或外部命令，也不是可运行的程序
> > 或批处理文件。
> > 我看了说明([https://github.com/miketwes/XX-Net-mini),提到Python安装时选择添加Windows环境变量,请问怎么选择添加WIN环境变量](https://github.com/miketwes/XX-Net-mini),%E6%8F%90%E5%88%B0Python%E5%AE%89%E8%A3%85%E6%97%B6%E9%80%89%E6%8B%A9%E6%B7%BB%E5%8A%A0Windows%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F,%E8%AF%B7%E9%97%AE%E6%80%8E%E4%B9%88%E9%80%89%E6%8B%A9%E6%B7%BB%E5%8A%A0WIN%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F)?
> 
> [XX-Net-mini-win10_x64.zip](https://github.com/miketwes/miketwes.github.io/blob/main/file/XX-Net-mini-win10_x64.zip)
> 集成了最新版本的Python 和 openssl
> Win10_x64用户解压后运行start.bat

****************************************
XX-Net-mini
****************************************


Microsoft Windows [版本 10.0.19042.746]
SystemType
x64-based PC



OpenSSL 1.1.1i  8 Dec 2020
Python 3.9.1

2021-01-22 16:39:47.619 [launcher][ERROR] launcher except:FileNotFoundError(2, 'No such file or directory')
2021-01-22 16:39:47.620 [launcher][ERROR] Except stack:Traceback (most recent call last):
  File "start.py", line 159, in <module>
    main()
  File "start.py", line 113, in main
    with open(fname, 'rb') as infile:
FileNotFoundError: [Errno 2] No such file or directory: 'G:\\XX-Net-mini-win10_x64\\data\\gae_proxy\\CA.crt'

Press Enter to continue...

**Comment by miketwes** [comment]
> > > > > 'python' 不是内部或外部命令，也不是可运行的程序
> > > > > 或批处理文件。
> > > > 
> > > > 
> > > > 使用前请确保系统已经安装了最新版本的Python 和 openssl, 在命令行运行 python --version 和 openssl version查看是否已经安装
> > > 
> > > 
> > > 明明都装了,为什么都提示
> > > c:>python --version
> > > 'python' 不是内部或外部命令，也不是可运行的程序
> > > 或批处理文件。
> > > c:>openssl version
> > > 'openssl' 不是内部或外部命令，也不是可运行的程序
> > > 或批处理文件。
> > > 我看了说明([https://github.com/miketwes/XX-Net-mini),提到Python安装时选择添加Windows环境变量,请问怎么选择添加WIN环境变量](https://github.com/miketwes/XX-Net-mini),%E6%8F%90%E5%88%B0Python%E5%AE%89%E8%A3%85%E6%97%B6%E9%80%89%E6%8B%A9%E6%B7%BB%E5%8A%A0Windows%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F,%E8%AF%B7%E9%97%AE%E6%80%8E%E4%B9%88%E9%80%89%E6%8B%A9%E6%B7%BB%E5%8A%A0WIN%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F)?
> > 
> > 
> > [XX-Net-mini-win10_x64.zip](https://github.com/miketwes/miketwes.github.io/blob/main/file/XX-Net-mini-win10_x64.zip)
> > 集成了最新版本的Python 和 openssl
> > Win10_x64用户解压后运行start.bat
> 
> XX-Net-mini
> 
> Microsoft Windows [版本 10.0.19042.746]
> SystemType
> x64-based PC
> 
> OpenSSL 1.1.1i 8 Dec 2020
> Python 3.9.1
> 
> ```
>             ------------------------------------------------------
>             XX-Net-mini Version 4.5.2
>             Python Version     : 3.8.7
>             Listen Address     : 127.0.0.1:8087
>             Using public APPID
>             ------------------------------------------------------
>             Network is ok, you can start to surf the internet!
> ```
> 
> 终于搞定了,但Chrome提示:
> 您的连接不是私密连接
> 攻击者可能会试图从 [www.behance.net](http://www.behance.net) 窃取您的信息（例如：密码、通讯内容或信用卡信息）。了解详情
> NET::ERR_CERT_AUTHORITY_INVALID
> 如果您想获得 Chrome 最高级别的安全保护，请开启增强型保护
> 
> 怎么破?



Chromium, chrome浏览器代理设置:

        chromium --proxy-server="http://127.0.0.1:8087" --ignore-certificate-errors

**Comment by tq01o3n** [comment]
> > > > > > 'python' 不是内部或外部命令，也不是可运行的程序
> > > > > > 或批处理文件。
> > > > > 
> > > > > 
> > > > > 使用前请确保系统已经安装了最新版本的Python 和 openssl, 在命令行运行 python --version 和 openssl version查看是否已经安装
> > > > 
> > > > 
> > > > 明明都装了,为什么都提示
> > > > c:>python --version
> > > > 'python' 不是内部或外部命令，也不是可运行的程序
> > > > 或批处理文件。
> > > > c:>openssl version
> > > > 'openssl' 不是内部或外部命令，也不是可运行的程序
> > > > 或批处理文件。
> > > > 我看了说明([https://github.com/miketwes/XX-Net-mini),提到Python安装时选择添加Windows环境变量,请问怎么选择添加WIN环境变量](https://github.com/miketwes/XX-Net-mini),%E6%8F%90%E5%88%B0Python%E5%AE%89%E8%A3%85%E6%97%B6%E9%80%89%E6%8B%A9%E6%B7%BB%E5%8A%A0Windows%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F,%E8%AF%B7%E9%97%AE%E6%80%8E%E4%B9%88%E9%80%89%E6%8B%A9%E6%B7%BB%E5%8A%A0WIN%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F)?
> > > 
> > > 
> > > [XX-Net-mini-win10_x64.zip](https://github.com/miketwes/miketwes.github.io/blob/main/file/XX-Net-mini-win10_x64.zip)
> > > 集成了最新版本的Python 和 openssl
> > > Win10_x64用户解压后运行start.bat
> > 
> > 
> > XX-Net-mini
> > Microsoft Windows [版本 10.0.19042.746]
> > SystemType
> > x64-based PC
> > OpenSSL 1.1.1i 8 Dec 2020
> > Python 3.9.1
> > ```
> >             ------------------------------------------------------
> >             XX-Net-mini Version 4.5.2
> >             Python Version     : 3.8.7
> >             Listen Address     : 127.0.0.1:8087
> >             Using public APPID
> >             ------------------------------------------------------
> >             Network is ok, you can start to surf the internet!
> > ```
> > 
> > 
> > 终于搞定了,但Chrome提示:
> > 您的连接不是私密连接
> > 攻击者可能会试图从 [www.behance.net](http://www.behance.net) 窃取您的信息（例如：密码、通讯内容或信用卡信息）。了解详情
> > NET::ERR_CERT_AUTHORITY_INVALID
> > 如果您想获得 Chrome 最高级别的安全保护，请开启增强型保护
> > 怎么破?
> 
> Chromium, chrome浏览器代理设置:
> 
> ```
>     chromium --proxy-server="http://127.0.0.1:8087" --ignore-certificate-errors
> ```

请问,我是用chrome的,请问这个代码输在哪里?

**Comment by miketwes** [comment]
> 请问,我是用chrome的,请问这个代码输在哪里?

![2](https://user-images.githubusercontent.com/6849681/105488576-cc074d80-5cec-11eb-8ae4-1d67f2b8fe1b.png)

另外第一次运行start.bat要导入证书

![3](https://user-images.githubusercontent.com/6849681/105489030-8a2ad700-5ced-11eb-813b-5749ae00831a.png)

**Comment by tq01o3n** [comment]
> > 请问,我是用chrome的,请问这个代码输在哪里?
> 
> ![2](https://user-images.githubusercontent.com/6849681/105488576-cc074d80-5cec-11eb-8ae4-1d67f2b8fe1b.png)
> 
> 另外第一次运行start.bat要导入证书
> 
> ![3](https://user-images.githubusercontent.com/6849681/105489030-8a2ad700-5ced-11eb-813b-5749ae00831a.png)

千辛万苦终于能上网了，但感觉速度还是很慢，不如x-tunnel快

**Comment by tq01o3n** [comment]
> > 请问,我是用chrome的,请问这个代码输在哪里?
> 
> ![2](https://user-images.githubusercontent.com/6849681/105488576-cc074d80-5cec-11eb-8ae4-1d67f2b8fe1b.png)
> 
> 另外第一次运行start.bat要导入证书
> 
> ![3](https://user-images.githubusercontent.com/6849681/105489030-8a2ad700-5ced-11eb-813b-5749ae00831a.png)

请问cmd频频出现602是什么意思?速度依然很慢很慢
![未标题-2](https://user-images.githubusercontent.com/15064148/105564311-969a4880-5d5c-11eb-90ec-1240240b97a4.jpg)

**Comment by miketwes** [comment]
> 请问cmd频频出现602是什么意思?速度依然很慢很慢
> ![未标题-2](https://user-images.githubusercontent.com/15064148/105564311-969a4880-5d5c-11eb-90ec-1240240b97a4.jpg)

Mini版XX-Ne使用707个固定ip, 但未对这些ip进一步筛查,  遇到不支持gae的ip会提示602

**Comment by miketwes** [comment]
> 请问cmd频频出现602是什么意思?速度依然很慢很慢
> ![未标题-2](https://user-images.githubusercontent.com/15064148/105564311-969a4880-5d5c-11eb-90ec-1240240b97a4.jpg)

Mini版XX-Ne使用707个固定ip, 但未对这些ip进一步筛查,  遇到不支持gae的ip会提示602

**Comment by miketwes** [comment]
> 请问cmd频频出现602是什么意思?速度依然很慢很慢
> ![未标题-2](https://user-images.githubusercontent.com/15064148/105564311-969a4880-5d5c-11eb-90ec-1240240b97a4.jpg)

Mini版XX-Ne使用707个固定ip, 但未对这些ip进一步筛查,  遇到不支持gae的ip会提示602

**Comment by tq01o3n** [comment]
> > 请问cmd频频出现602是什么意思?速度依然很慢很慢
> > ![未标题-2](https://user-images.githubusercontent.com/15064148/105564311-969a4880-5d5c-11eb-90ec-1240240b97a4.jpg)
> 
> Mini版XX-Ne使用707个固定ip, 但未对这些ip进一步筛查, 遇到不支持gae的ip会提示602

那进一步怎么办呢?

**Comment by miketwes** [comment]
> > > 请问cmd频频出现602是什么意思?速度依然很慢很慢
> > > ![未标题-2](https://user-images.githubusercontent.com/15064148/105564311-969a4880-5d5c-11eb-90ec-1240240b97a4.jpg)
> > 
> > 
> > Mini版XX-Ne使用707个固定ip, 但未对这些ip进一步筛查, 遇到不支持gae的ip会提示602
> 
> 那进一步怎么办呢?

暂时没有相关计划

**Comment by AeneasZhu** [comment]
@miketwes 用了自己的appid后就无法扫描gaeip了，切换成公共appid后才能正常扫描

**Comment by miketwes** [comment]
> @miketwes 用了自己的appid后就无法扫描gaeip了，切换成公共appid后才能正常扫描
Mini版XX-Ne使用固定ip,  不扫描ip

**Comment by sunsun-dot** [comment]
大神请问我在设置谷歌浏览器快捷方式时加入--proxy-server="http://127.0.0.1:8087" --ignore-certificate-errors后出现这个错误怎么解决鸭？求指教，不然可真就功亏一篑了
![image](https://user-images.githubusercontent.com/81130743/111935884-6d4d2d00-8aff-11eb-9e7a-52e3129eab53.png)

**Comment by sunsun-dot** [comment]
> > > > > > 'python' 不是内部或外部命令，也不是可运行的程序
> > > > > > 或批处理文件。
> > > > > 
> > > > > 
> > > > > 使用前请确保系统已经安装了最新版本的Python 和 openssl, 在命令行运行 python --version 和 openssl version查看是否已经安装
> > > > 
> > > > 
> > > > 明明都装了,为什么都提示
> > > > c:>python --version
> > > > 'python' 不是内部或外部命令，也不是可运行的程序
> > > > 或批处理文件。
> > > > c:>openssl version
> > > > 'openssl' 不是内部或外部命令，也不是可运行的程序
> > > > 或批处理文件。
> > > > 我看了说明([https://github.com/miketwes/XX-Net-mini),提到Python安装时选择添加Windows环境变量,请问怎么选择添加WIN环境变量](https://github.com/miketwes/XX-Net-mini),%E6%8F%90%E5%88%B0Python%E5%AE%89%E8%A3%85%E6%97%B6%E9%80%89%E6%8B%A9%E6%B7%BB%E5%8A%A0Windows%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F,%E8%AF%B7%E9%97%AE%E6%80%8E%E4%B9%88%E9%80%89%E6%8B%A9%E6%B7%BB%E5%8A%A0WIN%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F)?
> > > 
> > > 
> > > [XX-Net-mini-win10-x64.rar](https://github.com/miketwes/miketwes.github.io/blob/main/file/XX-Net-mini-win10-x64.rar)
> > > 集成了最新版本的Python 和 openssl
> > > Win10_x64用户解压后运行start.bat
> > 
> > 
> > XX-Net-mini
> > Microsoft Windows [版本 10.0.19042.746]
> > SystemType
> > x64-based PC
> > OpenSSL 1.1.1i 8 Dec 2020
> > Python 3.9.1
> > ```
> >             ------------------------------------------------------
> >             XX-Net-mini Version 4.5.2
> >             Python Version     : 3.8.7
> >             Listen Address     : 127.0.0.1:8087
> >             Using public APPID
> >             ------------------------------------------------------
> >             Network is ok, you can start to surf the internet!
> > ```
> > 
> > 
> > 终于搞定了,但Chrome提示:
> > 您的连接不是私密连接
> > 攻击者可能会试图从 [www.behance.net](http://www.behance.net) 窃取您的信息（例如：密码、通讯内容或信用卡信息）。了解详情
> > NET::ERR_CERT_AUTHORITY_INVALID
> > 如果您想获得 Chrome 最高级别的安全保护，请开启增强型保护
> > 怎么破?
> 
> Chromium, chrome浏览器代理设置:
> 
> ```
>     chromium --proxy-server="http://127.0.0.1:8087" --ignore-certificate-errors
> ```
大神请问我在设置谷歌浏览器快捷方式时加入--proxy-server="http://127.0.0.1:8087" --ignore-certificate-errors后出现这个错误怎么解决鸭？求指教，不然可真就功亏一篑了
![image](https://user-images.githubusercontent.com/81130743/111936010-adacab00-8aff-11eb-81f7-137710ab100c.png)

**Comment by miketwes** [comment]
> > > > > > > 'python' 不是内部或外部命令，也不是可运行的程序
> > > > > > > 或批处理文件。
> > > > > > 
> > > > > > 
> > > > > > 使用前请确保系统已经安装了最新版本的Python 和 openssl, 在命令行运行 python --version 和 openssl version查看是否已经安装
> > > > > 
> > > > > 
> > > > > 明明都装了,为什么都提示
> > > > > c:>python --version
> > > > > 'python' 不是内部或外部命令，也不是可运行的程序
> > > > > 或批处理文件。
> > > > > c:>openssl version
> > > > > 'openssl' 不是内部或外部命令，也不是可运行的程序
> > > > > 或批处理文件。
> > > > > 我看了说明([https://github.com/miketwes/XX-Net-mini),提到Python安装时选择添加Windows环境变量,请问怎么选择添加WIN环境变量](https://github.com/miketwes/XX-Net-mini),%E6%8F%90%E5%88%B0Python%E5%AE%89%E8%A3%85%E6%97%B6%E9%80%89%E6%8B%A9%E6%B7%BB%E5%8A%A0Windows%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F,%E8%AF%B7%E9%97%AE%E6%80%8E%E4%B9%88%E9%80%89%E6%8B%A9%E6%B7%BB%E5%8A%A0WIN%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F)?
> > > > 
> > > > 
> > > > [XX-Net-mini-win10-x64.rar](https://github.com/miketwes/miketwes.github.io/blob/main/file/XX-Net-mini-win10-x64.rar)
> > > > 集成了最新版本的Python 和 openssl
> > > > Win10_x64用户解压后运行start.bat
> > > 
> > > 
> > > XX-Net-mini
> > > Microsoft Windows [版本 10.0.19042.746]
> > > SystemType
> > > x64-based PC
> > > OpenSSL 1.1.1i 8 Dec 2020
> > > Python 3.9.1
> > > ```
> > >             ------------------------------------------------------
> > >             XX-Net-mini Version 4.5.2
> > >             Python Version     : 3.8.7
> > >             Listen Address     : 127.0.0.1:8087
> > >             Using public APPID
> > >             ------------------------------------------------------
> > >             Network is ok, you can start to surf the internet!
> > > ```
> > > 
> > > 
> > > 终于搞定了,但Chrome提示:
> > > 您的连接不是私密连接
> > > 攻击者可能会试图从 [www.behance.net](http://www.behance.net) 窃取您的信息（例如：密码、通讯内容或信用卡信息）。了解详情
> > > NET::ERR_CERT_AUTHORITY_INVALID
> > > 如果您想获得 Chrome 最高级别的安全保护，请开启增强型保护
> > > 怎么破?
> > 
> > 
> > Chromium, chrome浏览器代理设置:
> > ```
> >     chromium --proxy-server="http://127.0.0.1:8087" --ignore-certificate-errors
> > ```
> 
> 大神请问我在设置谷歌浏览器快捷方式时加入--proxy-server="http://127.0.0.1:8087" --ignore-certificate-errors后出现这个错误怎么解决鸭？求指教，不然可真就功亏一篑了
> ![image](https://user-images.githubusercontent.com/81130743/111936010-adacab00-8aff-11eb-81f7-137710ab100c.png)

![](https://user-images.githubusercontent.com/6849681/105488576-cc074d80-5cec-11eb-8ae4-1d67f2b8fe1b.png)

**Comment by Redamancys** [comment]
这个软件也很好用，不要在一棵树上吊死，https://github.com/dodois/Doisnet

**Comment by dylanleesky** [comment]
我的可用，开启原生IPV6后，IP资可快就满了。不过发现这个容易受影响，一旦开会啥的，资源就会大批量死球。稳定性没有鸽子的稳定。

**Comment by ottolize** [comment]
> 这个软件也很好用，不要在一棵树上吊死，https://github.com/dodois/Doisnet
没了

**Comment by ottolize** [comment]
> 这个软件也很好用，不要在一棵树上吊死，https://github.com/dodois/Doisnet

没了
