### ISSUE TITLE
路由器openwrt环境自动更新安装了Python3.9版本导致xx-net启动后报错

### ISSUE THREAD

**Issue by shipf0820** [XX-net/XX-Net#13488]
2021-03-16 16:48:34.934 - [INFO] load /tmp/mnt/TOSHIBA/data/XX-Net/code/4.5.3/x_tunnel/local/cloudflare_front/front_domains.json success

2021-03-16 16:48:34.937 - [INFO] SSL use version:TLSv1_3

2021-03-16 16:48:34.963 - [ERROR] updated cloudflare front domains from github fail:AttributeError("'NoneType' object has no attribute 'getsockopt'")

2021-03-16 16:48:34.971 - [INFO] OpenSSL support alpn

2021-03-16 16:48:34.972 - [INFO] load ip range file:/tmp/mnt/TOSHIBA/data/XX-Net/code/4.5.3/x_tunnel/local/cloudflare_front/ip_range.txt

2021-03-16 16:48:35.003 - [ERROR] Except stack:Traceback (most recent call last): File "/tmp/mnt/TOSHIBA/data/XX-Net/code/4.5.3/x_tunnel/local/cloudflare_front/host_manager.py", line 69, in update_front_domains response = client.request("GET", url) File "/tmp/mnt/TOSHIBA/data/XX-Net/code/4.5.3/lib/noarch/simple_http_client.py", line 469, in request sock = self.connect(upl.hostname, port, upl.scheme == b"https") File "/tmp/mnt/TOSHIBA/data/XX-Net/code/4.5.3/lib/noarch/simple_http_client.py", line 437, in connect sock = ssl.wrap_socket(sock) File "/opt/lib/python3.9/ssl.py", line 1405, in wrap_socket File "/opt/lib/python3.9/ssl.py", line 500, in wrap_socket File "/opt/lib/python3.9/ssl.py", line 987, in _create AttributeError: 'NoneType' object has no attribute 'getsockopt'

2021-03-16 16:48:35.057 - [INFO] load ip_list num:134, target num:134

2021-03-16 16:49:11.325 - [DEBUG] create_ssl update ip:172.67.225.211 time:345 h2:1 sni:www.tomosaki.ml, host:tomosaki.ml

2021-03-16 16:49:16.624 - [DEBUG] create_ssl update ip:1.0.0.73 time:301 h2:1 sni:standardalcohol.tk, host:standardalcohol.tk

2021-03-16 16:49:17.922 - [DEBUG] create_ssl update ip:1.1.1.89 time:290 h2:1 sni:www.tomosaki.ml, host:tomosaki.ml

2021-03-16 16:49:19.262 - [DEBUG] create_ssl update ip:1.0.0.211 time:320 h2:1 sni:www.meetgod.tk, host:meetgod.tk

2021-03-16 16:49:20.618 - [DEBUG] create_ssl update ip:198.41.208.109 time:336 h2:1 sni:xovowfx.tk, host:xovowfx.tk

**Comment by dutao6678** [comment]
你都用上openwrt软路由，为什么还用插件啊！~

**Comment by niu541412** [comment]
这个getsockopt的错误，好像忽略就行了。我一直都有，不论在本地还是路由器上，可能是服务器连接的问题
