### ISSUE TITLE
win10系统自动更新至20H2版本后 后台打不开了

### ISSUE THREAD

**Issue by maoxt** [XX-net/XX-Net#13513]
2021-05-01 21:41:06.315 [cloudflare_front][INFO] OpenSSL support alpn
2021-05-01 21:41:06.315 [cloudflare_front][INFO] load ip range file:E:\Tools\XX-Net\code\default\x_tunnel\local\cloudflare_front\ip_range.txt
2021-05-01 21:41:06.331 [cloudflare_front][INFO] load ip_list num:135, target num:135
2021-05-01 21:41:06.331 [x_tunnel][INFO] xxnet_version:4.5.3
2021-05-01 21:41:06.331 [x_tunnel][DEBUG] SendBuffer reset
2021-05-01 21:41:06.331 [x_tunnel][ERROR] bind to b'127.0.0.1':1080 fail:OSError(10013, '以一种访问权限不允许的方式做了 一个访问套接字的尝试。', None, 10013, None)
Exception in thread Thread-22:
T**raceback (most recent call last):
  File "E:\Tools\XX-Net\code\default\lib\noarch\simple_http_server.py", line 466, in add_listen
    sock.bind(addr)
OSError: [WinError 10013] 以一种访问权限不允许的方式做了一个访问套接字的尝试。**

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Tools\XX-Net\python3.8.2\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "E:\Tools\XX-Net\python3.8.2\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "E:\Tools\XX-Net\code\default\x_tunnel\local\__init__.py", line 14, in start
    client.main(args)
  File "E:\Tools\XX-Net\code\default\x_tunnel\local\client.py", line 193, in main
    g.socks5_server = simple_http_server.HTTPServer(addresses, Socks5Server, logger=xlog)
  File "E:\Tools\XX-Net\code\default\lib\noarch\simple_http_server.py", line 430, in __init__
    self.init_socket()
  File "E:\Tools\XX-Net\code\default\lib\noarch\simple_http_server.py", line 449, in init_socket
    self.add_listen((ip, port))
  File "E:\Tools\XX-Net\code\default\lib\noarch\simple_http_server.py", line 470, in add_listen
    raise Exception(err_string)
**Exception: bind to b'127.0.0.1':1080 fail:OSError(10013, '以一种访问权限不允许的方式做了一个访问套接字的尝试。', None, 10013, None)**
2021-05-01 21:41:10.104 [gae_proxy][WARNING] network IPv6 fail

**Comment by maoxt** [comment]
这个问题不普遍吗？

**Comment by nly4lov** [comment]
> 这个问题不普遍吗？

不。我也升级到20H2，现在翻得好好的

**Comment by maoxt** [comment]
> 
> 
> > 这个问题不普遍吗？
> 
> 不。我也升级到20H2，现在翻得好好的

奇怪了  我啥也没动啊  重新下载最新版本重新配置也是一样的问题
看错误提示是自带的http服务没有启动起来

**Comment by nly4lov** [comment]
> > > 这个问题不普遍吗？
> > 
> > 
> > 不。我也升级到20H2，现在翻得好好的
> 
> 奇怪了 我啥也没动啊 重新下载最新版本重新配置也是一样的问题
> 看错误提示是自带的http服务没有启动起来

https://github.com/XX-net/XX-Net/issues/12370
参考一下，看有用不

**Comment by lefantian** [comment]
20H2以后好几天都没ip连不上，今天挂了1个多小时找出6个ip好容易爬上来，不知道能减持多久，就感觉系统升级后ip少了，不知道是GFW的问题还是系统升级的问题

**Comment by nly4lov** [comment]
> 


<h2 id="title" style="margin: 0px 0px 20px; font-family: &quot;Microsoft YaHei&quot;, &quot;Segoe UI Light&quot;, &quot;Segoe UI&quot;, &quot;Heiti SC&quot;; font-weight: 700; line-height: 40px; color: rgb(52, 73, 94); text-rendering: optimizelegibility; font-size: 26px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">GAE Proxy Status Info</h2><div id="noob-info" class="fluent" style="padding: 10px; margin: 40px 0px; color: rgb(20, 108, 152); background-color: rgb(217, 237, 247); border: 1px solid rgb(188, 232, 241); border-radius: 4px; transition: color 0.3s ease 0s, background 0.3s ease 0s, border 0.3s ease 0s; font-family: &quot;Microsoft YaHei&quot;, &quot;Segoe UI Light&quot;, &quot;Segoe UI&quot;, &quot;Heiti SC&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">XX-Net 4.5.3, Everything is OK. Welcome to the FREE Internet.</div><div id="details" hidden="" style="overflow: hidden; color: rgb(52, 73, 94); font-family: &quot;Microsoft YaHei&quot;, &quot;Segoe UI Light&quot;, &quot;Segoe UI&quot;, &quot;Heiti SC&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: block;"><h4 style="margin: 4px 0px 10px; font-family: inherit; font-weight: 500; line-height: 20px; color: inherit; text-rendering: optimizelegibility; font-size: 18px;">Status</h4>
Property | Value
-- | --
IPv4 Status | OK
IPv6 Status(How enable) | OK
Good IPv4 Number | 0
Good IPv6 Number | 25
All IP Number | 29
XX-Net Status | working
IP Quality | 662
Connection Pool(Help) | new:0 h1:0 h2:17
Browser Proxy Setting | OK
CA status(Download) | OK
Number of IP-Scanning Threads(Settings) | 2

<h4 style="margin: 4px 0px 10px; font-family: inherit; font-weight: 500; line-height: 20px; color: inherit; text-rendering: optimizelegibility; font-size: 18px;">Configuration</h4>
Property | Value
-- | --
Listening At | 127.0.0.1:8087
IP mode | AUTO
LAN proxy | Disable

</div>

**Comment by Maogxer** [comment]
现在 21H1 7月累积更新不正常。卸载更新包又正常了。

**Comment by nly4lov** [comment]
不正常好久了。一会能翻一会不能。要不停地检查ip。或者重启xx

**Comment by Maogxer** [comment]
重启电脑，用管理员身份运行也不一定管用。

原因是Hyper-V保留了很多端口，导致这些端口没有被使用，也无法再使用。

**解决问题**

使用管理的身份运行 CMD ，设置动态端口的范围，使得这个保留端口的范围避开我们需要的端口范围。

```
> netsh int ipv4 set dynamicport tcp start=49152 num=16383
> netsh int ipv4 set dynamicport udp start=49152 num=16383
```

**Comment by maoxt** [comment]
> 
> 
> 重启电脑，用管理员身份运行也不一定管用。
> 
> 原因是Hyper-V保留了很多端口，导致这些端口没有被使用，也无法再使用。
> 
> **解决问题**
> 
> 使用管理的身份运行 CMD ，设置动态端口的范围，使得这个保留端口的范围避开我们需要的端口范围。
> 
> ```
> > netsh int ipv4 set dynamicport tcp start=49152 num=16383
> > netsh int ipv4 set dynamicport udp start=49152 num=16383
> ```

兄弟 目前测试有用  看意思就是被占用了默认的端口

**Comment by nly4lov** [comment]
> 用管理员身份运行就可以了。不知道为什么会这样。

用管理员身份运行啥？

**Comment by nly4lov** [comment]
> 重启电脑，用管理员身份运行也不一定管用。
> 
> 原因是Hyper-V保留了很多端口，导致这些端口没有被使用，也无法再使用。
> 
> **解决问题**
> 
> 使用管理的身份运行 CMD ，设置动态端口的范围，使得这个保留端口的范围避开我们需要的端口范围。
> 
> ```
> > netsh int ipv4 set dynamicport tcp start=49152 num=16383
> > netsh int ipv4 set dynamicport udp start=49152 num=16383
> ```

我搞了这个，加上管理员运行，现在出现另一种状况：xx说可以翻墙，实际上啥也打不开了
