### ISSUE TITLE
X-Tunnle无法使用

### ISSUE THREAD

**Issue by zhong1592158816** [XX-net/XX-Net#13527]
Cloudflare前端 日志

2021-05-23 13:15:38.944 - [INFO] load D:\Program Files\XX-Net\data\x_tunnel\cloudflare_domains.json success

2021-05-23 13:15:38.945 - [INFO] SSL use version:TLSv1_3

2021-05-23 13:15:38.946 - [ERROR] updated cloudflare front domains from github fail:AttributeError("'NoneType' object has no attribute 'getsockopt'")

2021-05-23 13:15:38.949 - [ERROR] Except stack:Traceback (most recent call last): File "D:\Program Files\XX-Net\code\4.5.3\x_tunnel\local\cloudflare_front\host_manager.py", line 69, in update_front_domains response = client.request("GET", url) File "D:\Program Files\XX-Net\code\4.5.3\lib\noarch\simple_http_client.py", line 469, in request sock = self.connect(upl.hostname, port, upl.scheme == b"https") File "D:\Program Files\XX-Net\code\4.5.3\lib\noarch\simple_http_client.py", line 437, in connect sock = ssl.wrap_socket(sock) File "D:\Program Files\XX-Net\python3.8.2\lib\ssl.py", line 1405, in wrap_socket return context.wrap_socket( File "D:\Program Files\XX-Net\python3.8.2\lib\ssl.py", line 500, in wrap_socket return self.sslsocket_class._create( File "D:\Program Files\XX-Net\python3.8.2\lib\ssl.py", line 987, in _create if sock.getsockopt(SOL_SOCKET, SO_TYPE) != SOCK_STREAM: AttributeError: 'NoneType' object has no attribute 'getsockopt'

2021-05-23 13:15:38.953 - [INFO] OpenSSL support alpn

2021-05-23 13:15:38.953 - [INFO] load ip range file:D:\Program Files\XX-Net\code\4.5.3\x_tunnel\local\cloudflare_front\ip_range.txt

2021-05-23 13:15:38.962 - [INFO] load ip_list num:118, target num:118

2021-05-23 13:15:40.599 - [DEBUG] create_ssl update ip:103.21.244.157 time:786 h2:1 sni:xovowfx.tk, host:xovowfx.tk

2021-05-23 13:15:42.340 - [ERROR] check_cert OSError("check sni:www.bookhome.ga fail, alt_names:('ssl406477.yunjiasussl.com',)")

2021-05-23 13:15:42.341 - [ERROR] Except stack:Traceback (most recent call last): File "D:\Program Files\XX-Net\code\4.5.3\lib\noarch\front_base\connect_creator.py", line 149, in check_cert raise socket.error('check sni:undefined fail, alt_names:undefined' % (ssl_sock.sni, peer_cert["altName"])) OSError: check sni:www.bookhome.ga fail, alt_names:('ssl406477.yunjiasussl.com',)

2021-05-23 13:15:42.341 - [DEBUG] create_ssl update ip:162.159.228.151 time:739 h2:1 sni:www.bookhome.ga, host:bookhome.ga

2021-05-23 13:15:52.068 - [ERROR] check_cert OSError("check sni:www.bookhome.ga fail, alt_names:('ssl382531.cloudflaressl.com',)")

2021-05-23 13:15:52.069 - [ERROR] Except stack:Traceback (most recent call last): File "D:\Program Files\XX-Net\code\4.5.3\lib\noarch\front_base\connect_creator.py", line 149, in check_cert raise socket.error('check sni:undefined fail, alt_names:undefined' % (ssl_sock.sni, peer_cert["altName"])) OSError: check sni:www.bookhome.ga fail, alt_names:('ssl382531.cloudflaressl.com',)

2021-05-23 13:15:52.071 - [DEBUG] create_ssl update ip:104.27.196.93 time:672 h2:1 sni:www.bookhome.ga, host:bookhome.ga

2021-05-23 13:15:53.714 - [DEBUG] create_ssl update ip:162.159.238.119 time:641 h2:1 sni:standardalcohol.tk, host:standardalcohol.tk

**Comment by guoguo5211314** [comment]
2021-05-25 15:39:17.216 - [INFO] xxnet_version:4.5.3

2021-05-25 15:39:17.217 - [DEBUG] SendBuffer reset

2021-05-25 15:39:17.218 - [INFO] server 127.0.0.1:1080 started.

2021-05-25 15:39:17.218 - [INFO] Socks5 server listen:127.0.0.1:1080.

2021-05-25 15:39:17.377 - [DEBUG] session not running, try login..

2021-05-25 15:39:18.604 - [WARNING] front retry center.xx-net.org/login

2021-05-25 15:39:21.917 - [WARNING] front retry center.xx-net.org/login

2021-05-25 15:39:26.164 - [WARNING] front retry center.xx-net.org/login

2021-05-25 15:39:27.384 - [WARNING] front retry center.xx-net.org/login

2021-05-25 15:39:28.634 - [WARNING] front retry center.xx-net.org/login

2021-05-25 15:39:31.110 - [WARNING] front retry center.xx-net.org/login

2021-05-25 15:39:32.328 - [WARNING] front retry center.xx-net.org/login

2021-05-25 15:39:33.547 - [WARNING] front retry center.xx-net.org/login

2021-05-25 15:39:36.837 - [WARNING] front retry center.xx-net.org/login

2021-05-25 15:39:39.070 - [WARNING] front retry center.xx-net.org/login

2021-05-25 15:39:45.113 - [WARNING] get_front fail

2021-05-25 15:39:47.391 - [WARNING] front retry center.xx-net.org/login

2021-05-25 15:39:53.458 - [WARNING] get_front fail

2021-05-25 15:39:54.473 - [WARNING] api:/login fail:status:602 t:37

2021-05-25 15:39:54.473 - [WARNING] x-tunnel request_balance fail when create_conn:status:602

2021-05-25 15:39:54.473 - [DEBUG] session not running, try login..

2021-05-25 15:39:56.312 - [DEBUG] socks handler read error OSError('recv fail')

2021-05-25 15:39:56.313 - [DEBUG] socks handler read error OSError('recv fail')

2021-05-25 15:39:59.521 - [WARNING] get_front fail

2021-05-25 15:40:05.559 - [WARNING] get_front fail

2021-05-25 15:40:11.611 - [WARNING] get_front fail

2021-05-25 15:40:17.652 - [WARNING] get_front fail

2021-05-25 15:40:23.697 - [WARNING] get_front fail

2021-05-25 15:40:24.704 - [WARNING] api:/login fail:status:602 t:30

2021-05-25 15:40:24.705 - [WARNING] x-tunnel request_balance fail when create_conn:status:602

2021-05-25 15:40:24.705 - [DEBUG] session not running, try login..

2021-05-25 15:40:29.771 - [WARNING] get_front fail

2021-05-25 15:40:35.806 - [WARNING] get_front fail

2021-05-25 15:40:41.853 - [WARNING] get_front fail

2021-05-25 15:40:47.919 - [WARNING] get_front fail

2021-05-25 15:40:49.128 - [WARNING] front retry center.xx-net.org/login

2021-05-25 15:40:55.184 - [WARNING] get_front fail

2021-05-25 15:40:56.190 - [WARNING] api:/login fail:status:602 t:31

2021-05-25 15:40:56.190 - [WARNING] x-tunnel request_balance fail when create_conn:status:602

2021-05-25 15:40:56.190 - [DEBUG] session not running, try login..

2021-05-25 15:41:01.225 - [WARNING] get_front fail

2021-05-25 15:41:07.260 - [WARNING] get_front fail

2021-05-25 15:41:13.308 - [WARNING] get_front fail

2021-05-25 15:41:19.346 - [WARNING] get_front fail

2021-05-25 15:41:25.373 - [WARNING] get_front fail

2021-05-25 15:41:26.388 - [WARNING] api:/login fail:status:602 t:30

2021-05-25 15:41:26.389 - [WARNING] x-tunnel request_balance fail when create_conn:status:602

2021-05-25 15:41:26.389 - [DEBUG] session not running, try login..

2021-05-25 15:41:31.432 - [WARNING] get_front fail

2021-05-25 15:41:37.470 - [WARNING] get_front fail

2021-05-25 15:41:43.534 - [WARNING] get_front fail

2021-05-25 15:41:49.565 - [WARNING] get_front fail

2021-05-25 15:41:50.803 - [WARNING] front retry center.xx-net.org/login

2021-05-25 15:41:56.845 - [WARNING] get_front fail

2021-05-25 15:41:57.861 - [WARNING] api:/login fail:status:602 t:31

2021-05-25 15:41:57.861 - [WARNING] x-tunnel request_balance fail when create_conn:status:602

2021-05-25 15:41:57.861 - [DEBUG] session not running, try login..

2021-05-25 15:42:02.893 - [WARNING] get_front fail

2021-05-25 15:42:08.926 - [WARNING] get_front fail

2021-05-25 15:42:14.981 - [WARNING] get_front fail

2021-05-25 15:42:21.038 - [WARNING] get_front fail

2021-05-25 15:42:27.102 - [WARNING] get_front fail

2021-05-25 15:42:28.111 - [WARNING] api:/login fail:status:602 t:30

2021-05-25 15:42:28.111 - [WARNING] x-tunnel request_balance fail when create_conn:status:602

2021-05-25 15:42:28.111 - [DEBUG] session not running, try login..

2021-05-25 15:42:33.147 - [WARNING] get_front fail

2021-05-25 15:42:39.192 - [WARNING] get_front fail

2021-05-25 15:42:45.247 - [WARNING] get_front fail

2021-05-25 15:42:51.296 - [WARNING] get_front fail

2021-05-25 15:42:52.514 - [WARNING] front retry center.xx-net.org/login

2021-05-25 15:42:58.539 - [WARNING] get_front fail

2021-05-25 15:42:59.546 - [WARNING] api:/login fail:status:602 t:31

2021-05-25 15:42:59.546 - [WARNING] x-tunnel request_balance fail when create_conn:status:602

2021-05-25 15:42:59.547 - [DEBUG] session not running, try login..

2021-05-25 15:43:04.571 - [WARNING] get_front fail

2021-05-25 15:43:10.602 - [WARNING] get_front fail

2021-05-25 15:43:16.638 - [WARNING] get_front fail

2021-05-25 15:43:22.674 - [WARNING] get_front fail

2021-05-25 15:43:28.717 - [WARNING] get_front fail

2021-05-25 15:43:29.722 - [WARNING] api:/login fail:status:602 t:30

2021-05-25 15:43:29.722 - [WARNING] x-tunnel request_balance fail when create_conn:status:602

2021-05-25 15:43:29.722 - [DEBUG] session not running, try login..

2021-05-25 15:43:34.781 - [WARNING] get_front fail

2021-05-25 15:43:40.831 - [WARNING] get_front fail

2021-05-25 15:43:46.864 - [WARNING] get_front fail

2021-05-25 15:43:52.916 - [WARNING] get_front fail

2021-05-25 15:43:54.172 - [WARNING] front retry center.xx-net.org/login

2021-05-25 15:44:00.242 - [WARNING] get_front fail

2021-05-25 15:44:01.257 - [WARNING] api:/login fail:status:602 t:31

2021-05-25 15:44:01.257 - [WARNING] x-tunnel request_balance fail when create_conn:status:602

2021-05-25 15:44:01.257 - [DEBUG] session not running, try login..

2021-05-25 15:44:06.301 - [WARNING] get_front fail

2021-05-25 15:44:12.344 - [WARNING] get_front fail

2021-05-25 15:44:18.383 - [WARNING] get_front fail

2021-05-25 15:44:24.428 - [WARNING] get_front fail

2021-05-25 15:44:30.483 - [WARNING] get_front fail

2021-05-25 15:44:31.496 - [WARNING] api:/login fail:status:602 t:30

2021-05-25 15:44:31.497 - [WARNING] x-tunnel request_balance fail when create_conn:status:602

2021-05-25 15:44:31.497 - [DEBUG] session not running, try login..

2021-05-25 15:44:36.522 - [WARNING] get_front fail

2021-05-25 15:44:42.592 - [WARNING] get_front fail

2021-05-25 15:44:48.665 - [WARNING] get_front fail

2021-05-25 15:44:54.720 - [WARNING] get_front fail

2021-05-25 15:44:55.941 - [WARNING] front retry center.xx-net.org/login

2021-05-25 15:45:01.997 - [WARNING] get_front fail

2021-05-25 15:45:03.012 - [WARNING] api:/login fail:status:602 t:31

2021-05-25 15:45:03.012 - [WARNING] x-tunnel request_balance fail when create_conn:status:602

2021-05-25 15:45:03.012 - [DEBUG] session not running, try login..

2021-05-25 15:45:08.059 - [WARNING] get_front fail

2021-05-25 15:45:14.118 - [WARNING] get_front fail

2021-05-25 15:45:20.170 - [WARNING] get_front fail

2021-05-25 15:45:26.201 - [WARNING] get_front fail

2021-05-25 15:45:32.239 - [WARNING] get_front fail

2021-05-25 15:45:33.253 - [WARNING] api:/login fail:status:602 t:30

2021-05-25 15:45:33.254 - [WARNING] x-tunnel request_balance fail when create_conn:status:602

2021-05-25 15:45:33.254 - [DEBUG] session not running, try login..

2021-05-25 15:45:38.305 - [WARNING] get_front fail

2021-05-25 15:45:44.349 - [WARNING] get_front fail

2021-05-25 15:45:50.392 - [WARNING] get_front fail

2021-05-25 15:45:56.431 - [WARNING] get_front fail

2021-05-25 15:45:57.872 - [WARNING] front retry center.xx-net.org/login

2021-05-25 15:46:03.937 - [WARNING] get_front fail

2021-05-25 15:46:04.940 - [WARNING] api:/login fail:status:602 t:31

2021-05-25 15:46:04.940 - [WARNING] x-tunnel request_balance fail when create_conn:status:602

2021-05-25 15:46:04.941 - [DEBUG] session not running, try login..

2021-05-25 15:46:09.965 - [WARNING] get_front fail

2021-05-25 15:46:16.014 - [WARNING] get_front fail

2021-05-25 15:46:22.057 - [WARNING] get_front fail

2021-05-25 15:46:28.091 - [WARNING] get_front fail

2021-05-25 15:46:34.156 - [WARNING] get_front fail

2021-05-25 15:46:35.163 - [WARNING] api:/login fail:status:602 t:30

2021-05-25 15:46:35.163 - [WARNING] x-tunnel request_balance fail when create_conn:status:602

2021-05-25 15:46:35.164 - [DEBUG] session not running, try login..

2021-05-25 15:46:40.210 - [WARNING] get_front fail

2021-05-25 15:46:46.248 - [WARNING] get_front fail

2021-05-25 15:46:52.291 - [WARNING] get_front fail

2021-05-25 15:46:58.331 - [WARNING] get_front fail

2021-05-25 15:46:59.557 - [WARNING] front retry center.xx-net.org/login

2021-05-25 15:47:05.606 - [WARNING] get_front fail

2021-05-25 15:47:06.618 - [WARNING] api:/login fail:status:602 t:31

2021-05-25 15:47:06.619 - [WARNING] x-tunnel request_balance fail when create_conn:status:602

2021-05-25 15:47:06.619 - [DEBUG] session not running, try login..

2021-05-25 15:47:11.648 - [WARNING] get_front fail

2021-05-25 15:47:17.701 - [WARNING] get_front fail

2021-05-25 15:47:23.767 - [WARNING] get_front fail

2021-05-25 15:47:29.826 - [WARNING] get_front fail

2021-05-25 15:47:35.884 - [WARNING] get_front fail

2021-05-25 15:47:36.892 - [WARNING] api:/login fail:status:602 t:30

2021-05-25 15:47:36.892 - [WARNING] x-tunnel request_balance fail when create_conn:status:602

2021-05-25 15:47:36.892 - [DEBUG] session not running, try login..

2021-05-25 15:47:41.932 - [WARNING] get_front fail

2021-05-25 15:47:47.977 - [WARNING] get_front fail

2021-05-25 15:47:54.017 - [WARNING] get_front fail

2021-05-25 15:48:00.051 - [WARNING] get_front fail

2021-05-25 15:48:01.271 - [WARNING] front retry center.xx-net.org/login

2021-05-25 15:48:07.307 - [WARNING] get_front fail

2021-05-25 15:48:08.316 - [WARNING] api:/login fail:status:602 t:31

2021-05-25 15:48:08.316 - [WARNING] x-tunnel request_balance fail when create_conn:status:602

2021-05-25 15:48:08.316 - [DEBUG] session not running, try login..

2021-05-25 15:48:13.350 - [WARNING] get_front fail

2021-05-25 15:48:19.402 - [WARNING] get_front fail

2021-05-25 15:48:25.426 - [WARNING] get_front fail

2021-05-25 15:48:31.474 - [WARNING] get_front fail

2021-05-25 15:48:37.514 - [WARNING] get_front fail

2021-05-25 15:48:38.522 - [WARNING] api:/login fail:status:602 t:30

2021-05-25 15:48:38.522 - [WARNING] x-tunnel request_balance fail when create_conn:status:602

2021-05-25 15:48:38.523 - [DEBUG] session not running, try login..

2021-05-25 15:48:43.577 - [WARNING] get_front fail

2021-05-25 15:48:49.614 - [WARNING] get_front fail

2021-05-25 15:48:55.674 - [WARNING] get_front fail

2021-05-25 15:49:01.733 - [WARNING] get_front fail

2021-05-25 15:49:02.959 - [WARNING] front retry center.xx-net.org/login

2021-05-25 15:49:09.009 - [WARNING] get_front fail

2021-05-25 15:49:10.011 - [WARNING] api:/login fail:status:602 t:31

2021-05-25 15:49:10.011 - [WARNING] x-tunnel request_balance fail when create_conn:status:602

2021-05-25 15:49:10.012 - [DEBUG] session not running, try login..

2021-05-25 15:49:15.054 - [WARNING] get_front fail

2021-05-25 15:49:21.103 - [WARNING] get_front fail

2021-05-25 15:49:27.168 - [WARNING] get_front fail

2021-05-25 15:49:33.211 - [WARNING] get_front fail

2021-05-25 15:49:39.251 - [WARNING] get_front fail

2021-05-25 15:49:40.254 - [WARNING] api:/login fail:status:602 t:30

2021-05-25 15:49:40.254 - [WARNING] x-tunnel request_balance fail when create_conn:status:602

2021-05-25 15:49:40.255 - [DEBUG] session not running, try login..

2021-05-25 15:49:45.287 - [WARNING] get_front fail

2021-05-25 15:49:51.350 - [WARNING] get_front fail

2021-05-25 15:49:57.408 - [WARNING] get_front fail

2021-05-25 15:50:03.484 - [WARNING] get_front fail

2021-05-25 15:50:05.143 - [WARNING] front retry center.xx-net.org/login

2021-05-25 15:50:11.203 - [WARNING] get_front fail

2021-05-25 15:50:12.216 - [WARNING] api:/login fail:status:602 t:31

2021-05-25 15:50:12.217 - [WARNING] x-tunnel request_balance fail when create_conn:status:602

2021-05-25 15:50:12.218 - [DEBUG] session not running, try login..

2021-05-25 15:50:17.259 - [WARNING] get_front fail

2021-05-25 15:50:23.291 - [WARNING] get_front fail

2021-05-25 15:50:29.347 - [WARNING] get_front fail

2021-05-25 15:50:35.401 - [WARNING] get_front fail

2021-05-25 15:50:41.452 - [WARNING] get_front fail

2021-05-25 15:50:42.457 - [WARNING] api:/login fail:status:602 t:30

2021-05-25 15:50:42.457 - [WARNING] x-tunnel request_balance fail when create_conn:status:602

2021-05-25 15:50:42.457 - [DEBUG] session not running, try login..

2021-05-25 15:50:47.501 - [WARNING] get_front fail

2021-05-25 15:50:53.535 - [WARNING] get_front fail

2021-05-25 15:50:59.567 - [WARNING] get_front fail

2021-05-25 15:51:05.628 - [WARNING] get_front fail

2021-05-25 15:51:06.887 - [WARNING] front retry center.xx-net.org/login

2021-05-25 15:51:12.925 - [WARNING] get_front fail

2021-05-25 15:51:13.938 - [WARNING] api:/login fail:status:602 t:31

2021-05-25 15:51:13.938 - [WARNING] x-tunnel request_balance fail when create_conn:status:602

**Comment by guoguo5211314** [comment]
2021-05-25 15:57:45.321 - [DEBUG] create ssl timeout fail.

2021-05-25 15:57:51.594 - [DEBUG] connect 94.237.101.11 network fail:OSError("conn fail, sni:enthusiasm-hang.us, top:enthusiasm-hang.us e:ConnectionRefusedError(10061, '由于目标计算机积极拒绝，无法连接。', None, 10061, None)")

2021-05-25 15:57:51.594 - [DEBUG] report_connect_fail:94.237.101.11

2021-05-25 15:57:52.596 - [WARNING] not enough ip

2021-05-25 15:58:02.597 - [WARNING] not enough ip

2021-05-25 15:58:12.612 - [WARNING] not enough ip

2021-05-25 15:58:22.628 - [WARNING] not enough ip

2021-05-25 15:58:32.634 - [WARNING] not enough ip

2021-05-25 15:58:42.635 - [WARNING] not enough ip

2021-05-25 15:58:46.077 - [DEBUG] create ssl timeout fail.

2021-05-25 15:58:52.646 - [WARNING] not enough ip

2021-05-25 15:59:02.660 - [WARNING] not enough ip

2021-05-25 15:59:12.662 - [WARNING] not enough ip

2021-05-25 15:59:22.668 - [WARNING] not enough ip

2021-05-25 15:59:32.671 - [WARNING] not enough ip

2021-05-25 15:59:42.684 - [WARNING] not enough ip

2021-05-25 15:59:46.563 - [DEBUG] create ssl timeout fail.

2021-05-25 15:59:52.699 - [WARNING] not enough ip

2021-05-25 16:00:02.709 - [WARNING] not enough ip

2021-05-25 16:00:12.714 - [WARNING] not enough ip

2021-05-25 16:00:22.729 - [WARNING] not enough ip

**Comment by hurphy** [comment]
先用其他代理把xxtunnel登录上去 再把其他代理撤了

**Comment by zhong1592158816** [comment]
> 先用其他代理把xxtunnel登录上去 再把其他代理撤了

xtunnel账号那里可以登录  但就是不能用  cloudflare日志里一片红

**Comment by zhong1592158816** [comment]
好像是因为端口冲突以后更改了端口  switchyomega没有改  现在ok了

**Comment by Yukkiasuna-sao** [comment]
大佬，
怎么改的啊？

**Comment by zhong1592158816** [comment]
久了有点忘了，我发这个issue的时候是只改了第一个图然后用不了，第二个图也改了以后好像就能用了

话说最近我登陆X-tunnel账号的时候老出问题  不知道你有没有

**Comment by Yukkiasuna-sao** [comment]
我也是，经常无法登陆。

发自我的iPhone
