### ISSUE TITLE
X-TUNNEL 连接服务器失败：session server login fail:602,更换任何服务器都一样,几个星期了

### ISSUE THREAD

**Issue by yuebe** [XX-net/XX-Net#13555]
日志================================================
2021-08-15 13:03:06.719 - [WARNING] get_front fail

2021-08-15 13:03:06.719 - [WARNING] login session fail, status:602

2021-08-15 13:03:06.749 - [DEBUG] start report_stat

2021-08-15 13:03:07.102 - [INFO] api:/report_stat success t:353

2021-08-15 13:03:16.719 - [WARNING] get_front fail

2021-08-15 13:03:16.719 - [WARNING] login session fail, status:602

2021-08-15 13:03:26.720 - [WARNING] get_front fail

2021-08-15 13:03:26.720 - [WARNING] login session fail, status:602

2021-08-15 13:03:26.720 - [WARNING] x-tunnel login_session fail, session not start

2021-08-15 13:03:27.873 - [WARNING] login session server is down, try get new server.

2021-08-15 13:03:27.873 - [WARNING] x-tunnel login_session fail, session not start

2021-08-15 13:03:27.873 - [DEBUG] session not running, try login..

2021-08-15 13:03:28.216 - [INFO] api:/login success t:342

2021-08-15 13:03:28.217 - [INFO] use server:v13.xx-net.org specify in config.

2021-08-15 13:03:28.217 - [INFO] request_balance host:v13.xx-net.org port:443 balance:0.000000 quota:2385450349116.000000

2021-08-15 13:03:38.217 - [WARNING] get_front fail

2021-08-15 13:03:38.217 - [WARNING] login session fail, status:602

2021-08-15 13:03:48.218 - [WARNING] get_front fail

2021-08-15 13:03:48.218 - [WARNING] login session fail, status:602

2021-08-15 13:03:58.219 - [WARNING] get_front fail

2021-08-15 13:03:58.219 - [WARNING] login session fail, status:602

2021-08-15 13:03:58.219 - [WARNING] x-tunnel login_session fail, session not start

2021-08-15 13:04:07.102 - [DEBUG] start report_stat

2021-08-15 13:04:08.174 - [INFO] api:/report_stat success t:1072

2021-08-15 13:04:08.219 - [WARNING] get_front fail

2021-08-15 13:04:08.219 - [WARNING] login session fail, status:602

2021-08-15 13:04:18.220 - [WARNING] get_front fail

2021-08-15 13:04:18.220 - [WARNING] login session fail, status:602

2021-08-15 13:04:28.221 - [WARNING] get_front fail

2021-08-15 13:04:28.221 - [WARNING] login session fail, status:602

2021-08-15 13:04:28.221 - [WARNING] x-tunnel login_session fail, session not start

2021-08-15 13:04:28.704 - [WARNING] login session server is down, try get new server.

2021-08-15 13:04:28.704 - [WARNING] x-tunnel login_session fail, session not start

2021-08-15 13:04:28.704 - [DEBUG] session not running, try login..

2021-08-15 13:04:29.806 - [INFO] api:/login success t:1102

2021-08-15 13:04:29.807 - [INFO] use server:v13.xx-net.org specify in config.

2021-08-15 13:04:29.807 - [INFO] request_balance host:v13.xx-net.org port:443 balance:0.000000 quota:2385450349116.000000

2021-08-15 13:04:39.808 - [WARNING] get_front fail

2021-08-15 13:04:39.808 - [WARNING] login session fail, status:602

2021-08-15 13:04:49.809 - [WARNING] get_front fail

2021-08-15 13:04:49.809 - [WARNING] login session fail, status:602

2021-08-15 13:04:50.441 - [DEBUG] x_tunnel force update info

2021-08-15 13:04:51.505 - [INFO] api:/login success t:1061

2021-08-15 13:04:51.505 - [INFO] use server:v13.xx-net.org specify in config.

2021-08-15 13:04:51.505 - [INFO] request_balance host:v13.xx-net.org port:443 balance:0.000000 quota:2385450349116.000000

2021-08-15 13:04:59.809 - [WARNING] get_front fail

2021-08-15 13:04:59.809 - [WARNING] login session fail, status:602

2021-08-15 13:04:59.809 - [WARNING] x-tunnel login_session fail, session not start

2021-08-15 13:05:08.175 - [DEBUG] start report_stat

2021-08-15 13:05:08.527 - [INFO] api:/report_stat success t:351

2021-08-15 13:05:08.752 - [DEBUG] socks handler read error OSError('recv fail')

2021-08-15 13:05:08.753 - [DEBUG] socks5 auth num:1, list:00

2021-08-15 13:05:08.753 - [WARNING] socks5 protocol error:ConnectionAbortedError(10053, '您的主机中的软件中止了一个已建立的连接。', None, 10053, None)

2021-08-15 13:05:08.755 - [DEBUG] socks5 auth num:1, list:00

2021-08-15 13:05:08.755 - [WARNING] socks5 protocol error:ConnectionAbortedError(10053, '您的主机中的软件中止了一个已建立的连接。', None, 10053, None)

2021-08-15 13:05:08.766 - [DEBUG] socks handler read error OSError('recv fail')

2021-08-15 13:05:08.768 - [DEBUG] socks5 auth num:1, list:00

2021-08-15 13:05:08.768 - [WARNING] socks5 protocol error:ConnectionAbortedError(10053, '您的主机中的软件中止了一个已建立的连接。', None, 10053, None)

Cloudflare前端日志===========================================
2021-08-15 10:23:03.277 - [DEBUG] POST center.standardalcohol.tk/login status:200 trace:0:start_request,0:get_task(3),0:get_worker(0):190.93.247.39,0:h2_req,0:start send header,0:start send left body,0:end send left body,339:h2_get_head,0:get_response,:0

2021-08-15 10:24:48.703 - [ERROR] check_cert OSError("check sni:xovowfx.tk fail, alt_names:('dev.dw.princessetamtam.com', 'dev.dw.princessetamtam.de', 'dev.dw.princessetamtam.co.uk')")

2021-08-15 10:24:48.704 - [ERROR] Except stack:Traceback (most recent call last): File "G:\Minority_prgram\Internet_Tools\_Proxy\XX-Net\code\4.5.3\lib\noarch\front_base\connect_creator.py", line 149, in check_cert raise socket.error('check sni:undefined fail, alt_names:undefined' % (ssl_sock.sni, peer_cert["altName"])) OSError: check sni:xovowfx.tk fail, alt_names:('dev.dw.princessetamtam.com', 'dev.dw.princessetamtam.de', 'dev.dw.princessetamtam.co.uk')

2021-08-15 10:32:53.159 - [ERROR] check_cert OSError("check sni:www.sacramen.tk fail, alt_names:('boroondara.vic.gov.au', 'www.boroondara.vic.gov.au')")

2021-08-15 10:32:53.159 - [ERROR] Except stack:Traceback (most recent call last): File "G:\Minority_prgram\Internet_Tools\_Proxy\XX-Net\code\4.5.3\lib\noarch\front_base\connect_creator.py", line 149, in check_cert raise socket.error('check sni:undefined fail, alt_names:undefined' % (ssl_sock.sni, peer_cert["altName"])) OSError: check sni:www.sacramen.tk fail, alt_names:('boroondara.vic.gov.au', 'www.boroondara.vic.gov.au')

2021-08-15 10:40:20.463 - [ERROR] check_cert OSError("check sni:www.meetgod.tk fail, alt_names:('cloudflare-dns.com', '*.cloudflare-dns.com', 'one.one.one.one', '1.1.1.1', '1.0.0.1', '162.159.36.1', '162.159.46.1', '2606:4700:4700:0:0:0:0:1111', '2606:4700:4700:0:0:0:0:1001', '2606:4700:4700:0:0:0:0:64', '2606:4700:4700:0:0:0:0:6400')")

2021-08-15 10:40:20.464 - [ERROR] Except stack:Traceback (most recent call last): File "G:\Minority_prgram\Internet_Tools\_Proxy\XX-Net\code\4.5.3\lib\noarch\front_base\connect_creator.py", line 149, in check_cert raise socket.error('check sni:undefined fail, alt_names:undefined' % (ssl_sock.sni, peer_cert["altName"])) OSError: check sni:www.meetgod.tk fail, alt_names:('cloudflare-dns.com', '*.cloudflare-dns.com', 'one.one.one.one', '1.1.1.1', '1.0.0.1', '162.159.36.1', '162.159.46.1', '2606:4700:4700:0:0:0:0:1111', '2606:4700:4700:0:0:0:0:1001', '2606:4700:4700:0:0:0:0:64', '2606:4700:4700:0:0:0:0:6400')

2021-08-15 10:43:22.483 - [ERROR] check_cert OSError("check sni:xovowfx.tk fail, alt_names:('2606:4700:4700:0:0:0:0:1112', '2606:4700:4700:0:0:0:0:1002', 'security.cloudflare-dns.com', '*.security.cloudflare-dns.com', '1.1.1.2', '1.0.0.2')")

2021-08-15 10:43:22.484 - [ERROR] Except stack:Traceback (most recent call last): File "G:\Minority_prgram\Internet_Tools\_Proxy\XX-Net\code\4.5.3\lib\noarch\front_base\connect_creator.py", line 149, in check_cert raise socket.error('check sni:undefined fail, alt_names:undefined' % (ssl_sock.sni, peer_cert["altName"])) OSError: check sni:xovowfx.tk fail, alt_names:('2606:4700:4700:0:0:0:0:1112', '2606:4700:4700:0:0:0:0:1002', 'security.cloudflare-dns.com', '*.security.cloudflare-dns.com', '1.1.1.2', '1.0.0.2')

2021-08-15 10:44:09.938 - [ERROR] updated cloudflare front domains from github fail:AttributeError("'NoneType' object has no attribute 'getsockopt'")

2021-08-15 10:44:09.939 - [ERROR] Except stack:Traceback (most recent call last): File "G:\Minority_prgram\Internet_Tools\_Proxy\XX-Net\code\4.5.3\x_tunnel\local\cloudflare_front\host_manager.py", line 69, in update_front_domains response = client.request("GET", url) File "G:\Minority_prgram\Internet_Tools\_Proxy\XX-Net\code\4.5.3\lib\noarch\simple_http_client.py", line 469, in request sock = self.connect(upl.hostname, port, upl.scheme == b"https") File "G:\Minority_prgram\Internet_Tools\_Proxy\XX-Net\code\4.5.3\lib\noarch\simple_http_client.py", line 437, in connect sock = ssl.wrap_socket(sock) File "G:\Minority_prgram\Internet_Tools\_Proxy\XX-Net\python3.8.2\lib\ssl.py", line 1405, in wrap_socket return context.wrap_socket( File "G:\Minority_prgram\Internet_Tools\_Proxy\XX-Net\python3.8.2\lib\ssl.py", line 500, in wrap_socket return self.sslsocket_class._create( File "G:\Minority_prgram\Internet_Tools\_Proxy\XX-Net\python3.8.2\lib\ssl.py", line 987, in _create if sock.getsockopt(SOL_SOCKET, SO_TYPE) != SOCK_STREAM: AttributeError: 'NoneType' object has no attribute 'getsockopt'

2021-08-15 10:49:35.672 - [ERROR] check_cert OSError("check sni:www.sacramen.tk fail, alt_names:('ssl405284.yunjiasussl.com',)")

2021-08-15 10:49:35.673 - [ERROR] Except stack:Traceback (most recent call last): File "G:\Minority_prgram\Internet_Tools\_Proxy\XX-Net\code\4.5.3\lib\noarch\front_base\connect_creator.py", line 149, in check_cert raise socket.error('check sni:undefined fail, alt_names:undefined' % (ssl_sock.sni, peer_cert["altName"])) OSError: check sni:www.sacramen.tk fail, alt_names:('ssl405284.yunjiasussl.com',)

2021-08-15 11:06:37.581 - [ERROR] check_cert OSError("check sni:www.meetgod.tk fail, alt_names:('2606:4700:4700:0:0:0:0:1113', '2606:4700:4700:0:0:0:0:1003', 'family.cloudflare-dns.com', '*.family.cloudflare-dns.com', '1.1.1.3', '1.0.0.3')")

2021-08-15 11:06:37.582 - [ERROR] Except stack:Traceback (most recent call last): File "G:\Minority_prgram\Internet_Tools\_Proxy\XX-Net\code\4.5.3\lib\noarch\front_base\connect_creator.py", line 149, in check_cert raise socket.error('check sni:undefined fail, alt_names:undefined' % (ssl_sock.sni, peer_cert["altName"])) OSError: check sni:www.meetgod.tk fail, alt_names:('2606:4700:4700:0:0:0:0:1113', '2606:4700:4700:0:0:0:0:1003', 'family.cloudflare-dns.com', '*.family.cloudflare-dns.com', '1.1.1.3', '1.0.0.3')

2021-08-15 11:12:49.175 - [ERROR] check_cert OSError("check sni:www.hatenaki.tk fail, alt_names:('ssl1040633.cloudflaressl.com', '*.dev.catalogoadomicilio.kimclark.com', 'dev.catalogoadomicilio.kimclark.com')")

2021-08-15 11:12:49.176 - [ERROR] Except stack:Traceback (most recent call last): File "G:\Minority_prgram\Internet_Tools\_Proxy\XX-Net\code\4.5.3\lib\noarch\front_base\connect_creator.py", line 149, in check_cert raise socket.error('check sni:undefined fail, alt_names:undefined' % (ssl_sock.sni, peer_cert["altName"])) OSError: check sni:www.hatenaki.tk fail, alt_names:('ssl1040633.cloudflaressl.com', '*.dev.catalogoadomicilio.kimclark.com', 'dev.catalogoadomicilio.kimclark.com')

2021-08-15 11:14:10.075 - [ERROR] updated cloudflare front domains from github fail:AttributeError("'NoneType' object has no attribute 'getsockopt'")

2021-08-15 11:14:10.077 - [ERROR] Except stack:Traceback (most recent call last): File "G:\Minority_prgram\Internet_Tools\_Proxy\XX-Net\code\4.5.3\x_tunnel\local\cloudflare_front\host_manager.py", line 69, in update_front_domains response = client.request("GET", url) File "G:\Minority_prgram\Internet_Tools\_Proxy\XX-Net\code\4.5.3\lib\noarch\simple_http_client.py", line 469, in request sock = self.connect(upl.hostname, port, upl.scheme == b"https") File "G:\Minority_prgram\Internet_Tools\_Proxy\XX-Net\code\4.5.3\lib\noarch\simple_http_client.py", line 437, in connect sock = ssl.wrap_socket(sock) File "G:\Minority_prgram\Internet_Tools\_Proxy\XX-Net\python3.8.2\lib\ssl.py", line 1405, in wrap_socket return context.wrap_socket( File "G:\Minority_prgram\Internet_Tools\_Proxy\XX-Net\python3.8.2\lib\ssl.py", line 500, in wrap_socket return self.sslsocket_class._create( File "G:\Minority_prgram\Internet_Tools\_Proxy\XX-Net\python3.8.2\lib\ssl.py", line 987, in _create if sock.getsockopt(SOL_SOCKET, SO_TYPE) != SOCK_STREAM: AttributeError: 'NoneType' object has no attribute 'getsockopt'

2021-08-15 11:23:06.959 - [WARNING] task POST v13.xx-net.org /data timeout

2021-08-15 11:23:06.960 - [WARNING] POST v13.standardalcohol.tk/data status:521 trace:0:start_request,1:get_task(3604),0:get_worker(0):141.101.113.116,0:h2_req,0:start send header,0:start send left body,0:end send left body,273:h2_get_head,1:h2_finish[SP:0],0:get_response,:0

2021-08-15 11:23:07.296 - [DEBUG] POST center.standardalcohol.tk/login status:200 trace:0:start_request,1:get_task(3604),0:get_worker(0):104.20.152.111,0:h2_req,0:start send header,0:start send left body,0:end send left body,333:h2_get_head,0:get_response,:0

2021-08-15 11:23:26.674 - [DEBUG] POST center.standardalcohol.tk/report_stat status:200 trace:0:start_request,0:get_task(19),0:get_worker(0):104.20.152.111,0:h2_req,0:start send header,0:start send left body,0:end send left body,328:h2_get_head,0:get_response,:0

2021-08-15 11:24:08.797 - [WARNING] task POST v13.xx-net.org /data timeout

2021-08-15 11:24:08.797 - [WARNING] POST v13.standardalcohol.tk/data status:521 trace:0:start_request,0:get_task(60),0:get_worker(0):141.101.113.116,0:h2_req,0:start send header,0:start send left body,0:end send left body,1189:h2_get_head,1:h2_finish[SP:0],0:get_response,:0

TLS-Relay前端日志============================================================

2021-08-15 13:21:04.913 - [WARNING] not enough ip

2021-08-15 13:21:15.914 - [WARNING] not enough ip

2021-08-15 13:21:26.915 - [WARNING] not enough ip

2021-08-15 13:21:37.915 - [WARNING] not enough ip

2021-08-15 13:21:48.916 - [WARNING] not enough ip

2021-08-15 13:21:59.916 - [WARNING] not enough ip

2021-08-15 13:22:00.559 - [DEBUG] create ssl timeout fail.

**Comment by snipertulip** [comment]
时好时坏，好一会就断线

**Comment by Felixchen1024** [comment]
同样问题
