### ISSUE TITLE
遇到“OSError: [WinError 10013] 以一种访问权限不允许的方式做了一个访问套接字的尝试。”的解决方法。

### ISSUE THREAD

**Issue by Maogxer** [XX-net/XX-Net#13552]
有时候启动xx-net后会出现这样的错误：
`2021-05-01 21:41:06.315 [cloudflare_front][INFO] OpenSSL support alpn
2021-05-01 21:41:06.315 [cloudflare_front][INFO] load ip range file:E:\Tools\XX-Net\code\default\x_tunnel\local\cloudflare_front\ip_range.txt
2021-05-01 21:41:06.331 [cloudflare_front][INFO] load ip_list num:135, target num:135
2021-05-01 21:41:06.331 [x_tunnel][INFO] xxnet_version:4.5.3
2021-05-01 21:41:06.331 [x_tunnel][DEBUG] SendBuffer reset
2021-05-01 21:41:06.331 [x_tunnel][ERROR] bind to b'127.0.0.1':1080 fail:OSError(10013, '以一种访问权限不允许的方式做了 一个访问套接字的尝试。', None, 10013, None)
Exception in thread Thread-22:
Traceback (most recent call last): File "E:\Tools\XX-Net\code\default\lib\noarch\simple_http_server.py", line 466, in add_listen sock.bind(addr) OSError: [WinError 10013] 以一种访问权限不允许的方式做了一个访问套接字的尝试。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "E:\Tools\XX-Net\python3.8.2\lib\threading.py", line 932, in _bootstrap_inner
self.run()
File "E:\Tools\XX-Net\python3.8.2\lib\threading.py", line 870, in run
self._target(*self.args, **self.kwargs) File "E:\Tools\XX-Net\code\default\x_tunnel\local__init.py", line 14, in start
client.main(args)
File "E:\Tools\XX-Net\code\default\x_tunnel\local\client.py", line 193, in main
g.socks5_server = simple_http_server.HTTPServer(addresses, Socks5Server, logger=xlog)
File "E:\Tools\XX-Net\code\default\lib\noarch\simple_http_server.py", line 430, in init
self.init_socket()
File "E:\Tools\XX-Net\code\default\lib\noarch\simple_http_server.py", line 449, in init_socket
self.add_listen((ip, port))
File "E:\Tools\XX-Net\code\default\lib\noarch\simple_http_server.py", line 470, in add_listen
raise Exception(err_string)
Exception: bind to b'127.0.0.1':1080 fail:OSError(10013, '以一种访问权限不允许的方式做了一个访问套接字的尝试。', None, 10013, None)
2021-05-01 21:41:10.104 [gae_proxy][WARNING] network IPv6 fail`

这是因为1080端口被占用了。
但是用`netstat -aon | findstr`却找不到端口，

**原因**
本机启用了 Hyper-V 功能，这个功能与 Docker 或者 虚拟机 有关，使用 WSL2也需要开启这个功能。Widows 默认把某些端口范围分给了 Hyper-V ，成为了保留端口，所以我们无法使用这个端口。

1. 查看 Windows 默认的 tcp 动态端口范围
使用命令`netsh int ipv4 show dynamicport tcp`就可以查看

2. 查看保留端口范围
使用命令 `netsh interface ipv4 show excludedportrange protocol=tcp` 就可查看保留端口的范围了。

有时候1080，8087，8085 这些端口会包含在这个范围之中。

**解决问题**

使用管理的身份运行 CMD ，设置动态端口的范围，使得这个保留端口的范围避开我们需要的端口范围。

```
> netsh int ipv4 set dynamicport tcp start=49152 num=16383
> netsh int ipv4 set dynamicport udp start=49152 num=16383
```

然后重新启动电脑

**Comment by tiantian1645** [comment]
不重启也可以

```
net stop winnat
netsh interface ipv4 show excludedportrange protocol=tcp
net start winnat
netsh interface ipv4 show excludedportrange protocol=tcp
```

https://gsw945.com/index.php/archives/33/

https://superuser.com/questions/1579346/many-excludedportranges-how-to-delete-hyper-v-is-disabled

https://github.com/docker/for-win/issues/3171#issuecomment-739740248

**Comment by hazzzzzy** [comment]
牛逼啊老师，我被卡好久了就是因为端口命名10086，用了一段时间才报错的
