### ISSUE TITLE
连接服务器失败：session server login fail:602

### ISSUE THREAD

**Issue by Felixchen1024** [XX-net/XX-Net#13561]
作者，你好，最近老是连不上，请问是服务器问题吗？
附上日志：
2021-08-19 14:54:51.521 - [INFO] xxnet_version:4.5.3

2021-08-19 14:54:51.521 - [DEBUG] SendBuffer reset

2021-08-19 14:54:51.556 - [INFO] server 127.0.0.1:1080 started.

2021-08-19 14:54:51.556 - [INFO] Socks5 server listen:127.0.0.1:1080.

2021-08-19 14:55:00.830 - [DEBUG] session not running, try login..

2021-08-19 14:55:08.524 - [WARNING] front retry center.xx-net.org/login

2021-08-19 14:55:15.322 - [WARNING] front retry center.xx-net.org/login

2021-08-19 14:55:24.221 - [WARNING] front retry center.xx-net.org/login

2021-08-19 14:55:33.623 - [WARNING] front retry center.xx-net.org/login

2021-08-19 14:55:35.624 - [WARNING] api:/login fail:status:602 t:34

2021-08-19 14:55:35.624 - [WARNING] x-tunnel request_balance fail when create_conn:status:602

2021-08-19 14:55:35.624 - [DEBUG] session not running, try login..

2021-08-19 14:55:42.564 - [WARNING] front retry center.xx-net.org/login

2021-08-19 14:55:47.556 - [WARNING] front retry center.xx-net.org/login

2021-08-19 14:55:56.105 - [WARNING] front retry center.xx-net.org/login

2021-08-19 14:56:01.184 - [WARNING] front retry center.xx-net.org/login

2021-08-19 14:56:09.634 - [WARNING] front retry center.xx-net.org/login

2021-08-19 14:56:11.635 - [WARNING] api:/login fail:status:602 t:36

2021-08-19 14:56:11.635 - [WARNING] x-tunnel request_balance fail when create_conn:status:602

2021-08-19 14:56:11.635 - [DEBUG] session not running, try login..

2021-08-19 14:56:17.862 - [WARNING] front retry center.xx-net.org/login

2021-08-19 14:56:26.935 - [WARNING] front retry center.xx-net.org/login

2021-08-19 14:56:29.267 - [INFO] api:/login success t:17630

2021-08-19 14:56:29.268 - [INFO] update xt_server v17.xx-net.org:443

2021-08-19 14:56:29.268 - [INFO] request_balance host:v17.xx-net.org port:443 balance:0.000000 quota:1461783416295.000000

2021-08-19 14:56:29.268 - [INFO] session timeout, reset it.

2021-08-19 14:56:29.268 - [WARNING] session stop but not running

2021-08-19 14:56:29.719 - [DEBUG] x_tunnel force update info

2021-08-19 14:56:29.911 - [WARNING] front retry center.xx-net.org/login

2021-08-19 14:56:31.229 - [INFO] api:/login success t:1508

2021-08-19 14:56:31.230 - [INFO] request_balance host:v17.xx-net.org port:443 balance:0.000000 quota:1461783416295.000000

2021-08-19 14:56:31.478 - [WARNING] front retry v17.xx-net.org/data

2021-08-19 14:56:34.654 - [WARNING] front retry v17.xx-net.org/data

2021-08-19 14:56:35.961 - [WARNING] login session server is down, try get new server.

2021-08-19 14:56:35.961 - [WARNING] x-tunnel login_session fail, session not start

2021-08-19 14:56:35.961 - [DEBUG] session not running, try login..

2021-08-19 14:56:36.135 - [WARNING] front retry center.xx-net.org/login

2021-08-19 14:56:37.454 - [INFO] api:/login success t:1492

2021-08-19 14:56:37.454 - [INFO] update xt_server v17.xx-net.org:443

2021-08-19 14:56:37.454 - [INFO] request_balance host:v17.xx-net.org port:443 balance:0.000000 quota:1461783416295.000000

2021-08-19 14:56:37.744 - [WARNING] login session server is down, try get new server.

2021-08-19 14:56:37.745 - [WARNING] x-tunnel login_session fail, session not start

2021-08-19 14:56:37.745 - [DEBUG] session not running, try login..

2021-08-19 14:56:37.941 - [WARNING] front retry center.xx-net.org/login

2021-08-19 14:56:39.240 - [INFO] api:/login success t:1494

2021-08-19 14:56:39.241 - [INFO] update xt_server v9.xx-net.org:443

2021-08-19 14:56:39.241 - [INFO] request_balance host:v9.xx-net.org port:443 balance:0.000000 quota:1461783416295.000000

2021-08-19 14:56:41.435 - [WARNING] front retry v9.xx-net.org/data

2021-08-19 14:56:44.636 - [WARNING] front retry v9.xx-net.org/data

2021-08-19 14:56:45.831 - [WARNING] front retry v9.xx-net.org/data

2021-08-19 14:56:47.007 - [WARNING] front retry v9.xx-net.org/data

2021-08-19 14:56:48.202 - [WARNING] front retry v9.xx-net.org/data

2021-08-19 14:56:49.970 - [WARNING] front retry v9.xx-net.org/data

2021-08-19 14:56:50.971 - [WARNING] login session fail, status:404

2021-08-19 14:56:51.697 - [WARNING] front retry v9.xx-net.org/data

2021-08-19 14:56:53.444 - [WARNING] front retry v9.xx-net.org/data

2021-08-19 14:56:54.779 - [WARNING] front retry v9.xx-net.org/data

2021-08-19 14:56:56.520 - [WARNING] front retry v9.xx-net.org/data

2021-08-19 14:56:56.525 - [DEBUG] start report_stat

2021-08-19 14:56:56.849 - [INFO] api:/report_stat success t:324

2021-08-19 14:56:57.854 - [WARNING] front retry v9.xx-net.org/data

2021-08-19 14:57:08.859 - [WARNING] get_front fail

2021-08-19 14:57:08.859 - [WARNING] login session fail, status:602

2021-08-19 14:57:18.863 - [WARNING] get_front fail

2021-08-19 14:57:18.863 - [WARNING] login session fail, status:602

2021-08-19 14:57:18.863 - [WARNING] x-tunnel login_session fail, session not start

2021-08-19 14:57:28.547 - [WARNING] front retry v9.xx-net.org/data

2021-08-19 14:57:29.548 - [WARNING] login session fail, status:602

2021-08-19 14:57:39.552 - [WARNING] get_front fail

2021-08-19 14:57:39.552 - [WARNING] login session fail, status:602

2021-08-19 14:57:49.559 - [WARNING] get_front fail

2021-08-19 14:57:49.559 - [WARNING] login session fail, status:602

2021-08-19 14:57:49.559 - [WARNING] x-tunnel login_session fail, session not start

2021-08-19 14:57:56.850 - [DEBUG] start report_stat

2021-08-19 14:57:57.169 - [INFO] api:/report_stat success t:318

2021-08-19 14:57:59.317 - [WARNING] front retry v9.xx-net.org/data

2021-08-19 14:58:00.318 - [WARNING] login session fail, status:404

2021-08-19 14:58:10.324 - [WARNING] get_front fail

2021-08-19 14:58:10.324 - [WARNING] login session fail, status:602

2021-08-19 14:58:20.329 - [WARNING] get_front fail

2021-08-19 14:58:20.329 - [WARNING] login session fail, status:602

2021-08-19 14:58:20.329 - [WARNING] x-tunnel login_session fail, session not start

2021-08-19 14:58:32.841 - [WARNING] front retry v9.xx-net.org/data

2021-08-19 14:58:33.843 - [WARNING] login session fail, status:602

2021-08-19 14:58:43.625 - [DEBUG] x-tunnel web_control 127.0.0.1:12124 POST /login

2021-08-19 14:58:43.847 - [WARNING] get_front fail

2021-08-19 14:58:43.847 - [WARNING] login session fail, status:602

2021-08-19 14:58:43.938 - [INFO] api:/login success t:312

2021-08-19 14:58:43.938 - [INFO] update xt_server v17.xx-net.org:443

2021-08-19 14:58:43.938 - [INFO] request_balance host:v17.xx-net.org port:443 balance:0.000000 quota:1461783416295.000000

2021-08-19 14:58:53.854 - [WARNING] get_front fail

2021-08-19 14:58:53.854 - [WARNING] login session fail, status:602

2021-08-19 14:58:53.854 - [WARNING] x-tunnel login_session fail, session not start

2021-08-19 14:58:54.036 - [WARNING] front retry v17.xx-net.org/data

2021-08-19 14:58:55.294 - [WARNING] login session server is down, try get new server.

2021-08-19 14:58:55.294 - [WARNING] x-tunnel login_session fail, session not start

2021-08-19 14:58:55.295 - [ERROR] any err:TypeError("object of type 'NoneType' has no len()")

2021-08-19 14:58:55.295 - [DEBUG] session not running, try login..

2021-08-19 14:58:55.305 - [ERROR] Except stack:Traceback (most recent call last): File "C:\XX-NET\XX-Net-windows-4.5.3\XX-Net\code\default\x_tunnel\local\proxy_handler.py", line 51, in handle self.socks5_handler() File "C:\XX-NET\XX-Net-windows-4.5.3\XX-Net\code\default\x_tunnel\local\proxy_handler.py", line 265, in socks5_handler conn_id = proxy_session.create_conn(sock, addr, port) File "C:\XX-NET\XX-Net-windows-4.5.3\XX-Net\code\default\x_tunnel\local\proxy_session.py", line 978, in create_conn if login_process(): File "C:\XX-NET\XX-Net-windows-4.5.3\XX-Net\code\default\x_tunnel\local\proxy_session.py", line 968, in login_process return g.session.start() File "C:\XX-NET\XX-Net-windows-4.5.3\XX-Net\code\default\x_tunnel\local\proxy_session.py", line 106, in start if not self.login_session(): File "C:\XX-NET\XX-Net-windows-4.5.3\XX-Net\code\default\x_tunnel\local\proxy_session.py", line 300, in login_session if len(g.server_host) == 0: TypeError: object of type 'NoneType' has no len()

2021-08-19 14:58:55.615 - [INFO] api:/login success t:319

2021-08-19 14:58:55.616 - [INFO] update xt_server v17.xx-net.org:443

2021-08-19 14:58:55.616 - [INFO] request_balance host:v17.xx-net.org port:443 balance:0.000000 quota:1461783416295.000000

2021-08-19 14:58:55.902 - [WARNING] login session server is down, try get new server.

2021-08-19 14:58:55.902 - [WARNING] x-tunnel login_session fail, session not start

2021-08-19 14:58:55.902 - [DEBUG] session not running, try login..

2021-08-19 14:58:56.081 - [WARNING] front retry center.xx-net.org/login

2021-08-19 14:58:57.170 - [DEBUG] start report_stat

2021-08-19 14:58:57.361 - [WARNING] front retry center.xx-net.org/report_stat

2021-08-19 14:58:57.401 - [INFO] api:/login success t:1499

2021-08-19 14:58:57.402 - [INFO] update xt_server v17.xx-net.org:443

2021-08-19 14:58:57.402 - [INFO] request_balance host:v17.xx-net.org port:443 balance:0.000000 quota:1461783416295.000000

2021-08-19 14:58:57.639 - [WARNING] login session server is down, try get new server.

2021-08-19 14:58:57.639 - [WARNING] x-tunnel login_session fail, session not start

2021-08-19 14:58:57.639 - [DEBUG] session not running, try login..

2021-08-19 14:58:57.840 - [WARNING] front retry center.xx-net.org/login

2021-08-19 14:58:58.700 - [INFO] api:/report_stat success t:1529

2021-08-19 14:58:59.149 - [INFO] api:/login success t:1507

2021-08-19 14:58:59.149 - [INFO] update xt_server v17.xx-net.org:443

2021-08-19 14:58:59.150 - [INFO] request_balance host:v17.xx-net.org port:443 balance:0.000000 quota:1461783416295.000000

2021-08-19 14:58:59.389 - [WARNING] login session server is down, try get new server.

2021-08-19 14:58:59.389 - [WARNING] x-tunnel login_session fail, session not start

2021-08-19 14:58:59.389 - [DEBUG] session not running, try login..

2021-08-19 14:58:59.712 - [INFO] api:/login success t:322

2021-08-19 14:58:59.712 - [INFO] update xt_server v17.xx-net.org:443

2021-08-19 14:58:59.712 - [INFO] request_balance host:v17.xx-net.org port:443 balance:0.000000 quota:1461783416295.000000

2021-08-19 14:58:59.988 - [WARNING] login session server is down, try get new server.

2021-08-19 14:58:59.989 - [WARNING] x-tunnel login_session fail, session not start

2021-08-19 14:58:59.989 - [DEBUG] session not running, try login..

2021-08-19 14:59:00.318 - [INFO] api:/login success t:327

2021-08-19 14:59:00.318 - [INFO] update xt_server v17.xx-net.org:443

2021-08-19 14:59:00.318 - [INFO] request_balance host:v17.xx-net.org port:443 balance:0.000000 quota:1461783416295.000000

2021-08-19 14:59:00.597 - [WARNING] login session server is down, try get new server.

2021-08-19 14:59:00.597 - [WARNING] x-tunnel login_session fail, session not start

2021-08-19 14:59:00.599 - [DEBUG] session not running, try login..

2021-08-19 14:59:00.916 - [INFO] api:/login success t:317

2021-08-19 14:59:00.917 - [INFO] update xt_server v17.xx-net.org:443

2021-08-19 14:59:00.917 - [INFO] request_balance host:v17.xx-net.org port:443 balance:0.000000 quota:1461783416295.000000

2021-08-19 14:59:10.924 - [WARNING] get_front fail

2021-08-19 14:59:10.924 - [WARNING] login session fail, status:602

2021-08-19 14:59:20.936 - [WARNING] get_front fail

2021-08-19 14:59:20.936 - [WARNING] login session fail, status:602

2021-08-19 14:59:36.376 - [WARNING] front retry v17.xx-net.org/data

2021-08-19 14:59:37.377 - [WARNING] login session fail, status:602

2021-08-19 14:59:37.377 - [WARNING] x-tunnel login_session fail, session not start

**Comment by Master-OAP** [comment]
绷不住了

**Comment by Felixchen1024** [comment]
作者还维护吗？刚充了1年。。。
