### ISSUE TITLE
fedora 35上3.5.3报错

### ISSUE THREAD

**Issue by lyfbuaa** [XX-net/XX-Net#13622]
2021-12-06 02:32:41.503 [launcher][INFO] use build-in openssl lib
2021-12-06 02:32:41.953 [launcher][INFO] start XX-Net 4.5.3
2021-12-06 02:32:41.954 [launcher][DEBUG] start confirm_xxnet_exit
2021-12-06 02:32:41.972 [launcher][DEBUG] good, xxnet:8085 clear!
2021-12-06 02:32:41.973 [launcher][DEBUG] finished confirm_xxnet_exit
2021-12-06 02:32:41.977 [launcher][INFO] start with allow remote connect.
2021-12-06 02:32:42.143 [gae_proxy][DEBUG] network IPv4 is ok, cost:88 ms
2021-12-06 02:32:42.145 [launcher][ERROR] start module gae_proxy fail:cannot import name 'Callable' from 'collections' (/usr/lib64/python3.10/collections/__init__.py)
2021-12-06 02:32:42.148 [launcher][ERROR] Except stack:Traceback (most recent call last):
  File "/home/developer/xx-net/code/default/launcher/module_init.py", line 44, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local'], 0)
  File "/home/developer/xx-net/code/default/gae_proxy/local/__init__.py", line 2, in <module>
    from . import apis
  File "/home/developer/xx-net/code/default/gae_proxy/local/apis.py", line 2, in <module>
    from .front import front, direct_front
  File "/home/developer/xx-net/code/default/gae_proxy/local/front.py", line 12, in <module>
    from front_base.connect_creator import ConnectCreator
  File "/home/developer/xx-net/code/default/lib/noarch/front_base/connect_creator.py", line 6, in <module>
    import socks
  File "/home/developer/xx-net/code/default/lib/noarch/socks.py", line 63, in <module>
    from collections import Callable
ImportError: cannot import name 'Callable' from 'collections' (/usr/lib64/python3.10/collections/__init__.py)

**Comment by lyfbuaa** [comment]
更新到3.5.6好像不报错了，关了吧
