### ISSUE TITLE
4.5.6无法登录

### ISSUE THREAD

**Issue by 189189lw** [XX-net/XX-Net#13649]
X-Tunnel 日志
2022-02-05 17:33:02.283 - [DEBUG] gae_proxy not running

2022-02-05 17:33:02.316 - [INFO] xxnet_version:4.5.6

2022-02-05 17:33:02.317 - [DEBUG] SendBuffer reset

2022-02-05 17:33:02.319 - [INFO] server 127.0.0.1:1080 started.

2022-02-05 17:33:02.319 - [INFO] Socks5 server listen:127.0.0.1:1080.

2022-02-05 17:33:49.503 - [DEBUG] x-tunnel web_control 127.0.0.1:50232 POST /login

2022-02-05 17:33:50.739 - [WARNING] front retry center.xx-net.org/login

2022-02-05 17:33:51.958 - [WARNING] front retry center.xx-net.org/login

2022-02-05 17:33:53.186 - [WARNING] front retry center.xx-net.org/login

2022-02-05 17:33:55.449 - [WARNING] front retry center.xx-net.org/login

2022-02-05 17:33:57.680 - [WARNING] front retry center.xx-net.org/login

2022-02-05 17:33:58.926 - [WARNING] front retry center.xx-net.org/login

2022-02-05 17:34:00.149 - [WARNING] front retry center.xx-net.org/login

2022-02-05 17:34:01.392 - [WARNING] front retry center.xx-net.org/login

2022-02-05 17:34:07.476 - [WARNING] get_front fail

2022-02-05 17:34:08.731 - [WARNING] front retry center.xx-net.org/login

2022-02-05 17:34:10.997 - [WARNING] front retry center.xx-net.org/login

2022-02-05 17:34:12.226 - [WARNING] front retry center.xx-net.org/login

2022-02-05 17:34:18.277 - [WARNING] get_front fail

2022-02-05 17:34:24.304 - [WARNING] get_front fail

2022-02-05 17:34:25.320 - [WARNING] api:/login fail:status:602 t:35

2022-02-05 17:34:25.571 - [DEBUG] x-tunnel web_control 127.0.0.1:50232 POST /login

2022-02-05 17:34:30.642 - [WARNING] get_front fail

2022-02-05 17:34:36.703 - [WARNING] get_front fail

2022-02-05 17:34:42.769 - [WARNING] get_front fail

2022-02-05 17:34:48.815 - [WARNING] get_front fail

2022-02-05 17:34:54.873 - [WARNING] get_front fail

2022-02-05 17:34:55.885 - [WARNING] api:/login fail:status:602 t:30
---------------------------------------------------------------------------------
Cloudflare前端 日志
2022-02-05 17:33:02.290 - [INFO] load F:\XX-Net-2.3.0\XX-Net-windows-4.5.6\XX-Net\code\default\x_tunnel\local\cloudflare_front\front_domains.json success

2022-02-05 17:33:02.291 - [INFO] SSL use version:TLSv1_3

2022-02-05 17:33:02.300 - [ERROR] updated cloudflare front domains from github fail:AttributeError("'NoneType' object has no attribute 'getsockopt'")

2022-02-05 17:33:02.301 - [INFO] OpenSSL support alpn

2022-02-05 17:33:02.302 - [INFO] load ip range file:F:\XX-Net-2.3.0\XX-Net-windows-4.5.6\XX-Net\code\default\x_tunnel\local\cloudflare_front\ip_range.txt

2022-02-05 17:33:02.309 - [ERROR] Except stack:Traceback (most recent call last): File "F:\XX-Net-2.3.0\XX-Net-windows-4.5.6\XX-Net\code\default\x_tunnel\local\cloudflare_front\host_manager.py", line 69, in update_front_domains response = client.request("GET", url) File "F:\XX-Net-2.3.0\XX-Net-windows-4.5.6\XX-Net\code\default\lib\noarch\simple_http_client.py", line 469, in request sock = self.connect(upl.hostname, port, upl.scheme == b"https") File "F:\XX-Net-2.3.0\XX-Net-windows-4.5.6\XX-Net\code\default\lib\noarch\simple_http_client.py", line 437, in connect sock = ssl.wrap_socket(sock) File "F:\XX-Net-2.3.0\XX-Net-windows-4.5.6\XX-Net\python3.8.2\lib\ssl.py", line 1405, in wrap_socket return context.wrap_socket( File "F:\XX-Net-2.3.0\XX-Net-windows-4.5.6\XX-Net\python3.8.2\lib\ssl.py", line 500, in wrap_socket return self.sslsocket_class._create( File "F:\XX-Net-2.3.0\XX-Net-windows-4.5.6\XX-Net\python3.8.2\lib\ssl.py", line 987, in _create if sock.getsockopt(SOL_SOCKET, SO_TYPE) != SOCK_STREAM: AttributeError: 'NoneType' object has no attribute 'getsockopt'

2022-02-05 17:33:02.312 - [INFO] load ip_list num:99, target num:99

2022-02-05 17:33:49.898 - [DEBUG] create_ssl update ip:190.93.247.123 time:367 h2:1 sni:xtunnel.xyz, host:xtunnel.xyz

2022-02-05 17:33:50.735 - [WARNING] 190.93.247.123 close, reason: status 403, trace: continue_timeout:0, processed:0, h2.stream_num:1, sni:xtunnel.xyz, host:xtunnel.xyz

2022-02-05 17:33:50.735 - [WARNING] task POST center.xx-net.org /login timeout

2022-02-05 17:33:50.736 - [DEBUG] 190.93.247.123 worker close:status 403 inactive:0

2022-02-05 17:33:50.737 - [WARNING] POST center.xtunnel.xyz/login status:403 trace:0:start_request,1:get_task(1),0:get_worker(0):190.93.247.123,0:h2_req,0:start send header,0:start send left body,0:end send left body,215:h2_get_head,2:get_response,:0

2022-02-05 17:33:51.273 - [DEBUG] create_ssl update ip:104.19.128.160 time:368 h2:1 sni:xtunnel.xyz, host:xtunnel.xyz

2022-02-05 17:33:51.953 - [WARNING] 104.19.128.160 close, reason: status 403, trace: continue_timeout:0, processed:0, h2.stream_num:1, sni:xtunnel.xyz, host:xtunnel.xyz

2022-02-05 17:33:51.953 - [WARNING] task POST center.xx-net.org /login timeout

2022-02-05 17:33:51.954 - [DEBUG] 104.19.128.160 worker close:status 403 inactive:0

2022-02-05 17:33:51.955 - [WARNING] POST center.xtunnel.xyz/login status:403 trace:0:start_request,0:get_task(1),0:get_worker(0):104.19.128.160,0:h2_req,0:start send header,0:start send left body,0:end send left body,203:h2_get_head,2:get_response,:0

2022-02-05 17:33:52.670 - [DEBUG] create_ssl update ip:141.101.114.208 time:388 h2:1 sni:www.pc-nvme.shop, host:pc-nvme.shop

2022-02-05 17:33:53.182 - [WARNING] 141.101.114.208 close, reason: status 403, trace: continue_timeout:0, processed:0, h2.stream_num:1, sni:www.pc-nvme.shop, host:pc-nvme.shop

2022-02-05 17:33:53.182 - [WARNING] task POST center.xx-net.org /login timeout

2022-02-05 17:33:53.183 - [DEBUG] 141.101.114.208 worker close:status 403 inactive:0

2022-02-05 17:33:53.183 - [WARNING] POST center.pc-nvme.shop/login status:403 trace:0:start_request,1:get_task(1),0:get_worker(0):141.101.114.208,0:h2_req,1:start send header,0:start send left body,0:end send left body,211:h2_get_head,2:get_response,:0

2022-02-05 17:33:54.083 - [DEBUG] create_ssl update ip:198.41.221.229 time:397 h2:1 sni:www.pc-nvme.shop, host:pc-nvme.shop

2022-02-05 17:33:55.443 - [WARNING] 198.41.221.229 close, reason: status 403, trace: continue_timeout:0, processed:0, h2.stream_num:1, sni:www.pc-nvme.shop, host:pc-nvme.shop

2022-02-05 17:33:55.443 - [WARNING] task POST center.xx-net.org /login timeout

2022-02-05 17:33:55.444 - [DEBUG] 198.41.221.229 worker close:status 403 inactive:0

2022-02-05 17:33:55.445 - [WARNING] POST center.pc-nvme.shop/login status:403 trace:0:start_request,0:get_task(2),0:get_worker(0):198.41.221.229,0:h2_req,1:start send header,0:start send left body,0:end send left body,227:h2_get_head,3:get_response,:0

2022-02-05 17:33:55.475 - [DEBUG] create_ssl update ip:190.93.247.123 time:389 h2:1 sni:www.household.monster, host:household.monster

2022-02-05 17:33:57.676 - [WARNING] 190.93.247.123 close, reason: status 403, trace: continue_timeout:0, processed:0, h2.stream_num:1, sni:www.household.monster, host:household.monster

2022-02-05 17:33:57.676 - [WARNING] task POST center.xx-net.org /login timeout

2022-02-05 17:33:57.677 - [DEBUG] 190.93.247.123 worker close:status 403 inactive:0

2022-02-05 17:33:57.678 - [WARNING] POST center.household.monster/login status:403 trace:0:start_request,1:get_task(2),0:get_worker(0):190.93.247.123,0:h2_req,0:start send header,0:start send left body,0:end send left body,209:h2_get_head,2:get_response,:0

2022-02-05 17:33:57.874 - [DEBUG] create_ssl update ip:104.19.128.160 time:407 h2:1 sni:www.pc-nvme.shop, host:pc-nvme.shop

2022-02-05 17:33:58.918 - [WARNING] 104.19.128.160 close, reason: status 403, trace: continue_timeout:0, processed:0, h2.stream_num:1, sni:www.pc-nvme.shop, host:pc-nvme.shop

2022-02-05 17:33:58.918 - [WARNING] task POST center.xx-net.org /login timeout

2022-02-05 17:33:58.919 - [DEBUG] 104.19.128.160 worker close:status 403 inactive:0

2022-02-05 17:33:58.920 - [WARNING] POST center.pc-nvme.shop/login status:403 trace:0:start_request,0:get_task(1),0:get_worker(0):104.19.128.160,0:h2_req,1:start send header,0:start send left body,0:end send left body,228:h2_get_head,2:get_response,:0

2022-02-05 17:33:59.258 - [DEBUG] create_ssl update ip:141.101.114.208 time:366 h2:1 sni:www.household.monster, host:household.monster

2022-02-05 17:34:00.144 - [WARNING] 141.101.114.208 close, reason: status 403, trace: continue_timeout:0, processed:0, h2.stream_num:1, sni:www.household.monster, host:household.monster

2022-02-05 17:34:00.144 - [WARNING] task POST center.xx-net.org /login timeout

2022-02-05 17:34:00.146 - [DEBUG] 141.101.114.208 worker close:status 403 inactive:0

2022-02-05 17:34:00.146 - [WARNING] POST center.household.monster/login status:403 trace:0:start_request,0:get_task(1),0:get_worker(0):141.101.114.208,0:h2_req,1:start send header,0:start send left body,0:end send left body,206:h2_get_head,2:get_response,:0

2022-02-05 17:34:00.666 - [DEBUG] create_ssl update ip:190.93.246.98 time:399 h2:1 sni:xtunnel.xyz, host:xtunnel.xyz

2022-02-05 17:34:01.385 - [WARNING] 190.93.246.98 close, reason: status 403, trace: continue_timeout:0, processed:0, h2.stream_num:1, sni:xtunnel.xyz, host:xtunnel.xyz

2022-02-05 17:34:01.385 - [WARNING] task POST center.xx-net.org /login timeout

2022-02-05 17:34:01.387 - [DEBUG] 190.93.246.98 worker close:status 403 inactive:0

2022-02-05 17:34:01.388 - [WARNING] POST center.xtunnel.xyz/login status:403 trace:0:start_request,1:get_task(1),0:get_worker(0):190.93.246.98,0:h2_req,1:start send header,0:start send left body,0:end send left body,217:h2_get_head,3:get_response,:0

2022-02-05 17:34:06.687 - [DEBUG] connect 104.18.54.33 network fail:OSError("conn fail, sni:b'www.household.monster', top:household.monster e:timeout('timed out')")

2022-02-05 17:34:06.688 - [DEBUG] report_connect_fail:104.18.54.33

2022-02-05 17:34:08.129 - [DEBUG] create_ssl update ip:104.16.172.76 time:425 h2:1 sni:xtunnel.xyz, host:xtunnel.xyz

2022-02-05 17:34:08.726 - [WARNING] 104.16.172.76 close, reason: status 403, trace: continue_timeout:0, processed:0, h2.stream_num:1, sni:xtunnel.xyz, host:xtunnel.xyz

2022-02-05 17:34:08.727 - [WARNING] task POST center.xx-net.org /login timeout

2022-02-05 17:34:08.728 - [DEBUG] 104.16.172.76 worker close:status 403 inactive:0

2022-02-05 17:34:08.729 - [WARNING] POST center.xtunnel.xyz/login status:403 trace:0:start_request,0:get_task(7),1:get_worker(0):104.16.172.76,0:h2_req,0:start send header,0:start send left body,0:end send left body,242:h2_get_head,3:get_response,:0

2022-02-05 17:34:09.560 - [DEBUG] create_ssl update ip:190.93.244.171 time:425 h2:1 sni:xtunnel.xyz, host:xtunnel.xyz

2022-02-05 17:34:10.967 - [DEBUG] create_ssl update ip:190.93.247.107 time:392 h2:1 sni:www.household.monster, host:household.monster

2022-02-05 17:34:10.993 - [WARNING] 190.93.244.171 close, reason: status 403, trace: continue_timeout:0, processed:0, h2.stream_num:1, sni:xtunnel.xyz, host:xtunnel.xyz

2022-02-05 17:34:10.993 - [WARNING] task POST center.xx-net.org /login timeout

2022-02-05 17:34:10.994 - [DEBUG] 190.93.244.171 worker close:status 403 inactive:0

2022-02-05 17:34:10.995 - [WARNING] POST center.xtunnel.xyz/login status:403 trace:0:start_request,0:get_task(2),0:get_worker(0):190.93.244.171,0:h2_req,0:start send header,0:start send left body,0:end send left body,245:h2_get_head,2:get_response,:0

2022-02-05 17:34:12.221 - [WARNING] 190.93.247.107 close, reason: status 403, trace: continue_timeout:0, processed:0, h2.stream_num:1, sni:www.household.monster, host:household.monster

2022-02-05 17:34:12.222 - [WARNING] task POST center.xx-net.org /login timeout

2022-02-05 17:34:12.223 - [DEBUG] 190.93.247.107 worker close:status 403 inactive:0

2022-02-05 17:34:12.224 - [WARNING] POST center.household.monster/login status:403 trace:0:start_request,1:get_task(1),0:get_worker(0):190.93.247.107,0:h2_req,0:start send header,0:start send left body,1:end send left body,217:h2_get_head,2:get_response,:0

2022-02-05 17:34:12.441 - [DEBUG] create_ssl update ip:104.16.55.95 time:435 h2:1 sni:xtunnel.xyz, host:xtunnel.xyz

**Comment by 189189lw** [comment]
换成4.6.8不行，我又换成4.5.6，还是不行。。我去年买了一年得流量的，流量在2022.8月才会用完，现在还有1100多G呢

**Comment by xxnet** [comment]
从日志看不是连接不上网络，而是系统拒绝了网络请求，要从系统进行检查.

先把电脑里防火墙、杀毒软件、安全软件停掉，再启动看看。

**Comment by 189189lw** [comment]
谢谢，今天可以了。。。没动什么就可以了，谢谢了
