### ISSUE TITLE
mac系统一直不显示托盘图标，但是可以正常使用。mac版本12.0.1，xx版本4.5.6

### ISSUE THREAD

**Issue by WangXueDongDreamS** [XX-net/XX-Net#13643]
* 请不要只写标题，不写内容，请先清空或另起新行，不遵守规则的提问会被自动关闭。

* X-Tunnel 支付后流量未及时到帐请直接向 xxnet.dev@gmail.com 发邮件，并附上帐号、交易单号等详细信息。

* 是否试过[最新的版本](https://github.com/XX-net/XX-Net/releases )？

* 是否查看过 [Wiki](https://github.com/XX-net/XX-Net/wiki )？

* 是否以相关关键词搜索过类似 issues？

* 描述遇到的问题，贴出所有能帮助分析问题的状态页和日志，如包含大量文本时，请上传为 txt 文件：

* 如果问题得到解决，请务必回复相关情况，谢谢。

* 即使最终无法解决你遇到的问题，这也是正常的，因为系统和网络环境千差万别。最终结果也能帮助到后来者，请保持正常交流，再寻它法。

* 请不要只写标题，不写内容，请先清空或另起新行，不遵守规则的提问会被自动关闭。

**Comment by xxnet** [comment]
请把启动日志贴出来。
启动过程应该会有两次提示权限，要输入密码或指纹确认。

**Comment by WangXueDongDreamS** [comment]
命令行用： ./start启动的，贴的/XX-Net-4.5.6/data/launcher/launcher.log里的日志
2022-01-30 21:30:31.028 - [INFO] use build-in openssl lib
2022-01-30 21:30:31.038 - [INFO] This is Android or IOS or router.
2022-01-30 21:30:31.091 - [INFO] start XX-Net 4.5.6
2022-01-30 21:30:31.091 - [DEBUG] start confirm_xxnet_exit
2022-01-30 21:30:31.097 - [DEBUG] good, xxnet:8085 clear!
2022-01-30 21:30:31.097 - [DEBUG] finished confirm_xxnet_exit
2022-01-30 21:30:31.342 - [INFO] module x_tunnel started
2022-01-30 21:30:31.342 - [INFO] start x_tunnel time cost:245 ms
2022-01-30 21:30:31.480 - [INFO] module smart_router started
2022-01-30 21:30:31.480 - [INFO] start smart_router time cost:137 ms
2022-01-30 21:30:31.480 - [INFO] begin to start web control
2022-01-30 21:30:31.481 - [INFO] server 127.0.0.1:8085 started.
2022-01-30 21:30:31.481 - [INFO] launcher web control started.
2022-01-30 21:30:32.492 - [INFO] get uuid:22c3ff4b-933b-4a81-bfa3-d68d80d83e86
2022-01-30 21:30:32.571 - [ERROR] check_update fail:URLError(ConnectionRefusedError(61, 'Connection refused'))
2022-01-30 21:30:32.582 - [ERROR] Except stack:Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 1346, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 950, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1417, in connect
    super().connect()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 921, in connect
    self.sock = self._create_connection(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/socket.py", line 843, in create_connection
    raise err
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/socket.py", line 831, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xxx/Applications/XX-Net-4.5.6/code/default/launcher/update.py", line 285, in check_push_update
    update_content = opener.open(req_url).read()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 1389, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 1349, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 61] Connection refused>

2022-01-30 21:30:32.582 - [INFO] download https://raw.githubusercontent.com/XX-net/XX-Net/master/code/default/update_v4.txt to /Users/xxx/Applications/XX-Net-4.5.6/data/downloads/version.txt, retry:0
2022-01-30 21:30:32.584 - [WARNING] download https://raw.githubusercontent.com/XX-net/XX-Net/master/code/default/update_v4.txt to /Users/xxx/Applications/XX-Net-4.5.6/data/downloads/version.txt fail:AttributeError("'NoneType' object has no attribute 'getsockopt'")
2022-01-30 21:30:32.584 - [INFO] download https://raw.githubusercontent.com/XX-net/XX-Net/master/code/default/update_v4.txt to /Users/xxx/Applications/XX-Net-4.5.6/data/downloads/version.txt, retry:1
2022-01-30 21:30:32.585 - [WARNING] download https://raw.githubusercontent.com/XX-net/XX-Net/master/code/default/update_v4.txt to /Users/xxx/Applications/XX-Net-4.5.6/data/downloads/version.txt fail:'Error connecting to HTTP proxy 127.0.0.1:8087: [Errno 61] Connection refused'
2022-01-30 21:30:32.585 - [WARNING] check update fail:OSError('get update file https://raw.githubusercontent.com/XX-net/XX-Net/master/code/default/update_v4.txt fail:')
2022-01-30 21:30:44.351 - [DEBUG] launcher web_control 127.0.0.1:54167 GET /config?cmd=get_version 
2022-01-30 21:30:44.353 - [DEBUG] launcher web_control 127.0.0.1:54168 GET /config?cmd=get_config 
2022-01-30 21:30:44.360 - [DEBUG] launcher web_control 127.0.0.1:54167 GET /config?cmd=get_config 
2022-01-30 21:30:44.379 - [DEBUG] launcher web_control 127.0.0.1:54168 GET /update?cmd=get_progress 
2022-01-30 21:30:45.381 - [DEBUG] launcher web_control 127.0.0.1:54167 GET /update?cmd=get_info 
2022-01-30 21:32:46.829 - [DEBUG] launcher web_control 127.0.0.1:54207 GET /config?cmd=get_config 
2022-01-30 21:32:46.829 - [DEBUG] launcher web_control 127.0.0.1:54167 GET /config?cmd=get_version 
2022-01-30 21:32:46.841 - [DEBUG] launcher web_control 127.0.0.1:54167 GET /config?cmd=get_config 
2022-01-30 21:32:46.855 - [DEBUG] launcher web_control 127.0.0.1:54207 GET /update?cmd=get_progress 
2022-01-30 21:32:47.858 - [DEBUG] launcher web_control 127.0.0.1:54207 GET /update?cmd=get_info 
2022-01-30 21:33:21.955 - [DEBUG] launcher web_control 127.0.0.1:54207 GET /config?cmd=get_version 
2022-01-30 21:33:21.957 - [DEBUG] launcher web_control 127.0.0.1:54167 GET /config?cmd=get_config 
2022-01-30 21:33:21.969 - [DEBUG] launcher web_control 127.0.0.1:54167 GET /config?cmd=get_config 
2022-01-30 21:33:21.981 - [WARNING] request /module/gae_proxy/control/status no module in path
2022-01-30 21:33:21.983 - [DEBUG] launcher web_control 127.0.0.1:54207 GET /config?cmd=get_config 
2022-01-30 21:33:21.985 - [DEBUG] launcher web_control 127.0.0.1:54219 GET /update?cmd=get_progress 
2022-01-30 21:33:21.988 - [WARNING] request /module/gae_proxy/control/status no module in path
2022-01-30 21:33:22.989 - [WARNING] request /module/gae_proxy/control/status no module in path
2022-01-30 21:33:22.991 - [DEBUG] launcher web_control 127.0.0.1:54207 GET /update?cmd=get_info 
2022-01-30 21:33:22.994 - [WARNING] request /module/gae_proxy/control/status no module in path
2022-01-30 21:33:23.993 - [WARNING] request /module/gae_proxy/control/status no module in path
2022-01-30 21:33:23.996 - [WARNING] request /module/gae_proxy/control/status no module in path
2022-01-30 21:33:25.001 - [WARNING] request /module/gae_proxy/control/status no module in path
2022-01-30 21:33:25.004 - [WARNING] request /module/gae_proxy/control/status no module in path
2022-01-30 21:33:26.007 - [WARNING] request /module/gae_proxy/control/status no module in path
2022-01-30 21:33:26.011 - [WARNING] request /module/gae_proxy/control/status no module in path
2022-01-30 21:33:27.013 - [WARNING] request /module/gae_proxy/control/status no module in path
2022-01-30 21:33:27.016 - [WARNING] request /module/gae_proxy/control/status no module in path
2022-01-30 21:33:28.017 - [WARNING] request /module/gae_proxy/control/status no module in path
2022-01-30 21:33:28.020 - [WARNING] request /module/gae_proxy/control/status no module in path
2022-01-30 21:33:29.020 - [WARNING] request /module/gae_proxy/control/status no module in path
2022-01-30 21:33:29.023 - [WARNING] request /module/gae_proxy/control/status no module in path
2022-01-30 21:33:30.025 - [WARNING] request /module/gae_proxy/control/status no module in path
2022-01-30 21:33:30.027 - [WARNING] request /module/gae_proxy/control/status no module in path
2022-01-30 21:33:30.403 - [WARNING] request /module/gae_proxy/control/status no module in path
2022-01-30 21:33:31.030 - [WARNING] request /module/gae_proxy/control/status no module in path
2022-01-30 21:33:31.033 - [WARNING] request /module/gae_proxy/control/status no module in path
2022-01-30 21:33:32.034 - [WARNING] request /module/gae_proxy/control/status no module in path
2022-01-30 21:33:32.037 - [WARNING] request /module/gae_proxy/control/status no module in path
2022-01-30 21:33:33.038 - [WARNING] request /module/gae_proxy/control/status no module in path
2022-01-30 21:33:33.041 - [WARNING] request /module/gae_proxy/control/status no module in path
2022-01-30 21:33:34.041 - [WARNING] request /module/gae_proxy/control/status no module in path
2022-01-30 21:33:34.045 - [WARNING] request /module/gae_proxy/control/status no module in path
2022-01-30 21:33:35.047 - [WARNING] request /module/gae_proxy/control/status no module in path
2022-01-30 21:33:35.051 - [WARNING] request /module/gae_proxy/control/status no module in path
2022-01-30 21:33:36.050 - [WARNING] request /module/gae_proxy/control/status no module in path
2022-01-30 21:33:36.053 - [WARNING] request /module/gae_proxy/control/status no module in path
2022-01-30 21:33:37.059 - [WARNING] request /module/gae_proxy/control/status no module in path
2022-01-30 21:33:37.063 - [WARNING] request /module/gae_proxy/control/status no module in path
2022-01-30 21:33:37.295 - [DEBUG] launcher web_control 127.0.0.1:54252 GET /config?cmd=set_config&show_detail=0 
2022-01-30 21:33:38.061 - [WARNING] request /module/gae_proxy/control/status no module in path
2022-01-30 21:33:39.066 - [WARNING] request /module/gae_proxy/control/status no module in path
2022-01-30 21:33:39.299 - [DEBUG] launcher web_control 127.0.0.1:54255 GET /config?cmd=set_config&show_detail=1 
2022-01-30 21:33:40.072 - [WARNING] request /module/gae_proxy/control/status no module in path
2022-01-30 21:33:40.077 - [WARNING] request /module/gae_proxy/control/status no module in path
2022-01-30 21:33:41.075 - [WARNING] request /module/gae_proxy/control/status no module in path
2022-01-30 21:33:41.079 - [WARNING] request /module/gae_proxy/control/status no module in path
2022-01-30 21:33:41.776 - [DEBUG] launcher web_control 127.0.0.1:54260 GET /config?cmd=get_version 
2022-01-30 21:33:41.780 - [DEBUG] launcher web_control 127.0.0.1:54261 GET /config?cmd=get_config 
2022-01-30 21:33:41.799 - [DEBUG] launcher web_control 127.0.0.1:54259 GET /update?cmd=get_progress 
2022-01-30 21:33:41.804 - [DEBUG] launcher web_control 127.0.0.1:54259 GET /config?cmd=get_config 
2022-01-30 21:33:41.812 - [DEBUG] launcher web_control 127.0.0.1:54259 GET /config?cmd=get_config 
2022-01-30 21:33:42.807 - [DEBUG] launcher web_control 127.0.0.1:54259 GET /update?cmd=get_info 
2022-01-30 21:33:46.153 - [DEBUG] launcher web_control 127.0.0.1:54259 GET /config?cmd=get_config 
2022-01-30 21:33:46.156 - [DEBUG] launcher web_control 127.0.0.1:54261 GET /config?cmd=get_config 
2022-01-30 21:33:53.552 - [DEBUG] launcher web_control 127.0.0.1:54261 GET /config_proxy?cmd=get_config 
2022-01-30 21:34:00.213 - [DEBUG] launcher web_control 127.0.0.1:54261 GET /config?cmd=get_version 
2022-01-30 21:34:00.215 - [DEBUG] launcher web_control 127.0.0.1:54259 GET /config?cmd=get_config 
2022-01-30 21:34:00.217 - [DEBUG] launcher web_control 127.0.0.1:54260 GET /config?cmd=get_version 
2022-01-30 21:34:00.231 - [DEBUG] launcher web_control 127.0.0.1:54260 GET /update?cmd=get_progress 
2022-01-30 21:34:00.236 - [DEBUG] launcher web_control 127.0.0.1:54260 GET /config?cmd=get_config 
2022-01-30 21:34:01.241 - [DEBUG] launcher web_control 127.0.0.1:54260 GET /update?cmd=get_info 
2022-01-30 21:34:16.877 - [DEBUG] launcher web_control 127.0.0.1:54260 GET /config?cmd=get_version 
2022-01-30 21:34:16.877 - [DEBUG] launcher web_control 127.0.0.1:54261 GET /config?cmd=get_config 
2022-01-30 21:34:16.889 - [DEBUG] launcher web_control 127.0.0.1:54260 GET /config?cmd=get_config 
2022-01-30 21:34:16.902 - [DEBUG] launcher web_control 127.0.0.1:54261 GET /update?cmd=get_progress 
2022-01-30 21:34:17.913 - [DEBUG] launcher web_control 127.0.0.1:54260 GET /update?cmd=get_info 
2022-01-30 21:34:21.475 - [DEBUG] launcher web_control 127.0.0.1:54261 GET /config?cmd=get_config 
2022-01-30 21:34:21.475 - [DEBUG] launcher web_control 127.0.0.1:54260 GET /config?cmd=get_version 
2022-01-30 21:34:21.487 - [DEBUG] launcher web_control 127.0.0.1:54260 GET /config?cmd=get_config 
2022-01-30 21:34:21.501 - [DEBUG] launcher web_control 127.0.0.1:54261 GET /update?cmd=get_progress 
2022-01-30 21:34:22.510 - [DEBUG] launcher web_control 127.0.0.1:54260 GET /update?cmd=get_info

**Comment by xxnet** [comment]
你 试试下载 Mac 专用版本，内置了python 引擎和需要的库。
https://github.com/XX-net/XX-Net/releases/download/4.5.6/XX-Net-mac-4.5.6.7z

**Comment by WangXueDongDreamS** [comment]
> 你 试试下载 Mac 专用版本，内置了python 引擎和需要的库。 https://github.com/XX-net/XX-Net/releases/download/4.5.6/XX-Net-mac-4.5.6.7z
换成mac专用的可以了，谢谢
