### ISSUE TITLE
[发布] Android版 XX-Net 4.7.2 

### ISSUE THREAD

**Issue by xxnet** [XX-net/XX-Net#13657]
发布Androd 版本 4.7.2,  请大家测试。

https://github.com/XX-net/XX-Net/releases/download/4.7.2/XX-Net-4.7.2-debug.apk

**Comment by XLX** [comment]
三星 S21U（Android 12）启动后白屏

**Comment by xxnet** [comment]
第一次启动要等大约30秒准备运行环境

**Comment by greenlioncn** [comment]
谢谢老大，辛苦了

**Comment by whylalacantuse** [comment]
华为P40PRO HarmonyOS2.0.0.222 无法安装。。
![QQ图片20220302184159](https://user-images.githubusercontent.com/34189137/156347738-270214ec-04fd-429a-a8a5-7c3750cef442.jpg)

**Comment by Vicious-circIe** [comment]
一直白屏没法用，等待和重开或清应用数据也没用

**Comment by Maogxer** [comment]
三星s9+也是白屏。

**Comment by greenlioncn** [comment]
huawei mate30也一直是白屏，等了很久试了多次结果都是白屏

**Comment by xxnet** [comment]
发现问题了，等我改一个新版本

**Comment by whylalacantuse** [comment]
> 华为P40PRO HarmonyOS2.0.0.222 无法安装。。 ![QQ图片20220302184159](https://user-images.githubusercontent.com/34189137/156347738-270214ec-04fd-429a-a8a5-7c3750cef442.jpg)

试了新的，仍然这样显示...

**Comment by Vicious-circIe** [comment]
能用，但是edge浏览器的翻译和b站的用户头像及弹幕加载不出，google play下载不了

**Comment by Maogxer** [comment]
三星 s9+ 可以正常启动。
play商店下载不了，youtube可以看电影。facebook，twitter，telegram，instagram等都正常。

**Comment by xxnet** [comment]
Play 商店下载不了，估计是用了UDP,暂时不支持，先用其他第三方应用市场代替吧，后面再吧UDP 加上

**Comment by csdekb** [comment]
能用，我在设置中“路由策略”里选择的是“黑名单—>X-Tunnel”，并且开启了“自动尝试直连”，但是当XX-Net运行时，微信公众号里的图片和朋友圈里的图片都很难加载出来，关掉XX-Net后这些图片就能很快显示出来了，不知道是什么原因；还有希望后续能够加入“可自主选择哪些app走XX-Net的流量”的功能，谢谢！

**Comment by XLX** [comment]
GAE模式，好像无法获取到IP，提示请尝试开启IPv6，实际是开了的，同样Appid在PC端正常

**Comment by xxnet** [comment]
@csdekb 你打开“允许远程访问”，然后在PC上看着智能路由的日志，看访问微信公众号里的图片和朋友圈里的图片，看哪些没有走direct. 

自主选择哪些app走代理这个不错，不过要过段时间再开发了。

@XLX X-Tunnel要登录GAE才能工作这个现象挺奇怪的，估计有bug

**Comment by csdekb** [comment]
@xxnet 感谢回复！这两天我又试了一下，发现当XX-Net运行时（选择的模式是“黑名单—>X-Tunnel”），不仅是微信公众号和朋友圈的图片，其他国内的一些网站感觉加载速度也会变慢，不知道是我自己这边的问题还是大家普遍的问题。那个智能路由的日志我不太会看，但是根据这个操作：“有的网站只能我们自己的内网访问，当XX-Net运行时这些网站我也能访问”，说明应该是direct的。

**Comment by csdekb** [comment]
@xxnet 感谢回复！这两天我又试了一下，发现当XX-Net运行时（选择的模式是“黑名单—>X-Tunnel”），不仅是微信公众号和朋友圈的图片，其他国内的一些网站感觉加载速度也会变慢，不知道是我自己这边的问题还是大家普遍的问题。那个智能路由的日志我不太会看，但是根据这个操作：“有的网站只能我们自己的内网访问，当XX-Net运行时这些网站我也能访问”，说明应该是direct的，但不知道为啥当XX-Net运行时direct的网站会变慢。

**Comment by csdekb** [comment]
@xxnet 感谢回复！这两天我又试了一下，发现当XX-Net运行时（选择的模式是“黑名单—>X-Tunnel”），不仅是微信公众号和朋友圈的图片，其他国内的一些网站感觉加载速度也会变慢，不知道是我自己这边的问题还是大家普遍的问题。那个智能路由的日志我不太会看，但是根据这个操作：“有的网站只能我们自己的内网访问，当XX-Net运行时这些网站我也能访问”，说明应该是direct的，但不知道为啥当XX-Net运行时direct的网站会变慢。

**Comment by Vicious-circIe** [comment]
第三方贴吧打不开

2022-03-05 22:58:01.705 - [ERROR] on_query except:ValueError("invalid literal for int() with base 10: 'qb-v6'")

2022-03-05 22:58:01.705 - [ERROR] Except stack:Traceback (most recent call last): File "/data/user/0/com.xxnet.vpn/files/running/xxnet/code/default/smart_router/local/dns_server.py", line 114, in on_udp_query reply.add_answer(RR(domain, ttl=60, rdata=A(ip))) File "/data/user/0/com.xxnet.vpn/files/running/xxnet/code/default/lib/noarch/dnslib/dns.py", line 984, in __init__ self.data = tuple(map(int,data.rstrip(".").split("."))) ValueError: invalid literal for int() with base 10: 'qb-v6'


info里最后是forward to direct的是直连吗？是forward to socks的是不是就是走xtunnel？

**Comment by Vicious-circIe** [comment]
第三方贴吧打不开

2022-03-05 23:10:12.216 - [DEBUG] DNS query:c.tieba.baidu.com type:1 from ('127.0.0.1', 39033)

2022-03-05 23:10:12.217 - [ERROR] on_query except:ValueError("invalid literal for int() with base 10: 'c'")

2022-03-05 23:10:12.217 - [ERROR] Except stack:Traceback (most recent call last): File "/data/user/0/com.xxnet.vpn/files/running/xxnet/code/default/smart_router/local/dns_server.py", line 114, in on_udp_query reply.add_answer(RR(domain, ttl=60, rdata=A(ip))) File "/data/user/0/com.xxnet.vpn/files/running/xxnet/code/default/lib/noarch/dnslib/dns.py", line 984, in __init__ self.data = tuple(map(int,data.rstrip(".").split("."))) ValueError: invalid literal for int() with base 10: 'c'

info里最后是forward to direct的是直连吗？是forward to socks的是不是就是走xtunnel？

**Comment by Chem2080** [comment]
提问：是否会考虑像Xndroid一样加入分应用代理模式？👀

**Comment by xxnet** [comment]
@Chem2080 
​后面会加入分应用代理的功能。
目前先把基本的性能提高做稳定。


@Vicious-circIe 
确认是bug, 回头修复

| info里最后是forward to direct的是直连吗？是forward to socks的是不是就是走xtunnel？
是的

@csdekb 
direct的网站会变慢，原因是android  VPN 实现不完善，还在优化中。

**Comment by csdekb** [comment]
@xxnet 好的，谢谢！辛苦了 ！

**Comment by ccwwhh101** [comment]
> apk签名了，并修复了一个启动问题。
> 
> 下载链接在这里： https://github.com/XX-net/XX-Net/releases/download/4.7.2/XX-Net-4.7.2b.apk

谢谢，下载了这个版本的目前可以使用

**Comment by xxnet** [comment]
请测试新版的Android：
https://github.com/XX-net/XX-Net/releases/download/4.7.3/XX-Net-1.1.1.apk

@Vicious-circIe 你报告的bug已经修复
@csdekb  速度问题已经解决
