### ISSUE TITLE
从 4.7.4 版开始就用不了了

### ISSUE THREAD

**Issue by AlephAlpha** [XX-net/XX-Net#13671]
我的操作系统是 Linux（Manjaro），Python 版本 是 3.10.2。

打开 XX-Net 之后根本无法运行，出现以下错误，然后就退出：

```
Start version:4.7.3
2022-03-14 10:58:42.076 [launcher][INFO] Using PyGObject as the GUI Backend.
Traceback (most recent call last):
  File "/home/alephalpha/下载/XX-Net/code/default/launcher/start.py", line 44, in <module>
    import sys_platform
  File "/home/alephalpha/下载/XX-Net/code/default/launcher/sys_platform.py", line 55, in <module>
    from gtk_tray import sys_tray
  File "/home/alephalpha/下载/XX-Net/code/default/launcher/gtk_tray.py", line 62, in <module>
    import module_init
  File "/home/alephalpha/下载/XX-Net/code/default/launcher/module_init.py", line 9, in <module>
    import web_control
  File "/home/alephalpha/下载/XX-Net/code/default/launcher/web_control.py", line 54, in <module>
    i18n_translator = SimpleI18N()
  File "/home/alephalpha/下载/XX-Net/code/default/launcher/simple_i18n.py", line 13, in __init__
    self.lang = get_language()
  File "/home/alephalpha/下载/XX-Net/code/default/launcher/config.py", line 139, in get_language
    lang = _get_os_language()
  File "/home/alephalpha/下载/XX-Net/code/default/launcher/config.py", line 94, in _get_os_language
    if sys_platform.platform == "mac":
AttributeError: partially initialized module 'sys_platform' has no attribute 'platform' (most likely due to a circular import)
```

4.7.3 以及更早的版本无此问题。

---

确切来说，是从 https://github.com/XX-net/XX-Net/commit/a24d0c6176259977e3bfc88f7c2a08ca2cb73f3d 这个 commit 开始出的问题。

**Comment by AlephAlpha** [comment]
感觉是这里的问题：

https://github.com/XX-net/XX-Net/blob/fc8c2763e72c2c10e49b19188f527d5b23e9360a/code/default/launcher/sys_platform.py#L53-L61

`platform = "linux"` 应该要放到这个 `if` 之前。

**Comment by xxnet** [comment]
循环依赖问题，之前没有测试出来。 试试 4.7.7 版本：
https://github.com/XX-net/XX-Net/releases/tag/4.7.7

**Comment by AlephAlpha** [comment]
现在可以了。
