### ISSUE TITLE
[发布]  4.9.6 修复GAE 模块

### ISSUE THREAD

**Issue by xxnet** [XX-net/XX-Net#13779]
发布链接：
https://github.com/XX-net/XX-Net/releases/tag/4.9.6

Google Appid 需要重新部署，部署可以参考这里：
https://github.com/XX-net/XX-Net/tree/master/code/default/gae_proxy/server
加了流量统计和限制功能，避免扣费，可靠性还需要观察。

**Comment by XLX** [comment]
还是不太会部署，执行gcloud init，登录谷歌邮箱、点击“允许”后，自动跳到XX-Net的页面上，然后就不知道怎么选appid了

**Comment by Quantum2Bits** [comment]
不能用。certs文件夹是用原来的。从新部署了app,没有部署cron,那是要收费的。下面是出错信息：
2022-09-13 16:12:53.049 [gae_proxy][ERROR] request_gae except:AttributeError("'Config' object has no attribute 'AUTORANGE_MAXSIZE'")
2022-09-13 16:12:53.049 [gae_proxy][ERROR] Except stack:Traceback (most recent call last):
  File "code/default/gae_proxy/local/gae_handler.py", line 535, in handler
    response = request_gae_proxy(method, url, headers, body)
  File "XX-Net-4.9.7/code/default/gae_proxy/local/gae_handler.py", line 428, in request_gae_proxy
    request_headers, request_body = pack_request(method, url, headers, body, timeout)
  File "XX-Net-4.9.7/code/default/gae_proxy/local/gae_handler.py", line 256, in pack_request
    kwargs[b'maxsize'] = front.config.AUTORANGE_MAXSIZE
AttributeError: 'Config' object has no attribute 'AUTORANGE_MAXSIZE'

2022-09-13 16:12:53.049 [simple_http_server][ERROR] handler:IndexError('tuple index out of range') cmd:POST path:/dns-query from:127.0.0.1:56126
2022-09-13 16:12:53.049 [simple_http_server][ERROR] Except stack:Traceback (most recent call last):
  File "XX-Net-4.9.7/code/default/gae_proxy/local/gae_handler.py", line 535, in handler
    response = request_gae_proxy(method, url, headers, body)
  File "XX-Net-4.9.7/code/default/gae_proxy/local/gae_handler.py", line 428, in request_gae_proxy
    request_headers, request_body = pack_request(method, url, headers, body, timeout)
  File "XX-Net-4.9.7/code/default/gae_proxy/local/gae_handler.py", line 256, in pack_request
    kwargs[b'maxsize'] = front.config.AUTORANGE_MAXSIZE
AttributeError: 'Config' object has no attribute 'AUTORANGE_MAXSIZE'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "XX-Net-4.9.7/code/default/lib/noarch/simple_http_server.py", line 190, in handle_one_request
    self.do_POST()
  File "XX-Net-4.9.7/code/default/gae_proxy/local/proxy_handler.py", line 260, in do_METHOD
    return self.go_AGENT()
  File "XX-Net-4.9.7/code/default/gae_proxy/local/proxy_handler.py", line 276, in go_AGENT
    if gae_handler.handler(self.command, self.host, self.url, request_headers, payload, self.wfile, self.go_DIRECT) != "ok":
  File "XX-Net-4.9.7/code/default/gae_proxy/local/gae_handler.py", line 550, in handler
    send_response(wfile, 502, body=e.args[1]) # 502 means Gateway error.
IndexError: tuple index out of range

**Comment by xxnet** [comment]
发现是一个低级错误：
https://github.com/XX-net/XX-Net/releases/tag/4.9.8

**Comment by xxnet** [comment]
@XLX 选appid 是在命令行界面上，会列出来几个appid 让你选。

**Comment by Quantum2Bits** [comment]
这回可以了，非常感谢开发者。

**Comment by xxnet** [comment]
@Quantum2Bits  根据Google的官方文档，每个人有3个免费的作业
https://cloud.google.com/scheduler/pricing?hl=zh-cn

实际要观察

**Comment by xxnet** [comment]
如果不行可以把判断放在每次访问里，逻辑稍微复杂一点

**Comment by Quantum2Bits** [comment]
> @Quantum2Bits 根据Google的官方文档，每个人有3个免费的作业 https://cloud.google.com/scheduler/pricing?hl=zh-cn
> 
> 实际要观察

但是开通cloudscheduler本身要收费，只能免费用31天。部署cron要开通cloudscheduler.

**Comment by entzug** [comment]
> @Quantum2Bits 根据Google的官方文档，每个人有3个免费的作业 https://cloud.google.com/scheduler/pricing?hl=zh-cn
> 
> 实际要观察

我看了文档，好像是一个gmail账户一个月免费执行3次，如果一个账户有3个项目，只能免费一天

**Comment by entzug** [comment]
> > @Quantum2Bits 根据Google的官方文档，每个人有3个免费的作业 https://cloud.google.com/scheduler/pricing?hl=zh-cn
> > 实际要观察
> 
> 不知道一个job是怎么定义的。一个gae的 project （一个appid）可以有多个job.

文档里说一个月免费3次，不是按app算，按账号算

**Comment by entzug** [comment]
403 Wrong password('') 
部署的时候 改了 gae.py 里的 password ，__password__ = 'xxxxxx'
这个密码在客户端哪里设置

**Comment by xxnet** [comment]
密码在几年前我嫌复杂从界面上去掉了，要加回去也不难。
格式考虑这样： 
   pass1@appid1|pass2@appid2 
每个appid 可以有独立的密码。
下面再放一个公用密码输入框，如果有10个appid，就不用每个都加。

**Comment by xxnet** [comment]
@Quantum2Bits 
我的理解是每个cron任务跑30天算一个 job。
每个人允许3个job，最多可以有3个appid可以配置 cron

可以用算法避开这个问题：
 服务端记录上次复位日期，每次有请求来，检查上次复位日期是否过期，如果过期就复位，然后更新复位日期

**Comment by entzug** [comment]
> 还是不太会部署，执行gcloud init，登录谷歌邮箱、点击“允许”后，自动跳到XX-Net的页面上，然后就不知道怎么选appid了

[ To initialize Cloud SDK:

If you are in a remote terminal session, you can use the --console-only flag to prevent the command from launching a browser-based authorization flow, if required:

gcloud init --console-only  ]

**Comment by Quantum2Bits** [comment]
这样好多了。

**Comment by VincentFortuneDeng** [comment]
> 

我也是，PowerShell输入gcloud init后跳转浏览器，然后在浏览器中授权，但授权后跳转到xxnet配置页面，之后就无响应了。
