### ISSUE TITLE
[发布] 4.12.0 模拟Chrome TLS连接指纹

### ISSUE THREAD

**Issue by xxnet** [XX-net/XX-Net#13804]
https://github.com/XX-net/XX-Net/releases/tag/4.12.0

模拟Chrome 的连接指纹，Android版本还需要编译库，待发布。

**Comment by robinlighting** [comment]
@xxnet x总，新版本的xx-net在win7中自动退出（我下载的是win7版本的xx-net）。

**Comment by WangXueDongDreamS** [comment]
4.12版本在mac下不能启动，进程也没有，看日志好像是有报错

**Comment by xxnet** [comment]
@robinlighting 
Win7 的安装包有问题，刚刚已经更新了， 你重新下载吧：
https://github.com/XX-net/XX-Net/releases/download/4.12.0/XX-Net-win7-4.12.0.7z

**Comment by xxnet** [comment]
@WangXueDongDreamS 

Mac 版存在缺库的问题，已经修复了，请重新下载：
https://github.com/XX-net/XX-Net/releases/download/4.12.0/XX-Net-mac-4.12.0.7z

**Comment by maysilence** [comment]
Win10版启动失败
2022-10-25 17:39:32.957 - [ERROR] check_cert AttributeError("'NoneType' object has no attribute 'native'")
2022-10-25 17:39:32.963 - [ERROR] Except stack:Traceback (most recent call last):
  File "D:\XX-Net\code\4.12.0\lib\noarch\front_base\connect_creator.py", line 125, in check_cert
    peer_cert = ssl_sock.get_cert()
  File "D:\XX-Net\code\4.12.0\lib\noarch\front_base\tlslite_wrap.py", line 85, in get_cert
    "altName": cert.subject_alt_name_value.native
AttributeError: 'NoneType' object has no attribute 'native'
升级了python到3.10也不行

**Comment by maysilence** [comment]
更新，发现只有GAE有这个问题
然后重新下载了一份启动，错误变了
2022-10-25 17:49:00.279 - [ERROR] Except stack:Traceback (most recent call last):
  File "D:\XX-Net\code\default\lib\noarch\front_base\connect_creator.py", line 125, in check_cert
    peer_cert = ssl_sock.get_cert()
  File "D:\XX-Net\code\default\lib\noarch\front_base\tlslite_wrap.py", line 85, in get_cert
    "altName": cert.subject_alt_name_value.native
AttributeError: 'NoneType' object has no attribute 'native'

**Comment by FL1399** [comment]
更新版启动时提示这个
2022-10-25 22:56:42.383 - [INFO] version:4.12.0

2022-10-25 22:56:42.383 - [DEBUG] SendBuffer reset

2022-10-25 22:56:42.384 - [ERROR] bind to b'127.0.0.1':1080 fail:OSError(10013, '以一种访问权限不允许的方式做了一个访问套接字的尝试。', None, 10013, None)

2022-10-25 22:56:42.384 - [ERROR] bind to b'127.0.0.1':1081 fail:OSError(10013, '以一种访问权限不允许的方式做了一个访问套接字的尝试。', None, 10013, None)

2022-10-25 22:56:42.384 - [INFO] server 127.0.0.1:1082 started.

2022-10-25 22:56:42.384 - [INFO] Socks5 server listen:127.0.0.1:1080.

2022-10-25 22:56:48.313 - [WARNING] get_front fail

2022-10-25 22:56:58.012 - [DEBUG] x-tunnel web_control 127.0.0.1:10400 POST /login

2022-10-25 22:57:03.015 - [WARNING] get_front fail

2022-10-25 22:57:09.016 - [WARNING] get_front fail

2022-10-25 22:57:15.018 - [WARNING] get_front fail

2022-10-25 22:57:21.019 - [WARNING] get_front fail

2022-10-25 22:57:27.021 - [WARNING] get_front fail

2022-10-25 22:57:28.021 - [WARNING] api:/login fail:status:602 t:30

**Comment by xxnet** [comment]
@FL1399 1080 端口被占用了，可能是别的代理工具。

**Comment by FL1399** [comment]
好的，我去排查一下
