### ISSUE TITLE
[发布] v4.12.1 修复 GAE 模块无法工作问题

### ISSUE THREAD

**Issue by xxnet** [XX-net/XX-Net#13806]
https://github.com/XX-net/XX-Net/releases/tag/4.12.1

**Comment by maysilence** [comment]
感谢大神！！！！

**Comment by Maogxer** [comment]
安卓，打开空白。版本4.12。
![Screenshot_20221026-112911_XX-Net](https://user-images.githubusercontent.com/84484782/197927896-f9dbabd5-6d0f-4a74-8d58-250bd86251db.jpg)

**Comment by Maogxer** [comment]
安卓，打开空白。版本4.12。


![Screenshot_20221026-113034_One UI Home](https://user-images.githubusercontent.com/84484782/197928096-c942fbf0-fdc4-4b55-9e49-141f3c871ada.jpg)
![Screenshot_20221026-113040_XX-Net](https://user-images.githubusercontent.com/84484782/197928109-6a005143-7bab-4d76-8213-fa2788fd605b.jpg)

**Comment by xxnet** [comment]
@Maogxer 你试试删除app重新安装

**Comment by Maogxer** [comment]
> @Maogxer 你试试删除app重新安装

删除重新安装了。先是直接更新到4.12.0，后删除重新下载安装4.12.0，再删除下载安装4.12.1。都是同样的情况。我的是三星s9＋，android 10。

**Comment by maysilence** [comment]
大神大神，启动还是报错
2022-10-26 17:03:24.725 [simple_http_server][ERROR] handler:AttributeError("'SSLContext' object has no attribute 'supported_protocol'") cmd:GET path:/module/gae_proxy/control/status from:127.0.0.1:54898
2022-10-26 17:03:24.727 [simple_http_server][ERROR] Except stack:Traceback (most recent call last):
  File "D:\XX-Net_4.12.1\code\default\lib\noarch\simple_http_server.py", line 188, in handle_one_request
    self.do_GET()
  File "D:\XX-Net_4.12.1\code\default\launcher\web_control.py", line 181, in do_GET
    controler.do_GET()
  File "D:\XX-Net_4.12.1\code\default\gae_proxy\local\web_control.py", line 129, in do_GET
    return self.req_status_handler()
  File "D:\XX-Net_4.12.1\code\default\gae_proxy\local\web_control.py", line 322, in req_status_handler
    "openssl_version": get_openssl_version(),
  File "D:\XX-Net_4.12.1\code\default\gae_proxy\local\web_control.py", line 105, in get_openssl_version
    front.openssl_context.supported_protocol(),
AttributeError: 'SSLContext' object has no attribute 'supported_protocol'
不断的重试 127.0.0.1:54898 各个端口

**Comment by xxnet** [comment]
这个bug只影响GAE状态页面展示，不影响其他模块工作，我晚点发个版本修复。

**Comment by maysilence** [comment]
> 这个bug只影响GAE状态页面展示，不影响其他模块工作，我晚点发个版本修复。

恩恩，发现了，确实可以用，但是看不了状态，辛苦大神了！

**Comment by xxnet** [comment]
@maysilence 版本已经发了 4.12.2，有空更新一下

**Comment by maysilence** [comment]
> @maysilence 版本已经发了 4.12.2，有空更新一下

没问题了！！！大神太效率了！！！点赞！！！
