### ISSUE TITLE
ImportError: No module named pygtk

### ISSUE THREAD

**Issue by gam2046** [XX-net/XX-Net#1381]
Ubuntu 
我运行start.sh，命令行显示如下：
```
Traceback (most recent call last):
  File "launcher/start.py", line 29, in <module>
    from gtk_tray import sys_tray
  File "/.../xx-net/launcher/gtk_tray.py", line 12, in <module>
    import pygtk
ImportError: No module named pygtk
```

所以就跑不起来。

**Comment by gam2046** [comment]
sudo apt-get install -y python-gtk2

**Comment by simonasd** [comment]
@gam2046 问题已经解决？多谢分享经验
