### ISSUE TITLE
[发布] 4.13.5 修复频繁崩溃的问题，修复任务栏图标问题

### ISSUE THREAD

**Issue by Michael-X-Net** [XX-net/XX-Net#13826]
@13823

**Comment by Michael-X-Net** [comment]
建议重新从 xx-net.com 下载

**Comment by cym104** [comment]
还是有那个过一段时间连接池就掉到0的问题。我现在能稳定使用的最新版本还停留在4.8.0. 这之后的所有版本都有这样那样的问题。
=============
2022-11-21 11:14:28.872 - [WARNING] recv n:-1 errno: 2 ip:172.217.215.206
2022-11-21 11:15:00.751 - [WARNING] recv n:-1 errno: 2 ip:172.253.62.134
2022-11-21 11:15:00.994 - [WARNING] recv n:0 errno: 5 ip:172.253.62.134
2022-11-21 11:15:16.061 - [WARNING] recv n:-1 errno: 2 ip:108.177.112.188
2022-11-21 11:15:16.283 - [DEBUG] recv 1
2022-11-21 11:15:16.283 - [DEBUG] recv 2
2022-11-21 11:15:16.283 - [WARNING] recv n:-1 errno: 2 ip:108.177.112.188
2022-11-21 11:15:17.159 - [WARNING] recv n:0 errno: 5 ip:108.177.112.188
2022-11-21 11:15:19.877 - [WARNING] recv n:-1 errno: 2 ip:172.253.113.206
2022-11-21 11:15:22.208 - [DEBUG] create ssl timeout fail.
2022-11-21 11:15:22.326 - [WARNING] recv n:-1 errno: 2 ip:64.233.166.168
2022-11-21 11:15:22.572 - [DEBUG] recv 1401
2022-11-21 11:15:26.675 - [WARNING] recv n:-1 errno: 2 ip:74.125.141.188
2022-11-21 11:15:26.905 - [DEBUG] recv 1
2022-11-21 11:15:26.905 - [WARNING] recv n:-1 errno: 2 ip:74.125.141.188
2022-11-21 11:15:26.906 - [DEBUG] recv 2
2022-11-21 11:15:26.906 - [WARNING] recv n:-1 errno: 2 ip:74.125.141.188
2022-11-21 11:15:27.805 - [WARNING] recv n:0 errno: 5 ip:74.125.141.188
2022-11-21 11:15:28.987 - [WARNING] recv n:-1 errno: 2 ip:172.253.62.128
2022-11-21 11:15:29.318 - [DEBUG] recv 40
2022-11-21 11:15:29.318 - [DEBUG] recv 39
2022-11-21 11:15:29.318 - [WARNING] recv n:-1 errno: 2 ip:172.253.62.128
2022-11-21 11:15:29.318 - [WARNING] recv n:0 errno: 5 ip:172.253.62.128
2022-11-21 11:15:46.905 - [WARNING] recv n:-1 errno: 2 ip:172.217.203.188
2022-11-21 11:15:47.134 - [DEBUG] recv 1
2022-11-21 11:15:47.134 - [DEBUG] recv 2
2022-11-21 11:15:47.134 - [WARNING] recv n:-1 errno: 2 ip:172.217.203.188
2022-11-21 11:15:48.037 - [WARNING] recv n:0 errno: 5 ip:172.217.203.188
2022-11-21 11:16:31.227 - [DEBUG] connect 108.177.103.153 network fail:OSError("conn b'108.177.103.153' fail, sni:None, e:TimeoutError('timed out')")
2022-11-21 11:16:31.227 - [DEBUG] report_connect_fail:108.177.103.153
2022-11-21 11:16:37.241 - [DEBUG] connect 2404:6800:4005:800::2014 network fail:OSError("conn b'2404:6800:4005:800::2014' fail, sni:None, e:TimeoutError('timed out')")
2022-11-21 11:16:37.241 - [DEBUG] report_connect_fail:2404:6800:4005:800::2014
2022-11-21 11:16:43.253 - [DEBUG] connect 2404:6800:4012:1::2014 network fail:OSError("conn b'2404:6800:4012:1::2014' fail, sni:None, e:TimeoutError('timed out')")
2022-11-21 11:16:43.253 - [DEBUG] report_connect_fail:2404:6800:4012:1::2014
2022-11-21 11:16:49.273 - [DEBUG] connect 2404:6800:4005:801::2014 network fail:OSError("conn b'2404:6800:4005:801::2014' fail, sni:None, e:TimeoutError('timed out')")
2022-11-21 11:16:49.273 - [DEBUG] report_connect_fail:2404:6800:4005:801::2014
2022-11-21 11:16:54.049 - [WARNING] recv n:-1 errno: 2 ip:108.177.119.134
2022-11-21 11:16:54.397 - [WARNING] recv n:0 errno: 5 ip:108.177.119.134
2022-11-21 11:16:54.773 - [WARNING] recv n:-1 errno: 2 ip:172.217.194.168
2022-11-21 11:16:54.864 - [DEBUG] recv 1401
2022-11-21 11:16:55.295 - [DEBUG] connect 2607:f8b0:4000:817::2014 network fail:OSError("conn b'2607:f8b0:4000:817::2014' fail, sni:None, e:TimeoutError('timed out')")
2022-11-21 11:16:55.295 - [DEBUG] report_connect_fail IPv6 continue_fail_count:11
2022-11-21 11:16:55.295 - [DEBUG] report_connect_fail:2607:f8b0:4000:817::2014
2022-11-21 11:16:55.907 - [DEBUG] network IPv6 is ok, cost:611 ms
2022-11-21 11:17:01.308 - [DEBUG] connect 2607:f8b0:4009:807::2014 network fail:OSError("conn b'2607:f8b0:4009:807::2014' fail, sni:None, e:TimeoutError('timed out')")
2022-11-21 11:17:01.308 - [DEBUG] report_connect_fail:2607:f8b0:4009:807::2014
2022-11-21 11:17:05.000 - [WARNING] recv n:-1 errno: 2 ip:104.199.185.90
2022-11-21 11:17:05.065 - [WARNING] recv n:-1 errno: 2 ip:104.199.185.90
2022-11-21 11:17:05.065 - [DEBUG] recv 33
2022-11-21 11:17:05.065 - [WARNING] recv n:0 errno: 6 ip:104.199.185.90
2022-11-21 11:17:05.586 - [DEBUG] recv 40
2022-11-21 11:17:05.587 - [WARNING] recv n:-1 errno: 2 ip:64.233.183.129
2022-11-21 11:17:05.808 - [DEBUG] recv 39
2022-11-21 11:17:05.808 - [WARNING] recv n:-1 errno: 2 ip:64.233.183.129
2022-11-21 11:17:05.809 - [WARNING] recv n:0 errno: 5 ip:64.233.183.129
2022-11-21 11:17:07.323 - [DEBUG] connect 2607:f8b0:4004:801::2014 network fail:OSError("conn b'2607:f8b0:4004:801::2014' fail, sni:None, e:TimeoutError('timed out')")
2022-11-21 11:17:07.323 - [DEBUG] report_connect_fail:2607:f8b0:4004:801::2014
2022-11-21 11:17:31.120 - [WARNING] recv n:-1 errno: 2 ip:172.253.58.188
2022-11-21 11:17:31.326 - [DEBUG] recv 1
2022-11-21 11:17:31.326 - [DEBUG] recv 2
2022-11-21 11:17:31.326 - [WARNING] recv n:-1 errno: 2 ip:172.253.58.188
2022-11-21 11:17:32.144 - [WARNING] recv n:0 errno: 5 ip:172.253.58.188
2022-11-21 11:17:37.154 - [WARNING] recv n:-1 errno: 2 ip:172.253.58.134
2022-11-21 11:17:37.360 - [WARNING] recv n:0 errno: 5 ip:172.253.58.134
2022-11-21 11:17:44.947 - [WARNING] recv n:-1 errno: 2 ip:216.58.214.172
2022-11-21 11:17:45.086 - [WARNING] recv n:-1 errno: 2 ip:209.85.200.168
2022-11-21 11:17:45.187 - [WARNING] recv n:0 errno: 5 ip:216.58.214.172
2022-11-21 11:17:45.314 - [DEBUG] recv 1401
2022-11-21 11:17:52.920 - [WARNING] recv n:-1 errno: 2 ip:172.217.24.80
2022-11-21 11:17:52.977 - [DEBUG] recv 40
2022-11-21 11:17:52.977 - [DEBUG] recv 39
2022-11-21 11:17:52.977 - [WARNING] recv n:-1 errno: 2 ip:172.217.24.80
2022-11-21 11:17:52.977 - [WARNING] recv n:0 errno: 5 ip:172.217.24.80
2022-11-21 11:18:29.495 - [WARNING] recv n:-1 errno: 2 ip:216.239.36.157
2022-11-21 11:18:33.282 - [WARNING] recv n:-1 errno: 2 ip:108.177.13.188
2022-11-21 11:18:35.475 - [DEBUG] recv 1
2022-11-21 11:18:35.475 - [DEBUG] recv 2
2022-11-21 11:18:35.475 - [WARNING] recv n:-1 errno: 2 ip:108.177.13.188
2022-11-21 11:18:36.738 - [WARNING] recv n:0 errno: 5 ip:108.177.13.188
2022-11-21 11:18:38.545 - [WARNING] recv n:-1 errno: 2 ip:172.253.58.134
2022-11-21 11:18:38.747 - [WARNING] recv n:0 errno: 5 ip:172.253.58.134
2022-11-21 11:18:43.382 - [WARNING] recv n:-1 errno: 2 ip:216.239.36.150
2022-11-21 11:18:45.995 - [WARNING] recv n:-1 errno: 2 ip:108.177.103.134
2022-11-21 11:18:46.200 - [WARNING] recv n:0 errno: 5 ip:108.177.103.134
2022-11-21 11:19:12.431 - [WARNING] recv n:-1 errno: 2 ip:172.217.193.128
2022-11-21 11:19:12.681 - [DEBUG] recv 40
2022-11-21 11:19:12.681 - [DEBUG] recv 39
2022-11-21 11:19:12.681 - [WARNING] recv n:-1 errno: 2 ip:172.217.193.128
2022-11-21 11:19:12.681 - [WARNING] recv n:0 errno: 5 ip:172.217.193.128
2022-11-21 11:19:15.626 - [WARNING] recv n:-1 errno: 2 ip:173.194.194.188
2022-11-21 11:19:15.845 - [DEBUG] recv 1
2022-11-21 11:19:15.845 - [DEBUG] recv 2
2022-11-21 11:19:15.845 - [WARNING] recv n:-1 errno: 2 ip:173.194.194.188
2022-11-21 11:19:16.730 - [WARNING] recv n:0 errno: 5 ip:173.194.194.188
2022-11-21 11:19:17.042 - [WARNING] recv n:-1 errno: 2 ip:108.177.119.168
2022-11-21 11:19:17.301 - [DEBUG] recv 1401
2022-11-21 11:19:17.578 - [WARNING] recv n:-1 errno: 2 ip:104.199.185.243
2022-11-21 11:19:17.672 - [DEBUG] recv 223
2022-11-21 11:19:17.678 - [ERROR] scan_ip_worker except:TypeError("'in ' requires string as left operand, not bytes")
2022-11-21 11:19:17.681 - [ERROR] Except stack:Traceback (most recent call last): File "C:\Program Files (x86)\XX-Net\code\4.14.5\lib\noarch\front_base\ip_manager.py", line 746, in scan_ip_worker result = self.check_ip(ip_str) File "C:\Program Files (x86)\XX-Net\code\4.14.5\gae_proxy\local\front.py", line 88, in check_ip return self.ip_checker.check_ip(ip, sni=sni, host=host) File "C:\Program Files (x86)\XX-Net\code\4.14.5\lib\noarch\front_base\check_ip.py", line 74, in check_ip if not self.check_response(response): File "C:\Program Files (x86)\XX-Net\code\4.14.5\gae_proxy\local\check_ip.py", line 55, in check_response if b"gws" not in server_type and b"Google Frontend" not in server_type and b"GFE" not in server_type: TypeError: 'in ' requires string as left operand, not bytes
2022-11-21 11:19:40.037 - [DEBUG] c

**Comment by lgeger** [comment]
这一版非常不稳定，登陆了之后网页访问不了，比如google，日志里也都是warning

**Comment by Michael-X-Net** [comment]
新版3.13.6 发布，修复上面反馈的问题
