### ISSUE TITLE
[发布] v4.13.4 修复异常奔溃错误

### ISSUE THREAD

**Issue by xxnet** [XX-net/XX-Net#13823]
https://github.com/XX-net/XX-Net/releases/tag/4.14.4

需要重现下载安装，建议从 https://xx-net.com 上下载独立版本安装。
#13821

**Comment by changeCat** [comment]
windows11  4.13.4版本，基本登陆失败，登录成功也不能连谷歌，右下角任务栏没有xx图标，一直回退到4.13.1基本可以正常使用
4.13.4的日志：
2022-11-19 18:25:20.922 - [INFO] version:4.13.4

2022-11-19 18:25:20.922 - [DEBUG] SendBuffer reset

2022-11-19 18:25:20.922 - [INFO] server 127.0.0.1:1080 started.

2022-11-19 18:25:20.922 - [INFO] Socks5 server listen:127.0.0.1:1080.

2022-11-19 18:25:20.990 - [WARNING] Socks4 connect fail, no conn_id

2022-11-19 18:25:20.990 - [WARNING] create conn fail

2022-11-19 18:25:21.028 - [WARNING] Socks4 connect fail, no conn_id

2022-11-19 18:25:21.245 - [WARNING] create conn fail

2022-11-19 18:25:21.736 - [WARNING] create conn fail

2022-11-19 18:25:21.738 - [WARNING] Socks4 connect fail, no conn_id

2022-11-19 18:25:23.557 - [DEBUG] x-tunnel web_control 127.0.0.1:1984 POST /login

2022-11-19 18:25:23.896 - [WARNING] create conn fail

2022-11-19 18:25:23.926 - [WARNING] Socks4 connect fail, no conn_id

2022-11-19 18:25:23.936 - [WARNING] create conn fail

2022-11-19 18:25:23.936 - [WARNING] Socks4 connect fail, no conn_id

2022-11-19 18:25:24.858 - [INFO] api:/login success t:1299

2022-11-19 18:25:24.858 - [INFO] update xt_server v3.xx-net.org:443

2022-11-19 18:25:24.859 - [INFO] request_balance host:v3.xx-net.org port:443 balance:16.800000 quota:25572487376525.000000

2022-11-19 18:25:35.952 - [WARNING] front retry v3.xx-net.org/data

2022-11-19 18:25:35.989 - [DEBUG] req_info in force

2022-11-19 18:25:35.989 - [DEBUG] x_tunnel force update info

2022-11-19 18:25:36.276 - [INFO] api:/login success t:285

2022-11-19 18:25:36.277 - [INFO] request_balance host:v3.xx-net.org port:443 balance:16.800000 quota:25572487375058.000000

2022-11-19 18:25:36.965 - [WARNING] login session fail, status:602

2022-11-19 18:25:38.303 - [DEBUG] x-tunnel web_control 127.0.0.1:1991 POST /login

2022-11-19 18:25:38.590 - [INFO] api:/login success t:286

2022-11-19 18:25:38.590 - [INFO] update xt_server v3.xx-net.org:443

2022-11-19 18:25:38.591 - [INFO] request_balance host:v3.xx-net.org port:443 balance:16.800000 quota:25572487375058.000000

2022-11-19 18:25:40.483 - [DEBUG] req_info in force

2022-11-19 18:25:40.484 - [DEBUG] x_tunnel force update info

2022-11-19 18:25:40.765 - [INFO] api:/login success t:280

2022-11-19 18:25:40.766 - [INFO] request_balance host:v3.xx-net.org port:443 balance:16.800000 quota:25572487375058.000000

2022-11-19 18:25:45.214 - [DEBUG] req_info in force

2022-11-19 18:25:45.214 - [DEBUG] x_tunnel force update info

2022-11-19 18:25:45.497 - [INFO] api:/login success t:282

2022-11-19 18:25:45.501 - [INFO] request_balance host:v3.xx-net.org port:443 balance:16.800000 quota:25572487375058.000000

2022-11-19 18:25:52.552 - [DEBUG] req_info in force

2022-11-19 18:25:52.553 - [DEBUG] x_tunnel force update info

2022-11-19 18:25:52.832 - [INFO] api:/login success t:279

2022-11-19 18:25:52.833 - [INFO] request_balance host:v3.xx-net.org port:443 balance:16.800000 quota:25572487375058.000000

2022-11-19 18:25:56.149 - [WARNING] front retry v3.xx-net.org/data

2022-11-19 18:25:57.152 - [WARNING] login session fail, status:602

2022-11-19 18:25:57.152 - [WARNING] x-tunnel login_session fail, session not start

2022-11-19 18:26:08.167 - [WARNING] front retry v3.xx-net.org/data

2022-11-19 18:26:09.182 - [WARNING] login session fail, status:602

2022-11-19 18:26:13.213 - [DEBUG] req_info in force

2022-11-19 18:26:13.214 - [DEBUG] x_tunnel force update info

2022-11-19 18:26:13.504 - [INFO] api:/login success t:289

2022-11-19 18:26:13.505 - [INFO] request_balance host:v3.xx-net.org port:443 balance:16.800000 quota:25572487375058.000000

2022-11-19 18:26:19.243 - [WARNING] get_front fail

2022-11-19 18:26:19.243 - [WARNING] login session fail, status:602

2022-11-19 18:26:20.466 - [DEBUG] req_info in force

2022-11-19 18:26:20.466 - [DEBUG] x_tunnel force update info

2022-11-19 18:26:20.758 - [INFO] api:/login success t:290

2022-11-19 18:26:20.759 - [INFO] request_balance host:v3.xx-net.org port:443 balance:16.800000 quota:25572487375058.000000

2022-11-19 18:26:21.624 - [INFO] login_session bytearray(b'xophojlm') time:24471 msg:Success

2022-11-19 18:26:21.626 - [INFO] session started.

2022-11-19 18:26:21.627 - [WARNING] session try to run but is running.

2022-11-19 18:26:21.627 - [INFO] socks5 ('127.0.0.1', 2009) connect to alive.github.com:443 conn_id:2

2022-11-19 18:26:21.628 - [INFO] socks5 ('127.0.0.1', 2022) connect to alive.github.com:443 conn_id:4

2022-11-19 18:26:21.628 - [INFO] socks5 ('127.0.0.1', 2024) connect to mtalk.google.com:443 conn_id:6

2022-11-19 18:26:21.628 - [INFO] socks5 ('127.0.0.1', 2031) connect to www.google.com.hk:443 conn_id:8

2022-11-19 18:26:21.628 - [INFO] socks5 ('127.0.0.1', 2032) connect to www.gstatic.com:443 conn_id:10

2022-11-19 18:26:21.628 - [INFO] Socks4:('127.0.0.1', 2033) to 140.82.113.26:443, conn_id:12

2022-11-19 18:26:21.628 - [INFO] socks5 ('127.0.0.1', 2034) connect to alive.github.com:443 conn_id:14

2022-11-19 18:26:21.628 - [INFO] Socks4:('127.0.0.1', 2038) to 140.82.113.26:443, conn_id:16

2022-11-19 18:26:21.628 - [INFO] Socks4:('127.0.0.1', 2039) to 74.125.203.188:443, conn_id:18

2022-11-19 18:26:21.628 - [INFO] socks5 ('127.0.0.1', 2040) connect to www.google.com.hk:443 conn_id:20

2022-11-19 18:26:21.629 - [DEBUG] Conn session:bytearray(b'xophojlm') conn:2 recv socket closed

2022-11-19 18:26:21.631 - [DEBUG] Conn session:bytearray(b'xophojlm') conn:4 recv socket closed

2022-11-19 18:26:21.631 - [DEBUG] Conn session:bytearray(b'xophojlm') conn:6 recv socket closed

2022-11-19 18:26:21.633 - [DEBUG] Conn session:xophojlm conn:2 stop:recv fail.

2022-11-19 18:26:21.633 - [DEBUG] Conn session:xophojlm conn:4 stop:recv fail.

2022-11-19 18:26:21.633 - [DEBUG] Conn session:xophojlm conn:6 stop:recv fail.

2022-11-19 18:26:21.633 - [DEBUG] remove conn:2 alive.github.com:443

2022-11-19 18:26:21.633 - [DEBUG] remove conn:4 alive.github.com:443

2022-11-19 18:26:21.633 - [DEBUG] remove conn:6 mtalk.google.com:443

2022-11-19 18:26:22.019 - [DEBUG] wid:0 no:1 rt:0.391102 st:0.097000 sw:25 snd:0 rcv:1200 s_pool:0 on_road:3 tor:3 sp:5

2022-11-19 18:26:22.020 - [DEBUG] Conn session:bytearray(b'xophojlm') conn:8 recv socket closed

2022-11-19 18:26:22.020 - [DEBUG] Conn session:xophojlm conn:8 stop:recv fail.

2022-11-19 18:26:22.021 - [DEBUG] remove conn:8 www.google.com.hk:443

2022-11-19 18:26:22.037 - [DEBUG] wid:1 no:2 rt:0.409122 st:0.060000 sw:25 snd:0 rcv:8520 s_pool:0 on_road:3 tor:3 sp:25

2022-11-19 18:26:22.297 - [DEBUG] wid:0 no:5 rt:0.277011 st:0.000000 sw:25 snd:0 rcv:2019 s_pool:0 on_road:4 tor:3 sp:8

2022-11-19 18:26:22.366 - [DEBUG] wid:4 no:7 rt:0.312893 st:0.000000 sw:25 snd:3566 rcv:6773 s_pool:0 on_road:5 tor:3 sp:34

2022-11-19 18:26:22.427 - [DEBUG] wid:2 no:3 rt:0.798269 st:0.454000 sw:25 snd:0 rcv:7982 s_pool:0 on_road:5 tor:3 sp:24

2022-11-19 18:26:22.621 - [DEBUG] wid:1 no:6 rt:0.584326 st:0.156000 sw:25 snd:2336 rcv:42949 s_pool:0 on_road:6 tor:3 sp:106

2022-11-19 18:26:22.658 - [INFO] Socks4:('127.0.0.1', 2043) to 202.160.128.205:443, conn_id:22

2022-11-19 18:26:22.827 - [DEBUG] wid:3 no:4 rt:1.185625 st:0.856000 sw:25 snd:4881 rcv:284 s_pool:0 on_road:8 tor:3 sp:16

2022-11-19 18:26:22.828 - [DEBUG] Conn session:bytearray(b'xophojlm') conn:16 Peer Close:recv closed

2022-11-19 18:26:22.828 - [DEBUG] Conn session:bytearray(b'xophojlm') conn:12 Peer Close:recv closed

2022-11-19 18:26:22.828 - [DEBUG] Conn session:bytearray(b'xophojlm') conn:14 Peer Close:recv closed

2022-11-19 18:26:22.828 - [DEBUG] Conn session:bytearray(b'xophojlm') conn:12 recv socket closed

2022-11-19 18:26:22.828 - [DEBUG] Conn session:bytearray(b'xophojlm') conn:14 recv socket closed

2022-11-19 18:26:22.828 - [DEBUG] Conn session:bytearray(b'xophojlm') conn:16 recv socket closed

2022-11-19 18:26:22.829 - [DEBUG] Conn session:xophojlm conn:16 stop:peer close

2022-11-19 18:26:22.829 - [DEBUG] Conn session:xophojlm conn:12 stop:peer close

2022-11-19 18:26:22.829 - [DEBUG] Conn session:xophojlm conn:14 stop:peer close

2022-11-19 18:26:22.829 - [DEBUG] Conn session:xophojlm conn:12 stop:recv fail.

2022-11-19 18:26:22.830 - [DEBUG] Conn session:xophojlm conn:14 stop:recv fail.

2022-11-19 18:26:22.830 - [DEBUG] Conn session:xophojlm conn:16 stop:recv fail.

2022-11-19 18:26:22.830 - [DEBUG] remove conn:16 140.82.113.26:443

2022-11-19 18:26:22.830 - [DEBUG] remove conn:12 140.82.113.26:443

2022-11-19 18:26:22.830 - [DEBUG] remove conn:14 alive.github.com:443

2022-11-19 18:26:22.831 - [DEBUG] remove conn:12 140.82.113.26:443

2022-11-19 18:26:22.831 - [DEBUG] remove conn:14 alive.github.com:443

2022-11-19 18:26:22.831 - [DEBUG] remove conn:16 140.82.113.26:443

2022-11-19 18:26:22.831 - [DEBUG] remove conn:12

2022-11-19 18:26:22.832 - [DEBUG] remove conn:14

2022-11-19 18:26:22.832 - [DEBUG] remove conn:16

2022-11-19 18:26:22.843 - [INFO] Socks4:('127.0.0.1', 2044) to 142.251.43.14:443, conn_id:24

2022-11-19 18:26:22.856 - [DEBUG] wid:5 no:9 rt:0.549204 st:0.264000 sw:25 snd:52 rcv:679 s_pool:0 on_road:8 tor:3 sp:3

2022-11-19 18:26:22.897 - [DEBUG] wid:1 no:13 rt:0.276456 st:0.000000 sw:25 snd:0 rcv:131 s_pool:0 on_road:8 tor:3 sp:1

2022-11-19 18:26:23.116 - [INFO] Socks4:('127.0.0.1', 2045) to 202.160.128.205:443, conn_id:26

2022-11-19 18:26:23.117 - [INFO] Socks4:('127.0.0.1', 2046) to 202.160.128.205:443, conn_id:28

2022-11-19 18:26:23.117 - [INFO] Socks4:('127.0.0.1', 2047) to 202.160.128.205:443, conn_id:30

2022-11-19 18:26:23.131 - [INFO] Socks4:('127.0.0.1', 2048) to 202.160.128.205:443, conn_id:32

2022-11-19 18:26:23.634 - [DEBUG] wid:0 no:8 rt:1.337418 st:1.035000 sw:25 snd:0 rcv:6943 s_pool:0 on_road:10 tor:3 sp:24

2022-11-19 18:26:24.130 - [DEBUG] wid:4 no:10 rt:1.743162 st:1.468000 sw:25 snd:344 rcv:1040 s_pool:0 on_road:11 tor:3 sp:6

2022-11-19 18:26:24.199 - [DEBUG] wid:2 no:11 rt:1.771978 st:1.486000 sw:25 snd:0 rcv:9344 s_pool:0 on_road:11 tor:3 sp:34

2022-11-19 18:26:24.221 - [DEBUG] wid:6 no:12 rt:1.772010 st:1.449000 sw:25 snd:131 rcv:7552 s_pool:0 on_road:11 tor:3 sp:25

2022-11-19 18:26:24.382 - [INFO] Socks4:('127.0.0.1', 2049) to 142.251.43.14:443, conn_id:34

2022-11-19 18:26:24.664 - [INFO] Socks4:('127.0.0.1', 2050) to 202.160.128.205:443, conn_id:36

2022-11-19 18:26:25.141 - [DEBUG] wid:7 no:14 rt:2.500278 st:2.216000 sw:25 snd:60 rcv:6783 s_pool:0 on_road:13 tor:3 sp:25

2022-11-19 18:26:25.612 - [DEBUG] wid:8 no:15 rt:2.938747 st:2.658000 sw:25 snd:825 rcv:1720 s_pool:0 on_road:13 tor:3 sp:10

2022-11-19 18:26:25.630 - [DEBUG] wid:5 no:17 rt:2.773862 st:2.451000 sw:25 snd:784 rcv:81 s_pool:0 on_road:12 tor:3 sp:3

2022-11-19 18:26:26.238 - [DEBUG] wid:3 no:16 rt:3.394461 st:3.049000 sw:25 snd:96 rcv:21 s_pool:0 on_road:13 tor:3 sp:1

2022-11-19 18:26:26.603 - [INFO] Socks4:('127.0.0.1', 2051) to 203.208.40.34:443, conn_id:38

2022-11-19 18:26:27.234 - [DEBUG] wid:1 no:18 rt:4.335766 st:4.020000 sw:25 snd:0 rcv:21 s_pool:0 on_road:13 tor:3 sp:1

2022-11-19 18:26:27.338 - [DEBUG] wid:9 no:19 rt:4.206889 st:3.895000 sw:25 snd:1951 rcv:4546 s_pool:0 on_road:13 tor:3 sp:22

2022-11-19 18:26:27.936 - [DEBUG] wid:10 no:20 rt:4.788926 st:4.468000 sw:25 snd:571 rcv:1000 s_pool:0 on_road:13 tor:3 sp:6

2022-11-19 18:26:32.956 - [DEBUG] wid:11 no:22 rt:9.306816 st:9.040000 sw:25 snd:1361 rcv:1000 s_pool:0 on_road:12 tor:3 sp:10

2022-11-19 18:26:37.966 - [DEBUG] wid:0 no:21 rt:14.332183 st:14.003000 sw:25 snd:0 rcv:1000 s_pool:0 on_road:11 tor:3 sp:4

2022-11-19 18:26:39.937 - [INFO] Socks4:('127.0.0.1', 2055) to 140.82.113.26:443, conn_id:40

2022-11-19 18:26:40.263 - [DEBUG] wid:4 no:23 rt:16.107996 st:15.835000 sw:25 snd:52 rcv:2858 s_pool:0 on_road:12 tor:3 sp:12

2022-11-19 18:26:40.562 - [DEBUG] wid:2 no:24 rt:16.363556 st:16.084000 sw:25 snd:0 rcv:713 s_pool:0 on_road:12 tor:3 sp:3

2022-11-19 18:26:40.870 - [DEBUG] wid:6 no:25 rt:16.636530 st:16.357000 sw:25 snd:60 rcv:115 s_pool:0 on_road:13 tor:3 sp:2

2022-11-19 18:26:45.873 - [DEBUG] wid:12 no:26 rt:21.481359 st:21.163000 sw:25 snd:647 rcv:115 s_pool:0 on_road:12 tor:3 sp:3

2022-11-19 18:26:50.084 - [DEBUG] wid:13 no:27 rt:25.403808 st:25.087000 sw:25 snd:571 rcv:21 s_pool:0 on_road:11 tor:3 sp:3

2022-11-19 18:26:50.484 - [DEBUG] wid:7 no:28 rt:25.325074 st:25.068000 sw:25 snd:3250 rcv:21 s_pool:0 on_road:10 tor:3 sp:14

2022-11-19 18:26:50.885 - [DEBUG] wid:5 no:29 rt:25.253950 st:24.972000 sw:25 snd:52 rcv:115 s_pool:0 on_road:9 tor:3 sp:2

2022-11-19 18:26:50.982 - [DEBUG] wid:8 no:30 rt:25.332033 st:25.063000 sw:25 snd:60 rcv:21 s_pool:0 on_road:8 tor:3 sp:1

2022-11-19 18:26:51.989 - [DEBUG] wid:3 no:31 rt:25.362147 st:25.088000 sw:25 snd:819 rcv:21 s_pool:0 on_road:7 tor:3 sp:4

2022-11-19 18:26:52.593 - [DEBUG] wid:1 no:32 rt:25.358796 st:25.072000 sw:25 snd:0 rcv:21 s_pool:0 on_road:6 tor:3 sp:1

2022-11-19 18:26:52.667 - [DEBUG] Conn session:bytearray(b'xophojlm') conn:22 recv socket closed

2022-11-19 18:26:52.667 - [DEBUG] Conn session:xophojlm conn:22 stop:recv fail.

2022-11-19 18:26:52.667 - [DEBUG] remove conn:22 202.160.128.205:443

2022-11-19 18:26:52.693 - [DEBUG] wid:9 no:33 rt:25.338757 st:25.066000 sw:25 snd:95 rcv:21 s_pool:0 on_road:7 tor:3 sp:1

2022-11-19 18:26:52.956 - [DEBUG] wid:0 no:34 rt:14.989395 st:14.788000 sw:25 snd:0 rcv:54 s_pool:0 on_road:6 tor:3 sp:2

2022-11-19 18:26:52.956 - [DEBUG] conn:22 not exist

2022-11-19 18:26:53.129 - [DEBUG] Conn session:bytearray(b'xophojlm') conn:26 recv socket closed

2022-11-19 18:26:53.129 - [DEBUG] Conn session:bytearray(b'xophojlm') conn:28 recv socket closed

2022-11-19 18:26:53.129 - [DEBUG] Conn session:bytearray(b'xophojlm') conn:30 recv socket closed

2022-11-19 18:26:53.129 - [DEBUG] Conn session:xophojlm conn:26 stop:recv fail.

2022-11-19 18:26:53.129 - [DEBUG] Conn session:xophojlm conn:28 stop:recv fail.

2022-11-19 18:26:53.129 - [DEBUG] Conn session:xophojlm conn:30 stop:recv fail.

2022-11-19 18:26:53.130 - [DEBUG] remove conn:26 202.160.128.205:443

2022-11-19 18:26:53.130 - [DEBUG] remove conn:28 202.160.128.205:443

2022-11-19 18:26:53.130 - [DEBUG] remove conn:30 202.160.128.205:443

2022-11-19 18:26:53.145 - [DEBUG] Conn session:bytearray(b'xophojlm') conn:32 recv socket closed

2022-11-19 18:26:53.145 - [DEBUG] Conn session:xophojlm conn:32 stop:recv fail.

2022-11-19 18:26:53.145 - [DEBUG] remove conn:32 202.160.128.205:443

2022-11-19 18:26:53.448 - [DEBUG] wid:10 no:35 rt:13.495284 st:13.301000 sw:25 snd:569 rcv:104 s_pool:0 on_road:8 tor:3 sp:5

2022-11-19 18:26:53.448 - [DEBUG] conn:26 not exist

2022-11-19 18:26:53.448 - [DEBUG] conn:28 not exist

2022-11-19 18:26:53.448 - [DEBUG] conn:30 not exist

2022-11-19 18:26:53.554 - [DEBUG] wid:4 no:36 rt:13.265648 st:13.066000 sw:25 snd:1194 rcv:54 s_pool:0 on_road:7 tor:3 sp:8

2022-11-19 18:26:53.554 - [DEBUG] conn:32 not exist

2022-11-19 18:26:54.672 - [DEBUG] Conn session:bytearray(b'xophojlm') conn:36 recv socket closed

2022-11-19 18:26:54.672 - [DEBUG] Conn session:xophojlm conn:36 stop:recv fail.

2022-11-19 18:26:54.672 - [DEBUG] remove conn:36 202.160.128.205:443

2022-11-19 18:26:55.059 - [DEBUG] wid:2 no:37 rt:14.495248 st:14.297000 sw:25 snd:0 rcv:54 s_pool:0 on_road:7 tor:3 sp:2

2022-11-19 18:26:55.059 - [DEBUG] conn:36 not exist

**Comment by cym104** [comment]
这个版本倒确实不会崩溃了，但是会反复出形如下面这样的报错，导致连接池总是过一段时间就会狂掉：

2022-11-19 22:03:42.031 - [WARNING] recv errno: 2 ip:2a00:1450:400e:80c::2014
2022-11-19 22:03:42.303 - [WARNING] recv errno: 2 ip:2a00:1450:400e:80c::2014
2022-11-19 22:03:42.304 - [WARNING] recv errno: 5 ip:2a00:1450:400e:80c::2014
2022-11-19 22:03:42.304 - [WARNING] h1 2a00:1450:400e:80c::2014 HEAD keep alive request fail:OSError(2)
2022-11-19 22:03:42.304 - [WARNING] 2a00:1450:400e:80c::2014 trace: 0:connect, 4629:init, 1003:head,:273, processed:0, transfered:0, sni:None

**Comment by cym104** [comment]
2022-11-19 22:13:54.487 - [ERROR] gae_handler.handler send response fail. e:SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:2396)') https://gql.reddit.com/

2022-11-19 22:13:54.487 - [ERROR] Except stack:Traceback (most recent call last): File "C:\Program Files (x86)\XX-Net\code\4.13.4\gae_proxy\local\gae_handler.py", line 696, in handler send_response_headers() File "C:\Program Files (x86)\XX-Net\code\4.13.4\gae_proxy\local\gae_handler.py", line 603, in send_response_headers send_header(wfile, key, value) File "C:\Program Files (x86)\XX-Net\code\4.13.4\gae_proxy\local\gae_handler.py", line 188, in send_header wfile.write(b"undefined: undefined\r\n" % (keyword, value)) File "C:\Program Files (x86)\XX-Net\python3\lib\socket.py", line 723, in write return self._sock.send(b) File "C:\Program Files (x86)\XX-Net\python3\lib\ssl.py", line 1205, in send return self._sslobj.write(data) ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:2396)

**Comment by Maogxer** [comment]
> https://github.com/XX-net/XX-Net/releases/tag/4.14.4
> 
> 需要重现下载安装，建议从 https://xx-net.com 上下载独立版本安装。 #13821

为什么从https://xx-net.com上下载，总是出现这个：
![Uploading Screenshot_20221120-135243_Chrome.jpg…]()

**Comment by Michael-X-Net** [comment]
@Maogxer 下载超时问题修复了

**Comment by Michael-X-Net** [comment]
@cym104  新版问题应该解决了：
https://github.com/XX-net/XX-Net/issues/13826
