### ISSUE TITLE
开启ipv6时，提示：进程：GAEProxy无响应，可能已退出

### ISSUE THREAD

**Issue by starsforever** [XX-net/XX-Net#13978]
其他一切显示正常，但无法开启IPv6，提示进程：GAEProxy无响应，可能已退出
![捕获](https://github.com/XX-net/XX-Net/assets/32722904/a8363722-8549-4db9-87a5-bb48bcde574c)
![捕获2](https://github.com/XX-net/XX-Net/assets/32722904/1bc36547-eac1-4951-a020-61a29b7f92d3)

诊断信息如下：
2023-10-04 20:23:09.042 - [INFO] start gae_proxy time cost:285 ms
2023-10-04 20:23:09.043 - [INFO] begin to start web control:[('127.0.0.1', 8085)]
2023-10-04 20:23:09.043 - [INFO] server 127.0.0.1:8085 started.
2023-10-04 20:23:09.043 - [INFO] launcher web control started.
2023-10-04 20:23:09.045 - [DEBUG] Popup http://localhost:8085/ on startup
2023-10-04 20:23:10.332 - [DEBUG] launcher web_control 127.0.0.1:2521 GET /config?cmd=get_version 
2023-10-04 20:23:10.338 - [DEBUG] launcher web_control 127.0.0.1:2521 GET /config?cmd=get_config 
2023-10-04 20:23:10.437 - [DEBUG] launcher web_control 127.0.0.1:2528 GET /update?cmd=get_progress 
2023-10-04 20:23:10.437 - [DEBUG] launcher web_control 127.0.0.1:2522 GET /config?cmd=get_config 
2023-10-04 20:23:19.620 - [DEBUG] launcher web_control 127.0.0.1:2521 GET /config?cmd=get_version 
2023-10-04 20:23:19.627 - [DEBUG] launcher web_control 127.0.0.1:2528 GET /config?cmd=get_config 
2023-10-04 20:23:19.629 - [DEBUG] launcher web_control 127.0.0.1:2522 GET /config?cmd=get_version 
2023-10-04 20:23:19.717 - [DEBUG] launcher web_control 127.0.0.1:2522 GET /update?cmd=get_progress 
2023-10-04 20:23:22.479 - [DEBUG] launcher web_control 127.0.0.1:2522 GET /log_files 
2023-10-04 20:23:24.548 - [DEBUG] launcher web_control 127.0.0.1:2610 GET /debug 
2023-10-04 20:23:24.883 - [ERROR] debug:KeyError(6020)
2023-10-04 20:23:24.887 - [ERROR] Except stack:Traceback (most recent call last):
  File "D:\XX-Net\code\default\launcher\web_control.py", line 888, in req_debug_handler
    stack = sys._current_frames()[thread.ident]
KeyError: 6020

2023-10-04 20:23:24.891 - [WARNING] request /module/x_tunnel/control/debug no module in path
2023-10-04 20:23:24.894 - [WARNING] request /module/x_tunnel/control/status no module in path
2023-10-04 20:23:24.897 - [WARNING] request /module/x_tunnel/control/cloudflare_front/debug no module in path
2023-10-04 20:23:24.900 - [WARNING] request /module/x_tunnel/control/tls_relay_front/debug no module in path
2023-10-04 20:23:24.903 - [WARNING] request /module/x_tunnel/control/seley_front/debug no module in path
2023-10-04 20:23:26.946 - [WARNING] request /module/x_tunnel/control/cloudflare_front/log no module in path
2023-10-04 20:23:26.947 - [ERROR] fetch info http://localhost:8085/module/x_tunnel/control/cloudflare_front/log?cmd=get_new&last_no=1 fail:JSONDecodeError('Expecting value: line 1 column 1 (char 0)')
2023-10-04 20:23:26.991 - [ERROR] Except stack:Traceback (most recent call last):
  File "D:\XX-Net\code\default\launcher\web_control.py", line 924, in req_log_files
    dat = json.loads(res.text)
  File "D:\XX-Net\python3\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "D:\XX-Net\python3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\XX-Net\python3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

2023-10-04 20:23:29.026 - [WARNING] request /module/x_tunnel/control/tls_relay_front/log no module in path
2023-10-04 20:23:29.027 - [ERROR] fetch info http://localhost:8085/module/x_tunnel/control/tls_relay_front/log?cmd=get_new&last_no=1 fail:JSONDecodeError('Expecting value: line 1 column 1 (char 0)')
2023-10-04 20:23:29.028 - [ERROR] Except stack:Traceback (most recent call last):
  File "D:\XX-Net\code\default\launcher\web_control.py", line 924, in req_log_files
    dat = json.loads(res.text)
  File "D:\XX-Net\python3\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "D:\XX-Net\python3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\XX-Net\python3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

2023-10-04 20:23:31.052 - [WARNING] request /module/x_tunnel/control/seley_front/log no module in path
2023-10-04 20:23:31.053 - [ERROR] fetch info http://localhost:8085/module/x_tunnel/control/seley_front/log?cmd=get_new&last_no=1 fail:JSONDecodeError('Expecting value: line 1 column 1 (char 0)')
2023-10-04 20:23:31.053 - [ERROR] Except stack:Traceback (most recent call last):
  File "D:\XX-Net\code\default\launcher\web_control.py", line 924, in req_log_files
    dat = json.loads(res.text)
  File "D:\XX-Net\python3\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "D:\XX-Net\python3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\XX-Net\python3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

2023-10-04 20:23:33.126 - [WARNING] request /module/x_tunnel/control/log no module in path
2023-10-04 20:23:33.127 - [ERROR] fetch info http://localhost:8085/module/x_tunnel/control/log?cmd=get_new&last_no=1 fail:JSONDecodeError('Expecting value: line 1 column 1 (char 0)')
2023-10-04 20:23:33.128 - [ERROR] Except stack:Traceback (most recent call last):
  File "D:\XX-Net\code\default\launcher\web_control.py", line 924, in req_log_files
    dat = json.loads(res.text)
  File "D:\XX-Net\python3\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "D:\XX-Net\python3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\XX-Net\python3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

2023-10-04 20:23:35.182 - [WARNING] request /module/smart_router/control/log no module in path
2023-10-04 20:23:35.183 - [ERROR] fetch info http://localhost:8085/module/smart_router/control/log?cmd=get_new&last_no=1 fail:JSONDecodeError('Expecting value: line 1 column 1 (char 0)')
2023-10-04 20:23:35.184 - [ERROR] Except stack:Traceback (most recent call last):
  File "D:\XX-Net\code\default\launcher\web_control.py", line 924, in req_log_files
    dat = json.loads(res.text)
  File "D:\XX-Net\python3\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "D:\XX-Net\python3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\XX-Net\python3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

2023-10-04 20:23:35.966 - [DEBUG] launcher web_control 127.0.0.1:2530 GET /config?cmd=get_version 
2023-10-04 20:23:35.968 - [DEBUG] launcher web_control 127.0.0.1:2532 GET /config?cmd=get_config 
2023-10-04 20:23:36.041 - [DEBUG] launcher web_control 127.0.0.1:2530 GET /config?cmd=get_config 
2023-10-04 20:23:36.043 - [DEBUG] launcher web_control 127.0.0.1:2532 GET /update?cmd=get_progress 
2023-10-04 20:23:37.218 - [DEBUG] launcher web_control 127.0.0.1:2715 GET /log?cmd=get_new&last_no=1 
2023-10-04 20:23:37.936 - [DEBUG] launcher web_control 127.0.0.1:2528 GET /config?cmd=get_version 
2023-10-04 20:23:37.937 - [DEBUG] launcher web_control 127.0.0.1:2521 GET /config?cmd=get_config 
2023-10-04 20:23:38.020 - [DEBUG] launcher web_control 127.0.0.1:2531 GET /config?cmd=get_config 
2023-10-04 20:23:38.030 - [DEBUG] launcher web_control 127.0.0.1:2693 GET /update?cmd=get_progress 
2023-10-04 20:23:40.031 - [DEBUG] launcher web_control 127.0.0.1:2693 GET /config?cmd=get_version 
2023-10-04 20:23:40.035 - [DEBUG] launcher web_control 127.0.0.1:2530 GET /config?cmd=get_config 
2023-10-04 20:23:40.114 - [DEBUG] launcher web_control 127.0.0.1:2528 GET /update?cmd=get_progress 
2023-10-04 20:23:45.235 - [DEBUG] launcher web_control 127.0.0.1:2530 GET /config?cmd=get_version 
2023-10-04 20:23:45.275 - [DEBUG] launcher web_control 127.0.0.1:2521 GET /config?cmd=get_version 
2023-10-04 20:23:45.275 - [DEBUG] launcher web_control 127.0.0.1:2530 GET /config?cmd=get_config 
2023-10-04 20:23:45.332 - [DEBUG] launcher web_control 127.0.0.1:2521 GET /update?cmd=get_progress 
2023-10-04 20:23:46.436 - [DEBUG] launcher web_control 127.0.0.1:2521 GET /log_files 
2023-10-04 20:23:48.484 - [DEBUG] launcher web_control 127.0.0.1:2788 GET /debug 
2023-10-04 20:23:48.561 - [WARNING] request /module/x_tunnel/control/debug no module in path
2023-10-04 20:23:48.564 - [WARNING] request /module/x_tunnel/control/status no module in path
2023-10-04 20:23:48.566 - [WARNING] request /module/x_tunnel/control/cloudflare_front/debug no module in path
2023-10-04 20:23:48.569 - [WARNING] request /module/x_tunnel/control/tls_relay_front/debug no module in path
2023-10-04 20:23:48.572 - [WARNING] request /module/x_tunnel/control/seley_front/debug no module in path
2023-10-04 20:23:50.622 - [WARNING] request /module/x_tunnel/control/cloudflare_front/log no module in path
2023-10-04 20:23:50.623 - [ERROR] fetch info http://localhost:8085/module/x_tunnel/control/cloudflare_front/log?cmd=get_new&last_no=1 fail:JSONDecodeError('Expecting value: line 1 column 1 (char 0)')
2023-10-04 20:23:50.625 - [ERROR] Except stack:Traceback (most recent call last):
  File "D:\XX-Net\code\default\launcher\web_control.py", line 924, in req_log_files
    dat = json.loads(res.text)
  File "D:\XX-Net\python3\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "D:\XX-Net\python3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\XX-Net\python3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

2023-10-04 20:23:52.649 - [WARNING] request /module/x_tunnel/control/tls_relay_front/log no module in path
2023-10-04 20:23:52.650 - [ERROR] fetch info http://localhost:8085/module/x_tunnel/control/tls_relay_front/log?cmd=get_new&last_no=1 fail:JSONDecodeError('Expecting value: line 1 column 1 (char 0)')
2023-10-04 20:23:52.651 - [ERROR] Except stack:Traceback (most recent call last):
  File "D:\XX-Net\code\default\launcher\web_control.py", line 924, in req_log_files
    dat = json.loads(res.text)
  File "D:\XX-Net\python3\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "D:\XX-Net\python3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\XX-Net\python3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

2023-10-04 20:23:54.717 - [WARNING] request /module/x_tunnel/control/seley_front/log no module in path
2023-10-04 20:23:54.718 - [ERROR] fetch info http://localhost:8085/module/x_tunnel/control/seley_front/log?cmd=get_new&last_no=1 fail:JSONDecodeError('Expecting value: line 1 column 1 (char 0)')
2023-10-04 20:23:54.719 - [ERROR] Except stack:Traceback (most recent call last):
  File "D:\XX-Net\code\default\launcher\web_control.py", line 924, in req_log_files
    dat = json.loads(res.text)
  File "D:\XX-Net\python3\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "D:\XX-Net\python3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\XX-Net\python3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by starsforever** [comment]
哪位能帮忙分析一下啊

**Comment by xxnet** [comment]
日志里有抛出异常，但是不影响使用的，下个版本修复这个日志错误。
你关注一下GAE日志。

**Comment by starsforever** [comment]
使用就提示 ：连接尚未建立 ipv6 fail



***@***.***
 
发件人： Michael.X
发送时间： 2023-10-10 11:11
收件人： XX-net/XX-Net
抄送： starsforever; Author
主题： Re: [XX-net/XX-Net] 开启ipv6时，提示：进程：GAEProxy无响应，可能已退出 (Issue #13978)
日志里有抛出异常，但是不影响使用的，下个版本修复这个日志错误。
你关注一下GAE日志。
