### ISSUE TITLE
Mac 上无法运行，需要安装哪些特定的软件？

### ISSUE THREAD

**Issue by shenhf** [XX-net/XX-Net#1402]
$ ./start.sh
Traceback (most recent call last):
  File "launcher/start.py", line 54, in <module>
    import web_control
  File "/Users/shenhf/XX-Net-2.6.2/launcher/web_control.py", line 13, in <module>
    import SocketServer, socket, ssl
  File "/usr/local/Cellar/python/2.7.7_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 60, in <module>
    import _ssl             # if we can't import it, let the error propagate
ImportError: dlopen(/usr/local/Cellar/python/2.7.7_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_ssl.so, 2): Symbol not found: _SSLv2_method
  Referenced from: /usr/local/Cellar/python/2.7.7_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_ssl.so
  Expected in: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
 in /usr/local/Cellar/python/2.7.7_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_ssl.so

$ openssl version
OpenSSL 1.0.1j 15 Oct 2014

**Comment by xxnet** [comment]
Mac什么版本？

日志报ssl库加载失败，还不是openssl

怀疑python 太老了，能否升级一下？

2015-11-18 8:38 GMT+08:00 Shenhf <notifications@github.com>:

**Comment by shenhf** [comment]
brew upgrade 升级了 python，可以运行了，谢谢！
