### ISSUE TITLE
GAE的“IP 段列表”里面要怎么写IPv6地址？

### ISSUE THREAD

**Issue by cym104** [XX-net/XX-Net#14086]
只要写了IPv6地址，日志里面就会报这样的错误：

2024-12-15 13:03:03.982 - [ERROR] load ip range:2001:4860::/32 fail:ValueError("invalid literal for int() with base 10: ''")

2024-12-15 13:03:03.983 - [ERROR] Except stack:Traceback (most recent call last): File "C:\Program Files (x86)\XX-Net\code\5.10.7\lib\noarch\front_base\ip_source.py", line 82, in load_ip_range nbegin = utils.ip_string_to_num(begin) File "C:\Program Files (x86)\XX-Net\code\5.10.7\lib\noarch\utils.py", line 211, in ip_string_to_num return reduce(lambda a, b: a << 8 | b, list(map(int, s.split(".")))) ValueError: invalid literal for int() with base 10: ''

2024-12-15 13:03:03.983 - [ERROR] load ip range:2404:6800::/32 fail:ValueError("invalid literal for int() with base 10: ''")

2024-12-15 13:03:03.984 - [ERROR] Except stack:Traceback (most recent call last): File "C:\Program Files (x86)\XX-Net\code\5.10.7\lib\noarch\front_base\ip_source.py", line 82, in load_ip_range nbegin = utils.ip_string_to_num(begin) File "C:\Program Files (x86)\XX-Net\code\5.10.7\lib\noarch\utils.py", line 211, in ip_string_to_num return reduce(lambda a, b: a << 8 | b, list(map(int, s.split(".")))) ValueError: invalid literal for int() with base 10: ''

2024-12-15 13:03:03.984 - [ERROR] load ip range:2404:f340::/32 fail:ValueError("invalid literal for int() with base 10: ''")

2024-12-15 13:03:03.984 - [ERROR] Except stack:Traceback (most recent call last): File "C:\Program Files (x86)\XX-Net\code\5.10.7\lib\noarch\front_base\ip_source.py", line 82, in load_ip_range nbegin = utils.ip_string_to_num(begin) File "C:\Program Files (x86)\XX-Net\code\5.10.7\lib\noarch\utils.py", line 211, in ip_string_to_num return reduce(lambda a, b: a << 8 | b, list(map(int, s.split(".")))) ValueError: invalid literal for int() with base 10: ''

**Comment by cym104** [comment]
有什么办法吗？
