### ISSUE TITLE
选择ipv6后，百度同步盘的上传下载时好时坏

### ISSUE THREAD

**Issue by HopingTang** [XX-net/XX-Net#1441]
-----------问题描述：
RT。
部分日志信息：
Nov 22 18:50:59 - [INFO] GAE 4840|2607:f8b0:400a:804::100b|4528 t:878 s:2 hs:468 200 http://pan.baidu.com/res/static/thirdparty/connect.jpg?t=1448189458
Nov 22 18:50:59 - [ERROR] gae_handler except:error(10054, '') http://nj.poms.baidupcs.com/file/0673d70d163e027b99de394451b17b59?bkt=p3-14000673d70d163e027b99de394451b17b5915fd39cc00000e61b12c&fid=4249141943-250528-316189177199430&time=1448189154&sign=FDTAXGERLBH-DCb740ccc5511e5e8fedcff06b081203-pu%2FNraanOtRPn77mtOzPRrTqqms%3D&to=nb&fm=MH,Nan,B,U,ny&sta_dx=230&sta_cs=0&sta_ft=zip&sta_ct=7&fm2=MH,Nanjing,B,U,ny&newver=1&newfm=1&secfm=1&flow_ver=3&pkey=14000673d70d163e027b99de394451b17b5915fd39cc00000e61b12c&sl=69337166&expires=8h&rt=pr&r=546528304&mlogid=748146336&vuk=4249141943&vbdid=-&fin=2008-10-30%20-%20Anna%20S%20-%20Thai%20Grass%20%28x57%29.zip&bflag=i,G,FG&slt=pm&uta=3&rtype=1&iv=0&isw=0&dp-logid=7555801531148981297&dp-callid=0.1
Nov 22 18:50:59 - [ERROR] Except stack:Traceback (most recent call last): File "C:\Users\Tang\Downloads\XX-Net-2.6.2\gae_proxy\local\gae_handler.py", line 380, in handler wfile.write("HTTP/1.1 %d undefined\r\n" % (response.status, response.reason)) File "C:\Users\Tang\Downloads\XX-Net-2.6.2\python27\1.0\lib\socket.py", line 324, in write self.flush() File "C:\Users\Tang\Downloads\XX-Net-2.6.2\python27\1.0\lib\socket.py", line 303, in flush self._sock.sendall(view[write_offset:write_offset+buffer_size]) File "C:\Users\Tang\Downloads\XX-Net-2.6.2\python27\1.0\lib\socket.py", line 224, in meth return getattr(self._sock,name)(*args) error: [Errno 10054]
Nov 22 18:50:59 - [WARNING] socket error:error(10054, '')
Nov 22 18:51:01 - [DEBUG] ssl_pool.get:2607:f8b0:400a:804::100b handshake:468
Nov 22 18:51:01 - [DEBUG] ssl_pool.get:2607:f8b0:400a:804::100b handshake:472
Nov 22 18:51:02 - [INFO] GAE 4876|2607:f8b0:400a:804::100b|13208 t:730 s:657 hs:472 200 http://pan.baidu.com/api/filemetas?blocks=1&logid=JwAxADQANAA4ADEAOAA5ADQANgAxACwAMQAxADQALgAyADEAMgAuADEAMwAwAC4AMQA3ADcA%0ALAAzADkAMAAnAA%3D%3D&clienttype=3&devuid=BDIMXV2%2DO%5FA47581CF871D4263A9DF84CEDACBAE7D%2DC%5F0%2DD%5FWD%2DWCAYUAF22708%2DM%5F00FF309D4565%2DV%5F608A48C4&channel=00000000000000000000000000000000&version=3.9.6.1
Nov 22 18:52:01 - [WARNING] APPID error:502 url:http://allall02.baidupcs.com/file/763b5da1f7bde266d951c8716c436d1b?bkt=p3-1400763b5da1f7bde266d951c8716c436d1b0c92470b00000ce1bbb0&fid=4249141943-250528-807614868057991&time=1448188829&sign=FDTAXGERLBH-DCb740ccc5511e5e8fedcff06b081203-QLNgHYDAVVr7%2BkIY32sIGfwPAsU%3D&to=ib&fm=MH,Nan,B,U,ny&sta_dx=206&sta_cs=0&sta_ft=zip&sta_ct=7&fm2=MH,Nanjing,B,U,ny&newver=1&newfm=1&secfm=1&flow_ver=3&pkey=1400763b5da1f7bde266d951c8716c436d1b0c92470b00000ce1bbb0&sl=74448974&expires=8h&rt=pr&r=599707472&mlogid=1170045126&vuk=4249141943&vbdid=-&fin=2008-10-20%20-%20Anna%20S%20-%20Spanish%20Wall%20%28x80%29.zip&bflag=i,G,F,K,LL&slt=pm&uta=3&rtype=1&iv=0&isw=0&dp-logid=7555714220887476590&dp-callid=0.1

-----------诊断信息：
sys-platform: x86, Windows-8-6.2.9200
os-system: Windows
os-version: 6.2.9200
os-release: 8
os-detail: Version:10-0; Build:10240; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36
xxnet-version: 2.6.2
python-version: 2.7.9

ipv6-status: 1
gws-ip-num: 49,36
connected-link: 5,1
ip-connect-interval: 10
scan-ip-thread-num: 0
ip-handshake-10: 459
block-stat: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by HopingTang** [comment]
可不可以帮忙看看是什么问题？如果要debug的话应该怎么做呀~

**Comment by simonasd** [comment]
@HopingTang 百度的海外线路本来就很糟糕，要说起来，不好用也是正常的。
