### ISSUE TITLE
pyOpenSSL库更新

### ISSUE THREAD

**Issue by Cat7373** [XX-net/XX-Net#1443]
新的库支持TLS1.2。
win7下运行、通过GAE访问Github、访问后台页面未发现异常。
稍后去win10做测试，Linux我可以用虚拟机跑个Ubuntu进行测试，但是其余平台无法进行测试。

https://github.com/Cat7373/XX-Net/tree/pyOpenSSL-Update

具体流程：
1. 从官方下载Python2.7.10。
2. 用pip下载pyOptnSSL，相关支持由pip全自动构建。
3. 用新的pyOptnSSL替换xx-net中的库。
4. 运行后看哪个地方抛异常，然后对有问题的库进行替换。

@xxnet 
https://github.com/XX-net/XX-Net/issues/154

**Comment by Cat7373** [comment]
win10下运行、通过GAE访问Github未发现异常。

**Comment by Cat7373** [comment]
瞅了瞅没有Ubuntu的虚拟机- -
只有个现成的CentOS- -
然后就遇到了这个问题 https://github.com/XX-net/XX-Net/issues/779
但是这个方式对CentOS无效- -

**Comment by Cat7373** [comment]
CentOS测试未发现异常，但是Ctrl+C无法正常关闭。

**Comment by bigwboy** [comment]
[root@cpdiaodu launcher]# python start.py 
Apr 07 20:29:05.077 - [INFO] start XX-Net get_version_fail
Apr 07 20:29:05.077 - [DEBUG] start confirm_xxnet_exit
Apr 07 20:29:05.079 - [DEBUG] good, xxnet:8087 cleared!
Apr 07 20:29:05.080 - [DEBUG] good, xxnet:8085 clear!
Apr 07 20:29:05.080 - [DEBUG] finished confirm_xxnet_exit
Apr 07 20:29:05.088 - [ERROR] start module gae_proxy fail:libssl.so.1.0.0: cannot open shared object file: No such file or directory
Apr 07 20:29:05.088 - [ERROR] Except stack:Traceback (most recent call last):
  File "/home/guangguang/XX-Net-2.9.6/launcher/module_init.py", line 37, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "/home/guangguang/XX-Net-2.9.6/gae_proxy/start.py", line 14, in <module>
    import local.proxy as client
  File "/home/guangguang/XX-Net-2.9.6/gae_proxy/local/proxy.py", line 95, in <module>
    from cert_util import CertUtil
  File "/home/guangguang/XX-Net-2.9.6/gae_proxy/local/cert_util.py", line 38, in <module>
    import OpenSSL
  File "/home/guangguang/XX-Net-2.9.6/python27/1.0/lib/linux/OpenSSL/__init__.py", line 36, in <module>
    from OpenSSL import crypto
ImportError: libssl.so.1.0.0: cannot open shared object file: No such file or directory

Traceback (most recent call last):
  File "start.py", line 135, in <module>
    main()
  File "start.py", line 110, in main
    module_init.start_all_auto()
  File "/home/guangguang/XX-Net-2.9.6/launcher/module_init.py", line 98, in start_all_auto
    start(module)
  File "/home/guangguang/XX-Net-2.9.6/launcher/module_init.py", line 37, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "/home/guangguang/XX-Net-2.9.6/gae_proxy/start.py", line 14, in <module>
    import local.proxy as client
  File "/home/guangguang/XX-Net-2.9.6/gae_proxy/local/proxy.py", line 95, in <module>
    from cert_util import CertUtil
  File "/home/guangguang/XX-Net-2.9.6/gae_proxy/local/cert_util.py", line 38, in <module>
    import OpenSSL
  File "/home/guangguang/XX-Net-2.9.6/python27/1.0/lib/linux/OpenSSL/__init__.py", line 36, in <module>
    from OpenSSL import crypto
ImportError: libssl.so.1.0.0: cannot open shared object file: No such file or directory
Stopping all modules before exit!
Apr 07 20:29:05.089 - [ERROR] stop module gae_proxy fail:'imp'
Apr 07 20:29:05.089 - [ERROR] Except stack:Traceback (most recent call last):
  File "/home/guangguang/XX-Net-2.9.6/launcher/module_init.py", line 71, in stop
    _start = proc_handler[module]["imp"].start
KeyError: 'imp'

**Comment by bigwboy** [comment]
我也是这个错误，不过 我[root@cpdiaodu launcher]# yum install pyOpenSSL
Loaded plugins: fastestmirror
Setting up Install Process
Loading mirror speeds from cached hostfile
 * base: mirrors.skyshe.cn
 * extras: mirrors.skyshe.cn
 * updates: mirrors.skyshe.cn
Package pyOpenSSL-0.13.1-2.el6.x86_64 already installed and latest version
Nothing to do

**Comment by bigwboy** [comment]
安装 openssl也无效

**Comment by xxnet** [comment]
​试试删除 python27/1.0/lib/linux/OpenSSL 目录
