### ISSUE TITLE
看个 youdube  360P 也就 70KB 太卡了你们那

### ISSUE THREAD

**Issue by lianbookca** [XX-net/XX-Net#1450]
看个 youdube  360P 也就 30KB 太卡了你们那
还有扫描 是打开就自动扫描 吗 ？ 
Property 	Value
IP num/good 	1500,1403
10th IP handshake(ms) 	390
connected link(帮助) 	2,9
scaning ip thread num 	50
block stat(帮助) 	OK
Appid
Property 	Value

working appids 	
Out of Quota appids 	
Not Exist appids 	
设置
Property 	Value
Proxy Listen 	127.0.0.1:8087
PAC URL 	http://127.0.0.1:8086/proxy.pac
IPv6 	0
ip-connect-interval 	20
ov 23 21:55:24 - [DEBUG] get ip:210.153.73.51 t:434

Nov 23 21:55:24 - [DEBUG] create ssl timeout fail.

Nov 23 21:55:24 - [DEBUG] create_ssl_connection fail

Nov 23 21:55:24 - [DEBUG] create ssl timeout fail.

Nov 23 21:55:24 - [DEBUG] create_ssl_connection fail

Nov 23 21:55:24 - [DEBUG] create ssl timeout fail.

Nov 23 21:55:24 - [DEBUG] create_ssl_connection fail

Nov 23 21:55:24 - [DEBUG] create ssl timeout fail.

Nov 23 21:55:24 - [DEBUG] create_ssl_connection fail

Nov 23 21:55:24 - [DEBUG] create ssl timeout fail.

Nov 23 21:55:24 - [DEBUG] create_ssl_connection fail

Nov 23 21:55:24 - [DEBUG] create_ssl update ip:213.158.11.196 time:423

Nov 23 21:55:25 - [ERROR] gae_handler except:error(10054, '') 
Nov 23 21:55:25 - [ERROR] Except stack:Traceback (most recent call last): File "C:\Users\Administrator\Desktop\XX-Net-2.5.3\gae_proxy\local\gae_handler.py", line 380, in handler wfile.write("HTTP/1.1 %d undefined\r\n" % (response.status, response.reason)) File "C:\Users\Administrator\Desktop\XX-Net-2.5.3\python27\1.0\lib\socket.py", line 324, in write self.flush() File "C:\Users\Administrator\Desktop\XX-Net-2.5.3\python27\1.0\lib\socket.py", line 303, in flush self._sock.sendall(view[write_offset:write_offset+buffer_size]) File "C:\Users\Administrator\Desktop\XX-Net-2.5.3\python27\1.0\lib\ssl.py", line 229, in sendall v = self.send(data[count:]) File "C:\Users\Administrator\Desktop\XX-Net-2.5.3\python27\1.0\lib\ssl.py", line 198, in send v = self._sslobj.write(data) error: [Errno 10054]

Nov 23 21:55:25 - [WARNING] socket error:error(10054, '')

Nov 23 21:55:25 - [DEBUG] get ip:203.113.160.71 t:434

Nov 23 21:55:28 - [DEBUG] 27.121.51.76 fail

Nov 23 21:55:28 - [DEBUG] 210.153.73.122 fail

Nov 23 21:55:28 - [DEBUG] 1.255.33.213 fail

Nov 23 21:55:28 - [DEBUG] 210.153.73.51 fail

Nov 23 21:55:29 - [DEBUG] get ip:203.113.160.101 t:434

Nov 23 21:55:29 - [DEBUG] get ip:106.162.199.111 t:434

Nov 23 21:55:29 - [DEBUG] get ip:1.255.22.207 t:435

Nov 23 21:55:29 - [DEBUG]LOG_EXCEPT: get ip:49.98.35.114 t:435, Except:[Errno 9] Bad file descriptor

Nov 23 21:55:29 - [DEBUG] 203.113.160.71 fail

Nov 23 21:55:30 - [DEBUG] get ip:106.162.192.185 t:435

**Comment by xyuanmu** [comment]
楼主用的什么版本？
试试在 xx-net/data/gae_proxy 里新建一个 manual.ini，输入下面的内容保存。关闭xx-net再运行。
当然也有可能是晚上拥堵。

[autorange]
threads = 8
maxsize = 524288
waitsize = 1048576
bufsize = 65536

**Comment by lianbookca** [comment]
@xyuanmu  2.6.2 的

**Comment by xyuanmu** [comment]
你试试上面的参数，刚刚试了下1080还是没问题的，也可能是网络环境不同，咱广东电信。本想上图，不知为什么GitHub上传图片失败。

**Comment by lianbookca** [comment]
@xyuanmu  我是了 还是 看是360P  200KB  不过下的话 就能 500KB以上了  有事 700KB 都有那
你什么版本啊

**Comment by xyuanmu** [comment]
@lianbookca 2.6.1，这两天谷歌IP有恢复的趋势，autorange用的是上面的。

**这是我的状态**
IP num/good	998,404
10th IP handshake(ms)	213

**Comment by lianbookca** [comment]
扫描IP设置  吗看你这这项的图片呗 还有你的 版本是稳定版本还是  有测试版本 就自动升级 @xyuanmu

**Comment by xyuanmu** [comment]
扫描IP用的是这里的IP段：https://gist.github.com/xyuanmu/f169d1b9586b7b414265
一般没什么重大更新就没升级，现在还用着2.6.1

**Comment by lianbookca** [comment]
那最大扫描线程数 是几啊   自动调整扫描线程数  是ON 还是OFF ！@xyuanmu

**Comment by xyuanmu** [comment]
最大50，ON

**Comment by lianbookca** [comment]
扫描IP用的是这里的IP段：https://gist.github.com/xyuanmu/f169d1b9586b7b414265  
是放在那里的 @xyuanmu

**Comment by xyuanmu** [comment]
直接复制到 **[IP段列表(支持格式)](http://127.0.0.1:8085/?module=gae_proxy&menu=scan_ip)** 里提交就行了。

**Comment by lianbookca** [comment]
@xyuanmu  这些IP 升级 软件不自己 改  还要自己手动改啊

**Comment by lianbookca** [comment]
@xyuanmu   怎么调也是  这个速度啊

**Comment by lianbookca** [comment]
@xyuanmu 怎么调也是 这个速度啊  
![Uploading 捕获.JPG…]()

**Comment by ksmter** [comment]
我也是，在线看500KB/s是个不可逾越的坎，用youtube dlg下载就有2MB/s,改参数也没什么明显效果
