### ISSUE TITLE
在修改  Google IP使用频率限制  是出现未知错误。

### ISSUE THREAD

**Issue by Oliver001** [XX-net/XX-Net#1463]
-----------问题描述：
在修改  Google IP使用频率限制 后点击保存出现未知错误。
日志如下：
Nov 24 17:54:30 - [INFO] load google ip_list num:1804, gws num:1804
Nov 24 17:54:30 - [ERROR] req_config_handler except:can't start new thread
Nov 24 17:54:30 - [ERROR] Except stack:Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\software\XX-Net-master\gae_proxy\local\web_control.py", line 504, in req_config_handler
    google_ip.reset()
  File "C:\Users\Administrator\Desktop\software\XX-Net-master\gae_proxy\local\google_ip.py", line 81, in reset
    self.search_more_google_ip()
  File "C:\Users\Administrator\Desktop\software\XX-Net-master\gae_proxy\local\google_ip.py", line 645, in search_more_google_ip
    p.start()
  File "C:\Users\Administrator\Desktop\software\XX-Net-master\python27\1.0\lib\threading.py", line 745, in start
    _start_new_thread(self.__bootstrap, ())
error: can't start new thread

Nov 24 17:54:31 - [DEBUG] get ip:1.255.22.174 t:95
Exception in thread Thread-502:
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\software\XX-Net-master\python27\1.0\lib\threading.py", line 810, in __bootstrap_inner
    self.run()
  File "C:\Users\Administrator\Desktop\software\XX-Net-master\python27\1.0\lib\threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Users\Administrator\Desktop\software\XX-Net-master\gae_proxy\local\connect_manager.py", line 360, in create_connection_daemon
    p.start()
  File "C:\Users\Administrator\Desktop\software\XX-Net-master\python27\1.0\lib\threading.py", line 745, in start
    _start_new_thread(self.__bootstrap, ())
error: can't start new thread

Nov 24 17:54:32 - [DEBUG] create_ssl update ip:1.255.22.174 time:115
unicode err:TypeError('decoding Unicode is not supported',)
line can't decode:Nov 24 17:47:50 - [INFO] OS                 : Version:10-0; Build:10586; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0

Except stack:Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\software\XX-Net-master\gae_proxy\local\xlog.py", line 154, in get_new_lines
    jd[i] = unicode(line, errors='replace')
TypeError: decoding Unicode is not supported

Nov 24 17:55:27 - [DEBUG] GAEProxy web_control 127.0.0.1:17910 POST /config?cmd=get_config
Nov 24 17:55:29 - [DEBUG] GAEProxy Web_control 127.0.0.1:17919 GET /scan_ip?cmd=get_range
Nov 24 17:55:29 - [DEBUG] GAEProxy Web_control 127.0.0.1:17918 GET /scan_ip?cmd=get_scan_ip_log
Nov 24 17:55:29 - [INFO] load ip range file:C:\Users\Administrator\Desktop\software\XX-Net-master\data\gae_proxy\ip_range.txt
Nov 24 17:55:29 - [DEBUG] GAEProxy web_control 127.0.0.1:17920 POST /config?cmd=get_config
Nov 24 17:55:35 - [INFO] scan_ip add ip:208.117.228.165 time:450
Nov 24 17:55:36 - [DEBUG] GAEProxy web_control 127.0.0.1:17945 POST /config?cmd=get_config
Nov 24 17:55:38 - [DEBUG] launcher web_control 127.0.0.1:17949 GET /download?cmd=get_progress
Nov 24 17:55:42 - [DEBUG] GAEProxy web_control 127.0.0.1:17968 POST /config?cmd=get_config
Nov 24 17:55:45 - [DEBUG] GAEProxy web_control 127.0.0.1:17979 POST /config?cmd=get_config
Nov 24 17:55:56 - [DEBUG] GAEProxy web_control 127.0.0.1:18005 POST /config?cmd=get_config
Nov 24 17:56:48 - [DEBUG] GAEProxy web_control 127.0.0.1:18006 POST /config?cmd=set_config
Nov 24 17:56:48 - [INFO] load google ip_list num:1805, gws num:1805
Nov 24 17:56:48 - [ERROR] req_config_handler except:can't start new thread
Nov 24 17:56:48 - [ERROR] Except stack:Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\software\XX-Net-master\gae_proxy\local\web_control.py", line 504, in req_config_handler
    google_ip.reset()
  File "C:\Users\Administrator\Desktop\software\XX-Net-master\gae_proxy\local\google_ip.py", line 81, in reset
    self.search_more_google_ip()
  File "C:\Users\Administrator\Desktop\software\XX-Net-master\gae_proxy\local\google_ip.py", line 645, in search_more_google_ip
    p.start()
  File "C:\Users\Administrator\Desktop\software\XX-Net-master\python27\1.0\lib\threading.py", line 745, in start
    _start_new_thread(self.__bootstrap, ())
error: can't start new thread

----------------------------------------N
ov 24 17:56:51 - [DEBUG] GAEProxy web_control 127.0.0.1:18168 POST /config?cmd=get_config
Exception happened during processing of request from ('127.0.0.1', 18169)
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\software\XX-Net-master\python27\1.0\lib\SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "C:\Users\Administrator\Desktop\software\XX-Net-master\python27\1.0\lib\SocketServer.py", line 604, in process_request
    t.start()
  File "C:\Users\Administrator\Desktop\software\XX-Net-master\python27\1.0\lib\threading.py", line 745, in start
    _start_new_thread(self.__bootstrap, ())
error: can't start new thread
----------------------------------------
Nov 24 17:57:50 - [INFO] PAC from:127.0.0.1:18348 GET /proxy.pac
Nov 24 17:57:50 - [WARNING] socket error:error(10054, 'An existing connection was forcibly closed by the remote host')
N-ov 24 18:00:21 - [DEBUG] launcher web_control 127.0.0.1:18782 GET /config?cmd=get_config
---------------------------------------N
ov 24 18:01:01 - [DEBUG] launcher web_control 127.0.0.1:18928 GET /config?cmd=get_config
Exception happened during processing of request from ('127.0.0.1', 18929)
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\software\XX-Net-master\python27\1.0\lib\SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "C:\Users\Administrator\Desktop\software\XX-Net-master\python27\1.0\lib\SocketServer.py", line 604, in process_request
    t.start()
  File "C:\Users\Administrator\Desktop\software\XX-Net-master\python27\1.0\lib\threading.py", line 745, in start
    _start_new_thread(self.__bootstrap, ())
error: can't start new thread
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 18935)
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\software\XX-Net-master\python27\1.0\lib\SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "C:\Users\Administrator\Desktop\software\XX-Net-master\python27\1.0\lib\SocketServer.py", line 604, in process_request
    t.start()
  File "C:\Users\Administrator\Desktop\software\XX-Net-master\python27\1.0\lib\threading.py", line 745, in start
    _start_new_thread(self.__bootstrap, ())
error: can't start new thread
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 18986)
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\software\XX-Net-master\python27\1.0\lib\SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "C:\Users\Administrator\Desktop\software\XX-Net-master\python27\1.0\lib\SocketServer.py", line 604, in process_request
    t.start()
  File "C:\Users\Administrator\Desktop\software\XX-Net-master\python27\1.0\lib\threading.py", line 745, in start
    _start_new_thread(self.__bootstrap, ())
error: can't start new thread
----------------------------------------
Nov 24 18:01:44 - [DEBUG] launcher web_control 127.0.0.1:19041 GET /config?cmd=get_config
N-ov 24 18:01:55 - [DEBUG] GAEProxy web_control 127.0.0.1:19083 POST /config?cmd=get_config
---------------------------------------
Exception happened during processing of request from ('127.0.0.1', 19085)
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\software\XX-Net-master\python27\1.0\lib\SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "C:\Users\Administrator\Desktop\software\XX-Net-master\python27\1.0\lib\SocketServer.py", line 604, in process_request
    t.start()
  File "C:\Users\Administrator\Desktop\software\XX-Net-master\python27\1.0\lib\threading.py", line 745, in start
    _start_new_thread(self.__bootstrap, ())
error: can't start new thread
----------------------------------------
Nov 24 18:02:07 - [DEBUG] GAEProxy web_control 127.0.0.1:19092 POST /config?cmd=get_config
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 19096)
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\software\XX-Net-master\python27\1.0\lib\SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "C:\Users\Administrator\Desktop\software\XX-Net-master\python27\1.0\lib\SocketServer.py", line 604, in process_request
    t.start()
  File "C:\Users\Administrator\Desktop\software\XX-Net-master\python27\1.0\lib\threading.py", line 745, in start
    _start_new_thread(self.__bootstrap, ())
error: can't start new thread
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 19120)
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\software\XX-Net-master\python27\1.0\lib\SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "C:\Users\Administrator\Desktop\software\XX-Net-master\python27\1.0\lib\SocketServer.py", line 604, in process_request
    t.start()
  File "C:\Users\Administrator\Desktop\software\XX-Net-master\python27\1.0\lib\threading.py", line 745, in start
    _start_new_thread(self.__bootstrap, ())
error: can't start new thread
----------------------------------------
Nov 24 18:02:20 - [DEBUG] GAEProxy web_control 127.0.0.1:19182 POST /config?cmd=get_config
Nov 24 18:02:25 - [DEBUG] GAEProxy web_control 127.0.0.1:19200 POST /config?cmd=get_config

-----------诊断信息：
sys-platform: AMD64, Windows-8-6.2.9200
os-system: Windows
os-version: 6.2.9200
os-release: 8
os-detail: Version:10-0; Build:10586; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36
xxnet-version: 2.6.2
python-version: 2.7.9

ipv6-status: 0
gws-ip-num: 1805,337
connected-link: 0,0
ip-connect-interval: 10
scan-ip-thread-num: 3
ip-handshake-10: 144
block-stat: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by Oliver001** [comment]
Nov 24 18:02:07 - [DEBUG] GAEProxy web_control 127.0.0.1:19092 POST /config?cmd=get_config
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 19096)
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\software\XX-Net-master\python27\1.0\lib\SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "C:\Users\Administrator\Desktop\software\XX-Net-master\python27\1.0\lib\SocketServer.py", line 604, in process_request
    t.start()
  File "C:\Users\Administrator\Desktop\software\XX-Net-master\python27\1.0\lib\threading.py", line 745, in start
    _start_new_thread(self.__bootstrap, ())
error: can't start new thread
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 19120)
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\software\XX-Net-master\python27\1.0\lib\SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "C:\Users\Administrator\Desktop\software\XX-Net-master\python27\1.0\lib\SocketServer.py", line 604, in process_request
    t.start()
  File "C:\Users\Administrator\Desktop\software\XX-Net-master\python27\1.0\lib\threading.py", line 745, in start
    _start_new_thread(self.__bootstrap, ())
error: can't start new thread
----------------------------------------
Nov 24 18:02:20 - [DEBUG] GAEProxy web_control 127.0.0.1:19182 POST /config?cmd=get_config
Nov 24 18:02:25 - [DEBUG] GAEProxy web_control 127.0.0.1:19200 POST /config?cmd=get_config
Nov 24 18:03:50 - [INFO] scan_ip add ip:222.165.163.92 time:680
N-ov 24 18:05:43 - [INFO] scan_ip add ip:203.176.178.26 time:309
---------------------------------------Nov 24 18:06:59 - [DEBUG] launcher web_control 127.0.0.1:20113 GET /css/bootstrap.css

NEov 24 18:06:59 - [DEBUG] launcher web_control 127.0.0.1:20114 GET /css/bootstrap-responsive.css
xception happened during processing of request fromN ov 24 18:10:08 - [INFO] scan_ip add ip:62.201.216.232 time:749
('127.0.0.1', 20115)
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\software\XX-Net-master\python27\1.0\lib\SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "C:\Users\Administrator\Desktop\software\XX-Net-master\python27\1.0\lib\SocketServer.py", line 604, in process_request
    t.start()
  File "C:\Users\Administrator\Desktop\software\XX-Net-master\python27\1.0\lib\threading.py", line 745, in start
    _start_new_thread(self.__bootstrap, ())
error: can't start new thread
----------------------------------------
Nov 24 18:10:35 - [DEBUG] launcher web_control 127.0.0.1:20116 GET /css/ladda-themeless.min.css
Nov 24 18:10:35 - [DEBUG] launcher web_control 127.0.0.1:20117 GET /css/style.css
N-ov 24 18:10:35 - [DEBUG] launcher web_control 127.0.0.1:20118 GET /js/jquery-1.11.2.min.js
---------------------------------------
Exception happened during processing of request from ('127.0.0.1', 20684)
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\software\XX-Net-master\python27\1.0\lib\SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "C:\Users\Administrator\Desktop\software\XX-Net-master\python27\1.0\lib\SocketServer.py", line 604, in process_request
    t.start()
  File "C:\Users\Administrator\Desktop\software\XX-Net-master\python27\1.0\lib\threading.py", line 745, in start
    _start_new_thread(self.__bootstrap, ())
error: can't start new thread
----------------------------------------
Nov 24 18:10:35 - [DEBUG] launcher web_control 127.0.0.1:20685 GET /js/flat-ui.min.js
Nov 24 18:10:35 - [DEBUG] launcher web_control 127.0.0.1:20686 GET /js/jquery.timer.js
----------------------------------------N
ov 24 18:10:35 - [DEBUG] launcher web_control 127.0.0.1:20687 GET /js/spin.min.js
Exception happened during processing of request from ('127.0.0.1', 20688)
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\software\XX-Net-master\python27\1.0\lib\SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "C:\Users\Administrator\Desktop\software\XX-Net-master\python27\1.0\lib\SocketServer.py", line 604, in process_request
    t.start()
  File "C:\Users\Administrator\Desktop\software\XX-Net-master\python27\1.0\lib\threading.py", line 745, in start
    _start_new_thread(self.__bootstrap, ())
error: can't start new thread
----------------------------------------
N-ov 24 18:10:35 - [DEBUG] launcher web_control 127.0.0.1:20689 GET /js/site.js?20150512
---------------------------------------
Exception happened during processing of request from ('127.0.0.1', 20690)
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\software\XX-Net-master\python27\1.0\lib\SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "C:\Users\Administrator\Desktop\software\XX-Net-master\python27\1.0\lib\SocketServer.py", line 604, in process_request
    t.start()
  File "C:\Users\Administrator\Desktop\software\XX-Net-master\python27\1.0\lib\threading.py", line 745, in start
    _start_new_thread(self.__bootstrap, ())
error: can't start new thread
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 20694)
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\software\XX-Net-master\python27\1.0\lib\SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "C:\Users\Administrator\Desktop\software\XX-Net-master\python27\1.0\lib\SocketServer.py", line 604, in process_request
    t.start()
  File "C:\Users\Administrator\Desktop\software\XX-Net-master\python27\1.0\lib\threading.py", line 745, in start
    _start_new_thread(self.__bootstrap, ())
error: can't start new thread
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 20698)
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\software\XX-Net-master\python27\1.0\lib\SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "C:\Users\Administrator\Desktop\software\XX-Net-master\python27\1.0\lib\SocketServer.py", line 604, in process_request
    t.start()
  File "C:\Users\Administrator\Desktop\software\XX-Net-master\python27\1.0\lib\threading.py", line 745, in start
    _start_new_thread(self.__bootstrap, ())
error: can't start new thread
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 20703)
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\software\XX-Net-master\python27\1.0\lib\SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "C:\Users\Administrator\Desktop\software\XX-Net-master\python27\1.0\lib\SocketServer.py", line 604, in process_request
    t.start()
  File "C:\Users\Administrator\Desktop\software\XX-Net-master\python27\1.0\lib\threading.py", line 745, in start
    _start_new_thread(self.__bootstrap, ())
error: can't start new thread
----------------------------------------
Nov 24 18:10:36 - [DEBUG] launcher web_control 127.0.0.1:20760 GET /config?cmd=get_config
unicode err:TypeError('decoding Unicode is not supported',)
line can't decode:Nov 24 17:47:50 - [INFO] OS                 : Version:10-0; Build:10586; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0

Except stack:Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\software\XX-Net-master\gae_proxy\local\xlog.py", line 154, in get_new_lines
    jd[i] = unicode(line, errors='replace')
TypeError: decoding Unicode is not supported

**Comment by xxnet** [comment]
你是什么版本？什么操作系统？

能否贴出状态页看看详细信息

2015-11-24 18:12 GMT+08:00 Oliver001 <notifications@github.com>:

**Comment by Oliver001** [comment]
os:win10 10586, 64bits
xxnet-version: 2.6.2
python-version: 2.7.9
-----------诊断信息：
sys-platform: AMD64, Windows-8-6.2.9200
os-system: Windows
os-version: 6.2.9200
os-release: 8
os-detail: Version:10-0; Build:10586; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36
xxnet-version: 2.6.2
python-version: 2.7.9

ipv6-status: 0
gws-ip-num: 1805,337
connected-link: 0,0
ip-connect-interval: 10
scan-ip-thread-num: 3
ip-handshake-10: 144
block-stat: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by xxnet** [comment]
你试试下载全新的版本是不是可以工作

2015-11-24 20:06 GMT+08:00 Oliver001 <notifications@github.com>:

**Comment by Oliver001** [comment]
@xxnet 我把最大扫描线程数设为500了，只要是修改了参数然后点击更新或保存(如修改最大扫描线程数、点击检测新版本等)都会存在无法访问127.0.0.1:8087，之后通过托盘图标右键菜单退出，再次启动依然不能使用，需要手动关闭残留的python.exe之后，再次打开才能正常使用。但当我把最大扫描线程数设为50之后，问题消失。
升级到2.7.0之后问题依旧。

**Comment by xxnet** [comment]
不建议把扫描线程开太高，有报告触发google 防攻击保护，要是差的路由器都会扛不住。

无法工作怀疑Win10 的线程数限制了

在 2015年11月24日 下午10:28，Oliver001 <notifications@github.com>写道：

**Comment by Oliver001** [comment]
出于扫描ip的原因，才开这么高的，之前的IP handshake(ms)一直好几百。用500线程扫描了一天就下降到200左右了。

对于这个问题是不是需要做异常处理，或者说至少也不应该不能用了吧，也不应该出现通过托盘图标右键菜单退出时还需要手动关闭残留的python.exe？

我看了下日志，报的错也就这两个。
python27\1.0\lib\threading.py", line 745, in start
_start_new_thread(self.__bootstrap, ())

XX-Net-master\gae_proxy\local\xlog.py", line 154, in get_new_lines
jd[i] = unicode(line, errors='replace')
TypeError: decoding Unicode is not supported

**Comment by xxnet** [comment]
在 2015年11月24日 下午11:12，Oliver001 <notifications@github.com>写道：

> 出于扫描ip的原因，才开这么高的，之前的IP handshake(ms)一直好几百。用500线程扫描了一天就下降到200左右了。
>
> 对于这个问题是不是需要做异常处理，或者说至少也不应该不能用了吧，也不应该出现通过托盘图标右键菜单退出时还需要手动关闭残留的python.exe？
>
这种情况出现的时候，即使捕捉到了，也难以处理，因为资源消耗光了。
除非针对扫描线程开太高的情况，做特定的调整：
  捕获到线程启动失败，就将扫描线程减半，然后重启整个进程。
  其他可以减少的线程还有分片下载线程


> 我看了下日志，报的错也就这两个。
> python27\1.0\lib\threading.py", line 745, in start
> _start_new_thread(self.__bootstrap, ())
>
这是启动线程失败，资源消耗完了，导致后面不再提供服务，因为每次新请求都需要再创建线程

> XX-Net-master\gae_proxy\local\xlog.py", line 154, in get_new_lines
> jd[i] = unicode(line, errors='replace')
> TypeError: decoding Unicode is not supported
>
这个不影响工作
