### ISSUE TITLE
start module gae_proxy fail

### ISSUE THREAD

**Issue by waitttttttttttttttttttttttting** [XX-net/XX-Net#1469]
E:\Tools\XX-Net\XX-Net-2.5.1>SET PYTHONPATH=

E:\Tools\XX-Net\XX-Net-2.5.1>"E:\Tools\XX-Net\XX-Net-2.5.1\python27/1.0/python.e
xe" "E:\Tools\XX-Net\XX-Net-2.5.1\launcher/start.py"
Nov 25 10:13:49 - [INFO] start XX-Net 2.6.2
Nov 25 10:13:49 - [DEBUG] start confirm_xxnet_exit
Nov 25 10:13:50 - [DEBUG] good, xxnet:8087 cleared!
Nov 25 10:13:51 - [DEBUG] good, xxnet:8085 clear!
Nov 25 10:13:51 - [DEBUG] finished confirm_xxnet_exit
Nov 25 10:13:51 - [ERROR] start module gae_proxy fail:No option 'max_links_per_i
p' in section: 'google_ip'
Traceback (most recent call last):
  File "E:\Tools\XX-Net\XX-Net-2.5.1\launcher\module_init.py", line 37, in start

    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['loca
l', 'start'], -1)
  File "E:\Tools\XX-Net\XX-Net-2.5.1\gae_proxy\start.py", line 14, in <module>
    import local.proxy as client
  File "E:\Tools\XX-Net\XX-Net-2.5.1\gae_proxy\local\proxy.py", line 74, in <mod
ule>
    from cert_util import CertUtil
  File "E:\Tools\XX-Net\XX-Net-2.5.1\gae_proxy\local\cert_util.py", line 44, in
<module>
    from config import config
  File "E:\Tools\XX-Net\XX-Net-2.5.1\gae_proxy\local\config.py", line 131, in <m
odule>
    config.load()
  File "E:\Tools\XX-Net\XX-Net-2.5.1\gae_proxy\local\config.py", line 118, in lo
ad
    self.max_links_per_ip = self.CONFIG.getint('google_ip', 'max_links_per_ip')
  File "E:\Tools\XX-Net\XX-Net-2.5.1\python27\1.0\lib\ConfigParser.py", line 359
, in getint
    return self._get(section, int, option)
  File "E:\Tools\XX-Net\XX-Net-2.5.1\python27\1.0\lib\ConfigParser.py", line 356
, in _get
    return conv(self.get(section, option))
  File "E:\Tools\XX-Net\XX-Net-2.5.1\python27\1.0\lib\ConfigParser.py", line 618
, in get
    raise NoOptionError(option, section)
NoOptionError: No option 'max_links_per_ip' in section: 'google_ip'

Nov 25 10:13:51 - [INFO] start gae_proxy time cost 62
Nov 25 10:13:51 - [INFO] begin to start web control
Nov 25 10:13:51 - [INFO] launcher web control started.
----------------------------------------
 Exception happened during processing of request from---------------------------
-------------
(Exception happened during processing of request from'127.0.0.1',  42248()'127.0
.0.1'
, T42251raceback (most recent call last):
)
 File "E:\Tools\XX-Net\XX-Net-2.5.1\python27\1.0\lib\SocketServer.py", line 593,
 in process_request_thread
Traceback (most recent call last):
  File "E:\Tools\XX-Net\XX-Net-2.5.1\python27\1.0\lib\SocketServer.py", line 593
, in process_request_thread
    self.finish_request(request, client_address)
    self.finish_request(request, client_address)
  File "E:\Tools\XX-Net\XX-Net-2.5.1\launcher\web_control.py", line 48, in finis
h_request
  File "E:\Tools\XX-Net\XX-Net-2.5.1\launcher\web_control.py", line 48, in finis
h_request
    self.RequestHandlerClass(request, client_address, self)
    self.RequestHandlerClass(request, client_address, self)
  File "E:\Tools\XX-Net\XX-Net-2.5.1\python27\1.0\lib\SocketServer.py", line 649
, in __init__
  File "E:\Tools\XX-Net\XX-Net-2.5.1\python27\1.0\lib\SocketServer.py", line 649
, in __init__
    self.handle()
  File "E:\Tools\XX-Net\XX-Net-2.5.1\python27\1.0\lib\BaseHTTPServer.py", line 3
40, in handle
    self.handle()
  File "E:\Tools\XX-Net\XX-Net-2.5.1\python27\1.0\lib\BaseHTTPServer.py", line 3
40, in handle
    self.handle_one_request()
  File "E:\Tools\XX-Net\XX-Net-2.5.1\python27\1.0\lib\BaseHTTPServer.py", line 3
28, in handle_one_request
    method()
  File "E:\Tools\XX-Net\XX-Net-2.5.1\launcher\web_control.py", line 143, in do_G
ET
    controler = module_init.proc_handler[module]["imp"].local.web_control.Contro
lHandler(self.client_address, self.headers, self.command, path, self.rfile, self
.wfile)
KeyError: 'imp'

**Comment by xxnet** [comment]
更新升级不完全导致的，你重新下载覆盖就好了

2015-11-25 10:16 GMT+08:00 waitttttttttttttttttttttttting <
notifications@github.com>:

**Comment by waitttttttttttttttttttttttting** [comment]
好的，谢谢，我这就去：）
