### ISSUE TITLE
GAEProxy状态信息显示空白

### ISSUE THREAD

**Issue by 1chenping** [XX-net/XX-Net#1508]
状态页显示空白, 很可能GAEProxy启动失败, 

控制台日志：
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 50657)
Traceback (most recent call last):
  File "F:\dev\soft\XX-Net-2.5.5\python27\1.0\lib\SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "F:\dev\soft\XX-Net-2.5.5\launcher\web_control.py", line 48, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "F:\dev\soft\XX-Net-2.5.5\python27\1.0\lib\SocketServer.py", line 649, in __init__
    self.handle()
  File "F:\dev\soft\XX-Net-2.5.5\python27\1.0\lib\BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "F:\dev\soft\XX-Net-2.5.5\python27\1.0\lib\BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "F:\dev\soft\XX-Net-2.5.5\launcher\web_control.py", line 143, in do_GET
    controler = module_init.proc_handler[module]["imp"].local.web_control.ControlHandler(self.client_address, self.heade
rs, self.command, path, self.rfile, self.wfile)
KeyError: 'imp'
----------------------------------------

**Comment by linhua55** [comment]
请重新下载，升级成稳定版！

2015-12-01 15:42 GMT+08:00 1chenping <notifications@github.com>:

**Comment by 1chenping** [comment]
升级到2.7.1了，已经ok 谢谢
