### ISSUE TITLE
不能正常启动 XX-Net 2.6.2 报错Errno 10013

### ISSUE THREAD

**Issue by lukeluan** [XX-net/XX-Net#1515]
报错信息如下，报error: [Errno 10013]，不解请帮忙看看

F:\XX-net\XX-Net-2.6.2>SET PYTHONPATH=

F:\XX-net\XX-Net-2.6.2>"F:\XX-net\XX-Net-2.6.2\python27/1.0/python.exe" "F:\XX-n
et\XX-Net-2.6.2\launcher/start.py"
Dec 02 20:37:42 - [INFO] start XX-Net 2.6.2
Dec 02 20:37:42 - [DEBUG] start confirm_xxnet_exit
Dec 02 20:37:42 - [DEBUG] <0>: try to terminate xxnet:8087
Dec 02 20:37:43 - [DEBUG] <1>: try to terminate xxnet:8087
Dec 02 20:37:44 - [DEBUG] <2>: try to terminate xxnet:8087
Dec 02 20:37:45 - [DEBUG] <3>: try to terminate xxnet:8087
Dec 02 20:37:46 - [DEBUG] <4>: try to terminate xxnet:8087
Dec 02 20:37:47 - [DEBUG] <5>: try to terminate xxnet:8087
Dec 02 20:37:48 - [DEBUG] <6>: try to terminate xxnet:8087
Dec 02 20:37:49 - [DEBUG] <7>: try to terminate xxnet:8087
Dec 02 20:37:50 - [DEBUG] <8>: try to terminate xxnet:8087
Dec 02 20:37:51 - [DEBUG] <9>: try to terminate xxnet:8087
Dec 02 20:37:52 - [DEBUG] <10>: try to terminate xxnet:8087
Dec 02 20:37:53 - [DEBUG] <11>: try to terminate xxnet:8087
Dec 02 20:37:54 - [DEBUG] <12>: try to terminate xxnet:8087
Dec 02 20:37:55 - [DEBUG] <13>: try to terminate xxnet:8087
Dec 02 20:37:56 - [DEBUG] <14>: try to terminate xxnet:8087
Dec 02 20:37:57 - [DEBUG] <15>: try to terminate xxnet:8087
Dec 02 20:37:58 - [DEBUG] <16>: try to terminate xxnet:8087
Dec 02 20:37:59 - [DEBUG] <17>: try to terminate xxnet:8087
Dec 02 20:38:00 - [DEBUG] <18>: try to terminate xxnet:8087
Dec 02 20:38:01 - [DEBUG] <19>: try to terminate xxnet:8087
Dec 02 20:38:02 - [DEBUG] <20>: try to terminate xxnet:8087
Dec 02 20:38:03 - [DEBUG] <21>: try to terminate xxnet:8087
Dec 02 20:38:04 - [DEBUG] <22>: try to terminate xxnet:8087
Dec 02 20:38:05 - [DEBUG] <23>: try to terminate xxnet:8087
Dec 02 20:38:06 - [DEBUG] <24>: try to terminate xxnet:8087
Dec 02 20:38:07 - [DEBUG] <25>: try to terminate xxnet:8087
Dec 02 20:38:08 - [DEBUG] <26>: try to terminate xxnet:8087
Dec 02 20:38:09 - [DEBUG] <27>: try to terminate xxnet:8087
Dec 02 20:38:10 - [DEBUG] <28>: try to terminate xxnet:8087
Dec 02 20:38:11 - [DEBUG] <29>: try to terminate xxnet:8087
Dec 02 20:38:13 - [DEBUG] good, xxnet:8085 clear!
Dec 02 20:38:13 - [DEBUG] finished confirm_xxnet_exit
Dec 02 20:38:13 - [INFO] load ip range file:F:\XX-net\XX-Net-2.6.2\gae_proxy\loc
al\ip_range.txt
Dec 02 20:38:13 - [INFO] load google ip_list num:6, gws num:6
Dec 02 20:38:13 - [INFO] SSL use version:TLSv1
Dec 02 20:38:14 - [DEBUG] ## GAEProxy set keep_running: True
Dec 02 20:38:14 - [INFO] ------------------------------------------------------
Dec 02 20:38:14 - [INFO] Python Version     : 2.7.9
Dec 02 20:38:14 - [INFO] OS                 : Version:6-1; Build:7601; Platform:
2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
Dec 02 20:38:14 - [INFO] Listen Address     : 127.0.0.1:8087
Dec 02 20:38:14 - [INFO] GAE APPID          : xxnet-1|xxnet-2|xxnet-3|xxnet-4|xx
net-5|xxnet-6|xxnet-7|xxnet-8|xxnet-9|xxnet-10|xxnet-11|xxnet-12|xxnet-13|xxnet-
14|xxnet-15|xxnet-16|xxnet-17|xxnet-18|xxnet-19|xxnet-20|xxnet-21|xxnet-22|xxnet
-23|xxnet-24|xxnet-25|xxnet-26|xxnet-27|xxnet-28|xxnet-29|xxnet-30|xxnet-31|xxne
t-32|xxnet-33|xxnet-34|xxnet-35|xxnet-36|xxnet-37|xxnet-38|xxnet-39|xxnet-40|xxn
et-41|xxnet-42|xxnet-43|xxnet-44|xxnet-45|xxnet-46|xxnet-47|xxnet-48|xxnet-49|xx
net-50|xxnet-51|xxnet-52|xxnet-53|xxnet-54|xxnet-55|xxnet-56|xxnet-57|xxnet-58|x
xnet-59|xxnet-60|xxnet-61|xxnet-62|xxnet-63|xxnet-64|xxnet-65|xxnet-66|xxnet-67|
xxnet-68|xxnet-69|xxnet-70|xxnet-71|xxnet-72|xxnet-72|xxnet-73|xxnet-74|xxnet-75
|xxnet-76|xxnet-77|xxnet-78|xxnet-79|xxnet-80|xxnet-81|xxnet-82|xxnet-83|xxnet-8
4|xxnet-85|xxnet-86|xxnet-87|xxnet-88|xxnet-89|xxnet-90|xxnet-91|xxnet-92|xxnet-
93|xxnet-94|xxnet-95|xxnet-96|xxnet-97|xxnet-98|xxnet-99|xxnet-100|xxnet-101|xxn
et-102|xxnet-103|xxnet-104|xxnet-105|xxnet-106|xxnet-107|xxnet-108|xxnet-109|xxn
et-110|xxnet-111|xxnet-112|xxnet-113|xxnet-114|xxnet-115|xxnet-116|xxnet-117|xxn
et-118|xxnet-119|xxnet-120|xxnet-121|xxnet-122|xxnet-123|xxnet-124|xxnet-125|xxn
et-126|xxnet-127|xxnet-128|xxnet-129|xxnet-130|xxnet-131|xxnet-132|xxnet-133|xxn
et-134|xxnet-135|xxnet-136|xxnet-137|xxnet-138|xxnet-139|xxnet-140|xxnet-141|xxn
et-142|xxnet-143|xxnet-144|xxnet-145|xxnet-146|xxnet-147|xxnet-148|xxnet-149|xxn
et-150|xxnet-151|xxnet-152|xxnet-153|xxnet-154|xxnet-155|xxnet-156|xxnet-157|xxn
et-158|xxnet-159
Dec 02 20:38:14 - [INFO] Pac Server         : http://127.0.0.1:8086/proxy.pac
Dec 02 20:38:14 - [INFO] ------------------------------------------------------
Dec 02 20:38:14 - [INFO] server 127.0.0.1:8087 started.
Exception in thread Thread-53:
Traceback (most recent call last):
  File "F:\XX-net\XX-Net-2.6.2\python27\1.0\lib\threading.py", line 810, in __bo
otstrap_inner
    self.run()
  File "F:\XX-net\XX-Net-2.6.2\python27\1.0\lib\threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "F:\XX-net\XX-Net-2.6.2\gae_proxy\start.py", line 19, in main
    client.main()
  File "F:\XX-net\XX-Net-2.6.2\gae_proxy\local\proxy.py", line 225, in main
    pac_daemon = simple_http_server.HTTPServer((config.PAC_IP, config.PAC_PORT),
 pac_server.PACServerHandler)
  File "F:\XX-net\XX-Net-2.6.2\gae_proxy\local\simple_http_server.py", line 191,
 in __init__
    self.socket.bind(self.server_address)
  File "F:\XX-net\XX-Net-2.6.2\python27\1.0\lib\socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 10013]

Dec 02 20:38:48 - [INFO] scan_ip add ip:203.176.178.42 time:349
Dec 02 20:39:50 - [INFO] scan_ip add ip:103.11.28.123 time:1092

**Comment by lukeluan** [comment]
好奇怪？已经能使用代理访问google了，但是双击start.vbs后桌面没产生快捷方式，以及任务栏上也没有XX-Net的运行状态图标。

**Comment by xxnet** [comment]
估计是原来没有退出，你打开任务管理器，停掉pythonw再重新启动

在 2015年12月2日 下午8:49，lukeluan <notifications@github.com>写道：
