### ISSUE TITLE
PHP代理无法正常使用

### ISSUE THREAD

**Issue by 872517414** [XX-net/XX-Net#1566]
PHP Server URL: http://csgocn.ml/xxnet/index.php 
PHP Password: csgocnml
浏览器访问跳转Google正常。

日志:
Dec 10 20:51:48 - [ERROR] create_http_request "POST csgocn.ml/xxnet/index.php?0.609540045853" failed:string index out of range
Dec 10 20:51:48 - [ERROR] Except stack:Traceback (most recent call last):
  File "M:\Program Files\XX-Net\php_proxy\local\proxylib.py", line 1781, in create_http_request
    sock = create_connection(host, port, timeout, validate=validate, cache_key=cache_key, headfirst=headfirst)
  File "M:\Program Files\XX-Net\php_proxy\local\proxylib.py", line 1471, in create_tcp_connection
    addresses = [(x, port) for x in self.gethostbyname2(hostname)]
  File "M:\Program Files\XX-Net\php_proxy\local\proxylib.py", line 1364, in gethostbyname2
    record = dnslib_resolve_over_udp(hostname, self.dns_servers, timeout=2, blacklist=self.dns_blacklist)
  File "M:\Program Files\XX-Net\php_proxy\local\proxylib.py", line 378, in dnslib_resolve_over_udp
    query = '.'.join(x[:-1] + x[-1].upper() for x in query.split('.')).title()
  File "M:\Program Files\XX-Net\php_proxy\local\proxylib.py", line 378, in <genexpr>
    query = '.'.join(x[:-1] + x[-1].upper() for x in query.split('.')).title()
IndexError: string index out of range

**Comment by jzp820927** [comment]
PHP 很早就没维护了，bug 可能较多，如果喜欢用 php 建议用 goproxy

**Comment by Jaggle** [comment]
@jzp820927 我会写php，难道维护php版的任务交给我了？

**Comment by Jaggle** [comment]
@jzp820927 顺便问一下，部署php服务端可以有办法让iphone使用吗？

**Comment by jzp820927** [comment]
最新版，也就是 3.2.6，PHP 模块都被移除了，你怎么维护？
