### ISSUE TITLE
更新后在cents 7上无法运行

### ISSUE THREAD

**Issue by broad3** [XX-net/XX-Net#1592]
12月 14 23:43:46.2 - [WARNING] import pynotify fail, please install python-notify if possiable.
12月 14 23:43:46.3 - [INFO] start XX-Net 2.7.3
12月 14 23:43:46.3 - [DEBUG] start confirm_xxnet_exit
12月 14 23:43:46.3 - [DEBUG] good, xxnet:8087 cleared!
12月 14 23:43:46.3 - [DEBUG] good, xxnet:8085 clear!
12月 14 23:43:46.3 - [DEBUG] finished confirm_xxnet_exit
12月 14 23:43:46.3 - [ERROR] start module gae_proxy fail:cannot import name Logger
12月 14 23:43:46.3 - [ERROR] Except stack:Traceback (most recent call last):
  File "~/XX-Net/launcher/module_init.py", line 37, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "~/XX-Net/gae_proxy/start.py", line 14, in <module>
    import local.proxy as client
  File "~/XX-Net/gae_proxy/local/proxy.py", line 86, in <module>
    from xlog import Logger
ImportError: cannot import name Logger

**Comment by xxnet** [comment]
你这是git更新吗？
   这个还没有发布测试版呢。

你检查有没有这个文件：
python27/1.0/lib/noarch/xlog.py

另外检查git status是否正常

2015-12-15 0:14 GMT+08:00 broad3 <notifications@github.com>:

**Comment by xxnet** [comment]
估计是 gae_proxy/local/xlog.py 没有删除，你检查下这个文件需要删除掉

2015-12-15 7:30 GMT+08:00 Net XX <xxnet.dev@gmail.com>:

**Comment by broad3** [comment]
我是通过git更新的，git status检查都是正常的。gae_proxy/local/xlog.py这个文件是有的，我再删除试一下

**Comment by broad3** [comment]
pull后已经好了

**Comment by xxnet** [comment]
ok

2015-12-15 10:28 GMT+08:00 broad3 <notifications@github.com>:
