### ISSUE TITLE
Win10 下不能启动，麻烦看看怎么回事？

### ISSUE THREAD

**Issue by KevinLeung007** [XX-net/XX-Net#1599]
运行 start.bat
显示如下：
Dec 15 16:46:42 - [INFO] start XX-Net 2.7.3
Dec 15 16:46:42 - [DEBUG] start confirm_xxnet_exit
Dec 15 16:46:43 - [DEBUG] good, xxnet:8087 cleared!
Dec 15 16:46:44 - [DEBUG] good, xxnet:8085 clear!
Dec 15 16:46:44 - [DEBUG] finished confirm_xxnet_exit
Dec 15 16:46:45 - [ERROR] start module gae_proxy fail:No option 'max_links_per_ip' in section: 'google_ip'
Traceback (most recent call last):
  File "C:\Users\kevin\Desktop\XX-Net\launcher\module_init.py", line 37, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "C:\Users\kevin\Desktop\XX-Net\gae_proxy\start.py", line 14, in <module>
    import local.proxy as client
  File "C:\Users\kevin\Desktop\XX-Net\gae_proxy\local\proxy.py", line 74, in <module>
    from cert_util import CertUtil
  File "C:\Users\kevin\Desktop\XX-Net\gae_proxy\local\cert_util.py", line 44, in <module>
    from config import config
  File "C:\Users\kevin\Desktop\XX-Net\gae_proxy\local\config.py", line 131, in <module>
    config.load()
  File "C:\Users\kevin\Desktop\XX-Net\gae_proxy\local\config.py", line 118, in load
    self.max_links_per_ip = self.CONFIG.getint('google_ip', 'max_links_per_ip')
  File "C:\Users\kevin\Desktop\XX-Net\python27\1.0\lib\ConfigParser.py", line 359, in getint
    return self._get(section, int, option)
  File "C:\Users\kevin\Desktop\XX-Net\python27\1.0\lib\ConfigParser.py", line 356, in _get
    return conv(self.get(section, option))
  File "C:\Users\kevin\Desktop\XX-Net\python27\1.0\lib\ConfigParser.py", line 618, in get
    raise NoOptionError(option, section)
NoOptionError: No option 'max_links_per_ip' in section: 'google_ip'

Dec 15 16:46:45 - [INFO] start gae_proxy time cost 31
Dec 15 16:46:45 - [INFO] begin to start web control
Dec 15 16:46:45 - [INFO] launcher web control started.
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 51208)
Traceback (most recent call last):
  File "C:\Users\kevin\Desktop\XX-Net\python27\1.0\lib\SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "C:\Users\kevin\Desktop\XX-Net\launcher\web_control.py", line 48, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Users\kevin\Desktop\XX-Net\python27\1.0\lib\SocketServer.py", line 649, in __init__
    self.handle()
  File "C:\Users\kevin\Desktop\XX-Net\python27\1.0\lib\BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "C:\Users\kevin\Desktop\XX-Net\python27\1.0\lib\BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "C:\Users\kevin\Desktop\XX-Net\launcher\web_control.py", line 143, in do_GET
    controler = module_init.proc_handler[module]["imp"].local.web_control.ControlHandler(self.client_address, self.headers, self.command, path, self.rfile, self.wfile)
K-eyError: 'imp'
-------------------------------------------------------------------------------

**Comment by xxnet** [comment]
估计是升级部分失败，老版本的问题，手动下载覆盖就好了

2015-12-15 16:49 GMT+08:00 KevinLeung007 <notifications@github.com>:
