### ISSUE TITLE
红字

### ISSUE THREAD

**Issue by ghosoft** [XX-net/XX-Net#161]
Apr 15 13:10:11 - [ERROR] _request:SysCallError(10054, 'Connection reset by peer')
Apr 15 13:10:11 - [ERROR] Except stack:Traceback (most recent call last):
File "C:\XXNET\XX-Net-1.8.7\goagent\3.1.48\local\gae_handler.py", line 120, in _request
response.begin()
File "C:\XXNET\XX-Net-1.8.7\python27\1.0\lib\httplib.py", line 409, in begin
version, status, reason = self._read_status()
File "C:\XXNET\XX-Net-1.8.7\python27\1.0\lib\httplib.py", line 365, in _read_status
line = self.fp.readline(_MAXLINE + 1)
File "C:\XXNET\XX-Net-1.8.7\python27\1.0\lib\socket.py", line 476, in readline
data = self._sock.recv(self._rbufsize)
File "C:\XXNET\XX-Net-1.8.7\goagent\3.1.48\local\openssl_wrap.py", line 84, in recv
return self.__iowait(self._connection.recv, bufsiz, flags)
File "C:\XXNET\XX-Net-1.8.7\goagent\3.1.48\local\openssl_wrap.py", line 34, in __iowait
return io_func(*args, **kwargs)
SysCallError: (10054, 'Connection reset by peer')

Apr 15 13:10:11 - [ERROR] gae_handler.handler TypeError('%d format: a number is required, not str',) http://www.st.com/st-web-ui/static/active/cn/fragment/website_building_block/site_media/icon/ico-20.gif , retry...
Apr 15 13:10:11 - [ERROR] Except stack:Traceback (most recent call last):
File "C:\XXNET\XX-Net-1.8.7\goagent\3.1.48\local\gae_handler.py", line 270, in handler
logging.debug("fetch gae status:%d url:%s", response.app_status, url)
File "C:\XXNET\XX-Net-1.8.7\goagent\3.1.48\local\logging.py", line 93, in debug
log('DEBUG', debug_color, '21610b', fmt, *args, **kwargs)
File "C:\XXNET\XX-Net-1.8.7\goagent\3.1.48\local\logging.py", line 65, in log
string = '%s - [%s] %s\n' % (time.ctime()[4:-5], level, fmt % args)
TypeError: %d format: a number is required, not str

**Comment by Cat7373** [comment]
看提示应该是连接被重置
应该是你连接的IP被封锁或者不稳定

**Comment by xxnet** [comment]
收到，日志等级太高了，我下个版本调低

在 2015年4月15日 上午8:10，Cat73 <notifications@github.com>写道：
