### ISSUE TITLE
KeyError: 'imp'

### ISSUE THREAD

**Issue by zjhzxhz** [XX-net/XX-Net#1610]
Error Log:

```
12月 16 14:55:01.0 - [INFO] remove_slowest_ip:103.11.28.237 handshake_time:653, fails:0
12月 16 14:55:01.3 - [ERROR] handler:KeyError('imp',)
12月 16 14:55:01.3 - [ERROR] Except stack:Traceback (most recent call last):
  File "/media/Data/Applications/GoAgent/XX-Net/python27/1.0/lib/noarch/simple_http_server.py", line 128, in handle_one_request
    self.do_POST()
  File "/media/Data/Applications/GoAgent/XX-Net/launcher/web_control.py", line 93, in do_POST
    controler = module_init.proc_handler[module]["imp"].local.web_control.ControlHandler(self.client_address, self.headers, self.command, path, self.rfile, self.wfile)
KeyError: 'imp'
```

**Comment by zjhzxhz** [comment]
The latest version (mater). 不是2.7.3.

**Comment by xxnet** [comment]
你访问了什么页面？
把启动最开始的贴出来看看

2015-12-16 14:58 GMT+08:00 Howard Shieh <notifications@github.com>:

**Comment by zjhzxhz** [comment]
Error Log:

```
xiehaozhe@XieHaozhe-PC:~/Public/XX-Net$ ./start.sh 
Gtk-Message: Failed to load module "canberra-gtk-module"
12月 16 16:05:11.6 - [INFO] start XX-Net 2.7.3
12月 16 16:05:11.6 - [DEBUG] start confirm_xxnet_exit
12月 16 16:05:11.6 - [DEBUG] good, xxnet:8087 cleared!
12月 16 16:05:11.6 - [DEBUG] good, xxnet:8085 clear!
12月 16 16:05:11.6 - [DEBUG] finished confirm_xxnet_exit
12月 16 16:05:11.6 - [INFO] module php_proxy started
12月 16 16:05:11.6 - [INFO] start php_proxy time cost 5
12月 16 16:05:11.8 - [INFO] SSL use version:TLSv1
12月 16 16:05:11.8 - [INFO] load ip range file:/media/Data/Applications/GoAgent/XX-Net/gae_proxy/local/ip_range.txt
/media/Data/Applications/GoAgent/XX-Net/php_proxy/local/proxy.py:91: UserWarning: libevent version mismatch: system version is '2.0.21-stable' but this gevent is compiled against '2.0.19-stable'
  __import__('gevent.monkey', fromlist=['.']).patch_all()
12月 16 16:05:11.9 - [INFO] load google ip_list num:3002, gws num:3000
12月 16 16:05:11.9 - [ERROR] start module gae_proxy fail:No module named _winreg
12月 16 16:05:12.0 - [ERROR] Except stack:Traceback (most recent call last):
  File "/media/Data/Applications/GoAgent/XX-Net/launcher/module_init.py", line 37, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "/media/Data/Applications/GoAgent/XX-Net/gae_proxy/start.py", line 14, in <module>
    import local.proxy as client
  File "/media/Data/Applications/GoAgent/XX-Net/gae_proxy/local/proxy.py", line 93, in <module>
    import proxy_handler
  File "/media/Data/Applications/GoAgent/XX-Net/gae_proxy/local/proxy_handler.py", line 22, in <module>
    import web_control
  File "/media/Data/Applications/GoAgent/XX-Net/gae_proxy/local/web_control.py", line 18, in <module>
    import _winreg as winreg
ImportError: No module named _winreg

12月 16 16:05:12.0 - [INFO] start gae_proxy time cost 367
12月 16 16:05:12.0 - [INFO] begin to start web control
12月 16 16:05:12.0 - [INFO] server 127.0.0.1:8085 started.
12月 16 16:05:12.0 - [INFO] launcher web control started.
Dec 16 16:05:12 - [WARNING] *NOTE*, please upgrade to gevent 1.1 as possible
Dec 16 16:05:12 - [INFO] ------------------------------------------------------
PHP Proxy Version    : 3.2.3 (python/2.7.9 gevent/0.13.6 pyopenssl/0.13)
PHP Listen         : 127.0.0.1:8088
PHP FetchServers   : ['http://zjhzxhz.com/goagent/index.php']
------------------------------------------------------

Dec 16 16:05:12 - [DEBUG] init_ca
^C12月 16 16:05:12.5 - [INFO] module php_proxy stopped
12月 16 16:05:12.5 - [ERROR] stop module gae_proxy fail:'imp'
12月 16 16:05:12.5 - [ERROR] Except stack:Traceback (most recent call last):
  File "/media/Data/Applications/GoAgent/XX-Net/launcher/module_init.py", line 71, in stop
    _start = proc_handler[module]["imp"].start
KeyError: 'imp'

Gtk-Message: Failed to load module "canberra-gtk-module"
[9711:9749:1216/160512:ERROR:nss_util.cc(839)] After loading Root Certs, loaded==false: NSS error code: -8018
```

访问什么页面都是空白, 都抛出那个异常.
OS: Debian Linux 8.2.

**Comment by zjhzxhz** [comment]
对了还有一个诡异的Bug:

```
load google ip_list num:3002, gws num:3000
```

为什么我的状态页面有时候会显示 Good IP: 3001, Total IP: 3000?

**Comment by xxnet** [comment]
2015-12-16 16:11 GMT+08:00 Howard Shieh <notifications@github.com>:

> 对了还有一个诡异的Bug:
>
> load google ip_list num:3002, gws num:3000
>
> 为什么我的状态页面有时候会显示 Good IP: 3001, Total IP: 3000?
>
>
> 这应该是计数器错误，没有加锁导致的，一般不会被发现，没想到你这3000个全部是好的，下次返回给用户前要先检查一下合理性，呵呵。

**Comment by xxnet** [comment]
提交修复了，不过获取系统代理设置的代码被我关掉了，否则非windows平台无法工作。
@simonasd 以后解决吧

在 2015年12月16日 下午4:15，Net XX <xxnet.dev@gmail.com>写道：

>
>
> 2015-12-16 16:11 GMT+08:00 Howard Shieh <notifications@github.com>:
>
>> 对了还有一个诡异的Bug:
>>
>> load google ip_list num:3002, gws num:3000
>>
>> 为什么我的状态页面有时候会显示 Good IP: 3001, Total IP: 3000?
>>
>>
>> 这应该是计数器错误，没有加锁导致的，一般不会被发现，没想到你这3000个全部是好的，下次返回给用户前要先检查一下合理性，呵呵。
>
>

**Comment by simonasd** [comment]
@xxnet 好的，将来这个是要放在诊断系统里的，到时候把检测程序分不同的操作系统来运作吧。

**Comment by zjhzxhz** [comment]
非专家模式有一个Bug, 参见PR #1613

**Comment by simonasd** [comment]
@zjhzxhz bug已确认。当时没注意
