### ISSUE TITLE
Mac OS X: Unknown locale: UTF-8

### ISSUE THREAD

**Issue by zjhzxhz** [XX-net/XX-Net#1619]
还是我…… 最新的Master在 Mac 下启动出现异常：

```
Traceback (most recent call last):
  File "launcher/start.py", line 74, in <module>
    import web_control
  File "/Applications/XX-Net/launcher/web_control.py", line 33, in <module>
    import jinja2_i18n_helper
  File "/Applications/XX-Net/launcher/jinja2_i18n_helper.py", line 112, in <module>
    ihelper = Jinja2I18nHelper()
  File "/Applications/XX-Net/launcher/jinja2_i18n_helper.py", line 70, in __init__
    self.current_locale, self.encoding = locale.getdefaultlocale() # tuple, e.g., ('en_US', 'UTF-8')                
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 543, in getdefaultlocale
    return _parse_localename(localename)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 475, in _parse_localename
    raise ValueError, 'unknown locale: %s' % localename
ValueError: unknown locale: UTF-8
```

OS: Mac OS X Yosemite 10.11.2

**Comment by yeahwu** [comment]
老方楼下的，我知道！

**Comment by zjhzxhz** [comment]
够了~ - -|||

**Comment by xxnet** [comment]
I think bug have fixed on trunk, download trunk version and test it.

2015-12-16 23:03 GMT+08:00 Howard Shieh <notifications@github.com>:

**Comment by zjhzxhz** [comment]
是的~ 已经可以使用了。
话说我改进了一下 Mac 下的字体 #1624 

还有一个问题, 貌似 PHP 模块没有汉化呢~
原谅我懒得开一个新的 Issue.
![screen shot 2015-12-17 at 13 27 50](https://cloud.githubusercontent.com/assets/1730504/11862121/22e5ae14-a4c2-11e5-8430-3397194a13b7.png)

**Comment by mikedchavez1010** [comment]
Thank you for your testing the development version with the new i18n feature on Mac, @zjhzxhz.
