### ISSUE TITLE
“无法连接到代理服务器”  状态页空白  根据指引运行start.bat无效

### ISSUE THREAD

**Issue by ericnic** [XX-net/XX-Net#1626]

**Comment by xxnet** [comment]
显示什么内容，把命令行窗口的内容贴上来

2015-12-17 13:44 GMT+08:00 ericnic <notifications@github.com>:

**Comment by ericnic** [comment]
File "E:\Program Files\XX-Net-2.1.2\launcher\web_control.py", line 48, in fini
sh_request
  File "E:\Program Files\XX-Net-2.1.2\python27\1.0\lib\SocketServer.py", line 59
3, in process_request_thread
Traceback (most recent call last):
    self.finish_request(request, client_address)
    self.handle()
    self.RequestHandlerClass(request, client_address, self)
    self.finish_request(request, client_address)
  File "E:\Program Files\XX-Net-2.1.2\python27\1.0\lib\SocketServer.py", line 59
3, in process_request_thread
  File "E:\Program Files\XX-Net-2.1.2\launcher\web_control.py", line 48, in fini
sh_request
  File "E:\Program Files\XX-Net-2.1.2\python27\1.0\lib\BaseHTTPServer.py", line
340, in handle
  File "E:\Program Files\XX-Net-2.1.2\python27\1.0\lib\SocketServer.py", line 64
9, in __init__
  File "E:\Program Files\XX-Net-2.1.2\launcher\web_control.py", line 48, in fini
sh_request
    self.finish_request(request, client_address)
    self.RequestHandlerClass(request, client_address, self)
    self.handle_one_request()
    self.handle()
    self.RequestHandlerClass(request, client_address, self)
  File "E:\Program Files\XX-Net-2.1.2\launcher\web_control.py", line 48, in fini
sh_request
  File "E:\Program Files\XX-Net-2.1.2\python27\1.0\lib\SocketServer.py", line 64
9, in __init__
  File "E:\Program Files\XX-Net-2.1.2\python27\1.0\lib\BaseHTTPServer.py", line
328, in handle_one_request
  File "E:\Program Files\XX-Net-2.1.2\python27\1.0\lib\BaseHTTPServer.py", line
340, in handle
  File "E:\Program Files\XX-Net-2.1.2\python27\1.0\lib\SocketServer.py", line 64
9, in __init__
    self.RequestHandlerClass(request, client_address, self)
    self.handle()
    method()
    self.handle_one_request()
    self.handle()
  File "E:\Program Files\XX-Net-2.1.2\python27\1.0\lib\SocketServer.py", line 64
9, in __init__
  File "E:\Program Files\XX-Net-2.1.2\python27\1.0\lib\BaseHTTPServer.py", line
340, in handle
  File "E:\Program Files\XX-Net-2.1.2\launcher\web_control.py", line 143, in do_
GET
  File "E:\Program Files\XX-Net-2.1.2\python27\1.0\lib\BaseHTTPServer.py", line
328, in handle_one_request
  File "E:\Program Files\XX-Net-2.1.2\python27\1.0\lib\BaseHTTPServer.py", line
340, in handle
    self.handle()
    self.handle_one_request()
    controler = module_init.proc_handler[module]["imp"].local.web_control.Contro
lHandler(self.client_address, self.headers, self.command, path, self.rfile, self
.wfile)
    method()
    self.handle_one_request()
  File "E:\Program Files\XX-Net-2.1.2\python27\1.0\lib\BaseHTTPServer.py", line
340, in handle
  File "E:\Program Files\XX-Net-2.1.2\python27\1.0\lib\BaseHTTPServer.py", line
328, in handle_one_request
KeyError: 'imp'
 - File "E:\Program Files\XX-Net-2.1.2\launcher\web_control.py", line 143, in do
_GET
---------------------------------------
 File "E:\Program Files\XX-Net-2.1.2\python27\1.0\lib\BaseHTTPServer.py", line 3
28, in handle_one_request
    self.handle_one_request()
    method()
    controler = module_init.proc_handler[module]["imp"].local.web_control.Contro
lHandler(self.client_address, self.headers, self.command, path, self.rfile, self
.wfile)
    method()
  File "E:\Program Files\XX-Net-2.1.2\python27\1.0\lib\BaseHTTPServer.py", line
328, in handle_one_request
  File "E:\Program Files\XX-Net-2.1.2\launcher\web_control.py", line 143, in do_
GET
KeyError: 'imp'
 - File "E:\Program Files\XX-Net-2.1.2\launcher\web_control.py", line 143, in do
_GET
---------------------------------------
    method()
    controler = module_init.proc_handler[module]["imp"].local.web_control.Contro
lHandler(self.client_address, self.headers, self.command, path, self.rfile, self
.wfile)
    controler = module_init.proc_handler[module]["imp"].local.web_control.Contro
lHandler(self.client_address, self.headers, self.command, path, self.rfile, self
.wfile)
  File "E:\Program Files\XX-Net-2.1.2\launcher\web_control.py", line 143, in do_
GET
KeyError: 'imp'
K-eyError: 'imp'
---------------------------------------
----------------------------------------   controler = module_init.proc_handler[
module]["imp"].local.web_control.ControlHandler(self.client_address, self.header
s, self.command, path, self.rfile, self.wfile)

KeyError: 'imp'
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 4885)
Traceback (most recent call last):
  File "E:\Program Files\XX-Net-2.1.2\python27\1.0\lib\SocketServer.py", line 59
3, in process_request_thread
    self.finish_request(request, client_address)
  File "E:\Program Files\XX-Net-2.1.2\launcher\web_control.py", line 48, in fini
sh_request
    self.RequestHandlerClass(request, client_address, self)
  File "E:\Program Files\XX-Net-2.1.2\python27\1.0\lib\SocketServer.py", line 64
9, in __init__
    self.handle()
  File "E:\Program Files\XX-Net-2.1.2\python27\1.0\lib\BaseHTTPServer.py", line
340, in handle
    self.handle_one_request()
  File "E:\Program Files\XX-Net-2.1.2\python27\1.0\lib\BaseHTTPServer.py", line
328, in handle_one_request
    method()
  File "E:\Program Files\XX-Net-2.1.2\launcher\web_control.py", line 143, in do_
GET
    controler = module_init.proc_handler[module]["imp"].local.web_control.Contro
lHandler(self.client_address, self.headers, self.command, path, self.rfile, self
.wfile)
KeyError: 'imp'
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 4886)
Traceback (most recent call last):
  File "E:\Program Files\XX-Net-2.1.2\python27\1.0\lib\SocketServer.py", line 59
3, in process_request_thread
    self.finish_request(request, client_address)
  File "E:\Program Files\XX-Net-2.1.2\launcher\web_control.py", line 48, in fini
sh_request
    self.RequestHandlerClass(request, client_address, self)
  File "E:\Program Files\XX-Net-2.1.2\python27\1.0\lib\SocketServer.py", line 64
9, in __init__
    self.handle()
  File "E:\Program Files\XX-Net-2.1.2\python27\1.0\lib\BaseHTTPServer.py", line
340, in handle
    self.handle_one_request()
  File "E:\Program Files\XX-Net-2.1.2\python27\1.0\lib\BaseHTTPServer.py", line
328, in handle_one_request
    method()
  File "E:\Program Files\XX-Net-2.1.2\launcher\web_control.py", line 143, in do_
GET
    controler = module_init.proc_handler[module]["imp"].local.web_control.Contro
lHandler(self.client_address, self.headers, self.command, path, self.rfile, self
.wfile)
KeyError: 'imp'
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 4887)
Traceback (most recent call last):
  File "E:\Program Files\XX-Net-2.1.2\python27\1.0\lib\SocketServer.py", line 59
3, in process_request_thread
    self.finish_request(request, client_address)
  File "E:\Program Files\XX-Net-2.1.2\launcher\web_control.py", line 48, in fini
sh_request
    self.RequestHandlerClass(request, client_address, self)
  File "E:\Program Files\XX-Net-2.1.2\python27\1.0\lib\SocketServer.py", line 64
9, in __init__
    self.handle()
  File "E:\Program Files\XX-Net-2.1.2\python27\1.0\lib\BaseHTTPServer.py", line
340, in handle
    self.handle_one_request()
  File "E:\Program Files\XX-Net-2.1.2\python27\1.0\lib\BaseHTTPServer.py", line
328, in handle_one_request
    method()
  File "E:\Program Files\XX-Net-2.1.2\launcher\web_control.py", line 143, in do_
GET
    controler = module_init.proc_handler[module]["imp"].local.web_control.Contro
lHandler(self.client_address, self.headers, self.command, path, self.rfile, self
.wfile)
KeyError: 'imp'
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 4888)
Traceback (most recent call last):
  File "E:\Program Files\XX-Net-2.1.2\python27\1.0\lib\SocketServer.py", line 59
3, in process_request_thread
    self.finish_request(request, client_address)
  File "E:\Program Files\XX-Net-2.1.2\launcher\web_control.py", line 48, in fini
sh_request
    self.RequestHandlerClass(request, client_address, self)
  File "E:\Program Files\XX-Net-2.1.2\python27\1.0\lib\SocketServer.py", line 64
9, in __init__
    self.handle()
  File "E:\Program Files\XX-Net-2.1.2\python27\1.0\lib\BaseHTTPServer.py", line
340, in handle
    self.handle_one_request()
  File "E:\Program Files\XX-Net-2.1.2\python27\1.0\lib\BaseHTTPServer.py", line
328, in handle_one_request
    method()
  File "E:\Program Files\XX-Net-2.1.2\launcher\web_control.py", line 143, in do_
GET
    controler = module_init.proc_handler[module]["imp"].local.web_control.Contro
lHandler(self.client_address, self.headers, self.command, path, self.rfile, self
.wfile)
KeyError: 'imp'
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 4891)
Traceback (most recent call last):
  File "E:\Program Files\XX-Net-2.1.2\python27\1.0\lib\SocketServer.py", line 59
3, in process_request_thread
    self.finish_request(request, client_address)
  File "E:\Program Files\XX-Net-2.1.2\launcher\web_control.py", line 48, in fini
sh_request
    self.RequestHandlerClass(request, client_address, self)
  File "E:\Program Files\XX-Net-2.1.2\python27\1.0\lib\SocketServer.py", line 64
9, in __init__
    self.handle()
  File "E:\Program Files\XX-Net-2.1.2\python27\1.0\lib\BaseHTTPServer.py", line
340, in handle
    self.handle_one_request()
  File "E:\Program Files\XX-Net-2.1.2\python27\1.0\lib\BaseHTTPServer.py", line
328, in handle_one_request
    method()
  File "E:\Program Files\XX-Net-2.1.2\launcher\web_control.py", line 143, in do_
GET
    controler = module_init.proc_handler[module]["imp"].local.web_control.Contro
lHandler(self.client_address, self.headers, self.command, path, self.rfile, self
.wfile)
KeyError: 'imp'
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 4892)
Traceback (most recent call last):
  File "E:\Program Files\XX-Net-2.1.2\python27\1.0\lib\SocketServer.py", line 59
3, in process_request_thread
    self.finish_request(request, client_address)
  File "E:\Program Files\XX-Net-2.1.2\launcher\web_control.py", line 48, in fini
sh_request
    self.RequestHandlerClass(request, client_address, self)
  File "E:\Program Files\XX-Net-2.1.2\python27\1.0\lib\SocketServer.py", line 64
9, in __init__
    self.handle()
  File "E:\Program Files\XX-Net-2.1.2\python27\1.0\lib\BaseHTTPServer.py", line
340, in handle
    self.handle_one_request()
  File "E:\Program Files\XX-Net-2.1.2\python27\1.0\lib\BaseHTTPServer.py", line
328, in handle_one_request
    method()
  File "E:\Program Files\XX-Net-2.1.2\launcher\web_control.py", line 143, in do_
GET
    controler = module_init.proc_handler[module]["imp"].local.web_control.Contro
lHandler(self.client_address, self.headers, self.command, path, self.rfile, self
.wfile)
KeyError: 'imp'
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 4893)
Traceback (most recent call last):
  File "E:\Program Files\XX-Net-2.1.2\python27\1.0\lib\SocketServer.py", line 59
3, in process_request_thread
    self.finish_request(request, client_address)
  File "E:\Program Files\XX-Net-2.1.2\launcher\web_control.py", line 48, in fini
sh_request
    self.RequestHandlerClass(request, client_address, self)
  File "E:\Program Files\XX-Net-2.1.2\python27\1.0\lib\SocketServer.py", line 64
9, in __init__
    self.handle()
  File "E:\Program Files\XX-Net-2.1.2\python27\1.0\lib\BaseHTTPServer.py", line
340, in handle
    self.handle_one_request()
  File "E:\Program Files\XX-Net-2.1.2\python27\1.0\lib\BaseHTTPServer.py", line
328, in handle_one_request
    method()
  File "E:\Program Files\XX-Net-2.1.2\launcher\web_control.py", line 143, in do_
GET
    controler = module_init.proc_handler[module]["imp"].local.web_control.Contro
lHandler(self.client_address, self.headers, self.command, path, self.rfile, self
.wfile)
KeyError: 'imp'
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 4894)
Traceback (most recent call last):
  File "E:\Program Files\XX-Net-2.1.2\python27\1.0\lib\SocketServer.py", line 59
3, in process_request_thread
    self.finish_request(request, client_address)
  File "E:\Program Files\XX-Net-2.1.2\launcher\web_control.py", line 48, in fini
sh_request
    self.RequestHandlerClass(request, client_address, self)
  File "E:\Program Files\XX-Net-2.1.2\python27\1.0\lib\SocketServer.py", line 64
9, in __init__
    self.handle()
  File "E:\Program Files\XX-Net-2.1.2\python27\1.0\lib\BaseHTTPServer.py", line
340, in handle
    self.handle_one_request()
  File "E:\Program Files\XX-Net-2.1.2\python27\1.0\lib\BaseHTTPServer.py", line
328, in handle_one_request
    method()
  File "E:\Program Files\XX-Net-2.1.2\launcher\web_control.py", line 143, in do_
GET
    controler = module_init.proc_handler[module]["imp"].local.web_control.Contro
lHandler(self.client_address, self.headers, self.command, path, self.rfile, self
.wfile)
KeyError: 'imp'
----------------------------------------

**Comment by ericnic** [comment]
这是运行那个bat之后显示的，不知道您指的命令行是这个吗?

**Comment by xxnet** [comment]
是这个，不过你要把一启动后出现的第一个异常贴出来，后面的已经无法工作的报错，不能定位问题。

2015-12-18 13:16 GMT+08:00 ericnic <notifications@github.com>:

**Comment by xxnet** [comment]
另外，你可以试试最新版本

在 2015年12月18日 下午2:35，Net XX <xxnet.dev@gmail.com>写道：

**Comment by ericnic** [comment]
谢谢您

我下载了最新版本的并复制了data文件夹后已经可以正常使用了

万分感谢
