### ISSUE TITLE
No CA file exist

### ISSUE THREAD

**Issue by Calvin-wang** [XX-net/XX-Net#1660]
Dec 21 12:55:03 - [INFO] start XX-Net 2.7.3
Dec 21 12:55:03 - [DEBUG] start confirm_xxnet_exit
Dec 21 12:55:03 - [DEBUG] good, xxnet:8087 cleared!
Dec 21 12:55:03 - [DEBUG] good, xxnet:8085 clear!
Dec 21 12:55:03 - [DEBUG] finished confirm_xxnet_exit
Dec 21 12:55:03 - [INFO] load ip range file:/Applications/XX-Net-2.7.3/gae_proxy/local/ip_range.txt
Dec 21 12:55:03 - [INFO] load google ip_list num:0, gws num:0
Dec 21 12:55:03 - [INFO] SSL use version:TLSv1
Dec 21 12:55:03 - [DEBUG] ## GAEProxy set keep_running: True
Dec 21 12:55:03 - [INFO] ------------------------------------------------------
Dec 21 12:55:03 - [INFO] Python Version     : 2.7.10
Dec 21 12:55:03 - [INFO] OS                 : Release:10.11.2; Version:('', '', '') Machine:x86_64
Dec 21 12:55:03 - [INFO] Listen Address     : 127.0.0.1:8087
Dec 21 12:55:03 - [INFO] GAE APPID          : xxnet-1|xxnet-2|xxnet-3|xxnet-4|xxnet-5|xxnet-6|xxnet-7|xxnet-8|xxnet-9|xxnet-10|xxnet-11|xxnet-12|xxnet-13|xxnet-14|xxnet-15|xxnet-16|xxnet-17|xxnet-18|xxnet-19|xxnet-20|xxnet-21|xxnet-22|xxnet-23|xxnet-24|xxnet-25|xxnet-26|xxnet-27|xxnet-28|xxnet-29|xxnet-30|xxnet-31|xxnet-32|xxnet-33|xxnet-34|xxnet-35|xxnet-36|xxnet-37|xxnet-38|xxnet-39|xxnet-40|xxnet-41|xxnet-42|xxnet-43|xxnet-44|xxnet-45|xxnet-46|xxnet-47|xxnet-48|xxnet-49|xxnet-50|xxnet-51|xxnet-52|xxnet-53|xxnet-54|xxnet-55|xxnet-56|xxnet-57|xxnet-58|xxnet-59|xxnet-60|xxnet-61|xxnet-62|xxnet-63|xxnet-64|xxnet-65|xxnet-66|xxnet-67|xxnet-68|xxnet-69|xxnet-70|xxnet-71|xxnet-72|xxnet-72|xxnet-73|xxnet-74|xxnet-75|xxnet-76|xxnet-77|xxnet-78|xxnet-79|xxnet-80|xxnet-81|xxnet-82|xxnet-83|xxnet-84|xxnet-85|xxnet-86|xxnet-87|xxnet-88|xxnet-89|xxnet-90|xxnet-91|xxnet-92|xxnet-93|xxnet-94|xxnet-95|xxnet-96|xxnet-97|xxnet-98|xxnet-99|xxnet-100|xxnet-101|xxnet-102|xxnet-103|xxnet-104|xxnet-105|xxnet-106|xxnet-107|xxnet-108|xxnet-109|xxnet-110|xxnet-111|xxnet-112|xxnet-113|xxnet-114|xxnet-115|xxnet-116|xxnet-117|xxnet-118|xxnet-119|xxnet-120|xxnet-121|xxnet-122|xxnet-123|xxnet-124|xxnet-125|xxnet-126|xxnet-127|xxnet-128|xxnet-129|xxnet-130|xxnet-131|xxnet-132|xxnet-133|xxnet-134|xxnet-135|xxnet-136|xxnet-137|xxnet-138|xxnet-139|xxnet-140|xxnet-141|xxnet-142|xxnet-143|xxnet-144|xxnet-145|xxnet-146|xxnet-147|xxnet-148|xxnet-149|xxnet-150|xxnet-151|xxnet-152|xxnet-153|xxnet-154|xxnet-155|xxnet-156|xxnet-157|xxnet-158|xxnet-159
Dec 21 12:55:03 - [INFO] Pac Server         : http://127.0.0.1:8086/proxy.pac
Dec 21 12:55:03 - [INFO] ------------------------------------------------------
Dec 21 12:55:03 - [INFO] no CA file exist
Dec 21 12:55:03 - [INFO] clean old site certs
Dec 21 12:55:03 - [INFO] generate CA file:/Applications/XX-Net-2.7.3/data/gae_proxy/CA.crt
Exception in thread Thread-53:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Applications/XX-Net-2.7.3/gae_proxy/start.py", line 19, in main
    client.main()
  File "/Applications/XX-Net-2.7.3/gae_proxy/local/proxy.py", line 217, in main
    CertUtil.init_ca()
  File "/Applications/XX-Net-2.7.3/gae_proxy/local/cert_util.py", line 535, in init_ca
    CertUtil.generate_ca_file()
  File "/Applications/XX-Net-2.7.3/gae_proxy/local/cert_util.py", line 194, in generate_ca_file
    key, ca = CertUtil.create_ca()
  File "/Applications/XX-Net-2.7.3/gae_proxy/local/cert_util.py", line 184, in create_ca
    'basicConstraints', False, 'CA:TRUE', ca, ca)
TypeError: X509Extension() takes exactly 3 arguments (5 given)

**Comment by xxnet** [comment]
把 gae_proxy/local/cert_utilpy", line 184
原来：
'basicConstraints', False, 'CA:TRUE', ca, ca)
改为：
basicConstraints', False, 'CA:TRUE', subject=ca, issuer=ca)

试试

2015-12-21 12:56 GMT+08:00 Calvin-wang <notifications@github.com>:
