### ISSUE TITLE
PHP Proxy: Exceptions must be old-style classes or derived from BaseException, not NoneType

### ISSUE THREAD

**Issue by zjhzxhz** [XX-net/XX-Net#1665]
When I'm using PHP Proxy, I got following exception:

```
[ERROR] Except stack:Traceback (most recent call last):
File "D:\Applications\GoAgent\XX-Net\php_proxy\local\proxylib.py", line 1781, in create_http_request
sock = create_connection(host, port, timeout, validate=validate, cache_key=cache_key, headfirst=headfirst)
File "D:\Applications\GoAgent\XX-Net\php_proxy\local\proxylib.py", line 1505, in create_tcp_connection
raise sock
TypeError: exceptions must be old-style classes or derived from BaseException, not NoneType
```

**Comment by xxnet** [comment]
the error is because the function can't create tcp connection.​

**Comment by zjhzxhz** [comment]
但是没有理由呀。之前都是可以用的呢 0 0

**Comment by xxnet** [comment]
代码几个月没有动过，你找找什么地方不一样，先把能用的环境找回来，再对比不同

2015-12-21 15:10 GMT+08:00 Haozhe Xie <notifications@github.com>:

**Comment by systemcumt** [comment]
楼主是的phpproxy是怎么搞的。。。我已经快搞晕了

**Comment by jzp820927** [comment]
@systemcumt 实在不行，你就用 goagetn 的 php 嘛，goagent 的 php 比较成熟。

**Comment by systemcumt** [comment]
@zjhzxhz 求楼主显灵，求指教求鞭打

**Comment by zjhzxhz** [comment]
@systemcumt 
把`php_proxy/server`里的内容放到一台可用的主机上(并且那台主机可以访问 Google)
然后在 XX-Net 的 PHP 模块页面完成配置。
默认的密码是`123456`.

**Comment by systemcumt** [comment]
@zjhzxhz 我也是这么操作的。搞不定。。。。不知道哪边有问题
