### ISSUE TITLE
ubuntu server 开机运行 无法远程连接Web控制端

### ISSUE THREAD

**Issue by asd3g2x** [XX-net/XX-Net#1682]
xx-net 2.8.2
ubuntu 14.04 
rc.local里加
/home/xx-net/start.sh
重启后能科学上网，但无法远程连接Web控制端
boot.log里有下面提示
-------------------------------------------------------------------------------------------------------------------------------
[WARNING] read request line empty
[ERROR] handler:AttributeError("'NoneType' object has no attribute 'startswith'",)
[ERROR] Except stack:Traceback (most recent call last):
  File "/home/xx-net/python27/1.0/lib/noarch/simple_http_server.py", line 126, in handle_one_request
    self.do_GET()
  File "/home/xx-net/launcher/web_control.py", line 106, in do_GET
    return self.req_index_handler()
  File "/home/xx-net/launcher/web_control.py", line 191, in req_index_handler
    self.load_module_menus()
  File "/home/xx-net/launcher/web_control.py", line 57, in load_module_menus
    stream = i18n_translator.render(locale_dir, os.path.join(root_path, module, "web_ui", "menu.yaml"))
  File "/home/xx-net/launcher/simple_i18n.py", line 135, in render
    po_file = os.path.join(lang_path, self.lang, "LC_MESSAGES", "messages.po")
  File "/usr/lib/python2.7/posixpath.py", line 75, in join
    if b.startswith('/'):
AttributeError: 'NoneType' object has no attribute 'startswith'
-------------------------------------------------------------------------------------------------------------------------------
在终端里运行
/home/xx-net/start.sh
则正常没有什么错误提示能远程连接Web控制端能科学上网

**Comment by xxnet** [comment]
估计是rclocal 里启动，获取不到系统语言信息。

刚刚加了个布丁，你试试trunk上的代码：
https://github.com/XX-net/XX-Net/archive/master.zip

2015-12-23 14:27 GMT+08:00 asd3g2x <notifications@github.com>:

**Comment by fuding** [comment]
奇怪，最近直接通过url下的github zip经常文件缺失，项目首页按钮Download zip下载的都正常

**Comment by xxnet** [comment]
在 2015年12月23日 下午3:47，fuding <notifications@github.com>写道：

> 奇怪，最近直接通过url下的github zip经常文件缺失，项目首页按钮Download zip下载的都正常
>
一直如此，被GFW干扰了

**Comment by asd3g2x** [comment]
测试完毕，能正常远程连接Web控制端了。非常感谢！

**Comment by xxnet** [comment]
好​
