### ISSUE TITLE
有一台电脑怎么运行不了啊？怎么解决？？

### ISSUE THREAD

**Issue by AKB48kojima** [XX-net/XX-Net#1704]
Dec 24 10:56:38.876 - [INFO] start XX-Net 2.8.3
Dec 24 10:56:38.876 - [DEBUG] start confirm_xxnet_exit
Dec 24 10:57:08.894 - [DEBUG] good, xxnet:8087 cleared!
Dec 24 10:57:09.894 - [DEBUG] good, xxnet:8085 clear!
Dec 24 10:57:09.894 - [DEBUG] finished confirm_xxnet_exit
Dec 24 10:57:10.268 - [ERROR] start module gae_proxy fail:DLL load failed: 应用
程序无法启动，因为应用程序的并行配置不正确。有关详细信息，请参阅应用程序事件日志
，或使用命令行 sxstrace.exe 工具。
Dec 24 10:57:10.277 - [ERROR] Except stack:Traceback (most recent call last):
  File "D:\Program Files\XX-Net\launcher\module_init.py", line 37, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['loca
l', 'start'], -1)
  File "D:\Program Files\XX-Net\gae_proxy\start.py", line 14, in <module>
    import local.proxy as client
  File "D:\Program Files\XX-Net\gae_proxy\local\proxy.py", line 94, in <module>
    from cert_util import CertUtil
  File "D:\Program Files\XX-Net\gae_proxy\local\cert_util.py", line 37, in <modu
le>
    import OpenSSL
  File "D:\Program Files\XX-Net\python27\1.0\lib\win32\OpenSSL\__init__.py", lin
e 26, in <module>
    from OpenSSL import crypto, rand, SSL
ImportError: DLL load failed: 应用程序无法启动，因为应用程序的并行配置不正确。有
关详细信息，请参阅应用程序事件日志，或使用命令行 sxstrace.exe 工具。

Dec 24 10:57:10.285 - [INFO] start gae_proxy time cost 346
Dec 24 10:57:10.288 - [INFO] begin to start web control
Dec 24 10:57:10.289 - [INFO] server 127.0.0.1:8085 started.
Dec 24 10:57:10.291 - [INFO] launcher web control started.
Dec 24 10:57:10.400 - [INFO] generate desktop shortcut
Dec 24 10:57:13.688 - [INFO] need_new_uuid: uuid is empty
Dec 24 10:57:13.690 - [INFO] generate uuid:3c0183cb-99d8-4221-88e3-cdbfa10468bc
Dec 24 10:57:13.695 - [INFO] get uuid:3c0183cb-99d8-4221-88e3-cdbfa10468bc
Dec 24 10:57:14.287 - [WARNING] request module:gae_proxy start fail
Dec 24 10:57:15.357 - [WARNING] check_update fail:URLError(SSLError(1, '_ssl.c:5
07: error:14077419:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert access denied
'),)
Dec 24 10:57:15.359 - [INFO] download https://raw.githubusercontent.com/XX-net/X
X-Net/master/README.md to D:\Program Files\XX-Net\data\downloads\README.md, retr
y:0
Dec 24 10:57:36.061 - [WARNING] request module:gae_proxy start fail
Dec 24 10:57:38.059 - [WARNING] request module:gae_proxy start fail
Dec 24 10:57:39.537 - [WARNING] request module:gae_proxy start fail
Dec 24 10:57:40.536 - [WARNING] request module:gae_proxy start fail
Dec 24 10:57:41.538 - [WARNING] request module:gae_proxy start fail

**Comment by xxnet** [comment]
1. 是什么操作系统？
2. 有没有开什么安全软件？如果有请试试先关闭
3. 确认下载的包完整，可以从别的电脑拷贝一份或试试重新下载
​

**Comment by AKB48kojima** [comment]
1、win7 64位系统。
2、我用的360卫士和杀毒，adsafe。我正常能用的也是装了这些，但是可以正常用了。
3、软件就是从你的首页下的。

**Comment by xyuanmu** [comment]
你另外一台电脑安装了哪些版本的vc++库，如2005，2008，2010，把这台没安装的安装上。

**Comment by xyuanmu** [comment]
你另外一台电脑安装了哪些版本的vc++库，如2005，2008，2010，把这台没安装的安装上。

**Comment by AKB48kojima** [comment]
我都安装了啊。

**Comment by wpyok500** [comment]
我在两台装有360的卫士和杀毒，xx都不能用。在没装360的卫士和杀毒用的很好。要翻墙就不要用360

**Comment by AKB48kojima** [comment]
那为啥我另一台能能翻墙的也是装了360和杀毒的，正常使用无问题。

**Comment by xxnet** [comment]
根据以往反馈，​360 会不定期的报 OpenSSL下的dll文件有病毒，而这个文件是从官方下载来的。
有考虑替换掉OpenSSL模块，全部用python实现的版本，还待研究

**Comment by AKB48kojima** [comment]
但是我这个没有报病毒啊。

**Comment by xxnet** [comment]
是不确定的报，概率不高，当然不排除真中毒的情况

2015-12-24 16:53 GMT+08:00 AKB48kojima <notifications@github.com>:

**Comment by xyuanmu** [comment]
这里有同样的问题，看看是不是没有安装VC++ 2008(x86)：https://github.com/XX-net/XX-Net/issues/1268#issuecomment-151050871

**Comment by AKB48kojima** [comment]
VC++ 2008(x86装不上，报错1935。
64位装的上。

**Comment by AKB48kojima** [comment]
悲剧VC++ 2008(x86)就是装不上，哎，只好这台继续用goagent了。

**Comment by linhua55** [comment]
@AKB48kojima 
可以尝试一下安装VC运行库合集，看能否安装成功
http://www.pc6.com/softview/SoftView_104246.html
注意：上述地址未经测试

**Comment by AKB48kojima** [comment]
按楼上的装了VC运行库合集依旧不行啊。
哎，还是继续用goagent

**Comment by S-Aoi** [comment]
我学校的电脑 xp 系统也是类似这个错误，装了 VC 运行库合集后可以运行。
