### ISSUE TITLE
转入Linux，但是出现这种错误，麻烦看看是哪个包没装呢？

### ISSUE THREAD

**Issue by condywl** [XX-net/XX-Net#1708]
/usr/XX-Net/launcher/gtk_tray.py:39: GtkWarning: 无法在模块路径中找到主题引擎：“adwaita”，
  self.trayicon = gtk.StatusIcon()
Dec 24 20:26:28 - [INFO] start XX-Net 2.7.3
Dec 24 20:26:28 - [DEBUG] start confirm_xxnet_exit
Dec 24 20:26:28 - [DEBUG] good, xxnet:8087 cleared!
Dec 24 20:26:28 - [DEBUG] good, xxnet:8085 clear!
Dec 24 20:26:28 - [DEBUG] finished confirm_xxnet_exit
Dec 24 20:26:28 - [ERROR] start module gae_proxy fail:/usr/XX-Net/python27/1.0/lib/linux/OpenSSL/crypto.so: 错误 ELF 类: ELFCLASS64
Traceback (most recent call last):
  File "/usr/XX-Net/launcher/module_init.py", line 37, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "/usr/XX-Net/gae_proxy/start.py", line 14, in <module>
    import local.proxy as client
  File "/usr/XX-Net/gae_proxy/local/proxy.py", line 74, in <module>
    from cert_util import CertUtil
  File "/usr/XX-Net/gae_proxy/local/cert_util.py", line 37, in <module>
    import OpenSSL
  File "/usr/XX-Net/python27/1.0/lib/linux/OpenSSL/__init__.py", line 36, in <module>
    from OpenSSL import crypto
ImportError: /usr/XX-Net/python27/1.0/lib/linux/OpenSSL/crypto.so: 错误 ELF 类: ELFCLASS64

Dec 24 20:26:28 - [INFO] start gae_proxy time cost 1
Dec 24 20:26:28 - [INFO] begin to start web control
Dec 24 20:26:28 - [INFO] launcher web control started.
[4566:4566:1224/202628:ERROR:browser_main_loop.cc(253)] Gtk: 无法在模块路径中找到主题引擎：“adwaita”，
[4566:4566:1224/202628:ERROR:browser_main_loop.cc(253)] Gtk: 无法在模块路径中找到主题引擎：“adwaita”，
已在现有的浏览器会话中创建新的窗口。
Dec 24 20:26:28 - [WARNING] request module:gae_proxy start fail
Dec 24 20:26:29 - [INFO] get uuid:709af401-38a9-4877-a959-8bdefa257e6a
Dec 24 20:26:29 - [WARNING] check_update fail:URLError(error(111, '\xe6\x8b\x92\xe7\xbb\x9d\xe8\xbf\x9e\xe6\x8e\xa5'),)
Dec 24 20:26:29 - [INFO] download https://raw.githubusercontent.com/XX-net/XX-Net/master/README.md to /usr/XX-Net/data/downloads/README.md, retry:0
Dec 24 20:26:29 - [WARNING] request module:gae_proxy start fail

**Comment by xxnet** [comment]
​python 的 OpenSSL 库没装
