### ISSUE TITLE
升级都 3.8.4 后，有个模块打不开

### ISSUE THREAD

**Issue by Anudorannador** [XX-net/XX-Net#1714]
```
Dec 25 15:31:56 - [INFO] start XX-Net 2.8.4
Dec 25 15:31:56 - [DEBUG] start confirm_xxnet_exit
Dec 25 15:31:57 - [DEBUG] good, xxnet:8087 cleared!
Dec 25 15:31:58 - [DEBUG] good, xxnet:8085 clear!
Dec 25 15:31:58 - [DEBUG] finished confirm_xxnet_exit
Dec 25 15:31:58 - [ERROR] start module gae_proxy fail:cannot import name Logger
Traceback (most recent call last):
  File "C:\XX-Net\launcher\module_init.py", line 37, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "C:\XX-Net\gae_proxy\start.py", line 14, in <module>
    import local.proxy as client
  File "C:\XX-Net\gae_proxy\local\proxy.py", line 87, in <module>
    from xlog import Logger
ImportError: cannot import name Logger

Dec 25 15:31:58 - [INFO] start gae_proxy time cost 29
Dec 25 15:31:58 - [INFO] begin to start web control
Dec 25 15:31:58 - [INFO] launcher web control started.
Dec 25 15:31:58 - [WARNING] request module:gae_proxy start fail
Dec 25 15:31:59 - [INFO] get uuid:fd9e0aa8-3871-4dec-86ac-63974aef990b
Dec 25 15:31:59 - [WARNING] request module:gae_proxy start fail
Dec 25 15:32:00 - [WARNING] check_update fail:URLError(error(10061, ''),)
Dec 25 15:32:00 - [INFO] download https://raw.githubusercontent.com/XX-net/XX-Net/master/README.md to C:\XX-Net\data\downloads\README.md, retry:0
Dec 25 15:32:00 - [WARNING] request module:gae_proxy start fail
Dec 25 15:32:01 - [WARNING] request module:gae_proxy start fail
Dec 25 15:32:03 - [WARNING] request module:gae_proxy start fail
Dec 25 15:32:04 - [WARNING] request module:gae_proxy start fail
Dec 25 15:32:05 - [WARNING] request module:gae_proxy start fail
Dec 25 15:32:06 - [WARNING] request module:gae_proxy start fail
Dec 25 15:32:08 - [WARNING] request module:gae_proxy start fail
Dec 25 15:32:09 - [WARNING] request module:gae_proxy start fail
Dec 25 15:32:10 - [WARNING] request module:gae_proxy start fail
^C
```
日志如图所示……
我导出来了。

**Comment by Anudorannador** [comment]
这个问题出现在从3.8.3自动升级到3.8.4过程中，手动升级就没问题……

**Comment by xxnet** [comment]
你打开 data/launcher/launcher.log，看看有没有报异常的日志

**Comment by jap33** [comment]
3.8.4起动后连接池一直为0不能用，3.8.3没有问题。

**Comment by Anudorannador** [comment]
@xxnet 呃。我已经删了，只保留了 good_ips.txt 和 手动配置文件 manual.ini...

**Comment by xxnet** [comment]
​@Anudorannador
  重新下载 2.8.4看看行不行

**Comment by xxnet** [comment]
​应该是自动升级模块有问题，正在改进
