### ISSUE TITLE
2.8.8无法打开

### ISSUE THREAD

**Issue by niodx** [XX-net/XX-Net#1760]
状态页显示空白, 很可能GAEProxy启动失败, 请按指引查找问题原因.

D:\Program Files (x86)\XX-Net>SET PYTHONPATH=

D:\Program Files (x86)\XX-Net>"D:\Program Files (x86)\XX-Net\python27/1.0/python.exe" "D:\Program Files (x86)\XX-Net\launcher/start.py"
Dec 29 13:40:06 - [INFO] start XX-Net 2.8.8
Dec 29 13:40:06 - [DEBUG] start confirm_xxnet_exit
Dec 29 13:40:07 - [DEBUG] good, xxnet:8087 cleared!
Dec 29 13:40:08 - [DEBUG] good, xxnet:8085 clear!
Dec 29 13:40:08 - [DEBUG] finished confirm_xxnet_exit
Dec 29 13:40:08 - [ERROR] start module gae_proxy fail:'str' object is not callable
Traceback (most recent call last):
  File "D:\Program Files (x86)\XX-Net\launcher\module_init.py", line 37, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "D:\Program Files (x86)\XX-Net\gae_proxy\start.py", line 14, in <module>
    import local.proxy as client
  File "D:\Program Files (x86)\XX-Net\gae_proxy\local\proxy.py", line 74, in <module>
    from cert_util import CertUtil
  File "D:\Program Files (x86)\XX-Net\gae_proxy\local\cert_util.py", line 16, in <module>
    xlog = getLogger("gae_proxy")
  File "D:\Program Files (x86)\XX-Net\gae_proxy\local\xlog.py", line 56, in getLogger
    return cls(*args, **kwargs)
TypeError: 'str' object is not callable

Dec 29 13:40:08 - [INFO] start gae_proxy time cost 39
Dec 29 13:40:08 - [INFO] begin to start web control
Dec 29 13:40:08 - [INFO] launcher web control started.
Dec 29 13:40:08 - [WARNING] request module:gae_proxy start fail

**Comment by niodx** [comment]
好吧 直接删除旧版重新下载后似乎正常了，我再看下

**Comment by iceliminghui** [comment]
我的在配置界面选择了升级，然后启动后变成这样了。
————————————————————————————————————————
Dec 29 15:24:00 - [INFO] start gae_proxy time cost 62
Dec 29 15:24:00 - [INFO] begin to start web control
Dec 29 15:24:00 - [INFO] launcher web control started.
Dec 29 15:24:05 - [DEBUG] launcher web_control 127.0.0.1:62636 GET /css/bootstra
p.css
Dec 29 15:24:05 - [DEBUG] launcher web_control 127.0.0.1:62637 GET /css/bootstra
p-responsive.css
Dec 29 15:24:05 - [DEBUG] launcher web_control 127.0.0.1:62638 GET /css/flat-ui.
css
Dec 29 15:24:05 - [DEBUG] launcher web_control 127.0.0.1:62639 GET /css/ladda-th
emeless.min.css
Dec 29 15:24:05 - [DEBUG] launcher web_control 127.0.0.1:62641 GET /js/jquery-1.
11.2.min.js
Dec 29 15:24:05 - [DEBUG] launcher web_control 127.0.0.1:62640 GET /css/style.cs
s?v=1
Dec 29 15:24:05 - [DEBUG] launcher web_control 127.0.0.1:62642 GET /js/flat-ui.m
in.js
Dec 29 15:24:05 - [DEBUG] launcher web_control 127.0.0.1:62643 GET /js/spin.min.
js
Dec 29 15:24:05 - [DEBUG] launcher web_control 127.0.0.1:62644 GET /js/ladda.min
.js
Dec 29 15:24:05 - [DEBUG] launcher web_control 127.0.0.1:62645 GET /js/site.js?2
0150512
Dec 29 15:24:05 - [DEBUG] launcher web_control 127.0.0.1:62646 GET /js/bootstrap
.min.js
Dec 29 15:24:05 - [DEBUG] launcher web_control 127.0.0.1:62647 GET /js/jquery.ti
mer.js
Dec 29 15:24:05 - [DEBUG] launcher web_control 127.0.0.1:62648 GET /img/logo.png

Dec 29 15:24:05 - [DEBUG] launcher web_control 127.0.0.1:62649 GET /img/fixed-wi
dth.png
Dec 29 15:24:05 - [DEBUG] launcher web_control 127.0.0.1:62650 GET /img/quit.png

Dec 29 15:24:05 - [WARNING] request module:gae_proxy start fail
Dec 29 15:24:06 - [WARNING] request module:gae_proxy start fail
Dec 29 15:24:07 - [WARNING] request module:gae_proxy start fail
Dec 29 15:24:08 - [WARNING] request module:gae_proxy start fail   （这一行无限循环）
————————————————————————————————————————

**Comment by liu-uil** [comment]
2.8.9也有这个问题

**Comment by jzp820927** [comment]
一般升级出现的问题，都是下载不完整，重新下载一次都可以解决！

**Comment by bbwwxxnet** [comment]
2.89总有用户账户控制的自启窗口弹出。如何是好，网上的方法不见效。
~\php_proxy\local\cert_util.py

**Comment by xxnet** [comment]
​这似乎是自动导入证书的脚本，你需要使用PHP模块吗？如果不用，可以关掉php模块

**Comment by hlee13** [comment]
同样遇到此类问题，如果定位是导入证书脚本的问题，尽早解决，并附上 patch

**Comment by hlee13** [comment]
重新下载 成本太高
