### ISSUE TITLE
在路由器上运行出现的状况

### ISSUE THREAD

**Issue by zodiac2222** [XX-net/XX-Net#1771]
root@Y:/opt/XXNet/launcher# python start.py
Traceback (most recent call last):
  File "start.py", line 77, in <module>
    import config
  File "/opt/XXNet/launcher/config.py", line 5, in <module>
    from distutils.version import LooseVersion
ImportError: No module named distutils.version

如果运行/opt/XXNet/gae_proxy/python start.py是能够运行的。但是几分钟会自动退出，没有错误提示。
另外始终无法打开web配置页面。
路由器是网件的wndr4500 v2，刷的tomato

**Comment by abchb99** [comment]
目前应该没有在路由器上运行的版本吧？

**Comment by swizardlv** [comment]
期待在openwrt上的版本
