### ISSUE TITLE
ubuntu15.10 终端可否用xx-net代理下载youtube视频 

### ISSUE THREAD

**Issue by evolutionboy** [XX-net/XX-Net#1782]
一直以来用的you-get 和SS，proxychains配合在终端下载youtube视频，以前基本我不下国外网站视频，但渐渐开始下国外视频了，高清水平就OK了，下载下来还省流量些，在电视机上放家人看。
但现在换成XX-net，就失败 了，
，，，，，，，，，，，
状态
属性 	值
本地网络状态 	OK
IP数量 	455
IP质量 	273
连接池(帮助) 	11 / 50
浏览器代理设置 	Fail
扫描IP线程数(设置) 	5
屏蔽状态 (帮助) 	OK
配置
属性 	值
监听代理 	127.0.0.1:8087
PAC自动代理地址 	http://127.0.0.1:8086/proxy.pac
IPv6 	禁用
Appid
属性 	值
当前工作AppID 	evolution-520
系统版本
属性 	值
XX-Net Version 	2.8.9
Python Version 	2.7.10
System Platform 	x86_64, Linux-4.2.0-22-generic-x86_64-with-Ubuntu-15.10-wily
OS System 	Linux
OS Version 	#27-Ubuntu SMP Thu Dec 17 22:57:08 UTC 2015
OS Release 	4.2.0-22-generic
OS Detail 	Dist:Ubuntu; Version:15.10; ID:wily
Language 	zh_CN
Architecture 	64bit,ELF
Browser 	Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:43.0) Gecko/20100101 Firefox/43.0
，，，，，，，，，，，，，，，，，
evolution@evolution:~$ proxychains you-get -i https://www.youtube.com/watch?v=zBh-sf-3jRU
ProxyChains-3.1 (http://proxychains.sf.net)
|DNS-request| www.youtube.com 
|S-chain|-<>-127.0.0.1:8087-<><>-4.2.2.2:53-<><>-OK
|S-chain|-<>-127.0.0.1:8087-<><>-4.2.2.2:53-<><>-OK
|S-chain|-<>-127.0.0.1:8087-<><>-4.2.2.2:53-<><>-OK
|DNS-response|: www.youtube.com does not exist
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.

**Comment by linhua55** [comment]
请使用you-get的调试选项
    proxychains you-get -di "https://www.youtube.com/watch?v=zBh-sf-3jRU"

在you-get中有指定http代理的选项
    you-get -di -x 127.0.0.1:8087  "https://www.youtube.com/watch?v=zBh-sf-3jRU"

**Comment by evolutionboy** [comment]
@linhua55 谢谢！刚试了，如下。
，，，，，，，，，，，，，，，
evolution@evolution:~$ you-get -di -x 127.0.0.1:8087 "https://www.youtube.com/watch?v=zBh-sf-3jRU"
you-get: version 0.4.217, a tiny downloader that scrapes the web.
you-get: ['https://www.youtube.com/watch?v=zBh-sf-3jRU']
Traceback (most recent call last):
  File "/usr/lib/python3.4/urllib/request.py", line 1183, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python3.4/http/client.py", line 1137, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.4/http/client.py", line 1182, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.4/http/client.py", line 1133, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.4/http/client.py", line 963, in _send_output
    self.send(msg)
  File "/usr/lib/python3.4/http/client.py", line 898, in send
    self.connect()
  File "/usr/lib/python3.4/http/client.py", line 1287, in connect
    server_hostname=server_hostname)
  File "/usr/lib/python3.4/ssl.py", line 362, in wrap_socket
    _context=self)
  File "/usr/lib/python3.4/ssl.py", line 580, in __init__
    self.do_handshake()
  File "/usr/lib/python3.4/ssl.py", line 807, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/dist-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1229, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1150, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1003, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1222, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/extractor.py", line 39, in download_by_url
    self.prepare(**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/extractors/youtube.py", line 142, in prepare
    video_info = parse.parse_qs(get_content('https://www.youtube.com/get_video_info?video_id={}'.format(self.vid)))
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 294, in get_content
    response = request.urlopen(req)
  File "/usr/lib/python3.4/urllib/request.py", line 161, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.4/urllib/request.py", line 464, in open
    response = self._open(req, data)
  File "/usr/lib/python3.4/urllib/request.py", line 482, in _open
    '_open', req)
  File "/usr/lib/python3.4/urllib/request.py", line 442, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 1226, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/python3.4/urllib/request.py", line 1185, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)>
evolution@evolution:~$ proxychains you-get -di "https://www.youtube.com/watch?v=zBh-sf-3jRU"
ProxyChains-3.1 (http://proxychains.sf.net)
|DNS-request| www.youtube.com 
|S-chain|-<>-127.0.0.1:8087-<><>-4.2.2.2:53-<><>-OK
|S-chain|-<>-127.0.0.1:8087-<><>-4.2.2.2:53-<><>-OK
|S-chain|-<>-127.0.0.1:8087-<><>-4.2.2.2:53-<><>-OK
|DNS-response|: www.youtube.com does not exist
you-get: version 0.4.217, a tiny downloader that scrapes the web.
you-get: ['https://www.youtube.com/watch?v=zBh-sf-3jRU']
Traceback (most recent call last):
  File "/usr/lib/python3.4/urllib/request.py", line 1183, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python3.4/http/client.py", line 1137, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.4/http/client.py", line 1182, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.4/http/client.py", line 1133, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.4/http/client.py", line 963, in _send_output
    self.send(msg)
  File "/usr/lib/python3.4/http/client.py", line 898, in send
    self.connect()
  File "/usr/lib/python3.4/http/client.py", line 1279, in connect
    super().connect()
  File "/usr/lib/python3.4/http/client.py", line 871, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python3.4/socket.py", line 494, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.4/socket.py", line 533, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 1] Unknown error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/dist-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1229, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1150, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1003, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 1222, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/extractor.py", line 39, in download_by_url
    self.prepare(**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/you_get/extractors/youtube.py", line 142, in prepare
    video_info = parse.parse_qs(get_content('https://www.youtube.com/get_video_info?video_id={}'.format(self.vid)))
  File "/usr/local/lib/python3.4/dist-packages/you_get/common.py", line 294, in get_content
    response = request.urlopen(req)
  File "/usr/lib/python3.4/urllib/request.py", line 161, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.4/urllib/request.py", line 464, in open
    response = self._open(req, data)
  File "/usr/lib/python3.4/urllib/request.py", line 482, in _open
    '_open', req)
  File "/usr/lib/python3.4/urllib/request.py", line 442, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 1226, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/python3.4/urllib/request.py", line 1185, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 1] Unknown error>
evolution@evolution:~$ ^C
evolution@evolution:~$

**Comment by linhua55** [comment]
第一个命令的错误是`证书验证失败`，可以提交给you-get `建议增加不检查证书的选项`的issue，
或者向ubuntu系统导入xx-net的证书，注意是导入到ubuntu系统中，不是导入到浏览器中。

**Comment by linhua55** [comment]
第一个命令的错误是`证书验证失败`，可以提交给you-get `建议增加不检查证书的选项`的issue，
或者向ubuntu系统导入xx-net的证书，注意是导入到ubuntu系统中，不是导入到浏览器中。

**Comment by linhua55** [comment]
第一个命令的错误是`证书验证失败`，可以提交给you-get `建议增加不检查证书的选项`的issue，
或者向ubuntu系统导入xx-net的证书，注意是导入到ubuntu系统中，不是导入到浏览器中。

**Comment by evolutionboy** [comment]
@linhua55 您说的很对，这次按你的方法网页下载成功了，之前还以为chromium的证书管理是用的系统的，看chromium中证书有，以为系统中有了。但我这还是出了点倒霉问题，
这次ubuntu15.10 amd64装的KDE笔记本最新版桌面，KDE自带的网络管理图形界面设置什么都失效，
网上找了下命令行导入证书，要么是archlinux的命令，要么是二年前goagent目录的导入方法，和xx-net有差别，您能直接告诉我ubuntu下把证书导入系统的命令吗？万分感谢。

**Comment by linhua55** [comment]
常见的管理网络的图形界面有两个软件：
1、NetworkManager   最常用的
2、wicd
看看NetworkManager是否安装
详细请参考Archwiki，如NetworkManager的Archwiki
关于导入证书到系统中，这个链接可能对你有用
http://askubuntu.com/questions/73287/how-do-i-install-a-root-certificate

**Comment by evolutionboy** [comment]
@linhua55 一点多我就按您的方法操作了，详情如下，太晚了就没回。
您说的其它方法也试了，1、NetworkManager 最常用的
2、wicd，两个都安装了，但只能管有线无线网络，不能设置代理，
我之前这方面也是好的，所说图形界面网络管理失效，是指的代理设置失效。
之前用过一种方法命令行设置过代理，
但证书命令行导入还是无效。问题怎么出的都不明确，只知道换自带桌面环境是好的，换Kde5，xfce4就不能设置代理了。以前kde5好像可以的，可能现在安装的这个KDE版本不是同一个吧。
，，，，，，，，，，，，，，，，，，
打开XX-Net文件夹，找到 data\gae_proxy 目录下的 "CA.crt" 证书，复制到家目录下
cd 
sudo mkdir /usr/share/ca-certificates/extra
sudo cp CA.crt /usr/share/ca-certificates/extra/CA.crt
sudo dpkg-reconfigure ca-certificates
按yes后进入下界面
，，，，，，，，，，，，
软件包设置                                                                                                                       
                                                                                                                                 
  ┌─────────────────────────────────────────────┤ ca-certificates configuration ├─────────────────────────────────────────────┐  
  │ This package installs common CA (Certificate Authority) certificates in /usr/share/ca-certificates. . Please select the   │  
  │ certificate authorities you trust so that their certificates are installed into /etc/ssl/certs. They will be compiled     │  
  │ into a single /etc/ssl/certs/ca-certificates.crt file.                                                                    │  
  │                                                                                                                           │  
  │ Certificates to activate:                                                                                                 │  
  │                                                                                                                           │  
  │    [ ] extra/CA.crt                                                                                                   ↑   │  
  │    [*] mozilla-1024/Entrust.net_Secure_Server_CA.crt                                                                  ▮   │  
  │    [*] mozilla-1024/GTE_CyberTrust_Global_Root.crt                                                                    ▒   │  
  │    [*] mozilla-1024/RSA_Root_Certificate_1.crt                                                                        ▒   │  
  │    [*] mozilla-1024/Thawte_Premium_Server_CA.crt                                                                      ▒   │  
  │    [*] mozilla-1024/Thawte_Server_CA.crt                                                                              ▒   │  
  │    [*] mozilla-1024/ValiCert_Class_1_VA.crt                                                                           ▒   │  
  │    [*] mozilla-1024/ValiCert_Class_2_VA.crt                                                                           ▒   │  
  │    [*] mozilla/ACCVRAIZ1.crt                                                                                          ▒   │  
  │    [*] mozilla/ACEDICOM_Root.crt                                                                                      ▒   │  
  │    [*] mozilla/AC_Raíz_Certicámara_S.A..crt                                                                           ▒   │  
  │    [*] mozilla/Actalis_Authentication_Root_CA.crt                                                                     ▒   │  
  │    [*] mozilla/AddTrust_External_Root.crt                                                                             ↓   │  
  │                                                                                                                           │  
  │                                                                                                                           │  
  │                                                          <确定>    
，，，，，，，，，，，，，，，，，，，
红色光标在    [ ] extra/CA.crt  这个上面时，回车，结果如下：
evolution@evolution:~$ sudo dpkg-reconfigure ca-certificates
正在处理用于 ca-certificates (20150426ubuntu1) 的触发器 ...
Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...

done.
done.
evolution@evolution:~$ 
，，，，，，，，，，，，
证书还是没进去。
，，，，，，，，，

**Comment by oolzpishere** [comment]
@evolutionboy 
sudo dpkg-reconfigure ca-certificates 里按空格为选定，我也按那个步骤加了证书，但是还是连不上

**Comment by jzp820927** [comment]
实在不行，就用火狐吧，火狐的证书的独立的
