### ISSUE TITLE
XX-Net 2.7.3 请问偶尔有红色错误，怎么解决呀

### ISSUE THREAD

**Issue by moerfutin** [XX-net/XX-Net#1797]
-----------问题描述：
请在此描述你遇到的问题，必要时贴出相关的日志信息。
Jan 02 21:48:06 - [DEBUG] ssl_pool.get:202.248.248.237 handshake:203 

Jan 02 21:48:07 - [ERROR] gae_handler except:error(10054, '') http://www.voachinese.com/img/videoOverlay_mmw.gif?v=__7.6.0.0.11 

Jan 02 21:48:07 - [ERROR] Except stack:Traceback (most recent call last): File "E:\program files\MyChrome\XX-Net-2.6.2\gae_proxy\local\gae_handler.py", line 380, in handler wfile.write("HTTP/1.1 %d undefined\r\n" % (response.status, response.reason)) File "E:\program files\MyChrome\XX-Net-2.6.2\python27\1.0\lib\socket.py", line 324, in write self.flush() File "E:\program files\MyChrome\XX-Net-2.6.2\python27\1.0\lib\socket.py", line 303, in flush self._sock.sendall(view[write_offset:write_offset+buffer_size]) File "E:\program files\MyChrome\XX-Net-2.6.2\python27\1.0\lib\socket.py", line 224, in meth return getattr(self._sock,name)(*args) error: [Errno 10054] 

Jan 02 21:48:07 - [WARNING] socket error:error(10054, '') 

Jan 02 21:48:16 - [DEBUG] ssl_pool.get:202.248.248.238 handshake:218 

-----------诊断信息：
sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko
xxnet-version: 2.7.3
python-version: 2.7.9

ipv6-status: 0
gws-ip-num: 229,132
connected-link: 4,50
ip-connect-interval: 10
scan-ip-thread-num: 60
ip-handshake-10: 406
block-stat: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by yeahwu** [comment]
当没看见。
