### ISSUE TITLE
win10 gae 无法启动

### ISSUE THREAD

**Issue by jason-chang** [XX-net/XX-Net#1843]
D:\Program Files (x86)\XX-Net>"D:\Program Files (x86)\XX-Net\python27/1.0/python.exe" "D:\Program Files (x86)\XX-Net\launcher/start.py"
Jan 07 12:04:03 - [INFO] start XX-Net 2.8.9
Jan 07 12:04:03 - [DEBUG] start confirm_xxnet_exit
Jan 07 12:04:04 - [DEBUG] good, xxnet:8087 cleared!
Jan 07 12:04:05 - [DEBUG] good, xxnet:8085 clear!
Jan 07 12:04:05 - [DEBUG] finished confirm_xxnet_exit
Jan 07 12:04:05 - [INFO] detect Win10, enable connect concurent control, interval:40
Jan 07 12:04:05 - [INFO] load ip range file:D:\Program Files (x86)\XX-Net\gae_proxy\local\ip_range.txt
Jan 07 12:04:05 - [ERROR] start module gae_proxy fail:'str' object is not callable
Traceback (most recent call last):
  File "D:\Program Files (x86)\XX-Net\launcher\module_init.py", line 37, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "D:\Program Files (x86)\XX-Net\gae_proxy\start.py", line 14, in <module>
    import local.proxy as client
  File "D:\Program Files (x86)\XX-Net\gae_proxy\local\proxy.py", line 81, in <module>
    import proxy_handler
  File "D:\Program Files (x86)\XX-Net\gae_proxy\local\proxy_handler.py", line 13, in <module>
    from connect_manager import https_manager,forwork_manager
  File "D:\Program Files (x86)\XX-Net\gae_proxy\local\connect_manager.py", line 42, in <module>
    from google_ip import google_ip
  File "D:\Program Files (x86)\XX-Net\gae_proxy\local\google_ip.py", line 28, in <module>
    import check_ip
  File "D:\Program Files (x86)\XX-Net\gae_proxy\local\check_ip.py", line 38, in <module>
    from appids_manager import appid_manager
  File "D:\Program Files (x86)\XX-Net\gae_proxy\local\appids_manager.py", line 10, in <module>
    xlog = getLogger("gae_proxy")
  File "D:\Program Files (x86)\XX-Net\gae_proxy\local\xlog.py", line 56, in getLogger
    return cls(*args, **kwargs)
TypeError: 'str' object is not callable

Jan 07 12:04:05 - [INFO] start gae_proxy time cost 98
Jan 07 12:04:05 - [INFO] begin to start web control
Jan 07 12:04:05 - [INFO] launcher web control started.

**Comment by xxnet** [comment]
​请重新下载2.8.9覆盖

**Comment by jason-chang** [comment]
OK 可以了
