### ISSUE TITLE
前天还好好的，今天就不行了，更新了版本也不行，谁能帮我看一下？谢谢

### ISSUE THREAD

**Issue by go2feel** [XX-net/XX-Net#1845]
D:\GitHub_local\XX-Net>SET PYTHONPATH=

D:\GitHub_local\XX-Net>"D:\GitHub_local\XX-Net\python27/1.0/python.exe" "D:\GitH
ub_local\XX-Net\launcher/start.py"
Jan 07 12:34:04.832 - [INFO] start XX-Net 2.8.9
Jan 07 12:34:04.833 - [DEBUG] start confirm_xxnet_exit
Jan 07 12:34:05.843 - [DEBUG] good, xxnet:8087 cleared!
Jan 07 12:34:06.863 - [DEBUG] good, xxnet:8085 clear!
Jan 07 12:34:06.864 - [DEBUG] finished confirm_xxnet_exit
Jan 07 12:34:06.991 - [DEBUG] network is ok, cost:72 ms
Jan 07 12:34:06.994 - [INFO] SSL use version:TLSv1
Jan 07 12:34:07.365 - [INFO] load ip range file:D:\GitHub_local\XX-Net\gae_proxy
\local\ip_range.txt
Jan 07 12:34:07.391 - [INFO] scan_ip_log roll D:\GitHub_local\XX-Net\data\gae_pr
oxy\scan_ip.log -> D:\GitHub_local\XX-Net\data\gae_proxy\scan_ip.1.log
Jan 07 12:34:07.393 - [ERROR] start module gae_proxy fail:[Error 32] : 'D:\\GitH
ub_local\\XX-Net\\data\\gae_proxy\\scan_ip.log'
Jan 07 12:34:07.395 - [ERROR] Except stack:Traceback (most recent call last):
  File "D:\GitHub_local\XX-Net\launcher\module_init.py", line 37, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['loca
l', 'start'], -1)
  File "D:\GitHub_local\XX-Net\gae_proxy\start.py", line 14, in <module>
    import local.proxy as client
  File "D:\GitHub_local\XX-Net\gae_proxy\local\proxy.py", line 98, in <module>
    import proxy_handler
  File "D:\GitHub_local\XX-Net\gae_proxy\local\proxy_handler.py", line 20, in <m
odule>
    import gae_handler
  File "D:\GitHub_local\XX-Net\gae_proxy\local\gae_handler.py", line 23, in <mod
ule>
    from connect_manager import https_manager
  File "D:\GitHub_local\XX-Net\gae_proxy\local\connect_manager.py", line 43, in
<module>
    from google_ip import google_ip
  File "D:\GitHub_local\XX-Net\gae_proxy\local\google_ip.py", line 22, in <modul
e>
    from scan_ip_log import scan_ip_log
  File "D:\GitHub_local\XX-Net\gae_proxy\local\scan_ip_log.py", line 65, in <mod
ule>
    scan_ip_log = Scan_ip_log()
  File "D:\GitHub_local\XX-Net\gae_proxy\local\scan_ip_log.py", line 16, in __in
it__
    self.open_log()
  File "D:\GitHub_local\XX-Net\gae_proxy\local\scan_ip_log.py", line 32, in open
_log
    self.roll_log()
  File "D:\GitHub_local\XX-Net\gae_proxy\local\scan_ip_log.py", line 43, in roll
_log
    shutil.move(self.log_path, file_name)
  File "D:\GitHub_local\XX-Net\python27\1.0\lib\shutil.py", line 302, in move
    os.unlink(src)
WindowsError: [Error 32] : 'D:\\GitHub_local\\XX-Net\\data\\gae_proxy\\scan_ip.l
og'

Jan 07 12:34:07.408 - [INFO] start gae_proxy time cost 533
Jan 07 12:34:07.409 - [INFO] begin to start web control
Jan 07 12:34:07.412 - [INFO] server 127.0.0.1:8085 started.
Jan 07 12:34:07.414 - [INFO] launcher web control started.
Jan 07 12:34:07.695 - [WARNING] request module:gae_proxy start fail
Jan 07 12:34:07.712 - [WARNING] request module:gae_proxy start fail
Jan 07 12:34:07.712 - [WARNING] request module:gae_proxy start fail
Jan 07 12:34:07.722 - [WARNING] request module:gae_proxy start fail
Jan 07 12:34:07.724 - [WARNING] request module:gae_proxy start fail
Jan 07 12:34:07.734 - [WARNING] request module:gae_proxy start fail
Jan 07 12:34:08.459 - [INFO] get uuid:301649a3-ba56-4532-b941-9e08c4fdd945
Jan 07 12:34:09.461 - [WARNING] check_update fail:URLError(error(10061, ''),)
Jan 07 12:34:09.463 - [INFO] download https://raw.githubusercontent.com/XX-net/X
X-Net/master/README.md to D:\GitHub_local\XX-Net\data\downloads\README.md, retry
:0
Jan 07 12:34:42.406 - [WARNING] request module:gae_proxy start fail
Jan 07 12:34:42.412 - [DEBUG] launcher web_control 127.0.0.1:61106 GET /config?c
md=get_config
Jan 07 12:35:02.412 - [WARNING] request module:gae_proxy start fail
Jan 07 12:35:03.414 - [WARNING] request module:gae_proxy start fail
Jan 07 12:35:04.415 - [WARNING] request module:gae_proxy start fail
Jan 07 12:35:05.419 - [WARNING] request module:gae_proxy start fail
Jan 07 12:35:06.422 - [WARNING] request module:gae_proxy start fail

**Comment by xxnet** [comment]
​ D:\GitHub_local\XX-Net\data\gae_proxy\scan_ip.log 这个文件删除应该就好了。

不过问题出在移动这个文件时失败了，你可以检查这个文件的属性是否只读，还是目录权限有限制

**Comment by go2feel** [comment]
确实是这个原因，非常感谢！
我想可能是我太久没重启了，平常不用了就休眠，可能不知道那个程序把它给占用了。

**Comment by aimilin6688** [comment]
我的也是启动失败，后来重新下载安装好的
