### ISSUE TITLE
作死导致xx-net无法启动

### ISSUE THREAD

**Issue by qq938403611** [XX-net/XX-Net#1866]
昨天看到有个Google Chrome 更新器 于是下载下来试了一下，试用了下生成绿色版chrome，可是看到不能直接更新google遂放弃，之后就发现xx-net无法启动。。。
C:\Windows\system32>"D:\XX-Net\python27/1.0/python.exe" "D:\XX-Net\launcher/start.py"
Jan 08 13:38:12 - [INFO] start XX-Net 2.8.9
Jan 08 13:38:12 - [DEBUG] start confirm_xxnet_exit
Jan 08 13:38:13 - [DEBUG] good, xxnet:8087 cleared!
Jan 08 13:38:14 - [DEBUG] good, xxnet:8085 clear!
Jan 08 13:38:14 - [DEBUG] finished confirm_xxnet_exit
Jan 08 13:38:14 - [ERROR] start module gae_proxy fail:'str' object is not callable
Traceback (most recent call last):
  File "D:\XX-Net\launcher\module_init.py", line 37, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "D:\XX-Net\gae_proxy\start.py", line 14, in <module>
    import local.proxy as client
  File "D:\XX-Net\gae_proxy\local\proxy.py", line 74, in <module>
    from cert_util import CertUtil
  File "D:\XX-Net\gae_proxy\local\cert_util.py", line 36, in <module>
    xlog = getLogger("gae_proxy")
  File "D:\XX-Net\gae_proxy\local\xlog.py", line 56, in getLogger
    return cls(*args, **kwargs)
TypeError: 'str' object is not callable

Jan 08 13:38:14 - [INFO] start gae_proxy time cost 16
Jan 08 13:38:14 - [INFO] begin to start web control
Jan 08 13:38:14 - [INFO] launcher web control started.
Jan 08 13:38:15 - [INFO] get uuid:3a081b07-28aa-45ca-82f3-884540f29887
Jan 08 13:38:16 - [WARNING] check_update fail:URLError(error(10061, ''),)
Jan 08 13:38:16 - [INFO] download https://raw.githubusercontent.com/XX-net/XX-Net/master/README.md to D:\XX-Net\data\downloads\README.md, retry:0

**Comment by xxnet** [comment]
​重新下载2.8.9覆盖

**Comment by qq938403611** [comment]
噗，，难道又是更新出错么。。

**Comment by awpshoot** [comment]
一样的问题，，下载个！！
