### ISSUE TITLE
在学校就好好的，回家就不行了，状态显示不了！是不使用了路由器问题啊？

### ISSUE THREAD

**Issue by YangNull** [XX-net/XX-Net#1899]
状态信息显示了：状态页显示空白, 很可能GAEProxy启动失败, 请按指引查找问题！这是什么回事，搞了半天了！

**Comment by jzp820927** [comment]
是不是下载不完整，重新下载试试

**Comment by LGA1150** [comment]
学校有IPv6，所以……

**Comment by simonasd** [comment]
@YangNull 你的情况好像与IPV6无关，而是启动失败。尝试用start.bat启动，看看报错？

**Comment by YangNull** [comment]
@simonasd
下面是报错的信息，
 D:\XX-Net-2.6.2>SET PYTHONPATH=

D:\XX-Net-2.6.2>"D:\XX-Net-2.6.2\python27/1.0/python.exe" "D:\XX-Net-2.6.2\launcher/start.py"
Jan 12 19:51:03 - [INFO] start XX-Net 2.8.9
Jan 12 19:51:03 - [DEBUG] start confirm_xxnet_exit
Jan 12 19:51:04 - [DEBUG] good, xxnet:8087 cleared!
Jan 12 19:51:05 - [DEBUG] good, xxnet:8085 clear!
Jan 12 19:51:05 - [DEBUG] finished confirm_xxnet_exit
Jan 12 19:51:05 - [ERROR] start module gae_proxy fail:'str' object is not callable
Traceback (most recent call last):
  File "D:\XX-Net-2.6.2\launcher\module_init.py", line 37, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "D:\XX-Net-2.6.2\gae_proxy\start.py", line 14, in <module>
    import local.proxy as client
  File "D:\XX-Net-2.6.2\gae_proxy\local\proxy.py", line 86, in <module>
    from config import config
  File "D:\XX-Net-2.6.2\gae_proxy\local\config.py", line 12, in <module>
    xlog = getLogger("gae_proxy")
  File "D:\XX-Net-2.6.2\gae_proxy\local\xlog.py", line 56, in getLogger
    return cls(*args, **kwargs)
TypeError: 'str' object is not callable

Jan 12 19:51:05 - [INFO] start gae_proxy time cost 19
Jan 12 19:51:05 - [INFO] begin to start web control
Jan 12 19:51:05 - [INFO] launcher web control started.
Jan 12 19:51:06 - [INFO] get uuid:67559cf5-8591-455a-bc2a-bb81bedc5a12
Jan 12 19:51:07 - [WARNING] check_update fail:URLError(error(10061, ''),)
Jan 12 19:51:07 - [INFO] download https://raw.githubusercontent.com/XX-net/XX-Net/master/README.md to D:\XX-Net-2.6.2\data\downloads\README.md, retry:0
Jan 12 19:51:22 - [DEBUG] launcher web_control 127.0.0.1:49479 GET /config?cmd=get_config
Jan 12 19:51:23 - [WARNING] request module:gae_proxy start fail
Jan 12 19:51:23 - [WARNING] request module:gae_proxy start fail
Jan 12 19:51:26 - [WARNING] request module:gae_proxy start fail
Jan 12 19:51:26 - [WARNING] request module:gae_proxy start fail
Jan 12 19:51:28 - [WARNING] request module:gae_proxy start fail
Jan 12 19:51:28 - [WARNING] request module:gae_proxy start fail
Jan 12 19:51:29 - [WARNING] request module:gae_proxy start fail
Jan 12 19:51:30 - [WARNING] request module:gae_proxy start fail
还有火狐firebug里看到
GET http://127.0.0.1:8085/module/gae_proxy/control/status 404 Not Found 3ms

**Comment by YangNull** [comment]
对了各位，我现在是属于局域网的环境，会不会是这个原因呢？

**Comment by xxnet** [comment]
​估计是升级失败了，你重新下载2.8.9覆盖

**Comment by YangNull** [comment]
@xxnet 谢谢，成功解决了问题了！但火狐还是上不到去，还是显示不受信任的连接！估计是证书问题了！
