### ISSUE TITLE
部署服务端appid问题

### ISSUE THREAD

**Issue by zhouytforever** [XX-net/XX-Net#1919]
输入它给生成的appid、google账号、弹出的16位密码后点击“保存”按钮，控制台报错：

------------------------------------------------红色字体（error部分）---------------------------------------
 1月 14 21:08:10.8 - [ERROR] handler:KeyError('appid',)
 1月 14 21:08:10.8 - [ERROR] Except stack:Traceback (most recent call last):
  File "/home/program/XX-Net-2.8.9/python27/1.0/lib/noarch/simple_http_server.py", line 128, in handle_one_request
    self.do_POST()
  File "/home/program/XX-Net-2.8.9/launcher/web_control.py", line 86, in do_POST
    controler.do_POST()
  File "/home/program/XX-Net-2.8.9/gae_proxy/local/web_control.py", line 301, in do_POST
    return self.req_deploy_handler()
  File "/home/program/XX-Net-2.8.9/gae_proxy/local/web_control.py", line 518, in req_deploy_handler
    appid = self.postvars['appid'][0]
KeyError: 'appid'
------------------------------------------------红色字体（error部分）---------------------------------------

------------------------------------------------绿色字体（debug部分）---------------------------------------
 1月 14 21:08:11.0 - [INFO] GAE CONNECT console.developers.google.com:443 
 1月 14 21:08:11.1 - [DEBUG] GAE CONNECT GET https://console.developers.google.com/m/operations?maxResults=100
 1月 14 21:08:11.1 - [DEBUG] ssl_pool.get:202.248.248.222 handshake:168
 1月 14 21:08:11.4 - [INFO] GAE 28|202.248.248.222|91845 t:303 s:2404 hs:168 Spd:7485602 200 https://console.developers.google.com/m/operations?maxResults=100
 1月 14 21:08:14.9 - [DEBUG] 202.248.248.213 close:HEAD
 1月 14 21:08:14.9 - [DEBUG] 202.248.248.221 close:HEAD
 1月 14 21:08:14.9 - [DEBUG] ssl_closed 202.248.248.213
 1月 14 21:08:14.9 - [DEBUG] ssl_closed 202.248.248.221
 1月 14 21:08:15.9 - [DEBUG] 175.28.1.153 close:HEAD
 1月 14 21:08:15.9 - [DEBUG] ssl_closed 175.28.1.153
 1月 14 21:08:20.9 - [DEBUG] 110.163.42.10 close:HEAD
 1月 14 21:08:20.9 - [DEBUG] ssl_closed 110.163.42.10
 1月 14 21:08:20.9 - [DEBUG] 202.248.151.45 close:HEAD
 1月 14 21:08:20.9 - [DEBUG] ssl_closed 202.248.151.45
 1月 14 21:08:20.9 - [DEBUG] 203.233.126.197 close:HEAD
 1月 14 21:08:20.9 - [DEBUG] ssl_closed 203.233.126.197
 1月 14 21:08:20.9 - [DEBUG] 58.69.77.86 close:HEAD
 1月 14 21:08:20.9 - [DEBUG] ssl_closed 58.69.77.86
 1月 14 21:08:21.2 - [DEBUG] get ip:202.248.248.213 t:160
 1月 14 21:08:21.3 - [DEBUG] get ip:202.248.248.221 t:181
 1月 14 21:08:21.4 - [DEBUG] get ip:110.163.42.10 t:265
 1月 14 21:08:21.5 - [DEBUG] create_ssl update ip:202.248.248.213 time:165
 1月 14 21:08:21.5 - [DEBUG] get ip:175.28.1.153 t:294
 1月 14 21:08:21.6 - [DEBUG] create_ssl update ip:202.248.248.221 time:165
 1月 14 21:08:21.6 - [DEBUG] get ip:202.248.151.45 t:314
 1月 14 21:08:21.8 - [DEBUG] create_ssl update ip:110.163.42.10 time:271
 1月 14 21:08:21.9 - [DEBUG] 63.117.14.36 close:HEAD
 1月 14 21:08:21.9 - [DEBUG] ssl_closed 63.117.14.36
 1月 14 21:08:22.0 - [DEBUG] create_ssl update ip:175.28.1.153 time:314
 1月 14 21:08:22.1 - [DEBUG] create_ssl update ip:202.248.151.45 time:342
------------------------------------------------绿色字体（debug部分）---------------------------------------

------------------------------------------------红色字体（error部分）---------------------------------------
WARNING:root:fetch:timeout('timed out',)
 1月 14 21:08:30.8 - [ERROR] handler:TypeError('%d format: a number is required, not str',)
 1月 14 21:08:30.8 - [ERROR] Except stack:Traceback (most recent call last):
  File "/home/program/XX-Net-2.8.9/python27/1.0/lib/noarch/simple_http_server.py", line 128, in handle_one_request
    self.do_POST()
  File "/home/program/XX-Net-2.8.9/gae_proxy/local/proxy_handler.py", line 101, in do_METHOD
    return self.forward_local()
  File "/home/program/XX-Net-2.8.9/gae_proxy/local/proxy_handler.py", line 70, in forward_local
    out_list.append("HTTP/1.1 %d\r\n" % status)
TypeError: %d format: a number is required, not str
------------------------------------------------红色字体（error部分）---------------------------------------

**Comment by zhouytforever** [comment]
resolved

**Comment by zhouytforever** [comment]
ok

I've resolved it by updating the deploying program in Firefox.

And , thanks!!!
