### ISSUE TITLE
XX-Net启动不起来，附日志信息，求诊断，谢谢！

### ISSUE THREAD

**Issue by boern** [XX-net/XX-Net#1941]
D:\XX-Net-2.8.9>SET PYTHONPATH=

D:\XX-Net-2.8.9>"D:\XX-Net-2.8.9\python27/1.0/python.exe" "D:\XX-Net-2.8.9\launcher/start.py"
Jan 18 10:46:29.782 - [INFO] start XX-Net 2.8.9
Jan 18 10:46:29.783 - [DEBUG] start confirm_xxnet_exit
Jan 18 10:46:29.785 - [DEBUG] good, xxnet:8087 cleared!
Jan 18 10:46:29.786 - [DEBUG] good, xxnet:8085 clear!
Jan 18 10:46:29.787 - [DEBUG] finished confirm_xxnet_exit
Jan 18 10:46:30.026 - [WARNING] network fail:gaierror(11001, 'getaddrinfo failed')
Jan 18 10:46:30.029 - [INFO] SSL use version:TLSv1
Jan 18 10:46:30.650 - [INFO] load ip range file:D:\XX-Net-2.8.9\gae_proxy\local\ip_range.txt
Jan 18 10:46:30.678 - [INFO] detect Win10, enable connect concurent control, interval:40
Jan 18 10:46:30.680 - [INFO] load google ip_list num:0, gws num:0
Jan 18 10:46:30.706 - [DEBUG] ## GAEProxy set keep_running: True
Jan 18 10:46:30.707 - [INFO] ------------------------------------------------------
Jan 18 10:46:30.707 - [INFO] Python Version     : 2.7.9
Jan 18 10:46:30.708 - [INFO] OS                 : Version:10-0; Build:10240; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
Jan 18 10:46:30.708 - [INFO] Listen Address     : 127.0.0.1:8087
Jan 18 10:46:30.709 - [INFO] GAE APPID          : xxnet-1|xxnet-2|xxnet-3|xxnet-4|xxnet-5|xxnet-6|xxnet-7|xxnet-8|xxnet-9|xxnet-10|xxnet-11|xxnet-12|xxnet-13|xxnet-14|xxnet-15|xxnet-16|xxnet-17|xxnet-18|xxnet-19|xxnet-20|xxnet-21|xxnet-22|xxnet-23|xxnet-24|xxnet-25|xxnet-26|xxnet-27|xxnet-28|xxnet-29|xxnet-30|xxnet-31|xxnet-32|xxnet-33|xxnet-34|xxnet-35|xxnet-36|xxnet-37|xxnet-38|xxnet-39|xxnet-40|xxnet-41|xxnet-42|xxnet-43|xxnet-44|xxnet-45|xxnet-46|xxnet-47|xxnet-48|xxnet-49|xxnet-50|xxnet-51|xxnet-52|xxnet-53|xxnet-54|xxnet-55|xxnet-56|xxnet-57|xxnet-58|xxnet-59|xxnet-60|xxnet-61|xxnet-62|xxnet-63|xxnet-64|xxnet-65|xxnet-66|xxnet-67|xxnet-68|xxnet-69|xxnet-70|xxnet-71|xxnet-72|xxnet-72|xxnet-73|xxnet-74|xxnet-75|xxnet-76|xxnet-77|xxnet-78|xxnet-79|xxnet-80|xxnet-81|xxnet-82|xxnet-83|xxnet-84|xxnet-85|xxnet-86|xxnet-87|xxnet-88|xxnet-89|xxnet-90|xxnet-91|xxnet-92|xxnet-93|xxnet-94|xxnet-95|xxnet-96|xxnet-97|xxnet-98|xxnet-99|xxnet-100|xxnet-101|xxnet-102|xxnet-103|xxnet-104|xxnet-105|xxnet-106|xxnet-107|xxnet-108|xxnet-109|xxnet-110|xxnet-111|xxnet-112|xxnet-113|xxnet-114|xxnet-115|xxnet-116|xxnet-117|xxnet-118|xxnet-119|xxnet-120|xxnet-121|xxnet-122|xxnet-123|xxnet-124|xxnet-125|xxnet-126|xxnet-127|xxnet-128|xxnet-129|xxnet-130|xxnet-131|xxnet-132|xxnet-133|xxnet-134|xxnet-135|xxnet-136|xxnet-137|xxnet-138|xxnet-139|xxnet-140|xxnet-141|xxnet-142|xxnet-143|xxnet-144|xxnet-145|xxnet-146|xxnet-147|xxnet-148|xxnet-149|xxnet-150|xxnet-151|xxnet-152|xxnet-153|xxnet-154|xxnet-155|xxnet-156|xxnet-157|xxnet-158|xxnet-159
Jan 18 10:46:30.711 - [INFO] Pac Server         : http://127.0.0.1:8086/proxy.pac
Jan 18 10:46:30.712 - [INFO] ------------------------------------------------------
Exception in thread Thread-54:
Traceback (most recent call last):
  File "D:\XX-Net-2.8.9\python27\1.0\lib\threading.py", line 810, in __bootstrap_inner
    self.run()
  File "D:\XX-Net-2.8.9\python27\1.0\lib\threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "D:\XX-Net-2.8.9\gae_proxy\start.py", line 19, in main
    client.main()
  File "D:\XX-Net-2.8.9\gae_proxy\local\proxy.py", line 239, in main
    proxy_daemon = simple_http_server.HTTPServer((config.LISTEN_IP, config.LISTEN_PORT), proxy_handler.GAEProxyHandler)
  File "D:\XX-Net-2.8.9\python27\1.0\lib\noarch\simple_http_server.py", line 255, in __init__
    self.init_socket()
  File "D:\XX-Net-2.8.9\python27\1.0\lib\noarch\simple_http_server.py", line 261, in init_socket
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
  File "D:\XX-Net-2.8.9\python27\1.0\lib\socket.py", line 187, in __init__
    _sock = _realsocket(family, type, proto)
error: [Errno 10106]

**Comment by xxnet** [comment]
​本地网络有问题，看看是不是杀毒、安全软件导致
