### ISSUE TITLE
CentOS启动失败，报错

### ISSUE THREAD

**Issue by sagecrow** [XX-net/XX-Net#1949]
CentOS release 6.5 (Final)，日志见下。
[root@vpn XX-Net-2.8.9]# start.sh
-bash: start.sh: command not found
[root@vpn XX-Net-2.8.9]# ./start.sh
Jan 20 00:24:08.950 - [INFO] start XX-Net 2.8.9
Jan 20 00:24:08.950 - [DEBUG] start confirm_xxnet_exit
Jan 20 00:24:08.954 - [DEBUG] good, xxnet:8087 cleared!
Jan 20 00:24:08.955 - [DEBUG] good, xxnet:8085 clear!
Jan 20 00:24:08.956 - [DEBUG] finished confirm_xxnet_exit
Jan 20 00:24:09.005 - [ERROR] start module gae_proxy fail:invalid syntax (socks.py, line 213)
Jan 20 00:24:09.007 - [ERROR] Except stack:Traceback (most recent call last):
  File "/root/XX-Net-2.8.9/launcher/module_init.py", line 37, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "/root/XX-Net-2.8.9/gae_proxy/start.py", line 14, in <module>
    import local.proxy as client
  File "/root/XX-Net-2.8.9/gae_proxy/local/proxy.py", line 98, in <module>
    import proxy_handler
  File "/root/XX-Net-2.8.9/gae_proxy/local/proxy_handler.py", line 20, in <module>
    import gae_handler
  File "/root/XX-Net-2.8.9/gae_proxy/local/gae_handler.py", line 23, in <module>
    from connect_manager import https_manager
  File "/root/XX-Net-2.8.9/gae_proxy/local/connect_manager.py", line 14, in <module>
    import socks
  File "/root/XX-Net-2.8.9/python27/1.0/lib/noarch/socks.py", line 213
    if type not in {socket.SOCK_STREAM, socket.SOCK_DGRAM}:
                                      ^
SyntaxError: invalid syntax

Jan 20 00:24:09.008 - [INFO] start gae_proxy time cost 51
Jan 20 00:24:09.008 - [INFO] begin to start web control
Jan 20 00:24:09.008 - [INFO] server 0.0.0.0:8085 started.
Jan 20 00:24:09.010 - [INFO] launcher web control started.
Jan 20 00:24:10.012 - [INFO] get uuid:d1caa8d6-e84d-46cd-8442-d54ee41dda52
Jan 20 00:24:10.044 - [WARNING] check_update fail:URLError(error(111, 'Connection refused'),)
Jan 20 00:24:10.044 - [INFO] download https://raw.githubusercontent.com/XX-net/XX-Net/master/README.md to /root/XX-Net-2.8.9/data/downloads/README.md, retry:0

**Comment by xxnet** [comment]
python --version

​看看python 是哪个版本

**Comment by sagecrow** [comment]
2.6.6的版本，centos里面最高是这个版本

**Comment by sagecrow** [comment]
在windows2003 sp2上也有问题，但是在我本机笔记本win10上面是好的。
Jan 19 18:43:27.000 - [INFO] start XX-Net get_version_fail
Jan 19 18:43:27.000 - [DEBUG] start confirm_xxnet_exit
Jan 19 18:43:27.984 - [DEBUG] good, xxnet:8087 cleared!
Jan 19 18:43:28.984 - [DEBUG] good, xxnet:8085 clear!
Jan 19 18:43:28.984 - [DEBUG] finished confirm_xxnet_exit
Jan 19 18:43:29.000 - [ERROR] start module gae_proxy fail:DLL load failed: 由于应用程序配置不正确，应用程序未能启动。重新安装应用程序可能会纠正这个问题。
Jan 19 18:43:29.015 - [ERROR] Except stack:Traceback (most recent call last):
  File "C:\firefox-xx-master\launcher\module_init.py", line 37, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "C:\firefox-xx-master\gae_proxy\start.py", line 14, in <module>
    import local.proxy as client
  File "C:\firefox-xx-master\gae_proxy\local\proxy.py", line 95, in <module>
    from cert_util import CertUtil
  File "C:\firefox-xx-master\gae_proxy\local\cert_util.py", line 38, in <module>
    import OpenSSL
  File "C:\firefox-xx-master\python27\1.0\lib\win32\OpenSSL\__init__.py", line 26, in <module>
    from OpenSSL import crypto, rand, SSL
ImportError: DLL load failed: 由于应用程序配置不正确，应用程序未能启动。重新安装应用程序可能会纠正这个问题。

Jan 19 18:43:29.015 - [INFO] start gae_proxy time cost 31
Jan 19 18:43:29.015 - [INFO] begin to start web control
Jan 19 18:43:29.015 - [INFO] launcher web control started.

**Comment by xxnet** [comment]
​"/root/XX-Net-289/python27/10/lib/noarch/sockspy", line 213 改成：
if type not in (socketSOCK_STREAM, socketSOCK_DGRAM):

在CentOS下， {} 改成 ()试试。

**Comment by sagecrow** [comment]
还是不行，报错日志和前面一样，没变化。
windows2003下我下载pythons的msi安装包安装后可以正常运行了

**Comment by kingjia1989** [comment]
请问楼主解决了吗？

**Comment by jzp820927** [comment]
CentOS 的软件都挺久，问题蛮多，建议用 ubuntu
