### ISSUE TITLE
GAEProxy状态信息   尚未建立连接

### ISSUE THREAD

**Issue by AgoniNemo** [XX-net/XX-Net#1958]
XX-Net Status：

sys-platform: x86_64, Darwin-15.0.0-x86_64-i386-64bit
os-system: Darwin
os-version: Darwin Kernel Version 15.0.0: Sat Sep 19 15:53:46 PDT 2015; root:xnu-3247.10.11~1/RELEASE_X86_64
os-release: 15.0.0
os-detail: Release:10.11.1; Version:('', '', '') Machine:x86_64
architecture: 64bit,
browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:43.0) Gecko/20100101 Firefox/43.0
xxnet-version: 2.8.9
python-version: 2.7.10

ipv6-status: 0
gws-ip-num: 3000 / 1512
network-status: OK
connected-link: 0 / 0
scan-ip-thread-num: 36
ip-quality: 220
block-stat: Connect Blocked, 692645035 seconds to wait.
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by AgoniNemo** [comment]
Jan 20 15:01:11.397 - [INFO] Exiting gae_proxy module...
Exception in thread Thread-4614:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/gmcc/Documents/XX-Net-2.5.5/python27/1.0/lib/noarch/simple_http_server.py", line 283, in serve_forever
    r, w, e = select.select(self.sockets, [], [], 1)
error: (9, 'Bad file descriptor')

Exception in thread Thread-4615:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/gmcc/Documents/XX-Net-2.5.5/python27/1.0/lib/noarch/simple_http_server.py", line 283, in serve_forever
    r, w, e = select.select(self.sockets, [], [], 1)
error: (9, 'Bad file descriptor')

Jan 20 15:01:11.413 - [DEBUG] ## GAEProxy set keep_running: False
Jan 20 15:01:11.442 - [INFO] module gae_proxy stopped
Jan 20 15:01:11.444 - [DEBUG] ## GAEProxy set keep_running: True
Jan 20 15:01:11.445 - [INFO] ------------------------------------------------------
Jan 20 15:01:11.445 - [INFO] Python Version     : 2.7.10
Jan 20 15:01:11.445 - [INFO] OS                 : Release:10.11.1; Version:('', '', '') Machine:x86_64
Jan 20 15:01:11.445 - [INFO] Listen Address     : 127.0.0.1:8087
Jan 20 15:01:11.445 - [INFO] GAE APPID          : celtic-house-105605|my-project-two-1090|nemoowall
Jan 20 15:01:11.445 - [INFO] Pac Server         : http://127.0.0.1:8086/proxy.pac
Jan 20 15:01:11.445 - [INFO] ------------------------------------------------------
Jan 20 15:01:11.523 - [INFO] GoAgent CA exist
Jan 20 15:01:11.523 - [INFO] server 127.0.0.1:8087 started.
Jan 20 15:01:11.524 - [INFO] server 127.0.0.1:8086 started.
Jan 20 15:01:11.543 - [INFO] module gae_proxy started
Jan 20 15:01:53.023 - [INFO] scan_ip add ip:84.235.77.18 time:1166
Jan 20 15:01:53.030 - [INFO] remove_slowest_ip:74.125.153.143 handshake_time:1783, fails:0
Jan 20 15:01:56.980 - [INFO] GAE CONNECT clients4.google.com:443 
Jan 20 15:01:56.986 - [DEBUG] GAE CONNECT POST https://clients4.google.com/chrome-sync/experimentstatus
Jan 20 15:02:11.988 - [DEBUG] create ssl timeout fail.
Jan 20 15:02:11.988 - [DEBUG] create_ssl_connection fail
Jan 20 15:02:26.732 - [DEBUG] create ssl timeout fail.
Jan 20 15:02:26.732 - [DEBUG] create_ssl_connection fail
Jan 20 15:02:26.752 - [DEBUG] create ssl timeout fail.
Jan 20 15:02:26.752 - [DEBUG] create_ssl_connection fail
Jan 20 15:02:26.994 - [DEBUG] create ssl timeout fail.
Jan 20 15:02:26.994 - [DEBUG] create_ssl_connection fail
Jan 20 15:02:41.738 - [DEBUG] create ssl timeout fail.
Jan 20 15:02:41.738 - [DEBUG] create_ssl_connection fail
Jan 20 15:02:41.753 - [DEBUG] create ssl timeout fail.
Jan 20 15:02:41.760 - [DEBUG] create_ssl_connection fail
Jan 20 15:02:42.004 - [DEBUG] create ssl timeout fail.
Jan 20 15:02:42.004 - [DEBUG] create_ssl_connection fail
Jan 20 15:02:42.012 - [DEBUG] GAE_Exception 2 'try max times'
Jan 20 15:02:42.012 - [WARNING] gae_exception:GAE_Exception() https://clients4.google.com/chrome-sync/experimentstatus
Jan 20 15:02:56.742 - [DEBUG] create ssl timeout fail.
Jan 20 15:02:56.742 - [DEBUG] create_ssl_connection fail
Jan 20 15:02:56.742 - [DEBUG] GAE_Exception 2 'try max times'
Jan 20 15:02:56.742 - [WARNING] gae_exception:GAE_Exception() http://clients1.google.com/ocsp
Jan 20 15:02:56.765 - [DEBUG] create ssl timeout fail.
Jan 20 15:02:56.765 - [DEBUG] create_ssl_connection fail
Jan 20 15:02:56.765 - [DEBUG] GAE_Exception 2 'try max times'
Jan 20 15:02:56.765 - [WARNING] gae_exception:GAE_Exception() http://clients1.google.com/ocsp

**Comment by AgoniNemo** [comment]
早上还用得好好的，下午就不行了

**Comment by simonasd** [comment]
>block-stat: Connect Blocked, 692645035 seconds to wait.

检测到了屏蔽状态。可是这个等待时间有点奇怪。呼叫@xxnet

**Comment by xxnet** [comment]
File "/Users/gmcc/Documents/XX-Net-2.5.5/python27/1.0/lib/noarch/simple_http_server.py",
line 283, in serve_forever
r, w, e = select.select(self.sockets, [], [], 1)
error: (9, 'Bad file descriptor')

​日志看，似乎是网络受限了

有没有睡眠之类的？比如合上笔记本重新打开之类的？
导致时间计算错乱的可能？
