### ISSUE TITLE
状态页显示空白, 很可能GAEProxy启动失败, 请按指引查找问题原因

### ISSUE THREAD

**Issue by wang3317198** [XX-net/XX-Net#2006]
request module:gae-proxy start fail
前几天使用都正常，今天突然不行了。

**Comment by xxnet** [comment]
先重新下载一个版本看看，不行的话，
​把一开始的日志贴出来看看

**Comment by jimzzj050** [comment]
我的也是显示状态页显示空白
D:\应用\翻墙软件\XX-Net-2.7.3>SET PYTHONPATH=

D:\应用\翻墙软件\XX-Net-2.7.3>"D:\应用\翻墙软件\XX-Net-2.7.3\python27/1.0/python.exe" "D:\应用\翻墙软件\XX-Net-2.7.3\launcher/start.py"
Jan 30 22:25:09 - [INFO] start XX-Net 2.8.9
Jan 30 22:25:09 - [DEBUG] start confirm_xxnet_exit
Jan 30 22:25:10 - [DEBUG] good, xxnet:8087 cleared!
Jan 30 22:25:10 - [DEBUG] <0>: try to terminate xxnet:8085
Jan 30 22:25:12 - [DEBUG] good, xxnet:8085 clear!
Jan 30 22:25:12 - [DEBUG] finished confirm_xxnet_exit
Jan 30 22:25:12 - [ERROR] start module gae_proxy fail:'str' object is not callable
Traceback (most recent call last):
  File "D:\应用\翻墙软件\XX-Net-2.7.3\launcher\module_init.py", line 37, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "D:\应用\翻墙软件\XX-Net-2.7.3\gae_proxy\start.py", line 14, in <module>
    import local.proxy as client
  File "D:\应用\翻墙软件\XX-Net-2.7.3\gae_proxy\local\proxy.py", line 74, in <module>
    from cert_util import CertUtil
  File "D:\应用\翻墙软件\XX-Net-2.7.3\gae_proxy\local\cert_util.py", line 36, in <module>
    xlog = getLogger("gae_proxy")
  File "D:\应用\翻墙软件\XX-Net-2.7.3\gae_proxy\local\xlog.py", line 56, in getLogger
    return cls(*args, **kwargs)
TypeError: 'str' object is not callable

Jan 30 22:25:12 - [INFO] start gae_proxy time cost 17
Jan 30 22:25:12 - [INFO] begin to start web control
Jan 30 22:25:12 - [INFO] launcher web control started.
Jan 30 22:25:12 - [WARNING] request module:gae_proxy start fail
Jan 30 22:25:12 - [WARNING] request module:gae_proxy start fail
Jan 30 22:25:13 - [WARNING] request module:gae_proxy start fail
Jan 30 22:25:13 - [INFO] get uuid:9981fe3a-3a69-41ea-8b62-2519521e6e36
Jan 30 22:25:13 - [WARNING] request module:gae_proxy start fail
Jan 30 22:25:14 - [WARNING] request module:gae_proxy start fail
Jan 30 22:25:14 - [WARNING] check_update fail:URLError(error(10061, ''),)
Jan 30 22:25:14 - [INFO] download https://raw.githubusercontent.com/XX-net/XX-Net/master/README.md to D:\应用\翻墙软件\XX-Net-2.7.3\data\downloads\README.md, retry:0
Jan 30 22:25:14 - [WARNING] request module:gae_proxy start fail
Jan 30 22:25:15 - [WARNING] request module:gae_proxy start fail
Jan 30 22:25:15 - [WARNING] request module:gae_proxy start fail
Jan 30 22:25:16 - [WARNING] request module:gae_proxy start fail
Jan 30 22:25:16 - [WARNING] request module:gae_proxy start fail
