### ISSUE TITLE
WIN10下打开就闪退，麻烦看一下，谢谢您

### ISSUE THREAD

**Issue by dabney777** [XX-net/XX-Net#2013]
整了一上午，一头雾水。
直接点start的快捷方式会闪退，用管理权限运行是找不到文件‘c:\Windows\system32\start.vbs'，请确定文件名正确后重试。
管理员权限运行start.bat,也是运行不了，下面是内容：
C:\Windows\system32>SET PYTHONPATH=

C:\Windows\system32>"C:\Users\Dabne\Desktop\XX-Net-2.8.9\python27/1.0/python.exe" "C:\Users\Dabne\Desktop\XX-Net-2.8.9\launcher/start.py"
Traceback (most recent call last):
  File "C:\Users\Dabne\Desktop\XX-Net-2.8.9\launcher/start.py", line 60, in <module>
    from win_tray import sys_tray
  File "C:\Users\Dabne\Desktop\XX-Net-2.8.9\launcher\win_tray.py", line 22, in <module>
    import module_init
  File "C:\Users\Dabne\Desktop\XX-Net-2.8.9\launcher\module_init.py", line 6, in <module>
    import config
  File "C:\Users\Dabne\Desktop\XX-Net-2.8.9\launcher\config.py", line 5, in <module>
    from distutils.version import LooseVersion
ImportError: No module named distutils.version

C:\Windows\system32>pause
请按任意键继续. . .
能帮忙解答一下吗，谢谢你了！

**Comment by dabney777** [comment]
各位用WIN10的时候没有遇到这个问题吗？我的是正版系统呀

**Comment by yeahwu** [comment]
这个问题俺在别的电脑上也遇到过，
好像firefox-xx不会，你试试

**Comment by imyan** [comment]
我就是win10家庭版的，一切正常，你整个文件夹是放在系统盘？试试移到其他地方试试

**Comment by andytree** [comment]
解决了吗？？我也遇到了这个问题。。好恼火！

**Comment by jzp820927** [comment]
win 的问题就是多，不行就用 xxmini

**Comment by andytree** [comment]
我解决了，其实是因为使用快压解压，使用7.ZIP解压出来使用就OK。。
