### ISSUE TITLE
求助 不能全部上传appid

### ISSUE THREAD

**Issue by ncmon** [XX-net/XX-Net#2014]
部署服务端的时候25个APPID只上传了其中8个然后就卡主不动了试了好几次都这样，有个还显示下面的文字 请问是怎么回事啊 
Jan 28 13:03:15 - ERROR:root:An unexpected error occurred. Aborting.
Traceback (most recent call last):
File "E:\Program Files\XX-Net-2.8.9\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 2114, in DoUpload
app_summary = self.Commit()
File "E:\Program Files\XX-Net-2.8.9\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 1905, in Commit
app_summary = self.Deploy()
File "E:\Program Files\XX-Net-2.8.9\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 1957, in Deploy
result = self.Send('/api/appversion/deploy')
File "E:\Program Files\XX-Net-2.8.9\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 1698, in Send
return self.rpcserver.Send(url, payload=payload, **self.params)
File "E:\Program Files\XX-Net-2.8.9\gae_proxy\server\lib\google\appengine\tools\appengine_rpc.py", line 368, in Send
f = self.opener.open(req)
File "E:\Program Files\XX-Net-2.8.9\python27\1.0\lib\urllib2.py", line 404, in open
response = self._open(req, data)
File "E:\Program Files\XX-Net-2.8.9\python27\1.0\lib\urllib2.py", line 422, in _open
'_open', req)
File "E:\Program Files\XX-Net-2.8.9\python27\1.0\lib\urllib2.py", line 382, in _call_chain
result = func(*args)
File "E:\Program Files\XX-Net-2.8.9\python27\1.0\lib\urllib2.py", line 1222, in https_open
return self.do_open(httplib.HTTPSConnection, req)
File "E:\Program Files\XX-Net-2.8.9\python27\1.0\lib\urllib2.py", line 1187, in do_open
r = h.getresponse(buffering=True)
File "E:\Program Files\XX-Net-2.8.9\python27\1.0\lib\httplib.py", line 1045, in getresponse
response.begin()
File "E:\Program Files\XX-Net-2.8.9\python27\1.0\lib\httplib.py", line 409, in begin
version, status, reason = self._read_status()
File "E:\Program Files\XX-Net-2.8.9\python27\1.0\lib\httplib.py", line 365, in _read_status
line = self.fp.readline(_MAXLINE + 1)
File "E:\Program Files\XX-Net-2.8.9\python27\1.0\lib\socket.py", line 476, in readline
data = self._sock.recv(self._rbufsize)
File "E:\Program Files\XX-Net-2.8.9\python27\1.0\lib\ssl.py", line 241, in recv
return self.read(buflen)
File "E:\Program Files\XX-Net-2.8.9\python27\1.0\lib\ssl.py", line 160, in read
return self._sslobj.read(len)
SSLError: The read operation timed out
Jan 28 13:03:15 - Rolling back the update.
Jan 28 13:03:15 - upload fail: The read operation timed out

**Comment by caofengzi** [comment]
剩下的appid你可以試試每次上傳2-4個，看看是否能夠成功部署。

**Comment by ncmon** [comment]
我觉得好像是XX-NET的问题  我用goagent已经全部成功上传了
