### ISSUE TITLE
状态页显示空白 很可能GAEProxy启动失败

### ISSUE THREAD

**Issue by jimzzj050** [XX-net/XX-Net#2054]
D:\应用\翻墙软件\XX-Net-2.7.3>SET PYTHONPATH=

D:\应用\翻墙软件\XX-Net-2.7.3>"D:\应用\翻墙软件\XX-Net-2.7.3\python27/1.0/python.exe" "D:\应用\翻墙软件\XX-Net-2.7.3\launcher/start.py"
Feb 03 23:39:35 - [INFO] start XX-Net 2.8.9
Feb 03 23:39:35 - [DEBUG] start confirm_xxnet_exit
Feb 03 23:39:36 - [DEBUG] good, xxnet:8087 cleared!
Feb 03 23:39:36 - [DEBUG] <0>: try to terminate xxnet:8085
Feb 03 23:39:38 - [DEBUG] good, xxnet:8085 clear!
Feb 03 23:39:38 - [DEBUG] finished confirm_xxnet_exit
Feb 03 23:39:38 - [ERROR] start module gae_proxy fail:'str' object is not callable
Traceback (most recent call last):
  File "D:\应用\翻墙软件\XX-Net-2.7.3\launcher\module_init.py", line 37, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "D:\应用\翻墙软件\XX-Net-2.7.3\gae_proxy\start.py", line 14, in <module>
    import local.proxy as client
  File "D:\应用\翻墙软件\XX-Net-2.7.3\gae_proxy\local\proxy.py", line 74, in <module>
    from cert_util import CertUtil
  File "D:\应用\翻墙软件\XX-Net-2.7.3\gae_proxy\local\cert_util.py", line 36, in <module>
    xlog = getLogger("gae_proxy")
  File "D:\应用\翻墙软件\XX-Net-2.7.3\gae_proxy\local\xlog.py", line 56, in getLogger
    return cls(*args, **kwargs)
TypeError: 'str' object is not callable

Feb 03 23:39:38 - [INFO] start gae_proxy time cost 14
Feb 03 23:39:38 - [INFO] begin to start web control
Feb 03 23:39:38 - [INFO] launcher web control started.
Feb 03 23:39:39 - [WARNING] request module:gae_proxy start fail
Feb 03 23:39:39 - [WARNING] request module:gae_proxy start fail
Feb 03 23:39:39 - [WARNING] request module:gae_proxy start fail
Feb 03 23:39:40 - [INFO] get uuid:9981fe3a-3a69-41ea-8b62-2519521e6e36
Feb 03 23:39:40 - [WARNING] request module:gae_proxy start fail
Feb 03 23:39:40 - [WARNING] request module:gae_proxy start fail
Feb 03 23:39:41 - [WARNING] check_update fail:URLError(error(10061, ''),)
Feb 03 23:39:41 - [INFO] download https://raw.githubusercontent.com/XX-net/XX-Net/master/README.md to D:\应用\翻墙软件\XX-Net-2.7.3\data\downloads\README.md, retry:0
Feb 03 23:39:41 - [WARNING] request module:gae_proxy start fail
Feb 03 23:39:41 - [WARNING] request module:gae_proxy start fail
Feb 03 23:39:42 - [WARNING] request module:gae_proxy start fail
Feb 03 23:39:42 - [WARNING] request module:gae_proxy start fail
Feb 03 23:39:43 - [WARNING] request module:gae_proxy start fail
Feb 03 23:39:43 - [WARNING] request module:gae_proxy start fail
Feb 03 23:39:44 - [WARNING] request module:gae_proxy start fail
Feb 03 23:39:44 - [WARNING] request module:gae_proxy start fail
Feb 03 23:39:45 - [WARNING] request module:gae_proxy start fail
Feb 03 23:39:45 - [WARNING] request module:gae_proxy start fail
Feb 03 23:39:46 - [WARNING] request module:gae_proxy start fail
Feb 03 23:39:46 - [WARNING] request module:gae_proxy start fail
Feb 03 23:39:47 - [WARNING] request module:gae_proxy start fail
Feb 03 23:39:47 - [WARNING] request module:gae_proxy start fail
Feb 03 23:39:48 - [WARNING] request module:gae_proxy start fail
Feb 03 23:39:48 - [WARNING] request module:gae_proxy start fail
Feb 03 23:39:49 - [WARNING] request module:gae_proxy start fail
Feb 03 23:39:49 - [WARNING] request module:gae_proxy start fail
Feb 03 23:39:50 - [WARNING] request module:gae_proxy start fail
Feb 03 23:39:50 - [WARNING] request module:gae_proxy start fail
Feb 03 23:39:51 - [WARNING] request module:gae_proxy start fail
Feb 03 23:39:51 - [WARNING] request module:gae_proxy start fail
请问这是啥情况？
如何解决呢？

**Comment by linhua55** [comment]
> D:\应用\翻墙软件\XX-Net-2.7.3

路径名不要包含中文

**Comment by ugvf2009** [comment]
像我这样的路径就好了。D:\Software\Xwall\XX-Net-2.8.10
