### ISSUE TITLE
部署服务端没有反应

### ISSUE THREAD

**Issue by heng0ai** [XX-net/XX-Net#2065]
我是kali linux 系统，我在Iceweasel浏览器上面部署服务端，但是 显示当前状态：空闲，日志一片空白，没有反应

终端显示这样的错误信息

WARNING:root:fetch:timeout('timed out',)
2月 06 11:11:43.32 - [ERROR] handler:TypeError('%d format: a number is required, not str',)
2月 06 11:11:43.32 - [ERROR] Except stack:Traceback (most recent call last):
  File "/root/桌面/XX-Net-2.8.9/python27/1.0/lib/noarch/simple_http_server.py", line 128, in handle_one_request
    self.do_POST()
  File "/root/桌面/XX-Net-2.8.9/gae_proxy/local/proxy_handler.py", line 101, in do_METHOD
    return self.forward_local()
  File "/root/桌面/XX-Net-2.8.9/gae_proxy/local/proxy_handler.py", line 70, in forward_local
    out_list.append("HTTP/1.1 %d\r\n" % status)
TypeError: %d format: a number is required, not str

**Comment by heng0ai** [comment]
刚才又试了试，然后变成了这样
2月 06 15:18:39.02 - [ERROR] handler:KeyError('appid',)
2月 06 15:18:39.03 - [ERROR] Except stack:Traceback (most recent call last):
  File "/root/桌面/XX-Net-2.8.9/python27/1.0/lib/noarch/simple_http_server.py", line 128, in handle_one_request
    self.do_POST()
  File "/root/桌面/XX-Net-2.8.9/launcher/web_control.py", line 86, in do_POST
    controler.do_POST()
  File "/root/桌面/XX-Net-2.8.9/gae_proxy/local/web_control.py", line 301, in do_POST
    return self.req_deploy_handler()
  File "/root/桌面/XX-Net-2.8.9/gae_proxy/local/web_control.py", line 518, in req_deploy_handler
    appid = self.postvars['appid'][0]
KeyError: 'appid'

**Comment by xyuanmu** [comment]
试试别解压到中文路径。
话说你这个issue提醒了我，顺便修复了一个Windows下python27的bug。
