### ISSUE TITLE
正常使用一段时间后无法启动，启动start.bat后界面如下

### ISSUE THREAD

**Issue by 2niuhe** [XX-net/XX-Net#2072]
D:\ProgramFile\XX-Net-2.8.9>SET PYTHONPATH=

D:\ProgramFile\XX-Net-2.8.9>"D:\ProgramFile\XX-Net-2.8.9\python27/1.0/python.exe
" "D:\ProgramFile\XX-Net-2.8.9\launcher/start.py"
Feb 10 08:22:55.270 - [INFO] start XX-Net 2.8.10
Feb 10 08:22:55.270 - [DEBUG] start confirm_xxnet_exit
Feb 10 08:22:56.299 - [DEBUG] good, xxnet:8087 cleared!
Feb 10 08:22:57.314 - [DEBUG] good, xxnet:8085 clear!
Feb 10 08:22:57.314 - [DEBUG] finished confirm_xxnet_exit
Feb 10 08:22:57.330 - [ERROR] start module gae_proxy fail:File contains no secti
on headers.
file: D:\ProgramFile\XX-Net-2.8.9\gae_proxy\local\proxy.ini, line: 1
"\xef\xbb\xbf; Don't Edit the file manual\n"
Feb 10 08:22:57.346 - [ERROR] Except stack:Traceback (most recent call last):
  File "D:\ProgramFile\XX-Net-2.8.9\launcher\module_init.py", line 37, in start
    proc_handler[module]["imp"] = **import**(module, globals(), locals(), ['loca
l', 'start'], -1)
  File "D:\ProgramFile\XX-Net-2.8.9\gae_proxy\start.py", line 14, in <module>
    import local.proxy as client
  File "D:\ProgramFile\XX-Net-2.8.9\gae_proxy\local\proxy.py", line 86, in <modu
le>
    from config import config
  File "D:\ProgramFile\XX-Net-2.8.9\gae_proxy\local\config.py", line 137, in <mo
dule>
    config.load()
  File "D:\ProgramFile\XX-Net-2.8.9\gae_proxy\local\config.py", line 32, in load

```
self.CONFIG.read(self.CONFIG_FILENAME)
```

  File "D:\ProgramFile\XX-Net-2.8.9\python27\1.0\lib\ConfigParser.py", line 305,
 in read
    self._read(fp, filename)
  File "D:\ProgramFile\XX-Net-2.8.9\python27\1.0\lib\ConfigParser.py", line 512,
 in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
MissingSectionHeaderError: File contains no section headers.
file: D:\ProgramFile\XX-Net-2.8.9\gae_proxy\local\proxy.ini, line: 1
"\xef\xbb\xbf; Don't Edit the file manual\n"

Traceback (most recent call last):
  File "D:\ProgramFile\XX-Net-2.8.9\launcher/start.py", line 132, in <module>
    main()
  File "D:\ProgramFile\XX-Net-2.8.9\launcher/start.py", line 107, in main
    module_init.start_all_auto()
  File "D:\ProgramFile\XX-Net-2.8.9\launcher\module_init.py", line 98, in start_
all_auto
    start(module)
  File "D:\ProgramFile\XX-Net-2.8.9\launcher\module_init.py", line 37, in start
    proc_handler[module]["imp"] = **import**(module, globals(), locals(), ['loca
l', 'start'], -1)
  File "D:\ProgramFile\XX-Net-2.8.9\gae_proxy\start.py", line 14, in <module>
    import local.proxy as client
  File "D:\ProgramFile\XX-Net-2.8.9\gae_proxy\local\proxy.py", line 86, in <modu
le>
    from config import config
  File "D:\ProgramFile\XX-Net-2.8.9\gae_proxy\local\config.py", line 137, in <mo
dule>
    config.load()
  File "D:\ProgramFile\XX-Net-2.8.9\gae_proxy\local\config.py", line 32, in load

```
self.CONFIG.read(self.CONFIG_FILENAME)
```

  File "D:\ProgramFile\XX-Net-2.8.9\python27\1.0\lib\ConfigParser.py", line 305,
 in read
    self._read(fp, filename)
  File "D:\ProgramFile\XX-Net-2.8.9\python27\1.0\lib\ConfigParser.py", line 512,
 in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
ConfigParser.MissingSectionHeaderError: File contains no section headers.
file: D:\ProgramFile\XX-Net-2.8.9\gae_proxy\local\proxy.ini, line: 1
"\xef\xbb\xbf; Don't Edit the file manual\n"
Stopping all modules before exit!
Feb 10 08:22:57.377 - [ERROR] stop module gae_proxy fail:'imp'
Feb 10 08:22:57.377 - [ERROR] Except stack:Traceback (most recent call last):
  File "D:\ProgramFile\XX-Net-2.8.9\launcher\module_init.py", line 71, in stop
    _start = proc_handler[module]["imp"].start
KeyError: 'imp'

D:\ProgramFile\XX-Net-2.8.9>pause
请按任意键继续. . .

**Comment by dabney777** [comment]
我也是这样。。

**Comment by randawn** [comment]
@2niuhe @dabney777 因为你在windows上编辑过proxy.ini了，估计是记事本编辑的。格式不对，重新下一个就好了。

**Comment by dabney777** [comment]
@randawn proxy.ini是XX-Net-2.9.2\php_proxy\local路径下的吧？我从网上下载后仍然不行，显示
C:\WINDOWS\system32>SET PYTHONPATH=

C:\WINDOWS\system32>"D:\XX-Net-2.9.2\python27/1.0/python.exe" "D:\XX-Net-2.9.2\launcher/start.py"
Traceback (most recent call last):
  File "D:\XX-Net-2.9.2\launcher/start.py", line 60, in <module>
    from win_tray import sys_tray
  File "D:\XX-Net-2.9.2\launcher\win_tray.py", line 19, in <module>
    import module_init
  File "D:\XX-Net-2.9.2\launcher\module_init.py", line 6, in <module>
    import config
  File "D:\XX-Net-2.9.2\launcher\config.py", line 5, in <module>
    from distutils.version import LooseVersion
ImportError: No module named distutils.version

我觉得问题主要出在第一行，为什么“set pythonpath= ”后面是空的呢?
谢谢你的回复~

**Comment by jzp820927** [comment]
下载最新版覆盖吧，一般都可以解决

**Comment by andytree** [comment]
我解决了，其实是因为使用快压解压，使用7.ZIP解压出来使用就OK。。

**Comment by dabney777** [comment]
是的，是因为快压的缘故
