### ISSUE TITLE
scan_ip_worker exit

### ISSUE THREAD

**Issue by Git8fire** [XX-net/XX-Net#2076]
我执行./start.sh 出现这个，请问怎么处理Traceback (most recent call last):
File "launcher/start.py", line 34, in
from instances import xlog
File "/home/gtr/Downloads/XX-Net-2.8.9/launcher/instances.py", line 12, in
xlog = Logger(file_name=log_file)
File "/home/gtr/Downloads/XX-Net-2.8.9/python27/1.0/lib/noarch/xlog.py", line 34, in init
self.set_file(file_name)
File "/home/gtr/Downloads/XX-Net-2.8.9/python27/1.0/lib/noarch/xlog.py", line 84, in set_file
self.log_fd = open(file_name, "w")

XX-Net Version 2.8.9
Python Version 2.7.11
System Platform x86_64, Linux-4.3.0-kali1-amd64-x86_64-with-Kali-kali-rolling-kali-rolling
OS System Linux
OS Version #1 SMP Debian 4.3.3-7kali2 (2016-01-27)
Language en_US
Architecture 64bit,ELF
Browser Mozilla/5.0 (X11; Linux x86_64; rv:44.0) Gecko/20100101 Firefox/44.0 Iceweasel/44.0
后来我用ls -al发现date目录所有者是root,管理员权限不够，用chgrp -R /chown -R 两个命令变更所有者。可以执行。./start.sh，但又出现 scan_ip_worker exit。
提示无连接，怎么处理？

**Comment by NeroRose** [comment]
难道xx-net不更新了吗！

**Comment by Git8fire** [comment]
我的问题与XX-NET不更新有什么关系。

**Comment by NeroRose** [comment]
如果被墙了还怎么找！
