### ISSUE TITLE
在TOMATO路由器上部署XXNET的问题

### ISSUE THREAD

**Issue by JohnAppleseeder** [XX-net/XX-Net#2094]
路由器装了tomato系统，装了entware-arm，也装了python，openssl，加了manual.ini,里面有我的appid，把listenip改成了0.0.0.0.现在用python打开路由器目录下的xxnet/gae_proxy/local/proxy.py出现以下错误：
`root@unknown:/opt# python /jffs/opt/etc/XXNet/gae_proxy/local/proxy.py
Feb 17 04:08:21.908 - [INFO] load manual.ini success
Traceback (most recent call last):
  File "/jffs/opt/etc/XXNet/gae_proxy/local/proxy.py", line 95, in <module>
    from cert_util import CertUtil
  File "/jffs/opt/etc/XXNet/gae_proxy/local/cert_util.py", line 38, in <module>
    import OpenSSL
  File "/jffs/opt/etc/XXNet/python27/1.0/lib/linux/OpenSSL/__init__.py", line 36, in <module>
    from OpenSSL import crypto
ImportError: /jffs/opt/etc/XXNet/python27/1.0/lib/linux/OpenSSL/crypto.so: wrong ELF class: ELFCLASS64
`
如何解决？

**Comment by JohnAppleseeder** [comment]
加载launcher/start.py:
`root@unknown:/tmp/home/root# mount -o bind /jffs/opt /opt
root@unknown:/tmp/home/root# cd /opt
root@unknown:/opt# python /jffs/opt/etc/XXNet/launcher/start.py
Feb 17 06:48:26.031 - [INFO] start XX-Net 2.8.9
Feb 17 06:48:26.032 - [DEBUG] start confirm_xxnet_exit
Feb 17 06:48:26.043 - [DEBUG] good, xxnet:8087 cleared!
Feb 17 06:48:26.050 - [DEBUG] good, xxnet:8085 clear!
Feb 17 06:48:26.050 - [DEBUG] finished confirm_xxnet_exit
Feb 17 06:48:26.146 - [INFO] load manual.ini success
Feb 17 06:48:26.177 - [ERROR] start module gae_proxy fail:/jffs/opt/etc/XXNet/python27/1.0/lib/linux/OpenSSL/crypto.so: wrong ELF class: ELFCLASS64
Feb 17 06:48:26.181 - [ERROR] Except stack:Traceback (most recent call last):
  File "/jffs/opt/etc/XXNet/launcher/module_init.py", line 37, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "/jffs/opt/etc/XXNet/gae_proxy/start.py", line 14, in <module>
    import local.proxy as client
  File "/jffs/opt/etc/XXNet/gae_proxy/local/proxy.py", line 95, in <module>
    from cert_util import CertUtil
  File "/jffs/opt/etc/XXNet/gae_proxy/local/cert_util.py", line 38, in <module>
    import OpenSSL
  File "/jffs/opt/etc/XXNet/python27/1.0/lib/linux/OpenSSL/__init__.py", line 36, in <module>
    from OpenSSL import crypto
ImportError: /jffs/opt/etc/XXNet/python27/1.0/lib/linux/OpenSSL/crypto.so: wrong ELF class: ELFCLASS64

Feb 17 06:48:26.183 - [INFO] start gae_proxy time cost 131
Feb 17 06:48:26.186 - [INFO] begin to start web control
Feb 17 06:48:26.187 - [INFO] server 127.0.0.1:8085 started.
Feb 17 06:48:26.189 - [INFO] launcher web control started.
Feb 17 06:48:27.200 - [INFO] get uuid:8260bc67-924c-493d-9f60-777bb22cb247
Feb 17 06:48:27.238 - [WARNING] check_update fail:URLError(error(111, 'Connection refused'),)
Feb 17 06:48:27.239 - [INFO] download https://raw.githubusercontent.com/XX-net/XX-Net/master/README.md to /jffs/opt/etc/XXNet/data/downloads/README.md, retry:0
Feb 17 06:48:28.548 - [WARNING] download https://raw.githubusercontent.com/XX-net/XX-Net/master/README.md to /jffs/opt/etc/XXNet/data/downloads/README.md URL fail:URLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] unknown error (_ssl.c:590)'),)
Feb 17 06:48:28.549 - [INFO] download https://raw.githubusercontent.com/XX-net/XX-Net/master/README.md to /jffs/opt/etc/XXNet/data/downloads/README.md, retry:1
Feb 17 06:48:28.557 - [WARNING] download https://raw.githubusercontent.com/XX-net/XX-Net/master/README.md to /jffs/opt/etc/XXNet/data/downloads/README.md URL fail:URLError(error(111, 'Connection refused'),)
Feb 17 06:48:28.558 - [WARNING] check update fail:IOError('get README https://raw.githubusercontent.com/XX-net/XX-Net/master/README.md fail:',)
root@unknown:/tmp/home/root# mount -o bind /jffs/opt /opt
root@unknown:/tmp/home/root# cd /opt
root@unknown:/opt# python /jffs/opt/etc/XXNet/launcher/start.py
Feb 17 06:48:26.031 - [INFO] start XX-Net 2.8.9
Feb 17 06:48:26.032 - [DEBUG] start confirm_xxnet_exit
Feb 17 06:48:26.043 - [DEBUG] good, xxnet:8087 cleared!
Feb 17 06:48:26.050 - [DEBUG] good, xxnet:8085 clear!
Feb 17 06:48:26.050 - [DEBUG] finished confirm_xxnet_exit
Feb 17 06:48:26.146 - [INFO] load manual.ini success
Feb 17 06:48:26.177 - [ERROR] start module gae_proxy fail:/jffs/opt/etc/XXNet/python27/1.0/lib/linux/OpenSSL/crypto.so: wrong ELF class: ELFCLASS64
Feb 17 06:48:26.181 - [ERROR] Except stack:Traceback (most recent call last):
  File "/jffs/opt/etc/XXNet/launcher/module_init.py", line 37, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "/jffs/opt/etc/XXNet/gae_proxy/start.py", line 14, in <module>
    import local.proxy as client
  File "/jffs/opt/etc/XXNet/gae_proxy/local/proxy.py", line 95, in <module>
    from cert_util import CertUtil
  File "/jffs/opt/etc/XXNet/gae_proxy/local/cert_util.py", line 38, in <module>
    import OpenSSL
  File "/jffs/opt/etc/XXNet/python27/1.0/lib/linux/OpenSSL/__init__.py", line 36, in <module>
    from OpenSSL import crypto
ImportError: /jffs/opt/etc/XXNet/python27/1.0/lib/linux/OpenSSL/crypto.so: wrong ELF class: ELFCLASS64

Feb 17 06:48:26.183 - [INFO] start gae_proxy time cost 131
Feb 17 06:48:26.186 - [INFO] begin to start web control
Feb 17 06:48:26.187 - [INFO] server 127.0.0.1:8085 started.
Feb 17 06:48:26.189 - [INFO] launcher web control started.
Feb 17 06:48:27.200 - [INFO] get uuid:8260bc67-924c-493d-9f60-777bb22cb247
Feb 17 06:48:27.238 - [WARNING] check_update fail:URLError(error(111, 'Connection refused'),)
Feb 17 06:48:27.239 - [INFO] download https://raw.githubusercontent.com/XX-net/XX-Net/master/README.md to /jffs/opt/etc/XXNet/data/downloads/README.md, retry:0
Feb 17 06:48:28.548 - [WARNING] download https://raw.githubusercontent.com/XX-net/XX-Net/master/README.md to /jffs/opt/etc/XXNet/data/downloads/README.md URL fail:URLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] unknown error (_ssl.c:590)'),)
Feb 17 06:48:28.549 - [INFO] download https://raw.githubusercontent.com/XX-net/XX-Net/master/README.md to /jffs/opt/etc/XXNet/data/downloads/README.md, retry:1
Feb 17 06:48:28.557 - [WARNING] download https://raw.githubusercontent.com/XX-net/XX-Net/master/README.md to /jffs/opt/etc/XXNet/data/downloads/README.md URL fail:URLError(error(111, 'Connection refused'),)
Feb 17 06:48:28.558 - [WARNING] check update fail:IOError('get README https://raw.githubusercontent.com/XX-net/XX-Net/master/README.md fail:',)


root@unknown:/tmp/home/root# mount -o bind /jffs/opt /opt
root@unknown:/tmp/home/root# cd /opt
root@unknown:/opt# python /jffs/opt/etc/XXNet/launcher/start.py
Feb 17 06:48:26.031 - [INFO] start XX-Net 2.8.9
Feb 17 06:48:26.032 - [DEBUG] start confirm_xxnet_exit
Feb 17 06:48:26.043 - [DEBUG] good, xxnet:8087 cleared!
Feb 17 06:48:26.050 - [DEBUG] good, xxnet:8085 clear!
Feb 17 06:48:26.050 - [DEBUG] finished confirm_xxnet_exit
Feb 17 06:48:26.146 - [INFO] load manual.ini success
Feb 17 06:48:26.177 - [ERROR] start module gae_proxy fail:/jffs/opt/etc/XXNet/python27/1.0/lib/linux/OpenSSL/crypto.so: wrong ELF class: ELFCLASS64
Feb 17 06:48:26.181 - [ERROR] Except stack:Traceback (most recent call last):
  File "/jffs/opt/etc/XXNet/launcher/module_init.py", line 37, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "/jffs/opt/etc/XXNet/gae_proxy/start.py", line 14, in <module>
    import local.proxy as client
  File "/jffs/opt/etc/XXNet/gae_proxy/local/proxy.py", line 95, in <module>
    from cert_util import CertUtil
  File "/jffs/opt/etc/XXNet/gae_proxy/local/cert_util.py", line 38, in <module>
    import OpenSSL
  File "/jffs/opt/etc/XXNet/python27/1.0/lib/linux/OpenSSL/__init__.py", line 36, in <module>
    from OpenSSL import crypto
ImportError: /jffs/opt/etc/XXNe
`
