### ISSUE TITLE
windows server 2008 2

### ISSUE THREAD

**Issue by yaubio** [XX-net/XX-Net#2111]

**Comment by yaubio** [comment]
D:\app\XX-Net>SET PYTHONPATH=

D:\app\XX-Net>"D:\app\XX-Net\python27/1.0/python.exe" "D:\app\XX-Net\launcher/st
art.py"
Feb 19 09:55:00.278 - [INFO] start XX-Net 2.8.9
Feb 19 09:55:00.279 - [DEBUG] start confirm_xxnet_exit
Feb 19 09:55:01.283 - [DEBUG] good, xxnet:8087 cleared!
Feb 19 09:55:01.326 - [DEBUG] <0>: try to terminate xxnet:8085
Feb 19 09:55:02.363 - [DEBUG] <1>: try to terminate xxnet:8085
Feb 19 09:55:03.401 - [DEBUG] <2>: try to terminate xxnet:8085
Feb 19 09:55:04.441 - [DEBUG] <3>: try to terminate xxnet:8085
Feb 19 09:55:05.478 - [DEBUG] <4>: try to terminate xxnet:8085
Feb 19 09:55:06.516 - [DEBUG] <5>: try to terminate xxnet:8085
Feb 19 09:55:07.552 - [DEBUG] <6>: try to terminate xxnet:8085
Feb 19 09:55:08.591 - [DEBUG] <7>: try to terminate xxnet:8085
Feb 19 09:55:09.629 - [DEBUG] <8>: try to terminate xxnet:8085
Feb 19 09:55:10.667 - [DEBUG] <9>: try to terminate xxnet:8085
Feb 19 09:55:11.705 - [DEBUG] <10>: try to terminate xxnet:8085
Feb 19 09:55:12.742 - [DEBUG] <11>: try to terminate xxnet:8085
Feb 19 09:55:13.780 - [DEBUG] <12>: try to terminate xxnet:8085
Feb 19 09:55:14.816 - [DEBUG] <13>: try to terminate xxnet:8085
Feb 19 09:55:15.853 - [DEBUG] <14>: try to terminate xxnet:8085
Feb 19 09:55:16.891 - [DEBUG] <15>: try to terminate xxnet:8085
Feb 19 09:55:17.931 - [DEBUG] <16>: try to terminate xxnet:8085
Feb 19 09:55:18.999 - [DEBUG] <17>: try to terminate xxnet:8085
Feb 19 09:55:20.101 - [DEBUG] <18>: try to terminate xxnet:8085
Feb 19 09:55:21.205 - [DEBUG] <19>: try to terminate xxnet:8085
Feb 19 09:55:22.309 - [DEBUG] <20>: try to terminate xxnet:8085
Feb 19 09:55:23.414 - [DEBUG] <21>: try to terminate xxnet:8085
Feb 19 09:55:24.484 - [DEBUG] <22>: try to terminate xxnet:8085
Feb 19 09:55:25.587 - [DEBUG] <23>: try to terminate xxnet:8085
Feb 19 09:55:26.690 - [DEBUG] <24>: try to terminate xxnet:8085
Feb 19 09:55:27.759 - [DEBUG] <25>: try to terminate xxnet:8085
Feb 19 09:55:28.863 - [DEBUG] <26>: try to terminate xxnet:8085
Feb 19 09:55:29.967 - [DEBUG] <27>: try to terminate xxnet:8085
Feb 19 09:55:31.036 - [DEBUG] <28>: try to terminate xxnet:8085
Feb 19 09:55:32.140 - [DEBUG] <29>: try to terminate xxnet:8085
Feb 19 09:55:33.206 - [DEBUG] finished confirm_xxnet_exit
Feb 19 09:55:35.354 - [DEBUG] network is ok, cost:1064 ms
Feb 19 09:55:35.410 - [INFO] SSL use version:TLSv1
Feb 19 09:55:36.105 - [INFO] load ip range file:D:\app\XX-Net\gae_proxy\local\ip
_range.txt
Feb 19 09:55:36.363 - [INFO] load google ip_list num:2546, gws num:2546
Feb 19 09:55:36.437 - [INFO] Adjust scan thread num from 50 to 0
Feb 19 09:55:36.567 - [DEBUG] ## GAEProxy set keep_running: True
Feb 19 09:55:36.636 - [INFO] ---------------------------------------------------
---
Feb 19 09:55:36.706 - [INFO] Python Version     : 2.7.9
Feb 19 09:55:36.775 - [INFO] OS                 : Version:6-1; Build:7601; Platf
orm:2; CSD:Service Pack 1; ServicePack:1-0; Suite:274; ProductType:0
Feb 19 09:55:36.877 - [INFO] Listen Address     : 127.0.0.1:8087
Feb 19 09:55:36.944 - [INFO] GAE APPID          : yaubioxxnet
Feb 19 09:55:37.012 - [INFO] Pac Server         : http://127.0.0.1:8086/proxy.pa
c
Feb 19 09:55:37.145 - [INFO] ---------------------------------------------------
---
Feb 19 09:55:37.268 - [INFO] server 127.0.0.1:8087 started.
Feb 19 09:55:37.336 - [INFO] server 127.0.0.1:8086 started.
Feb 19 09:55:37.463 - [INFO] module gae_proxy started
Feb 19 09:55:37.529 - [INFO] start gae_proxy time cost 4276
Feb 19 09:55:37.564 - [INFO] begin to start web control
Feb 19 09:55:37.631 - [ERROR] bind to 127.0.0.1:8085 fail
Traceback (most recent call last):
  File "D:\app\XX-Net\launcher/start.py", line 132, in <module>
    main()
  File "D:\app\XX-Net\launcher/start.py", line 109, in main
    web_control.start()
  File "D:\app\XX-Net\launcher\web_control.py", line 420, in start
    server = simple_http_server.HTTPServer((host_addr, host_port), Http_Handler)

  File "D:\app\XX-Net\python27\1.0\lib\noarch\simple_http_server.py", line 255,
in __init__
    self.init_socket()
  File "D:\app\XX-Net\python27\1.0\lib\noarch\simple_http_server.py", line 267,
in init_socket
    raise e
socket.error: [Errno 10013] An attempt was made to access a socket in a way forb
idden by its access permissions
Stopping all modules before exit!
Feb 19 09:55:38.543 - [DEBUG] start to terminate gae_proxy module
Feb 19 09:55:38.615 - [INFO] start to terminate GAE_Proxy
Feb 19 09:55:38.650 - [DEBUG] ## Set keep_running: False
Feb 19 09:55:38.717 - [DEBUG] module gae_proxy stopping
Feb 19 09:55:39.373 - [INFO] Exiting gae_proxy module...
Feb 19 09:55:39.416 - [WARNING] socket accept fail(errno: 9).
Feb 19 09:55:39.475 - [WARNING] socket accept fail(errno: 9).
Feb 19 09:55:39.542 - [DEBUG] ## GAEProxy set keep_running: False
Feb 19 09:55:39.597 - [INFO] module gae_proxy stopped

D:\app\XX-Net>pause
Press any key to continue . . .

**Comment by jzp820927** [comment]
你的 8085 端口应该被其他程序占用了

**Comment by yaubio** [comment]
PRTG占用的，谢谢
