### ISSUE TITLE
部署appid已经成功，但是在配置的时候出现如下错误信息

### ISSUE THREAD

**Issue by heng0ai** [XX-net/XX-Net#2112]
Feb 19 12:52:32.848 - [ERROR] req_config_handler except:invalid literal for int(
) with base 10: 'heng0ai0chuju@gmail.com'
Feb 19 12:52:32.848 - [ERROR] Except stack:Traceback (most recent call last):
  File "E:\XX-Net-2.8.10\gae_proxy\local\web_control.py", line 487, in req_confi
g_handler
    config.load()
  File "E:\XX-Net-2.8.10\gae_proxy\local\config.py", line 111, in load
    self.PROXY_PORT = int(self.PROXY_PORT)
ValueError: invalid literal for int() with base 10: 'heng0ai0chuju@gmail.com'

**Comment by xxnet** [comment]
​你是不是手动修改配置文件了？
请恢复配置文件，在web界面上设置

**Comment by heng0ai** [comment]
我应该是没有修改过配置文件，而且我在web界面上，没有找到恢复配置文件的选项

**Comment by xxnet** [comment]
删除 data/gae_proxy/config.ini
重新启动xx-net
在界面上重新设置appid

**Comment by heng0ai** [comment]
Feb 19 18:45:54.208 - [ERROR] req_config_handler except:invalid literal for int() with base 10: 'heng0ai0chuju@gmail.com' 

Feb 19 18:45:54 - [ERROR]LOG_EXCEPT: Except stack:Traceback (most recent call last): File "E:\XX-Net-2.8.9\gae_proxy\local\web_control.py", line 487, in req_config_handler config.load() File "E:\XX-Net-2.8.9\gae_proxy\local\config.py", line 111, in load self.PROXY_PORT = int(self.PROXY_PORT) ValueError: invalid literal for int() with base 10: 'heng0ai0chuju@gmail.com' , Except:[Errno 9] Bad file descriptor

不行，还是显示这样的错误信息

**Comment by xxnet** [comment]
​你找找哪个ini文件有‘heng0ai0chuju@gmail.com' 字符

实在不行，就重新下载一个解压，重新配置
