### ISSUE TITLE
archlinux下没办法跑起来，goagent原版没问题，可以跑起来。

### ISSUE THREAD

**Issue by hehh2001** [XX-net/XX-Net#217]
[wlb@sxtvs-wlb:goagent-master]$ sudo  python2.7  start.py 
Apr 23 17:06:05 - [INFO] load ip range file:/home/wlb/Downloads/goagent-master/local/ip_range.txt
Apr 23 17:06:05 - [INFO] load google ip_list num:2920, gws num:2920
Apr 23 17:06:05 - [DEBUG] sort ip time:2
Traceback (most recent call last):
  File "start.py", line 13, in <module>
    import local.proxy as goagent
  File "/home/wlb/Downloads/goagent-master/local/proxy.py", line 84, in <module>
    import web_control
  File "/home/wlb/Downloads/goagent-master/local/web_control.py", line 47, in <module>
    import yaml
ImportError: No module named yaml

[wlb@sxtvs-wlb:xx-net-1.10.1]$ sudo  ./start.sh
launcher version: 1.4.0
Traceback (most recent call last):
  File "launcher/start.py", line 60, in <module>
    main()
  File "launcher/start.py", line 55, in main
    from start import main as launcher_main
  File "/home/wlb/Downloads/xx-net-1.10.1/launcher/1.4.0/start.py", line 12, in <module>
    from gtk_tray import sys_tray
  File "/home/wlb/Downloads/xx-net-1.10.1/launcher/1.4.0/gtk_tray.py", line 18, in <module>
    import pynotify
ImportError: No module named pynotify
老大能否解决这一问题，能否做一个能直接能找IP的最简单goagent包，不带gtk前端的。

**Comment by xxnet** [comment]
请问你的ArchLinux是什么版本？

2015-04-23 5:13 GMT-04:00 he <notifications@github.com>:

**Comment by httpe** [comment]
Archlinux是可以用的。
要安装python2-notify包

**Comment by hehh2001** [comment]
感谢楼上的，安装python2-notify包就好了，但只有ROOT用户能运行，普通用户无法运行

**Comment by httpe** [comment]
我这里不用ROOT诶，你那里报什么错？

**Comment by hehh2001** [comment]
一直用原版的GOAGENT+GoGoTest    最近扫IP的工作太烦了，扫出来的IP用不到两天就不行了，才发现这个，想直接找个能换IP的，其它前端都不要。
