### ISSUE TITLE
不能重启XX-NET，要删除D:\XX-Net-2.8.9\data\gae_proxy\config.ini恢复默认才能启动公众ID附start.bat红字错误

### ISSUE THREAD

**Issue by Points-xx** [XX-net/XX-Net#2170]
部署后设置个人ID可查看到专案流量使用了，但是不能显示个人ID更不能重启XX-NET，要删除D:\XX-Net-2.8.9\data\gae_proxy\config.ini恢复默认才能启动公众ID附start.bat红字错误
Feb 26 16:59:56.492 - [ERROR] start module gae_proxy fail:invalid literal for int() with base 10: 'XXX@Gmail.com'
Feb 26 16:59:56.495 - [ERROR] Except stack:Traceback (most recent call last):
  File "D:\XX-Net-2.8.9\launcher\module_init.py", line 37, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "D:\XX-Net-2.8.9\gae_proxy\start.py", line 14, in <module>
    import local.proxy as client
  File "D:\XX-Net-2.8.9\gae_proxy\local\proxy.py", line 86, in <module>
    from config import config
  File "D:\XX-Net-2.8.9\gae_proxy\local\config.py", line 137, in <module>
    config.load()
  File "D:\XX-Net-2.8.9\gae_proxy\local\config.py", line 111, in load
    self.PROXY_PORT = int(self.PROXY_PORT)
ValueError: invalid literal for int() with base 10: 'XXX@Gmail.com'

**Comment by xxnet** [comment]
设置appid时，你的浏览器​自动填充，把 XXX@Gmail.com 给填到局域网代理端口了
后端也没有保护，导致出现这样的问题

**Comment by Points-xx** [comment]
“设置appid时，你的浏览器​自动填充，把 XXX@Gmail.com 给填到局域网代理端口了
后端也没有保护，导致出现这样的问题”请问解决方法，谢谢

**Comment by xxnet** [comment]
​代码已经修复了，你试试下载开发分支的版本
https://github.com/XX-net/XX-Net/archive/master.zip

**Comment by Points-xx** [comment]
Proxy port must be integer.

**Comment by Points-xx** [comment]
还是出错

**Comment by Points-xx** [comment]
手动修改D:\XX-Net-2.8.9\data\gae_proxy\config.ini
[proxy]
enable = 0
type = HTTP
host = 
port = 
user = 
passwd = 
可以用

**Comment by xxnet** [comment]
设置页面里，点开高级，打开代理设置，然后清楚端口的数据，再关闭代理，点保存。
因为设置的字段默认隐藏，被自动填了也看不到

**Comment by caofengzi** [comment]
如果你的appid已經是部署成功的可以用你自己的appid替換xx裡面的公用appid。
