### ISSUE TITLE
win10 10586 64位 XX-Net-2.8.9可以正常使用，更新到更高版本就会报错。

### ISSUE THREAD

**Issue by z344257899** [XX-net/XX-Net#2192]
win10 10586 64位XX-Net-2.8.9可以正常使用，更新到更高版本就会报错。
把XX-Net-2.8.9压缩包中的launcher下的win_tray.py复制后覆盖到更高版本中就可以正常使用。

**Comment by jzp820927** [comment]
具体报错的内容贴出来看看

**Comment by z344257899** [comment]
D:\软件\翻墙软件\XX-Net>SET PYTHONPATH=

D:\软件\翻墙软件\XX-Net>"D:\软件\翻墙软件\XX-Net\python27/1.0/python.exe" "D:\软件\翻墙软件\XX-Net\launcher/start.py"
Traceback (most recent call last):
  File "D:\软件\翻墙软件\XX-Net\launcher/start.py", line 60, in <module>
    from win_tray import sys_tray
  File "D:\软件\翻墙软件\XX-Net\launcher\win_tray.py", line 146, in <module>
    sys_tray = Win_tray()
  File "D:\软件\翻墙软件\XX-Net\launcher\win_tray.py", line 40, in __init__
    self.on_enable_pac()
  File "D:\软件\翻墙软件\XX-Net\launcher\win_tray.py", line 113, in on_enable_pac
    win32_proxy_manager.set_proxy("http://127.0.0.1:8086/proxy.pac")
  File "D:\软件\翻墙软件\XX-Net\python27\1.0\lib\win32\win32_proxy_manager.py", line 125, in set_proxy
    key,value,_ = winreg.EnumValue(CONNECTIONS, i)
WindowsError: [Error 14]

D:\软件\翻墙软件\XX-Net>pause
请按任意键继续. . .

**Comment by momoca** [comment]
删除原文件重下会解决.我刚刚就是发现升级后不好用了.

**Comment by z344257899** [comment]
@momoca 没用，删过N次了，只要用高于2.8.9版本的就会报错。

**Comment by xxnet** [comment]
刚刚加了try...cache，请帮忙测试有没有解决

​https://github.com/XX-net/XX-Net/archive/master.zip
包括看看托盘菜单设置代理是否有效

**Comment by z344257899** [comment]
@xxnet 已解决。托盘菜单设置代理有效
