### ISSUE TITLE
mac 上运行xx－net的问题

### ISSUE THREAD

**Issue by yangpengsheng** [XX-net/XX-Net#2213]
Mar 02 10:52:14.268 - [INFO] GoAgent CA exist
Mar 02 10:52:14.269 - [ERROR] bind to 127.0.0.1:8087 fail
Exception in thread Thread-54:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/yang/Documents/XX-Net-2.8.9/gae_proxy/start.py", line 19, in main
    client.main()
  File "/Users/yang/Documents/XX-Net-2.8.9/gae_proxy/local/proxy.py", line 239, in main
    proxy_daemon = simple_http_server.HTTPServer((config.LISTEN_IP, config.LISTEN_PORT), proxy_handler.GAEProxyHandler)
  File "/Users/yangpengsheng/Documents/XX-Net-2.8.9/python27/1.0/lib/noarch/simple_http_server.py", line 255, in __init__
    self.init_socket()
  File "/Users/yang/Documents/XX-Net-2.8.9/python27/1.0/lib/noarch/simple_http_server.py", line 267, in init_socket
    raise e
error: [Errno 48] Address already in use

怎么才能进入127。0.0.1的配置页面啊

**Comment by jzp820927** [comment]
你的 8087  端口应该是被其他进程占用了，你看看是哪个进程，kill 掉，再运行

**Comment by yangpengsheng** [comment]
lsof -i tcp:8087
COMMAND PID          USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
Python          627           yang    6u  IPv4 0xec250acfcda2b10b      0t0  TCP localhost:8087 (LISTEN)


提示端口时被python占用了的。。。。

**Comment by yangpengsheng** [comment]
@jzp820927 开始直接运行mac端的XX-NET配置页面提示没启动成功，我运行start.sh后那个程序自动关闭了

**Comment by jzp820927** [comment]
没有什么报错信息吗？

**Comment by yangpengsheng** [comment]
@jzp820927 没有其他的报错信息

**Comment by jzp820927** [comment]
没有搞错信息就不好判断力，看上面的提示，就是端口占用，你把所有 8087 的 id 都 kill ，再运行试试吧，不行，就重新下载最新版试试。

**Comment by yangpengsheng** [comment]
@jzp820927 在127的配置页面状态全是空白的。。会不会是防火墙的原因啊？

**Comment by yangpengsheng** [comment]
@jzp820927 确实是端口问题，谢谢啦～
