### ISSUE TITLE
求助，今天升级了archlinux，xx-net打不开了，帮忙看看啥情况。

### ISSUE THREAD

**Issue by nicegoing** [XX-net/XX-Net#2241]
[alex@arch XX-Net-2.8.10]$ ./start.sh
Mar 07 10:47:23.691 - [INFO] start XX-Net 2.9.2
Mar 07 10:47:23.691 - [DEBUG] start confirm_xxnet_exit
Mar 07 10:47:23.692 - [DEBUG] good, xxnet:8087 cleared!
Mar 07 10:47:23.692 - [DEBUG] good, xxnet:8085 clear!
Mar 07 10:47:23.692 - [DEBUG] finished confirm_xxnet_exit
Mar 07 10:47:23.696 - [ERROR] start module gae_proxy fail:/home/alex/Software/XX-Net-2.8.10/python27/1.0/lib/linux/OpenSSL/SSL.so: symbol SSLv3_method, version OPENSSL_1.0.0 not defined in file libssl.so.1.0.0 with link time reference
Mar 07 10:47:23.696 - [ERROR] Except stack:Traceback (most recent call last):
  File "/home/alex/Software/XX-Net-2.8.10/launcher/module_init.py", line 37, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "/home/alex/Software/XX-Net-2.8.10/gae_proxy/start.py", line 14, in <module>
    import local.proxy as client
  File "/home/alex/Software/XX-Net-2.8.10/gae_proxy/local/proxy.py", line 95, in <module>
    from cert_util import CertUtil
  File "/home/alex/Software/XX-Net-2.8.10/gae_proxy/local/cert_util.py", line 38, in <module>
    import OpenSSL
  File "/home/alex/Software/XX-Net-2.8.10/python27/1.0/lib/linux/OpenSSL/__init__.py", line 41, in <module>
    from OpenSSL import rand, SSL
ImportError: /home/alex/Software/XX-Net-2.8.10/python27/1.0/lib/linux/OpenSSL/SSL.so: symbol SSLv3_method, version OPENSSL_1.0.0 not defined in file libssl.so.1.0.0 with link time reference

Traceback (most recent call last):
  File "launcher/start.py", line 132, in <module>
    main()
  File "launcher/start.py", line 107, in main
    module_init.start_all_auto()
  File "/home/alex/Software/XX-Net-2.8.10/launcher/module_init.py", line 98, in start_all_auto
    start(module)
  File "/home/alex/Software/XX-Net-2.8.10/launcher/module_init.py", line 37, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "/home/alex/Software/XX-Net-2.8.10/gae_proxy/start.py", line 14, in <module>
    import local.proxy as client
  File "/home/alex/Software/XX-Net-2.8.10/gae_proxy/local/proxy.py", line 95, in <module>
    from cert_util import CertUtil
  File "/home/alex/Software/XX-Net-2.8.10/gae_proxy/local/cert_util.py", line 38, in <module>
    import OpenSSL
  File "/home/alex/Software/XX-Net-2.8.10/python27/1.0/lib/linux/OpenSSL/__init__.py", line 41, in <module>
    from OpenSSL import rand, SSL
ImportError: /home/alex/Software/XX-Net-2.8.10/python27/1.0/lib/linux/OpenSSL/SSL.so: symbol SSLv3_method, version OPENSSL_1.0.0 not defined in file libssl.so.1.0.0 with link time reference
Stopping all modules before exit!
Mar 07 10:47:23.697 - [ERROR] stop module gae_proxy fail:'imp'
Mar 07 10:47:23.697 - [ERROR] Except stack:Traceback (most recent call last):
  File "/home/alex/Software/XX-Net-2.8.10/launcher/module_init.py", line 71, in stop
    _start = proc_handler[module]["imp"].start
KeyError: 'imp'

**Comment by xxnet** [comment]
​pyOpenSSL 库的问题

**Comment by yyy123zc** [comment]
今天升级后同样问题，在Packages搜索OpenSSL后一个一个是的，安装sudo pacman -S openssl python2-pyopenssl就可以了。

**Comment by WuSiYu** [comment]
刚才遇到了同样的问题，安装python2-pyopenssl即可
sudo pacman -S python2-pyopenssl

**Comment by nicegoing** [comment]
谢谢，解决了。不知道为啥早上安装python2-pyopenssl不行，现在安装就可以了。
