### ISSUE TITLE
启动后无法读取配置

### ISSUE THREAD

**Issue by xugh7705** [XX-net/XX-Net#2281]
错误提示

D:\XX-Net-2.0.5>SET PYTHONPATH=

D:\XX-Net-2.0.5>"D:\XX-Net-2.0.5\python27/1.0/python.exe" "D:\XX-Net-2.0.5\launcher/start.py"
Mar 09 11:18:01 - [DEBUG] start confirm_xxnet_exit
Mar 09 11:18:02 - [ERROR] start module gae_proxy fail:'str' object is not callable
Traceback (most recent call last):
  File "D:\XX-Net-2.0.5\launcher\module_init.py", line 34, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "D:\XX-Net-2.0.5\gae_proxy\start.py", line 14, in <module>
    import local.proxy as client
  File "D:\XX-Net-2.0.5\gae_proxy\local\proxy.py", line 74, in <module>
    from cert_util import CertUtil
  File "D:\XX-Net-2.0.5\gae_proxy\local\cert_util.py", line 36, in <module>
    xlog = getLogger("gae_proxy")
  File "D:\XX-Net-2.0.5\gae_proxy\local\xlog.py", line 56, in getLogger
    return cls(*args, **kwargs)
TypeError: 'str' object is not callable

Mar 09 11:18:02 - [INFO] start gae_proxy time cost 7
Mar 09 11:18:03 - [INFO] get uuid:cf180fa4-b3fd-47e4-9ec2-67c55d868954
Mar 09 11:18:04 - [WARNING] check_update fail:URLError(error(10061, ''),)

**Comment by wupengshang** [comment]
我现在打不开127.0.0.1:8085的页面，您能吗？

**Comment by xxnet** [comment]
​请重新下载2.9.3覆盖
