### ISSUE TITLE
不能启动PYTHON，启动时候提示内容如下

### ISSUE THREAD

**Issue by kigkrazy** [XX-net/XX-Net#2283]
D:\XX-Net-2.8.9>SET PYTHONPATH=

D:\XX-Net-2.8.9>"D:\XX-Net-2.8.9\python27/1.0/python.exe" "D:\XX-Net-2.8.9\launc
her/start.py"
Traceback (most recent call last):
  File "D:\XX-Net-2.8.9\launcher/start.py", line 60, in <module>
    from win_tray import sys_tray
  File "D:\XX-Net-2.8.9\launcher\win_tray.py", line 146, in <module>
    sys_tray = Win_tray()
  File "D:\XX-Net-2.8.9\launcher\win_tray.py", line 40, in __init__
    self.on_enable_pac()
  File "D:\XX-Net-2.8.9\launcher\win_tray.py", line 113, in on_enable_pac
    win32_proxy_manager.set_proxy("http://127.0.0.1:8086/proxy.pac")
AttributeError: 'module' object has no attribute 'set_proxy'

**Comment by xxnet** [comment]
​重新下载2.9.3覆盖吧
