### ISSUE TITLE
使用X-Tunnel无法打开网页

### ISSUE THREAD

**Issue by aveellaw** [XX-net/XX-Net#2285]
已经开启了X-Tunnel模块，有流量，但是切换到X-Tunnel时打不开网页，部分日志如下：
`Mar 09 18:32:36.823 - [DEBUG] socks handler read error error('recv fail',)
Mar 09 18:32:36.824 - [DEBUG] socks handler read error error('recv fail',)
Mar 09 18:32:36.828 - [DEBUG] socks handler read error error('recv fail',)
Mar 09 18:32:37.438 - [DEBUG] socks handler read error error('recv fail',)
Mar 09 18:32:38.436 - [DEBUG] socks handler read error error('recv fail',)
Mar 09 18:32:38.436 - [DEBUG] socks handler read error error('recv fail',)
Mar 09 18:32:38.436 - [DEBUG] socks handler read error error('recv fail',)
Mar 09 18:32:38.436 - [DEBUG] socks handler read error error('recv fail',)
Mar 09 18:32:38.481 - [DEBUG] socks handler read error error('recv fail',)
Mar 09 18:32:41.065 - [DEBUG] socks handler read error error('recv fail',)
Mar 09 18:32:42.068 - [DEBUG] socks handler read error error('recv fail',)
Mar 09 18:32:47.063 - [DEBUG] socks handler read error error('recv fail',)
Mar 09 18:32:50.525 - [DEBUG] socks handler read error error('recv fail',)
Mar 09 18:32:53.662 - [DEBUG] socks handler read error error('recv fail',)
Mar 09 18:32:59.403 - [DEBUG] socks handler read error error('recv fail',)`
该如何解决呢？

**Comment by xxnet** [comment]
​Socks5协议，看看你设置代理有没有弄对

**Comment by aveellaw** [comment]
SwitchyOmega里X-Tunnel的代理服务器设置是这样的
![x-tunnel](https://cloud.githubusercontent.com/assets/17739215/13633789/38cc51a0-e62c-11e5-8d18-9a9798e21939.png)
还有其他需要修改的吗？

**Comment by xxnet** [comment]
​看上去没有问题。

你修改 x_tunnel/proxy_handler.py 35行：
   xlog.debug('socks handler read error %r', e)
改成：
   xlog.exception('socks handler read error %r', e)

然后再看看日志

**Comment by aveellaw** [comment]
现在的日志是这样子的：
> Mar 09 19:34:56.419 - [ERROR] socks handler read error error('recv fail',)
Mar 09 19:34:56.419 - [ERROR] socks handler read error error('recv fail',)
Mar 09 19:34:56.420 - [ERROR] Except stack:Traceback (most recent call last): File "D:\Downloads\XX-Net\x_tunnel\local\proxy_handler.py", line 29, in handle self.socks5_handler() File "D:\Downloads\XX-Net\x_tunnel\local\proxy_handler.py", line 127, in socks5_handler data = self.read_bytes(4) File "D:\Downloads\XX-Net\x_tunnel\local\proxy_handler.py", line 69, in read_bytes raise socket.error("recv fail") error: recv fail
Mar 09 19:34:56.420 - [ERROR] Except stack:Traceback (most recent call last): File "D:\Downloads\XX-Net\x_tunnel\local\proxy_handler.py", line 29, in handle self.socks5_handler() File "D:\Downloads\XX-Net\x_tunnel\local\proxy_handler.py", line 127, in socks5_handler data = self.read_bytes(4) File "D:\Downloads\XX-Net\x_tunnel\local\proxy_handler.py", line 69, in read_bytes raise socket.error("recv fail") error: recv fail
Mar 09 19:34:58.278 - [ERROR] socks handler read error error('recv fail',)
Mar 09 19:34:58 - [ERROR]LOG_EXCEPT: Except stack:Traceback (most recent call last): File "D:\Downloads\XX-Net\x_tunnel\local\proxy_handler.py", line 29, in handle self.socks5_handler() File "D:\Downloads\XX-Net\x_tunnel\local\proxy_handler.py", line 127, in socks5_handler data = self.read_bytes(4) File "D:\Downloads\XX-Net\x_tunnel\local\proxy_handler.py", line 69, in read_bytes raise socket.error("recv fail") error: recv fail , Except:[Errno 9] Bad file descriptor

**Comment by xxnet** [comment]
​已经进入socks5分支，但处理用户认证时失败。

你把 123行：
# xlog.debug("client version:%d, auth num:%d, list:%s", 5, auth_mode_num,
utils.str2hex(data))
前面的注释 # 去掉，并缩进4个空格，看看日志输出什么。

另外可以换个浏览器，比如Firefox，直接设置Socks5代理看看

**Comment by aveellaw** [comment]
改了之后是这样的：
> Mar 09 20:58:57.059 - [ERROR] any err:NameError("global name 'utils' is not defined",)
Mar 09 20:58:57.059 - [ERROR] Except stack:Traceback (most recent call last): File "D:\Downloads\XX-Net\x_tunnel\local\proxy_handler.py", line 29, in handle self.socks5_handler() File "D:\Downloads\XX-Net\x_tunnel\local\proxy_handler.py", line 123, in socks5_handler xlog.debug("client version:%d, auth num:%d, list:undefined", 5, auth_mode_num, utils.str2hex(data)) NameError: global name 'utils' is not defined
Mar 09 20:59:01.568 - [ERROR] any err:NameError("global name 'utils' is not defined",)
Mar 09 20:59:01 - [ERROR]LOG_EXCEPT: Except stack:Traceback (most recent call last): File "D:\Downloads\XX-Net\x_tunnel\local\proxy_handler.py", line 29, in handle self.socks5_handler() File "D:\Downloads\XX-Net\x_tunnel\local\proxy_handler.py", line 123, in socks5_handler xlog.debug("client version:%d, auth num:%d, list:undefined", 5, auth_mode_num, utils.str2hex(data)) NameError: global name 'utils' is not defined , Except:[Errno 9] Bad file descriptor

我用Firefox直接设置Socks5也还是不行...

**Comment by jzp820927** [comment]
你直接用 GAE 代理，能正常使用麽？

**Comment by aveellaw** [comment]
@jzp820927 GAE代理使用正常，不过部署新的appid时出现404错误，以前部署过的可以正常使用

**Comment by jzp820927** [comment]
现在 gae sdk 改了，使用要等更新了，才能部署了

**Comment by aveellaw** [comment]
我试过了  在现在这台电脑上重新下载配置最新版还是不行  在另一台电脑ipv6网络下X-Tunnel可以用

**Comment by jzp820927** [comment]
不会是你系统出问题了吧

**Comment by simear2004** [comment]
看看还有没有流量

**Comment by xxnet** [comment]
2016-03-09 21:29 GMT+08:00 aveellaw <notifications@github.com>:

> 改了之后是这样的：
>
> Mar 09 20:58:57.059 - [ERROR] any err:NameError("global name 'utils' is
> not defined",)
> Mar 09 20:58:57.059 - [ERROR] Except stack:Traceback (most recent call
> last): File "D:\Downloads\XX-Net\x_tunnel\local\proxy_handler.py", line 29,
> in handle self.socks5_handler() File
> "D:\Downloads\XX-Net\x_tunnel\local\proxy_handler.py", line 123, in
> socks5_handler xlog.debug("client version:%d, auth num:%d, list:undefined",
> 5, auth_mode_num, utils.str2hex(data)) NameError: global name 'utils' is
> not defined
> Mar 09 20:59:01.568 - [ERROR] any err:NameError("global name 'utils' is
> not defined",)
> Mar 09 20:59:01 - [ERROR]LOG_EXCEPT: Except stack:Traceback (most recent
> call last): File "D:\Downloads\XX-Net\x_tunnel\local\proxy_handler.py",
> line 29, in handle self.socks5_handler() File
> "D:\Downloads\XX-Net\x_tunnel\local\proxy_handler.py", line 123, in
> socks5_handler xlog.debug("client version:%d, auth num:%d, list:undefined",
> 5, auth_mode_num, utils.str2hex(data)) NameError: global name 'utils' is
> not defined , Except:[Errno 9] Bad file descriptor
>
> 你在这个文件第一行写:
import utils

再试试。


> 我用Firefox直接设置Socks5也还是不行...
>
你机器如果有杀毒软件、防火墙之类 的，先关掉。

**Comment by jzp820927** [comment]
国产安软，必须卸载。

**Comment by aveellaw** [comment]
Win10系统 并没有什么杀毒软件。换了2.9.4版本还是不行，在其他电脑就没问题，可能是我的系统出什么问题了吧，过段时间重装下再试试...

**Comment by jjandxa** [comment]
出现相同的问题

**Comment by jjandxa** [comment]
环境是：XX-NET.9.2、chrome、SwitchyOmega、Windows10
日志：[DEBUG] socks handler read error error('recv fail',)

需要将SwitchyOmega的X-Tunnel情况模式改为socket4才能正常使用？
