### ISSUE TITLE
windows10环境升级后启动异常

### ISSUE THREAD

**Issue by sirbaT** [XX-net/XX-Net#2289]
`异常提示
Traceback (most recent call last):
  File "E:\XX-Net-master\launcher\module_init.py", line 37, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "E:\XX-Net-master\gae_proxy\start.py", line 14, in <module>
    import local.proxy as client
  File "E:\XX-Net-master\gae_proxy\local\proxy.py", line 74, in <module>
    from cert_util import CertUtil
  File "E:\XX-Net-master\gae_proxy\local\cert_util.py", line 36, in <module>
    xlog = getLogger("gae_proxy")
  File "E:\XX-Net-master\gae_proxy\local\xlog.py", line 56, in getLogger
    return cls(*args, **kwargs)
TypeError: 'str' object is not callable`

**Comment by xxnet** [comment]
​你重新下载新版试试

**Comment by sirbaT** [comment]
重新下载后确实可以用了，但是确实不知道为什么这样的

**Comment by jzp820927** [comment]
在线升级不完整造成的，主要原因是 网络干扰
