### ISSUE TITLE
20160310XX-NET随机启动手动执行start.bat脚本后，报如下错误。

### ISSUE THREAD

**Issue by aceslup** [XX-net/XX-Net#2295]
Traceback (most recent call last):
  File "C:\APP\goagent\launcher/start.py", line 60, in <module>
    from win_tray import sys_tray
  File "C:\APP\goagent\launcher\win_tray.py", line 146, in <module>
    sys_tray = Win_tray()
  File "C:\APP\goagent\launcher\win_tray.py", line 40, in __init__
    self.on_enable_pac()
  File "C:\APP\goagent\launcher\win_tray.py", line 113, in on_enable_pac
    win32_proxy_manager.set_proxy("http://127.0.0.1:8086/proxy.pac")
AttributeError: 'module' object has no attribute 'set_proxy'

**Comment by aceslup** [comment]
已解决。重新覆盖XX-Net2.9.3执行bat能正常运行。

>在未覆盖之前，看到x_tunnel目录是空的，python3目录里也没有任何内容。覆盖后多了一些内容。不知道是否是自动更新出错。

**Comment by xxnet** [comment]
​重新下载新版覆盖看看

**Comment by caoyu** [comment]
最新版本win32_tray中用的是win32_proxy_manager.set_proxy("http://127.0.0.1:8086/proxy.pac"),实际python 的win32_proxy_manager中似乎并没有此方法？

**Comment by caoyu** [comment]
哈哈，用python3 branch下的win32_proxy_manager替换，问题解决。

**Comment by aceslup** [comment]
@xxnet 覆盖更新后，能解决。可能是自动更新出错。

**Comment by aceslup** [comment]
@caoyu 就是覆盖解决的。: )

**Comment by caoyu** [comment]
@aceslup 哦原来更新了版本，直接用新版覆盖就能解决。关于更新的问题https://github.com/XX-net/XX-Net/issues/2310
