### ISSUE TITLE
求助，执行./start.sh报错。archlinux_64

### ISSUE THREAD

**Issue by icheontao** [XX-net/XX-Net#2305]
3月 10 16:45:15.14 - [WARNING] import pynotify fail, please install python-notify if possiable.
3月 10 16:45:15.20 - [INFO] start XX-Net 2.9.3
3月 10 16:45:15.20 - [DEBUG] start confirm_xxnet_exit
3月 10 16:45:15.20 - [DEBUG] good, xxnet:8087 cleared!
3月 10 16:45:15.20 - [DEBUG] good, xxnet:8085 clear!
3月 10 16:45:15.20 - [DEBUG] finished confirm_xxnet_exit
3月 10 16:45:15.21 - [ERROR] start module gae_proxy fail:/home/taolichuan/coding/git_code/XX-Net/python27/1.0/lib/linux/OpenSSL/SSL.so: symbol SSLv3_method, version OPENSSL_1.0.0 not defined in file libssl.so.1.0.0 with link time reference
3月 10 16:45:15.21 - [ERROR] Except stack:Traceback (most recent call last):
  File "/home/taolichuan/coding/git_code/XX-Net/launcher/module_init.py", line 37, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "/home/taolichuan/coding/git_code/XX-Net/gae_proxy/start.py", line 14, in <module>
    import local.proxy as client
  File "/home/taolichuan/coding/git_code/XX-Net/gae_proxy/local/proxy.py", line 95, in <module>
    from cert_util import CertUtil
  File "/home/taolichuan/coding/git_code/XX-Net/gae_proxy/local/cert_util.py", line 38, in <module>
    import OpenSSL
  File "/home/taolichuan/coding/git_code/XX-Net/python27/1.0/lib/linux/OpenSSL/__init__.py", line 41, in <module>
    from OpenSSL import rand, SSL
ImportError: /home/taolichuan/coding/git_code/XX-Net/python27/1.0/lib/linux/OpenSSL/SSL.so: symbol SSLv3_method, version OPENSSL_1.0.0 not defined in file libssl.so.1.0.0 with link time reference

Traceback (most recent call last):
  File "launcher/start.py", line 132, in <module>
    main()
  File "launcher/start.py", line 107, in main
    module_init.start_all_auto()
  File "/home/taolichuan/coding/git_code/XX-Net/launcher/module_init.py", line 98, in start_all_auto
    start(module)
  File "/home/taolichuan/coding/git_code/XX-Net/launcher/module_init.py", line 37, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "/home/taolichuan/coding/git_code/XX-Net/gae_proxy/start.py", line 14, in <module>
    import local.proxy as client
  File "/home/taolichuan/coding/git_code/XX-Net/gae_proxy/local/proxy.py", line 95, in <module>
    from cert_util import CertUtil
  File "/home/taolichuan/coding/git_code/XX-Net/gae_proxy/local/cert_util.py", line 38, in <module>
    import OpenSSL
  File "/home/taolichuan/coding/git_code/XX-Net/python27/1.0/lib/linux/OpenSSL/__init__.py", line 41, in <module>
    from OpenSSL import rand, SSL
ImportError: /home/taolichuan/coding/git_code/XX-Net/python27/1.0/lib/linux/OpenSSL/SSL.so: symbol SSLv3_method, version OPENSSL_1.0.0 not defined in file libssl.so.1.0.0 with link time reference
Stopping all modules before exit!
3月 10 16:45:15.21 - [ERROR] stop module gae_proxy fail:'imp'
3月 10 16:45:15.21 - [ERROR] Except stack:Traceback (most recent call last):
  File "/home/taolichuan/coding/git_code/XX-Net/launcher/module_init.py", line 71, in stop
    _start = proc_handler[module]["imp"].start
KeyError: 'imp'

**Comment by jzp820927** [comment]
version OPENSSL_1.0.0 not defined in file libssl.so.1.0.0 with link time reference

好像是 openssl 的问题，升级下试试

**Comment by icheontao** [comment]
@jzp820927 openssl是最新的，昨天都能运行，今天就报错。

**Comment by xxnet** [comment]
​试试把 XX-Net/python27/1.0/lib/linux/OpenSSL 删除，用系统自带的pyOpenSSL库

**Comment by icheontao** [comment]
@xxnet 删除后报错[ERROR] start module gae_proxy fail:No module named OpenSSL。是不是默认python版本是3的原因啊

**Comment by jzp820927** [comment]
你看看启动日志 py版本是几

**Comment by xxnet** [comment]
​应该不是python3的问题。

你安装pyOpenSSL 库看看

**Comment by icheontao** [comment]
@jzp820927 @xxnet  谢谢，已解决。在python2中安装了pyOpenSSL库
