### ISSUE TITLE
deepin15.1升级XX-Net2.93（2.94）后不能运行

### ISSUE THREAD

**Issue by yyy123zc** [XX-net/XX-Net#2322]
deepin15.1升级XX-Net2.93（2.94）后不能运行，但XX-Net2.92运行正常。因为deepin论坛不能发有关XX-Net的帖子，所以来到这询问。
运行XX-Net2.93（2.94）显示结果如下：
3月 11 23:27:59.75 - [WARNING] import pynotify fail, please install python-notify if possiable.
/home/dzqnyb/XX-Net-dzqnyb/launcher/gtk_tray.py:60: GtkWarning: 无法在模块路径中找到主题引擎：“adwaita”，
  trayicon = gtk.StatusIcon()
3月 11 23:27:59.79 - [INFO] start XX-Net 2.9.3
3月 11 23:27:59.79 - [DEBUG] start confirm_xxnet_exit
3月 11 23:27:59.79 - [DEBUG] <0>: try to terminate xxnet:8087
3月 11 23:28:02.79 - [DEBUG] good, xxnet:8087 cleared!
3月 11 23:28:02.80 - [DEBUG] good, xxnet:8085 clear!
3月 11 23:28:02.80 - [DEBUG] finished confirm_xxnet_exit
3月 11 23:28:02.90 - [DEBUG] network is ok, cost:73 ms
3月 11 23:28:02.90 - [INFO] SSL use version:TLSv1_2
3月 11 23:28:02.90 - [INFO] load ip range file:/home/dzqnyb/XX-Net-dzqnyb/data/gae_proxy/ip_range.txt
3月 11 23:28:02.94 - [INFO] load google ip_list num:1720, gws num:1720
3月 11 23:28:02.96 - [DEBUG] ## GAEProxy set keep_running: True
3月 11 23:28:02.96 - [INFO] ------------------------------------------------------
3月 11 23:28:02.96 - [INFO] Python Version     : 2.7.11
3月 11 23:28:02.96 - [INFO] OS                 : Dist:debian; Version:8.0; ID:
3月 11 23:28:02.96 - [INFO] Listen Address     : 127.0.0.1:8087
3月 11 23:28:02.96 - [INFO] GAE APPID          : dzqn-yb|dzqnyb-988|dzqn-yb-1167|dzqnyb-1167|ultimate-flare-116715|copper-bot-116715|optimum-time-116715|alpine-sentry-116715|lucky-dahlia-116715|master-inn-116715
3月 11 23:28:02.96 - [INFO] Pac Server         : http://127.0.0.1:8086/proxy.pac
3月 11 23:28:02.96 - [INFO] ------------------------------------------------------
3月 11 23:28:02.99 - [WARNING] please install *libnss3-tools* package to import GoAgent root ca
3月 11 23:28:02.99 - [INFO] server 127.0.0.1:8087 started.
3月 11 23:28:02.99 - [ERROR] bind to 127.0.0.1:8086 fail
Exception in thread Thread-54:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/dzqnyb/XX-Net-dzqnyb/gae_proxy/start.py", line 19, in main
    client.main()
  File "/home/dzqnyb/XX-Net-dzqnyb/gae_proxy/local/proxy.py", line 242, in main
    pac_daemon = simple_http_server.HTTPServer((config.PAC_IP, config.PAC_PORT), pac_server.PACServerHandler)
  File "/home/dzqnyb/XX-Net-dzqnyb/python27/1.0/lib/noarch/simple_http_server.py", line 259, in __init__
    self.init_socket()
  File "/home/dzqnyb/XX-Net-dzqnyb/python27/1.0/lib/noarch/simple_http_server.py", line 264, in init_socket
    self.add_listen(addr)
  File "/home/dzqnyb/XX-Net-dzqnyb/python27/1.0/lib/noarch/simple_http_server.py", line 273, in add_listen
    raise e
error: [Errno 98] 地址已在使用

3月 11 23:28:31.60 - [INFO] scan_ip add ip:185.2.108.245 time:933

同时删除XX-Net2.93（2.94）文件夹安装XX-Net2.92运行正常结果如下：
/home/dzqnyb/XX-Net-dzqnyb/launcher/gtk_tray.py:60: GtkWarning: 无法在模块路径中找到主题引擎：“adwaita”，
  trayicon = gtk.StatusIcon()
3月 12 01:44:28.69 - [INFO] start XX-Net 2.9.2
3月 12 01:44:28.69 - [DEBUG] start confirm_xxnet_exit
3月 12 01:44:28.69 - [DEBUG] good, xxnet:8087 cleared!
3月 12 01:44:28.69 - [DEBUG] good, xxnet:8085 clear!
3月 12 01:44:28.69 - [DEBUG] finished confirm_xxnet_exit
3月 12 01:44:28.80 - [DEBUG] network is ok, cost:85 ms
3月 12 01:44:28.81 - [INFO] SSL use version:TLSv1_2
3月 12 01:44:28.81 - [INFO] load ip range file:/home/dzqnyb/XX-Net-dzqnyb/gae_proxy/local/ip_range.txt
3月 12 01:44:28.82 - [INFO] load google ip_list num:23, gws num:23
3月 12 01:44:28.83 - [DEBUG] ## GAEProxy set keep_running: True
3月 12 01:44:28.83 - [INFO] ------------------------------------------------------
3月 12 01:44:28.83 - [INFO] Python Version     : 2.7.11
3月 12 01:44:28.83 - [INFO] OS                 : Dist:debian; Version:8.0; ID:
3月 12 01:44:28.83 - [INFO] Listen Address     : 127.0.0.1:8087
3月 12 01:44:28.83 - [INFO] GAE APPID          : dzqn-yb|dzqnyb-988|dzqn-yb-1167|dzqnyb-1167|ultimate-flare-116715|copper-bot-116715|optimum-time-116715|alpine-sentry-116715|lucky-dahlia-116715|master-inn-116715
3月 12 01:44:28.83 - [INFO] Pac Server         : http://127.0.0.1:8086/proxy.pac
3月 12 01:44:28.83 - [INFO] ------------------------------------------------------
3月 12 01:44:28.83 - [WARNING] please install *libnss3-tools* package to import GoAgent root ca
3月 12 01:44:28.83 - [INFO] server 127.0.0.1:8087 started.
3月 12 01:44:28.83 - [INFO] server 127.0.0.1:8086 started.
3月 12 01:44:28.93 - [INFO] module gae_proxy started
3月 12 01:44:28.93 - [INFO] start gae_proxy time cost 241
3月 12 01:44:28.93 - [INFO] begin to start web control
3月 12 01:44:28.93 - [INFO] server 127.0.0.1:8085 started.
3月 12 01:44:28.93 - [INFO] launcher web control started.
3月 12 01:44:29.94 - [INFO] get uuid:195434b3-6955-44cb-80e1-f91c35a0d38f
3月 12 01:44:29.94 - [INFO] GAE CONNECT xxnet-update.appspot.com:443 
3月 12 01:44:29.95 - [DEBUG] GAE CONNECT Direct GET https://xxnet-update.appspot.com/update.json?uuid=195434b3-6955-44cb-80e1-f91c35a0d38f&version=2.9.2&platform=Linux-4.2.0-1-amd64-x86_64-with-debian-8.0
3月 12 01:44:29.95 - [DEBUG] get ip:118.98.77.228 t:291

**Comment by linhua55** [comment]
程序没彻底退出，占用8087端口

**Comment by firstuanl** [comment]
293,294都有这个占用，292之前就没有，最近就google上不去，整这个也碰到。

**Comment by firstuanl** [comment]
重启系统，运行xxnet就端口占用

**Comment by xxnet** [comment]
sudo ​netstat -napt |grep 8086 看看是什么程序在占用端口

**Comment by yyy123zc** [comment]
运行sudo ​netstat -napt |grep 8086显示：
:~$ sudo netstat -napt |grep 8086
tcp        0      0 127.0.0.1:8086          0.0.0.0:*               LISTEN      3274/python2

**Comment by xxnet** [comment]
​ps aux |grep 3274 看看是什么进程

**Comment by yyy123zc** [comment]
dzqnyb@dzqnyb-pc:~$ sudo netstat -napt |grep 8086
tcp        0      0 127.0.0.1:8086          0.0.0.0:*               LISTEN      2614/python2        
dzqnyb@dzqnyb-pc:~$ ps aux |grep 2614 
root      2614  0.7  0.5 2253540 44844 pts/0   Sl+  16:10   0:01 python2 launcher/start.py
dzqnyb    3134  0.0  0.0  18764  2380 pts/1    S+   16:14   0:00 grep 2614
dzqnyb@dzqnyb-pc:~$ ps aux |grep 3134
dzqnyb    3142  0.0  0.0  18764  2216 pts/1    S+   16:14   0:00 grep 3134
dzqnyb@dzqnyb-pc:~$ ps aux |grep 3142
dzqnyb    3164  0.0  0.0  18764  2380 pts/1    S+   16:14   0:00 grep 3142

**Comment by yyy123zc** [comment]
以python2 launcher/start.py搜索出帖子：https://github.com/XX-net/XX-Net/issues/1962
dzqnyb@dzqnyb-pc:~/XX-Net$ cat start.sh
#!/bin/bash

SCRIPTPATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $SCRIPTPATH

if hash python2 2>/dev/null; then
    python2 launcher/start.py
else
    python launcher/start.py
fi

下面不会弄：
root@dzqnyb-pc:~# /bin/bash
root@dzqnyb-pc:~# SCRIPTPATH=dirname "${BASH_SOURCE[0]}"
bash: : 未找到命令
root@dzqnyb-pc:~# cd $SCRIPTPATH
root@dzqnyb-pc:~# if hash python2 2>/dev/null; then
> python2 launcher/start.py
> else
> python launcher/start.py
>

**Comment by yyy123zc** [comment]
dzqnyb@dzqnyb-pc:~$ python2 launcher/start.py
python2: can't open file 'launcher/start.py': [Errno 2] No such file or directory
dzqnyb@dzqnyb-pc:~$ python launcher/start.py
python: can't open file 'launcher/start.py': [Errno 2] No such file or directory

**Comment by yyy123zc** [comment]
dzqnyb@dzqnyb-pc:~$ python 
Python 2.7.11 (default, Jan 11 2016, 21:04:40) 
[GCC 5.3.1 20160101] on linux2
Type "help", "copyright", "credits" or "license" for more information.

**Comment by yyy123zc** [comment]
@xxnet 
dzqnyb@dzqnyb-pc:~$ sudo netstat -napt |grep 8086
tcp 0 0 127.0.0.1:8086 0.0.0.0:* LISTEN 2614/python2

dzqnyb@dzqnyb-pc:~$ ps aux |grep 2614 
root 2614 0.7 0.5 2253540 44844 pts/0 Sl+ 16:10 0:01 python2 launcher/start.py
dzqnyb 3134 0.0 0.0 18764 2380 pts/1 S+ 16:14 0:00 grep 2614
dzqnyb@dzqnyb-pc:~$ ps aux |grep 3134
dzqnyb 3142 0.0 0.0 18764 2216 pts/1 S+ 16:14 0:00 grep 3134
dzqnyb@dzqnyb-pc:~$ ps aux |grep 3142
dzqnyb 3164 0.0 0.0 18764 2380 pts/1 S+ 16:14 0:00 grep 3142

dzqnyb@dzqnyb-pc:~/XX-Net$ cat start.sh
#!/bin/bash

SCRIPTPATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $SCRIPTPATH

if hash python2 2>/dev/null; then
python2 launcher/start.py
else
python launcher/start.py
fi

dzqnyb@dzqnyb-pc:~$ python2 launcher/start.py
python2: can't open file 'launcher/start.py': [Errno 2] No such file or directory
dzqnyb@dzqnyb-pc:~$ python launcher/start.py
python: can't open file 'launcher/start.py': [Errno 2] No such file or directory

dzqnyb@dzqnyb-pc:~$ python 
Python 2.7.11 (default, Jan 11 2016, 21:04:40) 
[GCC 5.3.1 20160101] on linux2
Type "help", "copyright", "credits" or "license" for more information.

**Comment by linhua55** [comment]
$ lsof -i :8086 -s TCP:LISTEN |grep LISTEN|cut -d " " -f 2|xargs sudo kill

**Comment by yyy123zc** [comment]
dzqnyb@dzqnyb-pc:~$ lsof -i :8086 -s TCP:LISTEN |grep LISTEN|cut -d " " -f 2|xargs sudo kill
[sudo] dzqnyb 的密码：

Usage:
 kill [options] <pid> [...]

Options:
 <pid> [...]            send signal to every <pid> listed
 -<signal>, -s, --signal <signal>
                        specify the <signal> to be sent
 -l, --list=[<signal>]  list all signal names, or convert one to a name
 -L, --table            list all signal names in a nice table

 -h, --help     display this help and exit
 -V, --version  output version information and exit

For more details see kill(1).

运行后还是不行

**Comment by yyy123zc** [comment]
dzqnyb@dzqnyb-pc:~$ sudo lsof -i :8086 -s TCP:LISTEN |grep LISTEN|cut -d " " -f 2|xargs sudo kill

/home/dzqnyb/XX-Net/launcher/gtk_tray.py:60: GtkWarning: 无法在模块路径中找到主题引擎：“adwaita”，
  trayicon = gtk.StatusIcon()
3月 12 21:53:36.62 - [INFO] start XX-Net 2.9.4
3月 12 21:53:36.62 - [DEBUG] start confirm_xxnet_exit
3月 12 21:53:36.62 - [DEBUG] good, xxnet:8087 cleared!
3月 12 21:53:36.62 - [DEBUG] good, xxnet:8085 clear!
3月 12 21:53:36.62 - [DEBUG] finished confirm_xxnet_exit
3月 12 21:53:36.76 - [DEBUG] network is ok, cost:96 ms
3月 12 21:53:36.76 - [INFO] SSL use version:TLSv1_2
3月 12 21:53:36.76 - [INFO] load ip range file:/home/dzqnyb/XX-Net/gae_proxy/local/ip_range.txt
3月 12 21:53:36.77 - [INFO] load google ip_list num:96, gws num:96
3月 12 21:53:36.79 - [DEBUG] ## GAEProxy set keep_running: True
3月 12 21:53:36.79 - [INFO] ------------------------------------------------------
3月 12 21:53:36.79 - [INFO] Python Version     : 2.7.11
3月 12 21:53:36.79 - [INFO] OS                 : Dist:debian; Version:8.0; ID:
3月 12 21:53:36.79 - [INFO] Listen Address     : 127.0.0.1:8087
3月 12 21:53:36.79 - [INFO] GAE APPID          : 
3月 12 21:53:36.79 - [INFO] Pac Server         : http://127.0.0.1:8086/proxy.pac
3月 12 21:53:36.79 - [INFO] ------------------------------------------------------
3月 12 21:53:36.81 - [WARNING] please install *libnss3-tools* package to import GoAgent root ca
3月 12 21:53:36.81 - [INFO] server 127.0.0.1:8087 started.
3月 12 21:53:36.81 - [INFO] server 127.0.0.1:8086 started.
3月 12 21:53:36.88 - [INFO] module gae_proxy started
3月 12 21:53:36.88 - [INFO] start gae_proxy time cost 259
WARNING:root:Load Crypto.Cipher.ARC4 Failed, Use Pure Python Instead.
3月 12 21:53:36.89 - [INFO] use config_path:/home/dzqnyb/XX-Net/data/x_tunnel/client.json
3月 12 21:53:36.89 - [INFO] Use proxy:127.0.0.1:8087
3月 12 21:53:36.89 - [DEBUG] x-tunnel no account
3月 12 21:53:36.89 - [WARNING] x-tunnel session not start
3月 12 21:53:36.89 - [ERROR] bind to 127.0.0.1:1080 fail
Exception in thread Thread-57:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/dzqnyb/XX-Net/x_tunnel/start.py", line 19, in main
    client.main()
  File "/home/dzqnyb/XX-Net/x_tunnel/local/client.py", line 154, in main
    g.socks5_server = simple_http_server.HTTPServer((g.config.socks_host, g.config.socks_port), Socks5Server)
  File "/home/dzqnyb/XX-Net/python27/1.0/lib/noarch/simple_http_server.py", line 259, in __init__
    self.init_socket()
  File "/home/dzqnyb/XX-Net/python27/1.0/lib/noarch/simple_http_server.py", line 264, in init_socket
    self.add_listen(addr)
  File "/home/dzqnyb/XX-Net/python27/1.0/lib/noarch/simple_http_server.py", line 273, in add_listen
    raise e
error: [Errno 98] 地址已在使用

3月 12 21:53:40.43 - [INFO] GAE CONNECT clients1.google.com:443 
3月 12 21:53:40.44 - [WARNING] read request line empty
3月 12 21:53:41.28 - [DEBUG] get ip:202.248.151.54 t:332
3月 12 21:53:41.39 - [DEBUG] get ip:118.98.77.238 t:356

**Comment by yyy123zc** [comment]
dzqnyb@dzqnyb-pc:~$ sudo lsof -i :8086 -s TCP:LISTEN |grep LISTEN|cut -d " " -f 2|xargs sudo kill
dzqnyb@dzqnyb-pc:~$ sudo netstat -napt |grep 8086
tcp        0      0 127.0.0.1:8086          0.0.0.0:*               LISTEN      11692/python2       
dzqnyb@dzqnyb-pc:~$ ps aux |grep 11692
root     11692  0.7  0.5 2253248 45056 pts/1   Sl+  21:53   0:01 python2 launcher/start.py
dzqnyb   11957  0.0  0.0  18764  2336 pts/0    S+   21:56   0:00 grep 11692
dzqnyb@dzqnyb-pc:~$ ps aux |grep 11957
dzqnyb   11982  0.0  0.0  18764  2316 pts/0    R+   21:56   0:00 grep 11957
dzqnyb@dzqnyb-pc:~$ ps aux |grep 18764
dzqnyb   12044  0.0  0.0  18764  2144 pts/0    S+   21:57   0:00 grep 18764
dzqnyb@dzqnyb-pc:~$ cat start.sh
cat: start.sh: 没有那个文件或目录
dzqnyb@dzqnyb-pc:~$ cd ~/XX-Net
dzqnyb@dzqnyb-pc:~/XX-Net$ cat start.sh
#!/bin/bash

SCRIPTPATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $SCRIPTPATH

if hash python2 2>/dev/null; then
    python2 launcher/start.py
else
    python launcher/start.py
fi
dzqnyb@dzqnyb-pc:~/XX-Net$ python2 launcher/start.py
Traceback (most recent call last):
  File "launcher/start.py", line 34, in <module>
    from instances import xlog
  File "/home/dzqnyb/XX-Net/launcher/instances.py", line 12, in <module>
    xlog = Logger(file_name=log_file)
  File "/home/dzqnyb/XX-Net/python27/1.0/lib/noarch/xlog.py", line 35, in __init__
    self.set_file(file_name)
  File "/home/dzqnyb/XX-Net/python27/1.0/lib/noarch/xlog.py", line 90, in set_file
    self.log_fd = open(file_name, "w")
IOError: [Errno 13] Permission denied: '/home/dzqnyb/XX-Net/data/launcher/launcher.log'

dzqnyb@dzqnyb-pc:~/XX-Net$ sudo python2 launcher/start.py
[sudo] dzqnyb 的密码：
/home/dzqnyb/XX-Net/launcher/gtk_tray.py:60: GtkWarning: 无法在模块路径中找到主题引擎：“adwaita”，
  trayicon = gtk.StatusIcon()
3月 12 22:00:56.93 - [INFO] start XX-Net 2.9.4
3月 12 22:00:56.93 - [DEBUG] start confirm_xxnet_exit
3月 12 22:00:56.93 - [DEBUG] <0>: try to terminate xxnet:8087
3月 12 22:00:59.93 - [DEBUG] good, xxnet:8087 cleared!
3月 12 22:00:59.93 - [DEBUG] good, xxnet:8085 clear!
3月 12 22:00:59.93 - [DEBUG] finished confirm_xxnet_exit
3月 12 22:01:02.90 - [DEBUG] network is ok, cost:2943 ms
3月 12 22:01:02.90 - [INFO] SSL use version:TLSv1_2
3月 12 22:01:02.90 - [INFO] load ip range file:/home/dzqnyb/XX-Net/gae_proxy/local/ip_range.txt
3月 12 22:01:02.93 - [INFO] load google ip_list num:104, gws num:104
3月 12 22:01:02.93 - [DEBUG] ## GAEProxy set keep_running: True
3月 12 22:01:02.93 - [INFO] ------------------------------------------------------
3月 12 22:01:02.93 - [INFO] Python Version     : 2.7.11
3月 12 22:01:02.94 - [INFO] OS                 : Dist:debian; Version:8.0; ID:
3月 12 22:01:02.94 - [INFO] Listen Address     : 127.0.0.1:8087
3月 12 22:01:02.94 - [INFO] GAE APPID          : 
3月 12 22:01:02.94 - [INFO] Pac Server         : http://127.0.0.1:8086/proxy.pac
3月 12 22:01:02.94 - [INFO] ------------------------------------------------------
3月 12 22:01:02.94 - [WARNING] please install *libnss3-tools* package to import GoAgent root ca
3月 12 22:01:02.94 - [INFO] server 127.0.0.1:8087 started.
3月 12 22:01:02.94 - [INFO] server 127.0.0.1:8086 started.
3月 12 22:01:03.03 - [INFO] module gae_proxy started
3月 12 22:01:03.03 - [INFO] start gae_proxy time cost 3101
WARNING:root:Load Crypto.Cipher.ARC4 Failed, Use Pure Python Instead.
3月 12 22:01:03.04 - [INFO] use config_path:/home/dzqnyb/XX-Net/data/x_tunnel/client.json
3月 12 22:01:03.04 - [INFO] Use proxy:127.0.0.1:8087
3月 12 22:01:03.04 - [DEBUG] x-tunnel no account
3月 12 22:01:03.04 - [WARNING] x-tunnel session not start
3月 12 22:01:03.04 - [ERROR] bind to 127.0.0.1:1080 fail
Exception in thread Thread-57:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/dzqnyb/XX-Net/x_tunnel/start.py", line 19, in main
    client.main()
  File "/home/dzqnyb/XX-Net/x_tunnel/local/client.py", line 154, in main
    g.socks5_server = simple_http_server.HTTPServer((g.config.socks_host, g.config.socks_port), Socks5Server)
  File "/home/dzqnyb/XX-Net/python27/1.0/lib/noarch/simple_http_server.py", line 259, in __init__
    self.init_socket()
  File "/home/dzqnyb/XX-Net/python27/1.0/lib/noarch/simple_http_server.py", line 264, in init_socket
    self.add_listen(addr)
  File "/home/dzqnyb/XX-Net/python27/1.0/lib/noarch/simple_http_server.py", line 273, in add_listen
    raise e
error: [Errno 98] 地址已在使用

3月 12 22:01:03.06 - [INFO] GAE CONNECT clients1.google.com:443 


dzqnyb@dzqnyb-pc:~/XX-Net$ sudo python launcher/start.py
/home/dzqnyb/XX-Net/launcher/gtk_tray.py:60: GtkWarning: 无法在模块路径中找到主题引擎：“adwaita”，
  trayicon = gtk.StatusIcon()
3月 12 22:01:33.21 - [INFO] start XX-Net 2.9.4
3月 12 22:01:33.21 - [DEBUG] start confirm_xxnet_exit
3月 12 22:01:33.21 - [DEBUG] good, xxnet:8087 cleared!
3月 12 22:01:33.21 - [DEBUG] good, xxnet:8085 clear!
3月 12 22:01:33.21 - [DEBUG] finished confirm_xxnet_exit
3月 12 22:01:34.99 - [DEBUG] network is ok, cost:1736 ms
3月 12 22:01:34.99 - [INFO] SSL use version:TLSv1_2
3月 12 22:01:34.99 - [INFO] load ip range file:/home/dzqnyb/XX-Net/gae_proxy/local/ip_range.txt
3月 12 22:01:35.00 - [INFO] load google ip_list num:104, gws num:104
3月 12 22:01:35.01 - [DEBUG] ## GAEProxy set keep_running: True
3月 12 22:01:35.01 - [INFO] ------------------------------------------------------
3月 12 22:01:35.01 - [INFO] Python Version     : 2.7.11
3月 12 22:01:35.02 - [INFO] OS                 : Dist:debian; Version:8.0; ID:
3月 12 22:01:35.02 - [INFO] Listen Address     : 127.0.0.1:8087
3月 12 22:01:35.02 - [INFO] GAE APPID          : 
3月 12 22:01:35.02 - [INFO] Pac Server         : http://127.0.0.1:8086/proxy.pac
3月 12 22:01:35.02 - [INFO] ------------------------------------------------------
3月 12 22:01:35.02 - [WARNING] please install *libnss3-tools* package to import GoAgent root ca
3月 12 22:01:35.02 - [INFO] server 127.0.0.1:8087 started.
3月 12 22:01:35.02 - [INFO] server 127.0.0.1:8086 started.
3月 12 22:01:35.11 - [INFO] module gae_proxy started
3月 12 22:01:35.11 - [INFO] start gae_proxy time cost 1898
WARNING:root:Load Crypto.Cipher.ARC4 Failed, Use Pure Python Instead.
3月 12 22:01:35.12 - [INFO] use config_path:/home/dzqnyb/XX-Net/data/x_tunnel/client.json
3月 12 22:01:35.12 - [INFO] Use proxy:127.0.0.1:8087
3月 12 22:01:35.12 - [DEBUG] x-tunnel no account
3月 12 22:01:35.12 - [WARNING] x-tunnel session not start
3月 12 22:01:35.12 - [ERROR] bind to 127.0.0.1:1080 fail
Exception in thread Thread-57:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/dzqnyb/XX-Net/x_tunnel/start.py", line 19, in main
    client.main()
  File "/home/dzqnyb/XX-Net/x_tunnel/local/client.py", line 154, in main
    g.socks5_server = simple_http_server.HTTPServer((g.config.socks_host, g.config.socks_port), Socks5Server)
  File "/home/dzqnyb/XX-Net/python27/1.0/lib/noarch/simple_http_server.py", line 259, in __init__
    self.init_socket()
  File "/home/dzqnyb/XX-Net/python27/1.0/lib/noarch/simple_http_server.py", line 264, in init_socket
    self.add_listen(addr)
  File "/home/dzqnyb/XX-Net/python27/1.0/lib/noarch/simple_http_server.py", line 273, in add_listen
    raise e
error: [Errno 98] 地址已在使用

3月 12 22:01:36.30 - [INFO] GAE CONNECT clients1.google.com:443

**Comment by linhua55** [comment]
$ lsof -i :8086 -i :8087 -i :1080 -s TCP:LISTEN |grep LISTEN|cut -d " " -f 2|xargs sudo kill

**Comment by yyy123zc** [comment]
linhua55 谢谢你！但还是不行，运行提示和上面的一样。

**Comment by jzp820927** [comment]
不晓得你的端口是被什么占用率

**Comment by firstuanl** [comment]
没有运行xx时，sudo netstat -napt |grep 8086没有内容
运行就说端口占用，sudo netstat -napt |grep 8086出来也就他自己

sudo netstat -napt |grep 8086
tcp        0      0 127.0.0.1:8086          0.0.0.0:*               LISTEN      6379/python2  

ps aux | grep 6379
firstua+  6379  0.7  1.0 2317032 38264 pts/4   Sl+  09:40   0:01 python2 launcher/start.py
firstua+  6958  0.0  0.0  15968   928 pts/8    S+   09:42   0:00 grep --color=auto 6379

2.9.2上不了google

**Comment by firstuanl** [comment]
ubuntu 14.04

**Comment by firstuanl** [comment]
但是我下载了2.8.10到2.9.2的几个版本都上不了google，不知是哪个版本出问题

**Comment by yyy123zc** [comment]
首先和firstuanl 情况一致，都是未运行XX-Net时未占用8086，运行XX-Net2.93（2.94）时占用。
但我的XX-Net一直能上google，现在deepin系统下XX-Net2.92和windows10、archlinux下XX-Net2.94一直能上google。使用XX-Net以来除了网站禁止使用XX-Net访问之外，没遇到其它不能访问的网站。

首先谢谢各位的帮助!2.92还能用，我就一只用2.92吧。本人对计算机是不懂的，使用linux一直靠百度、google，所以不知道列出什么东西能对大家有用。
这贴大家不用回了，我将我查询的最后一点东西列出来，希望有用。
每次使用XX-Net2.94后查询sudo netstat -napt |grep 8086和sudo netstat -napt |grep 8087显示同一端口，比如这次显示端口是3006，但我再进程管理器内未找到3006端口，使用netstat、netstat -a、netstat -lx、netstat --verbose等命令都没有找到3006，有tcp        0      0 localhost:8086          0.0.0.0:*               LISTEN         |           tcp        0      0 localhost:8087         0.0.0.0:*               LISTEN  .
没搜索出列出python进程的命令，不知道 python -v命令有用吗：
dzqnyb@dzqnyb-pc:~$ python -v
# installing zipimport hook
import zipimport # builtin
# installed zipimport hook
# /usr/lib/python2.7/site.pyc matches /usr/lib/python2.7/site.py
import site # precompiled from /usr/lib/python2.7/site.pyc
# /usr/lib/python2.7/os.pyc matches /usr/lib/python2.7/os.py
import os # precompiled from /usr/lib/python2.7/os.pyc
import errno # builtin
import posix # builtin
# /usr/lib/python2.7/posixpath.pyc matches /usr/lib/python2.7/posixpath.py
import posixpath # precompiled from /usr/lib/python2.7/posixpath.pyc
# /usr/lib/python2.7/stat.pyc matches /usr/lib/python2.7/stat.py
import stat # precompiled from /usr/lib/python2.7/stat.pyc
# /usr/lib/python2.7/genericpath.pyc matches /usr/lib/python2.7/genericpath.py
import genericpath # precompiled from /usr/lib/python2.7/genericpath.pyc
# /usr/lib/python2.7/warnings.pyc matches /usr/lib/python2.7/warnings.py
import warnings # precompiled from /usr/lib/python2.7/warnings.pyc
# /usr/lib/python2.7/linecache.pyc matches /usr/lib/python2.7/linecache.py
import linecache # precompiled from /usr/lib/python2.7/linecache.pyc
# /usr/lib/python2.7/types.pyc matches /usr/lib/python2.7/types.py
import types # precompiled from /usr/lib/python2.7/types.pyc
# /usr/lib/python2.7/UserDict.pyc matches /usr/lib/python2.7/UserDict.py
import UserDict # precompiled from /usr/lib/python2.7/UserDict.pyc
# /usr/lib/python2.7/_abcoll.pyc matches /usr/lib/python2.7/_abcoll.py
import _abcoll # precompiled from /usr/lib/python2.7/_abcoll.pyc
# /usr/lib/python2.7/abc.pyc matches /usr/lib/python2.7/abc.py
import abc # precompiled from /usr/lib/python2.7/abc.pyc
# /usr/lib/python2.7/_weakrefset.pyc matches /usr/lib/python2.7/_weakrefset.py
import _weakrefset # precompiled from /usr/lib/python2.7/_weakrefset.pyc
import _weakref # builtin
# /usr/lib/python2.7/copy_reg.pyc matches /usr/lib/python2.7/copy_reg.py
import copy_reg # precompiled from /usr/lib/python2.7/copy_reg.pyc
# /usr/lib/python2.7/traceback.pyc matches /usr/lib/python2.7/traceback.py
import traceback # precompiled from /usr/lib/python2.7/traceback.pyc
# /usr/lib/python2.7/sysconfig.pyc matches /usr/lib/python2.7/sysconfig.py
import sysconfig # precompiled from /usr/lib/python2.7/sysconfig.pyc
# /usr/lib/python2.7/re.pyc matches /usr/lib/python2.7/re.py
import re # precompiled from /usr/lib/python2.7/re.pyc
# /usr/lib/python2.7/sre_compile.pyc matches /usr/lib/python2.7/sre_compile.py
import sre_compile # precompiled from /usr/lib/python2.7/sre_compile.pyc
import _sre # builtin
# /usr/lib/python2.7/sre_parse.pyc matches /usr/lib/python2.7/sre_parse.py
import sre_parse # precompiled from /usr/lib/python2.7/sre_parse.pyc
# /usr/lib/python2.7/sre_constants.pyc matches /usr/lib/python2.7/sre_constants.py
import sre_constants # precompiled from /usr/lib/python2.7/sre_constants.pyc
import _locale # builtin
# /usr/lib/python2.7/_sysconfigdata.pyc matches /usr/lib/python2.7/_sysconfigdata.py
import _sysconfigdata # precompiled from /usr/lib/python2.7/_sysconfigdata.pyc
# /usr/lib/python2.7/plat-x86_64-linux-gnu/_sysconfigdata_nd.pyc matches /usr/lib/python2.7/plat-x86_64-linux-gnu/_sysconfigdata_nd.py
import _sysconfigdata_nd # precompiled from /usr/lib/python2.7/plat-x86_64-linux-gnu/_sysconfigdata_nd.pyc
# /usr/lib/python2.7/sitecustomize.pyc matches /usr/lib/python2.7/sitecustomize.py
import sitecustomize # precompiled from /usr/lib/python2.7/sitecustomize.pyc
import encodings # directory /usr/lib/python2.7/encodings
# /usr/lib/python2.7/encodings/__init__.pyc matches /usr/lib/python2.7/encodings/__init__.py
import encodings # precompiled from /usr/lib/python2.7/encodings/__init__.pyc
# /usr/lib/python2.7/codecs.pyc matches /usr/lib/python2.7/codecs.py
import codecs # precompiled from /usr/lib/python2.7/codecs.pyc
import _codecs # builtin
# /usr/lib/python2.7/encodings/aliases.pyc matches /usr/lib/python2.7/encodings/aliases.py
import encodings.aliases # precompiled from /usr/lib/python2.7/encodings/aliases.pyc
# /usr/lib/python2.7/encodings/utf_8.pyc matches /usr/lib/python2.7/encodings/utf_8.py
import encodings.utf_8 # precompiled from /usr/lib/python2.7/encodings/utf_8.pyc
Python 2.7.11 (default, Jan 11 2016, 21:04:40) 
[GCC 5.3.1 20160101] on linux2
Type "help", "copyright", "credits" or "license" for more information.
dlopen("/usr/lib/python2.7/lib-dynload/readline.x86_64-linux-gnu.so", 2);
import readline # dynamically loaded from /usr/lib/python2.7/lib-dynload/readline.x86_64-linux-gnu.so
