### ISSUE TITLE
把监听地址改为0.0.0.0后，xxnet就无法启动而且改回去也无法再启动

### ISSUE THREAD

**Issue by just4somefun** [XX-net/XX-Net#2329]
因需要设置局域网共享，所以需要监听0.0.0.0，以前用的是正常的。
后来可能因为自动升级又被改成127.0.0.1了，于是改成0.0.0.0，但是改完重启发现无法启动，改回127.0.0.1后也无法恢复正常启动，只能重新解压。

我按proxy.ini文档里的说明设置一个manual.ini在Data目录下也是无法启动xxnet。

发现只有第一次解压xxnet时在默认什么设置都没有修改的情况下可以正常启动，其他时候都不行。
现在变成无法设置监听0.0.0.0了

不知道是否我系统的问题
操作系统win8.1
2.9.2和2.9.4版本都有上述同样问题。

有遇到同样问题的吗？求帮助

**Comment by jzp820927** [comment]
你是用记事本改的麽？

**Comment by just4somefun** [comment]
@jzp820927 那肯定了啊

**Comment by jzp820927** [comment]
如果是用 windows 自带的记事本改的，可能会出现格式问题，建议用 notepad++ 重新改原文件试试

**Comment by just4somefun** [comment]
就是用notepad++

**Comment by jzp820927** [comment]
那就不知道是什么原因了，日志贴出来看看吧

**Comment by just4somefun** [comment]
以下是在data/gae_proxy/manual.ini文件中放入以下参数：

`[listen]
ip = 0.0.0.0 <- GoAgent代理服务的监听绑定ip
port = 8087 <- 代理绑定端口
visible = 1 <- 目前无效
debuginfo = 0 <- 目前无效

[pac]
; 自动代理
enable = 1
ip = 0.0.0.0
port = 8086
file = proxy.pac
gfwlist = https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt

;adblock = http://adblock-chinalist.googlecode.com/svn/trunk/adblock.txt
; adblock 项目已经停止维护更新
expired = 86400`

然后启动start.bat，启动日志如下：

`H:\fuck.gfw\XX-Net-2.9.4>SET PYTHONPATH=

H:\fuck.gfw\XX-Net-2.9.4>"H:\fuck.gfw\XX-Net-2.9.4\python27/1.0/python.exe" "H:\
fuck.gfw\XX-Net-2.9.4\launcher/start.py"
Mar 19 13:45:29.686 - [INFO] start XX-Net 2.9.4
Mar 19 13:45:29.686 - [DEBUG] start confirm_xxnet_exit
Mar 19 13:45:30.702 - [DEBUG] good, xxnet:8087 cleared!
Mar 19 13:45:31.718 - [DEBUG] good, xxnet:8085 clear!
Mar 19 13:45:31.718 - [DEBUG] finished confirm_xxnet_exit
Mar 19 13:45:31.718 - [INFO] load manual.ini success
Mar 19 13:45:31.718 - [ERROR] start module gae_proxy fail:invalid literal for in
t() with base 10: '8087 <- \xe4\xbb\xa3\xe7\x90\x86\xe7\xbb\x91\xe5\xae\x9a\xe7\
xab\xaf\xe5\x8f\xa3'
Mar 19 13:45:31.718 - [ERROR] Except stack:Traceback (most recent call last):
  File "H:\fuck.gfw\XX-Net-2.9.4\launcher\module_init.py", line 37, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['loca
l', 'start'], -1)
  File "H:\fuck.gfw\XX-Net-2.9.4\gae_proxy\start.py", line 14, in <module>
    import local.proxy as client
  File "H:\fuck.gfw\XX-Net-2.9.4\gae_proxy\local\proxy.py", line 86, in <module>

    from config import config
  File "H:\fuck.gfw\XX-Net-2.9.4\gae_proxy\local\config.py", line 141, in <modul
e>
    config.load()
  File "H:\fuck.gfw\XX-Net-2.9.4\gae_proxy\local\config.py", line 50, in load
    self.LISTEN_PORT = self.CONFIG.getint('listen', 'port')
  File "H:\fuck.gfw\XX-Net-2.9.4\python27\1.0\lib\ConfigParser.py", line 359, in
 getint
    return self._get(section, int, option)
  File "H:\fuck.gfw\XX-Net-2.9.4\python27\1.0\lib\ConfigParser.py", line 356, in
 _get
    return conv(self.get(section, option))
ValueError: invalid literal for int() with base 10: '8087 <- \xe4\xbb\xa3\xe7\x9
0\x86\xe7\xbb\x91\xe5\xae\x9a\xe7\xab\xaf\xe5\x8f\xa3'

Traceback (most recent call last):
  File "H:\fuck.gfw\XX-Net-2.9.4\launcher/start.py", line 132, in <module>
    main()
  File "H:\fuck.gfw\XX-Net-2.9.4\launcher/start.py", line 107, in main
    module_init.start_all_auto()
  File "H:\fuck.gfw\XX-Net-2.9.4\launcher\module_init.py", line 98, in start_all
_auto
    start(module)
  File "H:\fuck.gfw\XX-Net-2.9.4\launcher\module_init.py", line 37, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['loca
l', 'start'], -1)
  File "H:\fuck.gfw\XX-Net-2.9.4\gae_proxy\start.py", line 14, in <module>
    import local.proxy as client
  File "H:\fuck.gfw\XX-Net-2.9.4\gae_proxy\local\proxy.py", line 86, in <module>

    from config import config
  File "H:\fuck.gfw\XX-Net-2.9.4\gae_proxy\local\config.py", line 141, in <modul
e>
    config.load()
  File "H:\fuck.gfw\XX-Net-2.9.4\gae_proxy\local\config.py", line 50, in load
    self.LISTEN_PORT = self.CONFIG.getint('listen', 'port')
  File "H:\fuck.gfw\XX-Net-2.9.4\python27\1.0\lib\ConfigParser.py", line 359, in
 getint
    return self._get(section, int, option)
  File "H:\fuck.gfw\XX-Net-2.9.4\python27\1.0\lib\ConfigParser.py", line 356, in
 _get
    return conv(self.get(section, option))
ValueError: invalid literal for int() with base 10: '8087 <- \xe4\xbb\xa3\xe7\x9
0\x86\xe7\xbb\x91\xe5\xae\x9a\xe7\xab\xaf\xe5\x8f\xa3'
Stopping all modules before exit!
Mar 19 13:45:31.827 - [ERROR] stop module gae_proxy fail:'imp'
Mar 19 13:45:31.827 - [ERROR] Except stack:Traceback (most recent call last):
  File "H:\fuck.gfw\XX-Net-2.9.4\launcher\module_init.py", line 71, in stop
    _start = proc_handler[module]["imp"].start
KeyError: 'imp'


H:\fuck.gfw\XX-Net-2.9.4>pause
请按任意键继续. . .`

这个是launcher.log

`Mar 19 13:45:29.686 - [INFO] start XX-Net 2.9.4
Mar 19 13:45:29.686 - [DEBUG] start confirm_xxnet_exit
Mar 19 13:45:30.702 - [DEBUG] good, xxnet:8087 cleared!
Mar 19 13:45:31.718 - [DEBUG] good, xxnet:8085 clear!
Mar 19 13:45:31.718 - [DEBUG] finished confirm_xxnet_exit
Mar 19 13:45:31.718 - [ERROR] start module gae_proxy fail:invalid literal for int() with base 10: '8087 <- \xe4\xbb\xa3\xe7\x90\x86\xe7\xbb\x91\xe5\xae\x9a\xe7\xab\xaf\xe5\x8f\xa3'
Mar 19 13:45:31.718 - [ERROR] Except stack:Traceback (most recent call last):
  File "H:\fuck.gfw\XX-Net-2.9.4\launcher\module_init.py", line 37, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "H:\fuck.gfw\XX-Net-2.9.4\gae_proxy\start.py", line 14, in <module>
    import local.proxy as client
  File "H:\fuck.gfw\XX-Net-2.9.4\gae_proxy\local\proxy.py", line 86, in <module>
    from config import config
  File "H:\fuck.gfw\XX-Net-2.9.4\gae_proxy\local\config.py", line 141, in <module>
    config.load()
  File "H:\fuck.gfw\XX-Net-2.9.4\gae_proxy\local\config.py", line 50, in load
    self.LISTEN_PORT = self.CONFIG.getint('listen', 'port')
  File "H:\fuck.gfw\XX-Net-2.9.4\python27\1.0\lib\ConfigParser.py", line 359, in getint
    return self._get(section, int, option)
  File "H:\fuck.gfw\XX-Net-2.9.4\python27\1.0\lib\ConfigParser.py", line 356, in _get
    return conv(self.get(section, option))
ValueError: invalid literal for int() with base 10: '8087 <- \xe4\xbb\xa3\xe7\x90\x86\xe7\xbb\x91\xe5\xae\x9a\xe7\xab\xaf\xe5\x8f\xa3'

Mar 19 13:45:31.827 - [ERROR] stop module gae_proxy fail:'imp'
Mar 19 13:45:31.827 - [ERROR] Except stack:Traceback (most recent call last):
  File "H:\fuck.gfw\XX-Net-2.9.4\launcher\module_init.py", line 71, in stop
    _start = proc_handler[module]["imp"].start
KeyError: 'imp'

`

请哪位指点一下到底是哪里出了问题，谢谢。

**Comment by jzp820927** [comment]
`[listen]

第一行，最前面多了个什么符号？删了试试

**Comment by just4somefun** [comment]
'[listen] 前面那个'是用了发帖工具栏中的 <code>标签

另外经过实际测试，我使用manual.ini自定义设置不能生效，反而使用config.ini才能生效

**Comment by chenyun90323** [comment]
确认你的行尾结束符是/n而不是/r/n了么？我这么修改是完全没有问题的呀
`[listen]

ip = 0.0.0.0

[pac]

ip = 0.0.0.0

[control]
ip = 0.0.0.0`

**Comment by jia460580031** [comment]
我跟楼主一样情况。。请问如何解决？

**Comment by jzp820927** [comment]
我去，都升级到最新版试试吧
