### ISSUE TITLE
ip不够，8.3删了运行8.4，导入ip， 错误。。。

### ISSUE THREAD

**Issue by RomainChan** [XX-net/XX-Net#2339]
日志在此
Mar 13 15:50:19.121 - [DEBUG] create_ssl update ip:189.215.200.18 time:657
Mar 13 15:50:19.285 - [WARNING] fetch gae status:400 url:https://clients4.google.com/chrome-sync/experimentstatus
Mar 13 15:50:19.287 - [WARNING] IP:189.215.200.19 not support GAE, server type:
Mar 13 15:50:19.289 - [INFO] remove ip:189.215.200.19 left amount:1717 gws_num:1717
Mar 13 15:50:19.417 - [DEBUG] 71.19.176.247 fail:timeout('timed out',)
Mar 13 15:50:19.418 - [DEBUG] report_connect_fail:71.19.176.247
Mar 13 15:50:19.482 - [WARNING] fetch gae status:400 url:http://www.google-analytics.com/__utm.gif?utmwv=5.6.7&utms=10&utmn=1385662516&utmhn=henmfoppjjkcencpbjaigfahdjlgpegn&utmcs=UTF-8&utmsr=1920x1080&utmvp=1920x917&utmsc=24-bit&utmul=zh-cn&utmje=0&utmfl=20.0%20r0&utmdt=New%20Tab&utmhid=1548888705&utmr=-&utmp=%2Fmain.html&utmht=1457855412430&utmac=UA-49733703-1&utmcc=__utma%3D32568359.1323244440.1454391755.1457787385.1457853623.29%3B%2B__utmz%3D32568359.1454391755.1.1.utmcsr%3D(direct)%7Cutmccn%3D(direct)%7Cutmcmd%3D(none)%3B&utmjid=&utmu=qAAAAAAAAAAAAAAAAAAAAAAE~
Mar 13 15:50:19.486 - [WARNING] IP:189.215.200.18 not support GAE, server type:
Mar 13 15:50:19.486 - [INFO] remove ip:189.215.200.18 left amount:1716 gws_num:1716
Mar 13 15:50:19.908 - [DEBUG] 77.214.53.214 fail:timeout('timed out',)
Mar 13 15:50:19.910 - [DEBUG] report_connect_fail:77.214.53.214
Mar 13 15:50:20.114 - [DEBUG] 85.182.250.92 fail:timeout('timed out',)
Mar 13 15:50:20.115 - [DEBUG] report_connect_fail:85.182.250.92
Mar 13 15:50:20.124 - [DEBUG] get ip:63.117.68.25 t:100
Mar 13 15:50:20.913 - [DEBUG] get ip:103.11.28.33 t:100
Mar 13 15:50:21.991 - [DEBUG] 62.75.10.40 fail:timeout('timed out',)
Mar 13 15:50:21.992 - [DEBUG] report_connect_fail:62.75.10.40
Mar 13 15:50:22.094 - [DEBUG] 212.188.10.171 fail:timeout('timed out',)
Mar 13 15:50:22.095 - [DEBUG] report_connect_fail:212.188.10.171
Mar 13 15:50:22.995 - [DEBUG] get ip:24.226.16.137 t:100
Mar 13 15:50:23.025 - [DEBUG] get ip:49.231.60.213 t:100
Mar 13 15:50:23.098 - [DEBUG] get ip:63.117.68.21 t:100
Mar 13 15:50:23.126 - [DEBUG] get ip:80.239.174.100 t:100
Mar 13 15:50:23.227 - [DEBUG] get ip:41.221.196.55 t:100
Mar 13 15:50:23.329 - [DEBUG] get ip:197.158.80.49 t:100
Mar 13 15:50:23.431 - [DEBUG] get ip:201.157.30.53 t:100
Mar 13 15:50:23.532 - [DEBUG] get ip:49.98.35.86 t:100
Mar 13 15:50:23.634 - [DEBUG] get ip:63.117.215.52 t:100
Mar 13 15:50:24.158 - [DEBUG] 63.117.68.25 fail:timeout('timed out',)
Mar 13 15:50:24.160 - [DEBUG] report_connect_fail:63.117.68.25
Mar 13 15:50:25.163 - [DEBUG] get ip:184.150.183.184 t:100
Mar 13 15:50:25.627 - [DEBUG] create_ssl update ip:201.157.30.53 time:800
Mar 13 15:50:25.647 - [DEBUG] get ip:200.77.168.153 t:100
Mar 13 15:50:25.995 - [DEBUG] 103.11.28.33 fail:timeout('timed out',)
Mar 13 15:50:25.997 - [DEBUG] report_connect_fail:103.11.28.33
Mar 13 15:50:26.066 - [WARNING] fetch gae status:400 url:https://clients2.google.com/service/update2
Mar 13 15:50:26.068 - [WARNING] IP:201.157.30.53 not support GAE, server type:
Mar 13 15:50:26.069 - [INFO] remove ip:201.157.30.53 left amount:1715 gws_num:1715
Mar 13 15:50:26.999 - [DEBUG] get ip:37.29.1.120 t:100
Mar 13 15:50:27.092 - [INFO] GAE CONNECT mtalk.google.com:5228
Mar 13 15:50:27.120 - [WARNING] parse request fail:)
Mar 13 15:50:28.125 - [DEBUG] 63.117.215.52 fail:timeout('timed out',)
Mar 13 15:50:28.126 - [DEBUG] report_connect_fail:63.117.215.52
Mar 13 15:50:28.149 - [DEBUG] get ip:202.67.41.179 t:100
Mar 13 15:50:28.162 - [DEBUG] 49.98.35.86 fail:timeout('timed out',)
Mar 13 15:50:28.163 - [DEBUG] report_connect_fail:49.98.35.86
Mar 13 15:50:28.251 - [DEBUG] get ip:193.134.255.88 t:100
Mar 13 15:50:28.907 - [DEBUG] 197.158.80.49 fail:timeout('timed out',)
Mar 13 15:50:28.910 - [DEBUG] report_connect_fail:197.158.80.49
Mar 13 15:50:28.954 - [DEBUG] get ip:201.67.193.109 t:100
Mar 13 15:50:28.977 - [DEBUG] network is ok, cost:68 ms
Mar 13 15:50:29.016 - [DEBUG] create ssl timeout fail.
Mar 13 15:50:29.017 - [DEBUG] create_ssl_connection fail
Mar 13 15:50:29.120 - [DEBUG] 41.221.196.55 fail:timeout('timed out',)
Mar 13 15:50:29.121 - [DEBUG] report_connect_fail:41.221.196.55
Mar 13 15:50:29.324 - [DEBUG] create ssl timeout fail.
Mar 13 15:50:29.326 - [DEBUG] create_ssl_connection fail
Mar 13 15:50:29.650 - [DEBUG] 200.77.168.153 fail:timeout('timed out',)
Mar 13 15:50:29.652 - [DEBUG] report_connect_fail:200.77.168.153
Mar 13 15:50:30.166 - [DEBUG] create ssl timeout fail.
Mar 13 15:50:30.167 - [DEBUG] create_ssl_connection fail
Mar 13 15:50:30.305 - [DEBUG] create ssl timeout fail.
Mar 13 15:50:30.307 - [DEBUG] create_ssl_connection fail
Mar 13 15:50:31.138 - [DEBUG] 37.29.1.120 fail:timeout('timed out',)
Mar 13 15:50:31.140 - [DEBUG] report_connect_fail:37.29.1.120
Mar 13 15:50:31.730 - [DEBUG] 184.150.183.184 fail:timeout('timed out',)
Mar 13 15:50:31.732 - [DEBUG] report_connect_fail:184.150.183.184
Mar 13 15:50:32.032 - [INFO] GAE CONNECT www.googleapis.com:443
Mar 13 15:50:32.073 - [DEBUG] GAE CONNECT POST https://www.googleapis.com/oauth2/v4/token
Mar 13 15:50:32.143 - [DEBUG] get ip:125.234.53.91 t:100
Mar 13 15:50:32.254 - [DEBUG] 193.134.255.88 fail:timeout('timed out',)
Mar 13 15:50:32.256 - [DEBUG] report_connect_fail:193.134.255.88
Mar 13 15:50:32.709 - [DEBUG] create_ssl update ip:49.231.60.213 time:849
Mar 13 15:50:32.734 - [DEBUG] get ip:189.63.251.175 t:100
Mar 13 15:50:32.957 - [DEBUG] 201.67.193.109 fail:timeout('timed out',)
Mar 13 15:50:32.958 - [DEBUG] report_connect_fail:201.67.193.109
Mar 13 15:50:33.142 - [WARNING] fetch gae status:400 url:https://clients4.google.com/chrome-sync/experimentstatus
Mar 13 15:50:33.143 - [WARNING] IP:49.231.60.213 not support GAE, server type:
Mar 13 15:50:33.146 - [INFO] remove ip:49.231.60.213 left amount:1714 gws_num:1714
Mar 13 15:50:33.655 - [DEBUG] 202.67.41.179 fail:timeout('timed out',)
Mar 13 15:50:33.656 - [DEBUG] report_connect_fail:202.67.41.179
Mar 13 15:50:33.950 - [DEBUG] 80.239.174.100 fail:timeout('timed out',)
Mar 13 15:50:33.952 - [DEBUG] report_connect_fail:80.239.174.100
Mar 13 15:50:34.057 - [DEBUG] get ip:71.19.176.243 t:100
Mar 13 15:50:34.158 - [DEBUG] get ip:189.63.251.176 t:100
Mar 13 15:50:34.159 - [DEBUG] 63.117.68.21 fail:timeout('timed out',)
Mar 13 15:50:34.162 - [DEBUG] report_connect_fail:63.117.68.21
Mar 13 15:50:34.260 - [DEBUG] get ip:208.117.245.41 t:100
Mar 13 15:50:34.361 - [DEBUG] get ip:189.247.148.17 t:100
Mar 13 15:50:34.464 - [DEBUG] get ip:202.67.41.178 t:100
Mar 13 15:50:34.490 - [DEBUG] create ssl timeout fail.
Mar 13 15:50:34.491 - [DEBUG] create_ssl_connection fail
Mar 13 15:50:34.565 - [DEBUG] get ip:31.55.163.187 t:100
Mar 13 15:50:34.666 - [DEBUG] get ip:31.55.162.145 t:100
Mar 13 15:50:35.163 - [DEBUG] get ip:4.31.115.206 t:100
Mar 13 15:50:35.734 - [DEBUG] 24.226.16.137 fail:timeout('timed out',)
Mar 13 15:50:35.735 - [DEBUG] report_connect_fail:24.226.16.137
Mar 13 15:50:36.738 - [DEBUG] 189.63.251.175 fail:timeout('timed out',)
Mar 13 15:50:36.747 - [DEBUG] report_connect_fail continue_fail_count:11
Mar 13 15:50:36.750 - [DEBUG] get ip:103.11.28.144 t:100
Mar 13 15:50:36.807 - [DEBUG] network is ok, cost:57 ms
Mar 13 15:50:37.100 - [DEBUG] 125.234.53.91 fail:timeout('timed out',)
Mar 13 15:50:37.101 - [DEBUG] report_connect_fail:125.234.53.91
Mar 13 15:50:37.753 - [DEBUG] get ip:103.11.28.145 t:100
Mar 13 15:50:38.061 - [DEBUG] 71.19.176.243 fail:timeout('timed out',)
Mar 13 15:50:38.061 - [DEBUG] report_connect_fail:71.19.176.243
Mar 13 15:50:38.085 - [DEBUG] get ip:208.54.64.54 t:100
Mar 13 15:50:38.104 - [DEBUG] get ip:103.11.28.147 t:100
Mar 13 15:50:38.262 - [DEBUG] 208.117.245.41 fail:timeout('timed out',)
Mar 13 15:50:38.263 - [DEBUG] report_connect_fail:208.117.245.41
Mar 13 15:50:38.288 - [DEBUG] get ip:200.28.6.92 t:100
Mar 13 15:50:40.184 - [DEBUG] 4.31.115.206 fail:timeout('timed out',)
Mar 13 15:50:40.185 - [DEBUG] report_connect_fail:4.31.115.206
Mar 13 15:50:40.751 - [DEBUG] 103.11.28.144 fail:timeout('timed out',)
Mar 13 15:50:40.752 - [DEBUG] report_connect_fail:103.11.28.144
Mar 13 15:50:41.105 - [DEBUG] 31.55.162.145 fail:timeout('timed out',)
Mar 13 15:50:41.106 - [DEBUG] report_connect_fail:31.55.162.145
Mar 13 15:50:41.144 - [DEBUG] 31.55.163.187 fail:timeout('timed out',)
Mar 13 15:50:41.145 - [DEBUG] report_connect_fail:31.55.163.187
Mar 13 15:50:41.186 - [DEBUG] get ip:190.211.175.25 t:100
Mar 13 15:50:41.207 - [DEBUG] get ip:103.11.28.149 t:100
Mar 13 15:50:41.309 - [DEBUG] get ip:189.63.251.175 t:100
Mar 13 15:50:41.754 - [DEBUG] get ip:4.35.2.179 t:100
Mar 13 15:50:42.088 - [DEBUG] 208.54.64.54 fail:timeout('timed out',)
Mar 13 15:50:42.091 - [DEBUG] report_connect_fail:208.54.64.54
Mar 13 15:50:42.284 - [DEBUG] GAEProxy web_control 127.0.0.1:62725 POST /config?cmd=get_config
Mar 13 15:50:42.307 - [DEBUG] 200.28.6.92 fail:timeout('timed out',)
Mar 13 15:50:42.307 - [DEBUG] report_connect_fail:200.28.6.92
Mar 13 15:50:42.339 - [INFO] GAE CONNECT clients1.google.com:443
Mar 13 15:50:42.356 - [DEBUG] GAE CONNECT POST https://clients1.google.com/tbproxy/af/query?client=Google%20Chrome
Mar 13 15:50:42.955 - [DEBUG] 202.67.41.178 fail:timeout('timed out',)
Mar 13 15:50:42.957 - [DEBUG] report_connect_fail:202.67.41.178
Mar 13 15:50:43.671 - [DEBUG] create_ssl update ip:103.11.28.145 time:5519
Mar 13 15:50:43.712 - [DEBUG] GAEProxy web_control 127.0.0.1:62725 POST /config?cmd=set_config
Mar 13 15:50:43.735 - [INFO] load google ip_list num:1714, gws num:1714
Mar 13 15:50:43.740 - [INFO] Adjust scan thread num from 20 to 0
Mar 13 15:50:44.329 - [DEBUG] create ssl timeout fail.
Mar 13 15:50:44.330 - [DEBUG] create_ssl_connection fail
Mar 13 15:50:44.330 - [DEBUG] GAE_Exception 2 'try max times'
Mar 13 15:50:44.332 - [WARNING] gae_exception:GAE_Exception() https://www.googleapis.com/oauth2/v4/token
Mar 13 15:50:44.674 - [DEBUG] get ip:189.194.54.79 t:100
Mar 13 15:50:44.754 - [DEBUG] 189.247.148.17 fail:timeout('timed out',)
Mar 13 15:50:44.754 - [DEBUG] report_connect_fail continue_fail_count:11
Mar 13 15:50:44.755 - [DEBUG] ssl_closed 189.247.148.17
Mar 13 15:50:44.827 - [DEBUG] network is ok, cost:71 ms
Mar 13 15:50:45.108 - [DEBUG] 189.63.251.176 fail:timeout('timed out',)
Mar 13 15:50:45.109 - [DEBUG] report_connect_fail:189.63.251.176
Mar 13 15:50:45.110 - [DEBUG] ssl_closed 189.63.251.176
Mar 13 15:50:45.169 - [DEBUG] create ssl timeout fail.
Mar 13 15:50:45.170 - [DEBUG] create_ssl_connection fail
Mar 13 15:50:45.172 - [DEBUG] GAE_Exception 2 'try max times'
Mar 13 15:50:45.173 - [WARNING] gae_exception:GAE_Exception() https://clients1.google.com/tbproxy/af/query?client=Google%20Chrome
Mar 13 15:50:45.190 - [DEBUG] 190.211.175.25 fail:timeout('timed out',)
Mar 13 15:50:45.190 - [DEBUG] report_connect_fail:190.211.175.25
Mar 13 15:50:45.193 - [DEBUG] ssl_closed 190.211.175.25
Mar 13 15:50:45.310 - [DEBUG] create ssl timeout fail.
Mar 13 15:50:45.311 - [DEBUG] create_ssl_connection fail
Mar 13 15:50:45.686 - [DEBUG] GAEProxy Web_control 127.0.0.1:62725 GET /deploy?cmd=get_log
Mar 13 15:50:46.097 - [DEBUG] 4.35.2.179 fail:timeout('timed out',)
Mar 13 15:50:46.098 - [DEBUG] report_connect_fail:4.35.2.179
Mar 13 15:50:46.100 - [DEBUG] ssl_closed 4.35.2.179
Mar 13 15:50:46.184 - [DEBUG] 189.63.251.175 fail:timeout('timed out',)
Mar 13 15:50:46.186 - [DEBUG] report_connect_fail:189.63.251.175
Mar 13 15:50:46.187 - [DEBUG] ssl_closed 189.63.251.175
Mar 13 15:50:46.194 - [DEBUG] get ip:41.77.223.225 t:100
Mar 13 15:50:46.411 - [DEBUG] get ip:201.227.61.33 t:100
Mar 13 15:50:46.413 - [INFO] GAE CONNECT www.googleapis.com:443
Mar 13 15:50:46.453 - [DEBUG] GAE CONNECT POST https://www.googleapis.com/oauth2/v4/token
Mar 13 15:50:46.512 - [DEBUG] get ip:182.79.251.20 t:100
Mar 13 15:50:46.615 - [DEBUG] get ip:67.50.19.18 t:100
Mar 13 15:50:46.687 - [DEBUG] GAEProxy Web_control 127.0.0.1:62725 GET /deploy?cmd=get_log
Mar 13 15:50:46.715 - [DEBUG] get ip:189.247.148.17 t:100
Mar 13 15:50:46.816 - [DEBUG] get ip:103.11.28.149 t:100
Mar 13 15:50:46.917 - [DEBUG] get ip:62.78.98.151 t:100
Mar 13 15:50:47.076 - [DEBUG] create ssl timeout fail.
Mar 13 15:50:47.076 - [DEBUG] create_ssl_connection fail
Mar 13 15:50:47.103 - [DEBUG] get ip:103.11.28.147 t:100
Mar 13 15:50:47.685 - [DEBUG] GAEProxy Web_control 127.0.0.1:62725 GET /deploy?cmd=get_log
Mar 13 15:50:48.675 - [DEBUG] 189.194.54.79 fail:timeout('timed out',)
Mar 13 15:50:48.677 - [DEBUG] report_connect_fail:189.194.54.79
Mar 13 15:50:48.694 - [DEBUG] GAEProxy Web_control 127.0.0.1:62725 GET /deploy?cmd=get_log
Mar 13 15:50:49.259 - [DEBUG] create ssl timeout fail.
Mar 13 15:50:49.260 - [DEBUG] create_ssl_connection fail
Mar 13 15:50:49.494 - [DEBUG] create ssl timeout fail.
Mar 13 15:50:49.495 - [DEBUG] create_ssl_connection fail
Mar 13 15:50:49.627 - [ERROR] request failed:[('SSL routines', 'SSL3_WRITE_BYTES', 'ssl handshake failure')]
Mar 13 15:50:49.631 - [ERROR] Except stack:Traceback (most recent call last): File "D:\download\XX-Net-2.9.4\gae_proxy\local\gae_handler.py", line 167, in request response = _request(ssl_sock, headers, payload) File "D:\download\XX-Net-2.9.4\gae_proxy\local\gae_handler.py", line 113, in _request sended = sock.send(payload[start:start+send_size]) File "D:\download\XX-Net-2.9.4\gae_proxy\local\openssl_wrap.py", line 78, in __send return self.__iowait(self._connection.send, data, flags) File "D:\download\XX-Net-2.9.4\gae_proxy\local\openssl_wrap.py", line 47, in __iowait return io_func(*args, **kwargs) Error: [('SSL routines', 'SSL3_WRITE_BYTES', 'ssl handshake failure')]

**Comment by RomainChan** [comment]
诊断在此
XX-Net Status：

sys-platform: AMD64, Windows-10-10.0.10586
os-system: Windows
os-version: 10.0.10586
os-release: 10
os-detail: Version:10-0; Build:10586; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.97 Safari/537.36
xxnet-version: 2.9.4
python-version: 2.7.11

ipv6-status: 0
gws-ip-num: 1671 / 1418
network-status: OK
connected-link: 0 / 0
scan-ip-thread-num: 0
ip-quality: 100
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by jzp820927** [comment]
[ERROR] request failed:[('SSL routines', 'SSL3_WRITE_BYTES', 'ssl handshake failure')]

ssl 握手失败，应该是没有可用IP吧

**Comment by RomainChan** [comment]
对对对对对对对，总也搜不到啊，难道只能用别人共享的吗

发自我的 iPhone

**Comment by RomainChan** [comment]
我都允许了一天了ip还是0，以前很快的

**Comment by jzp820927** [comment]
你是什么地区？什么网啊？现在可用IP还是蛮多的

**Comment by xxnet** [comment]
​不要倒入ip，重新扫描看看

**Comment by ztjal** [comment]
最近IP失效很快，感觉是以小时为单位的，我是限最大100个的，估计两天不扫的话90%都死了。

**Comment by RomainChan** [comment]
谢谢，我试试看 把ip删了重新扫描中
