### ISSUE TITLE
win7系统

### ISSUE THREAD

**Issue by thatluck** [XX-net/XX-Net#2340]
D:\XX-Net-2.5.1>SET PYTHONPATH=

D:\XX-Net-2.5.1>"D:\XX-Net-2.5.1\python27/1.0/python.exe" "D:\XX-Net-2.5.1\launc
her/start.py"
Traceback (most recent call last):
  File "D:\XX-Net-2.5.1\launcher/start.py", line 60, in <module>
    from win_tray import sys_tray
  File "D:\XX-Net-2.5.1\launcher\win_tray.py", line 146, in <module>
    sys_tray = Win_tray()
  File "D:\XX-Net-2.5.1\launcher\win_tray.py", line 40, in __init__
    self.on_enable_pac()
  File "D:\XX-Net-2.5.1\launcher\win_tray.py", line 113, in on_enable_pac
    win32_proxy_manager.set_proxy("http://127.0.0.1:8086/proxy.pac")
AttributeError: 'module' object has no attribute 'set_proxy'

D:\XX-Net-2.5.1>pause
请按任意键继续. . .

**Comment by jzp820927** [comment]
是不是在线升级导致的问题，重新下载最新版覆盖试试

**Comment by yeahwu** [comment]
应该是电脑防火墙的问题。你这个版本是怎么回事？2.5.1

**Comment by thatluck** [comment]
谢谢大家的关注，问题已解决，最新版本没有这个问题。
