### ISSUE TITLE
不知道为什么启动不起来了，提示：状态页显示空白, 很可能GAEProxy启动失败,

### ISSUE THREAD

**Issue by deviljz** [XX-net/XX-Net#2341]
提示：状态页显示空白, 很可能GAEProxy启动失败,

win10系统

运行start.bat的log如下
D:\Program Files (x86)\XX-Net-2.7.3>SET PYTHONPATH=

D:\Program Files (x86)\XX-Net-2.7.3>"D:\Program Files (x86)\XX-Net-2.7.3\python27/1.0/python.exe" "D:\Program Files (x86)\XX-Net-2.7.3\launcher/start.py"
Mar 13 19:10:16 - [INFO] start XX-Net 2.9.2
Mar 13 19:10:16 - [DEBUG] start confirm_xxnet_exit
Mar 13 19:10:17 - [DEBUG] good, xxnet:8087 cleared!
Mar 13 19:10:18 - [DEBUG] <0>: try to terminate xxnet:8085
Mar 13 19:10:20 - [DEBUG] good, xxnet:8085 clear!
Mar 13 19:10:20 - [DEBUG] finished confirm_xxnet_exit
Mar 13 19:10:20 - [ERROR] start module gae_proxy fail:'str' object is not callable
Traceback (most recent call last):
  File "D:\Program Files (x86)\XX-Net-2.7.3\launcher\module_init.py", line 37, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "D:\Program Files (x86)\XX-Net-2.7.3\gae_proxy\start.py", line 14, in <module>
    import local.proxy as client
  File "D:\Program Files (x86)\XX-Net-2.7.3\gae_proxy\local\proxy.py", line 74, in <module>
    from cert_util import CertUtil
  File "D:\Program Files (x86)\XX-Net-2.7.3\gae_proxy\local\cert_util.py", line 36, in <module>
    xlog = getLogger("gae_proxy")
  File "D:\Program Files (x86)\XX-Net-2.7.3\gae_proxy\local\xlog.py", line 56, in getLogger
    return cls(*args, **kwargs)
TypeError: 'str' object is not callable

Mar 13 19:10:20 - [INFO] start gae_proxy time cost 34
Mar 13 19:10:20 - [INFO] begin to start web control
Mar 13 19:10:20 - [INFO] launcher web control started.
Mar 13 19:10:20 - [WARNING] request module:gae_proxy start fail
Mar 13 19:10:21 - [WARNING] request module:gae_proxy start fail
Mar 13 19:10:21 - [INFO] get uuid:545f045b-82e3-41c2-bb84-9768e363f132
Mar 13 19:10:22 - [WARNING] request module:gae_proxy start fail
Mar 13 19:10:22 - [WARNING] check_update fail:URLError(error(10061, ''),)
Mar 13 19:10:23 - [INFO] download https://raw.githubusercontent.com/XX-net/XX-Net/master/README.md to D:\Program Files (x86)\XX-Net-2.7.3\data\downloads\README.md, retry:0
Mar 13 19:10:23 - [WARNING] request module:gae_proxy start fail
Mar 13 19:10:24 - [WARNING] request module:gae_proxy start fail
Mar 13 19:10:25 - [WARNING] request module:gae_proxy start fail
Mar 13 19:10:27 - [WARNING] request module:gae_proxy start fail
Mar 13 19:10:36 - [WARNING] request module:gae_proxy start fail
Mar 13 19:10:36 - [WARNING] request module:gae_proxy start fail
Mar 13 19:10:36 - [WARNING] request module:gae_proxy start fail
Mar 13 19:10:36 - [WARNING] request module:gae_proxy start fail
Mar 13 19:10:36 - [WARNING] request module:gae_proxy start fail
Mar 13 19:10:36 - [WARNING] request module:gae_proxy start fail
Mar 13 19:10:36 - [WARNING] request module:gae_proxy start fail
Mar 13 19:10:36 - [WARNING] request module:gae_proxy start fail
Mar 13 19:10:36 - [WARNING] request module:gae_proxy start fail
Mar 13 19:10:37 - [WARNING] request module:gae_proxy start fail
Mar 13 19:10:38 - [WARNING] request module:gae_proxy start fail
Mar 13 19:10:39 - [WARNING] request module:gae_proxy start fail
Mar 13 19:10:40 - [WARNING] request module:gae_proxy start fail
Mar 13 19:10:41 - [WARNING] request module:gae_proxy start fail

**Comment by deviljz** [comment]
我更新到2.9.2版本又正常了

**Comment by jzp820927** [comment]
估计是自动更新造成的，建议直接下载最新版覆盖运行
