### ISSUE TITLE
Archlinux 打开start.sh后报错，好象是openssl问题？

### ISSUE THREAD

**Issue by sxq112358** [XX-net/XX-Net#2342]
从几天前开始就一直这样o_0
不仅仅是2.9.4这个版本。。我试了之前用的2.3.0，windows上用的2.9.0都出现这个错误
难道说是arch太激进，更新了什么东西?不是很懂o_0

错误信息：

3月 13 20:37:44.18 - [WARNING] import pynotify fail, please install python-notify if possiable.
3月 13 20:37:44.24 - [INFO] start XX-Net 2.9.4
3月 13 20:37:44.24 - [DEBUG] start confirm_xxnet_exit
3月 13 20:37:44.24 - [DEBUG] good, xxnet:8087 cleared!
3月 13 20:37:44.24 - [DEBUG] good, xxnet:8085 clear!
3月 13 20:37:44.24 - [DEBUG] finished confirm_xxnet_exit
3月 13 20:37:44.26 - [ERROR] start module gae_proxy fail:/home/cirno/Downloads/XX-Net-2.9.4/python27/1.0/lib/linux/OpenSSL/SSL.so: symbol SSLv3_method, version OPENSSL_1.0.0 not defined in file libssl.so.1.0.0 with link time reference
3月 13 20:37:44.26 - [ERROR] Except stack:Traceback (most recent call last):
  File "/home/cirno/Downloads/XX-Net-2.9.4/launcher/module_init.py", line 37, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "/home/cirno/Downloads/XX-Net-2.9.4/gae_proxy/start.py", line 14, in <module>
    import local.proxy as client
  File "/home/cirno/Downloads/XX-Net-2.9.4/gae_proxy/local/proxy.py", line 95, in <module>
    from cert_util import CertUtil
  File "/home/cirno/Downloads/XX-Net-2.9.4/gae_proxy/local/cert_util.py", line 38, in <module>
    import OpenSSL
  File "/home/cirno/Downloads/XX-Net-2.9.4/python27/1.0/lib/linux/OpenSSL/__init__.py", line 41, in <module>
    from OpenSSL import rand, SSL
ImportError: /home/cirno/Downloads/XX-Net-2.9.4/python27/1.0/lib/linux/OpenSSL/SSL.so: symbol SSLv3_method, version OPENSSL_1.0.0 not defined in file libssl.so.1.0.0 with link time reference

Traceback (most recent call last):
  File "launcher/start.py", line 132, in <module>
    main()
  File "launcher/start.py", line 107, in main
    module_init.start_all_auto()
  File "/home/cirno/Downloads/XX-Net-2.9.4/launcher/module_init.py", line 98, in start_all_auto
    start(module)
  File "/home/cirno/Downloads/XX-Net-2.9.4/launcher/module_init.py", line 37, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "/home/cirno/Downloads/XX-Net-2.9.4/gae_proxy/start.py", line 14, in <module>
    import local.proxy as client
  File "/home/cirno/Downloads/XX-Net-2.9.4/gae_proxy/local/proxy.py", line 95, in <module>
    from cert_util import CertUtil
  File "/home/cirno/Downloads/XX-Net-2.9.4/gae_proxy/local/cert_util.py", line 38, in <module>
    import OpenSSL
  File "/home/cirno/Downloads/XX-Net-2.9.4/python27/1.0/lib/linux/OpenSSL/__init__.py", line 41, in <module>
    from OpenSSL import rand, SSL
ImportError: /home/cirno/Downloads/XX-Net-2.9.4/python27/1.0/lib/linux/OpenSSL/SSL.so: symbol SSLv3_method, version OPENSSL_1.0.0 not defined in file libssl.so.1.0.0 with link time reference
Stopping all modules before exit!
3月 13 20:37:44.26 - [ERROR] stop module gae_proxy fail:'imp'
3月 13 20:37:44.26 - [ERROR] Except stack:Traceback (most recent call last):
  File "/home/cirno/Downloads/XX-Net-2.9.4/launcher/module_init.py", line 71, in stop
    _start = proc_handler[module]["imp"].start
KeyError: 'imp'

**Comment by nicegoing** [comment]
和我一样的情况。[#2241](https://github.com/XX-net/XX-Net/issues/2241)

**Comment by sxq112358** [comment]
@nicegoing 非常感谢，安装python2-pyopenssl后已经解决
