### ISSUE TITLE
win32_proxy_manager.set_proxy 错误  'module' object has no attribute 'set_proxy'

### ISSUE THREAD

**Issue by wangshaochun** [XX-net/XX-Net#2348]
错误消息
F:\XX-Net-2.7.3>"F:\XX-Net-2.7.3\python27/1.0/python.exe" "F:\XX-Net-2.7.3\launcher/start.py"
Traceback (most recent call last):
  File "F:\XX-Net-2.7.3\launcher/start.py", line 60, in <module>
    from win_tray import sys_tray
  File "F:\XX-Net-2.7.3\launcher\win_tray.py", line 146, in <module>
    sys_tray = Win_tray()
  File "F:\XX-Net-2.7.3\launcher\win_tray.py", line 40, in __init__
    self.on_enable_pac()
  File "F:\XX-Net-2.7.3\launcher\win_tray.py", line 113, in on_enable_pac
    win32_proxy_manager.set_proxy("http://127.0.0.1:8086/proxy.pac")
AttributeError: 'module' object has no attribute 'set_proxy'

**Comment by wangshaochun** [comment]
https://github.com/XX-net/XX-Net/issues/2320
