### ISSUE TITLE
全局PAC智能代理为什么切换不过来

### ISSUE THREAD

**Issue by markwu414102** [XX-net/XX-Net#2390]
现在只能用浏览器访问外国网站，别的软件不能浏览了

**Comment by markwu414102** [comment]
```
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 314, in 'calling callback function'
  File "D:\XX-Net-2.8.9\python27\1.0\lib\win32\systray\traybar.py", line 83, in
WndProc
    self._message_dict[msg](hwnd, msg, wparam.value, lparam.value)
  File "D:\XX-Net-2.8.9\python27\1.0\lib\win32\systray\traybar.py", line 271, in
 _command
    self._execute_menu_option(id)
  File "D:\XX-Net-2.8.9\python27\1.0\lib\win32\systray\traybar.py", line 278, in
 _execute_menu_option
    menu_action(self)
  File "D:\XX-Net-2.8.9\launcher\win_tray.py", line 113, in on_enable_pac
    win32_proxy_manager.set_proxy("http://127.0.0.1:8086/proxy.pac")
AttributeError: 'module' object has no attribute 'set_proxy'
```
版本：2.93

**Comment by jzp820927** [comment]
下载最新版覆盖试试，是不是自动升级的问题

**Comment by markwu414102** [comment]
下载了稳定版可以了
