### ISSUE TITLE
python3 分支

### ISSUE THREAD

**Issue by xxnet** [XX-net/XX-Net#2402]
python3分支launcher和GAE_proxy、部署服务端都可以工作了。
x_tunnel/php_proxy还未处理。

大家跑跑看有什么问题，反馈到这里:  
https://github.com/XX-net/XX-Net/archive/python3.zip

**Comment by caofengzi** [comment]
win7/32錯誤報告。〉無法啟動此程序，因為計算機中丟失〉api-ms-crt-runtime-|1-1-0.dll

**Comment by yeahwu** [comment]
报错，如图，另外提交了一个哪啥……
![23333](https://cloud.githubusercontent.com/assets/13328328/13840096/2fda98a6-ec5b-11e5-95d5-c1a385e5cc4c.JPG)

**Comment by xxnet** [comment]
​可能python3 的win32 运行环境有问题，可以去下个标准的python3.4 的运行环境，试试看

**Comment by Suwmlee** [comment]
我是在win10下测试的，用的是python35（vs2015编译的版本）没有遇到问题。
 [stackoverflow解答](http://stackoverflow.com/questions/33265663/api-ms-win-crt-runtime-l1-1-0-dll-is-missing-when-open-office-file)

**Comment by xxnet** [comment]
​是不是需要安装布丁，最好能够让新手不用去处理这种细节

**Comment by Suwmlee** [comment]
恩，这个问题解决方法是安装Visual C++ Redistributable 2015。
因为python35版本使用vs2015编译的，在win10中依赖环境是默认安装的，win10以下版本可能需要安装。
因为python无法运行，只能在bat中看看如果处理了

**Comment by xxnet** [comment]
​需要的文件多大？
之前也试过把VC的运行环境库打包在包里

**Comment by yeahwu** [comment]
O了，其实啥事也没干，就是打开windwos update更新鸟几十个文件，然后把xx-net多重启几次就好鸟。

**Comment by Suwmlee** [comment]
大约有13M..我看下还有没有其他的方案.

默认的xtunnel好像是开的，需要关闭。

**Comment by yeahwu** [comment]
data/launcher/config.yaml 里把1改为0就关鸟
```
x_tunnel: {auto_start: 1}
```
然后整个太粗糙鸟，start.vbs无效等

**Comment by caofengzi** [comment]
俺为什么安装不了 Visual C++ Redistributable 2015呢？win7/32。弄了很久，每次安装完系统就提示修复。

Sent using CloudMagic Email [https://cloudmagic.com/k/d/mailapp?ct=pa&cv=8.2.23&pv=4.4.4&source=email_footer_2] On 周四, 3月 17, 2016 at 5:36 下午, Suwmlee < notifications@github.com [notifications@github.com] > wrote:
恩，这个问题解决方法是安装Visual C++ Redistributable 2015。
因为python35版本使用vs2015编译的，在win10中依赖环境是默认安装的，win10以下版本可能需要安装。
因为python无法运行，只能在bat中看看如果处理了

**Comment by yeahwu** [comment]
然后，俺是win7

**Comment by caofengzi** [comment]
y老大一共更新了多少个文件啊？

Sent using CloudMagic Email [https://cloudmagic.com/k/d/mailapp?ct=pa&cv=8.2.23&pv=4.4.4&source=email_footer_2] On 周四, 3月 17, 2016 at 7:12 下午, YeahWu < notifications@github.com [notifications@github.com] > wrote:
O了，其实啥事也没干，就是打开windwos update更新鸟几十个文件，然后把xx-net多重启几次就好鸟。

**Comment by yeahwu** [comment]
@caofengzi 打开系统windwos update，把该更新的文件，该打的补丁全部打上，重启，再试试

**Comment by yeahwu** [comment]
@caofengzi 俺只打了重要的补丁，几十个吧。这些个补丁随便打，没问题的。

**Comment by Suwmlee** [comment]
@caofengzi  找KB2999226补丁试一试。

**Comment by caofengzi** [comment]
谢谢老大们啊！哈哈

Sent using CloudMagic Email [https://cloudmagic.com/k/d/mailapp?ct=pa&cv=8.2.23&pv=4.4.4&source=email_footer_2] On 周四, 3月 17, 2016 at 7:38 下午, Suwmlee < notifications@github.com [notifications@github.com] > wrote:
@caofengzi [https://github.com/caofengzi] 找KB2999226补丁试一试。

**Comment by renyouguo** [comment]
是不是需要很两个版本，一个集成运行环境，一个win10无需版。

**Comment by yeahwu** [comment]
刚试了ubuntu 14.04版 32位  报错如下
```
will@ubuntu:~$ cd /home/will/xxx
will@ubuntu:~/xxx$ ./start.sh
Mar 17 20:05:57.248 - [WARNING] import pynotify fail, please install python-notify if possiable.
Mar 17 20:05:57.458 - [INFO] start XX-Net get_version_fail
Mar 17 20:05:57.459 - [DEBUG] start confirm_xxnet_exit
Mar 17 20:05:57.479 - [DEBUG] good, xxnet:8087 cleared!
Mar 17 20:05:57.481 - [DEBUG] good, xxnet:8085 clear!
Mar 17 20:05:57.482 - [DEBUG] finished confirm_xxnet_exit
Mar 17 20:05:57.508 - [INFO] load config.ini success
Mar 17 20:05:57.514 - [ERROR] start module gae_proxy fail:No module named 'OpenSSL'
Mar 17 20:05:57.516 - [ERROR] Except stack:Traceback (most recent call last):
  File "/home/will/xxx/launcher/module_init.py", line 37, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['start'], 0)
  File "/home/will/xxx/gae_proxy/start.py", line 14, in <module>
    import local.proxy as client
  File "/home/will/xxx/gae_proxy/local/proxy.py", line 100, in <module>
    from local.cert_util import CertUtil
  File "/home/will/xxx/gae_proxy/local/cert_util.py", line 42, in <module>
    import OpenSSL
ImportError: No module named 'OpenSSL'

Traceback (most recent call last):
  File "launcher/start.py", line 132, in <module>
    main()
  File "launcher/start.py", line 107, in main
    module_init.start_all_auto()
  File "/home/will/xxx/launcher/module_init.py", line 98, in start_all_auto
    start(module)
  File "/home/will/xxx/launcher/module_init.py", line 37, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['start'], 0)
  File "/home/will/xxx/gae_proxy/start.py", line 14, in <module>
    import local.proxy as client
  File "/home/will/xxx/gae_proxy/local/proxy.py", line 100, in <module>
    from local.cert_util import CertUtil
  File "/home/will/xxx/gae_proxy/local/cert_util.py", line 42, in <module>
    import OpenSSL
ImportError: No module named 'OpenSSL'
Stopping all modules before exit!
Mar 17 20:05:57.580 - [ERROR] stop module gae_proxy fail:'imp'
Mar 17 20:05:57.580 - [ERROR] Except stack:Traceback (most recent call last):
  File "/home/will/xxx/launcher/module_init.py", line 71, in stop
    _start = proc_handler[module]["imp"].start
KeyError: 'imp'
```

**Comment by renyouguo** [comment]
还有能否借此机会编译出winx64版？

**Comment by Suwmlee** [comment]
@yeahwu ImportError:  ``No module named 'OpenSSL'``
python3需要安装pyOpenSSL
```sh
pip3 install pyOpenSSL
```

**Comment by yeahwu** [comment]
放弃鸟，ubuntu发行版装不上
linux mint版装上了pyOpenSSL还是一样报错
崩溃

**Comment by linhua55** [comment]
dll和exe文件可用[UPX](http://upx.sourceforge.net)压缩一下

**Comment by jzp820927** [comment]
root@trsb-cardmgr:~/XX-Net-python3# ./start.sh
Mar 17 21:54:51.086 - [INFO] start XX-Net get_version_fail
Mar 17 21:54:51.086 - [DEBUG] start confirm_xxnet_exit
Mar 17 21:54:51.090 - [DEBUG] good, xxnet:8087 cleared!
Mar 17 21:54:51.091 - [DEBUG] good, xxnet:8085 clear!
Mar 17 21:54:51.091 - [DEBUG] finished confirm_xxnet_exit
Mar 17 21:54:51.097 - [ERROR] start module x_tunnel fail:No module named 'proxy_handler'
Mar 17 21:54:51.097 - [ERROR] Except stack:Traceback (most recent call last):
  File "/root/XX-Net-python3/launcher/module_init.py", line 37, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['start'], 0)
  File "/root/XX-Net-python3/x_tunnel/start.py", line 14, in <module>
    import local.client as client
  File "/root/XX-Net-python3/x_tunnel/local/client.py", line 38, in <module>
    from proxy_handler import Socks5Server
ImportError: No module named 'proxy_handler'

Traceback (most recent call last):
  File "launcher/start.py", line 132, in <module>
    main()
  File "launcher/start.py", line 107, in main
    module_init.start_all_auto()
  File "/root/XX-Net-python3/launcher/module_init.py", line 98, in start_all_auto
    start(module)
  File "/root/XX-Net-python3/launcher/module_init.py", line 37, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['start'], 0)
  File "/root/XX-Net-python3/x_tunnel/start.py", line 14, in <module>
    import local.client as client
  File "/root/XX-Net-python3/x_tunnel/local/client.py", line 38, in <module>
    from proxy_handler import Socks5Server
ImportError: No module named 'proxy_handler'
Stopping all modules before exit!
Mar 17 21:54:51.143 - [ERROR] stop module x_tunnel fail:'imp'
Mar 17 21:54:51.143 - [ERROR] Except stack:Traceback (most recent call last):
  File "/root/XX-Net-python3/launcher/module_init.py", line 71, in stop
    _start = proc_handler[module]["imp"].start
KeyError: 'imp'

ubuntu server 15.10 x64  ，pip3 install pyOpenSSL ，已经安装。

**Comment by jzp820927** [comment]
OK，搞定，完美运行。
系统：ubuntu server 15.10 x64
安装依赖：pip3 install pyOpenSSL
关闭 x_tunnel 的自动启动，不然会报下面的错误。
 [ERROR] start module x_tunnel fail:No module named 'proxy_handler'

运行日志：
root@ubuntu:~/XX-Net-python3# ./start.sh
Mar 17 22:05:27.920 - [INFO] start XX-Net get_version_fail
Mar 17 22:05:27.920 - [DEBUG] start confirm_xxnet_exit
Mar 17 22:05:27.930 - [DEBUG] good, xxnet:8087 cleared!
Mar 17 22:05:27.932 - [DEBUG] good, xxnet:8085 clear!
Mar 17 22:05:27.932 - [DEBUG] finished confirm_xxnet_exit
Mar 17 22:05:27.941 - [INFO] load config.ini success
Mar 17 22:05:27.942 - [INFO] load manual.ini success
Mar 17 22:05:28.239 - [DEBUG] network is ok, cost:194 ms
Mar 17 22:05:28.251 - [INFO] SSL use version:TLSv1_2
Mar 17 22:05:28.255 - [INFO] load ip range file:/root/XX-Net-python3/data/gae_proxy/ip_range.txt
Mar 17 22:05:28.284 - [INFO] load google ip_list num:3000, gws num:3000
Mar 17 22:05:28.310 - [INFO] load config.ini success
Mar 17 22:05:28.312 - [INFO] load manual.ini success
Mar 17 22:05:28.313 - [DEBUG] ## GAEProxy set keep_running: True
Mar 17 22:05:28.319 - [INFO] ------------------------------------------------------
Mar 17 22:05:28.319 - [INFO] Python Version     : 3.4.3+
Mar 17 22:05:28.320 - [INFO] OS                 : Dist:Ubuntu; Version:15.10; ID:wily
Mar 17 22:05:28.320 - [INFO] Listen Address     : 0.0.0.0:8086
Mar 17 22:05:28.320 - [INFO] GAE APPID          : xxnet-jzp-1|xxnet-jzp-2|xxnet-jzp-3|xxnet-jzp-4|xxnet-jzp-5
Mar 17 22:05:28.320 - [INFO] ------------------------------------------------------
Mar 17 22:05:28.329 - [INFO] server 0.0.0.0:8086 started.
Mar 17 22:05:28.395 - [DEBUG] get ip:45.64.28.43 t:112
Mar 17 22:05:28.408 - [INFO] module gae_proxy started
Mar 17 22:05:28.408 - [INFO] start gae_proxy time cost 476
Mar 17 22:05:28.411 - [INFO] module php_proxy started
Mar 17 22:05:28.411 - [INFO] start php_proxy time cost 2
Mar 17 22:05:28.412 - [INFO] begin to start web control
Mar 17 22:05:28.412 - [INFO] server 0.0.0.0:8085 started.
Mar 17 22:05:28.415 - [INFO] launcher web control started.
Mar 17 22:05:28.420 - [INFO] generate desktop shortcut
Mar 17 22:05:28.506 - [DEBUG] get ip:45.64.28.13 t:149

**Comment by caofengzi** [comment]
@Suwmlee 謝謝老大的解答，俺這個是系統版本低低原因報錯，重新換了一個版本低系統可以運行了。

**Comment by yeahwu** [comment]
@Suwmlee 感觉这个萌萌的小眼睛，是谁的小号！

**Comment by ztjal** [comment]
python3官方有一种embeddable的版本，极好的方式，直接将py生成pyd再打包到zip里边，建议py3分支的版本稳定后也试下用这种方式打包。

**Comment by xxnet** [comment]
​手机版可以这么干

**Comment by renyouguo** [comment]
@xxnet X-Tunnel 能否开放自己搭服务器？能否直接利用现有的ss服务器？

**Comment by xxnet** [comment]
如果私用，我可以提供另一套系统，可以替换ss，如果ss被封了的话。
如果要卖VPN/SS，我直接提供服务，价格按批发价供应，只在VPS的流量价格上收15%的维护费，要怎么卖代理商定价，包括怎么做套餐，也可以订制。

**Comment by yeahwu** [comment]
@xxnet 要不要在俺群里给你打打广告？呵呵

**Comment by xxnet** [comment]
好啊，看看有没有市场，哈哈

**Comment by simonasd** [comment]
@xxnet

首先声明不是我不支持创收啊。。。但是像我这样的人肯定还是更喜欢使用自建、自行维护的服务。别的不说，统一都使用您的服务，万一哪天您被捕或者服务端被黑了，一大票用户都要倒霉。尤其是用户里面如果有敏感人士的话。

目前的一些方案虽然很适合自有VPS，但是都存在单一IP容易被封锁的问题。能借助GAE转发还是很不错的。

**Comment by gxz1989611** [comment]
mac 10.11.4暂时无法执行，看了下mac系统没有安装python3的库，然后xxnet自带的python3只有win下的可执行程序~我懒得再在mac配置python3了，python2的版本目前用的非常顺畅~
