### ISSUE TITLE
PHP代理无法访问HTTPS和SSL站点问题（非证书问题）

### ISSUE THREAD

**Issue by HappysurfBlocking** [XX-net/XX-Net#2431]
当我试图连接http站点，可以正常访问网页，
Mar 19 14:25:38 - [INFO] ------------------------------------------------------
PHP Proxy Version    : 3.2.3 (python/2.7.11 gevent/1.0.1 pyopenssl/0.13.1)
PHP Listen         : 127.0.0.1:8088
PHP FetchServers   : ['https://happysurf-happyblog.rhcloud.com/xxnet-php/']
------------------------------------------------------
Mar 19 14:26:13 - [INFO] 127.0.0.1:1471 "PHP GET http://www.baidu.com/ HTTP/1.1" 200 
当我尝试连接https站点便会得到ERR_CONNECTION_CLOSED的提示，伴随着日志记录：
Mar 19 14:28:39 - [INFO] 127.0.0.1:2185 "STRIP CONNECT beacons.gvt2.com:443 HTTP/1.1" - -
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 2185)
Traceback (most recent call last):
  File "D:\Program Files (x86)\Anti-GFW\XX-Net\python27\1.0\lib\SocketServer.py", line 599, in process_request_thread
    self.finish_request(request, client_address)
  File "D:\Program Files (x86)\Anti-GFW\XX-Net\php_proxy\local\proxylib.py", line 619, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "D:\Program Files (x86)\Anti-GFW\XX-Net\php_proxy\local\proxy.py", line 764, in __init__
    SimpleProxyHandler.__init__(self, *args, **kwargs)
  File "D:\Program Files (x86)\Anti-GFW\XX-Net\python27\1.0\lib\SocketServer.py", line 655, in __init__
    self.handle()
  File "D:\Program Files (x86)\Anti-GFW\XX-Net\python27\1.0\lib\BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "D:\Program Files (x86)\Anti-GFW\XX-Net\php_proxy\local\proxylib.py", line 1295, in handle_one_request
    return BaseHTTPServer.BaseHTTPRequestHandler.handle_one_request(self)
  File "D:\Program Files (x86)\Anti-GFW\XX-Net\python27\1.0\lib\BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "D:\Program Files (x86)\Anti-GFW\XX-Net\php_proxy\local\proxylib.py", line 1326, in do_METHOD
    return plugin.handle(self, **action[1])
  File "D:\Program Files (x86)\Anti-GFW\XX-Net\php_proxy\local\proxylib.py", line 726, in handle
    self.do_ssl_handshake(handler)
  File "D:\Program Files (x86)\Anti-GFW\XX-Net\php_proxy\local\proxylib.py", line 713, in do_ssl_handshake
    ssl_sock = ssl.wrap_socket(handler.connection, keyfile=certfile, certfile=certfile, server_side=True, ssl_version=self.ssl_method, ciphers=self.ciphers)
  File "D:\Program Files (x86)\Anti-GFW\XX-Net\python27\1.0\lib\win32\gevent\ssl.py", line 383, in wrap_socket
    ciphers=ciphers)
  File "D:\Program Files (x86)\Anti-GFW\XX-Net\python27\1.0\lib\win32\gevent\ssl.py", line 89, in __init__
    self._sslobj = _ssl.sslwrap(self._sock, server_side,
AttributeError: 'module' object has no attribute 'sslwrap'
但是，当我将我使用的PHP代理地址访入以前的GAEProxy中时，能正常使用：
------------------------------------------------------
GoProxy Version    : r169 (go/go1.5.1 windows/386)
Listen Address     : 127.0.0.1:8080
RoundTrip Filters  : autoproxy,php,direct
Pac Server         : http://127.0.0.1:8080/proxy.pac
------------------------------------------------------
I0319 14:30:07.044243    5532 autoproxy.go:134] start updater for &autoproxy.GFWList{URL:(*url.URL)(0x12b97080), Filename:"gfwlist.txt", Encoding:"base64", Duration:86400000000000}
I0319 14:30:07.080326    5532 main.go:177] ListenAndServe on 127.0.0.1:8080
I0319 14:30:15.116781    5532 stripssl.go:126] 127.0.0.1:2518 "STRIP CONNECT www.google.com.hk:443 HTTP/1.1" - -
I0319 14:30:17.116962    5532 stripssl.go:126] 127.0.0.1:2530 "STRIP CONNECT www.baidu.com:443 HTTP/1.1" - -
I0319 14:30:19.830419    5532 php.go:124] 127.0.0.1:2518 "PHP POST https://www.google.com.hk/domainreliability/upload HTTP/1.1" 200 319
这应该是个BUG，以前是没有的，望修复。
XX-Net Version	2.9.2
Python Version	2.7.11
System Platform	AMD64, Windows-10-10.0.10586
OS System	Windows
OS Version	10.0.10586
OS Release	10
OS Detail	Version:10-0; Build:10586; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
Language	zh_CN
Architecture	32bit,WindowsPE
Browser	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.75 Safari/537.36

**Comment by xxx233** [comment]
用的什么空间？既然goproxy能用，干嘛不直接用goproxy，据我所知，“狗屁”的php优化得很不错。
而且这两种好像也不可以通用吧，一个是golang写的，一个python写的。
