### ISSUE TITLE
双击start.vbs没有反应

### ISSUE THREAD

**Issue by lwhgeren** [XX-net/XX-Net#2462]
因为原先的版本自动更新失败，所以手动下载最新版2.9.2，解压至C/program files文件夹，将原先的版本手动删除（手贱啊！！）然后双击start.vbs就没有反应了，不知何故，请高手解答，谢谢！！
双击start.bat 报错如下:
C:\Program Files (x86)\XX-Net-2.9.4>SET PYTHONPATH=

C:\Program Files (x86)\XX-Net-2.9.4>"C:\Program Files (x86)\XX-Net-2.9.4\python27/1.0/python.exe" "C:\Program Files (x86)\XX-Net-2.9.4\launcher/start.py"
Traceback (most recent call last):
  File "C:\Program Files (x86)\XX-Net-2.9.4\launcher/start.py", line 32, in <module>
    create_data_path()
  File "C:\Program Files (x86)\XX-Net-2.9.4\launcher/start.py", line 24, in create_data_path
    os.mkdir(data_path)
WindowsError: [Error 5] : 'C:\\Program Files (x86)\\XX-Net-2.9.4\\data'

C:\Program Files (x86)\XX-Net-2.9.4>pause

**Comment by lwhgeren** [comment]
自己已经解决，参考论坛中的一些见解，应以管理员身份运行start.bat
