### ISSUE TITLE
【日志】X-Tunnel 连接故障

### ISSUE THREAD

**Issue by kittycheny** [XX-net/XX-Net#2464]
X-Tunnel 在连接时反复报错，无法正常使用，求助。

附上错误日志：

Mar 22 12:33:45.918 - [ERROR] socks handler read error error('recv fail',)
Mar 22 12:33:45.918 - [ERROR] socks handler read error error('recv fail',)
Mar 22 12:33:45.918 - [ERROR] Except stack:Traceback (most recent call last): File "E:\XX-Net\x_tunnel\local\proxy_handler.py", line 29, in handle self.socks5_handler() File "E:\XX-Net\x_tunnel\local\proxy_handler.py", line 127, in socks5_handler data = self.read_bytes(4) File "E:\XX-Net\x_tunnel\local\proxy_handler.py", line 69, in read_bytes raise socket.error("recv fail") error: recv fail
Mar 22 12:33:45.918 - [ERROR] Except stack:Traceback (most recent call last): File "E:\XX-Net\x_tunnel\local\proxy_handler.py", line 29, in handle self.socks5_handler() File "E:\XX-Net\x_tunnel\local\proxy_handler.py", line 127, in socks5_handler data = self.read_bytes(4) File "E:\XX-Net\x_tunnel\local\proxy_handler.py", line 69, in read_bytes raise socket.error("recv fail") error: recv fail

Mar 22 12:33:49.885 - [ERROR] socks handler read error error('recv fail',)
Mar 22 12:33:49.885 - [ERROR] Except stack:Traceback (most recent call last): File "E:\XX-Net\x_tunnel\local\proxy_handler.py", line 29, in handle self.socks5_handler() File "E:\XX-Net\x_tunnel\local\proxy_handler.py", line 127, in socks5_handler data = self.read_bytes(4) File "E:\XX-Net\x_tunnel\local\proxy_handler.py", line 69, in read_bytes raise socket.error("recv fail") error: recv fail

附上X-TUNNEL连接信息：
Mar 22 10:02:45.809 - [INFO] Use proxy:127.0.0.1:8087
Mar 22 10:02:46.589 - [INFO] api:login success t:779
Mar 22 10:02:46.589 - [INFO] update xt_server 104.207.140.47:6666
Mar 22 10:02:46.589 - [INFO] request_balance host:104.207.140.47 port:6666 balance:0.000000 quota:18562822250.000000
Mar 22 10:02:46.917 - [INFO] login_session time:328 msg:Success
Mar 22 10:02:46.917 - [INFO] Socks5 server listen:0.0.0.0:1080.
Mar 22 10:03:07.886 - [DEBUG] x_tunnel force update info
Mar 22 10:03:08.195 - [INFO] api:login success t:309
Mar 22 10:03:08.195 - [INFO] request_balance host:104.207.140.47 port:6666 balance:0.000000 quota:18562822250.000000
Mar 22 12:32:49.995 - [INFO] Use proxy:127.0.0.1:8087
Mar 22 12:32:51.894 - [INFO] login_session time:1884 msg:Success
Mar 22 12:32:51.894 - [INFO] Socks5 server listen:0.0.0.0:1080.

附上XX-Net/goagent连接诊断信息：
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.37 Safari/537.36
xxnet-version: get_version_fail
python-version: 2.7.11

ipv6-status: 0
gws-ip-num: total:1896 good:162
network-status: OK
connected-link: new:9 used:2
scan-ip-thread-num: 188
ip-quality: 359
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by xxnet** [comment]
​先用正式发布的版本吧，python3分支还有问题

**Comment by kittycheny** [comment]
@xxnet 我这边重新下载了正式发布的版本，故障依旧，之前也没有用python3
