### ISSUE TITLE
部署私人APPID一直失败

### ISSUE THREAD

**Issue by ithaIca** [XX-net/XX-Net#2467]
2016-03-22 16:54:17,615 - root - INFO - set proxy to http://127.0.0.1:8087
2016-03-22 16:54:17,637 - root - INFO - ============ Begin upload ============
2016-03-22 16:54:17,638 - root - INFO - appid:tenren1
2016-03-22 16:54:17,696 - root - INFO - Send: /api/appversion/rollback, params={'version': '1', 'app_id': 'tenren1'}
2016-03-22 16:54:40,638 - oauth2client.client - INFO - Successfully retrieved access token
2016-03-22 16:54:43,135 - root - INFO - Send: /api/appversion/rollback, params={'version': '1', 'app_id': 'tenren1'}
2016-03-22 16:54:55,154 - root - ERROR - upload fail:ServerNotFoundError('Unable to find the server at appengine.google.com',)
Traceback (most recent call last):
File "D:\XX-Net-2.9.4\XX-Net-2.9.4\gae_proxy\server\uploader.py", line 70, in upload
result = appcfg.AppCfgApp(['appcfg', 'rollback', dirname ]).Run()
File "D:\XX-Net-2.9.4\XX-Net-2.9.4\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 2951, in Run
self.action(self)
File "D:\XX-Net-2.9.4\XX-Net-2.9.4\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 5044, in __call__
return method()
File "D:\XX-Net-2.9.4\XX-Net-2.9.4\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 4397, in Rollback
self._Rollback()
File "D:\XX-Net-2.9.4\XX-Net-2.9.4\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 4442, in _Rollback
appversion.Rollback(force_rollback)
File "D:\XX-Net-2.9.4\XX-Net-2.9.4\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 2362, in Rollback
force_rollback='1' if force_rollback else '0')
File "D:\XX-Net-2.9.4\XX-Net-2.9.4\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 1696, in Send
result = self.rpcserver.Send(url, payload=payload, **kwargs)
File "D:\XX-Net-2.9.4\XX-Net-2.9.4\gae_proxy\server\lib\google\appengine\tools\appengine_rpc_httplib2.py", line 247, in Send
url, method=method, body=payload, headers=headers)
File "D:\XX-Net-2.9.4\XX-Net-2.9.4\gae_proxy\server\lib\oauth2client\client.py", line 562, in new_request
redirections, connection_type)
File "D:\XX-Net-2.9.4\XX-Net-2.9.4\gae_proxy\server\lib\httplib2\__init__.py", line 1593, in request
(response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
File "D:\XX-Net-2.9.4\XX-Net-2.9.4\gae_proxy\server\lib\httplib2\__init__.py", line 1341, in _request
(response, content) = self._conn_request(conn, request_uri, method, body, headers)
File "D:\XX-Net-2.9.4\XX-Net-2.9.4\gae_proxy\server\lib\httplib2\__init__.py", line 1283, in _conn_request
raise ServerNotFoundError("Unable to find the server at %s" % conn.host)
ServerNotFoundError: Unable to find the server at appengine.google.com
2016-03-22 16:54:55,165 - root - INFO - Retry 2 time...
2016-03-22 16:54:56,250 - root - INFO - Send: /api/appversion/rollback, params={'version': '1', 'app_id': 'tenren1'}
2016-03-22 16:55:00,653 - root - INFO - =======================
2016-03-22 16:55:00,654 - root - INFO - Deploy failed appid list:
2016-03-22 16:55:00,654 - root - INFO - - tenren1
2016-03-22 16:55:00,654 - root - INFO - == END ==

**Comment by xxnet** [comment]
在data/gae_proxy/下放一个manual.ini，放入下面内容
​
[hosts]
appengine.google.com = gae

**Comment by shawwokou123** [comment]
打开VPN再部署

**Comment by ithaIca** [comment]
还是不行，一直卡在这里
2016-03-22 17:32:47,332 - root - INFO - set proxy to http://127.0.0.1:8087
2016-03-22 17:32:47,359 - root - INFO - ============ Begin upload ============
2016-03-22 17:32:47,361 - root - INFO - appid:tenren1
2016-03-22 17:32:47,424 - root - INFO - Send: /api/appversion/rollback, params={'version': '1', 'app_id': 'tenren1'}
2016-03-22 17:33:30,592 - root - ERROR - upload fail:ServerNotFoundError('Unable to find the server at accounts.google.com',)
Traceback (most recent call last):
File "D:\XX-Net-2.9.4\XX-Net-2.9.4\gae_proxy\server\uploader.py", line 70, in upload
result = appcfg.AppCfgApp(['appcfg', 'rollback', dirname ]).Run()
File "D:\XX-Net-2.9.4\XX-Net-2.9.4\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 2951, in Run
self.action(self)
File "D:\XX-Net-2.9.4\XX-Net-2.9.4\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 5044, in __call__
return method()
File "D:\XX-Net-2.9.4\XX-Net-2.9.4\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 4397, in Rollback
self._Rollback()
File "D:\XX-Net-2.9.4\XX-Net-2.9.4\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 4442, in _Rollback
appversion.Rollback(force_rollback)
File "D:\XX-Net-2.9.4\XX-Net-2.9.4\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 2362, in Rollback
force_rollback='1' if force_rollback else '0')
File "D:\XX-Net-2.9.4\XX-Net-2.9.4\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 1696, in Send
result = self.rpcserver.Send(url, payload=payload, **kwargs)
File "D:\XX-Net-2.9.4\XX-Net-2.9.4\gae_proxy\server\lib\google\appengine\tools\appengine_rpc_httplib2.py", line 241, in Send
self._Authenticate(self.http, auth_errors[0] > 0)
File "D:\XX-Net-2.9.4\XX-Net-2.9.4\gae_proxy\server\lib\google\appengine\tools\appengine_rpc_httplib2.py", line 459, in _Authenticate
self.credentials = tools.run_flow(flow, self.storage, self.flags)
File "D:\XX-Net-2.9.4\XX-Net-2.9.4\gae_proxy\server\lib\oauth2client\util.py", line 137, in positional_wrapper
return wrapped(*args, **kwargs)
File "D:\XX-Net-2.9.4\XX-Net-2.9.4\gae_proxy\server\lib\oauth2client\tools.py", line 225, in run_flow
credential = flow.step2_exchange(code, http=http)
File "D:\XX-Net-2.9.4\XX-Net-2.9.4\gae_proxy\server\lib\oauth2client\util.py", line 137, in positional_wrapper
return wrapped(*args, **kwargs)
File "D:\XX-Net-2.9.4\XX-Net-2.9.4\gae_proxy\server\lib\oauth2client\client.py", line 1993, in step2_exchange
headers=headers)
File "D:\XX-Net-2.9.4\XX-Net-2.9.4\gae_proxy\server\lib\httplib2\__init__.py", line 1593, in request
(response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
File "D:\XX-Net-2.9.4\XX-Net-2.9.4\gae_proxy\server\lib\httplib2\__init__.py", line 1341, in _request
(response, content) = self._conn_request(conn, request_uri, method, body, headers)
File "D:\XX-Net-2.9.4\XX-Net-2.9.4\gae_proxy\server\lib\httplib2\__init__.py", line 1283, in _conn_request
raise ServerNotFoundError("Unable to find the server at %s" % conn.host)
ServerNotFoundError: Unable to find the server at accounts.google.com
2016-03-22 17:33:30,601 - root - INFO - Retry 1 time...
2016-03-22 17:32:47,332 - root - INFO - set proxy to http://127.0.0.1:8087
2016-03-22 17:32:47,359 - root - INFO - ============ Begin upload ============
2016-03-22 17:32:47,361 - root - INFO - appid:tenren1
2016-03-22 17:32:47,424 - root - INFO - Send: /api/appversion/rollback, params={'version': '1', 'app_id': 'tenren1'}
2016-03-22 17:33:30,592 - root - ERROR - upload fail:ServerNotFoundError('Unable to find the server at accounts.google.com',)
Traceback (most recent call last):
File "D:\XX-Net-2.9.4\XX-Net-2.9.4\gae_proxy\server\uploader.py", line 70, in upload
result = appcfg.AppCfgApp(['appcfg', 'rollback', dirname ]).Run()
File "D:\XX-Net-2.9.4\XX-Net-2.9.4\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 2951, in Run
self.action(self)
File "D:\XX-Net-2.9.4\XX-Net-2.9.4\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 5044, in __call__
return method()
File "D:\XX-Net-2.9.4\XX-Net-2.9.4\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 4397, in Rollback
self._Rollback()
File "D:\XX-Net-2.9.4\XX-Net-2.9.4\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 4442, in _Rollback
appversion.Rollback(force_rollback)
File "D:\XX-Net-2.9.4\XX-Net-2.9.4\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 2362, in Rollback
force_rollback='1' if force_rollback else '0')
File "D:\XX-Net-2.9.4\XX-Net-2.9.4\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 1696, in Send
result = self.rpcserver.Send(url, payload=payload, **kwargs)
File "D:\XX-Net-2.9.4\XX-Net-2.9.4\gae_proxy\server\lib\google\appengine\tools\appengine_rpc_httplib2.py", line 241, in Send
self._Authenticate(self.http, auth_errors[0] > 0)
File "D:\XX-Net-2.9.4\XX-Net-2.9.4\gae_proxy\server\lib\google\appengine\tools\appengine_rpc_httplib2.py", line 459, in _Authenticate
self.credentials = tools.run_flow(flow, self.storage, self.flags)
File "D:\XX-Net-2.9.4\XX-Net-2.9.4\gae_proxy\server\lib\oauth2client\util.py", line 137, in positional_wrapper
return wrapped(*args, **kwargs)
File "D:\XX-Net-2.9.4\XX-Net-2.9.4\gae_proxy\server\lib\oauth2client\tools.py", line 225, in run_flow
credential = flow.step2_exchange(code, http=http)
File "D:\XX-Net-2.9.4\XX-Net-2.9.4\gae_proxy\server\lib\oauth2client\util.py", line 137, in positional_wrapper
return wrapped(*args, **kwargs)
File "D:\XX-Net-2.9.4\XX-Net-2.9.4\gae_proxy\server\lib\oauth2client\client.py", line 1993, in step2_exchange
headers=headers)
File "D:\XX-Net-2.9.4\XX-Net-2.9.4\gae_proxy\server\lib\httplib2\__init__.py", line 1593, in request
(response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
File "D:\XX-Net-2.9.4\XX-Net-2.9.4\gae_proxy\server\lib\httplib2\__init__.py", line 1341, in _request
(response, content) = self._conn_request(conn, request_uri, method, body, headers)
File "D:\XX-Net-2.9.4\XX-Net-2.9.4\gae_proxy\server\lib\httplib2\__init__.py", line 1283, in _conn_request
raise ServerNotFoundError("Unable to find the server at %s" % conn.host)
ServerNotFoundError: Unable to find the server at accounts.google.com
2016-03-22 17:33:30,601 - root - INFO - Retry 1 time...

**Comment by jzp820927** [comment]
下载最新版覆盖试试吧

**Comment by ithaIca** [comment]
我用的是2.9.4版的

**Comment by ithaIca** [comment]
还是说要变为2.9.3？

**Comment by jzp820927** [comment]
不用了，已经是最新版了，那就不晓得是什么问题了

**Comment by ithaIca** [comment]
好吧

**Comment by jzp820927** [comment]
或者你用 goagent 部署服务端试试吧，反正都是通用的
