### ISSUE TITLE
SSLError: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:1750) 

### ISSUE THREAD

**Issue by aetheryang** [XX-net/XX-Net#2474]
Mar 23 14:38:23.182 - [DEBUG] network is ok, cost:15166 ms

Mar 23 14:38:23.193 - [INFO] SSL use version:TLSv1_2

Mar 23 14:38:23.200 - [INFO] load ip range file:/home/future_suse/xx-net/gae_proxy/local/ip_range.txt

Mar 23 14:38:23.223 - [INFO] load google ip_list num:22, gws num:22

Mar 23 14:38:23.253 - [DEBUG] ## GAEProxy set keep_running: True

Mar 23 14:38:23.266 - [INFO] ------------------------------------------------------

Mar 23 14:38:23.266 - [INFO] Python Version : 2.7.9

Mar 23 14:38:23.266 - [INFO] OS : Dist:openSUSE ; Version:42.1; ID:x86_64

Mar 23 14:38:23.266 - [INFO] Listen Address : 127.0.0.1:8087

Mar 23 14:38:23.267 - [INFO] GAE APPID : **something**

Mar 23 14:38:23.267 - [INFO] Pac Server : http://127.0.0.1:8086/proxy.pac

Mar 23 14:38:23.267 - [INFO] ------------------------------------------------------

Mar 23 14:38:23.280 - [WARNING] please install *libnss3-tools* package to import GoAgent root ca

Mar 23 14:38:24.567 - [INFO] GAE CONNECT xxnet-update.appspot.com:443

Mar 23 14:38:24.573 - [DEBUG] GAE CONNECT Direct GET https://xxnet-update.appspot.com/update.json?uuid=49817f7f-c932-4867-903b-63cb08a8fb0b&version=2.9.4&platform=Linux-4.1.15-8-default-x86_64-with-SuSE-42.1-x86_64

Mar 23 14:38:24.574 - [DEBUG] get ip:203.211.8.119 t:138

Mar 23 14:38:24.768 - [DEBUG] create_ssl update ip:203.211.8.119 time:132

Mar 23 14:38:24.875 - [DEBUG] get ip:66.96.224.205 t:175

Mar 23 14:38:25.020 - [INFO] DIRECT t:446 s:1674 200 xxnet-update.appspot.com /update.json?uuid=49817f7f-c932-4867-903b-63cb08a8fb0b&version=2.9.4&platform=Linux-4.1.15-8-default-x86_64-with-SuSE-42.1-x86_64

Mar 23 14:38:25.136 - [DEBUG] create_ssl update ip:66.96.224.205 time:175

Mar 23 14:38:25.176 - [DEBUG] get ip:219.124.146.155 t:200

Mar 23 14:38:25.476 - [DEBUG] get ip:118.98.111.207 t:201

Mar 23 14:38:25.482 - [DEBUG] create_ssl update ip:219.124.146.155 time:206

Mar 23 14:38:25.533 - [DEBUG] get ip:118.98.111.230 t:202

Mar 23 14:38:25.634 - [DEBUG] get ip:216.58.193.96 t:344

Mar 23 14:38:25.734 - [DEBUG] get ip:208.65.153.150 t:402

Mar 23 14:38:25.769 - [DEBUG] get ip:49.98.24.141 t:402

Mar 23 14:38:25.803 - [DEBUG] create_ssl update ip:118.98.111.230 time:181

Mar 23 14:38:25.835 - [DEBUG] get ip:216.58.194.196 t:404

Mar 23 14:38:25.935 - [DEBUG] get ip:217.119.118.119 t:546

Mar 23 14:38:26.036 - [DEBUG] get ip:180.188.250.17 t:558

Mar 23 14:38:26.137 - [DEBUG] get ip:78.11.253.208 t:561

Mar 23 14:38:26.137 - [DEBUG] get ip:92.46.70.24 t:638

Mar 23 14:38:26.199 - [DEBUG] create_ssl update ip:118.98.111.207 time:325

Mar 23 14:38:26.237 - [DEBUG] get ip:202.248.248.232 t:661

Mar 23 14:38:26.321 - [DEBUG] create_ssl update ip:208.65.153.150 time:392

Mar 23 14:38:26.348 - [DEBUG] create_ssl update ip:216.58.193.96 time:547

Mar 23 14:38:26.472 - [DEBUG] create_ssl update ip:216.58.194.196 time:426

Mar 23 14:38:26.619 - [DEBUG] create_ssl update ip:49.98.24.141 time:650

Mar 23 14:38:26.734 - [DEBUG] create_ssl update ip:217.119.118.119 time:533

Mar 23 14:38:26.853 - [DEBUG] create_ssl update ip:202.248.248.232 time:412

Mar 23 14:38:26.959 - [DEBUG] create_ssl update ip:78.11.253.208 time:549

Mar 23 14:38:27.208 - [DEBUG] create_ssl update ip:180.188.250.17 time:896

Mar 23 14:38:27.299 - [INFO] GAE CONNECT www.twitter.com:443

Mar 23 14:38:27.309 - [ERROR] ssl.wrap_socket(self.connection=) failed: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:1750) path:www.twitter.com:443, errno:1

Mar 23 14:38:27.310 - [INFO] GAE CONNECT www.twitter.com:443

Mar 23 14:38:27.311 - [INFO] GAE CONNECT www.twitter.com:443

Mar 23 14:38:27.317 - [DEBUG] create_ssl update ip:92.46.70.24 time:908

Mar 23 14:38:27.323 - [ERROR] ssl.wrap_socket(self.connection=) failed: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:1750) path:www.twitter.com:443, errno:1

Mar 23 14:38:27.324 - [ERROR] ssl.wrap_socket(self.connection=) failed: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:1750) path:www.twitter.com:443, errno:1

Mar 23 14:38:27.347 - [ERROR] Except stack:Traceback (most recent call last): File "/home/future_suse/xx-net/gae_proxy/local/proxy_handler.py", line 219, in do_CONNECT_AGENT self.raw_requestline = self.rfile.readline(65537) File "/usr/lib64/python2.7/socket.py", line 476, in readline data = self._sock.recv(self._rbufsize) File "/usr/lib64/python2.7/ssl.py", line 722, in recv return self.read(buflen) File "/usr/lib64/python2.7/ssl.py", line 616, in read v = self._sslobj.read(len or 1024) SSLError: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:1750)

Mar 23 14:38:27.347 - [ERROR] Except stack:Traceback (most recent call last): File "/home/future_suse/xx-net/gae_proxy/local/proxy_handler.py", line 219, in do_CONNECT_AGENT self.raw_requestline = self.rfile.readline(65537) File "/usr/lib64/python2.7/socket.py", line 476, in readline data = self._sock.recv(self._rbufsize) File "/usr/lib64/python2.7/ssl.py", line 722, in recv return self.read(buflen) File "/usr/lib64/python2.7/ssl.py", line 616, in read v = self._sslobj.read(len or 1024) SSLError: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:1750)

Mar 23 14:38:27.347 - [ERROR] Except stack:Traceback (most recent call last): File "/home/future_suse/xx-net/gae_proxy/local/proxy_handler.py", line 219, in do_CONNECT_AGENT self.raw_requestline = self.rfile.readline(65537) File "/usr/lib64/python2.7/socket.py", line 476, in readline data = self._sock.recv(self._rbufsize) File "/usr/lib64/python2.7/ssl.py", line 722, in recv return self.read(buflen) File "/usr/lib64/python2.7/ssl.py", line 616, in read v = self._sslobj.read(len or 1024) SSLError: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:1750)

Mar 23 14:38:28.302 - [INFO] GAE CONNECT www.twitter.com:443

Mar 23 14:38:28.302 - [INFO] GAE CONNECT www.twitter.com:443

Mar 23 14:38:28.305 - [INFO] GAE CONNECT www.twitter.com:443

Mar 23 14:38:28.314 - [ERROR] ssl.wrap_socket(self.connection=) failed: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:1750) path:www.twitter.com:443, errno:1

Mar 23 14:38:28.314 - [ERROR] Except stack:Traceback (most recent call last): File "/home/future_suse/xx-net/gae_proxy/local/proxy_handler.py", line 219, in do_CONNECT_AGENT self.raw_requestline = self.rfile.readline(65537) File "/usr/lib64/python2.7/socket.py", line 476, in readline data = self._sock.recv(self._rbufsize) File "/usr/lib64/python2.7/ssl.py", line 722, in recv return self.read(buflen) File "/usr/lib64/python2.7/ssl.py", line 616, in read v = self._sslobj.read(len or 1024) SSLError: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:1750)

Mar 23 14:38:28.320 - [ERROR] ssl.wrap_socket(self.connection=) failed: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:1750) path:www.twitter.com:443, errno:1

Mar 23 14:38:28.320 - [ERROR] Except stack:Traceback (most recent call last): File "/home/future_suse/xx-net/gae_proxy/local/proxy_handler.py", line 219, in do_CONNECT_AGENT self.raw_requestline = self.rfile.readline(65537) File "/usr/lib64/python2.7/socket.py", line 476, in readline data = self._sock.recv(self._rbufsize) File "/usr/lib64/python2.7/ssl.py", line 722, in recv return self.read(buflen) File "/usr/lib64/python2.7/ssl.py", line 616, in read v = self._sslobj.read(len or 1024) SSLError: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:1750)

Mar 23 14:38:28.320 - [ERROR] ssl.wrap_socket(self.connection=) failed: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:1750) path:www.twitter.com:443, errno:1

Mar 23 14:38:28.320 - [ERROR] Except stack:Traceback (most recent call last): File "/home/future_suse/xx-net/gae_proxy/local/proxy_handler.py", line 219, in do_CONNECT_AGENT self.raw_requestline = self.rfile.readline(65537) File "/usr/lib64/python2.7/socket.py", line 476, in readline data = self._sock.recv(self._rbufsize) File "/usr/lib64/python2.7/ssl.py", line 722, in recv return self.read(buflen) File "/usr/lib64/python2.7/ssl.py", line 616, in read v = self._sslobj.read(len or 1024) SSLError: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:1750)

Mar 23 14:38:29.301 - [INFO] GAE CONNECT www.twitter.com:443

Mar 23 14:38:29.301 - [INFO] GAE CONNECT www.twitter.com:443

Mar 23 14:38:29.302 - [INFO] GAE CONNECT www.twitter.com:443

Mar 23 14:38:29.314 - [ERROR] ssl.wrap_socket(self.connection=) failed: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:1750) path:www.twitter.com:443, errno:1

Mar 23 14:38:29.314 - [ERROR] Except stack:Traceback (most recent call last): File "/home/future_suse/xx-net/gae_proxy/local/proxy_handler.py", line 219, in do_CONNECT_AGENT self.raw_requestline = self.rfile.readline(65537) File "/usr/lib64/python2.7/socket.py", line 476, in readline data = self._sock.recv(self._rbufsize) File "/usr/lib64/python2.7/ssl.py", line 722, in recv return self.read(buflen) File "/usr/lib64/python2.7/ssl.py", line 616, in read v = self._sslobj.read(len or 1024) SSLError: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:1750)

Mar 23 14:38:29.319 - [ERROR] ssl.wrap_socket(self.connection=) failed: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:1750) path:www.twitter.com:443, errno:1

Mar 23 14:38:29.320 - [ERROR] Except stack:Traceback (most recent call last): File "/home/future_suse/xx-net/gae_proxy/local/proxy_handler.py", line 219, in do_CONNECT_AGENT self.raw_requestline = self.rfile.readline(65537) File "/usr/lib64/python2.7/socket.py", line 476, in readline data = self._sock.recv(self._rbufsize) File "/usr/lib64/python2.7/ssl.py", line 722, in recv return self.read(buflen) File "/usr/lib64/python2.7/ssl.py", line 616, in read v = self._sslobj.read(len or 1024) SSLError: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:1750)

Mar 23 14:38:29.320 - [ERROR] ssl.wrap_socket(self.connection=) failed: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:1750) path:www.twitter.com:443, errno:1

Mar 23 14:38:29.320 - [ERROR] Except stack:Traceback (most recent call last): File "/home/future_suse/xx-net/gae_proxy/local/proxy_handler.py", line 219, in do_CONNECT_AGENT self.raw_requestline = self.rfile.readline(65537) File "/usr/lib64/python2.7/socket.py", line 476, in readline data = self._sock.recv(self._rbufsize) File "/usr/lib64/python2.7/ssl.py", line 722, in recv return self.read(buflen) File "/usr/lib64/python2.7/ssl.py", line 616, in read v = self._sslobj.read(len or 1024) SSLError: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:1750)

Mar 23 14:38:30.318 - [INFO] GAE CONNECT www.twitter.com:443

Mar 23 14:38:30.318 - [INFO] GAE CONNECT www.twitter.com:443

Mar 23 14:38:30.318 - [INFO] GAE CONNECT www.twitter.com:443

Mar 23 14:38:30.330 - [ERROR] ssl.wrap_socket(self.connection=) failed: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:1750) path:www.twitter.com:443, errno:1

Mar 23 14:38:30.330 - [ERROR] Except stack:Traceback (most recent call last): File "/home/future_suse/xx-net/gae_proxy/local/proxy_handler.py", line 219, in do_CONNECT_AGENT self.raw_requestline = self.rfile.readline(65537) File "/usr/lib64/python2.7/socket.py", line 476, in readline data = self._sock.recv(self._rbufsize) File "/usr/lib64/python2.7/ssl.py", line 722, in recv return self.read(buflen) File "/usr/lib64/python2.7/ssl.py", line 616, in read v = self._sslobj.read(len or 1024) SSLError: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:1750)

Mar 23 14:38:30.335 - [ERROR] ssl.wrap_socket(self.connection=) failed: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:1750) path:www.twitter.com:443, errno:1

Mar 23 14:38:30.335 - [ERROR] Except stack:Traceback (most recent call last): File "/home/future_suse/xx-net/gae_proxy/local/proxy_handler.py", line 219, in do_CONNECT_AGENT self.raw_requestline = self.rfile.readline(65537) File "/usr/lib64/python2.7/socket.py", line 476, in readline data = self._sock.recv(self._rbufsize) File "/usr/lib64/python2.7/ssl.py", line 722, in recv return self.read(buflen) File "/usr/lib64/python2.7/ssl.py", line 616, in read v = self._sslobj.read(len or 1024) SSLError: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:1750)

Mar 23 14:38:30.336 - [ERROR] ssl.wrap_socket(self.connection=) failed: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:1750) path:www.twitter.com:443, errno:1

Mar 23 14:38:30.336 - [ERROR] Except stack:Traceback (most recent call last): File "/home/future_suse/xx-net/gae_proxy/local/proxy_handler.py", line 219, in do_CONNECT_AGENT self.raw_requestline = self.rfile.readline(65537) File "/usr/lib64/python2.7/socket.py", line 476, in readline data = self._sock.recv(self._rbufsize) File "/usr/lib64/python2.7/ssl.py", line 722, in recv return self.read(buflen) File "/usr/lib64/python2.7/ssl.py", line 616, in read v = self._sslobj.read(len or 1024) SSLError: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:1750)

Mar 23 14:38:30.887 - [INFO] GAE CONNECT www.twitter.com:443

Mar 23 14:38:30.913 - [ERROR] ssl.wrap_socket(self.connection=) failed: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:1750) path:www.twitter.com:443, errno:1

Mar 23 14:38:30.914 - [ERROR] Except stack:Traceback (most recent call last): File "/home/future_suse/xx-net/gae_proxy/local/proxy_handler.py", line 219, in do_CONNECT_AGENT self.raw_requestline = self.rfile.readline(65537) File "/usr/lib64/python2.7/socket.py", line 476, in readline data = self._sock.recv(self._rbufsize) File "/usr/lib64/python2.7/ssl.py", line 722, in recv return self.read(buflen) File "/usr/lib64/python2.7/ssl.py", line 616, in read v = self._sslobj.read(len or 1024) SSLError: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:1750)

Mar 23 14:38:30.922 - [INFO] GAE CONNECT www.twitter.com:443

Mar 23 14:38:30.961 - [ERROR] ssl.wrap_socket(self.connection=) failed: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:1750) path:www.twitter.com:443, errno:1

Mar 23 14:38:30.961 - [ERROR] Except stack:Traceback (most recent call last): File "/home/future_suse/xx-net/gae_proxy/local/proxy_handler.py", line 219, in do_CONNECT_AGENT self.raw_requestline = self.rfile.readline(65537) File "/usr/lib64/python2.7/socket.py", line 476, in readline data = self._sock.recv(self._rbufsize) File "/usr/lib64/python2.7/ssl.py", line 722, in recv return self.read(buflen) File "/usr/lib64/python2.7/ssl.py", line 616, in read v = self._sslobj.read(len or 1024) SSLError: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:1750)

Mar 23 14:38:31.006 - [INFO] GAE CONNECT www.twitter.com:443

Mar 23 14:38:31.007 - [INFO] GAE CONNECT www.twitter.com:443

Mar 23 14:38:31.008 - [INFO] GAE CONNECT www.twitter.com:443

Mar 23 14:38:31.009 - [INFO] GAE CONNECT www.twitter.com:443

Mar 23 14:38:31.017 - [ERROR] ssl.wrap_socket(self.connection=) failed: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:1750) path:www.twitter.com:443, errno:1

Mar 23 14:38:31.017 - [ERROR] Except stack:Traceback (most recent call last): File "/home/future_suse/xx-net/gae_proxy/local/proxy_handler.py", line 219, in do_CONNECT_AGENT self.raw_requestline = self.rfile.readline(65537) File "/usr/lib64/python2.7/socket.py", line 476, in readline data = self._sock.recv(self._rbufsize) File "/usr/lib64/python2.7/ssl.py", line 722, in recv return self.read(buflen) File "/usr/lib64/python2.7/ssl.py", line 616, in read v = self._sslobj.read(len or 1024) SSLError: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:1750)

Mar 23 14:38:31.019 - [ERROR] ssl.wrap_socket(self.connection=) failed: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:1750) path:www.twitter.com:443, errno:1

Mar 23 14:38:31.019 - [ERROR] Except stack:Traceback (most recent call last): File "/home/future_suse/xx-net/gae_proxy/local/proxy_handler.py", line 219, in do_CONNECT_AGENT self.raw_requestline = self.rfile.readline(65537) File "/usr/lib64/python2.7/socket.py", line 476, in readline data = self._sock.recv(self._rbufsize) File "/usr/lib64/python2.7/ssl.py", line 722, in recv return self.read(buflen) File "/usr/lib64/python2.7/ssl.py", line 616, in read v = self._sslobj.read(len or 1024) SSLError: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:1750)

Mar 23 14:38:31.020 - [ERROR] ssl.wrap_socket(self.connection=) failed: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:1750) path:www.twitter.com:443, errno:1

Mar 23 14:38:31.020 - [ERROR] Except stack:Traceback (most recent call last): File "/home/future_suse/xx-net/gae_proxy/local/proxy_handler.py", line 219, in do_CONNECT_AGENT self.raw_requestline = self.rfile.readline(65537) File "/usr/lib64/python2.7/socket.py", line 476, in readline data = self._sock.recv(self._rbufsize) File "/usr/lib64/python2.7/ssl.py", line 722, in recv return self.read(buflen) File "/usr/lib64/python2.7/ssl.py", line 616, in read v = self._sslobj.read(len or 1024) SSLError: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:1750)

Mar 23 14:38:31.022 - [ERROR] ssl.wrap_socket(self.connection=) failed: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:1750) path:www.twitter.com:443, errno:1

Mar 23 14:38:31.022 - [ERROR] Except stack:Traceback (most recent call last): File "/home/future_suse/xx-net/gae_proxy/local/proxy_handler.py", line 219, in do_CONNECT_AGENT self.raw_requestline = self.rfile.readline(65537) File "/usr/lib64/python2.7/socket.py", line 476, in readline data = self._sock.recv(self._rbufsize) File "/usr/lib64/python2.7/ssl.py", line 722, in recv return self.read(buflen) File "/usr/lib64/python2.7/ssl.py", line 616, in read v = self._sslobj.read(len or 1024) SSLError: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:1750)

Mar 23 14:38:31.958 - [INFO] GAE CONNECT www.twitter.com:443

Mar 23 14:38:31.958 - [INFO] GAE CONNECT www.twitter.com:443

Mar 23 14:38:31.961 - [INFO] GAE CONNECT www.twitter.com:443

Mar 23 14:38:31.974 - [ERROR] ssl.wrap_socket(self.connection=) failed: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:1750) path:www.twitter.com:443, errno:1

Mar 23 14:38:31.974 - [ERROR] Except stack:Traceback (most recent call last): File "/home/future_suse/xx-net/gae_proxy/local/proxy_handler.py", line 219, in do_CONNECT_AGENT self.raw_requestline = self.rfile.readline(65537) File "/usr/lib64/python2.7/socket.py", line 476, in readline data = self._sock.recv(self._rbufsize) File "/usr/lib64/python2.7/ssl.py", line 722, in recv return self.read(buflen) File "/usr/lib64/python2.7/ssl.py", line 616, in read v = self._sslobj.read(len or 1024) SSLError: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:1750)

Mar 23 14:38:31.974 - [ERROR] ssl.wrap_socket(self.connection=) failed: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:1750) path:www.twitter.com:443, errno:1

Mar 23 14:38:31.975 - [ERROR] ssl.wrap_socket(self.connection=) failed: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:1750) path:www.twitter.com:443, errno:1

Mar 23 14:38:31.975 - [ERROR] Except stack:Traceback (most recent call last): File "/home/future_suse/xx-net/gae_proxy/local/proxy_handler.py", line 219, in do_CONNECT_AGENT self.raw_requestline = self.rfile.readline(65537) File "/usr/lib64/python2.7/socket.py", line 476, in readline data = self._sock.recv(self._rbufsize) File "/usr/lib64/python2.7/ssl.py", line 722, in recv return self.read(buflen) File "/usr/lib64/python2.7/ssl.py", line 616, in read v = self._sslobj.read(len or 1024) SSLError: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:1750)

Mar 23 14:38:31.976 - [ERROR] Except stack:Traceback (most recent call last): File "/home/future_suse/xx-net/gae_proxy/local/proxy_handler.py", line 219, in do_CONNECT_AGENT self.raw_requestline = self.rfile.readline(65537) File "/usr/lib64/python2.7/socket.py", line 476, in readline data = self._sock.recv(self._rbufsize) File "/usr/lib64/python2.7/ssl.py", line 722, in recv return self.read(buflen) File "/usr/lib64/python2.7/ssl.py", line 616, in read v = self._sslobj.read(len or 1024) SSLError: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:1750)

Mar 23 14:38:32.948 - [INFO] GAE CONNECT www.twitter.com:443

Mar 23 14:38:32.949 - [INFO] GAE CONNECT www.twitter.com:443

Mar 23 14:38:32.949 - [INFO] GAE CONNECT www.twitter.com:443

Mar 23 14:38:32.960 - [ERROR] ssl.wrap_socket(self.connection=) failed: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:1750) path:www.twitter.com:443, errno:1

Mar 23 14:38:32.960 - [ERROR] Except stack:Traceback (most recent call last): File "/home/future_suse/xx-net/gae_proxy/local/proxy_handler.py", line 219, in do_CONNECT_AGENT self.raw_requestline = self.rfile.readline(65537) File "/usr/lib64/python2.7/socket.py", line 476, in readline data = self._sock.recv(self._rbufsize) File "/usr/lib64/python2.7/ssl.py", line 722, in recv return self.read(buflen) File "/usr/lib64/python2.7/ssl.py", line 616, in read v = self._sslobj.read(len or 1024) SSLError: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:1750)

Mar 23 14:38:32.961 - [ERROR] ssl.wrap_socket(self.connection=) failed: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:1750) path:www.twitter.com:443, errno:1

Mar 23 14:38:32.961 - [ERROR] Except stack:Traceback (most recent call last): File "/home/future_suse/xx-net/gae_proxy/local/proxy_handler.py", line 219, in do_CONNECT_AGENT self.raw_requestline = self.rfile.readline(65537) File "/usr/lib64/python2.7/socket.py", line 476, in readline data = self._sock.recv(self._rbufsize) File "/usr/lib64/python2.7/ssl.py", line 722, in recv return self.read(buflen) File "/usr/lib64/python2.7/ssl.py", line 616, in read v = self._sslobj.read(len or 1024) SSLError: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:1750)

Mar 23 14:38:32.965 - [ERROR] ssl.wrap_socket(self.connection=) failed: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:1750) path:www.twitter.com:443, errno:1

Mar 23 14:38:32.965 - [ERROR] Except stack:Traceback (most recent call last): File "/home/future_suse/xx-net/gae_proxy/local/proxy_handler.py", line 219, in do_CONNECT_AGENT self.raw_requestline = self.rfile.readline(65537) File "/usr/lib64/python2.7/socket.py", line 476, in readline data = self._sock.recv(self._rbufsize) File "/usr/lib64/python2.7/ssl.py", line 722, in recv return self.read(buflen) File "/usr/lib64/python2.7/ssl.py", line 616, in read v = self._sslobj.read(len or 1024) SSLError: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:1750)

Mar 23 14:38:33.955 - [INFO] GAE CONNECT www.twitter.com:443

Mar 23 14:38:33.956 - [INFO] GAE CONNECT www.twitter.com:443

Mar 23 14:38:33.957 - [INFO] GAE CONNECT www.twitter.com:443

Mar 23 14:38:33.967 - [ERROR] ssl.wrap_socket(self.connection=) failed: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:1750) path:www.twitter.com:443, errno:1

Mar 23 14:38:33.967 - [ERROR] Except stack:Traceback (most recent call last): File "/home/future_suse/xx-net/gae_proxy/local/proxy_handler.py", line 219, in do_CONNECT_AGENT self.raw_requestline = self.rfile.readline(65537) File "/usr/lib64/python2.7/socket.py", line 476, in readline data = self._sock.recv(self._rbufsize) File "/usr/lib64/python2.7/ssl.py", line 722, in recv return self.read(buflen) File "/usr/lib64/python2.7/ssl.py", line 616, in read v = self._sslobj.read(len or 1024) SSLError: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:1750)

Mar 23 14:38:33.968 - [ERROR] ssl.wrap_socket(self.connection=) failed: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:1750) path:www.twitter.com:443, errno:1

Mar 23 14:38:33.968 - [ERROR] Except stack:Traceback (most recent call last): File "/home/future_suse/xx-net/gae_proxy/local/proxy_handler.py", line 219, in do_CONNECT_AGENT self.raw_requestline = self.rfile.readline(65537) File "/usr/lib64/python2.7/socket.py", line 476, in readline data = self._sock.recv(self._rbufsize) File "/usr/lib64/python2.7/ssl.py", line 722, in recv return self.read(buflen) File "/usr/lib64/python2.7/ssl.py", line 616, in read v = self._sslobj.read(len or 1024) SSLError: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:1750)

Mar 23 14:38:33.974 - [ERROR] ssl.wrap_socket(self.connection=) failed: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:1750) path:www.twitter.com:443, errno:1

Mar 23 14:38:33.974 - [ERROR] Except stack:Traceback (most recent call last): File "/home/future_suse/xx-net/gae_proxy/local/proxy_handler.py", line 219, in do_CONNECT_AGENT self.raw_requestline = self.rfile.readline(65537) File "/usr/lib64/python2.7/socket.py", line 476, in readline data = self._sock.recv(self._rbufsize) File "/usr/lib64/python2.7/ssl.py", line 722, in recv return self.read(buflen) File "/usr/lib64/python2.7/ssl.py", line 616, in read v = self._sslobj.read(len or 1024) SSLError: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:1750)

完整日志：
[debug.txt](https://github.com/XX-net/XX-Net/files/185517/debug.txt)

**Comment by xxnet** [comment]
浏览器要 导入证书

**Comment by caofengzi** [comment]
把以前的證書刪除然後重新導入新證書，火狐有時候的確會出現這個問題。

**Comment by aetheryang** [comment]
2.9.4似乎有些问题，换到2.9.2后可以正常fq。如果需要进一步测试我可以提供一些debug信息。
