### ISSUE TITLE
XX-Net无法建立连接

### ISSUE THREAD

**Issue by shelfee** [XX-net/XX-Net#2492]
-----------
问题描述：
请在此描述你遇到的问题，必要时贴出相关的日志信息。

-----------
诊断信息：
sys-platform: i686, Linux-3.16.0-23-generic-i686-with-Ubuntu-14.10-utopic
os-system: Linux
os-version: #31-Ubuntu SMP Tue Oct 21 18:00:35 UTC 2014
os-release: 3.16.0-23-generic
os-detail: Dist:Ubuntu; Version:14.10; ID:utopic
architecture: 32bit,ELF
browser: Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:33.0) Gecko/20100101 Firefox/33.0
xxnet-version: 2.9.2
python-version: 2.7.8

ipv6-status: 0
gws-ip-num: 109 / 109
network-status: OK
connected-link: 0 / 0
scan-ip-thread-num: 50
ip-quality: 225
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by jzp820927** [comment]
日志？

**Comment by shelfee** [comment]
3月 25 20:49:34.7 - [DEBUG] network is ok, cost:122 ms

3月 25 20:49:34.7 - [INFO] SSL use version:TLSv1

3月 25 20:49:34.7 - [INFO] load ip range file:/home/shelfee/下载/XX-Net-2.9.2/gae_proxy/local/ip_range.txt

3月 25 20:49:34.8 - [INFO] load google ip_list num:189, gws num:189

3月 25 20:49:34.9 - [DEBUG] ## GAEProxy set keep_running: True

3月 25 20:49:34.9 - [INFO] ------------------------------------------------------

3月 25 20:49:34.9 - [INFO] Python Version : 2.7.8

3月 25 20:49:34.9 - [INFO] OS : Dist:Ubuntu; Version:14.10; ID:utopic

3月 25 20:49:34.9 - [INFO] Listen Address : 127.0.0.1:8087

3月 25 20:49:34.9 - [INFO] GAE APPID :

3月 25 20:49:34.9 - [INFO] Pac Server : http://127.0.0.1:8086/proxy.pac

3月 25 20:49:34.9 - [INFO] ------------------------------------------------------

3月 25 20:49:36.6 - [INFO] scan_ip add ip:202.93.153.166 time:319

3月 25 20:49:50.0 - [INFO] scan_ip add ip:175.28.1.99 time:270

3月 25 20:49:56.9 - [INFO] scan_ip add ip:103.16.207.242 time:318

3月 25 20:50:00.6 - [INFO] scan_ip add ip:175.28.1.100 time:242

3月 25 20:50:04.4 - [INFO] scan_ip add ip:24.220.112.189 time:810

3月 25 20:50:10.7 - [INFO] scan_ip add ip:175.28.1.144 time:287

3月 25 20:50:15.6 - [INFO] scan_ip add ip:103.16.207.98 time:379

3月 25 20:50:21.5 - [INFO] scan_ip add ip:103.11.28.222 time:360

**Comment by shelfee** [comment]
shell 里报错
 3月 25 20:49:36.0 - [ERROR] check_update except:__init__() got an unexpected keyword argument 'context'
 3月 25 20:49:36.0 - [ERROR] Except stack:Traceback (most recent call last):
  File "/home/shelfee/下载/XX-Net-2.9.2/launcher/update.py", line 259, in check_push_update
    opener = get_opener()
  File "/home/shelfee/下载/XX-Net-2.9.2/launcher/update.py", line 44, in get_opener
    https_handler = urllib2.HTTPSHandler(context=context)
TypeError: __init__() got an unexpected keyword argument 'context'

**Comment by jzp820927** [comment]
好像是检查更新报错，但是更新应该不影响使用才对啊
