### ISSUE TITLE
最新开发版，网页界面中部署服务端无提示失败

### ISSUE THREAD

**Issue by yfdyh000** [XX-net/XX-Net#2496]
直接调用 uploader.py 正常。

[INFO] deploy begin.
Traceback (most recent call last):
  File "D:\XX-Net\gae_proxy\server\uploader.py", line 45, in <module>
    from google.appengine.tools import appengine_rpc, appcfg
  File "D:\XX-Net\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 56, in <module>
    from oauth2client.contrib import devshell
ImportError: No module named 'oauth2client.contrib'

**Comment by xxnet** [comment]
​什么操作系统？

**Comment by xxnet** [comment]
你是哪个版本哪个分支？
master分支上，gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 56
的内容是：

from oauth2client import devshell

**Comment by yfdyh000** [comment]
Win10，py3分支。网页中日志空白，提示部署完成，但“终止”按钮还在。控制台是输出上述信息。
重试了一遍依然如此。那么可能是py3分支的问题。

**Comment by xxnet** [comment]
​py3分支，oauth2client 在 lib/noarch目录下，contrib 是存在的。
你查查看

**Comment by yfdyh000** [comment]
弄明白了，我升级py3分支时没清理，直接覆盖的，py2的不少库还在 gae_proxy\server\lib\oauth2client 里面，包括那个contrib。

不过干净的py3 zip导出仍遇到问题：
D:\7c407d081b0badc5764570c53e0a3c1e6fdd5f9e\gae_proxy\server>uploader.py xx-net 1@1.com 1
Traceback (most recent call last):
  File "D:\7c407d081b0badc5764570c53e0a3c1e6fdd5f9e\gae_proxy\server\uploader.py", line 45, in <module>
    from google.appengine.tools import appengine_rpc, appcfg
  File "D:\7c407d081b0badc5764570c53e0a3c1e6fdd5f9e\gae_proxy\server\lib\google\appengine\tools\appengine_rpc.py", line 303
    "and verify you are a human.  Then try again."), file=sys.stderr)
                                                         ^
SyntaxError: invalid syntax

**Comment by yfdyh000** [comment]
啊，有点跑题了，那是cmd操作。网页操作看上去正常了。

**Comment by xxnet** [comment]
​
gae_proxy\server\lib\google\appengine\tools\appengine_rpc.py", line 303
这个语法确实有点奇怪：
            print((
              "Please go to\n"
              "https://www.google.com/accounts/DisplayUnlockCaptcha\n"
              "and verify you are a human.  Then try again."),
file=sys.stderr)

不知道是不是win 命令行执行会有问题
