### ISSUE TITLE
Arch Linux 无法启动

### ISSUE THREAD

**Issue by fhybj** [XX-net/XX-Net#2517]
环境
===========================================
Python 版本： 2.7
系统： 32位系统

错误提示
===========================================
Mar 27 23:18:32.315 - [WARNING] import pynotify fail, please install python-notify if possiable.
Mar 27 23:18:32.405 - [INFO] start XX-Net 2.9.2
Mar 27 23:18:32.405 - [DEBUG] start confirm_xxnet_exit
Mar 27 23:18:32.408 - [DEBUG] good, xxnet:8087 cleared!
Mar 27 23:18:32.409 - [DEBUG] good, xxnet:8085 clear!
Mar 27 23:18:32.410 - [DEBUG] finished confirm_xxnet_exit
Mar 27 23:18:32.422 - [ERROR] start module gae_proxy fail:/home/xxx/XX-Net-2.9.2/python27/1.0/lib/linux/OpenSSL/crypto.so: wrong ELF class: ELFCLASS64
Mar 27 23:18:32.423 - [ERROR] Except stack:Traceback (most recent call last):
  File "/home/xxx/XX-Net-2.9.2/launcher/module_init.py", line 37, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "/home/xxx/XX-Net-2.9.2/gae_proxy/start.py", line 14, in <module>
    import local.proxy as client
  File "/home/xxx/XX-Net-2.9.2/gae_proxy/local/proxy.py", line 95, in <module>
    from cert_util import CertUtil
  File "/home/xxx/XX-Net-2.9.2/gae_proxy/local/cert_util.py", line 38, in <module>
    import OpenSSL
  File "/home/xxx/XX-Net-2.9.2/python27/1.0/lib/linux/OpenSSL/__init__.py", line 36, in <module>
    from OpenSSL import crypto
ImportError: /home/xxx/XX-Net-2.9.2/python27/1.0/lib/linux/OpenSSL/crypto.so: wrong ELF class: ELFCLASS64

Traceback (most recent call last):
  File "launcher/start.py", line 132, in <module>
    main()
  File "launcher/start.py", line 107, in main
    module_init.start_all_auto()
  File "/home/xxx/XX-Net-2.9.2/launcher/module_init.py", line 98, in start_all_auto
    start(module)
  File "/home/xxx/XX-Net-2.9.2/launcher/module_init.py", line 37, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "/home/xxx/XX-Net-2.9.2/gae_proxy/start.py", line 14, in <module>
    import local.proxy as client
  File "/home/xxx/XX-Net-2.9.2/gae_proxy/local/proxy.py", line 95, in <module>
    from cert_util import CertUtil
  File "/home/xxx/XX-Net-2.9.2/gae_proxy/local/cert_util.py", line 38, in <module>
    import OpenSSL
  File "/home/xxx/XX-Net-2.9.2/python27/1.0/lib/linux/OpenSSL/__init__.py", line 36, in <module>
    from OpenSSL import crypto
ImportError: /home/xxx/XX-Net-2.9.2/python27/1.0/lib/linux/OpenSSL/crypto.so: wrong ELF class: ELFCLASS64
Stopping all modules before exit!
Mar 27 23:18:32.424 - [ERROR] stop module gae_proxy fail:'imp'
Mar 27 23:18:32.424 - [ERROR] Except stack:Traceback (most recent call last):
  File "/home/xxx/XX-Net-2.9.2/launcher/module_init.py", line 71, in stop
    _start = proc_handler[module]["imp"].start
KeyError: 'imp'

**Comment by jzp820927** [comment]
不会是自动升级的时候，被破坏了吧，下载最新版覆盖试试

**Comment by fhybj** [comment]
@jzp820927 使用的是最新的稳定版本——2.9.2，而且是第一次在这台PC上运行。
crypto.so: wrong ELF class: ELFCLASS64 我怀疑是否是因为我的系统是32位，而官方提供的crypto.so库是64位导致的。
我尝试过手动编译openssl，用编译获得的libcrypto.so替换自带的so库，但还是无法运行。
我编译使用的命令: ./Configure shared && make

**Comment by fhybj** [comment]
@jzp820927 另一个怀疑点，我的系统中有多个版本的Python，包括Python2.7，Python3.5

**Comment by jzp820927** [comment]
默认的python 应该是 2吧，目前确实不支持3

**Comment by fhybj** [comment]
@jzp820927 Python2.7是支持的吧，用python2.7 launcher/start.py启动也是报错

**Comment by xxnet** [comment]
要​安装pyOpenSSL 库

**Comment by fhybj** [comment]
@xxnet 安装pyOpenSSL库之后可以运行了，谢谢！

@jzp820927 也感谢您的热情帮助，谢谢！
