### ISSUE TITLE
启动检查更新报错导致整个服务挂掉

### ISSUE THREAD

**Issue by kingour** [XX-net/XX-Net#257]
```
Apr 27 10:27:18 - [ERROR] check_update except:''
Traceback (most recent call last):
  File "D:\DevApp\XX-Net\launcher\1.4.0\update.py", line 216, in check_update
    update_content = opener.open(req_url).read()
  File "D:\DevApp\XX-Net\python27\1.0\lib\urllib2.py", line 404, in open
    response = self._open(req, data)
  File "D:\DevApp\XX-Net\python27\1.0\lib\urllib2.py", line 422, in _open
    '_open', req)
  File "D:\DevApp\XX-Net\python27\1.0\lib\urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "D:\DevApp\XX-Net\python27\1.0\lib\urllib2.py", line 1222, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "D:\DevApp\XX-Net\python27\1.0\lib\urllib2.py", line 1187, in do_open
    r = h.getresponse(buffering=True)
  File "D:\DevApp\XX-Net\python27\1.0\lib\httplib.py", line 1045, in getresponse

    response.begin()
  File "D:\DevApp\XX-Net\python27\1.0\lib\httplib.py", line 409, in begin
    version, status, reason = self._read_status()
  File "D:\DevApp\XX-Net\python27\1.0\lib\httplib.py", line 373, in _read_status
```

求解决

**Comment by xxnet** [comment]
应该只影响检查更新，不影响使用。

你可以把检查更新关闭试试。
最近不稳定，你可以试试 1.9.4


2015-04-26 22:28 GMT-04:00 Kingour <notifications@github.com>:

**Comment by kingour** [comment]
实际上就是更新检查导致的，出错过后下面没日志输出了
我用1.11.3覆盖更新就好了

**Comment by xxnet** [comment]
能用就好。

我把检查更新加上异常检测，失败后，只提示警告就好。下次更新。

在 2015年4月26日 下午11:08，Kingour <notifications@github.com>写道：
