### ISSUE TITLE
我的终端部署全部失败了，求高手解答

### ISSUE THREAD

**Issue by freefly521** [XX-net/XX-Net#2746]
今天想着上YouTube，发现要私人appid，于是按着要求做了，因为Google的账号和appid是好几年前就弄过，而且当时也成功使用了，现在重新按照要求部署了，却始终不行，不知道什么原因，求高手帮忙解答
2016-04-06 18:38:45,709 - root - INFO - Retry 2 time...
2016-04-06 18:38:46,746 - root - INFO - Send: /api/appversion/rollback, params={'version': '1', 'app_id': 'kylemillton'}
2016-04-06 18:38:52,773 - root - ERROR - upload fail:error(10061, '')
Traceback (most recent call last):
File "D:\Program Files\ChromeGAE\Proxy\GoAgent\gae_proxy\server\uploader.py", line 70, in upload
result = appcfg.AppCfgApp(['appcfg', 'rollback', dirname ]).Run()
File "D:\Program Files\ChromeGAE\Proxy\GoAgent\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 2951, in Run
self.action(self)
File "D:\Program Files\ChromeGAE\Proxy\GoAgent\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 5044, in __call__
return method()
File "D:\Program Files\ChromeGAE\Proxy\GoAgent\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 4397, in Rollback
self._Rollback()
File "D:\Program Files\ChromeGAE\Proxy\GoAgent\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 4442, in _Rollback
appversion.Rollback(force_rollback)
File "D:\Program Files\ChromeGAE\Proxy\GoAgent\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 2362, in Rollback
force_rollback='1' if force_rollback else '0')
File "D:\Program Files\ChromeGAE\Proxy\GoAgent\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 1696, in Send
result = self.rpcserver.Send(url, payload=payload, **kwargs)
File "D:\Program Files\ChromeGAE\Proxy\GoAgent\gae_proxy\server\lib\google\appengine\tools\appengine_rpc_httplib2.py", line 247, in Send
url, method=method, body=payload, headers=headers)
File "D:\Program Files\ChromeGAE\Proxy\GoAgent\gae_proxy\server\lib\httplib2\__init__.py", line 1593, in request
(response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
File "D:\Program Files\ChromeGAE\Proxy\GoAgent\gae_proxy\server\lib\httplib2\__init__.py", line 1341, in _request
(response, content) = self._conn_request(conn, request_uri, method, body, headers)
File "D:\Program Files\ChromeGAE\Proxy\GoAgent\gae_proxy\server\lib\httplib2\__init__.py", line 1277, in _conn_request
conn.connect()
File "D:\Program Files\ChromeGAE\Proxy\GoAgent\gae_proxy\server\lib\httplib2\__init__.py", line 1062, in connect
raise socket.error, msg
error: [Errno 10061] 
2016-04-06 18:38:52,778 - root - INFO - Retry 3 time...
2016-04-06 18:38:54,779 - root - INFO - =======================
2016-04-06 18:38:54,780 - root - INFO - Deploy failed appid list:
2016-04-06 18:38:54,782 - root - INFO - - freefly521071
2016-04-06 18:38:54,782 - root - INFO - - freefly521116
2016-04-06 18:38:54,783 - root - INFO - - freefly521521
2016-04-06 18:38:54,785 - root - INFO - - freefly521829
2016-04-06 18:38:54,785 - root - INFO - - freefly521930
2016-04-06 18:38:54,786 - root - INFO - - kylejoshua521
2016-04-06 18:38:54,786 - root - INFO - - kylejoshua521116
2016-04-06 18:38:54,786 - root - INFO - - kylejoshua521829
2016-04-06 18:38:54,788 - root - INFO - - kylejoshua521930
2016-04-06 18:38:54,788 - root - INFO - - kylemillton
2016-04-06 18:38:54,789 - root - INFO - == END ==

**Comment by jtlifos** [comment]
你确认是用原账号密码输入部署的吗？不如重新申请个账号算了

**Comment by freefly521** [comment]
没错，就是原账号密码，而且我即使重新申请了一个账号之后重试了，还是一样的错误？ 请问该怎么解决的呢

**Comment by jtlifos** [comment]
那看起来是你自己系统出了点问题，重装xxnet和chrome。

**Comment by noveleven** [comment]
XX开始会给你提供公用的appid，但是要想访问google，你还需要有可用的ip并建立socket链接后才能访问。所以你可以先等待一段时间去扫描可用ip，等到可以通过公共appid访问google之后再部署你的终端服务。或者你也可以通过内地google镜像网站去部署（如http://www.521google.com/等）

**Comment by jzp820927** [comment]
弱安全那些都弄了没
