### ISSUE TITLE
centos6.5 X64 执行失败

### ISSUE THREAD

**Issue by bigwboy** [XX-net/XX-Net#2770]
Apr 07 17:38:50.407 - [INFO] start XX-Net 2.9.4
Apr 07 17:38:50.408 - [DEBUG] start confirm_xxnet_exit
Apr 07 17:38:50.409 - [DEBUG] good, xxnet:8087 cleared!
Apr 07 17:38:50.410 - [DEBUG] good, xxnet:8085 clear!
Apr 07 17:38:50.410 - [DEBUG] finished confirm_xxnet_exit
Apr 07 17:38:50.464 - [ERROR] start module gae_proxy fail:invalid syntax (socks.py, line 213)
Apr 07 17:38:50.464 - [ERROR] Except stack:Traceback (most recent call last):
  File "/root/XX-Net-2.9.4/launcher/module_init.py", line 37, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "/root/XX-Net-2.9.4/gae_proxy/start.py", line 14, in <module>
    import local.proxy as client
  File "/root/XX-Net-2.9.4/gae_proxy/local/proxy.py", line 98, in <module>
    import proxy_handler
  File "/root/XX-Net-2.9.4/gae_proxy/local/proxy_handler.py", line 20, in <module>
    import gae_handler
  File "/root/XX-Net-2.9.4/gae_proxy/local/gae_handler.py", line 23, in <module>
    from connect_manager import https_manager
  File "/root/XX-Net-2.9.4/gae_proxy/local/connect_manager.py", line 14, in <module>
    import socks
  File "/root/XX-Net-2.9.4/python27/1.0/lib/noarch/socks.py", line 213
    if type not in {socket.SOCK_STREAM, socket.SOCK_DGRAM}:
                                      ^
SyntaxError: invalid syntax

Traceback (most recent call last):
  File "launcher/start.py", line 132, in <module>
    main()
  File "launcher/start.py", line 107, in main
    module_init.start_all_auto()
  File "/root/XX-Net-2.9.4/launcher/module_init.py", line 98, in start_all_auto
    start(module)
  File "/root/XX-Net-2.9.4/launcher/module_init.py", line 37, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "/root/XX-Net-2.9.4/gae_proxy/start.py", line 14, in <module>
    import local.proxy as client
  File "/root/XX-Net-2.9.4/gae_proxy/local/proxy.py", line 98, in <module>
    import proxy_handler
  File "/root/XX-Net-2.9.4/gae_proxy/local/proxy_handler.py", line 20, in <module>
    import gae_handler
  File "/root/XX-Net-2.9.4/gae_proxy/local/gae_handler.py", line 23, in <module>
    from connect_manager import https_manager
  File "/root/XX-Net-2.9.4/gae_proxy/local/connect_manager.py", line 14, in <module>
    import socks
  File "/root/XX-Net-2.9.4/python27/1.0/lib/noarch/socks.py", line 213
    if type not in {socket.SOCK_STREAM, socket.SOCK_DGRAM}:
                                      ^
SyntaxError: invalid syntax
Stopping all modules before exit!
Apr 07 17:38:50.465 - [ERROR] stop module gae_proxy fail:'imp'
Apr 07 17:38:50.465 - [ERROR] Except stack:Traceback (most recent call last):
  File "/root/XX-Net-2.9.4/launcher/module_init.py", line 71, in stop
    _start = proc_handler[module]["imp"].start
KeyError: 'imp'

**Comment by jzp820927** [comment]
估计是 python 版本太低了，对语法支持有问题，你看看 python 什么版本

**Comment by bigwboy** [comment]
我的是2.7的，我换成过3.4的版本，不过那样就更糟糕了。

**Comment by jzp820927** [comment]
3.4 要下载 python3 分支的版本才行

**Comment by bigwboy** [comment]
哪个版本是python3分支的

**Comment by jzp820927** [comment]
https://github.com/XX-net/XX-Net/tree/python3

**Comment by bigwboy** [comment]
感谢                                                                                                                                                                                                                                                                                                                                        发送自我的 BlackBerry 10 智能手机。                                                                                                                                                                                                                发件人： 天朝屁民已发送： 2016年4月7日星期四 21:36收件人： XX-net/XX-Net答复： XX-net/XX-Net抄送： bigwboy主题： Re: [XX-net/XX-Net] centos6.5 X64 执行失败 (#2770)https://github.com/XX-net/XX-Net/tree/python3

—You are receiving this because you authored the thread.Reply to this email directly or view it on GitHub
