### ISSUE TITLE
WIN7 HOME PREMIU 64 不能用 原来用的旗舰版没问题.求教

### ISSUE THREAD

**Issue by picfan** [XX-net/XX-Net#2812]
C:\Users\Bin\Downloads\XX-Net-2.9.6>SET PYTHONPATH=

C:\Users\Bin\Downloads\XX-Net-2.9.6>"C:\Users\Bin\Downloads\XX-Net-2.9.6\python2
7/1.0/python.exe" "C:\Users\Bin\Downloads\XX-Net-2.9.6\launcher/start.py"
Traceback (most recent call last):
  File "C:\Users\Bin\Downloads\XX-Net-2.9.6\launcher/start.py", line 63, in <mod
ule>
    from win_tray import sys_tray
  File "C:\Users\Bin\Downloads\XX-Net-2.9.6\launcher\win_tray.py", line 19, in <
module>
    import module_init
  File "C:\Users\Bin\Downloads\XX-Net-2.9.6\launcher\module_init.py", line 6, in
 <module>
    import config
  File "C:\Users\Bin\Downloads\XX-Net-2.9.6\launcher\config.py", line 5, in <mod
ule>
    from distutils.version import LooseVersion
ImportError: No module named distutils.version

C:\Users\Bin\Downloads\XX-Net-2.9.6>pause
请按任意键继续. . .

**Comment by jzp820927** [comment]
重新下载覆盖试试

**Comment by andytree** [comment]
我解决了，其实是因为使用快压解压，使用7.ZIP解压出来使用就OK。。
