### ISSUE TITLE
申请了两个GAE AppID。为什么部署配置不成功呢，根据攻略来的啊。

### ISSUE THREAD

**Issue by keliandemao123** [XX-net/XX-Net#2839]
2016-04-11 16:16:43,266 - root - INFO - set proxy to http://127.0.0.1:8087
2016-04-11 16:16:43,266 - root - INFO - ============ Begin upload ============
2016-04-11 16:16:43,266 - root - INFO - appid:maomi746
2016-04-11 16:16:43,282 - root - INFO - Send: /api/appversion/rollback, params={'version': '1', 'app_id': 'maomi746'}
2016-04-11 16:16:54,588 - root - ERROR - upload fail:ServerNotFoundError('Unable to find the server at appengine.google.com',)
Traceback (most recent call last):
File "C:\Users\Administrator\Desktop\XX-Net-2.9.4\gae_proxy\server\uploader.py", line 70, in upload
result = appcfg.AppCfgApp(['appcfg', 'rollback', dirname ]).Run()
File "C:\Users\Administrator\Desktop\XX-Net-2.9.4\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 2951, in Run
self.action(self)
File "C:\Users\Administrator\Desktop\XX-Net-2.9.4\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 5044, in __call__
return method()
File "C:\Users\Administrator\Desktop\XX-Net-2.9.4\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 4397, in Rollback
self._Rollback()
File "C:\Users\Administrator\Desktop\XX-Net-2.9.4\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 4442, in _Rollback
appversion.Rollback(force_rollback)
File "C:\Users\Administrator\Desktop\XX-Net-2.9.4\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 2362, in Rollback
force_rollback='1' if force_rollback else '0')
File "C:\Users\Administrator\Desktop\XX-Net-2.9.4\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 1696, in Send
result = self.rpcserver.Send(url, payload=payload, **kwargs)
File "C:\Users\Administrator\Desktop\XX-Net-2.9.4\gae_proxy\server\lib\google\appengine\tools\appengine_rpc_httplib2.py", line 247, in Send
url, method=method, body=payload, headers=headers)
File "C:\Users\Administrator\Desktop\XX-Net-2.9.4\gae_proxy\server\lib\httplib2\__init__.py", line 1593, in request
(response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
File "C:\Users\Administrator\Desktop\XX-Net-2.9.4\gae_proxy\server\lib\httplib2\__init__.py", line 1341, in _request
(response, content) = self._conn_request(conn, request_uri, method, body, headers)
File "C:\Users\Administrator\Desktop\XX-Net-2.9.4\gae_proxy\server\lib\httplib2\__init__.py", line 1283, in _conn_request
raise ServerNotFoundError("Unable to find the server at %s" % conn.host)
ServerNotFoundError: Unable to find the server at appengine.google.com
2016-04-11 16:16:54,588 - root - INFO - Retry 1 time...
2016-04-11 16:16:54,631 - root - INFO - Send: /api/appversion/rollback, params={'version': '1', 'app_id': 'maomi746'}
2016-04-11 16:17:05,671 - root - ERROR - upload fail:ServerNotFoundError('Unable to find the server at appengine.google.com',)
Traceback (most recent call last):
File "C:\Users\Administrator\Desktop\XX-Net-2.9.4\gae_proxy\server\uploader.py", line 70, in upload
result = appcfg.AppCfgApp(['appcfg', 'rollback', dirname ]).Run()
File "C:\Users\Administrator\Desktop\XX-Net-2.9.4\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 2951, in Run
self.action(self)
File "C:\Users\Administrator\Desktop\XX-Net-2.9.4\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 5044, in __call__
return method()
File "C:\Users\Administrator\Desktop\XX-Net-2.9.4\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 4397, in Rollback
self._Rollback()
File "C:\Users\Administrator\Desktop\XX-Net-2.9.4\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 4442, in _Rollback
appversion.Rollback(force_rollback)
File "C:\Users\Administrator\Desktop\XX-Net-2.9.4\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 2362, in Rollback
force_rollback='1' if force_rollback else '0')
File "C:\Users\Administrator\Desktop\XX-Net-2.9.4\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 1696, in Send
result = self.rpcserver.Send(url, payload=payload, **kwargs)
File "C:\Users\Administrator\Desktop\XX-Net-2.9.4\gae_proxy\server\lib\google\appengine\tools\appengine_rpc_httplib2.py", line 247, in Send
url, method=method, body=payload, headers=headers)
File "C:\Users\Administrator\Desktop\XX-Net-2.9.4\gae_proxy\server\lib\httplib2\__init__.py", line 1593, in request
(response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
File "C:\Users\Administrator\Desktop\XX-Net-2.9.4\gae_proxy\server\lib\httplib2\__init__.py", line 1341, in _request
(response, content) = self._conn_request(conn, request_uri, method, body, headers)
File "C:\Users\Administrator\Desktop\XX-Net-2.9.4\gae_proxy\server\lib\httplib2\__init__.py", line 1283, in _conn_request
raise ServerNotFoundError("Unable to find the server at %s" % conn.host)
ServerNotFoundError: Unable to find the server at appengine.google.com
2016-04-11 16:17:05,673 - root - INFO - Retry 2 time...
2016-04-11 16:17:06,697 - root - INFO - Send: /api/appversion/rollback, params={'version': '1', 'app_id': 'maomi746'}
2016-04-11 16:17:17,739 - root - ERROR - upload fail:ServerNotFoundError('Unable to find the server at appengine.google.com',)
Traceback (most recent call last):
File "C:\Users\Administrator\Desktop\XX-Net-2.9.4\gae_proxy\server\uploader.py", line 70, in upload
result = appcfg.AppCfgApp(['appcfg', 'rollback', dirname ]).Run()
File "C:\Users\Administrator\Desktop\XX-Net-2.9.4\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 2951, in Run
self.action(self)
File "C:\Users\Administrator\Desktop\XX-Net-2.9.4\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 5044, in __call__
return method()
File "C:\Users\Administrator\Desktop\XX-Net-2.9.4\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 4397, in Rollback
self._Rollback()
File "C:\Users\Administrator\Desktop\XX-Net-2.9.4\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 4442, in _Rollback
appversion.Rollback(force_rollback)
File "C:\Users\Administrator\Desktop\XX-Net-2.9.4\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 2362, in Rollback
force_rollback='1' if force_rollback else '0')
File "C:\Users\Administrator\Desktop\XX-Net-2.9.4\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 1696, in Send
result = self.rpcserver.Send(url, payload=payload, **kwargs)
File "C:\Users\Administrator\Desktop\XX-Net-2.9.4\gae_proxy\server\lib\google\appengine\tools\appengine_rpc_httplib2.py", line 247, in Send
url, method=method, body=payload, headers=headers)
File "C:\Users\Administrator\Desktop\XX-Net-2.9.4\gae_proxy\server\lib\httplib2\__init__.py", line 1593, in request
(response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
File "C:\Users\Administrator\Desktop\XX-Net-2.9.4\gae_proxy\server\lib\httplib2\__init__.py", line 1341, in _request
(response, content) = self._conn_request(conn, request_uri, method, body, headers)
File "C:\Users\Administrator\Desktop\XX-Net-2.9.4\gae_proxy\server\lib\httplib2\__init__.py", line 1283, in _conn_request
raise ServerNotFoundError("Unable to find the server at %s" % conn.host)
ServerNotFoundError: Unable to find the server at appengine.google.com
2016-04-11 16:17:17,740 - root - INFO - Retry 3 time...
2016-04-11 16:17:19,743 - root - INFO - =======================
2016-04-11 16:17:19,743 - root - INFO - Deploy failed appid list:
2016-04-11 16:17:19,743 - root - INFO - - maomi746
2016-04-11 16:17:19,743 - root - INFO - == END ==

**Comment by keliandemao123** [comment]
总是失败，现在还是用的公共APPID

**Comment by jzp820927** [comment]
2016-04-11 16:16:54,588 - root - ERROR - upload fail:ServerNotFoundError('Unable to find the server at appengine.google.com',)

appid 没弄错吧

**Comment by keliandemao123** [comment]
没有啊 就根据攻略一步步来的

**Comment by jzp820927** [comment]
你是在 web 界面部署到吗？

**Comment by keliandemao123** [comment]
是啊 是在浏览器里部署的

**Comment by keliandemao123** [comment]
注册了两个ID。都能查的到

**Comment by xxnet** [comment]
这种情况是ip不支持 appengine.google.com 的direct 模式。
简单的方法是下载开发分支版本：https://github.com/XX-net/XX-Net/archive/master.zip
爱折腾的修改 gae_proxy/local/proxy.ini
 把 appengine.google.com = direct 这行后面改成gae
  另外 www.google.com = direct 也改成 www.google.com = gae
