### ISSUE TITLE
问个openwrt部署XX-Net的问题

### ISSUE THREAD

**Issue by binbin000** [XX-net/XX-Net#2843]
上传完，在启动的时候提示错误，小白一枚，不知道怎么树立，求指教

root@OpenWrt:~# bash /XX-Net/start.sh
Apr 11 22:25:57.960 - [INFO] start XX-Net get_version_fail
Apr 11 22:25:57.962 - [DEBUG] start confirm_xxnet_exit
Apr 11 22:25:57.985 - [DEBUG] good, xxnet:8087 cleared!
Apr 11 22:25:57.998 - [DEBUG] good, xxnet:8085 clear!
Apr 11 22:25:57.999 - [DEBUG] finished confirm_xxnet_exit
Apr 11 22:25:58.219 - [INFO] load manual.ini success
/usr/bin/python2.7: '/XX-Net/python27/1.0/lib/linux/OpenSSL/crypto.so' is not an                                                                              ELF executable for MIPS
Apr 11 22:25:58.307 - [ERROR] start module gae_proxy fail:File not found
Apr 11 22:25:58.338 - [ERROR] Except stack:Traceback (most recent call last):
  File "/XX-Net/launcher/module_init.py", line 37, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['loca                                                                             l', 'start'], -1)
  File "/XX-Net/gae_proxy/start.py", line 14, in <module>
    import local.proxy as client
  File "/XX-Net/gae_proxy/local/proxy.py", line 95, in <module>
    from cert_util import CertUtil
  File "/XX-Net/gae_proxy/local/cert_util.py", line 38, in <module>
    import OpenSSL
  File "/XX-Net/python27/1.0/lib/linux/OpenSSL/__init__.py", line 36, in <module                                                                             >
    from OpenSSL import crypto
ImportError: File not found

Traceback (most recent call last):
  File "launcher/start.py", line 135, in <module>
    main()
  File "launcher/start.py", line 110, in main
    module_init.start_all_auto()
  File "/XX-Net/launcher/module_init.py", line 98, in start_all_auto
    start(module)
  File "/XX-Net/launcher/module_init.py", line 37, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['loca                                                                             l', 'start'], -1)
  File "/XX-Net/gae_proxy/start.py", line 14, in <module>
    import local.proxy as client
  File "/XX-Net/gae_proxy/local/proxy.py", line 95, in <module>
    from cert_util import CertUtil
  File "/XX-Net/gae_proxy/local/cert_util.py", line 38, in <module>
    import OpenSSL
  File "/XX-Net/python27/1.0/lib/linux/OpenSSL/__init__.py", line 36, in <module                                                                             >
    from OpenSSL import crypto
ImportError: File not found
Stopping all modules before exit!
Apr 11 22:25:58.353 - [ERROR] stop module gae_proxy fail:'imp'
Apr 11 22:25:58.355 - [ERROR] Except stack:Traceback (most recent call last):
  File "/XX-Net/launcher/module_init.py", line 71, in stop
    _start = proc_handler[module]["imp"].start
KeyError: 'imp'

**Comment by jzp820927** [comment]
Apr 11 22:25:58.307 - [ERROR] start module gae_proxy fail:File not found

未找到文件，检查文件上传是否完整

**Comment by binbin000** [comment]
你好，文件是上传完了得，是不是权限的问题啊，我发现所有文件都没有执行权限啊

除了文件夹权限都是  rw-r--r--

**Comment by binbin000** [comment]
/usr/bin/python2.7: '/XX-Net/python27/1.0/lib/linux/OpenSSL/crypto.so' is not an ELF executable for MIPS
 
这句是不是说什么不对啊，纯小白一枚，真弄不好就算了。。。

确认了不是权限问题

**Comment by jzp820927** [comment]
好像是不支持 MIPS CPU。

**Comment by xxnet** [comment]
试试:
rm -rf /XX-Net/python27/1.0/lib/linux/OpenSSL/
然后安装 pyOpenSSL

**Comment by binbin000** [comment]
@xxnet
 pyopenssl是不是就是python-openssl     openwrt源里面只有python-openssl

按照你的方法还是不行，下面是提示，貌似是没有openssl，难道只能试试mini了吗？还是说openwrt没有pyopenssl的缘故？

root@OpenWrt:~# bash /XX-Net/start.sh
Apr 14 21:45:10.090 - [INFO] start XX-Net get_version_fail
Apr 14 21:45:10.092 - [DEBUG] start confirm_xxnet_exit
Apr 14 21:45:10.114 - [DEBUG] good, xxnet:8087 cleared!
Apr 14 21:45:10.126 - [DEBUG] good, xxnet:8085 clear!
Apr 14 21:45:10.128 - [DEBUG] finished confirm_xxnet_exit
Apr 14 21:45:10.327 - [INFO] load manual.ini success
Apr 14 21:45:10.381 - [ERROR] start module gae_proxy fail:No module named OpenSSL
Apr 14 21:45:10.387 - [ERROR] Except stack:Traceback (most recent call last):
  File "/XX-Net/launcher/module_init.py", line 37, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "/XX-Net/gae_proxy/start.py", line 14, in <module>
    import local.proxy as client
  File "/XX-Net/gae_proxy/local/proxy.py", line 95, in <module>
    from cert_util import CertUtil
  File "/XX-Net/gae_proxy/local/cert_util.py", line 38, in <module>
    import OpenSSL
ImportError: No module named OpenSSL

Traceback (most recent call last):
  File "launcher/start.py", line 135, in <module>
    main()
  File "launcher/start.py", line 110, in main
    module_init.start_all_auto()
  File "/XX-Net/launcher/module_init.py", line 98, in start_all_auto
    start(module)
  File "/XX-Net/launcher/module_init.py", line 37, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "/XX-Net/gae_proxy/start.py", line 14, in <module>
    import local.proxy as client
  File "/XX-Net/gae_proxy/local/proxy.py", line 95, in <module>
    from cert_util import CertUtil
  File "/XX-Net/gae_proxy/local/cert_util.py", line 38, in <module>
    import OpenSSL
ImportError: No module named OpenSSL
Stopping all modules before exit!
Apr 14 21:45:10.402 - [ERROR] stop module gae_proxy fail:'imp'
Apr 14 21:45:10.404 - [ERROR] Except stack:Traceback (most recent call last):
  File "/XX-Net/launcher/module_init.py", line 71, in stop
    _start = proc_handler[module]["imp"].start
KeyError: 'imp'

**Comment by jzp820927** [comment]
Apr 14 21:45:10.381 - [ERROR] start module gae_proxy fail:No module named OpenSSL

确实是没有 pyopenssl
