### ISSUE TITLE
启动后报错：start module gae_proxy fail:DLL load failed: 操作 系统无法运行 %1。

### ISSUE THREAD

**Issue by sunking0505** [XX-net/XX-Net#2847]
D:\云梯\XX-Net-master>SET PYTHONPATH=

D:\云梯\XX-Net-master>"D:\云梯\XX-Net-master\python27/1.0/python.exe" "D:\云梯\X
X-Net-master\launcher/start.py"
Apr 11 23:46:07.549 - [INFO] start XX-Net get_version_fail
Apr 11 23:46:07.550 - [DEBUG] start confirm_xxnet_exit
Apr 11 23:46:09.505 - [DEBUG] good, xxnet:8087 cleared!
Apr 11 23:46:10.510 - [DEBUG] good, xxnet:8085 clear!
Apr 11 23:46:10.512 - [DEBUG] finished confirm_xxnet_exit
Apr 11 23:46:10.566 - [ERROR] start module gae_proxy fail:DLL load failed: 操作
系统无法运行 %1。
Apr 11 23:46:10.569 - [ERROR] Except stack:Traceback (most recent call last):
  File "D:\云梯\XX-Net-master\launcher\module_init.py", line 37, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['loca
l', 'start'], -1)
  File "D:\云梯\XX-Net-master\gae_proxy\start.py", line 14, in <module>
    import local.proxy as client
  File "D:\云梯\XX-Net-master\gae_proxy\local\proxy.py", line 95, in <module>
    from cert_util import CertUtil
  File "D:\云梯\XX-Net-master\gae_proxy\local\cert_util.py", line 38, in <module
>
    import OpenSSL
  File "D:\云梯\XX-Net-master\python27\1.0\lib\win32\OpenSSL\__init__.py", line
26, in <module>
    from OpenSSL import crypto, rand, SSL
ImportError: DLL load failed: 操作系统无法运行 %1。

Traceback (most recent call last):
  File "D:\云梯\XX-Net-master\launcher/start.py", line 135, in <module>
    main()
  File "D:\云梯\XX-Net-master\launcher/start.py", line 110, in main
    module_init.start_all_auto()
  File "D:\云梯\XX-Net-master\launcher\module_init.py", line 98, in start_all_au
to
    start(module)
  File "D:\云梯\XX-Net-master\launcher\module_init.py", line 37, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['loca
l', 'start'], -1)
  File "D:\云梯\XX-Net-master\gae_proxy\start.py", line 14, in <module>
    import local.proxy as client
  File "D:\云梯\XX-Net-master\gae_proxy\local\proxy.py", line 95, in <module>
    from cert_util import CertUtil
  File "D:\云梯\XX-Net-master\gae_proxy\local\cert_util.py", line 38, in <module
>
    import OpenSSL
  File "D:\云梯\XX-Net-master\python27\1.0\lib\win32\OpenSSL\__init__.py", line
26, in <module>
    from OpenSSL import crypto, rand, SSL
ImportError: DLL load failed: 操作系统无法运行 %1。
Stopping all modules before exit!
Apr 11 23:46:10.580 - [ERROR] stop module gae_proxy fail:'imp'
Apr 11 23:46:10.581 - [ERROR] Except stack:Traceback (most recent call last):
  File "D:\云梯\XX-Net-master\launcher\module_init.py", line 71, in stop
    _start = proc_handler[module]["imp"].start
KeyError: 'imp'

D:\云梯\XX-Net-master>pause
请按任意键继续. . .

**Comment by jzp820927** [comment]
试试下载最新版覆盖

**Comment by sunking0505** [comment]
下载了2.9.4版本，启动后还是报一样的错

**Comment by jzp820927** [comment]
对了，路径不要有中文，好像容易出问题

**Comment by xxnet** [comment]
​什么操作系统？

**Comment by sunking0505** [comment]
WIN7 专业版 SP1。另：我更改了中文路径为英文的也同样报错。

**Comment by jzp820927** [comment]
那就不知道是什么问题了，问X大吧

**Comment by xxnet** [comment]
​试试早期的版本 2.8.9
看看是不是新版python引入的
