### ISSUE TITLE
打开XX-NET时，没有弹出配置页面，也没有任务栏图标

### ISSUE THREAD

**Issue by bnbplayer** [XX-net/XX-Net#2876]
如题。给人的感觉就是放佛没有正常启动。但是我却能够上gmail和YouTube，不过打开facebook就会出问题。

其中，任务管理器有Pythonnow的进程。

双击start.bat后，控制台返回的结果如下：

E:\common tools\XX-Net-master>SET PYTHONPATH=

E:\common tools\XX-Net-master>"E:\common tools\XX-Net-master\python27/1.0/python
.exe" "E:\common tools\XX-Net-master\launcher/start.py"
Apr 13 22:17:56.791 - [INFO] start XX-Net get_version_fail
Apr 13 22:17:56.791 - [DEBUG] start confirm_xxnet_exit
Apr 13 22:17:57.805 - [DEBUG] good, xxnet:8087 cleared!
Apr 13 22:17:58.819 - [DEBUG] good, xxnet:8085 clear!
Apr 13 22:17:58.819 - [DEBUG] finished confirm_xxnet_exit
Apr 13 22:18:00.541 - [DEBUG] network is ok, cost:1674 ms
Apr 13 22:18:00.557 - [INFO] SSL use version:TLSv1
Apr 13 22:18:01.146 - [INFO] load ip range file:E:\common tools\XX-Net-master\da
ta\gae_proxy\ip_range.txt
Apr 13 22:18:01.208 - [INFO] load google ip_list num:2339, gws num:2339
Apr 13 22:18:01.270 - [DEBUG] ## GAEProxy set keep_running: True
Apr 13 22:18:01.270 - [INFO] ---------------------------------------------------
---
Apr 13 22:18:01.270 - [INFO] Python Version     : 2.7.11
Apr 13 22:18:01.270 - [INFO] OS                 : Version:6-1; Build:7601; Platf
orm:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
Apr 13 22:18:01.270 - [INFO] Listen Address     : 127.0.0.1:8087
Apr 13 22:18:01.270 - [INFO] GAE APPID          : leavemealone-1135
Apr 13 22:18:01.270 - [INFO] Pac Server         : http://127.0.0.1:8086/proxy.pa
c
Apr 13 22:18:01.286 - [INFO] ---------------------------------------------------
---
Apr 13 22:18:01.305 - [INFO] server 127.0.0.1:8087 started.
Apr 13 22:18:01.308 - [INFO] server 127.0.0.1:8086 started.
Apr 13 22:18:01.363 - [INFO] module gae_proxy started
Apr 13 22:18:01.363 - [INFO] start gae_proxy time cost:2543 ms
WARNING:root:Load Crypto.Cipher.ARC4 Failed, Use Pure Python Instead.
Apr 13 22:18:01.378 - [INFO] use config_path:E:\common tools\XX-Net-master\data\
x_tunnel\client.json
Apr 13 22:18:01.378 - [INFO] Use proxy:127.0.0.1:8087
Apr 13 22:18:01.378 - [DEBUG] x-tunnel no account
Apr 13 22:18:01.378 - [WARNING] x-tunnel session not start
Apr 13 22:18:01.378 - **[ERROR] bind to 127.0.0.1:1080 fail**
Exception in thread Thread-207:
Traceback (most recent call last):
  File "E:\common tools\XX-Net-master\python27\1.0\lib\threading.py", line 801,
in __bootstrap_inner
    self.run()
  File "E:\common tools\XX-Net-master\python27\1.0\lib\threading.py", line 754,
in run
    self.__target(*self.__args, **self.__kwargs)
  File "E:\common tools\XX-Net-master\x_tunnel\start.py", line 19, in main
    client.main()
  File "E:\common tools\XX-Net-master\x_tunnel\local\client.py", line 154, in ma
in
    g.socks5_server = simple_http_server.HTTPServer((g.config.socks_host, g.conf
ig.socks_port), Socks5Server)
  File "E:\common tools\XX-Net-master\python27\1.0\lib\noarch\simple_http_server
.py", line 259, in __init__
    self.init_socket()
  File "E:\common tools\XX-Net-master\python27\1.0\lib\noarch\simple_http_server
.py", line 264, in init_socket
    self.add_listen(addr)
  File "E:\common tools\XX-Net-master\python27\1.0\lib\noarch\simple_http_server
.py", line 273, in add_listen
    raise e
error: [Errno 10013]

可见，返回了端口绑定错误，还有一个10013错误

求解决

**Comment by heiheihei120** [comment]
我先开网页再开xxnet能打开xx 你试试

**Comment by jzp820927** [comment]
看看书什么占用 1080 端口了
