### ISSUE TITLE
Debian系统下无法打开127.0.0.1:8085

### ISSUE THREAD

**Issue by supvesonico** [XX-net/XX-Net#2900]
以前安装过xx-net，然后删除了整个文件夹之后重新下载了最新的xx-net（之前不知道怎么回事无法更新），启动之后托盘图标没有了，于是想去管理页面调出来，结果访问127.0.0.1:8085失败，请问是否是管理页面地址更新了？

**Comment by supvesonico** [comment]
补充：可以正常使用也可以正常上Google等网站……

**Comment by supvesonico** [comment]
ps.通过terminal启动xx-net疑似是错误日志的一些东西：
Exception in thread Thread-57:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/sonico/.XX-Net-2.9.4/x_tunnel/start.py", line 19, in main
    client.main()
  File "/home/sonico/.XX-Net-2.9.4/x_tunnel/local/client.py", line 154, in main
    g.socks5_server = simple_http_server.HTTPServer((g.config.socks_host, g.config.socks_port), Socks5Server)
  File "/home/sonico/.XX-Net-2.9.4/python27/1.0/lib/noarch/simple_http_server.py", line 259, in __init__
    self.init_socket()
  File "/home/sonico/.XX-Net-2.9.4/python27/1.0/lib/noarch/simple_http_server.py", line 264, in init_socket
    self.add_listen(addr)
  File "/home/sonico/.XX-Net-2.9.4/python27/1.0/lib/noarch/simple_http_server.py", line 273, in add_listen
    raise e

**Comment by jzp820927** [comment]
检查下，是不是监听端口有冲突

**Comment by supvesonico** [comment]
日志显示并无冲突，netcat也并未查找到端口有任何异常

**Comment by jzp820927** [comment]
那也不太明白了，等XX老大来看看吧

**Comment by xxnet** [comment]
监听到8085端口时失败，怀疑是被占用了
​用 sudo netstat -napl |grep 8085
看有什么输出，如果找到对应进程，把它杀掉试试

**Comment by supvesonico** [comment]
并无回显…事实上在命令行启动的时候它日志信息显示的就是在8085上成功启动，good什么的……

**Comment by frankie-huang** [comment]
同样sudo netstat -napl |grep 8085后无回显，谷歌上得去，youtube打得开，就是无法访问xx-net 主页127.0.0.1:8085
