### ISSUE TITLE
 bodhi3.0启动XX-net出错!

### ISSUE THREAD

**Issue by Anway2** [XX-net/XX-Net#2904]
事先已安装ibnss3-tools和python-gtk2。进入文件目录后，直接终端输入“sudo ./start.sh"，输入root密码，弹出一堆文字（如下）后自动退出。How?Why?

4月 15 15:03:49.5 - [INFO] start XX-Net 2.9.4
4月 15 15:03:49.5 - [DEBUG] start confirm_xxnet_exit
4月 15 15:03:49.5 - [DEBUG] good, xxnet:8087 cleared!
4月 15 15:03:49.5 - [DEBUG] good, xxnet:8085 clear!
4月 15 15:03:49.5 - [DEBUG] finished confirm_xxnet_exit
4月 15 15:03:49.5 - [ERROR] start module gae_proxy fail:/home/anway/Downloads/XX-Net-2.9.4/python27/1.0/lib/linux/OpenSSL/crypto.so: wrong ELF class: ELFCLASS64
4月 15 15:03:49.5 - [ERROR] Except stack:Traceback (most recent call last):
File "/home/anway/Downloads/XX-Net-2.9.4/launcher/module_init.py", line 37, in start
proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
File "/home/anway/Downloads/XX-Net-2.9.4/gae_proxy/start.py", line 14, in <module>
import local.proxy as client
File "/home/anway/Downloads/XX-Net-2.9.4/gae_proxy/local/proxy.py", line 95, in <module>
from cert_util import CertUtil
File "/home/anway/Downloads/XX-Net-2.9.4/gae_proxy/local/cert_util.py", line 38, in <module>
import OpenSSL
File "/home/anway/Downloads/XX-Net-2.9.4/python27/1.0/lib/linux/OpenSSL/__init__.py", line 36, in <module>
from OpenSSL import crypto
ImportError: /home/anway/Downloads/XX-Net-2.9.4/python27/1.0/lib/linux/OpenSSL/crypto.so: wrong ELF class: ELFCLASS64

Traceback (most recent call last):
File "launcher/start.py", line 132, in <module>
main()
File "launcher/start.py", line 107, in main
module_init.start_all_auto()
File "/home/anway/Downloads/XX-Net-2.9.4/launcher/module_init.py", line 98, in start_all_auto
start(module)
File "/home/anway/Downloads/XX-Net-2.9.4/launcher/module_init.py", line 37, in start
proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
File "/home/anway/Downloads/XX-Net-2.9.4/gae_proxy/start.py", line 14, in <module>
import local.proxy as client
File "/home/anway/Downloads/XX-Net-2.9.4/gae_proxy/local/proxy.py", line 95, in <module>
from cert_util import CertUtil
File "/home/anway/Downloads/XX-Net-2.9.4/gae_proxy/local/cert_util.py", line 38, in <module>
import OpenSSL
File "/home/anway/Downloads/XX-Net-2.9.4/python27/1.0/lib/linux/OpenSSL/__init__.py", line 36, in <module>
from OpenSSL import crypto
ImportError: /home/anway/Downloads/XX-Net-2.9.4/python27/1.0/lib/linux/OpenSSL/crypto.so: wrong ELF class: ELFCLASS64
Stopping all modules before exit!
4月 15 15:03:49.5 - [ERROR] stop module gae_proxy fail:'imp'
4月 15 15:03:49.5 - [ERROR] Except stack:Traceback (most recent call last):
File "/home/anway/Downloads/XX-Net-2.9.4/launcher/module_init.py", line 71, in stop
_start = proc_handler[module]["imp"].start
KeyError: 'imp'

**Comment by jzp820927** [comment]
pip install pyopenssl

**Comment by xxnet** [comment]
默认提供的库是64位的，估计你的机器是32位的。

优先使用系统的pyopenssl 库，如果需要，试试删除自带的库：
​rm -rf /home/anway/Downloads/XX-Net-2.9.4/python27/1.0/lib/linux/OpenSSL/

**Comment by Anway2** [comment]
删除自带的库后问题依旧！

**Comment by jzp820927** [comment]
没用过这个系统，你是运行的 py2版本的XX，还是 py3 版本的XX

**Comment by xxnet** [comment]
​删除库后，日志贴出来看看

**Comment by Anway2** [comment]
4月 16 09:39:34.8 - [INFO] start XX-Net 2.9.4
 4月 16 09:39:34.8 - [DEBUG] start confirm_xxnet_exit
 4月 16 09:39:34.8 - [DEBUG] good, xxnet:8087 cleared!
 4月 16 09:39:34.8 - [DEBUG] good, xxnet:8085 clear!
 4月 16 09:39:34.8 - [DEBUG] finished confirm_xxnet_exit
 4月 16 09:39:34.8 - [ERROR] start module gae_proxy fail:No module named OpenSSL
 4月 16 09:39:34.8 - [ERROR] Except stack:Traceback (most recent call last):
  File "/home/anway/Downloads/XX-Net-2.9.4/launcher/module_init.py", line 37, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "/home/anway/Downloads/XX-Net-2.9.4/gae_proxy/start.py", line 14, in <module>
    import local.proxy as client
  File "/home/anway/Downloads/XX-Net-2.9.4/gae_proxy/local/proxy.py", line 95, in <module>
    from cert_util import CertUtil
  File "/home/anway/Downloads/XX-Net-2.9.4/gae_proxy/local/cert_util.py", line 38, in <module>
    import OpenSSL
ImportError: No module named OpenSSL

 4月 16 09:39:34.8 - [ERROR] stop module gae_proxy fail:'imp'
 4月 16 09:39:34.8 - [ERROR] Except stack:Traceback (most recent call last):
  File "/home/anway/Downloads/XX-Net-2.9.4/launcher/module_init.py", line 71, in stop
    _start = proc_handler[module]["imp"].start
KeyError: 'imp'

**Comment by xxnet** [comment]
缺 pyOpenSSL库，执行这句了没有？
​pip install pyopenssl

**Comment by Anway2** [comment]
执行了，不过似乎安装pyopenssl库没成功！

Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 283, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1436, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 672, in install
    self.move_wheel_files(self.source_dir, root=root)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 902, in move_wheel_files
    pycompile=self.pycompile,
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 206, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 193, in clobber
    os.makedirs(destsubdir)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/OpenSSL'

最后一句说是没权限，可我加sudo执行也不成功！

**Comment by xxnet** [comment]
bodhi 简介说是基于Ubuntu改的，你可以参考wiki的ubuntu文档，试试：
sudo apt-get install python-OpenSSL

**Comment by Anway2** [comment]
呵呵，搞定。太感谢了！
一直拘泥于pip install pyopenssl。其实apt-get install  python-OpenSSL就OK！

**Comment by jzp820927** [comment]
我的 ubuntu 用 pip install pyopenssl 就能搞定，不知道你的为什么不行

**Comment by Anway2** [comment]
也许版本不一致的原因吧！
家里另一台电脑是linuxmint17，XX那是拿来就能用，pip都不用。
感谢各位热情应助！
