### ISSUE TITLE
2.94和2.96版win7 64位无法启动，运行start.bat提示如下

### ISSUE THREAD

**Issue by flybord** [XX-net/XX-Net#2914]
D:\Documents\XX-Net>SET PYTHONPATH=

D:\Documents\XX-Net>"D:\Documents\XX-Net\python27/1.0/python.exe" "D:\Documents\
XX-Net\launcher/start.py"
Traceback (most recent call last):
  File "D:\Documents\XX-Net\launcher/start.py", line 63, in <module>
    from win_tray import sys_tray
  File "D:\Documents\XX-Net\launcher\win_tray.py", line 18, in <module>
    import win32_proxy_manager
  File "D:\Documents\XX-Net\python27\1.0\lib\win32\win32_proxy_manager.py", line
 22, in <module>
    CONNECTIONS = winreg.OpenKey(winreg.HKEY_CURRENT_USER, CONN_PATH, 0, winreg.
KEY_ALL_ACCESS)
WindowsError: [Error 5]

**Comment by xxnet** [comment]
​试试早期的版本 2.8.9 有没有这个问题
已分析是否新版改动带来的bug
