### ISSUE TITLE
好消息，3.00 大版本出来了，大家快来测试吧。。。

### ISSUE THREAD

**Issue by jzp820927** [XX-net/XX-Net#2915]
好消息，3.00 大版本出来了，大家快来测试吧。。。

**Comment by yeahwu** [comment]
然而启动报错，ubnutu14.04
```
4月 16 19:08:31.0 - [ERROR] start module gae_proxy fail:cannot import name init_context
 4月 16 19:08:31.0 - [ERROR] Except stack:Traceback (most recent call last):
  File "/home/will/XX-Net-3.0.0/code/default/launcher/module_init.py", line 37, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "/home/will/XX-Net-3.0.0/code/default/gae_proxy/start.py", line 13, in <module>
    import local.proxy as client
  File "/home/will/XX-Net-3.0.0/code/default/gae_proxy/local/proxy.py", line 98, in <module>
    import proxy_handler
  File "/home/will/XX-Net-3.0.0/code/default/gae_proxy/local/proxy_handler.py", line 54, in <module>
    import gae_handler
  File "/home/will/XX-Net-3.0.0/code/default/gae_proxy/local/gae_handler.py", line 67, in <module>
    from connect_manager import https_manager
  File "/home/will/XX-Net-3.0.0/code/default/gae_proxy/local/connect_manager.py", line 58, in <module>
    from google_ip import google_ip
  File "/home/will/XX-Net-3.0.0/code/default/gae_proxy/local/google_ip.py", line 15, in <module>
    import check_ip
  File "/home/will/XX-Net-3.0.0/code/default/gae_proxy/local/check_ip.py", line 33, in <module>
    from openssl_wrap import SSLConnection, init_context
ImportError: cannot import name init_context

 4月 16 19:08:31.0 - [ERROR] launcher except:ImportError('cannot import name init_context',)
 4月 16 19:08:31.1 - [ERROR] Except stack:Traceback (most recent call last):
  File "code/default/launcher/start.py", line 135, in <module>
  File "code/default/launcher/start.py", line 110, in main
  File "/home/will/XX-Net-3.0.0/code/default/launcher/module_init.py", line 98, in start_all_auto
    start(module)
  File "/home/will/XX-Net-3.0.0/code/default/launcher/module_init.py", line 37, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "/home/will/XX-Net-3.0.0/code/default/gae_proxy/start.py", line 13, in <module>
    import local.proxy as client
  File "/home/will/XX-Net-3.0.0/code/default/gae_proxy/local/proxy.py", line 98, in <module>
    import proxy_handler
  File "/home/will/XX-Net-3.0.0/code/default/gae_proxy/local/proxy_handler.py", line 54, in <module>
    import gae_handler
  File "/home/will/XX-Net-3.0.0/code/default/gae_proxy/local/gae_handler.py", line 67, in <module>
    from connect_manager import https_manager
  File "/home/will/XX-Net-3.0.0/code/default/gae_proxy/local/connect_manager.py", line 58, in <module>
    from google_ip import google_ip
  File "/home/will/XX-Net-3.0.0/code/default/gae_proxy/local/google_ip.py", line 15, in <module>
    import check_ip
  File "/home/will/XX-Net-3.0.0/code/default/gae_proxy/local/check_ip.py", line 33, in <module>
    from openssl_wrap import SSLConnection, init_context
ImportError: cannot import name init_context

Press any to exit...
```

**Comment by xxnet** [comment]
​3.0.0 有问题，试试3.0.1

**Comment by pm19960106** [comment]
3.0.1！？

**Comment by yeahwu** [comment]
刚简单测了一下，配置项不能保存自己的appid，
然后今天才知道火狐证书自动导入，很牛

**Comment by jzp820927** [comment]
@pm19960106 3.XX 大版本的设计目标是 模块化的重构，也就是说，按需下载和运行，不像 2.XX 是一个版本适应所有平台，对于每种不同的平台，都会有一些多余的库文件，而且大版本对自动更新也不太适应，文件太大太多，容易造成下载断流，运行出错，所以这个版本可以从根本解决在线更新的问题。

**Comment by pm19960106** [comment]
Chrome要怎么改成自己的appid？部署完保存以后还是公共appid

**Comment by yeahwu** [comment]
@pm19960106 看来是bug，等3.02版吧，呵呵

**Comment by causlayer** [comment]
mac 10.11.4升级后无法启动

**Comment by yeahwu** [comment]
建议下载2.9.7版使用，ip段更新了，不易出问题。

**Comment by jzp820927** [comment]
确实，这个是测试版，不适合要稳定使用的，稳定使用还是暂时用 2.xx 好，3.xx 主要是用来测试 bug，适合 小白鼠

**Comment by Anway2** [comment]
3.0.2已出，修正不能保存appid!

**Comment by xxnet** [comment]
目前主要解决升级问题。

目录结构进行了重构，适应自动升级，并且在升级失败时不会导致无法使用。
调整策略：
+ 原来根目录下的模块，移动到 code/$version 目录下  
  这样不同版本的代码可以共存，在升级时，代码放在新的目录下，不会因为覆盖代码导致失效。  
  启动时读取code/version.txt，判断启动的版本。升级也是在升级成功后，修改这个文件，达到切换版本的目标。  
  默认版本是“default”，避免git 目录发布时需要变化，以及冲突处理的麻烦  

+ 各版本号文件  
 code/version.txt           当前工作的版本号  
 code/default/download.md       github上新用户下载页面   
  |code/default/update_version.txt     可供更新的版本

**Comment by xxnet** [comment]
3.0.1 可以试试能否升级到3.0.2

**Comment by jzp820927** [comment]
行，我先下个 3.0.1 测试下在线升级 3.0.2

**Comment by jzp820927** [comment]
对了，这次 目录调整，对 data 用户数据目录没有影响吧？也就是说，2.xx 的data 可以直接用于 3.xx 吧？

**Comment by xxnet** [comment]
@jzp820927 分模块的计划做了调整：
   把模块分得细，会出现接近10个模块/20个不同分支版本，担心整个系统变复杂，难以维护。  
   改进为：先进行结构调整，解决自动升级问题，暂不细分模块。  
   后面再进一步调整，逐步把大的非核心模块分离出来，目前有两个大模块可以分解：
+   python win32的执行环境，可以减少一半的大小。
+  gae 部署的库，在需要时才在后台自动下载

data目录没有改动

**Comment by jzp820927** [comment]
恩，这个设计不错，我觉得最优先要考虑分离处理的模块应该是执行环境，因为执行环境一般很少升级，而且文件体积也最大，而且也只用下载一次，可以说是只要下载一次，就不用管的东西。
然后在 web 端的升级页面，可以考虑把各个模块的升级分开处理（每个模块对应一个 branch），类似下面这样。

XX-NET 核心模块         当前版本：3.0.0     最新版本：3.0.2      可升级 | 升级按钮(亮色)
python 执行环境(win)  当前版本：2.7.11    最新版本：2.7.11     无升级 | 升级按钮(灰色)
GAE 服务端                当前版本：1.0.0     最新版本：1.0.0       无升级 | 升级按钮(灰色)
X_TUNNTL 模块         当前版本：1.0.0     最新版本：1.0.0       无升级 | 升级按钮(灰色)

**Comment by xxnet** [comment]
@causlayer  
 单独下载3.0.2，运行start.sh后出什么错误？

**Comment by yeahwu** [comment]
3.0.1升级到3.0.2没有问题，id也能保存了。

**Comment by jzp820927** [comment]
这个版本最适合那些网络环境较差的用户来测试，比如 帝都，魔都之类的。网络较好地区测试，可能测试不出什么问题。

**Comment by xxnet** [comment]
征集mac用户：
start.command 删除了，需要start.sh启动。
另外Mac 下的开机自启动会存在问题，待处理。

**Comment by jzp820927** [comment]
屌丝一枚，帮不上什么忙了。。

**Comment by yeahwu** [comment]
@zjhzxhz 直接喊老方楼下的来测试

**Comment by yukuai0011** [comment]
哪里下载？？

**Comment by jzp820927** [comment]
@yukuai0011 https://github.com/XX-net/XX-Net/releases 这儿下载

**Comment by yeahwu** [comment]
@xxnet  这货升个级立马变成一个胖子，本来就2，30mb吧！升级后变成60多mb了。是不是default文件夹可以删掉了？

**Comment by zjhzxhz** [comment]
几天没动静果然有大动静~~ Let me try~~

**Comment by yeahwu** [comment]
@zjhzxhz 你看你这匿名做得多差，俺不但知道你是老方楼下的，还知道你用的是mac，话说你要是妹纸就好鸟……

**Comment by xxnet** [comment]
@yeahwu 目前还未默认删除default，以后看稳定了，就可以在升级成功后，自动删除前面的版本。

**Comment by zjhzxhz** [comment]
@yeahwu 
这大号就算了~ 你看那个小号其实还是不错的~

**Comment by yeahwu** [comment]
@zjhzxhz 其实在这里面俺也是有小号的，然而你们并不知道是哪个！哈哈哈

**Comment by xxnet** [comment]
@jzp820927 
  分模块升级，1.x.x 就是这么设计的，实践结果发现gae_proxy 高度依赖launcher，
分模块之后变复杂了，所以才改成一个版本号，简单明了。
以2.x.x的发展情况，升级依赖还是很明显，还有python源码其实很小，就考虑不分模块了

**Comment by ByeGFW** [comment]
@xxnet 
之前2.x版本在Mac下用`start.sh`没问题. 一会儿我试一下看~
那个开机启动的问题 我晚些时候看看能不能修复.

话说感觉只是建立了几个文件夹呀? 有模块化吗?

**Comment by jzp820927** [comment]
好吧，现在解决在线升级问题，以后在考虑模块分离的优化问题

**Comment by keyoushi** [comment]
嗯，试了下2.9.7，直接重新扫的，大概45分钟扫了快80个有效IP，连接池大概在10/50左右，速度还可以，流畅低帧720P和1080P。不错。等下再试试3.0.2

**Comment by yukuai0011** [comment]
现在（3.0.2）速度很好啊，看youtube1080p 30帧数无压力

**Comment by keyoushi** [comment]
OK,3.0.2版本也重新部署完毕，赶脚模块变化比较大，连快捷方式的指向都不一样了。有效IP目前还不多，但质量蛮好，速度很快。给作者赞一个。但X-TUNNEL的速度依然不如XX本身，逗比作者2333333o(^▽^)o~

**Comment by yeahwu** [comment]
看来新ip段还是很给力的，x-tunnel是为了手机端准备的，然后匿名性很好，这不也是为了大家的安全嘛。

**Comment by simonasd** [comment]
给力。

很多具体的细节可以慢慢敲定，这个新机制的框架先完善好，将来要做什么修改都容易。

**Comment by keyoushi** [comment]
@yeahwu 这货手机端能用？哪有教程瞻仰一番？

**Comment by jzp820927** [comment]
@keyoushi 目前有 开发板的 XXNET apk，你可以直接用 apk

**Comment by keyoushi** [comment]
@jzp820927 安卓版？duang~了........俺还是等ios版吧.......

**Comment by CHN008** [comment]
这个升级的方法好,把Data里的配置文件放到新的xx-net程序里面就能直接运行.

另外感觉怎么xx-mini连接速度和稳定性不如xx-net呢.

**Comment by yeahwu** [comment]
@CHN008 一样的东西，何来快慢之说，mini简练，对俺来说反而配置更简单，直观。

**Comment by CHN008** [comment]
@yeahwu 哦,好吧,也许是心理作用 哈哈.

刚上面忘记说了,新的xx-net,火狐中还要删除原来的证书,再重新导入证书;但是Chrome和搜狗之类的都不用,难道是火狐对安全要求的严格一些?

**Comment by yeahwu** [comment]
火狐的证书是单独在浏览器里面的，不同于chrome，安全方面火狐还是要好点的，毕竟开源，而且tor都在用。

**Comment by xxnet** [comment]
@simonasd 估计是下载包出错了，而python中解压没有报错。
看来要加上hash校验才行。

**Comment by keyoushi** [comment]
赶脚3.0.2版本对优质IP的检索还是有点问题，一共400个左右IP，每次都会在使用过程中出现有效IP慢慢减少到30左右，必须手动重新检查IP后，才会恢复到60左右，连接池的状态也才会恢复正常。

**Comment by CHN008** [comment]
@yeahwu 哦 明白了.我看了一下我Chrome里面Google域名的证书是ESET杀毒软件提供的.

**Comment by streamgo** [comment]
3.0.2版本在哪里可以下载？

**Comment by keyoushi** [comment]
@streamgo  https://github.com/XX-net/XX-Net/releases/tag/3.0.2

**Comment by streamgo** [comment]
谢谢楼上了。

**Comment by streamgo** [comment]
@keyoushi 谢谢了。

**Comment by simonasd** [comment]
@xxnet 哈希校验一定要有，最好再加上签名。最近爆出一个神秘木马，就是劫持了一些缺乏校验机制的自动更新，实现无感入侵的目的。

**Comment by jzp820927** [comment]
神秘木马？对于 https 应该无效吧？

**Comment by Anway2** [comment]
Apk?where？

**Comment by jzp820927** [comment]
3.xx 版本还没有 APK

**Comment by simonasd** [comment]
@jzp820927  网络劫持只是一种形式。对Github上发布的哈希做一个签名，客户端用公钥进行签证，总是有备无患的。对这个研究不多，根据刚查的资料，现有的库应该就可以实现。

**Comment by yeahwu** [comment]
https加密的劫持也不容易

**Comment by streamgo** [comment]
明白的。只是墙肯定要越来越高。

2016-04-18 14:59 GMT+08:00 YeahWu <notifications@github.com>:
