### ISSUE TITLE
运行XX-Net出错

### ISSUE THREAD

**Issue by always-waiting** [XX-net/XX-Net#2973]
错误信息如下：
```
4月 19 16:34:35.5 - [ERROR] check_update fail:TypeError("'NoneType' object has no attribute '__getitem__'",)
4月 19 16:34:35.5 - [ERROR] Except stack:Traceback (most recent call last):
  File "/home/matthew/Documents/software/XX-Net-2.8.9/launcher/update.py", line 248, in check_update
    if LooseVersion(current_version) < LooseVersion(versions[1][1]):
TypeError: 'NoneType' object has no attribute '__getitem__'

```

 这个是少库吗？

**Comment by always-waiting** [comment]
这是日志文件
```
XX-Net Status：

sys-platform: x86_64, Linux-4.2.0-35-generic-x86_64-with-Ubuntu-14.04-trusty
os-system: Linux
os-version: #40~14.04.1-Ubuntu SMP Fri Mar 18 16:37:35 UTC 2016
os-release: 4.2.0-35-generic
os-detail: Dist:Ubuntu; Version:14.04; ID:trusty
architecture: 64bit,ELF
browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/49.0.2623.108 Chrome/49.0.2623.108 Safari/537.36
xxnet-version: 2.9.2
python-version: 2.7.6

ipv6-status: 0
gws-ip-num: 3000 / 8
network-status: OK
connected-link: 0 / 7
scan-ip-thread-num: 50
ip-quality: 757
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false
```

**Comment by always-waiting** [comment]
@yeahwu 
能解释一下部署appid的作用吗？
我重装了系统，下载了新的XX-Net，以前是2.8版本，现在用2.9版本了
我还需要重新部署appid吗？还是直接用原来版本里配置GAEProxy里面的appid就可以了？

**Comment by jzp820927** [comment]
不用部署了，直接用以前的就行了，证书，如果真的导入了，就试试能正常使用就行了

**Comment by yeahwu** [comment]
https://github.com/XX-net/XX-Net/wiki/%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95

**Comment by yeahwu** [comment]
首先说说运行报错，ubuntu需要装一些依赖文件，命令见下面
https://github.com/XX-net/XX-Net/wiki/%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95
再就是你问的appid，appid就是服务端，xx-net为客户端，这个能理解吧
证书问题，ubuntu应该是自动导入的，
手动导入不成功，那么你就先删除系统浏览器中原有的证书，再导入，证书名，goagent xx-net.crt

**Comment by always-waiting** [comment]
@yeahwu 
我已经安装了
https://github.com/XX-net/XX-Net/wiki/%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95
下Linux列出的依赖包，也重启过电脑了，还是有
```
 4月 20 10:51:00.4 - [ERROR] check_update fail:TypeError("'NoneType' object has no attribute '__getitem__'",)
 4月 20 10:51:00.4 - [ERROR] Except stack:Traceback (most recent call last):
  File "/home/matthew/Documents/software/XX-Net-2.9.6/launcher/update.py", line 248, in check_update
    if LooseVersion(current_version) < LooseVersion(versions[1][1]):
TypeError: 'NoneType' object has no attribute '__getitem__'
```
这个错误

**Comment by jzp820927** [comment]
这个是检查更新失败，应该不影响使用
