### ISSUE TITLE
Mac 平台支持

### ISSUE THREAD

**Issue by xxnet** [XX-net/XX-Net#3]
Mac下的适配

**Comment by tom1027** [comment]
错误如下
Traceback (most recent call last):
  File "/Path/XX-Net-1.0.6/XX-Net-1.0.6/launcher/1.0.0/start.py", line 67, in <module>
    main()
  File "/Path/XX-Net-1.0.6/XX-Net-1.0.6/launcher/1.0.0/start.py", line 53, in main
    sys_tray.serve_forever()
NameError: global name 'sys_tray' is not defined

**Comment by xxnet** [comment]
调试过了，可以试试。
