### ISSUE TITLE
ubuntu下运行错误（通过git clone xxnet最新源码）

### ISSUE THREAD

**Issue by yuan78** [XX-net/XX-Net#3019]
ubuntu下运行错误（通过git clone xxnet最新源码）,报错如下：

# ./xxnet
Python 2.7.10
XX-Net version:default
 4月 22 19:31:41.1 - [INFO] start XX-Net 3.0.4
 4月 22 19:31:41.1 - [DEBUG] start confirm_xxnet_exit
 4月 22 19:31:41.1 - [DEBUG] good, xxnet:8087 cleared!
 4月 22 19:31:41.1 - [DEBUG] good, xxnet:8085 clear!
 4月 22 19:31:41.1 - [DEBUG] finished confirm_xxnet_exit
 4月 22 19:31:41.1 - [ERROR] launcher except:OSError(2, '\xe6\xb2\xa1\xe6\x9c\x89\xe9\x82\xa3\xe4\xb8\xaa\xe6\x96\x87\xe4\xbb\xb6\xe6\x88\x96\xe7\x9b\xae\xe5\xbd\x95')
 4月 22 19:31:41.1 - [ERROR] Except stack:Traceback (most recent call last):
  File "code/default/launcher/start.py", line 143, in <module>
  File "code/default/launcher/start.py", line 115, in main
  File "/home/yuan/XX-Net/code/default/launcher/post_update.py", line 27, in run
    shutil.rmtree(os.path.join(top_path, 'launcher')) # launcher is for auto-update from 2.X
  File "/usr/lib/python2.7/shutil.py", line 239, in rmtree
    onerror(os.listdir, path, sys.exc_info())
  File "/usr/lib/python2.7/shutil.py", line 237, in rmtree
    names = os.listdir(path)
OSError: [Errno 2] 没有那个文件或目录: '/home/yuan/XX-Net/launcher'

Press any to exit...
(start.py:6245): libappindicator-WARNING **: Unable to get the session bus: 连接已关闭

(start.py:6245): LIBDBUSMENU-GLIB-WARNING **: Unable to get session bus: 连接已关闭
^C
Traceback (most recent call last):
  File "code/default/launcher/start.py", line 149, in <module>
    input('Press any to exit...')

Stopping all modules before exit!

**Comment by yuan78** [comment]
突然发现需要手动把launcher目录手动放到XX-Net目录下，才能解决问题。
这个bug能不能修复下

**Comment by yeahwu** [comment]
一直没弄明白xx-net目录下的这个launcher文件是干什么的？有用吗？
