### ISSUE TITLE
PHP Proxy 错误

### ISSUE THREAD

**Issue by yuningning520** [XX-net/XX-Net#3030]
Apr 23 09:28:34 - [INFO] ------------------------------------------------------
PHP Proxy Version : 3.2.3 (python/2.7.11 gevent/1.0.1 pyopenssl/0.13.1)
PHP Listen : 127.0.0.1:8088
PHP FetchServers : ['http://centrumfinansowa.pl/php/index.php']
------------------------------------------------------

Apr 23 09:28:34 - [DEBUG] init_ca
Apr 23 09:30:15 - [DEBUG] qname= reply_server='114.114.114.114' record null iplist=[]
Apr 23 09:30:17 - [DEBUG] qname= dnsserver='114.114.114.114' record iplist=[]
Apr 23 09:30:17 - [ERROR] create_http_request "POST http://centrumfinansowa.pl/php/index.php?0.598023582383" failed:exceptions must be old-style classes or derived from BaseException, not NoneType
Apr 23 09:30:17 - [ERROR] Except stack:Traceback (most recent call last):
File "D:\SW\PF\XX-Net\code\default\php_proxy\local\proxylib.py", line 1781, in create_http_request
sock = create_connection(host, port, timeout, validate=validate, cache_key=cache_key, headfirst=headfirst)
File "D:\SW\PF\XX-Net\code\default\php_proxy\local\proxylib.py", line 1505, in create_tcp_connection
raise sock
TypeError: exceptions must be old-style classes or derived from BaseException, not NoneType

Apr 23 09:30:17 - [ERROR] create_http_request "POST http://centrumfinansowa.pl/php/index.php?0.598023582383" failed:exceptions must be old-style classes or derived from BaseException, not NoneType
Apr 23 09:30:17 - [ERROR] Except stack:Traceback (most recent call last):
File "D:\SW\PF\XX-Net\code\default\php_proxy\local\proxylib.py", line 1781, in create_http_request
sock = create_connection(host, port, timeout, validate=validate, cache_key=cache_key, headfirst=headfirst)
File "D:\SW\PF\XX-Net\code\default\php_proxy\local\proxylib.py", line 1505, in create_tcp_connection
raise sock
TypeError: exceptions must be old-style classes or derived from BaseException, not NoneType

Apr 23 09:30:17 - [WARNING] GET "http://www.baidu.com/" failed TypeError('exceptions must be old-style classes or derived from BaseException, not NoneType',)
Apr 23 09:30:17 - [DEBUG] qname= dnsserver='8.8.8.8' record iplist=['107.180.44.223']

xx和服务器里都是3.0.4的

**Comment by jzp820927** [comment]
XX 的 PHP，好像不更新了，如果你要用 PHP，建议你用 goproxy ，效率和速度都比XX的PHP高很多

**Comment by yuningning520** [comment]
好的，谢谢
