### ISSUE TITLE
部署失败

### ISSUE THREAD

**Issue by zzgpku** [XX-net/XX-Net#3054]
2016-04-25 18:23:10,234 - root - INFO - enable debug logging
2016-04-25 18:23:10,234 - root - INFO - set proxy to http://127.0.0.1:8087
2016-04-25 18:23:10,282 - root - INFO - ============ Begin upload ============
2016-04-25 18:23:10,282 - root - INFO - appid:（####）
2016-04-25 18:23:10,375 - root - INFO - Send: /api/appversion/rollback, params={'version': '1', 'app_id': '（####）'}
2016-04-25 18:23:10,375 - google.appengine.tools.appengine_rpc - DEBUG - _Authenticate skipped auth; needs_auth=False
2016-04-25 18:23:10,375 - google.appengine.tools.appengine_rpc - DEBUG - Sending request to https://appengine.google.com/api/appversion/rollback?app_id=zzgldr&force_rollback=0&version=1 headers={'X-appcfg-api-version': '1', 'content-length': '0', 'Content-Type': 'application/octet-stream'} body=
2016-04-25 18:23:53,562 - root - ERROR - upload fail:error(10060, '')
Traceback (most recent call last):
File "E:\XX-Net-master\code\default\gae_proxy\server\uploader.py", line 70, in upload
result = appcfg.AppCfgApp(['appcfg', 'rollback', dirname ]).Run()
File "E:\XX-Net-master\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 2951, in Run
self.action(self)
File "E:\XX-Net-master\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 5044, in __call__
return method()
File "E:\XX-Net-master\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 4397, in Rollback
self._Rollback()
File "E:\XX-Net-master\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 4442, in _Rollback
appversion.Rollback(force_rollback)
File "E:\XX-Net-master\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 2362, in Rollback
force_rollback='1' if force_rollback else '0')
File "E:\XX-Net-master\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 1696, in Send
result = self.rpcserver.Send(url, payload=payload, **kwargs)
File "E:\XX-Net-master\code\default\gae_proxy\server\lib\google\appengine\tools\appengine_rpc_httplib2.py", line 247, in Send
url, method=method, body=payload, headers=headers)
File "E:\XX-Net-master\code\default\gae_proxy\server\lib\httplib2__init__.py", line 1593, in request
(response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
File "E:\XX-Net-master\code\default\gae_proxy\server\lib\httplib2__init__.py", line 1341, in _request
(response, content) = self._conn_request(conn, request_uri, method, body, headers)
File "E:\XX-Net-master\code\default\gae_proxy\server\lib\httplib2__init__.py", line 1315, in _conn_request
conn.connect()
File "E:\XX-Net-master\code\default\gae_proxy\server\lib\httplib2__init__.py", line 1062, in connect
raise socket.error, msg
error: [Errno 10060]

**Comment by zzgpku** [comment]
下载的3.0.4版本，windows 10 64位系统。

**Comment by aiyh** [comment]
建议升级新版本直接解压覆盖前面版本的，系统内置升级功能容易出错

**Comment by zzgpku** [comment]
原来用的是2.9.2版本，和3.0.4版本软件目录下的文件夹都不一样，怎么覆盖？

**Comment by jzp820927** [comment]
或者你可以试试用 2.9.7 部署

**Comment by zzgpku** [comment]
已覆盖，但部署还是失败

**Comment by jzp820927** [comment]
那就只有等X大来看看了
