### ISSUE TITLE
重试部署很多次都失败

### ISSUE THREAD

**Issue by liangruiben** [XX-net/XX-Net#3072]
2016-04-27 02:22:30,226 - root - INFO - set proxy to http://127.0.0.1:8087
2016-04-27 02:22:30,226 - root - INFO - ============ Begin upload ============
2016-04-27 02:22:30,226 - root - INFO - appid:pxmmlxwmmzavnfck
2016-04-27 02:22:30,256 - root - INFO - Send: /api/appversion/rollback, params={'version': '1', 'app_id': 'pxmmlxwmmzavnfck'}
2016-04-27 02:22:35,687 - oauth2client.client - INFO - Successfully retrieved access token
2016-04-27 02:22:36,201 - root - INFO - Send: /api/appversion/rollback, params={'version': '1', 'app_id': 'pxmmlxwmmzavnfck'}
2016-04-27 02:22:36,684 - root - INFO - Send: /api/appversion/rollback, params={'version': '1', 'app_id': 'pxmmlxwmmzavnfck'}
2016-04-27 02:22:37,098 - root - INFO - =======================
2016-04-27 02:22:37,098 - root - INFO - Deploy failed appid list:
2016-04-27 02:22:37,098 - root - INFO - - pxmmlxwmmzavnfck
2016-04-27 02:22:37,098 - root - INFO - == END ==

**Comment by jzp820927** [comment]
用 2.9.7 部署

**Comment by liangruiben** [comment]
试过了,也不行,换最新的3.x也一样

**Comment by jzp820927** [comment]
授权有没有成功

**Comment by liangruiben** [comment]
有弹出授权界面,提示也是完成授权
用最新版有一个提示404的

**Comment by jzp820927** [comment]
如果授权成功了，应该就没问题了，你在 appengine.google.com 看看 appid 的状态呢

**Comment by liangruiben** [comment]
GOOGLE.COM提示The authentication flow has completed.

LOG显示

2016-04-30 21:13:17,733 - root - INFO - enable debug logging
2016-04-30 21:13:17,734 - root - INFO - set proxy to http://127.0.0.1:8087
2016-04-30 21:13:17,739 - root - INFO - ============ Begin upload ============
2016-04-30 21:13:17,740 - root - INFO - appid:ixbcqtaxonsthrzh
2016-04-30 21:13:17,767 - root - INFO - Send: /api/appversion/rollback, params={'version': '1', 'app_id': 'ixbcqtaxonsthrzh'}
2016-04-30 21:13:17,767 - google.appengine.tools.appengine_rpc - DEBUG - _Authenticate skipped auth; needs_auth=False
2016-04-30 21:13:17,769 - google.appengine.tools.appengine_rpc - DEBUG - Sending request to https://appengine.google.com/api/appversion/rollback?app_id=ixbcqtaxonsthrzh&force_rollback=0&version=1 headers={'X-appcfg-api-version': '1', 'content-length': '0', 'Content-Type': 'application/octet-stream'} body=
2016-04-30 21:13:21,664 - google.appengine.tools.appengine_rpc - DEBUG - Got http error 401.
2016-04-30 21:13:21,664 - google.appengine.tools.appengine_rpc - DEBUG - Attempting to auth. This is try 1 of 3.
2016-04-30 21:13:21,664 - google.appengine.tools.appengine_rpc - DEBUG - _Authenticate requesting auth
2016-04-30 21:13:28,007 - oauth2client.client - INFO - Successfully retrieved access token
2016-04-30 21:13:28,010 - google.appengine.tools.appengine_rpc - DEBUG - _Authenticate configuring auth; needs_auth=True
2016-04-30 21:13:28,012 - google.appengine.tools.appengine_rpc - DEBUG - Sending request to https://appengine.google.com/api/appversion/rollback?app_id=ixbcqtaxonsthrzh&force_rollback=0&version=1 headers={'X-appcfg-api-version': '1', 'content-length': '0', 'Content-Type': 'application/octet-stream'} body=
2016-04-30 21:13:28,618 - google.appengine.tools.appengine_rpc - DEBUG - Got http error 404.
2016-04-30 21:13:28,618 - google.appengine.tools.appengine_rpc - DEBUG - Unexpected results: {'status': '404', 'content-length': '61', 'expires': 'Mon, 01 Jan 1990 00:00:00 GMT', '-content-encoding': 'gzip', 'content-type': 'text/plain'}
2016-04-30 21:13:28,648 - root - INFO - Send: /api/appversion/rollback, params={'version': '1', 'app_id': 'ixbcqtaxonsthrzh'}
2016-04-30 21:13:28,650 - google.appengine.tools.appengine_rpc - DEBUG - _Authenticate configuring auth; needs_auth=False
2016-04-30 21:13:28,650 - google.appengine.tools.appengine_rpc - DEBUG - Sending request to https://appengine.google.com/api/appversion/rollback?app_id=ixbcqtaxonsthrzh&force_rollback=0&version=1 headers={'X-appcfg-api-version': '1', 'content-length': '0', 'Content-Type': 'application/octet-stream'} body=
2016-04-30 21:13:29,321 - google.appengine.tools.appengine_rpc - DEBUG - Got http error 404.
2016-04-30 21:13:29,321 - google.appengine.tools.appengine_rpc - DEBUG - Unexpected results: {'status': '404', 'content-length': '61', 'expires': 'Mon, 01 Jan 1990 00:00:00 GMT', '-content-encoding': 'gzip', 'content-type': 'text/plain'}
2016-04-30 21:13:29,345 - root - INFO - Send: /api/appversion/rollback, params={'version': '1', 'app_id': 'ixbcqtaxonsthrzh'}
2016-04-30 21:13:29,345 - google.appengine.tools.appengine_rpc - DEBUG - _Authenticate configuring auth; needs_auth=False
2016-04-30 21:13:29,346 - google.appengine.tools.appengine_rpc - DEBUG - Sending request to https://appengine.google.com/api/appversion/rollback?app_id=ixbcqtaxonsthrzh&force_rollback=0&version=1 headers={'X-appcfg-api-version': '1', 'content-length': '0', 'Content-Type': 'application/octet-stream'} body=
2016-04-30 21:13:29,869 - google.appengine.tools.appengine_rpc - DEBUG - Got http error 404.
2016-04-30 21:13:29,869 - google.appengine.tools.appengine_rpc - DEBUG - Unexpected results: {'status': '404', 'content-length': '61', 'expires': 'Mon, 01 Jan 1990 00:00:00 GMT', '-content-encoding': 'gzip', 'content-type': 'text/plain'}
2016-04-30 21:13:29,871 - root - INFO - =======================
2016-04-30 21:13:29,871 - root - INFO - Deploy failed appid list:
2016-04-30 21:13:29,872 - root - INFO - - ixbcqtaxonsthrzh
2016-04-30 21:13:29,872 - root - INFO - == END ==

**Comment by jzp820927** [comment]
看不出什么大明显的错误，等 X 老大来看吧

**Comment by xxnet** [comment]
​这个问题是因为很多google  ip已经不支持direct模式。
而配置还有direct模式。


手动处理可以这样：打开data/gae_proxy/config.ini
 把direct 都改成 gae

**Comment by liangruiben** [comment]
没有看到有CONFIG.ini 我用最新的3.x版

**Comment by jzp820927** [comment]
要在 web 界面配置过，才会有 config。ini 文件吧

**Comment by liangruiben** [comment]
配置过了,没有出现

**Comment by jzp820927** [comment]
那就干脆全部删了，重新下载

**Comment by hyndaniel** [comment]
不知道你的问题和我一样不，我是刚刚解决的，也是自己太马虎
//项目名称 
test
您的项目 ID： sonic-airfoil-130010  修改
显示高级选项…//
部署的ID是自动生成的，不是你起的名字
可以在https://appengine.google.com/  里找到

**Comment by liangruiben** [comment]
找到INI了,改了还是这样

2016-05-05 01:46:17,581 - root - INFO - enable debug logging
2016-05-05 01:46:17,582 - root - INFO - set proxy to http://127.0.0.1:8087
2016-05-05 01:46:17,588 - root - INFO - ============ Begin upload ============
2016-05-05 01:46:17,589 - root - INFO - appid:fukvnsnolgnaspvr
2016-05-05 01:46:17,621 - root - INFO - Send: /api/appversion/rollback, params={'version': '1', 'app_id': 'fukvnsnolgnaspvr'}
2016-05-05 01:46:17,621 - google.appengine.tools.appengine_rpc - DEBUG - _Authenticate skipped auth; needs_auth=False
2016-05-05 01:46:17,622 - google.appengine.tools.appengine_rpc - DEBUG - Sending request to https://appengine.google.com/api/appversion/rollback?app_id=fukvnsnolgnaspvr&force_rollback=0&version=1 headers={'X-appcfg-api-version': '1', 'content-length': '0', 'Content-Type': 'application/octet-stream'} body=
2016-05-05 01:46:18,759 - google.appengine.tools.appengine_rpc - DEBUG - Got http error 401.
2016-05-05 01:46:18,759 - google.appengine.tools.appengine_rpc - DEBUG - Attempting to auth. This is try 1 of 3.
2016-05-05 01:46:18,760 - google.appengine.tools.appengine_rpc - DEBUG - _Authenticate requesting auth
2016-05-05 01:46:26,167 - oauth2client.client - INFO - Successfully retrieved access token
2016-05-05 01:46:26,174 - google.appengine.tools.appengine_rpc - DEBUG - _Authenticate configuring auth; needs_auth=True
2016-05-05 01:46:26,174 - google.appengine.tools.appengine_rpc - DEBUG - Sending request to https://appengine.google.com/api/appversion/rollback?app_id=fukvnsnolgnaspvr&force_rollback=0&version=1 headers={'X-appcfg-api-version': '1', 'content-length': '0', 'Content-Type': 'application/octet-stream'} body=
2016-05-05 01:46:26,563 - google.appengine.tools.appengine_rpc - DEBUG - Got http error 404.
2016-05-05 01:46:26,565 - google.appengine.tools.appengine_rpc - DEBUG - Unexpected results: {'status': '404', 'content-length': '61', 'expires': 'Mon, 01 Jan 1990 00:00:00 GMT', '-content-encoding': 'gzip', 'content-type': 'text/plain'}
2016-05-05 01:46:26,596 - root - INFO - Send: /api/appversion/rollback, params={'version': '1', 'app_id': 'fukvnsnolgnaspvr'}
2016-05-05 01:46:26,598 - google.appengine.tools.appengine_rpc - DEBUG - _Authenticate configuring auth; needs_auth=False
2016-05-05 01:46:26,598 - google.appengine.tools.appengine_rpc - DEBUG - Sending request to https://appengine.google.com/api/appversion/rollback?app_id=fukvnsnolgnaspvr&force_rollback=0&version=1 headers={'X-appcfg-api-version': '1', 'content-length': '0', 'Content-Type': 'application/octet-stream'} body=
2016-05-05 01:46:26,930 - google.appengine.tools.appengine_rpc - DEBUG - Got http error 404.
2016-05-05 01:46:26,930 - google.appengine.tools.appengine_rpc - DEBUG - Unexpected results: {'status': '404', 'content-length': '61', 'expires': 'Mon, 01 Jan 1990 00:00:00 GMT', '-content-encoding': 'gzip', 'content-type': 'text/plain'}
2016-05-05 01:46:26,960 - root - INFO - Send: /api/appversion/rollback, params={'version': '1', 'app_id': 'fukvnsnolgnaspvr'}
2016-05-05 01:46:26,960 - google.appengine.tools.appengine_rpc - DEBUG - _Authenticate configuring auth; needs_auth=False
2016-05-05 01:46:26,960 - google.appengine.tools.appengine_rpc - DEBUG - Sending request to https://appengine.google.com/api/appversion/rollback?app_id=fukvnsnolgnaspvr&force_rollback=0&version=1 headers={'X-appcfg-api-version': '1', 'content-length': '0', 'Content-Type': 'application/octet-stream'} body=
2016-05-05 01:46:27,302 - google.appengine.tools.appengine_rpc - DEBUG - Got http error 404.
2016-05-05 01:46:27,303 - google.appengine.tools.appengine_rpc - DEBUG - Unexpected results: {'status': '404', 'content-length': '61', 'expires': 'Mon, 01 Jan 1990 00:00:00 GMT', '-content-encoding': 'gzip', 'content-type': 'text/plain'}
2016-05-05 01:46:27,309 - root - INFO - =======================
2016-05-05 01:46:27,309 - root - INFO - Deploy failed appid list:
2016-05-05 01:46:27,309 - root - INFO - - fukvnsnolgnaspvr
2016-05-05 01:46:27,311 - root - INFO - == END ==

**Comment by liangruiben** [comment]
我理解错了,我以为是复制生成的一次性密码.....原来是项目名称...

**Comment by xxnet** [comment]
1. 用最新的3.1.5版本

2. 删除data/gae_proxy/config.ini

3. 再次部署，如果还有问题，把GAE_proxy的日志贴出来和部署部署日志，都贴出来

**Comment by jasonjacky** [comment]
我用目前最新的稳定版本xxnet部署多次失败, 使用推荐的Deploy_XXNET使用ssr也不行, 哎 蛋疼...
2018-01-15 23:05:56,148 - root - INFO - enable debug logging
2018-01-15 23:05:56,148 - root - INFO - set proxy to http://127.0.0.1:8087
2018-01-15 23:05:56,154 - root - INFO - ============ Begin upload ============
2018-01-15 23:05:56,154 - root - INFO - appid:201801132147
2018-01-15 23:05:56,177 - root - INFO - Send: /api/appversion/rollback, params={'version': '1', 'app_id': '201801132147'}
2018-01-15 23:05:56,177 - google.appengine.tools.appengine_rpc - DEBUG - _Authenticate skipped auth; needs_auth=False
2018-01-15 23:05:56,177 - google.appengine.tools.appengine_rpc - DEBUG - Sending request to https://appengine.google.com/api/appversion/rollback?app_id=201801132147&force_rollback=0&version=1 headers={'X-appcfg-api-version': '1', 'content-length': '0', 'Content-Type': 'application/octet-stream'} body=
2018-01-15 23:05:57,114 - google.appengine.tools.appengine_rpc - DEBUG - Got http error 401.
2018-01-15 23:05:57,114 - google.appengine.tools.appengine_rpc - DEBUG - Attempting to auth. This is try 1 of 3.
2018-01-15 23:05:57,114 - google.appengine.tools.appengine_rpc - DEBUG - _Authenticate requesting auth
2018-01-15 23:07:21,148 - oauth2client.client - INFO - Successfully retrieved access token
2018-01-15 23:07:21,151 - google.appengine.tools.appengine_rpc - DEBUG - _Authenticate configuring auth; needs_auth=True
2018-01-15 23:07:21,151 - google.appengine.tools.appengine_rpc - DEBUG - Sending request to https://appengine.google.com/api/appversion/rollback?app_id=201801132147&force_rollback=0&version=1 headers={'X-appcfg-api-version': '1', 'content-length': '0', 'Content-Type': 'application/octet-stream'} body=
2018-01-15 23:07:22,447 - google.appengine.tools.appengine_rpc - DEBUG - Got http error 404.
2018-01-15 23:07:22,447 - google.appengine.tools.appengine_rpc - DEBUG - Unexpected results: {'status': '404', 'content-length': '155', '-content-encoding': 'gzip', 'x-cloud-trace-context': 'deb8aaf8155d9376771436b16e01fbcf;o=1', 'content-type': 'text/plain'}
2018-01-15 23:07:22,469 - root - INFO - Send: /api/appversion/rollback, params={'version': '1', 'app_id': '201801132147'}
2018-01-15 23:07:22,470 - google.appengine.tools.appengine_rpc - DEBUG - _Authenticate configuring auth; needs_auth=False
2018-01-15 23:07:22,470 - google.appengine.tools.appengine_rpc - DEBUG - Sending request to https://appengine.google.com/api/appversion/rollback?app_id=201801132147&force_rollback=0&version=1 headers={'X-appcfg-api-version': '1', 'content-length': '0', 'Content-Type': 'application/octet-stream'} body=
2018-01-15 23:07:22,993 - google.appengine.tools.appengine_rpc - DEBUG - Got http error 404.
2018-01-15 23:07:22,993 - google.appengine.tools.appengine_rpc - DEBUG - Unexpected results: {'status': '404', 'content-length': '155', '-content-encoding': 'gzip', 'x-cloud-trace-context': '862e04fea1720c400321186599324eb1', 'content-type': 'text/plain'}
2018-01-15 23:07:23,012 - root - INFO - Send: /api/appversion/rollback, params={'version': '1', 'app_id': '201801132147'}
2018-01-15 23:07:23,012 - google.appengine.tools.appengine_rpc - DEBUG - _Authenticate configuring auth; needs_auth=False
2018-01-15 23:07:23,012 - google.appengine.tools.appengine_rpc - DEBUG - Sending request to https://appengine.google.com/api/appversion/rollback?app_id=201801132147&force_rollback=0&version=1 headers={'X-appcfg-api-version': '1', 'content-length': '0', 'Content-Type': 'application/octet-stream'} body=
2018-01-15 23:07:24,549 - google.appengine.tools.appengine_rpc - DEBUG - Got http error 404.
2018-01-15 23:07:24,549 - google.appengine.tools.appengine_rpc - DEBUG - Unexpected results: {'status': '404', 'content-length': '155', '-content-encoding': 'gzip', 'x-cloud-trace-context': '2a005a5904b40e07f2adb2710787ec72', 'content-type': 'text/plain'}
2018-01-15 23:07:24,551 - root - INFO - ============ Begin upload ============
2018-01-15 23:07:24,552 - root - INFO - appid:201801132309
2018-01-15 23:07:24,573 - root - INFO - Send: /api/appversion/rollback, params={'version': '1', 'app_id': '201801132309'}
2018-01-15 23:07:24,575 - google.appengine.tools.appengine_rpc - DEBUG - _Authenticate configuring auth; needs_auth=False
2018-01-15 23:07:24,575 - google.appengine.tools.appengine_rpc - DEBUG - Sending request to https://appengine.google.com/api/appversion/rollback?app_id=201801132309&force_rollback=0&version=1 headers={'X-appcfg-api-version': '1', 'content-length': '0', 'Content-Type': 'application/octet-stream'} body=
2018-01-15 23:07:25,785 - google.appengine.tools.appengine_rpc - DEBUG - Got http error 404.
2018-01-15 23:07:25,785 - google.appengine.tools.appengine_rpc - DEBUG - Unexpected results: {'status': '404', 'content-length': '155', '-content-encoding': 'gzip', 'x-cloud-trace-context': '6751782313b80e128f60f627272b8c28', 'content-type': 'text/plain'}
2018-01-15 23:07:25,805 - root - INFO - Send: /api/appversion/rollback, params={'version': '1', 'app_id': '201801132309'}
2018-01-15 23:07:25,805 - google.appengine.tools.appengine_rpc - DEBUG - _Authenticate configuring auth; needs_auth=False
2018-01-15 23:07:25,805 - google.appengine.tools.appengine_rpc - DEBUG - Sending request to https://appengine.google.com/api/appversion/rollback?app_id=201801132309&force_rollback=0&version=1 headers={'X-appcfg-api-version': '1', 'content-length': '0', 'Content-Type': 'application/octet-stream'} body=
2018-01-15 23:07:36,392 - google.appengine.tools.appengine_rpc - DEBUG - Got http error 404.
2018-01-15 23:07:36,394 - google.appengine.tools.appengine_rpc - DEBUG - Unexpected results: {'status': '404', 'content-length': '155', '-content-encoding': 'gzip', 'x-cloud-trace-context': '51cd6528bee0ff10e6fe992335639fd6', 'content-type': 'text/plain'}
2018-01-15 23:07:36,411 - root - INFO - Send: /api/appversion/rollback, params={'version': '1', 'app_id': '201801132309'}
2018-01-15 23:07:36,411 - google.appengine.tools.appengine_rpc - DEBUG - _Authenticate configuring auth; needs_auth=False
2018-01-15 23:07:36,411 - google.appengine.tools.appengine_rpc - DEBUG - Sending request to https://appengine.google.com/api/appversion/rollback?app_id=201801132309&force_rollback=0&version=1 headers={'X-appcfg-api-version': '1', 'content-length': '0', 'Content-Type': 'application/octet-stream'} body=
2018-01-15 23:07:37,779 - google.appengine.tools.appengine_rpc - DEBUG - Got http error 404.
2018-01-15 23:07:37,780 - google.appengine.tools.appengine_rpc - DEBUG - Unexpected results: {'status': '404', 'content-length': '155', '-content-encoding': 'gzip', 'x-cloud-trace-context': '4b7344a9142260e0bcdc9ac420a0b75b;o=1', 'content-type': 'text/plain'}
2018-01-15 23:07:37,782 - root - INFO - =======================
2018-01-15 23:07:37,782 - root - INFO - Deploy failed appid list:
2018-01-15 23:07:37,782 - root - INFO - - 201801132147
2018-01-15 23:07:37,783 - root - INFO - - 201801132309
2018-01-15 23:07:37,783 - root - INFO - == END ==


Deploy_XXNET的log
===============================================================
 XXNET 服务端部署程序, 开始上传 gae 应用文件夹
 Linux/Mac 用户, 请使用 python uploader.py 来上传应用
===============================================================

请输入您的appid, 多个appid请用|号隔开
注意：appid 请勿包含 ios/android/mobile 等字样，否则可能被某些网站识别成移动设备
。
APPID:201801132147|201801132309
11:03 PM Application: 201801132147
11:03 PM Host: appengine.google.com
11:03 PM Rolling back the update.
Traceback (most recent call last):
  File "python27.py", line 95, in <module>
  File "C:\Users\ycp\Desktop\Deploy_XXNET_Server-master\uploader.py", line 141,
in <module>
    main()
  File "C:\Users\ycp\Desktop\Deploy_XXNET_Server-master\uploader.py", line 127,
in main
    upload('gae', appid)
  File "C:\Users\ycp\Desktop\Deploy_XXNET_Server-master\uploader.py", line 111,
in upload
    appcfg.main(['appcfg', 'rollback', dirname])
  File "C:\Users\ycp\Desktop\Deploy_XXNET_Server-master\google_appengine\google\
appengine\tools\appcfg.py", line 5388, in main
    result = AppCfgApp(argv).Run()
  File "C:\Users\ycp\Desktop\Deploy_XXNET_Server-master\google_appengine\google\
appengine\tools\appcfg.py", line 2951, in Run
    self.action(self)
  File "C:\Users\ycp\Desktop\Deploy_XXNET_Server-master\google_appengine\google\
appengine\tools\appcfg.py", line 5044, in __call__
    return method()
  File "C:\Users\ycp\Desktop\Deploy_XXNET_Server-master\google_appengine\google\
appengine\tools\appcfg.py", line 4397, in Rollback
    self._Rollback()
  File "C:\Users\ycp\Desktop\Deploy_XXNET_Server-master\google_appengine\google\
appengine\tools\appcfg.py", line 4442, in _Rollback
    appversion.Rollback(force_rollback)
  File "C:\Users\ycp\Desktop\Deploy_XXNET_Server-master\google_appengine\google\
appengine\tools\appcfg.py", line 2362, in Rollback
    force_rollback='1' if force_rollback else '0')
  File "C:\Users\ycp\Desktop\Deploy_XXNET_Server-master\google_appengine\google\
appengine\tools\appcfg.py", line 1696, in Send
    result = self.rpcserver.Send(url, payload=payload, **kwargs)
  File "google_appengine\google\appengine\tools\appengine_rpc_httplib2.py", line
 247, in Send
    url, method=method, body=payload, headers=headers)
  File "google_appengine\httplib2\__init__.py", line 1584, in request
    (response, content) = self._request(conn, authority, uri, request_uri, metho
d, body, headers, redirections, cachekey)
  File "google_appengine\httplib2\__init__.py", line 1332, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, he
aders)
  File "google_appengine\httplib2\__init__.py", line 1268, in _conn_request
    conn.connect()
  File "google_appengine\httplib2\__init__.py", line 1011, in connect
    sock.connect((self.host, self.port))
  File "PySocks\socks.py", line 740, in connect
    raise ProxyConnectionError(msg, error)
socks.ProxyConnectionError: Error connecting to SOCKS5 proxy 127.0.0.1:1080: [Er
rno 10060]
请按任意键继续. . .
