### ISSUE TITLE
启动不了

### ISSUE THREAD

**Issue by geyang2014** [XX-net/XX-Net#3075]
D:\软件备份\XX-Net-master>SET PYTHONPATH=

D:\软件备份\XX-Net-master>"D:\软件备份\XX-Net-master\python27/1.0/python.exe" "D:\软件备份\XX-Net-master\launcher/start.py"
Apr 27 11:24:04.604 - [INFO] start XX-Net get_version_fail
Apr 27 11:24:04.605 - [DEBUG] start confirm_xxnet_exit
Apr 27 11:24:04.608 - [DEBUG] good, xxnet:8087 cleared!
Apr 27 11:24:04.610 - [DEBUG] good, xxnet:8085 clear!
Apr 27 11:24:04.611 - [DEBUG] finished confirm_xxnet_exit
Apr 27 11:24:05.885 - [WARNING] network fail:gaierror(11001, 'getaddrinfo failed')
Apr 27 11:24:05.909 - [INFO] SSL use version:TLSv1
Apr 27 11:24:06.486 - [INFO] load ip range file:D:\软件备份\XX-Net-master\data\gae_proxy\ip_range.txt
Apr 27 11:24:06.586 - [INFO] detected Win10, enable connect concurrency control, interval:200
Apr 27 11:24:06.676 - [INFO] load google ip_list num:3000, gws num:3000
Apr 27 11:24:06.811 - [DEBUG] ## GAEProxy set keep_running: True
Apr 27 11:24:06.813 - [INFO] ------------------------------------------------------
Apr 27 11:24:06.816 - [INFO] Python Version     : 2.7.11
Apr 27 11:24:06.817 - [INFO] OS                 : Version:10-0; Build:10586; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
Apr 27 11:24:06.820 - [INFO] Listen Address     : 127.0.0.1:8087
Apr 27 11:24:06.822 - [INFO] GAE APPID          : geyangapp
Apr 27 11:24:06.824 - [INFO] Pac Server         : http://127.0.0.1:8086/proxy.pac
Apr 27 11:24:06.826 - [INFO] ------------------------------------------------------
Exception in thread Thread-54:
Traceback (most recent call last):
  File "D:\软件备份\XX-Net-master\python27\1.0\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "D:\软件备份\XX-Net-master\python27\1.0\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "D:\软件备份\XX-Net-master\gae_proxy\start.py", line 19, in main
    client.main()
  File "D:\软件备份\XX-Net-master\gae_proxy\local\proxy.py", line 236, in main
    proxy_daemon = simple_http_server.HTTPServer((config.LISTEN_IP, config.LISTEN_PORT), proxy_handler.GAEProxyHandler)
  File "D:\软件备份\XX-Net-master\python27\1.0\lib\noarch\simple_http_server.py", line 259, in __init__
    self.init_socket()
  File "D:\软件备份\XX-Net-master\python27\1.0\lib\noarch\simple_http_server.py", line 264, in init_socket
    self.add_listen(addr)
  File "D:\软件备份\XX-Net-master\python27\1.0\lib\noarch\simple_http_server.py", line 267, in add_listen
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
  File "D:\软件备份\XX-Net-master\python27\1.0\lib\socket.py", line 191, in __init__
    _sock = _realsocket(family, type, proto)
error: [Errno 10106]

**Comment by yeahwu** [comment]
重新下载安装一下，关掉迅雷，360等

**Comment by lijipeng787** [comment]
同样的问题，请问该如何解决

**Comment by jzp820927** [comment]
奇葩问题，路径尽量别带中文

**Comment by lijipeng787** [comment]
@jzp820927  同样的问题，非中文路径，电脑一个月没有用，再用的时候就出现这种问题了

**Comment by jzp820927** [comment]
那就不大清楚了，等X大来看看吧

**Comment by xxnet** [comment]
确实很奇怪。
从日志看，是在请求socket对象时失败，以前没有遇到过。
可以停掉杀毒/安全软件试试。

另一个怀疑的，端口被占用了？看看系统8087端口有没有被占用了

**Comment by linhua55** [comment]
用这个命令可查看8087端口是否被占用：
    netstat -an |findstr LISTEN|findstr 8087
