### ISSUE TITLE
最新版有时会为响应

### ISSUE THREAD

**Issue by yechao25038** [XX-net/XX-Net#3128]
刚下载最新版本的。扫描ip会为响应，浏览网页一会也会为响应。这是日志。
Apr 30 23:29:55.710 - [ERROR] ssl send:Error([('SSL routines', 'ssl3_write_bytes', 'ssl handshake failure')],)
Apr 30 23:29:55.711 - [ERROR] Except stack:Traceback (most recent call last): File "D:\Software\XX-Net-master\code\default\gae_proxy\local\openssl_wrap.py", line 95, in __send return self.__iowait(self._connection.send, data, flags) File "D:\Software\XX-Net-master\code\default\gae_proxy\local\openssl_wrap.py", line 80, in __iowait raise e Error: [('SSL routines', 'ssl3_write_bytes', 'ssl handshake failure')]

**Comment by yechao25038** [comment]
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36
xxnet-version: 3.0.4

python-version: 2.7.11
openssl-version: 0.15.1 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:56 good:51
network-status: OK
connected-link: new:0 used:0
worker: h1:0 h2:32
scan-ip-thread-num: 500
ip-quality: 315
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by jzp820927** [comment]
是不是你扫描线程开的太高了，调低试试

**Comment by yechao25038** [comment]
好的，最近ip太少 我就提高扫描线程了。我去试试
