### ISSUE TITLE
IP数量为零

### ISSUE THREAD

**Issue by alfredyuan123** [XX-net/XX-Net#3130]
最近两天开始IP数量一直为零。报错为“You may want to  turn on IP scaner”，事实上我是将“自动调整扫描线程数”打开了的。不知大家是否遇到过这个问题？

**Comment by jzp820927** [comment]
什么版本？

**Comment by alfredyuan123** [comment]
前两天的是2.8.9，刚升级后变成了	3.0.4，不过仍然不行

**Comment by alfredyuan123** [comment]
日志如下：

May 01 01:58:11.415 - [INFO] SSL use version:TLSv1_2
May 01 01:58:12.553 - [INFO] OpenSSL support alpn
May 01 01:58:12.556 - [INFO] load ip range file:F:\\\\XX-net\XX-Net-2.8.9\data\gae_proxy\ip_range.txt
May 01 01:58:12.589 - [WARNING] line err:
May 01 01:58:13.566 - [DEBUG] network is ok, cost:2537 ms
May 01 01:58:18.408 - [INFO] load google ip_list num:0, gws num:0
May 01 01:58:18.412 - [INFO] OpenSSL support alpn
May 01 01:58:18.420 - [ERROR] data/gae_proxy/manual.ini load error:File contains no section headers. file: , line: 1 "\xef\xbb\xbf; Don't Edit the file manual\r\n"
May 01 01:58:18.420 - [ERROR] Except stack:Traceback (most recent call last): File "F:\\\\XX-net\XX-Net-2.8.9\code\default\gae_proxy\local\config.py", line 44, in load self.CONFIG.readfp(io.BytesIO(content)) File "F:\\\\XX-net\XX-Net-2.8.9\code\default\python27\1.0\lib\ConfigParser.py", line 324, in readfp self._read(fp, filename) File "F:\\\\XX-net\XX-Net-2.8.9\code\default\python27\1.0\lib\ConfigParser.py", line 512, in _read raise MissingSectionHeaderError(fpname, lineno, line) MissingSectionHeaderError: File contains no section headers. file: , line: 1 "\xef\xbb\xbf; Don't Edit the file manual\r\n"
May 01 01:58:18.421 - [DEBUG] ## GAEProxy set keep_running: True
May 01 01:58:18.421 - [INFO] ------------------------------------------------------
May 01 01:58:18.421 - [INFO] Python Version : 2.7.11
May 01 01:58:18.422 - [INFO] OS : Version:6-3; Build:9600; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
May 01 01:58:18.422 - [INFO] Listen Address : 127.0.0.1:8087
May 01 01:58:18.422 - [INFO] GAE APPID : alfredyuan123double|alfredyuan123triple|alfredyuan123quadruple|alfredyuan123quintuple|alfredyuan123sextuple|alfredyuan123septuple
May 01 01:58:18.422 - [INFO] Pac Server : http://127.0.0.1:8086/proxy.pac
May 01 01:58:18.422 - [INFO] ------------------------------------------------------
May 01 01:58:19.735 - [INFO] GAE CONNECT xxnet-update.appspot.com:443
May 01 01:58:19.749 - [DEBUG] GAE CONNECT GET https://xxnet-update.appspot.com/update.json?uuid=8624cf65-1f27-40ef-b697-df41bac83fc1&version=3.0.4&platform=Windows-8.1-6.3.9600
May 01 01:58:21.118 - [INFO] GAE CONNECT xxnet-update.appspot.com:443
May 01 01:58:21.134 - [DEBUG] GAE CONNECT GET https://xxnet-update.appspot.com/update.json?uuid=8624cf65-1f27-40ef-b697-df41bac83fc1&version=3.0.4&platform=Windows-8.1-6.3.9600
May 01 01:58:35.132 - [DEBUG] GAEProxy web_control 127.0.0.1:6354 POST /config?cmd=get_config
May 01 01:58:35.134 - [DEBUG] GAEProxy Web_control 127.0.0.1:6355 GET /scan_ip?cmd=get_range
May 01 01:58:35.134 - [INFO] load ip range file:F:\\\\XX-net\XX-Net-2.8.9\data\gae_proxy\ip_range.txt
May 01 01:58:38.763 - [DEBUG] GAEProxy Web_control 127.0.0.1:6354 GET /deploy?cmd=get_log
May 01 01:58:38.991 - [DEBUG] GAEProxy web_control 127.0.0.1:6354 POST /config?cmd=get_config
May 01 01:59:18.416 - [WARNING] no enough ip
May 01 01:59:18.916 - [WARNING] no enough ip
May 01 01:59:19.418 - [WARNING] no enough ip
May 01 01:59:19.750 - [DEBUG] create ssl timeout fail.
May 01 01:59:19.750 - [DEBUG] create ssl timeout fail.
May 01 01:59:19.750 - [DEBUG] GAE_Exception 1 'no ssl_sock'
May 01 01:59:19.752 - [WARNING] get worker fail:GAE_Exception()
May 01 01:59:19.753 - [DEBUG] response_fail:get worker fail:GAE_Exception()
May 01 01:59:19.754 - [WARNING] fetch gae status:506 url:https://xxnet-update.appspot.com/update.json?uuid=8624cf65-1f27-40ef-b697-df41bac83fc1&version=3.0.4&platform=Windows-8.1-6.3.9600
May 01 01:59:19.755 - [WARNING] GAE GET https://xxnet-update.appspot.com/update.json?uuid=8624cf65-1f27-40ef-b697-df41bac83fc1&version=3.0.4&platform=Windows-8.1-6.3.9600 request fail
May 01 01:59:19.919 - [WARNING] no enough ip
May 01 01:59:20.419 - [WARNING] no enough ip
May 01 01:59:20.921 - [WARNING] no enough ip
May 01 01:59:21.423 - [WARNING] no enough ip
May 01 01:59:21.923 - [WARNING] no enough ip

**Comment by panzer1313208** [comment]
IP段全被封了。唉。

**Comment by keyoushi** [comment]
因为XX.NET的IP段是公开的，所以3000个内置IP基本会被封死。建议大家还是根据自己的网络状况自行配制manual.ini文件，尽量扫更多的IP，才有可能流畅使用。

**Comment by xxnet** [comment]
​你把
data/gae_proxy/manual.ini
删掉，里面格式错了

**Comment by alfredyuan123** [comment]
请问你说的把manual.ini删掉是指把这个文件直接删除吗？我试了一下，好像还是不行啊@xxnet

**Comment by alfredyuan123** [comment]
@keyoushi 请问你说的自行配制manual.ini是配置里面的哪项啊？是否有相关教程啊？谢谢~

**Comment by alfredyuan123** [comment]
已经解决了，谢谢大家~  我把原来的程序全部uninstall,然后再重装xx-net，就弄好了~

**Comment by panzer1313208** [comment]
@keyoushi 要我说。弄个主机放IP段。然后xxnet全部从那个主机里获取IP段。

**Comment by panzer1313208** [comment]
IP能扫。IP段怎么扫？GFW封的是IP段。IP段被封了那IP就全都不能用了
