### ISSUE TITLE
openwrt 运行xx-Net报错，请作者看看原因？

### ISSUE THREAD

**Issue by jlzsss** [XX-net/XX-Net#3159]
报错信息如下：
May 02 20:58:00.896 - [DEBUG] get ip:190.113.97.236 t:955
May 02 20:58:00.906 - [DEBUG] create_ssl update ip:66.96.226.215 time:913 h2:0
May 02 20:58:01.082 - [ERROR] start module x_tunnel fail:dynamic module does not define init function (init_ctypes)
May 02 20:58:01.099 - [ERROR] Except stack:Traceback (most recent call last):
  File "/mnt/sda1/XX-Net/code/default/launcher/module_init.py", line 37, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "/mnt/sda1/XX-Net/code/default/x_tunnel/start.py", line 14, in <module>
    import local.client as client
  File "/mnt/sda1/XX-Net/code/default/x_tunnel/local/client.py", line 40, in <module>
    import proxy_session
  File "/mnt/sda1/XX-Net/code/default/x_tunnel/local/proxy_session.py", line 13, in <module>
    import encrypt
  File "/mnt/sda1/XX-Net/code/default/python27/1.0/lib/noarch/encrypt.py", line 32, in <module>
    from scrypto import m2, rc4_md5, salsa20_ctr, ctypes_openssl, table
  File "/mnt/sda1/XX-Net/code/default/python27/1.0/lib/noarch/scrypto/ctypes_openssl.py", line 27, in <module>
    from ctypes import CDLL, c_char_p, c_int, c_long, byref,\
  File "/mnt/sda1/optware/usr/lib/python2.7/ctypes/__init__.py", line 10, in <module>
    from _ctypes import Union, Structure, Array
ImportError: dynamic module does not define init function (init_ctypes)

May 02 20:58:01.101 - [ERROR] launcher except:ImportError('dynamic module does not define init function (init_ctypes)',)
May 02 20:58:01.108 - [ERROR] Except stack:Traceback (most recent call last):
  File "/mnt/sda1/XX-Net/code/default/launcher/start.py", line 153, in <module>
    main()
  File "/mnt/sda1/XX-Net/code/default/launcher/start.py", line 130, in main
    module_init.start_all_auto()
  File "/mnt/sda1/XX-Net/code/default/launcher/module_init.py", line 98, in start_all_auto
    start(module)
  File "/mnt/sda1/XX-Net/code/default/launcher/module_init.py", line 37, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "/mnt/sda1/XX-Net/code/default/x_tunnel/start.py", line 14, in <module>
    import local.client as client
  File "/mnt/sda1/XX-Net/code/default/x_tunnel/local/client.py", line 40, in <module>
    import proxy_session
  File "/mnt/sda1/XX-Net/code/default/x_tunnel/local/proxy_session.py", line 13, in <module>
    import encrypt
  File "/mnt/sda1/XX-Net/code/default/python27/1.0/lib/noarch/encrypt.py", line 32, in <module>
    from scrypto import m2, rc4_md5, salsa20_ctr, ctypes_openssl, table
  File "/mnt/sda1/XX-Net/code/default/python27/1.0/lib/noarch/scrypto/ctypes_openssl.py", line 27, in <module>
    from ctypes import CDLL, c_char_p, c_int, c_long, byref,\
  File "/mnt/sda1/optware/usr/lib/python2.7/ctypes/__init__.py", line 10, in <module>
    from _ctypes import Union, Structure, Array
ImportError: dynamic module does not define init function (init_ctypes)

**Comment by xxnet** [comment]
​先把x_tunnel模块关掉
