### ISSUE TITLE
Mac 下使用google.com失败，但google.com.hk可以

### ISSUE THREAD

**Issue by causlayer** [XX-net/XX-Net#3174]
XX-Net Status:

sys-platform: x86_64, Darwin-15.4.0-x86_64-i386-64bit
os-system: Darwin
os-version: Darwin Kernel Version 15.4.0: Fri Feb 26 22:08:05 PST 2016; root:xnu-3248.40.184~3/RELEASE_X86_64
os-release: 15.4.0
os-detail: Release:10.11.4; Version:('', '', '') Machine:x86_64
architecture: 64bit,
browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36
xxnet-version: 3.1.2

python-version: 2.7.10
openssl-version: 0.13.1 TLSv1 h2:no

ipv6-status: 0
gws-ip-num: total:2606 good:117
network-status: OK
connected-link: new:0 used:0
worker: h1:25 h2:0
scan-ip-thread-num: 50
ip-quality: 483
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

错误代码：
File "/Applications/XX-Net/code/default/gae_proxy/local/connect_manager.py", line 116, in get_nowait return self.get(block=False, only_h1=only_h1) File "/Applications/XX-Net/code/default/gae_proxy/local/connect_manager.py", line 110, in get item = self._get(only_h1=only_h1) File "/Applications/XX-Net/code/default/gae_proxy/local/connect_manager.py", line 131, in _get raise Exception("get no ssl") Exception: get no ssl
May 03 12:56:13.671 - [ERROR] direct_handler.handler Exception('get no ssl',) www.google.com /favicon.ico , retry...
May 03 12:56:13.671 - [ERROR] Except stack:Traceback (most recent call last): File "/Applications/XX-Net/code/default/gae_proxy/local/direct_handler.py", line 95, in handler response = fetch(method, host, url, headers, body) File "/Applications/XX-Net/code/default/gae_proxy/local/direct_handler.py", line 50, in fetch ssl_sock = https_manager.get_ssl_connection(host) File "/Applications/XX-Net/code/default/gae_proxy/local/connect_manager.py", line 509, in get_ssl_connection ret = self.host_conn_pool[host].get_nowait(only_h1=True) File "/Applications/XX-Net/code/default/gae_proxy/local/connect_manager.py", line 116, in get_nowait return self.get(block=False, only_h1=only_h1) File "/Applications/XX-Net/code/default/gae_proxy/local/connect_manager.py", line 110, in get item = self._get(only_h1=only_h1) File "/Applications/XX-Net/code/default/gae_proxy/local/connect_manager.py", line 131, in _get raise Exception("get no ssl") Exception: get no ssl

**Comment by xxnet** [comment]
​问题已经定位到了，在master分支上，待大家测试稳定了发新版

https://github.com/XX-net/XX-Net/archive/master.zip

**Comment by causlayer** [comment]
已经pull了最新的，另外问下mac开机启动的问题看下呗。

**Comment by xxnet** [comment]
​Mac不熟，等其他人看看
