### ISSUE TITLE
看youtube时偶尔会报错

### ISSUE THREAD

**Issue by 94oiio** [XX-net/XX-Net#3186]
May 03 19:03:26.195 - [DEBUG] create_ssl update ip:118.98.36.15 time:634 h2:0
May 03 19:03:26.328 - [DEBUG] 203.117.34.166 fail:timeout('timed out',)
May 03 19:03:26.328 - [DEBUG] report_connect_fail:203.117.34.166
May 03 19:03:26.493 - [DEBUG] create_ssl update ip:190.240.2.110 time:651 h2:0
May 03 19:03:26 - [DEBUG]LOG_EXCEPT: create_ssl update ip:62.119.230.179 time:641 h2:0, Except:[Errno 9] Bad file descriptor
May 03 19:03:26.804 - [ERROR] 27.80.250.235 head appid:gx1994101310 request fail:SysCallError(10054, 'WSAECONNRESET')
May 03 19:03:26.806 - [ERROR] Except stack:Traceback (most recent call last): File "D:\Tools\XX-Net\code\default\gae_proxy\local\http1.py", line 154, in head_request response.begin() File "D:\Tools\XX-Net\code\default\python27\1.0\lib\httplib.py", line 453, in begin version, status, reason = self._read_status() File "D:\Tools\XX-Net\code\default\python27\1.0\lib\httplib.py", line 409, in _read_status line = self.fp.readline(_MAXLINE + 1) File "D:\Tools\XX-Net\code\default\python27\1.0\lib\socket.py", line 480, in readline data = self._sock.recv(self._rbufsize) File "D:\Tools\XX-Net\code\default\gae_proxy\local\openssl_wrap.py", line 118, in recv return self.__iowait(self._connection.recv, bufsiz, flags) File "D:\Tools\XX-Net\code\default\gae_proxy\local\openssl_wrap.py", line 80, in __iowait raise e SysCallError: (10054, 'WSAECONNRESET')
May 03 19:03:26.806 - [DEBUG] report_connect_fail:27.80.250.235
May 03 19:03:27.167 - [INFO] GAE CONNECT r16---sn-vgqsen7r.googlevideo.com:443
May 03 19:03:27.172 - [ERROR] 61.238.239.13 head appid:gx1994101310 request fail:SysCallError(10054, 'WSAECONNRESET')
May 03 19:03:27.173 - [ERROR] Except stack:Traceback (most recent call last): File "D:\Tools\XX-Net\code\default\gae_proxy\local\http1.py", line 154, in head_request response.begin() File "D:\Tools\XX-Net\code\default\python27\1.0\lib\httplib.py", line 453, in begin version, status, reason = self._read_status() File "D:\Tools\XX-Net\code\default\python27\1.0\lib\httplib.py", line 409, in _read_status line = self.fp.readline(_MAXLINE + 1) File "D:\Tools\XX-Net\code\default\python27\1.0\lib\socket.py", line 480, in readline data = self._sock.recv(self._rbufsize) File "D:\Tools\XX-Net\code\default\gae_proxy\local\openssl_wrap.py", line 118, in recv return self.__iowait(self._connection.recv, bufsiz, flags) File "D:\Tools\XX-Net\code\default\gae_proxy\local\openssl_wrap.py", line 80, in __iowait raise e SysCallError: (10054, 'WSAECONNRESET')
May 03 19:03:27.173 - [DEBUG] report_connect_fail:61.238.239.13
May 03 19:03:27.181 - [DEBUG] GAE CONNECT GET https://r16---sn-vgqsen7r.googlevideo.com/videoplayback?signature=17BFB145FC6C4DB521F23FE80977B516718E1BD3.79E711577A3CE864FD63C0C685601B0D6E5CE7D4&upn=FZ5XmH6ftR4&id=o-AIox4f42jYNDplVOv2mNAVAHncBECFNOvWhy97QX0RNj&keepalive=yes&clen=182655906&ip=107.178.194.110&sparams=clen,dur,expire,gir,id,initcwndbps,ip,ipbits,ipbypass,itag,keepalive,lmt,mime,mm,mn,ms,mv,pl,requiressl,source,upn&fexp=3300014%2C3300113%2C3300133%2C3300164%2C3312381%2C9412777%2C9416126%2C9416891%2C9417893%2C9422545%2C9422596%2C9426985%2C9428398%2C9431012%2C9431309%2C9432683%2C9433096%2C9433508%2C9433644%2C9433946%2C9434087%2C9434290%2C9434767%2C9435580%2C9435685&pl=27&dur=1958.890&source=youtube&requiressl=yes&gir=yes&mime=video%2Fwebm&key=cms1&expire=1462294842&lmt=1462191113289955&sver=3&ipbits=0&itag=247&cpn=pklkUxS1wp7DODAD&alr=yes&ratebypass=yes&c=WEB&cver=1.20160428&redirect_counter=1&req_id=386f2622340c43e9&cms_redirect=yes&ipbypass=yes&mm=31&mn=sn-vgqsen7r&ms=au&mt=1462273074&mv=m&range=26116283-27873426&rn=166&rbuf=104904
May 03 19:03:28.301 - [DEBUG] 207.181.192.145 fail:timeout('timed out',)
May 03 19:03:28.301 - [DEBUG] report_connect_fail:207.181.192.145
May 03 19:03:29.610 - [DEBUG] 40.133.6.23 fail:timeout('timed out',)
May 03 19:03:29.610 - [DEBUG] report_connect_fail:40.133.6.23
May 03 19:03:30 - [INFO]LOG_EXCEPT: >>>>>>>>>>>>>>> RangeFetch started('https://r16---sn-vgqsen7r.googlevideo.com/videoplayback?signature=17BFB145FC6C4DB521F23FE80977B516718E1BD3.79E711577A3CE864FD63C0C685601B0D6E5CE7D4&upn=FZ5XmH6ftR4&id=o-AIox4f42jYNDplVOv2mNAVAHncBECFNOvWhy97QX0RNj&keepalive=yes&clen=182655906&ip=107.178.194.110&sparams=clen,dur,expire,gir,id,initcwndbps,ip,ipbits,ipbypass,itag,keepalive,lmt,mime,mm,mn,ms,mv,pl,requiressl,source,upn&fexp=3300014%2C3300113%2C3300133%2C3300164%2C3312381%2C9412777%2C9416126%2C9416891%2C9417893%2C9422545%2C9422596%2C9426985%2C9428398%2C9431012%2C9431309%2C9432683%2C9433096%2C9433508%2C9433644%2C9433946%2C9434087%2C9434290%2C9434767%2C9435580%2C9435685&pl=27&dur=1958.890&source=youtube&requiressl=yes&gir=yes&mime=video%2Fwebm&key=cms1&expire=1462294842&lmt=1462191113289955&sver=3&ipbits=0&itag=247&cpn=pklkUxS1wp7DODAD&alr=yes&ratebypass=yes&c=WEB&cver=1.20160428&redirect_counter=1&req_id=386f2622340c43e9&cms_redirect=yes&ipbypass=yes&mm=31&mn=sn-vgqsen7r&ms=au&mt=1462273074&mv=m&range=26116283-27873426&rn=166&rbuf=104904') 0-1048575, Except:[Errno 9] Bad file descriptor
May 03 19:03:30.538 - [INFO] >>>>>>>>>>>>>>> [thread 5900] 1048576 bytes 0-1048575/1757144
May 03 19:03:30.540 - [INFO] >>>>>>>>>>>>>>> Successfully reached 1048575 bytes.

**Comment by 94oiio** [comment]
May 03 19:01:12.519 - [INFO] GAE CONNECT r16---sn-vgqsen7r.googlevideo.com:443
May 03 19:01:12.533 - [DEBUG] GAE CONNECT GET https://r16---sn-vgqsen7r.googlevideo.com/videoplayback?signature=17BFB145FC6C4DB521F23FE80977B516718E1BD3.79E711577A3CE864FD63C0C685601B0D6E5CE7D4&upn=FZ5XmH6ftR4&id=o-AIox4f42jYNDplVOv2mNAVAHncBECFNOvWhy97QX0RNj&keepalive=yes&clen=182655906&ip=107.178.194.110&sparams=clen,dur,expire,gir,id,initcwndbps,ip,ipbits,ipbypass,itag,keepalive,lmt,mime,mm,mn,ms,mv,pl,requiressl,source,upn&fexp=3300014%2C3300113%2C3300133%2C3300164%2C3312381%2C9412777%2C9416126%2C9416891%2C9417893%2C9422545%2C9422596%2C9426985%2C9428398%2C9431012%2C9431309%2C9432683%2C9433096%2C9433508%2C9433644%2C9433946%2C9434087%2C9434290%2C9434767%2C9435580%2C9435685&pl=27&dur=1958.890&source=youtube&requiressl=yes&gir=yes&mime=video%2Fwebm&key=cms1&expire=1462294842&lmt=1462191113289955&sver=3&ipbits=0&itag=247&cpn=pklkUxS1wp7DODAD&alr=yes&ratebypass=yes&c=WEB&cver=1.20160428&redirect_counter=1&req_id=386f2622340c43e9&cms_redirect=yes&ipbypass=yes&mm=31&mn=sn-vgqsen7r&ms=au&mt=1462273074&mv=m&range=3354603-4376967&rn=133&rbuf=10341
May 03 19:01:12.786 - [INFO] GAE t:351 s:5721 GET https://www.youtube.com/api/timedtext?v=l-5vD5YVLv8&key=yttt1&signature=E44B460406AFB6F84C0BAB4C724E97939388BE23.3574159B4F0E7E659A265640CEEEA48E3D474823&expire=1462298442&caps=asr&asr_langs=ja%2Ces%2Cko%2Cit%2Cde%2Cnl%2Cpt%2Cru%2Cfr%2Cen&hl=zh_CN&sparams=asr_langs%2Ccaps%2Cv%2Cexpire&kind=asr&lang=en&fmt=srv1
May 03 19:01:12.820 - [WARNING] server app return fail, status:502
May 03 19:01:12.820 - [ERROR] gae_handler.handler TypeError('not a valid non-string sequence or mapping object',) https://r1---sn-vgqs7nlz.googlevideo.com/videoplayback?signature=402D6E9A6A9B538C2896E16E6E27086CACDBDF86.4D294A12902771F84609227865F6A82EA2EBD37C&upn=FZ5XmH6ftR4&id=o-AIox4f42jYNDplVOv2mNAVAHncBECFNOvWhy97QX0RNj&keepalive=yes&clen=25891908&ip=107.178.194.118&sparams=clen,dur,expire,gir,id,initcwndbps,ip,ipbits,ipbypass,itag,keepalive,lmt,mime,mm,mn,ms,mv,pl,requiressl,source,upn&fexp=3300014%2C3300113%2C3300133%2C3300164%2C3312381%2C9412777%2C9416126%2C9416891%2C9417893%2C9422545%2C9422596%2C9426985%2C9428398%2C9431012%2C9431309%2C9432683%2C9433096%2C9433508%2C9433644%2C9433946%2C9434087%2C9434290%2C9434767%2C9435580%2C9435685&pl=27&dur=1958.921&source=youtube&requiressl=yes&gir=yes&mime=audio%2Fwebm&key=cms1&expire=1462294842&lmt=1462188328196788&sver=3&ipbits=0&itag=251&cpn=pklkUxS1wp7DODAD&alr=yes&ratebypass=yes&c=WEB&cver=1.20160428&redirect_counter=1&req_id=8a2ff91b8ce74649&cms_redirect=yes&ipbypass=yes&mm=31&mn=sn-vgqs7nlz&ms=au&mt=1462273074&mv=m&range=131072-213364&rn=122&rbuf=5307 , retry...
May 03 19:01:12.820 - [ERROR] Except stack:Traceback (most recent call last): File "D:\Tools\XX-Net\code\default\gae_proxy\local\gae_handler.py", line 333, in request_gae_proxy xlog.warn('app_msg:undefined', urllib.urlencode(response.app_msg)) File "D:\Tools\XX-Net\code\default\python27\1.0\lib\urllib.py", line 1333, in urlencode raise TypeError TypeError: not a valid non-string sequence or mapping object
May 03 19:01:13 - [INFO]LOG_EXCEPT: GAE t:31774 s:82293 GET https://r1---sn-vgqs7nlz.googlevideo.com/videoplayback?signature=402D6E9A6A9B538C2896E16E6E27086CACDBDF86.4D294A12902771F84609227865F6A82EA2EBD37C&upn=FZ5XmH6ftR4&id=o-AIox4f42jYNDplVOv2mNAVAHncBECFNOvWhy97QX0RNj&keepalive=yes&clen=25891908&ip=107.178.194.118&sparams=clen,dur,expire,gir,id,initcwndbps,ip,ipbits,ipbypass,itag,keepalive,lmt,mime,mm,mn,ms,mv,pl,requiressl,source,upn&fexp=3300014%2C3300113%2C3300133%2C3300164%2C3312381%2C9412777%2C9416126%2C9416891%2C9417893%2C9422545%2C9422596%2C9426985%2C9428398%2C9431012%2C9431309%2C9432683%2C9433096%2C9433508%2C9433644%2C9433946%2C9434087%2C9434290%2C9434767%2C9435580%2C9435685&pl=27&dur=1958.921&source=youtube&requiressl=yes&gir=yes&mime=audio%2Fwebm&key=cms1&expire=1462294842&lmt=1462188328196788&sver=3&ipbits=0&itag=251&cpn=pklkUxS1wp7DODAD&alr=yes&ratebypass=yes&c=WEB&cver=1.20160428&redirect_counter=1&req_id=8a2ff91b8ce74649&cms_redirect=yes&ipbypass=yes&mm=31&mn=sn-vgqs7nlz&ms=au&mt=1462273074&mv=m&range=131072-213364&rn=122&rbuf=5307, Except:[Errno 9] Bad file descriptor

**Comment by xxnet** [comment]
​这个异常没有捕获，下次补上
