### ISSUE TITLE
ArchLinux上启动不了

### ISSUE THREAD

**Issue by linhua55** [XX-net/XX-Net#3218]
git最新版 https://github.com/XX-net/XX-Net/commit/6d9f6eb825d3cdfa209955f1094f212f832935d7
已安装 python2-pyopenssl 和python-pyopenssl
    ➜  XX-Net git:(work) ./start
    XX-Net version:default
    Install python-openssl and libnss3-tools for your system
    which: no apt-get in (/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl)
    which: no dnf in (/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl)
    which: no yum in (/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl)
    May 05 00:52:08.234 - [WARNING] import pynotify fail, please install python-notify if possiable.
    May 05 00:52:08.752 - [INFO] import build-in openssl fail:VerificationError("importing '/home/lh/Documents/Github/XX-Net/code/default/python27/1.0/lib/linux/cryptography/_Cryptography_cffi_f3e4673fx399b1113.so': /home/lh/Documents/Github/XX-Net/code/default/python27/1.0/lib/linux/cryptography/_Cryptography_cffi_f3e4673fx399b1113.so: symbol SSLv3_method, version OPENSSL_1.0.0 not defined in file libssl.so.1.0.0 with link time reference",)
    May 05 00:52:08.753 - [ERROR] import system python-OpenSSL fail:VerificationError("importing '/home/lh/Documents/Github/XX-Net/code/default/python27/1.0/lib/linux/cryptography/_Cryptography_cffi_f3e4673fx399b1113.so': /home/lh/Documents/Github/XX-Net/code/default/python27/1.0/lib/linux/cryptography/_Cryptography_cffi_f3e4673fx399b1113.so: symbol SSLv3_method, version OPENSSL_1.0.0 not defined in file libssl.so.1.0.0 with link time reference",)
    May 05 00:52:08.753 - [ERROR] Except stack:Traceback (most recent call last):
      File "code/default/launcher/start.py", line 94, in <module>
        import OpenSSL
      File "/usr/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
        from OpenSSL import rand, crypto, SSL
      File "/usr/lib/python2.7/site-packages/OpenSSL/rand.py", line 12, in <module>
        from OpenSSL._util import (
      File "/usr/lib/python2.7/site-packages/OpenSSL/_util.py", line 9, in <module>
        binding = Binding()
      File "/home/lh/Documents/Github/XX-Net/code/default/python27/1.0/lib/linux/cryptography/hazmat/bindings/openssl/binding.py", line 114, in __init__
        self._ensure_ffi_initialized()
      File "/home/lh/Documents/Github/XX-Net/code/default/python27/1.0/lib/linux/cryptography/hazmat/bindings/openssl/binding.py", line 126, in _ensure_ffi_initialized
        cls._modules,
      File "/home/lh/Documents/Github/XX-Net/code/default/python27/1.0/lib/linux/cryptography/hazmat/bindings/utils.py", line 31, in load_library_for_binding
        lib = ffi.verifier.load_library()
      File "/home/lh/Documents/Github/XX-Net/code/default/python27/1.0/lib/linux/cffi/verifier.py", line 111, in load_library
        return self._load_library()
      File "/home/lh/Documents/Github/XX-Net/code/default/python27/1.0/lib/linux/cffi/verifier.py", line 222, in _load_library
        return self._vengine.load_library()
      File "/home/lh/Documents/Github/XX-Net/code/default/python27/1.0/lib/linux/cffi/vengine_cpy.py", line 155, in load_library
        raise ffiplatform.VerificationError(error)
    VerificationError: importing '/home/lh/Documents/Github/XX-Net/code/default/python27/1.0/lib/linux/cryptography/_Cryptography_cffi_f3e4673fx399b1113.so': /home/lh/Documents/Github/XX-Net/code/default/python27/1.0/lib/linux/cryptography/_Cryptography_cffi_f3e4673fx399b1113.so: symbol SSLv3_method, version OPENSSL_1.0.0 not defined in file libssl.so.1.0.0 with link time reference
    
    Try install python-openssl
    
    Press Enter to continue...

**Comment by yyssxx** [comment]
3.1.5，ubuntu16.04 同样的问题

**Comment by xxnet** [comment]
​先试试把
/home/lh/Documents/Github/XX-Net/code/default/python27/1.0/lib/linux/cryptography/




*  删除或移走按代码逻辑，应该是去使用系统的cryptography 库，而不是内置的库。现在需要定位问题出在哪里*

**Comment by yyssxx** [comment]
删除了cryptography，正常启动，问题解决。

**Comment by Hilshire** [comment]
3.2.8，archlinux，同样的问题。把目录删了也没用。最后是手动安装python2-pyopenssl解决的。

**Comment by jzp820927** [comment]
解决了就好
