### ISSUE TITLE
自动升级失败

### ISSUE THREAD

**Issue by zwkno1** [XX-net/XX-Net#3224]
运行一次关掉就成这样了，下载的是3.1.4好像他会自动升级到3.1.5,升级完就启动不了了

XX-Net version:3.1.5
Install python-openssl and libnss3-tools for your system
which: no apt-get in (/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl)
which: no dnf in (/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl)
which: no yum in (/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl)
May 05 14:03:51.058 - [INFO] import build-in openssl fail:VerificationError("importing '/home/zwk/bin/XX-Net-3.1.4/code/3.1.5/python27/1.0/lib/linux/cryptography/_Cryptography_cffi_f3e4673fx399b1113.so': /home/zwk/bin/XX-Net-3.1.4/code/3.1.5/python27/1.0/lib/linux/cryptography/_Cryptography_cffi_f3e4673fx399b1113.so: symbol SSLv3_method, version OPENSSL_1.0.0 not defined in file libssl.so.1.0.0 with link time reference",)
May 05 14:03:51.059 - [ERROR] import system python-OpenSSL fail:VerificationError("importing '/home/zwk/bin/XX-Net-3.1.4/code/3.1.5/python27/1.0/lib/linux/cryptography/_Cryptography_cffi_f3e4673fx399b1113.so': /home/zwk/bin/XX-Net-3.1.4/code/3.1.5/python27/1.0/lib/linux/cryptography/_Cryptography_cffi_f3e4673fx399b1113.so: symbol SSLv3_method, version OPENSSL_1.0.0 not defined in file libssl.so.1.0.0 with link time reference",)
May 05 14:03:51.059 - [ERROR] Except stack:Traceback (most recent call last):
  File "code/3.1.5/launcher/start.py", line 94, in <module>
    import OpenSSL
  File "/usr/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/lib/python2.7/site-packages/OpenSSL/rand.py", line 12, in <module>
    from OpenSSL._util import (
  File "/usr/lib/python2.7/site-packages/OpenSSL/_util.py", line 9, in <module>
    binding = Binding()
  File "/home/zwk/bin/XX-Net-3.1.4/code/3.1.5/python27/1.0/lib/linux/cryptography/hazmat/bindings/openssl/binding.py", line 114, in __init__
    self._ensure_ffi_initialized()
  File "/home/zwk/bin/XX-Net-3.1.4/code/3.1.5/python27/1.0/lib/linux/cryptography/hazmat/bindings/openssl/binding.py", line 126, in _ensure_ffi_initialized
    cls._modules,
  File "/home/zwk/bin/XX-Net-3.1.4/code/3.1.5/python27/1.0/lib/linux/cryptography/hazmat/bindings/utils.py", line 31, in load_library_for_binding
    lib = ffi.verifier.load_library()
  File "/home/zwk/bin/XX-Net-3.1.4/code/3.1.5/python27/1.0/lib/linux/cffi/verifier.py", line 111, in load_library
    return self._load_library()
  File "/home/zwk/bin/XX-Net-3.1.4/code/3.1.5/python27/1.0/lib/linux/cffi/verifier.py", line 222, in _load_library
    return self._vengine.load_library()
  File "/home/zwk/bin/XX-Net-3.1.4/code/3.1.5/python27/1.0/lib/linux/cffi/vengine_cpy.py", line 155, in load_library
    raise ffiplatform.VerificationError(error)
VerificationError: importing '/home/zwk/bin/XX-Net-3.1.4/code/3.1.5/python27/1.0/lib/linux/cryptography/_Cryptography_cffi_f3e4673fx399b1113.so': /home/zwk/bin/XX-Net-3.1.4/code/3.1.5/python27/1.0/lib/linux/cryptography/_Cryptography_cffi_f3e4673fx399b1113.so: symbol SSLv3_method, version OPENSSL_1.0.0 not defined in file libssl.so.1.0.0 with link time reference

Try install python-openssl

Press Enter to continue...

extra/python-pyopenssl 16.0.0-1 [已安装]
extra/python2-pyopenssl 16.0.0-1 [已安装]

**Comment by xxnet** [comment]
​先执行
rm -rf

*/home/zwk/bin/XX-Net-3.1.4/code/3.1.5/python27/1.0/lib/linux/cryptography/把这个库删了吧，我也把自动升级挺了再说*

**Comment by zwkno1** [comment]
不支持arch。。。
加个pacman呗

**Comment by zjhzxhz** [comment]
@zwkno1 
我好像加了pacman了吧?
你看`start`脚本~ 启动的时候会安装依赖项呀.

有什么异常吗?

**Comment by zwkno1** [comment]
看日志他应该是没发现系统的pyopenssl，使用了 build-in openssl

**Comment by xxnet** [comment]
​这个问题刚提交代码了，master上你测试下

**Comment by zwkno1** [comment]
行了，现在不会升级到3.1.5了
