### ISSUE TITLE
3.1.4和3.1.5开启一段时间之后，就用不了，但没有崩溃

### ISSUE THREAD

**Issue by sanan2015** [XX-net/XX-Net#3227]
3.1.4和3.1.5开启一段时间之后，就用不了，显示代理有问题，但软件没有崩溃
管理页面打不开，加载不出页面，启动管理页面的时候与平常不同，调用的是ie
换回2.9.4正常使用

**Comment by sanan2015** [comment]
补充一下，刚开启的时候是正常且速度很快，但过一段时间就出现问题

**Comment by jzp820927** [comment]
看看日志吧

**Comment by sanan2015** [comment]
管理页面都进不了，取不到日志

**Comment by zjhzxhz** [comment]
@sanan2015 
感觉是在抛异常~
试着用Debug模式启动看看.

如果你在用Windows, 就启动start.bat
如果用Linux, 用Shell启动start脚本

然后看在控制台的输出.

**Comment by sfqfirst** [comment]
3.1.3遇到相同的问题。启一段时间之后，就用不了

XX-Net Status:

sys-platform: x86, Windows-XP-5.1.2600-SP3
os-system: Windows
os-version: 5.1.2600
os-release: XP
os-detail: Version:5-1; Build:2600; Platform:2; CSD:Service Pack 3; ServicePack:3-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 5.1; rv:45.0) Gecko/20100101 Firefox/45.0
xxnet-version: 3.1.3

python-version: 2.7.11
openssl-version: 0.15.1 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:6552 good:5314
network-status: OK
connected-link: new:0 used:0
worker: h1:25 h2:2
scan-ip-thread-num: 1
ip-quality: 187
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by xxnet** [comment]
​怀疑还是cryptography库有问题。

试试start.bat 启动，看看卡住时，日志显示什么

**Comment by sfqfirst** [comment]
换3.1.4，遇到相同的问题。启一段时间之后，卡住
May 05 17:51:28.643 - [INFO] GAE t:359 s:0 POST https://www.google.com.hk/gen_204?atyp=i&ct=slh&cad=&ei=RxYrV_C1Jcf-ugTD
nI7oDA&s=11&v=2&pv=0.47601482179015875&me=104:1462441879505,V,0,0,0,0:5992,U,5992:0,V,0,0,1920,965:198,H,66,i:18,H,66,o:
6,H,60,i:16,H,60,o:1,H,53,i:9,H,53,o:1758,H,66,i:144,H,66,o:594,e,B&zx=1462441888241
May 05 17:51:29.059 - [DEBUG] ip:111.86.247.94 real fail
May 05 17:51:32.039 - [DEBUG] ssl_closed 210.139.253.94
May 05 17:51:32.044 - [DEBUG] ssl_closed 202.224.62.118
May 05 17:51:33.050 - [DEBUG] ssl_closed 210.139.253.109
May 05 17:51:34.060 - [DEBUG] ip:118.98.106.187 real fail
May 05 17:51:39.062 - [DEBUG] ip:118.98.106.157 real fail
May 05 17:51:39.951 - [DEBUG] restore ip:118.98.106.148
May 05 17:51:43.197 - [INFO] GAE CONNECT www.google.com:443
May 05 17:51:43.198 - [INFO] GAE CONNECT www.google.com:443
Exception in thread Thread-47:
Traceback (most recent call last):
  File "D:\Downloads\翻墙\XX-Net-master\code\default\python27\1.0\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "D:\Downloads\翻墙\XX-Net-master\code\default\python27\1.0\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "D:\Downloads\翻墙\XX-Net-master\code\default\python27\1.0\lib\noarch\simple_http_server.py", line 308, in serve_
forever
    self.process_connect(sock, address)
  File "D:\Downloads\翻墙\XX-Net-master\code\default\python27\1.0\lib\noarch\simple_http_server.py", line 314, in proces
s_connect
    client_thread.start()
  File "D:\Downloads\翻墙\XX-Net-master\code\default\python27\1.0\lib\threading.py", line 736, in start
    _start_new_thread(self.__bootstrap, ())
error: can't start new thread

May 05 17:51:43.607 - [DEBUG] create ssl timeout fail.
May 05 17:51:43.608 - [WARNING] check_update fail:HTTPError()
May 05 17:51:43.609 - [INFO] download https://raw.githubusercontent.com/XX-net/XX-Net/master/code/default/update_version
.txt to D:\Downloads\翻墙\XX-Net-master\data\downloads\version.txt, retry:0
May 05 17:52:38.503 - [DEBUG] launcher web_control 127.0.0.1:47954 GET /config?cmd=get_config
May 05 17:52:40.154 - [INFO] scan_ip add ip:86.127.118.148 time:782

**Comment by sfqfirst** [comment]
3.1.3，访问youtube首页，用2分钟后卡住
May 05 17:57:58.012 - [DEBUG] restore ip:118.98.106.153
DEBUG:root:buffer socket flush:24
INFO:hyper.http20.connection:Sending frame SettingsFrame on stream 0
DEBUG:root:buffer socket flush:15
INFO:hyper.http20.connection:Received frame SettingsFrame on stream 0
INFO:hyper.http20.connection:Sending frame SettingsFrame on stream 0
DEBUG:root:buffer socket flush:9
INFO:hyper.http20.connection:Received frame WindowUpdateFrame on stream 0
DEBUG:hyper.packages.hpack.hpack:HPACK encoding [(':method', 'GET'), (':scheme', 'https'), (':authority', 'xxnet-1.appsp
ot.com'), (':path', '/_gh/')]
DEBUG:hyper.packages.hpack.hpack:Adding (':method', 'GET') to the header table
DEBUG:hyper.packages.hpack.hpack:Encoding 2 with 7 bits
DEBUG:hyper.packages.hpack.hpack:Adding (':scheme', 'https') to the header table
DEBUG:hyper.packages.hpack.hpack:Encoding 7 with 7 bits
DEBUG:hyper.packages.hpack.hpack:Adding (':authority', 'xxnet-1.appspot.com') to the header table
DEBUG:hyper.packages.hpack.hpack:Encoding 1 with 6 bits
DEBUG:hyper.packages.hpack.hpack:Encoding 14 with 7 bits
DEBUG:hyper.packages.hpack.hpack:Adding (':path', '/_gh/') to the header table
DEBUG:hyper.packages.hpack.hpack:Encoding 4 with 6 bits
DEBUG:hyper.packages.hpack.hpack:Encoding 4 with 7 bits
DEBUG:hyper.packages.hpack.hpack:Encoded header block to 倗A庴姊?隕gJ??D刡)
INFO:hyper.http20.connection:Sending frame HeadersFrame on stream 1
DEBUG:root:buffer socket flush:33
INFO:hyper.http20.connection:Received frame SettingsFrame on stream 0
May 05 17:58:03.014 - [DEBUG] ip:118.98.106.178 real fail
INFO:hyper.http20.connection:Received frame HeadersFrame on stream 1
DEBUG:hyper.packages.hpack.hpack:Decoding 坃嘔|?猘椷=縅?覀

**Comment by sfqfirst** [comment]
3.1.4，访问youtube，卡住时的日志
Exception in thread Thread-128:
Traceback (most recent call last):
  File "D:\Downloads\翻墙\XX-Net-master\code\default\python27\1.0\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "D:\Downloads\翻墙\XX-Net-master\code\default\python27\1.0\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "D:\Downloads\翻墙\XX-Net-master\code\default\gae_proxy\local\connect_manager.py", line 398, in connect_thread
    self.ssl_timeout_cb(ssl_sock)
  File "D:\Downloads\翻墙\XX-Net-master\code\default\gae_proxy\local\http_dispatcher.py", line 92, in on_ssl_created_cb
    worker = HTTP2_worker(ssl_sock, self.close_cb, self.retry_task_cb)
  File "D:\Downloads\翻墙\XX-Net-master\code\default\gae_proxy\local\http2_connection.py", line 126, in __init__
    threading.Thread(target=self.recv_loop).start()
  File "D:\Downloads\翻墙\XX-Net-master\code\default\python27\1.0\lib\threading.py", line 736, in start
    _start_new_thread(self.__bootstrap, ())
error: can't start new thread

May 05 18:08:27.008 - [DEBUG] get ip:210.143.147.38 t:386
May 05 18:08:27.590 - [DEBUG] create_ssl update ip:210.143.147.38 time:389 h2:1
Exception in thread Thread-49:
Traceback (most recent call last):
  File "D:\Downloads\翻墙\XX-Net-master\code\default\python27\1.0\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "D:\Downloads\翻墙\XX-Net-master\code\default\python27\1.0\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "D:\Downloads\翻墙\XX-Net-master\code\default\gae_proxy\local\connect_manager.py", line 398, in connect_thread
    self.ssl_timeout_cb(ssl_sock)
  File "D:\Downloads\翻墙\XX-Net-master\code\default\gae_proxy\local\http_dispatcher.py", line 92, in on_ssl_created_cb
    worker = HTTP2_worker(ssl_sock, self.close_cb, self.retry_task_cb)
  File "D:\Downloads\翻墙\XX-Net-master\code\default\gae_proxy\local\http2_connection.py", line 126, in __init__
    threading.Thread(target=self.recv_loop).start()
  File "D:\Downloads\翻墙\XX-Net-master\code\default\python27\1.0\lib\threading.py", line 736, in start
    _start_new_thread(self.__bootstrap, ())
error: can't start new thread

May 05 18:08:27.930 - [DEBUG] 203.165.14.242 fail:timeout('timed out',)
May 05 18:08:27.933 - [DEBUG] report_connect_fail:203.165.14.242
May 05 18:08:28.534 - [DEBUG] ip:118.98.106.246 real fail
May 05 18:08:28.938 - [DEBUG] get ip:118.98.106.163 t:386
May 05 18:08:32.941 - [DEBUG] 118.98.106.163 fail:timeout('timed out',)
May 05 18:08:32.941 - [DEBUG] report_connect_fail:118.98.106.163
May 05 18:08:33.944 - [DEBUG] get ip:118.98.36.29 t:273
May 05 18:08:34.330 - [DEBUG] create_ssl update ip:118.98.36.29 time:273 h2:1
Exception in thread Thread-198:
Traceback (most recent call last):
  File "D:\Downloads\翻墙\XX-Net-master\code\default\python27\1.0\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "D:\Downloads\翻墙\XX-Net-master\code\default\python27\1.0\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "D:\Downloads\翻墙\XX-Net-master\code\default\gae_proxy\local\connect_manager.py", line 398, in connect_thread
    self.ssl_timeout_cb(ssl_sock)
  File "D:\Downloads\翻墙\XX-Net-master\code\default\gae_proxy\local\http_dispatcher.py", line 92, in on_ssl_created_cb
    worker = HTTP2_worker(ssl_sock, self.close_cb, self.retry_task_cb)
  File "D:\Downloads\翻墙\XX-Net-master\code\default\gae_proxy\local\http2_connection.py", line 126, in __init__
    threading.Thread(target=self.recv_loop).start()
  File "D:\Downloads\翻墙\XX-Net-master\code\default\python27\1.0\lib\threading.py", line 736, in start
    _start_new_thread(self.__bootstrap, ())
error: can't start new thread

May 05 18:08:35.831 - [DEBUG] restore ip:118.98.106.153
May 05 18:08:36.729 - [DEBUG] restore ip:118.98.106.162

**Comment by xxnet** [comment]
​看样子是有线程没有退出，累计到后面无法再创建线程了。
继续查bug

**Comment by sfqfirst** [comment]
（1）3.0.4：在Win8 x64 有线网环境，访问youtube，运行正常。在Win XP x86上无线网，运行正常
（2）3.1.4、3.1.3： 
  在Win8 x64，有线网络，访问youtube运行2分钟卡住，pythonw.exe会自动退出，日志和上面一样。
  在Win XP x86上无线网，访问youtube运行正常。

**Comment by sanan2015** [comment]
我换回了2.9.6，明显速度快了好多T_T
在3.0以上，谷歌搜索的时候联想都需要1-2秒，现在搜索马上能联想，搜索结果页面加载也非常快。ip是从3.0转移过来的，设置文件也转移过来了
建议检查一下实际优化的效果

**Comment by CongZeng** [comment]
![image](https://cloud.githubusercontent.com/assets/17735842/15087579/9ba692f4-141c-11e6-8142-e8ec9b6d37e0.png)
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36
xxnet-version: 3.1.6

python-version: 2.7.11
openssl-version: 0.15.1 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:1179 good:950
network-status: OK
connected-link: new:0 used:0
worker: h1:29 h2:0
scan-ip-thread-num: 0
ip-quality: 106
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by CHN008** [comment]
我还以为是我一个人遇到这问题了呢,刚Google都打不开了,关闭代理才能上这里来.
IP数量有一千多个,一会儿显示:尚未建立连接,一会儿显示"System Idle".等一下换回之前的版本看看.
