### ISSUE TITLE
经常报错

### ISSUE THREAD

**Issue by 94oiio** [XX-net/XX-Net#3263]
May 08 13:06:49.786 - [INFO] scan_ip add ip:78.37.100.231 time:777
May 08 13:06:49.832 - [DEBUG] sort ip time:46ms
May 08 13:06:49.832 - [INFO] remove_slowest_ip:78.11.253.249 handshake_time:567, fails:1
May 08 13:06:51.524 - [ERROR] 66.96.226.225 head appid:gx199410135 request fail:SysCallError(10054, 'WSAECONNRESET')
May 08 13:06:51.527 - [ERROR] Except stack:Traceback (most recent call last): File "D:\Tools\XX-Net\code\default\gae_proxy\local\http1.py", line 165, in head_request response.begin() File "D:\Tools\XX-Net\code\default\python27\1.0\lib\httplib.py", line 453, in begin version, status, reason = self._read_status() File "D:\Tools\XX-Net\code\default\python27\1.0\lib\httplib.py", line 409, in _read_status line = self.fp.readline(_MAXLINE + 1) File "D:\Tools\XX-Net\code\default\python27\1.0\lib\socket.py", line 480, in readline data = self._sock.recv(self._rbufsize) File "D:\Tools\XX-Net\code\default\gae_proxy\local\openssl_wrap.py", line 118, in recv return self.__iowait(self._connection.recv, bufsiz, flags) File "D:\Tools\XX-Net\code\default\gae_proxy\local\openssl_wrap.py", line 80, in __iowait raise e SysCallError: (10054, 'WSAECONNRESET')
May 08 13:06:51.527 - [DEBUG] report_connect_fail:66.96.226.225
May 08 13:06:53.046 - [DEBUG] ip:216.239.90.110 real fail
May 08 13:06:56.530 - [DEBUG] 66.96.226.225 worker close:keep alive

**Comment by 94oiio** [comment]
而且上谷歌不能即时搜索了
![default](https://cloud.githubusercontent.com/assets/18633798/15096148/64fbe8fe-151f-11e6-8657-168e89bac8d7.PNG)


最新版xx win10 64位

**Comment by HappysurfBlocking** [comment]
WSAECONNRESET是链接被重置，可能是电脑性能不够或者受到干扰
至于Google Instant不可用，也许是GDC代理本身的缘故
