### ISSUE TITLE
报错，但不影响使用

### ISSUE THREAD

**Issue by HappysurfBlocking** [XX-net/XX-Net#3265]
May 08 14:39:52.479 - [DEBUG] report_connect_fail:202.75.141.250
May 08 14:39:52.511 - [WARNING] 172.217.25.241 _consume_single_frame:SysCallError(10035, 'WSAEWOULDBLOCK')
May 08 14:39:52.513 - [DEBUG] ssl_closed 172.217.25.241
May 08 14:39:52.516 - [DEBUG] 172.217.25.241 worker close:disconnect:SysCallError(10035, 'WSAEWOULDBLOCK')
Exception in thread Thread-144:
Traceback (most recent call last):
  File "D:\Program Files (x86)\Anti-GFW\XX-Net\code\default\python27\1.0\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "D:\Program Files (x86)\Anti-GFW\XX-Net\code\default\python27\1.0\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "D:\Program Files (x86)\Anti-GFW\XX-Net\code\default\gae_proxy\local\http2_connection.py", line 167, in send_loop
    self._sock.flush()
  File "D:\Program Files (x86)\Anti-GFW\XX-Net\code\default\python27\1.0\lib\noarch\hyper\common\bufsocket.py", line 122, in flush
    sended = self._sck.send(data[start:start+send_size])
  File "D:\Program Files (x86)\Anti-GFW\XX-Net\code\default\gae_proxy\local\openssl_wrap.py", line 95, in __send
    return self.__iowait(self._connection.send, data, flags)
  File "D:\Program Files (x86)\Anti-GFW\XX-Net\code\default\gae_proxy\local\openssl_wrap.py", line 80, in __iowait
    raise e
SysCallError: (10038, 'WSAENOTSOCK')

May 08 14:39:52.681 - [DEBUG] 113.171.244.55 fail:timeout('timed out',)
May 08 14:39:52.685 - [DEBUG] report_connect_fail:113.171.244.55
May 08 14:39:53.049 - [DEBUG] 202.75.141.224 fail:timeout('timed out',)
May 08 14:39:53.060 - [DEBUG] create_ssl update ip:113.171.252.222 time:398 h2:1
May 08 14:39:53.060 - [DEBUG] report_connect_fail:202.75.141.224
May 08 14:39:53.161 - [DEBUG] create_ssl update ip:181.49.182.211 time:3068 h2:0
May 08 14:39:54.249 - [DEBUG] create_ssl update ip:106.103.1.164 time:2042 h2:0
May 08 14:40:00.635 - [DEBUG] create_ssl update ip:208.117.233.145 time:7667 h2:0

**Comment by xxnet** [comment]
收到，下次进去过滤日志
