### ISSUE TITLE
May 09 19:39:31.827 - [INFO] use build-in openssl lib May 09 19:39:31.830 - [INFO] start XX-Net 3.1.9 May 09 19:39:31.830 - [DEBUG] start confirm_xxnet_exit May 09 19:39:32.833 - [DEBUG] good, xxnet:8087 cleared! May 09 19:39:33.837 - [DEBUG] good, xxnet:8085 clear! May 09 19:39:33.838 - [DEBUG] finished confirm_xxnet_exit May 09 19:39:33.848 - [INFO] migrating to 3.x.x May 09 19:39:33.850 - [ERROR] launcher except:WindowsError(32, '') May 09 19:39:33.852 - [ERROR] Except stack:Traceback (most recent call last):   File "D:\Program Files\XX-Net\code\default\launcher\start.py", line 185, in <module>     main()   File "D:\Program Files\XX-Net\code\default\launcher\start.py", line 158, in main     post_update.run(last_run_version)   File "D:\Program Files\XX-Net\code\default\launcher\post_update.py", line 39, in run     os.remove(filepath) WindowsError: [Error 32] : 'D:\\Program Files\\XX-Net\\QQ\xce\xe5\xb1\xca\xbd\xd8\xcd\xbc\xce\xb4\xc3\xfc\xc3\xfb.png'

### ISSUE THREAD

**Issue by xhybb** [XX-net/XX-Net#3292]
点击上面的 ↑Preview↑ 来查看格式化后的说明。

---
## 提问之前
1. 首先请确认你使用的是[最新版本](https://github.com/XX-net/XX-Net/blob/master/code/default/download.md)，你的问题可能已经在新版本里解决了。
2. 请阅读[故障速查手册](https://github.com/XX-net/XX-Net/wiki/
(https://github.com/XX-net/XX-Net/wiki/故障速查手册)，大部分问题都能在这里找到答案。
3. 请在 [issue](https://github.com/XX-net/XX-Net/issues) 区搜索有无类似的问题。

---
## 问题内容
1. 请尽可能详细的描述你的问题，如问题能重现请附带重现方法。
2. 当你的问题得到解决后，记得关闭问题。
3. 可以参考[示例 issue](https://github.com/XX-net/XX-Net/issues/3193)。

### 附加内容
1. 提交 issue 时请贴出诊断信息、GAEProxy 日志，以便开发者和其他用户更好地帮助你。
2. 如果是部署相关的问题，请一并附带部署日志。
3. 如果你有任何与这个问题有关的信息，也请一并发出来。
4. 如果你没有提供诊断信息，我们很可能会忽略这个问题。

#### 获取诊断信息
点击[状态页](http://127.0.0.1:8085)下方的【诊断信息】按钮，如没有这个按钮，请将显示详细信息从【OFF】改为【ON】。

#### 获取日志
打开 [GAEProxy 日志页](http://127.0.0.1:8085/?module=gae_proxy&menu=logging) 复制网页右边部分的内容。

---
请在阅读完后点击上边的 Write，删除说明内容，然后描述你遇到的问题。

**Comment by jzp820927** [comment]
这 标题，太BT了

**Comment by Cat7373** [comment]
请。。。请贴出诊断日志。。。
谢谢。。。
以及如果能把标题改掉。。。
改成你的问题。。。
那就更好了。。。
日志请贴在内容里。。。

**Comment by Cat7373** [comment]
日志简单整理

    May 09 19:39:31.827 - [INFO] use build-in openssl lib 
    May 09 19:39:31.830 - [INFO] start XX-Net 3.1.9 
    May 09 19:39:31.830 - [DEBUG] start confirm_xxnet_exit 
    May 09 19:39:32.833 - [DEBUG] good, xxnet:8087 cleared! 
    May 09 19:39:33.837 - [DEBUG] good, xxnet:8085 clear! 
    May 09 19:39:33.838 - [DEBUG] finished confirm_xxnet_exit 
    May 09 19:39:33.848 - [INFO] migrating to 3.x.x 
    May 09 19:39:33.850 - [ERROR] launcher except:WindowsError(32, '') 
    May 09 19:39:33.852 - [ERROR] Except stack:Traceback (most recent call last):
        File "D:\Program Files\XX-Net\code\default\launcher\start.py", line 185, in <module> main()
        File "D:\Program Files\XX-Net\code\default\launcher\start.py", line 158, in main post_update.run(last_run_version)
        File "D:\Program Files\XX-Net\code\default\launcher\post_update.py", line 39, in run os.remove(filepath) WindowsError: [Error 32] : 'D:\\Program Files\\XX-Net\\QQ\xce\xe5\xb1\xca\xbd\xd8\xcd\xbc\xce\xb4\xc3\xfc\xc3\xfb.png'

**Comment by Cat7373** [comment]
日志简单整理

    May 09 19:39:31.827 - [INFO] use build-in openssl lib 
    May 09 19:39:31.830 - [INFO] start XX-Net 3.1.9 
    May 09 19:39:31.830 - [DEBUG] start confirm_xxnet_exit 
    May 09 19:39:32.833 - [DEBUG] good, xxnet:8087 cleared! 
    May 09 19:39:33.837 - [DEBUG] good, xxnet:8085 clear! 
    May 09 19:39:33.838 - [DEBUG] finished confirm_xxnet_exit 
    May 09 19:39:33.848 - [INFO] migrating to 3.x.x 
    May 09 19:39:33.850 - [ERROR] launcher except:WindowsError(32, '') 
    May 09 19:39:33.852 - [ERROR] Except stack:Traceback (most recent call last):
        File "D:\Program Files\XX-Net\code\default\launcher\start.py", line 185, in <module> main()
        File "D:\Program Files\XX-Net\code\default\launcher\start.py", line 158, in main post_update.run(last_run_version)
        File "D:\Program Files\XX-Net\code\default\launcher\post_update.py", line 39, in run os.remove(filepath) WindowsError: [Error 32] : 'D:\\Program Files\\XX-Net\\QQ\xce\xe5\xb1\xca\xbd\xd8\xcd\xbc\xce\xb4\xc3\xfc\xc3\xfb.png'

**Comment by Cat7373** [comment]
日志简单整理

    May 09 19:39:31.827 - [INFO] use build-in openssl lib 
    May 09 19:39:31.830 - [INFO] start XX-Net 3.1.9 
    May 09 19:39:31.830 - [DEBUG] start confirm_xxnet_exit 
    May 09 19:39:32.833 - [DEBUG] good, xxnet:8087 cleared! 
    May 09 19:39:33.837 - [DEBUG] good, xxnet:8085 clear! 
    May 09 19:39:33.838 - [DEBUG] finished confirm_xxnet_exit 
    May 09 19:39:33.848 - [INFO] migrating to 3.x.x 
    May 09 19:39:33.850 - [ERROR] launcher except:WindowsError(32, '') 
    May 09 19:39:33.852 - [ERROR] Except stack:Traceback (most recent call last):
        File "D:\Program Files\XX-Net\code\default\launcher\start.py", line 185, in <module> main()
        File "D:\Program Files\XX-Net\code\default\launcher\start.py", line 158, in main post_update.run(last_run_version)
        File "D:\Program Files\XX-Net\code\default\launcher\post_update.py", line 39, in run os.remove(filepath) WindowsError: [Error 32] : 'D:\\Program Files\\XX-Net\\QQ\xce\xe5\xb1\xca\xbd\xd8\xcd\xbc\xce\xb4\xc3\xfc\xc3\xfb.png'

**Comment by Cat7373** [comment]
日志简单整理

    May 09 19:39:31.827 - [INFO] use build-in openssl lib 
    May 09 19:39:31.830 - [INFO] start XX-Net 3.1.9 
    May 09 19:39:31.830 - [DEBUG] start confirm_xxnet_exit 
    May 09 19:39:32.833 - [DEBUG] good, xxnet:8087 cleared! 
    May 09 19:39:33.837 - [DEBUG] good, xxnet:8085 clear! 
    May 09 19:39:33.838 - [DEBUG] finished confirm_xxnet_exit 
    May 09 19:39:33.848 - [INFO] migrating to 3.x.x 
    May 09 19:39:33.850 - [ERROR] launcher except:WindowsError(32, '') 
    May 09 19:39:33.852 - [ERROR] Except stack:Traceback (most recent call last):
        File "D:\Program Files\XX-Net\code\default\launcher\start.py", line 185, in <module> main()
        File "D:\Program Files\XX-Net\code\default\launcher\start.py", line 158, in main post_update.run(last_run_version)
        File "D:\Program Files\XX-Net\code\default\launcher\post_update.py", line 39, in run os.remove(filepath) WindowsError: [Error 32] : 'D:\\Program Files\\XX-Net\\QQ\xce\xe5\xb1\xca\xbd\xd8\xcd\xbc\xce\xb4\xc3\xfc\xc3\xfb.png'

**Comment by jzp820927** [comment]
这都能整理出来，牛逼

**Comment by Cat7373** [comment]
XX-Net 肯定有 Bug - -
我只点了一次 Comment - -

是用 Notepad++ 直接替换的- -

**Comment by xxnet** [comment]
我知道为什么Cat73 会不断重复了，一会发个版本。

为什么XX目录下有个QQ呢？

**Comment by Cat7373** [comment]
@yeahwu 不是也说出现过重复的问题- -

**Comment by jzp820927** [comment]
我也是 Notepad++ 的老用户了

**Comment by Cat7373** [comment]
@xxnet 可能是截图吧

**Comment by keyoushi** [comment]
Notepad用来修改蓝灯的中转IP，刚刚的(●'◡'●)~

**Comment by jzp820927** [comment]
蓝灯现在都慢成翔了，还有人在研究啊。

**Comment by Cat7373** [comment]
蓝灯虽然不怎么快，但是有些时候 XX-Net 没法用，只能用蓝灯。
比如：https://github.com/XX-net/XX-Net/issues/362

**Comment by zjhzxhz** [comment]
我是看到标题进来的 (doge脸)

**Comment by yeahwu** [comment]
没蓝灯用了，俺准备来编译lantern了
官方的那个启动弹窗就是流氓行径，还关不掉
