### ISSUE TITLE
我安装最新版本的时候报错！不知道为什么

### ISSUE THREAD

**Issue by rocke** [XX-net/XX-Net#3313]
May 10 17:06:57.539 - [ERROR] launcher except:WindowsError(32, '')
May 10 17:06:57.556 - [ERROR] Except stack:Traceback (most recent call last):
  File "E:\XX-Net-2.5.3\code\default\launcher\start.py", line 182, in <module>
    main()
  File "E:\XX-Net-2.5.3\code\default\launcher\start.py", line 155, in main
    post_update.run(last_run_version)
  File "E:\XX-Net-2.5.3\code\default\launcher\post_update.py", line 42, in run
    shutil.rmtree(filepath)
  File "E:\XX-Net-2.5.3\code\default\python27\1.0\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "E:\XX-Net-2.5.3\code\default\python27\1.0\lib\shutil.py", line 256, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "E:\XX-Net-2.5.3\code\default\python27\1.0\lib\shutil.py", line 254, in rmtree
    os.rmdir(path)
WindowsError: [Error 32] : 'E:\\XX-Net-2.5.3\\gae_proxy\\local'

**Comment by jzp820927** [comment]
是不是下载不完整，重新下载试试

**Comment by xxnet** [comment]
怀疑是文件权限问题。

​找个新的目录解压，把data目录拷过去就好

**Comment by yeahwu** [comment]
关杀毒，关防火墙试试

**Comment by rocke** [comment]
各位！ 已经处理完毕，处理过程如下：

1、安装python2.7.11版本，先安装python。
2、彻底删除原来旧版本的xx-net。删除不了重启删除
3、再安装新的版本就可以解决我的问题了
