### ISSUE TITLE
部署GOOGLE API ID的时候出现upload fail:ValidationError

### ISSUE THREAD

**Issue by rocke** [XX-net/XX-Net#3331]
2016-05-11 08:11:14,927 - root - INFO - set proxy to http://127.0.0.1:8087
2016-05-11 08:11:14,927 - root - INFO - ============ Begin upload ============
2016-05-11 08:11:14,927 - root - INFO - appid:xx-rocke-net
2016-05-11 08:11:14,953 - root - INFO - Send: /api/appversion/rollback, params={'version': '1', 'app_id': 'xx-rocke-net'}
2016-05-11 08:12:15,513 - root - ERROR - upload fail:ValidationError("Value '600' for response_code is out of range 100 - 599",)
Traceback (most recent call last):
File "E:\XX-Net-2.5.3\code\default\gae_proxy\server\uploader.py", line 70, in upload
result = appcfg.AppCfgApp(['appcfg', 'rollback', dirname ]).Run()
File "E:\XX-Net-2.5.3\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 2951, in Run
self.action(self)
File "E:\XX-Net-2.5.3\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 5044, in __call__
return method()
File "E:\XX-Net-2.5.3\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 4397, in Rollback
self._Rollback()
File "E:\XX-Net-2.5.3\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 4442, in _Rollback
appversion.Rollback(force_rollback)
File "E:\XX-Net-2.5.3\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 2362, in Rollback
force_rollback='1' if force_rollback else '0')
File "E:\XX-Net-2.5.3\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 1702, in Send
request_size_bytes)
File "E:\XX-Net-2.5.3\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 1723, in _RegisterReqestForLogging
request_size_bytes=request_size_bytes))
File "E:\XX-Net-2.5.3\code\default\gae_proxy\server\lib\google\appengine\api\validation.py", line 273, in __init__
self.SetMultiple(attributes)
File "E:\XX-Net-2.5.3\code\default\gae_proxy\server\lib\google\appengine\api\validation.py", line 177, in SetMultiple
self.Set(key, value)
File "E:\XX-Net-2.5.3\code\default\gae_proxy\server\lib\google\appengine\api\validation.py", line 305, in Set
setattr(self, key, value)
File "E:\XX-Net-2.5.3\code\default\gae_proxy\server\lib\google\appengine\api\validation.py", line 361, in __setattr__
value = self.GetValidator(key)(value, key)
File "E:\XX-Net-2.5.3\code\default\gae_proxy\server\lib\google\appengine\api\validation.py", line 599, in __call__
return self.Validate(value, key)
File "E:\XX-Net-2.5.3\code\default\gae_proxy\server\lib\google\appengine\api\validation.py", line 1157, in Validate
% (value, key, self.minimum, self.maximum))
ValidationError: Value '600' for response_code is out of range 100 - 599
2016-05-11 08:12:15,630 - root - INFO - Retry 1 time...

**Comment by wenliyang** [comment]
升级到最新版本再部署
