### ISSUE TITLE
3.1.15 无法启动

### ISSUE THREAD

**Issue by Sam0523** [XX-net/XX-Net#3367]
```
5月 12 20:06:04.62 - [ERROR] start module gae_proxy fail:[Errno -2] Name or service not known
5月 12 20:06:04.62 - [ERROR] Except stack:Traceback (most recent call last):
  File "/home/sam/github/XX-Net/code/default/launcher/module_init.py", line 37, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "/home/sam/github/XX-Net/code/default/gae_proxy/start.py", line 13, in <module>
    import local.proxy as client
  File "/home/sam/github/XX-Net/code/default/gae_proxy/local/proxy.py", line 97, in <module>
    import proxy_handler
  File "/home/sam/github/XX-Net/code/default/gae_proxy/local/proxy_handler.py", line 66, in <module>
    get_self_host = socket.gethostbyname_ex(socket.gethostname())
gaierror: [Errno -2] Name or service not known

5月 12 20:06:04.62 - [ERROR] launcher except:gaierror(-2, 'Name or service not known')
5月 12 20:06:04.62 - [ERROR] Except stack:Traceback (most recent call last):
  File "code/default/launcher/start.py", line 182, in <module>
  File "code/default/launcher/start.py", line 159, in main
  File "/home/sam/github/XX-Net/code/default/launcher/module_init.py", line 98, in start_all_auto
    start(module)
  File "/home/sam/github/XX-Net/code/default/launcher/module_init.py", line 37, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "/home/sam/github/XX-Net/code/default/gae_proxy/start.py", line 13, in <module>
    import local.proxy as client
  File "/home/sam/github/XX-Net/code/default/gae_proxy/local/proxy.py", line 97, in <module>
    import proxy_handler
  File "/home/sam/github/XX-Net/code/default/gae_proxy/local/proxy_handler.py", line 66, in <module>
    get_self_host = socket.gethostbyname_ex(socket.gethostname())
gaierror: [Errno -2] Name or service not known
```

**Comment by Sam0523** [comment]
而且出现这个错误之后无法正常退出，只能 kill

**Comment by xxnet** [comment]
​先用3.1.14吧，3.1.15存在问题，回滚了
