### ISSUE TITLE
RedHat 6.5上无法运行

### ISSUE THREAD

**Issue by eejackyang** [XX-net/XX-Net#3376]
运行错误为：

May 13 12:33:07.846 - [ERROR] import system python-OpenSSL fail:ImportError("/lib64/libc.so.6: version `GLIBC_2.14' not found (required by /home/user1/XX-Net-3.1.15/code/default/python27/1.0/lib/linux/_cffi_backend.so)",)
May 13 12:33:07.847 - [ERROR] Except stack:Traceback (most recent call last):
  File "code/default/launcher/start.py", line 112, in <module>
    import OpenSSL
  File "/home/user1/gcc-4.8.4/rtf/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/home/user1/gcc-4.8.4/rtf/lib/python2.7/site-packages/OpenSSL/rand.py", line 12, in <module>
    from OpenSSL._util import (
  File "/home/user1/gcc-4.8.4/rtf/lib/python2.7/site-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/home/user1/XX-Net-3.1.15/code/default/python27/1.0/lib/linux/cryptography/hazmat/bindings/openssl/binding.py", line 60, in <module>
    class Binding(object):
  File "/home/user1/XX-Net-3.1.15/code/default/python27/1.0/lib/linux/cryptography/hazmat/bindings/openssl/binding.py", line 109, in Binding
    libraries=_get_libraries(sys.platform)
  File "/home/user1/XX-Net-3.1.15/code/default/python27/1.0/lib/linux/cryptography/hazmat/bindings/utils.py", line 97, in build_ffi_for_binding
    extra_link_args=extra_link_args,
  File "/home/user1/XX-Net-3.1.15/code/default/python27/1.0/lib/linux/cryptography/hazmat/bindings/utils.py", line 105, in build_ffi
    ffi = FFI()
  File "/home/user1/XX-Net-3.1.15/code/default/python27/1.0/lib/linux/cffi/api.py", line 56, in __init__
    import _cffi_backend as backend
ImportError: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /home/user1/XX-Net-3.1.15/code/default/python27/1.0/lib/linux/_cffi_backend.so)

Try install python-openssl

Press Enter to continue...

但是我在那个服务器上没有权限升级那个libc库，请问大家这个问题该如何解决？谢谢！

**Comment by jzp820927** [comment]
Try install python-openssl

都提示你要安装这个包了，不安装肯定用不了

**Comment by eejackyang** [comment]
@jzp820927 这个包已经装了，问题应该在于我们得到的_cffi_backend.so那个文件是通过新版的libc库编译的，因此在RedHat那种比较老的库上无法找到那个定义。

**Comment by jzp820927** [comment]
好吧，没用过 rh 都是用 ubu，不熟悉这个系统，只有等X大来看看了

**Comment by eejackyang** [comment]
@jzp820927 跪求X大关注啊。。。万分火急

**Comment by eejackyang** [comment]
参见：https://github.com/XX-net/XX-Net/issues/3380
