### ISSUE TITLE
请问_cffi_backend.so那个文件是怎么生成的？

### ISSUE THREAD

**Issue by eejackyang** [XX-net/XX-Net#3380]
它的源代码在哪里？

路径为：
code/default/python27/1.0/lib/linux/_cffi_backend.so

这个文件能不能根据自己的系统环境自行生成？现在好像是给定的生成好的，但是里面需要的一些库跟我的机器不一致。

请问怎么生成这个文件？谢谢～

**Comment by xyuanmu** [comment]
这玩意儿就有点类似Windows系统的dll文件，而且32位和64位编译的不通用。自己编译的话一般安装pyOpenSSL的命令都能安装这个库，看你是什么系统了，可以参考下：https://github.com/xyuanmu/XX-Mini/wiki/No-module-named-OpenSSL

**Comment by eejackyang** [comment]
@xyuanmu 谢谢X大！我再试试~系统是RedHat 6.5 (64bit)，已经装了libffi-devel和openssl和pyopenssl，估计把那个文件替换掉就行了，我看看能不能再系统里找到_cffi_backend.so

**Comment by xyuanmu** [comment]
据我的经验，你可以尝试重命名_cffi_backend.so，应该会自动检索系统中安装好的模块。

**Comment by eejackyang** [comment]
@xyuanmu 谢谢！结果发现是libffi-devel没有安装。但是安装了之后，仍然有错误。错误信息如下：


May 14 02:37:11.982 - [ERROR] start module gae_proxy fail:No such protocol
May 14 02:37:11.983 - [ERROR] Except stack:Traceback (most recent call last):
  File "/home/user1/XX-Net-3.1.15/code/default/launcher/module_init.py", line 37, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "/home/user1/XX-Net-3.1.15/code/default/gae_proxy/start.py", line 13, in <module>
    import local.proxy as client
  File "/home/user1/XX-Net-3.1.15/code/default/gae_proxy/local/proxy.py", line 97, in <module>
    import proxy_handler
  File "/home/user1/XX-Net-3.1.15/code/default/gae_proxy/local/proxy_handler.py", line 53, in <module>
    import gae_handler
  File "/home/user1/XX-Net-3.1.15/code/default/gae_proxy/local/gae_handler.py", line 65, in <module>
    from appids_manager import appid_manager
  File "/home/user1/XX-Net-3.1.15/code/default/gae_proxy/local/appids_manager.py", line 11, in <module>
    import check_ip
  File "/home/user1/XX-Net-3.1.15/code/default/gae_proxy/local/check_ip.py", line 60, in <module>
    openssl_context = openssl_wrap.SSLConnection.context_builder(ca_certs=g_cacertfile)
  File "/home/user1/XX-Net-3.1.15/code/default/gae_proxy/local/openssl_wrap.py", line 248, in context_builder
    ssl_context = OpenSSL.SSL.Context(protocol_version)
  File "/home/user1/XX-Net-3.1.15/code/default/python27/1.0/lib/noarch/OpenSSL/SSL.py", line 473, in __init__
    raise ValueError("No such protocol")
ValueError: No such protocol

然后对/home/user1/XX-Net-3.1.15/code/default/gae_proxy/local/openssl_wrap.py这个文件进行了修改。在第245行添加了一句：ssl_version = "TLSv1"，发现可以正确执行了。好像之前的是"TLSV1_2"那个版本，所以才会显示no such protocol的。具体原因不知。加了这么一句之后，确实可以正常执行了。

目前可以访问www.google.com.hk和youtube，但是奇怪的是gmail却无法访问。输入用户名和密码之后，总是提示“您所请求的网页无效”。这个不知道是什么问题。

另外，输入127.0.0.1:8085，并没有跳转到配置页面，因此现在我不知道怎么设置我自己拥有的google appid。可能现在一直在用共用的那个google appid。

**Comment by xyuanmu** [comment]
3.1.15访问谷歌是有些问题，先退回到3.1.14版本。

**Comment by eejackyang** [comment]
@xyuanmu 好的，谢谢X大！
