### ISSUE TITLE
求助！在小米路由器R1D上部署XX-Net 3.1.14出现问题

### ISSUE THREAD

**Issue by sntea** [XX-net/XX-Net#3391]
求助！在小米路由器R1D上部署XX-Net 3.1.14出现问题
无法打开管理页面，已经开启远程连接Web控制端，但是输入  地址:8085无法访问

下面是启动页面的一些信息：

root@XiaoQiang:~# /userdisk/data/python/bin/python/userdisk/data/xx-net/code/def
ault/launcher/start.py
-ash: /userdisk/data/python/bin/python/userdisk/data/xx-net/code/default/launche                                                                             r/start.py: not found
root@XiaoQiang:~# /userdisk/data/python/bin/python /userdisk/data/xx-net/code/de
fault/launcher/start.py
/userdisk/data/python/bin/python: '/userdisk/data/xx-net/code/default/python27/1                                                                             .0/lib/linux/_cffi_backend.so' is not an ELF executable for ARM
/userdisk/data/python/bin/python: '/userdisk/data/xx-net/code/default/python27/1                                                                             .0/lib/linux/_cffi_backend.so' is not an ELF executable for ARM
May 15 01:14:22.748 - [INFO] import build-in openssl fail:ImportError('File not                                                                              found',)
May 15 01:14:23.560 - [INFO] start XX-Net 3.1.14
May 15 01:14:23.561 - [DEBUG] start confirm_xxnet_exit
May 15 01:14:23.569 - [DEBUG] good, xxnet:8087 cleared!
May 15 01:14:23.574 - [DEBUG] good, xxnet:8085 clear!
May 15 01:14:23.574 - [DEBUG] finished confirm_xxnet_exit
May 15 01:14:23.689 - [INFO] load manual.ini success
May 15 01:14:24.241 - [INFO] SSL use version:TLSv1
May 15 01:14:24.255 - [INFO] OpenSSL dont't support npn/alpn, no HTTP/2 supporte                                                                             d.
May 15 01:14:24.261 - [INFO] load ip range file:/userdisk/data/xx-net/code/defau                                                                             lt/gae_proxy/local/ip_range.txt
May 15 01:14:24.679 - [INFO] load google ip_list num:785, gws num:785
May 15 01:14:24.846 - [INFO] OpenSSL dont't support npn/alpn, no HTTP/2 supporte                                                                             d.
May 15 01:14:24.849 - [DEBUG] get ip:113.171.252.161 t:159
May 15 01:14:24.862 - [DEBUG] get ip:113.171.247.19 t:167
May 15 01:14:24.891 - [INFO] load manual.ini success
May 15 01:14:24.897 - [DEBUG] ## GAEProxy set keep_running: True
May 15 01:14:24.900 - [INFO] ---------------------------------------------------                                                                             ---
May 15 01:14:24.900 - [INFO] Python Version     : 2.7.5
May 15 01:14:24.902 - [INFO] OS                 : Dist:; Version:; ID:
May 15 01:14:24.902 - [INFO] Listen Address     : 0.0.0.0:8087
May 15 01:14:24.902 - [INFO] GAE APPID          : 
May 15 01:14:24.903 - [INFO] Pac Server         : http://0.0.0.0:8086/proxy.pac
May 15 01:14:24.903 - [INFO] ---------------------------------------------------                                                                             ---
May 15 01:14:24.939 - [INFO] server 0.0.0.0:8087 started.
May 15 01:14:24.940 - [INFO] server 0.0.0.0:8086 started.
May 15 01:14:24.980 - [INFO] module gae_proxy started
May 15 01:14:24.981 - [INFO] start gae_proxy time cost:1405 ms
WARNING:root:Load Crypto.Cipher.ARC4 Failed, Use Pure Python Instead.
May 15 01:14:25.135 - [INFO] use config_path:/userdisk/data/xx-net/data/x_tunnel                                                                             /client.json
May 15 01:14:25.136 - [INFO] Use proxy:127.0.0.1:8087
May 15 01:14:25.137 - [DEBUG] x-tunnel no account
May 15 01:14:25.138 - [WARNING] x-tunnel session not start
May 15 01:14:25.138 - [ERROR] bind to 127.0.0.1:1080 fail:error(98, 'Address alr                                                                             eady in use')
Exception in thread Thread-211:
Traceback (most recent call last):
  File "/userdisk/data/python/lib/python2.7/threading.py", line 808, in __bootst                                                                             rap_inner
    self.run()
  File "/userdisk/data/python/lib/python2.7/threading.py", line 761, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/userdisk/data/xx-net/code/default/x_tunnel/start.py", line 19, in main
    client.main()
  File "/userdisk/data/xx-net/code/default/x_tunnel/local/client.py", line 154,                                                                              in main
    g.socks5_server = simple_http_server.HTTPServer((g.config.socks_host, g.conf                                                                             ig.socks_port), Socks5Server)
  File "/userdisk/data/xx-net/code/default/python27/1.0/lib/noarch/simple_http_s                                                                             erver.py", line 259, in __init__
    self.init_socket()
  File "/userdisk/data/xx-net/code/default/python27/1.0/lib/noarch/simple_http_s                                                                             erver.py", line 264, in init_socket
    self.add_listen(addr)
  File "/userdisk/data/xx-net/code/default/python27/1.0/lib/noarch/simple_http_s                                                                             erver.py", line 274, in add_listen
    raise Exception(err_string)
Exception: bind to 127.0.0.1:1080 fail:error(98, 'Address already in use')

May 15 01:14:25.239 - [DEBUG] create_ssl update ip:113.171.247.19 time:238 h2:0
May 15 01:14:25.239 - [DEBUG] create_ssl update ip:113.171.252.161 time:234 h2:0
May 15 01:14:25.364 - [DEBUG] get ip:113.171.244.83 t:168
May 15 01:14:25.548 - [DEBUG] network is ok, cost:1571 ms
May 15 01:14:25.648 - [DEBUG] create_ssl update ip:113.171.244.83 time:192 h2:0
May 15 01:14:33.642 - [INFO] scan_ip add ip:46.134.193.13 time:792
May 15 01:14:44.357 - [INFO] scan_ip add ip:113.171.252.179 time:190
May 15 01:14:47.209 - [INFO] scan_ip add ip:213.59.210.122 time:392
May 15 01:14:57.992 - [INFO] scan_ip add ip:200.28.8.29 time:1221
May 15 01:15:11.254 - [INFO] scan_ip add ip:196.46.1.177 time:1962
May 15 01:15:18.112 - [INFO] scan_ip add ip:31.55.162.179 time:828
May 15 01:15:25.294 - [INFO] scan_ip add ip:92.226.2.177 time:1204
May 15 01:15:31.507 - [INFO] scan_ip add ip:122.168.100.114 time:4106
May 15 01:15:33.925 - [INFO] scan_ip add ip:41.189.63.84 time:852
May 15 01:15:35.111 - [INFO] scan_ip add ip:103.15.244.160 time:1049
May 15 01:15:35.524 - [INFO] scan_ip add ip:212.122.6.244 time:230
May 15 01:15:37.022 - [INFO] scan_ip add ip:185.42.244.146 time:809
May 15 01:15:48.591 - [INFO] scan_ip add ip:24.156.131.28 time:671
May 15 01:15:51.582 - [INFO] scan_ip add ip:194.24.134.94 time:795
May 15 01:15:56.993 - [INFO] scan_ip add ip:184.150.152.121 time:514
May 15 01:16:18.647 - [INFO] scan_ip add ip:184.150.183.114 time:913
May 15 01:16:20.313 - [INFO] scan_ip add ip:193.192.250.177 time:4423
May 15 01:16:34.438 - [INFO] scan_ip add ip:95.153.46.228 time:630
May 15 01:16:45.519 - [INFO] scan_ip add ip:24.53.238.12 time:600
May 15 01:16:50.103 - [INFO] scan_ip add ip:213.105.64.218 time:1522
May 15 01:16:52.703 - [INFO] scan_ip add ip:157.157.135.50 time:1948
May 15 01:17:01.136 - [INFO] scan_ip add ip:195.13.231.177 time:984
May 15 01:17:02.067 - [INFO] scan_ip add ip:94.20.252.31 time:432
May 15 01:17:11.034 - [INFO] scan_ip add ip:202.75.147.41 time:679
May 15 01:17:16.686 - [INFO] scan_ip add ip:193.134.255.18 time:461
May 15 01:17:16.864 - [INFO] scan_ip add ip:77.37.252.55 time:627
May 15 01:17:29.973 - [INFO] scan_ip add ip:202.75.147.52 time:898
May 15 01:17:34.286 - [INFO] scan_ip add ip:213.94.75.108 time:3022
May 15 01:17:35.318 - [INFO] scan_ip add ip:109.195.105.180 time:2089
May 15 01:17:36.135 - [INFO] scan_ip add ip:46.61.155.97 time:400
May 15 01:17:44.085 - [INFO] scan_ip add ip:194.90.196.27 time:1869
May 15 01:17:47.786 - [INFO] scan_ip add ip:193.134.255.12 time:482
May 15 01:17:54.937 - [INFO] PAC from:192.168.31.198:45629 GET /proxy.pac
May 15 01:17:55.145 - [INFO] PAC from:192.168.31.198:52119 GET /proxy.pac

**Comment by sorsoso** [comment]
找到\data\launcher\config.yaml文件
修改
launcher: {allow_remote_connect: 0
为:
launcher: {allow_remote_connect: 1

xxnet默认不允许外网访问WEB设置界面,所以路由器上运行xxnet电脑端访问也算外网了.
此项修改就好了.

---------------------------------------------------------------
另外你的1080端口被占用导致xtunnel模块没跑起来,2个选择如果不用去模块管理那里关掉,用就修改一下端口

**Comment by sorsoso** [comment]
还有你的openssl貌似不支持npn/alpn. 可以更新一下openssl和py-openssl

**Comment by gxggsrmyy** [comment]
@sorsoso 请教你的是什么版本，python27 - 2.7.11-1 这个版本怎么安装， 用 opkg install python 默认安装的是低版本的，你列出的这此程序应怎么装。

**Comment by gxggsrmyy** [comment]
@sorsoso 怎样更新openssl和py-openssl

**Comment by gxggsrmyy** [comment]
@sorsoso   openwrt chaos_calmer/15.05.1/ramips/mt7620/ 小米路由mini  的python版本是   
 python_2.7.9-6_ramips_24kec.ipk   python-openssl_2.7.9-6_ramips_24kec.ipk

**Comment by jkle112** [comment]
小菜鸟想请教如何安装,如果可以请大神写个简单教程,谢谢!

**Comment by sorsoso** [comment]
@gxggsrmyy  这帖子说的是小米r1d.是armv7处理器的,我刷了tomato 1.30 
源就不一样 http://ipkg.nslu2-linux.org/optware-ng/buildroot-armeabi-ng/

**Comment by edwinhuish** [comment]
求大神附上小米路由部署XX-NET的教程。

**Comment by sntea** [comment]
最新情况。已经成功部署了，2.9.6版本基本正常运行，在启动脚本不知道怎么写，现在就差开机自动启动脚本了，
我在/etc/rc.local添加了脚本不能开机自动启动，求帮助写条开机启动脚本。
以下是/etc/rc.local文件全部内容，到底是哪里错了？
# restore phy config
speed=$(uci -q get xiaoqiang.common.WAN_SPEED)
[ -n "$speed" ] && /usr/sbin/phyhelper swan "$speed"
    sleep 5
    iptables -I INPUT -p tcp --dport 8087 -j ACCEPT
    iptables -I INPUT -p tcp --dport 8086 -j ACCEPT
    sleep 10
    /userdisk/data/python/bin/python /userdisk/data/xx-net/launcher/setup.py &
	
exit 0

以下是一些启动信息

BusyBox v1.19.4 (2016-01-26 16:02:03 CST) built-in shell (ash)
Enter 'help' for a list of built-in commands.

 -----------------------------------------------------
        Welcome to XiaoQiang!
 -----------------------------------------------------
root@XiaoQiang:~# python /userdisk/data/xx-net/launcher/start.py
May 20 23:58:16.505 - [INFO] start XX-Net 2.9.6
May 20 23:58:16.506 - [DEBUG] start confirm_xxnet_exit
May 20 23:58:16.517 - [DEBUG] good, xxnet:8087 cleared!
May 20 23:58:16.535 - [DEBUG] good, xxnet:8085 clear!
May 20 23:58:16.535 - [DEBUG] finished confirm_xxnet_exit
May 20 23:58:16.672 - [INFO] load manual.ini success
May 20 23:58:17.257 - [DEBUG] network is ok, cost:141 ms
May 20 23:58:17.261 - [INFO] SSL use version:TLSv1
May 20 23:58:17.268 - [INFO] load ip range file:/userdisk/data/xx-net/gae_proxy/local/ip_range.txt
May 20 23:58:18.022 - [INFO] load google ip_list num:3000, gws num:3000
May 20 23:58:18.064 - [DEBUG] sort ip time:41ms
May 20 23:58:18.850 - [INFO] load manual.ini success
May 20 23:58:18.862 - [DEBUG] ## GAEProxy set keep_running: True
May 20 23:58:18.872 - [INFO] ------------------------------------------------------
May 20 23:58:18.874 - [INFO] Python Version     : 2.7.5
May 20 23:58:18.876 - [INFO] OS                 : Dist:; Version:; ID:
May 20 23:58:18.878 - [INFO] Listen Address     : 0.0.0.0:8087
May 20 23:58:18.878 - [INFO] GAE APPID          : api-project-741670468655
May 20 23:58:18.879 - [INFO] Pac Server         : http://0.0.0.0:8086/proxy.pac
May 20 23:58:18.879 - [INFO] ------------------------------------------------------
May 20 23:58:18.919 - [INFO] server 0.0.0.0:8087 started.
May 20 23:58:18.941 - [INFO] server 0.0.0.0:8086 started.
May 20 23:58:19.025 - [INFO] module gae_proxy started
May 20 23:58:19.026 - [INFO] start gae_proxy time cost 2490
May 20 23:58:19.027 - [INFO] begin to start web control
May 20 23:58:19.028 - [INFO] server 0.0.0.0:8085 started.
May 20 23:58:19.037 - [INFO] launcher web control started.
May 20 23:58:20.044 - [INFO] get uuid:5e1ee0ea-5c30-4d5f-a6eb-542e68e54621
May 20 23:58:21.058 - [INFO] GAE CONNECT xxnet-update.appspot.com:443
May 20 23:58:21.089 - [DEBUG] get ip:183.78.5.186 t:560
May 20 23:58:21.151 - [DEBUG] GAE CONNECT Direct GET https://xxnet-update.appspot.com/update.json?uuid=5e1ee0ea-5c30-4d5f-a6eb-542e68e54621&version=2.9.6&platform=Linux-2.6.36-armv7l-with-libc0
May 20 23:58:21.156 - [DEBUG] get ip:95.154.114.82 t:608
May 20 23:58:21.190 - [DEBUG] get ip:66.96.224.222 t:839
May 20 23:58:21.291 - [DEBUG] get ip:64.71.249.119 t:872
May 20 23:58:21.393 - [DEBUG] get ip:115.254.106.243 t:909
May 20 23:58:21.495 - [DEBUG] get ip:115.254.97.98 t:920
May 20 23:58:21.597 - [DEBUG] get ip:115.254.106.211 t:923
May 20 23:58:21.699 - [DEBUG] get ip:184.150.153.18 t:927
May 20 23:58:21.800 - [DEBUG] get ip:184.150.186.93 t:945
May 20 23:58:21.902 - [DEBUG] get ip:115.254.121.218 t:949
May 20 23:58:22.003 - [DEBUG] get ip:222.165.163.83 t:964
May 20 23:58:22.252 - [DEBUG] create_ssl update ip:66.96.224.222 time:749
May 20 23:58:22.252 - [DEBUG] create_ssl update ip:183.78.5.186 time:673
May 20 23:58:22.308 - [DEBUG] get ip:189.194.54.113 t:993
May 20 23:58:22.415 - [DEBUG] create_ssl update ip:64.71.249.119 time:847
May 20 23:58:22.641 - [DEBUG] create_ssl update ip:115.254.106.243 time:834
May 20 23:58:22.771 - [DEBUG] create_ssl update ip:115.254.97.98 time:854
May 20 23:58:22.969 - [DEBUG] create_ssl update ip:115.254.106.211 time:917
May 20 23:58:23.273 - [WARNING] direct_handler.fetch bad status line:BadStatusLine("''",)
May 20 23:58:23.274 - [DEBUG] 183.78.5.186 close:request_fail
May 20 23:58:23.274 - [DEBUG] ssl_closed 183.78.5.186
May 20 23:58:23.286 - [DEBUG] create_ssl update ip:115.254.121.218 time:928
May 20 23:58:23.527 - [DEBUG] create_ssl update ip:222.165.163.83 time:1172
May 20 23:58:23.740 - [INFO] DIRECT t:2587 s:1674 200 xxnet-update.appspot.com /update.json?uuid=5e1ee0ea-5c30-4d5f-a6eb-542e68e54621&version=2.9.6&platform=Linux-2.6.36-armv7l-with-libc0
May 20 23:58:23.744 - [INFO] download https://raw.githubusercontent.com/XX-net/XX-Net/master/README.md to /userdisk/data/xx-net/data/downloads/README.md, retry:0
May 20 23:58:24.843 - [ERROR] check_update fail:TypeError("'NoneType' object has no attribute '__getitem__'",)
May 20 23:58:24.863 - [ERROR] Except stack:Traceback (most recent call last):
  File "/userdisk/data/xx-net/launcher/update.py", line 248, in check_update
    if LooseVersion(current_version) < LooseVersion(versions[1][1]):
TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by jzp820927** [comment]
直接写 python /userdisk/data/xx-net/launcher/start.py 到 rc.local 里面呢？

**Comment by sntea** [comment]
试过了，没有开机启动！
上面有我的 rc.local 文件全部代码，不知道哪里错了

**Comment by magian1127** [comment]
我是RD2 部署成功...最新的版本...但是 网上下的 python2.7.5 版本太低..无法支持http/2...
希望谁能编译下 python2.7.12 包含 pyopenss最新版就好了..这样就可以比较好的支持新版xx-net
