### ISSUE TITLE
X-TUNNEL不能用

### ISSUE THREAD

**Issue by sunny-m** [XX-net/XX-Net#3399]
##满怀欣喜的购买了季度卡，一个月过去了，一直都不能用，眼看要到期，来提个问题，希望能够得到解决。
诊断信息：
```
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.10586
os-system: Windows
os-version: 10.0.10586
os-release: 10
os-detail: Version:10-0; Build:10586; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36
xxnet-version: 3.1.16

python-version: 2.7.11
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:418 good:330
network-status: OK
connected-link: new:2 used:0
worker: h1:27 h2:1
scan-ip-thread-num: 5
ip-quality: 197
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false
```
流量买了好久，但是X-TUNNEL就是不能用，作为付费用户希望能够得到解答，以下是日志信息，一直在输出错误：
```
May 16 09:37:06.035 - [DEBUG] socks5 auth num:1, list:00
May 16 09:37:06.035 - [ERROR] socks5 protocol error:error('recv fail',)
May 16 09:37:06.035 - [ERROR] Except stack:Traceback (most recent call last): File "D:\Program Files (x86)\XX-Net\code\default\x_tunnel\local\proxy_handler.py", line 131, in socks5_handler data = self.read_bytes(4) File "D:\Program Files (x86)\XX-Net\code\default\x_tunnel\local\proxy_handler.py", line 74, in read_bytes raise socket.error("recv fail") error: recv fail
```
并没有看懂，不知道怎么使用，另外，我在手机上下载了**Shadowrocket**,能否使用这个app配置X-TUNNEL?

**Comment by xxnet** [comment]
​如果安装了迅雷，请先卸载了重启电脑，再试试。

x_tunnel和ss不同，不能混用

**Comment by sunny-m** [comment]
卸载后测试通过，可以使用了。如何让全局代理都走x_tunnel，而不是只有浏览器内容？

**Comment by ugvf2009** [comment]
@sunny-m 全局走x_tunnel,要用什么辅助工具么？

**Comment by xxnet** [comment]
​试试SocksCap

**Comment by sunny-m** [comment]
谢谢解答。
