### ISSUE TITLE
在foxmail上无法使用GMAIL邮箱？报错见内，能否帮忙解决一下？

### ISSUE THREAD

**Issue by angel126** [XX-net/XX-Net#34]
Feb 23 09:58:55 - [INFO] GAE CONNECT imap.gmail.com:993 
Feb 23 09:59:18 - [DEBUG] forward closed.

Feb 23 10:09:45 - [INFO] "GAE t:377 speed:2809 len:1059 status:405 CONNECT imap.gmail.com:993 HTTP/1.1"
Feb 23 10:09:45 - [WARNING] GAEProxyHandler.do_METHOD_AGENT return SSLError(1, '_ssl.c:1309: error:1409F07F:SSL routines:SSL3_WRITE_PENDING:bad write retry'), abort. url='imap.gmail.com:993' 

foxmail状态一直显示 检查所有邮件。
FOXMAIL设置 http代理 127.0.0.1 8087

**Comment by angel126** [comment]
这个是用thunderbird 的错误
Feb 23 13:32:18 - [INFO] GAE CONNECT services.addons.mozilla.org:443 
Feb 23 13:32:18 - [DEBUG] GAE CONNECT GET https://services.addons.mozilla.org/zh-CN/thunderbird/discovery/pane/31.4.0/WINNT
Feb 23 13:32:18 - [WARNING] request failed:None
Feb 23 13:32:18 - [WARNING] request failed:None
Feb 23 13:32:18 - [WARNING] request failed:None
Feb 23 13:32:18 - [ERROR] GAEProxyHandler.do_METHOD_AGENT 'https://services.addons.mozilla.org/zh-CN/thunderbird/discovery/pane/31.4.0/WINNT' return KeyError(None,)
Feb 23 13:32:18 - [ERROR] Except stack:Traceback (most recent call last):
File "E:\Downloads\Tools\google\XX-Net-1.0.9\goagent\3.1.34\local\proxy_handler.py", line 479, in do_AGENT
response = gae_urlfetch(self.command, self.path, request_headers, payload, **kwargs)
File "E:\Downloads\Tools\google\XX-Net-1.0.9\goagent\3.1.34\local\proxy_handler.py", line 202, in gae_urlfetch
response = request(payload, request_headers)
File "E:\Downloads\Tools\google\XX-Net-1.0.9\goagent\3.1.34\local\proxy_handler.py", line 147, in request
ssl_sock = https_manager.create_ssl_connection()
File "E:\Downloads\Tools\google\XX-Net-1.0.9\goagent\3.1.34\local\connect_manager.py", line 297, in create_ssl_connection
ret = self.conn_pool.get_nowait()
File "E:\Downloads\Tools\google\XX-Net-1.0.9\goagent\3.1.34\local\connect_manager.py", line 102, in get_nowait
return self.get(block=False)
File "E:\Downloads\Tools\google\XX-Net-1.0.9\goagent\3.1.34\local\connect_manager.py", line 96, in get
item = self._get()
File "E:\Downloads\Tools\google\XX-Net-1.0.9\goagent\3.1.34\local\connect_manager.py", line 113, in _get
self.pool.pop(fastest_sock)
KeyError: None

**Comment by xxnet** [comment]
这算是一个bug吧，目前的版本没有考虑到非443端口的google服务，下个版本修复

**Comment by xxnet** [comment]
尝试了一下，发现目前的技术方案不能支持，放弃了，建议用web方式访问gmail吧，比foxmail好太多了。

**Comment by vipzrx** [comment]
@xxnet @angel126 我也是用tb，已经使用ss全局代理，还是无法收gmail。
你们的tb可以接收gmail吗？

**Comment by jzp820927** [comment]
在你原贴回复你了。
