### ISSUE TITLE
3.1.4，linux下报502错误

### ISSUE THREAD

**Issue by CodeLieutenant** [XX-net/XX-Net#3414]
错误日志见下：

May 17 11:37:20.521 - [WARNING] server app return fail, status:502
May 17 11:37:20.521 - [ERROR] gae_handler.handler TypeError('not a valid non-string sequence or mapping object',) http://ris.szpl.gov.cn/bol/projectdetail.aspx?id=18546 , retry...
May 17 11:37:20.521 - [ERROR] Except stack:Traceback (most recent call last):
  File "/opt/proxyservers/xxnet/xxnet/app9237/code/default/gae_proxy/local/gae_handler.py", line 333, in request_gae_proxy
    xlog.warn('app_msg:%s', urllib.urlencode(response.app_msg))
  File "/opt/apps_install/python2.7/lib/python2.7/urllib.py", line 1315, in urlencode
    raise TypeError
TypeError: not a valid non-string sequence or mapping object

**Comment by jzp820927** [comment]
访问国内网站？

**Comment by CodeLieutenant** [comment]
对，访问的国内的网站。大概率会出现TypeError错误。原因是哪方面的呢

**Comment by jzp820927** [comment]
没必要吧，国外网站直连就行了，估计应该是国内网站的兼容性问题，以前还有人说，访问百度有乱码

**Comment by CodeLieutenant** [comment]
我因为某些原因，需要隐藏ip，不能直连。看错误应该是类型错误，提示不是有效的字符串序列。。我在想，这些提示是不是无效提示，就是60内没成功，retry的时候打的日志

**Comment by jzp820927** [comment]
gae 对部分网站是有兼容性问题，或者可以试试 x_tunnel 或者 蓝灯
