### ISSUE TITLE
Ubuntu14.04下3.1.14版本无法显示配置界面

### ISSUE THREAD

**Issue by CornerOfSkyline** [XX-net/XX-Net#3530]
## 问题内容
1. 使用Ubuntu14.04版本，XX-NET版本为3.1.14，手动从2.6升级过来，保留data文件夹；
2. 使用./start启动XX-NET后，终端窗口显示会报错，错误信息如下：

 5月 27 23:47:24.7 - [INFO] Use proxy:127.0.0.1:8087
 5月 27 23:47:24.7 - [DEBUG] create_ssl update ip:118.98.111.95 time:535 h2:0
 5月 27 23:47:24.7 - [DEBUG] x-tunnel no account
 5月 27 23:47:24.7 - [WARNING] x-tunnel session not start
 5月 27 23:47:24.7 - [ERROR] bind to 127.0.0.1:1080 fail:error(98, '\xe5\x9c\xb0\xe5\x9d\x80\xe5\xb7\xb2\xe5\x9c\xa8\xe4\xbd\xbf\xe7\x94\xa8')
Exception in thread Thread-62:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/Tools/XX-Net/code/default/x_tunnel/start.py", line 19, in main
    client.main()
  File "/home/Tools/XX-Net/code/default/x_tunnel/local/client.py", line 154, in main
    g.socks5_server = simple_http_server.HTTPServer((g.config.socks_host, g.config.socks_port), Socks5Server)
  File "/home/Tools/XX-Net/code/default/python27/1.0/lib/noarch/simple_http_server.py", line 259, in __init__
    self.init_socket()
  File "/home/Tools/XX-Net/code/default/python27/1.0/lib/noarch/simple_http_server.py", line 264, in init_socket
    self.add_listen(addr)
  File "/home/Tools/XX-Net/code/default/python27/1.0/lib/noarch/simple_http_server.py", line 274, in add_listen
    raise Exception(err_string)
Exception: bind to 127.0.0.1:1080 fail:error(98, '\xe5\x9c\xb0\xe5\x9d\x80\xe5\xb7\xb2\xe5\x9c\xa8\xe4\xbd\xbf\xe7\x94\xa8')

PHP_proxy XX-Net - PHP_proxy                                 C,,  
5月 27 23:47:45.4 - [INFO] scan_ip add ip:109.110.33.49 time:409
5月 27 23:47:52.0 - [INFO] scan_ip add ip:41.221.196.29 time:2102
5月 27 23:47:56.4 - [INFO] scan_ip add ip:77.234.90.104 time:741
5月 27 23:48:06.6 - [INFO] scan_ip add ip:82.113.19.55 time:616

3.采用火狐浏览器，可以访问google和youtube，任务栏上方无XX-NET图标， [GAEProxy 日志页](http://127.0.0.1:8085/?module=gae_proxy&menu=logging)无法打开，显示：Firefox 无法建立到 127.0.0.1:8085 服务器的连接。

**Comment by jzp820927** [comment]
5月 27 23:47:24.7 - [ERROR] bind to 127.0.0.1:1080 fail:error(98, 

端口绑定失败，你是不是开着 SS 客户端的？

**Comment by yaoguaishou** [comment]
我曾经尝试把XX-net目录下的文件权限全部修改为777，任务栏图标又回来了

**Comment by CornerOfSkyline** [comment]
应该没开SS客户端，我也不太清楚什么是SS客户端
