### ISSUE TITLE
部署私有appid失败，怎么解？

### ISSUE THREAD

**Issue by niubaty** [XX-net/XX-Net#3537]
http://127.0.0.1:8085/?module=gae_proxy&menu=deploy 
在该页面，把那一串字符复制进去后，点击开始部署.会弹出一个google的页面让我点allow.点完了就卡在那.这是部署日志:
2016-05-29 09:49:00,191 - root - INFO - set proxy to http://127.0.0.1:8087
2016-05-29 09:49:00,212 - root - INFO - ============ Begin upload ============
2016-05-29 09:49:00,212 - root - INFO - appid:ujefpqfjwkohiqxw
2016-05-29 09:49:00,264 - root - INFO - Send: /api/appversion/rollback, params={'version': '1', 'app_id': 'ujefpqfjwkohiqxw'}
2016-05-29 09:49:20,286 - root - ERROR - upload fail:ServerNotFoundError('Unable to find the server at appengine.google.com',)
Traceback (most recent call last):
File "/home/clicknight/bak/xxnet/XX-Net-3.1.14/code/default/gae_proxy/server/uploader.py", line 70, in upload
result = appcfg.AppCfgApp(['appcfg', 'rollback', dirname ]).Run()
File "/home/clicknight/bak/xxnet/XX-Net-3.1.14/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 2951, in Run
self.action(self)
File "/home/clicknight/bak/xxnet/XX-Net-3.1.14/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 5044, in **call**
return method()
File "/home/clicknight/bak/xxnet/XX-Net-3.1.14/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 4397, in Rollback
self._Rollback()
File "/home/clicknight/bak/xxnet/XX-Net-3.1.14/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 4442, in _Rollback
appversion.Rollback(force_rollback)
File "/home/clicknight/bak/xxnet/XX-Net-3.1.14/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 2362, in Rollback
force_rollback='1' if force_rollback else '0')
File "/home/clicknight/bak/xxnet/XX-Net-3.1.14/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 1696, in Send
result = self.rpcserver.Send(url, payload=payload, **kwargs)
File "/home/clicknight/bak/xxnet/XX-Net-3.1.14/code/default/gae_proxy/server/lib/google/appengine/tools/appengine_rpc_httplib2.py", line 247, in Send
url, method=method, body=payload, headers=headers)
File "/home/clicknight/bak/xxnet/XX-Net-3.1.14/code/default/gae_proxy/server/lib/httplib2/__init__.py", line 1593, in request
(response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
File "/home/clicknight/bak/xxnet/XX-Net-3.1.14/code/default/gae_proxy/server/lib/httplib2/__init__.py", line 1341, in _request
(response, content) = self._conn_request(conn, request_uri, method, body, headers)
File "/home/clicknight/bak/xxnet/XX-Net-3.1.14/code/default/gae_proxy/server/lib/httplib2/__init__.py", line 1283, in _conn_request
raise ServerNotFoundError("Unable to find the server at %s" % conn.host)
ServerNotFoundError: Unable to find the server at appengine.google.com
2016-05-29 09:49:20,303 - root - INFO - Retry 1 time...
2016-05-29 09:49:20,318 - root - INFO - Send: /api/appversion/rollback, params={'version': '1', 'app_id': 'ujefpqfjwkohiqxw'}
2016-05-29 09:49:40,336 - root - ERROR - upload fail:ServerNotFoundError('Unable to find the server at appengine.google.com',)
Traceback (most recent call last):
File "/home/clicknight/bak/xxnet/XX-Net-3.1.14/code/default/gae_proxy/server/uploader.py", line 70, in upload
result = appcfg.AppCfgApp(['appcfg', 'rollback', dirname ]).Run()
File "/home/clicknight/bak/xxnet/XX-Net-3.1.14/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 2951, in Run
self.action(self)
File "/home/clicknight/bak/xxnet/XX-Net-3.1.14/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 5044, in __call__
return method()
File "/home/clicknight/bak/xxnet/XX-Net-3.1.14/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 4397, in Rollback
self._Rollback()
File "/home/clicknight/bak/xxnet/XX-Net-3.1.14/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 4442, in _Rollback
appversion.Rollback(force_rollback)
File "/home/clicknight/bak/xxnet/XX-Net-3.1.14/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 2362, in Rollback
force_rollback='1' if force_rollback else '0')
File "/home/clicknight/bak/xxnet/XX-Net-3.1.14/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 1696, in Send
result = self.rpcserver.Send(url, payload=payload, **kwargs)
File "/home/clicknight/bak/xxnet/XX-Net-3.1.14/code/default/gae_proxy/server/lib/google/appengine/tools/appengine_rpc_httplib2.py", line 247, in Send
url, method=method, body=payload, headers=headers)
File "/home/clicknight/bak/xxnet/XX-Net-3.1.14/code/default/gae_proxy/server/lib/httplib2/__init__.py", line 1593, in request
(response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
File "/home/clicknight/bak/xxnet/XX-Net-3.1.14/code/default/gae_proxy/server/lib/httplib2/__init__.py", line 1341, in _request
(response, content) = self._conn_request(conn, request_uri, method, body, headers)
File "/home/clicknight/bak/xxnet/XX-Net-3.1.14/code/default/gae_proxy/server/lib/httplib2/__init__.py", line 1283, in _conn_request
raise ServerNotFoundError("Unable to find the server at %s" % conn.host)
ServerNotFoundError: Unable to find the server at appengine.google.com
2016-05-29 09:49:40,337 - root - INFO - Retry 2 time...
2016-05-29 09:49:41,360 - root - INFO - Send: /api/appversion/rollback, params={'version': '1', 'app_id': 'ujefpqfjwkohiqxw'}
2016-05-29 09:50:01,378 - root - ERROR - upload fail:ServerNotFoundError('Unable to find the server at appengine.google.com',)
Traceback (most recent call last):
File "/home/clicknight/bak/xxnet/XX-Net-3.1.14/code/default/gae_proxy/server/uploader.py", line 70, in upload
result = appcfg.AppCfgApp(['appcfg', 'rollback', dirname ]).Run()
File "/home/clicknight/bak/xxnet/XX-Net-3.1.14/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 2951, in Run
self.action(self)
File "/home/clicknight/bak/xxnet/XX-Net-3.1.14/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 5044, in __call__
return method()
File "/home/clicknight/bak/xxnet/XX-Net-3.1.14/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 4397, in Rollback
self._Rollback()
File "/home/clicknight/bak/xxnet/XX-Net-3.1.14/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 4442, in _Rollback
appversion.Rollback(force_rollback)
File "/home/clicknight/bak/xxnet/XX-Net-3.1.14/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 2362, in Rollback
force_rollback='1' if force_rollback else '0')
File "/home/clicknight/bak/xxnet/XX-Net-3.1.14/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 1696, in Send
result = self.rpcserver.Send(url, payload=payload, **kwargs)
File "/home/clicknight/bak/xxnet/XX-Net-3.1.14/code/default/gae_proxy/server/lib/google/appengine/tools/appengine_rpc_httplib2.py", line 247, in Send
url, method=method, body=payload, headers=headers)
File "/home/clicknight/bak/xxnet/XX-Net-3.1.14/code/default/gae_proxy/server/lib/httplib2/__init__.py", line 1593, in request
(response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
File "/home/clicknight/bak/xxnet/XX-Net-3.1.14/code/default/gae_proxy/server/lib/httplib2/__init__.py", line 1341, in _request
(response, content) = self._conn_request(conn, request_uri, method, body, headers)
File "/home/clicknight/bak/xxnet/XX-Net-3.1.14/code/default/gae_proxy/server/lib/httplib2/__init__.py", line 1283, in _conn_request
raise ServerNotFoundError("Unable to find the server at %s" % conn.host)
ServerNotFoundError: Unable to find the server at appengine.google.com
2016-05-29 09:50:01,379 - root - INFO - Retry 3 time...
2016-05-29 09:50:03,382 - root - INFO - =======================
2016-05-29 09:50:03,382 - root - INFO - Deploy failed appid list:
2016-05-29 09:50:03,383 - root - INFO - - ujefpqfjwkohiqxw
2016-05-29 09:50:03,383 - root - INFO - == END ==
从结果上看，应该是部署失败了吧.
进入https://appengine.google.com/  发现appid的status是none deployed.
并且http://127.0.0.1:8085/?module=gae_proxy&menu=status上面提示也是:您正在使用公共APPID，因为资源有限，使用上存在限制，建议部署私有APPID。

怎么解？

**Comment by nly4lov** [comment]
if you can visit google, fb, tt, ytb, etc., before this uploading, then i am not sure what's up.

**Comment by yeahwu** [comment]
最新版试试
Adam Song <notifications@github.com>于2016年5月29日 周日00:54写道：

**Comment by teN-XX** [comment]
这个问题应该在3.1.17已经解决了，请升级到3.1.17以上的版本再试试。

**Comment by niubaty** [comment]
试了3.1.18和3.1.19，还是老问题。这次的log是：

2016-05-29 23:44:12,524 - root - INFO - set proxy to http://127.0.0.1:8087
2016-05-29 23:44:12,525 - root - INFO - ============ Begin upload ============
2016-05-29 23:44:12,525 - root - INFO - appid:gtbgbtihvjlioozn
2016-05-29 23:44:12,539 - root - INFO - Send: /api/appversion/rollback, params={'version': '1', 'app_id': 'gtbgbtihvjlioozn'}
2016-05-29 23:45:13,777 - oauth2client.client - INFO - Successfully retrieved access token
2016-05-29 23:45:14,599 - root - INFO - Send: /api/appversion/rollback, params={'version': '1', 'app_id': 'gtbgbtihvjlioozn'}
2016-05-29 23:45:15,078 - root - INFO - Send: /api/appversion/rollback, params={'version': '1', 'app_id': 'gtbgbtihvjlioozn'}
2016-05-29 23:45:15,569 - root - INFO - =======================
2016-05-29 23:45:15,569 - root - INFO - Deploy failed appid list:
2016-05-29 23:45:15,570 - root - INFO - - gtbgbtihvjlioozn
2016-05-29 23:45:15,570 - root - INFO - == END ==

**Comment by nly4lov** [comment]
我各版本都一直能翻，有时也许有小问题，但从来没有布署不了的时候

**Comment by niubaty** [comment]
访问google是可以，但是访问ytb不行啊。如果可以，当然希望偶尔能下点东西啊：）
