### ISSUE TITLE
openwrt 路由器上的 pyopenssl  版本太低，不支持者http2

### ISSUE THREAD

**Issue by gxggsrmyy** [XX-net/XX-Net#3556]
@yeahwu  xxnet在openwrt 路由器上 运行，调用的pyopenssl是系统的，而不是xx-net 自带的，现在openwrt 路由器上的 pyopenssl 版本太低不支持 http2,    怎样才能调用xx-net  自带的pyopenssl，不过好象xx-net 上自带的pyopenssl  linux 版本不支持 openwrt，,能不能 给xx-net 增加一个openwrt版本的pyopenssl，另外想问，pyopenssl  和python-openssl 有什么区别?

**Comment by yeahwu** [comment]
这个问题对于俺来说有点难道哇！平时也就吹牛，打屁的干活……
俺帮你转接 @xxnet

**Comment by junegucas** [comment]
openwrt的版本？
昨晚刚在trunk上试验成功，支持http2。
opkg update
opkg install bash
opkg insatll python
opkg install python-pyopenssl
就可以直接用了。
其他版本的Openwrt，未曾试验成功过，即使装上trunk源里的也会无法启动。

@yeahwu 那么接下来，如何做透明代理？redsocks2是否会牺牲速度而且二次转发是否存在证书问题？本人用redsocks2做透明代理，任何被墙网站都提示证书链不完整。

**Comment by junegucas** [comment]
最新版的trunk无luci界面，需先通过command line调试通网络后再进行包的安装。

**Comment by jzp820927** [comment]
以前 goa 自带透明代理配置，挺好用的。不过好像 XXNET 没把这个移植过来，挺可惜的。

**Comment by sbitoh** [comment]
@junegucas  我找了一天了也找不到python-pyopenssl，请问哪个源有这个啊

**Comment by junegucas** [comment]
@sbitoh  
https://downloads.openwrt.org/snapshots/trunk/ar71xx/generic/packages/packages/python-pyopenssl_16.0.0-1_ar71xx.ipk
替换对应平台即可，ar71xx

**Comment by roc1010kmt** [comment]
@junegucas # opkg install python-pyopenssl_16.0.0-1_ar71xx.ipk
Installing python-pyopenssl (16.0.0-1) to root...
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for python-pyopenssl:
 *      python-cryptography *   python-six *
 * opkg_install_cmd: Cannot install package python-pyopenssl.

**Comment by roc1010kmt** [comment]
@junegucas 我安裝你提供的python-pyopenssl_16.0.0-1_ar71xx.ipk版,啟動xxnet錯誤?
# python /tmp/xx/proxy.py
Traceback (most recent call last):
File "/tmp/xx/proxy.py", line 63, in 
from OpenSSL import version as openssl_version
File "/usr/lib/python2.7/site-packages/OpenSSL/init.py", line 8, in 
from OpenSSL import rand, crypto, SSL
File "/usr/lib/python2.7/site-packages/OpenSSL/rand.py", line 12, in 
from OpenSSL._util import (
File "/usr/lib/python2.7/site-packages/OpenSSL/_util.py", line 6, in 
from cryptography.hazmat.bindings.openssl.binding import Binding
File "/usr/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 14, in 
from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: File not found

**Comment by roc1010kmt** [comment]
pyopenssl_16啟動不了出錯,pyopenssl_10可以啟動.
不知為什麼路由器比電腦慢好多?youtube720p非常卡基本看不了.
電腦上就非常順暢.為什麼?

**Comment by jzp820927** [comment]
观察 CPU 和内存 占用，估计是硬件性能不足。

**Comment by roc1010kmt** [comment]
@jzp820927 系統平均負荷到過3.13左右,正常嗎?

**Comment by jzp820927** [comment]
内存呢？

**Comment by roc1010kmt** [comment]
内存82%左右,cpu100%,看視頻時.

**Comment by roc1010kmt** [comment]
為什麼關了putty,xxnet也跟著退出?

**Comment by jzp820927** [comment]
那就对了吗，内存82%左右,cpu100%, 那就等于是满负荷运行了，不卡才怪。
你要用  nohup 命令 & 运行，才能在后台运行，不会你退出 putty，程序也退出了。

**Comment by roc1010kmt** [comment]
@jzp820927 有解決辦法嗎?什麼等級的路由器能完美運行?

**Comment by jzp820927** [comment]
硬件处理能力不足，除了更换更强劲的硬件，还有什么办法，我推荐 树莓派，运行这个绰绰有余。

**Comment by roc1010kmt** [comment]
看到好多人用小米路由器?小米不卡?

**Comment by jzp820927** [comment]
说实话，国产入门级路由器，硬件配置都很低。不过如果你有小米路由也可以试试

**Comment by roc1010kmt** [comment]
树莓派是單板電腦吧?怎麼做路由器?

**Comment by jzp820927** [comment]
那就得自己该做了，google 搜索， 树莓派 路由，你就会知道答案了。

**Comment by roc1010kmt** [comment]
@junegucas 你的openwrt什麼版本?15.05.1裝pyopenssl_16啟動不了報錯?
