### ISSUE TITLE
请大家看看这是什么问题

### ISSUE THREAD

**Issue by yangchangyz** [XX-net/XX-Net#3609]
Jun 06 13:17:45.871 - [ERROR] google_ip.runJob fail:TypeError("unsupported operand type(s) for +=: 'int' and 'NoneType'",)
Jun 06 13:17:45.871 - [ERROR] Except stack:Traceback (most recent call last):
  File "D:\翻墙\XX-Net\XX-Mini\XX-Mini_win_v1.2.7\python27.zip\google_ip.py", line 619, in scan_ip_worker
  File "D:\翻墙\XX-Net\XX-Mini\XX-Mini_win_v1.2.7\python27.zip\check_ip.py", line 213, in test_gae_ip2
  File "D:\翻墙\XX-Net\XX-Mini\XX-Mini_win_v1.2.7\python27.zip\hyper\http20\connection.py", line 114, in __init__
  File "D:\翻墙\XX-Net\XX-Mini\XX-Mini_win_v1.2.7\python27.zip\hyper\http20\connection.py", line 282, in _send_preamble
  File "D:\翻墙\XX-Net\XX-Mini\XX-Mini_win_v1.2.7\python27.zip\hyper\common\bufsocket.py", line 110, in send
  File "D:\翻墙\XX-Net\XX-Mini\XX-Mini_win_v1.2.7\python27.zip\hyper\common\bufsocket.py", line 123, in flush
TypeError: unsupported operand type(s) for +=: 'int' and 'NoneType'

请大家看看这是什么问题？

**Comment by Cat7373** [comment]
这是 XX-Mini 的问题，请去 XX-Mini 的 Issue 区反馈。
https://github.com/xyuanmu/XX-Mini/issues
