### ISSUE TITLE
新版本没有START.SH，如何在OPENWRT运行

### ISSUE THREAD

**Issue by sbitoh** [XX-net/XX-Net#3685]
按网上说的都配置好了，就是没有START.SH，怎么运行啊？
直接./START是不行的，没反映
default下的XX_NET.SH也不行，返回代码如下：
Python 2.7.3
Starting xx_net proxy server: xx_net.

/code/default/launcher/start.py 运行这个结果如下：
/mnt/SAWYER/soft/usr/bin/python2.7: '/mnt/SAWYER/b/code/default/python27/1.0/lib/linux/_cffi_backend.so' is not an ELF executable for MIPS
/mnt/SAWYER/soft/usr/bin/python2.7: '/mnt/SAWYER/b/code/default/python27/1.0/lib/linux/_cffi_backend.so' is not an ELF executable for MIPS
Jun 21 08:43:54.087 - [INFO] import build-in openssl fail:ImportError('File not found',)
Jun 21 08:44:09.015 - [INFO] start XX-Net 3.1.14
Jun 21 08:44:10.885 - [DEBUG] start confirm_xxnet_exit
Jun 21 08:44:10.915 - [DEBUG] good, xxnet:8087 cleared!
Jun 21 08:44:10.930 - [DEBUG] good, xxnet:8085 clear!
Jun 21 08:44:10.932 - [DEBUG] finished confirm_xxnet_exit
Jun 21 08:44:11.044 - [ERROR] start module gae_proxy fail:File contains no section headers.
file: /mnt/SAWYER/b/code/default/gae_proxy/local/proxy.ini, line: 1
"\xef\xbb\xbf; Don't Edit the file manual\r\n"
Jun 21 08:44:11.062 - [ERROR] Except stack:Traceback (most recent call last):
  File "/mnt/SAWYER/b/code/default/launcher/module_init.py", line 37, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "/mnt/SAWYER/b/code/default/gae_proxy/start.py", line 13, in <module>
    import local.proxy as client
  File "/mnt/SAWYER/b/code/default/gae_proxy/local/proxy.py", line 85, in <module>
    from config import config
  File "/mnt/SAWYER/b/code/default/gae_proxy/local/config.py", line 142, in <module>
    config.load()
  File "/mnt/SAWYER/b/code/default/gae_proxy/local/config.py", line 32, in load
    self.CONFIG.read(self.CONFIG_FILENAME)
  File "/mnt/SAWYER/soft/usr/lib/python2.7/ConfigParser.py", line 305, in read
    self._read(fp, filename)
  File "/mnt/SAWYER/soft/usr/lib/python2.7/ConfigParser.py", line 512, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
MissingSectionHeaderError: File contains no section headers.
file: /mnt/SAWYER/b/code/default/gae_proxy/local/proxy.ini, line: 1
"\xef\xbb\xbf; Don't Edit the file manual\r\n"

Jun 21 08:44:11.067 - [ERROR] launcher except:File contains no section headers.
file: /mnt/SAWYER/b/code/default/gae_proxy/local/proxy.ini, line: 1
"\xef\xbb\xbf; Don't Edit the file manual\r\n"
Jun 21 08:44:11.074 - [ERROR] Except stack:Traceback (most recent call last):
  File "/mnt/SAWYER/b/code/default/launcher/start.py", line 182, in <module>
    main()
  File "/mnt/SAWYER/b/code/default/launcher/start.py", line 159, in main
    module_init.start_all_auto()
  File "/mnt/SAWYER/b/code/default/launcher/module_init.py", line 98, in start_all_auto
    start(module)
  File "/mnt/SAWYER/b/code/default/launcher/module_init.py", line 37, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "/mnt/SAWYER/b/code/default/gae_proxy/start.py", line 13, in <module>
    import local.proxy as client
  File "/mnt/SAWYER/b/code/default/gae_proxy/local/proxy.py", line 85, in <module>
    from config import config
  File "/mnt/SAWYER/b/code/default/gae_proxy/local/config.py", line 142, in <module>
    config.load()
  File "/mnt/SAWYER/b/code/default/gae_proxy/local/config.py", line 32, in load
    self.CONFIG.read(self.CONFIG_FILENAME)
  File "/mnt/SAWYER/soft/usr/lib/python2.7/ConfigParser.py", line 305, in read
    self._read(fp, filename)
  File "/mnt/SAWYER/soft/usr/lib/python2.7/ConfigParser.py", line 512, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
MissingSectionHeaderError: File contains no section headers.
file: /mnt/SAWYER/b/code/default/gae_proxy/local/proxy.ini, line: 1
"\xef\xbb\xbf; Don't Edit the file manual\r\n"

求大神帮忙

**Comment by sbitoh** [comment]
执行了import OpenSSL，返回结果如下：
  File "<stdin>", line 1
    import OpenSSL
    ^
IndentationError: unexpected indent

这是我安装 的和OPENSSL有关的文件和版本
libopenssl 1.0.2-2 
pyopenssl 0.10-1 
python-openssl 2.7.3-2

**Comment by jzp820927** [comment]
估计是你 python 版本太低了吧

**Comment by Cat7373** [comment]
bash ./start

**Comment by sbitoh** [comment]
@jzp820927 找不到Pandora用的新的PYTHON,官方源里的是2.7.3的，伤心啊，大神有2.7.6的源吗？

**Comment by sbitoh** [comment]
@Cat7373 
bash版本是4.2-5 ，运行结果如下：
[root@PandoraBox_ACEC:/mnt/SAWYER/b]#ls
README.md     SwitchyOmega  code          data          start         start.bat     start.vbs
[root@PandoraBox_ACEC:/mnt/SAWYER/b]#bash ./start
-ash: bash: not found
还是不行。。。。。

**Comment by junegucas** [comment]
@sbitoh  你现在不仅bash不可用，连opkg都用不了了，可能，当然其他的很多命令你都用不了了。我当时重刷了OpenWrt.

**Comment by sbitoh** [comment]
@junegucas opkg可用。。。。

**Comment by sbitoh** [comment]
@Cat7373 三种方法都试了，还是不行，请问怎么给 start 文件 rx 权限

**Comment by junegucas** [comment]
chmod +x start

**Comment by junegucas** [comment]
可是这不是权限问题，是你的包管理系统出了问题，即使重装bash，也还是不行的。

**Comment by jzp820927** [comment]
bash ./start 不行，就试试  sh ./start
