### ISSUE TITLE
在NAS群晖DSM中安装XX-Net遇到问题

### ISSUE THREAD

**Issue by GerGitHub** [XX-net/XX-Net#3708]
先在群晖开启了TELET和SSH功能, WINSCP登录管理群晖根目录, PUTTY登陆到命令页面, 手动安装了optware,并修改PATH, `$PATH`
> -ash: /opt/bin:/opt/sbin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/syno/sbin:/usr/syno/bin:/usr/local/sbin:/usr/local/bin: not found

DSM自己已经带有 `python `
> Python 2.7.9 (default, Jun 11 2015, 05:35:22)
[GCC 4.6.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>

# **XX-Net2**版
通过WINSCP把XX-Net 2.0.5版复制到/opt/etc/文件夹内, XX-Net文件夹内我只保留了gae_proxy和python27两个文件夹,python27文件夹还必须保留,否则无法运行
`python /opt/etc/XX-Net/gae_proxy/start.py`
XX-Net开始运行了,OK! 修改了proxy.ini 把8087的IP换成了0.0.0.0,PAC的IP也换成了0.0.0.0, 局域网实现了IP代理共享;

我想只保留gae_prox文件夹,把python27文件夹给删掉,结果就运行返回如下内容

> 
Traceback (most recent call last):
  File "/opt/etc/XX-Net/gae_proxy/start.py", line 13, in <module>
    import local.proxy as client
  File "/volume1/@optware/etc/XX-Net/gae_proxy/local/proxy.py", line 83, in <module>
    import proxy_handler
  File "/volume1/@optware/etc/XX-Net/gae_proxy/local/proxy_handler.py", line 24, in <module>
    from connect_manager import https_manager,forwork_manager
  File "/volume1/@optware/etc/XX-Net/gae_proxy/local/connect_manager.py", line 17, in <module>
    import socks
ImportError: No module named socks

不明白这是什么原因, 请高手分析解决一下;

# **XX-Net3**版
我更新下载了XX-Net3.2版带有python3的,把XX-Net3也全拷到/opt/et目录下,Python3保留运行命令
`python /opt/etc/XX-Net3/gae_proxy/start.py`
运行不成功

> 
Traceback (most recent call last):
  File "/opt/etc/XX-Net/gae_proxy/start.py", line 13, in <module>
    import local.proxy as client
  File "/volume1/@optware/etc/XX-Net/gae_proxy/local/proxy.py", line 83, in <module>
    import proxy_handler
  File "/volume1/@optware/etc/XX-Net/gae_proxy/local/proxy_handler.py", line 24, in <module>
    from connect_manager import https_manager,forwork_manager
  File "/volume1/@optware/etc/XX-Net/gae_proxy/local/connect_manager.py", line 17, in <module>
    import socks
ImportError: No module named socks
DiskStation>
DiskStation> python /opt/etc/XX-NetP3/gae_proxy/start.py
Traceback (most recent call last):
  File "/opt/etc/XX-NetP3/gae_proxy/start.py", line 14, in <module>
    import local.proxy as client
  File "/volume1/@optware/etc/XX-NetP3/gae_proxy/local/proxy.py", line 73, in <module>
    import urllib.request, urllib.error, urllib.parse
ImportError: No module named request

也是运行不了,

目前Goagent,XX-mini可以直接python运行

XX-Net2系列版本必须同文件夹内带有Python27才可以运行,2.5版也试了,带有Python27就可以运行,删掉Python27文件夹就不可以

XX-Net3直接无法运行

不知道以上出现的问题是什么原因, 如何处理????

还有一个问题, 在成功运行的XX-Net 2.0.5时,通过共享代理登google网页,正常显示, facebook和twitter的页面显示就是乱的, 可能是证书的原因造成的, 安装了一个facebook的cert,然后facebook显示就正常了;

**Comment by Cat7373** [comment]
XX-Net3.x 一样是使用 Python2.x 的哟

**Comment by Cat7373** [comment]
至于 XX-Net2.0.5 已经是很早以前的版本了，基本不会再进行维护了哟

**Comment by jzp820927** [comment]
安装你的需求来说，XX-mini 就是最适合你的了，何必还要去 折腾 XXNET，都是一个东西，没必要。

**Comment by hehh2001** [comment]
话说mini 版用起来太爽了，小巧，我要的功能全有，布署在路由器上妥妥的
