### ISSUE TITLE
mac 10.11.5 python 2.7.10 xx-net 3.1.9/3.2.4无法启动

### ISSUE THREAD

**Issue by oganda** [XX-net/XX-Net#3804]
双击start或者命令行./start运行后都是如下提示
➜ ./start
grep: unknown --color option
Python 2.7.10
XX-Net version:default
➜ 

然后就没有然后了,也无法访问127.0.0.1:8085. 已确认8085端口无其他服务占用
新人一枚,到这一步就无法继续了,求前辈指点,是否缺少了什么步骤导致我无法启动

**Comment by jzp820927** [comment]
升级到最新版试试

**Comment by oganda** [comment]
还是不行,一样的反馈

**Comment by yeahwu** [comment]
给权限，chmod a+x

**Comment by oganda** [comment]
已经授权了还是一样
![image](https://cloud.githubusercontent.com/assets/4241122/16644768/d8a5e244-4451-11e6-9da0-f2a0ab618271.png)

**Comment by jzp820927** [comment]
试试手动输入命令运行：
python xx-net/code/default/gae_proxy/start.py

**Comment by cc941201** [comment]
执行`./start -hungup`，将错误信息发上来

**Comment by oganda** [comment]
Jul 07 17:47:35.951 - [ERROR] bind to 127.0.0.1:8087 fail:error(48, 'Address already in use')
Exception in thread Thread-58:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/bluesoul/Downloads/XX-Net-3.1.19/code/default/gae_proxy/start.py", line 18, in main
    client.main()
  File "/Users/bluesoul/Downloads/XX-Net-3.1.19/code/default/gae_proxy/local/proxy.py", line 155, in main
    proxy_daemon = simple_http_server.HTTPServer((config.LISTEN_IP, config.LISTEN_PORT), proxy_handler.GAEProxyHandler)
  File "/Users/bluesoul/Downloads/XX-Net-3.1.19/code/default/python27/1.0/lib/noarch/simple_http_server.py", line 259, in __init__
    self.init_socket()
  File "/Users/bluesoul/Downloads/XX-Net-3.1.19/code/default/python27/1.0/lib/noarch/simple_http_server.py", line 264, in init_socket
    self.add_listen(addr)
  File "/Users/bluesoul/Downloads/XX-Net-3.1.19/code/default/python27/1.0/lib/noarch/simple_http_server.py", line 274, in add_listen
    raise Exception(err_string)
Exception: bind to 127.0.0.1:8087 fail:error(48, 'Address already in use')

8087被占用了,但是我改了config.yaml里面的端口也没用
➜ more data/launcher/config.yaml
modules:
  gae_proxy: {auto_start: 1}
  launcher: {allow_remote_connect: 0, control_port: 8085, last_run_version: 3.1.19,
    proxy: pac, xxnet_port: 8088}
  php_proxy: {control_port: 8083}
  x_tunnel: {auto_start: 1}

求指点

**Comment by cc941201** [comment]
端口占用一般重启一下就好了

**Comment by oganda** [comment]
还是不行
![image](https://cloud.githubusercontent.com/assets/4241122/16826032/9a6e58f2-49ac-11e6-9533-b5d372c2d02d.png)

**Comment by yeahwu** [comment]
你这占用的是1080端口，也就是ss端口！
oganda <notifications@github.com>于2016年7月14日 周四10:21写道：

**Comment by oganda** [comment]
停掉ss,搞定了,cool,感谢各位指点
