### ISSUE TITLE
ubuntu chrome 代理问题

### ISSUE THREAD

**Issue by zsxgb** [XX-net/XX-Net#3809]
XX-Net Status:

sys-platform: x86_64, Linux-4.4.0-28-generic-x86_64-with-Ubuntu-16.04-xenial
os-system: Linux
os-version: #47-Ubuntu SMP Fri Jun 24 10:09:13 UTC 2016
os-release: 4.4.0-28-generic
os-detail: Dist:Ubuntu; Version:16.04; ID:xenial
architecture: 64bit,ELF
browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36
xxnet-version: 3.2.4

python-version: 2.7.11+
openssl-version: 16.0.0 TLSv1_2 h2:npn

ipv6-status: 0
gws-ip-num: total:16 good:16
network-status: OK
connected-link: new:2 used:0
worker: h1:1 h2:1
scan-ip-thread-num: 50
ip-quality: 887
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

情况 ubuntu16.04 安装过很多次，只有这一次，这个问题有点怪。显示是代理问题，但是chrome和浏览器插件都处理好了。没有什么问题。为什么会代理出问题呢。

**Comment by jzp820927** [comment]
gws-ip-num: total:16 good:16

IP太少了，可以试试删除 data 重新扫描

**Comment by zsxgb** [comment]
删除之后还是这样的。也重新扫描了。

**Comment by zsxgb** [comment]
我觉得没有IP写的就是显示没有IP之类的，现在是检查浏览器代理设置。我觉得应该是哪里有设置错误。不知道应该咋处理

**Comment by jzp820927** [comment]
那你试试用代理访问个网站，看看日志有没有什么报错

**Comment by zsxgb** [comment]
现在的情况是我用firefox没有问题，而google chrome是写着请检查浏览器代理设置。
XX-Net Status:

sys-platform: x86_64, Linux-4.4.0-28-generic-x86_64-with-Ubuntu-16.04-xenial
os-system: Linux
os-version: #47-Ubuntu SMP Fri Jun 24 10:09:13 UTC 2016
os-release: 4.4.0-28-generic
os-detail: Dist:Ubuntu; Version:16.04; ID:xenial
architecture: 64bit,ELF
browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36
xxnet-version: 3.2.4

python-version: 2.7.11+
openssl-version: 16.0.0 TLSv1_2 h2:npn

ipv6-status: 0
gws-ip-num: total:47 good:46
network-status: OK
connected-link: new:8 used:0
worker: h1:11 h2:10
scan-ip-thread-num: 50
ip-quality: 294
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false



日志如下
7月 07 16:18:39.29 - [DEBUG] create_ssl update ip:177.35.32.221 time:596 h2:0
7月 07 16:18:39.37 - [DEBUG] create_ssl update ip:177.35.32.215 time:600 h2:0
7月 07 16:18:39.40 - [DEBUG] get ip:213.105.64.211 t:683
7月 07 16:18:39.61 - [DEBUG] get ip:213.105.64.206 t:684
7月 07 16:18:39.65 - [DEBUG] create_ssl update ip:92.197.129.95 time:682 h2:0
7月 07 16:18:39.86 - [DEBUG] create_ssl update ip:92.197.129.112 time:638 h2:0
7月 07 16:18:40.05 - [DEBUG] create_ssl update ip:92.246.12.214 time:649 h2:0
7月 07 16:18:40.19 - [DEBUG] create_ssl update ip:213.105.64.228 time:692 h2:0
7月 07 16:18:40.43 - [DEBUG] create_ssl update ip:213.105.64.211 time:683 h2:0
7月 07 16:18:40.64 - [DEBUG] create_ssl update ip:213.105.64.206 time:687 h2:0
7月 07 16:18:49.09 - [INFO] scan_ip add ip:103.233.37.14 time:699
7月 07 16:18:58.75 - [INFO] scan_ip add ip:202.93.153.168 time:295
7月 07 16:19:06.36 - [INFO] scan_ip add ip:203.78.36.97 time:114
7月 07 16:19:08.59 - [DEBUG] GAE GET http://www.gstatic.com/generate_204
7月 07 16:19:11.49 - [INFO] scan_ip add ip:203.252.15.155 time:599
7月 07 16:19:12.21 - [INFO] GAE t:3620 s:0 GET http://www.gstatic.com/generate_204 h2_get_head:3619
7月 07 16:19:15.03 - [INFO] scan_ip add ip:92.246.12.230 time:730
7月 07 16:19:16.38 - [INFO] scan_ip add ip:41.201.164.168 time:759
7月 07 16:19:24.07 - [INFO] scan_ip add ip:202.122.145.48 time:664
7月 07 16:19:29.40 - [DEBUG] get ip:203.78.36.97 t:114
7月 07 16:19:29.58 - [DEBUG] create_ssl update ip:203.78.36.97 time:119 h2:0
7月 07 16:19:29.58 - [DEBUG] get ip:202.93.153.168 t:295
7月 07 16:19:29.85 - [DEBUG] create_ssl update ip:202.93.153.168 time:180 h2:0

**Comment by zsxgb** [comment]
7月 07 16:47:06.59 - [INFO] scan_ip add ip:58.26.8.115 time:465
7月 07 16:47:06.77 - [ERROR] ssl.wrap_socket(self.connection=<ssl.SSLSocket object at 0x7f91ac3d7c08>) failed: [SSL: SSLV3_ALERT_BAD_CERTIFICATE] sslv3 alert bad certificate (_ssl.c:1754) path:www.twitter.com:443, errno:1
7月 07 16:47:06.77 - [ERROR] ssl.wrap_socket(self.connection=<ssl.SSLSocket object at 0x7f91ac876050>) failed: [SSL: SSLV3_ALERT_BAD_CERTIFICATE] sslv3 alert bad certificate (_ssl.c:1754) path:www.twitter.com:443, errno:1
7月 07 16:47:06.77 - [ERROR] Except stack:Traceback (most recent call last):
  File "/home/zsx/桌面/XX-Net-3.2.4/code/default/gae_proxy/local/proxy_handler.py", line 296, in do_CONNECT_AGENT
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
  File "/usr/lib/python2.7/ssl.py", line 752, in recv
    return self.read(buflen)
  File "/usr/lib/python2.7/ssl.py", line 639, in read
    v = self._sslobj.read(len)
SSLError: [SSL: SSLV3_ALERT_BAD_CERTIFICATE] sslv3 alert bad certificate (_ssl.c:1754)

7月 07 16:47:06.77 - [ERROR] Except stack:Traceback (most recent call last):
  File "/home/zsx/桌面/XX-Net-3.2.4/code/default/gae_proxy/local/proxy_handler.py", line 296, in do_CONNECT_AGENT
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
  File "/usr/lib/python2.7/ssl.py", line 752, in recv
    return self.read(buflen)
  File "/usr/lib/python2.7/ssl.py", line 639, in read
    v = self._sslobj.read(len)
SSLError: [SSL: SSLV3_ALERT_BAD_CERTIFICATE] sslv3 alert bad certificate (_ssl.c:1754)

我想我找到问题了。应该是新版的chrome对证书的支持问题。我导入证书在chrome一直不成功。应该咋办呢

**Comment by jzp820927** [comment]
导入证书不成功？有啥提示？

**Comment by yeahwu** [comment]
去wiki看一下，先删掉老证书，再导入新证书。

**Comment by zsxgb** [comment]
新装机的系统，少了一个什么东西。我后来仔细看的日志的时候，发现没有，然后装了一下，apt-get。然后是重启了一下，就好了。

**Comment by zsxgb** [comment]
多谢各位。
