### ISSUE TITLE
Centos 7 xx_net

### ISSUE THREAD

**Issue by evilstyle** [XX-net/XX-Net#383]
[root@centos1 XX-Net-1.13.6]# source chstart.sh
launcher version: 1.4.0
Traceback (most recent call last):
  File "launcher/start.py", line 63, in <module>
    main()
  File "launcher/start.py", line 58, in main
    from start import main as launcher_main
  File "/opt/XX-Net-1.13.6/launcher/1.4.0/start.py", line 13, in <module>
    from gtk_tray import sys_tray
  File "/opt/XX-Net-1.13.6/launcher/1.4.0/gtk_tray.py", line 18, in <module>
    import pynotify
ImportError: No module named pynotify
[root@centos1 XX-Net-1.13.6]# source start.sh
launcher version: 1.4.0
Traceback (most recent call last):
  File "launcher/start.py", line 63, in <module>
    main()
  File "launcher/start.py", line 58, in main
    from start import main as launcher_main
  File "/opt/XX-Net-1.13.6/launcher/1.4.0/start.py", line 13, in <module>
    from gtk_tray import sys_tray
  File "/opt/XX-Net-1.13.6/launcher/1.4.0/gtk_tray.py", line 18, in <module>
    import pynotify
ImportError: No module named pynotify
麻烦帮忙看看 这是什么情况 我没找到libnss3 这个lib 是这原因吗？

**Comment by xxnet** [comment]
试试：
sudo yum install python-notify

2015-05-10 23:34 GMT-04:00 evilstyle <notifications@github.com>:

**Comment by evilstyle** [comment]
我使用的epel 的源 ，yum install python-* 了所有 ，现在还是有pynotify eror，我查了下如果调用py-notify
先import notify

**Comment by xxnet** [comment]
参考：
https://bugs.launchpad.net/backintime/+bug/1406087

说centos 7没有包含 notify库了。

临时的做法:
1. 编辑 launcher/1.4.0/gtk_tray.py
  把pynotify 相关的行注释掉

2. 另一个办法：不显示托盘图标：
  cp launcher/1.4.0/non_tray.py launcher/1.4.0/gtk_tray.py

3. 找一个老版本的cent 6，把pynotify库拷贝过去。

2015-05-11 3:38 GMT-04:00 evilstyle <notifications@github.com>:

**Comment by xxnet** [comment]
下次import失败，就把notify 功能取消掉，不提示了。

**Comment by evilstyle** [comment]
ok

**Comment by xxnet** [comment]
1.14.6版本，pynotify作为可选模式。

如果找不到，就把这个功能屏蔽了，不会影响启动，你可以试试

2015-05-12 23:49 GMT-04:00 evilstyle <notifications@github.com>:

**Comment by evilstyle** [comment]
我试一试，谢谢哈。

**Comment by evilstyle** [comment]
ok 可以正常使用了。
