### ISSUE TITLE
请教！Openwrt布置XX-net出错。版本3.2.4

### ISSUE THREAD

**Issue by realGrimReaper** [XX-net/XX-Net#3833]
如题，Openwrt中设置好XX-net，启动后出现以下红字内容
Jul 11 00:53:44.969 - [ERROR] data/gae_proxy/manual.ini load error:File contains no section headers.
file: <???>, line: 1
'\xef\xbb\xbf[listen]\r\n'
Jul 11 00:53:45.522 - [ERROR] Except stack:Traceback (most recent call last):
  File "/mnt/usb/XX3/code/default/gae_proxy/local/config.py", line 44, in load
    self.CONFIG.readfp(io.BytesIO(content))
  File "/mnt/usb/usr/lib/python2.7/ConfigParser.py", line 324, in readfp
    self._read(fp, filename)
  File "/mnt/usb/usr/lib/python2.7/ConfigParser.py", line 512, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
MissingSectionHeaderError: File contains no section headers.
file: <???>, line: 1
'\xef\xbb\xbf[listen]\r\n'

在manual.ini中设置如下：
[listen]
ip = 0.0.0.0
port = 8087
visible = 1
debuginfo = 0

[pac]
enable = 1
ip = 0.0.0.0
port = 8086
file = proxy.pac
gfwlist = https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt
;adblock = http://adblock-chinalist.googlecode.com/svn/trunk/adblock.txt
; this project have stopped.
expired = 86400

[autorange]
threads = 8
maxsize = 524288
waitsize = 1048576
bufsize = 65535

[google_ip]
use_ipv6 = 0
auto_adjust_scan_ip_thread_num = 1
max_scan_ip_thread_num = 50
max_good_ip_num = 3000
ip_connect_interval = 8
max_links_per_ip = 3

; traffic quota: 100k/second
ip_traffic_quota = 100000
ip_traffic_quota_base = 100000

[connect_manager]
https_max_connect_thread = 10
https_connection_pool_min = 5
https_connection_pool_max = 50

请大神帮忙看看问题出在哪了。不胜感激。

**Comment by jzp820927** [comment]
Jul 11 00:53:44.969 - [ERROR] data/gae_proxy/manual.ini load error:File contains no section headers.

应该是 manual.ini 文件的 语法格式有问题

**Comment by realGrimReaper** [comment]
@jzp820927 谢谢，已将编码格式调整后解决。

**Comment by realGrimReaper** [comment]
请问XXnet在openwrt中运行需要python-pyopenssl吗？已安装python-openssl和pyopenssl，找不到Python-pyopenssl对应7260a的源，在运行xxnet后，提示几个文件is not an elf executable for MIPS, google 了一下是引文没装Python-pyopenssl所致。

**Comment by jzp820927** [comment]
openssl 相关的库是必须的。用于加密解密。

**Comment by realGrimReaper** [comment]
@jzp820927 谢谢回复。但是网上有教程，只是安装pyopenssl就好，不用非要安装python-pyopenssl。我已安装前者，却依然报错，按照github的教程是要安装后者的。但是那个库太老了，根本没有地方下。好像也有说法是pyopenssl取代了Python-pyopenssl。

**Comment by jzp820927** [comment]
一般相关的都装上，基本上不会出问题。

**Comment by realGrimReaper** [comment]
问题就是无法安装官方要求的库啊，但是google了会发现很多人都没有安装python-pyopenssl。[https://dreamcreator108.com/dreams/openwrt-xx-net/](url)

**Comment by jzp820927** [comment]
实在不行，可以试试 xxmini 有很多人在 ow 上运行 mini 成功了。

**Comment by realGrimReaper** [comment]
已经下载，之前看到兄弟回复别人的帖子提到过...实在不行就试试，谢谢

**Comment by realGrimReaper** [comment]
刷成14版本OW已解决，15版本中function脚本也有bug，在安装Python时不编译脚本会报错。

**Comment by jzp820927** [comment]
看来想要愉快的翻墙对 ow 版本还说蛮讲究的
