### ISSUE TITLE
x_tunnel不会使用

### ISSUE THREAD

**Issue by Yoshiki5** [XX-net/XX-Net#3855]
谷歌浏览器SwitchyOmega插件
新建情景模式“代理服务器”模式，名称“x_tunnel"，”默认“ ”SOCKS5“ ”127.0.0.1“ ”1080“
右键XX-NET图标，勾选”取消全局代理“
SwitchyOmega插件切换至”x_tunnel"全局代理模式

日志分别如下：
 [DEBUG] remove conn_id:6
---------------------------------------------------------------------------------
 [DEBUG] Conn session: conn:7 stop:system reset
---------------------------------------------------------------------------------
 [INFO] roundtrip port:6666 thread exit
 [DEBUG] remove conn_id:2
 [INFO] use config_path:E:\XX-Net-3.2.5\data\x_tunnel\client.json
 [INFO] Use proxy:127.0.0.1:8087
 [DEBUG] remove conn_id:1
 [INFO] login_session time:492 msg:Success
 [INFO] Socks5 server listen:127.0.0.1:1080.
---------------------------------------------------------------------------------
 [DEBUG] socks5 auth num:1, list:00
 [ERROR] socks5 protocol error:error('recv fail',)
 [ERROR] Except stack:Traceback (most recent call last): File "E:\XX-Net3.2.5\code\default\x_tunnel\local\proxy_handler.py", line 131, in socks5_handler data = self.read_bytes(4) File "E:\XX-Net-3.2.5\code\default\x_tunnel\local\proxy_handler.py", line 74, in read_bytes raise socket.error("recv fail") error: recv fail
---------------------------------------------------------------------------------

实在是不明白哪做错了...求指教！

**Comment by Yoshiki5** [comment]
已找到解决方法了
结束迅雷的“XLServicePlatform”服务就好用了
发问之前就应该搜索一下的，打扰大家了。

**Comment by ugvf2009** [comment]
长姿势了，原来迅雷会对XXnet有影响。

**Comment by jzp820927** [comment]
迅雷不仅对 XX 有影响，对 SS 也有影响
