### ISSUE TITLE
centos下报错“start module gae_proxy fail:invalid syntax (socks.py)”

### ISSUE THREAD

**Issue by OMGZui** [XX-net/XX-Net#3899]
Python 2.6.6
XX-Net version:default
7月 19 06:20:40.34 - [INFO] import build-in openssl fail:ImportError('libffi.so.6: \xe6\x97\xa0\xe6\xb3\x95\xe6\x89\x93\xe5\xbc\x80\xe5\x85\xb1\xe4\xba\xab\xe5\xaf\xb9\xe8\xb1\xa1\xe6\x96\x87\xe4\xbb\xb6: \xe6\xb2\xa1\xe6\x9c\x89\xe9\x82\xa3\xe4\xb8\xaa\xe6\x96\x87\xe4\xbb\xb6\xe6\x88\x96\xe7\x9b\xae\xe5\xbd\x95',)
7月 19 06:20:40.35 - [INFO] start XX-Net 3.2.5
7月 19 06:20:40.35 - [DEBUG] start confirm_xxnet_exit
7月 19 06:20:40.35 - [DEBUG] good, xxnet:8087 cleared!
7月 19 06:20:40.35 - [DEBUG] good, xxnet:8085 clear!
7月 19 06:20:40.35 - [DEBUG] finished confirm_xxnet_exit
7月 19 06:20:40.37 - [ERROR] start module gae_proxy fail:invalid syntax (socks.py, line 213)
7月 19 06:20:40.37 - [ERROR] Except stack:Traceback (most recent call last):
  File "/opt/soft/XX-Net/code/default/launcher/module_init.py", line 37, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "/opt/soft/XX-Net/code/default/gae_proxy/start.py", line 13, in <module>
    import local.proxy as client
  File "/opt/soft/XX-Net/code/default/gae_proxy/local/proxy.py", line 97, in <module>
    import proxy_handler
  File "/opt/soft/XX-Net/code/default/gae_proxy/local/proxy_handler.py", line 54, in <module>
    import gae_handler
  File "/opt/soft/XX-Net/code/default/gae_proxy/local/gae_handler.py", line 65, in <module>
    from appids_manager import appid_manager
  File "/opt/soft/XX-Net/code/default/gae_proxy/local/appids_manager.py", line 11, in <module>
    import check_ip
  File "/opt/soft/XX-Net/code/default/gae_proxy/local/check_ip.py", line 50, in <module>
    import socks
  File "/opt/soft/XX-Net/code/default/python27/1.0/lib/noarch/socks.py", line 213
    if type not in {socket.SOCK_STREAM, socket.SOCK_DGRAM}:
                                      ^
SyntaxError: invalid syntax

7月 19 06:20:40.37 - [ERROR] launcher except:SyntaxError('invalid syntax', ('/opt/soft/XX-Net/code/default/python27/1.0/lib/noarch/socks.py', 213, 43, '        if type not in {socket.SOCK_STREAM, socket.SOCK_DGRAM}:\n'))
7月 19 06:20:40.37 - [ERROR] Except stack:Traceback (most recent call last):
  File "code/default/launcher/start.py", line 182, in <module>
  File "code/default/launcher/start.py", line 159, in main
  File "/opt/soft/XX-Net/code/default/launcher/module_init.py", line 98, in start_all_auto
    start(module)
  File "/opt/soft/XX-Net/code/default/launcher/module_init.py", line 37, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "/opt/soft/XX-Net/code/default/gae_proxy/start.py", line 13, in <module>
    import local.proxy as client
  File "/opt/soft/XX-Net/code/default/gae_proxy/local/proxy.py", line 97, in <module>
    import proxy_handler
  File "/opt/soft/XX-Net/code/default/gae_proxy/local/proxy_handler.py", line 54, in <module>
    import gae_handler
  File "/opt/soft/XX-Net/code/default/gae_proxy/local/gae_handler.py", line 65, in <module>
    from appids_manager import appid_manager
  File "/opt/soft/XX-Net/code/default/gae_proxy/local/appids_manager.py", line 11, in <module>
    import check_ip
  File "/opt/soft/XX-Net/code/default/gae_proxy/local/check_ip.py", line 50, in <module>
    import socks
  File "/opt/soft/XX-Net/code/default/python27/1.0/lib/noarch/socks.py", line 213
    if type not in {socket.SOCK_STREAM, socket.SOCK_DGRAM}:
                                      ^
SyntaxError: invalid syntax

**Comment by yeahwu** [comment]
这个是python版本太低了。不支持python2.6的了
OMGZui <notifications@github.com>于2016年7月19日 周二21:22写道：

**Comment by jzp820927** [comment]
版本太低，语法错误
