### ISSUE TITLE
mac

### ISSUE THREAD

**Issue by sungerk** [XX-net/XX-Net#3924]
2016-07-23 13:05:47,809 - root - INFO - set proxy to http://127.0.0.1:8087
2016-07-23 13:05:47,811 - root - INFO - ============ Begin upload ============
2016-07-23 13:05:47,811 - root - INFO - appid:sunger-appid
2016-07-23 13:05:47,834 - root - INFO - Send: /api/appversion/rollback, params={'version': '1', 'app_id': 'sunger-appid'}
2016-07-23 13:05:49,701 - root - ERROR - upload fail:EOFError('EOF when reading a line',)
Traceback (most recent call last):
File "/Users/sunger/Downloads/XX-Net-3.1.19/code/3.2.5/gae_proxy/server/uploader.py", line 70, in upload
result = appcfg.AppCfgApp(['appcfg', 'rollback', dirname ]).Run()
File "/Users/sunger/Downloads/XX-Net-3.1.19/code/3.2.5/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 2951, in Run
self.action(self)
File "/Users/sunger/Downloads/XX-Net-3.1.19/code/3.2.5/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 5044, in __call__
return method()
File "/Users/sunger/Downloads/XX-Net-3.1.19/code/3.2.5/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 4397, in Rollback
self._Rollback()
File "/Users/sunger/Downloads/XX-Net-3.1.19/code/3.2.5/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 4442, in _Rollback
appversion.Rollback(force_rollback)
File "/Users/sunger/Downloads/XX-Net-3.1.19/code/3.2.5/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 2362, in Rollback
force_rollback='1' if force_rollback else '0')
File "/Users/sunger/Downloads/XX-Net-3.1.19/code/3.2.5/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 1696, in Send
result = self.rpcserver.Send(url, payload=payload, **kwargs)
File "/Users/sunger/Downloads/XX-Net-3.1.19/code/3.2.5/gae_proxy/server/lib/google/appengine/tools/appengine_rpc_httplib2.py", line 241, in Send
self._Authenticate(self.http, auth_errors[0] > 0)
File "/Users/sunger/Downloads/XX-Net-3.1.19/code/3.2.5/gae_proxy/server/lib/google/appengine/tools/appengine_rpc_httplib2.py", line 459, in _Authenticate
self.credentials = tools.run_flow(flow, self.storage, self.flags)
File "/Users/sunger/Downloads/XX-Net-3.1.19/code/3.2.5/gae_proxy/server/lib/oauth2client/util.py", line 137, in positional_wrapper
return wrapped(*args, **kwargs)
File "/Users/sunger/Downloads/XX-Net-3.1.19/code/3.2.5/gae_proxy/server/lib/oauth2client/tools.py", line 222, in run_flow
code = input('Enter verification code: ').strip()
EOFError: EOF when reading a line
2016-07-23 13:05:49,703 - root - INFO - Retry 1 time...
2016-07-23 13:05:49,722 - root - INFO - Send: /api/appversion/rollback, params={'version': '1', 'app_id': 'sunger-appid'}
2016-07-23 13:05:50,153 - root - ERROR - upload fail:EOFError('EOF when reading a line',)
Traceback (most recent call last):
File "/Users/sunger/Downloads/XX-Net-3.1.19/code/3.2.5/gae_proxy/server/uploader.py", line 70, in upload
result = appcfg.AppCfgApp(['appcfg', 'rollback', dirname ]).Run()
File "/Users/sunger/Downloads/XX-Net-3.1.19/code/3.2.5/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 2951, in Run
self.action(self)
File "/Users/sunger/Downloads/XX-Net-3.1.19/code/3.2.5/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 5044, in __call__
return method()
File "/Users/sunger/Downloads/XX-Net-3.1.19/code/3.2.5/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 4397, in Rollback
self._Rollback()
File "/Users/sunger/Downloads/XX-Net-3.1.19/code/3.2.5/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 4442, in _Rollback
appversion.Rollback(force_rollback)
File "/Users/sunger/Downloads/XX-Net-3.1.19/code/3.2.5/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 2362, in Rollback
force_rollback='1' if force_rollback else '0')
File "/Users/sunger/Downloads/XX-Net-3.1.19/code/3.2.5/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 1696, in Send
result = self.rpcserver.Send(url, payload=payload, **kwargs)
File "/Users/sunger/Downloads/XX-Net-3.1.19/code/3.2.5/gae_proxy/server/lib/google/appengine/tools/appengine_rpc_httplib2.py", line 241, in Send
self._Authenticate(self.http, auth_errors[0] > 0)
File "/Users/sunger/Downloads/XX-Net-3.1.19/code/3.2.5/gae_proxy/server/lib/google/appengine/tools/appengine_rpc_httplib2.py", line 459, in _Authenticate
self.credentials = tools.run_flow(flow, self.storage, self.flags)
File "/Users/sunger/Downloads/XX-Net-3.1.19/code/3.2.5/gae_proxy/server/lib/oauth2client/util.py", line 137, in positional_wrapper
return wrapped(*args, **kwargs)
File "/Users/sunger/Downloads/XX-Net-3.1.19/code/3.2.5/gae_proxy/server/lib/oauth2client/tools.py", line 222, in run_flow
code = input('Enter verification code: ').strip()
EOFError: EOF when reading a line
2016-07-23 13:05:50,153 - root - INFO - Retry 2 time...
2016-07-23 13:05:51,175 - root - INFO - Send: /api/appversion/rollback, params={'version': '1', 'app_id': 'sunger-appid'}
2016-07-23 13:05:51,602 - root - ERROR - upload fail:EOFError('EOF when reading a line',)
Traceback (most recent call last):
File "/Users/sunger/Downloads/XX-Net-3.1.19/code/3.2.5/gae_proxy/server/uploader.py", line 70, in upload
result = appcfg.AppCfgApp(['appcfg', 'rollback', dirname ]).Run()
File "/Users/sunger/Downloads/XX-Net-3.1.19/code/3.2.5/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 2951, in Run
self.action(self)
File "/Users/sunger/Downloads/XX-Net-3.1.19/code/3.2.5/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 5044, in __call__
return method()
File "/Users/sunger/Downloads/XX-Net-3.1.19/code/3.2.5/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 4397, in Rollback
self._Rollback()
File "/Users/sunger/Downloads/XX-Net-3.1.19/code/3.2.5/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 4442, in _Rollback
appversion.Rollback(force_rollback)
File "/Users/sunger/Downloads/XX-Net-3.1.19/code/3.2.5/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 2362, in Rollback
force_rollback='1' if force_rollback else '0')
File "/Users/sunger/Downloads/XX-Net-3.1.19/code/3.2.5/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 1696, in Send
result = self.rpcserver.Send(url, payload=payload, **kwargs)
File "/Users/sunger/Downloads/XX-Net-3.1.19/code/3.2.5/gae_proxy/server/lib/google/appengine/tools/appengine_rpc_httplib2.py", line 241, in Send
self._Authenticate(self.http, auth_errors[0] > 0)
File "/Users/sunger/Downloads/XX-Net-3.1.19/code/3.2.5/gae_proxy/server/lib/google/appengine/tools/appengine_rpc_httplib2.py", line 459, in _Authenticate
self.credentials = tools.run_flow(flow, self.storage, self.flags)
File "/Users/sunger/Downloads/XX-Net-3.1.19/code/3.2.5/gae_proxy/server/lib/oauth2client/util.py", line 137, in positional_wrapper
return wrapped(*args, **kwargs)
File "/Users/sunger/Downloads/XX-Net-3.1.19/code/3.2.5/gae_proxy/server/lib/oauth2client/tools.py", line 222, in run_flow
code = input('Enter verification code: ').strip()
EOFError: EOF when reading a line
2016-07-23 13:05:51,602 - root - INFO - Retry 3 time...
2016-07-23 13:05:53,603 - root - INFO - =======================
2016-07-23 13:05:53,603 - root - INFO - Deploy failed appid list:
2016-07-23 13:05:53,604 - root - INFO - - sunger-appid
2016-07-23 13:05:53,604 - root - INFO - == END ==

**Comment by jzp820927** [comment]
你这个是在 部署服务端？

**Comment by sungerk** [comment]
部署失败

**Comment by jzp820927** [comment]
没有 mac 机器，不能确定问题
