### ISSUE TITLE
最近在深度系统上有点问题

### ISSUE THREAD

**Issue by sonichy** [XX-net/XX-Net#3963]
可以翻墙，但是http://localhost:8085/打不开。
 ./start.sh

7月 29 19:55:32.47 - [INFO] start XX-Net get_version_fail
7月 29 19:55:32.47 - [DEBUG] start confirm_xxnet_exit
7月 29 19:55:32.47 - [DEBUG] <0>: try to terminate xxnet:8087
7月 29 19:55:33.48 - [DEBUG] <1>: try to terminate xxnet:8087
7月 29 19:55:34.48 - [DEBUG] <2>: try to terminate xxnet:8087
7月 29 19:55:35.48 - [DEBUG] <3>: try to terminate xxnet:8087
7月 29 19:55:36.49 - [DEBUG] <4>: try to terminate xxnet:8087
7月 29 19:55:37.49 - [DEBUG] <5>: try to terminate xxnet:8087
7月 29 19:55:38.49 - [DEBUG] <6>: try to terminate xxnet:8087
7月 29 19:55:39.50 - [DEBUG] <7>: try to terminate xxnet:8087
7月 29 19:55:40.50 - [DEBUG] <8>: try to terminate xxnet:8087
7月 29 19:55:41.50 - [DEBUG] <9>: try to terminate xxnet:8087
7月 29 19:55:42.50 - [DEBUG] <10>: try to terminate xxnet:8087
7月 29 19:55:43.51 - [DEBUG] <11>: try to terminate xxnet:8087
7月 29 19:55:44.51 - [DEBUG] <12>: try to terminate xxnet:8087
7月 29 19:55:45.51 - [DEBUG] <13>: try to terminate xxnet:8087
7月 29 19:55:46.51 - [DEBUG] <14>: try to terminate xxnet:8087
7月 29 19:55:47.52 - [DEBUG] <15>: try to terminate xxnet:8087
7月 29 19:55:48.52 - [DEBUG] <16>: try to terminate xxnet:8087
7月 29 19:55:49.52 - [DEBUG] <17>: try to terminate xxnet:8087
7月 29 19:55:50.53 - [DEBUG] <18>: try to terminate xxnet:8087
7月 29 19:55:51.53 - [DEBUG] <19>: try to terminate xxnet:8087
7月 29 19:55:52.53 - [DEBUG] <20>: try to terminate xxnet:8087
7月 29 19:55:53.54 - [DEBUG] <21>: try to terminate xxnet:8087
7月 29 19:55:54.54 - [DEBUG] <22>: try to terminate xxnet:8087
7月 29 19:55:55.54 - [DEBUG] <23>: try to terminate xxnet:8087
7月 29 19:55:56.54 - [DEBUG] <24>: try to terminate xxnet:8087
7月 29 19:55:57.55 - [DEBUG] <25>: try to terminate xxnet:8087
7月 29 19:55:58.55 - [DEBUG] <26>: try to terminate xxnet:8087
7月 29 19:55:59.55 - [DEBUG] <27>: try to terminate xxnet:8087
7月 29 19:56:00.56 - [DEBUG] <28>: try to terminate xxnet:8087
7月 29 19:56:01.56 - [DEBUG] <29>: try to terminate xxnet:8087
7月 29 19:56:02.56 - [DEBUG] good, xxnet:8085 clear!
7月 29 19:56:02.56 - [DEBUG] finished confirm_xxnet_exit
7月 29 19:56:02.78 - [DEBUG] network is ok, cost:120 ms
7月 29 19:56:02.79 - [INFO] SSL use version:TLSv1
7月 29 19:56:02.79 - [INFO] load ip range file:/media/administrator/软件/NET/翻墙/XX-Net-2.9.6/gae_proxy/local/ip_range.txt
7月 29 19:56:02.83 - [INFO] load google ip_list num:1073, gws num:1073
7月 29 19:56:02.86 - [DEBUG] ## GAEProxy set keep_running: True
7月 29 19:56:02.86 - [INFO] ------------------------------------------------------
7月 29 19:56:02.86 - [INFO] Python Version     : 2.7.11+
7月 29 19:56:02.86 - [INFO] OS                 : Dist:debian; Version:8.0; ID:
7月 29 19:56:02.86 - [INFO] Listen Address     : 127.0.0.1:8087
7月 29 19:56:02.86 - [INFO] GAE APPID          : celestial-now-128701
7月 29 19:56:02.86 - [INFO] Pac Server         : http://127.0.0.1:8086/proxy.pac
7月 29 19:56:02.86 - [INFO] ------------------------------------------------------
7月 29 19:56:02.89 - [WARNING] please install *libnss3-tools* package to import GoAgent root ca
7月 29 19:56:02.89 - [WARNING] please install *libnss3-tools* package to import GoAgent root ca
7月 29 19:56:02.89 - [ERROR] bind to 127.0.0.1:8087 fail
Exception in thread Thread-54:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/media/administrator/软件/NET/翻墙/XX-Net-2.9.6/gae_proxy/start.py", line 19, in main
    client.main()
  File "/media/administrator/软件/NET/翻墙/XX-Net-2.9.6/gae_proxy/local/proxy.py", line 236, in main
    proxy_daemon = simple_http_server.HTTPServer((config.LISTEN_IP, config.LISTEN_PORT), proxy_handler.GAEProxyHandler)
  File "/media/administrator/软件/NET/翻墙/XX-Net-2.9.6/python27/1.0/lib/noarch/simple_http_server.py", line 259, in __init__
    self.init_socket()
  File "/media/administrator/软件/NET/翻墙/XX-Net-2.9.6/python27/1.0/lib/noarch/simple_http_server.py", line 264, in init_socket
    self.add_listen(addr)
  File "/media/administrator/软件/NET/翻墙/XX-Net-2.9.6/python27/1.0/lib/noarch/simple_http_server.py", line 273, in add_listen
    raise e
error: [Errno 98] 地址已在使用

7月 29 19:56:11.37 - [INFO] scan_ip add ip:159.148.69.170 time:693
7月 29 19:56:11.66 - [INFO] scan_ip add ip:181.48.252.49 time:1064
7月 29 19:56:17.79 - [INFO] scan_ip add ip:41.201.128.101 time:767
7月 29 19:56:47.00 - [INFO] scan_ip add ip:194.24.134.106 time:514
7月 29 19:57:23.18 - [INFO] scan_ip add ip:216.147.171.230 time:758
7月 29 19:57:26.17 - [INFO] scan_ip add ip:177.101.143.215 time:817
7月 29 19:57:38.32 - [INFO] scan_ip add ip:41.201.128.99 time:666
7月 29 19:58:22.60 - [INFO] scan_ip add ip:61.238.239.88 time:403

**Comment by jzp820927** [comment]
7月 29 19:56:02.89 - [ERROR] bind to 127.0.0.1:8087 fail

端口绑定失败，你的 8087 端口被占用了
