### ISSUE TITLE
ubuntu下firefox设置

### ISSUE THREAD

**Issue by fccf** [XX-net/XX-Net#3964]
XX-Net Status:

sys-platform: x86_64, Linux-4.4.0-31-generic-x86_64-with-Ubuntu-16.04-xenial
os-system: Linux
os-version: #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016
os-release: 4.4.0-31-generic
os-detail: Dist:Ubuntu; Version:16.04; ID:xenial
architecture: 64bit,ELF
browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0
xxnet-version: 3.2.6

python-version: 2.7.11+
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:202 good:194
network-status: OK
connected-link: new:2 used:0
worker: h1:17 h2:1
scan-ip-thread-num: 50
ip-quality: 307
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by fccf** [comment]
连接不上google

**Comment by fccf** [comment]
日志信息：

7月 29 22:36:52.51 - [ERROR] Except stack:Traceback (most recent call last): File "/home/cfang/sft/XX-Net/code/default/gae_proxy/local/proxy_handler.py", line 296, in do_CONNECT_AGENT self.raw_requestline = self.rfile.readline(65537) File "/usr/lib/python2.7/socket.py", line 480, in readline data = self._sock.recv(self._rbufsize) File "/usr/lib/python2.7/ssl.py", line 752, in recv return self.read(buflen) File "/usr/lib/python2.7/ssl.py", line 639, in read v = self._sslobj.read(len) SSLError: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:1754)

7月 29 22:36:55.93 - [INFO] scan_ip add ip:217.75.205.214 time:707

7月 29 22:37:05.61 - [INFO] PAC from:127.0.0.1:43078 GET /proxy.pac

7月 29 22:37:10.91 - [DEBUG] ssl_closed 115.164.12.149

7月 29 22:37:10.91 - [DEBUG] 115.164.12.149 worker close:idle timeout

7月 29 22:37:11.02 - [DEBUG] ssl_closed 115.164.12.148

**Comment by jzp820927** [comment]
好提示，好像是证书问题，是不是没导入证书

**Comment by fccf** [comment]
按照教程上手动导入了，怎么查看导入成功没有呢？

**Comment by fccf** [comment]
firefox浏览器要先删除 cert8.db 文件，才能成功导入证书；
然后就能愉快的玩耍了

**Comment by fccf** [comment]
为什么就google不能用，facebook, you tube, twitter, gmail都可以用

**Comment by fccf** [comment]
在google+中 google app : search可以打开google搜索，

**Comment by jzp820927** [comment]
是不是因为是 http 非加密链接
