### ISSUE TITLE
openwrt上又出现问题

### ISSUE THREAD

**Issue by Vector2001** [XX-net/XX-Net#3969]
只能用/code/default/launcher/start.py启动之后，有一段时间都是正常运作的，但是刚刚突然开始报错，重启进程后ip清零，且过了不久又开始出现同样的报错信息

> [INFO]LOG_EXCEPT: scan_ip add ip:181.15.96.205 time:3713, Except:[Errno 5] Input/output error
 Traceback (most recent call last): File "/root/xxnet/code/default/python27/1.0/lib/noarch/xlog.py", line 110, in log self.set_console_color(console_color) File "/root/xxnet/code/default/python27/1.0/lib/noarch/xlog.py", line 78, in  self.set_console_color = lambda color: sys.stderr.write(color) IOError: [Errno 5] Input/output error

**Comment by jzp820927** [comment]
不明觉厉，等Y大来看看

**Comment by junegucas** [comment]
文件占用？
