### ISSUE TITLE
Mac 10.10.3 xx-net 1.14.6 ValueError: No such protocol

### ISSUE THREAD

**Issue by koalaroot** [XX-net/XX-Net#403]
/Volumes/Macintosh\ HD\ 2/Program\ Files/XX-Net-1.14.6/start.command ; exit;
launcher version: 1.4.0
May 13 21:31:11 - [INFO] use goagent version:3.1.49
May 13 21:31:11 - [INFO] goagent 3.1.49 started /Volumes/Macintosh HD 2/Program Files/XX-Net-1.14.6/goagent/3.1.49/start.py
May 13 21:31:11 - [INFO] load ip range file:/Volumes/Macintosh HD 2/Program Files/XX-Net-1.14.6/goagent/3.1.49/local/ip_range.txt
May 13 21:31:11 - [INFO] load google ip_list num:3000, gws num:3000
May 13 21:31:11 - [DEBUG] sort ip time:4
Traceback (most recent call last):
  File "/Volumes/Macintosh HD 2/Program Files/XX-Net-1.14.6/goagent/3.1.49/start.py", line 13, in <module>
    import local.proxy as goagent
  File "/Volumes/Macintosh HD 2/Program Files/XX-Net-1.14.6/goagent/3.1.49/local/proxy.py", line 83, in <module>
    import proxy_handler
  File "/Volumes/Macintosh HD 2/Program Files/XX-Net-1.14.6/goagent/3.1.49/local/proxy_handler.py", line 24, in <module>
    from connect_manager import https_manager,forwork_manager
  File "/Volumes/Macintosh HD 2/Program Files/XX-Net-1.14.6/goagent/3.1.49/local/connect_manager.py", line 616, in <module>
    https_manager = Https_connection_manager()
  File "/Volumes/Macintosh HD 2/Program Files/XX-Net-1.14.6/goagent/3.1.49/local/connect_manager.py", line 188, in __init__
    self.openssl_context = SSLConnection.context_builder(ca_certs=g_cacertfile)
  File "/Volumes/Macintosh HD 2/Program Files/XX-Net-1.14.6/goagent/3.1.49/local/openssl_wrap.py", line 119, in context_builder
    ssl_context = OpenSSL.SSL.Context(protocol_version)
  File "build/bdist.macosx-10.6-intel/egg/OpenSSL/SSL.py", line 261, in __init__
    # must be used.
ValueError: No such protocol

**Comment by xxnet** [comment]
发布了 V1.14.8 ，请测试是否解决了这个问题

2015-05-13 9:32 GMT-04:00 koalaroot <notifications@github.com>:

**Comment by sagexy** [comment]
还是没解决
launcher version: 1.4.0
May 14 09:57:57 - [INFO] module goagent version _ not exist
May 14 09:57:57 - [INFO] module goagent auto upgrade to version 3.1.49
May 14 09:57:57 - [INFO] module launcher version _ not exist
May 14 09:57:57 - [INFO] module launcher auto upgrade to version 1.4.0
May 14 09:57:57 - [INFO] module php_proxy version _ not exist
May 14 09:57:57 - [INFO] module php_proxy auto upgrade to version 1.0.0
May 14 09:57:58 - [INFO] use goagent version:3.1.49
May 14 09:57:58 - [INFO] goagent 3.1.49 started /Users/xy/App/XX-Net-1.14.8/goagent/3.1.49/start.py
May 14 09:57:58 - [INFO] load ip range file:/Users/xy/App/XX-Net-1.14.8/goagent/3.1.49/local/ip_range.txt
May 14 09:57:58 - [INFO] load google ip_list num:3000, gws num:3000
May 14 09:57:58 - [DEBUG] sort ip time:2
May 14 09:57:58 - [INFO] SSL use version:TLSv1_2
Traceback (most recent call last):
  File "/Users/xy/App/XX-Net-1.14.8/goagent/3.1.49/start.py", line 13, in <module>
    import local.proxy as goagent
  File "/Users/xy/App/XX-Net-1.14.8/goagent/3.1.49/local/proxy.py", line 83, in <module>
    import proxy_handler
  File "/Users/xy/App/XX-Net-1.14.8/goagent/3.1.49/local/proxy_handler.py", line 24, in <module>
    from connect_manager import https_manager,forwork_manager
  File "/Users/xy/App/XX-Net-1.14.8/goagent/3.1.49/local/connect_manager.py", line 616, in <module>
    https_manager = Https_connection_manager()
  File "/Users/xy/App/XX-Net-1.14.8/goagent/3.1.49/local/connect_manager.py", line 188, in __init__
    self.openssl_context = SSLConnection.context_builder(ca_certs=g_cacertfile)
  File "/Users/xy/App/XX-Net-1.14.8/goagent/3.1.49/local/openssl_wrap.py", line 130, in context_builder
    ssl_context = OpenSSL.SSL.Context(protocol_version)
  File "build/bdist.macosx-10.6-intel/egg/OpenSSL/SSL.py", line 261, in __init__
    # must be used.
ValueError: No such protocol

**Comment by Pd69bq** [comment]
我印象当中mac下苹果好像比较不推崇使用openssl

**Comment by xxnet** [comment]
为什么？

2015-05-14 15:55 GMT+08:00 Chris Baconham <notifications@github.com>:

**Comment by xxnet** [comment]
发新版 1.14.9 处理mac 10.10 无法工作

2015-05-14 16:50 GMT+08:00 Net XX <xxnet.dev@gmail.com>:

**Comment by cnccn** [comment]
@xxnet 目前使用1.14.2版，Mac OS X 10.10，没有出现上述问题，是不是与本来安了openssl有关？请问后续更新版本的SSL 更新具体是怎样的

**Comment by xxnet** [comment]
Mac 10.10 的OpenSSL 库中，比较奇怪的是提供了TLSv1.2 的接口，却无法使用，导致判断是否有效的机制有问题。

以后这类修改要作足够的测试才行。


在 2015年5月15日 下午7:36，cnccn <notifications@github.com>写道：

**Comment by cnccn** [comment]
@xxnet 对mac程序不熟悉，请教一下，xxnet调用的是系统自带的openssl么？还是作者封包到程序里的组件呢？我还以为我没有出现楼主的问题是因为homebrew里面安装了openssl

**Comment by xxnet** [comment]
目前的优先顺序是，先调用系统的openssl，再用封包里的openssl。

有问题怀疑是因为系统的openssl 适配不好。

在 2015年5月16日 下午12:33，cnccn <notifications@github.com>写道：
