### ISSUE TITLE
ubuntu安装以后无法连通本地的8085端口

### ISSUE THREAD

**Issue by wangmengyu** [XX-net/XX-Net#404]
查看了端口的使用情况并没有程序占用。
.shart.sh, 每次启动报错
想部署也部署不了。

**Comment by xxnet** [comment]
启动报错，请贴出报错内容

在 2015年5月13日 下午7:17，wangmengyu <notifications@github.com>写道：

**Comment by wangmengyu** [comment]
wealink@wealink-Vostro-3900:~/xx$ sudo ./start.sh
[sudo] password for wealink: 
get_launcher_version_from_config: 'NoneType' object has no attribute '__getitem__'
launcher version: 1.4.0
May 14 17:40:03 - [INFO] module goagent version _ not exist
Traceback (most recent call last):
  File "launcher/start.py", line 63, in <module>
    main()
  File "launcher/start.py", line 58, in main
    from start import main as launcher_main
  File "/home/wealink/xx/launcher/1.4.0/start.py", line 13, in <module>
    from gtk_tray import sys_tray
  File "/home/wealink/xx/launcher/1.4.0/gtk_tray.py", line 25, in <module>
    import module_init
  File "/home/wealink/xx/launcher/1.4.0/module_init.py", line 5, in <module>
    import config
  File "/home/wealink/xx/launcher/1.4.0/config.py", line 115, in <module>
    main()
  File "/home/wealink/xx/launcher/1.4.0/config.py", line 112, in main
    if recheck_module_path():
  File "/home/wealink/xx/launcher/1.4.0/config.py", line 92, in recheck_module_path
    set(["modules", module, "current_version"], current_version)
  File "/home/wealink/xx/launcher/1.4.0/config.py", line 54, in set
    _set(config, path, val)
  File "/home/wealink/xx/launcher/1.4.0/config.py", line 48, in _set
    if k0 not in m:
TypeError: argument of type 'NoneType' is not iterable
wealink@wealink-Vostro-3900:~/xx$

**Comment by wangmengyu** [comment]
我的UBUNTU 是14.04稳定版的. 不知道是不是依赖没有按装, 请大神指教啊.

**Comment by xxnet** [comment]
在Ubuntu14.04上，没有重现你的现象。

你能否试着查问题出在什么地方。
简单的方法如下：
把出错的行前面，增加print xxx，看问题出在哪里。

这两个地方：
File "/home/wealink/xx/launcher/1.4.0/config.py", line 54, in set
_set(config, path, val)
File "/home/wealink/xx/launcher/1.4.0/config.py", line 48, in _set
if k0 not in m:

把相关变量都打出来


在 2015年5月14日 下午5:44，wangmengyu <notifications@github.com>写道：
