### ISSUE TITLE
fedora24从fdzh源安装xx-net运行报错

### ISSUE THREAD

**Issue by zhaoyang017** [XX-net/XX-Net#4051]
8月 14 16:21:14.03 - [ERROR] ssl.wrap_socket(self.connection=<ssl.SSLSocket object at 0x7f0780339e60>) failed: [SSL: SSLV3_ALERT_BAD_CERTIFICATE] sslv3 alert bad certificate (_ssl.c:1754) path:www.twitter.com:443, errno:1
8月 14 16:21:14.03 - [ERROR] Except stack:Traceback (most recent call last):
  File "/usr/share/xx-net/gae_proxy/local/proxy_handler.py", line 211, in do_CONNECT_AGENT
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib64/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
  File "/usr/lib64/python2.7/ssl.py", line 756, in recv
    return self.read(buflen)
  File "/usr/lib64/python2.7/ssl.py", line 643, in read
    v = self._sslobj.read(len)
SSLError: [SSL: SSLV3_ALERT_BAD_CERTIFICATE] sslv3 alert bad certificate (_ssl.c:1754)

8月 14 16:21:14.03 - [ERROR] ssl.wrap_socket(self.connection=<ssl.SSLSocket object at 0x7f0780339320>) failed: [SSL: SSLV3_ALERT_BAD_CERTIFICATE] sslv3 alert bad certificate (_ssl.c:1754) path:www.twitter.com:443, errno:1
8月 14 16:21:14.03 - [ERROR] Except stack:Traceback (most recent call last):
  File "/usr/share/xx-net/gae_proxy/local/proxy_handler.py", line 211, in do_CONNECT_AGENT
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib64/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
  File "/usr/lib64/python2.7/ssl.py", line 756, in recv
    return self.read(buflen)
  File "/usr/lib64/python2.7/ssl.py", line 643, in read
    v = self._sslobj.read(len)
SSLError: [SSL: SSLV3_ALERT_BAD_CERTIFICATE] sslv3 alert bad certificate (_ssl.c:1754)

8月 14 16:21:14.03 - [ERROR] ssl.wrap_socket(self.connection=<ssl.SSLSocket object at 0x7f07803399b0>) failed: [SSL: SSLV3_ALERT_BAD_CERTIFICATE] sslv3 alert bad certificate (_ssl.c:1754) path:www.twitter.com:443, errno:1
8月 14 16:21:14.03 - [ERROR] Except stack:Traceback (most recent call last):
  File "/usr/share/xx-net/gae_proxy/local/proxy_handler.py", line 211, in do_CONNECT_AGENT
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib64/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
  File "/usr/lib64/python2.7/ssl.py", line 756, in recv
    return self.read(buflen)
  File "/usr/lib64/python2.7/ssl.py", line 643, in read
    v = self._sslobj.read(len)
SSLError: [SSL: SSLV3_ALERT_BAD_CERTIFICATE] sslv3 alert bad certificate (_ssl.c:1754)

**Comment by zhaoyang017** [comment]
更奇怪的是我配置好了代理一直提示 浏览器代理设置 错误 求助

**Comment by jzp820927** [comment]
好像是证书的问题，你就直接下载源码运行吧，反正也不麻烦。

**Comment by zhaoyang017** [comment]
@jzp820927 我下载源码也是证书问题，才直接从源安装的，按官方证书错误的解决办法手动导入自动生成的证书总是提示证书无效并且提示浏览器代理设置 错误

**Comment by jzp820927** [comment]
你的 python 是什么版本的

**Comment by zhaoyang017** [comment]
@jzp820927 Python 2.7.12  GCC 6.1.1 是版本问题吗

**Comment by jzp820927** [comment]
不确定，没遇到过，这种报错，如果是客户端没装安装，服务端应该不会报错。

**Comment by yan12125** [comment]
我遇到相同的問題，後來發現之前有導入舊的GoAgen XX-Nett證書到Firefox，刪除後再導入新證書即可

環境：
* Arch Linux x86_64
* Python 2.7.12
* OpenSSL 1.0.2j
* Firefox 49.0.1
* Arch官方的pyopenssl 16.1.0，XX-net裡的pyopenssl無法使用

**Comment by jzp820927** [comment]
证书问题一般都是情理不完整造成的
