### ISSUE TITLE
ubuntu下，./start XX-Net.desktop 失败 求指点

### ISSUE THREAD

**Issue by q54528** [XX-net/XX-Net#4084]
dd@ubuntu:~/下载/XX$ ./start XX-Net.desktop
Python 2.7.12
XX-Net version:default
XX-Net.desktop already exists
Traceback (most recent call last):
  File "code/default/launcher/start.py", line 37, in <module>
    from instances import xlog
  File "/home/dd/下载/XX/code/default/launcher/instances.py", line 12, in <module>
    xlog = Logger(file_name=log_file)
  File "/home/dd/下载/XX/code/default/python27/1.0/lib/noarch/xlog.py", line 35, in __init__
    self.set_file(file_name)
  File "/home/dd/下载/XX/code/default/python27/1.0/lib/noarch/xlog.py", line 90, in set_file
    self.log_fd = open(file_name, "w")
IOError: [Errno 13] Permission denied: '/home/dd/\xe4\xb8\x8b\xe8\xbd\xbd/XX/data/launcher/launcher.log'

Ubuntu 新手，求教怎么破

**Comment by jzp820927** [comment]
IOError: [Errno 13] Permission denied: '/home/dd/\xe4\xb8\x8b\xe8\xbd\xbd/XX/data/launcher/launcher.log'

好像是权限的问题。

**Comment by asd2003asd** [comment]
start文件右键属性把只读改成读写应该就可以了。

**Comment by q54528** [comment]
我root之后也没法修改，怪了。我的root方法：sudo su


2016-08-19 18:47 GMT+08:00 asd2003asd <notifications@github.com>:

**Comment by jzp820927** [comment]
看看是不是没有写入权限。

**Comment by Iensgh** [comment]
我的开启方法
python XX-Net-?.?.?/code/default/launcher/start.py

**Comment by asd2003asd** [comment]
我kali下可以直接改文件读写权限

**Comment by q54528** [comment]
ubuntu 开启没有图标，只有在终端的扫描IP，大家也是吗

**Comment by jzp820927** [comment]
能用就行了吧
