### ISSUE TITLE
求助。不知怎么了就用不了了。

### ISSUE THREAD

**Issue by cyang812** [XX-net/XX-Net#4121]
## 问题内容
1. 之前可用，不知是不是chrome更新还是怎么就用不了了。
2.提示一直都是请检查浏览器代理设置。
3. 试过重装chrome，重新使用xx-net，重新安装代理插件。

### 附加内容1
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.14388
os-system: Windows
os-version: 10.0.14388
os-release: 10
os-detail: Version:10-0; Build:14388; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36
xxnet-version: 3.2.6

python-version: 2.7.11
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:8 good:8
network-status: OK
connected-link: new:5 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 50
ip-quality: 9999
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

### 附加内容2
Aug 27 15:36:54.237 - [INFO] use config_path:F:\XX-Net\data\x_tunnel\client.json
Aug 27 15:36:54.237 - [INFO] Use proxy:127.0.0.1:8087
Aug 27 15:36:54.237 - [DEBUG] x-tunnel no account
Aug 27 15:36:54.237 - [WARNING] x-tunnel session not start
Aug 27 15:36:54.239 - [INFO] Socks5 server listen:127.0.0.1:1080.
Aug 27 15:38:31.750 - [DEBUG] socks5 auth num:1, list:00
Aug 27 15:38:31.750 - [ERROR] socks5 protocol error:error('recv fail',)
Aug 27 15:38:31.750 - [ERROR] Except stack:Traceback (most recent call last): File "F:\XX-Net\code\default\x_tunnel\local\proxy_handler.py", line 131, in socks5_handler data = self.read_bytes(4) File "F:\XX-Net\code\default\x_tunnel\local\proxy_handler.py", line 74, in read_bytes raise socket.error("recv fail") error: recv fail

**Comment by xiaoyan94** [comment]
14388……为什么我的还停留在10586……

**Comment by jzp820927** [comment]
IP 数量过少，试着删除 data 目录，重新运行 XXNET

**Comment by cyang812** [comment]
IP数不是9999吗？不少了啊。试过删除目录后，重新运行。还是一样的结果

**Comment by wenliyang** [comment]
gws-ip-num: total:8 good:8

8个IP，太少了

**Comment by cyang812** [comment]
IP少怎么办？删除data目录重新运行也不行啊。

**Comment by jzp820927** [comment]
如果扫描不到IP，请检查你的网络环境，你是什么带宽？

**Comment by cyang812** [comment]
校园网，100M.如果是联通VPN10M.
两种情况IP都最多不超多8

**Comment by cyang812** [comment]
可以了。今天重新扫描IP，数量可以达到30多。现在正常了。

**Comment by jzp820927** [comment]
校园网，完全可以用 ipv6 嘛

**Comment by cyang812** [comment]
今天打开，IP可扫描到300多，但还是提示检查浏览器代理设置，代理插件这边应该没问题，不知道又怎么了。
另外，IPV6怎么用，有线接入是，学校分配的还是IPV4，只有WIFI才有给IPV6。

## 错误报告
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.14388
os-system: Windows
os-version: 10.0.14388
os-release: 10
os-detail: Version:10-0; Build:14388; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36
xxnet-version: 3.2.6

python-version: 2.7.11
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:341 good:293
network-status: OK
connected-link: new:2 used:0
worker: h1:7 h2:0
scan-ip-thread-num: 50
ip-quality: 155
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by jzp820927** [comment]
估计是不是你们学校的网络有什么限制，如果分配的是 IPV4，不是 IPV6，肯定用不了 IPV6
