### ISSUE TITLE
xxnet部署appid失败

### ISSUE THREAD

**Issue by pixiang** [XX-net/XX-Net#4200]
点击上面的 ↑Preview↑ 来查看格式化后的说明。
失败日志如下：
2016-09-15 10:34:30,894 - root - INFO - set proxy to http://127.0.0.1:8087
2016-09-15 10:34:30,904 - root - INFO - ============ Begin upload ============
2016-09-15 10:34:30,904 - root - INFO - appid:xxnet-goagent-141605
2016-09-15 10:34:30,923 - root - INFO - Send: /api/appversion/rollback, params={'version': '1', 'app_id': 'xxnet-goagent-141605'}
2016-09-15 10:35:13,243 - root - ERROR - upload fail:error(10060, '')
Traceback (most recent call last):
File "E:\others\XX-Net-2.9.6\XX-Net-2.9.6\gae_proxy\server\uploader.py", line 70, in upload
result = appcfg.AppCfgApp(['appcfg', 'rollback', dirname ]).Run()
File "E:\others\XX-Net-2.9.6\XX-Net-2.9.6\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 2951, in Run
self.action(self)
File "E:\others\XX-Net-2.9.6\XX-Net-2.9.6\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 5044, in __call__
return method()
File "E:\others\XX-Net-2.9.6\XX-Net-2.9.6\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 4397, in Rollback
self._Rollback()
File "E:\others\XX-Net-2.9.6\XX-Net-2.9.6\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 4442, in _Rollback
appversion.Rollback(force_rollback)
File "E:\others\XX-Net-2.9.6\XX-Net-2.9.6\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 2362, in Rollback
force_rollback='1' if force_rollback else '0')
File "E:\others\XX-Net-2.9.6\XX-Net-2.9.6\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 1696, in Send
result = self.rpcserver.Send(url, payload=payload, **kwargs)
File "E:\others\XX-Net-2.9.6\XX-Net-2.9.6\gae_proxy\server\lib\google\appengine\tools\appengine_rpc_httplib2.py", line 247, in Send
url, method=method, body=payload, headers=headers)
File "E:\others\XX-Net-2.9.6\XX-Net-2.9.6\gae_proxy\server\lib\httplib2\__init__.py", line 1593, in request
(response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
File "E:\others\XX-Net-2.9.6\XX-Net-2.9.6\gae_proxy\server\lib\httplib2\__init__.py", line 1341, in _request
(response, content) = self._conn_request(conn, request_uri, method, body, headers)
File "E:\others\XX-Net-2.9.6\XX-Net-2.9.6\gae_proxy\server\lib\httplib2\__init__.py", line 1315, in _conn_request
conn.connect()
File "E:\others\XX-Net-2.9.6\XX-Net-2.9.6\gae_proxy\server\lib\httplib2\__init__.py", line 1062, in connect
raise socket.error, msg
error: [Errno 10060] 
2016-09-15 10:35:13,249 - root - INFO - Retry 1 time...
2016-09-15 10:35:13,265 - root - INFO - Send: /api/appversion/rollback, params={'version': '1', 'app_id': 'xxnet-goagent-141605'}
2016-09-15 10:35:55,305 - root - ERROR - upload fail:error(10060, '')
Traceback (most recent call last):
File "E:\others\XX-Net-2.9.6\XX-Net-2.9.6\gae_proxy\server\uploader.py", line 70, in upload
result = appcfg.AppCfgApp(['appcfg', 'rollback', dirname ]).Run()
File "E:\others\XX-Net-2.9.6\XX-Net-2.9.6\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 2951, in Run
self.action(self)
File "E:\others\XX-Net-2.9.6\XX-Net-2.9.6\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 5044, in __call__
return method()
File "E:\others\XX-Net-2.9.6\XX-Net-2.9.6\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 4397, in Rollback
self._Rollback()
File "E:\others\XX-Net-2.9.6\XX-Net-2.9.6\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 4442, in _Rollback
appversion.Rollback(force_rollback)
File "E:\others\XX-Net-2.9.6\XX-Net-2.9.6\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 2362, in Rollback
force_rollback='1' if force_rollback else '0')
File "E:\others\XX-Net-2.9.6\XX-Net-2.9.6\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 1696, in Send
result = self.rpcserver.Send(url, payload=payload, **kwargs)
File "E:\others\XX-Net-2.9.6\XX-Net-2.9.6\gae_proxy\server\lib\google\appengine\tools\appengine_rpc_httplib2.py", line 247, in Send
url, method=method, body=payload, headers=headers)
File "E:\others\XX-Net-2.9.6\XX-Net-2.9.6\gae_proxy\server\lib\httplib2\__init__.py", line 1593, in request
(response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
File "E:\others\XX-Net-2.9.6\XX-Net-2.9.6\gae_proxy\server\lib\httplib2\__init__.py", line 1341, in _request
(response, content) = self._conn_request(conn, request_uri, method, body, headers)
File "E:\others\XX-Net-2.9.6\XX-Net-2.9.6\gae_proxy\server\lib\httplib2\__init__.py", line 1315, in _conn_request
conn.connect()
File "E:\others\XX-Net-2.9.6\XX-Net-2.9.6\gae_proxy\server\lib\httplib2\__init__.py", line 1062, in connect
raise socket.error, msg
error: [Errno 10060] 
2016-09-15 10:35:55,306 - root - INFO - Retry 2 time...
2016-09-15 10:35:56,344 - root - INFO - Send: /api/appversion/rollback, params={'version': '1', 'app_id': 'xxnet-goagent-141605'}
2016-09-15 10:36:38,348 - root - ERROR - upload fail:error(10060, '')
Traceback (most recent call last):
File "E:\others\XX-Net-2.9.6\XX-Net-2.9.6\gae_proxy\server\uploader.py", line 70, in upload
result = appcfg.AppCfgApp(['appcfg', 'rollback', dirname ]).Run()
File "E:\others\XX-Net-2.9.6\XX-Net-2.9.6\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 2951, in Run
self.action(self)
File "E:\others\XX-Net-2.9.6\XX-Net-2.9.6\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 5044, in __call__
return method()
File "E:\others\XX-Net-2.9.6\XX-Net-2.9.6\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 4397, in Rollback
self._Rollback()
File "E:\others\XX-Net-2.9.6\XX-Net-2.9.6\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 4442, in _Rollback
appversion.Rollback(force_rollback)
File "E:\others\XX-Net-2.9.6\XX-Net-2.9.6\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 2362, in Rollback
force_rollback='1' if force_rollback else '0')
File "E:\others\XX-Net-2.9.6\XX-Net-2.9.6\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 1696, in Send
result = self.rpcserver.Send(url, payload=payload, **kwargs)
File "E:\others\XX-Net-2.9.6\XX-Net-2.9.6\gae_proxy\server\lib\google\appengine\tools\appengine_rpc_httplib2.py", line 247, in Send
url, method=method, body=payload, headers=headers)
File "E:\others\XX-Net-2.9.6\XX-Net-2.9.6\gae_proxy\server\lib\httplib2\__init__.py", line 1593, in request
(response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
File "E:\others\XX-Net-2.9.6\XX-Net-2.9.6\gae_proxy\server\lib\httplib2\__init__.py", line 1341, in _request
(response, content) = self._conn_request(conn, request_uri, method, body, headers)
File "E:\others\XX-Net-2.9.6\XX-Net-2.9.6\gae_proxy\server\lib\httplib2\__init__.py", line 1315, in _conn_request
conn.connect()
File "E:\others\XX-Net-2.9.6\XX-Net-2.9.6\gae_proxy\server\lib\httplib2\__init__.py", line 1062, in connect
raise socket.error, msg
error: [Errno 10060] 
2016-09-15 10:36:38,349 - root - INFO - Retry 3 time...
2016-09-15 10:36:40,365 - root - INFO - =======================
2016-09-15 10:36:40,367 - root - INFO - Deploy failed appid list:
2016-09-15 10:36:40,367 - root - INFO - - xxnet-goagent-141605
2016-09-15 10:36:40,368 - root - INFO - == END ==
---
## 提问之前
1. 首先请确认你使用的是[最新版本](https://github.com/XX-net/XX-Net/blob/master/code/default/download.md)，你的问题可能已经在新版本里解决了。
2. 请阅读[故障速查手册](https://github.com/XX-net/XX-Net/wiki/故障速查手册)，大部分问题都能在这里找到答案。
3. 请在 [issue](https://github.com/XX-net/XX-Net/issues) 区搜索有无类似的问题。

---
## 问题内容
1. 请尽可能详细的描述你的问题，如问题能重现请附带重现方法。
2. 当你的问题得到解决后，记得关闭问题。
3. 可以参考[示例 issue](https://github.com/XX-net/XX-Net/issues/3193)。

### 附加内容
1. 提交 issue 时请贴出诊断信息、GAEProxy 日志，以便开发者和其他用户更好地帮助你。
2. 如果是部署相关的问题，请一并附带部署日志。
3. 如果你有任何与这个问题有关的信息，也请一并发出来。
4. 如果你没有提供诊断信息，我们很可能会忽略这个问题。

#### 获取诊断信息
点击[状态页](http://127.0.0.1:8085)下方的【诊断信息】按钮，如没有这个按钮，请将显示详细信息从【OFF】改为【ON】。

#### 获取日志
打开 [GAEProxy 日志页](http://127.0.0.1:8085/?module=gae_proxy&menu=logging) 复制网页右边部分的内容。

---
请在阅读完后点击上边的 Write，删除说明内容，然后描述你遇到的问题。

**Comment by jzp820927** [comment]
请先测试一下，GAE 代理是否可以正常使用，再部署

**Comment by pixiang** [comment]
hi，@jzp820927 ，怎么看GAE代理使用？下面是我的诊断信息
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.10586
os-system: Windows
os-version: 10.0.10586
os-release: 10
os-detail: Version:10-0; Build:10586; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36
xxnet-version: 2.9.6

python-version: 2.7.11

ipv6-status: 0
gws-ip-num: total:311 good:234
network-status: OK
connected-link: new:5 used:1
scan-ip-thread-num: 0
ip-quality: 348
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: true
Appids_Not_Exist: true
Using_Public_Appid: true

**Comment by wenliyang** [comment]
请升级到最新版本再部署

**Comment by jzp820927** [comment]
就是设置系统代理为 XX，任何打开一个被墙的网站，如果能正常打开，就说明 GAE 工作正常

**Comment by pixiang** [comment]
@jzp820927 ，能正常打开被墙的页面。现在还有哪出问题了

**Comment by jzp820927** [comment]
如果 GAE 代理正常，应该可以部署服务端

**Comment by pixiang** [comment]
@jzp820927 @wenliyang 我点击了自动升级到稳定版，然后就一直显示等待图标

**Comment by wenliyang** [comment]
手动下载，不要用软件的升级功能
https://github.com/XX-net/XX-Net/releases/tag/3.2.6

**Comment by jzp820927** [comment]
自动升级不行，就手动下载吧，我都是手动下载，没感觉有多麻烦。
