### ISSUE TITLE
ubuntu16.04使用xx-net遇到些问题

### ISSUE THREAD

**Issue by Nemokang** [XX-net/XX-Net#4289]
使用./start 命令后显示chrom不能再root下运行，然后按照百度的方法，在chromium-browser里面添加了
--user-data-dir(好像是这个，不记得了)接着就可以在运行./start 的时候打开chromium了（这里运行的时候没有在桌面什么城快捷方式，我用ubuntu14.04的时候是会自动生成的）

配置了一番后，可以正常使用了，但是关闭terminal的话，就不能继续使用了。

然后就使用default里面的xx_net.sh开启后台嘛，这样就能关闭terminal了。

这时的问题就是，我用命令行运行start或者xx_net.sh会弹出谷歌xxnet的配置网页，我的插件啊书签啊都是同步在这个窗口里面，如果我关闭这个窗口，我就不能继续科学上网了（新打开的chromium窗口没有插件，也没有书签什么的，xxnet没有在上面生效）

希望解决这个关闭窗口后就不能再使用xxnet的问题，要是上面那个快捷方式未生成的问题能解决就最好了。

**Comment by Nemokang** [comment]
![Uploading Screenshot from 2016-09-29 17-17-24.jpg…]()

**Comment by jzp820927** [comment]
你是用的  xxnet 和 chrome 的整合包麽？还是单独的 XXNET？如果是 单独的 XXNET ，应该不会影响到你 chrome 浏览器的书签啊，这是2个独立的软件，应该没有联系的

**Comment by Nemokang** [comment]
我用的单独的xxnet
只能以root权限运行./start ，然后运行后会以root权限打开chrom。
我只能在这个窗口翻墙，如果我右键任务栏的chrom快捷方式，新建一个窗口，这个窗口上就不能翻墙

**Comment by jzp820927** [comment]
你是用的 omega 插件？还是直接设置系统代理？

**Comment by Nemokang** [comment]
omega插件。
第一次配置的时候，我先运行./start，然后弹出了root权限下的chromium窗口，我在这个窗口里配置了omega。
然后就发现，只有这种情况下打开的窗口有omega插件，我平时自己打开是没有的

**Comment by jzp820927** [comment]
这个不科学啊，是不是一个登录了 google 账号，一个没登录？
或者笨一点的版本，你在那个打开没有插件的 chromium 下面再安装一次 omega 插件？

**Comment by Nemokang** [comment]
哈哈哈，超神奇，两个窗口我都装了插件试过，那个通过快捷方式打开的新chromium窗口不能翻墙的，显示不是私密连接什么的。似乎只能想办法怎么用root权限打开chromium了

**Comment by linhua55** [comment]
”显示不是私密连接什么的“  ，，这个提示 说明没有安装证书

**Comment by jzp820927** [comment]
你那个没插件的是不是用的隐私模式

**Comment by lusilong** [comment]
alex@alex:~/xxNet$ sudo ./start 
XX-Net version:4.5.3
2021-02-20 21:41:47.411 [launcher][INFO] use build-in openssl lib
2021-02-20 21:41:47.509 [launcher][INFO] Using PyGObject as the GUI Backend.
2021-02-20 21:41:47.597 [launcher][INFO] Gtk.StatusIcon used.
2021-02-20 21:41:47.598 [launcher][INFO] start XX-Net 4.5.3
2021-02-20 21:41:47.598 [launcher][DEBUG] start confirm_xxnet_exit
2021-02-20 21:42:17.630 [launcher][DEBUG] good, xxnet:8085 clear!
2021-02-20 21:42:17.631 [launcher][DEBUG] finished confirm_xxnet_exit
2021-02-20 21:42:17.704 [gae_proxy][INFO] ------------------------------------------------------
2021-02-20 21:42:17.705 [gae_proxy][INFO] Python Version     : 3.5.2
2021-02-20 21:42:17.705 [gae_proxy][INFO] OS                 : Ubuntu

2021-02-20 21:42:17.705 [gae_proxy][INFO] Listen Address     : 127.0.0.1:8087
2021-02-20 21:42:17.705 [gae_proxy][INFO] Using public APPID
2021-02-20 21:42:17.705 [gae_proxy][INFO] ------------------------------------------------------
2021-02-20 21:42:17.707 [gae_proxy][DEBUG] Importing CA
2021-02-20 21:42:17.755 [gae_proxy][INFO] Database $HOME/.pki/nssdb cert exist
2021-02-20 21:42:17.755 [gae_proxy][DEBUG] Begin importing CA to Firefox
2021-02-20 21:42:17.756 [gae_proxy][INFO] Removing old cert to Firefox in /home/alex/.mozilla/firefox/cqf2ve25.default
GoAgent XX-Net - GoAgent                                     C,,  
2021-02-20 21:42:17.761 [gae_proxy][INFO] Add new cert to Firefox in /home/alex/.mozilla/firefox/cqf2ve25.default
2021-02-20 21:42:17.765 [gae_proxy][INFO] SSL use version:SSLv1
2021-02-20 21:42:17.766 [gae_proxy][INFO] OpenSSL support alpn
2021-02-20 21:42:17.766 [gae_proxy][INFO] load ip range file:/home/alex/xxNet/code/default/gae_proxy/local/ip_range.txt
2021-02-20 21:42:17.771 [gae_proxy][INFO] SSL use version:SSLv1
2021-02-20 21:42:17.772 [gae_proxy][ERROR] bind to b'127.0.0.1':8087 fail:OSError(98, '地址已在使用')
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/home/alex/xxNet/code/default/lib/noarch/simple_http_server.py", line 466, in add_listen
    sock.bind(addr)
OSError: [Errno 98] 地址已在使用

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/alex/xxNet/code/default/gae_proxy/local/__init__.py", line 12, in start
    proxy.main(args)
  File "/home/alex/xxNet/code/default/gae_proxy/local/proxy.py", line 139, in main
    addresses, proxy_handler.GAEProxyHandler, logger=xlog)
  File "/home/alex/xxNet/code/default/lib/noarch/simple_http_server.py", line 430, in __init__
    self.init_socket()
  File "/home/alex/xxNet/code/default/lib/noarch/simple_http_server.py", line 449, in init_socket
    self.add_listen((ip, port))
  File "/home/alex/xxNet/code/default/lib/noarch/simple_http_server.py", line 470, in add_listen
    raise Exception(err_string)
Exception: bind to b'127.0.0.1':8087 fail:OSError(98, '地址已在使用')

2021-02-20 21:42:17.845 [gae_proxy][DEBUG] network IPv4 is ok, cost:206 ms
2021-02-20 21:42:36.886 [gae_proxy][WARNING] network IPv6 fail
2021-02-20 21:46:24.010 [gae_proxy][DEBUG] report_connect_fail IPv6 continue_fail_count:11
2021-02-20 21:46:42.030 [gae_proxy][DEBUG] report_connect_fail IPv6 continue_fail_count:12
2021-02-20 21:46:42.719 [gae_proxy][WARNING] network IPv6 fail
2021-02-20 21:47:00.048 [gae_proxy][DEBUG] report_connect_fail IPv6 continue_fail_count:13
2021-02-20 21:47:18.067 [gae_proxy][DEBUG] report_connect_fail IPv6 continue_fail_count:14
2021-02-20 21:47:18.337 [gae_proxy][WARNING] network IPv6 fail
请问为什么我的不能弹出网页配置设置界面呀？
