### ISSUE TITLE
xx-net部署401错误

### ISSUE THREAD

**Issue by YvanLaucsu** [XX-net/XX-Net#4308]
按照github步骤部署xx-net，xx-net版本为3.2.6，chrome版本为53.0.2785.143 m (64-bit)。GAE代理正常，在部署私有appid时，已启用弱安全选项。部署时，弹出两次权限申请。第一次允许之后，出现The authentication flow has completed.然后出现第二次权限申请。第二次权限申请点击允许之后没有响应。下面部署日志。求大侠帮忙看看问题出现在哪
2016-10-05 10:06:25,380 - root - INFO - enable debug logging
2016-10-05 10:06:25,380 - root - INFO - set proxy to http://127.0.0.1:8087
2016-10-05 10:06:25,395 - root - INFO - ============ Begin upload ============
2016-10-05 10:06:25,395 - root - INFO - appid:xx-net1-145501
2016-10-05 10:06:25,421 - root - INFO - Send: /api/appversion/rollback, params={'version': '1', 'app_id': 'xx-net1-145501'}
2016-10-05 10:06:25,421 - google.appengine.tools.appengine_rpc - DEBUG - _Authenticate skipped auth; needs_auth=False
2016-10-05 10:06:25,421 - google.appengine.tools.appengine_rpc - DEBUG - Sending request to https://appengine.google.com/api/appversion/rollback?app_id=xx-net1-145501&force_rollback=0&version=1 headers={'X-appcfg-api-version': '1', 'content-length': '0', 'Content-Type': 'application/octet-stream'} body=
2016-10-05 10:06:26,114 - google.appengine.tools.appengine_rpc - DEBUG - Got http error 401.
2016-10-05 10:06:26,114 - google.appengine.tools.appengine_rpc - DEBUG - Attempting to auth. This is try 1 of 3.
2016-10-05 10:06:26,114 - google.appengine.tools.appengine_rpc - DEBUG - _Authenticate requesting auth
2016-10-05 10:06:30,970 - oauth2client.client - INFO - Successfully retrieved access token
2016-10-05 10:06:30,970 - root - ERROR - upload fail:IOError(2, 'No such file or directory')
Traceback (most recent call last):
File "D:\XX-Net\code\default\gae_proxy\server\uploader.py", line 70, in upload
result = appcfg.AppCfgApp(['appcfg', 'rollback', dirname ]).Run()
File "D:\XX-Net\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 2951, in Run
self.action(self)
File "D:\XX-Net\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 5044, in __call__
return method()
File "D:\XX-Net\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 4397, in Rollback
self._Rollback()
File "D:\XX-Net\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 4442, in _Rollback
appversion.Rollback(force_rollback)
File "D:\XX-Net\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 2362, in Rollback
force_rollback='1' if force_rollback else '0')
File "D:\XX-Net\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 1696, in Send
result = self.rpcserver.Send(url, payload=payload, **kwargs)
File "D:\XX-Net\code\default\gae_proxy\server\lib\google\appengine\tools\appengine_rpc_httplib2.py", line 241, in Send
self._Authenticate(self.http, auth_errors[0] > 0)
File "D:\XX-Net\code\default\gae_proxy\server\lib\google\appengine\tools\appengine_rpc_httplib2.py", line 459, in _Authenticate
self.credentials = tools.run_flow(flow, self.storage, self.flags)
File "D:\XX-Net\code\default\gae_proxy\server\lib\oauth2client\util.py", line 137, in positional_wrapper
return wrapped(*args, **kwargs)
File "D:\XX-Net\code\default\gae_proxy\server\lib\oauth2client\tools.py", line 229, in run_flow
storage.put(credential)
File "D:\XX-Net\code\default\gae_proxy\server\lib\oauth2client\client.py", line 388, in put
self.locked_put(credentials)
File "D:\XX-Net\code\default\gae_proxy\server\lib\oauth2client\file.py", line 109, in locked_put
self._create_file_if_needed()
File "D:\XX-Net\code\default\gae_proxy\server\lib\oauth2client\file.py", line 95, in _create_file_if_needed
open(self._filename, 'a+b').close()
IOError: [Errno 2] No such file or directory: 'd:\\SPB_Data/.appcfg_oauth2_tokens'
2016-10-05 10:06:30,970 - root - INFO - Retry 1 time...
2016-10-05 10:06:31,003 - root - INFO - Send: /api/appversion/rollback, params={'version': '1', 'app_id': 'xx-net1-145501'}
2016-10-05 10:06:31,003 - google.appengine.tools.appengine_rpc - DEBUG - _Authenticate skipped auth; needs_auth=False
2016-10-05 10:06:31,003 - google.appengine.tools.appengine_rpc - DEBUG - Sending request to https://appengine.google.com/api/appversion/rollback?app_id=xx-net1-145501&force_rollback=0&version=1 headers={'X-appcfg-api-version': '1', 'content-length': '0', 'Content-Type': 'application/octet-stream'} body=
2016-10-05 10:06:31,342 - google.appengine.tools.appengine_rpc - DEBUG - Got http error 401.
2016-10-05 10:06:31,342 - google.appengine.tools.appengine_rpc - DEBUG - Attempting to auth. This is try 1 of 3.

**Comment by jzp820927** [comment]
2016-10-05 10:06:30,970 - root - ERROR - upload fail:IOError(2, 'No such file or directory')
Traceback (most recent call last):
IOError: [Errno 2] No such file or directory: 'd:\SPB_Data/.appcfg_oauth2_tokens'

提示说，没有发现 d:\SPB_Data/.appcfg_oauth2_tokens 这个文件，直接检查下这个文件

**Comment by YvanLaucsu** [comment]
d:\SPB_Data/.appcfg_oauth2_tokens 确实是没有这个文件。这应该是个秘钥文件，怎么生成？

**Comment by jzp820927** [comment]
认证通过以后就会生成，如果没生成，应该是你认证没通过

**Comment by YvanLaucsu** [comment]
可是在谷歌个人账户里面明明是授权了的。

**Comment by jzp820927** [comment]
你是什么系统？

**Comment by YvanLaucsu** [comment]
win7 64位旗舰版

**Comment by jzp820927** [comment]
那应该不是系统的问题，要不把 XX 删了，重新下载一次再试试
