### ISSUE TITLE
部署失败，主要错误ERROR - upload fail

### ISSUE THREAD

**Issue by dengzhencn** [XX-net/XX-Net#4320]
按照github步骤部署xx-net，xx-net版本为3.2.6，Chrome 42.0.2311.135 (64-bit)，Mac系统10.11，公共代理可以上，部署私人不行。。。
2016-10-07 10:02:59,247 - root - INFO - set proxy to http://127.0.0.1:8087
2016-10-07 10:02:59,249 - root - INFO - ============ Begin upload ============
2016-10-07 10:02:59,249 - root - INFO - appid:tangent-145702
2016-10-07 10:02:59,270 - root - INFO - Send: /api/appversion/rollback, params={'version': '1', 'app_id': 'tangent-145702'}
2016-10-07 10:02:59,660 - root - ERROR - upload fail:EOFError('EOF when reading a line',)
Traceback (most recent call last):
File "/Users/dengzhen/Desktop/XX-Net-3.2.6/code/default/gae_proxy/server/uploader.py", line 70, in upload
result = appcfg.AppCfgApp(['appcfg', 'rollback', dirname ]).Run()
File "/Users/dengzhen/Desktop/XX-Net-3.2.6/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 2951, in Run
self.action(self)
File "/Users/dengzhen/Desktop/XX-Net-3.2.6/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 5044, in __call__
return method()
File "/Users/dengzhen/Desktop/XX-Net-3.2.6/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 4397, in Rollback
self._Rollback()
File "/Users/dengzhen/Desktop/XX-Net-3.2.6/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 4442, in _Rollback
appversion.Rollback(force_rollback)
File "/Users/dengzhen/Desktop/XX-Net-3.2.6/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 2362, in Rollback
force_rollback='1' if force_rollback else '0')
File "/Users/dengzhen/Desktop/XX-Net-3.2.6/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 1696, in Send
result = self.rpcserver.Send(url, payload=payload, **kwargs)
File "/Users/dengzhen/Desktop/XX-Net-3.2.6/code/default/gae_proxy/server/lib/google/appengine/tools/appengine_rpc_httplib2.py", line 241, in Send
self._Authenticate(self.http, auth_errors[0] > 0)
File "/Users/dengzhen/Desktop/XX-Net-3.2.6/code/default/gae_proxy/server/lib/google/appengine/tools/appengine_rpc_httplib2.py", line 459, in _Authenticate
self.credentials = tools.run_flow(flow, self.storage, self.flags)
File "/Users/dengzhen/Desktop/XX-Net-3.2.6/code/default/gae_proxy/server/lib/oauth2client/util.py", line 137, in positional_wrapper
return wrapped(*args, **kwargs)
File "/Users/dengzhen/Desktop/XX-Net-3.2.6/code/default/gae_proxy/server/lib/oauth2client/tools.py", line 222, in run_flow
code = input('Enter verification code: ').strip()
EOFError: EOF when reading a line
2016-10-07 10:02:59,668 - root - INFO - Retry 1 time...
2016-10-07 10:02:59,688 - root - INFO - Send: /api/appversion/rollback, params={'version': '1', 'app_id': 'tangent-145702'}
2016-10-07 10:02:59,971 - root - ERROR - upload fail:EOFError('EOF when reading a line',)
Traceback (most recent call last):
File "/Users/dengzhen/Desktop/XX-Net-3.2.6/code/default/gae_proxy/server/uploader.py", line 70, in upload
result = appcfg.AppCfgApp(['appcfg', 'rollback', dirname ]).Run()
File "/Users/dengzhen/Desktop/XX-Net-3.2.6/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 2951, in Run
self.action(self)
File "/Users/dengzhen/Desktop/XX-Net-3.2.6/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 5044, in __call__
return method()
File "/Users/dengzhen/Desktop/XX-Net-3.2.6/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 4397, in Rollback
self._Rollback()
File "/Users/dengzhen/Desktop/XX-Net-3.2.6/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 4442, in _Rollback
appversion.Rollback(force_rollback)
File "/Users/dengzhen/Desktop/XX-Net-3.2.6/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 2362, in Rollback
force_rollback='1' if force_rollback else '0')
File "/Users/dengzhen/Desktop/XX-Net-3.2.6/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 1696, in Send
result = self.rpcserver.Send(url, payload=payload, **kwargs)
File "/Users/dengzhen/Desktop/XX-Net-3.2.6/code/default/gae_proxy/server/lib/google/appengine/tools/appengine_rpc_httplib2.py", line 241, in Send
self._Authenticate(self.http, auth_errors[0] > 0)
File "/Users/dengzhen/Desktop/XX-Net-3.2.6/code/default/gae_proxy/server/lib/google/appengine/tools/appengine_rpc_httplib2.py", line 459, in _Authenticate
self.credentials = tools.run_flow(flow, self.storage, self.flags)
File "/Users/dengzhen/Desktop/XX-Net-3.2.6/code/default/gae_proxy/server/lib/oauth2client/util.py", line 137, in positional_wrapper
return wrapped(*args, **kwargs)
File "/Users/dengzhen/Desktop/XX-Net-3.2.6/code/default/gae_proxy/server/lib/oauth2client/tools.py", line 222, in run_flow
code = input('Enter verification code: ').strip()
EOFError: EOF when reading a line
2016-10-07 10:02:59,971 - root - INFO - Retry 2 time...
2016-10-07 10:03:01,003 - root - INFO - Send: /api/appversion/rollback, params={'version': '1', 'app_id': 'tangent-145702'}
2016-10-07 10:03:01,272 - root - ERROR - upload fail:EOFError('EOF when reading a line',)
Traceback (most recent call last):
File "/Users/dengzhen/Desktop/XX-Net-3.2.6/code/default/gae_proxy/server/uploader.py", line 70, in upload
result = appcfg.AppCfgApp(['appcfg', 'rollback', dirname ]).Run()
File "/Users/dengzhen/Desktop/XX-Net-3.2.6/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 2951, in Run
self.action(self)
File "/Users/dengzhen/Desktop/XX-Net-3.2.6/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 5044, in __call__
return method()
File "/Users/dengzhen/Desktop/XX-Net-3.2.6/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 4397, in Rollback
self._Rollback()
File "/Users/dengzhen/Desktop/XX-Net-3.2.6/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 4442, in _Rollback
appversion.Rollback(force_rollback)
File "/Users/dengzhen/Desktop/XX-Net-3.2.6/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 2362, in Rollback
force_rollback='1' if force_rollback else '0')
File "/Users/dengzhen/Desktop/XX-Net-3.2.6/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 1696, in Send
result = self.rpcserver.Send(url, payload=payload, **kwargs)
File "/Users/dengzhen/Desktop/XX-Net-3.2.6/code/default/gae_proxy/server/lib/google/appengine/tools/appengine_rpc_httplib2.py", line 241, in Send
self._Authenticate(self.http, auth_errors[0] > 0)
File "/Users/dengzhen/Desktop/XX-Net-3.2.6/code/default/gae_proxy/server/lib/google/appengine/tools/appengine_rpc_httplib2.py", line 459, in _Authenticate
self.credentials = tools.run_flow(flow, self.storage, self.flags)
File "/Users/dengzhen/Desktop/XX-Net-3.2.6/code/default/gae_proxy/server/lib/oauth2client/util.py", line 137, in positional_wrapper
return wrapped(*args, **kwargs)
File "/Users/dengzhen/Desktop/XX-Net-3.2.6/code/default/gae_proxy/server/lib/oauth2client/tools.py", line 222, in run_flow
code = input('Enter verification code: ').strip()
EOFError: EOF when reading a line
2016-10-07 10:03:01,273 - root - INFO - Retry 3 time...
2016-10-07 10:03:03,277 - root - INFO - =======================
2016-10-07 10:03:03,278 - root - INFO - Deploy failed appid list:
2016-10-07 10:03:03,278 - root - INFO - - tangent-145702
2016-10-07 10:03:03,278 - root - INFO - == END ==
---
## 提问之前
1. 首先请确认你使用的是[最新版本](https://github.com/XX-net/XX-Net/blob/master/code/default/download.md)，你的问题可能已经在新版本里解决了。
2. 请阅读[故障速查手册](https://github.com/XX-net/XX-Net/wiki/故障速查手册)，大部分问题都能在这里找到答案。
3. 请在 [issue](https://github.com/XX-net/XX-Net/issues) 区搜索有无类似的问题。

#### 获取诊断信息
XX-Net Status:

sys-platform: x86_64, Darwin-15.5.0-x86_64-i386-64bit
os-system: Darwin
os-version: Darwin Kernel Version 15.5.0: Tue Apr 19 18:36:36 PDT 2016; root:xnu-3248.50.21~8/RELEASE_X86_64
os-release: 15.5.0
os-detail: Release:10.11.5; Version:('', '', '') Machine:x86_64
architecture: 64bit,
browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36
xxnet-version: 3.2.6

python-version: 2.7.10
openssl-version: 16.0.0 TLSv1 h2:alpn

ipv6-status: 0
gws-ip-num: total:3000 good:211
network-status: OK
connected-link: new:2 used:0
worker: h1:24 h2:7
scan-ip-thread-num: 50
ip-quality: 270
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: true
Appids_Not_Exist: true
Using_Public_Appid: true

**Comment by jzp820927** [comment]
好像很多 MAC 平台都遇到问题了，都是因为升级以后出现的问题，初步怀疑是 MAC 升级产生的问题，如果条件允许，可以考虑到 win 下面部署试试

**Comment by dengzhencn** [comment]
只有一部Mac。。。如果有升级解决就好了。。。

**Comment by jzp820927** [comment]
那就用 公共 appid 吧

**Comment by dengzhencn** [comment]
有没有可能其他原因？

**Comment by jzp820927** [comment]
没有 MAC 机器，没法测试，只是最近 issues 里面很多人反映，mac 升级后就不能用了。使用我猜测是这个问题。或者你也可以和 issues 里面其他用 mac 系统的交流下。
