### ISSUE TITLE
在线等回复关于“部署XX-Net至GAE”

### ISSUE THREAD

**Issue by Periclesgithub** [XX-net/XX-Net#4404]
自己的APPID用完了，又申请了几个，正在部署，但是一直没有动静！
反馈如下：

2016-10-20 13:43:00,865 - root - INFO - enable debug logging
2016-10-20 13:43:00,865 - root - INFO - set proxy to http://127.0.0.1:8087
2016-10-20 13:43:00,894 - root - INFO - ============ Begin upload ============
2016-10-20 13:43:00,894 - root - INFO - appid:atomic-kit-145811
2016-10-20 13:43:00,945 - root - INFO - Send: /api/appversion/rollback, params={'version': '1', 'app_id': 'atomic-kit-145811'}
2016-10-20 13:43:00,945 - google.appengine.tools.appengine_rpc - DEBUG - _Authenticate skipped auth; needs_auth=False
2016-10-20 13:43:00,945 - google.appengine.tools.appengine_rpc - DEBUG - Sending request to https://appengine.google.com/api/appversion/rollback?app_id=atomic-kit-145811&force_rollback=0&version=1 headers={'X-appcfg-api-version': '1', 'content-length': '0', 'Content-Type': 'application/octet-stream'} body=
2016-10-20 13:52:27,832 - google.appengine.tools.appengine_rpc - DEBUG - Got http error 600.
2016-10-20 13:52:27,832 - google.appengine.tools.appengine_rpc - DEBUG - Unexpected results: {'status': '600', 'content-length': '134', 'connection': 'close'}
2016-10-20 13:52:27,833 - root - ERROR - upload fail:ValidationError("Value '600' for response_code is out of range 100 - 599",)
Traceback (most recent call last):
File "/home/asoka/Documents/softwaredeb/xxnet/XX-Net-3.2.6/code/default/gae_proxy/server/uploader.py", line 70, in upload
result = appcfg.AppCfgApp(['appcfg', 'rollback', dirname ]).Run()
File "/home/asoka/Documents/softwaredeb/xxnet/XX-Net-3.2.6/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 2951, in Run
self.action(self)
File "/home/asoka/Documents/softwaredeb/xxnet/XX-Net-3.2.6/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 5044, in __call__
return method()
File "/home/asoka/Documents/softwaredeb/xxnet/XX-Net-3.2.6/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 4397, in Rollback
self._Rollback()
File "/home/asoka/Documents/softwaredeb/xxnet/XX-Net-3.2.6/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 4442, in _Rollback
appversion.Rollback(force_rollback)
File "/home/asoka/Documents/softwaredeb/xxnet/XX-Net-3.2.6/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 2362, in Rollback
force_rollback='1' if force_rollback else '0')
File "/home/asoka/Documents/softwaredeb/xxnet/XX-Net-3.2.6/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 1702, in Send
request_size_bytes)
File "/home/asoka/Documents/softwaredeb/xxnet/XX-Net-3.2.6/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 1723, in _RegisterReqestForLogging
request_size_bytes=request_size_bytes))
File "/home/asoka/Documents/softwaredeb/xxnet/XX-Net-3.2.6/code/default/gae_proxy/server/lib/google/appengine/api/validation.py", line 273, in __init__
self.SetMultiple(attributes)
File "/home/asoka/Documents/softwaredeb/xxnet/XX-Net-3.2.6/code/default/gae_proxy/server/lib/google/appengine/api/validation.py", line 177, in SetMultiple
self.Set(key, value)
File "/home/asoka/Documents/softwaredeb/xxnet/XX-Net-3.2.6/code/default/gae_proxy/server/lib/google/appengine/api/validation.py", line 305, in Set
setattr(self, key, value)
File "/home/asoka/Documents/softwaredeb/xxnet/XX-Net-3.2.6/code/default/gae_proxy/server/lib/google/appengine/api/validation.py", line 361, in __setattr__
value = self.GetValidator(key)(value, key)
File "/home/asoka/Documents/softwaredeb/xxnet/XX-Net-3.2.6/code/default/gae_proxy/server/lib/google/appengine/api/validation.py", line 599, in __call__
return self.Validate(value, key)
File "/home/asoka/Documents/softwaredeb/xxnet/XX-Net-3.2.6/code/default/gae_proxy/server/lib/google/appengine/api/validation.py", line 1157, in Validate
% (value, key, self.minimum, self.maximum))
ValidationError: Value '600' for response_code is out of range 100 - 599
2016-10-20 13:52:27,862 - root - INFO - Retry 1 time...
2016-10-20 13:52:27,875 - root - INFO - Send: /api/appversion/rollback, params={'version': '1', 'app_id': 'atomic-kit-145811'}
2016-10-20 13:52:27,875 - google.appengine.tools.appengine_rpc - DEBUG - _Authenticate skipped auth; needs_auth=False
2016-10-20 13:52:27,875 - google.appengine.tools.appengine_rpc - DEBUG - Sending request to https://appengine.google.com/api/appversion/rollback?app_id=atomic-kit-145811&force_rollback=0&version=1 headers={'X-appcfg-api-version': '1', 'content-length': '0', 'Content-Type': 'application/octet-stream'} body=

**Comment by jzp820927** [comment]
还是 ubuntu 1604 系统？

**Comment by nly4lov** [comment]
部署之前确保要可以FQ

**Comment by Periclesgithub** [comment]
是Ubuntu16.04，现在弄好了，谢谢各位。

**Comment by jzp820927** [comment]
弄好了，不分享一下经验？也可以帮助其他人嘛
