### ISSUE TITLE
ubuntu下的xx-net图标点击没有反应。

### ISSUE THREAD

**Issue by miss13** [XX-net/XX-Net#4434]
ubuntu下的xx-net图标点击没有反应。怎么才能像win下面点击图标开启xx-net，还有就是xx-net后台也不显示。

**Comment by jzp820927** [comment]
自己连几个快捷方式，运行命令  python code/default/launcher/start.py

**Comment by miss13** [comment]
谢谢😜


在2016年10月25日 22:33 ，天朝屁民<mailto:notifications@github.com>写道：


自己连几个快捷方式，运行命令 python code/default/launcher/start.py

**Comment by dreamidiot** [comment]
@jzp820927 
我的ubuntu倒是装完xxnet后，双击图标有反应的
但是，我的Lubuntu 16.04 LTS 32bit,，装完后双击没反应
用你的方法创建快捷方式不行，反馈如下：

Traceback (most recent call last):
  File "start.py", line 37, in <module>
    from instances import xlog
  File "/home/lubuntu32/Documents/XX-Net-master/code/default/launcher/instances.py", line 12, in <module>
    xlog = Logger(file_name=log_file)
  File "/home/lubuntu32/Documents/XX-Net-master/code/default/python27/1.0/lib/noarch/xlog.py", line 35, in __init__
    self.set_file(file_name)
  File "/home/lubuntu32/Documents/XX-Net-master/code/default/python27/1.0/lib/noarch/xlog.py", line 90, in set_file
    self.log_fd = open(file_name, "w")
IOError: [Errno 13] Permission denied: '/home/lubuntu32/Documents/XX-Net-master/data/launcher/launcher.log'

请问是什么问题啊？该如何解决？谢谢！
xxnet功能正常，就是每次都cd 然后./start太烦了

**Comment by jzp820927** [comment]
IOError: [Errno 13] Permission denied: '/home/lubuntu32/Documents/XX-Net-master/data/launcher/launcher.log'

看报错信息，应该是权限问题，你坚持下，这路径 XX 是否有权限。

**Comment by dreamidiot** [comment]
@jzp820927 
确实是权限的问题，用su root获得权限后，就能创建图标了！但是图标创建后，一重启，双击图标又没反应了。。。

后来看了之前的issue，原来首次安装的时候不要sudo，直接./start就可以了，这样双击后就能运行了，重启后依然有效。

多谢！

**Comment by miss13** [comment]
原来是这样的，看来重新得重新布置一次了。谢谢

发件人: dreamidiot [mailto:notifications@github.com]
发送时间: 2016年10月31日 19:40
收件人: XX-net/XX-Net <XX-Net@noreply.github.com>
抄送: miss13 <xuhuaipeng2015@outlook.com>; Author <author@noreply.github.com>
主题: Re: [XX-net/XX-Net] ubuntu下的xx-net图标点击没有反应。 (#4434)


@jzp820927<https://github.com/jzp820927>
确实是权限的问题，用su root获得权限后，就能创建图标了！但是图标创建后，一重启，双击图标又没反应了。。。

后来看了之前的issue，原来首次安装的时候不要sudo，直接./start就可以了，这样双击后就能运行了，重启后依然有效。

多谢！
