### ISSUE TITLE
最新的macOS无法打开呀

### ISSUE THREAD

**Issue by elvis1121** [XX-net/XX-Net#4471]
用终端cd到xxnet 然后./start也不行

**Comment by elvis1121** [comment]
ElvisMac:~ elvis$ cd /Users/elvis/Desktop/apps/XX-Net 
ElvisMac:XX-Net elvis$ ./start
Python 2.7.10
XX-Net version:default
ElvisMac:XX-Net elvis$ 

终端返回这样的结果，但是就是不启动

**Comment by elvis1121** [comment]
活动监视器里也看不到Python启动

**Comment by jzp820927** [comment]
终端下输入命令 
python code/default/launcher/start.py
试试呢

**Comment by elvis1121** [comment]
@jzp820927 要先cd到xxnet的目录吧？结果我贴在下面，还是没启动成功
ElvisMac:~ elvis$ cd /Users/elvis/Desktop/apps/XX-Net 
ElvisMac:XX-Net elvis$ python code/default/launcher/start.py
Oct 31 17:19:44.399 - [INFO] use build-in openssl lib
Oct 31 17:19:44.400 - [INFO] start XX-Net 3.2.8
Oct 31 17:19:44.400 - [DEBUG] start confirm_xxnet_exit
Oct 31 17:19:44.401 - [DEBUG] good, xxnet:8087 cleared!
Oct 31 17:19:44.402 - [DEBUG] good, xxnet:8085 clear!
Oct 31 17:19:44.402 - [DEBUG] finished confirm_xxnet_exit
Oct 31 17:19:44.474 - [INFO] SSL use version:TLSv1
Oct 31 17:19:44.476 - [INFO] OpenSSL support alpn
Oct 31 17:19:44.478 - [INFO] load ip range file:/Users/elvis/Desktop/apps/XX-Net/code/default/gae_proxy/local/ip_range.txt
Oct 31 17:19:44.498 - [ERROR] start module gae_proxy fail:[Errno 13] Permission denied: '/Users/elvis/Desktop/apps/XX-Net/data/gae_proxy/scan_ip.log'
Oct 31 17:19:44.501 - [ERROR] Except stack:Traceback (most recent call last):
  File "/Users/elvis/Desktop/apps/XX-Net/code/default/launcher/module_init.py", line 37, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "/Users/elvis/Desktop/apps/XX-Net/code/default/gae_proxy/start.py", line 13, in <module>
    import local.proxy as client
  File "/Users/elvis/Desktop/apps/XX-Net/code/default/gae_proxy/local/proxy.py", line 97, in <module>
    import proxy_handler
  File "/Users/elvis/Desktop/apps/XX-Net/code/default/gae_proxy/local/proxy_handler.py", line 54, in <module>
    import gae_handler
  File "/Users/elvis/Desktop/apps/XX-Net/code/default/gae_proxy/local/gae_handler.py", line 69, in <module>
    from google_ip import google_ip
  File "/Users/elvis/Desktop/apps/XX-Net/code/default/gae_proxy/local/google_ip.py", line 37, in <module>
    from scan_ip_log import scan_ip_log
  File "/Users/elvis/Desktop/apps/XX-Net/code/default/gae_proxy/local/scan_ip_log.py", line 65, in <module>
    scan_ip_log = Scan_ip_log()
  File "/Users/elvis/Desktop/apps/XX-Net/code/default/gae_proxy/local/scan_ip_log.py", line 16, in __init__
    self.open_log()
  File "/Users/elvis/Desktop/apps/XX-Net/code/default/gae_proxy/local/scan_ip_log.py", line 34, in open_log
    self.log_fd = open(self.log_path, "a")
IOError: [Errno 13] Permission denied: '/Users/elvis/Desktop/apps/XX-Net/data/gae_proxy/scan_ip.log'

Oct 31 17:19:44.501 - [ERROR] launcher except:IOError(13, 'Permission denied')
Oct 31 17:19:44.502 - [ERROR] Except stack:Traceback (most recent call last):
  File "code/default/launcher/start.py", line 182, in <module>
  File "code/default/launcher/start.py", line 159, in main
  File "/Users/elvis/Desktop/apps/XX-Net/code/default/launcher/module_init.py", line 98, in start_all_auto
    start(module)
  File "/Users/elvis/Desktop/apps/XX-Net/code/default/launcher/module_init.py", line 37, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "/Users/elvis/Desktop/apps/XX-Net/code/default/gae_proxy/start.py", line 13, in <module>
    import local.proxy as client
  File "/Users/elvis/Desktop/apps/XX-Net/code/default/gae_proxy/local/proxy.py", line 97, in <module>
    import proxy_handler
  File "/Users/elvis/Desktop/apps/XX-Net/code/default/gae_proxy/local/proxy_handler.py", line 54, in <module>
    import gae_handler
  File "/Users/elvis/Desktop/apps/XX-Net/code/default/gae_proxy/local/gae_handler.py", line 69, in <module>
    from google_ip import google_ip
  File "/Users/elvis/Desktop/apps/XX-Net/code/default/gae_proxy/local/google_ip.py", line 37, in <module>
    from scan_ip_log import scan_ip_log
  File "/Users/elvis/Desktop/apps/XX-Net/code/default/gae_proxy/local/scan_ip_log.py", line 65, in <module>
    scan_ip_log = Scan_ip_log()
  File "/Users/elvis/Desktop/apps/XX-Net/code/default/gae_proxy/local/scan_ip_log.py", line 16, in __init__
    self.open_log()
  File "/Users/elvis/Desktop/apps/XX-Net/code/default/gae_proxy/local/scan_ip_log.py", line 34, in open_log
    self.log_fd = open(self.log_path, "a")
IOError: [Errno 13] Permission denied: '/Users/elvis/Desktop/apps/XX-Net/data/gae_proxy/scan_ip.log'

Press Enter to continue...Oct 31 17:19:47.188 - [DEBUG] network is ok, cost:2750 ms

Stopping all modules before exit!
Oct 31 17:20:29.368 - [ERROR] stop module gae_proxy fail:'imp'
Oct 31 17:20:29.368 - [ERROR] Except stack:Traceback (most recent call last):
  File "/Users/elvis/Desktop/apps/XX-Net/code/default/launcher/module_init.py", line 71, in stop
    _start = proc_handler[module]["imp"].start
KeyError: 'imp'

**Comment by elvis1121** [comment]
<img width="606" alt="qq20161031-0 2x" src="https://cloud.githubusercontent.com/assets/5030867/19849478/7f7e6fa4-9f8e-11e6-9e45-53eaaa32dfed.png">

**Comment by jzp820927** [comment]
Oct 31 17:19:44.498 - [ERROR] start module gae_proxy fail:[Errno 13] Permission denied: '/Users/elvis/Desktop/apps/XX-Net/data/gae_proxy/scan_ip.log'
Oct 31 17:19:44.501 - [ERROR] Except stack:Traceback (most recent call last):
File "/Users/elvis/Desktop/apps/XX-Net/code/default/launcher/module_init.py", line 37, in start
Oct 31 17:19:44.501 - [ERROR] launcher except:IOError(13, 'Permission denied')

没有权限，你先设定一下文件权限。

**Comment by elvis1121** [comment]
都是系统允许读写呀 staff 和 everyone 只读，这个一直没动过

**Comment by elvis1121** [comment]
把everyone改成读写之后还是启动不了😂

**Comment by jzp820927** [comment]
那就不太清楚了，反正日志提示的 “Permission denied”，我没有 mac 机器，也没法测试了。

**Comment by noveleven** [comment]
macOS sierra 和 XX-Net 3.2.8 测试没有问题

**Comment by elvis1121** [comment]
重装了还是不能启动😂

**Comment by jzp820927** [comment]
MAC 系统最近经常有人反映升级到最新版，无法正常运行，估计应该是系统本身的原因。

**Comment by hzxie** [comment]
XX-Net 3.2.8, macOS Sierra
没有问题。

**Comment by xiaolugo** [comment]
@用python打开一次就行了，多谢@jzp820927!!!

**Comment by jzp820927** [comment]
不客气

**Comment by Bohan-Song** [comment]
@jzp820927   
00MacBook-pro:~ shirley$ /Users/shirley/Documents/XX-Net-3.6.6/start ; exit;
XX-Net version:default
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[进程已完成]

mac第一次打开成功了，一切正常，重启之后就打不开了，浏览器也进不去，图标也没有 。。。

**Comment by Bohan-Song** [comment]
@jzp820927   python code/default/launcher/start.py了一下  
0MacBook-pro:~ root# python /Users/shirley/Documents/XX-Net-3.6.6/code/default/launcher/start.py 
Oct 02 09:46:21.156 - [INFO] use build-in openssl lib
Oct 02 09:46:21.157 - [INFO] start XX-Net 3.6.6
Oct 02 09:46:21.157 - [DEBUG] start confirm_xxnet_exit
Oct 02 09:46:51.278 - [DEBUG] good, xxnet:8087 cleared!
Oct 02 09:47:21.283 - [DEBUG] good, xxnet:8085 clear!
Oct 02 09:47:21.283 - [DEBUG] finished confirm_xxnet_exit
Oct 02 09:47:21.340 - [INFO] SSL use version:TLSv1
Oct 02 09:47:21.340 - [INFO] OpenSSL support alpn
Oct 02 09:47:21.342 - [INFO] load ip range file:/Users/shirley/Documents/XX-Net-3.6.6/code/default/gae_proxy/local/ip_range.txt
Oct 02 09:47:21.344 - [INFO] Use google ip pool.
Oct 02 09:47:21.383 - [INFO] load google ip_list num:3000, gws num:3000
Oct 02 09:47:21.396 - [INFO] OpenSSL support alpn
Oct 02 09:47:21.406 - [DEBUG] ## GAEProxy set keep_running: True
Oct 02 09:47:21.407 - [INFO] ------------------------------------------------------
Oct 02 09:47:21.407 - [INFO] Python Version     : 2.7.10
Oct 02 09:47:21.407 - [INFO] OS                 : Release:10.12.6; Version:('', '', '') Machine:x86_64
Oct 02 09:47:21.407 - [INFO] Listen Address     : 127.0.0.1:8087
Oct 02 09:47:21.407 - [INFO] GAE APPID          : bobo-150712|bobo1-150712|bobo2-150712|bobo3-150712|bobo4-150712
Oct 02 09:47:21.407 - [INFO] Pac Server         : http://127.0.0.1:8086/proxy.pac
Oct 02 09:47:21.407 - [INFO] ------------------------------------------------------
Oct 02 09:47:21.447 - [INFO] GoAgent CA exist
Oct 02 09:47:21.447 - [ERROR] bind to 127.0.0.1:8087 fail:error(48, 'Address already in use')
Exception in thread Thread-60:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/shirley/Documents/XX-Net-3.6.6/code/default/gae_proxy/start.py", line 18, in main
    client.main()
  File "/Users/shirley/Documents/XX-Net-3.6.6/code/default/gae_proxy/local/proxy.py", line 155, in main
    proxy_daemon = simple_http_server.HTTPServer((config.LISTEN_IP, config.LISTEN_PORT), proxy_handler.GAEProxyHandler)
  File "/Users/shirley/Documents/XX-Net-3.6.6/code/default/python27/1.0/lib/noarch/simple_http_server.py", line 369, in __init__
    self.init_socket()
  File "/Users/shirley/Documents/XX-Net-3.6.6/code/default/python27/1.0/lib/noarch/simple_http_server.py", line 379, in init_socket
    self.add_listen(addr)
  File "/Users/shirley/Documents/XX-Net-3.6.6/code/default/python27/1.0/lib/noarch/simple_http_server.py", line 393, in add_listen
    raise Exception(err_string)
Exception: bind to 127.0.0.1:8087 fail:error(48, 'Address already in use')

Oct 02 09:47:24.149 - [DEBUG] create_ssl update ip:128.0.31.250 time:731 h2:1
Oct 02 09:47:25.411 - [DEBUG] 115.254.97.14 fail:timeout('timed out',)
Oct 02 09:47:25.412 - [DEBUG] report_connect_fail:115.254.97.14
Oct 02 09:47:25.412 - [DEBUG] 115.254.106.209 fail:timeout('timed out',)
Oct 02 09:47:25.413 - [DEBUG] report_connect_fail:115.254.106.209
Oct 02 09:47:26.422 - [DEBUG] 128.0.31.216 fail:timeout('timed out',)
Oct 02 09:47:26.422 - [DEBUG] report_connect_fail:128.0.31.216
Oct 02 09:47:26.469 - [DEBUG] create_ssl update ip:128.0.31.234 time:979 h2:1
Oct 02 09:47:26.927 - [DEBUG] 128.0.31.221 fail:timeout('timed out',)
Oct 02 09:47:26.928 - [DEBUG] report_connect_fail:128.0.31.221

**Comment by xxnet** [comment]
​原来的进程没有退出
试试 kill 原来的进程，可以用ps 或 top 看原来的进程号

**Comment by Bohan-Song** [comment]
@xxnet  退了，重启过也不行啊。。。

**Comment by xxnet** [comment]
​另外解压一个干净的版本试试

**Comment by Bohan-Song** [comment]
@xxnet  也试过了。不行  😭

**Comment by xxnet** [comment]
​cd /Users/shirley/Documents/XX-Net-3.6.6/
./start

 输出什么日志

**Comment by Bohan-Song** [comment]
什么都没有，回车就直接换行，回到命令窗口。
哎~不行就用windows吧

**Comment by jzp820927** [comment]
Exception: bind to 127.0.0.1:8087 fail:error(48, 'Address already in use')

端口占用，好好检查下

**Comment by Bohan-Song** [comment]
就是xxnet占用的呗，但是我不会查😭

**Comment by jzp820927** [comment]
难道你运行了2个 XXNET，任务管理器查看，任何结束掉占用端口的进程

**Comment by Bohan-Song** [comment]
搞定了，多谢
不过最近IP很少啊，我3000IP有效只有6个，延迟1000+
