### ISSUE TITLE
以前部署成功过，也能上谷歌。但最近部署失败

### ISSUE THREAD

**Issue by zhengyong46** [XX-net/XX-Net#4489]
2016-11-02 14:36:44,506 - root - INFO - set proxy to http://127.0.0.1:8087
2016-11-02 14:36:44,523 - root - INFO - ============ Begin upload ============
2016-11-02 14:36:44,523 - root - INFO - appid:myappid-2325
2016-11-02 14:36:44,538 - root - INFO - Send: /api/appversion/rollback, params={'version': '1', 'app_id': 'myappid-2325'}
2016-11-02 14:36:45,723 - root - ERROR - upload fail:EOFError('EOF when reading a line',)
Traceback (most recent call last):
 File "D:\work\XX-Net-3.2.8\code\default\gae_proxy\server\uploader.py", line 70, in upload
 result = appcfg.AppCfgApp(['appcfg', 'rollback', dirname ]).Run()
 File "D:\work\XX-Net-3.2.8\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 2951, in Run
 self.action(self)
 File "D:\work\XX-Net-3.2.8\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 5044, in __call__
 return method()
 File "D:\work\XX-Net-3.2.8\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 4397, in Rollback
 self._Rollback()
 File "D:\work\XX-Net-3.2.8\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 4442, in _Rollback
 appversion.Rollback(force_rollback)
 File "D:\work\XX-Net-3.2.8\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 2362, in Rollback
 force_rollback='1' if force_rollback else '0')
 File "D:\work\XX-Net-3.2.8\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 1696, in Send
 result = self.rpcserver.Send(url, payload=payload, **kwargs)
 File "D:\work\XX-Net-3.2.8\code\default\gae_proxy\server\lib\google\appengine\tools\appengine_rpc_httplib2.py", line 241, in Send
 self._Authenticate(self.http, auth_errors[0] > 0)
 File "D:\work\XX-Net-3.2.8\code\default\gae_proxy\server\lib\google\appengine\tools\appengine_rpc_httplib2.py", line 459, in _Authenticate
 self.credentials = tools.run_flow(flow, self.storage, self.flags)
 File "D:\work\XX-Net-3.2.8\code\default\gae_proxy\server\lib\oauth2client\util.py", line 137, in positional_wrapper
 return wrapped(*args, **kwargs)
 File "D:\work\XX-Net-3.2.8\code\default\gae_proxy\server\lib\oauth2client\tools.py", line 222, in run_flow
 code = input('Enter verification code: ').strip()
EOFError: EOF when reading a line
2016-11-02 14:36:45,864 - root - INFO - Retry 1 time...
2016-11-02 14:36:45,894 - root - INFO - Send: /api/appversion/rollback, params={'version': '1', 'app_id': 'myappid-2325'}
2016-11-02 14:36:46,487 - root - ERROR - upload fail:EOFError('EOF when reading a line',)
Traceback (most recent call last):
 File "D:\work\XX-Net-3.2.8\code\default\gae_proxy\server\uploader.py", line 70, in upload
 result = appcfg.AppCfgApp(['appcfg', 'rollback', dirname ]).Run()
 File "D:\work\XX-Net-3.2.8\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 2951, in Run
 self.action(self)
 File "D:\work\XX-Net-3.2.8\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 5044, in __call__
 return method()
 File "D:\work\XX-Net-3.2.8\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 4397, in Rollback
 self._Rollback()
 File "D:\work\XX-Net-3.2.8\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 4442, in _Rollback
 appversion.Rollback(force_rollback)
 File "D:\work\XX-Net-3.2.8\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 2362, in Rollback
 force_rollback='1' if force_rollback else '0')
 File "D:\work\XX-Net-3.2.8\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 1696, in Send
 result = self.rpcserver.Send(url, payload=payload, **kwargs)
 File "D:\work\XX-Net-3.2.8\code\default\gae_proxy\server\lib\google\appengine\tools\appengine_rpc_httplib2.py", line 241, in Send
 self._Authenticate(self.http, auth_errors[0] > 0)
 File "D:\work\XX-Net-3.2.8\code\default\gae_proxy\server\lib\google\appengine\tools\appengine_rpc_httplib2.py", line 459, in _Authenticate
 self.credentials = tools.run_flow(flow, self.storage, self.flags)
 File "D:\work\XX-Net-3.2.8\code\default\gae_proxy\server\lib\oauth2client\util.py", line 137, in positional_wrapper
 return wrapped(*args, **kwargs)
 File "D:\work\XX-Net-3.2.8\code\default\gae_proxy\server\lib\oauth2client\tools.py", line 222, in run_flow
 code = input('Enter verification code: ').strip()
EOFError: EOF when reading a line
2016-11-02 14:36:46,487 - root - INFO - Retry 2 time...
2016-11-02 14:36:47,517 - root - INFO - Send: /api/appversion/rollback, params={'version': '1', 'app_id': 'myappid-2325'}
2016-11-02 14:36:48,220 - root - ERROR - upload fail:EOFError('EOF when reading a line',)
Traceback (most recent call last):
 File "D:\work\XX-Net-3.2.8\code\default\gae_proxy\server\uploader.py", line 70, in upload
 result = appcfg.AppCfgApp(['appcfg', 'rollback', dirname ]).Run()
 File "D:\work\XX-Net-3.2.8\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 2951, in Run
 self.action(self)
 File "D:\work\XX-Net-3.2.8\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 5044, in __call__
 return method()
 File "D:\work\XX-Net-3.2.8\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 4397, in Rollback
 self._Rollback()
 File "D:\work\XX-Net-3.2.8\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 4442, in _Rollback
 appversion.Rollback(force_rollback)
 File "D:\work\XX-Net-3.2.8\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 2362, in Rollback
 force_rollback='1' if force_rollback else '0')
 File "D:\work\XX-Net-3.2.8\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 1696, in Send
 result = self.rpcserver.Send(url, payload=payload, **kwargs)
 File "D:\work\XX-Net-3.2.8\code\default\gae_proxy\server\lib\google\appengine\tools\appengine_rpc_httplib2.py", line 241, in Send
 self._Authenticate(self.http, auth_errors[0] > 0)
 File "D:\work\XX-Net-3.2.8\code\default\gae_proxy\server\lib\google\appengine\tools\appengine_rpc_httplib2.py", line 459, in _Authenticate
 self.credentials = tools.run_flow(flow, self.storage, self.flags)
 File "D:\work\XX-Net-3.2.8\code\default\gae_proxy\server\lib\oauth2client\util.py", line 137, in positional_wrapper
 return wrapped(*args, **kwargs)
 File "D:\work\XX-Net-3.2.8\code\default\gae_proxy\server\lib\oauth2client\tools.py", line 222, in run_flow
 code = input('Enter verification code: ').strip()
EOFError: EOF when reading a line
2016-11-02 14:36:48,220 - root - INFO - Retry 3 time...
2016-11-02 14:36:50,232 - root - INFO - =======================
2016-11-02 14:36:50,232 - root - INFO - Deploy failed appid list:
2016-11-02 14:36:50,232 - root - INFO - - myappid-2325
2016-11-02 14:36:50,232 - root - INFO - == END ==

**Comment by jzp820927** [comment]
什么版本
