### ISSUE TITLE
win10 XX net显示请检查浏览器代理设置，右下角图标更改代理方式无效。

### ISSUE THREAD

**Issue by 863233821** [XX-net/XX-Net#4507]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.14959
os-system: Windows
os-version: 10.0.14959
os-release: 10
os-detail: Version:10-0; Build:14959; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.87 Safari/537.36
xxnet-version: 3.2.7

python-version: 2.7.11
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:433 good:414
network-status: OK
connected-link: new:2 used:0
worker: h1:2 h2:3
scan-ip-thread-num: 50
ip-quality: 368
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

证书已导入。。不能选择全局代理或是智能代理。

**Comment by jzp820927** [comment]
近段时间干扰挺厉害。不好确定原因，把日志贴出来看看

**Comment by xSancy** [comment]
你这系统太新了，XX-NET右下角切换代理方式有BUG，我的LTSB2016没这个问题。显示请检查浏览器代理设置，只要系统设置代理或者浏览器代理正确，一样能用。我有时也会显示请检查浏览器代理设置。

**Comment by 863233821** [comment]
Nov 06 17:10:00.764 - [INFO] SSL use version:TLSv1_2
Nov 06 17:10:01.242 - [DEBUG] network is ok, cost:713 ms
Nov 06 17:10:01.374 - [INFO] OpenSSL support alpn
Nov 06 17:10:01.375 - [INFO] load ip range file:F:\\XX-Net-3.2.7\code\default\gae_proxy\local\ip_range.txt
Nov 06 17:10:01.392 - [INFO] detected Win10, enable connect concurrency control, interval:40
Nov 06 17:10:01.395 - [INFO] load google ip_list num:187, gws num:187
Nov 06 17:10:01.403 - [INFO] OpenSSL support alpn
Nov 06 17:10:01.403 - [DEBUG] get ip:61.238.239.209 t:84
Nov 06 17:10:01.405 - [DEBUG] get ip:113.171.253.147 t:200
Nov 06 17:10:01.409 - [DEBUG] ## GAEProxy set keep_running: True
Nov 06 17:10:01.410 - [INFO] ------------------------------------------------------
Nov 06 17:10:01.410 - [INFO] Python Version : 2.7.11
Nov 06 17:10:01.410 - [INFO] OS : Version:10-0; Build:14959; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
Nov 06 17:10:01.410 - [INFO] Listen Address : 127.0.0.1:8087
Nov 06 17:10:01.410 - [INFO] GAE APPID :
Nov 06 17:10:01.410 - [INFO] Pac Server : http://127.0.0.1:8086/proxy.pac
Nov 06 17:10:01.410 - [INFO] ------------------------------------------------------
Nov 06 17:10:01.663 - [DEBUG] create_ssl update ip:61.238.239.209 time:220 h2:0
Nov 06 17:10:01.663 - [DEBUG] get ip:115.254.106.210 t:302
Nov 06 17:10:01.747 - [DEBUG] create_ssl update ip:113.171.253.147 time:207 h2:0
Nov 06 17:10:01.905 - [DEBUG] get ip:183.87.151.92 t:317
Nov 06 17:10:02.062 - [DEBUG] create_ssl update ip:115.254.106.210 time:265 h2:0
Nov 06 17:10:02.377 - [DEBUG] create_ssl update ip:183.87.151.92 time:314 h2:0
Nov 06 17:10:02.726 - [INFO] GAE CONNECT xxnet-update.appspot.com:443
Nov 06 17:10:02.739 - [DEBUG] GAE CONNECT Direct GET https://xxnet-update.appspot.com/update.json?uuid=cd23b1f6-f8a1-4aa8-bd65-b8e18a60912a&version=3.2.7&platform=Windows-10-10.0.14959
Nov 06 17:10:03.065 - [INFO] DIRECT t:325 s:1674 200 xxnet-update.appspot.com /update.json?uuid=cd23b1f6-f8a1-4aa8-bd65-b8e18a60912a&version=3.2.7&platform=Windows-10-10.0.14959
Nov 06 17:10:36.582 - [DEBUG] GAEProxy Web_control 127.0.0.1:14366 GET /deploy?cmd=get_log
Nov 06 17:10:36.723 - [DEBUG] GAEProxy web_control 127.0.0.1:14368 POST /config?cmd=get_config
Nov 06 17:10:50.434 - [DEBUG] 113.171.253.147 close:host pool alive_timeout
Nov 06 17:10:50.434 - [DEBUG] ssl_closed 113.171.253.147
Nov 06 17:10:52.070 - [DEBUG] get ip:113.171.253.147 t:207
Nov 06 17:10:52.370 - [DEBUG] create_ssl update ip:113.171.253.147 time:203 h2:0
Nov 06 17:10:52.370 - [DEBUG] get ip:201.165.221.83 t:394
Nov 06 17:10:53.014 - [DEBUG] create_ssl update ip:201.165.221.83 time:434 h2:0
Nov 06 17:11:22.226 - [INFO] scan_ip add ip:181.192.63.246 time:834
Nov 06 17:11:25.952 - [INFO] scan_ip add ip:173.194.77.191 time:430
Nov 06 17:11:43.024 - [DEBUG] get ip:208.65.154.151 t:395
Nov 06 17:11:45.082 - [DEBUG] create_ssl update ip:208.65.154.151 time:388 h2:1
Nov 06 17:11:45.082 - [DEBUG] get ip:104.237.184.27 t:407
Nov 06 17:11:45.722 - [DEBUG] create_ssl update ip:104.237.184.27 time:400 h2:1
Nov 06 17:11:56.958 - [INFO] scan_ip add ip:181.192.63.211 time:835
Nov 06 17:12:12.448 - [INFO] scan_ip add ip:63.117.215.91 time:773
Nov 06 17:12:13.740 - [INFO] scan_ip add ip:63.135.48.146 time:580
Nov 06 17:12:27.199 - [INFO] scan_ip add ip:103.44.151.58 time:673
Nov 06 17:12:32.687 - [WARNING] 208.65.154.151 _consume_single_frame:SysCallError(10054,'WSAECONNRESET')
Nov 06 17:12:32.687 - [DEBUG] ssl_closed 208.65.154.151
Nov 06 17:12:32.687 - [DEBUG] 208.65.154.151 worker close:disconnect:SysCallError(10054,'WSAECONNRESET')
Nov 06 17:12:35.728 - [DEBUG] get ip:208.65.154.151 t:388
Nov 06 17:12:36.314 - [DEBUG] create_ssl update ip:208.65.154.151 time:391 h2:1
Nov 06 17:12:36.314 - [DEBUG] get ip:189.199.19.33 t:411
Nov 06 17:12:37.005 - [DEBUG] create_ssl update ip:189.199.19.33 time:436 h2:0
Nov 06 17:13:13.844 - [INFO] scan_ip add ip:58.26.8.82 time:690
Nov 06 17:13:23.729 - [WARNING] 208.65.154.151 _consume_single_frame:SysCallError(10054,'WSAECONNRESET')
Nov 06 17:13:23.730 - [DEBUG] ssl_closed 208.65.154.151
Nov 06 17:13:23.730 - [DEBUG] 208.65.154.151 worker close:disconnect:SysCallError(10054,'WSAECONNRESET')
Nov 06 17:13:27.012 - [DEBUG] get ip:208.65.154.151 t:391
Nov 06 17:13:27.982 - [DEBUG] create_ssl update ip:208.65.154.151 time:430 h2:1
Nov 06 17:13:27.982 - [DEBUG] get ip:208.117.237.95 t:424
Nov 06 17:13:28.561 - [DEBUG] create_ssl update ip:208.117.237.95 time:388 h2:1
Nov 06 17:13:30.990 - [INFO] scan_ip add ip:69.160.212.13 time:3150
Nov 06 17:13:48.066 - [DEBUG] appid:xxnet-7-1294 head fail status:502
Nov 06 17:13:48.066 - [DEBUG] report_connect_fail:183.87.151.92
Nov 06 17:13:49.660 - [DEBUG] recheck_ip:183.87.151.92 restore okl
Nov 06 17:13:49.662 - [DEBUG] 183.87.151.92 worker close:keep alive
Nov 06 17:13:59.566 - [DEBUG] restore ip:183.87.151.92
Nov 06 17:14:15.763 - [WARNING] 208.117.237.95 _consume_single_frame:SysCallError(10054,'WSAECONNRESET')
Nov 06 17:14:15.763 - [DEBUG] ssl_closed 208.117.237.95
Nov 06 17:14:15.763 - [DEBUG] 208.117.237.95 worker close:disconnect:SysCallError(10054,'WSAECONNRESET')
Nov 06 17:14:18.567 - [DEBUG] get ip:208.117.237.95 t:388
Nov 06 17:14:19.575 - [INFO] scan_ip add ip:103.15.42.141 time:575
Nov 06 17:14:20.872 - [DEBUG] create_ssl update ip:208.117.237.95 time:391 h2:1
Nov 06 17:14:20.873 - [DEBUG] get ip:173.194.77.191 t:430
Nov 06 17:14:21.621 - [DEBUG] create_ssl update ip:173.194.77.191 time:470 h2:1
Nov 06 17:14:23.734 - [INFO] scan_ip add ip:189.199.103.152 time:825
Nov 06 17:14:26.930 - [INFO] scan_ip add ip:118.98.111.97 time:172
Nov 06 17:14:27.193 - [INFO] scan_ip add ip:61.238.239.222 time:86
Nov 06 17:14:41.700 - [INFO] scan_ip add ip:113.171.245.126 time:169
Nov 06 17:15:08.815 - [WARNING] 208.117.237.95 _consume_single_frame:SysCallError(10054,'WSAECONNRESET')
Nov 06 17:15:08.815 - [DEBUG] ssl_closed 208.117.237.95
Nov 06 17:15:08.816 - [DEBUG] 208.117.237.95 worker close:disconnect:SysCallError(10054,'WSAECONNRESET')
Nov 06 17:15:11.626 - [DEBUG] get ip:61.238.239.222 t:86
Nov 06 17:15:12.093 - [DEBUG] create_ssl update ip:61.238.239.222 time:79 h2:1
Nov 06 17:15:12.093 - [DEBUG] get ip:113.171.245.126 t:169
Nov 06 17:15:12.401 - [DEBUG] create_ssl update ip:113.171.245.126 time:171 h2:0
Nov 06 17:15:29.843 - [INFO] scan_ip add ip:189.199.71.175 time:478
Nov 06 17:15:45.792 - [DEBUG] ssl_closed 104.237.184.27
Nov 06 17:15:45.792 - [DEBUG] 104.237.184.27 worker close:GoAway: additional_data:session_timed_out
Nov 06 17:16:02.453 - [DEBUG] get ip:118.98.111.97 t:172
Nov 06 17:16:02.694 - [DEBUG] create_ssl update ip:118.98.111.97 time:162 h2:0
Nov 06 17:16:02.695 - [DEBUG] get ip:208.117.237.95 t:391
Nov 06 17:16:03.124 - [DEBUG] connect 208.117.237.95 fail:(10054,'WSAECONNRESET') cost:390 h:0
Nov 06 17:16:03.124 - [DEBUG] report_connect_fail:208.117.237.95
Nov 06 17:16:03.125 - [DEBUG] get ip:104.237.184.27 t:400
Nov 06 17:16:03.770 - [DEBUG] create_ssl update ip:104.237.184.27 time:434 h2:1
Nov 06 17:16:13.934 - [DEBUG] restore ip:208.117.237.95
Nov 06 17:16:21.313 - [WARNING] 61.238.239.222 _consume_single_frame:SysCallError(10054,'WSAECONNRESET')
Nov 06 17:16:21.313 - [DEBUG] ssl_closed 61.238.239.222
Nov 06 17:16:21.313 - [DEBUG] 61.238.239.222 worker close:disconnect:SysCallError(10054,'WSAECONNRESET')
Nov 06 17:16:27.235 - [INFO] scan_ip add ip:201.174.96.27 time:421
Nov 06 17:16:28.746 - [DEBUG] 113.171.245.126 keep alive fail, inactive_time:76 head_timeout:21
Nov 06 17:16:28.746 - [DEBUG] report_connect_fail:113.171.245.126
Nov 06 17:16:37.056 - [DEBUG] 113.171.245.126 worker close:keep alive
Nov 06 17:16:38.861 - [INFO] scan_ip add ip:24.244.4.56 time:698
Nov 06 17:16:43.752 - [DEBUG] ip:113.171.245.126 real fail
Nov 06 17:16:44.147 - [INFO] scan_ip add ip:189.197.77.34 time:586
Nov 06 17:16:48.961 - [INFO] scan_ip add ip:201.132.92.42 time:566
Nov 06 17:16:49.624 - [INFO] scan_ip add ip:103.4.111.105 time:706
Nov 06 17:16:51.018 - [WARNING] 104.237.184.27 _consume_single_frame:SysCallError(10054,'WSAECONNRESET')
Nov 06 17:16:51.018 - [DEBUG] ssl_closed 104.237.184.27
Nov 06 17:16:51.018 - [DEBUG] 104.237.184.27 worker close:disconnect:SysCallError(10054,'WSAECONNRESET')
Nov 06 17:16:53.616 - [INFO] scan_ip add ip:216.58.195.97 time:448
Nov 06 17:16:53.776 - [DEBUG] get ip:61.238.239.222 t:79
Nov 06 17:16:57.842 - [DEBUG] 61.238.239.222 fail:timeout('timed out',)
Nov 06 17:16:57.842 - [DEBUG] report_connect_fail:61.238.239.222
Nov 06 17:16:57.843 - [DEBUG] get ip:208.117.237.95 t:394
Nov 06 17:16:58.272 - [DEBUG] connect 208.117.237.95 fail:(10054,'WSAECONNRESET') cost:429 h:0
Nov 06 17:16:58.272 - [DEBUG] report_connect_fail:208.117.237.95
Nov 06 17:16:58.272 - [DEBUG] get ip:201.174.96.27 t:421
Nov 06 17:16:58.943 - [DEBUG] create_ssl update ip:201.174.96.27 time:422 h2:0
Nov 06 17:16:58.943 - [DEBUG] get ip:201.174.48.55 t:434
Nov 06 17:16:59.627 - [DEBUG] create_ssl update ip:201.174.48.55 time:429 h2:0
Nov 06 17:17:12.844 - [DEBUG] ip:61.238.239.222 real fail
Nov 06 17:17:13.669 - [DEBUG] restore ip:208.117.237.95
Nov 06 17:17:19.922 - [INFO] scan_ip add ip:189.193.189.18 time:512
Nov 06 17:17:28.028 - [DEBUG] ssl_closed 208.65.154.151
Nov 06 17:17:28.028 - [DEBUG] 208.65.154.151 worker close:GoAway: additional_data:session_timed_out
Nov 06 17:17:44.097 - [INFO] scan_ip add ip:103.15.42.176 time:625
Nov 06 17:17:45.990 - [INFO] scan_ip add ip:189.199.71.182 time:546
Nov 06 17:17:49.633 - [DEBUG] get ip:208.117.237.95 t:405
Nov 06 17:17:50.476 - [DEBUG] create_ssl update ip:208.117.237.95 time:390 h2:1
Nov 06 17:17:50.476 - [DEBUG] get ip:208.65.154.151 t:430
Nov 06 17:17:51.079 - [DEBUG] create_ssl update ip:208.65.154.151 time:404 h2:1
Nov 06 17:17:51.524 - [INFO] scan_ip add ip:114.130.6.40 time:583
Nov 06 17:17:56.889 - [INFO] scan_ip add ip:63.84.3.51 time:450
Nov 06 17:18:21.700 - [DEBUG] ssl_closed 173.194.77.191
Nov 06 17:18:21.700 - [DEBUG] 173.194.77.191 worker close:GoAway: additional_data:session_timed_out
Nov 06 17:18:25.773 - [INFO] scan_ip add ip:200.94.238.55 time:726
Nov 06 17:18:38.078 - [WARNING] 208.117.237.95 _consume_single_frame:SysCallError(10054,'WSAECONNRESET')
Nov 06 17:18:38.078 - [DEBUG] ssl_closed 208.117.237.95
Nov 06 17:18:38.078 - [DEBUG] 208.117.237.95 worker close:disconnect:SysCallError(10054,'WSAECONNRESET')
Nov 06 17:18:39.089 - [WARNING] 208.65.154.151 _consume_single_frame:SysCallError(10054,'WSAECONNRESET')
Nov 06 17:18:39.090 - [DEBUG] ssl_closed 208.65.154.151
Nov 06 17:18:39.091 - [DEBUG] 208.65.154.151 worker close:disconnect:SysCallError(10054,'WSAECONNRESET')
Nov 06 17:18:41.086 - [DEBUG] get ip:208.117.237.95 t:390
Nov 06 17:18:43.246 - [DEBUG] create_ssl update ip:208.117.237.95 time:401 h2:1
Nov 06 17:18:43.246 - [DEBUG] get ip:208.65.154.151 t:404
Nov 06 17:18:43.834 - [DEBUG] create_ssl update ip:208.65.154.151 time:394 h2:1
Nov 06 17:18:51.378 - [INFO] scan_ip add ip:87.79.22.239 time:717
Nov 06 17:19:12.798 - [INFO] scan_ip add ip:61.238.239.169 time:305
Nov 06 17:19:26.183 - [INFO] scan_ip add ip:177.124.192.94 time:1121
Nov 06 17:19:31.120 - [WARNING] 208.117.237.95 _consume_single_frame:SysCallError(10054,'WSAECONNRESET')
Nov 06 17:19:31.120 - [DEBUG] ssl_closed 208.117.237.95
Nov 06 17:19:31.121 - [DEBUG] 208.117.237.95 worker close:disconnect:SysCallError(10054,'WSAECONNRESET')
Nov 06 17:19:33.840 - [DEBUG] get ip:61.238.239.169 t:305
Nov 06 17:19:33.885 - [INFO] scan_ip add ip:202.4.173.159 time:569
Nov 06 17:19:33.964 - [DEBUG] create_ssl update ip:61.238.239.169 time:85 h2:0
Nov 06 17:19:33.964 - [DEBUG] get ip:208.117.237.95 t:401
Nov 06 17:19:34.597 - [DEBUG] create_ssl update ip:208.117.237.95 time:394 h2:1
Nov 06 17:19:55.124 - [INFO] scan_ip add ip:103.9.105.41 time:677
Nov 06 17:20:01.415 - [INFO] PAC from:127.0.0.1:4928 GET /proxy.pac
Nov 06 17:20:01.416 - [INFO] try download 'https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt' to update_pacfile('F:\\\xd1\xb8\xc0\xd7\xcf\xc2\xd4\xd8\\XX-Net-3.2.7\\data\\gae_proxy\\proxy.pac')
Nov 06 17:20:01.430 - [DEBUG] GAE GET https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt
Nov 06 17:20:01.451 - [DEBUG] get ip:104.237.184.27 t:434
Nov 06 17:20:01.648 - [WARNING] 208.117.237.95 _consume_single_frame:SysCallError(10054,'WSAECONNRESET')
Nov 06 17:20:01.648 - [DEBUG] ssl_closed 208.117.237.95
Nov 06 17:20:01.648 - [DEBUG] 208.117.237.95 worker close:disconnect:SysCallError(10054,'WSAECONNRESET')
Nov 06 17:20:01.950 - [DEBUG] get ip:69.46.66.31 t:438
Nov 06 17:20:02.452 - [DEBUG] get ip:216.58.195.212 t:446
Nov 06 17:20:02.954 - [DEBUG] get ip:216.58.195.97 t:448
Nov 06 17:20:03.101 - [DEBUG] create_ssl update ip:216.58.195.212 time:416 h2:1
Nov 06 17:20:03.301 - [DEBUG] create_ssl update ip:104.237.184.27 time:403 h2:1
Nov 06 17:20:03.438 - [DEBUG] create_ssl update ip:69.46.66.31 time:697 h2:1
Nov 06 17:20:03.457 - [DEBUG] get ip:63.84.3.51 t:450
Nov 06 17:20:03.575 - [DEBUG] create_ssl update ip:216.58.195.97 time:413 h2:1
Nov 06 17:20:03.957 - [DEBUG] get ip:189.199.19.25 t:450
Nov 06 17:20:04.068 - [DEBUG] 118.98.111.97 keep alive fail, inactive_time:241 head_timeout:21
Nov 06 17:20:04.068 - [DEBUG] report_connect_fail:118.98.111.97
Nov 06 17:20:04.102 - [DEBUG] get ip:216.58.194.93 t:459
Nov 06 17:20:04.215 - [DEBUG] create_ssl update ip:63.84.3.51 time:461 h2:0
Nov 06 17:20:04.303 - [DEBUG] get ip:173.194.77.191 t:470
Nov 06 17:20:04.439 - [DEBUG] get ip:216.58.192.199 t:472
Nov 06 17:20:04.460 - [DEBUG] get ip:208.117.237.95 t:394
Nov 06 17:20:04.575 - [DEBUG] get ip:201.167.5.216 t:472
Nov 06 17:20:04.601 - [DEBUG] get ip:189.199.71.175 t:478
Nov 06 17:20:04.846 - [DEBUG] create_ssl update ip:216.58.194.93 time:407 h2:1
Nov 06 17:20:04.907 - [DEBUG] connect 208.117.237.95 fail:(10054,'WSAECONNRESET') cost:427 h:0
Nov 06 17:20:04.907 - [DEBUG] report_connect_fail:208.117.237.95
Nov 06 17:20:04.908 - [DEBUG] get ip:189.198.250.31 t:483
Nov 06 17:20:04.942 - [DEBUG] create_ssl update ip:173.194.77.191 time:426 h2:1
Nov 06 17:20:04.960 - [DEBUG] get ip:201.174.96.76 t:486
Nov 06 17:20:05.104 - [DEBUG] create_ssl update ip:189.199.19.25 time:485 h2:0
Nov 06 17:20:05.132 - [DEBUG] create_ssl update ip:216.58.192.199 time:462 h2:1
Nov 06 17:20:05.216 - [DEBUG] get ip:67.221.221.142 t:491
Nov 06 17:20:05.461 - [DEBUG] get ip:201.174.97.25 t:491
Nov 06 17:20:05.625 - [DEBUG] create_ssl update ip:189.198.250.31 time:467 h2:1
Nov 06 17:20:05.644 - [DEBUG] create_ssl update ip:201.174.96.76 time:442 h2:0
Nov 06 17:20:05.715 - [DEBUG] create_ssl update ip:189.199.71.175 time:541 h2:0
Nov 06 17:20:05.716 - [DEBUG] get ip:201.167.56.239 t:492
Nov 06 17:20:05.813 - [DEBUG] create_ssl update ip:201.167.5.216 time:504 h2:0
Nov 06 17:20:05.846 - [DEBUG] get ip:189.193.189.142 t:500
Nov 06 17:20:05.948 - [DEBUG] get ip:64.233.180.145 t:500
Nov 06 17:20:05.962 - [DEBUG] get ip:189.199.71.43 t:500
Nov 06 17:20:06.106 - [DEBUG] get ip:216.58.193.18 t:502
Nov 06 17:20:06.143 - [DEBUG] get ip:189.215.132.22 t:503
Nov 06 17:20:06.274 - [DEBUG] create_ssl update ip:201.174.97.25 time:445 h2:1
Nov 06 17:20:06.388 - [DEBUG] create_ssl update ip:67.221.221.142 time:450 h2:0
Nov 06 17:20:06.415 - [DEBUG] ssl_closed 61.238.239.209
Nov 06 17:20:06.415 - [DEBUG] 61.238.239.209 worker close:idle timeout
Nov 06 17:20:06.488 - [DEBUG] create_ssl update ip:201.167.56.239 time:485 h2:0
Nov 06 17:20:06.653 - [DEBUG] create_ssl update ip:189.193.189.142 time:539 h2:0
Nov 06 17:20:06.675 - [DEBUG] ssl_closed 115.254.106.210
Nov 06 17:20:06.675 - [DEBUG] 115.254.106.210 worker close:idle timeout
Nov 06 17:20:07.298 - [DEBUG] create_ssl update ip:216.58.193.18 time:430 h2:1
Nov 06 17:20:07.299 - [DEBUG] create_ssl update ip:189.215.132.22 time:542 h2:0
Nov 06 17:20:08.074 - [DEBUG] create_ssl update ip:189.199.71.43 time:517 h2:0
Nov 06 17:20:08.443 - [DEBUG] create_ssl update ip:64.233.180.145 time:467 h2:1
Nov 06 17:20:10.143 - [DEBUG] 118.98.111.97 worker close:keep alive
Nov 06 17:20:11.905 - [INFO] scan_ip add ip:50.86.10.110 time:2815
Nov 06 17:20:16.188 - [INFO] scan_ip add ip:203.176.178.33 time:217
Nov 06 17:20:19.069 - [DEBUG] ip:118.98.111.97 real fail
Nov 06 17:20:19.900 - [DEBUG] restore ip:208.117.237.95
Nov 06 17:20:23.692 - [INFO] scan_ip add ip:189.203.232.40 time:631
Nov 06 17:20:25.099 - [INFO] scan_ip add ip:201.174.97.56 time:424
Nov 06 17:20:31.122 - [INFO] scan_ip add ip:114.130.6.54 time:604
Nov 06 17:20:46.555 - [INFO] scan_ip add ip:202.134.14.91 time:866
Nov 06 17:20:52.931 - [INFO] scan_ip add ip:216.254.140.52 time:700
Nov 06 17:20:56.505 - [DEBUG] get ip:203.176.178.33 t:217
Nov 06 17:20:56.966 - [DEBUG] create_ssl update ip:203.176.178.33 time:197 h2:0
Nov 06 17:20:56.966 - [DEBUG] get ip:61.238.239.209 t:220
Nov 06 17:20:57.081 - [DEBUG] create_ssl update ip:61.238.239.209 time:74 h2:0
Nov 06 17:20:57.139 - [DEBUG] ssl_closed 113.171.253.147
Nov 06 17:20:57.139 - [DEBUG] 113.171.253.147 worker close:idle timeout
Nov 06 17:20:57.425 - [DEBUG] ssl_closed 201.165.221.83
Nov 06 17:20:57.425 - [DEBUG] 201.165.221.83 worker close:idle timeout
Nov 06 17:21:47.087 - [DEBUG] get ip:113.171.253.147 t:203
Nov 06 17:21:48.111 - [DEBUG] create_ssl update ip:113.171.253.147 time:201 h2:0
Nov 06 17:21:48.111 - [DEBUG] get ip:115.254.106.210 t:265
Nov 06 17:21:48.556 - [DEBUG] create_ssl update ip:115.254.106.210 time:272 h2:0
Nov 06 17:21:55.846 - [INFO] scan_ip add ip:186.226.128.168 time:854
Nov 06 17:22:05.202 - [INFO] scan_ip add ip:189.197.79.116 time:561
Nov 06 17:22:09.811 - [INFO] scan_ip add ip:202.75.147.20 time:363
Nov 06 17:22:13.523 - [DEBUG] 61.238.239.209 keep alive fail, inactive_time:76 head_timeout:21
Nov 06 17:22:13.523 - [DEBUG] report_connect_fail:61.238.239.209
Nov 06 17:22:14.687 - [INFO] scan_ip add ip:189.199.103.47 time:598
Nov 06 17:22:19.015 - [DEBUG] 61.238.239.209 worker close:keep alive
Nov 06 17:22:28.527 - [DEBUG] ip:61.238.239.209 real fail
Nov 06 17:22:38.567 - [DEBUG] get ip:202.75.147.20 t:363
Nov 06 17:22:39.154 - [DEBUG] create_ssl update ip:202.75.147.20 time:379 h2:0
Nov 06 17:22:39.155 - [DEBUG] get ip:208.117.237.95 t:394
Nov 06 17:22:39.786 - [DEBUG] create_ssl update ip:208.117.237.95 time:395 h2:1
Nov 06 17:22:41.388 - [DEBUG] ssl_closed 189.199.19.33
Nov 06 17:22:41.388 - [DEBUG] 189.199.19.33 worker close:idle timeout
Nov 06 17:23:21.835 - [INFO] scan_ip add ip:50.86.10.96 time:558
Nov 06 17:23:29.800 - [DEBUG] get ip:201.174.97.56 t:424
Nov 06 17:23:30.440 - [DEBUG] create_ssl update ip:201.174.97.56 time:430 h2:0
Nov 06 17:23:30.441 - [DEBUG] get ip:201.165.221.83 t:434
Nov 06 17:23:31.091 - [DEBUG] create_ssl update ip:201.165.221.83 time:387 h2:0
Nov 06 17:23:32.222 - [INFO] scan_ip add ip:103.21.169.252 time:205
Nov 06 17:23:36.666 - [INFO] scan_ip add ip:189.215.132.49 time:605
Nov 06 17:23:58.621 - [INFO] scan_ip add ip:186.46.140.126 time:800
Nov 06 17:24:02.649 - [WARNING] 208.65.154.151 _consume_single_frame:ConnectionResetError()
Nov 06 17:24:02.649 - [WARNING] get body fail, left:95735 https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt
Nov 06 17:24:02.650 - [INFO] GAE t:241218 s:143825 GET https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt get_response:274
Nov 06 17:24:02.650 - [DEBUG] ssl_closed 208.65.154.151
Nov 06 17:24:02.650 - [DEBUG] 208.65.154.151 worker close:disconnect:ConnectionResetError()
Nov 06 17:24:02.651 - [ERROR] update_pacfile failed: TypeError(Error('Incorrect padding',),)
Nov 06 17:24:02.676 - [ERROR] Except stack:Traceback (most recent call last): File "F:\\XX-Net-3.2.7\code\default\gae_proxy\local\pac_server.py", line 110, in update_pacfile autoproxy_content = base64.b64decode(pac_content) File "F:\\XX-Net-3.2.7\code\default\python27\1.0\lib\base64.py", line 77, in b64decode raise TypeError(msg) TypeError: Incorrect padding
Nov 06 17:24:03.153 - [DEBUG] ssl_closed 216.58.195.212
Nov 06 17:24:03.153 - [DEBUG] 216.58.195.212 worker close:GoAway: additional_data:session_timed_out
Nov 06 17:24:03.409 - [DEBUG] ssl_closed 104.237.184.27
Nov 06 17:24:03.409 - [DEBUG] 104.237.184.27 worker close:GoAway: additional_data:session_timed_out
Nov 06 17:24:03.412 - [DEBUG] ssl_closed 69.46.66.31
Nov 06 17:24:03.412 - [DEBUG] 69.46.66.31 worker close:GoAway: additional_data:session_timed_out
Nov 06 17:24:03.686 - [DEBUG] ssl_closed 216.58.195.97
Nov 06 17:24:03.686 - [DEBUG] 216.58.195.97 worker close:GoAway: additional_data:session_timed_out
Nov 06 17:24:04.872 - [DEBUG] ssl_closed 216.58.194.93
Nov 06 17:24:04.872 - [DEBUG] 216.58.194.93 worker close:GoAway: additional_data:session_timed_out
Nov 06 17:24:05.155 - [DEBUG] ssl_closed 216.58.192.199
Nov 06 17:24:05.155 - [DEBUG] 216.58.192.199 worker close:GoAway: additional_data:session_timed_out
Nov 06 17:24:05.194 - [WARNING] 173.194.77.191 _consume_single_frame:ConnectionResetError()
Nov 06 17:24:05.195 - [DEBUG] ssl_closed 173.194.77.191
Nov 06 17:24:05.195 - [DEBUG] 173.194.77.191 worker close:disconnect:ConnectionResetError()
Nov 06 17:24:05.645 - [DEBUG] ssl_closed 189.198.250.31
Nov 06 17:24:05.645 - [DEBUG] 189.198.250.31 worker close:GoAway: additional_data:session_timed_out
Nov 06 17:24:06.299 - [DEBUG] ssl_closed 201.174.97.25
Nov 06 17:24:06.299 - [DEBUG] 201.174.97.25 worker close:GoAway: additional_data:session_timed_out
Nov 06 17:24:07.324 - [DEBUG] ssl_closed 216.58.193.18
Nov 06 17:24:07.324 - [DEBUG] 216.58.193.18 worker close:GoAway: additional_data:session_timed_out
Nov 06 17:24:08.538 - [DEBUG] ssl_closed 64.233.180.145
Nov 06 17:24:08.538 - [DEBUG] 64.233.180.145 worker close:GoAway: additional_data:session_timed_out

**Comment by jzp820927** [comment]
看日志也没发现啥问题。或者你手动设置代理试试看

**Comment by Hollykitty** [comment]
@863233821 这个问题确实暂时没解决办法，我比较早的时候就反馈过，里面的答案都没用，手动一次次设置太麻烦了~#4371

**Comment by jzp820927** [comment]
或者可以试试网站找下，有没有第三方用来设置代理的工具。
