### ISSUE TITLE
win10 14939双击start.vbs无任何反应

### ISSUE THREAD

**Issue by kimishen2008** [XX-net/XX-Net#4512]
如题，从3.2.7开始，现在是3.2.8，问题依旧。应管理员模式启动start.bat是可以运行的，但是命令窗口不能隐藏。但是点击start.vbs就是无任何反应，这个文件也无法修改成管理员模式启动。
用命令行 运行default\python27\1.0\python.exe code\default\launcher\start.py得到的反馈是
Traceback (most recent call last):
  File "code\default\launcher\start.py", line 37, in <module>
    from instances import xlog
  File "C:\Program Files (x86)\XX-Net-3.2.8\code\default\launcher\instances.py", line 12, in <module>
    xlog = Logger(file_name=log_file)
  File "C:\Program Files (x86)\XX-Net-3.2.8\code\default\python27\1.0\lib\noarch\xlog.py", line 35, in __init__
    self.set_file(file_name)
  File "C:\Program Files (x86)\XX-Net-3.2.8\code\default\python27\1.0\lib\noarch\xlog.py", line 90, in set_file
    self.log_fd = open(file_name, "w")
IOError: [Errno 13] Permission denied: 'C:\\Program Files (x86)\\XX-Net-3.2.8\\data\\launcher\\launcher.log'

**Comment by SeaHOH** [comment]
在 .vbs 文件前端添加一下代码：
>If WScript.Arguments.length = 0 Then
  '无参数传入时运行
  Set objShell = CreateObject("Shell.Application")
  '以管理员权限重新运行本脚本。
  objShell.ShellExecute "wscript.exe", Chr(34) & WScript.ScriptFullName & Chr(34) & " uac", "", "runas", 1
  Set objShell = NoThing
  WScript.quit
End If

**Comment by kimishen2008** [comment]
试了，没什么用

**Comment by jzp820927** [comment]
Win 10 的问题挺多的

**Comment by SeaHOH** [comment]
start.vbs 的代码四个月没改动了，应该是你的系统有变动。
还有检查一下 ``XX-Net-3.2.8`` 这个文件夹的权限。

**Comment by UltraDWS** [comment]
@kimishen2008 我也是1607，你解压完了注意检查start.vbs的文件安全属性，如果是锁定文件就解锁，然后在目录里搜python.exe和pythonw.exe确保他们也是解锁状态，然后管理员权限运行start.vbs，在这些之前最好删除旧证书，让start.vbs加载的时候重新添加新证书。

**Comment by UltraDWS** [comment]
我是直接1511易升升级的1607，没毛病，全数功能正常。
