### ISSUE TITLE
Macbook昨天自动升级了 今天就打不开XX了……

### ISSUE THREAD

**Issue by ydl825312** [XX-net/XX-Net#4535]
用的稳定版3.2.7
双击start
Last login: Fri Nov 11 13:51:06 on ttys000
mactekiMacBook-Pro:~ mac$ /Users/mac/Desktop/XX-Net-3.2.7/start ; exit;
Python 2.7.10
XX-Net version:default
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

用./start命令
mactekiMacBook-Pro:XX-Net-3.2.7 mac$ ./start
Python 2.7.10
XX-Net version:default

然后就没有然后了 ……好气啊……是因为macbook更新系统的问题么

**Comment by jzp820927** [comment]
90% 可能性是因为升级 MAC 造成的，以前也有人反映过，一升级就用不了了。这个是 MAC 系统的问题，和XX没关系了

**Comment by hzxie** [comment]
Ref #4471

**Comment by ydl825312** [comment]
@jzp820927 
运行后如下
mactekiMacBook-Pro:launcher mac$ python /Users/mac/Desktop/XX-Net-3.2.7/code/default/launcher/start.py 
Nov 14 10:11:11.398 - [INFO] use build-in openssl lib
Nov 14 10:11:11.399 - [INFO] start XX-Net 3.2.7
Nov 14 10:11:11.399 - [DEBUG] start confirm_xxnet_exit
Nov 14 10:11:11.402 - [DEBUG] <0>: try to terminate xxnet:8087
Nov 14 10:11:12.407 - [DEBUG] good, xxnet:8087 cleared!
Nov 14 10:11:12.408 - [DEBUG] good, xxnet:8085 clear!
Nov 14 10:11:12.408 - [DEBUG] finished confirm_xxnet_exit
Nov 14 10:11:12.462 - [INFO] SSL use version:TLSv1
Nov 14 10:11:12.464 - [INFO] OpenSSL support alpn
Nov 14 10:11:12.465 - [INFO] load ip range file:/Users/mac/Desktop/XX-Net-3.2.7/code/default/gae_proxy/local/ip_range.txt
Nov 14 10:11:12.523 - [INFO] load google ip_list num:2304, gws num:2304
Nov 14 10:11:12.536 - [INFO] OpenSSL support alpn
Nov 14 10:11:12.537 - [DEBUG] get ip:202.86.162.172 t:73
Nov 14 10:11:12.540 - [DEBUG] get ip:61.238.239.250 t:179
Nov 14 10:11:12.546 - [DEBUG] ## GAEProxy set keep_running: True
Nov 14 10:11:12.546 - [INFO] ------------------------------------------------------
Nov 14 10:11:12.546 - [INFO] Python Version     : 2.7.10
Nov 14 10:11:12.547 - [INFO] OS                 : Release:10.12.1; Version:('', '', '') Machine:x86_64
Nov 14 10:11:12.547 - [INFO] Listen Address     : 127.0.0.1:8087
Nov 14 10:11:12.547 - [INFO] GAE APPID          : ydl825312|ydl82531201||ydl82531202|ydl82531203|ydl82531204|ydl82531205|ydl82531206|ydl82531207|ydl82531208|ydl82531209
Nov 14 10:11:12.547 - [INFO] Pac Server         : http://127.0.0.1:8086/proxy.pac
Nov 14 10:11:12.547 - [INFO] ------------------------------------------------------
Nov 14 10:11:12.590 - [INFO] try auto import CA command:osascript -e 'do shell script "security delete-certificate -Z 3658FB97B142189961807771DEC31FEF6B880273;security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain ../../../../data/gae_proxy/CA.crt" with administrator privileges' 
Nov 14 10:11:12.669 - [DEBUG] create_ssl update ip:202.86.162.172 time:90 h2:1
Nov 14 10:11:12.669 - [DEBUG] get ip:59.18.45.190 t:187
Nov 14 10:11:12.805 - [DEBUG] create_ssl update ip:61.238.239.250 time:186 h2:0
Nov 14 10:11:12.928 - [DEBUG] create_ssl update ip:59.18.45.190 time:178 h2:0
Nov 14 10:11:13.508 - [DEBUG] network is ok, cost:1080 ms

Nov 14 10:11:15.646 - [INFO] server 127.0.0.1:8087 started.
Nov 14 10:11:15.646 - [INFO] server 127.0.0.1:8086 started.
Nov 14 10:11:15.730 - [INFO] module gae_proxy started
Nov 14 10:11:15.730 - [INFO] start gae_proxy time cost:3322 ms
WARNING:root:Load Crypto.Cipher.ARC4 Failed, Use Pure Python Instead.
Nov 14 10:11:15.738 - [INFO] use config_path:/Users/mac/Desktop/XX-Net-3.2.7/data/x_tunnel/client.json
Nov 14 10:11:15.738 - [INFO] Use proxy:127.0.0.1:8087
Nov 14 10:11:15.738 - [DEBUG] x-tunnel no account
Nov 14 10:11:15.738 - [WARNING] x-tunnel session not start
Nov 14 10:11:15.738 - [ERROR] bind to 127.0.0.1:1080 fail:error(48, 'Address already in use')
Exception in thread Thread-61:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/mac/Desktop/XX-Net-3.2.7/code/default/x_tunnel/start.py", line 19, in main
    client.main()
  File "/Users/mac/Desktop/XX-Net-3.2.7/code/default/x_tunnel/local/client.py", line 154, in main
    g.socks5_server = simple_http_server.HTTPServer((g.config.socks_host, g.config.socks_port), Socks5Server)
  File "/Users/mac/Desktop/XX-Net-3.2.7/code/default/python27/1.0/lib/noarch/simple_http_server.py", line 263, in __init__
    self.init_socket()
  File "/Users/mac/Desktop/XX-Net-3.2.7/code/default/python27/1.0/lib/noarch/simple_http_server.py", line 268, in init_socket
    self.add_listen(addr)
  File "/Users/mac/Desktop/XX-Net-3.2.7/code/default/python27/1.0/lib/noarch/simple_http_server.py", line 278, in add_listen
    raise Exception(err_string)
Exception: bind to 127.0.0.1:1080 fail:error(48, 'Address already in use')

Nov 14 10:11:41.559 - [DEBUG] GAEProxy Web_control 127.0.0.1:51739 GET /quit 
Nov 14 10:11:41.720 - [INFO] Exiting gae_proxy module...
Exception in thread Thread-59:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/mac/Desktop/XX-Net-3.2.7/code/default/python27/1.0/lib/noarch/simple_http_server.py", line 301, in serve_forever
    r, w, e = select.select(self.sockets, [], [], 3)
error: (9, 'Bad file descriptor')

Exception in thread Thread-60:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/mac/Desktop/XX-Net-3.2.7/code/default/python27/1.0/lib/noarch/simple_http_server.py", line 301, in serve_forever
    r, w, e = select.select(self.sockets, [], [], 3)
error: (9, 'Bad file descriptor')

Nov 14 10:11:41.721 - [DEBUG] ## GAEProxy set keep_running: False
Nov 14 10:11:41.918 - [INFO] scan_ip add ip:92.226.2.104 time:3372

有一个Error： Exception: bind to 127.0.0.1:1080 fail:error(48, 'Address already in use')

神烦

**Comment by ydl825312** [comment]
雾草…………我能翻墙了 但是没有XXnet的图标   然后http://127.0.0.1:8085/进不去 这是什么鬼

@jzp820927

**Comment by ydl825312** [comment]
3.2.8也试过 不行   但是貌似运行python code/default/launcher/start.py后可以翻墙了   不过没有xx的图标 XX的设置页面也进不去
@hzxie

**Comment by jzp820927** [comment]
通过终端运行是没有图标的。8085 打不开，你是不是通过代理打开的？

**Comment by ydl825312** [comment]
@jzp820927 直连的啊……eggache

**Comment by jzp820927** [comment]
那你可以检查下 8085 端口是否已经监听

**Comment by ydl825312** [comment]
活动监视器里 pid按大小排列 没有发现8085端口 
![default](https://cloud.githubusercontent.com/assets/12187279/20256334/c51dd35c-aa7d-11e6-9c0e-1b7128c4b969.jpeg)

要怎么办啊

**Comment by jzp820927** [comment]
这个不是看监听的，终端运行 netstat -tlnp 看看

**Comment by ydl825312** [comment]
运行netstat -tlnp 回车没任何反应 
然后网上找了lsof命令
运行如图
![default](https://cloud.githubusercontent.com/assets/12187279/20256788/9fd3c3e2-aa80-11e6-9ff8-f039a1dfb2dd.jpeg)

**Comment by ydl825312** [comment]
还有个问题就是 我把3.2.7文件夹删了 重新下载了3.2.8 重启电脑 没有运行3.2.8  然后还是能翻墙？惊了……

**Comment by jzp820927** [comment]
只有 8087 和 8086，没有 8085

**Comment by ydl825312** [comment]
对啊……所以我现在要怎么办

**Comment by jzp820927** [comment]
不好确定问题原因，日志也没有，看看  data/gae_proxy 下面有没有日志文件

**Comment by ydl825312** [comment]
log文件只有个scan_ip  还有个good_ip文本

**Comment by jzp820927** [comment]
需要看看启动时的日志，应该是启动时候，哪儿出问题了

**Comment by ydl825312** [comment]
没有……启动时候没有日志 不管是直接运行start还是通过终端运行  但是我还是能翻墙……8085还是进不去

**Comment by ydl825312** [comment]
把所有有关服务强制退出 然后重启  不能翻墙
然后直接运行start 依然没有xxnet图标 没有8085设置页面 但是可以翻墙
所以就是运行start是有用的 但是只是没有设置页
所以这是为毛啊………………我想要设置页啊

**Comment by jzp820927** [comment]
那我也不太清楚了，没有 MAC 机器，没法测试。等高手来帮你解决吧

**Comment by ydl825312** [comment]
只能这样了……

**Comment by vvzwvv** [comment]
我遇到一样的问题：
[ERROR] bind to 127.0.0.1:1080 fail:error(48, 'Address already in use')
因为之前装了Shadowsocks，1080端口被ss-local占用。
先运行lsof -i:1080看下ss-local的PID。
由于ss-local的父进程是launchd，用kill -9杀不死，所以执行launchctl list，找到对应ss-local PID的那个Label，我的是com.qiuyuzhou.shadowsocksX-NG.local，在运行launchctl remove com.qiuyuzhou.shadowsocksX-NG.local就可以解除占用了。
之后直接打开start就能进入XX-Net设置页面。

**Comment by ydl825312** [comment]
@vvzwvv 厉害！解决了！真想给你一个么么哒！谢谢！
