### ISSUE TITLE
部署APPID时一直显示“正在部署”，无法完成（已解决）

### ISSUE THREAD

**Issue by publiclasss** [XX-net/XX-Net#4577]
#### 问题已解决
申请了第二个APPID，点击“开始部署”后没有弹出授权窗口，一直显示“正在部署”
（Chrome浏览器最新版，已允许弹窗）
开了蓝灯后进行部署，还是碰到一样的问题。似乎跟部署时是否翻墙没有关系。

1. 日志说“root - ERROR - upload fail:ValidationError("Value '600' for response_code is out of range 100 - 599",)” 是出了什么问题？
2. 日志说“Authenticate skipped auth; needs_auth=False”，是不是无需授权于是跳过了它？

#### 诊断信息
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.14393
os-system: Windows
os-version: 10.0.14393
os-release: 10
os-detail: Version:10-0; Build:14393; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36
xxnet-version: 3.2.7

python-version: 2.7.11
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 1
gws-ip-num: total:12540 good:77
network-status: OK
connected-link: new:3 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 0
ip-quality: 410
is-idle: 1
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: false
Appids_Out_Of_Quota: true
Appids_Not_Exist: false
Using_Public_Appid: false

#### 部署日志
2016-11-17 15:10:26,545 - root - INFO - enable debug logging
2016-11-17 15:10:26,546 - root - INFO - set proxy to http://127.0.0.1:8087
2016-11-17 15:10:26,549 - root - INFO - ============ Begin upload ============
2016-11-17 15:10:26,549 - root - INFO - appid:xx-net2-******
2016-11-17 15:10:26,582 - root - INFO - Send: /api/appversion/rollback, params={'version': '1', 'app_id': 'xx-net2-******'}
2016-11-17 15:10:26,584 - google.appengine.tools.appengine_rpc - DEBUG - _Authenticate skipped auth; needs_auth=False
2016-11-17 15:10:26,584 - google.appengine.tools.appengine_rpc - DEBUG - Sending request to https://appengine.google.com/api/appversion/rollback?app_id=xx-net2-******&force_rollback=0&version=1 headers={'X-appcfg-api-version': '1', 'content-length': '0', 'Content-Type': 'application/octet-stream'} body=
2016-11-17 15:18:46,944 - google.appengine.tools.appengine_rpc - DEBUG - Got http error 600.
2016-11-17 15:18:46,946 - google.appengine.tools.appengine_rpc - DEBUG - Unexpected results: {'status': '600', 'content-length': '131', 'connection': 'close'}
2016-11-17 15:18:46,947 - root - ERROR - upload fail:ValidationError("Value '600' for response_code is out of range 100 - 599",)
Traceback (most recent call last):
File "C:\Users\Downloads\XX-Net-3.1.19\code\3.2.7\gae_proxy\server\uploader.py", line 70, in upload
result = appcfg.AppCfgApp(['appcfg', 'rollback', dirname ]).Run()
File "C:\Users\Downloads\XX-Net-3.1.19\code\3.2.7\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 2951, in Run
self.action(self)
File "C:\Users\Downloads\XX-Net-3.1.19\code\3.2.7\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 5044, in __call__
return method()
File "C:\Users\Downloads\XX-Net-3.1.19\code\3.2.7\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 4397, in Rollback
self._Rollback()
File "C:\Users\Downloads\XX-Net-3.1.19\code\3.2.7\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 4442, in _Rollback
appversion.Rollback(force_rollback)
File "C:\Users\Downloads\XX-Net-3.1.19\code\3.2.7\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 2362, in Rollback
force_rollback='1' if force_rollback else '0')
File "C:\Users\Downloads\XX-Net-3.1.19\code\3.2.7\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 1702, in Send
request_size_bytes)
File "C:\Users\Downloads\XX-Net-3.1.19\code\3.2.7\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 1723, in _RegisterReqestForLogging
request_size_bytes=request_size_bytes))
File "C:\Users\Downloads\XX-Net-3.1.19\code\3.2.7\gae_proxy\server\lib\google\appengine\api\validation.py", line 273, in __init__
self.SetMultiple(attributes)
File "C:\Users\Downloads\XX-Net-3.1.19\code\3.2.7\gae_proxy\server\lib\google\appengine\api\validation.py", line 177, in SetMultiple
self.Set(key, value)
File "C:\Users\Downloads\XX-Net-3.1.19\code\3.2.7\gae_proxy\server\lib\google\appengine\api\validation.py", line 305, in Set
setattr(self, key, value)
File "C:\Users\Downloads\XX-Net-3.1.19\code\3.2.7\gae_proxy\server\lib\google\appengine\api\validation.py", line 361, in __setattr__
value = self.GetValidator(key)(value, key)
File "C:\Users\Downloads\XX-Net-3.1.19\code\3.2.7\gae_proxy\server\lib\google\appengine\api\validation.py", line 599, in __call__
return self.Validate(value, key)
File "C:\Users\Downloads\XX-Net-3.1.19\code\3.2.7\gae_proxy\server\lib\google\appengine\api\validation.py", line 1157, in Validate
% (value, key, self.minimum, self.maximum))
ValidationError: Value '600' for response_code is out of range 100 - 599
2016-11-17 15:18:46,986 - root - INFO - Retry 1 time...

**Comment by jzp820927** [comment]
没有弹窗肯定是不行的，必须浏览器弹窗登录授权以后，才能部署。不知道你是用的什么浏览器操作的

**Comment by publiclasss** [comment]
@jzp820927 用的是Chrome；部署第一个APPID时有弹窗，这次就没有了，很奇怪

**Comment by jzp820927** [comment]
你的意思，以前用这个浏览器成功部署过？

**Comment by publiclasss** [comment]
@jzp820927 是的。
刚才解决了，其实是CA证书的问题，下载证书安装后就好了；感谢帮助=D

**Comment by SeaHOH** [comment]
解决了就关闭吧
