### ISSUE TITLE
xxnet突然无法启动

### ISSUE THREAD

**Issue by jang-u** [XX-net/XX-Net#4646]
3.26、3.27、3.28同样问题同样提示
python窗口信息如下

```
Nov xx xx:19:40.017 - [INFO] use build-in openssl lib
Nov xx xx:19:40.017 - [INFO] start XX-Net 3.2.8
Nov xx xx:19:40.017 - [DEBUG] start confirm_xxnet_exit
Nov xx xx:19:41.037 - [DEBUG] good, xxnet:8087 cleared!
Nov xx xx:19:41.037 - [DEBUG] <0>: try to terminate xxnet:8085
Nov xx xx:19:42.037 - [DEBUG] <1>: try to terminate xxnet:8085
Nov xx xx:19:43.037 - [DEBUG] <2>: try to terminate xxnet:8085
Nov xx xx:19:44.037 - [DEBUG] <3>: try to terminate xxnet:8085
Nov xx xx:19:45.037 - [DEBUG] <4>: try to terminate xxnet:8085
Nov xx xx:19:46.037 - [DEBUG] <5>: try to terminate xxnet:8085
Nov xx xx:19:47.037 - [DEBUG] <6>: try to terminate xxnet:8085
Nov xx xx:19:48.043 - [DEBUG] <7>: try to terminate xxnet:8085
Nov xx xx:19:49.043 - [DEBUG] <8>: try to terminate xxnet:8085
Nov xx xx:19:50.043 - [DEBUG] <9>: try to terminate xxnet:8085
Nov xx xx:19:51.043 - [DEBUG] <10>: try to terminate xxnet:8085
Nov xx xx:19:52.043 - [DEBUG] <11>: try to terminate xxnet:8085
Nov xx xx:19:53.043 - [DEBUG] <12>: try to terminate xxnet:8085
Nov xx xx:19:54.043 - [DEBUG] <13>: try to terminate xxnet:8085
Nov xx xx:19:55.043 - [DEBUG] <14>: try to terminate xxnet:8085
Nov xx xx:19:56.046 - [DEBUG] <15>: try to terminate xxnet:8085
Nov xx xx:19:57.046 - [DEBUG] <16>: try to terminate xxnet:8085
Nov xx xx:19:58.046 - [DEBUG] <17>: try to terminate xxnet:8085
Nov xx xx:19:59.049 - [DEBUG] <18>: try to terminate xxnet:8085
Nov xx xx:20:00.056 - [DEBUG] <19>: try to terminate xxnet:8085
Nov xx xx:20:01.056 - [DEBUG] <20>: try to terminate xxnet:8085
Nov xx xx:20:02.056 - [DEBUG] <21>: try to terminate xxnet:8085
Nov xx xx:20:03.056 - [DEBUG] <22>: try to terminate xxnet:8085
Nov xx xx:20:04.056 - [DEBUG] <23>: try to terminate xxnet:8085
Nov xx xx:20:05.056 - [DEBUG] <24>: try to terminate xxnet:8085
Nov xx xx:20:06.060 - [DEBUG] <25>: try to terminate xxnet:8085
Nov xx xx:20:07.060 - [DEBUG] <26>: try to terminate xxnet:8085
Nov xx xx:20:08.060 - [DEBUG] <27>: try to terminate xxnet:8085
Nov xx xx:20:09.060 - [DEBUG] <28>: try to terminate xxnet:8085
Nov xx xx:20:10.060 - [DEBUG] <29>: try to terminate xxnet:8085
Nov xx xx:20:11.060 - [DEBUG] finished confirm_xxnet_exit
Nov xx xx:20:11.070 - [INFO] load config.ini success
Nov xx xx:20:11.390 - [INFO] SSL use version:TLSv1_2
Nov xx xx:20:12.410 - [INFO] OpenSSL support alpn
Nov xx xx:20:12.410 - [INFO] load ip range file:x:\XX-Net-3.2.8\code\default\gae_proxy\local\ip_range.txt
Nov xx xx:20:12.450 - [INFO] load google ip_list num:3000, gws num:3000
Nov xx xx:20:12.460 - [INFO] OpenSSL support alpn
Nov xx xx:20:12.460 - [DEBUG] get ip:202.75.147.30 t:310
Nov xx xx:20:12.460 - [DEBUG] get ip:84.208.42.236 t:450
Nov xx xx:20:12.470 - [INFO] load config.ini success
Nov xx xx:20:12.470 - [DEBUG] ## GAEProxy set keep_running: True
Nov xx xx:20:12.470 - [INFO] ------------------------------------------------------
Nov xx xx:20:12.470 - [INFO] Python Version     : 2.7.11
Nov xx xx:20:12.470 - [INFO] OS                 : Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:256; ProductType:0
Nov xx xx:20:12.470 - [INFO] Listen Address     : 127.0.0.1:8087
Nov xx xx:20:12.470 - [INFO] GAE APPID          : x1:x2:x3
Nov xx xx:20:12.470 - [INFO] Pac Server         : http://127.0.0.1:8086/proxy.pac
Nov xx xx:20:12.470 - [INFO] ------------------------------------------------------
Nov xx xx:20:12.480 - [INFO] server 127.0.0.1:8087 started.
Nov xx xx:20:12.490 - [INFO] server 127.0.0.1:8086 started.
Nov xx xx:20:12.570 - [INFO] module gae_proxy started
Nov xx xx:20:12.570 - [INFO] start gae_proxy time cost:1509 ms
WARNING:root:Load Crypto.Cipher.ARC4 Failed, Use Pure Python Instead.
Nov xx xx:20:12.590 - [INFO] use config_path:x:\XX-Net-3.2.8\data\x_tunnel\client.json
Nov xx xx:20:12.590 - [INFO] Use proxy:127.0.0.1:8087
Nov xx xx:20:12.590 - [DEBUG] x-tunnel no account
Nov xx xx:20:12.600 - [WARNING] x-tunnel session not start
Nov xx xx:20:12.600 - [INFO] server 127.0.0.1:1080 started.
Nov xx xx:20:12.600 - [INFO] Socks5 server listen:127.0.0.1:1080.
Nov xx xx:20:12.690 - [INFO] module x_tunnel started
Nov xx xx:20:12.690 - [INFO] start x_tunnel time cost:120 ms
Nov xx xx:20:12.690 - [INFO] begin to start web control
Nov xx xx:20:12.690 - [ERROR] bind to 127.0.0.1:8085 fail:error(10013, '')
Nov xx xx:20:12.690 - [ERROR] launcher except:Exception("bind to 127.0.0.1:8085fail:error(10013, '')",)
Nov xx xx:20:12.690 - [ERROR] Except stack:Traceback (most recent call last):
  File "x:\XX-Net-3.2.8\code\default\launcher\start.py", line 182, in <module>
    main()
  File "x:\XX-Net-3.2.8\code\default\launcher\start.py", line 161, in main
    web_control.start()
  File "x:\XX-Net-3.2.8\code\default\launcher\web_control.py", line 419, in start
    server = simple_http_server.HTTPServer((host_addr, host_port), Http_Handler)

  File "x:\XX-Net-3.2.8\code\default\python27\1.0\lib\noarch\simple_http_server.py", line 263, in __init__
    self.init_socket()
  File "x:\XX-Net-3.2.8\code\default\python27\1.0\lib\noarch\simple_http_server.py", line 268, in init_socket
    self.add_listen(addr)
  File "x:\XX-Net-3.2.8\code\default\python27\1.0\lib\noarch\simple_http_server.py", line 278, in add_listen
    raise Exception(err_string)
Exception: bind to 127.0.0.1:8085 fail:error(10013, '')

Press Enter to continue...
Nov xx xx:20:12.960 - [DEBUG] get ip:122.149.3.247 t:490
Nov xx xx:20:13.460 - [DEBUG] get ip:41.201.164.178 t:509
Nov xx xx:20:13.610 - [DEBUG] create_ssl update ip:202.75.147.30 time:939 h2:0
Nov xx xx:20:13.620 - [DEBUG] get ip:41.201.128.97 t:509
Nov xx xx:20:13.670 - [DEBUG] create_ssl update ip:122.149.3.247 time:480 h2:0
Nov xx xx:20:13.961 - [DEBUG] get ip:113.171.247.121 t:519
Nov xx xx:20:14.321 - [DEBUG] create_ssl update ip:41.201.128.97 time:470 h2:0
Nov xx xx:20:14.391 - [DEBUG] create_ssl update ip:84.208.42.236 time:1690 h2:0
Nov xx xx:20:14.591 - [DEBUG] create_ssl update ip:113.171.247.121 time:430 h2:0

Nov xx xx:20:14.621 - [DEBUG] network is ok, cost:3521 ms
Nov xx xx:20:17.462 - [DEBUG] 41.201.164.178 fail:timeout('timed out',)
Nov xx xx:20:17.462 - [DEBUG] report_connect_fail:41.201.164.178
Nov xx xx:20:32.477 - [DEBUG] ip:41.201.164.178 real fail
```

goproxy r1161正常使用

**Comment by jzp820927** [comment]
Nov xx xx:20:12.690 - [ERROR] bind to 127.0.0.1:8085 fail:error(10013, '')

8085 端口监听失败，坚持是否有进程占用 8085 端口。SS那些要关了，也有冲突

**Comment by jang-u** [comment]
防火墙没看到8085端口被占用
但应该是被占用了
修改\XX-Net-3.2.8\data\launcher\config.yaml，换其他端口，成功启动xx-net
正常使用，但是manual.ini设置无效，config.ini设置有效

蓝牙设备会占用8085端口吗？

**Comment by SeaHOH** [comment]
windows 可以用资源管理器查看，网上还有各种端口小工具，都可以看到是什么进程占用端口。
360 wifi 会搞 8087 端口。

**Comment by jzp820927** [comment]
cmd 运行 netstat -ano 看看就知道了。

**Comment by jang-u** [comment]
查到了，是新安装的某软件的一个服务占用了，已解决
希望xx-net能设置控制台端口
感谢！

**Comment by jzp820927** [comment]
配置文件可以改啊，你前面不是说已经改了吗

**Comment by broardshore** [comment]
看看我这个启动异常是什么原因造成的
![default](https://cloud.githubusercontent.com/assets/20060544/20779599/77644ba6-b7b0-11e6-8302-b95e62245f95.png)

**Comment by broardshore** [comment]
似乎找到原因了，跟我设置的最大扫描线程数有关，我改成默认的50，立刻就可以打开了

**Comment by jzp820927** [comment]
估计路由不行，支持不了太高的线程
