### ISSUE TITLE
无法自动更新，手动更新出错

### ISSUE THREAD

**Issue by httpe** [XX-net/XX-Net#466]
在1.14.8的时候无法自动更新至1.14.9，现在1.14.9也无法自动更新至1.14.10
但曾经的某版本是可以自动升级的……

手动按“检查新版本”则会出现“发生未知错误, 请刷新页面重试.”
此时，日志中出现以下异常：

May 27 19:25:38 - [ERROR] url in downloading, https://raw.githubusercontent.com/XX-net/XX-Net/master/README.md
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 60823)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 599, in process_request_thread
    self.finish_request(request, client_address)
  File "/home/arce/XX-Net/launcher/1.4.0/web_control.py", line 48, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/home/arce/XX-Net/launcher/1.4.0/web_control.py", line 143, in do_GET
    self.req_config_handler()
  File "/home/arce/XX-Net/launcher/1.4.0/web_control.py", line 300, in req_config_handler
    versions = update_from_github.get_github_versions()
  File "/home/arce/XX-Net/launcher/1.4.0/update_from_github.py", line 104, in get_github_versions
    raise IOError("get README %s fail:" % readme_url)
IOError: get README https://raw.githubusercontent.com/XX-net/XX-Net/master/README.md fail:
----------------------------------------

在程序刚启动时也会报错：
May 27 19:24:57 - [INFO] ssl error: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:581), create full domain cert for host:xxnet-update.appspot.com
May 27 19:24:57 - [WARNING] check_update fail:URLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)'),)
May 27 19:24:57 - [INFO] download https://raw.githubusercontent.com/XX-net/XX-Net/master/README.md to /home/arce/XX-Net/data/downloads/README.md
May 27 19:24:57 - [INFO] GAE CONNECT raw.githubusercontent.com:443 
May 27 19:24:57 - [INFO] ssl error: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:581), create full domain cert for host:raw.githubusercontent.com
May 27 19:24:57 - [WARNING] download https://raw.githubusercontent.com/XX-net/XX-Net/master/README.md to /home/arce/XX-Net/data/downloads/README.md fail:URLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)'),)
May 27 19:24:57 - [WARNING] check_update fail:IOError('get README https://raw.githubusercontent.com/XX-net/XX-Net/master/README.md fail:',)

版本信息：
Sys Platform 	linux2
OS System 	Linux
OS version 	#1 SMP PREEMPT Fri May 22 03:05:23 UTC 2015
OS release 	4.0.4-2-ARCH
OS detail 	Dist:; Version:; ID:
language 	zh_CN
architecture 	64bitELF
Browser 	Mozilla/5.0 (X11; Linux x86_64; rv:38.0) Gecko/20100101 Firefox/38.0
XX-Net Version 	1.14.9
Launcher Version 	1.4.0
GoAgent Version 	3.1.49
Python Version 	2.7.9
Proxy Listen 	127.0.0.1:8087
working appids 	×××××
Out of Quota appids 	
Not Exist appids 	
PAC URL 	http://127.0.0.1:8086/proxy.pac
Google IP 	3000
connected link(帮助) 	10,0
ip-connect-interval 	10
scan ip thread num 	20
block stat(帮助) 	OK

**Comment by HUMORCE** [comment]
不要覆盖，
备份.\data\goagent\good_ip.txt就行了

**Comment by httpe** [comment]
没看懂楼上在说啥……我的手动不是指覆盖= =
覆盖当然可以用，我就是这么升到1.14.19的

**Comment by HUMORCE** [comment]
我的意思是，直接删掉旧版的整个目录，然后重新下载新版
备份旧版的 good_ip.txt 复制到新版本相应位置就可以了。

配置页面的自动更新不好用

**Comment by httpe** [comment]
我知道啊……覆盖安装可用，没有问题。
就是因为自动更新不好用，所以我才来这里报BUG给作者求修复嘛……

**Comment by xxnet** [comment]
前面的版本，有些自动更新有问题。
最新版的自动更新，应该是可以工作的。

在 2015年5月28日 下午9:37，httpe <notifications@github.com>写道：

**Comment by httpe** [comment]
@xxnet 经测试，上述问题在1.14.10中依旧存在，报错信息也一样

**Comment by xxnet** [comment]
certificate verify failed

是因为证书没有导入到系统中，新的Linux下的问题。
待研究

2015-05-29 12:58 GMT+08:00 httpe <notifications@github.com>:

**Comment by httpe** [comment]
@xxnet 恩，确实是自动导入没有成功的问题。我手动将GoAgent的CA放入系统CA文件，自动升级功能可以正常运行，且启动时也再不报错。

附上系统相关信息供参考：
我用的是Arch，其CA证书统一放在/etc/ca-certificates/extracted
其目录结构为：
```
/etc/ca-certificates/extracted：
-r--r--r-- 1 root root 363752 5月  17 21:18 ca-bundle.trust.crt
dr-xr-xr-x 2 root root  36864 5月  29 17:41 cadir
-r--r--r-- 1 root root 222689 5月  17 21:18 email-ca-bundle.pem
-r--r--r-- 1 root root 215629 5月  17 21:18 objsign-ca-bundle.pem
-r--r--r-- 1 root root 271929 5月  29 17:32 tls-ca-bundle.pem
```
TLS所用的证书都在tls-ca-bundle.pem里。手动将Goagent的CA的-----BEGIN CERTIFICATE-----到-----END CERTIFICATE-----部分添加到tls-ca-bundle.pem的末端，问题便不再出现。

**Comment by xxnet** [comment]
恩，谢谢提供的信息。
发现debian 8的机制又不同，
/usr/share/ca-certificates 证书文件要放在这下面，
/etc/ssl/certs/ 这下面还有链接符，
/etc/ca-certificates.conf 再更新这个文件。

具体还要研究。
总之新的Linux对证书的路径管理，又需要去适配。

在 2015年5月29日 下午5:48，httpe <notifications@github.com>写道：
