### ISSUE TITLE
3.2.7版本，在linux上启动报错

### ISSUE THREAD

**Issue by caichy** [XX-net/XX-Net#4667]
2.6.32-279.el6.x86_64 #1 SMP Wed Jun 13 18:24:36 EDT 2012 x86_64 x86_64 x86_64 GNU/Linux
日志如下：

Dec 01 22:12:53.437 - [DEBUG] finished confirm_xxnet_exit
Dec 01 22:12:53.527 - [INFO] SSL use version:TLSv1_2
Dec 01 22:12:53.528 - [ERROR] start module gae_proxy fail:No such protocol
Dec 01 22:12:53.530 - [ERROR] Except stack:Traceback (most recent call last):
  File "/tol/app/proxy/XX-Net-3.2.7/code/default/launcher/module_init.py", line 37, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "/tol/app/proxy/XX-Net-3.2.7/code/default/gae_proxy/start.py", line 13, in <module>
    import local.proxy as client
  File "/tol/app/proxy/XX-Net-3.2.7/code/default/gae_proxy/local/proxy.py", line 97, in <module>
    import proxy_handler
  File "/tol/app/proxy/XX-Net-3.2.7/code/default/gae_proxy/local/proxy_handler.py", line 54, in <module>
    import gae_handler
  File "/tol/app/proxy/XX-Net-3.2.7/code/default/gae_proxy/local/gae_handler.py", line 65, in <module>
    from appids_manager import appid_manager
  File "/tol/app/proxy/XX-Net-3.2.7/code/default/gae_proxy/local/appids_manager.py", line 11, in <module>
    import check_ip
  File "/tol/app/proxy/XX-Net-3.2.7/code/default/gae_proxy/local/check_ip.py", line 60, in <module>
    openssl_context = openssl_wrap.SSLConnection.context_builder(ca_certs=g_cacertfile)
  File "/tol/app/proxy/XX-Net-3.2.7/code/default/gae_proxy/local/openssl_wrap.py", line 246, in context_builder
    ssl_context = OpenSSL.SSL.Context(protocol_version)
  File "/tol/app/proxy/XX-Net-3.2.7/code/default/python27/1.0/lib/noarch/OpenSSL/SSL.py", line 472, in __init__
    raise ValueError("No such protocol")
ValueError: No such protocol

**Comment by jzp820927** [comment]
Dec 01 22:12:53.528 - [ERROR] start module gae_proxy fail:No such protocol

好像第一次看到这种错误，什么没有这个协议，我去，是什么 Linux 系统啊？

**Comment by caichy** [comment]
Red Hat Enterprise Linux Server release 6.3 (Santiago)

**Comment by SeaHOH** [comment]
升级 openssl

**Comment by caichy** [comment]
OpenSSL 1.0.0-fips 29 Mar 2010
是这个版本

**Comment by jzp820927** [comment]
好吧，rpm 系的 Linux 系统，软件和库都很老，问题较多（肥多了 除外）
