### ISSUE TITLE
NoOptionError: No option 'hosts' in section: 'proxy'

### ISSUE THREAD

**Issue by tchklmxx** [XX-net/XX-Net#4722]
Dec 15 12:44:25.136 - [INFO] use build-in openssl lib
Dec 15 12:44:25.136 - [INFO] start XX-Net 3.2.8
Dec 15 12:44:25.136 - [DEBUG] start confirm_xxnet_exit
Dec 15 12:44:26.160 - [DEBUG] good, xxnet:8087 cleared!
Dec 15 12:44:27.191 - [DEBUG] good, xxnet:8085 clear!
Dec 15 12:44:27.191 - [DEBUG] finished confirm_xxnet_exit
Dec 15 12:44:27.222 - [ERROR] start module gae_proxy fail:No option 'hosts' in s
ection: 'proxy'
Dec 15 12:44:27.222 - [ERROR] Except stack:Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\XX-Net-master\XX-Net-master\code\default\
launcher\module_init.py", line 37, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['loca
l', 'start'], -1)
  File "C:\Users\Administrator\Desktop\XX-Net-master\XX-Net-master\code\default\
gae_proxy\start.py", line 13, in <module>
    import local.proxy as client
  File "C:\Users\Administrator\Desktop\XX-Net-master\XX-Net-master\code\default\
gae_proxy\local\proxy.py", line 85, in <module>
    from config import config
  File "C:\Users\Administrator\Desktop\XX-Net-master\XX-Net-master\code\default\
gae_proxy\local\config.py", line 145, in <module>
    config.load()
  File "C:\Users\Administrator\Desktop\XX-Net-master\XX-Net-master\code\default\
gae_proxy\local\config.py", line 59, in load
    self.ONLYHOSTS = [x.strip() for x in self.CONFIG.get('proxy', 'hosts').split
("|")]
  File "C:\Python27\lib\ConfigParser.py", line 618, in get
    raise NoOptionError(option, section)
NoOptionError: No option 'hosts' in section: 'proxy'

Dec 15 12:44:27.222 - [ERROR] launcher except:No option 'hosts' in section: 'pro
xy'
Dec 15 12:44:27.222 - [ERROR] Except stack:Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\XX-Net-master\XX-Net-master\code\default\
launcher\start.py", line 182, in <module>
    main()
  File "C:\Users\Administrator\Desktop\XX-Net-master\XX-Net-master\code\default\
launcher\start.py", line 159, in main
    module_init.start_all_auto()
  File "C:\Users\Administrator\Desktop\XX-Net-master\XX-Net-master\code\default\
launcher\module_init.py", line 98, in start_all_auto
    start(module)
  File "C:\Users\Administrator\Desktop\XX-Net-master\XX-Net-master\code\default\
launcher\module_init.py", line 37, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['loca
l', 'start'], -1)
  File "C:\Users\Administrator\Desktop\XX-Net-master\XX-Net-master\code\default\
gae_proxy\start.py", line 13, in <module>
    import local.proxy as client
  File "C:\Users\Administrator\Desktop\XX-Net-master\XX-Net-master\code\default\
gae_proxy\local\proxy.py", line 85, in <module>
    from config import config
  File "C:\Users\Administrator\Desktop\XX-Net-master\XX-Net-master\code\default\
gae_proxy\local\config.py", line 145, in <module>
    config.load()
  File "C:\Users\Administrator\Desktop\XX-Net-master\XX-Net-master\code\default\
gae_proxy\local\config.py", line 59, in load
    self.ONLYHOSTS = [x.strip() for x in self.CONFIG.get('proxy', 'hosts').split
("|")]
  File "C:\Python27\lib\ConfigParser.py", line 618, in get
    raise NoOptionError(option, section)
NoOptionError: No option 'hosts' in section: 'proxy'

刚安装就出现这个错误，连第一步都过不去 怎么破

**Comment by jzp820927** [comment]
https://github.com/XX-net/XX-Net/issues/4712#issuecomment-266739549

打开上面这个接连，下载 proxy.zip，覆盖 code/default/gae_proxy/local/proxy.ini 文件。
