### ISSUE TITLE
新电脑上配置XX-Net失败

### ISSUE THREAD

**Issue by kgbook** [XX-net/XX-Net#4731]
---
## 操作流程
1.右键start.bat，以管理员身份运行，failed。
2. 从其他电脑copy已配置好的XX-Net到本机，failed。

---
## 现象
1. 没有生成XX-Net快捷方式，任务栏无XX-Net。

---
### 运行log

Dec 16 17:27:15.516 - [INFO] use build-in openssl lib
Dec 16 17:27:15.518 - [INFO] start XX-Net 3.2.8
Dec 16 17:27:15.518 - [DEBUG] start confirm_xxnet_exit
Dec 16 17:27:16.520 - [DEBUG] good, xxnet:8087 cleared!
Dec 16 17:27:17.523 - [DEBUG] good, xxnet:8085 clear!
Dec 16 17:27:17.524 - [DEBUG] finished confirm_xxnet_exit
Dec 16 17:27:17.550 - [ERROR] start module gae_proxy fail:No option 'hosts' in s
ection: 'proxy'
Dec 16 17:27:17.552 - [ERROR] Except stack:Traceback (most recent call last):
  File "D:\Program Files (x86)\XX-Net\code\default\launcher\module_init.py", lin
e 37, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['loca
l', 'start'], -1)
  File "D:\Program Files (x86)\XX-Net\code\default\gae_proxy\start.py", line 13,
 in <module>
    import local.proxy as client
  File "D:\Program Files (x86)\XX-Net\code\default\gae_proxy\local\proxy.py", li
ne 85, in <module>
    from config import config
  File "D:\Program Files (x86)\XX-Net\code\default\gae_proxy\local\config.py", l
ine 145, in <module>
    config.load()
  File "D:\Program Files (x86)\XX-Net\code\default\gae_proxy\local\config.py", l
ine 59, in load
    self.ONLYHOSTS = [x.strip() for x in self.CONFIG.get('proxy', 'hosts').split
("|")]
  File "D:\Program Files (x86)\XX-Net\code\default\python27\1.0\lib\ConfigParser
.py", line 618, in get
    raise NoOptionError(option, section)
NoOptionError: No option 'hosts' in section: 'proxy'

Dec 16 17:27:17.556 - [ERROR] launcher except:No option 'hosts' in section: 'pro
xy'
Dec 16 17:27:17.558 - [ERROR] Except stack:Traceback (most recent call last):
  File "D:\Program Files (x86)\XX-Net\code\default\launcher\start.py", line 182,
 in <module>
    main()
  File "D:\Program Files (x86)\XX-Net\code\default\launcher\start.py", line 159,
 in main
    module_init.start_all_auto()
  File "D:\Program Files (x86)\XX-Net\code\default\launcher\module_init.py", lin
e 98, in start_all_auto
    start(module)
  File "D:\Program Files (x86)\XX-Net\code\default\launcher\module_init.py", lin
e 37, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['loca
l', 'start'], -1)
  File "D:\Program Files (x86)\XX-Net\code\default\gae_proxy\start.py", line 13,
 in <module>
    import local.proxy as client
  File "D:\Program Files (x86)\XX-Net\code\default\gae_proxy\local\proxy.py", li
ne 85, in <module>
    from config import config
  File "D:\Program Files (x86)\XX-Net\code\default\gae_proxy\local\config.py", l
ine 145, in <module>
    config.load()
  File "D:\Program Files (x86)\XX-Net\code\default\gae_proxy\local\config.py", l
ine 59, in load
    self.ONLYHOSTS = [x.strip() for x in self.CONFIG.get('proxy', 'hosts').split
("|")]
  File "D:\Program Files (x86)\XX-Net\code\default\python27\1.0\lib\ConfigParser
.py", line 618, in get
    raise NoOptionError(option, section)
NoOptionError: No option 'hosts' in section: 'proxy'

Press Enter to continue...

**Comment by jzp820927** [comment]
#4712 (comment)

打开上面这个接连，下载 proxy.zip，解压后，覆盖同名的 code/default/gae_proxy/local/proxy.ini 文件。

**Comment by kgbook** [comment]
已解决并部署好；感谢。

**Comment by DouMiaoO-Oo** [comment]
覆盖了zip，成功解决了

**Comment by jzp820927** [comment]
最新版已经解决了这个问题，以后可以直接下载最新版即可
