### ISSUE TITLE
求助，自从半个月前开始CA就显示失败，然后到现在打开google都显示为“不安全”

### ISSUE THREAD

**Issue by GoForFree** [XX-net/XX-Net#4947]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.14393
os-system: Windows
os-version: 10.0.14393
os-release: 10
os-detail: Version:10-0; Build:14393; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
xxnet-version: 3.2.9

python-version: 2.7.11
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:3000 good:2879
network-status: OK
connected-link: new:2 used:0
worker: h1:18 h2:5
scan-ip-thread-num: 50
ip-quality: 238
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by jzp820927** [comment]
证书，证书，证书，导入证书

**Comment by GoForFree** [comment]
我导入了好几次都不管用....重新下载了稳定版什么还是这个样，另外证书导入后显示过期也让我无语，难道要把系统以及浏览器的证书都删掉重新导入才行？

**Comment by jzp820927** [comment]
那就删除 data，删除导入系统的证书，重启 XX，重新导入 新证书到系统

**Comment by myjlpt** [comment]
@jzp820927 貌似删掉CA证书就好，不必删除整个DATA吧？那样很多信息重新来不划算吧

**Comment by jzp820927** [comment]
区别不大，现在 IP 干扰厉害，删除 data 还可以清理僵尸 IP

**Comment by cell13** [comment]
打开google，显示不安全的连接：
www.google.com.hk 的管理员未正确配置网站。为避免您的信息被窃，Firefox 没有建立与该网站的连接。
此网站使用了 HTTP 严格传输安全（HSTS）要求 Firefox 只进行安全连接。正因如此，您不能为此证书添加一个例外。
尝试解决：删掉证书，重新添加证书；更新代码到最新版本。结果依然显示不安全的连接。
错误日志：
Feb 08 22:59:37.352 - [ERROR] ssl.wrap_socket(self.connection=) failed: [SSL: SSLV3_ALERT_CERTIFICATE_EXPIRED] sslv3 alert certificate expired (_ssl.c:1751) path:www.google.com.hk:443, errno:1
Feb 08 22:59:37.353 - [ERROR] Except stack:Traceback (most recent call last): File "XX-Net-3.2.9\code\default\gae_proxy\local\proxy_handler.py", line 314, in do_CONNECT_AGENT self.raw_requestline = self.rfile.readline(65537) File "XX-Net-3.2.9\code\default\python27\1.0\lib\socket.py", line 480, in readline data = self._sock.recv(self._rbufsize) File "XX-Net-3.2.9\code\default\python27\1.0\lib\ssl.py", line 734, in recv return self.read(buflen) File "XX-Net-3.2.9\code\default\python27\1.0\lib\ssl.py", line 621, in read v = self._sslobj.read(len or 1024) SSLError: [SSL: SSLV3_ALERT_CERTIFICATE_EXPIRED] sslv3 alert certificate expired (_ssl.c:1751)

**Comment by jzp820927** [comment]
导入证书

**Comment by cell13** [comment]
已经解决问题，谢谢，有此问题的小伙伴可以参考！
使用的办法：删除 data，删除导入系统的证书，重启 XX，重新导入 新证书到系统
