### ISSUE TITLE
连续好几天xx-net起不起来了

### ISSUE THREAD

**Issue by cchjgood** [XX-net/XX-Net#5173]
运行bat,日志如下：
Mar 20 22:56:54.003 - [INFO] use build-in openssl lib
Mar 20 22:56:54.005 - [INFO] start XX-Net 3.3.0
Mar 20 22:56:54.005 - [DEBUG] start confirm_xxnet_exit
Mar 20 22:56:55.010 - [DEBUG] good, xxnet:8087 cleared!
Mar 20 22:56:56.013 - [DEBUG] good, xxnet:8085 clear!
Mar 20 22:56:56.013 - [DEBUG] finished confirm_xxnet_exit
Mar 20 22:56:56.296 - [INFO] SSL use version:TLSv1_2
Mar 20 22:56:56.992 - [INFO] OpenSSL support alpn
Mar 20 22:56:56.994 - [INFO] load ip range file:E:\XX-Net3.3.0\code\default\gae_proxy\local\ip_range.txt
Mar 20 22:56:57.021 - [INFO] detected Win10, enable connect concurrency control, interval:40
Mar 20 22:56:57.037 - [INFO] load google ip_list num:1615, gws num:1615
Mar 20 22:56:57.102 - [DEBUG] network is ok, cost:1039 ms
Mar 20 22:56:57.208 - [ERROR] start module gae_proxy fail:can't start new thread
Mar 20 22:56:57.210 - [ERROR] Except stack:Traceback (most recent call last):
  File "E:\XX-Net3.3.0\code\default\launcher\module_init.py", line 37, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "E:\XX-Net3.3.0\code\default\gae_proxy\start.py", line 13, in <module>
    import local.proxy as client
  File "E:\XX-Net3.3.0\code\default\gae_proxy\local\proxy.py", line 97, in <module>
    import proxy_handler
  File "E:\XX-Net3.3.0\code\default\gae_proxy\local\proxy_handler.py", line 54, in <module>
    import gae_handler
  File "E:\XX-Net3.3.0\code\default\gae_proxy\local\gae_handler.py", line 69, in <module>
    from google_ip import google_ip
  File "E:\XX-Net3.3.0\code\default\gae_proxy\local\google_ip.py", line 730, in <module>
    google_ip = IpManager()
  File "E:\XX-Net3.3.0\code\default\gae_proxy\local\google_ip.py", line 67, in __init__
    self.reset()
  File "E:\XX-Net3.3.0\code\default\gae_proxy\local\google_ip.py", line 111, in reset
    self.search_more_google_ip()
  File "E:\XX-Net3.3.0\code\default\gae_proxy\local\google_ip.py", line 663, in search_more_google_ip
    p.start()
  File "E:\XX-Net3.3.0\code\default\python27\1.0\lib\threading.py", line 736, in start
    _start_new_thread(self.__bootstrap, ())
error: can't start new thread

Mar 20 22:56:57.210 - [ERROR] launcher except:error("can't start new thread",)
Mar 20 22:56:57.212 - [ERROR] Except stack:Traceback (most recent call last):
  File "E:\XX-Net3.3.0\code\default\launcher\start.py", line 182, in <module>
    main()
  File "E:\XX-Net3.3.0\code\default\launcher\start.py", line 159, in main
    module_init.start_all_auto()
  File "E:\XX-Net3.3.0\code\default\launcher\module_init.py", line 98, in start_all_auto
    start(module)
  File "E:\XX-Net3.3.0\code\default\launcher\module_init.py", line 37, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "E:\XX-Net3.3.0\code\default\gae_proxy\start.py", line 13, in <module>
    import local.proxy as client
  File "E:\XX-Net3.3.0\code\default\gae_proxy\local\proxy.py", line 97, in <module>
    import proxy_handler
  File "E:\XX-Net3.3.0\code\default\gae_proxy\local\proxy_handler.py", line 54, in <module>
    import gae_handler
  File "E:\XX-Net3.3.0\code\default\gae_proxy\local\gae_handler.py", line 69, in <module>
    from google_ip import google_ip
  File "E:\XX-Net3.3.0\code\default\gae_proxy\local\google_ip.py", line 730, in <module>
    google_ip = IpManager()
  File "E:\XX-Net3.3.0\code\default\gae_proxy\local\google_ip.py", line 67, in __init__
    self.reset()
  File "E:\XX-Net3.3.0\code\default\gae_proxy\local\google_ip.py", line 111, in reset
    self.search_more_google_ip()
  File "E:\XX-Net3.3.0\code\default\gae_proxy\local\google_ip.py", line 663, in search_more_google_ip
    p.start()
  File "E:\XX-Net3.3.0\code\default\python27\1.0\lib\threading.py", line 736, in start
    _start_new_thread(self.__bootstrap, ())
error: can't start new thread

Press Enter to continue...Exception in thread Thread-2:
Traceback (most recent call last):
  File "E:\XX-Net3.3.0\code\default\python27\1.0\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "E:\XX-Net3.3.0\code\default\python27\1.0\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "E:\XX-Net3.3.0\code\default\gae_proxy\local\google_ip.py", line 642, in scan_ip_worker
    xlog.exception("google_ip.runJob fail:%r", e)
AttributeError: 'NoneType' object has no attribute 'exception'

Exception in thread Thread-4:
Traceback (most recent call last):
  File "E:\XX-Net3.3.0\code\default\python27\1.0\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "E:\XX-Net3.3.0\code\default\python27\1.0\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "E:\XX-Net3.3.0\code\default\gae_proxy\local\google_ip.py", line 642, in scan_ip_worker
    xlog.exception("google_ip.runJob fail:%r", e)
AttributeError: 'NoneType' object has no attribute 'exception'
Exception in thread Thread-6:
Traceback (most recent call last):
  File "E:\XX-Net3.3.0\code\default\python27\1.0\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "E:\XX-Net3.3.0\code\default\python27\1.0\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "E:\XX-Net3.3.0\code\default\gae_proxy\local\google_ip.py", line 642, in scan_ip_worker
    xlog.exception("google_ip.runJob fail:%r", e)
AttributeError: 'NoneType' object has no attribute 'exception'
倒腾了好几天了，前一阵一直用的好的，这几天一直用不了，又重新下载了最新版本，每次都是运行一次，配置完之后，关闭重启就又起不来了。
系统是Win10 
浏览器chrome 56

**Comment by jzp820927** [comment]
win 10 问题真多，是怎么 运行的？

**Comment by cchjgood** [comment]
解决了，最大扫描线程数设置成1000太大，改小点就好了
