### ISSUE TITLE
无法部署XX-Net至GAE

### ISSUE THREAD

**Issue by izzg** [XX-net/XX-Net#521]
部署GAE AppID时总显示：
          当前状态:, 异常。
          异常信息:init

**Comment by xxnet** [comment]
请贴出状态页和GoAgent日志

在 2015年6月14日 下午5:04，izzg <notifications@github.com>写道：

**Comment by izzg** [comment]
状态页
 
               
                                                                                               
GoAgent代理日志 
                                                                   
重新安装XX-Net之后，部署GAE ID的时候填完APPID 邮箱 
密码之后点“开始部署”后会自动跳至“日志”页面，但日志页面没有任何反应，空白。 
                                                                     
 
Date: Tue, 16 Jun 2015 19:26:35 -0700

**Comment by gm8811** [comment]
May 15 11:26:45.573 - [INFO] deploy begin.
May 15 11:26:46.587 - [DEBUG] GAEProxy Web_control 127.0.0.1:50132 GET /deploy?cmd=get_log
May 15 11:26:47.464 - [DEBUG] ip:59.18.35.150 real fail
May 15 11:26:51.798 - [DEBUG] ssl_closed 61.238.239.236
May 15 11:26:51.799 - [DEBUG] 61.238.239.236 worker close:GoAway: additional_data:session_timed_out
May 15 11:26:52.541 - [DEBUG] ssl_closed 61.238.239.221
May 15 11:26:52.541 - [DEBUG] 61.238.239.221 worker close:GoAway: additional_data:session_timed_out
May 15 11:26:53.305 - [WARNING] 61.238.239.162 _consume_single_frame:ConnectionResetError()
May 15 11:26:53.306 - [DEBUG] ssl_closed 61.238.239.162
May 15 11:26:53.306 - [DEBUG] 61.238.239.162 worker close:disconnect:ConnectionResetError()
May 15 11:26:53.329 - [WARNING] 61.238.239.242 _consume_single_frame:ConnectionResetError()
May 15 11:26:53.330 - [DEBUG] ssl_closed 61.238.239.242
May 15 11:26:53.330 - [DEBUG] 61.238.239.242 worker close:disconnect:ConnectionResetError()
May 15 11:26:59.645 - [INFO] scan_ip add ip:210.143.147.92 time:353
May 15 11:26:59.654 - [INFO] remove_slowest_ip:185.2.108.190 handshake_time:953, fails:0
May 15 11:27:06.616 - [INFO] GAE CONNECT clients4.google.com:443
May 15 11:27:06.663 - [DEBUG] GAE CONNECT Direct POST https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=uWpRBMtMJxxr%2ByhVM3yT2Q%3D%3D
May 15 11:27:06.663 - [DEBUG] host_conn_pool clients4.google.com get:203.233.96.12 handshake:155
May 15 11:27:07.237 - [INFO] DIRECT chucked t:573 s:3079 200 clients4.google.com /chrome-sync/command/?client=Google+Chrome&client_id=uWpRBMtMJxxr%2ByhVM3yT2Q%3D%3D
May 15 11:27:07.252 - [INFO] GAE CONNECT clients4.google.com:443
May 15 11:27:07.283 - [DEBUG] GAE CONNECT Direct POST https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=uWpRBMtMJxxr%2ByhVM3yT2Q%3D%3D
May 15 11:27:07.283 - [DEBUG] host_conn_pool clients4.google.com get:203.233.96.12 handshake:155
May 15 11:27:07.457 - [INFO] DIRECT chucked t:174 s:599 200 clients4.google.com /chrome-sync/command/?client=Google+Chrome&client_id=uWpRBMtMJxxr%2ByhVM3yT2Q%3D%3D
May 15 11:27:10.379 - [WARNING] 203.217.98.37 _consume_single_frame:ConnectionResetError()
May 15 11:27:10.379 - [DEBUG] 203.217.98.37 worker close:disconnect:ConnectionResetError()
May 15 11:27:15.106 - [DEBUG] ssl_closed 111.86.157.149
May 15 11:27:15.106 - [DEBUG] 111.86.157.149 worker close:idle timeout
May 15 11:27:16.109 - [DEBUG] ssl_closed 213.24.121.115
May 15 11:27:16.109 - [DEBUG] 213.24.121.115 worker close:idle timeout
May 15 11:27:16.470 - [INFO] scan_ip add ip:65.199.248.49 time:468
May 15 11:27:16.485 - [INFO] remove_slowest_ip:203.165.13.221 handshake_time:952, fails:0
May 15 11:27:17.767 - [INFO] scan_ip add ip:109.110.33.22 time:181
May 15 11:27:17.781 - [INFO] remove_slowest_ip:212.9.14.247 handshake_time:952, fails:0
May 15 11:27:18.769 - [DEBUG] GAE POST http://1.192.193.135/cloudquery.php
May 15 11:27:18.769 - [DEBUG] get ip:61.238.239.242 t:98
May 15 11:27:18.937 - [DEBUG] create_ssl update ip:61.238.239.242 time:118 h2:1
May 15 11:27:19.282 - [DEBUG] get ip:61.238.239.162 t:108
May 15 11:27:19.442 - [DEBUG] create_ssl update ip:61.238.239.162 time:116 h2:1
May 15 11:27:19.620 - [INFO] GAE t:850 s:197 POST http://1.192.193.135/cloudquery.php get_response:848
May 15 11:27:19.782 - [DEBUG] get ip:61.238.239.221 t:115
May 15 11:27:19.938 - [DEBUG] get ip:61.238.239.236 t:117
May 15 11:27:19.949 - [DEBUG] create_ssl update ip:61.238.239.221 time:101 h2:1
May 15 11:27:20.077 - [DEBUG] create_ssl update ip:61.238.239.236 time:95 h2:1
May 15 11:27:20.297 - [DEBUG] get ip:109.110.33.22 t:181
May 15 11:27:20.453 - [DEBUG] get ip:203.165.14.217 t:190
May 15 11:27:20.582 - [DEBUG] create_ssl update ip:109.110.33.22 time:207 h2:0
May 15 11:27:20.678 - [DEBUG] get ip:111.107.254.149 t:198
May 15 11:27:20.804 - [DEBUG] get ip:27.90.189.212 t:212
May 15 11:27:20.953 - [DEBUG] get ip:27.90.189.208 t:217
May 15 11:27:21.077 - [DEBUG] get ip:111.86.157.149 t:217
May 15 11:27:21.263 - [DEBUG] create_ssl update ip:27.90.189.208 time:207 h2:0
May 15 11:27:21.304 - [DEBUG] get ip:111.86.157.143 t:217
May 15 11:27:21.410 - [DEBUG] create_ssl update ip:111.86.157.149 time:225 h2:0
May 15 11:27:21.583 - [DEBUG] get ip:202.224.62.83 t:221
May 15 11:27:21.788 - [DEBUG] create_ssl update ip:111.86.157.143 time:377 h2:0
May 15 11:27:24.453 - [DEBUG] 203.165.14.217 fail:timeout('timed out',)
May 15 11:27:24.453 - [DEBUG] report_connect_fail:203.165.14.217
May 15 11:27:24.681 - [DEBUG] 111.107.254.149 fail:timeout('timed out',)
May 15 11:27:24.681 - [DEBUG] report_connect_fail:111.107.254.149
May 15 11:27:24.751 - [DEBUG] GAE POST https://www.google.com.hk/gen_204?atyp=i&ct=slh&cad=&ei=Sh4ZWdKkL-uU0gKH-q6gCg&s=13&v=2&pv=0.5785504488347681&me=82:1494818671588,V,0,0,0,0:169820,U,169820:0,V,0,0,1366,662:1217,h,1,36,i:16,h,1,36,o:0,h,1,41,i:17,h,1,41,o:7,h,1,47,i:16,h,1,47,o:2045,e,H&zx=1494818844726
May 15 11:27:24.805 - [DEBUG] 27.90.189.212 fail:timeout('timed out',)
May 15 11:27:24.805 - [DEBUG] report_connect_fail:27.90.189.212
May 15 11:27:25.081 - [INFO] GAE t:330 s:0 POST https://www.google.com.hk/gen_204?atyp=i&ct=slh&cad=&ei=Sh4ZWdKkL-uU0gKH-q6gCg&s=13&v=2&pv=0.5785504488347681&me=82:1494818671588,V,0,0,0,0:169820,U,169820:0,V,0,0,1366,662:1217,h,1,36,i:16,h,1,36,o:0,h,1,41,i:17,h,1,41,o:7,h,1,47,i:16,h,1,47,o:2045,e,H&zx=1494818844726 get_response:330
May 15 11:27:25.587 - [DEBUG] 202.224.62.83 fail:timeout('timed out',)
May 15 11:27:25.587 - [DEBUG] report_connect_fail:202.224.62.83
May 15 11:27:25.863 - [DEBUG] appid:xxnet-9 head fail status:503
May 15 11:27:25.863 - [DEBUG] report_connect_fail:212.122.6.207
May 15 11:27:25.904 - [DEBUG] appid:xxnet-47 head fail status:503
May 15 11:27:25.904 - [DEBUG] report_connect_fail:202.248.248.76
May 15 11:27:26.393 - [DEBUG] recheck_ip:202.248.248.76 restore okl
May 15 11:27:26.394 - [DEBUG] 202.248.248.76 worker close:keep alive
May 15 11:27:29.698 - [INFO] scan_ip add ip:203.165.14.229 time:190
May 15 11:27:29.714 - [INFO] remove_slowest_ip:202.224.62.83 handshake_time:221, fails:1
May 15 11:27:30.876 - [DEBUG] 212.122.6.207 worker close:keep alive
May 15 11:27:34.958 - [DEBUG] restore ip:203.165.14.217
May 15 11:27:35.052 - [INFO] scan_ip add ip:92.126.155.80 time:718
May 15 11:27:35.083 - [DEBUG] sort ip time:30ms
May 15 11:27:35.083 - [INFO] remove_slowest_ip:27.90.189.212 handshake_time:212, fails:1
May 15 11:27:35.489 - [INFO] scan_ip add ip:203.217.98.56 time:502
May 15 11:27:35.520 - [DEBUG] sort ip time:30ms
May 15 11:27:35.520 - [INFO] remove_slowest_ip:212.122.6.207 handshake_time:202, fails:1
May 15 11:27:36.163 - [INFO] scan_ip add ip:72.234.39.224 time:609
May 15 11:27:36.225 - [DEBUG] sort ip time:61ms
May 15 11:27:36.225 - [INFO] remove_slowest_ip:111.107.254.149 handshake_time:198, fails:1
May 15 11:27:37.491 - [INFO] scan_ip add ip:118.143.88.184 time:406
May 15 11:27:37.522 - [DEBUG] sort ip time:31ms
May 15 11:27:37.522 - [INFO] remove_slowest_ip:173.224.96.37 handshake_time:952, fails:0
May 15 11:27:39.969 - [DEBUG] ip:111.107.254.149 real fail
May 15 11:27:44.978 - [DEBUG] ip:27.90.189.212 real fail
May 15 11:27:45.822 - [DEBUG] ssl_closed 122.56.115.183
May 15 11:27:45.822 - [DEBUG] 122.56.115.183 worker close:idle timeout
May 15 11:27:49.979 - [DEBUG] ip:202.224.62.83 real fail
May 15 11:27:50.948 - [DEBUG] restore ip:212.122.6.207
May 15 11:27:52.863 - [INFO] scan_ip add ip:200.28.8.105 time:802
May 15 11:27:52.877 - [INFO] remove_slowest_ip:115.254.97.78 handshake_time:951, fails:0
May 15 11:27:52.877 - [INFO] remove_slowest_ip:59.18.46.160 handshake_time:950, fails:0
May 15 11:27:54.688 - [DEBUG] 203.233.96.12 close:host pool alive_timeout
May 15 11:27:54.688 - [DEBUG] ssl_closed 203.233.96.12
May 15 11:27:55.970 - [DEBUG] ip:202.248.248.76 real fail
May 15 11:28:01.927 - [DEBUG] GAE GET http://config.pinyin.sogou.com/api/popup/lotus.php?h=17664E88CE2BD2F6FCA5B7EB73342EB5&v=7.7.0.6390&r=0000_sogou_pinyin_68e&ppversion=3.1.0.2034
May 15 11:28:01.927 - [DEBUG] get ip:203.233.96.12 t:155
May 15 11:28:02.142 - [DEBUG] create_ssl update ip:203.233.96.12 time:152 h2:0
May 15 11:28:02.439 - [DEBUG] get ip:202.248.248.76 t:175
May 15 11:28:02.454 - [INFO] GAE t:526 s:34 GET http://config.pinyin.sogou.com/api/popup/lotus.php?h=17664E88CE2BD2F6FCA5B7EB73342EB5&v=7.7.0.6390&r=0000_sogou_pinyin_68e&ppversion=3.1.0.2034 get_response:526
May 15 11:28:02.626 - [INFO] scan_ip add ip:154.67.1.144 time:1412
May 15 11:28:02.626 - [INFO] remove_slowest_ip:154.67.1.144 handshake_time:1412, fails:0
May 15 11:28:02.650 - [DEBUG] GAE GET http://info.pinyin.sogou.com/ime_push/getPopupIni.php?h=17664E88CE2BD2F6FCA5B7EB73342EB5&v=7.7.0.6390&r=0000_sogou_pinyin_68e&passport=&activeOp=0&action_skin=16&action_dict=1&action_normal=32&action_gram=514&skinOp=c17301i17301&updateOp=650&dictOp=c0i17301&DisabledEntries=160&disable_newword=1&uex=0&defaultime=0&fvo=6.1.7601&pvo=6.1.7601&sgse=0&ppversion=3.1.0.2034&active_skin=&active_skin_id=&active_skin_md5=&active_skin_isflash=0&urlguide=20120216&type=query&Popup_DisableSkinBubble=1&pushids=&hpushids=&hpopids=&popids=&condids=N10000112&sgse_r=
May 15 11:28:02.717 - [DEBUG] create_ssl update ip:202.248.248.76 time:184 h2:0
May 15 11:28:02.950 - [DEBUG] get ip:203.165.14.229 t:190
May 15 11:28:03.143 - [DEBUG] get ip:203.165.14.217 t:202
May 15 11:28:03.245 - [DEBUG] create_ssl update ip:203.165.14.229 time:187 h2:0
May 15 11:28:03.270 - [INFO] GAE t:619 s:1138 GET http://info.pinyin.sogou.com/ime_push/getPopupIni.php?h=17664E88CE2BD2F6FCA5B7EB73342EB5&v=7.7.0.6390&r=0000_sogou_pinyin_68e&passport=&activeOp=0&action_skin=16&action_dict=1&action_normal=32&action_gram=514&skinOp=c17301i17301&updateOp=650&dictOp=c0i17301&DisabledEntries=160&disable_newword=1&uex=0&defaultime=0&fvo=6.1.7601&pvo=6.1.7601&sgse=0&ppversion=3.1.0.2034&active_skin=&active_skin_id=&active_skin_md5=&active_skin_isflash=0&urlguide=20120216&type=query&Popup_DisableSkinBubble=1&pushids=&hpushids=&hpopids=&popids=&condids=N10000112&sgse_r= get_response:618
May 15 11:28:03.990 - [DEBUG] GAE GET http://ping.pinyin.sogou.com/gender.gif?prob0=0.135184&prob1=0.864816&ppversion=3.1.0.2034&passport=&h=17664E88CE2BD2F6FCA5B7EB73342EB5&v=7.7.0.6390&r=0000_sogou_pinyin_68e
May 15 11:28:03.991 - [DEBUG] GAE GET http://ping.pinyin.sogou.com/pingback_bubble.gif?h=17664E88CE2BD2F6FCA5B7EB73342EB5&v=7.7.0.6390&r=0000_sogou_pinyin_68e&passport=&ppversion=3.1.0.2034&bb_type=Query_period
May 15 11:28:04.458 - [INFO] GAE t:467 s:0 GET http://ping.pinyin.sogou.com/gender.gif?prob0=0.135184&prob1=0.864816&ppversion=3.1.0.2034&passport=&h=17664E88CE2BD2F6FCA5B7EB73342EB5&v=7.7.0.6390&r=0000_sogou_pinyin_68e get_response:451
May 15 11:28:04.583 - [INFO] GAE t:590 s:0 GET http://ping.pinyin.sogou.com/pingback_bubble.gif?h=17664E88CE2BD2F6FCA5B7EB73342EB5&v=7.7.0.6390&r=0000_sogou_pinyin_68e&passport=&ppversion=3.1.0.2034&bb_type=Query_period get_response:588
May 15 11:28:07.156 - [DEBUG] 203.165.14.217 fail:timeout('timed out',)
May 15 11:28:07.156 - [DEBUG] report_connect_fail:203.165.14.217
May 15 11:28:10.287 - [INFO] scan_ip add ip:201.157.30.164 time:1312
May 15 11:28:10.298 - [INFO] remove_slowest_ip:201.157.30.164 handshake_time:1312, fails:0

**Comment by gm8811** [comment]
没有任何反应，上面是日志，看不懂。

**Comment by jzp820927** [comment]
上面的日志，是部署问题？还是代理问题？请详细说明

**Comment by hopesala** [comment]
我的一直这样，部署失败
2018-07-21 23:07:16,763 - root - INFO - set proxy to http://127.0.0.1:8087
2018-07-21 23:07:16,764 - root - INFO - ============ Begin upload ============
2018-07-21 23:07:16,764 - root - INFO - appid:xnet52156
2018-07-21 23:07:16,777 - root - INFO - Send: /api/appversion/rollback, params={'version': '1', 'app_id': 'xnet52156'}
2018-07-21 23:07:16,800 - root - ERROR - upload fail:BadStatusLine("''",)
Traceback (most recent call last):
File "/Users/caochenghua/Downloads/XX-Net-3.12.10/code/default/gae_proxy/server/uploader.py", line 72, in upload
result = appcfg.AppCfgApp(['appcfg', 'rollback', '--oauth2_credential_file', cookie_file, dirname]).Run()
File "/Users/caochenghua/Downloads/XX-Net-3.12.10/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 2951, in Run
self.action(self)
File "/Users/caochenghua/Downloads/XX-Net-3.12.10/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 5044, in __call__
return method()
File "/Users/caochenghua/Downloads/XX-Net-3.12.10/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 4397, in Rollback
self._Rollback()
File "/Users/caochenghua/Downloads/XX-Net-3.12.10/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 4442, in _Rollback
appversion.Rollback(force_rollback)
File "/Users/caochenghua/Downloads/XX-Net-3.12.10/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 2362, in Rollback
force_rollback='1' if force_rollback else '0')
File "/Users/caochenghua/Downloads/XX-Net-3.12.10/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 1696, in Send
result = self.rpcserver.Send(url, payload=payload, **kwargs)
File "/Users/caochenghua/Downloads/XX-Net-3.12.10/code/default/gae_proxy/server/lib/google/appengine/tools/appengine_rpc_httplib2.py", line 247, in Send
url, method=method, body=payload, headers=headers)
File "/Users/caochenghua/Downloads/XX-Net-3.12.10/code/default/gae_proxy/server/lib/httplib2/__init__.py", line 1593, in request
(response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
File "/Users/caochenghua/Downloads/XX-Net-3.12.10/code/default/gae_proxy/server/lib/httplib2/__init__.py", line 1341, in _request
(response, content) = self._conn_request(conn, request_uri, method, body, headers)
File "/Users/caochenghua/Downloads/XX-Net-3.12.10/code/default/gae_proxy/server/lib/httplib2/__init__.py", line 1311, in _conn_request
response = conn.getresponse()
File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1121, in getresponse
response.begin()
File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 438, in begin
version, status, reason = self._read_status()
File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 402, in _read_status
raise BadStatusLine(line)
BadStatusLine: ''
2018-07-21 23:07:16,802 - root - INFO - Retry 1 time...
2018-07-21 23:07:16,814 - root - INFO - Send: /api/appversion/rollback, params={'version': '1', 'app_id': 'xnet52156'}
2018-07-21 23:07:16,836 - root - ERROR - upload fail:BadStatusLine("''",)
Traceback (most recent call last):
File "/Users/caochenghua/Downloads/XX-Net-3.12.10/code/default/gae_proxy/server/uploader.py", line 72, in upload
result = appcfg.AppCfgApp(['appcfg', 'rollback', '--oauth2_credential_file', cookie_file, dirname]).Run()
File "/Users/caochenghua/Downloads/XX-Net-3.12.10/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 2951, in Run
self.action(self)
File "/Users/caochenghua/Downloads/XX-Net-3.12.10/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 5044, in __call__
return method()
File "/Users/caochenghua/Downloads/XX-Net-3.12.10/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 4397, in Rollback
self._Rollback()
File "/Users/caochenghua/Downloads/XX-Net-3.12.10/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 4442, in _Rollback
appversion.Rollback(force_rollback)
File "/Users/caochenghua/Downloads/XX-Net-3.12.10/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 2362, in Rollback
force_rollback='1' if force_rollback else '0')
File "/Users/caochenghua/Downloads/XX-Net-3.12.10/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 1696, in Send
result = self.rpcserver.Send(url, payload=payload, **kwargs)
File "/Users/caochenghua/Downloads/XX-Net-3.12.10/code/default/gae_proxy/server/lib/google/appengine/tools/appengine_rpc_httplib2.py", line 247, in Send
url, method=method, body=payload, headers=headers)
File "/Users/caochenghua/Downloads/XX-Net-3.12.10/code/default/gae_proxy/server/lib/httplib2/__init__.py", line 1593, in request
(response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
File "/Users/caochenghua/Downloads/XX-Net-3.12.10/code/default/gae_proxy/server/lib/httplib2/__init__.py", line 1341, in _request
(response, content) = self._conn_request(conn, request_uri, method, body, headers)
File "/Users/caochenghua/Downloads/XX-Net-3.12.10/code/default/gae_proxy/server/lib/httplib2/__init__.py", line 1311, in _conn_request
response = conn.getresponse()
File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1121, in getresponse
response.begin()
File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 438, in begin
version, status, reason = self._read_status()
File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 402, in _read_status
raise BadStatusLine(line)
BadStatusLine: ''
2018-07-21 23:07:16,836 - root - INFO - Retry 2 time...
2018-07-21 23:07:17,857 - root - INFO - Send: /api/appversion/rollback, params={'version': '1', 'app_id': 'xnet52156'}
2018-07-21 23:07:17,878 - root - ERROR - upload fail:BadStatusLine("''",)
Traceback (most recent call last):
File "/Users/caochenghua/Downloads/XX-Net-3.12.10/code/default/gae_proxy/server/uploader.py", line 72, in upload
result = appcfg.AppCfgApp(['appcfg', 'rollback', '--oauth2_credential_file', cookie_file, dirname]).Run()
File "/Users/caochenghua/Downloads/XX-Net-3.12.10/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 2951, in Run
self.action(self)
File "/Users/caochenghua/Downloads/XX-Net-3.12.10/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 5044, in __call__
return method()
File "/Users/caochenghua/Downloads/XX-Net-3.12.10/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 4397, in Rollback
self._Rollback()
File "/Users/caochenghua/Downloads/XX-Net-3.12.10/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 4442, in _Rollback
appversion.Rollback(force_rollback)
File "/Users/caochenghua/Downloads/XX-Net-3.12.10/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 2362, in Rollback
force_rollback='1' if force_rollback else '0')
File "/Users/caochenghua/Downloads/XX-Net-3.12.10/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 1696, in Send
result = self.rpcserver.Send(url, payload=payload, **kwargs)
File "/Users/caochenghua/Downloads/XX-Net-3.12.10/code/default/gae_proxy/server/lib/google/appengine/tools/appengine_rpc_httplib2.py", line 247, in Send
url, method=method, body=payload, headers=headers)
File "/Users/caochenghua/Downloads/XX-Net-3.12.10/code/default/gae_proxy/server/lib/httplib2/__init__.py", line 1593, in request
(response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
File "/Users/caochenghua/Downloads/XX-Net-3.12.10/code/default/gae_proxy/server/lib/httplib2/__init__.py", line 1341, in _request
(response, content) = self._conn_request(conn, request_uri, method, body, headers)
File "/Users/caochenghua/Downloads/XX-Net-3.12.10/code/default/gae_proxy/server/lib/httplib2/__init__.py", line 1311, in _conn_request
response = conn.getresponse()
File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1121, in getresponse
response.begin()
File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 438, in begin
version, status, reason = self._read_status()
File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 402, in _read_status
raise BadStatusLine(line)
BadStatusLine: ''
2018-07-21 23:07:17,879 - root - INFO - Retry 3 time...
2018-07-21 23:07:19,884 - root - INFO - =======================
2018-07-21 23:07:19,884 - root - INFO - Deploy failed appid list:
2018-07-21 23:07:19,884 - root - INFO - - xnet52156
2018-07-21 23:07:19,885 - root - INFO - == END ==

**Comment by SeaHOH** [comment]
@hopesala 你部署之前试过能访问谷歌吗？

**Comment by jasonzhouu** [comment]
遇到和 @hopesala 同样的问题，这个日志中我觉得最重要的一行是：
`ERROR - upload fail:BadStatusLine("''",)`
之后自动重试3次，最后停止。
