### ISSUE TITLE
一直说“请检查浏览器代理设置。”

### ISSUE THREAD

**Issue by ylhaven** [XX-net/XX-Net#5250]
-----------
问题描述：
请在此描述你遇到的问题，必要时贴出相关的日志信息。

-----------
诊断信息：
sys-platform: AMD64, Windows-7-6.1.7600
os-system: Windows
os-version: 6.1.7600
os-release: 7
os-detail: Version:6-1; Build:7600; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3053.3 Safari/537.36
xxnet-version: 2.9.2
python-version: 2.7.9

ipv6-status: 0
gws-ip-num: 3000 / 168
network-status: OK
connected-link: 7 / 50
scan-ip-thread-num: 50
ip-quality: 429
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by jzp820927** [comment]
Ctrl + F5 强制刷新

**Comment by summerlove66** [comment]
我也遇到了同样的问题。 帮忙看一下可以吗 ，另外我无法 配置GAEProxy ，总是提示无效的APPID
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.14393
os-system: Windows
os-version: 10.0.14393
os-release: 10
os-detail: Version:10-0; Build:14393; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.130 Safari/537.36
xxnet-version: 3.2.9

python-version: 2.7.11
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:411 good:93
network-status: OK
connected-link: new:6 used:0
worker: h1:13 h2:7
scan-ip-thread-num: 50
ip-quality: 392
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: true
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by jzp820927** [comment]
提示无效的APPID
那应该是你没配置服务端吧

**Comment by summerlove66** [comment]
服务端 配置成功了

**Comment by jzp820927** [comment]
浏览器打开 https://你的appid.appspot.com 看看显示的什么内容

**Comment by dsb123dsb** [comment]
我的也是提示检查浏览器代理设置，appid是部署成功的，日志这样报错：
Apr 08 09:01:22.386 - [INFO] scan_ip add ip:194.182.232.121 time:449
Apr 08 09:01:43.096 - [INFO] scan_ip add ip:65.199.248.49 time:467
Apr 08 09:01:43.096 - [ERROR] google_ip.runJob fail:IOError(9, 'Bad file descriptor')
Apr 08 09:01:43.097 - [ERROR] Except stack:Traceback (most recent call last): File "D:\cs\github\XX-Net\code\default\gae_proxy\local\google_ip.py", line 638, in scan_ip_worker scan_ip_log.info("Add undefined time:%d CN:undefined ", ip, result.handshake_time, result.domain) File "D:\cs\github\XX-Net\code\default\gae_proxy\local\scan_ip_log.py", line 60, in info self.log('INFO', fmt, *args) File "D:\cs\github\XX-Net\code\default\gae_proxy\local\scan_ip_log.py", line 50, in log self.log_fd.write(string) IOError: [Errno 9] Bad file descriptor

**Comment by snchrome** [comment]
我也遇到这个情况，按你说的运行了，提示如下：
@jzp820927 GoAgent 服务端已经在 2015-05-28 16:59:57 升级到 3.2.0 版本, 请更新您的客户端。
------------------------
下面是诊断信息：
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.14393
os-system: Windows
os-version: 10.0.14393
os-release: 10
os-detail: Version:10-0; Build:14393; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36
xxnet-version: 3.2.9

python-version: 2.7.11
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:145 good:71
network-status: OK
connected-link: new:7 used:0
worker: h1:21 h2:7
scan-ip-thread-num: 50
ip-quality: 549
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by jzp820927** [comment]
@snchrome 你这个也提示无效的APPID？

**Comment by snchrome** [comment]
@jzp820927 没有提示无效appid，用xx-net的时候部分网站可以翻墙访问，访问谷歌、wiki网站 就提示不是安全网络，不能访问了。

**Comment by jzp820927** [comment]
那应该是证书问题吧

**Comment by snchrome** [comment]
@jzp820927 谢谢提醒，最后按#5116 《问题解决了！！！！ - “ 请检查浏览器代理设置 ” 和“您的连接不是私密连接》 删除证书，改了那行注释解决了。

**Comment by jzp820927** [comment]
最新版应该已经处理这个问题了，或者你可以升级到最新版试试。
