### ISSUE TITLE
请问3.3.0版在openwrt中如何启动成功

### ISSUE THREAD

**Issue by wds75** [XX-net/XX-Net#5287]
请教2个问题：
1、3.3.0版本，在openwrt里执行./xx_net.sh后，输出
Python 2.7.9
Starting xx_net proxy server: xx_net.

再执行./xx_net.sh status显示
Python 2.7.9
ps: invalid option -- a
BusyBox v1.23.2 (2017-02-09 15:24:42 EST) multi-call binary.
Usage: ps
Show list of processes
        w       Wide output
xx-net stoped
似乎程序没有启动。
2、WIKI里教程：
允许远程访问Web界面：
修改 XX-Net/data/launcher/config.yaml
modules:{
launcher:{ allow_remote_connect:1 }
但实际上没有data这个文件夹，也没有config.yaml这个文件。

**Comment by jzp820927** [comment]
终端运行下面命令试试
python code/default/launcher/start.py

**Comment by roc1010kmt** [comment]
不是雙核心cpu的路由器就不要運行XX-Net了，上網慢機能不夠用。

**Comment by jzp820927** [comment]
确实以目前路由器的配置确实不太适合运行代理类的程序，比较消耗资源。我觉得用  树莓派 跑的话，就绰绰有余了。

**Comment by wds75** [comment]
为了安装pyopenssl，必须先安装cryptography，而为了cryptography，必须安装cffi，但是安装cffi1.10失败，源码、whl和以下安装命令，出错提示全部一样。
pip install cffi
Collecting cffi
  Using cached cffi-1.10.0.tar.gz
    Complete output from command python setup.py egg_info:
    unable to execute 'ccache_cc': No such file or directory
    unable to execute 'ccache_cc': No such file or directory

        No working compiler found, or bogus compiler options
        passed to the compiler from Python's distutils module.
        See the error messages above.
        (If they are about -mno-fused-madd and you are on OS/X 10.8,
        see http://stackoverflow.com/questions/22313407/ .)

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-zofWRQ/cffi/

**Comment by wds75** [comment]
python /usr/bin/XX-Net/code/default/launcher/start.py
python: '/usr/bin/XX-Net/code/default/python27/1.0/lib/linux/_cffi_backend.so' i                                                        s not an ELF executable for MIPS
python: '/usr/bin/XX-Net/code/default/python27/1.0/lib/linux/_cffi_backend.so' i                                                        s not an ELF executable for MIPS
Apr 15 21:37:02.292 - [INFO] import build-in openssl fail:ImportError('File not                                                         found',)
python: '/usr/bin/XX-Net/code/default/python27/1.0/lib/linux/_cffi_backend.so' i                                                        s not an ELF executable for MIPS
python: '/usr/bin/XX-Net/code/default/python27/1.0/lib/linux/_cffi_backend.so' i                                                        s not an ELF executable for MIPS
Apr 15 21:37:03.180 - [ERROR] import system python-OpenSSL fail:ImportError('Fil                                                        e not found',)
Apr 15 21:37:03.192 - [ERROR] Except stack:Traceback (most recent call last):
  File "/usr/bin/XX-Net/code/default/launcher/start.py", line 112, in <module>
    import OpenSSL
  File "/usr/lib/python2.7/site-packages/pyOpenSSL-16.2.0-py2.7.egg/OpenSSL/__in                                                        it__.py", line 8, in <module>
  File "/usr/lib/python2.7/site-packages/pyOpenSSL-16.2.0-py2.7.egg/OpenSSL/rand                                                        .py", line 12, in <module>
  File "/usr/lib/python2.7/site-packages/pyOpenSSL-16.2.0-py2.7.egg/OpenSSL/_uti                                                        l.py", line 6, in <module>
  File "/usr/bin/XX-Net/code/default/python27/1.0/lib/linux/cryptography/hazmat/                                                        bindings/openssl/binding.py", line 60, in <module>
    class Binding(object):
  File "/usr/bin/XX-Net/code/default/python27/1.0/lib/linux/cryptography/hazmat/                                                        bindings/openssl/binding.py", line 109, in Binding
    libraries=_get_libraries(sys.platform)
  File "/usr/bin/XX-Net/code/default/python27/1.0/lib/linux/cryptography/hazmat/                                                        bindings/utils.py", line 97, in build_ffi_for_binding
    extra_link_args=extra_link_args,
  File "/usr/bin/XX-Net/code/default/python27/1.0/lib/linux/cryptography/hazmat/                                                        bindings/utils.py", line 105, in build_ffi
    ffi = FFI()
  File "/usr/bin/XX-Net/code/default/python27/1.0/lib/linux/cffi/api.py", line 5                                                        6, in __init__
    import _cffi_backend as backend
ImportError: File not found

Try install python-openssl

**Comment by jzp820927** [comment]
python: '/usr/bin/XX-Net/code/default/python27/1.0/lib/linux/_cffi_backend.so' i s not an ELF executable for MIPS

看提示，好像是 cffi 库有问题，不是 mips 的格式。

**Comment by wds75** [comment]
是的，cffi无法安装~

**Comment by jzp820927** [comment]
莫非是 XX 内置的库，不支持 mips 的 CPU ？
