### ISSUE TITLE
无法部署XX-Net至GAE且没有部署日志

### ISSUE THREAD

**Issue by ljhui** [XX-net/XX-Net#5299]
# 问题描述
我在fedora24上安装了最新版xx-net,可以使用，但当我想部署自己的appid时，总是没用，我按照的是[how to create my appids](https://github.com/XX-net/XX-Net/wiki/how-to-create-my-appids)中的教程创建的appid,然后按照[部署服务端](https://github.com/XX-net/XX-Net/wiki/%E2%80%9C%E9%83%A8%E7%BD%B2%E6%9C%8D%E5%8A%A1%E7%AB%AF%E2%80%9D%E9%A1%B5%E9%9D%A2)页面指导来部署，当我点击开始部署后，会显示"当前状态：部署完成"，但根本没有日志出现，终端内显示这么一段代码
```
Apr 17 17:27:59.328 - [INFO] deploy begin.
Traceback (most recent call last):
  File "/usr/share/xx-net/gae_proxy/server/uploader.py", line 68, in <module>
    my_stdout = Logger("upload.log")
  File "/usr/share/xx-net/gae_proxy/server/uploader.py", line 53, in __init__
    self.fd = open(log_file_name, "w")
IOError: [Errno 13] Permission denied: 'upload.log'
```
这应该是无法上传日志的错误吧

# 诊断信息
```
XX-Net Status：

sys-platform: x86_64, Linux-4.10.9-100.fc24.x86_64-x86_64-with-fedora-24-Twenty_Four
os-system: Linux
os-version: #1 SMP Mon Apr 10 14:47:56 UTC 2017
os-release: 4.10.9-100.fc24.x86_64
os-detail: Dist:Fedora; Version:24; ID:Twenty Four
architecture: 64bit,
browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36
xxnet-version: 2.9.1
python-version: 2.7.13

ipv6-status: 0
gws-ip-num: 194 / 49
network-status: OK
connected-link: 7 / 5
scan-ip-thread-num: 50
ip-quality: 1496
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true
```
# GAEProxy日志
```
Apr 17 17:35:02.925 - [INFO] deploy begin.
Apr 17 17:35:03.314 - [INFO] GAE 27|85.112.121.187|3914 t:767 s:110 hs:591 200 http://push.mail.163.com/cometd?message=%5B%7B%22channel%22%3A%22%2Fservice%2Fpush%22%2C%22clientId%22%3A%22oif84l1vbipe%22%2C%22timestamp%22%3A1492421670705%2C%22data%22%3A%7B%22uid%22%3A%22myljhui%40163.com%22%2C%22auth%22%3A%22gB8.bLs_jhAn7z_Od2xDRBUHDqPPoDEMi1APDp1cPCOn68YH69PjrGT4iz2YFVR.V3CL89nqxooRQZWuXjffipFvhagCIckaNrK0h6f24xu2_ckc.yFs5oB7Cr2v0hRzI35PLDKLmakxNxJzrDZrj1lffYe55xANUatQXSUjaN38JT6Q6yl1x7QAN5JrpackO%22%2C%22product%22%3A%22chrome%22%2C%22event%22%3A%22login%22%7D%7D%5D
Apr 17 17:35:03.360 - [DEBUG] ssl_pool.get:85.112.121.187 handshake:591
Apr 17 17:35:03.465 - [INFO] GAE 17|195.80.179.173|2154 t:996 s:129 hs:649 200 http://push.mail.163.com/cometd?message=%5B%7B%22channel%22%3A%22%2Fmeta%2Freconnect%22%2C%22clientId%22%3A%22oif84l1vbipe%22%2C%22timestamp%22%3A1492421670703%7D%5D
Apr 17 17:35:03.509 - [DEBUG] ssl_pool.get:195.80.179.173 handshake:649
Apr 17 17:35:03.935 - [DEBUG] GAEProxy Web_control 127.0.0.1:53670 GET /deploy?cmd=get_log
Apr 17 17:35:04.308 - [INFO] GAE 27|85.112.121.187|4144 t:947 s:129 hs:591 200 http://push.mail.163.com/cometd?message=%5B%7B%22channel%22%3A%22%2Fmeta%2Freconnect%22%2C%22clientId%22%3A%22oif84l1vbipe%22%2C%22timestamp%22%3A1492421670735%7D%5D
Apr 17 17:35:04.350 - [DEBUG] ssl_pool.get:85.112.121.187 handshake:591
Apr 17 17:35:05.346 - [INFO] GAE 27|85.112.121.187|4393 t:996 s:129 hs:591 200 http://push.mail.163.com/cometd?message=%5B%7B%22channel%22%3A%22%2Fmeta%2Freconnect%22%2C%22clientId%22%3A%22oif84l1vbipe%22%2C%22timestamp%22%3A1492421670772%7D%5D
Apr 17 17:35:05.389 - [DEBUG] ssl_pool.get:85.112.121.187 handshake:591
Apr 17 17:35:06.384 - [DEBUG] ip:190.212.166.187 real fail
Apr 17 17:35:06.628 - [INFO] GAE 27|85.112.121.187|4642 t:1239 s:127 hs:591 200 http://push.mail.163.com/cometd?message=%5B%7B%22channel%22%3A%22%2Fservice%2Fpush%22%2C%22clientId%22%3A%22oif84l1vbipe%22%2C%22timestamp%22%3A1492421670774%2C%22data%22%3A%7B%22uid%22%3A%22myljhui%40163.com%22%2C%22auth%22%3A%22gB8.bLs_jhAn7z_Od2xDRBUHDqPPoDEMi1APDp1cPCOn68YH69PjrGT4iz2YFVR.V3CL89nqxooRQZWuXjffipFvhagCIckaNrK0h6f24xu2_ckc.yFs5oB7Cr2v0hRzI35PLDKLmakxNxJzrDZrj1lffYe55xANUatQXSUjaN38JT6Q6yl1x7QAN5JrpackO%22%2C%22product%22%3A%22chrome%22%2C%22event%22%3A%22login%22%7D%7D%5D
Apr 17 17:35:06.672 - [DEBUG] ssl_pool.get:85.112.121.187 handshake:591
Apr 17 17:35:06.678 - [WARNING] APPID error:502 url:http://push.mail.163.com/cometd?message=%5B%7B%22channel%22%3A%22%2Fmeta%2Fconnect%22%2C%22timestamp%22%3A1492421667340%7D%5D
Apr 17 17:35:06.678 - [DEBUG] 93.123.23.87 close:app err
Apr 17 17:35:06.678 - [DEBUG] ssl_closed 93.123.23.87
Apr 17 17:35:06.681 - [DEBUG] ssl_pool.get:93.123.23.93 handshake:699
Apr 17 17:35:07.694 - [INFO] GAE 27|85.112.121.187|4889 t:1022 s:129 hs:591 200 http://push.mail.163.com/cometd?message=%5B%7B%22channel%22%3A%22%2Fmeta%2Freconnect%22%2C%22clientId%22%3A%22oif84l1vbipe%22%2C%22timestamp%22%3A1492421670898%7D%5D
Apr 17 17:35:07.694 - [INFO] GAE 30|93.123.23.93|2619 t:1014 s:127 hs:699 200 http://push.mail.163.com/cometd?message=%5B%7B%22channel%22%3A%22%2Fservice%2Fpush%22%2C%22clientId%22%3A%22oif84l1vbipe%22%2C%22timestamp%22%3A1492421670901%2C%22data%22%3A%7B%22uid%22%3A%22myljhui%40163.com%22%2C%22auth%22%3A%22gB8.bLs_jhAn7z_Od2xDRBUHDqPPoDEMi1APDp1cPCOn68YH69PjrGT4iz2YFVR.V3CL89nqxooRQZWuXjffipFvhagCIckaNrK0h6f24xu2_ckc.yFs5oB7Cr2v0hRzI35PLDKLmakxNxJzrDZrj1lffYe55xANUatQXSUjaN38JT6Q6yl1x7QAN5JrpackO%22%2C%22product%22%3A%22chrome%22%2C%22event%22%3A%22login%22%7D%7D%5D
Apr 17 17:35:07.739 - [DEBUG] ssl_pool.get:85.112.121.187 handshake:591
Apr 17 17:35:07.740 - [DEBUG] ssl_pool.get:93.123.23.93 handshake:699
Apr 17 17:35:08.302 - [DEBUG] restore ip:172.217.29.180
Apr 17 17:35:08.677 - [INFO] GAE 20|62.197.198.149|368 t:20208 s:111 hs:523 200 http://push.mail.163.com/cometd?message=%5B%7B%22channel%22%3A%22%2Fmeta%2Fconnect%22%2C%22timestamp%22%3A1492421668799%7D%5D
Apr 17 17:35:08.720 - [DEBUG] ssl_pool.get:62.197.198.149 handshake:523
Apr 17 17:35:09.034 - [INFO] start to terminate GAE_Proxy
```
希望能先解决部署日志无法显示的错误，再解决部署不成功的问题

**Comment by jzp820927** [comment]
Permission denied: 'upload.log'
错误提示，很明显，没有 upload.log 文件的权限，检查你 linux 系统的权限设置，给 upload.log 加上当前用户的 读写权限。

**Comment by ljhui** [comment]
@jzp820927 ,问下这个upload.log在哪，使用locate upload.log没找到，去/var/log下也没有，默认这个log文件生成在哪，按理应用自动生成的就应该可以读取吗，怎么没权限？

**Comment by ljhui** [comment]
@1dot75cm,突然发现fedora24从FZUG源安装的XX-net是2.9.1不是最新版,直接可从xx-net的master分支，在终端./start，成功部署所有appid.希望FZUG的xx-net的源能更新下

**Comment by jzp820927** [comment]
我去，原来不是最新版
