### ISSUE TITLE
xx-net 3.30在lede下无法启动，求解，谢谢

### ISSUE THREAD

**Issue by badcrazy** [XX-net/XX-Net#5316]
已经安装python python-openssl pythen-pyopenssl
用start启动，出现错误信息

Python 2.7.13
XX-Net version:default
You have not installed pyOpenSSL yet.
Please install pyOpenSSL.
Apr 20 23:56:23.816 - [INFO] import build-in openssl fail:ImportError('Error relocating /usr/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so: EC_POINT_set_affine_coordinates_GF2m: symbol not found',)
Apr 20 23:56:23.850 - [ERROR] import system python-OpenSSL fail:ImportError('Error relocating /usr/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so: EC_POINT_set_affine_coordinates_GF2m: symbol not found',)
Apr 20 23:56:23.853 - [ERROR] Except stack:Traceback (most recent call last):
  File "code/default/launcher/start.py", line 112, in <module>
    import OpenSSL
  File "/usr/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/lib/python2.7/site-packages/OpenSSL/rand.py", line 12, in <module>
    from OpenSSL._util import (
  File "/usr/lib/python2.7/site-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/usr/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 14, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: Error relocating /usr/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so: EC_POINT_set_affine_coordinates_GF2m: symbol not found

Try install python-openssl
这个怎么破？

**Comment by jzp820927** [comment]
pip install pyOpenSSL

**Comment by badcrazy** [comment]
pyOpenSSL就是python-pyopenssl，已经安装了，就是安装了还不认才来问

**Comment by SeaHOH** [comment]
可能 CPU 对不上，没安装对版本。建议去 lede 官网看看。

**Comment by jzp820927** [comment]
赶脚还是 ubuntu 用起来最方便。

**Comment by badcrazy** [comment]
看了不少帖子发现pyopenssl 16运行会出错，老版本10就ok，可是去哪里找10啊？需要arm_cortex-a9版本

**Comment by jzp820927** [comment]
你这个不会是运行在树莓派上吧？

**Comment by badcrazy** [comment]
bcm4709的设备

**Comment by jzp820927** [comment]
哦，是小主机？

**Comment by badcrazy** [comment]
换了个源用老版本pyopenssl果然可以了，唉，还真是无语

**Comment by jzp820927** [comment]
没有可以经常更新的源，确实老火

**Comment by pchaos** [comment]
@badcrazy 换的啥源？
