### ISSUE TITLE
Debian 7.8安装XX-net失败

### ISSUE THREAD

**Issue by hbhuyt** [XX-net/XX-Net#538]
我在vmware虚拟机(8.0)的Debian7.8中下载并运行./start.sh安装XX-net出错了提示信息如下：
root@D32:/home/*****/文档/XX-Net-master# ./start.sh
('launcher version:', '1.4.0')
Jun 21 15:26:57 - [INFO] use goagent version:3.1.49
Jun 21 15:26:57 - [INFO] goagent 3.1.49 started /home/*****/文档/XX-Net-master/goagent/3.1.49/start.py
Traceback (most recent call last):
  File "/home/*****/文档/XX-Net-master/goagent/3.1.49/start.py", line 13, in <module>
    import local.proxy as goagent
  File "/home/*****/文档/XX-Net-master/goagent/3.1.49/local/proxy.py", line 77, in <module>
    from cert_util import CertUtil
  File "/home/******/文档/XX-Net-master/goagent/3.1.49/local/cert_util.py", line 37, in <module>
    import OpenSSL
  File "/home/*****/文档/XX-Net-master/python27/1.0/lib/linux/OpenSSL/__init__.py", line 36, in <module>
    from OpenSSL import crypto
ImportError: /home/*****/文档/XX-Net-master/python27/1.0/lib/linux/OpenSSL/crypto.so: wrong ELF class: ELFCLASS64

我用file命令查看crypto.so
root@D32:/home/*****/文档/XX-Net-master/python27/1.0/lib/linux/OpenSSL# ls
crypto.so  __init__.py	__init__.pyc  rand.so  SSL.so  version.py
root@D32:/home/******/文档/XX-Net-master/python27/1.0/lib/linux/OpenSSL# file crypto.so
crypto.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=0xde30eced9aa433980917a560e2972be62632e47c, stripped

我安装的debian是32位的版本，请问这个是只能在64位debian下运行吗？哪里可以下载编译好的32位版可用的crypto.so呢？

**Comment by xxnet** [comment]
自己安装库应该就OK了.
试试这个命令：
sudo pip2 install pyopenssl

2015-06-21 15:37 GMT+08:00 hbhuyt <notifications@github.com>:

**Comment by Git8fire** [comment]
我执行./start.sh 出现这个，请问怎么处理Traceback (most recent call last):
  File "launcher/start.py", line 34, in <module>
    from instances import xlog
  File "/home/gtr/Downloads/XX-Net-2.8.9/launcher/instances.py", line 12, in <module>
    xlog = Logger(file_name=log_file)
  File "/home/gtr/Downloads/XX-Net-2.8.9/python27/1.0/lib/noarch/xlog.py", line 34, in __init__
    self.set_file(file_name)
  File "/home/gtr/Downloads/XX-Net-2.8.9/python27/1.0/lib/noarch/xlog.py", line 84, in set_file
    self.log_fd = open(file_name, "w")

XX-Net Version 	2.8.9
Python Version 	2.7.11
System Platform 	x86_64, Linux-4.3.0-kali1-amd64-x86_64-with-Kali-kali-rolling-kali-rolling
OS System 	Linux
OS Version 	#1 SMP Debian 4.3.3-7kali2 (2016-01-27)
Language 	en_US
Architecture 	64bit,ELF
Browser 	Mozilla/5.0 (X11; Linux x86_64; rv:44.0) Gecko/20100101 Firefox/44.0 Iceweasel/44.0

**Comment by Git8fire** [comment]
后来我用ls -al发现date目录所有者是root,管理员权限不够，用chgrp -R /chown -R 两个命令变更所有者。可以执行。./start.sh，但又出现 scan_ip_worker exit。
提示无连接，怎么处理？
