### ISSUE TITLE
提示：“请检查浏览器代理设置”，但是按说明设置了好像也不行···，有老司机带带路吗

### ISSUE THREAD

**Issue by zhuwenlv** [XX-net/XX-Net#5394]
-----------
问题描述：
请在此描述你遇到的问题，必要时贴出相关的日志信息。

-----------
诊断信息：
sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.81 Safari/537.36
xxnet-version: 2.9.4
python-version: 2.7.11

ipv6-status: 0
gws-ip-num: 3000 / 257
network-status: OK
connected-link: 9 / 50
scan-ip-thread-num: 50
ip-quality: 266
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by jzp820927** [comment]
升级 XX 到最新版

**Comment by zhuwenlv** [comment]
jzp820927你好，更新了版本了后还是提示原来的问题······


XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.81 Safari/537.36
xxnet-version: 3.3.0

python-version: 2.7.11
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:1184 good:764
network-status: OK
connected-link: new:5 used:0
worker: h1:15 h2:6
scan-ip-thread-num: 50
ip-quality: 177
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by willwudk** [comment]
有人提了呀，把之前的证书删光，再升级重新导一遍证书

**Comment by jzp820927** [comment]
xxnet-version: 3.3.0
最新版是 3.3.1，不是 3.3.0
升级到 3.3.1 之后，然后按照 #5322 操作。

**Comment by zhuwenlv** [comment]
更新最新版本后已经解决了，谢谢

**Comment by sxliuxiu** [comment]
请检查浏览器代理设置。。更新到最新版，也没能解决问题。。下边是日志。
May 03 20:35:55.701 - [ERROR] ssl.wrap_socket(self.connection=) failed: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:1751) path:www.twitter.com:443, errno:1

May 03 20:35:55.701 - [ERROR] Except stack:Traceback (most recent call last): File "E:\\XX-Net-3.3.1\XX-Net-3.3.1\code\default\gae_proxy\local\proxy_handler.py", line 314, in do_CONNECT_AGENT self.raw_requestline = self.rfile.readline(65537) File "E:\\XX-Net-3.3.1\XX-Net-3.3.1\code\default\python27\1.0\lib\socket.py", line 480, in readline data = self._sock.recv(self._rbufsize) File "E:\\XX-Net-3.3.1\XX-Net-3.3.1\code\default\python27\1.0\lib\ssl.py", line 734, in recv return self.read(buflen) File "E:\\XX-Net-3.3.1\XX-Net-3.3.1\code\default\python27\1.0\lib\ssl.py", line 621, in read v = self._sslobj.read(len or 1024) SSLError: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:1751)

May 03 20:35:55.702 - [WARNING] Method CONNECT not support in GAEProxy for www.twitter.com:443

May 03 20:35:56.742 - [WARNING] Method CONNECT not support in GAEProxy for www.twitter.com:443

May 03 20:35:56.750 - [WARNING] Method CONNECT not support in GAEProxy for www.twitter.com:443

May 03 20:35:56.757 - [WARNING] Method CONNECT not support in GAEProxy for www.twitter.com:443

May 03 20:36:05.803 - [DEBUG] ssl_closed 202.75.147.24

May 03 20:36:05.803 - [DEBUG] 202.75.147.24 worker close:GoAway: additional_data:session_timed_out

**Comment by jzp820927** [comment]
贴状态页出来看看
