### ISSUE TITLE
xx-net  在lede里部署问题

### ISSUE THREAD

**Issue by llqy** [XX-net/XX-Net#5454]
lede17版本
安装了 python  python-openssl   python-pyopenssl

运行start

```shell
root@LEDE_R5:/app/XX-net# ./start
Python 2.7.13
XX-Net version:default
Installing pyOpenSSL for your system... Please type in your password if requested
May 06 22:16:17.591 - [INFO] import build-in openssl fail:ImportError('Error relocating /usr/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so: EC_POINT_set_affine_coordinates_GF2m: symbol not found',)
May 06 22:16:17.603 - [ERROR] import system python-OpenSSL fail:ImportError('Error relocating /usr/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so: EC_POINT_set_affine_coordinates_GF2m: symbol not found',)
May 06 22:16:17.605 - [ERROR] Except stack:Traceback (most recent call last):
  File "code/default/launcher/start.py", line 112, in <module>
    import OpenSSL
  File "/usr/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
  File "/usr/lib/python2.7/site-packages/OpenSSL/rand.py", line 12, in <module>
  File "/usr/lib/python2.7/site-packages/OpenSSL/_util.py", line 6, in <module>
  File "/usr/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 14, in <module>
ImportError: Error relocating /usr/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so: EC_POINT_set_affine_coordinates_GF2m: symbol not found

Try install python-openssl
```

**Comment by jzp820927** [comment]
看提示。是要你安装 python-openssl
不知道你是怎么安装的？

**Comment by sky123456789sky** [comment]
你可以装koolshare坛子里的LEDE 我装了没这个问题

**Comment by llqy** [comment]
@sky123456789sky  请问你的K3用koolshare坛子里的lede 能装xx-net吗,是update大大发布的吗,我用的是lean大大发布的lede for k3

**Comment by sky123456789sky** [comment]
额 我是软路由 不是用的K3 你可以换个中科大的源试试
