### ISSUE TITLE
ubuntu 无法上传appid

### ISSUE THREAD

**Issue by watsonyanghx** [XX-net/XX-Net#5476]
Ubuntu 16，无法上传appid，log如下：

2017-05-10 10:18:18,908 - root - INFO - ============ Begin upload ============
2017-05-10 10:18:18,908 - root - INFO - appid：&&&×&……&……
2017-05-10 10:18:18,916 - root - ERROR - upload fail:IOError(5, 'Input/output error')
Traceback (most recent call last):
File "/home/yang/XX-Net/code/default/gae_proxy/server/uploader.py", line 70, in upload
result = appcfg.AppCfgApp(['appcfg', 'rollback', dirname ]).Run()
File "/home/yang/XX-Net/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 2951, in Run
self.action(self)
File "/home/yang/XX-Net/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 5044, in __call__
return method()
File "/home/yang/XX-Net/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 4397, in Rollback
self._Rollback()
File "/home/yang/XX-Net/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 4419, in _Rollback
module_yaml = self._ParseAppInfoFromYaml(self.basepath)
File "/home/yang/XX-Net/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 3374, in _ParseAppInfoFromYaml
StatusUpdate(msg, self.error_fh)
File "/home/yang/XX-Net/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 206, in StatusUpdate
PrintUpdate(msg, error_fh)
File "/home/yang/XX-Net/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 201, in PrintUpdate
print >>error_fh, '%s %s' % (timestamp.strftime('%I:%M %p'), msg)
IOError: [Errno 5] Input/output error
2017-05-10 10:18:18,917 - root - INFO - Retry 1 time...
2017-05-10 10:18:18,924 - root - ERROR - upload fail:IOError(5, 'Input/output error')
Traceback (most recent call last):
File "/home/yang/XX-Net/code/default/gae_proxy/server/uploader.py", line 70, in upload
result = appcfg.AppCfgApp(['appcfg', 'rollback', dirname ]).Run()
File "/home/yang/XX-Net/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 2951, in Run
self.action(self)
File "/home/yang/XX-Net/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 5044, in __call__
return method()
File "/home/yang/XX-Net/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 4397, in Rollback
self._Rollback()
File "/home/yang/XX-Net/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 4419, in _Rollback
module_yaml = self._ParseAppInfoFromYaml(self.basepath)
File "/home/yang/XX-Net/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 3374, in _ParseAppInfoFromYaml
StatusUpdate(msg, self.error_fh)
File "/home/yang/XX-Net/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 206, in StatusUpdate
PrintUpdate(msg, error_fh)
File "/home/yang/XX-Net/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 201, in PrintUpdate
print >>error_fh, '%s %s' % (timestamp.strftime('%I:%M %p'), msg)
IOError: [Errno 5] Input/output error
2017-05-10 10:18:18,924 - root - INFO - Retry 2 time...
2017-05-10 10:18:19,933 - root - ERROR - upload fail:IOError(5, 'Input/output error')
Traceback (most recent call last):
File "/home/yang/XX-Net/code/default/gae_proxy/server/uploader.py", line 70, in upload
result = appcfg.AppCfgApp(['appcfg', 'rollback', dirname ]).Run()
File "/home/yang/XX-Net/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 2951, in Run
self.action(self)
……

**Comment by jzp820927** [comment]
没见过这种错误，是在 web 页面部署的吗？

**Comment by Wows233** [comment]
1.可能python版本不对？是否改过设置？
2.请从relase页面下载 https://github.com/XX-net/XX-Net/releases/tag/3.3.1

另外除了第一次运行导入证书，不建议用root用户执行。普通用户也可以的，但是要使用chmod获取data文件夹权限。被代码注入就嘿嘿嘿

**Comment by watsonyanghx** [comment]
重启就好了，thanks。 @Wows233，@jzp820927
