### ISSUE TITLE
linux下chrome上google有私密连接的问题

### ISSUE THREAD

**Issue by wan9wu** [XX-net/XX-Net#5493]
---
## 问题内容
chrome打开后无法上google等网站，提示有私密连接问题，按照大家的方法试了删除data目录下的证书文件和文件夹，删除chrome下的GoAgent证书（我的chrome下没有XXNET的证书），然后重新启动XX-NET，依然不管用。
后来用root启动start，提示chrome必须用非root用户登录，虽然有提示但也可以正常启动，启动后
依然有私密连接的问题。

### 正常启动提示内容
5月 11 19:16:13.08 - [DEBUG] ## GAEProxy set keep_running: True
5月 11 19:16:13.08 - [INFO] ------------------------------------------------------
5月 11 19:16:13.08 - [INFO] Python Version     : 2.7.12+
5月 11 19:16:13.08 - [INFO] OS                 : Dist:Deepin; Version:15.4; ID:unstable
5月 11 19:16:13.08 - [INFO] Listen Address     : 127.0.0.1:8087
5月 11 19:16:13.08 - [INFO] GAE APPID          : 
5月 11 19:16:13.08 - [INFO] Pac Server         : http://127.0.0.1:8086/proxy.pac
5月 11 19:16:13.08 - [INFO] ------------------------------------------------------
5月 11 19:16:13.08 - [INFO] no CA file exist
5月 11 19:16:13.08 - [INFO] clean old site certs
Exception in thread Thread-58:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/wangwu/APP/XX-Net/code/3.3.1/gae_proxy/start.py", line 18, in main
    client.main()
  File "/home/wangwu/APP/XX-Net/code/3.3.1/gae_proxy/local/proxy.py", line 153, in main
    CertUtil.init_ca()
  File "/home/wangwu/APP/XX-Net/code/3.3.1/gae_proxy/local/cert_util.py", line 537, in init_ca
    any(os.remove(x) for x in glob.glob(CertUtil.ca_certdir+'/*.crt')+glob.glob(CertUtil.ca_certdir+'/.*.crt'))
  File "/home/wangwu/APP/XX-Net/code/3.3.1/gae_proxy/local/cert_util.py", line 537, in <genexpr>
    any(os.remove(x) for x in glob.glob(CertUtil.ca_certdir+'/*.crt')+glob.glob(CertUtil.ca_certdir+'/.*.crt'))
OSError: [Errno 13] 权限不够: '/home/wangwu/APP/XX-Net/data/gae_proxy/certs/.google.com.crt'

提示权限不够后用root启动正常，只是会提示下无法启动chrome。
#### 获取诊断信息
XX-Net Status:

sys-platform: x86_64, Linux-4.9.0-deepin4-amd64-x86_64-with-Deepin-15.4-unstable
os-system: Linux
os-version: #1 SMP PREEMPT Deepin 4.9.8-4 (2017-04-17)
os-release: 4.9.0-deepin4-amd64
os-detail: Dist:Deepin; Version:15.4; ID:unstable
architecture: 64bit,ELF
browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
xxnet-version: 3.3.1

python-version: 2.7.12+
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:3000 good:2549
network-status: OK
connected-link: new:2 used:0
worker: h1:14 h2:7
scan-ip-thread-num: 50
ip-quality: 372
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

#### 获取日志
我在root启动后的日志中发现了这一条
5月 11 19:19:22.29 - [INFO] create CA
5月 11 19:19:22.29 - [WARNING] please install *libnss3-tools* package to import GoAgent root ca
可能有用，待我把这个包安上试下。
---

**Comment by wan9wu** [comment]
已经解决，解决方法如下：
首先删除XX-NET根目录/data/gae_proxy/certs文件夹和CA.crt文件。
然后在chrome的设置中将GoAgent的证书删除了
确保你的XX-NET在最新版3.3.1。
最后通过命令行用root权限启动start
如果命令行中有提示 [WARNING] please install libnss3-tools package to import GoAgent root ca，那么恭喜你的情况和我一样，用apt-get install libnss3-tools命令安装完之后，重新启动一遍XX-NET就好了。

**Comment by longkx** [comment]
这两天升级chrome后也遇到这个问题，每次都说要检查配置，亲测楼上可用，不过我是win7

**Comment by jzp820927** [comment]
#5322

**Comment by Chinalink** [comment]
亲测可用，win7.
chrome打开google提示私密链接，也可用此方式解决。
另外xx-net提示请检测浏览器配置，也可用此方式解决。

**Comment by wyunlingy** [comment]
已经解决，解决方法如下：
首先删除XX-NET根目录/data/gae_proxy/certs文件夹和CA.crt文件。
然后在chrome的设置中将GoAgent的证书删除了关闭chrome。

先用apt-get install libnss3-tools命令安装完之后
再启动start,一切OK
最后感谢楼主巴巴

**Comment by ycsun19** [comment]
ubuntu亲测可用，搞了好久的问题终于解决了，多谢！
