### ISSUE TITLE
windows 8.1 start.bat failed

### ISSUE THREAD

**Issue by hlee13** [XX-net/XX-Net#550]
when I run start.bat on windows 8.1, get error below:

ImportError: No module named distutils.version

**Comment by xxnet** [comment]
1. XX-Net是什么版本？
2. 请贴出详细的全部输出

2015-06-25 2:52 GMT+08:00 hlee13 <notifications@github.com>:

**Comment by hlee13** [comment]
![image](https://cloud.githubusercontent.com/assets/4981187/8346135/e0322f1e-1b2a-11e5-913a-7606bd4d6fbd.png)

**Comment by hlee13** [comment]
branch master on windows 8.1 when I run start.bat , like below:

C:\Users\xxxxxx\Downloads\XX-Net-master>"C:\Users\xxxxxx\Downloads\XX-Net-master\python27/1.0/python.exe" "C:\Users\xxxxxx\Downloads\XX-Net-master\launcher/start.py" 
launcher version: 1.4.0
Traceback (most recent call last):
  File "C:\Users\xxxxxx\Downloads\XX-Net-master\launcher/start.py", line 63, in <module>
    main()
  File "C:\Users\xxxxxx\Downloads\XX-Net-master\launcher/start.py", line 58, in main
    from start import main as launcher_main
  File "C:\Users\xxxxxx\Downloads\XX-Net-master\launcher\1.4.0\start.py", line 17, in <module>
    from win_tray import sys_tray
  File "C:\Users\xxxxxx\Downloads\XX-Net-master\launcher\1.4.0\win_tray.py", line 19, in <module>
    import module_init
  File "C:\Users\xxxxxx\Downloads\XX-Net-master\launcher\1.4.0\module_init.py", line 5, in <module>
    import config
  File "C:\Users\xxxxxx\Downloads\XX-Net-master\launcher\1.4.0\config.py", line 7, in <module>
    from distutils.version import LooseVersion
ImportError: No module named version

**Comment by linhua55** [comment]
"C:\Users\xxxxxx\Downloads"
请确保路径名不包含中文

**Comment by hlee13** [comment]
确定

**Comment by xxnet** [comment]
请检查目录C:\Users\xxxxxx\Downloads\XX-Net-master\ 下面，有没有这个文件：
python27/1.0/lib/distutils/version.py



2015-06-25 12:13 GMT+08:00 hlee13 <notifications@github.com>:

**Comment by hlee13** [comment]
都有的 ，这些低级错误，我都排除了，才来 issue的

**Comment by hlee13** [comment]
都有的 ，这些低级错误，我都排除了，才来 issue的

**Comment by hlee13** [comment]
都有的 ，这些低级错误，我都排除了，才来 issue的

**Comment by hlee13** [comment]
都有的 ，这些低级错误，我都排除了，才来 issue的

**Comment by hlee13** [comment]
都有的 ，这些低级错误，我都排除了，才来 issue的

**Comment by hlee13** [comment]
都有的 ，这些低级错误，我都排除了，才来 issue的

**Comment by hlee13** [comment]
都有的 ，这些低级错误，我都排除了，才来 issue的
