### ISSUE TITLE
win10 1703无法启动xxnet

### ISSUE THREAD

**Issue by uniqueyehu** [XX-net/XX-Net#5537]
更新到win10 1703之后，今天启动xxnet时，发现无法启动。下载了3.3.2的代码，依然无法启动，提示bind to 127.0.0.1:8087 fail，有日志输出入下：

May 17 21:14:58.342 - [INFO] use build-in openssl lib
May 17 21:14:58.345 - [INFO] start XX-Net 3.3.2
May 17 21:14:58.345 - [DEBUG] start confirm_xxnet_exit
May 17 21:14:59.351 - [DEBUG] good, xxnet:8087 cleared!
May 17 21:15:00.355 - [DEBUG] good, xxnet:8085 clear!
May 17 21:15:00.356 - [DEBUG] finished confirm_xxnet_exit
May 17 21:15:00.681 - [INFO] SSL use version:TLSv1_2
May 17 21:15:01.445 - [DEBUG] network is ok, cost:980 ms
May 17 21:15:01.455 - [INFO] OpenSSL support alpn
May 17 21:15:01.459 - [INFO] load ip range file:D:\ProgramFiles\XX-Net-3.3.2\code\default\gae_proxy\local\ip_range.txt
May 17 21:15:01.482 - [INFO] detected Win10, enable connect concurrency control, interval:40
May 17 21:15:01.483 - [INFO] load google ip_list num:36, gws num:36
May 17 21:15:01.496 - [INFO] OpenSSL support alpn
May 17 21:15:01.497 - [DEBUG] get ip:202.28.85.254 t:269
May 17 21:15:01.500 - [DEBUG] get ip:172.217.5.170 t:473
May 17 21:15:01.510 - [DEBUG] ## GAEProxy set keep_running: True
May 17 21:15:01.512 - [INFO] ------------------------------------------------------
May 17 21:15:01.512 - [INFO] Python Version     : 2.7.13
May 17 21:15:01.512 - [INFO] OS                 : Version:10-0; Build:15063; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
May 17 21:15:01.513 - [INFO] Listen Address     : 127.0.0.1:8087
May 17 21:15:01.513 - [INFO] GAE APPID          :
May 17 21:15:01.513 - [INFO] Pac Server         : http://127.0.0.1:8086/proxy.pac
May 17 21:15:01.513 - [INFO] ------------------------------------------------------
May 17 21:15:01.516 - [ERROR] bind to 127.0.0.1:8087 fail:error(10013, '')
Exception in thread Thread-58:
Traceback (most recent call last):
  File "D:\ProgramFiles\XX-Net-3.3.2\code\default\python27\1.0\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "D:\ProgramFiles\XX-Net-3.3.2\code\default\python27\1.0\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "D:\ProgramFiles\XX-Net-3.3.2\code\default\gae_proxy\start.py", line 18, in main
    client.main()
  File "D:\ProgramFiles\XX-Net-3.3.2\code\default\gae_proxy\local\proxy.py", line 155, in main
    proxy_daemon = simple_http_server.HTTPServer((config.LISTEN_IP, config.LISTEN_PORT), proxy_handler.GAEProxyHandler)
  File "D:\ProgramFiles\XX-Net-3.3.2\code\default\python27\1.0\lib\noarch\simple_http_server.py", line 263, in __init__
    self.init_socket()
  File "D:\ProgramFiles\XX-Net-3.3.2\code\default\python27\1.0\lib\noarch\simple_http_server.py", line 268, in init_socket
    self.add_listen(addr)
  File "D:\ProgramFiles\XX-Net-3.3.2\code\default\python27\1.0\lib\noarch\simple_http_server.py", line 278, in add_listen
    raise Exception(err_string)
Exception: bind to 127.0.0.1:8087 fail:error(10013, '')

May 17 21:15:02.002 - [DEBUG] get ip:59.18.35.147 t:488
May 17 21:15:02.253 - [DEBUG] create_ssl update ip:172.217.5.170 time:491 h2:1
May 17 21:15:02.503 - [DEBUG] get ip:103.233.37.37 t:584
May 17 21:15:03.005 - [DEBUG] get ip:203.146.98.113 t:588
May 17 21:15:03.256 - [DEBUG] get ip:210.143.70.21 t:615
May 17 21:15:03.505 - [DEBUG] get ip:190.212.166.142 t:650
May 17 21:15:04.006 - [DEBUG] get ip:203.66.155.180 t:658
May 17 21:15:04.508 - [DEBUG] get ip:61.238.239.144 t:661
May 17 21:15:05.010 - [DEBUG] get ip:188.21.9.222 t:664
May 17 21:15:05.268 - [DEBUG] create_ssl update ip:203.66.155.180 time:946 h2:1
May 17 21:15:05.502 - [DEBUG] 202.28.85.254 fail:timeout('timed out',)
May 17 21:15:05.504 - [DEBUG] report_connect_fail:202.28.85.254
May 17 21:15:05.517 - [DEBUG] get ip:157.157.135.45 t:686
May 17 21:15:06.009 - [DEBUG] 59.18.35.147 fail:timeout('timed out',)
May 17 21:15:06.011 - [DEBUG] report_connect_fail:59.18.35.147
May 17 21:15:06.025 - [DEBUG] get ip:212.142.160.85 t:687
May 17 21:15:06.034 - [DEBUG] get ip:216.58.207.177 t:690
May 17 21:15:06.270 - [DEBUG] get ip:81.167.38.120 t:691
May 17 21:15:06.508 - [DEBUG] create_ssl update ip:188.21.9.222 time:668 h2:0
May 17 21:15:08.531 - [DEBUG] create_ssl update ip:81.167.38.120 time:699 h2:0
May 17 21:15:08.570 - [DEBUG] create_ssl update ip:61.238.239.144 time:668 h2:0
May 17 21:15:08.969 - [DEBUG] create_ssl update ip:210.143.70.21 time:984 h2:0
May 17 21:15:09.300 - [DEBUG] create_ssl update ip:203.146.98.113 time:1021 h2:1
May 17 21:15:10.732 - [DEBUG] create_ssl update ip:216.58.207.177 time:4354 h2:1
May 17 21:15:12.210 - [DEBUG] create_ssl update ip:212.142.160.85 time:4348 h2:1
May 17 21:15:20.505 - [DEBUG] ip:202.28.85.254 real fail
May 17 21:15:09.551 - [DEBUG] 157.157.135.45 fail:timeout('timed out',)
May 17 21:15:11.647 - [DEBUG] 190.212.166.142 fail:timeout('timed out',)
May 17 21:15:11.771 - [DEBUG] 103.233.37.37 fail:timeout('timed out',)
May 17 21:15:31.045 - [DEBUG] report_connect_fail:157.157.135.45
May 17 21:15:31.047 - [DEBUG] report_connect_fail:190.212.166.142
May 17 21:15:31.047 - [DEBUG] report_connect_fail:103.233.37.37
May 17 21:15:36.046 - [DEBUG] ip:59.18.35.147 real fail
May 17 21:15:46.048 - [DEBUG] ip:157.157.135.45 real fail

**Comment by jzp820927** [comment]
你的 8087 端口，被其他进程占用

**Comment by uniqueyehu** [comment]
刚开始我看了一下，发现并没有什么进程占用8087端口。。。
然后我想到了电脑里装的360安全卫士(⊙o⊙)。。。
卸载了360之后，就能正确启动了~\(≧▽≦)/~
估计是360的锅。。。

**Comment by jzp820927** [comment]
好吧，其实我们已经强调很多次了，用 XXNET，尽量少用国产软件，会出现很多莫名其妙的问题

**Comment by langbao** [comment]
早就不用360等国产软件了。
