### ISSUE TITLE
XX-net 3.3.1 无法启动

### ISSUE THREAD

**Issue by hadementin** [XX-net/XX-Net#5564]
## XX-net 3.3.1 无法启动
---

1.*OS Version:*
`OS 名称:          Microsoft Windows 10 家庭版`
`OS 版本:          10.0.15063 暂缺 Build 15063`
2. *XX-net Version:*
`3.3.1`
3. *启动 start.bat 报溢出异常如下:*
`
May 22 14:55:45.120 - [INFO] use build-in openssl lib
May 22 14:55:45.122 - [INFO] start XX-Net 3.3.1
May 22 14:55:45.123 - [DEBUG] start confirm_xxnet_exit
May 22 14:55:46.141 - [DEBUG] good, xxnet:8087 cleared!
May 22 14:55:47.172 - [DEBUG] good, xxnet:8085 clear!
May 22 14:55:47.172 - [DEBUG] finished confirm_xxnet_exit
May 22 14:55:47.541 - [INFO] SSL use version:TLSv1_2
May 22 14:55:48.005 - [DEBUG] network is ok, cost:748 ms
May 22 14:55:48.204 - [INFO] OpenSSL support alpn
May 22 14:55:48.204 - [INFO] load ip range file:D:\Program Files\XX\XX-Net-3.3.1\code\default\gae_proxy\local\ip_range.txt
May 22 14:55:48.242 - [INFO] detected Win10, enable connect concurrency control, interval:40
May 22 14:55:48.242 - [INFO] load google ip_list num:275, gws num:275
May 22 14:55:48.242 - [ERROR] start module gae_proxy fail:range() result has too many items
May 22 14:55:48.242 - [ERROR] Except stack:Traceback (most recent call last):
  File "D:\Program Files\XX\XX-Net-3.3.1\code\default\launcher\module_init.py", line 37, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "D:\Program Files\XX\XX-Net-3.3.1\code\default\gae_proxy\start.py", line 13, in <module>
    import local.proxy as client
  File "D:\Program Files\XX\XX-Net-3.3.1\code\default\gae_proxy\local\proxy.py", line 97, in <module>
    import proxy_handler
  File "D:\Program Files\XX\XX-Net-3.3.1\code\default\gae_proxy\local\proxy_handler.py", line 54, in <module>
    import gae_handler
  File "D:\Program Files\XX\XX-Net-3.3.1\code\default\gae_proxy\local\gae_handler.py", line 69, in <module>
    from google_ip import google_ip
  File "D:\Program Files\XX\XX-Net-3.3.1\code\default\gae_proxy\local\google_ip.py", line 730, in <module>
    google_ip = IpManager()
  File "D:\Program Files\XX\XX-Net-3.3.1\code\default\gae_proxy\local\google_ip.py", line 67, in __init__
    self.reset()
  File "D:\Program Files\XX\XX-Net-3.3.1\code\default\gae_proxy\local\google_ip.py", line 111, in reset
    self.search_more_google_ip()
  File "D:\Program Files\XX\XX-Net-3.3.1\code\default\gae_proxy\local\google_ip.py", line 657, in search_more_google_ip
    for i in range(0, new_thread_num):
OverflowError: range() result has too many items

May 22 14:55:48.242 - [ERROR] launcher except:OverflowError('range() result has too many items',)
May 22 14:55:48.257 - [ERROR] Except stack:Traceback (most recent call last):
  File "D:\Program Files\XX\XX-Net-3.3.1\code\default\launcher\start.py", line 182, in <module>
    main()
  File "D:\Program Files\XX\XX-Net-3.3.1\code\default\launcher\start.py", line 159, in main
    module_init.start_all_auto()
  File "D:\Program Files\XX\XX-Net-3.3.1\code\default\launcher\module_init.py", line 98, in start_all_auto
    start(module)
  File "D:\Program Files\XX\XX-Net-3.3.1\code\default\launcher\module_init.py", line 37, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "D:\Program Files\XX\XX-Net-3.3.1\code\default\gae_proxy\start.py", line 13, in <module>
    import local.proxy as client
  File "D:\Program Files\XX\XX-Net-3.3.1\code\default\gae_proxy\local\proxy.py", line 97, in <module>
    import proxy_handler
  File "D:\Program Files\XX\XX-Net-3.3.1\code\default\gae_proxy\local\proxy_handler.py", line 54, in <module>
    import gae_handler
  File "D:\Program Files\XX\XX-Net-3.3.1\code\default\gae_proxy\local\gae_handler.py", line 69, in <module>
    from google_ip import google_ip
  File "D:\Program Files\XX\XX-Net-3.3.1\code\default\gae_proxy\local\google_ip.py", line 730, in <module>
    google_ip = IpManager()
  File "D:\Program Files\XX\XX-Net-3.3.1\code\default\gae_proxy\local\google_ip.py", line 67, in __init__
    self.reset()
  File "D:\Program Files\XX\XX-Net-3.3.1\code\default\gae_proxy\local\google_ip.py", line 111, in reset
    self.search_more_google_ip()
  File "D:\Program Files\XX\XX-Net-3.3.1\code\default\gae_proxy\local\google_ip.py", line 657, in search_more_google_ip
    for i in range(0, new_thread_num):
OverflowError: range() result has too many items

Press Enter to continue...
`
---

**Comment by jzp820927** [comment]
第一次看到这个报错信息，改动过什么参数么

**Comment by hadementin** [comment]
修改了最大线程扫描数，退出后，就起不来了。重新解压了一个。

**Comment by jzp820927** [comment]
for i in range(0, new_thread_num):
OverflowError: range() result has too many items

从报错信息来看，应该是你的最大连接数改的太大了。改回默认试试
