### ISSUE TITLE
IP只有1个，延迟9999，无法上网

### ISSUE THREAD

**Issue by Pyw2003** [XX-net/XX-Net#5607]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.14393
os-system: Windows
os-version: 10.0.14393
os-release: 10
os-detail: Version:10-0; Build:14393; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
xxnet-version: 3.3.2

python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:12 good:1
network-status: OK
connected-link: new:0 used:0
worker: h1:0 h2:1
scan-ip-thread-num: 50
ip-quality: 9999
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by Pyw2003** [comment]
今天早上还好好的，现在最多也就4、5个IP，基本打不开网页了

高级 - 检查所有IP
  属性       值
 总IP数	21
 剩余数	 0
有效IP数   4

**Comment by Pyw2003** [comment]
运行日志提示：[WARNING] NO ENOUGH IP

**Comment by jzp820927** [comment]
加大扫描消除

**Comment by Pyw2003** [comment]
怎么做？

**Comment by Pyw2003** [comment]
最大扫描线程数已经调到了1000，仍然只有15个IP

**Comment by Pyw2003** [comment]
XX-Net 打不开，无法运行

```
May 28 12:45:23.001 - [ERROR] start module gae_proxy fail:can't start new thread
May 28 12:45:23.013 - [ERROR] Except stack:Traceback (most recent call last):
  File "C:\Users\12713\Desktop\XX-Net-3.3.2\code\default\launcher\module_init.py", line 37, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "C:\Users\12713\Desktop\XX-Net-3.3.2\code\default\gae_proxy\start.py", line 13, in <module>
    import local.proxy as client
  File "C:\Users\12713\Desktop\XX-Net-3.3.2\code\default\gae_proxy\local\proxy.py", line 97, in <module>
    import proxy_handler
  File "C:\Users\12713\Desktop\XX-Net-3.3.2\code\default\gae_proxy\local\proxy_handler.py", line 54, in <module>
    import gae_handler
  File "C:\Users\12713\Desktop\XX-Net-3.3.2\code\default\gae_proxy\local\gae_handler.py", line 69, in <module>
    from google_ip import google_ip
  File "C:\Users\12713\Desktop\XX-Net-3.3.2\code\default\gae_proxy\local\google_ip.py", line 730, in <module>
    google_ip = IpManager()
  File "C:\Users\12713\Desktop\XX-Net-3.3.2\code\default\gae_proxy\local\google_ip.py", line 67, in __init__
    self.reset()
  File "C:\Users\12713\Desktop\XX-Net-3.3.2\code\default\gae_proxy\local\google_ip.py", line 111, in reset
    self.search_more_google_ip()
  File "C:\Users\12713\Desktop\XX-Net-3.3.2\code\default\gae_proxy\local\google_ip.py", line 663, in search_more_google_ip
    p.start()
  File "C:\Users\12713\Desktop\XX-Net-3.3.2\code\default\python27\1.0\lib\threading.py", line 736, in start
    _start_new_thread(self.__bootstrap, ())
error: can't start new thread

May 28 12:45:23.013 - [ERROR] launcher except:error("can't start new thread",)
May 28 12:45:23.017 - [ERROR] Except stack:Traceback (most recent call last):
  File "C:\Users\12713\Desktop\XX-Net-3.3.2\code\default\launcher\start.py", line 182, in <module>
    main()
  File "C:\Users\12713\Desktop\XX-Net-3.3.2\code\default\launcher\start.py", line 159, in main
    module_init.start_all_auto()
  File "C:\Users\12713\Desktop\XX-Net-3.3.2\code\default\launcher\module_init.py", line 98, in start_all_auto
    start(module)
  File "C:\Users\12713\Desktop\XX-Net-3.3.2\code\default\launcher\module_init.py", line 37, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "C:\Users\12713\Desktop\XX-Net-3.3.2\code\default\gae_proxy\start.py", line 13, in <module>
    import local.proxy as client
  File "C:\Users\12713\Desktop\XX-Net-3.3.2\code\default\gae_proxy\local\proxy.py", line 97, in <module>
    import proxy_handler
  File "C:\Users\12713\Desktop\XX-Net-3.3.2\code\default\gae_proxy\local\proxy_handler.py", line 54, in <module>
    import gae_handler
  File "C:\Users\12713\Desktop\XX-Net-3.3.2\code\default\gae_proxy\local\gae_handler.py", line 69, in <module>
    from google_ip import google_ip
  File "C:\Users\12713\Desktop\XX-Net-3.3.2\code\default\gae_proxy\local\google_ip.py", line 730, in <module>
    google_ip = IpManager()
  File "C:\Users\12713\Desktop\XX-Net-3.3.2\code\default\gae_proxy\local\google_ip.py", line 67, in __init__
    self.reset()
  File "C:\Users\12713\Desktop\XX-Net-3.3.2\code\default\gae_proxy\local\google_ip.py", line 111, in reset
    self.search_more_google_ip()
  File "C:\Users\12713\Desktop\XX-Net-3.3.2\code\default\gae_proxy\local\google_ip.py", line 663, in search_more_google_ip
    p.start()
  File "C:\Users\12713\Desktop\XX-Net-3.3.2\code\default\python27\1.0\lib\threading.py", line 736, in start
    _start_new_thread(self.__bootstrap, ())
error: can't start new thread
```

**Comment by jzp820927** [comment]
你的 扫描线程跳到太大了，使用报错了，跳到几百，如果还不行，只有怀疑是你网络的问题了。

**Comment by Pyw2003** [comment]
现在显示扫描IP线程数是46，但是只有五六个有效IP，已经把最大扫描线程数调到了200

```
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.14393
os-system: Windows
os-version: 10.0.14393
os-release: 10
os-detail: Version:10-0; Build:14393; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
xxnet-version: 3.3.2

python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:12 good:5
network-status: OK
connected-link: new:0 used:0
worker: h1:0 h2:1
scan-ip-thread-num: 46
ip-quality: 1453
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false
```

**Comment by Pyw2003** [comment]
不行，XX-Net又坏掉了，根本打不开

**Comment by Pyw2003** [comment]
`状态页显示空白, 很可能GAEProxy启动失败, 请按指引查找问题原因。`

**Comment by Pyw2003** [comment]
随便截一段日志吧，IP不够，网页基本打不开

```
May 28 13:02:36.441 - [DEBUG] create_ssl update ip:5.20.5.230 time:1026 h2:1
May 28 13:02:36.581 - [DEBUG] get ip:115.84.108.249 t:310
May 28 13:02:36.605 - [DEBUG] get ip:63.117.215.79 t:534
May 28 13:02:37.084 - [DEBUG] get ip:181.192.63.219 t:753
May 28 13:02:37.457 - [DEBUG] get ip:110.93.194.183 t:792
May 28 13:02:37.597 - [DEBUG] get ip:195.177.197.15 t:907
May 28 13:02:37.863 - [INFO] GAE CONNECT clients4.google.com:443
May 28 13:02:37.879 - [DEBUG] GAE CONNECT Direct POST https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=8EH/8Tt/EbvMGmDqk2NLzA%3D%3D
May 28 13:02:37.879 - [DEBUG] host_conn_pool clients4.google.com get:203.66.155.144 handshake:500
May 28 13:02:38.113 - [DEBUG] get ip:150.100.16.94 t:171
May 28 13:02:38.504 - [DEBUG] 200.28.6.158 fail:timeout('timed out',)
May 28 13:02:38.504 - [DEBUG] report_connect_fail:200.28.6.158
May 28 13:02:38.504 - [DEBUG] get ip:66.96.226.188 t:1335
May 28 13:02:38.519 - [INFO] DIRECT chucked t:640 s:5668 200 clients4.google.com /chrome-sync/command/?client=Google+Chrome&client_id=8EH/8Tt/EbvMGmDqk2NLzA%3D%3D
May 28 13:02:38.519 - [INFO] GAE CONNECT clients4.google.com:443
May 28 13:02:38.535 - [DEBUG] GAE CONNECT Direct POST https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=8EH/8Tt/EbvMGmDqk2NLzA%3D%3D
May 28 13:02:38.535 - [DEBUG] host_conn_pool clients4.google.com get:203.66.155.144 handshake:500
May 28 13:02:38.629 - [DEBUG] get ip:111.95.240.205 t:468
May 28 13:02:39.037 - [INFO] DIRECT chucked t:501 s:618 200 clients4.google.com /chrome-sync/command/?client=Google+Chrome&client_id=8EH/8Tt/EbvMGmDqk2NLzA%3D%3D
May 28 13:02:39.143 - [DEBUG] get ip:130.111.19.153 t:569
May 28 13:02:39.190 - [DEBUG] create_ssl update ip:85.112.121.185 time:4340 h2:0
May 28 13:02:39.424 - [DEBUG] create_ssl update ip:150.100.16.94 time:250 h2:0
May 28 13:02:39.799 - [DEBUG] create_ssl update ip:202.75.141.229 time:469 h2:0
May 28 13:02:40.595 - [DEBUG] 115.84.108.249 fail:timeout('timed out',)
May 28 13:02:40.595 - [DEBUG] report_connect_fail:115.84.108.249
May 28 13:02:42.519 - [DEBUG] 66.96.226.188 fail:timeout('timed out',)
May 28 13:02:42.519 - [DEBUG] report_connect_fail:66.96.226.188
May 28 13:02:42.738 - [DEBUG] 111.95.240.205 fail:timeout('timed out',)
May 28 13:02:42.738 - [DEBUG] report_connect_fail:111.95.240.205
May 28 13:02:42.831 - [DEBUG] 195.177.197.15 fail:timeout('timed out',)
May 28 13:02:42.831 - [DEBUG] report_connect_fail:195.177.197.15
May 28 13:02:42.878 - [DEBUG] 110.93.194.183 fail:timeout('timed out',)
May 28 13:02:42.878 - [DEBUG] report_connect_fail:110.93.194.183
May 28 13:02:42.925 - [DEBUG] 181.192.63.219 fail:timeout('timed out',)
May 28 13:02:42.925 - [DEBUG] report_connect_fail:181.192.63.219
May 28 13:02:42.972 - [DEBUG] 63.117.215.79 fail:timeout('timed out',)
May 28 13:02:42.972 - [DEBUG] report_connect_fail:63.117.215.79
May 28 13:02:43.003 - [DEBUG] 125.234.50.157 fail:timeout('timed out',)
May 28 13:02:43.003 - [DEBUG] report_connect_fail:125.234.50.157
May 28 13:02:43.150 - [DEBUG] 189.247.160.117 fail:timeout('timed out',)
May 28 13:02:43.150 - [DEBUG] report_connect_fail:189.247.160.117
May 28 13:02:43.197 - [DEBUG] 130.111.19.153 fail:timeout('timed out',)
May 28 13:02:43.197 - [DEBUG] report_connect_fail:130.111.19.153
May 28 13:02:43.744 - [INFO] GAE CONNECT clients1.google.com:443
May 28 13:02:43.760 - [DEBUG] GAE CONNECT Direct POST https://clients1.google.com/tbproxy/af/query?client=Google%20Chrome
May 28 13:02:43.760 - [DEBUG] host_conn_pool clients1.google.com get:202.75.141.213 handshake:323
May 28 13:02:53.521 - [DEBUG] ip:200.28.6.158 real fail
May 28 13:02:58.525 - [DEBUG] ip:115.84.108.249 real fail
May 28 13:03:03.528 - [DEBUG] ip:66.96.226.188 real fail
May 28 13:03:08.532 - [DEBUG] ip:111.95.240.205 real fail
May 28 13:03:13.545 - [DEBUG] ip:195.177.197.15 real fail
May 28 13:03:18.558 - [DEBUG] ip:110.93.194.183 real fail
May 28 13:03:22.237 - [DEBUG] 113.171.245.92 close:host pool alive_timeout
May 28 13:03:22.237 - [DEBUG] ssl_closed 113.171.245.92
May 28 13:03:23.561 - [DEBUG] ip:181.192.63.219 real fail
May 28 13:03:24.606 - [DEBUG] restore ip:63.117.215.79
May 28 13:03:25.518 - [INFO] GAE CONNECT clients4.google.com:443
May 28 13:03:25.534 - [DEBUG] GAE CONNECT Direct POST https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=8EH/8Tt/EbvMGmDqk2NLzA%3D%3D
May 28 13:03:25.534 - [DEBUG] host_conn_pool clients4.google.com get:203.66.155.144 handshake:500
May 28 13:03:25.842 - [INFO] DIRECT chucked t:308 s:4855 200 clients4.google.com /chrome-sync/command/?client=Google+Chrome&client_id=8EH/8Tt/EbvMGmDqk2NLzA%3D%3D
May 28 13:03:25.850 - [INFO] GAE CONNECT clients4.google.com:443
May 28 13:03:25.862 - [DEBUG] GAE CONNECT Direct POST https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=8EH/8Tt/EbvMGmDqk2NLzA%3D%3D
May 28 13:03:25.866 - [DEBUG] host_conn_pool clients4.google.com get:203.66.155.144 handshake:500
May 28 13:03:26.080 - [INFO] DIRECT chucked t:213 s:544 200 clients4.google.com /chrome-sync/command/?client=Google+Chrome&client_id=8EH/8Tt/EbvMGmDqk2NLzA%3D%3D
May 28 13:03:28.063 - [INFO] scan_ip add ip:92.246.12.208 time:655
May 28 13:03:28.373 - [INFO] GAE CONNECT clients2.google.com:443
May 28 13:03:28.388 - [DEBUG] GAE CONNECT Direct POST https://clients2.google.com/service/update2?cup2key=6:2737759085&cup2hreq=54aa69c3ee330f1cb217933aa0bbf5e47a73eea1d4e7cf0e25eadb160da07d0f
May 28 13:03:28.388 - [DEBUG] get ip:113.171.245.92 t:453
May 28 13:03:28.900 - [DEBUG] get ip:63.117.215.79 t:503
May 28 13:03:29.009 - [DEBUG] create_ssl update ip:113.171.245.92 time:407 h2:0
May 28 13:03:29.411 - [DEBUG] get ip:92.246.12.208 t:655
May 28 13:03:29.520 - [INFO] DIRECT chucked t:1131 s:866 200 clients2.google.com /service/update2?cup2key=6:2737759085&cup2hreq=54aa69c3ee330f1cb217933aa0bbf5e47a73eea1d4e7cf0e25eadb160da07d0f
May 28 13:03:29.520 - [DEBUG] GAE GET http://redirector.gvt1.com/edgedl/release2/AKwEjLXJ5T67/crl-set-5487049096795464299.crx.data
May 28 13:03:29.552 - [WARNING] 85.112.121.185 head appid:linen-sun-139023 request fail:SysCallError(10053, 'WSAECONNABORTED')
May 28 13:03:29.552 - [DEBUG] report_connect_fail:85.112.121.185
May 28 13:03:29.567 - [DEBUG] get ip:200.63.214.145 t:634
May 28 13:03:29.614 - [DEBUG] ip:125.234.50.157 real fail
May 28 13:03:29.774 - [INFO] GAE t:253 s:658 GET http://redirector.gvt1.com/edgedl/release2/AKwEjLXJ5T67/crl-set-5487049096795464299.crx.data h1_req:16,get_response:237
May 28 13:03:29.774 - [DEBUG] GAE GET http://r6---sn-vgqsknel.gvt1.com/edgedl/release2/AKwEjLXJ5T67/crl-set-5487049096795464299.crx.data?cms_redirect=yes&expire=1495962005&ip=107.178.194.41&ipbits=0&mip=107.178.194.41&mm=28&mn=sn-vgqsknel&ms=nvh&mt=1495947545&mv=m&pl=28&shardbypass=yes&sparams=expire,ip,ipbits,mip,mm,mn,ms,mv,pl,shardbypass&signature=48BE07873AE59F678139DC41ADA6620049DE803B.1F86FDB37F6E9E1F5EB3B37B3118EB9EE6D72A79&key=cms1
May 28 13:03:29.914 - [DEBUG] get ip:191.243.156.38 t:776
May 28 13:03:30.024 - [DEBUG] get ip:200.28.6.184 t:896
May 28 13:03:30.102 - [INFO] GAE t:328 s:0 GET http://r6---sn-vgqsknel.gvt1.com/edgedl/release2/AKwEjLXJ5T67/crl-set-5487049096795464299.crx.data?cms_redirect=yes&expire=1495962005&ip=107.178.194.41&ipbits=0&mip=107.178.194.41&mm=28&mn=sn-vgqsknel&ms=nvh&mt=1495947545&mv=m&pl=28&shardbypass=yes&sparams=expire,ip,ipbits,mip,mm,mn,ms,mv,pl,shardbypass&signature=48BE07873AE59F678139DC41ADA6620049DE803B.1F86FDB37F6E9E1F5EB3B37B3118EB9EE6D72A79&key=cms1 get_response:328
May 28 13:03:30.117 - [DEBUG] GAE GET http://r5---sn-vgqsenls.gvt1.com/edgedl/release2/AKwEjLXJ5T67/crl-set-5487049096795464299.crx.data?expire=1495962005&ip=107.178.194.31&ipbits=0&mip=107.178.194.41&pl=28&shardbypass=yes&sparams=expire,ip,ipbits,ipbypass,mip,mm,mn,ms,mv,pl,shardbypass&signature=369DA7930C4DB2034BD3BB3331781A87B939DB48.0F1F06D4CDA0D888173596882193E6CB8C17572C&key=cms1&redirect_counter=1&req_id=a6abb8bf1621e523&cms_redirect=yes&ipbypass=yes&mm=28&mn=sn-vgqsenls&ms=nvh&mt=1495947545&mv=m
May 28 13:03:30.425 - [DEBUG] get ip:103.17.215.20 t:213
May 28 13:03:30.767 - [INFO] GAE t:649 s:164816 GET http://r5---sn-vgqsenls.gvt1.com/edgedl/release2/AKwEjLXJ5T67/crl-set-5487049096795464299.crx.data?expire=1495962005&ip=107.178.194.31&ipbits=0&mip=107.178.194.41&pl=28&shardbypass=yes&sparams=expire,ip,ipbits,ipbypass,mip,mm,mn,ms,mv,pl,shardbypass&signature=369DA7930C4DB2034BD3BB3331781A87B939DB48.0F1F06D4CDA0D888173596882193E6CB8C17572C&key=cms1&redirect_counter=1&req_id=a6abb8bf1621e523&cms_redirect=yes&ipbypass=yes&mm=28&mn=sn-vgqsenls&ms=nvh&mt=1495947545&mv=m get_response:292,h1_finish[SP:462512]:356
May 28 13:03:30.783 - [DEBUG] create_ssl update ip:200.63.214.145 time:602 h2:0
May 28 13:03:30.783 - [DEBUG] get ip:203.133.72.150 t:657
May 28 13:03:30.799 - [INFO] GAE CONNECT clients2.google.com:443
May 28 13:03:30.815 - [DEBUG] GAE CONNECT Direct POST https://clients2.google.com/service/update2
May 28 13:03:30.815 - [DEBUG] host_conn_pool clients2.google.com get:113.171.245.92 handshake:407
May 28 13:03:30.940 - [DEBUG] get ip:94.20.252.153 t:733
May 28 13:03:30.940 - [DEBUG] create_ssl update ip:92.246.12.208 time:654 h2:0
May 28 13:03:31.034 - [DEBUG] create_ssl update ip:203.133.72.150 time:171 h2:0
May 28 13:03:31.143 - [DEBUG] create_ssl update ip:63.117.215.79 time:639 h2:0
May 28 13:03:31.220 - [INFO] DIRECT chucked t:404 s:187 200 clients2.google.com /service/update2
May 28 13:03:31.311 - [DEBUG] create_ssl update ip:200.28.6.184 time:870 h2:0
May 28 13:03:32.458 - [WARNING] no enough ip
May 28 13:03:33.463 - [WARNING] no enough ip
May 28 13:03:33.940 - [DEBUG] 191.243.156.38 fail:timeout('timed out',)
May 28 13:03:34.431 - [DEBUG] 103.17.215.20 fail:timeout('timed out',)
May 28 13:03:34.478 - [WARNING] no enough ip
May 28 13:03:34.619 - [DEBUG] ip:189.247.160.117 real fail
May 28 13:03:34.996 - [DEBUG] 94.20.252.153 fail:timeout('timed out',)
May 28 13:03:35.483 - [WARNING] no enough ip
May 28 13:03:36.496 - [WARNING] no enough ip
May 28 13:03:37.508 - [WARNING] no enough ip
May 28 13:03:38.510 - [WARNING] no enough ip
May 28 13:03:39.513 - [WARNING] no enough ip
May 28 13:03:39.513 - [DEBUG] report_connect_fail:191.243.156.38
May 28 13:03:39.622 - [DEBUG] ip:130.111.19.153 real fail
May 28 13:03:40.515 - [WARNING] no enough ip
May 28 13:03:40.515 - [DEBUG] report_connect_fail:103.17.215.20
May 28 13:03:41.520 - [WARNING] no enough ip
May 28 13:03:41.520 - [DEBUG] report_connect_fail:94.20.252.153
May 28 13:03:42.524 - [WARNING] no enough ip
May 28 13:03:43.528 - [WARNING] no enough ip
May 28 13:03:43.528 - [DEBUG] 85.112.121.185 worker close:keep alive
May 28 13:03:44.534 - [WARNING] no enough ip
```

**Comment by myjlpt** [comment]
这两天掉的确实蛮厉害，8000几稳定多时，现在：
属性	值
本地网络状态	OK
IP数量	4912
空闲	0
IP延迟	106

**Comment by jzp820927** [comment]
要不把 XX 整个删了，重新下载试试

**Comment by Pyw2003** [comment]
今天上午已经删了重装好几次了，后来一点一点恢复了，现在已经可以正常访问网页了

**Comment by jzp820927** [comment]
不确定，是不是干扰加重了。
