### ISSUE TITLE
1.16.0闪退

### ISSUE THREAD

**Issue by jang-u** [XX-net/XX-Net#565]
('launcher version:', '1.4.0')
Traceback (most recent call last):
  File "?\XX-Net-1.16.0\launcher/start.py", line 63, in <module>
    main()
  File "?\XX-Net-1.16.0\launcher/start.py", line 58, in main
    from start import main as launcher_main
  File "?\XX-Net-1.16.0\launcher\1.4.0\start.py", line 15, in <module>
    from win_tray import sys_tray
  File "?\XX-Net-1.16.0\launcher\1.4.0\win_tray.py", line 20, in <module>
    import module_init
  File "?\XX-Net-1.16.0\launcher\1.4.0\module_init.py", line 7, in <module>
    import web_control
  File "?\XX-Net-1.16.0\launcher\1.4.0\web_control.py", line 31, in <module>
    import update_from_github
  File "?\XX-Net-1.16.0\launcher\1.4.0\update_from_github.py", line 20, in <module>
    from update import opener
  File "?\XX-Net-1.16.0\launcher\1.4.0\update.py", line 44, in <module>
    opener = create_url_opener()
  File "?\XX-Net-1.16.0\launcher\1.4.0\update.py", line 37, in create_url_opener
    context = ssl.create_default_context(purpose=ssl.Purpose.SERVER_AUTH,AttributeError: 'module' object has no attribute 'create_default_context'

**Comment by xxnet** [comment]
1.16.1 发布，修复这个bug，谢谢反馈

2015-07-04 13:29 GMT+08:00 jang-u <notifications@github.com>:

**Comment by yjd** [comment]
刚才开启，然后自动升级导致和你同样问题。

**Comment by xxnet** [comment]
抱歉，没有测试好

2015-07-04 13:38 GMT+08:00 yjd <notifications@github.com>:

**Comment by yjd** [comment]
return openergit
NameError: global name 'openergit' is not defined

问题还没修好。

**Comment by xxnet** [comment]
发布的时候，把git命令敲到代码里了，1.16.3 发布，win7 下测试过

2015-07-04 13:45 GMT+08:00 yjd <notifications@github.com>:

**Comment by bgobgobgo** [comment]
XX-Net Version 1.16.3 在windows10上无法上谷歌

**Comment by xxnet** [comment]
请bgobgobgo另外开issue

2015-07-05 8:59 GMT+08:00 bgobgobgo <notifications@github.com>:

**Comment by bgobgobgo** [comment]
经过尝试:XX-Net Version 1.16.3 在windows10上无法使用谷歌搜索,经过尝试IE是可以上的，但火狐上不了，就是通过google引擎搜索不了，通过bing引擎搜索就可以，
