### ISSUE TITLE
v1.16.3版Arch依然无法自动更新

### ISSUE THREAD

**Issue by httpe** [XX-net/XX-Net#575]
新版的发布说明中说修复了Arch下证书的问题，但是实际测试中依然没有解决，依然无法自动导入证书。并且，手动导入证书至/etc/ca-certificates/extracted/tls-ca-bundle.pem后，在以前的版本中如此操作之后可以正常更新，但新版反而不行了。

手动导入证书后点“检查更新”显示的错误（和没导入前基本一样）：
```
Jul  5 20:54:23 - [ERROR] download https://raw.githubusercontent.com/XX-net/XX-Net/master/README.md to /home/arce/XX-Net/data/downloads/README.md fail:HTTPError()
Traceback (most recent call last):
  File "/home/arce/XX-Net/launcher/1.4.0/update_from_github.py", line 63, in download_file
    req = opener.open(url)
  File "/usr/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 504: 

----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 52614)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 599, in process_request_thread
    self.finish_request(request, client_address)
  File "/home/arce/XX-Net/launcher/1.4.0/web_control.py", line 48, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/home/arce/XX-Net/launcher/1.4.0/web_control.py", line 143, in do_GET
    self.req_config_handler()
  File "/home/arce/XX-Net/launcher/1.4.0/web_control.py", line 310, in req_config_handler
    versions = update_from_github.get_github_versions()
  File "/home/arce/XX-Net/launcher/1.4.0/update_from_github.py", line 104, in get_github_versions
    raise IOError("get README %s fail:" % readme_url)
IOError: get README https://raw.githubusercontent.com/XX-net/XX-Net/master/README.md fail:
----------------------------------------
Jul  5 20:54:23 - [DEBUG] launcher web_control 127.0.0.1:52846 GET /config?cmd=get_new_version 
Jul  5 20:54:23 - [ERROR] url in downloading, https://raw.githubusercontent.com/XX-net/XX-Net/master/README.md
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 52846)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 599, in process_request_thread
    self.finish_request(request, client_address)
  File "/home/arce/XX-Net/launcher/1.4.0/web_control.py", line 48, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/home/arce/XX-Net/launcher/1.4.0/web_control.py", line 143, in do_GET
    self.req_config_handler()
  File "/home/arce/XX-Net/launcher/1.4.0/web_control.py", line 310, in req_config_handler
    versions = update_from_github.get_github_versions()
  File "/home/arce/XX-Net/launcher/1.4.0/update_from_github.py", line 104, in get_github_versions
    raise IOError("get README %s fail:" % readme_url)
IOError: get README https://raw.githubusercontent.com/XX-net/XX-Net/master/README.md fail:
----------------------------------------
```

**Comment by xxnet** [comment]
504 Gateway Timeout

日志里看，已经不是之前的证书错误了。
504是网关超时，会不会是偶然现象？
  这里的网关应该是github的网关

2015-07-05 21:12 GMT+08:00 httpe <notifications@github.com>:

**Comment by xxnet** [comment]
重新看了源码，这里的504网关超时，有可能是goagent返回的，
  goagent如果没有足够好的ip，连接超时，也会返回504。

因此，请先确认能够翻墙，再测试能否自动更新

2015-07-06 8:54 GMT+08:00 Net XX <xxnet.dev@gmail.com>:

**Comment by httpe** [comment]
重新测试后正常运行~多谢修复～
