### ISSUE TITLE
无法部署服务端

### ISSUE THREAD

**Issue by a449122580** [XX-net/XX-Net#5810]
# 问题描述
无法部署服务端
# 诊断信息

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.15063
os-system: Windows
os-version: 10.0.15063
os-release: 10
os-detail: Version:10-0; Build:15063; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:53.0) Gecko/20100101 Firefox/53.0
xxnet-version: 3.3.1

python-version: 2.7.11
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:12298 good:12280
network-status: OK
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 500
ip-quality: 100
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

# 日志

2017-06-20 15:54:36,224 - root - INFO - set proxy to http://127.0.0.1:8087
2017-06-20 15:54:36,239 - root - INFO - ============ Begin upload ============
2017-06-20 15:54:36,239 - root - INFO - appid:xxnet-xxxxx
2017-06-20 15:54:36,263 - root - INFO - Send: /api/appversion/rollback, params={'version': '1', 'app_id': 'xxnet-171306'}
2017-06-20 16:13:56,772 - root - ERROR - upload fail:ValidationError("Value '600' for response_code is out of range 100 - 599",)
Traceback (most recent call last):
File "C:\XX-Net-3.3.1\code\default\gae_proxy\server\uploader.py", line 70, in upload
result = appcfg.AppCfgApp(['appcfg', 'rollback', dirname ]).Run()
File "C:\XX-Net-3.3.1\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 2951, in Run
self.action(self)
File "C:\XX-Net-3.3.1\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 5044, in __call__
return method()
File "C:\XX-Net-3.3.1\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 4397, in Rollback
self._Rollback()
File "C:\XX-Net-3.3.1\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 4442, in _Rollback
appversion.Rollback(force_rollback)
File "C:\XX-Net-3.3.1\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 2362, in Rollback
force_rollback='1' if force_rollback else '0')
File "C:\XX-Net-3.3.1\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 1702, in Send
request_size_bytes)
File "C:\XX-Net-3.3.1\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 1723, in _RegisterReqestForLogging
request_size_bytes=request_size_bytes))
File "C:\XX-Net-3.3.1\code\default\gae_proxy\server\lib\google\appengine\api\validation.py", line 273, in __init__
self.SetMultiple(attributes)
File "C:\XX-Net-3.3.1\code\default\gae_proxy\server\lib\google\appengine\api\validation.py", line 177, in SetMultiple
self.Set(key, value)
File "C:\XX-Net-3.3.1\code\default\gae_proxy\server\lib\google\appengine\api\validation.py", line 305, in Set
setattr(self, key, value)
File "C:\XX-Net-3.3.1\code\default\gae_proxy\server\lib\google\appengine\api\validation.py", line 361, in __setattr__
value = self.GetValidator(key)(value, key)
File "C:\XX-Net-3.3.1\code\default\gae_proxy\server\lib\google\appengine\api\validation.py", line 599, in __call__
return self.Validate(value, key)
File "C:\XX-Net-3.3.1\code\default\gae_proxy\server\lib\google\appengine\api\validation.py", line 1157, in Validate
% (value, key, self.minimum, self.maximum))
ValidationError: Value '600' for response_code is out of range 100 - 599
2017-06-20 16:13:56,822 - root - INFO - Retry 1 time...
2017-06-20 16:13:56,842 - root - INFO - Send: /api/appversion/rollback, params={'version': '1', 'app_id': 'xxnet-171306'}

**Comment by wenliyang** [comment]
请升级到最新的 3.3.4 版本

**Comment by a449122580** [comment]
@wenliyang 感谢大佬，现在配置好了，但是一直在扫描ip扫不出来

**Comment by a449122580** [comment]
![image](https://user-images.githubusercontent.com/13272715/27328086-6590cd56-55e3-11e7-8aa0-b250c54ce68e.png)

**Comment by a449122580** [comment]
接后续，这个还没好只是刷新了浏览器，代理和证书又变成fail了

**Comment by wenliyang** [comment]
IP 不足的问题，只有开着 XX-Net 让它扫
证书的问题，参考 #5322

**Comment by a449122580** [comment]
浏览器允许弹出窗口，配置服务器还是不会弹出授权怎么办？

**Comment by jzp820927** [comment]
你上面不是说，你服务端已经部署好了吗？

**Comment by a449122580** [comment]
![image](https://user-images.githubusercontent.com/13272715/27334211-1e79e732-55fb-11e7-84d6-cc01721ccbf2.png)
![image](https://user-images.githubusercontent.com/13272715/27334267-4f41ea90-55fb-11e7-98db-ae53cb7e7f31.png)

**Comment by a449122580** [comment]
@jzp820927 新加两个appid

**Comment by jzp820927** [comment]
你是要部署新的 appid？

**Comment by a449122580** [comment]
昨天挂了一晚上，今天早上又部署成功了

**Comment by a449122580** [comment]
![image](https://user-images.githubusercontent.com/13272715/27362380-b118b216-5660-11e7-895d-cfe89c6ab62d.png)

**Comment by jzp820927** [comment]
搞定了就好，现在可以正常使用了撒？

**Comment by liangliangge521** [comment]
最简单方法就是把你上一版本的 data 文件夹复制到新版本里覆盖，这样就不用从新部署了，我一般无法部署时都用这方法
