### ISSUE TITLE
初次运行未产生 CA.crt

### ISSUE THREAD

**Issue by wdoo01** [XX-net/XX-Net#588]
初次运行如下

```
> sudo ./start.sh 
('launcher version:', '1.4.0')
Jul  7 20:16:21 - [INFO] use goagent version:3.1.49
Jul  7 20:16:21 - [INFO] goagent 3.1.49 started /home/zh/tools/XX-Net/goagent/3.1.49/start.py
Traceback (most recent call last):
  File "/home/zh/tools/XX-Net/goagent/3.1.49/start.py", line 13, in <module>
    import local.proxy as goagent
  File "/home/zh/tools/XX-Net/goagent/3.1.49/local/proxy.py", line 78, in <module>
    import pac_server
  File "/home/zh/tools/XX-Net/goagent/3.1.49/local/pac_server.py", line 52, in <module>
    opener = create_url_opener()
  File "/home/zh/tools/XX-Net/goagent/3.1.49/local/pac_server.py", line 44, in create_url_opener
    cafile=cafile)
  File "/usr/lib64/python2.7/ssl.py", line 435, in create_default_context
    context.load_verify_locations(cafile, capath, cadata)
IOError: [Errno 2] No such file or directory

```

而 data/goagent/ 下也没有 CA.crt 

直接运行 xx-net/goagent 的 proxy.py 结果基本同上

系统：Fedora 22

nss-tools python-nss 是源里最新的

已知可运行官方的goagent 3.2 （虽然一片 timeout） 

求教……

**Comment by tossp** [comment]
archlinux +1

**Comment by tossp** [comment]
我尝试把我在win7中的data目录给覆盖过来就正常了

**Comment by xxnet** [comment]
发了 1.16.4 修复了这个问题

2015-07-08 15:17 GMT+08:00 TossPig <notifications@github.com>:

**Comment by wdoo01** [comment]
确实修复了，谢谢
