### ISSUE TITLE
使用用一会就显示：请检查浏览器代理设置。

### ISSUE THREAD

**Issue by qjlxg** [XX-net/XX-Net#5905]
刷新也不可以  退出客户端再打又可以用一会，过后又不行
删除过CA.crt和certs文件夹也无效
属性	值
本地网络状态	OK
IP数量	570
空闲	0
IP延迟	65
连接池(帮助)	新:1 h1:17 h2:26
浏览器代理设置	Fail
CA证书状态(下载)	Fail
刚进入后的日志:
Jun 30 15:37:52.663 - [ERROR] load ip range: fail:ValueError("invalid literal for int() with base 10: '\\xe9\\xa6\\x99\\xe6\\xb8\\xaf'",)
Jun 30 15:37:52.663 - [ERROR] Except stack:Traceback (most recent call last): File "D:\XX-Net-3.3.2\XX-Net-3.3.4\code\default\gae_proxy\local\google_ip_range.py", line 64, in load_ip_range nbegin = ip_utils.ip_string_to_num(begin) File "D:\XX-Net-3.3.2\XX-Net-3.3.4\code\default\gae_proxy\local\ip_utils.py", line 9, in ip_string_to_num return reduce(lambda a, b: a << 8 | b, map(int, s.split("."))) ValueError: invalid literal for int() with base 10: '\xe9\xa6\x99\xe6\xb8\xaf'
Jun 30 15:37:52.663 - [ERROR] load ip range: fail:ValueError("invalid literal for int() with base 10: '\\xe5\\x8f\\xb0\\xe6\\xb9\\xbe'",)
Jun 30 15:37:52.664 - [ERROR] Except stack:Traceback (most recent call last): File "D:\XX-Net-3.3.2\XX-Net-3.3.4\code\default\gae_proxy\local\google_ip_range.py", line 64, in load_ip_range nbegin = ip_utils.ip_string_to_num(begin) File "D:\XX-Net-3.3.2\XX-Net-3.3.4\code\default\gae_proxy\local\ip_utils.py", line 9, in ip_string_to_num return reduce(lambda a, b: a << 8 | b, map(int, s.split("."))) ValueError: invalid literal for int() with base 10: '\xe5\x8f\xb0\xe6\xb9\xbe'
Jun 30 15:37:52.664 - [ERROR] load ip range: fail:ValueError("invalid literal for int() with base 10: '\\xe7\\xbe\\x8e\\xe5\\x9b\\xbd'",)
Jun 30 15:37:52.664 - [ERROR] Except stack:Traceback (most recent call last): File "D:\XX-Net-3.3.2\XX-Net-3.3.4\code\default\gae_proxy\local\google_ip_range.py", line 64, in load_ip_range nbegin = ip_utils.ip_string_to_num(begin) File "D:\XX-Net-3.3.2\XX-Net-3.3.4\code\default\gae_proxy\local\ip_utils.py", line 9, in ip_string_to_num return reduce(lambda a, b: a << 8 | b, map(int, s.split("."))) ValueError: invalid literal for int() with base 10: '\xe7\xbe\x8e\xe5\x9b\xbd'
Jun 30 15:37:52.664 - [ERROR] load ip range: fail:ValueError("invalid literal for int() with base 10: '\\xe6\\xbe\\xb3\\xe9\\x97\\xa8'",)
Jun 30 15:37:52.664 - [ERROR] Except stack:Traceback (most recent call last): File "D:\XX-Net-3.3.2\XX-Net-3.3.4\code\default\gae_proxy\local\google_ip_range.py", line 64, in load_ip_range nbegin = ip_utils.ip_string_to_num(begin) File "D:\XX-Net-3.3.2\XX-Net-3.3.4\code\default\gae_proxy\local\ip_utils.py", line 9, in ip_string_to_num return reduce(lambda a, b: a << 8 | b, map(int, s.split("."))) ValueError: invalid literal for int() with base 10: '\xe6\xbe\xb3\xe9\x97\xa8'
Jun 30 15:37:52.664 - [ERROR] load ip range://///////////////////////////////////// fail:ValueError('too many values to unpack',)
Jun 30 15:37:52.664 - [ERROR] Except stack:Traceback (most recent call last): File "D:\XX-Net-3.3.2\XX-Net-3.3.4\code\default\gae_proxy\local\google_ip_range.py", line 63, in load_ip_range begin, end = ip_utils.split_ip(line) File "D:\XX-Net-3.3.2\XX-Net-3.3.4\code\default\gae_proxy\local\ip_utils.py", line 109, in split_ip (ip, bits) = strline.split("/") ValueError: too many values to unpack
Jun 30 15:37:52.664 - [ERROR] load ip range::202.158.57.0-202.158.57.255 fail:ValueError("invalid literal for int() with base 10: '\\xe5\\x8d\\xb0\\xe5\\xb0\\xbc:202'",)
Jun 30 15:37:52.664 - [ERROR] Except stack:Traceback (most recent call last): File "D:\XX-Net-3.3.2\XX-Net-3.3.4\code\default\gae_proxy\local\google_ip_range.py", line 64, in load_ip_range nbegin = ip_utils.ip_string_to_num(begin) File "D:\XX-Net-3.3.2\XX-Net-3.3.4\code\default\gae_proxy\local\ip_utils.py", line 9, in ip_string_to_num return reduce(lambda a, b: a << 8 | b, map(int, s.split("."))) ValueError: invalid literal for int() with base 10: '\xe5\x8d\xb0\xe5\xb0\xbc:202'
Jun 30 15:37:52.664 - [ERROR] load ip range::115.84.108.0-115.84.108.255 fail:ValueError("invalid literal for int() with base 10: '\\xe8\\x80\\x81\\xe6\\x8c\\x9d:115'",)
Jun 30 15:37:52.664 - [ERROR] Except stack:Traceback (most recent call last): File "D:\XX-Net-3.3.2\XX-Net-3.3.4\code\default\gae_proxy\local\google_ip_range.py", line 64, in load_ip_range nbegin = ip_utils.ip_string_to_num(begin) File "D:\XX-Net-3.3.2\XX-Net-3.3.4\code\default\gae_proxy\local\ip_utils.py", line 9, in ip_string_to_num return reduce(lambda a, b: a << 8 | b, map(int, s.split("."))) ValueError: invalid literal for int() with base 10: '\xe8\x80\x81\xe6\x8c\x9d:115'

**Comment by SeaHOH** [comment]
似乎文件损坏了，重新下载个试试。

**Comment by qjlxg** [comment]
我试过，没有效果

**Comment by SeaHOH** [comment]
md5 对得上吗？

**Comment by qjlxg** [comment]
不能用后日志有提示:
[WARNING] server app return fail, status:502
[WARNING] consume_single_frame:ConnectionResetError()
[DEBUG]  worker close:idle timeout

**Comment by SeaHOH** [comment]
怀疑 ip_range.txt 有损坏，单独下载它替换试试。

**Comment by qjlxg** [comment]
我先试试看，谢谢。

**Comment by qjlxg** [comment]
我换回3.3.2暂时正常.
