### ISSUE TITLE
XX-Net无法打开

### ISSUE THREAD

**Issue by zzy2** [XX-net/XX-Net#6014]
运行start.bat报错
launcher.log的内容:
Jul 13 13:07:31.101 - [INFO] use build-in openssl lib
Jul 13 13:07:31.132 - [INFO] start XX-Net 3.3.4
Jul 13 13:07:31.199 - [DEBUG] start confirm_xxnet_exit
Jul 13 13:07:32.249 - [DEBUG] good, xxnet:8087 cleared!
Jul 13 13:07:33.271 - [DEBUG] good, xxnet:8085 clear!
Jul 13 13:07:33.279 - [DEBUG] finished confirm_xxnet_exit
Jul 13 13:07:37.984 - [ERROR] start module gae_proxy fail:can't start new thread
Jul 13 13:07:46.294 - [ERROR] Except stack:Traceback (most recent call last):
  File "C:\Users\wiran\Documents\XX-Net-3.3.4\code\default\launcher\module_init.py", line 37, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "C:\Users\wiran\Documents\XX-Net-3.3.4\code\default\gae_proxy\start.py", line 13, in <module>
    import local.proxy as client
  File "C:\Users\wiran\Documents\XX-Net-3.3.4\code\default\gae_proxy\local\proxy.py", line 97, in <module>
    import proxy_handler
  File "C:\Users\wiran\Documents\XX-Net-3.3.4\code\default\gae_proxy\local\proxy_handler.py", line 54, in <module>
    import gae_handler
  File "C:\Users\wiran\Documents\XX-Net-3.3.4\code\default\gae_proxy\local\gae_handler.py", line 69, in <module>
    from google_ip import google_ip
  File "C:\Users\wiran\Documents\XX-Net-3.3.4\code\default\gae_proxy\local\google_ip.py", line 730, in <module>
    google_ip = IpManager()
  File "C:\Users\wiran\Documents\XX-Net-3.3.4\code\default\gae_proxy\local\google_ip.py", line 67, in __init__
    self.reset()
  File "C:\Users\wiran\Documents\XX-Net-3.3.4\code\default\gae_proxy\local\google_ip.py", line 111, in reset
    self.search_more_google_ip()
  File "C:\Users\wiran\Documents\XX-Net-3.3.4\code\default\gae_proxy\local\google_ip.py", line 663, in search_more_google_ip
    p.start()
  File "C:\Users\wiran\Documents\XX-Net-3.3.4\code\default\python27\1.0\lib\threading.py", line 736, in start
    _start_new_thread(self.__bootstrap, ())
error: can't start new thread

Jul 13 13:07:46.339 - [ERROR] launcher except:error("can't start new thread",)
Jul 13 13:07:46.468 - [ERROR] Except stack:Traceback (most recent call last):
  File "C:\Users\wiran\Documents\XX-Net-3.3.4\code\default\launcher\start.py", line 182, in <module>
    main()
  File "C:\Users\wiran\Documents\XX-Net-3.3.4\code\default\launcher\start.py", line 159, in main
    module_init.start_all_auto()
  File "C:\Users\wiran\Documents\XX-Net-3.3.4\code\default\launcher\module_init.py", line 98, in start_all_auto
    start(module)
  File "C:\Users\wiran\Documents\XX-Net-3.3.4\code\default\launcher\module_init.py", line 37, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "C:\Users\wiran\Documents\XX-Net-3.3.4\code\default\gae_proxy\start.py", line 13, in <module>
    import local.proxy as client
  File "C:\Users\wiran\Documents\XX-Net-3.3.4\code\default\gae_proxy\local\proxy.py", line 97, in <module>
    import proxy_handler
  File "C:\Users\wiran\Documents\XX-Net-3.3.4\code\default\gae_proxy\local\proxy_handler.py", line 54, in <module>
    import gae_handler
  File "C:\Users\wiran\Documents\XX-Net-3.3.4\code\default\gae_proxy\local\gae_handler.py", line 69, in <module>
    from google_ip import google_ip
  File "C:\Users\wiran\Documents\XX-Net-3.3.4\code\default\gae_proxy\local\google_ip.py", line 730, in <module>
    google_ip = IpManager()
  File "C:\Users\wiran\Documents\XX-Net-3.3.4\code\default\gae_proxy\local\google_ip.py", line 67, in __init__
    self.reset()
  File "C:\Users\wiran\Documents\XX-Net-3.3.4\code\default\gae_proxy\local\google_ip.py", line 111, in reset
    self.search_more_google_ip()
  File "C:\Users\wiran\Documents\XX-Net-3.3.4\code\default\gae_proxy\local\google_ip.py", line 663, in search_more_google_ip
    p.start()
  File "C:\Users\wiran\Documents\XX-Net-3.3.4\code\default\python27\1.0\lib\threading.py", line 736, in start
    _start_new_thread(self.__bootstrap, ())
error: can't start new thread

**Comment by SeaHOH** [comment]
下载后第一次运行？可能有坏文件，请重新下载。

否则重启一下机器看是否正常。

再不然就进行下系统更新。

**Comment by LockGit** [comment]
建议改成 XX-Net 3.3.1  稳定版， 你是windows系统，从最后的报错信息可以看出，是无法创建新线程

**Comment by warmd** [comment]
Jul 13 22:06:45.860 - [INFO] use build-in openssl lib
Jul 13 22:06:45.860 - [INFO] start XX-Net 3.3.4
Jul 13 22:06:45.860 - [DEBUG] start confirm_xxnet_exit
Jul 13 22:06:45.866 - [DEBUG] <0>: try to terminate xxnet:8087
Jul 13 22:06:47.867 - [DEBUG] good, xxnet:8087 cleared!
Jul 13 22:06:48.879 - [DEBUG] good, xxnet:7777 clear!
Jul 13 22:06:48.879 - [DEBUG] finished confirm_xxnet_exit
Jul 13 22:06:50.048 - [ERROR] start module gae_proxy fail:can't start new thread
Jul 13 22:06:50.049 - [ERROR] Except stack:Traceback (most recent call last):
  File "Z:\Program Files\XX-Net-3.1.19\code\3.3.4\launcher\module_init.py", line 37, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "Z:\Program Files\XX-Net-3.1.19\code\3.3.4\gae_proxy\start.py", line 13, in <module>
    import local.proxy as client
  File "Z:\Program Files\XX-Net-3.1.19\code\3.3.4\gae_proxy\local\proxy.py", line 97, in <module>
    import proxy_handler
  File "Z:\Program Files\XX-Net-3.1.19\code\3.3.4\gae_proxy\local\proxy_handler.py", line 54, in <module>
    import gae_handler
  File "Z:\Program Files\XX-Net-3.1.19\code\3.3.4\gae_proxy\local\gae_handler.py", line 69, in <module>
    from google_ip import google_ip
  File "Z:\Program Files\XX-Net-3.1.19\code\3.3.4\gae_proxy\local\google_ip.py", line 730, in <module>
    google_ip = IpManager()
  File "Z:\Program Files\XX-Net-3.1.19\code\3.3.4\gae_proxy\local\google_ip.py", line 67, in __init__
    self.reset()
  File "Z:\Program Files\XX-Net-3.1.19\code\3.3.4\gae_proxy\local\google_ip.py", line 111, in reset
    self.search_more_google_ip()
  File "Z:\Program Files\XX-Net-3.1.19\code\3.3.4\gae_proxy\local\google_ip.py", line 663, in search_more_google_ip
    p.start()
  File "Z:\Program Files\XX-Net-3.1.19\code\3.3.4\python27\1.0\lib\threading.py", line 736, in start
    _start_new_thread(self.__bootstrap, ())
error: can't start new thread

Jul 13 22:06:50.049 - [ERROR] launcher except:error("can't start new thread",)
Jul 13 22:06:50.050 - [ERROR] Except stack:Traceback (most recent call last):
  File "Z:\Program Files\XX-Net-3.1.19\code\3.3.4\launcher\start.py", line 182, in <module>
    main()
  File "Z:\Program Files\XX-Net-3.1.19\code\3.3.4\launcher\start.py", line 159, in main
    module_init.start_all_auto()
  File "Z:\Program Files\XX-Net-3.1.19\code\3.3.4\launcher\module_init.py", line 98, in start_all_auto
    start(module)
  File "Z:\Program Files\XX-Net-3.1.19\code\3.3.4\launcher\module_init.py", line 37, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "Z:\Program Files\XX-Net-3.1.19\code\3.3.4\gae_proxy\start.py", line 13, in <module>
    import local.proxy as client
  File "Z:\Program Files\XX-Net-3.1.19\code\3.3.4\gae_proxy\local\proxy.py", line 97, in <module>
    import proxy_handler
  File "Z:\Program Files\XX-Net-3.1.19\code\3.3.4\gae_proxy\local\proxy_handler.py", line 54, in <module>
    import gae_handler
  File "Z:\Program Files\XX-Net-3.1.19\code\3.3.4\gae_proxy\local\gae_handler.py", line 69, in <module>
    from google_ip import google_ip
  File "Z:\Program Files\XX-Net-3.1.19\code\3.3.4\gae_proxy\local\google_ip.py", line 730, in <module>
    google_ip = IpManager()
  File "Z:\Program Files\XX-Net-3.1.19\code\3.3.4\gae_proxy\local\google_ip.py", line 67, in __init__
    self.reset()
  File "Z:\Program Files\XX-Net-3.1.19\code\3.3.4\gae_proxy\local\google_ip.py", line 111, in reset
    self.search_more_google_ip()
  File "Z:\Program Files\XX-Net-3.1.19\code\3.3.4\gae_proxy\local\google_ip.py", line 663, in search_more_google_ip
    p.start()
  File "Z:\Program Files\XX-Net-3.1.19\code\3.3.4\python27\1.0\lib\threading.py", line 736, in start
    _start_new_thread(self.__bootstrap, ())
error: can't start new thread

Jul 13 22:06:51.169 - [ERROR] stop module gae_proxy fail:'imp'
Jul 13 22:06:51.169 - [ERROR] Except stack:Traceback (most recent call last):
  File "Z:\Program Files\XX-Net-3.1.19\code\3.3.4\launcher\module_init.py", line 71, in stop
    _start = proc_handler[module]["imp"].start
KeyError: 'imp'

**Comment by jzp820927** [comment]
有没有改动过 扫描线程？感觉好像是 扫描线程过高？

**Comment by warmd** [comment]
@jzp820927 改过。。。现在应该如何改回？

**Comment by warmd** [comment]
@jzp820927 改回后已恢复，谢谢～

**Comment by zzy2** [comment]
谢谢各位,原因是扫描ip线程过多,已经解决:)
