### ISSUE TITLE
youtube不能播放视频

### ISSUE THREAD

**Issue by wsgdlhy** [XX-net/XX-Net#6082]
网站能打开，但播放不了视频，中间的圆圈一直在转。

**Comment by wsgdlhy** [comment]
7月 22 16:25:24.51 - [WARNING] no enough ip

7月 22 16:25:25.51 - [WARNING] no enough ip

7月 22 16:25:26.51 - [WARNING] no enough ip

7月 22 16:25:27.51 - [WARNING] no enough ip

7月 22 16:25:27.51 - [WARNING] no enough ip

7月 22 16:25:28.52 - [WARNING] no enough ip

7月 22 16:25:30.84 - [ERROR] ssl.wrap_socket(self.connection=) failed: [SSL: SSLV3_ALERT_CERTIFICATE_EXPIRED] sslv3 alert certificate expired (_ssl.c:1864) path:redirector.googlevideo.com:443, errno:1

7月 22 16:25:30.84 - [ERROR] Except stack:Traceback (most recent call last): File "/home/xx/XX-Net-master/code/3.3.4/gae_proxy/local/proxy_handler.py", line 314, in do_CONNECT_AGENT self.raw_requestline = self.rfile.readline(65537) File "/usr/lib/python2.7/socket.py", line 480, in readline data = self._sock.recv(self._rbufsize) File "/usr/lib/python2.7/ssl.py", line 766, in recv return self.read(buflen) File "/usr/lib/python2.7/ssl.py", line 653, in read v = self._sslobj.read(len) SSLError: [SSL: SSLV3_ALERT_CERTIFICATE_EXPIRED] sslv3 alert certificate expired (_ssl.c:1864)

7月 22 16:25:38.74 - [ERROR] ssl.wrap_socket(self.connection=) failed: [SSL: SSLV3_ALERT_CERTIFICATE_EXPIRED] sslv3 alert certificate expired (_ssl.c:1864) path:s.youtube.com:443, errno:1

7月 22 16:25:38.74 - [ERROR] Except stack:Traceback (most recent call last): File "/home/xx/XX-Net-master/code/3.3.4/gae_proxy/local/proxy_handler.py", line 314, in do_CONNECT_AGENT self.raw_requestline = self.rfile.readline(65537) File "/usr/lib/python2.7/socket.py", line 480, in readline data = self._sock.recv(self._rbufsize) File "/usr/lib/python2.7/ssl.py", line 766, in recv return self.read(buflen) File "/usr/lib/python2.7/ssl.py", line 653, in read v = self._sslobj.read(len) SSLError: [SSL: SSLV3_ALERT_CERTIFICATE_EXPIRED] sslv3 alert certificate expired (_ssl.c:1864)

**Comment by wsgdlhy** [comment]
已解决，删除证书重新导入就行了
