### ISSUE TITLE
使用you-get下载youtube视频失败 close() takes at most 2 arguments (3 given)

### ISSUE THREAD

**Issue by N46AN** [XX-net/XX-Net#6084]
使用以下命令下载：
```
$ ./you-get -di -x 127.0.0.1:8087 https://www.youtube.com/watch?v=hEnyvdvS6UQ
[DEBUG] get_content: https://www.youtube.com/get_video_info?video_id=hEnyvdvS6UQ
[DEBUG] get_content: https://www.youtube.com/watch?v=hEnyvdvS6UQ
[DEBUG] get_content: https://www.youtube.com/yts/jsbin/player-vflGD0HaZ/en_US/base.js
```
在这里卡住不动。

与此同时，xxnet日志：
```
Jul 22 19:29:31.550 - [DEBUG] ssl_closed 173.194.26.104
Jul 22 19:29:38.184 - [DEBUG] ip:216.58.207.74 real fail
Jul 22 19:31:32.884 - [DEBUG] GAE GET https://www.youtube.com/get_video_info?video_id=hEnyvdvS6UQ
^[[A^[[BJul 22 19:31:52.635 - [DEBUG] GAE GET https://www.youtube.com/get_video_info?video_id=hEnyvdvS6UQ
Jul 22 19:31:53.431 - [INFO] GAE t:790 s:42920 GET https://www.youtube.com/get_video_info?video_id=hEnyvdvS6UQ h2_get_head:560,h2_finish[SP:193342]:223
Jul 22 19:31:53.562 - [DEBUG] GAE GET https://www.youtube.com/watch?v=hEnyvdvS6UQ
Jul 22 19:31:54.697 - [INFO] GAE t:1133 s:176961 GET https://www.youtube.com/watch?v=hEnyvdvS6UQ h2_get_head:617,h2_finish[SP:346991]:510
Jul 22 19:31:54.816 - [DEBUG] GAE GET https://www.youtube.com/yts/jsbin/player-vflGD0HaZ/en_US/base.js
Jul 22 19:31:55.097 - [INFO] RangeFetch 0-1246938 started('https://www.youtube.com/yts/jsbin/player-vflGD0HaZ/en_US/base.js') 
Exception in thread Thread-94:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/simon/Apps/XX-Net-3.2.3/code/3.3.4/gae_proxy/local/gae_handler.py", line 613, in fetch_worker
    self.fetch(begin, end, None)
  File "/home/simon/Apps/XX-Net-3.2.3/code/3.3.4/gae_proxy/local/gae_handler.py", line 649, in fetch
    response.worker.close("range status:%s", response.status)
TypeError: close() takes at most 2 arguments (3 given)

Jul 22 19:31:56.896 - [DEBUG] RangeFetch [209.85.234.98] 43% length:548576 range:bytes 0-548575/1246939 https://www.youtube.com/yts/jsbin/player-vflGD0HaZ/en_US/base.js h2_get_head:270

```
在这里卡住不动。

多次尝试，现象完全一样。卡住的位置相同

**Comment by wildcatstudio** [comment]
复制下载链接到迅雷，迅雷设置xx-net代理，就可以断点续传了。
