### ISSUE TITLE
部署服务器时出错

### ISSUE THREAD

**Issue by zhangqiangeek** [XX-net/XX-Net#6126]
2017-07-27 18:53:49,877 - root - INFO - set proxy to http://127.0.0.1:8087
2017-07-27 18:53:49,878 - root - INFO - ============ Begin upload ============
2017-07-27 18:53:49,878 - root - INFO - appid:macxx-175010
2017-07-27 18:53:49,893 - root - INFO - Send: /api/appversion/rollback, params={'version': '1', 'app_id': 'macxx-175010'}
2017-07-27 18:53:50,392 - root - ERROR - upload fail:EOFError('EOF when reading a line',)
Traceback (most recent call last):
File "/Users/evilhex/myapp/XX-Net-3.3.6/code/default/gae_proxy/server/uploader.py", line 70, in upload
result = appcfg.AppCfgApp(['appcfg', 'rollback', dirname ]).Run()
File "/Users/evilhex/myapp/XX-Net-3.3.6/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 2951, in Run
self.action(self)
File "/Users/evilhex/myapp/XX-Net-3.3.6/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 5044, in __call__
return method()
File "/Users/evilhex/myapp/XX-Net-3.3.6/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 4397, in Rollback
self._Rollback()
File "/Users/evilhex/myapp/XX-Net-3.3.6/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 4442, in _Rollback
appversion.Rollback(force_rollback)
File "/Users/evilhex/myapp/XX-Net-3.3.6/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 2362, in Rollback
force_rollback='1' if force_rollback else '0')
File "/Users/evilhex/myapp/XX-Net-3.3.6/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 1696, in Send
result = self.rpcserver.Send(url, payload=payload, **kwargs)
File "/Users/evilhex/myapp/XX-Net-3.3.6/code/default/gae_proxy/server/lib/google/appengine/tools/appengine_rpc_httplib2.py", line 241, in Send
self._Authenticate(self.http, auth_errors[0] > 0)
File "/Users/evilhex/myapp/XX-Net-3.3.6/code/default/gae_proxy/server/lib/google/appengine/tools/appengine_rpc_httplib2.py", line 459, in _Authenticate
self.credentials = tools.run_flow(flow, self.storage, self.flags)
File "/Users/evilhex/myapp/XX-Net-3.3.6/code/default/gae_proxy/server/lib/oauth2client/util.py", line 137, in positional_wrapper
return wrapped(*args, **kwargs)
File "/Users/evilhex/myapp/XX-Net-3.3.6/code/default/gae_proxy/server/lib/oauth2client/tools.py", line 222, in run_flow
code = input('Enter verification code: ').strip()
EOFError: EOF when reading a line
2017-07-27 18:53:50,394 - root - INFO - Retry 1 time...
2017-07-27 18:53:50,406 - root - INFO - Send: /api/appversion/rollback, params={'version': '1', 'app_id': 'macxx-175010'}
2017-07-27 18:53:50,699 - root - ERROR - upload fail:EOFError('EOF when reading a line',)
Traceback (most recent call last):
File "/Users/evilhex/myapp/XX-Net-3.3.6/code/default/gae_proxy/server/uploader.py", line 70, in upload
result = appcfg.AppCfgApp(['appcfg', 'rollback', dirname ]).Run()
File "/Users/evilhex/myapp/XX-Net-3.3.6/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 2951, in Run
self.action(self)
File "/Users/evilhex/myapp/XX-Net-3.3.6/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 5044, in __call__
return method()
File "/Users/evilhex/myapp/XX-Net-3.3.6/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 4397, in Rollback
self._Rollback()
File "/Users/evilhex/myapp/XX-Net-3.3.6/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 4442, in _Rollback
appversion.Rollback(force_rollback)
File "/Users/evilhex/myapp/XX-Net-3.3.6/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 2362, in Rollback
force_rollback='1' if force_rollback else '0')
File "/Users/evilhex/myapp/XX-Net-3.3.6/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 1696, in Send
result = self.rpcserver.Send(url, payload=payload, **kwargs)
File "/Users/evilhex/myapp/XX-Net-3.3.6/code/default/gae_proxy/server/lib/google/appengine/tools/appengine_rpc_httplib2.py", line 241, in Send
self._Authenticate(self.http, auth_errors[0] > 0)
File "/Users/evilhex/myapp/XX-Net-3.3.6/code/default/gae_proxy/server/lib/google/appengine/tools/appengine_rpc_httplib2.py", line 459, in _Authenticate
self.credentials = tools.run_flow(flow, self.storage, self.flags)
File "/Users/evilhex/myapp/XX-Net-3.3.6/code/default/gae_proxy/server/lib/oauth2client/util.py", line 137, in positional_wrapper
return wrapped(*args, **kwargs)
File "/Users/evilhex/myapp/XX-Net-3.3.6/code/default/gae_proxy/server/lib/oauth2client/tools.py", line 222, in run_flow
code = input('Enter verification code: ').strip()
EOFError: EOF when reading a line
2017-07-27 18:53:50,699 - root - INFO - Retry 2 time...
2017-07-27 18:53:51,715 - root - INFO - Send: /api/appversion/rollback, params={'version': '1', 'app_id': 'macxx-175010'}
2017-07-27 18:53:51,995 - root - ERROR - upload fail:EOFError('EOF when reading a line',)
Traceback (most recent call last):
File "/Users/evilhex/myapp/XX-Net-3.3.6/code/default/gae_proxy/server/uploader.py", line 70, in upload
result = appcfg.AppCfgApp(['appcfg', 'rollback', dirname ]).Run()
File "/Users/evilhex/myapp/XX-Net-3.3.6/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 2951, in Run
self.action(self)
File "/Users/evilhex/myapp/XX-Net-3.3.6/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 5044, in __call__
return method()
File "/Users/evilhex/myapp/XX-Net-3.3.6/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 4397, in Rollback
self._Rollback()
File "/Users/evilhex/myapp/XX-Net-3.3.6/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 4442, in _Rollback
appversion.Rollback(force_rollback)
File "/Users/evilhex/myapp/XX-Net-3.3.6/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 2362, in Rollback
force_rollback='1' if force_rollback else '0')
File "/Users/evilhex/myapp/XX-Net-3.3.6/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 1696, in Send
result = self.rpcserver.Send(url, payload=payload, **kwargs)
File "/Users/evilhex/myapp/XX-Net-3.3.6/code/default/gae_proxy/server/lib/google/appengine/tools/appengine_rpc_httplib2.py", line 241, in Send
self._Authenticate(self.http, auth_errors[0] > 0)
File "/Users/evilhex/myapp/XX-Net-3.3.6/code/default/gae_proxy/server/lib/google/appengine/tools/appengine_rpc_httplib2.py", line 459, in _Authenticate
self.credentials = tools.run_flow(flow, self.storage, self.flags)
File "/Users/evilhex/myapp/XX-Net-3.3.6/code/default/gae_proxy/server/lib/oauth2client/util.py", line 137, in positional_wrapper
return wrapped(*args, **kwargs)
File "/Users/evilhex/myapp/XX-Net-3.3.6/code/default/gae_proxy/server/lib/oauth2client/tools.py", line 222, in run_flow
code = input('Enter verification code: ').strip()
EOFError: EOF when reading a line
2017-07-27 18:53:51,995 - root - INFO - Retry 3 time...
2017-07-27 18:53:53,996 - root - INFO - =======================
2017-07-27 18:53:53,996 - root - INFO - Deploy failed appid list:
2017-07-27 18:53:53,996 - root - INFO - - macxx-175010
2017-07-27 18:53:53,996 - root - INFO - == END ==

**Comment by jzp820927** [comment]
https://github.com/XX-net/XX-Net/wiki/how-to-create-my-appids
