### ISSUE TITLE
这是什么情况，不影响使用！

### ISSUE THREAD

**Issue by shenhix** [XX-net/XX-Net#613]
Jul 14 11:47:05 - [ERROR] gae_handler except:error(10058, '') http://i.ytimg.com/vi/mlAeekLgMDM/mqdefault.jpg
Jul 14 11:47:05 - [ERROR] Except stack:Traceback (most recent call last): File "D:\Administrator\Documents\X\����\XX-Net\goagent\3.1.49\local\gae_handler.py", line 345, in handler wfile.write("HTTP/1.1 %d undefined\r\n" % (response.status, response.reason)) File "D:\Administrator\Documents\X\����\XX-Net\python27\1.0\lib\socket.py", line 324, in write self.flush() File "D:\Administrator\Documents\X\����\XX-Net\python27\1.0\lib\socket.py", line 303, in flush self._sock.sendall(view[write_offset:write_offset+buffer_size]) File "D:\Administrator\Documents\X\����\XX-Net\python27\1.0\lib\ssl.py", line 229, in sendall v = self.send(data[count:]) File "D:\Administrator\Documents\X\����\XX-Net\python27\1.0\lib\ssl.py", line 198, in send v = self._sslobj.write(data) error: [Errno 10058]

**Comment by shenhix** [comment]
已解决！。。
是配置文件没搞好！
