### ISSUE TITLE
Ubuntu16.04 启动start报错python-openssl, 安装完成后仍然无法启动

### ISSUE THREAD

**Issue by chy996633** [XX-net/XX-Net#6265]
Ubuntu16.04
Python2.7

情况: 进入XX-Net文件夹执行./start 提示 

`Python 2.7.12
XX-Net version:default
Installing pyOpenSSL for your system... Please type in your password if requested
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-openssl is already the newest version (0.15.1-2build1).
0 upgraded, 0 newly installed, 0 to remove and 102 not upgraded.
XX-Net.desktop already exists
Aug 14 21:18:12.955 - [INFO] import build-in openssl fail:AttributeError("'module' object has no attribute 'SSL_ST_INIT'",)
Aug 14 21:18:12.959 - [ERROR] import system python-OpenSSL fail:AttributeError("'module' object has no attribute 'SSL_ST_INIT'",)
Aug 14 21:18:12.960 - [ERROR] Except stack:Traceback (most recent call last):
  File "code/default/launcher/start.py", line 112, in <module>
    import OpenSSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 118, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'

Try install python-openssl
`

运行命令 sudo apt-get install python-openssl 后发现已经安装最新版本

而 pip install python-openssl 则无法安装对应的模块

请问该如何解决?

**Comment by chy996633** [comment]
After I run

sudo pip uninstall pyOpenSSL 
sudo pip install pyOpenSSL 

it started !
