### ISSUE TITLE
 No module named systray

### ISSUE THREAD

**Issue by sd3494702** [XX-net/XX-Net#628]
下载了最新的XX-Net-master后.双击START.BAT后不能用.出现如下
Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

C:\Users\TNT>"D:\Google Chrome\XX-Net-master\start.bat"

C:\Users\TNT>"D:\Google Chrome\XX-Net-master\python27/1.0/python.exe" "D:\Google
 Chrome\XX-Net-master\launcher/start.py"
Traceback (most recent call last):
  File "D:\Google Chrome\XX-Net-master\launcher/start.py", line 29, in <module>
    from win_tray import sys_tray
  File "D:\Google Chrome\XX-Net-master\launcher\win_tray.py", line 13, in <modul
e>
    from systray import SysTrayIcon
ImportError: No module named systray

C:\Users\TNT>

之前的那个版本还用的好好的.

**Comment by Cat7373** [comment]
有新版 2.0.1 更新即可
