### ISSUE TITLE
XX的朋友们，有没有会这个的？

### ISSUE THREAD

**Issue by lele2010lele** [XX-net/XX-Net#6324]

**Comment by lele2010lele** [comment]
第二个问题，我下载的YouTube-dlGUI也是不会用，不显示下载

![image](https://user-images.githubusercontent.com/10057760/29761591-837582ea-8bfc-11e7-9a86-32d0f9f7d1b8.png)

![image](https://user-images.githubusercontent.com/10057760/29761644-c43462f6-8bfc-11e7-9b13-991d3b1576f4.png)

**Comment by lele2010lele** [comment]
![image](https://user-images.githubusercontent.com/10057760/29761664-e3b1d7e4-8bfc-11e7-8edc-74cbb7311b7b.png)

**Comment by onplus** [comment]
2. 试试放在D盘，权限问题

**Comment by justfornodejs** [comment]
硕鼠不好吗

**Comment by lele2010lele** [comment]
硕鼠可以下载YouTube吗？

**Comment by lele2010lele** [comment]
@onplus 放别的盘就有log了。。。。
Exception in thread Thread-5:
Traceback (most recent call last):
  File "threading.pyc", line 810, in __bootstrap_inner
  File "youtube_dl_gui\downloadmanager.pyc", line 248, in run
  File "youtube_dl_gui\downloaders.pyc", line 105, in download
  File "youtube_dl_gui\downloaders.pyc", line 292, in _create_process
  File "subprocess.pyc", line 710, in __init__
  File "subprocess.pyc", line 958, in _execute_child
WindowsError: [Error 2]

**Comment by pdwjun** [comment]
@lele2010lele 可以下youtube，但还是需要代理才能下

**Comment by lele2010lele** [comment]
试过了，不好用的硕鼠，等了好久都是0%，我还是老老实实的用youtube-dl吧，麻烦就麻烦点

**Comment by iceliminghui** [comment]
@lele2010lele 下载youtube的视频，用油猴插件，或者IDM。
