### ISSUE TITLE
使用最新版，Appid注册成功，部署失败（Ubuntu 2017系统）

### ISSUE THREAD

**Issue by LoneStar01** [XX-net/XX-Net#6360]
公共APPID联网正常，注册正常。
弹不出新网页，当前页提示部署完成，但日志显示部署失败！（（Connection Refused）

2017-09-03 16:33:36,487 - root - INFO - enable debug logging
2017-09-03 16:33:36,488 - root - INFO - set proxy to http://127.0.0.1:8087
2017-09-03 16:33:36,490 - root - INFO - ============ Begin upload ============
2017-09-03 16:33:36,490 - root - INFO - appid:project-of-my-own
2017-09-03 16:33:36,526 - root - INFO - Send: /api/appversion/rollback, params={'version': '1', 'app_id': 'project-of-my-own'}
2017-09-03 16:33:36,526 - google.appengine.tools.appengine_rpc - DEBUG - _Authenticate skipped auth; needs_auth=False
2017-09-03 16:33:36,526 - google.appengine.tools.appengine_rpc - DEBUG - Sending request to https://appengine.google.com/api/appversion/rollback?app_id=project-of-my-own&force_rollback=0&version=1 headers={'X-appcfg-api-version': '1', 'content-length': '0', 'Content-Type': 'application/octet-stream'} body=
2017-09-03 16:33:36,528 - root - ERROR - upload fail:error(111, 'Connection refused')
Traceback (most recent call last):
File "/home/me/Programee/XX-Net-3.3.6/code/default/gae_proxy/server/uploader.py", line 70, in upload
result = appcfg.AppCfgApp(['appcfg', 'rollback', dirname ]).Run()
File "/home/me/Programee/XX-Net-3.3.6/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 2951, in Run
self.action(self)
File "/home/me/Programee/XX-Net-3.3.6/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 5044, in __call__
return method()
File "/home/me/Programee/XX-Net-3.3.6/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 4397, in Rollback
self._Rollback()
File "/home/me/Programee/XX-Net-3.3.6/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 4442, in _Rollback
appversion.Rollback(force_rollback)
File "/home/me/Programee/XX-Net-3.3.6/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 2362, in Rollback
force_rollback='1' if force_rollback else '0')
File "/home/me/Programee/XX-Net-3.3.6/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 1696, in Send
result = self.rpcserver.Send(url, payload=payload, **kwargs)
File "/home/me/Programee/XX-Net-3.3.6/code/default/gae_proxy/server/lib/google/appengine/tools/appengine_rpc_httplib2.py", line 247, in Send
url, method=method, body=payload, headers=headers)
File "/home/me/Programee/XX-Net-3.3.6/code/default/gae_proxy/server/lib/httplib2/__init__.py", line 1593, in request
(response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
File "/home/me/Programee/XX-Net-3.3.6/code/default/gae_proxy/server/lib/httplib2/__init__.py", line 1341, in _request
(response, content) = self._conn_request(conn, request_uri, method, body, headers)
File "/home/me/Programee/XX-Net-3.3.6/code/default/gae_proxy/server/lib/httplib2/__init__.py", line 1277, in _conn_request
conn.connect()
File "/home/me/Programee/XX-Net-3.3.6/code/default/gae_proxy/server/lib/httplib2/__init__.py", line 1062, in connect
raise socket.error, msg
error: [Errno 111] Connection refused
2017-09-03 16:33:36,531 - root - INFO - Retry 1 time...
2017-09-03 16:33:36,565 - root - INFO - Send: /api/appversion/rollback, params={'version': '1', 'app_id': 'project-of-my-own'}
2017-09-03 16:33:36,566 - google.appengine.tools.appengine_rpc - DEBUG - _Authenticate skipped auth; needs_auth=False
2017-09-03 16:33:36,566 - google.appengine.tools.appengine_rpc - DEBUG - Sending request to https://appengine.google.com/api/appversion/rollback?app_id=project-of-my-own&force_rollback=0&version=1 headers={'X-appcfg-api-version': '1', 'content-length': '0', 'Content-Type': 'application/octet-stream'} body=
2017-09-03 16:33:36,567 - root - ERROR - upload fail:error(111, 'Connection refused')
Traceback (most recent call last):
File "/home/me/Programee/XX-Net-3.3.6/code/default/gae_proxy/server/uploader.py", line 70, in upload
result = appcfg.AppCfgApp(['appcfg', 'rollback', dirname ]).Run()
File "/home/me/Programee/XX-Net-3.3.6/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 2951, in Run
self.action(self)
File "/home/me/Programee/XX-Net-3.3.6/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 5044, in __call__
return method()
File "/home/me/Programee/XX-Net-3.3.6/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 4397, in Rollback
self._Rollback()
File "/home/me/Programee/XX-Net-3.3.6/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 4442, in _Rollback
appversion.Rollback(force_rollback)
File "/home/me/Programee/XX-Net-3.3.6/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 2362, in Rollback
force_rollback='1' if force_rollback else '0')
File "/home/me/Programee/XX-Net-3.3.6/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 1696, in Send
result = self.rpcserver.Send(url, payload=payload, **kwargs)
File "/home/me/Programee/XX-Net-3.3.6/code/default/gae_proxy/server/lib/google/appengine/tools/appengine_rpc_httplib2.py", line 247, in Send
url, method=method, body=payload, headers=headers)
File "/home/me/Programee/XX-Net-3.3.6/code/default/gae_proxy/server/lib/httplib2/__init__.py", line 1593, in request
(response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
File "/home/me/Programee/XX-Net-3.3.6/code/default/gae_proxy/server/lib/httplib2/__init__.py", line 1341, in _request
(response, content) = self._conn_request(conn, request_uri, method, body, headers)
File "/home/me/Programee/XX-Net-3.3.6/code/default/gae_proxy/server/lib/httplib2/__init__.py", line 1277, in _conn_request
conn.connect()
File "/home/me/Programee/XX-Net-3.3.6/code/default/gae_proxy/server/lib/httplib2/__init__.py", line 1062, in connect
raise socket.error, msg
error: [Errno 111] Connection refused
2017-09-03 16:33:36,569 - root - INFO - Retry 2 time...
2017-09-03 16:33:37,610 - root - INFO - Send: /api/appversion/rollback, params={'version': '1', 'app_id': 'project-of-my-own'}
2017-09-03 16:33:37,611 - google.appengine.tools.appengine_rpc - DEBUG - _Authenticate skipped auth; needs_auth=False
2017-09-03 16:33:37,611 - google.appengine.tools.appengine_rpc - DEBUG - Sending request to https://appengine.google.com/api/appversion/rollback?app_id=project-of-my-own&force_rollback=0&version=1 headers={'X-appcfg-api-version': '1', 'content-length': '0', 'Content-Type': 'application/octet-stream'} body=
2017-09-03 16:33:37,613 - root - ERROR - upload fail:error(111, 'Connection refused')
Traceback (most recent call last):
File "/home/me/Programee/XX-Net-3.3.6/code/default/gae_proxy/server/uploader.py", line 70, in upload
result = appcfg.AppCfgApp(['appcfg', 'rollback', dirname ]).Run()
File "/home/me/Programee/XX-Net-3.3.6/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 2951, in Run
self.action(self)
File "/home/me/Programee/XX-Net-3.3.6/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 5044, in __call__
return method()
File "/home/me/Programee/XX-Net-3.3.6/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 4397, in Rollback
self._Rollback()
File "/home/me/Programee/XX-Net-3.3.6/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 4442, in _Rollback
appversion.Rollback(force_rollback)
File "/home/me/Programee/XX-Net-3.3.6/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 2362, in Rollback
force_rollback='1' if force_rollback else '0')
File "/home/me/Programee/XX-Net-3.3.6/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 1696, in Send
result = self.rpcserver.Send(url, payload=payload, **kwargs)
File "/home/me/Programee/XX-Net-3.3.6/code/default/gae_proxy/server/lib/google/appengine/tools/appengine_rpc_httplib2.py", line 247, in Send
url, method=method, body=payload, headers=headers)
File "/home/me/Programee/XX-Net-3.3.6/code/default/gae_proxy/server/lib/httplib2/__init__.py", line 1593, in request
(response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
File "/home/me/Programee/XX-Net-3.3.6/code/default/gae_proxy/server/lib/httplib2/__init__.py", line 1341, in _request
(response, content) = self._conn_request(conn, request_uri, method, body, headers)
File "/home/me/Programee/XX-Net-3.3.6/code/default/gae_proxy/server/lib/httplib2/__init__.py", line 1277, in _conn_request
conn.connect()
File "/home/me/Programee/XX-Net-3.3.6/code/default/gae_proxy/server/lib/httplib2/__init__.py", line 1062, in connect
raise socket.error, msg
error: [Errno 111] Connection refused
2017-09-03 16:33:37,615 - root - INFO - Retry 3 time...
2017-09-03 16:33:39,618 - root - INFO - =======================
2017-09-03 16:33:39,618 - root - INFO - Deploy failed appid list:
2017-09-03 16:33:39,618 - root - INFO - - project-of-my-own
2017-09-03 16:33:39,618 - root - INFO - == END ==

点击上面的 ↑Preview↑ 来查看格式化后的说明。

---
## 提问之前
1. 首先请确认你使用的是[最新版本](https://github.com/XX-net/XX-Net/blob/master/code/default/download.md)，你的问题可能已经在新版本里解决了。
2. 请阅读[故障速查手册](https://github.com/XX-net/XX-Net/wiki/故障速查手册)，大部分问题都能在这里找到答案。
3. 请在 [issue](https://github.com/XX-net/XX-Net/issues) 区搜索有无类似的问题。

---
## 问题内容
1. 请尽可能详细的描述你的问题，如问题能重现请附带重现方法。
2. 当你的问题得到解决后，记得关闭问题。
3. 可以参考[示例 issue](https://github.com/XX-net/XX-Net/issues/3193)。

### 附加内容
1. 提交 issue 时请贴出诊断信息、GAEProxy 日志，以便开发者和其他用户更好地帮助你。
2. 如果是部署相关的问题，请一并附带部署日志。
3. 如果你有任何与这个问题有关的信息，也请一并发出来。
4. 如果你没有提供诊断信息，我们很可能会忽略这个问题。

#### 获取诊断信息
点击[状态页](http://127.0.0.1:8085)下方的【诊断信息】按钮，如没有这个按钮，请将显示详细信息从【OFF】改为【ON】。

#### 获取日志
打开 [GAEProxy 日志页](http://127.0.0.1:8085/?module=gae_proxy&menu=logging) 复制网页右边部分的内容。

---
请在阅读完后点击上边的 Write，删除说明内容，然后描述你遇到的问题。

**Comment by MaoJianwei** [comment]
最新版的可以正常部署，但是部署上去的服务器端有问题，我刚刚提交了BUG修复，请跟踪：
https://github.com/XX-net/XX-Net/pull/6388

**Comment by CHN008** [comment]
换另一种代理工具去部署就好了

**Comment by xxnet** [comment]
​部署问题，在3.4.2 中已修复

**Comment by WLZLCX** [comment]
哦，修复了呀

正好已下载3.4.2版
