### ISSUE TITLE
部署后访问_gh返回500

### ISSUE THREAD

**Issue by zxyqwe** [XX-net/XX-Net#6370]
使用的master分支最新版，在gae部署成功，但是在验证配置的时候失败，访问 my.appspot.com/_gh/ 返回500 Internal Server Error

从gae的日志看，似乎是python版本有点问题
```
 Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 299, in _LoadHandler
    handler, path, err = LoadObject(self._handler)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 85, in LoadObject
    obj = __import__(path[0])
  File "/base/data/home/apps/s~my/1.403881313176754637/gae.py", line 124
    data = 'HTTP/1.1 %d %s\r\n%s\r\n\r\n%s' %
                                             ^
SyntaxError: invalid syntax
```

**Comment by onplus** [comment]
最新的gae.py这个代码出错了https://github.com/XX-net/XX-Net/commit/faede9040decd0c65548018c23a4172c0e467f0f?diff=unified#diff-cbf9fda2cda82aa23b92d5909e37dd90R124 
把本地代码改成正确的再重新部署https://github.com/XX-net/XX-Net/blob/187fc01e524eeca45451e52bc6f4f890f5678290/code/default/gae_proxy/server/gae/gae.py

**Comment by zxyqwe** [comment]
确实是这个问题，可以自行修改解决。无论是加入反斜杠\，或者是将status换到上一行，都可以。
