### ISSUE TITLE
双击start.bat启动失败

### ISSUE THREAD

**Issue by SixGod-xm** [XX-net/XX-Net#6379]
Sep 05 19:23:37.525 - [ERROR] import system python-OpenSSL fail:ImportError('DLL load failed: %1 \xb2\xbb\xca\xc7\xd3\xd0\xd0\xa7\xb5\xc4 Win32 \xd3\xa6\xd3\xc3\xb3\xcc\xd0\xf2\xa1\xa3',)
Sep 05 19:23:37.526 - [ERROR] Except stack:Traceback (most recent call last):
  File "D:\software\XX-Net-3.3.6\code\default\launcher\start.py", line 112, in <module>
    import OpenSSL
  File "D:\software\XX-Net-3.3.6\code\default\python27\1.0\lib\noarch\OpenSSL\__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "D:\software\XX-Net-3.3.6\code\default\python27\1.0\lib\noarch\OpenSSL\rand.py", line 12, in <module>
    from OpenSSL._util import (
  File "D:\software\XX-Net-3.3.6\code\default\python27\1.0\lib\noarch\OpenSSL\_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "C:\Users\SixGod\AppData\Roaming\Python\Python27\site-packages\cryptography\hazmat\bindings\openssl\binding.py", line 13, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: DLL load failed: %1 不是有效的 Win32 应用程序。

Try install python-openssl

win10系统

**Comment by SixGod-xm** [comment]
看提示应该是需要安装pyopenssl  但是我使用命令pip install pyopenssl 安装的时候，显示我有这个。
code：
C:\Users\SixGod>pip install pyopenssl
Requirement already satisfied: pyopenssl in c:\python27\lib\site-packages
Requirement already satisfied: six>=1.5.2 in c:\users\sixgod\appdata\roaming\python\python27\site-packages (from pyopenssl)
Requirement already satisfied: cryptography>=1.9 in c:\users\sixgod\appdata\roaming\python\python27\site-packages (from pyopenssl)
Requirement already satisfied: asn1crypto>=0.21.0 in c:\users\sixgod\appdata\roaming\python\python27\site-packages (from cryptography>=1.9->pyopenssl)
Requirement already satisfied: idna>=2.1 in c:\python27\lib\site-packages (from cryptography>=1.9->pyopenssl)
Requirement already satisfied: ipaddress in c:\users\sixgod\appdata\roaming\python\python27\site-packages (from cryptography>=1.9->pyopenssl)
Requirement already satisfied: cffi>=1.7 in c:\users\sixgod\appdata\roaming\python\python27\site-packages (from cryptography>=1.9->pyopenssl)
Requirement already satisfied: enum34 in c:\users\sixgod\appdata\roaming\python\python27\site-packages (from cryptography>=1.9->pyopenssl)
Requirement already satisfied: pycparser in c:\users\sixgod\appdata\roaming\python\python27\site-packages (from cffi>=1.7->cryptography>=1.9->pyopenssl)

**Comment by onplus** [comment]
https://github.com/XX-net/XX-Net/issues/6248#issuecomment-322193720
https://github.com/XX-net/XX-Net/wiki/How-to-get-start-error-log

系统的python是你自己安装的吗？

另外你打开cmd测试一下这两个命令，看一下python的版本
1. `D:\software\XX-Net-3.3.6\code\default\python27\1.0\python`
1. `python`

**Comment by SixGod-xm** [comment]
C:\Users\SixGod>D:\software\XX-Net-3.3.6\code\default\python27\1.0\python
Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()

C:\Users\SixGod>python
Python 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>

**Comment by onplus** [comment]
32位和64位不兼容。

**Comment by SixGod-xm** [comment]
您好，没有这个文件。D:\software\XX-Net-3.3.6\environment.txt
另外我重新下载了32位的python2.7.13版本安装在我电脑上面。但是点击start.bat的时候还是提示相同的错误。我看了一下我电脑的环境变量中，也没有PYYTHONHOME的环境变量。
非常感谢您。

**Comment by zuyoushen** [comment]
看这里[https://github.com/XX-net/XX-Net/pull/6357](url)

**Comment by onplus** [comment]
执行 `set >D:\software\XX-Net-3.3.6\environment.txt` 之后就有了。

python多版本容易出问题，干脆卸了，装anaconda。
这就应该不会干扰到XX-Net的运行了

**Comment by MaoJianwei** [comment]
这个脚本太不自动化了，新电脑不能够解压直接用XX-NET！装了python也不能

**Comment by onplus** [comment]
@MaoJianwei 不是新電腦不能直接用，是最新版本有bug。
https://github.com/XX-net/XX-Net/pull/6357
XX-Net在windows下是不依賴系統python的。
