### ISSUE TITLE
2.0.2版本启动出错（https://github.com/XX-net/XX-Net/commit/35fcc7995289d87b952ab4210d47bc4990ba1a0a）

### ISSUE THREAD

**Issue by linhua55** [XX-net/XX-Net#646]
系统：Archlinux
➜  XX-Net git:(master) ./start.sh
Jul 17 17:43:55 - [WARNING] import pynotify fail, please install python-notify if possiable.
Jul 17 17:43:55 - [DEBUG] start confirm_xxnet_exit
Jul 17 17:43:57 - [ERROR] start module gae_proxy fail:'module' object has no attribute 'Handler'
Traceback (most recent call last):
  File "/home/lh/openshift/XX-Net/launcher/module_init.py", line 39, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "/home/lh/openshift/XX-Net/gae_proxy/start.py", line 13, in <module>
    import local.proxy as client
  File "/home/lh/openshift/XX-Net/gae_proxy/local/proxy.py", line 77, in <module>
    from cert_util import CertUtil
  File "/home/lh/openshift/XX-Net/gae_proxy/local/cert_util.py", line 41, in <module>
    from pyasn1.codec.der.decoder import decode
  File "/usr/lib/python2.7/site-packages/pyasn1/codec/der/decoder.py", line 2, in <module>
    from pyasn1.codec.cer import decoder
  File "/usr/lib/python2.7/site-packages/pyasn1/codec/cer/decoder.py", line 3, in <module>
    from pyasn1.codec.ber import decoder
  File "/usr/lib/python2.7/site-packages/pyasn1/codec/ber/decoder.py", line 5, in <module>
    from pyasn1 import debug, error
  File "/usr/lib/python2.7/site-packages/pyasn1/debug.py", line 39, in <module>
    class NullHandler(logging.Handler):
AttributeError: 'module' object has no attribute 'Handler'

**Comment by linhua55** [comment]
#647

**Comment by linhua55** [comment]
好像是在一次系统更新之后，2.0.1版本才突然报错，启动不了的。以下是更新的包
[2015-07-17 16:54] [ALPM] upgraded btrfs-progs (4.1-1 -> 4.1.2-1)
[2015-07-17 16:54] [ALPM] upgraded krb5 (1.13.1-1 -> 1.13.2-1)
[2015-07-17 16:54] [ALPM] upgraded less (478-1 -> 479-1)
[2015-07-17 16:54] [ALPM] upgraded device-mapper (2.02.122-1 -> 2.02.123-1)
[2015-07-17 16:54] [ALPM] upgraded dhclient (4.3.2-1 -> 4.3.2-2)
[2015-07-17 16:54] [ALPM] upgraded xorg-server-common (1.17.2-2 -> 1.17.2-3)
[2015-07-17 16:54] [ALPM] upgraded xorg-server (1.17.2-2 -> 1.17.2-3)
[2015-07-17 16:54] [ALPM] upgraded libtiff (4.0.3-5 -> 4.0.4-1)
[2015-07-17 16:54] [ALPM] upgraded ffmpeg (1:2.7.1-1 -> 1:2.7.1-2)
[2015-07-17 16:54] [ALPM] upgraded file (5.23-2 -> 5.24-1)
[2015-07-17 16:54] [ALPM] upgraded gtk-update-icon-cache (3.16.5-1 -> 3.16.5-2)
[2015-07-17 16:54] [ALPM] upgraded llvm-libs (3.6.1-1 -> 3.6.2-1)
[2015-07-17 16:54] [ALPM] upgraded mesa (10.6.1-1 -> 10.6.2-1)
[2015-07-17 16:54] [ALPM] upgraded flashplugin (11.2.202.481-1 -> 11.2.202.491-1)
[2015-07-17 16:54] [ALPM] upgraded git (2.4.5-1 -> 2.4.6-1)
[2015-07-17 16:54] [ALPM] upgraded gtk3 (3.16.5-1 -> 3.16.5-2)
[2015-07-17 16:54] [ALPM] upgraded imagemagick (6.9.1.4-1 -> 6.9.1.8-1)
[2015-07-17 16:54] [ALPM] upgraded ipython (3.2.0-2 -> 3.2.1-1)
[2015-07-17 16:54] [ALPM] upgraded python-pyzmq (14.6.0-3 -> 14.7.0-1)
[2015-07-17 16:54] [ALPM] upgraded ipython-notebook (3.2.0-2 -> 3.2.1-1)
[2015-07-17 16:54] [ALPM] upgraded ipython2 (3.2.0-2 -> 3.2.1-1)
[2015-07-17 16:54] [ALPM] upgraded libwbclient (4.2.2-1 -> 4.2.3-1)
[2015-07-17 16:54] [ALPM] upgraded tevent (0.9.24-1 -> 0.9.25-1)
[2015-07-17 16:54] [ALPM] upgraded smbclient (4.2.2-1 -> 4.2.3-1)
[2015-07-17 16:54] [ALPM] upgraded kdebase-runtime (15.04.3-1 -> 15.04.3-3)
[2015-07-17 16:54] [ALPM] upgraded lib32-elfutils (0.161-2 -> 0.163-1)
[2015-07-17 16:54] [ALPM] upgraded lib32-krb5 (1.13.1-1 -> 1.13.2-2)
[2015-07-17 16:54] [ALPM] upgraded lib32-llvm-libs (3.6.1-1 -> 3.6.2-1)
[2015-07-17 16:54] [ALPM] upgraded lib32-xz (5.2.1-1 -> 5.2.1-2)
[2015-07-17 16:55] [ALPM] upgraded lib32-mesa (10.6.1-1 -> 10.6.2-1)
[2015-07-17 16:55] [ALPM] upgraded libmm-glib (1.4.8-2 -> 1.4.10-2)
[2015-07-17 16:55] [ALPM] upgraded libnm-glib (1.0.2-4 -> 1.0.4-1)
[2015-07-17 16:55] [ALPM] upgraded linux (4.0.7-2 -> 4.1.2-2)

**Comment by xxnet** [comment]
看样子是新版的 pyasn1 里调用logging库，而XX-Net的logging库是自己定义的，没有Handler这个类，导致加载失败

2015-07-17 19:47 GMT+08:00 linhua55 <notifications@github.com>:

**Comment by xxnet** [comment]
合理的解决方案，需要把XX-Net里的logging换个名字，比如mylog之类的，避免跟系统库重名

2015-07-17 19:51 GMT+08:00 Net XX <xxnet.dev@gmail.com>:

**Comment by linhua55** [comment]
对，试试看

**Comment by linhua55** [comment]
@xxnet 
自己还没改完，就看你更新了，你怎么改的？

**Comment by xxnet** [comment]
用pycharm 只能改名，很方便，改后再git diff 检查，再运行测试，大概40分钟搞定

2015-07-18 11:11 GMT+08:00 linhua55 <notifications@github.com>:
