### ISSUE TITLE
2.0.2启动出错

### ISSUE THREAD

**Issue by wsgdlhy** [XX-net/XX-Net#647]
archlinux

Exception happened during processing of request from ('127.0.0.1', 40061)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 599, in process_request_thread
    self.finish_request(request, client_address)
  File "/home/fu/XX-Net-master/launcher/web_control.py", line 48, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/home/fu/XX-Net-master/launcher/web_control.py", line 143, in do_GET
    controler = module_init.proc_handler[module]["imp"].local.web_control.ControlHandler(self.client_address, self.headers, self.command, path, self.rfile, self.wfile)
KeyError: 'imp'

**Comment by linhua55** [comment]
#646

**Comment by xxnet** [comment]
2.0.4 改过来了，请测试

2015-07-17 19:23 GMT+08:00 linhua55 <notifications@github.com>:

**Comment by httpe** [comment]
Archlinux下2.0.4正常运行

**Comment by xxnet** [comment]
ok

2015-07-18 11:21 GMT+08:00 httpe <notifications@github.com>:

**Comment by wsgdlhy** [comment]
可以使用了，但100th IP handshake(ms) 1341  一直很高

**Comment by wsgdlhy** [comment]
非常感谢！！！
