### ISSUE TITLE
Get Fail:session server login fail, code:1 msg:auth fail

### ISSUE THREAD

**Issue by litengzi** [XX-net/XX-Net#6525]
在Xtunnel登录页面，总是显示这个：Get Fail:session server login fail, code:1 msg:auth fail，然后连不上……谁知道问题在哪

**Comment by litengzi** [comment]
Sep 18 00:39:28.612 - [WARNING] session not running, try to connect
Sep 18 00:40:28.975 - [WARNING] login_session time:60362 fail, res:1 msg:auth fail
Sep 18 00:40:28.975 - [WARNING] x-tunnel login_session fail, session not start
Sep 18 00:40:28.975 - [WARNING] create conn fail
Sep 18 00:40:28.978 - [DEBUG] session not running, try login..
Sep 18 00:42:06.057 - [INFO] api:/login success t:97078
Sep 18 00:42:06.057 - [INFO] update xt_server v3.xx-net.online:443
Sep 18 00:42:06.057 - [INFO] request_balance host:v3.xx-net.online port:443 balance:0.000000 quota:312935101194.000000
Sep 18 00:42:06.057 - [WARNING] session not running, try to connect
Sep 18 00:43:06.440 - [WARNING] login_session time:60383 fail, res:1 msg:auth fail
Sep 18 00:43:06.440 - [WARNING] x-tunnel login_session fail, session not start
Sep 18 00:43:06.440 - [WARNING] create conn fail
Sep 18 00:43:06.451 - [DEBUG] session not running, try login..
Sep 18 00:43:06.761 - [INFO] api:/login success t:309
Sep 18 00:43:06.761 - [INFO] update xt_server v3.xx-net.online:443
Sep 18 00:43:06.761 - [INFO] request_balance host:v3.xx-net.online port:443 balance:0.000000 quota:313135101194.000000
Sep 18 00:43:06.761 - [WARNING] session not running, try to connect
Sep 18 00:43:27.183 - [ERROR] socks handler read error error('recv fail',)
Sep 18 00:43:27.183 - [ERROR] Except stack:Traceback (most recent call last): File "C:\Users\\Desktop\XX-Net-3.5.3\code\default\x_tunnel\local\proxy_handler.py", line 26, in handle socks_version = self.read_bytes(1) File "C:\Users\\Desktop\XX-Net-3.5.3\code\default\x_tunnel\local\proxy_handler.py", line 74, in read_bytes raise socket.error("recv fail") error: recv fail

**Comment by xxnet** [comment]
​是登陆服务器出问题了，已经恢复。

**Comment by litengzi** [comment]
@xxnet 是的，我想问下为啥我的流量每天都在涨，一天涨两三G，我之前是买了300G

**Comment by xxnet** [comment]
​现在是测试阶段，每次登陆都会送一点流量，有效期只有一天。

很多地方GAE 被封了，X-tunnel 新版本用户增加很多，服务器压力大很多，出现一些问题。


服务端和客户端都还在优化中，能用先用，性能优化和完善正在进行中。
