### ISSUE TITLE
关于汤博乐的问题

### ISSUE THREAD

**Issue by TXIuTnVsbA** [XX-net/XX-Net#6658]
明明已经满速下载了,但是还是很卡,查看了日志之后发现gae错误,什么鬼= =难怪汤博乐的视频看不了
XX-Net Status:

sys-platform: AMD64, Windows-7-6.1.7601-SP1
os-system: Windows
os-version: 6.1.7601
os-release: 7
os-detail: Version:6-1; Build:7601; Platform:2; CSD:Service Pack 1; ServicePack:1-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.79 Safari/537.36
xxnet-version: 3.6.1

python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:3020 good:1253
network-status: OK
connected-link: new:8 used:0
worker: h1:29 h2:6
scan-ip-thread-num: 0
ip-quality: 143
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

异常日志:
Sep 24 06:19:58.944 - [ERROR] gae_handler.handler KeyError('https://v.tumblr.com/tumblr_m7vkranEc51rv218b_r1.mov:1506205185.685000',) https://v.tumblr.com/tumblr_m7vkranEc51rv218b_r1.mov , retry...
Sep 24 06:19:58.945 - [ERROR] Except stack:Traceback (most recent call last): File "D:\XX-Net-master\code\3.6.1\gae_proxy\local\gae_handler.py", line 335, in request_gae_proxy response = request_gae_server(request_headers, request_body, url) File "D:\XX-Net-master\code\3.6.1\gae_proxy\local\gae_handler.py", line 194, in request_gae_server response = http_dispatch.request(headers, body, url) File "D:\XX-Net-master\code\3.6.1\gae_proxy\local\http_dispatcher.py", line 194, in request del self.working_tasks[task.unique_id] KeyError: 'https://v.tumblr.com/tumblr_m7vkranEc51rv218b_r1.mov:1506205185.685000'
Sep 24 06:19:58.965 - [ERROR] gae_handler.handler KeyError('https://vtt.tumblr.com/tumblr_md4mrhtRcB1r9lt0u.mp4:1506205195.787000',) https://vtt.tumblr.com/tumblr_md4mrhtRcB1r9lt0u.mp4 , retry...
Sep 24 06:19:58.966 - [ERROR] Except stack:Traceback (most recent call last): File "D:\XX-Net-master\code\3.6.1\gae_proxy\local\gae_handler.py", line 335, in request_gae_proxy response = request_gae_server(request_headers, request_body, url) File "D:\XX-Net-master\code\3.6.1\gae_proxy\local\gae_handler.py", line 194, in request_gae_server response = http_dispatch.request(headers, body, url) File "D:\XX-Net-master\code\3.6.1\gae_proxy\local\http_dispatcher.py", line 194, in request del self.working_tasks[task.unique_id] KeyError: 'https://vtt.tumblr.com/tumblr_md4mrhtRcB1r9lt0u.mp4:1506205195.787000'
Sep 24 06:19:58.995 - [ERROR] gae_handler.handler KeyError('https://vtt.tumblr.com/tumblr_md4mrhtRcB1r9lt0u.mp4:1506205195.785000',) https://vtt.tumblr.com/tumblr_md4mrhtRcB1r9lt0u.mp4 , retry...
Sep 24 06:19:58.995 - [ERROR] Except stack:Traceback (most recent call last): File "D:\XX-Net-master\code\3.6.1\gae_proxy\local\gae_handler.py", line 335, in request_gae_proxy response = request_gae_server(request_headers, request_body, url) File "D:\XX-Net-master\code\3.6.1\gae_proxy\local\gae_handler.py", line 194, in request_gae_server response = http_dispatch.request(headers, body, url) File "D:\XX-Net-master\code\3.6.1\gae_proxy\local\http_dispatcher.py", line 194, in request del self.working_tasks[task.unique_id] KeyError: 'https://vtt.tumblr.com/tumblr_md4mrhtRcB1r9lt0u.mp4:1506205195.785000'

**Comment by TXIuTnVsbA** [comment]
以前好像不怎么会,这几天升级了之后才会这样的

**Comment by if2012** [comment]
点击那些按钮经常出现“登录出现了错误，请稍后再试。”的提示。也注册不了，到最后一步的时候无限触发人工检测。

**Comment by OuyangIPC** [comment]
卧槽，刚查了一下，tumblr原来是，哎，不说了，厉害厉害，是在下见识短浅了

**Comment by Yuan720** [comment]
注意身体
