### ISSUE TITLE
请问一下在Deepin系统上怎么配置呢？

### ISSUE THREAD

**Issue by herkoy** [XX-net/XX-Net#6702]
遇到这种情况怎么解决呢？求助

Python 2.7.13
XX-Net version:default
Traceback (most recent call last):
  File "code/default/launcher/start.py", line 45, in <module>
    from instances import xlog
  File "/home/zyj/APP/XX-Net-master/code/default/launcher/instances.py", line 12, in <module>
    xlog = Logger(file_name=log_file)
  File "/home/zyj/APP/XX-Net-master/code/default/python27/1.0/lib/noarch/xlog.py", line 35, in __init__
    self.set_file(file_name)
  File "/home/zyj/APP/XX-Net-master/code/default/python27/1.0/lib/noarch/xlog.py", line 90, in set_file
    self.log_fd = open(file_name, "w")
IOError: [Errno 13] Permission denied: '/home/zyj/APP/XX-Net-master/data/launcher/launcher.log'

**Comment by xxnet** [comment]
​检查目录权限

怀疑解压缩是root，而执行是zyj

**Comment by herkoy** [comment]
好的，我试试，谢谢！！
