### ISSUE TITLE
ubuntu16.04 系统挂起再进入时，xx-net无法访问

### ISSUE THREAD

**Issue by tomorrow-dy** [XX-net/XX-Net#6722]
ubuntu16.04 系统挂起再进入时，xx-net无法访问，尝试重新打开，没有任何反应，重启电脑后正常，求助大神如何解决

**Comment by mnplex** [comment]
遇到同样的问题，Archlinux。更奇怪的是我两台机器，同样的系统，同样的python版本，SSD的重新唤醒连webui都不能访问了，机械硬盘却的正常。log也没有任何异常。

**Comment by netAir** [comment]
我也是.....Ubuntu17.04

**Comment by netAir** [comment]
如需日志内容,请问所需日志文件路径是什么,我把内容发上来

**Comment by mnplex** [comment]
日志就是在终端里./start启动的那一堆, 只要不出现红字黄字就是正常。
挂起又唤醒以后也没有异常，除了no enough ip的warning。
还是把诊断信息发上来吧。

这是我的
```
XX-Net Status:

sys-platform: x86_64, Linux-4.13.3-1-ARCH-x86_64-with-glibc2.2.5
os-system: Linux
os-version: #1 SMP PREEMPT Thu Sep 21 20:33:16 CEST 2017
os-release: 4.13.3-1-ARCH
os-detail: Dist:; Version:; ID:
architecture: 64bit,
browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
xxnet-version: 3.6.3

python-version: 2.7.14
openssl-version: 17.3.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:2984 good:0
network-status: OK
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 50
ip-quality: 9999
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false
```
请忽视这些天0可用IP的细节(￣▽￣;)

你们的分区情况可以发上来吗？
我的df -h是
```
Filesystem     Type      Size  Used Avail Use% Mounted on
dev            devtmpfs  1.9G     0  1.9G   0% /dev
run            tmpfs     1.9G  852K  1.9G   1% /run
/dev/sda3      ext4      117G   31G   81G  28% /
tmpfs          tmpfs     1.9G   68M  1.8G   4% /dev/shm
tmpfs          tmpfs     1.9G     0  1.9G   0% /sys/fs/cgroup
tmpfs          tmpfs     1.9G  444K  1.9G   1% /tmp
/dev/sda2      ext2       97M   48M   45M  53% /boot
tmpfs          tmpfs     382M   20K  382M   1% /run/user/1000
```

**Comment by netAir** [comment]
每次挂起唤醒后,webUI无法访问,也无法通过8087端口进行代理访问.
再通过终端运行xxnet,上面的问题依然存在.
下面为诊断信息与日志

开机后正常运行的日志:
```
XX-Net Status:

sys-platform: x86_64, Linux-4.10.0-35-generic-x86_64-with-Ubuntu-17.04-zesty
os-system: Linux
os-version: #39-Ubuntu SMP Wed Sep 13 07:46:59 UTC 2017
os-release: 4.10.0-35-generic
os-detail: Dist:Ubuntu; Version:17.04; ID:zesty
architecture: 64bit,
browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/61.0.3163.79 Chrome/61.0.3163.79 Safari/537.36
xxnet-version: 3.6.7

python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:3000 good:3
network-status: OK
connected-link: new:0 used:0
worker: h1:2 h2:0
scan-ip-thread-num: 50
ip-quality: 1636
is-idle: 0
block-stat: Connect Blocked, 2 seconds to wait.
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false
```
挂起唤醒后,运行xxnet终端输出内容,python的报错都出来了┑(￣Д ￣)┍
```
10月 05 12:46:57.3 - [INFO] use build-in openssl lib
10月 05 12:46:57.3 - [INFO] start XX-Net 3.6.7
10月 05 12:46:57.3 - [DEBUG] start confirm_xxnet_exit
10月 05 12:47:27.4 - [DEBUG] good, xxnet:8087 cleared!
10月 05 12:47:57.4 - [DEBUG] good, xxnet:8085 clear!
10月 05 12:47:57.4 - [DEBUG] finished confirm_xxnet_exit
10月 05 12:47:57.4 - [INFO] SSL use version:TLSv1_2
10月 05 12:47:57.4 - [INFO] OpenSSL support alpn
10月 05 12:47:57.4 - [INFO] load ip range file:/opt/XX-Net-master/code/3.6.7/gae_proxy/local/ip_range.txt
10月 05 12:47:57.4 - [INFO] Use google ip range.
10月 05 12:47:57.4 - [INFO] load google ip_list num:3000, gws num:3000
10月 05 12:47:57.4 - [INFO] OpenSSL support alpn
10月 05 12:47:57.4 - [DEBUG] ## GAEProxy set keep_running: True
10月 05 12:47:57.4 - [INFO] ------------------------------------------------------
10月 05 12:47:57.4 - [INFO] Python Version     : 2.7.13
10月 05 12:47:57.4 - [INFO] OS                 : Dist:Ubuntu; Version:17.04; ID:zesty
10月 05 12:47:57.4 - [INFO] Listen Address     : 127.0.0.1:8087
10月 05 12:47:57.4 - [INFO] GAE APPID          : jcmdaili-1|jcmdaili-2|jcmdaili-3|jcmdaili-4|jcmdaili-5|jcmdaili-6|jcmdaili-7|jcmdaili-8|jcmdaili-9|jcmdaili-10
10月 05 12:47:57.4 - [INFO] Pac Server         : http://127.0.0.1:8086/proxy.pac
10月 05 12:47:57.4 - [INFO] ------------------------------------------------------
/opt/XX-Net-master/code/3.6.7/python27/1.0/lib/noarch/OpenSSL/crypto.py:1110: UserWarning: implicit cast from 'char *' to a different pointer type: will be forbidden in the future (check that the types are as you expect; use an explicit ffi.cast() if they are correct)
  self._x509, digest, result_buffer, result_length)
10月 05 12:47:57.5 - [INFO] system cert exist
GoAgent XX-Net - GoAgent                                     C,,  
10月 05 12:47:57.5 - [ERROR] bind to 127.0.0.1:8087 fail:error(98, '\xe5\x9c\xb0\xe5\x9d\x80\xe5\xb7\xb2\xe5\x9c\xa8\xe4\xbd\xbf\xe7\x94\xa8')
10月 05 12:47:57.6 - [DEBUG] network is ok, cost:268 ms
Exception in thread Thread-59:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/XX-Net-master/code/3.6.7/gae_proxy/start.py", line 18, in main
    client.main()
  File "/opt/XX-Net-master/code/3.6.7/gae_proxy/local/proxy.py", line 155, in main
    proxy_daemon = simple_http_server.HTTPServer((config.LISTEN_IP, config.LISTEN_PORT), proxy_handler.GAEProxyHandler)
  File "/opt/XX-Net-master/code/3.6.7/python27/1.0/lib/noarch/simple_http_server.py", line 369, in __init__
    self.init_socket()
  File "/opt/XX-Net-master/code/3.6.7/python27/1.0/lib/noarch/simple_http_server.py", line 379, in init_socket
    self.add_listen(addr)
  File "/opt/XX-Net-master/code/3.6.7/python27/1.0/lib/noarch/simple_http_server.py", line 393, in add_listen
    raise Exception(err_string)
Exception: bind to 127.0.0.1:8087 fail:error(98, '\xe5\x9c\xb0\xe5\x9d\x80\xe5\xb7\xb2\xe5\x9c\xa8\xe4\xbd\xbf\xe7\x94\xa8')
```
我的分区情况:
```
文件系统        容量  已用  可用 已用% 挂载点
udev            5.8G     0  5.8G    0% /dev
tmpfs           1.2G   11M  1.2G    1% /run
/dev/sda8       424G  128G  275G   32% /
tmpfs           5.9G   12M  5.9G    1% /dev/shm
tmpfs           5.0M  4.0K  5.0M    1% /run/lock
tmpfs           5.9G     0  5.9G    0% /sys/fs/cgroup
/dev/sda2        95M   31M   65M   33% /boot/efi
tmpfs           1.2G  148K  1.2G    1% /run/user/1000

```

**Comment by mnplex** [comment]
报错是端口被占用

我没有仔细看过代码，可能是唤醒之后simple_http_server不工作了，但是8085,8087端口还占着

我写了个脚本先判断webUI是否还能访问，如果不能了就把进程杀了重新开一个
算是个临时解决办法吧
