### ISSUE TITLE
最新版本无法部署认证自己的appid

### ISSUE THREAD

**Issue by rainplus** [XX-net/XX-Net#6727]
---
自己手殘 在macOs rm -rf ~ 了自己的目录后，重新下载XX-net的3.6.3版本，发现部署不了自己的appId?
---

部署日志：
017-09-29 15:27:33,454 - root - INFO - enable debug logging
2017-09-29 15:27:33,454 - root - INFO - set proxy to http://127.0.0.1:8087
2017-09-29 15:27:33,455 - root - INFO - ============ Begin upload ============
2017-09-29 15:27:33,455 - root - INFO - appid:my-appid
2017-09-29 15:27:33,470 - root - INFO - Send: /api/appversion/rollback, params={'version': '1', 'app_id': 'my-appid'}
2017-09-29 15:27:33,470 - google.appengine.tools.appengine_rpc - DEBUG - _Authenticate skipped auth; needs_auth=False
2017-09-29 15:27:33,471 - google.appengine.tools.appengine_rpc - DEBUG - Sending request to https://appengine.google.com/api/appversion/rollback?app_id=my-appid&force_rollback=0&version=1 headers={'X-appcfg-api-version': '1', 'content-length': '0', 'Content-Type': 'application/octet-stream'} body=
2017-09-29 15:27:43,374 - google.appengine.tools.appengine_rpc - DEBUG - Got http error 401.
2017-09-29 15:27:43,375 - google.appengine.tools.appengine_rpc - DEBUG - Attempting to auth. This is try 1 of 3.
2017-09-29 15:27:43,375 - google.appengine.tools.appengine_rpc - DEBUG - _Authenticate requesting auth
2017-09-29 15:27:43,377 - root - ERROR - upload fail:EOFError('EOF when reading a line',)
Traceback (most recent call last):
File "/Users/rainplus/XX-Net-3.6.3/code/default/gae_proxy/server/uploader.py", line 70, in upload
result = appcfg.AppCfgApp(['appcfg', 'rollback', dirname ]).Run()
File "/Users/rainplus/XX-Net-3.6.3/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 2951, in Run
self.action(self)
File "/Users/rainplus/XX-Net-3.6.3/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 5044, in __call__
return method()
File "/Users/rainplus/XX-Net-3.6.3/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 4397, in Rollback
self._Rollback()
File "/Users/rainplus/XX-Net-3.6.3/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 4442, in _Rollback
appversion.Rollback(force_rollback)
File "/Users/rainplus/XX-Net-3.6.3/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 2362, in Rollback
force_rollback='1' if force_rollback else '0')
File "/Users/rainplus/XX-Net-3.6.3/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 1696, in Send
result = self.rpcserver.Send(url, payload=payload, **kwargs)
File "/Users/rainplus/XX-Net-3.6.3/code/default/gae_proxy/server/lib/google/appengine/tools/appengine_rpc_httplib2.py", line 241, in Send
self._Authenticate(self.http, auth_errors[0] > 0)
File "/Users/rainplus/XX-Net-3.6.3/code/default/gae_proxy/server/lib/google/appengine/tools/appengine_rpc_httplib2.py", line 459, in _Authenticate
self.credentials = tools.run_flow(flow, self.storage, self.flags)
File "/Users/rainplus/XX-Net-3.6.3/code/default/gae_proxy/server/lib/oauth2client/util.py", line 137, in positional_wrapper
return wrapped(*args, **kwargs)
File "/Users/rainplus/XX-Net-3.6.3/code/default/gae_proxy/server/lib/oauth2client/tools.py", line 222, in run_flow
code = input('Enter verification code: ').strip()
EOFError: EOF when reading a line
2017-09-29 15:27:43,379 - root - INFO - Retry 1 time...
2017-09-29 15:27:43,393 - root - INFO - Send: /api/appversion/rollback, params={'version': '1', 'app_id': 'my-appid'}
2017-09-29 15:27:43,393 - google.appengine.tools.appengine_rpc - DEBUG - _Authenticate skipped auth; needs_auth=False
2017-09-29 15:27:43,394 - google.appengine.tools.appengine_rpc - DEBUG - Sending request to https://appengine.google.com/api/appversion/rollback?app_id=my-appid&force_rollback=0&version=1 headers={'X-appcfg-api-version': '1', 'content-length': '0', 'Content-Type': 'application/octet-stream'} body=
2017-09-29 15:27:49,178 - google.appengine.tools.appengine_rpc - DEBUG - Got http error 401.
2017-09-29 15:27:49,178 - google.appengine.tools.appengine_rpc - DEBUG - Attempting to auth. This is try 1 of 3.
2017-09-29 15:27:49,178 - google.appengine.tools.appengine_rpc - DEBUG - _Authenticate requesting auth
2017-09-29 15:27:49,180 - root - ERROR - upload fail:EOFError('EOF when reading a line',)
Traceback (most recent call last):
File "/Users/rainplus/XX-Net-3.6.3/code/default/gae_proxy/server/uploader.py", line 70, in upload
result = appcfg.AppCfgApp(['appcfg', 'rollback', dirname ]).Run()
File "/Users/rainplus/XX-Net-3.6.3/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 2951, in Run
self.action(self)
File "/Users/rainplus/XX-Net-3.6.3/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 5044, in __call__
return method()
File "/Users/rainplus/XX-Net-3.6.3/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 4397, in Rollback
self._Rollback()
File "/Users/rainplus/XX-Net-3.6.3/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 4442, in _Rollback
appversion.Rollback(force_rollback)
File "/Users/rainplus/XX-Net-3.6.3/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 2362, in Rollback
force_rollback='1' if force_rollback else '0')
File "/Users/rainplus/XX-Net-3.6.3/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 1696, in Send
result = self.rpcserver.Send(url, payload=payload, **kwargs)
File "/Users/rainplus/XX-Net-3.6.3/code/default/gae_proxy/server/lib/google/appengine/tools/appengine_rpc_httplib2.py", line 241, in Send
self._Authenticate(self.http, auth_errors[0] > 0)
File "/Users/rainplus/XX-Net-3.6.3/code/default/gae_proxy/server/lib/google/appengine/tools/appengine_rpc_httplib2.py", line 459, in _Authenticate
self.credentials = tools.run_flow(flow, self.storage, self.flags)
File "/Users/rainplus/XX-Net-3.6.3/code/default/gae_proxy/server/lib/oauth2client/util.py", line 137, in positional_wrapper
return wrapped(*args, **kwargs)
File "/Users/rainplus/XX-Net-3.6.3/code/default/gae_proxy/server/lib/oauth2client/tools.py", line 222, in run_flow
code = input('Enter verification code: ').strip()
EOFError: EOF when reading a line
2017-09-29 15:27:49,181 - root - INFO - Retry 2 time...
2017-09-29 15:27:50,199 - root - INFO - Send: /api/appversion/rollback, params={'version': '1', 'app_id': 'my-appid'}
2017-09-29 15:27:50,200 - google.appengine.tools.appengine_rpc - DEBUG - _Authenticate skipped auth; needs_auth=False
2017-09-29 15:27:50,200 - google.appengine.tools.appengine_rpc - DEBUG - Sending request to https://appengine.google.com/api/appversion/rollback?app_id=my-appid&force_rollback=0&version=1 headers={'X-appcfg-api-version': '1', 'content-length': '0', 'Content-Type': 'application/octet-stream'} body=
2017-09-29 15:27:54,676 - google.appengine.tools.appengine_rpc - DEBUG - Got http error 401.
2017-09-29 15:27:54,676 - google.appengine.tools.appengine_rpc - DEBUG - Attempting to auth. This is try 1 of 3.
2017-09-29 15:27:54,676 - google.appengine.tools.appengine_rpc - DEBUG - _Authenticate requesting auth
2017-09-29 15:27:54,678 - root - ERROR - upload fail:EOFError('EOF when reading a line',)
Traceback (most recent call last):
File "/Users/rainplus/XX-Net-3.6.3/code/default/gae_proxy/server/uploader.py", line 70, in upload
result = appcfg.AppCfgApp(['appcfg', 'rollback', dirname ]).Run()
File "/Users/rainplus/XX-Net-3.6.3/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 2951, in Run
self.action(self)
File "/Users/rainplus/XX-Net-3.6.3/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 5044, in __call__
return method()
File "/Users/rainplus/XX-Net-3.6.3/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 4397, in Rollback
self._Rollback()
File "/Users/rainplus/XX-Net-3.6.3/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 4442, in _Rollback
appversion.Rollback(force_rollback)
File "/Users/rainplus/XX-Net-3.6.3/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 2362, in Rollback
force_rollback='1' if force_rollback else '0')
File "/Users/rainplus/XX-Net-3.6.3/code/default/gae_proxy/server/lib/google/appengine/tools/appcfg.py", line 1696, in Send
result = self.rpcserver.Send(url, payload=payload, **kwargs)
File "/Users/rainplus/XX-Net-3.6.3/code/default/gae_proxy/server/lib/google/appengine/tools/appengine_rpc_httplib2.py", line 241, in Send
self._Authenticate(self.http, auth_errors[0] > 0)
File "/Users/rainplus/XX-Net-3.6.3/code/default/gae_proxy/server/lib/google/appengine/tools/appengine_rpc_httplib2.py", line 459, in _Authenticate
self.credentials = tools.run_flow(flow, self.storage, self.flags)
File "/Users/rainplus/XX-Net-3.6.3/code/default/gae_proxy/server/lib/oauth2client/util.py", line 137, in positional_wrapper
return wrapped(*args, **kwargs)
File "/Users/rainplus/XX-Net-3.6.3/code/default/gae_proxy/server/lib/oauth2client/tools.py", line 222, in run_flow
code = input('Enter verification code: ').strip()
EOFError: EOF when reading a line
2017-09-29 15:27:54,678 - root - INFO - Retry 3 time...
2017-09-29 15:27:56,681 - root - INFO - =======================
2017-09-29 15:27:56,681 - root - INFO - Deploy failed appid list:
2017-09-29 15:27:56,681 - root - INFO - - my-appid
2017-09-29 15:27:56,681 - root - INFO - == END ==1

**Comment by rainplus** [comment]
我自己知道401是未授权，但是他不弹出窗口让我认证？

**Comment by onplus** [comment]
https://github.com/XX-net/XX-Net/wiki/how-to-create-my-appids#%E8%AF%B4%E6%98%8E

**Comment by rainplus** [comment]
应用是chrome版本的（主动更新到62了）问题吧，无法打开弹窗进行认证。我没有按照文档的其他方式进行设置，感觉还是要翻墙，步骤有上有点烦杂

**Comment by jzp820927** [comment]
其实也可以在 gae 的 web shell 上部署的。
