### ISSUE TITLE
ubuntu 14.04.5 LTS无法启动XX-net 3.6.3

### ISSUE THREAD

**Issue by jiangzhengwenjz** [XX-net/XX-Net#6742]
此前已有过几次无法启动，但重启后都变回正常状态。这次重启数次也无用。
尝试利用sudo ./start启动，只能得到如下信息：
Python 2.7.6
XX-Net version:3.6.3
XX-Net.desktop already exists
Traceback (most recent call last):
  File "code/3.6.3/launcher/start.py", line 75, in <module>
    from gtk_tray import sys_tray
  File "/usr/local/XX-Net-3.3.1/code/3.6.3/launcher/gtk_tray.py", line 12, in <module>
    import config
  File "/usr/local/XX-Net-3.3.1/code/3.6.3/launcher/config.py", line 102, in <module>
    init()
  File "/usr/local/XX-Net-3.3.1/code/3.6.3/launcher/config.py", line 98, in init
    if recheck_module_path():
  File "/usr/local/XX-Net-3.3.1/code/3.6.3/launcher/config.py", line 75, in recheck_module_path
    set(["modules", module, "auto_start"], 1)
  File "/usr/local/XX-Net-3.3.1/code/3.6.3/launcher/config.py", line 58, in set
    _set(config, path, val)
  File "/usr/local/XX-Net-3.3.1/code/3.6.3/launcher/config.py", line 51, in _set
    if k0 not in m:
TypeError: argument of type 'NoneType' is not iterable

**Comment by xxnet** [comment]
​检查 data/launcher/config.yaml
估计这个文件坏了。
先看看文件内容，试试删除后启动

**Comment by jiangzhengwenjz** [comment]
删除这个文件后完美解决了，之前是空的
非常感谢回答！

**Comment by roc1010kmt** [comment]
最好升級到ubuntu 1６.04。
