### ISSUE TITLE
请问一下x-tunnel在python代码里怎么设置代理

### ISSUE THREAD

**Issue by derrickcyt** [XX-net/XX-Net#6797]
我参考了chrome的SwitchyOmega的设置，写了下面的python代码：

`# -*- coding: utf-8 -*-
import requests

proxies = {
    'http': 'socks5://127.0.0.1:1080',
    'https': 'socks5://127.0.0.1:1080'
}

url = "https://www.youtube.com/"
r = requests.get(url, proxies=proxies)
print r.text`

显示错误：
`Traceback (most recent call last):
  File "/Users/Derrick/PycharmProjects/crawl_projects/douban_love/socks_test.py", line 17, in <module>
    r = requests.get(url, proxies=proxies)
  File "/Users/Derrick/anaconda2/lib/python2.7/site-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/Users/Derrick/anaconda2/lib/python2.7/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/Derrick/anaconda2/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/Derrick/anaconda2/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/Users/Derrick/anaconda2/lib/python2.7/site-packages/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: EOF occurred in violation of protocol (_ssl.c:590)`

请问是什么问题？

**Comment by xxnet** [comment]
​看看x-tunnel 日志，有没有什么异常;
先确认浏览器在这个代理下可以工作。

**Comment by derrickcyt** [comment]
@xxnet 

我的是MacBook。Chrome浏览器能正常使用，能访问网站。配置是在wiki下的x-tunnel配置导入。
然后使用代码运行的时候，x-tunnel如下：

`Oct 04 11:37:28.837 - [INFO] socks5 ('127.0.0.1', 52932) connect to 8.7.198.45:443 conn_id:52
Oct 04 11:37:28.837 - [DEBUG] start roundtrip transfer_no:6431 send_data_len:29 ack_len:0
Oct 04 11:37:28.847 - [DEBUG] start roundtrip transfer_no:6432 send_data_len:283 ack_len:0
Oct 04 11:37:34.509 - [DEBUG] roundtrip time:5671 cost:5015 transfer_no:6431 send_sn:470 send:29 recv_sn:0 rcv:11 status:200
Oct 04 11:37:34.509 - [DEBUG] start roundtrip transfer_no:6433 send_data_len:0 ack_len:0
Oct 04 11:37:34.510 - [DEBUG] roundtrip time:5663 cost:5015 transfer_no:6432 send_sn:471 send:283 recv_sn:0 rcv:11 status:200
Oct 04 11:37:34.510 - [DEBUG] start roundtrip transfer_no:6434 send_data_len:0 ack_len:0
Oct 04 11:37:39.982 - [DEBUG] roundtrip time:5471 cost:5064 transfer_no:6434 send_sn:0 send:0 recv_sn:0 rcv:11 status:200
Oct 04 11:37:39.982 - [DEBUG] start roundtrip transfer_no:6435 send_data_len:0 ack_len:0
Oct 04 11:37:40.363 - [DEBUG] roundtrip time:5853 cost:5060 transfer_no:6433 send_sn:0 send:0 recv_sn:0 rcv:11 status:200
Oct 04 11:37:40.363 - [DEBUG] start roundtrip transfer_no:6436 send_data_len:0 ack_len:0
Oct 04 11:37:45.720 - [DEBUG] roundtrip time:5356 cost:5007 transfer_no:6436 send_sn:0 send:0 recv_sn:0 rcv:11 status:200
Oct 04 11:37:45.720 - [DEBUG] roundtrip time:5737 cost:5007 transfer_no:6435 send_sn:0 send:0 recv_sn:0 rcv:11 status:200
Oct 04 11:37:45.720 - [DEBUG] start roundtrip transfer_no:6437 send_data_len:0 ack_len:0
Oct 04 11:37:45.720 - [DEBUG] start roundtrip transfer_no:6438 send_data_len:0 ack_len:0
Oct 04 11:37:51.287 - [DEBUG] roundtrip time:5566 cost:5007 transfer_no:6438 send_sn:0 send:0 recv_sn:0 rcv:11 status:200
Oct 04 11:37:51.287 - [DEBUG] start roundtrip transfer_no:6439 send_data_len:0 ack_len:0
Oct 04 11:37:51.342 - [DEBUG] roundtrip time:5622 cost:5066 transfer_no:6437 send_sn:0 send:0 recv_sn:0 rcv:11 status:200
Oct 04 11:37:51.342 - [DEBUG] start roundtrip transfer_no:6440 send_data_len:0 ack_len:0
Oct 04 11:37:56.580 - [DEBUG] roundtrip time:5293 cost:5038 transfer_no:6439 send_sn:0 send:0 recv_sn:0 rcv:11 status:200
Oct 04 11:37:56.580 - [DEBUG] start roundtrip transfer_no:6441 send_data_len:0 ack_len:0
Oct 04 11:37:56.819 - [DEBUG] roundtrip time:5476 cost:5226 transfer_no:6440 send_sn:0 send:0 recv_sn:0 rcv:11 status:200
Oct 04 11:37:56.820 - [DEBUG] start roundtrip transfer_no:6442 send_data_len:0 ack_len:0
Oct 04 11:37:59.389 - [DEBUG] roundtrip time:2808 cost:2576 transfer_no:6441 send_sn:0 send:0 recv_sn:365 rcv:37 status:200
Oct 04 11:37:59.389 - [DEBUG] start roundtrip transfer_no:6443 send_data_len:0 ack_len:8
Oct 04 11:37:59.389 - [INFO] Conn session:ffjoamam conn:52 Peer Close:connect fail
Oct 04 11:37:59.391 - [DEBUG] start roundtrip transfer_no:6444 send_data_len:20 ack_len:0
Oct 04 11:37:59.391 - [DEBUG] Conn session:ffjoamam conn:52 stop:peer close
Oct 04 11:37:59.937 - [DEBUG] remove conn_id:52`

**Comment by derrickcyt** [comment]
@xxnet 

@xxnet

我的是MacBook。Chrome浏览器能正常使用，能访问网站。配置是在wiki下的x-tunnel配置导入。
然后使用代码运行的时候，x-tunnel如下：

Oct 04 11:37:28.837 - [INFO] socks5 ('127.0.0.1', 52932) connect to 8.7.198.45:443 conn_id:52
Oct 04 11:37:28.837 - [DEBUG] start roundtrip transfer_no:6431 send_data_len:29 ack_len:0
Oct 04 11:37:28.847 - [DEBUG] start roundtrip transfer_no:6432 send_data_len:283 ack_len:0
Oct 04 11:37:34.509 - [DEBUG] roundtrip time:5671 cost:5015 transfer_no:6431 send_sn:470 send:29 recv_sn:0 rcv:11 status:200
Oct 04 11:37:34.509 - [DEBUG] start roundtrip transfer_no:6433 send_data_len:0 ack_len:0
Oct 04 11:37:34.510 - [DEBUG] roundtrip time:5663 cost:5015 transfer_no:6432 send_sn:471 send:283 recv_sn:0 rcv:11 status:200
Oct 04 11:37:34.510 - [DEBUG] start roundtrip transfer_no:6434 send_data_len:0 ack_len:0
Oct 04 11:37:39.982 - [DEBUG] roundtrip time:5471 cost:5064 transfer_no:6434 send_sn:0 send:0 recv_sn:0 rcv:11 status:200
Oct 04 11:37:39.982 - [DEBUG] start roundtrip transfer_no:6435 send_data_len:0 ack_len:0
Oct 04 11:37:40.363 - [DEBUG] roundtrip time:5853 cost:5060 transfer_no:6433 send_sn:0 send:0 recv_sn:0 rcv:11 status:200
Oct 04 11:37:40.363 - [DEBUG] start roundtrip transfer_no:6436 send_data_len:0 ack_len:0
Oct 04 11:37:45.720 - [DEBUG] roundtrip time:5356 cost:5007 transfer_no:6436 send_sn:0 send:0 recv_sn:0 rcv:11 status:200
Oct 04 11:37:45.720 - [DEBUG] roundtrip time:5737 cost:5007 transfer_no:6435 send_sn:0 send:0 recv_sn:0 rcv:11 status:200
Oct 04 11:37:45.720 - [DEBUG] start roundtrip transfer_no:6437 send_data_len:0 ack_len:0
Oct 04 11:37:45.720 - [DEBUG] start roundtrip transfer_no:6438 send_data_len:0 ack_len:0
Oct 04 11:37:51.287 - [DEBUG] roundtrip time:5566 cost:5007 transfer_no:6438 send_sn:0 send:0 recv_sn:0 rcv:11 status:200
Oct 04 11:37:51.287 - [DEBUG] start roundtrip transfer_no:6439 send_data_len:0 ack_len:0
Oct 04 11:37:51.342 - [DEBUG] roundtrip time:5622 cost:5066 transfer_no:6437 send_sn:0 send:0 recv_sn:0 rcv:11 status:200
Oct 04 11:37:51.342 - [DEBUG] start roundtrip transfer_no:6440 send_data_len:0 ack_len:0
Oct 04 11:37:56.580 - [DEBUG] roundtrip time:5293 cost:5038 transfer_no:6439 send_sn:0 send:0 recv_sn:0 rcv:11 status:200
Oct 04 11:37:56.580 - [DEBUG] start roundtrip transfer_no:6441 send_data_len:0 ack_len:0
Oct 04 11:37:56.819 - [DEBUG] roundtrip time:5476 cost:5226 transfer_no:6440 send_sn:0 send:0 recv_sn:0 rcv:11 status:200
Oct 04 11:37:56.820 - [DEBUG] start roundtrip transfer_no:6442 send_data_len:0 ack_len:0
Oct 04 11:37:59.389 - [DEBUG] roundtrip time:2808 cost:2576 transfer_no:6441 send_sn:0 send:0 recv_sn:365 rcv:37 status:200
Oct 04 11:37:59.389 - [DEBUG] start roundtrip transfer_no:6443 send_data_len:0 ack_len:8
Oct 04 11:37:59.389 - [INFO] Conn session:ffjoamam conn:52 Peer Close:connect fail
Oct 04 11:37:59.391 - [DEBUG] start roundtrip transfer_no:6444 send_data_len:20 ack_len:0
Oct 04 11:37:59.391 - [DEBUG] Conn session:ffjoamam conn:52 stop:peer close
Oct 04 11:37:59.937 - [DEBUG] remove conn_id:52

**Comment by xxnet** [comment]
因为requests 用的域名解析，还是用墙内的，解析到了 8.7.198.45 <http://8.7.198.45:443>，这个ip 是假的。

建议你先修改 /etc/hosts
添加一行：
216.58.192.206   www.youtube.com

再试试

**Comment by derrickcyt** [comment]
@xxnet 
可以了！！感谢！

**Comment by derrickcyt** [comment]
@xxnet 
我看了一下requests的源码，将协议从socks5改为socks5h就好了，socks5使用本地的dns，socks5h使用的是remote dns。

**Comment by xxnet** [comment]
​good，学习了
