### ISSUE TITLE
报错，无法正常运行

### ISSUE THREAD

**Issue by tianxingyzxq** [XX-net/XX-Net#6803]
10月 03 23:18:11.5 - [INFO] use config_path:/home/tx/XX-net/data/x_tunnel/client.json
10月 03 23:18:11.5 - [ERROR] bind to 127.0.0.1:1080 fail:error(98, '\xe5\x9c\xb0\xe5\x9d\x80\xe5\xb7\xb2\xe5\x9c\xa8\xe4\xbd\xbf\xe7\x94\xa8')
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/tx/XX-net/code/3.6.3/x_tunnel/start.py", line 19, in main
    client.main()
  File "/home/tx/XX-net/code/3.6.3/x_tunnel/local/client.py", line 146, in main
    g.socks5_server = simple_http_server.HTTPServer((g.config.socks_host, g.config.socks_port), Socks5Server)
  File "/home/tx/XX-net/code/3.6.3/python27/1.0/lib/noarch/simple_http_server.py", line 274, in __init__
    self.init_socket()
  File "/home/tx/XX-net/code/3.6.3/python27/1.0/lib/noarch/simple_http_server.py", line 284, in init_socket
    self.add_listen(addr)
  File "/home/tx/XX-net/code/3.6.3/python27/1.0/lib/noarch/simple_http_server.py", line 298, in add_listen
    raise Exception(err_string)
Exception: bind to 127.0.0.1:1080 fail:error(98, '\xe5\x9c\xb0\xe5\x9d\x80\xe5\xb7\xb2\xe5\x9c\xa8\xe4\xbd\xbf\xe7\x94\xa8')

10月 03 23:18:11.5 - [DEBUG] network is ok, cost:70 ms

**Comment by tianxingyzxq** [comment]
地址被占了？这种情况要怎么解决呢

**Comment by xxnet** [comment]
​netstat -naptl |grep 1080 看是哪个进程在占用，kill 掉

**Comment by tianxingyzxq** [comment]
OK了
