### ISSUE TITLE
[发布] 3.6.9 稍微改进 x-tunnel

### ISSUE THREAD

**Issue by xxnet** [XX-net/XX-Net#6999]
新版支持http2连接，对连接太差，又能够登陆的用户，应该有改进效果：

https://codeload.github.com/XX-net/XX-Net/zip/3.6.9

**Comment by Fzongx** [comment]
火速下载

**Comment by dagerdager** [comment]
可以用

**Comment by tislam8888** [comment]
安卓的 能够直接复制 这里面的 data 文件夹 升级吗

**Comment by touchtop** [comment]
的确有效，x-tunnel可用了，感谢辛苦工作。

**Comment by bolaparte** [comment]
Login fail:parse json fail

**Comment by IM-111** [comment]
现在的xx-net好像封了tweets，导致推特不能搜索,hashtag也搜不到结果，不知有没解决方法

**Comment by shuiliu11** [comment]
有效，很给力，再一次体现技术实力！！！

**Comment by dagerdager** [comment]
又不能用了
Oct 08 20:19:32.318 - [DEBUG] create ssl timeout fail.

Oct 08 20:20:01.327 - [DEBUG] create ssl timeout fail.

Oct 08 20:21:32.394 - [DEBUG] create ssl timeout fail.

Oct 08 20:22:01.414 - [DEBUG] create ssl timeout fail.

Oct 08 20:23:32.551 - [DEBUG] create ssl timeout fail.

Oct 08 20:24:01.583 - [DEBUG] create ssl timeout fail.

Oct 08 20:25:32.711 - [DEBUG] create ssl timeout fail.

Oct 08 20:26:01.762 - [DEBUG] create ssl timeout fail.

Oct 08 20:27:32.893 - [DEBUG] create ssl timeout fail.

Oct 08 20:28:01.919 - [DEBUG] create ssl timeout fail.

Oct 08 20:29:33.027 - [DEBUG] create ssl timeout fail.

Oct 08 20:30:02.067 - [DEBUG] create ssl timeout fail.

Oct 08 20:31:33.153 - [DEBUG] create ssl timeout fail.

Oct 08 20:32:02.161 - [DEBUG] create ssl timeout fail.

Oct 08 20:33:33.274 - [DEBUG] create ssl timeout fail.

Oct 08 20:34:02.282 - [DEBUG] create ssl timeout fail.

Oct 08 20:35:33.487 - [DEBUG] create ssl timeout fail.

Oct 08 20:36:02.535 - [DEBUG] create ssl timeout fail.

Oct 08 20:37:33.635 - [DEBUG] create ssl timeout fail.

Oct 08 20:38:02.636 - [DEBUG] create ssl timeout fail.

**Comment by xxnet** [comment]
​@tislam8888
  3.6.9 已推送测试版更新，android 可以直接在Web界面上升级。

@bolaparte
  先排除 data/x_tunnel/client.json 内容格式有没有错误。
  再重新登陆一次看看
@dagerdager

  不能保证能用，如果全封了，就无法使用的，新版本只是做到在少量连接下可以使用。

**Comment by onplus** [comment]
[ERROR] google_ip.runJob fail:NameError("global name 'ip' is not defined",)
[ERROR] Except stack:Traceback (most recent call last): 
File "D:\WorkSpace\Tools\XX-Net\code\3.6.9\x_tunnel\local\cloudflare_front\ip_manager.py", line 639, in scan_ip_worker result = check_ip.test_xtunnel_ip2(ip) 
File "D:\WorkSpace\Tools\XX-Net\code\3.6.9\x_tunnel\local\cloudflare_front\check_ip.py", line 313, in test_xtunnel_ip2 return check_xtunnel_http2(ssl_sock, host) 
File "D:\WorkSpace\Tools\XX-Net\code\3.6.9\x_tunnel\local\cloudflare_front\check_ip.py", line 259, in check_xtunnel_http2 
xlog.debug("ip:undefined http/1.1:%r", ip, e ) NameError: global name 'ip' is not defined

https://github.com/XX-net/XX-Net/blob/master/code/default/x_tunnel/local/cloudflare_front/ip_manager.py#L625

https://github.com/XX-net/XX-Net/blob/d7417cb42fbaa97e7a54bc4aa7ac9e48721948e5/code/default/x_tunnel/local/cloudflare_front/check_ip.py#L252-L260

**Comment by ffdzpilot** [comment]
可以用了，刚把蓝灯500m榨干，赶紧打开YouTube任性的压压惊。祝最终邪不压正。

**Comment by suhaojia** [comment]
@xxnet 
怎么排除data/x_tunnel/client.json 内容格式有没有错误，我打开了以后是 visual studio打开的
里面只有账户 密码还是加密过的
我是3.6.9版本 能登录了 流量什么都有 
设置也按照使用说明设置好了
但是就是一直尚未建立连接

**Comment by XLX** [comment]
亲测新版 X-Tunnel 可用，上个版本之前还处于只能登录不能用的状态。目前来看，速度和 IPv6 6to4 方案的 GAE 基本持平，Youtube 720p 的水平，1080p 会卡。已经非常不错了，感谢作者。

**Comment by xxnet** [comment]
​已确认bug，发3.6.10

**Comment by bitternolis** [comment]
可用

**Comment by sky2917** [comment]
我这显示：Login fail:parse json fail

Oct 08 21:24:14.404 - [DEBUG] x-tunnel web_control 127.0.0.1:57259 POST /login
Oct 08 21:24:15.187 - [WARNING] api:/login parse json:{"quota_list": {"current": {"end_time": 1507484699, "quota": 200000000}, "backup": [{"end_time": 1507484863, "quota": 200000000}, {"end_time": 1507484864, "quota": 200000000}, {"end_time": 1507484871, "quota": 200000000}, {"end_time": 1507484894, "quota": 200000000}, {"end_time": 1507490639, "quota": 200000000}, {"end_time": 1507490640, "quota": 200000000}, {"end_time": 1507490641, "quota": 200000000}, {"end_time": 1507490643, "quota": 200000000}, {"end_time": 1507490649, "quota": 200000000}, {"end_time": 1507497873, "quota": 200000000}, {"end_time": 1507498209, "quota": 200000000}, {"end_time": 1507498630, "quota": 200000000}, {"end_time": 1507503090, "quota": 200000000}, {"end_time": 1507511332, "quota": 200000000}, {"end_time": 1507511864, "quota": 200000000}, {"end_time": 1507513871, "quota": 200000000}, {"end_time": 1507521559, "quota": 200000000}, {"end_time": 1507521581, "quota": 200000000}, {"end_time": 1507523872, "quota": 200000000}, {"end_time": 1507527173, "quota": 200000000}, {"end_time": 1507527324, "quota": 200000000}, {"end_time": 1507527652, "quota": 200000000}, {"end_time": 1507527653, "quota": 200000000}, {"end_time": 1507528490, "quota": 200000000}, {"end_time": 1507528510, "quota": 200000000}, {"end_time": 1507528571, "quota": 200000000}, {"end_time": 1507528572, "quota": 200000000}, {"end_time": 1507528595, "quota": 200000000}, {"end_time": 1507528597, "quota": 200000000}, {"end_time": 1507528642, "quota": 200000000}, {"end_time": 1507532373, "quota": 200000000}, {"end_time": 1507532374, "quota": 600000000}, {"end_time": 1507532375, "quota": 200000000}, {"end_time": 1507532383, "quota": 200000000}, {"end_time": 1507533544, "quota": 200000000}, {"end_time": 1507533974, "quota": 200000000}, {"end_time": 1507534282, "quota": 200000000}, {"end_time": 1507534698, "quota": 200000000}, {"end_time": 1507539377, "quota": 200000000}, {"end_time": 1507539385, "quota": 200000000}, {"end_time": 1507539697, "quota": 200000000}, {"end_time": 1507548512, "quota": 400000000}, {"end_time": 1507548516, "quota": 200000000}, {"end_time": 1507554821, "quota": 200000000}, {"end_time": 1507554824, "quota": 200000000}, {"end_time": 1507554828, "quota": 200000000}, {"end_time": 1507554829, "quota": 200000000}, {"end_time": 1507554830, "quota": 200000000}, {"end_time": 1507554860, "quota": 200000000}, {"end_time": 1507555090, "quota": 200000000}, {"end_time": 1507555217, "quota": 200000000}, {"end_time fail:ValueError('Unterminated string starting at: line 1 column 2432 (char 2431)',)
Oct 08 21:24:18.300 - [DEBUG] x-tunnel no account
Oct 08 21:24:18.300 - [WARNING] create conn fail
Oct 08 21:24:18.304 - [DEBUG] x-tunnel no account
Oct 08 21:24:18.304 - [WARNING] Socks4 connect fail, no conn_id

**Comment by bitternolis** [comment]
对连接太差，又能够登陆的用户有效，自然对不能登陆的用户无效了。

**Comment by suhaojia** [comment]
咦咦咦 居然好了 我一直盯着gae 没去打开外网试试 原来已经好了啊！！！！！

**Comment by Fzongx** [comment]
我两个x tunnel账号,一个可登录且好使,另一个不能登录,错误提示:parse json fail

**Comment by kim-wang-bj** [comment]
Oct 08 21:49:18.704 - [INFO] use config_path:C:\software\XX-Net-3.6.10\data\x_tunnel\client.json
Oct 08 21:49:18.704 - [INFO] X-Tunnel window:33554432
Oct 08 21:49:18.705 - [INFO] Socks5 server listen:127.0.0.1:1080.
Oct 08 21:50:12.281 - [DEBUG] x-tunnel web_control 127.0.0.1:7938 POST /login
Oct 08 21:51:07.403 - [WARNING] api:/login fail:status:500 t:55
Oct 08 21:52:24.354 - [DEBUG] x-tunnel web_control 127.0.0.1:7942 POST /login
Oct 08 21:52:25.577 - [WARNING] api:/login parse json:{"quota_list": {"current": {"end_time": 1507518144, "quota": 199084631}, "backup": [{"end_time": 1507518145, "quota": 600000000}, {"end_time": 1507520232, "quota": 200000000}, {"end_time": 1507520820, "quota": 200000000}, {"end_time": 1507523875, "quota": 200000000}, {"end_time": 1507531919, "quota": 200000000}, {"end_time": 1507532111, "quota": 200000000}, {"end_time": 1507532365, "quota": 200000000}, {"end_time": 1507532649, "quota": 200000000}, {"end_time": 1507532804, "quota": 200000000}, {"end_time": 1507532936, "quota": 200000000}, {"end_time": 1507533114, "quota": 200000000}, {"end_time": 1507534732, "quota": 200000000}, {"end_time": 1507535721, "quota": 200000000}, {"end_time": 1507537335, "quota": 200000000}, {"end_time": 1507537401, "quota": 200000000}, {"end_time": 1507537418, "quota": 200000000}, {"end_time": 1507539368, "quota": 200000000}, {"end_time": 1507539567, "quota": 200000000}, {"end_time": 1507542721, "quota": 200000000}, {"end_time": 1507543552, "quota": 200000000}, {"end_time": 1507543720, "quota": 200000000}, {"end_time": 1507545223, "quota": 200000000}, {"end_time": 1507545605, "quota": 200000000}, {"end_time": 1507546743, "quota": 200000000}, {"end_time": 1507546819, "quota" fail:ValueError('Expecting : delimiter: line 1 column 1221 (char 1220)',)

**Comment by kim-wang-bj** [comment]
我这遇到parse json fail。把旧版的data\x_tunnel\client.json拷贝过去就好了。

**Comment by guojiaxu1** [comment]
Login fail:parse json fail   请问这个怎么解决呀？总是提示这个

**Comment by gggccc44** [comment]
或者X-Tunnel不用443，貌似在那里看到说墙封443封的厉害

**Comment by xxnet** [comment]
Login fail:parse json fail
确实是客户端bug，已经修复。

存在问题的请下载新版：
https://github.com/XX-net/XX-Net/archive/3.6.11.zip

**Comment by nly4lov** [comment]
ip数仍然是2个
