### ISSUE TITLE
求大神解答，为毛部署失败

### ISSUE THREAD

**Issue by JasonZuo123** [XX-net/XX-Net#7095]
2017-10-10 13:56:39,210 - root - INFO - enable debug logging
2017-10-10 13:56:39,211 - root - INFO - set proxy to http://127.0.0.1:8087
2017-10-10 13:56:39,217 - root - INFO - ============ Begin upload ============
2017-10-10 13:56:39,217 - root - INFO - appid:vpn0123-隐藏掉。。
2017-10-10 13:56:39,242 - root - INFO - Send: /api/appversion/rollback, params={'version': '1', 'app_id': 'vpn0123-隐藏掉。。'}
2017-10-10 13:56:39,242 - google.appengine.tools.appengine_rpc - DEBUG - _Authenticate skipped auth; needs_auth=False
2017-10-10 13:56:39,243 - google.appengine.tools.appengine_rpc - DEBUG - Sending request to https://appengine.google.com/api/appversion/rollback?app_id=vpn0123-隐藏掉。。&force_rollback=0&version=1 headers={'X-appcfg-api-version': '1', 'content-length': '0', 'Content-Type': 'application/octet-stream'} body=
2017-10-10 14:03:37,178 - google.appengine.tools.appengine_rpc - DEBUG - Got http error 600.
2017-10-10 14:03:37,180 - google.appengine.tools.appengine_rpc - DEBUG - Unexpected results: {'status': '600', 'content-length': '144', 'connection': 'close'}
2017-10-10 14:03:37,180 - root - ERROR - upload fail:ValidationError("Value '600' for response_code is out of range 100 - 599",)
Traceback (most recent call last):
File "C:\Users\Jason_Zuo\Desktop\XX-Net-3.6.8\XX-Net-3.6.8\code\default\gae_proxy\server\uploader.py", line 70, in upload
result = appcfg.AppCfgApp(['appcfg', 'rollback', dirname ]).Run()
File "C:\Users\Jason_Zuo\Desktop\XX-Net-3.6.8\XX-Net-3.6.8\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 2951, in Run
self.action(self)
File "C:\Users\Jason_Zuo\Desktop\XX-Net-3.6.8\XX-Net-3.6.8\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 5044, in __call__
return method()
File "C:\Users\Jason_Zuo\Desktop\XX-Net-3.6.8\XX-Net-3.6.8\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 4397, in Rollback
self._Rollback()
File "C:\Users\Jason_Zuo\Desktop\XX-Net-3.6.8\XX-Net-3.6.8\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 4442, in _Rollback
appversion.Rollback(force_rollback)
File "C:\Users\Jason_Zuo\Desktop\XX-Net-3.6.8\XX-Net-3.6.8\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 2362, in Rollback
force_rollback='1' if force_rollback else '0')
File "C:\Users\Jason_Zuo\Desktop\XX-Net-3.6.8\XX-Net-3.6.8\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 1702, in Send
request_size_bytes)
File "C:\Users\Jason_Zuo\Desktop\XX-Net-3.6.8\XX-Net-3.6.8\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 1723, in _RegisterReqestForLogging
request_size_bytes=request_size_bytes))
File "C:\Users\Jason_Zuo\Desktop\XX-Net-3.6.8\XX-Net-3.6.8\code\default\gae_proxy\server\lib\google\appengine\api\validation.py", line 273, in __init__
self.SetMultiple(attributes)
File "C:\Users\Jason_Zuo\Desktop\XX-Net-3.6.8\XX-Net-3.6.8\code\default\gae_proxy\server\lib\google\appengine\api\validation.py", line 177, in SetMultiple
self.Set(key, value)
File "C:\Users\Jason_Zuo\Desktop\XX-Net-3.6.8\XX-Net-3.6.8\code\default\gae_proxy\server\lib\google\appengine\api\validation.py", line 305, in Set
setattr(self, key, value)
File "C:\Users\Jason_Zuo\Desktop\XX-Net-3.6.8\XX-Net-3.6.8\code\default\gae_proxy\server\lib\google\appengine\api\validation.py", line 361, in __setattr__
value = self.GetValidator(key)(value, key)
File "C:\Users\Jason_Zuo\Desktop\XX-Net-3.6.8\XX-Net-3.6.8\code\default\gae_proxy\server\lib\google\appengine\api\validation.py", line 599, in __call__
return self.Validate(value, key)
File "C:\Users\Jason_Zuo\Desktop\XX-Net-3.6.8\XX-Net-3.6.8\code\default\gae_proxy\server\lib\google\appengine\api\validation.py", line 1157, in Validate
% (value, key, self.minimum, self.maximum))
ValidationError: Value '600' for response_code is out of range 100 - 599
2017-10-10 14:03:37,187 - root - INFO - Retry 1 time...
2017-10-10 14:03:37,209 - root - INFO - Send: /api/appversion/rollback, params={'version': '1', 'app_id': 'vpn0123-隐藏掉'}
2017-10-10 14:03:37,210 - google.appengine.tools.appengine_rpc - DEBUG - _Authenticate skipped auth; needs_auth=False
2017-10-10 14:03:37,210 - google.appengine.tools.appengine_rpc - DEBUG - Sending request to https://appengine.google.com/api/appversion/rollback?app_id=vpn0123-隐藏掉'&force_rollback=0&version=1 headers={'X-appcfg-api-version': '1', 'content-length': '0', 'Content-Type': 'application/octet-stream'} body=
2017-10-10 14:07:39,204 - google.appengine.tools.appengine_rpc - DEBUG - Got http error 600.
2017-10-10 14:07:39,206 - google.appengine.tools.appengine_rpc - DEBUG - Unexpected results: {'status': '600', 'content-length': '144', 'connection': 'close'}
2017-10-10 14:07:39,206 - root - ERROR - upload fail:ValidationError("Value '600' for response_code is out of range 100 - 599",)
Traceback (most recent call last):
File "C:\Users\Jason_Zuo\Desktop\XX-Net-3.6.8\XX-Net-3.6.8\code\default\gae_proxy\server\uploader.py", line 70, in upload
result = appcfg.AppCfgApp(['appcfg', 'rollback', dirname ]).Run()
File "C:\Users\Jason_Zuo\Desktop\XX-Net-3.6.8\XX-Net-3.6.8\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 2951, in Run
self.action(self)
File "C:\Users\Jason_Zuo\Desktop\XX-Net-3.6.8\XX-Net-3.6.8\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 5044, in __call__
return method()
File "C:\Users\Jason_Zuo\Desktop\XX-Net-3.6.8\XX-Net-3.6.8\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 4397, in Rollback
self._Rollback()
File "C:\Users\Jason_Zuo\Desktop\XX-Net-3.6.8\XX-Net-3.6.8\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 4442, in _Rollback
appversion.Rollback(force_rollback)
File "C:\Users\Jason_Zuo\Desktop\XX-Net-3.6.8\XX-Net-3.6.8\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 2362, in Rollback
force_rollback='1' if force_rollback else '0')
File "C:\Users\Jason_Zuo\Desktop\XX-Net-3.6.8\XX-Net-3.6.8\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 1702, in Send
request_size_bytes)
File "C:\Users\Jason_Zuo\Desktop\XX-Net-3.6.8\XX-Net-3.6.8\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 1723, in _RegisterReqestForLogging
request_size_bytes=request_size_bytes))
File "C:\Users\Jason_Zuo\Desktop\XX-Net-3.6.8\XX-Net-3.6.8\code\default\gae_proxy\server\lib\google\appengine\api\validation.py", line 273, in __init__
self.SetMultiple(attributes)
File "C:\Users\Jason_Zuo\Desktop\XX-Net-3.6.8\XX-Net-3.6.8\code\default\gae_proxy\server\lib\google\appengine\api\validation.py", line 177, in SetMultiple
self.Set(key, value)
File "C:\Users\Jason_Zuo\Desktop\XX-Net-3.6.8\XX-Net-3.6.8\code\default\gae_proxy\server\lib\google\appengine\api\validation.py", line 305, in Set
setattr(self, key, value)
File "C:\Users\Jason_Zuo\Desktop\XX-Net-3.6.8\XX-Net-3.6.8\code\default\gae_proxy\server\lib\google\appengine\api\validation.py", line 361, in __setattr__
value = self.GetValidator(key)(value, key)
File "C:\Users\Jason_Zuo\Desktop\XX-Net-3.6.8\XX-Net-3.6.8\code\default\gae_proxy\server\lib\google\appengine\api\validation.py", line 599, in __call__
return self.Validate(value, key)
File "C:\Users\Jason_Zuo\Desktop\XX-Net-3.6.8\XX-Net-3.6.8\code\default\gae_proxy\server\lib\google\appengine\api\validation.py", line 1157, in Validate
% (value, key, self.minimum, self.maximum))
ValidationError: Value '600' for response_code is out of range 100 - 599
2017-10-10 14:07:39,207 - root - INFO - Retry 2 time...
2017-10-10 14:07:40,242 - root - INFO - Send: /api/appversion/rollback, params={'version': '1', 'app_id': 'vpn0123-隐藏掉'}
2017-10-10 14:07:40,242 - google.appengine.tools.appengine_rpc - DEBUG - _Authenticate skipped auth; needs_auth=False
2017-10-10 14:07:40,243 - google.appengine.tools.appengine_rpc - DEBUG - Sending request to https://appengine.google.com/api/appversion/rollback?app_id=vpn0123-隐藏掉'&force_rollback=0&version=1 headers={'X-appcfg-api-version': '1', 'content-length': '0', 'Content-Type': 'application/octet-stream'} body=
2017-10-10 14:11:07,318 - google.appengine.tools.appengine_rpc - DEBUG - Got http error 600.
2017-10-10 14:11:07,318 - google.appengine.tools.appengine_rpc - DEBUG - Unexpected results: {'status': '600', 'content-length': '144', 'connection': 'close'}
2017-10-10 14:11:07,319 - root - ERROR - upload fail:ValidationError("Value '600' for response_code is out of range 100 - 599",)
Traceback (most recent call last):
File "C:\Users\Jason_Zuo\Desktop\XX-Net-3.6.8\XX-Net-3.6.8\code\default\gae_proxy\server\uploader.py", line 70, in upload
result = appcfg.AppCfgApp(['appcfg', 'rollback', dirname ]).Run()
File "C:\Users\Jason_Zuo\Desktop\XX-Net-3.6.8\XX-Net-3.6.8\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 2951, in Run
self.action(self)
File "C:\Users\Jason_Zuo\Desktop\XX-Net-3.6.8\XX-Net-3.6.8\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 5044, in __call__
return method()
File "C:\Users\Jason_Zuo\Desktop\XX-Net-3.6.8\XX-Net-3.6.8\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 4397, in Rollback
self._Rollback()
File "C:\Users\Jason_Zuo\Desktop\XX-Net-3.6.8\XX-Net-3.6.8\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 4442, in _Rollback
appversion.Rollback(force_rollback)
File "C:\Users\Jason_Zuo\Desktop\XX-Net-3.6.8\XX-Net-3.6.8\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 2362, in Rollback
force_rollback='1' if force_rollback else '0')
File "C:\Users\Jason_Zuo\Desktop\XX-Net-3.6.8\XX-Net-3.6.8\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 1702, in Send
request_size_bytes)
File "C:\Users\Jason_Zuo\Desktop\XX-Net-3.6.8\XX-Net-3.6.8\code\default\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 1723, in _RegisterReqestForLogging
request_size_bytes=request_size_bytes))
File "C:\Users\Jason_Zuo\Desktop\XX-Net-3.6.8\XX-Net-3.6.8\code\default\gae_proxy\server\lib\google\appengine\api\validation.py", line 273, in __init__
self.SetMultiple(attributes)
File "C:\Users\Jason_Zuo\Desktop\XX-Net-3.6.8\XX-Net-3.6.8\code\default\gae_proxy\server\lib\google\appengine\api\validation.py", line 177, in SetMultiple
self.Set(key, value)
File "C:\Users\Jason_Zuo\Desktop\XX-Net-3.6.8\XX-Net-3.6.8\code\default\gae_proxy\server\lib\google\appengine\api\validation.py", line 305, in Set
setattr(self, key, value)
File "C:\Users\Jason_Zuo\Desktop\XX-Net-3.6.8\XX-Net-3.6.8\code\default\gae_proxy\server\lib\google\appengine\api\validation.py", line 361, in __setattr__
value = self.GetValidator(key)(value, key)
File "C:\Users\Jason_Zuo\Desktop\XX-Net-3.6.8\XX-Net-3.6.8\code\default\gae_proxy\server\lib\google\appengine\api\validation.py", line 599, in __call__
return self.Validate(value, key)
File "C:\Users\Jason_Zuo\Desktop\XX-Net-3.6.8\XX-Net-3.6.8\code\default\gae_proxy\server\lib\google\appengine\api\validation.py", line 1157, in Validate
% (value, key, self.minimum, self.maximum))
ValidationError: Value '600' for response_code is out of range 100 - 599
2017-10-10 14:11:07,319 - root - INFO - Retry 3 time...
2017-10-10 14:11:09,322 - root - INFO - =======================
2017-10-10 14:11:09,322 - root - INFO - Deploy failed appid list:
2017-10-10 14:11:09,322 - root - INFO - - vpn0123-隐藏掉
2017-10-10 14:11:09,322 - root - INFO - == END ==

**Comment by LittlePigIsKid** [comment]
部署的时候需要是可以翻墙的，你确认一下现在是可以翻墙的不

**Comment by JasonZuo123** [comment]
部署的时候我还无法翻墙，我还没找到什么免费的代理软件。。。有好的推荐吗？

**Comment by carotin** [comment]
1.上传时首先确认--->允许不够安全的应用：开启
2.还是上传不了，下载SSTap然后去找个SS帐号

**Comment by liangliangge521** [comment]
不用那么麻烦，把你旧版本里的data文件夹复制到新版本的xxnet里覆盖即可，这样就不用重新部署了，打开xxnet直接显示部署完成，然后翻墙就行了（有个前提就是你旧版本的xxnet必须是部署成功的）
