### ISSUE TITLE
2.05启动失败

### ISSUE THREAD

**Issue by nflswyz** [XX-net/XX-Net#710]
一开始是覆盖2.04版本的，出现问题后解压到全新的文件夹，没有解决问题。
系统是Win8.1 64位。
因隐私原因把路径里的用户名换成了[username]，请见谅。
```
Jul 23 13:15:39 - [DEBUG] start confirm_xxnet_exit
Jul 23 13:15:40 - [INFO] load ip range file:C:\Users\[username]\Apps\XX-Net-maste
r\gae_proxy\local\ip_range.txt
Jul 23 13:15:40 - [INFO] load google ip_list num:100, gws num:100
Jul 23 13:15:40 - [INFO] SSL use version:TLSv1
Jul 23 13:15:40 - [INFO] ------------------------------------------------------
GAEProxy Version    : gae_proxy (python/2.7.9 )
Listen Address     : 127.0.0.1:8087
GAE APPID          : xxnet-1|xxnet-2|xxnet-3|xxnet-4|xxnet-5|xxnet-6|xxnet-7|xxn
et-8|xxnet-9|xxnet-10|xxnet-11|xxnet-12|xxnet-13|xxnet-14|xxnet-15|xxnet-16|xxne
t-17|xxnet-18|xxnet-19|xxnet-20|xxnet-21|xxnet-22|xxnet-23|xxnet-24|xxnet-25|xxn
et-26|xxnet-27|xxnet-28|xxnet-29|xxnet-30|xxnet-31|xxnet-32|xxnet-33|xxnet-34|xx
net-35|xxnet-36|xxnet-37|xxnet-38|xxnet-39|xxnet-40|xxnet-41|xxnet-42|xxnet-43|x
xnet-44|xxnet-45|xxnet-46|xxnet-47|xxnet-48|xxnet-49|xxnet-50|xxnet-51|xxnet-52|
xxnet-53|xxnet-54|xxnet-55|xxnet-56|xxnet-57|xxnet-58|xxnet-59|xxnet-60|xxnet-61
|xxnet-62|xxnet-63|xxnet-64|xxnet-65|xxnet-66|xxnet-67|xxnet-68|xxnet-69|xxnet-7
0|xxnet-71|xxnet-72|xxnet-72|xxnet-73|xxnet-74|xxnet-75|xxnet-76|xxnet-77|xxnet-
78|xxnet-79|xxnet-80|xxnet-81|xxnet-82|xxnet-83|xxnet-84|xxnet-85|xxnet-86|xxnet
-87|xxnet-88|xxnet-89|xxnet-90|xxnet-91|xxnet-92|xxnet-93|xxnet-94|xxnet-95|xxne
t-96|xxnet-97|xxnet-98|xxnet-99|xxnet-100|xxnet-101|xxnet-102|xxnet-103|xxnet-10
4|xxnet-105|xxnet-106|xxnet-107|xxnet-108|xxnet-109|xxnet-110|xxnet-111|xxnet-11
2|xxnet-113|xxnet-114|xxnet-115|xxnet-116|xxnet-117|xxnet-118|xxnet-119|xxnet-12
0|xxnet-121|xxnet-122|xxnet-123|xxnet-124|xxnet-125|xxnet-126|xxnet-127|xxnet-12
8|xxnet-129|xxnet-130|xxnet-131|xxnet-132|xxnet-133|xxnet-134|xxnet-135|xxnet-13
6|xxnet-137|xxnet-138|xxnet-139|xxnet-140|xxnet-141|xxnet-142|xxnet-143|xxnet-14
4|xxnet-145|xxnet-146|xxnet-147|xxnet-148|xxnet-149|xxnet-150|xxnet-151|xxnet-15
2|xxnet-153|xxnet-154|xxnet-155|xxnet-156|xxnet-157|xxnet-158|xxnet-159
Pac Server         : http://127.0.0.1:8086/proxy.pac
------------------------------------------------------

Jul 23 13:15:41 - [INFO] gae_proxy started
Jul 23 13:15:41 - [INFO] start gae_proxy time cost 967
Traceback (most recent call last):
  File "C:\Users\[username]\Apps\XX-Net-master\launcher/start.py", line 98, in <m
odule>
    main()
  File "C:\Users\[username]\Apps\XX-Net-master\launcher/start.py", line 77, in ma
in
    web_control.start()
  File "C:\Users\[username]\Apps\XX-Net-master\launcher\web_control.py", line 389
, in start
    server = LocalServer(("0.0.0.0", 8085), Http_Handler)
  File "C:\Users\[username]\Apps\XX-Net-master\python27\1.0\lib\SocketServer.py",
 line 419, in __init__
    self.server_bind()
  File "C:\Users\[username]\Apps\XX-Net-master\python27\1.0\lib\SocketServer.py",
 line 430, in server_bind
    self.socket.bind(self.server_address)
  File "C:\Users\[username]\Apps\XX-Net-master\python27\1.0\lib\socket.py", line
224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 10013]
Stopping all modules before exit!
Jul 23 13:15:41 - [DEBUG] module gae_proxy stopping
Jul 23 13:15:41 - [DEBUG] get ip:202.86.162.41 t:99
Jul 23 13:15:41 - [INFO] Exiting gae_proxy module...
Jul 23 13:15:42 - [DEBUG] get ip:103.1.139.167 t:392
Jul 23 13:15:42 - [INFO] Finished Exiting gae_proxy module...
Jul 23 13:15:42 - [INFO] module gae_proxy stopped
```

**Comment by xxnet** [comment]
绑定8085端口失败，看看是不是有 其他进程监听这个端口

2015-07-23 13:32 GMT+08:00 nflswyz <notifications@github.com>:
