### ISSUE TITLE
Segmentation fault (openssl)

### ISSUE THREAD

**Issue by postadelmaga** [XX-net/XX-Net#7120]
Sorry I live in china but I don't speak Chinese, I am a bad waiguo ren :)

I try to run xx-net on Arch linux but I got a _Segmentation fault_ ( few month ago it was working fine, so it think it may be some issue related to Arch ) 

here the log:
```
$ $ ./start 
XX-Net version:default

(start.py:9492): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",

(start.py:9492): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",
ott 11 00:10:48.012 - [INFO] import build-in openssl fail:AttributeError("'module' object has no attribute 'SSL_ST_INIT'",)
ott 11 00:10:48.055 - [INFO] start XX-Net 3.6.13
ott 11 00:10:48.055 - [DEBUG] start confirm_xxnet_exit
ott 11 00:10:48.056 - [DEBUG] good, xxnet:8087 cleared!                                                                                                                     
ott 11 00:10:48.056 - [DEBUG] good, xxnet:8085 clear!                                                                                                                       
ott 11 00:10:48.056 - [DEBUG] finished confirm_xxnet_exit                                                                                                                   
ott 11 00:10:48.099 - [INFO] SSL use version:TLSv1_2
ott 11 00:10:48.100 - [INFO] OpenSSL support alpn
ott 11 00:10:48.104 - [INFO] load ip range file:/home/fra/Desktop/XX-Net-master/code/default/gae_proxy/local/ip_range.txt
ott 11 00:10:48.134 - [INFO] Use google ip range.
ott 11 00:10:48.134 - [INFO] load google ip_list num:0, gws num:0
ott 11 00:10:48.137 - [INFO] OpenSSL support alpn
ott 11 00:10:48.139 - [WARNING] no enough ip
ott 11 00:10:48.142 - [DEBUG] ## GAEProxy set keep_running: True
ott 11 00:10:48.142 - [INFO] ------------------------------------------------------
ott 11 00:10:48.142 - [INFO] Python Version     : 2.7.14
ott 11 00:10:48.142 - [INFO] OS                 : Dist:; Version:; ID:
ott 11 00:10:48.142 - [INFO] Listen Address     : 127.0.0.1:8087
ott 11 00:10:48.142 - [INFO] GAE APPID          :
ott 11 00:10:48.143 - [INFO] Pac Server         : http://127.0.0.1:8086/proxy.pac
ott 11 00:10:48.143 - [INFO] ------------------------------------------------------
ott 11 00:10:48.153 - [INFO] system cert exist
GoAgent XX-Net - GoAgent                                     C,,
ott 11 00:10:48.176 - [INFO] server 127.0.0.1:8087 started.
ott 11 00:10:48.177 - [INFO] server 127.0.0.1:8086 started.
ott 11 00:10:48.241 - [INFO] module gae_proxy started
ott 11 00:10:48.241 - [INFO] start gae_proxy time cost:184 ms
./start: line 32:  9492 Segmentation fault      (core dumped) ${PYTHON} code/${VERSION}/launcher/start.py
```

Any idea what is wrong ?

**Comment by e2889e** [comment]
This is my log, i guess something wrong with your openssl library.
```
Oct 11 00:40:59.706 - [DEBUG] network is ok, cost:823 ms
Oct 11 00:40:59.726 - [INFO] server 127.0.0.1:8087 started.
Oct 11 00:40:59.727 - [INFO] server 127.0.0.1:8086 started.
Oct 11 00:40:59.813 - [INFO] module gae_proxy started
Oct 11 00:40:59.814 - [INFO] start gae_proxy time cost:1055 ms
WARNING:root:Load Crypto.Cipher.ARC4 Failed, Use Pure Python Instead.
Oct 11 00:40:59.953 - [INFO] SSL use version:TLSv1_2
Oct 11 00:40:59.954 - [INFO] OpenSSL support alpn
```

**Comment by xxnet** [comment]
Try download the zip from github, unzip and run it.

try install package:
python2-*pyopenssl*


If fail again, try run python with gdb:
gdb python
set args code/default/launcher/start.py
r

It will show the place when
*Segmentation fault happened*

**Comment by postadelmaga** [comment]
_python2-pyopenssl_ is already installed on my system, anyway I have reinstalled ( still the issue is there :(

So, as you suggested, I started it with gdb ... looks you are right something is wrong with openssl :

```
Starting program: /usr/bin/python2 code/default/launcher/start.py
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".

(start.py:2814): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",

(start.py:2814): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",
ott 11 09:53:03.267 - [INFO] import build-in openssl fail:AttributeError("'module' object has no attribute 'SSL_ST_INIT'",)
ott 11 09:53:03.339 - [INFO] start XX-Net 3.6.13
ott 11 09:53:03.339 - [DEBUG] start confirm_xxnet_exit
ott 11 09:53:03.340 - [DEBUG] good, xxnet:8087 cleared!                                                                                                                     
ott 11 09:53:03.341 - [DEBUG] good, xxnet:8085 clear!                                                                                                                       
ott 11 09:53:03.341 - [DEBUG] finished confirm_xxnet_exit                                                                                                                   
[New Thread 0x7fffe7845700 (LWP 2826)]
ott 11 09:53:03.416 - [INFO] SSL use version:TLSv1_2
ott 11 09:53:03.416 - [INFO] OpenSSL support alpn
ott 11 09:53:03.418 - [INFO] load ip range file:/home/fra/Desktop/XX-Net-master/code/default/gae_proxy/local/ip_range.txt
ott 11 09:53:03.446 - [INFO] Use google ip range.
ott 11 09:53:03.446 - [INFO] load google ip_list num:0, gws num:0
[New Thread 0x7fffe6e37700 (LWP 2827)]
[New Thread 0x7fffe6e16700 (LWP 2828)]
[New Thread 0x7fffe6df5700 (LWP 2829)]
[New Thread 0x7fffe6dd4700 (LWP 2830)]
[New Thread 0x7fffe6db3700 (LWP 2831)]
[New Thread 0x7fffe6d92700 (LWP 2832)]
[New Thread 0x7fffe6d71700 (LWP 2833)]
[New Thread 0x7fffe6d50700 (LWP 2834)]
[New Thread 0x7fffe6d2f700 (LWP 2835)]
[New Thread 0x7fffe6d0e700 (LWP 2836)]
[New Thread 0x7fffe6ced700 (LWP 2837)]
ott 11 09:53:03.449 - [INFO] OpenSSL support alpn
[New Thread 0x7fffe6ccc700 (LWP 2838)]
[New Thread 0x7fffe6cab700 (LWP 2839)]
[New Thread 0x7fffe6c8a700 (LWP 2840)]
[New Thread 0x7fffe6c69700 (LWP 2841)]
[New Thread 0x7fffe6c48700 (LWP 2842)]
[New Thread 0x7fffe6c27700 (LWP 2843)]
ott 11 09:53:03.452 - [WARNING] no enough ip
[New Thread 0x7fffe6c06700 (LWP 2844)]
ott 11 09:53:03.456 - [DEBUG] ## GAEProxy set keep_running: True
[New Thread 0x7fffe6ba5700 (LWP 2845)]
ott 11 09:53:03.456 - [INFO] ------------------------------------------------------
ott 11 09:53:03.456 - [INFO] Python Version     : 2.7.14
ott 11 09:53:03.457 - [INFO] OS                 : Dist:; Version:; ID:
ott 11 09:53:03.457 - [INFO] Listen Address     : 127.0.0.1:8087
ott 11 09:53:03.457 - [INFO] GAE APPID          :
ott 11 09:53:03.457 - [INFO] Pac Server         : http://127.0.0.1:8086/proxy.pac
ott 11 09:53:03.457 - [INFO] ------------------------------------------------------
ott 11 09:53:03.468 - [INFO] system cert exist
GoAgent XX-Net - GoAgent                                     C,,
ott 11 09:53:03.489 - [DEBUG] network is ok, cost:117 ms
[Thread 0x7fffe7845700 (LWP 2826) exited]
ott 11 09:53:03.492 - [INFO] server 127.0.0.1:8087 started.
[New Thread 0x7fffe7845700 (LWP 2851)]
ott 11 09:53:03.492 - [INFO] server 127.0.0.1:8086 started.
[New Thread 0x7fffe6b84700 (LWP 2852)]
ott 11 09:53:03.555 - [INFO] module gae_proxy started
ott 11 09:53:03.555 - [INFO] start gae_proxy time cost:214 ms

Thread 1 "python2" received signal SIGSEGV, Segmentation fault.
0x00007fffe88c5b18 in CRYPTO_lock () from /usr/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so
(gdb)
```

**Comment by xxnet** [comment]
Try uninstall the system OpenSSL and cryptography packages.

xx-net have a build-in OpenSSL package.
you can try it by the command:

python code/default/launcher/start.py

(don't use ./start command because it will install pyOpenSL lib automatic)

**Comment by postadelmaga** [comment]
I removed both packages but it complains _python-openssl_ is missing
```
$ python2 start.py

(start.py:18482): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",

(start.py:18482): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",
ott 11 14:57:59.793 - [INFO] import build-in openssl fail:AttributeError("'module' object has no attribute 'SSL_ST_INIT'",)
ott 11 14:57:59.798 - [ERROR] import system python-OpenSSL fail:AttributeError("'module' object has no attribute 'SSL_ST_INIT'",)
ott 11 14:57:59.798 - [ERROR] Except stack:Traceback (most recent call last):
  File "start.py", line 148, in <module>
    import OpenSSL
  File "/home/fra/Desktop/XX-Net-master/code/default/python27/1.0/lib/noarch/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/home/fra/Desktop/XX-Net-master/code/default/python27/1.0/lib/noarch/OpenSSL/SSL.py", line 124, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'

Try install python-openssl

Press Enter to continue...
```

if I install python2-pyopenssl ( _python2-cryptography_  it installed as dependency so I removed after the installation of pyopenssl) I got this:
```
$ python2 start.py                

(start.py:19346): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",

(start.py:19346): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",
ott 11 15:10:25.906 - [INFO] import build-in openssl fail:VerificationError("importing '/home/fra/Desktop/XX-Net-master/code/default/python27/1.0/lib/linux/cryptography/_Cryptography_cffi_f3e4673fx399b1113.so': /home/fra/Desktop/XX-Net-master/code/default/python27/1.0/lib/linux/cryptography/_Cryptography_cffi_f3e4673fx399b1113.so: symbol SSLv3_method, version OPENSSL_1.0.0 not defined in file libssl.so.1.0.0 with link time reference",)
ott 11 15:10:26.463 - [ERROR] import system python-OpenSSL fail:VerificationError("importing '/home/fra/Desktop/XX-Net-master/code/default/python27/1.0/lib/linux/cryptography/_Cryptography_cffi_f3e4673fx399b1113.so': /home/fra/Desktop/XX-Net-master/code/default/python27/1.0/lib/linux/cryptography/_Cryptography_cffi_f3e4673fx399b1113.so: symbol SSLv3_method, version OPENSSL_1.0.0 not defined in file libssl.so.1.0.0 with link time reference",)                                                                       
ott 11 15:10:26.464 - [ERROR] Except stack:Traceback (most recent call last):                                                                                               
  File "start.py", line 148, in <module>                                                                                                                                    
    import OpenSSL                                                                                                                                                          
  File "/usr/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>                                                                                          
    from OpenSSL import crypto, SSL                                                                                                                                         
  File "/usr/lib/python2.7/site-packages/OpenSSL/crypto.py", line 16, in <module>                                                                                           
    from OpenSSL._util import (                                                                                                                                             
  File "/usr/lib/python2.7/site-packages/OpenSSL/_util.py", line 9, in <module>
    binding = Binding()
  File "/home/fra/Desktop/XX-Net-master/code/default/python27/1.0/lib/linux/cryptography/hazmat/bindings/openssl/binding.py", line 114, in __init__
    self._ensure_ffi_initialized()
  File "/home/fra/Desktop/XX-Net-master/code/default/python27/1.0/lib/linux/cryptography/hazmat/bindings/openssl/binding.py", line 126, in _ensure_ffi_initialized
    cls._modules,
  File "/home/fra/Desktop/XX-Net-master/code/default/python27/1.0/lib/linux/cryptography/hazmat/bindings/utils.py", line 31, in load_library_for_binding
    lib = ffi.verifier.load_library()
  File "/usr/lib/python2.7/site-packages/cffi/verifier.py", line 115, in load_library
    return self._load_library()
  File "/usr/lib/python2.7/site-packages/cffi/verifier.py", line 226, in _load_library
    return self._vengine.load_library()
  File "/usr/lib/python2.7/site-packages/cffi/vengine_cpy.py", line 159, in load_library
    raise VerificationError(error)
VerificationError: importing '/home/fra/Desktop/XX-Net-master/code/default/python27/1.0/lib/linux/cryptography/_Cryptography_cffi_f3e4673fx399b1113.so': /home/fra/Desktop/XX-Net-master/code/default/python27/1.0/lib/linux/cryptography/_Cryptography_cffi_f3e4673fx399b1113.so: symbol SSLv3_method, version OPENSSL_1.0.0 not defined in file libssl.so.1.0.0 with link time reference

Try install python-openssl

Press Enter to continue...
```

**Comment by xxnet** [comment]
​First case:
   use arch linux system pyOpenSSL, with Segmentation fault
    There maybe bug exist in the pyOpenSSl lib in the system version.

Second case:
  build-in pyOpenSSL lib can't run in new ArchLinux

Third case:
  system  pyOpenSSL can't work  with build-in cryptography.

Can you use other linux like ubuntu?

Other idea:
Find an other version of pyOpenSSL not released by Arch, or build from
source.

**Comment by postadelmaga** [comment]
I am not very expert with python ...  
If I use pip to install the packages I have the impression it downloads them from the python official repo, or am I wrong ? 
( because in my previous attempt I have removed all packages with pacman and then installed them with pip ... )  

Anyway I think you can close this issue as it looks specific to my distro, I ll try to find a solution and eventually update this issue. (hopefully some packages update will fix the problem ) 

Thank you very much for your support.

**Comment by xxnet** [comment]
​I think we can keep this issue if other people encounter this problem.

pip installed package is different as the pacman install, you can try it.
uninstall all system package: pyOpenSSL and cryptography before install use
pip

**Comment by postadelmaga** [comment]
I did that but the result is the same ... 
Does it means that either there is an issue in some other system libraries either is xx-net code that cause the segmentation fault ?

**Comment by xxnet** [comment]
This is the first time segmentation fault in pyOpenSSL.
Do you have other linux? or you can try other linux in virtualbox.

**Comment by postadelmaga** [comment]
It works on another arch linux so it is probably some issue with my installation.
Unfortunately even if it starts It cannot find any suitable ip address ( I am using it from china ) so it is not very useful at the moment.

**Comment by xxnet** [comment]
​which city you locate?
you can try x-tunnel module, which proxy port is 1080.

**Comment by postadelmaga** [comment]
sichuan chengdu
How to use x-tunnel ? is there any guide in english for that ? ( is it free to use x-tunnel ? )

**Comment by xxnet** [comment]
​download 3.7.2 version
set proxy port to 1080.

register x-tunnel account, you can get 500M for test, and 200M everyday
this month.

**Comment by xxnet** [comment]
https://github.com/XX-net/XX-Net/wiki/how-to-use-X-Tunnel
​

**Comment by xxnet** [comment]
https://github.com/XX-net/XX-Net/wiki/How-to-use-XTunnel
​
