### ISSUE TITLE
扫不到IP，log一直报错

### ISSUE THREAD

**Issue by swim2sun** [XX-net/XX-Net#7148]
错误如下：
```
Oct 11 12:58:50.348 - [ERROR] Except stack:Traceback (most recent call last): File "/Users/youxiangyang/tools/XX-Net-3.2.7/code/3.6.13/gae_proxy/local/google_ip.py", line 633, in scan_ip_worker ip = self.get_ip_to_scan() File "/Users/youxiangyang/tools/XX-Net-3.2.7/code/3.6.13/gae_proxy/local/google_ip_range.py", line 177, in get_ip index = random.randint(0, len(self.ip_range_list) - 1) File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/random.py", line 242, in randint return self.randrange(a, b+1) File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/random.py", line 218, in randrange raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width) ValueError: empty range for randrange() (0,0, 0)
Oct 11 12:58:50.348 - [ERROR] Except stack:Traceback (most recent call last): File "/Users/youxiangyang/tools/XX-Net-3.2.7/code/3.6.13/gae_proxy/local/google_ip.py", line 633, in scan_ip_worker ip = self.get_ip_to_scan() File "/Users/youxiangyang/tools/XX-Net-3.2.7/code/3.6.13/gae_proxy/local/google_ip_range.py", line 177, in get_ip index = random.randint(0, len(self.ip_range_list) - 1) File 
```

版本信息

```
XX-Net Status:

sys-platform: x86_64, Darwin-17.0.0-x86_64-i386-64bit
os-system: Darwin
os-version: Darwin Kernel Version 17.0.0: Thu Aug 24 21:48:19 PDT 2017; root:xnu-4570.1.46~2/RELEASE_X86_64
os-release: 17.0.0
os-detail: Release:10.13; Version:('', '', '') Machine:x86_64
architecture: 64bit,
browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Safari/604.1.38
xxnet-version: 3.6.13

python-version: 2.7.10
openssl-version: 16.0.0 TLSv1 h2:alpn

ipv6-status: 0
gws-ip-num: total:5000 good:0
network-status: OK
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 64
ip-quality: 9999
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false
```

**Comment by jishuaihua** [comment]
把CA删了重启试试，我的可以用了。

**Comment by swim2sun** [comment]
@jishuaihua 删除CA证书吗？

我把` ip_range.txt `删了，重启后就不报错了，但还是没扫到IP

**Comment by jishuaihua** [comment]
我是把文件目录下data/gae_proxy/下的CA文件删除，启动XX-net，问题就没有了。得到一个高手的指点。
