### ISSUE TITLE
appid申请求助

### ISSUE THREAD

**Issue by sundaqing1969** [XX-net/XX-Net#7288]
===============================================================
GoProxy 服务端部署程序, 开始上传 gae 应用文件夹
Linux/Mac 用户, 请使用 python uploader.py 来上传应用

请输入您的appid, 多个appid请用|号隔开
特别提醒：appid 请勿包含 ID/Email 等个人信息！
APPID:daqing-sun
05:43 PM Application: daqing-sun
05:43 PM Host: appengine.google.com
05:43 PM Rolling back the update.
Error 403: --- begin server output ---
You do not have permission to modify this app (app_id=u'b~daqing-sun').
--- end server output ---
Traceback (most recent call last):
File "uploader.py", line 151, in 
File "uploader.py", line 144, in main
File "uploader.py", line 112, in upload
File "D:\下载夹\goproxy-gae-r90\google_appengine\google\appengine\tools\appcfg
.py", line 5516, in main
SystemExit: 1

**Comment by sundaqing1969** [comment]
上面是部署appid的日志，部署失败，求原因

**Comment by sundaqing1969** [comment]
App 引擎
Your first app with Python

选择位置
部署
让我们开始吧。 

参照互动式教程的说明，部署您的第一个应用

**Comment by onplus** [comment]
https://github.com/XX-net/XX-Net/tree/master/code/default/gae_proxy/server

**Comment by sundaqing1969** [comment]
@onplus,我部署goproxy的服务端

**Comment by onplus** [comment]
你的教程地址在哪儿

**Comment by sundaqing1969** [comment]
https://github.com/Alvin9999/new-pac/wiki/%E8%87%AA%E5%BB%BAappid%E5%92%8C%E6%90%9C%E8%B0%B7%E6%AD%8Cip%E6%95%99%E7%A8%8B%EF%BC%88GoAgent%E7%89%88%E5%92%8CGoProxy%E7%89%88%EF%BC%89

**Comment by sundaqing1969** [comment]
申请流程正常走完

**Comment by onplus** [comment]
appid有数字吗

**Comment by sundaqing1969** [comment]
有一个没有，其它有

**Comment by sundaqing1969** [comment]
都不能部署goproxy服务端

**Comment by onplus** [comment]
如果你确定appid没错，下载新的goproxy客户端试试https://github.com/goproxy0/goproxy/releases

**Comment by sundaqing1969** [comment]
谢谢！
