### ISSUE TITLE
2.0.5启动失败

### ISSUE THREAD

**Issue by wsdyuuu** [XX-net/XX-Net#762]
系统是win7 旗舰版 
目前状态页空白，试着运行start.bat
得到
D:\XX-Net-2.0.5>"D:\XX-Net-2.0.5\python27/1.0/python.exe" "D:\XX-Net-2.0.5\launc
her/start.py"
Aug 03 00:42:14 - [DEBUG] start confirm_xxnet_exit
Aug 03 00:42:15 - [ERROR] start module gae_proxy fail:No module named _memimport
er
Traceback (most recent call last):
  File "D:\XX-Net-2.0.5\launcher\module_init.py", line 34, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['loca
l', 'start'], -1)
  File "D:\XX-Net-2.0.5\gae_proxy\start.py", line 13, in <module>
    import local.proxy as client
  File "D:\XX-Net-2.0.5\gae_proxy\local\proxy.py", line 77, in <module>
    from cert_util import CertUtil
  File "D:\XX-Net-2.0.5\gae_proxy\local\cert_util.py", line 37, in <module>
    import OpenSSL
  File "D:\XX-Net-2.0.5\python27\1.0\lib\win32\OpenSSL\__init__.py", line 26, in
 <module>
    from OpenSSL import crypto, rand, SSL
  File "D:\XX-Net-2.0.5\python27\1.0\lib\win32\OpenSSL\crypto.py", line 11, in <
module>
    __bootstrap__()
  File "D:\XX-Net-2.0.5\python27\1.0\lib\win32\OpenSSL\crypto.py", line 3, in __
bootstrap__
    import _memimporter, sys
ImportError: No module named _memimporter

Aug 03 00:42:15 - [INFO] start gae_proxy time cost 13
Aug 03 00:42:16 - [INFO] get uuid:01468e95-051b-4405-8c02-c6f9da9d1d49
Aug 03 00:42:17 - [WARNING] check_update fail:URLError(error(10061, ''),)
Aug 03 00:42:17 - [INFO] download https://raw.githubusercontent.com/XX-net/XX-Ne
t/master/README.md to D:\XX-Net-2.0.5\data\downloads\README.md
Aug 03 00:42:18 - [ERROR] download https://raw.githubusercontent.com/XX-net/XX-N
et/master/README.md to D:\XX-Net-2.0.5\data\downloads\README.md fail:URLError(er
ror(10061, ''),)
Traceback (most recent call last):
  File "D:\XX-Net-2.0.5\launcher\update_from_github.py", line 64, in download_fi
le
    req = opener.open(url)
  File "D:\XX-Net-2.0.5\python27\1.0\lib\urllib2.py", line 404, in open
    response = self._open(req, data)
  File "D:\XX-Net-2.0.5\python27\1.0\lib\urllib2.py", line 422, in _open
    '_open', req)
  File "D:\XX-Net-2.0.5\python27\1.0\lib\urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "D:\XX-Net-2.0.5\python27\1.0\lib\urllib2.py", line 1222, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "D:\XX-Net-2.0.5\python27\1.0\lib\urllib2.py", line 1184, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 10061] >

Aug 03 00:42:18 - [ERROR] check_update fail:IOError('get README https://raw.gith
ubusercontent.com/XX-net/XX-Net/master/README.md fail:',)
Traceback (most recent call last):
  File "D:\XX-Net-2.0.5\launcher\update.py", line 241, in check_update
    versions = update_from_github.get_github_versions()
  File "D:\XX-Net-2.0.5\launcher\update_from_github.py", line 106, in get_github
_versions
    raise IOError("get README %s fail:" % readme_url)
IOError: get README https://raw.githubusercontent.com/XX-net/XX-Net/master/READM
E.md fail:

求帮助，谢谢！

**Comment by xxnet** [comment]
没找到特别的原因，试试重新下载一个干净的版本

2015-08-03 0:43 GMT+08:00 wsdyuuu <notifications@github.com>:
