### ISSUE TITLE
懂python语言的，帮我看看

### ISSUE THREAD

**Issue by sundaqing1969** [XX-net/XX-Net#7701]
Traceback (most recent call last):
  File "uploader.py", line 151, in <module>
  File "uploader.py", line 144, in main
  File "uploader.py", line 112, in upload
  File "D:\下载夹\goproxy-gae-r90\google_appengine\google\appengine\tools\appcfg
.py", line 5516, in main

上面的提示是什么意思，部署命令窗口的提示

**Comment by ghostzhao** [comment]
检查appid是否正确，如多个id 先用一个或者确认分割符号！如第一次上传 检查你填写的是否为appid ，gae有两个显示 只有一个能用 ，可以先填写xxnet-4测试下 英文符号全小写

**Comment by sundaqing1969** [comment]
提示来自goproxy的部署命令窗口，goproxy项目删除了，跑这里来问一下。
