### ISSUE TITLE
skype官网乱码

### ISSUE THREAD

**Issue by unccp** [XX-net/XX-Net#7884]
![qq 20171101164544](https://user-images.githubusercontent.com/32110483/32267010-af48081a-bf24-11e7-966c-faeb442cdaf0.png)

如图。
以前用agogent试过类似的情况，求解。

**Comment by cym104** [comment]
我用IE开任何有油管内容的网页，油管的部分都是这样。其他的浏览器都没问题。真奇怪。

**Comment by hzx505** [comment]
碰到 了。
safari v10 系统10.10.5 ，上YOUTUBE 同楼主一样
safari v11 系统10.11.6 ，上YOUTUBE 正常 不乱码

**Comment by hzx505** [comment]
再试了 上SKYPE 2个系统都正常

**Comment by Lovefish** [comment]
同样的情况...

**Comment by unccp** [comment]
更正：不是agogent，是goagent

**Comment by xxnet** [comment]
GAE​网站兼容性问题，请使用x-tunnel

**Comment by unccp** [comment]
@xxnet x-tunnel完全用不了

日志如下
Nov 02 11:53:16.747 - [INFO] use config_path:D:\XX-Net\data\x_tunnel\client.json
Nov 02 11:53:16.748 - [INFO] X-Tunnel window:33554432
Nov 02 11:53:16.748 - [INFO] Socks5 server listen:127.0.0.1:1080.
Nov 02 12:18:36.680 - [DEBUG] x_tunnel force update info
Nov 02 12:18:37.018 - [INFO] api:/login success t:337
Nov 02 12:18:37.018 - [INFO] update xt_server v8.xx-net.net:443
Nov 02 12:18:37.018 - [INFO] request_balance host:v8.xx-net.net port:443 balance:0.000000 quota:1149186150.000000
Nov 02 12:18:40.471 - [INFO] login_session hxxcbpid time:3453 msg:Success
Nov 02 12:18:40.894 - [DEBUG] x_tunnel force update info
Nov 02 12:18:41.252 - [INFO] api:/login success t:357
Nov 02 12:18:41.253 - [INFO] request_balance host:v8.xx-net.net port:443 balance:0.000000 quota:1149186150.000000
Nov 02 12:19:23.304 - [DEBUG] socks5 auth num:1, list:00
Nov 02 12:19:23.304 - [ERROR] socks5 protocol error:error('recv fail',)
Nov 02 12:19:23.305 - [ERROR] Except stack:Traceback (most recent call last): File "D:\XX-Net\code\3.7.7\x_tunnel\local\proxy_handler.py", line 163, in socks5_handler data = self.read_bytes(4) File "D:\XX-Net\code\3.7.7\x_tunnel\local\proxy_handler.py", line 106, in read_bytes raise socket.error("recv fail") error: recv fail
Nov 02 12:19:23.354 - [DEBUG] socks5 auth num:1, list:00
Nov 02 12:19:23.354 - [ERROR] socks5 protocol error:error('recv fail',)
Nov 02 12:19:23.354 - [ERROR] Except stack:Traceback (most recent call last): File "D:\XX-Net\code\3.7.7\x_tunnel\local\proxy_handler.py", line 163, in socks5_handler data = self.read_bytes(4) File "D:\XX-Net\code\3.7.7\x_tunnel\local\proxy_handler.py", line 106, in read_bytes raise socket.error("recv fail") error: recv fail
Nov 02 12:19:23.379 - [DEBUG] socks5 auth num:1, list:00
Nov 02 12:19:23.379 - [ERROR] socks5 protocol error:error('recv fail',)
Nov 02 12:19:23.379 - [ERROR] Except stack:Traceback (most recent call last): File "D:\XX-Net\code\3.7.7\x_tunnel\local\proxy_handler.py", line 163, in socks5_handler data = self.read_bytes(4) File "D:\XX-Net\code\3.7.7\x_tunnel\local\proxy_handler.py", line 106, in read_bytes raise socket.error("recv fail") error: recv fail
Nov 02 12:19:24.316 - [DEBUG] socks5 auth num:1, list:00
Nov 02 12:19:24.316 - [ERROR] socks5 protocol error:error('recv fail',)
Nov 02 12:19:24.316 - [ERROR] Except stack:Traceback (most recent call last): File "D:\XX-Net\code\3.7.7\x_tunnel\local\proxy_handler.py", line 163, in socks5_handler data = self.read_bytes(4) File "D:\XX-Net\code\3.7.7\x_tunnel\local\proxy_handler.py", line 106, in read_bytes raise socket.error("recv fail") error: recv fail
Nov 02 12:19:25.740 - [DEBUG] socks5 auth num:1, list:00
Nov 02 12:19:25.740 - [ERROR] socks5 protocol error:error('recv fail',)
Nov 02 12:19:25.740 - [ERROR] Except stack:Traceback (most recent call last): File "D:\XX-Net\code\3.7.7\x_tunnel\local\proxy_handler.py", line 163, in socks5_handler data = self.read_bytes(4) File "D:\XX-Net\code\3.7.7\x_tunnel\local\proxy_handler.py", line 106, in read_bytes raise socket.error("recv fail") error: recv fail
Nov 02 12:19:32.583 - [DEBUG] socks5 auth num:1, list:00
Nov 02 12:19:32.583 - [ERROR] socks5 protocol error:error('recv fail',)
Nov 02 12:19:32.584 - [ERROR] Except stack:Traceback (most recent call last): File "D:\XX-Net\code\3.7.7\x_tunnel\local\proxy_handler.py", line 163, in socks5_handler data = self.read_bytes(4) File "D:\XX-Net\code\3.7.7\x_tunnel\local\proxy_handler.py", line 106, in read_bytes raise socket.error("recv fail") error: recv fail
Nov 02 12:19:33.361 - [DEBUG] socks5 auth num:1, list:00
Nov 02 12:19:33.361 - [ERROR] socks5 protocol error:error('recv fail',)
Nov 02 12:19:33.361 - [ERROR] Except stack:Traceback (most recent call last): File "D:\XX-Net\code\3.7.7\x_tunnel\local\proxy_handler.py", line 163, in socks5_handler data = self.read_bytes(4) File "D:\XX-Net\code\3.7.7\x_tunnel\local\proxy_handler.py", line 106, in read_bytes raise socket.error("recv fail") error: recv fail
Nov 02 12:20:28.888 - [DEBUG] socks5 auth num:1, list:00
Nov 02 12:20:28.888 - [ERROR] socks5 protocol error:error('recv fail',)
Nov 02 12:20:28.888 - [ERROR] Except stack:Traceback (most recent call last): File "D:\XX-Net\code\3.7.7\x_tunnel\local\proxy_handler.py", line 163, in socks5_handler data = self.read_bytes(4) File "D:\XX-Net\code\3.7.7\x_tunnel\local\proxy_handler.py", line 106, in read_bytes raise socket.error("recv fail") error: recv fail
Nov 02 12:20:30.633 - [DEBUG] socks5 auth num:1, list:00
Nov 02 12:20:30.633 - [ERROR] socks5 protocol error:error('recv fail',)
Nov 02 12:20:30.634 - [ERROR] Except stack:Traceback (most recent call last): File "D:\XX-Net\code\3.7.7\x_tunnel\local\proxy_handler.py", line 163, in socks5_handler data = self.read_bytes(4) File "D:\XX-Net\code\3.7.7\x_tunnel\local\proxy_handler.py", line 106, in read_bytes raise socket.error("recv fail") error: recv fail
Nov 02 12:20:31.025 - [DEBUG] socks5 auth num:1, list:00
Nov 02 12:20:31.025 - [ERROR] socks5 protocol error:error('recv fail',)
Nov 02 12:20:31.025 - [ERROR] Except stack:Traceback (most recent call last): File "D:\XX-Net\code\3.7.7\x_tunnel\local\proxy_handler.py", line 163, in socks5_handler data = self.read_bytes(4) File "D:\XX-Net\code\3.7.7\x_tunnel\local\proxy_handler.py", line 106, in read_bytes raise socket.error("recv fail") error: recv fail
Nov 02 12:20:58.987 - [DEBUG] socks5 auth num:1, list:00
Nov 02 12:20:58.987 - [ERROR] socks5 protocol error:error('recv fail',)
Nov 02 12:20:58.988 - [ERROR] Except stack:Traceback (most recent call last): File "D:\XX-Net\code\3.7.7\x_tunnel\local\proxy_handler.py", line 163, in socks5_handler data = self.read_bytes(4) File "D:\XX-Net\code\3.7.7\x_tunnel\local\proxy_handler.py", line 106, in read_bytes raise socket.error("recv fail") error: recv fail
Nov 02 12:21:07.659 - [DEBUG] socks5 auth num:1, list:00
Nov 02 12:21:07.659 - [ERROR] socks5 protocol error:error('recv fail',)
Nov 02 12:21:07.659 - [ERROR] Except stack:Traceback (most recent call last): File "D:\XX-Net\code\3.7.7\x_tunnel\local\proxy_handler.py", line 163, in socks5_handler data = self.read_bytes(4) File "D:\XX-Net\code\3.7.7\x_tunnel\local\proxy_handler.py", line 106, in read_bytes raise socket.error("recv fail") error: recv fail@xxnet x-tunnel完全用不了

日志如下
Nov 02 11:53:16.747 - [INFO] use config_path:D:\XX-Net\data\x_tunnel\client.json
Nov 02 11:53:16.748 - [INFO] X-Tunnel window:33554432
Nov 02 11:53:16.748 - [INFO] Socks5 server listen:127.0.0.1:1080.
Nov 02 12:18:36.680 - [DEBUG] x_tunnel force update info
Nov 02 12:18:37.018 - [INFO] api:/login success t:337
Nov 02 12:18:37.018 - [INFO] update xt_server v8.xx-net.net:443
Nov 02 12:18:37.018 - [INFO] request_balance host:v8.xx-net.net port:443 balance:0.000000 quota:1149186150.000000
Nov 02 12:18:40.471 - [INFO] login_session hxxcbpid time:3453 msg:Success
Nov 02 12:18:40.894 - [DEBUG] x_tunnel force update info
Nov 02 12:18:41.252 - [INFO] api:/login success t:357
Nov 02 12:18:41.253 - [INFO] request_balance host:v8.xx-net.net port:443 balance:0.000000 quota:1149186150.000000
Nov 02 12:19:23.304 - [DEBUG] socks5 auth num:1, list:00
Nov 02 12:19:23.304 - [ERROR] socks5 protocol error:error('recv fail',)
Nov 02 12:19:23.305 - [ERROR] Except stack:Traceback (most recent call last): File "D:\XX-Net\code\3.7.7\x_tunnel\local\proxy_handler.py", line 163, in socks5_handler data = self.read_bytes(4) File "D:\XX-Net\code\3.7.7\x_tunnel\local\proxy_handler.py", line 106, in read_bytes raise socket.error("recv fail") error: recv fail
Nov 02 12:19:23.354 - [DEBUG] socks5 auth num:1, list:00
Nov 02 12:19:23.354 - [ERROR] socks5 protocol error:error('recv fail',)
Nov 02 12:19:23.354 - [ERROR] Except stack:Traceback (most recent call last): File "D:\XX-Net\code\3.7.7\x_tunnel\local\proxy_handler.py", line 163, in socks5_handler data = self.read_bytes(4) File "D:\XX-Net\code\3.7.7\x_tunnel\local\proxy_handler.py", line 106, in read_bytes raise socket.error("recv fail") error: recv fail
Nov 02 12:19:23.379 - [DEBUG] socks5 auth num:1, list:00
Nov 02 12:19:23.379 - [ERROR] socks5 protocol error:error('recv fail',)
Nov 02 12:19:23.379 - [ERROR] Except stack:Traceback (most recent call last): File "D:\XX-Net\code\3.7.7\x_tunnel\local\proxy_handler.py", line 163, in socks5_handler data = self.read_bytes(4) File "D:\XX-Net\code\3.7.7\x_tunnel\local\proxy_handler.py", line 106, in read_bytes raise socket.error("recv fail") error: recv fail
Nov 02 12:19:24.316 - [DEBUG] socks5 auth num:1, list:00
Nov 02 12:19:24.316 - [ERROR] socks5 protocol error:error('recv fail',)
Nov 02 12:19:24.316 - [ERROR] Except stack:Traceback (most recent call last): File "D:\XX-Net\code\3.7.7\x_tunnel\local\proxy_handler.py", line 163, in socks5_handler data = self.read_bytes(4) File "D:\XX-Net\code\3.7.7\x_tunnel\local\proxy_handler.py", line 106, in read_bytes raise socket.error("recv fail") error: recv fail
Nov 02 12:19:25.740 - [DEBUG] socks5 auth num:1, list:00
Nov 02 12:19:25.740 - [ERROR] socks5 protocol error:error('recv fail',)
Nov 02 12:19:25.740 - [ERROR] Except stack:Traceback (most recent call last): File "D:\XX-Net\code\3.7.7\x_tunnel\local\proxy_handler.py", line 163, in socks5_handler data = self.read_bytes(4) File "D:\XX-Net\code\3.7.7\x_tunnel\local\proxy_handler.py", line 106, in read_bytes raise socket.error("recv fail") error: recv fail
Nov 02 12:19:32.583 - [DEBUG] socks5 auth num:1, list:00
Nov 02 12:19:32.583 - [ERROR] socks5 protocol error:error('recv fail',)
Nov 02 12:19:32.584 - [ERROR] Except stack:Traceback (most recent call last): File "D:\XX-Net\code\3.7.7\x_tunnel\local\proxy_handler.py", line 163, in socks5_handler data = self.read_bytes(4) File "D:\XX-Net\code\3.7.7\x_tunnel\local\proxy_handler.py", line 106, in read_bytes raise socket.error("recv fail") error: recv fail
Nov 02 12:19:33.361 - [DEBUG] socks5 auth num:1, list:00
Nov 02 12:19:33.361 - [ERROR] socks5 protocol error:error('recv fail',)
Nov 02 12:19:33.361 - [ERROR] Except stack:Traceback (most recent call last): File "D:\XX-Net\code\3.7.7\x_tunnel\local\proxy_handler.py", line 163, in socks5_handler data = self.read_bytes(4) File "D:\XX-Net\code\3.7.7\x_tunnel\local\proxy_handler.py", line 106, in read_bytes raise socket.error("recv fail") error: recv fail
Nov 02 12:20:28.888 - [DEBUG] socks5 auth num:1, list:00
Nov 02 12:20:28.888 - [ERROR] socks5 protocol error:error('recv fail',)
Nov 02 12:20:28.888 - [ERROR] Except stack:Traceback (most recent call last): File "D:\XX-Net\code\3.7.7\x_tunnel\local\proxy_handler.py", line 163, in socks5_handler data = self.read_bytes(4) File "D:\XX-Net\code\3.7.7\x_tunnel\local\proxy_handler.py", line 106, in read_bytes raise socket.error("recv fail") error: recv fail
Nov 02 12:20:30.633 - [DEBUG] socks5 auth num:1, list:00
Nov 02 12:20:30.633 - [ERROR] socks5 protocol error:error('recv fail',)
Nov 02 12:20:30.634 - [ERROR] Except stack:Traceback (most recent call last): File "D:\XX-Net\code\3.7.7\x_tunnel\local\proxy_handler.py", line 163, in socks5_handler data = self.read_bytes(4) File "D:\XX-Net\code\3.7.7\x_tunnel\local\proxy_handler.py", line 106, in read_bytes raise socket.error("recv fail") error: recv fail
Nov 02 12:20:31.025 - [DEBUG] socks5 auth num:1, list:00
Nov 02 12:20:31.025 - [ERROR] socks5 protocol error:error('recv fail',)
Nov 02 12:20:31.025 - [ERROR] Except stack:Traceback (most recent call last): File "D:\XX-Net\code\3.7.7\x_tunnel\local\proxy_handler.py", line 163, in socks5_handler data = self.read_bytes(4) File "D:\XX-Net\code\3.7.7\x_tunnel\local\proxy_handler.py", line 106, in read_bytes raise socket.error("recv fail") error: recv fail
Nov 02 12:20:58.987 - [DEBUG] socks5 auth num:1, list:00
Nov 02 12:20:58.987 - [ERROR] socks5 protocol error:error('recv fail',)
Nov 02 12:20:58.988 - [ERROR] Except stack:Traceback (most recent call last): File "D:\XX-Net\code\3.7.7\x_tunnel\local\proxy_handler.py", line 163, in socks5_handler data = self.read_bytes(4) File "D:\XX-Net\code\3.7.7\x_tunnel\local\proxy_handler.py", line 106, in read_bytes raise socket.error("recv fail") error: recv fail
Nov 02 12:21:07.659 - [DEBUG] socks5 auth num:1, list:00
Nov 02 12:21:07.659 - [ERROR] socks5 protocol error:error('recv fail',)
Nov 02 12:21:07.659 - [ERROR] Except stack:Traceback (most recent call last): File "D:\XX-Net\code\3.7.7\x_tunnel\local\proxy_handler.py", line 163, in socks5_handler data = self.read_bytes(4) File "D:\XX-Net\code\3.7.7\x_tunnel\local\proxy_handler.py", line 106, in read_bytes raise socket.error("recv fail") error: recv fail

**Comment by xxnet** [comment]
​你设置socks5 代理时，是不是填了用户名密码了？
不要填用户名密码

**Comment by xxnet** [comment]
@uuccp
 你上面的日志，是什么浏览器访问的？
 试试设置为http代理，端口还是1080

**Comment by unccp** [comment]
@xxnet 
我用的是google浏览器，用的代理软件SwitchyOmega，配置是安装xx-net的时候导入的，没修改过。
![11111111111](https://user-images.githubusercontent.com/32110483/32358404-c2967016-c080-11e7-9de8-144d9291a1af.png)
日志是xx-net配置页里面的截图
![22222](https://user-images.githubusercontent.com/32110483/32358407-cc884f5e-c080-11e7-9a14-f8a1704ddca0.png)
流量也是有的
![222222](https://user-images.githubusercontent.com/32110483/32358411-d4560b0e-c080-11e7-930b-d72bba71e712.png)

**Comment by unccp** [comment]
@xxnet
![111](https://user-images.githubusercontent.com/32110483/32358451-35e4caae-c081-11e7-9f46-b304891862b2.png)
