### ISSUE TITLE
Mac： No module named Foundation

### ISSUE THREAD

**Issue by koalaroot** [XX-net/XX-Net#79]
Mac OS X 10.10.2

运行start.command

反馈如下：

Traceback (most recent call last):
  File "/Volumes/Macintosh HD 2/Program Files/XX-Net-1.3.6/launcher/1.0.8/start.py", line 20, in <module>
    from mac_tray import sys_tray
  File "/Volumes/Macintosh HD 2/Program Files/XX-Net-1.3.6/launcher/1.0.8/mac_tray.py", line 15, in <module>
    import rumps
  File "/Volumes/Macintosh HD 2/Program Files/XX-Net-1.3.6/python27/1.0/lib/osx/rumps/__init__.py", line 25, in <module>
    from .rumps import (separator, debug_mode, alert, notification, application_support, timers, quit_application, timer,
  File "/Volumes/Macintosh HD 2/Program Files/XX-Net-1.3.6/python27/1.0/lib/osx/rumps/rumps.py", line 15, in <module>
    from Foundation import (NSDate, NSTimer, NSRunLoop, NSDefaultRunLoopMode, NSSearchPathForDirectoriesInDomains,
ImportError: No module named Foundation
logout

**Comment by xxnet** [comment]
请google "ImportError: No module named Foundation"

第一个文章下面提到 python 2.7 的处理方法：
 export .....的那一行就好了。

我下一个版本解决。

2015-03-23 10:19 GMT-04:00 koalaroot <notifications@github.com>:

**Comment by lifeva** [comment]
另有建议，托盘图标就不要显示文字了，视觉感受比较差。另外是否显示托盘图标，最好可配置。

**Comment by xxnet** [comment]
恩，正在考虑如何优化，谢谢反馈。

在 2015年3月24日 下午9:21，lifeva <notifications@github.com>写道：

**Comment by koalaroot** [comment]
1.4.1

Traceback (most recent call last):
  File "/Volumes/Macintosh HD 2/Program Files/XX-Net-1.4.1/launcher/1.0.9/start.py", line 25, in <module>
    from mac_tray import sys_tray
  File "/Volumes/Macintosh HD 2/Program Files/XX-Net-1.4.1/launcher/1.0.9/mac_tray.py", line 15, in <module>
    import rumps
  File "/Volumes/Macintosh HD 2/Program Files/XX-Net-1.4.1/python27/1.0/lib/darwin/rumps/__init__.py", line 25, in <module>
    from .rumps import (separator, debug_mode, alert, notification, application_support, timers, quit_application, timer,
  File "/Volumes/Macintosh HD 2/Program Files/XX-Net-1.4.1/python27/1.0/lib/darwin/rumps/rumps.py", line 15, in <module>
    from Foundation import (NSDate, NSTimer, NSRunLoop, NSDefaultRunLoopMode, NSSearchPathForDirectoriesInDomains,
ImportError: No module named Foundation
logout

**Comment by xxnet** [comment]
请问是什么操作版本？

ImportError: No module named Foundation
 缺乏包含一个库路径：
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python
代码中已经处理了，估计还有问题。

你看看是否存在这个路径；

再试试
打开命令行，执行
export
PYTHONPATH="/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/"
然后到XX-Net目录启动start.sh

参考：
http://stackoverflow.com/questions/1614648/importerror-no-module-named-foundation

请反馈问题有没有解决，好在下一个版本中处理，谢谢。


2015-03-29 9:08 GMT-04:00 koalaroot <notifications@github.com>:

**Comment by xxnet** [comment]
有遇到同样问题未解决的朋友，请帮忙提供以下信息：
find /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/ 
把信息发出来，帮助分析。

如果内容太多，可以：
find /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/ > ~/ lib.txt
让后把用户目录下的lib.txt作为附件贴上来，或发我邮箱： xxnet.dev@gmail.com
谢谢

**Comment by xxnet** [comment]
有遇到同样问题未解决的朋友，请帮忙提供以下信息：
find /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/ 
把信息发出来，帮助分析。

如果内容太多，可以：
find /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/ > ~/ lib.txt
让后把用户目录下的lib.txt作为附件贴上来，或发我邮箱： xxnet.dev@gmail.com
谢谢

**Comment by xxnet** [comment]
1.8.1 发布
重构了Mac下的托盘实现，不再依赖 Foundation模块

请测试
