### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by BigBigWolf** [XX-net/XX-Net#7918]
日志如下：
Exception in thread Thread-510:
Traceback (most recent call last):
  File "D:\Program\XX-Net\code\3.7.8\python27\1.0\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "D:\Program\XX-Net\code\3.7.8\python27\1.0\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "D:\Program\XX-Net\code\3.7.8\gae_proxy\local\google_ip.py", line 652, in scan_ip_worker
    xlog.exception("google_ip.runJob fail:%r", e)
AttributeError: 'NoneType' object has no attribute 'exception'

**Comment by xxnet** [comment]
​试试重新下载一个，怀疑下载不完整
