### ISSUE TITLE
配置更新后，xx-net无法再打开

### ISSUE THREAD

**Issue by NARUTONBM** [XX-net/XX-Net#8204]
之前是3.7.9，点击更新后，点快捷键无法打开，点击start.bat，出现红色错误信息。
Nov 10 01:31:41.037 [launcher][INFO] use build-in openssl lib
Nov 10 01:31:41.038 [launcher][INFO] start XX-Net 3.7.15
Nov 10 01:31:41.039 [launcher][DEBUG] start confirm_xxnet_exit
Nov 10 01:31:42.052 [launcher][DEBUG] good, xxnet:8087 cleared!
Nov 10 01:31:43.055 [launcher][DEBUG] good, xxnet:8085 clear!
Nov 10 01:31:43.055 [launcher][DEBUG] finished confirm_xxnet_exit
Nov 10 01:31:43.098 [launcher][ERROR] start module gae_proxy fail:invalid literal for int() with base 10: '9117110vfyl,.'
Nov 10 01:31:43.102 [launcher][ERROR] Except stack:Traceback (most recent call last):
  File "C:\Foreign-Software\XX-Net\code\3.7.15\launcher\module_init.py", line 38, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "C:\Foreign-Software\XX-Net\code\3.7.15\gae_proxy\start.py", line 13, in <module>
    import local.proxy as client
  File "C:\Foreign-Software\XX-Net\code\3.7.15\gae_proxy\local\proxy.py", line 97, in <module>
    import proxy_handler
  File "C:\Foreign-Software\XX-Net\code\3.7.15\gae_proxy\local\proxy_handler.py", line 54, in <module>
    import gae_handler
  File "C:\Foreign-Software\XX-Net\code\3.7.15\gae_proxy\local\gae_handler.py", line 75, in <module>
    from appids_manager import appid_manager
  File "C:\Foreign-Software\XX-Net\code\3.7.15\gae_proxy\local\appids_manager.py", line 11, in <module>
    import check_ip
  File "C:\Foreign-Software\XX-Net\code\3.7.15\gae_proxy\local\check_ip.py", line 51, in <module>
    import check_local_network
  File "C:\Foreign-Software\XX-Net\code\3.7.15\gae_proxy\local\check_local_network.py", line 139, in <module>
    IPv4 = CheckNetwork("IPv4")
  File "C:\Foreign-Software\XX-Net\code\3.7.15\gae_proxy\local\check_local_network.py", line 50, in __init__
    self.http_client = simple_http_client.Client(self.proxy, timeout=30)
  File "C:\Foreign-Software\XX-Net\code\3.7.15\python27\1.0\lib\noarch\simple_http_client.py", line 483, in __init__
    "port": proxy_sp.port,
  File "C:\Foreign-Software\XX-Net\code\3.7.15\python27\1.0\lib\urlparse.py", line 113, in port
    port = int(port, 10)
ValueError: invalid literal for int() with base 10: '9117110vfyl,.'

Nov 10 01:31:43.103 [launcher][ERROR] launcher except:ValueError("invalid literal for int() with base 10: '9117110vfyl,.'",)
Nov 10 01:31:43.104 [launcher][ERROR] Except stack:Traceback (most recent call last):
  File "C:\Foreign-Software\XX-Net\code\3.7.15\launcher\start.py", line 221, in <module>
    main()
  File "C:\Foreign-Software\XX-Net\code\3.7.15\launcher\start.py", line 198, in main
    module_init.start_all_auto()
  File "C:\Foreign-Software\XX-Net\code\3.7.15\launcher\module_init.py", line 99, in start_all_auto
    start(module)
  File "C:\Foreign-Software\XX-Net\code\3.7.15\launcher\module_init.py", line 38, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "C:\Foreign-Software\XX-Net\code\3.7.15\gae_proxy\start.py", line 13, in <module>
    import local.proxy as client
  File "C:\Foreign-Software\XX-Net\code\3.7.15\gae_proxy\local\proxy.py", line 97, in <module>
    import proxy_handler
  File "C:\Foreign-Software\XX-Net\code\3.7.15\gae_proxy\local\proxy_handler.py", line 54, in <module>
    import gae_handler
  File "C:\Foreign-Software\XX-Net\code\3.7.15\gae_proxy\local\gae_handler.py", line 75, in <module>
    from appids_manager import appid_manager
  File "C:\Foreign-Software\XX-Net\code\3.7.15\gae_proxy\local\appids_manager.py", line 11, in <module>
    import check_ip
  File "C:\Foreign-Software\XX-Net\code\3.7.15\gae_proxy\local\check_ip.py", line 51, in <module>
    import check_local_network
  File "C:\Foreign-Software\XX-Net\code\3.7.15\gae_proxy\local\check_local_network.py", line 139, in <module>
    IPv4 = CheckNetwork("IPv4")
  File "C:\Foreign-Software\XX-Net\code\3.7.15\gae_proxy\local\check_local_network.py", line 50, in __init__
    self.http_client = simple_http_client.Client(self.proxy, timeout=30)
  File "C:\Foreign-Software\XX-Net\code\3.7.15\python27\1.0\lib\noarch\simple_http_client.py", line 483, in __init__
    "port": proxy_sp.port,
  File "C:\Foreign-Software\XX-Net\code\3.7.15\python27\1.0\lib\urlparse.py", line 113, in port
    port = int(port, 10)
ValueError: invalid literal for int() with base 10: '9117110vfyl,.'

**Comment by gjbg1989** [comment]
自动升级失败，官网下载解压。。。
