### ISSUE TITLE
Macbook 10.10.2  XX-net 1.4.0

### ISSUE THREAD

**Issue by yiluheihei** [XX-net/XX-Net#83]
Traceback (most recent call last):
  File "/Users/caoyang/Downloads/app/网络/XX-Net-1.4.0/launcher/1.0.9/start.py", line 86, in <module>
    main()
  File "/Users/caoyang/Downloads/app/网络/XX-Net-1.4.0/launcher/1.0.9/start.py", line 63, in main
    web_control.start()
  File "/Users/caoyang/Downloads/app/网络/XX-Net-1.4.0/launcher/1.0.9/web_control.py", line 269, in start
    server = LocalServer(("127.0.0.1", 8085), Http_Handler)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 419, in __init__
    self.server_bind()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 430, in server_bind
    self.socket.bind(self.server_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 48] Address already in use
Stopping all modules before exit!
Mar 28 23:03:34 - [INFO] module goagent stopped
logout

[进程已完成]

**Comment by xxnet** [comment]
这提示是端口被占用了。
解决方法是三条命令：sudo -s 输入密码得权限，lsof -i:8087 得到占用8087端口Python的KID号，例如：python
YYY，最后输入kill YYY，端口释放。不放心？再重新 lsof -i:8087 一下，看python还有没有。



2015-03-28 11:04 GMT-04:00 yang <notifications@github.com>:

**Comment by yiluheihei** [comment]
谢谢你的帮助，但是我试了下  貌似还是不行 
bash-3.2# lsof -i:8087
COMMAND  PID USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
Python  8906 root    7u  IPv4 0xee64545f98c2f07d      0t0  TCP localhost:8087 (LISTEN)
bash-3.2# kill 8976
bash: kill: (8976) - No such process
bash-3.2# kill 8906
bash-3.2# lsof -i:8087
COMMAND  PID USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
Python  8933 root    7u  IPv4 0xee64545f99f086fd      0t0  TCP localhost:8087 (LISTEN)
bash-3.2# 

貌似每次再lsof -i:8087都还显示在占用

**Comment by xxnet** [comment]
看看python的进程，全部kill试试：
 ps aux |grep -i python

然后kill -9 $pid看看

2015-04-03 6:28 GMT-04:00 yang <notifications@github.com>:

**Comment by l1000x** [comment]
果然是8087端口被占用了,关闭相应程序后好了
