### ISSUE TITLE
XX-Net1.40无法运行Mac 10.10.2

### ISSUE THREAD

**Issue by cncyk06** [XX-net/XX-Net#84]
点击start.command无法运行，提示：IOError: [Errno 13] Permission denied: '/Users/caca/Desktop/XX-Net-master/data/launcher/log.log
本人对电脑完全不懂，求解答。
感谢作者的付出
ps：按照百度所说已经进行sudo chmod 777 *.command或文件夹  以赋予权限，无效
1.3.6版本依旧可以使用

以下附上部分操作提示
yingkangdeMacBook-Pro:~ caca$ sudo python /Users/caca/Desktop/XX-Net-master/launcher/start.py 
Traceback (most recent call last):
  File "/Users/caca/Desktop/XX-Net-master/launcher/1.0.9/start.py", line 25, in <module>
    from mac_tray import sys_tray
  File "/Users/caca/Desktop/XX-Net-master/launcher/1.0.9/mac_tray.py", line 86, in <module>
    sys_tray = Mac_tray()
  File "/Users/caca/Desktop/XX-Net-master/launcher/1.0.9/mac_tray.py", line 23, in __init__
    super(Mac_tray, self).__init__("XX-Net", title="XX-Net", icon="Python.ico", quit_button=None)
  File "/Users/caca/Desktop/XX-Net-master/python27/1.0/lib/darwin/rumps/rumps.py", line 923, in __init__
    self._application_support = application_support(self._name)
  File "/Users/caca/Desktop/XX-Net-master/python27/1.0/lib/darwin/rumps/rumps.py", line 107, in application_support
    os.mkdir(app_support_path)
OSError: [Errno 2] No such file or directory: '/var/root/Library/Application Support/XX-Net'

yingkangdeMacBook-Pro:~ caca$ python /Users/caca/Desktop/XX-Net-master/launcher/start.py 
Traceback (most recent call last):
  File "/Users/caca/Desktop/XX-Net-master/launcher/1.0.9/start.py", line 25, in <module>
    from mac_tray import sys_tray
  File "/Users/caca/Desktop/XX-Net-master/launcher/1.0.9/mac_tray.py", line 17, in <module>
    import module_init
  File "/Users/caca/Desktop/XX-Net-master/launcher/1.0.9/module_init.py", line 2, in <module>
    import logging
  File "/Users/caca/Desktop/XX-Net-master/launcher/1.0.9/logging.py", line 41, in <module>
    log_fd = open(log_path, "a")
IOError: [Errno 13] Permission denied: '/Users/caca/Desktop/XX-Net-master/data/launcher/log.log'

**Comment by xxnet** [comment]
chmod -R 777 /Users/caca/Desktop/XX-Net-master/

-R能够修改所有的目录和文件

2015-03-28 13:14 GMT-04:00 cncyk06 <notifications@github.com>:
