### ISSUE TITLE
GAE能用，但是X-Tunnel连不上

### ISSUE THREAD

**Issue by gracias0427** [XX-net/XX-Net#8401]
我购买了X-Tunnel套餐，发现GAE正常使用，但是切换用X-Tunnel现在完全连不上网络

Global

Property | Value
-- | --
Server listen address | SOCKS5://127.0.0.1:1080
Handle num | 265
Response time | 7220
Roundtrip num | 2624
Slow roundtrip | 40
Timeout roundtrip | 24
Speed | Up: 0.0 B/s / Down: 0.0 B/s
Total use | Up: 783.9 KB / Down: 9.1 MB

GAE front

Property | Value
-- | --
Score | 344
Success num | 2202
Fail num | 119
Worker num | 60
Total use | Up: 716.7 KB / Down: 7.5 MB

Cloudflare front

Property | Value
-- | --
Score | False
Success num | 29
Fail num | 108
Worker num | 0
Total use | Up: 1.8 KB / Down: 83.7 KB

Heroku front

Property | Value
-- | --
Score | False
Success num | 630
Fail num | 0
Worker num | 0
Total use | Up: 65.3 KB / Down: 1.6 MB

日志
Nov 16 19:33:52.180 - [WARNING] roundtrip time:15256 transfer_no:8 send_sn:8 send:531 status:601 retry:2
Nov 16 19:33:52.809 - [ERROR] request except:KeyError(24,) retry 7
Nov 16 19:33:52.809 - [ERROR] request except:KeyError(27,) retry 2
Nov 16 19:33:52.809 - [ERROR] request except:KeyError(28,) retry 2
Nov 16 19:33:52.810 - [ERROR] Except stack:Traceback (most recent call last): File "E:\install\XX-Net-3.3.0\code\3.7.16\x_tunnel\local\proxy_session.py", line 362, in normal_roundtrip_worker self.transfer_list[transfer_no]["try"] = try_no KeyError: 24
Nov 16 19:33:52.810 - [ERROR] Except stack:Traceback (most recent call last): File "E:\install\XX-Net-3.3.0\code\3.7.16\x_tunnel\local\proxy_session.py", line 362, in normal_roundtrip_worker self.transfer_list[transfer_no]["try"] = try_no KeyError: 27
Nov 16 19:33:52.810 - [ERROR] Except stack:Traceback (most recent call last): File "E:\install\XX-Net-3.3.0\code\3.7.16\x_tunnel\local\proxy_session.py", line 362, in normal_roundtrip_worker self.transfer_list[transfer_no]["try"] = try_no KeyError: 28
Nov 16 19:33:52.812 - [ERROR] request except:KeyError(30,) retry 2
Nov 16 19:33:52.812 - [ERROR] Except stack:Traceback (most recent call last): File "E:\install\XX-Net-3.3.0\code\3.7.16\x_tunnel\local\proxy_session.py", line 362, in normal_roundtrip_worker self.transfer_list[transfer_no]["try"] = try_no KeyError: 30
Nov 16 19:33:52.813 - [ERROR] request except:KeyError(35,) retry 2
Nov 16 19:33:52.813 - [ERROR] request except:KeyError(37,) retry 2
Nov 16 19:33:52.813 - [ERROR] request except:KeyError(33,) retry 2
Nov 16 19:33:52.813 - [ERROR] request except:KeyError(34,) retry 2
Nov 16 19:33:52.814 - [ERROR] request except:KeyError(32,) retry 2
Nov 16 19:33:52.814 - [ERROR] request except:KeyError(31,) retry 2
Nov 16 19:33:52.814 - [ERROR] request except:KeyError(36,) retry 2
Nov 16 19:33:52.815 - [ERROR] Except stack:Traceback (most recent call last): File "E:\install\XX-Net-3.3.0\code\3.7.16\x_tunnel\local\proxy_session.py", line 362, in normal_roundtrip_worker self.transfer_list[transfer_no]["try"] = try_no KeyError: 35
Nov 16 19:33:52.815 - [ERROR] Except stack:Traceback (most recent call last): File "E:\install\XX-Net-3.3.0\code\3.7.16\x_tunnel\local\proxy_session.py", line 362, in normal_roundtrip_worker self.transfer_list[transfer_no]["try"] = try_no KeyError: 37
Nov 16 19:33:52.816 - [ERROR] Except stack:Traceback (most recent call last): File "E:\install\XX-Net-3.3.0\code\3.7.16\x_tunnel\local\proxy_session.py", line 362, in normal_roundtrip_worker self.transfer_list[transfer_no]["try"] = try_no KeyError: 33
Nov 16 19:33:52.816 - [ERROR] Except stack:Traceback (most recent call last): File "E:\install\XX-Net-3.3.0\code\3.7.16\x_tunnel\local\proxy_session.py", line 362, in normal_roundtrip_worker self.transfer_list[transfer_no]["try"] = try_no KeyError: 34
Nov 16 19:33:52.816 - [ERROR] Except stack:Traceback (most recent call last): File "E:\install\XX-Net-3.3.0\code\3.7.16\x_tunnel\local\proxy_session.py", line 362, in normal_roundtrip_worker self.transfer_list[transfer_no]["try"] = try_no KeyError: 32
Nov 16 19:33:52.816 - [ERROR] Except stack:Traceback (most recent call last): File "E:\install\XX-Net-3.3.0\code\3.7.16\x_tunnel\local\proxy_session.py", line 362, in normal_roundtrip_worker self.transfer_list[transfer_no]["try"] = try_no KeyError: 31
Nov 16 19:33:52.817 - [ERROR] Except stack:Traceback (most recent call last): File "E:\install\XX-Net-3.3.0\code\3.7.16\x_tunnel\local\proxy_session.py", line 362, in normal_roundtrip_worker self.transfer_list[transfer_no]["try"] = try_no KeyError: 36
Nov 16 19:33:53.176 - [ERROR] request except:KeyError(40,) retry 2
Nov 16 19:33:53.176 - [ERROR] Except stack:Traceback (most recent call last): File "E:\install\XX-Net-3.3.0\code\3.7.16\x_tunnel\local\proxy_session.py", line 362, in normal_roundtrip_worker self.transfer_list[transfer_no]["try"] = try_no KeyError: 40
Nov 16 19:33:53.178 - [ERROR] request except:KeyError(43,) retry 2
Nov 16 19:33:53.178 - [ERROR] request except:KeyError(41,) retry 2
Nov 16 19:33:53.178 - [ERROR] Except stack:Traceback (most recent call last): File "E:\install\XX-Net-3.3.0\code\3.7.16\x_tunnel\local\proxy_session.py", line 362, in normal_roundtrip_worker self.transfer_list[transfer_no]["try"] = try_no KeyError: 43
Nov 16 19:33:53.178 - [ERROR] Except stack:Traceback (most recent call last): File "E:\install\XX-Net-3.3.0\code\3.7.16\x_tunnel\local\proxy_session.py", line 362, in normal_roundtrip_worker self.transfer_list[transfer_no]["try"] = try_no KeyError: 41
Nov 16 19:33:53.179 - [ERROR] request except:KeyError(42,) retry 2
Nov 16 19:33:53.179 - [ERROR] request except:KeyError(44,) retry 2
Nov 16 19:33:53.179 - [ERROR] Except stack:Traceback (most recent call last): File "E:\install\XX-Net-3.3.0\code\3.7.16\x_tunnel\local\proxy_session.py", line 362, in normal_roundtrip_worker self.transfer_list[transfer_no]["try"] = try_no KeyError: 42
Nov 16 19:33:53.179 - [ERROR] Except stack:Traceback (most recent call last): File "E:\install\XX-Net-3.3.0\code\3.7.16\x_tunnel\local\proxy_session.py", line 362, in normal_roundtrip_worker self.transfer_list[transfer_no]["try"] = try_no KeyError: 44
Nov 16 19:33:54.181 - [ERROR] request except:KeyError(8,) retry 3
Nov 16 19:33:54.181 - [ERROR] Except stack:Traceback (most recent call last): File "E:\install\XX-Net-3.3.0\code\3.7.16\x_tunnel\local\proxy_session.py", line 362, in normal_roundtrip_worker self.transfer_list[transfer_no]["try"] = try_no KeyError: 8
Nov 16 19:33:56.728 - [DEBUG] roundtrip time:12226 cost:5006 transfer_no:47 send_sn:47 send:34 recv_sn:0 rcv:11 status:200

**Comment by gjbg1989** [comment]
首先得开启 http://127.0.0.1:8085/?module=launcher&menu=config  模块管理——启用 X_tunnel
也得一定时间的扫描？

**Comment by xxnet** [comment]
是bug，试试 3.7.18版本，特别对这个地方加了处理。

**Comment by chkjc10** [comment]
3.7.18依然是同样的问题，不好用

**Comment by gjbg1989** [comment]
不是不好用，而是没用好😭
xyuanmu/XX-Mini: XX-Net 精简版 - https://github.com/xyuanmu/XX-Mini

**Comment by xxnet** [comment]
​新发布 3.8.0，改善X-Tunnel卡顿
请测试
https://github.com/XX-net/XX-Net/issues/8441
