### ISSUE TITLE
升级Win10后XX-net打不开了

### ISSUE THREAD

**Issue by xydbhzl** [XX-net/XX-Net#846]
刚升级好，点原来XX-net的快捷方式没反应，用管理员权限也没反应。
然后重新下了一个2.0.5版的，start.lnk运行之后有提示导入证书，但是却没有像以前那样弹出chrome，也没生成桌面快捷方式，再怎么点start.vbs都没反应了，后台倒是有pythonw.exe在运行
XX-net的配置页面压根就进不去。
求问各位大侠这是什么情况？

**Comment by xxnet** [comment]
命令行下，执行start.bat 看看

在 2015年8月21日 上午10:48，xydbhzl <notifications@github.com>写道：

**Comment by xydbhzl** [comment]
烦请楼上大侠帮忙看一下，谢谢！

Microsoft Windows [版本 10.0.10240]
(c) 2015 Microsoft Corporation. All rights reserved.

C:\Users\Xu>d:

D:\>cd XX-net-2.0.5

D:\XX-Net-2.0.5>start.bat

D:\XX-Net-2.0.5>"D:\XX-Net-2.0.5\python27/1.0/python.exe" "D:\XX-Net-2.0.5\launcher/start.py"
Aug 21 12:43:56 - [DEBUG] start confirm_xxnet_exit
Aug 21 12:43:57 - [INFO] load ip range file:D:\XX-Net-2.0.5\gae_proxy\local\ip_range.txt
Aug 21 12:43:57 - [INFO] load google ip_list num:100, gws num:100
Aug 21 12:43:57 - [INFO] SSL use version:TLSv1
Aug 21 12:43:57 - [INFO] ------------------------------------------------------
GAEProxy Version    : gae_proxy (python/2.7.9 )
Listen Address     : 127.0.0.1:8087
GAE APPID          : xxnet-1|xxnet-2|xxnet-3|xxnet-4|xxnet-5|xxnet-6|xxnet-7|xxnet-8|xxnet-9|xxnet-10|xxnet-11|xxnet-12|xxnet-13|xxnet-14|xxnet-15|xxnet-16|xxnet-17|xxnet-18|xxnet-19|xxnet-20|xxnet-21|xxnet-22|xxnet-23|xxnet-24|xxnet-25|xxnet-26|xxnet-27|xxnet-28|xxnet-29|xxnet-30|xxnet-31|xxnet-32|xxnet-33|xxnet-34|xxnet-35|xxnet-36|xxnet-37|xxnet-38|xxnet-39|xxnet-40|xxnet-41|xxnet-42|xxnet-43|xxnet-44|xxnet-45|xxnet-46|xxnet-47|xxnet-48|xxnet-49|xxnet-50|xxnet-51|xxnet-52|xxnet-53|xxnet-54|xxnet-55|xxnet-56|xxnet-57|xxnet-58|xxnet-59|xxnet-60|xxnet-61|xxnet-62|xxnet-63|xxnet-64|xxnet-65|xxnet-66|xxnet-67|xxnet-68|xxnet-69|xxnet-70|xxnet-71|xxnet-72|xxnet-72|xxnet-73|xxnet-74|xxnet-75|xxnet-76|xxnet-77|xxnet-78|xxnet-79|xxnet-80|xxnet-81|xxnet-82|xxnet-83|xxnet-84|xxnet-85|xxnet-86|xxnet-87|xxnet-88|xxnet-89|xxnet-90|xxnet-91|xxnet-92|xxnet-93|xxnet-94|xxnet-95|xxnet-96|xxnet-97|xxnet-98|xxnet-99|xxnet-100|xxnet-101|xxnet-102|xxnet-103|xxnet-104|xxnet-105|xxnet-106|xxnet-107|xxnet-108|xxnet-109|xxnet-110|xxnet-111|xxnet-112|xxnet-113|xxnet-114|xxnet-115|xxnet-116|xxnet-117|xxnet-118|xxnet-119|xxnet-120|xxnet-121|xxnet-122|xxnet-123|xxnet-124|xxnet-125|xxnet-126|xxnet-127|xxnet-128|xxnet-129|xxnet-130|xxnet-131|xxnet-132|xxnet-133|xxnet-134|xxnet-135|xxnet-136|xxnet-137|xxnet-138|xxnet-139|xxnet-140|xxnet-141|xxnet-142|xxnet-143|xxnet-144|xxnet-145|xxnet-146|xxnet-147|xxnet-148|xxnet-149|xxnet-150|xxnet-151|xxnet-152|xxnet-153|xxnet-154|xxnet-155|xxnet-156|xxnet-157|xxnet-158|xxnet-159
Pac Server         : http://127.0.0.1:8086/proxy.pac
------------------------------------------------------

Aug 21 12:43:57 - [INFO] no CA file exist
Aug 21 12:43:57 - [INFO] clean old site certs
Aug 21 12:43:57 - [INFO] generate CA file:D:\XX-Net-2.0.5\data\gae_proxy\CA.crt
Aug 21 12:43:57 - [INFO] create ca
Exception in thread Thread-52:
Traceback (most recent call last):
  File "D:\XX-Net-2.0.5\python27\1.0\lib\threading.py", line 810, in __bootstrap_inner
    self.run()
  File "D:\XX-Net-2.0.5\python27\1.0\lib\threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "D:\XX-Net-2.0.5\gae_proxy\start.py", line 18, in main
    client.main()
  File "D:\XX-Net-2.0.5\gae_proxy\local\proxy.py", line 235, in main
    proxy_daemon = LocalProxyServer((config.LISTEN_IP, config.LISTEN_PORT), proxy_handler.GAEProxyHandler)
  File "D:\XX-Net-2.0.5\python27\1.0\lib\SocketServer.py", line 419, in __init__
    self.server_bind()
  File "D:\XX-Net-2.0.5\python27\1.0\lib\SocketServer.py", line 431, in server_bind
    self.server_address = self.socket.getsockname()
  File "D:\XX-Net-2.0.5\python27\1.0\lib\socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
gaierror: [Errno 10022] getaddrinfo failed

Aug 21 12:43:58 - [DEBUG] get ip:202.86.162.41 t:99
Aug 21 12:43:58 - [DEBUG] get ip:103.1.139.167 t:392
Aug 21 12:43:59 - [DEBUG] get ip:208.117.255.111 t:453
Aug 21 12:43:59 - [INFO] scan_ip add ip:163.28.116.31 time:594
Aug 21 12:43:59 - [DEBUG] get ip:208.117.239.132 t:491
Aug 21 12:43:59 - [DEBUG] get ip:41.201.164.41 t:551
Aug 21 12:44:00 - [DEBUG] get ip:82.135.118.51 t:578
Aug 21 12:44:00 - [DEBUG] get ip:194.78.99.205 t:579
Aug 21 12:44:00 - [DEBUG] get ip:193.134.255.146 t:600
Aug 21 12:44:00 - [DEBUG] get ip:58.145.238.54 t:605
Aug 21 12:44:01 - [DEBUG] get ip:41.201.164.22 t:616
Aug 21 12:44:02 - [DEBUG] create_ssl 202.86.162.41 fail:timed out cost:4001 h:0
Aug 21 12:44:02 - [DEBUG] report_connect_fail network fail
Aug 21 12:44:02 - [DEBUG] create_ssl 103.1.139.167 fail:timed out cost:4000 h:0
Aug 21 12:44:02 - [DEBUG] report_connect_fail network fail
Aug 21 12:44:03 - [DEBUG] create_ssl 208.117.255.111 fail:timed out cost:4001 h:0
Aug 21 12:44:03 - [DEBUG] report_connect_fail network fail
Aug 21 12:44:03 - [DEBUG] create_ssl 208.117.239.132 fail:timed out cost:4002 h:0
Aug 21 12:44:03 - [DEBUG] report_connect_fail network fail
Aug 21 12:44:03 - [DEBUG] get ip:82.135.118.54 t:624
Aug 21 12:44:03 - [DEBUG] create_ssl 41.201.164.41 fail:timed out cost:4000 h:0
Aug 21 12:44:03 - [DEBUG] report_connect_fail network fail
Aug 21 12:44:03 - [DEBUG] get ip:193.120.166.119 t:626
Aug 21 12:44:04 - [DEBUG] create_ssl 82.135.118.51 fail:timed out cost:4001 h:0
Aug 21 12:44:04 - [DEBUG] report_connect_fail network fail
Aug 21 12:44:04 - [DEBUG] get ip:37.228.69.16 t:668
Aug 21 12:44:04 - [DEBUG] create_ssl 194.78.99.205 fail:timed out cost:4000 h:0
Aug 21 12:44:04 - [DEBUG] report_connect_fail network fail
Aug 21 12:44:04 - [DEBUG] get ip:61.19.1.235 t:678
Aug 21 12:44:04 - [DEBUG] create_ssl 193.134.255.146 fail:timed out cost:4001 h:0
Aug 21 12:44:04 - [DEBUG] report_connect_fail network fail
Aug 21 12:44:04 - [DEBUG] get ip:64.15.112.53 t:695
Aug 21 12:44:04 - [DEBUG] create_ssl 58.145.238.54 fail:timed out cost:4001 h:0
Aug 21 12:44:04 - [DEBUG] report_connect_fail network fail
Aug 21 12:44:05 - [DEBUG] get ip:208.117.244.31 t:739
Aug 21 12:44:05 - [DEBUG] create_ssl 41.201.164.22 fail:timed out cost:4000 h:0
Aug 21 12:44:05 - [DEBUG] report_connect_fail network fail
Aug 21 12:44:05 - [DEBUG] get ip:220.255.6.5 t:745
Aug 21 12:44:05 - [DEBUG] get ip:139.175.107.80 t:747
Aug 21 12:44:05 - [DEBUG] get ip:173.194.21.76 t:749
Aug 21 12:44:06 - [DEBUG] get ip:193.134.255.9 t:751
Aug 21 12:44:07 - [DEBUG] create_ssl 82.135.118.54 fail:timed out cost:4002 h:0
Aug 21 12:44:07 - [DEBUG] report_connect_fail network fail
Aug 21 12:44:07 - [DEBUG] create_ssl 193.120.166.119 fail:timed out cost:4001 h:0
Aug 21 12:44:07 - [DEBUG] report_connect_fail network fail
Aug 21 12:44:08 - [DEBUG] create_ssl 37.228.69.16 fail:timed out cost:4000 h:0
Aug 21 12:44:08 - [DEBUG] report_connect_fail network fail
Aug 21 12:44:08 - [DEBUG] create_ssl 61.19.1.235 fail:timed out cost:4002 h:0
Aug 21 12:44:08 - [DEBUG] report_connect_fail network fail
Aug 21 12:44:08 - [DEBUG] get ip:202.86.162.41 t:99
Aug 21 12:44:08 - [DEBUG] create_ssl 64.15.112.53 fail:timed out cost:4002 h:0
Aug 21 12:44:08 - [DEBUG] report_connect_fail network fail
Aug 21 12:44:08 - [DEBUG] get ip:103.1.139.167 t:392
Aug 21 12:44:09 - [DEBUG] create_ssl 208.117.244.31 fail:timed out cost:4002 h:0
Aug 21 12:44:09 - [DEBUG] report_connect_fail network fail
Aug 21 12:44:09 - [DEBUG] get ip:208.117.255.111 t:453
Aug 21 12:44:09 - [DEBUG] create_ssl 220.255.6.5 fail:timed out cost:4001 h:0
Aug 21 12:44:09 - [DEBUG] report_connect_fail network fail
Aug 21 12:44:09 - [DEBUG] get ip:208.117.239.132 t:491
Aug 21 12:44:09 - [DEBUG] create_ssl 139.175.107.80 fail:timed out cost:4001 h:0
Aug 21 12:44:09 - [DEBUG] report_connect_fail network fail
Aug 21 12:44:09 - [DEBUG] get ip:41.201.164.41 t:551
Aug 21 12:44:09 - [DEBUG] create_ssl 173.194.21.76 fail:timed out cost:4000 h:0
Aug 21 12:44:09 - [DEBUG] report_connect_fail network fail
Aug 21 12:44:10 - [DEBUG] get ip:82.135.118.51 t:578
Aug 21 12:44:10 - [DEBUG] create_ssl 193.134.255.9 fail:timed out cost:4002 h:0
Aug 21 12:44:10 - [DEBUG] report_connect_fail network fail
Aug 21 12:44:10 - [DEBUG] get ip:194.78.99.205 t:579
Aug 21 12:44:10 - [DEBUG] get ip:163.28.116.31 t:594
Aug 21 12:44:10 - [DEBUG] get ip:193.134.255.146 t:600
Aug 21 12:44:11 - [DEBUG] get ip:58.145.238.54 t:605
Aug 21 12:44:11 - [DEBUG] create_ssl update ip:163.28.116.31 time:597
Aug 21 12:44:12 - [DEBUG] get ip:41.201.164.22 t:616
Aug 21 12:44:12 - [DEBUG] create_ssl 202.86.162.41 fail:timed out cost:4002 h:0
Aug 21 12:44:12 - [DEBUG] create_ssl 103.1.139.167 fail:timed out cost:4001 h:0
Aug 21 12:44:13 - [DEBUG] create_ssl 208.117.255.111 fail:timed out cost:4001 h:0
Aug 21 12:44:13 - [DEBUG] create_ssl 208.117.239.132 fail:timed out cost:4000 h:0
Aug 21 12:44:13 - [DEBUG] create_ssl 41.201.164.41 fail:timed out cost:4000 h:0
Aug 21 12:44:14 - [DEBUG] create_ssl 82.135.118.51 fail:timed out cost:4001 h:0
Aug 21 12:44:14 - [DEBUG] create_ssl 194.78.99.205 fail:timed out cost:4001 h:0
Aug 21 12:44:14 - [DEBUG] create_ssl 193.134.255.146 fail:timed out cost:4002 h:0
Aug 21 12:44:15 - [DEBUG] create_ssl 58.145.238.54 fail:timed out cost:4002 h:0
Aug 21 12:44:15 - [DEBUG] report_connect_fail network fail
Aug 21 12:44:15 - [DEBUG] report_connect_fail network fail
Aug 21 12:44:15 - [DEBUG] report_connect_fail network fail
Aug 21 12:44:15 - [DEBUG] report_connect_fail network fail
Aug 21 12:44:15 - [DEBUG] report_connect_fail network fail
Aug 21 12:44:15 - [DEBUG] report_connect_fail network fail
Aug 21 12:44:15 - [DEBUG] report_connect_fail network fail
Aug 21 12:44:15 - [DEBUG] report_connect_fail network fail
Aug 21 12:44:15 - [DEBUG] report_connect_fail network fail
Aug 21 12:44:16 - [DEBUG] get ip:82.135.118.54 t:624
Aug 21 12:44:16 - [DEBUG] get ip:193.120.166.119 t:626
Aug 21 12:44:16 - [DEBUG] get ip:37.228.69.16 t:668
Aug 21 12:44:16 - [DEBUG] get ip:61.19.1.235 t:678
Aug 21 12:44:16 - [DEBUG] get ip:64.15.112.53 t:695
Aug 21 12:44:16 - [DEBUG] get ip:208.117.244.31 t:739
Aug 21 12:44:16 - [DEBUG] get ip:220.255.6.5 t:745
Aug 21 12:44:16 - [DEBUG] get ip:139.175.107.80 t:747
Aug 21 12:44:16 - [DEBUG] get ip:173.194.21.76 t:749
Stopping all modules before exit!
Aug 21 12:44:19 - [DEBUG] module gae_proxy stopping
Aug 21 12:44:19 - [INFO] module gae_proxy stopped
终止批处理操作吗(Y/N)?

**Comment by xydbhzl** [comment]
烦请大侠帮忙看一下，谢谢！
因为他一直在运行，我就强行终止了

Microsoft Windows 版本 10.0.10240
<https://github.com/XX-net/XX-Net/issues/c> 2015
Microsoft Corporation. All rights reserved.

C:\Users\Xu>d:

D:>cd XX-net-2.0.5

D:\XX-Net-2.0.5>start.bat

D:\XX-Net-2.0.5>"D:\XX-Net-2.0.5\python27/1.0/python.exe"
"D:\XX-Net-2.0.5\launcher/start.py"
Aug 21 12:43:56 - [DEBUG] start confirm_xxnet_exit
Aug 21 12:43:57 - [INFO] load ip range
file:D:\XX-Net-2.0.5\gae_proxy\local\ip_range.txt
Aug 21 12:43:57 - [INFO] load google ip_list num:100, gws num:100
Aug 21 12:43:57 - [INFO] SSL use version:TLSv1
Aug 21 12:43:57 - [INFO]
------------------------------------------------------
GAEProxy Version : gae_proxy (python/2.7.9 )
Listen Address : 127.0.0.1:8087
GAE APPID :
xxnet-1|xxnet-2|xxnet-3|xxnet-4|xxnet-5|xxnet-6|xxnet-7|xxnet-8|xxnet-9|xxnet-10|xxnet-11|xxnet-12|xxnet-13|xxnet-14|xxnet-15|xxnet-16|xxnet-17|xxnet-18|xxnet-19|xxnet-20|xxnet-21|xxnet-22|xxnet-23|xxnet-24|xxnet-25|xxnet-26|xxnet-27|xxnet-28|xxnet-29|xxnet-30|xxnet-31|xxnet-32|xxnet-33|xxnet-34|xxnet-35|xxnet-36|xxnet-37|xxnet-38|xxnet-39|xxnet-40|xxnet-41|xxnet-42|xxnet-43|xxnet-44|xxnet-45|xxnet-46|xxnet-47|xxnet-48|xxnet-49|xxnet-50|xxnet-51|xxnet-52|xxnet-53|xxnet-54|xxnet-55|xxnet-56|xxnet-57|xxnet-58|xxnet-59|xxnet-60|xxnet-61|xxnet-62|xxnet-63|xxnet-64|xxnet-65|xxnet-66|xxnet-67|xxnet-68|xxnet-69|xxnet-70|xxnet-71|xxnet-72|xxnet-72|xxnet-73|xxnet-74|xxnet-75|xxnet-76|xxnet-77|xxnet-78|xxnet-79|xxnet-80|xxnet-81|xxnet-82|xxnet-83|xxnet-84|xxnet-85|xxnet-86|xxnet-87|xxnet-88|xxnet-89|xxnet-90|xxnet-91|xxnet-92|xxnet-93|xxnet-94|xxnet-95|xxnet-96|xxnet-97|xxnet-98|xxnet-99|xxnet-100|xxnet-101|xxnet-102|xxnet-103|xxnet-104|xxnet-105|xxnet-106|xxnet-107|xxnet-108|xxnet-109|xxnet-110|xxnet-111|xxnet-112|xxnet-113|xxnet-114|xxnet-115|xxnet-116|xxnet-117|xxnet-118|xxnet-119|xxnet-120|xxnet-121|xxnet-122|xxnet-123|xxnet-124|xxnet-125|xxnet-126|xxnet-127|xxnet-128|xxnet-129|xxnet-130|xxnet-131|xxnet-132|xxnet-133|xxnet-134|xxnet-135|xxnet-136|xxnet-137|xxnet-138|xxnet-139|xxnet-140|xxnet-141|xxnet-142|xxnet-143|xxnet-144|xxnet-145|xxnet-146|xxnet-147|xxnet-148|xxnet-149|xxnet-150|xxnet-151|xxnet-152|xxnet-153|xxnet-154|xxnet-155|xxnet-156|xxnet-157|xxnet-158|xxnet-159
Pac Server : http://127.0.0.1:8086/proxy.pac

Aug 21 12:43:57 - [INFO] no CA file exist
Aug 21 12:43:57 - [INFO] clean old site certs
Aug 21 12:43:57 - [INFO] generate CA
file:D:\XX-Net-2.0.5\data\gae_proxy\CA.crt
Aug 21 12:43:57 - [INFO] create ca
Exception in thread Thread-52:
Traceback (most recent call last):
File "D:\XX-Net-2.0.5\python27\1.0\lib\threading.py", line 810, in







*bootstrap_innerself.run()File
"D:\XX-Net-2.0.5\python27\1.0\lib\threading.py", line 763, in
runself.__target(self.__args, *self.__kwargs)File
"D:\XX-Net-2.0.5\gae_proxy\start.py", line 18, in mainclient.main()File
"D:\XX-Net-2.0.5\gae_proxy\local\proxy.py", line 235, in mainproxy_daemon =
LocalProxyServer((config.LISTEN_IP, config.LISTEN_PORT),
proxy_handler.GAEProxyHandler)File
"D:\XX-Net-2.0.5\python27\1.0\lib\SocketServer.py", line 419, in __init*
self.server_bind()
File "D:\XX-Net-2.0.5\python27\1.0\lib\SocketServer.py", line 431, in
server_bind
self.server_address = self.socket.getsockname()
File "D:\XX-Net-2.0.5\python27\1.0\lib\socket.py", line 224, in meth
return getattr(self._sock,name)(*args)
gaierror: [Errno 10022] getaddrinfo failed

Aug 21 12:43:58 - [DEBUG] get ip:202.86.162.41 t:99
Aug 21 12:43:58 - [DEBUG] get ip:103.1.139.167 t:392
Aug 21 12:43:59 - [DEBUG] get ip:208.117.255.111 t:453
Aug 21 12:43:59 - [INFO] scan_ip add ip:163.28.116.31 time:594
Aug 21 12:43:59 - [DEBUG] get ip:208.117.239.132 t:491
Aug 21 12:43:59 - [DEBUG] get ip:41.201.164.41 t:551
Aug 21 12:44:00 - [DEBUG] get ip:82.135.118.51 t:578
Aug 21 12:44:00 - [DEBUG] get ip:194.78.99.205 t:579
Aug 21 12:44:00 - [DEBUG] get ip:193.134.255.146 t:600
Aug 21 12:44:00 - [DEBUG] get ip:58.145.238.54 t:605
Aug 21 12:44:01 - [DEBUG] get ip:41.201.164.22 t:616
Aug 21 12:44:02 - [DEBUG] create_ssl 202.86.162.41 fail:timed out cost:4001
h:0
Aug 21 12:44:02 - [DEBUG] report_connect_fail network fail
Aug 21 12:44:02 - [DEBUG] create_ssl 103.1.139.167 fail:timed out cost:4000
h:0
Aug 21 12:44:02 - [DEBUG] report_connect_fail network fail
Aug 21 12:44:03 - [DEBUG] create_ssl 208.117.255.111 fail:timed out
cost:4001 h:0
Aug 21 12:44:03 - [DEBUG] report_connect_fail network fail
Aug 21 12:44:03 - [DEBUG] create_ssl 208.117.239.132 fail:timed out
cost:4002 h:0
Aug 21 12:44:03 - [DEBUG] report_connect_fail network fail
Aug 21 12:44:03 - [DEBUG] get ip:82.135.118.54 t:624
Aug 21 12:44:03 - [DEBUG] create_ssl 41.201.164.41 fail:timed out cost:4000
h:0
Aug 21 12:44:03 - [DEBUG] report_connect_fail network fail
Aug 21 12:44:03 - [DEBUG] get ip:193.120.166.119 t:626
Aug 21 12:44:04 - [DEBUG] create_ssl 82.135.118.51 fail:timed out cost:4001
h:0
Aug 21 12:44:04 - [DEBUG] report_connect_fail network fail
Aug 21 12:44:04 - [DEBUG] get ip:37.228.69.16 t:668
Aug 21 12:44:04 - [DEBUG] create_ssl 194.78.99.205 fail:timed out cost:4000
h:0
Aug 21 12:44:04 - [DEBUG] report_connect_fail network fail
Aug 21 12:44:04 - [DEBUG] get ip:61.19.1.235 t:678
Aug 21 12:44:04 - [DEBUG] create_ssl 193.134.255.146 fail:timed out
cost:4001 h:0
Aug 21 12:44:04 - [DEBUG] report_connect_fail network fail
Aug 21 12:44:04 - [DEBUG] get ip:64.15.112.53 t:695
Aug 21 12:44:04 - [DEBUG] create_ssl 58.145.238.54 fail:timed out cost:4001
h:0
Aug 21 12:44:04 - [DEBUG] report_connect_fail network fail
Aug 21 12:44:05 - [DEBUG] get ip:208.117.244.31 t:739
Aug 21 12:44:05 - [DEBUG] create_ssl 41.201.164.22 fail:timed out cost:4000
h:0
Aug 21 12:44:05 - [DEBUG] report_connect_fail network fail
Aug 21 12:44:05 - [DEBUG] get ip:220.255.6.5 t:745
Aug 21 12:44:05 - [DEBUG] get ip:139.175.107.80 t:747
Aug 21 12:44:05 - [DEBUG] get ip:173.194.21.76 t:749
Aug 21 12:44:06 - [DEBUG] get ip:193.134.255.9 t:751
Aug 21 12:44:07 - [DEBUG] create_ssl 82.135.118.54 fail:timed out cost:4002
h:0
Aug 21 12:44:07 - [DEBUG] report_connect_fail network fail
Aug 21 12:44:07 - [DEBUG] create_ssl 193.120.166.119 fail:timed out
cost:4001 h:0
Aug 21 12:44:07 - [DEBUG] report_connect_fail network fail
Aug 21 12:44:08 - [DEBUG] create_ssl 37.228.69.16 fail:timed out cost:4000
h:0
Aug 21 12:44:08 - [DEBUG] report_connect_fail network fail
Aug 21 12:44:08 - [DEBUG] create_ssl 61.19.1.235 fail:timed out cost:4002
h:0
Aug 21 12:44:08 - [DEBUG] report_connect_fail network fail
Aug 21 12:44:08 - [DEBUG] get ip:202.86.162.41 t:99
Aug 21 12:44:08 - [DEBUG] create_ssl 64.15.112.53 fail:timed out cost:4002
h:0
Aug 21 12:44:08 - [DEBUG] report_connect_fail network fail
Aug 21 12:44:08 - [DEBUG] get ip:103.1.139.167 t:392
Aug 21 12:44:09 - [DEBUG] create_ssl 208.117.244.31 fail:timed out
cost:4002 h:0
Aug 21 12:44:09 - [DEBUG] report_connect_fail network fail
Aug 21 12:44:09 - [DEBUG] get ip:208.117.255.111 t:453
Aug 21 12:44:09 - [DEBUG] create_ssl 220.255.6.5 fail:timed out cost:4001
h:0
Aug 21 12:44:09 - [DEBUG] report_connect_fail network fail
Aug 21 12:44:09 - [DEBUG] get ip:208.117.239.132 t:491
Aug 21 12:44:09 - [DEBUG] create_ssl 139.175.107.80 fail:timed out
cost:4001 h:0
Aug 21 12:44:09 - [DEBUG] report_connect_fail network fail
Aug 21 12:44:09 - [DEBUG] get ip:41.201.164.41 t:551
Aug 21 12:44:09 - [DEBUG] create_ssl 173.194.21.76 fail:timed out cost:4000
h:0
Aug 21 12:44:09 - [DEBUG] report_connect_fail network fail
Aug 21 12:44:10 - [DEBUG] get ip:82.135.118.51 t:578
Aug 21 12:44:10 - [DEBUG] create_ssl 193.134.255.9 fail:timed out cost:4002
h:0
Aug 21 12:44:10 - [DEBUG] report_connect_fail network fail
Aug 21 12:44:10 - [DEBUG] get ip:194.78.99.205 t:579
Aug 21 12:44:10 - [DEBUG] get ip:163.28.116.31 t:594
Aug 21 12:44:10 - [DEBUG] get ip:193.134.255.146 t:600
Aug 21 12:44:11 - [DEBUG] get ip:58.145.238.54 t:605
Aug 21 12:44:11 - [DEBUG] create_ssl update ip:163.28.116.31 time:597
Aug 21 12:44:12 - [DEBUG] get ip:41.201.164.22 t:616
Aug 21 12:44:12 - [DEBUG] create_ssl 202.86.162.41 fail:timed out cost:4002
h:0
Aug 21 12:44:12 - [DEBUG] create_ssl 103.1.139.167 fail:timed out cost:4001
h:0
Aug 21 12:44:13 - [DEBUG] create_ssl 208.117.255.111 fail:timed out
cost:4001 h:0
Aug 21 12:44:13 - [DEBUG] create_ssl 208.117.239.132 fail:timed out
cost:4000 h:0
Aug 21 12:44:13 - [DEBUG] create_ssl 41.201.164.41 fail:timed out cost:4000
h:0
Aug 21 12:44:14 - [DEBUG] create_ssl 82.135.118.51 fail:timed out cost:4001
h:0
Aug 21 12:44:14 - [DEBUG] create_ssl 194.78.99.205 fail:timed out cost:4001
h:0
Aug 21 12:44:14 - [DEBUG] create_ssl 193.134.255.146 fail:timed out
cost:4002 h:0
Aug 21 12:44:15 - [DEBUG] create_ssl 58.145.238.54 fail:timed out cost:4002
h:0
Aug 21 12:44:15 - [DEBUG] report_connect_fail network fail
Aug 21 12:44:15 - [DEBUG] report_connect_fail network fail
Aug 21 12:44:15 - [DEBUG] report_connect_fail network fail
Aug 21 12:44:15 - [DEBUG] report_connect_fail network fail
Aug 21 12:44:15 - [DEBUG] report_connect_fail network fail
Aug 21 12:44:15 - [DEBUG] report_connect_fail network fail
Aug 21 12:44:15 - [DEBUG] report_connect_fail network fail
Aug 21 12:44:15 - [DEBUG] report_connect_fail network fail
Aug 21 12:44:15 - [DEBUG] report_connect_fail network fail
Aug 21 12:44:16 - [DEBUG] get ip:82.135.118.54 t:624
Aug 21 12:44:16 - [DEBUG] get ip:193.120.166.119 t:626
Aug 21 12:44:16 - [DEBUG] get ip:37.228.69.16 t:668
Aug 21 12:44:16 - [DEBUG] get ip:61.19.1.235 t:678
Aug 21 12:44:16 - [DEBUG] get ip:64.15.112.53 t:695
Aug 21 12:44:16 - [DEBUG] get ip:208.117.244.31 t:739
Aug 21 12:44:16 - [DEBUG] get ip:220.255.6.5 t:745
Aug 21 12:44:16 - [DEBUG] get ip:139.175.107.80 t:747
Aug 21 12:44:16 - [DEBUG] get ip:173.194.21.76 t:749
Stopping all modules before exit!
Aug 21 12:44:19 - [DEBUG] module gae_proxy stopping
Aug 21 12:44:19 - [INFO] module gae_proxy stopped
终止批处理操作吗(Y/N)?

在 2015年8月21日 上午11:23，xxnet <notifications@github.com>写道：

**Comment by xxnet** [comment]
试试 重新下载个新的解压执行看看

2015-08-21 15:16 GMT+08:00 xydbhzl <notifications@github.com>:

**Comment by xydbhzl** [comment]
重新解压也是这样，不管什么版本都是

2015-08-21 17:47 GMT+08:00 xxnet <notifications@github.com>:

**Comment by xxnet** [comment]
看日志是 getsockname出问题。
 你的win10 是什么版本？我这边没有遇到过这样的问题。


2015-08-21 20:44 GMT+08:00 xydbhzl <notifications@github.com>:

**Comment by xydbhzl** [comment]
麻烦你了！我的就是Windows专业版，版本号10.0.10240，是前几天从Win7安装自动更新直接升级上来的。

2015-08-21 21:17 GMT+08:00 xxnet <notifications@github.com>:

**Comment by kairi1227** [comment]
楼上有没有解决该问题，我也是升级win10后出现的问题？分享一下你解决的方法。。

**Comment by xydbhzl** [comment]
没有，早就换用SS了..

2016-02-15 14:31 GMT+08:00 kairi1227 <notifications@github.com>:

**Comment by kairi1227** [comment]
我的问题解决了，请参考issue #2315
