### ISSUE TITLE
Mac OS X 10.10.5下php模块还是不行

### ISSUE THREAD

**Issue by causlayer** [XX-net/XX-Net#852]
Aug 21 14:10:31 - [INFO] ------------------------------------------------------
PHP proxy Version : 3.2.3 (python/2.7.1 gevent/1.0.1 pyopenssl/0.13.1)
PHP Listen : 127.0.0.1:8088
PHP FetchServers : ['http://www.test.com/proxy/index.php']
------------------------------------------------------

Aug 21 14:10:31 - [DEBUG] init_ca
Aug 21 14:10:31 - [INFO] PHP_proxy CA exist
Aug 22 06:39:18 - [DEBUG] PHP web_control 127.0.0.1:61042 POST /config?cmd=get_config 
Aug 22 06:39:25 - [INFO] 127.0.0.1:61104 "STRIP CONNECT autoproxy-gfwlist.googlecode.com:443 HTTP/1.1" - -
Aug 22 06:39:25 - [INFO] 127.0.0.1:61105 "STRIP CONNECT autoproxy-gfwlist.googlecode.com:443 HTTP/1.1" - -
Aug 22 06:39:25 - [INFO] 127.0.0.1:61106 "STRIP CONNECT autoproxy-gfwlist.googlecode.com:443 HTTP/1.1" - -
Aug 22 06:39:25 - [INFO] 127.0.0.1:61107 "STRIP CONNECT autoproxy-gfwlist.googlecode.com:443 HTTP/1.1" - -
Aug 22 06:39:28 - [INFO] 127.0.0.1:61138 "STRIP CONNECT clients4.google.com:443 HTTP/1.1" - -
Aug 22 06:39:28 - [INFO] 127.0.0.1:61139 "STRIP CONNECT clients4.google.com:443 HTTP/1.1" - -
Aug 22 06:39:28 - [INFO] 127.0.0.1:61140 "STRIP CONNECT clients4.google.com:443 HTTP/1.1" - -
Aug 22 06:39:28 - [INFO] 127.0.0.1:61141 "STRIP CONNECT clients4.google.com:443 HTTP/1.1" - -
Aug 22 06:39:29 - [INFO] 127.0.0.1:61148 "STRIP CONNECT apis.google.com:443 HTTP/1.1" - -
Aug 22 06:39:29 - [INFO] 127.0.0.1:61147 "STRIP CONNECT www.google.com.hk:443 HTTP/1.1" - -
Aug 22 06:39:29 - [INFO] 127.0.0.1:61149 "STRIP CONNECT plus.google.com:443 HTTP/1.1" - -
Aug 22 06:39:29 - [INFO] 127.0.0.1:61150 "STRIP CONNECT plus.google.com:443 HTTP/1.1" - -
Aug 22 06:39:29 - [INFO] 127.0.0.1:61151 "STRIP CONNECT ssl.gstatic.com:443 HTTP/1.1" - -
Aug 22 06:39:29 - [INFO] 127.0.0.1:61152 "STRIP CONNECT www.google.com.hk:443 HTTP/1.1" - -
Aug 22 06:39:29 - [INFO] 127.0.0.1:61153 "STRIP CONNECT www.google.com.hk:443 HTTP/1.1" - -
Aug 22 06:39:30 - [INFO] 127.0.0.1:61166 "STRIP CONNECT clients4.google.com:443 HTTP/1.1" - -
Aug 22 06:39:30 - [INFO] 127.0.0.1:61167 "STRIP CONNECT clients4.google.com:443 HTTP/1.1" - -
Aug 22 06:39:30 - [INFO] 127.0.0.1:61168 "STRIP CONNECT clients4.google.com:443 HTTP/1.1" - -
Aug 22 06:39:30 - [INFO] 127.0.0.1:61169 "STRIP CONNECT clients4.google.com:443 HTTP/1.1" - -
Aug 22 06:39:34 - [INFO] 127.0.0.1:61207 "STRIP CONNECT www.youtube.com:443 HTTP/1.1" - -
Aug 22 06:39:35 - [INFO] 127.0.0.1:61211 "STRIP CONNECT www.youtube.com:443 HTTP/1.1" - -
Aug 22 06:39:35 - [INFO] 127.0.0.1:61212 "STRIP CONNECT www.youtube.com:443 HTTP/1.1" - -
Aug 22 06:39:35 - [INFO] 127.0.0.1:61213 "STRIP CONNECT www.youtube.com:443 HTTP/1.1" - -
Aug 22 06:39:35 - [INFO] 127.0.0.1:61214 "STRIP CONNECT www.youtube.com:443 HTTP/1.1" - -
Aug 22 06:39:35 - [INFO] 127.0.0.1:61216 "STRIP CONNECT www.youtube.com:443 HTTP/1.1" - -
Aug 22 06:39:35 - [INFO] 127.0.0.1:61217 "STRIP CONNECT www.youtube.com:443 HTTP/1.1" - -
Aug 22 06:39:35 - [INFO] 127.0.0.1:61218 "STRIP CONNECT www.youtube.com:443 HTTP/1.1" - -
Aug 22 06:39:35 - [INFO] 127.0.0.1:61219 "STRIP CONNECT www.youtube.com:443 HTTP/1.1" - -
Aug 22 06:39:38 - [INFO] 127.0.0.1:61252 "STRIP CONNECT www.youtube.com:443 HTTP/1.1" - -
Aug 22 06:39:38 - [INFO] 127.0.0.1:61253 "STRIP CONNECT www.youtube.com:443 HTTP/1.1" - -
Aug 22 06:39:38 - [INFO] 127.0.0.1:61254 "STRIP CONNECT www.youtube.com:443 HTTP/1.1" - -
Aug 22 06:39:38 - [INFO] 127.0.0.1:61255 "STRIP CONNECT www.youtube.com:443 HTTP/1.1" - -
Aug 22 06:39:40 - [INFO] 127.0.0.1:61276 "STRIP CONNECT www.youtube.com:443 HTTP/1.1" - -
Aug 22 06:39:40 - [INFO] 127.0.0.1:61278 "STRIP CONNECT www.youtube.com:443 HTTP/1.1" - -
Aug 22 06:39:40 - [INFO] 127.0.0.1:61279 "STRIP CONNECT www.youtube.com:443 HTTP/1.1" - -
Aug 22 06:39:40 - [INFO] 127.0.0.1:61280 "STRIP CONNECT www.youtube.com:443 HTTP/1.1" - -
Aug 22 06:39:55 - [INFO] 127.0.0.1:61421 "STRIP CONNECT www.youtube.com:443 HTTP/1.1" - -
Aug 22 06:39:55 - [INFO] 127.0.0.1:61422 "STRIP CONNECT www.youtube.com:443 HTTP/1.1" - -
Aug 22 06:39:55 - [INFO] 127.0.0.1:61423 "STRIP CONNECT www.youtube.com:443 HTTP/1.1" - -
Aug 22 06:39:55 - [INFO] 127.0.0.1:61424 "STRIP CONNECT www.youtube.com:443 HTTP/1.1" - -

一直就是这样。

**Comment by causlayer** [comment]
莫非使用mac系统的朋友你们的php模块都能正常运行吗？

**Comment by lele2010lele** [comment]
我的无问题啊

**Comment by causlayer** [comment]
我报这个错误：
Aug 24 23:58:53 - [INFO] PHP_proxy CA exist
Aug 24 23:59:15 - [INFO] 127.0.0.1:56216 "STRIP CONNECT www.facebook.com:443 HTTP/1.1" - -
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 56216)
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 599, in process_request_thread
    self.finish_request(request, client_address)
  File "/Applications/XX-Net/php_proxy/local/proxylib.py", line 619, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/Applications/XX-Net/php_proxy/local/proxy.py", line 763, in __init__
    SimpleProxyHandler.__init__(self, *args, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/Applications/XX-Net/php_proxy/local/proxylib.py", line 1295, in handle_one_request
    return BaseHTTPServer.BaseHTTPRequestHandler.handle_one_request(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/Applications/XX-Net/php_proxy/local/proxylib.py", line 1326, in do_METHOD
    return plugin.handle(self, **action[1])
  File "/Applications/XX-Net/php_proxy/local/proxylib.py", line 726, in handle
    self.do_ssl_handshake(handler)
  File "/Applications/XX-Net/php_proxy/local/proxylib.py", line 713, in do_ssl_handshake
    ssl_sock = ssl.wrap_socket(handler.connection, keyfile=certfile, certfile=certfile, server_side=True, ssl_version=self.ssl_method, ciphers=self.ciphers)
  File "/Library/Python/2.7/site-packages/gevent/ssl.py", line 383, in wrap_socket
    ciphers=ciphers)
  File "/Library/Python/2.7/site-packages/gevent/ssl.py", line 89, in __init__
    self._sslobj = _ssl.sslwrap(self._sock, server_side,
AttributeError: 'module' object has no attribute 'sslwrap'
----------------------------------------
Aug 24 23:59:15 - [INFO] 127.0.0.1:56217 "STRIP CONNECT www.facebook.com:443 HTTP/1.1" - -
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 56217)
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 599, in process_request_thread
    self.finish_request(request, client_address)
  File "/Applications/XX-Net/php_proxy/local/proxylib.py", line 619, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/Applications/XX-Net/php_proxy/local/proxy.py", line 763, in __init__
    SimpleProxyHandler.__init__(self, *args, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/Applications/XX-Net/php_proxy/local/proxylib.py", line 1295, in handle_one_request
    return BaseHTTPServer.BaseHTTPRequestHandler.handle_one_request(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/Applications/XX-Net/php_proxy/local/proxylib.py", line 1326, in do_METHOD
    return plugin.handle(self, **action[1])
  File "/Applications/XX-Net/php_proxy/local/proxylib.py", line 726, in handle
    self.do_ssl_handshake(handler)
  File "/Applications/XX-Net/php_proxy/local/proxylib.py", line 713, in do_ssl_handshake
    ssl_sock = ssl.wrap_socket(handler.connection, keyfile=certfile, certfile=certfile, server_side=True, ssl_version=self.ssl_method, ciphers=self.ciphers)
  File "/Library/Python/2.7/site-packages/gevent/ssl.py", line 383, in wrap_socket
    ciphers=ciphers)
  File "/Library/Python/2.7/site-packages/gevent/ssl.py", line 89, in __init__
    self._sslobj = _ssl.sslwrap(self._sock, server_side,
AttributeError: 'module' object has no attribute 'sslwrap'

请问怎么解决，谢谢

**Comment by xxnet** [comment]
看上去是系统的gevent 太老了，没有支持ssl，想办法升级gevent吧

2015-08-25 0:02 GMT+08:00 causlayer <notifications@github.com>:

**Comment by causlayer** [comment]
gevent升级到最新版本了，facebook是能打开，但很慢，还是会报错
PHP proxy Version : 3.2.3 (python/2.7.1 gevent/1.0.2 pyopenssl/0.13.1)
Aug 25 17:25:51 - [ERROR] ssl.wrap_socket(connection=) failed: [Errno 22] Invalid argument
Aug 25 17:25:51 - [ERROR] Except stack:Traceback (most recent call last):
File "/Applications/XX-Net/php_proxy/local/proxylib.py", line 726, in handle
self.do_ssl_handshake(handler)
File "/Applications/XX-Net/php_proxy/local/proxylib.py", line 713, in do_ssl_handshake
ssl_sock = ssl.wrap_socket(handler.connection, keyfile=certfile, certfile=certfile, server_side=True, ssl_version=self.ssl_method, ciphers=self.ciphers)
File "/Library/Python/2.7/site-packages/gevent/_sslgte279.py", line 636, in wrap_socket
ciphers=ciphers)
File "/Library/Python/2.7/site-packages/gevent/_sslgte279.py", line 223, in __init__
self.getpeername()
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
return getattr(self._sock,name)(*args)
error: [Errno 22] Invalid argument

Aug 25 17:25:21 - [INFO] 127.0.0.1:53080 "STRIP CONNECT fbcdn-photos-c-a.akamaihd.net:443 HTTP/1.1" - -
Aug 25 17:25:31 - [INFO] 127.0.0.1:53081 "STRIP CONNECT fbcdn-photos-c-a.akamaihd.net:443 HTTP/1.1" - -
Aug 25 17:25:41 - [INFO] 127.0.0.1:53082 "STRIP CONNECT fbcdn-photos-c-a.akamaihd.net:443 HTTP/1.1" - -
Aug 25 17:25:51 - [INFO] 127.0.0.1:53079 "PHP GET https://www.facebook.com/ HTTP/1.1" 200 -
Aug 25 17:25:51 - [INFO] 127.0.0.1:53083 "STRIP CONNECT fbcdn-photos-h-a.akamaihd.net:443 HTTP/1.1" - -
Aug 25 17:25:51 - [INFO] 127.0.0.1:53084 "STRIP CONNECT fbcdn-photos-h-a.akamaihd.net:443 HTTP/1.1" - -
Aug 25 17:25:51 - [INFO] 127.0.0.1:53085 "STRIP CONNECT fbcdn-photos-h-a.akamaihd.net:443 HTTP/1.1" - -
Aug 25 17:25:51 - [ERROR] ssl.wrap_socket(connection=) failed: [Errno 22] Invalid argument
Aug 25 17:25:51 - [INFO] 127.0.0.1:53086 "STRIP CONNECT fbcdn-profile-a.akamaihd.net:443 HTTP/1.1" - -
Aug 25 17:25:31 - [INFO] 127.0.0.1:53081 "STRIP CONNECT fbcdn-photos-c-a.akamaihd.net:443 HTTP/1.1" - -
Aug 25 17:25:41 - [INFO] 127.0.0.1:53082 "STRIP CONNECT fbcdn-photos-c-a.akamaihd.net:443 HTTP/1.1" - -
Aug 25 17:25:51 - [INFO] 127.0.0.1:53079 "PHP GET https://www.facebook.com/ HTTP/1.1" 200 -
Aug 25 17:25:51 - [INFO] 127.0.0.1:53083 "STRIP CONNECT fbcdn-photos-h-a.akamaihd.net:443 HTTP/1.1" - -
Aug 25 17:25:51 - [INFO] 127.0.0.1:53084 "STRIP CONNECT fbcdn-photos-h-a.akamaihd.net:443 HTTP/1.1" - -
Aug 25 17:25:51 - [INFO] 127.0.0.1:53085 "STRIP CONNECT fbcdn-photos-h-a.akamaihd.net:443 HTTP/1.1" - -
Aug 25 17:25:51 - [ERROR] ssl.wrap_socket(connection=) failed: [Errno 22] Invalid argument
Aug 25 17:25:51 - [ERROR] Except stack:Traceback (most recent call last):
File "/Applications/XX-Net/php_proxy/local/proxylib.py", line 726, in handle
self.do_ssl_handshake(handler)
File "/Applications/XX-Net/php_proxy/local/proxylib.py", line 713, in do_ssl_handshake
ssl_sock = ssl.wrap_socket(handler.connection, keyfile=certfile, certfile=certfile, server_side=True, ssl_version=self.ssl_method, ciphers=self.ciphers)
File "/Library/Python/2.7/site-packages/gevent/_sslgte279.py", line 636, in wrap_socket
ciphers=ciphers)
File "/Library/Python/2.7/site-packages/gevent/_sslgte279.py", line 223, in __init__
self.getpeername()
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
return getattr(self._sock,name)(*args)
error: [Errno 22] Invalid argument

Aug 25 17:25:51 - [INFO] 127.0.0.1:53087 "STRIP CONNECT fbcdn-profile-a.akamaihd.net:443 HTTP/1.1" - -
Aug 25 17:25:51 - [ERROR] ssl.wrap_socket(connection=) failed: [Errno 22] Invalid argument
Aug 25 17:25:51 - [ERROR] Except stack:Traceback (most recent call last):
File "/Applications/XX-Net/php_proxy/local/proxylib.py", line 726, in handle
self.do_ssl_handshake(handler)
File "/Applications/XX-Net/php_proxy/local/proxylib.py", line 713, in do_ssl_handshake
ssl_sock = ssl.wrap_socket(handler.connection, keyfile=certfile, certfile=certfile, server_side=True, ssl_version=self.ssl_method, ciphers=self.ciphers)
File "/Library/Python/2.7/site-packages/gevent/_sslgte279.py", line 636, in wrap_socket
ciphers=ciphers)
File "/Library/Python/2.7/site-packages/gevent/_sslgte279.py", line 223, in __init__
self.getpeername()
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
return getattr(self._sock,name)(*args)
error: [Errno 22] Invalid argument

**Comment by xxnet** [comment]
日志看，这个gevent也有问题。
暂时没有好办法，试试lantern或者goproxy吧

2015-08-25 17:28 GMT+08:00 causlayer <notifications@github.com>:

**Comment by causlayer** [comment]
那请问为何gaeproxy模块就没有问题，很流畅，而只是phpproxy模块有问题呢，之前没有这个问题的啊

**Comment by xxnet** [comment]
php_proxy 模块用到了gevent，而gae_proxy没有用gevent

在 2015年8月26日 上午9:22，causlayer <notifications@github.com>写道：

**Comment by causlayer** [comment]
我看最新版是修改了local目录下的cert_util.py文件导致的这个问题，之前都可以正常使用，这里可以在配置页面上做选择吗？因为mac下的gevent版本1.0.2就是最新的了，也还是不行，谢谢

**Comment by xxnet** [comment]
那你可以先退会早前的版本，cert_util的修改，对php_proxy 没有影响的

在 2015年8月26日 上午11:09，causlayer <notifications@github.com>写道：

**Comment by causlayer** [comment]
好的，希望能早点解决这个问题，谢谢
