### ISSUE TITLE
挂代理后无法登录，3.8.2版本login session fail, status:602

### ISSUE THREAD

**Issue by adgj8** [XX-net/XX-Net#8545]
在公司内网，使用公司代理出口
设置代理后，无法正常登录，尝试切换版本到3.7.18或者3.8.0均无法登录

![xx net](https://user-images.githubusercontent.com/4918336/33109136-e4c2f16a-cf7a-11e7-957b-308176c064da.png)
![xx net](https://user-images.githubusercontent.com/4918336/33109142-f2f0d7d4-cf7a-11e7-82cb-d100bce0a7fd.png)

---
另：建议将代理信息显示到状态页

**Comment by xxnet** [comment]
​贴 GAE日志和Cloudflare 日志看看

**Comment by chasingw** [comment]
@xxnet 我的也是602，登录不上
```
11月 22 14:38:42.1 [cloudflare_front][DEBUG] create_ssl update ip:104.25.68.215 time:1729 h2:0 sni:drop-books.com top:flar.tk
11月 22 14:38:42.2 [cloudflare_front][DEBUG] create_ssl update ip:141.101.113.198 time:1808 h2:0 sni:planningwales.com top:superx.gq
11月 22 14:38:43.3 [cloudflare_front][DEBUG] create_ssl update ip:190.93.244.222 time:1808 h2:0 sni:pusatinkubatorbayi.com top:c-term.tk
11月 22 14:38:48.4 [x_tunnel][WARNING] login session fail, status:602
11月 22 14:38:49.1 [cloudflare_front][ERROR] 190.93.245.85 h1_request:Exception('time out',) inactive_time:310 task.timeout:10
11月 22 14:38:49.1 [cloudflare_front][ERROR] Except stack:Traceback (most recent call last):
  File "/home/maxwell/Software/XX-Net/code/default/x_tunnel/local/cloudflare_front/http1.py", line 133, in request_task
    response.begin(timeout=timeout)
  File "/home/maxwell/Software/XX-Net/code/default/python27/1.0/lib/noarch/simple_http_client.py", line 168, in begin
    line = self.read_line(timeout)
  File "/home/maxwell/Software/XX-Net/code/default/python27/1.0/lib/noarch/simple_http_client.py", line 118, in read_line
    raise Exception("time out")
Exception: time out

11月 22 14:38:49.1 [cloudflare_front][WARNING] 190.93.245.85 trace: 0:connect, 866:init, 0:head, 353:head end, 299266:request,:11029, processed:0, transfered:0, sni:blacksdirectory.com

```
```
11月 22 14:38:54.7 [cloudflare_front][DEBUG] restore ip:104.16.70.158
11月 22 14:38:58.4 [x_tunnel][WARNING] login session fail, status:602
11月 22 14:39:01.3 [cloudflare_front][DEBUG] restore ip:190.93.245.131
11月 22 14:39:01.3 [x_tunnel][WARNING] api:/login fail:status:602 t:37
11月 22 14:39:01.3 [x_tunnel][WARNING] x-tunnel request_balance fail when create_conn:status:602
11月 22 14:39:01.3 [x_tunnel][WARNING] create conn fail
11月 22 14:39:01.3 [x_tunnel][DEBUG] session not running, try login..
11月 22 14:39:08.4 [x_tunnel][WARNING] login session fail, status:602
11月 22 14:39:11.0 [gae_proxy][DEBUG] create ssl timeout fail.
11月 22 14:39:11.4 [gae_proxy][WARNING] no enough ip
11月 22 14:39:18.4 [x_tunnel][WARNING] login session fail, status:602
11月 22 14:39:28.4 [x_tunnel][WARNING] login session fail, status:602
11月 22 14:39:34.3 [x_tunnel][WARNING] api:/login fail:status:602 t:33
11月 22 14:39:34.3 [x_tunnel][WARNING] x-tunnel request_balance fail when create_conn:status:602
11月 22 14:39:34.3 [x_tunnel][WARNING] Socks4 connect fail, no conn_id
11月 22 14:39:34.3 [x_tunnel][DEBUG] session not running, try login..
11月 22 14:39:38.4 [x_tunnel][WARNING] login session fail, status:602
11月 22 14:39:48.4 [x_tunnel][WARNING] login session fail, status:602
11月 22 14:39:58.5 [x_tunnel][WARNING] login session fail, status:602
11月 22 14:40:07.4 [x_tunnel][WARNING] api:/login fail:status:602 t:33
11月 22 14:40:07.4 [x_tunnel][WARNING] x-tunnel request_balance fail when create_conn:status:602
11月 22 14:40:07.4 [x_tunnel][WARNING] Socks4 connect fail, no conn_id
11月 22 14:40:07.4 [x_tunnel][DEBUG] session not running, try login..
11月 22 14:40:08.5 [x_tunnel][WARNING] login session fail, status:602
11月 22 14:40:11.0 [gae_proxy][DEBUG] create ssl timeout fail.
11月 22 14:40:11.0 [gae_proxy][WARNING] no enough ip
11月 22 14:40:11.4 [gae_proxy][WARNING] no enough ip
11月 22 14:40:11.5 [gae_proxy][WARNING] no enough ip
11月 22 14:40:12.0 [gae_proxy][WARNING] no enough ip
11月 22 14:40:12.5 [gae_proxy][WARNING] no enough ip
11月 22 14:40:13.0 [gae_proxy][WARNING] no enough ip
11月 22 14:40:13.5 [gae_proxy][WARNING] no enough ip
11月 22 14:40:14.1 [gae_proxy][WARNING] no enough ip
11月 22 14:40:14.6 [gae_proxy][WARNING] no enough ip
11月 22 14:40:15.1 [gae_proxy][WARNING] no enough ip
11月 22 14:40:15.6 [gae_proxy][WARNING] no enough ip
11月 22 14:40:18.5 [x_tunnel][WARNING] login session fail, status:602
```

**Comment by xxnet** [comment]
​@chasingw
 你把GAE 的诊断信息，X-Tunnel 的状态页，Cloudflare的日志，都贴出来

**Comment by JoJoZhan** [comment]
同样登录不了

**Comment by chasingw** [comment]
@xxnet 
GAE诊断信息：
```
XX-Net Status:

sys-platform: x86_64, Linux-4.4.0-98-generic-x86_64-with-Ubuntu-14.04-trusty
os-system: Linux
os-version: #121~14.04.1-Ubuntu SMP Wed Oct 11 11:54:55 UTC 2017
os-release: 4.4.0-98-generic
os-detail: Dist:Ubuntu; Version:14.04; ID:trusty
architecture: 64bit,ELF
browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
xxnet-version: 3.8.2
python-version: 2.7.6
openssl-version: 0.13 TLSv1 h2:no
use-ipv6: auto
gws-ip-num: total:0 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 20
ip-quality: 9999
is-idle: 1
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false
```
X-Tunnel 的状态页：

Cloudflare日志:
```
11月 23 08:02:03.2 - [DEBUG] updated cloudflare front domains from github fail:'Socket error: timed out'
11月 23 08:32:09.7 - [DEBUG] updated cloudflare front domains from github fail:'Socket error: timed out'
11月 23 09:02:16.2 - [DEBUG] updated cloudflare front domains from github fail:'Socket error: timed out'
11月 23 09:10:55.4 - [DEBUG] 190.93.247.209 close:get_timeout
11月 23 09:10:55.4 - [DEBUG] 104.27.53.152 close:get_timeout
11月 23 09:10:55.4 - [WARNING] get task but inactive time:65821
11月 23 09:10:55.4 - [DEBUG] 104.16.131.101 close:get_timeout
11月 23 09:10:55.4 - [DEBUG] 104.19.95.1 worker close:inactive timeout 65821
11月 23 09:10:55.4 - [DEBUG] 104.25.131.96 close:get_timeout
11月 23 09:10:55.4 - [WARNING] get task but inactive time:65821
11月 23 09:10:55.4 - [DEBUG] 162.159.228.176 close:get_timeout
11月 23 09:10:55.4 - [DEBUG] 104.20.171.19 worker close:inactive timeout 65821
11月 23 09:10:55.4 - [WARNING] get task but inactive time:65822
11月 23 09:10:55.4 - [DEBUG] 104.24.88.114 close:get_timeout
11月 23 09:10:55.4 - [DEBUG] 104.25.68.215 worker close:inactive timeout 65822
11月 23 09:10:55.4 - [DEBUG] 104.19.61.129 close:get_timeout
11月 23 09:10:55.4 - [DEBUG] 141.101.121.90 close:get_timeout
11月 23 09:10:55.9 - [DEBUG] create_ssl update ip:104.25.131.96 time:518 h2:0 sni:startup.global top:singlefly.tk
11月 23 09:10:56.0 - [DEBUG] head request 104.25.131.96
11月 23 09:10:56.5 - [DEBUG] create_ssl update ip:190.93.246.131 time:530 h2:0 sni:artesolecuador.com top:flar.tk
11月 23 09:10:56.5 - [DEBUG] head request 190.93.246.131
11月 23 09:10:57.2 - [DEBUG] create_ssl update ip:162.159.228.176 time:749 h2:0 sni:trustedcasementwindows.com top:movistar.gq
11月 23 09:10:57.2 - [DEBUG] head request 162.159.228.176
11月 23 09:10:57.8 - [DEBUG] create_ssl update ip:104.24.88.114 time:825 h2:0 sni:cottontocashmere.com top:superx.gq
11月 23 09:10:57.8 - [DEBUG] head request 104.24.88.114
11月 23 09:10:58.0 - [DEBUG] create_ssl update ip:104.16.131.101 time:499 h2:0 sni:journomate.com top:flar.tk
11月 23 09:10:58.0 - [DEBUG] head request 104.16.131.101
11月 23 09:10:58.0 - [WARNING] POST center.singlefly.tk/login status:403 trace:0:start_request,0:get_task(65822),0:get_worker(0):104.19.95.1,0:retry,0:get_task(0),0:get_worker(0):104.20.171.19,0:retry,0:get_task(0),0:get_worker(0):104.25.68.215,0:retry,0:get_task(0),2375:get_worker(2):104.25.131.96,0:h1_req,0:h1_req_sended,171:response_begin,0:h1_get_head,0:h1_finish[SP:1004],0:get_response,:0
11月 23 09:10:58.0 - [DEBUG] create_ssl update ip:104.27.53.152 time:547 h2:0 sni:switchsitiosweb.com top:movistar.gq
11月 23 09:10:58.7 - [DEBUG] create_ssl update ip:141.101.121.90 time:778 h2:0 sni:weerstationbennekom.nl top:superx.gq
11月 23 09:10:58.8 - [DEBUG] create_ssl update ip:104.19.61.129 time:1810 h2:0 sni:familychiropracticwny.com top:movistar.gq
11月 23 09:10:58.9 - [DEBUG] create_ssl update ip:190.93.247.209 time:735 h2:0 sni:planningwales.com top:superx.gq
11月 23 09:10:59.0 - [DEBUG] create_ssl update ip:104.24.91.106 time:557 h2:0 sni:alkes.me top:c-term.tk
11月 23 09:10:59.3 - [DEBUG] create_ssl update ip:190.93.244.39 time:506 h2:0 sni:techbestadsweb.site top:flar.tk
11月 23 09:15:58.4 - [DEBUG] 190.93.244.39 close:get_timeout
11月 23 09:15:58.4 - [DEBUG] 104.27.53.152 close:get_timeout
11月 23 09:15:58.4 - [DEBUG] 104.24.91.106 close:get_timeout
11月 23 09:15:58.4 - [DEBUG] 190.93.247.209 close:get_timeout
11月 23 09:15:58.4 - [DEBUG] 141.101.121.90 close:get_timeout
11月 23 09:15:58.4 - [DEBUG] 104.19.61.129 close:get_timeout
11月 23 09:15:58.5 - [WARNING] POST center.flar.tk/login status:403 trace:0:start_request,0:get_task(300),0:get_worker(0):104.16.131.101,0:h1_req,0:h1_req_sended,171:response_begin,0:h1_get_head,0:h1_finish[SP:1003],0:get_response,:0
11月 23 09:15:59.2 - [DEBUG] create_ssl update ip:104.27.53.152 time:834 h2:0 sni:slybailbonds.com top:freenum.cf
11月 23 09:15:59.2 - [DEBUG] head request 104.27.53.152
11月 23 09:15:59.3 - [DEBUG] create_ssl update ip:141.101.121.90 time:483 h2:0 sni:gloryamedica.com top:c-term.tk
11月 23 09:16:00.1 - [DEBUG] create_ssl update ip:190.93.247.209 time:696 h2:0 sni:xhappynewyear2018.com top:flar.tk
11月 23 09:16:00.4 - [DEBUG] create_ssl update ip:104.24.91.106 time:566 h2:0 sni:bcstandart.ru top:dragon-dreamer.com
11月 23 09:16:00.7 - [DEBUG] create_ssl update ip:190.93.244.39 time:509 h2:0 sni:jualdefibrillator.com top:c-term.tk
11月 23 09:16:00.8 - [DEBUG] create_ssl update ip:104.20.144.33 time:491 h2:0 sni:audiodim.me top:c-term.tk
11月 23 09:16:00.9 - [DEBUG] create_ssl update ip:198.41.221.213 time:527 h2:0 sni:franklinmahotel.com top:freenum.cf
11月 23 09:20:59.0 - [WARNING] POST center.flar.tk/login status:403 trace:0:start_request,0:get_task(300),0:get_worker(0):104.16.131.101,0:h1_req,0:h1_req_sended,174:response_begin,0:h1_get_head,0:h1_finish[SP:989],0:get_response,:0
```

**Comment by xxnet** [comment]
​cloudflare h1 模式有bug，正在研究，解决了就出新版。

OpenSSL 如果能够升级到支持h2的新版，应该也能解决问题。

**Comment by chasingw** [comment]
@xxnet 升级了v3.8.3 可以了, 赞 谢谢

**Comment by adgj8** [comment]
同上，升级后解决
