### ISSUE TITLE
GAEProxy启动不起来了

### ISSUE THREAD

**Issue by lichunqiang** [XX-net/XX-Net#874]
```
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 59622)
Traceback (most recent call last):
  File "D:\XX-Net-2.1.1\python27\1.0\lib\SocketServer.py", line 593, in process
request_thread
    self.finish_request(request, client_address)
  File "D:\XX-Net-2.1.1\launcher\web_control.py", line 48, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "D:\XX-Net-2.1.1\python27\1.0\lib\SocketServer.py", line 649, in __init_

    self.handle()
  File "D:\XX-Net-2.1.1\python27\1.0\lib\BaseHTTPServer.py", line 340, in handl

    self.handle_one_request()
  File "D:\XX-Net-2.1.1\python27\1.0\lib\BaseHTTPServer.py", line 328, in handl
_one_request
    method()
  File "D:\XX-Net-2.1.1\launcher\web_control.py", line 143, in do_GET
    controler = module_init.proc_handler[module]["imp"].local.web_control.Contr
lHandler(self.client_address, self.headers, self.command, path, self.rfile, sel
.wfile)
KeyError: 'imp'
```

**Comment by xxnet** [comment]
把启动的日志贴出来，似乎是启动失败了

2015-08-27 16:15 GMT+08:00 李某某 <notifications@github.com>:

**Comment by lichunqiang** [comment]
重新删了，下载最新的安上好了  - - ！
