### ISSUE TITLE
macos 10.13.1 打不开 没有图标

### ISSUE THREAD

**Issue by IamHimon** [XX-net/XX-Net#8757]
* 是否试过最新的测试版本？
  很多问题在最新测试版中已解决。
  

* 是否看过Issues区最近的讨论？
  请在 (https://github.com/XX-net/XX-Net/issues) 搜索有无类似的问题。
  

* 是否查看过Wiki（https://github.com/XX-net/XX-Net/wiki）
  请阅读[故障速查手册](https://github.com/XX-net/XX-Net/wiki/故障速查手册)，大部分问题都能在这里找到答案。

* 简单描述遇到的问题：

* 做过哪些尝试：

* 请贴出对应模块的状态页

* 请贴出相关的日志

## 常见问题：  
* 扫描不到GAE的ip  
   请尝试启用IPv6，参考  
   https://github.com/XX-net/XX-Net/wiki/%E5%A6%82%E4%BD%95%E5%BC%80%E5%90%AFIPv6    
   
   或者试试X-Tunnel 模块  
   https://github.com/XX-net/XX-Net/wiki/x-tunnel%E4%BD%BF%E7%94%A8%E6%95%99%E7%A8%8B  
   
* X-tunnel 无法连接  
  如果能够登录，请确认代理端口为1080.
  如果速度不稳定或无法登录，请贴出X-Tunnel 的Status页面。

**Comment by xxnet** [comment]
用哪个版本？

试试前面几个版本，确认是不是新版改出来的bug

**Comment by IamHimon** [comment]
@xxnet 试了最新版3.8.3，以及之前的版本3.4.0都不行,  可能macos最新版本不支持了。我还买了流量，，，希望你们赶紧搞定这个bug啊。嘻嘻

**Comment by xxnet** [comment]
​直接访问 http://127.0.0.1:8085 可以吗？

不行的话，贴出启动日志看看

**Comment by IamHimon** [comment]
@xxnet 如果双击start，启动日志：
`XX-Net version:default
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[进程已完成]`

如果在命令行 ./start 启动，日志：
`XX-Net version:default`

**Comment by IamHimon** [comment]
@xxnet 我在命令行执行: 
`Traceback (most recent call last):
  File "code/default/launcher/start.py", line 49, in <module>
    from xlog import getLogger
  File "/Users/himon/apps/XX-Net-3.7.10/code/default/python27/1.0/lib/noarch/xlog.py", line 262, in <module>
    default_log = getLogger()
  File "/Users/himon/apps/XX-Net-3.7.10/code/default/python27/1.0/lib/noarch/xlog.py", line 248, in getLogger
    if not isinstance(name, basestring):
NameError: name 'basestring' is not defined`
我的python是3.6.2的， 好像是是这个'basestring'在python3中没有了，但是怎么改呢？我也不能将python3降到python2.

**Comment by onplus** [comment]
mac系统不是自带python2吗？

**Comment by IamHimon** [comment]
@onplus 但是，我工作需要，装了python3。不知道换成python2之后回不回好。但是很多人反应macos新系统没法用xxnet。

**Comment by IamHimon** [comment]
@xxnet 我自己更改了对应文件的内容, 单纯从python版本角度出发，google了一个方案：‘ basestring’-> 'str', 'unicode'->'str'，
重新执行： `python code/default/launcher/start.py`，又出现下面错误：（从‘Nov’开始是红色字体）
`Nov 30 20:45:12.141 [b'launcher'][INFO] use build-in openssl lib
uncaught Exception: <class 'ModuleNotFoundError'> No module named 'urlparse' <traceback object at 0x10d1591c8>
Nov 30 20:45:12.142 [b'launcher'][ERROR] uncaught Exception, type=<class 'ModuleNotFoundError'> value=No module named 'urlparse' traceback:<traceback object at 0x10d1591c8>`

**Comment by onplus** [comment]
`code/default/python27/1.0/python  code/default/launcher/statrt.py `

**Comment by onplus** [comment]
系统python你也删了？

**Comment by IamHimon** [comment]
@onplus 系统python当然没删，但是改系统的python版本不是治标的解决方案啊。

**Comment by saintethan** [comment]
可以修改一下xx-net的python文档，在第一行加上你系统内python2的执行路径。

**Comment by IamHimon** [comment]
@saintethan 修改哪一个文件呢？

**Comment by xxnet** [comment]
​先命令行启动吧：

你系统的python2.7  code/default/launcher/statrt.py
