### ISSUE TITLE
状态页空白 start.bat报错HttpError

### ISSUE THREAD

**Issue by jxiaolong** [XX-net/XX-Net#890]
Aug 30 23:01:03 - [INFO] SSL use version:TLSv1
Aug 30 23:01:04 - [INFO] ------------------------------------------------------
GAEProxy Version   : gae_proxy (python/2.7.9)
Listen Address     : 127.0.0.1:8087
GAE APPID          : xxnet-1|xxnet-2|xxnet-3|xxnet-4|xxnet-5|xxnet-6|xxnet-7|xxnet-8|xxnet-9|xxnet-10|xxnet-11|xxnet-12
xxnet-13|xxnet-14|xxnet-15|xxnet-16|xxnet-17|xxnet-18|xxnet-19|xxnet-20|xxnet-21|xxnet-22|xxnet-23|xxnet-24|xxnet-25|xx
et-26|xxnet-27|xxnet-28|xxnet-29|xxnet-30|xxnet-31|xxnet-32|xxnet-33|xxnet-34|xxnet-35|xxnet-36|xxnet-37|xxnet-38|xxnet
39|xxnet-40|xxnet-41|xxnet-42|xxnet-43|xxnet-44|xxnet-45|xxnet-46|xxnet-47|xxnet-48|xxnet-49|xxnet-50|xxnet-51|xxnet-52
xxnet-53|xxnet-54|xxnet-55|xxnet-56|xxnet-57|xxnet-58|xxnet-59|xxnet-60|xxnet-61|xxnet-62|xxnet-63|xxnet-64|xxnet-65|xx
et-66|xxnet-67|xxnet-68|xxnet-69|xxnet-70|xxnet-71|xxnet-72|xxnet-72|xxnet-73|xxnet-74|xxnet-75|xxnet-76|xxnet-77|xxnet
78|xxnet-79|xxnet-80|xxnet-81|xxnet-82|xxnet-83|xxnet-84|xxnet-85|xxnet-86|xxnet-87|xxnet-88|xxnet-89|xxnet-90|xxnet-91
xxnet-92|xxnet-93|xxnet-94|xxnet-95|xxnet-96|xxnet-97|xxnet-98|xxnet-99|xxnet-100|xxnet-101|xxnet-102|xxnet-103|xxnet-1
4|xxnet-105|xxnet-106|xxnet-107|xxnet-108|xxnet-109|xxnet-110|xxnet-111|xxnet-112|xxnet-113|xxnet-114|xxnet-115|xxnet-1
6|xxnet-117|xxnet-118|xxnet-119|xxnet-120|xxnet-121|xxnet-122|xxnet-123|xxnet-124|xxnet-125|xxnet-126|xxnet-127|xxnet-1
8|xxnet-129|xxnet-130|xxnet-131|xxnet-132|xxnet-133|xxnet-134|xxnet-135|xxnet-136|xxnet-137|xxnet-138|xxnet-139|xxnet-1
0|xxnet-141|xxnet-142|xxnet-143|xxnet-144|xxnet-145|xxnet-146|xxnet-147|xxnet-148|xxnet-149|xxnet-150|xxnet-151|xxnet-1
2|xxnet-153|xxnet-154|xxnet-155|xxnet-156|xxnet-157|xxnet-158|xxnet-159
Pac Server         : http://127.0.0.1:8086/proxy.pac
------------------------------------------------------

Aug 30 23:01:04 - [INFO] gae_proxy started
Aug 30 23:01:04 - [INFO] start gae_proxy time cost 1573
Aug 30 23:01:05 - [INFO] get uuid:67598092-17dc-46b6-a379-36b2f1afdc94
Aug 30 23:01:12 - [WARNING] check_update fail:HTTPError()
Aug 30 23:01:12 - [INFO] download https://raw.githubusercontent.com/XX-net/XX-Net/master/README.md to D:\代理\XX-Net-2.
.2\data\downloads\README.md

**Comment by xxnet** [comment]
这个错误只是检查升级失败，不影响后面使用

2015-08-30 23:09 GMT+08:00 jxiaolong <notifications@github.com>:

**Comment by jxiaolong** [comment]
但是我状态也完全空白，GAEProxy 启动失败！

**Comment by zrz2035** [comment]
我的状态也是空白，按照您的解决方案做了之后还是的，运行start.bat是这样的
![33](https://cloud.githubusercontent.com/assets/12880753/9571550/e1b66036-4fd1-11e5-99c2-a37de2654237.jpg)

**Comment by zrz2035** [comment]
@xxnet  我是昨天晚上用了今天早上再打开就空白了，这是什么原因导致的启动错误呢？如何避免呢？

**Comment by jxiaolong** [comment]
我使用了，稳定版跟测试版，两个版本都报错，状态页都空白！

**Comment by xxnet** [comment]
@zrz2035
请滚动到最上面看最先出错的那几行

在 2015年8月31日 上午11:22，jxiaolong <notifications@github.com>写道：

**Comment by jxiaolong** [comment]
@xxnet 

D:\代理\XX-Net-2.0.5>"D:\代理\XX-Net-2.0.5\python27/1.0/python.exe" "D:\代理\XX-Net-2.0.5\launcher/start.py"
Aug 31 12:07:04 - [DEBUG] start confirm_xxnet_exit
Aug 31 12:07:05 - [ERROR] start module gae_proxy fail:No module named _memimporter
Traceback (most recent call last):
  File "D:\代理\XX-Net-2.0.5\launcher\module_init.py", line 34, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "D:\代理\XX-Net-2.0.5\gae_proxy\start.py", line 13, in <module>
    import local.proxy as client
  File "D:\代理\XX-Net-2.0.5\gae_proxy\local\proxy.py", line 77, in <module>
    from cert_util import CertUtil
  File "D:\代理\XX-Net-2.0.5\gae_proxy\local\cert_util.py", line 37, in <module>
    import OpenSSL
  File "D:\代理\XX-Net-2.0.5\python27\1.0\lib\win32\OpenSSL\__init__.py", line 26, in <module>
    from OpenSSL import crypto, rand, SSL
  File "D:\代理\XX-Net-2.0.5\python27\1.0\lib\win32\OpenSSL\crypto.py", line 11, in <module>
    __bootstrap__()
  File "D:\代理\XX-Net-2.0.5\python27\1.0\lib\win32\OpenSSL\crypto.py", line 3, in __bootstrap__
    import _memimporter, sys
ImportError: No module named _memimporter

Aug 31 12:07:05 - [INFO] start gae_proxy time cost 32
Aug 31 12:07:06 - [INFO] get uuid:802bea74-23d5-423d-9558-24d0bb744ff6
Aug 31 12:07:07 - [WARNING] check_update fail:URLError(error(10061, ''),)
Aug 31 12:07:07 - [INFO] download https://raw.githubusercontent.com/XX-net/XX-Net/master/README.md to D:\代理\XX-Net-2.0
.5\data\downloads\README.md
Aug 31 12:07:08 - [ERROR] download https://raw.githubusercontent.com/XX-net/XX-Net/master/README.md to D:\代理\XX-Net-2.
0.5\data\downloads\README.md fail:URLError(error(10061, ''),)
Traceback (most recent call last):
  File "D:\代理\XX-Net-2.0.5\launcher\update_from_github.py", line 64, in download_file
    req = opener.open(url)
  File "D:\代理\XX-Net-2.0.5\python27\1.0\lib\urllib2.py", line 404, in open
    response = self._open(req, data)
  File "D:\代理\XX-Net-2.0.5\python27\1.0\lib\urllib2.py", line 422, in _open
    '_open', req)
  File "D:\代理\XX-Net-2.0.5\python27\1.0\lib\urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "D:\代理\XX-Net-2.0.5\python27\1.0\lib\urllib2.py", line 1222, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "D:\代理\XX-Net-2.0.5\python27\1.0\lib\urllib2.py", line 1184, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 10061] >

Aug 31 12:07:08 - [ERROR] check_update fail:IOError('get README https://raw.githubusercontent.com/XX-net/XX-Net/master/R
EADME.md fail:',)
Traceback (most recent call last):
  File "D:\代理\XX-Net-2.0.5\launcher\update.py", line 241, in check_update
    versions = update_from_github.get_github_versions()
  File "D:\代理\XX-Net-2.0.5\launcher\update_from_github.py", line 106, in get_github_versions
    raise IOError("get README %s fail:" % readme_url)
IOError: get README https://raw.githubusercontent.com/XX-net/XX-Net/master/README.md fail:

**Comment by zrz2035** [comment]
@xxnet 这次运行是这样子的了
![22222](https://cloud.githubusercontent.com/assets/12880753/9572064/7e455f52-4fdb-11e5-885f-910b4a4da924.jpg)

**Comment by xxnet** [comment]
这个错误很奇怪，网上竟然没有找到相关报告。
  请停掉各种杀掉软件试试

2015-08-31 12:26 GMT+08:00 zrz2035 <notifications@github.com>:

**Comment by jxiaolong** [comment]
停掉杀软一样不可以！

**Comment by zrz2035** [comment]
我都没有用杀毒软件……我之前下载过一个畅游版的chrome，那个自带的XXnet一直是好的，会不会是跟xxnet放置的目录有关系呢？我自己下载的是放在D盘的，我的默认chrome浏览器是放在C盘的

**Comment by xxnet** [comment]
恩，各种可能都试试。
先停杀毒软件，然后重新解压一个原始的zip文件试试启动。
还有试试放在不同目录下。

@zrz2035
   畅游版的chrome，那个自带的XXnet可以工作
   你的情况非常好，请研究看看规律是什么。
   从可以工作的版本开始
   逐步把其变到无法工作的版本的状态，看在那一步出现问题。

在 2015年8月31日 下午1:27，zrz2035 <notifications@github.com>写道：
