### ISSUE TITLE
把gae-agent作为calibre的代理出现问题

### ISSUE THREAD

**Issue by Curriculu** [XX-net/XX-Net#8956]
在calibre中抓取新闻的时候，有时候抓取某些站点的新闻的时候需要使用代理。使用gae agent作为calibre的代理时，calibre自身可以识别，但是在抓取的时候会出现ssl_cerficate无法识别的问题。错误信息如下：
Python function terminated unexpectedly
  <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)> (Error Code: 1)
Traceback (most recent call last):
  File "site.py", line 101, in main
  File "site.py", line 78, in run_entry_point
  File "site-packages\calibre\utils\ipc\worker.py", line 195, in main
  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 26, in gui_convert
  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1088, in run
  File "site-packages\calibre\customize\conversion.py", line 245, in __call__
  File "site-packages\calibre\ebooks\conversion\plugins\recipe_input.py", line 119, in convert
  File "site-packages\calibre\web\feeds\news.py", line 1023, in download
  File "site-packages\calibre\web\feeds\news.py", line 1190, in build_index
  File "<string>", line 48, in parse_index
  File "<string>", line 56, in parse_section
  File "site-packages\calibre\web\feeds\news.py", line 675, in index_to_soup
  File "site-packages\mechanize\_mechanize.py", line 239, in open_novisit
  File "site-packages\mechanize\_mechanize.py", line 284, in _mech_open
  File "site-packages\mechanize\_opener.py", line 195, in open
  File "site-packages\mechanize\_urllib2_fork.py", line 352, in _open
  File "site-packages\mechanize\_urllib2_fork.py", line 340, in _call_chain
  File "site-packages\calibre\utils\browser.py", line 28, in https_open
  File "site-packages\mechanize\_urllib2_fork.py", line 1160, in do_open
urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>
这个问题在不同版本的xx-net里面都出现过，在3.8.3版本里面没有出现，但是在现在使用的3.8.5里面每一个抓取的新闻都出现了这样的错误信息。请教一下怎么处理

**Comment by SeaHOH** [comment]
证书导入系统没有？

**Comment by Curriculu** [comment]
不知道啊，就是导入了默认浏览器而已。我用的是chrome，手动导入了浏览器的证书里。

**Comment by xxnet** [comment]
证书​需要导入到操作系统，不想折腾就用x-tunnel

**Comment by Curriculu** [comment]
导入到了操作系统里面还是有问题，一样的错误情况。
