### ISSUE TITLE
3.8.6测试版无法启动，code/version.txt 改成3.8.5版正常使用

### ISSUE THREAD

**Issue by loveFeng** [XX-net/XX-Net#8958]
XX-Net version:3.8.6
12月 11 14:58:43.2 [launcher][INFO] import build-in openssl fail:ImportError('No module named pycparser',)
12月 11 14:58:43.2 [launcher][INFO] start XX-Net 3.8.6
12月 11 14:58:43.2 [launcher][DEBUG] start confirm_xxnet_exit
12月 11 14:58:43.2 [launcher][DEBUG] good, xxnet:8085 clear!
12月 11 14:58:43.2 [launcher][DEBUG] finished confirm_xxnet_exit
12月 11 14:58:43.2 [gae_proxy][INFO] load manual.ini success
12月 11 14:58:43.2 [gae_proxy][INFO] SSL use version:TLSv1
12月 11 14:58:43.2 [gae_proxy][INFO] OpenSSL dont't support npn/alpn, no HTTP/2 supported.
12月 11 14:58:43.2 [gae_proxy][INFO] load ip range file:/home/xxx/xxx/proxy/XX-Net/code/3.8.6/gae_proxy/local/ip_range.txt
12月 11 14:58:43.3 [gae_proxy][INFO] load google ip_list num:6000, gws num:6000
12月 11 14:58:43.3 [gae_proxy][INFO] load manual.ini success
12月 11 14:58:43.3 [gae_proxy][DEBUG] ## GAEProxy set keep_running: True
12月 11 14:58:43.3 [gae_proxy][INFO] ------------------------------------------------------
12月 11 14:58:43.3 [gae_proxy][INFO] Python Version     : 2.7.6
12月 11 14:58:43.3 [gae_proxy][INFO] OS                 : Dist:LinuxMint; Version:17; ID:qiana
12月 11 14:58:43.3 [gae_proxy][INFO] Listen Address     : 127.0.0.1:8087
12月 11 14:58:43.3 [gae_proxy][INFO] GAE APPID          : xxx
12月 11 14:58:43.3 [gae_proxy][INFO] Pac Server         : http://127.0.0.1:8086/proxy.pac
12月 11 14:58:43.3 [gae_proxy][INFO] ------------------------------------------------------
Exception in thread Thread-30:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/xxx/xxx/proxy/XX-Net/code/3.8.6/gae_proxy/start.py", line 18, in main
    client.main()
  File "/home/xxx/xxx/proxy/XX-Net/code/3.8.6/gae_proxy/local/proxy.py", line 153, in main
    CertUtil.init_ca()
  File "/home/xxx/xxx/proxy/XX-Net/code/3.8.6/gae_proxy/local/cert_util.py", line 606, in init_ca
    CertUtil.cert_publickey = OpenSSL.crypto.load_publickey(OpenSSL.crypto.FILETYPE_PEM, fp.read())
AttributeError: 'module' object has no attribute 'load_publickey'

12月 11 14:58:43.7 [gae_proxy][DEBUG] network IPv4 is ok, cost:502 ms
12月 11 14:58:44.4 [gae_proxy][DEBUG] network IPv6 is ok, cost:1178 ms

**Comment by xxnet** [comment]
​3.8.7 修复上面的问题，请测试

**Comment by gjbg1989** [comment]
新特性：修复Linux/Android 下，老的pyOpenSSL 支持问题。
原以为只与Linux/Android相关，Win系统忽略此版的😱，试试。。。
