### ISSUE TITLE
无法启动 之前正常 如何解决chrome最近卡的不行

### ISSUE THREAD

**Issue by LuoboWang1** [XX-net/XX-Net#8980]
Dec 12 19:30:03.442 [launcher][ERROR] start module gae_proxy fail:cannot import name __version__
Dec 12 19:30:03.458 [launcher][ERROR] Except stack:Traceback (most recent call last):
  File "D:\Program Files\XX-Net-3.3.4\code\default\launcher\module_init.py", line 38, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "D:\Program Files\XX-Net-3.3.4\code\default\gae_proxy\local\__init__.py", line 2, in <module>
    import apis
  File "D:\Program Files\XX-Net-3.3.4\code\default\gae_proxy\local\apis.py", line 1, in <module>
    from web_control import user_config
  File "D:\Program Files\XX-Net-3.3.4\code\default\gae_proxy\local\web_control.py", line 27, in <module>
    from appids_manager import appid_manager
  File "D:\Program Files\XX-Net-3.3.4\code\default\gae_proxy\local\appids_manager.py", line 11, in <module>
    import check_ip
  File "D:\Program Files\XX-Net-3.3.4\code\default\gae_proxy\local\check_ip.py", line 53, in <module>
    import cert_util
  File "D:\Program Files\XX-Net-3.3.4\code\default\gae_proxy\local\cert_util.py", line 43, in <module>
    from pyasn1.codec.der.decoder import decode
  File "D:\Program Files\XX-Net-3.3.4\code\default\python27\1.0\lib\noarch\pyasn1\codec\der\decoder.py", line 3, in <module>
    from pyasn1.codec.cer import decoder
  File "D:\Program Files\XX-Net-3.3.4\code\default\python27\1.0\lib\noarch\pyasn1\codec\cer\decoder.py", line 3, in <module>
    from pyasn1.codec.ber import decoder
  File "D:\Program Files\XX-Net-3.3.4\code\default\python27\1.0\lib\noarch\pyasn1\codec\ber\decoder.py", line 5, in <module>
    from pyasn1 import debug, error
  File "D:\Program Files\XX-Net-3.3.4\code\default\python27\1.0\lib\noarch\pyasn1\debug.py", line 4, in <module>
    from pyasn1 import __version__
ImportError: cannot import name __version__

Dec 12 19:30:03.458 [launcher][ERROR] launcher except:ImportError('cannot import name __version__',)
Dec 12 19:30:03.474 [launcher][ERROR] Except stack:Traceback (most recent call last):
  File "D:\Program Files\XX-Net-3.3.4\code\default\launcher\start.py", line 221, in <module>
    main()
  File "D:\Program Files\XX-Net-3.3.4\code\default\launcher\start.py", line 198, in main
    module_init.start_all_auto()
  File "D:\Program Files\XX-Net-3.3.4\code\default\launcher\module_init.py", line 111, in start_all_auto
    start(module)
  File "D:\Program Files\XX-Net-3.3.4\code\default\launcher\module_init.py", line 38, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "D:\Program Files\XX-Net-3.3.4\code\default\gae_proxy\local\__init__.py", line 2, in <module>
    import apis
  File "D:\Program Files\XX-Net-3.3.4\code\default\gae_proxy\local\apis.py", line 1, in <module>
    from web_control import user_config
  File "D:\Program Files\XX-Net-3.3.4\code\default\gae_proxy\local\web_control.py", line 27, in <module>
    from appids_manager import appid_manager
  File "D:\Program Files\XX-Net-3.3.4\code\default\gae_proxy\local\appids_manager.py", line 11, in <module>
    import check_ip
  File "D:\Program Files\XX-Net-3.3.4\code\default\gae_proxy\local\check_ip.py", line 53, in <module>
    import cert_util
  File "D:\Program Files\XX-Net-3.3.4\code\default\gae_proxy\local\cert_util.py", line 43, in <module>
    from pyasn1.codec.der.decoder import decode
  File "D:\Program Files\XX-Net-3.3.4\code\default\python27\1.0\lib\noarch\pyasn1\codec\der\decoder.py", line 3, in <module>
    from pyasn1.codec.cer import decoder
  File "D:\Program Files\XX-Net-3.3.4\code\default\python27\1.0\lib\noarch\pyasn1\codec\cer\decoder.py", line 3, in <module>
    from pyasn1.codec.ber import decoder
  File "D:\Program Files\XX-Net-3.3.4\code\default\python27\1.0\lib\noarch\pyasn1\codec\ber\decoder.py", line 5, in <module>
    from pyasn1 import debug, error
  File "D:\Program Files\XX-Net-3.3.4\code\default\python27\1.0\lib\noarch\pyasn1\debug.py", line 4, in <module>
    from pyasn1 import __version__
ImportError: cannot import name __version__

**Comment by gjbg1989** [comment]
https://github.com/XX-net/XX-Net
X-Tunnel 请升级到3.8.5 （使用教程）
GAE: 扫不到ip，请开启ipv6，请参考： 如何开启IPv6

**Comment by LuoboWang1** [comment]
我是3.8.4只是文件夹名字一直没变。现在看来正常开启了。但是最小化没有显示，任务管理器后台进程才能看到，不知为何。

**Comment by gjbg1989** [comment]
哦，最小化没有显示——不是被任务栏折叠隐藏了？
卡的不行—— #8915 tertdo.bat自动或手动优选服务器，文件解压放在 XX-Net 程序的根目录

**Comment by LuoboWang1** [comment]
teredo.zip下载不了 解决方法太复杂 目前就这个样子等有空再弄。

**Comment by gjbg1989** [comment]
FQ 下载？

**Comment by LuoboWang1** [comment]
突然自行恢复不知为何 目前一期正常 感谢
