### ISSUE TITLE
部署服务器端错误

### ISSUE THREAD

**Issue by comandosne** [XX-net/XX-Net#90]
Mar 30 21:14:22 - Scanning files on local disk.
Mar 30 21:14:51 - ERROR:root:An unexpected error occurred. Aborting.
Traceback (most recent call last):
  File "C:\Users\Fei\Downloads\XX-Net-1.4.0\goagent\3.1.41\server\lib\google\appengine\tools\appcfg.py", line 2070, in DoUpload
    missing_files = self.Begin()
  File "C:\Users\Fei\Downloads\XX-Net-1.4.0\goagent\3.1.41\server\lib\google\appengine\tools\appcfg.py", line 1740, in Begin
    self.Send('/api/appversion/create', payload=self.config.ToYAML())
  File "C:\Users\Fei\Downloads\XX-Net-1.4.0\goagent\3.1.41\server\lib\google\appengine\tools\appcfg.py", line 1698, in Send
    return self.rpcserver.Send(url, payload=payload, **self.params)
  File "C:\Users\Fei\Downloads\XX-Net-1.4.0\goagent\3.1.41\server\lib\google\appengine\tools\appengine_rpc.py", line 380, in Send
    self._Authenticate()
  File "C:\Users\Fei\Downloads\XX-Net-1.4.0\goagent\3.1.41\server\lib\google\appengine\tools\appengine_rpc.py", line 438, in _Authenticate
    super(HttpRpcServer, self)._Authenticate()
  File "C:\Users\Fei\Downloads\XX-Net-1.4.0\goagent\3.1.41\server\lib\google\appengine\tools\appengine_rpc.py", line 321, in _Authenticate
    self._GetAuthCookie(auth_token)
  File "C:\Users\Fei\Downloads\XX-Net-1.4.0\goagent\3.1.41\server\lib\google\appengine\tools\appengine_rpc.py", line 255, in _GetAuthCookie
    response = self.opener.open(req)
  File "C:\Users\Fei\Downloads\XX-Net-1.4.0\python27\1.0\lib\urllib2.py", line 404, in open
    response = self._open(req, data)
  File "C:\Users\Fei\Downloads\XX-Net-1.4.0\python27\1.0\lib\urllib2.py", line 422, in _open
    '_open', req)
  File "C:\Users\Fei\Downloads\XX-Net-1.4.0\python27\1.0\lib\urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "C:\Users\Fei\Downloads\XX-Net-1.4.0\python27\1.0\lib\urllib2.py", line 1222, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "C:\Users\Fei\Downloads\XX-Net-1.4.0\python27\1.0\lib\urllib2.py", line 1187, in do_open
    r = h.getresponse(buffering=True)
  File "C:\Users\Fei\Downloads\XX-Net-1.4.0\python27\1.0\lib\httplib.py", line 1045, in getresponse
    response.begin()
  File "C:\Users\Fei\Downloads\XX-Net-1.4.0\python27\1.0\lib\httplib.py", line 409, in begin
    version, status, reason = self._read_status()
  File "C:\Users\Fei\Downloads\XX-Net-1.4.0\python27\1.0\lib\httplib.py", line 365, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "C:\Users\Fei\Downloads\XX-Net-1.4.0\python27\1.0\lib\socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
  File "C:\Users\Fei\Downloads\XX-Net-1.4.0\python27\1.0\lib\ssl.py", line 241, in recv
    return self.read(buflen)
  File "C:\Users\Fei\Downloads\XX-Net-1.4.0\python27\1.0\lib\ssl.py", line 160, in read
    return self._sslobj.read(len)
SSLError: The read operation timed out
Mar 30 21:14:51 - upload  fail: The read operation timed out

Mar 30 21:14:51 - Retry again.

**Comment by xxnet** [comment]
最近GFW对https的域名干扰严重，需要再研究新的方法。

听说你过半小时后再试试，可能就能再成功几个。

2015-03-30 9:28 GMT-04:00 comandosne <notifications@github.com>:

**Comment by xxnet** [comment]
1.7 已经解决
