### ISSUE TITLE
openwrt运行xx-net，报错 Try install python-openssl

### ISSUE THREAD

**Issue by uncledragon** [XX-net/XX-Net#9025]
硬件：小米路由器mini，16M内存，挂了32gu盘，128ram
系统：openwrt 15.01.1，已经安装了 python  python-openssl pyopenssl_0.10-1_ramips_24kec

 直接执行  ./XX-Net-3.8.7/start， 报错-ash: ./XX-Net-3.8.7/start: not found
执行   python ./XX-Net-3.8.7/code/default/launcher/start.py，报错
  
python: '/mnt/sda1/XX-Net-3.8.7/code/default/python27/1.0/lib/linux/_cffi_backend.so' is not an ELF executable for MIPS
Dec 14 09:38:20.294 [launcher][INFO] import build-in openssl fail:ImportError('No module named pycparser',)
python: '/mnt/sda1/XX-Net-3.8.7/code/default/python27/1.0/lib/linux/_cffi_backend.so' is not an ELF executable for MIPS
Dec 14 09:38:22.156 [launcher][ERROR] import system python-OpenSSL fail:ImportError('No module named pycparser',)
Dec 14 09:38:22.787 [launcher][ERROR] Except stack:Traceback (most recent call last):
  File "./XX-Net-3.8.7/code/default/launcher/start.py", line 150, in <module>
    import OpenSSL
  File "/mnt/sda1/XX-Net-3.8.7/code/default/python27/1.0/lib/noarch/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/mnt/sda1/XX-Net-3.8.7/code/default/python27/1.0/lib/noarch/OpenSSL/rand.py", line 12, in <module>
    from OpenSSL._util import (
  File "/mnt/sda1/XX-Net-3.8.7/code/default/python27/1.0/lib/noarch/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/mnt/sda1/XX-Net-3.8.7/code/default/python27/1.0/lib/linux/cryptography/hazmat/bindings/openssl/binding.py", line 60, in <module>
    class Binding(object):
  File "/mnt/sda1/XX-Net-3.8.7/code/default/python27/1.0/lib/linux/cryptography/hazmat/bindings/openssl/binding.py", line 109, in Binding
    libraries=_get_libraries(sys.platform)
  File "/mnt/sda1/XX-Net-3.8.7/code/default/python27/1.0/lib/linux/cryptography/hazmat/bindings/utils.py", line 97, in build_ffi_for_binding
    extra_link_args=extra_link_args,
  File "/mnt/sda1/XX-Net-3.8.7/code/default/python27/1.0/lib/linux/cryptography/hazmat/bindings/utils.py", line 105, in build_ffi
    ffi = FFI()
  File "/mnt/sda1/XX-Net-3.8.7/code/default/python27/1.0/lib/linux/cffi/api.py", line 52, in __init__
    from . import cparser, model
  File "/mnt/sda1/XX-Net-3.8.7/code/default/python27/1.0/lib/linux/cffi/cparser.py", line 6, in <module>
    import pycparser
ImportError: No module named pycparser

Try install python-openssl

Press Enter to continue...

python-openssl已经安装了。
进入python，import pycparser也显示该模块不存在，但是反复安装python都没有解决

**Comment by xxnet** [comment]
​删除 /mnt/sda1/XX-Net-3.8.7/code/default/python27/1.0/lib/linux/ 试试，
openwrt 一般是MIPS，和x86不同。

**Comment by uncledragon** [comment]
@xxnet 
​删除 /mnt/sda1/XX-Net-3.8.7/code/default/python27/1.0/lib/linux/
以后运行 python ./XX-Net-3.8.7/code/default/launcher/start.py又出现新的错误
Dec 14 12:23:10.640 [launcher][INFO] import build-in openssl fail:ImportError('No module named cryptography.hazmat.bindings.openssl.binding',)
Dec 14 12:23:10.696 [launcher][ERROR] import system python-OpenSSL fail:ImportError('No module named cryptography.hazmat.bindings.openssl.binding',)
Dec 14 12:23:10.704 [launcher][ERROR] Except stack:Traceback (most recent call last):
  File "/mnt/sda1/XX-Net-3.8.7/code/default/launcher/start.py", line 150, in <module>
    import OpenSSL
  File "/mnt/sda1/XX-Net-3.8.7/code/default/python27/1.0/lib/noarch/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/mnt/sda1/XX-Net-3.8.7/code/default/python27/1.0/lib/noarch/OpenSSL/rand.py", line 12, in <module>
    from OpenSSL._util import (
  File "/mnt/sda1/XX-Net-3.8.7/code/default/python27/1.0/lib/noarch/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
ImportError: No module named cryptography.hazmat.bindings.openssl.binding

Try install python-openssl

Press Enter to continue...

**Comment by xxnet** [comment]
​​删除 /mnt/sda1/XX-Net-3.8.7/code/default/python27/1.0/lib/noarch/OpenSSL
 本来应该先找到系统的OpenSSL 的，但是却先找到自带的OpenSSL

看看能否找到系统的OpenSSL

**Comment by uncledragon** [comment]
@xxnet 
删除/mnt/sda1/XX-Net-3.8.7/code/default/python27/1.0/lib/noarch/OpenSSL后，执行报错：
Dec 20 20:34:45.674 [launcher][INFO] import build-in openssl fail:ImportError('No module named OpenSSL',)
Dec 20 20:34:45.683 [launcher][ERROR] import system python-OpenSSL fail:ImportError('No module named OpenSSL',)
Dec 20 20:34:45.687 [launcher][ERROR] Except stack:Traceback (most recent call last):
  File "./XX-Net-3.9.1/code/default/launcher/start.py", line 151, in <module>
    import OpenSSL
ImportError: No module named OpenSSL

Try install python-openssl
