### ISSUE TITLE
3.9.2 智能路由模式高占用

### ISSUE THREAD

**Issue by jinke159** [XX-net/XX-Net#9212]
# 智能路由占用百分之30，并且无法正常连接,一段时间后恢复正常，但cpu还是30的高占用

中间访问了https://maps.google.com/maps/timeline?hl=zh-CN
出现400错误 
> 400.That’s an error.
 Your client has issued a malformed or illegal request. That’s all we know. 

`Dec 25 18:15:30.426 - [ERROR] Except stack:Traceback (most recent call last): File "D:\FQ\XX-Net-3.8.5\code\3.9.2\smart_router\local\pipe_socks.py", line 138, in pipe r, w, e = select.select(self.read_set, self.write_set, self.error_set, 0.1) File "D:\FQ\XX-Net-3.8.5\code\3.9.2\python27\1.0\lib\socket.py", line 228, in meth return getattr(self._sock,name)(*args) File "D:\FQ\XX-Net-3.8.5\code\3.9.2\python27\1.0\lib\socket.py", line 174, in _dummy raise error(EBADF, 'Bad file descriptor') error: [Errno 9] Bad file descriptor`

`Dec 25 18:15:30.426 - [ERROR] pipe except:error(9, 'Bad file descriptor')`

昨天发了log后貌似被盯上了，今天上午gae无限中断，关闭猫一段时间后才回复

**Comment by GoodSake** [comment]
被盯上也没事，咱可是动态ip哦，哈哈哈。

**Comment by xxnet** [comment]
​一般是建立太多链接，导致路由器异常/ISP 限制。
重启就好了。

**Comment by changshunxu520** [comment]
3.9.2以后做了很大的改动？现在直接就是127.0.0.1：8085一直没有相应。
