### ISSUE TITLE
3.9.2版本，ubuntu 16.04，系统休眠（suspend）一段时间后就连不上网了，必须重新运行./start

### ISSUE THREAD

**Issue by dong-jy** [XX-net/XX-Net#9251]
启动方式：
`./start`

版本：
3.9.2

系统：
ubuntu 16.04， 用miredo连接IPv6。

网络连接：
wifi

复现方式：
系统休眠（suspend）一段时间（时间10分钟以上）后连不上网。然后在Terminal 尝试用 `Ctrl+C`时退出程序时，会出现：
`[smart_router][INFO] pipe stopped.`
程序继续运行，再按`Ctrl+C`，出现：
`[ERROR] uncaught Exception, type=<type 'exceptions.KeyboardInterrupt'> value= traceback:<traceback object at 0x7f1e6d623368>`
然后要`kill`才能彻底关闭，之后运行`./start`就好了。

发生频率：几乎每次suspend时间超过30分钟都会发生，短时间睡眠却没事。

下面的是其它问题：

日志里经常出现有这样一段Error：
`Dec 28 17:46:45.726 [simple_http_server][ERROR] handler:'Req command format fail:)\x02\xa3\x07' cmd:None path:mtalk.google.com:5228 from:127.0.0.1:50144
Dec 28 17:46:45.727 [gae_proxy][DEBUG] GAE POST https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=qAULh43iO/d4nDKWC97/IA%3D%3D
Dec 28 17:46:45.727 [simple_http_server][ERROR] Except stack:Traceback (most recent call last):
  File "/code/3.9.2/python27/1.0/lib/noarch/simple_http_server.py", line 160, in handle_one_request
    self.do_CONNECT()
  File "/code/3.9.2/gae_proxy/local/proxy_handler.py", line 286, in do_CONNECT
    return self.do_CONNECT_AGENT()
  File "/code/3.9.2/gae_proxy/local/proxy_handler.py", line 316, in do_CONNECT_AGENT
    self.parse_request()
  File "/code/3.9.2/python27/1.0/lib/noarch/simple_http_server.py", line 131, in parse_request
    raise ParseReqFail("Req command format fail:%s" % requestline)
ParseReqFail: 'Req command format fail:)\x02\xa3\x07'
`

另一个问题是为什么OS X 和 Linux 要用不同的方案启动？
https://github.com/XX-net/XX-Net/blob/bd338e4f16878f6a4e5cd412e04b65eeaf97facc/start#L70-L74

**Comment by xxnet** [comment]
​休眠后无法联网，可能是哪里的计时器没有处理好，先记下来。

mtalk.google.com:5228 异常，是因为非HTTP 请求，解析失败，要走X-Tunnel才行。

OSX 平台，大部分用户不喜欢有个命令行窗口，所以跑在后台，桌面干净。
  如果能够知道是双击 start 启动，还是命令行执行 start，就能够更好处理这个问题了。

**Comment by dong-jy** [comment]
@xxnet 
谢谢

是在在命令行`./start`启动的。
这些都是小问题，我修改了问题描述，表达更加清楚点。

最近一周IPv6连接干扰加强了，GAE速度只有100k左右。可惜我能力有限，写quic还帮不上忙了。

**Comment by xxnet** [comment]
certificate is none 一般是tcp连接上了，但是SSL 握手是受到干扰，ServerHello 包没有收到就reset了。
简单讲，就是墙在干扰。

**Comment by dong-jy** [comment]
@xxnet 
明白了
