### ISSUE TITLE
SMART ROUTER的问题

### ISSUE THREAD

**Issue by yuningning520** [XX-net/XX-Net#9353]
3.9.3重启模块
直接打开百度的话，就是直连
打开google再打开百度的话，就是代理，之后无论打开什么都是代理
Jan 06 01:52:47.878 - [DEBUG] host:hm.baidu.com:443 do gae
另外顺便看见一个报错

Jan 06 02:01:27.317 - [ERROR] domain host:hpd.baidu.com:443 rule:gae except:error(10053, '')
Jan 06 02:01:27.319 - [ERROR] Except stack:Traceback (most recent call last): File "D:\SW\PF\XX-Net\code\default\smart_router\local\smart_route.py", line 297, in try_loop do_gae(sock, host, port, client_address, left_buf) File "D:\SW\PF\XX-Net\code\default\smart_router\local\smart_route.py", line 266, in do_gae req.do_METHOD() File "D:\SW\PF\XX-Net\code\default\gae_proxy\local\proxy_handler.py", line 223, in do_METHOD return self.do_AGENT() File "D:\SW\PF\XX-Net\code\default\gae_proxy\local\proxy_handler.py", line 271, in do_AGENT gae_handler.handler(self.command, self.path, request_headers, payload, self.wfile) File "D:\SW\PF\XX-Net\code\default\gae_proxy\local\gae_handler.py", line 480, in handler return send_response(wfile, response.app_status, body=response.app_msg) File "D:\SW\PF\XX-Net\code\default\gae_proxy\local\gae_handler.py", line 176, in send_response send_header(wfile, key, value) File "D:\SW\PF\XX-Net\code\default\gae_proxy\local\gae_handler.py", line 160, in send_header wfile.write("undefined: undefined\r\n" % (keyword, value)) File "D:\SW\PF\XX-Net\code\default\python27\1.0\lib\socket.py", line 328, in write self.flush() File "D:\SW\PF\XX-Net\code\default\python27\1.0\lib\socket.py", line 307, in flush self._sock.sendall(view[write_offset:write_offset+buffer_size]) File "D:\SW\PF\XX-Net\code\default\python27\1.0\lib\ssl.py", line 753, in sendall v = self.send(data[count:]) File "D:\SW\PF\XX-Net\code\default\python27\1.0\lib\ssl.py", line 719, in send v = self._sslobj.write(data) error: [Errno 10053]

**Comment by gjbg1989** [comment]
http://127.0.0.1:8085/?module=smart_router&menu=config 规则——直连列表：添加百度？

**Comment by xxnet** [comment]
估计解析出来的baidu ip是墙外的，导致走GAE。
​看来需要添加白名单，避免墙内的域名走代理。
