### ISSUE TITLE
enable_ipv6无法获得权限

### ISSUE THREAD

**Issue by yurjane** [XX-net/XX-Net#9373]
Get Admin
[SC] OpenService 失败 5:

拒绝访问。

[SC] StartService 失败 1056:

服务的实例已在运行中。

[SC] OpenService 失败 5:

拒绝访问。

[SC] StartService 失败 1056:

服务的实例已在运行中。

[SC] OpenService 失败 5:

拒绝访问。

[SC] StartService 失败 1056:

服务的实例已在运行中。

[SC] ChangeServiceConfig 成功
[SC] StartService 失败 1056:

服务的实例已在运行中。

[SC] OpenService 失败 1060:

指定的服务未安装。

[SC] StartService 失败 1056:

服务的实例已在运行中。

[SC] ChangeServiceConfig 成功
[SC] StartService 失败 1056:

服务的实例已在运行中。

[SC] OpenService 失败 5:

拒绝访问。

[SC] StartService 失败 1056:

服务的实例已在运行中。

[SC] ChangeServiceConfig 成功
[SC] StartService 失败 1056:

服务的实例已在运行中。

正在重置 分段转发，完成!
正在重置 分段，完成!
正在重置 控制协议，完成!
正在重置 回显顺序请求，完成!
正在重置 全局，完成!
正在重置 接口，完成!
正在重置 任意广播地址，完成!
正在重置 多播地址，完成!
正在重置 单播地址，完成!
正在重置 邻居，完成!
正在重置 路径，完成!
正在重置 潜在，完成!
正在重置 前缀策略，完成!
正在重置 代理邻居，完成!
正在重置 路由，完成!
正在重置 站点前缀，完成!
正在重置 子接口，完成!
正在重置 唤醒模式，完成!
正在重置 解析邻居，完成!
正在重置 ，完成!
正在重置 ，完成!
正在重置 ，完成!
正在重置 ，完成!
正在重置 ，失败。
拒绝访问。

正在重置 ，完成!
正在重置 ，完成!
正在重置 ，完成!
正在重置 ，完成!
正在重置 ，完成!
正在重置 ，完成!
正在重置 ，完成!
重新启动计算机来完成此操作。

确定。

确定。

确定。

确定。

确定。

确定。

路由删除失败: 找不到元素。

文件名、目录名或卷标语法不正确。

确定。

确定。

操作成功完成。
操作成功完成。
确定。

确定。

确定。

确定。

确定。

确定。

路由删除失败: 找不到元素。

文件名、目录名或卷标语法不正确。

确定。

确定。

操作成功完成。

Windows IP 配置

已成功刷新 DNS 解析缓存。

**Comment by gjbg1989** [comment]
netsh int ipv6 show teredo 贴运行结果及XX-Net诊断信息

**Comment by yurjane** [comment]
Windows IP 配置

   主机名  . . . . . . . . . . . . . : LAPTOP-P87IMOQP
   主 DNS 后缀 . . . . . . . . . . . : 
   节点类型  . . . . . . . . . . . . : 混合
   IP 路由已启用 . . . . . . . . . . : 否
   WINS 代理已启用 . . . . . . . . . : 否
   DNS 后缀搜索列表  . . . . . . . . : lan

以太网适配器 VPN - VPN Client:

   媒体状态  . . . . . . . . . . . . : 媒体已断开连接
   连接特定的 DNS 后缀 . . . . . . . : 
   描述. . . . . . . . . . . . . . . : VPN Client Adapter - VPN
   物理地址. . . . . . . . . . . . . : 00-AC-BA-C5-0F-9C
   DHCP 已启用 . . . . . . . . . . . : 是
   自动配置已启用. . . . . . . . . . : 是

以太网适配器 Ethernet:

   媒体状态  . . . . . . . . . . . . : 媒体已断开连接
   连接特定的 DNS 后缀 . . . . . . . : edu2act.org
   描述. . . . . . . . . . . . . . . : Realtek PCIe FE Family Controller
   物理地址. . . . . . . . . . . . . : 40-B0-34-6A-BA-08
   DHCP 已启用 . . . . . . . . . . . : 是
   自动配置已启用. . . . . . . . . . : 是

无线局域网适配器 Local Area Connection* 2:

   媒体状态  . . . . . . . . . . . . : 媒体已断开连接
   连接特定的 DNS 后缀 . . . . . . . : 
   描述. . . . . . . . . . . . . . . : Microsoft Wi-Fi Direct Virtual Adapter
   物理地址. . . . . . . . . . . . . : 30-E3-7A-54-7E-9C
   DHCP 已启用 . . . . . . . . . . . : 是
   自动配置已启用. . . . . . . . . . : 是

无线局域网适配器 Local Area Connection* 14:

   媒体状态  . . . . . . . . . . . . : 媒体已断开连接
   连接特定的 DNS 后缀 . . . . . . . : 
   描述. . . . . . . . . . . . . . . : Microsoft Wi-Fi Direct Virtual Adapter #3
   物理地址. . . . . . . . . . . . . : 32-E3-7A-54-7E-9B
   DHCP 已启用 . . . . . . . . . . . : 是
   自动配置已启用. . . . . . . . . . : 是

以太网适配器 VMware Network Adapter VMnet1:

   连接特定的 DNS 后缀 . . . . . . . : 
   描述. . . . . . . . . . . . . . . : VMware Virtual Ethernet Adapter for VMnet1
   物理地址. . . . . . . . . . . . . : 00-50-56-C0-00-01
   DHCP 已启用 . . . . . . . . . . . : 否
   自动配置已启用. . . . . . . . . . : 是
   本地链接 IPv6 地址. . . . . . . . : fe80::ad51:70ca:68ac:90f2%2(首选) 
   IPv4 地址 . . . . . . . . . . . . : 192.168.159.1(首选) 
   子网掩码  . . . . . . . . . . . . : 255.255.255.0
   默认网关. . . . . . . . . . . . . : 
   DHCPv6 IAID . . . . . . . . . . . : 654331990
   DHCPv6 客户端 DUID  . . . . . . . : 00-01-00-01-21-D9-14-3F-30-E3-7A-54-7E-9B
   DNS 服务器  . . . . . . . . . . . : fec0:0:0:ffff::1%1
                                       fec0:0:0:ffff::2%1
                                       fec0:0:0:ffff::3%1
   TCPIP 上的 NetBIOS  . . . . . . . : 已启用

以太网适配器 VMware Network Adapter VMnet8:

   连接特定的 DNS 后缀 . . . . . . . : 
   描述. . . . . . . . . . . . . . . : VMware Virtual Ethernet Adapter for VMnet8
   物理地址. . . . . . . . . . . . . : 00-50-56-C0-00-08
   DHCP 已启用 . . . . . . . . . . . : 否
   自动配置已启用. . . . . . . . . . : 是
   本地链接 IPv6 地址. . . . . . . . : fe80::5052:a164:3a9a:2161%5(首选) 
   IPv4 地址 . . . . . . . . . . . . : 192.168.119.1(首选) 
   子网掩码  . . . . . . . . . . . . : 255.255.255.0
   默认网关. . . . . . . . . . . . . : 
   DHCPv6 IAID . . . . . . . . . . . : 671109206
   DHCPv6 客户端 DUID  . . . . . . . : 00-01-00-01-21-D9-14-3F-30-E3-7A-54-7E-9B
   DNS 服务器  . . . . . . . . . . . : fec0:0:0:ffff::1%1
                                       fec0:0:0:ffff::2%1
                                       fec0:0:0:ffff::3%1
   TCPIP 上的 NetBIOS  . . . . . . . : 已启用

以太网适配器 Ethernet 4:

   媒体状态  . . . . . . . . . . . . : 媒体已断开连接
   连接特定的 DNS 后缀 . . . . . . . : 
   描述. . . . . . . . . . . . . . . : TAP Adapter V9 for Private Tunnel
   物理地址. . . . . . . . . . . . . : 00-FF-99-4E-93-EF
   DHCP 已启用 . . . . . . . . . . . : 否
   自动配置已启用. . . . . . . . . . : 是

以太网适配器 Ethernet 5:

   媒体状态  . . . . . . . . . . . . : 媒体已断开连接
   连接特定的 DNS 后缀 . . . . . . . : 
   描述. . . . . . . . . . . . . . . : TAP Adapter V9 for Private Tunnel #2
   物理地址. . . . . . . . . . . . . : 00-FF-B2-74-8F-BA
   DHCP 已启用 . . . . . . . . . . . : 是
   自动配置已启用. . . . . . . . . . : 是

无线局域网适配器 Wi-Fi:

   连接特定的 DNS 后缀 . . . . . . . : lan
   描述. . . . . . . . . . . . . . . : Intel(R) Dual Band Wireless-AC 3168
   物理地址. . . . . . . . . . . . . : 30-E3-7A-54-7E-9B
   DHCP 已启用 . . . . . . . . . . . : 是
   自动配置已启用. . . . . . . . . . : 是
   IPv4 地址 . . . . . . . . . . . . : 192.168.2.211(首选) 
   子网掩码  . . . . . . . . . . . . : 255.255.255.0
   获得租约的时间  . . . . . . . . . : 2018年1月7日 15:49:52
   租约过期的时间  . . . . . . . . . : 2018年1月8日 15:49:51
   默认网关. . . . . . . . . . . . . : 192.168.2.1
   DHCP 服务器 . . . . . . . . . . . : 192.168.2.1
   DNS 服务器  . . . . . . . . . . . : 192.168.2.1
   TCPIP 上的 NetBIOS  . . . . . . . : 已启用

以太网适配器 Bluetooth Network Connection:

   媒体状态  . . . . . . . . . . . . : 媒体已断开连接
   连接特定的 DNS 后缀 . . . . . . . : 
   描述. . . . . . . . . . . . . . . : Bluetooth Device (Personal Area Network)
   物理地址. . . . . . . . . . . . . : 30-E3-7A-54-7E-9F
   DHCP 已启用 . . . . . . . . . . . : 是
   自动配置已启用. . . . . . . . . . : 是

隧道适配器 Local Area Connection* 13:

   媒体状态  . . . . . . . . . . . . : 媒体已断开连接
   连接特定的 DNS 后缀 . . . . . . . : 
   描述. . . . . . . . . . . . . . . : Microsoft Teredo Tunneling Adapter
   物理地址. . . . . . . . . . . . . : 00-00-00-00-00-00-00-E0
   DHCP 已启用 . . . . . . . . . . . : 否
   自动配置已启用. . . . . . . . . . : 是
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient (Group Policy) 
服务器名称              : teredo.remlab.net
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : offline
错误                    : 未能打开隧道适配器


发布    类型     跃点数 前缀                     索引 网关/接口名称
------- -------- ---    ------------------------ --- ------------------------
否        系统        256  ::1/128                     1  Loopback Pseudo-Interface 1
否        系统        256  fe80::/64                  15  Bluetooth Network Connection
否        系统        256  fe80::/64                  11  Local Area Connection* 2
否        系统        256  fe80::/64                   2  VMware Network Adapter VMnet1
否        系统        256  fe80::/64                  18  Ethernet 5
否        系统        256  fe80::/64                   5  VMware Network Adapter VMnet8
否        系统        256  fe80::/64                  13  Ethernet 4
否        系统        256  fe80::/64                  12  Local Area Connection* 14
否        系统        256  fe80::/64                  41  Local Area Connection* 13
否        系统        256  fe80::100:7f:fffe/128      41  Local Area Connection* 13
否        系统        256  fe80::2c10:7b17:b681:d63/128   18  Ethernet 5
否        系统        256  fe80::5052:a164:3a9a:2161/128    5  VMware Network Adapter VMnet8
否        系统        256  fe80::5c65:e81b:d5ad:c1b9/128   15  Bluetooth Network Connection
否        系统        256  fe80::5d07:9bef:f415:28c6/128   11  Local Area Connection* 2
否        系统        256  fe80::acb3:813a:bfbd:5cd1/128   13  Ethernet 4
否        系统        256  fe80::ad51:70ca:68ac:90f2/128    2  VMware Network Adapter VMnet1
否        系统        256  fe80::c067:c7fc:817e:b937/128   12  Local Area Connection* 14
否        系统        256  ff00::/8                    1  Loopback Pseudo-Interface 1
否        系统        256  ff00::/8                   15  Bluetooth Network Connection
否        系统        256  ff00::/8                   11  Local Area Connection* 2
否        系统        256  ff00::/8                    2  VMware Network Adapter VMnet1
否        系统        256  ff00::/8                   18  Ethernet 5
否        系统        256  ff00::/8                    5  VMware Network Adapter VMnet8
否        系统        256  ff00::/8                   13  Ethernet 4
否        系统        256  ff00::/8                   12  Local Area Connection* 14
否        系统        256  ff00::/8                   41  Local Area Connection* 13


Idx     Met         MTU          状态                名称
---  ----------  ----------  ------------  ---------------------------
 41          75        1472  disconnected  Local Area Connection* 13
 11          25        1500  disconnected  Local Area Connection* 2
  1          75  4294967295  connected     Loopback Pseudo-Interface 1
 15          65        1500  disconnected  Bluetooth Network Connection
 12          25        1500  disconnected  Local Area Connection* 14
  2          35        1500  connected     VMware Network Adapter VMnet1
  5          35        1500  connected     VMware Network Adapter VMnet8
 13          35        1500  disconnected  Ethernet 4
 18          35        1500  disconnected  Ethernet 5

查询活动状态...

优先顺序    标签   前缀
----------  -----  --------------------------------
        30      1  2002::/16
         5      1  2001::/32


接口 41: Local Area Connection* 13

地址类型   DAD 状态    有效寿命   首选寿命   地址
---------  ----------- ---------- ---------- ------------------------
其他         反对            infinite   infinite fe80::100:7f:fffe%41

接口 11: Local Area Connection* 2

地址类型   DAD 状态    有效寿命   首选寿命   地址
---------  ----------- ---------- ---------- ------------------------
其他         反对            infinite   infinite fe80::5d07:9bef:f415:28c6%11

接口 1: Loopback Pseudo-Interface 1

地址类型   DAD 状态    有效寿命   首选寿命   地址
---------  ----------- ---------- ---------- ------------------------
其他         首选项           infinite   infinite ::1

接口 15: Bluetooth Network Connection

地址类型   DAD 状态    有效寿命   首选寿命   地址
---------  ----------- ---------- ---------- ------------------------
其他         反对            infinite   infinite fe80::5c65:e81b:d5ad:c1b9%15

接口 12: Local Area Connection* 14

地址类型   DAD 状态    有效寿命   首选寿命   地址
---------  ----------- ---------- ---------- ------------------------
其他         反对            infinite   infinite fe80::c067:c7fc:817e:b937%12

接口 2: VMware Network Adapter VMnet1

地址类型   DAD 状态    有效寿命   首选寿命   地址
---------  ----------- ---------- ---------- ------------------------
其他         首选项           infinite   infinite fe80::ad51:70ca:68ac:90f2%2

接口 5: VMware Network Adapter VMnet8

地址类型   DAD 状态    有效寿命   首选寿命   地址
---------  ----------- ---------- ---------- ------------------------
其他         首选项           infinite   infinite fe80::5052:a164:3a9a:2161%5

接口 13: Ethernet 4

地址类型   DAD 状态    有效寿命   首选寿命   地址
---------  ----------- ---------- ---------- ------------------------
其他         反对            infinite   infinite fe80::acb3:813a:bfbd:5cd1%13

接口 18: Ethernet 5

地址类型   DAD 状态    有效寿命   首选寿命   地址
---------  ----------- ---------- ---------- ------------------------
其他         反对            infinite   infinite fe80::2c10:7b17:b681:d63%18

===========================================================================
接口列表
 20...00 ac ba c5 0f 9c ......VPN Client Adapter - VPN
 16...40 b0 34 6a ba 08 ......Realtek PCIe FE Family Controller
 11...30 e3 7a 54 7e 9c ......Microsoft Wi-Fi Direct Virtual Adapter
 12...32 e3 7a 54 7e 9b ......Microsoft Wi-Fi Direct Virtual Adapter #3
  2...00 50 56 c0 00 01 ......VMware Virtual Ethernet Adapter for VMnet1
  5...00 50 56 c0 00 08 ......VMware Virtual Ethernet Adapter for VMnet8
 13...00 ff 99 4e 93 ef ......TAP Adapter V9 for Private Tunnel
 18...00 ff b2 74 8f ba ......TAP Adapter V9 for Private Tunnel #2
 19...30 e3 7a 54 7e 9b ......Intel(R) Dual Band Wireless-AC 3168
 15...30 e3 7a 54 7e 9f ......Bluetooth Device (Personal Area Network)
  1...........................Software Loopback Interface 1
 41...00 00 00 00 00 00 00 e0 Microsoft Teredo Tunneling Adapter
===========================================================================

IPv4 路由表
===========================================================================
活动路由:
网络目标        网络掩码          网关       接口   跃点数
          0.0.0.0          0.0.0.0      192.168.2.1    192.168.2.211     45
        127.0.0.0        255.0.0.0            在链路上         127.0.0.1    331
        127.0.0.1  255.255.255.255            在链路上         127.0.0.1    331
  127.255.255.255  255.255.255.255            在链路上         127.0.0.1    331
      192.168.2.0    255.255.255.0            在链路上     192.168.2.211    301
    192.168.2.211  255.255.255.255            在链路上     192.168.2.211    301
    192.168.2.255  255.255.255.255            在链路上     192.168.2.211    301
    192.168.119.0    255.255.255.0            在链路上     192.168.119.1    291
    192.168.119.1  255.255.255.255            在链路上     192.168.119.1    291
  192.168.119.255  255.255.255.255            在链路上     192.168.119.1    291
    192.168.159.0    255.255.255.0            在链路上     192.168.159.1    291
    192.168.159.1  255.255.255.255            在链路上     192.168.159.1    291
  192.168.159.255  255.255.255.255            在链路上     192.168.159.1    291
        224.0.0.0        240.0.0.0            在链路上         127.0.0.1    331
        224.0.0.0        240.0.0.0            在链路上     192.168.2.211    301
        224.0.0.0        240.0.0.0            在链路上     192.168.159.1    291
        224.0.0.0        240.0.0.0            在链路上     192.168.119.1    291
  255.255.255.255  255.255.255.255            在链路上         127.0.0.1    331
  255.255.255.255  255.255.255.255            在链路上     192.168.2.211    301
  255.255.255.255  255.255.255.255            在链路上     192.168.159.1    291
  255.255.255.255  255.255.255.255            在链路上     192.168.119.1    291
===========================================================================
永久路由:
  无

IPv6 路由表
===========================================================================
活动路由:
 接口跃点数网络目标                网关
  1    331 ::1/128                  在链路上
  2    291 fe80::/64                在链路上
  5    291 fe80::/64                在链路上
  5    291 fe80::5052:a164:3a9a:2161/128
                                    在链路上
  2    291 fe80::ad51:70ca:68ac:90f2/128
                                    在链路上
  1    331 ff00::/8                 在链路上
  2    291 ff00::/8                 在链路上
  5    291 ff00::/8                 在链路上
===========================================================================
永久路由:
  无

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.108 Safari/537.36
xxnet-version: 3.8.5
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:6000 ipv4:0 ipv6:2672
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 200
ip-quality: 314
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by gjbg1989** [comment]
#8915 tertdo.bat自动或手动优选服务器（文件解压放在 XX-Net 程序的根目录）
Ipv6 自动转换 | ??闪闪的红星?? - http://songjinju.com/2017/10/12/Ipv6-%E8%87%AA%E5%8A%A8%E8%BD%AC%E6%8D%A2/#more
转：把注册表修改了一下，机器重启就好了 HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\TCPIP6\Parameters 修改 DisabledComponents 十六进制值为0，没有项目新建一个DWORD（32位）值。
此后再出问题：多次刷新或重载控制页，或右键 XX-Net 状态栏图标重启、再稍侯，或结束进程pythonw.exe、（关闭浏览器、）重启 XX-Net、再稍侯，或换服务器，或结束进程pythonw.exe、禁用再启用网络，或机器重启。或结束全部 RuntimeBroker.exe 进程、右键 XX-Net 状态栏图标重启（待验证）

**Comment by yurjane** [comment]
emmmm.....我也不知道做了什么，连接恢复了。。。。
emmmm.....又失去连接了，然而我什么也没做。。。。
关于打开ipv6隧道的方法我都试过了，但还是不行
关于http://test-ipv6.com/#网站的结果
    你的公网 IPv4 地址是 111.11.85.6
    你的运营商（ISP）是 CMNET-V4HEBEI-AS-AP Hebei Mobile Communication Company Limited
    在你所在的地区，本站的测试结果并不可靠。
    没有检测到 IPv6 地址 [更多信息]
    当内容商同时提供 IPv4 和 IPv6 时，你的浏览器会欣然通过 IPv4 连接。
    连接纯 IPv6 网站超时，你会感觉所有纯 IPv6 网站好像都宕机了
    为了保证最佳的网络性能和连接性，向你的运营商咨询原生 IPv6 事宜吧。 [更多信息]
    本站现已支持 HTTPS。 [更多信息]
    你的 DNS 服务器（可能由运营商提供）已经接入 IPv6 互联网了
还有一个问题：no enough ip

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.108 Safari/537.36
xxnet-version: 3.9.3
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:117 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 200
ip-quality: 9999
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by gjbg1989** [comment]
use-ipv6: auto——改为只用 ipv6
emmmm.....我也不知道做了什么，连接恢复了。。。。
emmmm.....又失去连接了，然而我什么也没做。。。。——自动更换服务器
关于打开ipv6隧道的方法我都试过了，但还是不行——只要开启过，就不再需要“关于打开ipv6隧道的方法我都试过了”，长篇大论对小白无效， netsh int ipv6 show teredo 贴运行结果及XX-Net诊断信息即可。
按上上楼的每步操作到位后正常应不是问题。检查注册表项
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\Dnscache\Parameters]
"AddrConfigControl"=dword:00000000

（开机）启动XX-Net前即运行以下bat可观察变化过程，状态dormant即已正常。
:loop
netsh int teredo show state
ping 127.0.0.1 > null
goto loop

**Comment by yurjane** [comment]
Teredo 参数
---------------------------------------------
类型                    : enterpriseclient
服务器名称              : teredo.remlab.net
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : qualified
客户端类型              : teredo client
网络                    : unmanaged
NAT                     : symmetric (port)
NAT 特殊行为   : UPNP: 否，PortPreserving: 否
本地映射           : 192.168.2.211:59080
外部 NAT 映射    : 183.197.99.115:61040

XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.108 Safari/537.36
xxnet-version: 3.9.3
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:123 ipv4:0 ipv6:22
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 200
ip-quality: 480
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

能连上的时候我是在学校的内网，用ISATAP隧道
但回到宿舍就没有ipv6了

**Comment by gjbg1989** [comment]
学校的内网、回到宿舍有什么不同？——也许宜各自独用XX-Net，至少是good_ip.txt有所区分？没经验。。。
http://127.0.0.1:8085/?module=launcher&menu=config 代理——帮助 https://github.com/XX-net/XX-Net/wiki/GoAgent-Intranet-proxy

**Comment by gjbg1989** [comment]
貌似 WIFI 网络宜取消勾选网络连接中的 IPv6 协议？

**Comment by yurjane** [comment]
学校教室是内网ip，而宿舍是公网ip

**Comment by gjbg1989** [comment]
所言都是非校园网

**Comment by gjbg1989** [comment]
弃用 ISP 商 DNS，指定 IPv4 及 IPv6 DNS？

**Comment by yurjane** [comment]
我想重头来过，该怎么做

**Comment by gjbg1989** [comment]
想重头来过——简单，遵循各自独用XX-Net的原则，完整复制一份在公网内运行，建议基本已完全给出

**Comment by yurjane** [comment]
为啥我的证书安装不上。。。
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.108 Safari/537.36
xxnet-version: 3.9.3
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:123 ipv4:0 ipv6:22
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 200
ip-quality: 480
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by yurjane** [comment]
怎么改为只用 ipv6

**Comment by gjbg1989** [comment]
http://127.0.0.1:8085/?module=gae_proxy&menu=advanced 使用IPv6

**Comment by gjbg1989** [comment]
为啥我的证书安装不上。。。——不是学校教室内网正常？正常即证书已经安装上
proxy_state: Fail
ca_state: Fail——并非只有证书不正常，IPv6 没正常、代理不正常也是这结果

**Comment by yurjane** [comment]
我的隧道适配器的默认网关是：：，这个怎么办

**Comment by gjbg1989** [comment]
运行XX-net目录下的 disable 与 enable bat

**Comment by yurjane** [comment]
emmm...如果disable与enable有用就好了。。。。
xx-net始终显示请开启ipv6（隧道）等等的字眼。。。
崩溃。。

**Comment by yurjane** [comment]
Jan 08 19:45:40.661 [simple_http_server][ERROR] handler:'Req command format fail:)\x02\xa7\x02' cmd:None path:mtalk.google.com:5228 from:127.0.0.1:50506
Jan 08 19:45:40.698 [simple_http_server][ERROR] Except stack:Traceback (most recent call last):
  File "C:\Program Files (x86)\XX-Net\code\default\python27\1.0\lib\noarch\simple_http_server.py", line 160, in handle_one_request
    self.do_CONNECT()
  File "C:\Program Files (x86)\XX-Net\code\default\gae_proxy\local\proxy_handler.py", line 289, in do_CONNECT
    return self.do_CONNECT_AGENT()
  File "C:\Program Files (x86)\XX-Net\code\default\gae_proxy\local\proxy_handler.py", line 319, in do_CONNECT_AGENT
    self.parse_request()
  File "C:\Program Files (x86)\XX-Net\code\default\python27\1.0\lib\noarch\simple_http_server.py", line 131, in parse_request
    raise ParseReqFail("Req command format fail:%s" % requestline)
ParseReqFail: 'Req command format fail:)\x02\xa7\x02'
emmmm...这块显红字，我学过python，这是啥问题

**Comment by gjbg1989** [comment]
3.7.11版XX-net目录下的 disable 与 enable bat 好用，新版未试

**Comment by yurjane** [comment]
emmmm...今天查了查ip，发现是内网，怎么关6to4隧道

**Comment by gjbg1989** [comment]
#关闭和卸载Teredo、6to4、isatap
netsh interface teredo set state disable
netsh interface 6to4 set state disabled
netsh interface isatap set state disabled

**Comment by yurjane** [comment]
teredo.zip的工具在哪。。。。

**Comment by gjbg1989** [comment]
![default](https://user-images.githubusercontent.com/13290970/34710603-fa78fce6-f556-11e7-818d-77cb2a867074.png)

**Comment by yurjane** [comment]
显不出来。。。。

**Comment by yurjane** [comment]
根目录下找不到。。。。

**Comment by gjbg1989** [comment]
😝从上到下，我的第二回帖的第一项

**Comment by yurjane** [comment]
用完tertdo.bat之后的结果
Teredo 参数
---------------------------------------------
类型                    : client
服务器名称              : teredo2.remlab.net
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : probe (primary server)
客户端类型              : teredo client
网络                    : unmanaged

**Comment by gjbg1989** [comment]
状态 : probe (primary server)——正常化的前奏，扫描一定时间，应🆗

**Comment by yurjane** [comment]
现在没有足够ip
还有，正常情况下本地策略编辑器中关于teredo的设定都处于什么状态（未配置or已启用or已禁用）

**Comment by yurjane** [comment]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.108 Safari/537.36
xxnet-version: 3.8.7
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:0 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 10
ip-quality: 9999
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by gjbg1989** [comment]
未配置

**Comment by gjbg1989** [comment]
use-ipv6: auto——改为只用 ipv6
gws-ip-num: total:0 ipv4:0 ipv6:0 😱

**Comment by gjbg1989** [comment]
netsh int ipv6 set teredo enterpriseclient

**Comment by yurjane** [comment]
什么都没发生。。。

**Comment by yurjane** [comment]
老铁，要不加波QQ，细聊😱

**Comment by gjbg1989** [comment]
QQ——那个——流氓，已不玩N年😂

**Comment by gjbg1989** [comment]
scan-ip-thread-num: 10 后面添加个0，正常后改回

**Comment by gjbg1989** [comment]
弃用 ISP 商 DNS ，指定 IPv4 及 IPv6 DNS ？

**Comment by yurjane** [comment]
还是这样。。。
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:256; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.108 Safari/537.36
xxnet-version: 3.9.3
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:0 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 200
ip-quality: 9999
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by yurjane** [comment]
加载慢，请先忽略

**Comment by gjbg1989** [comment]
lan-proxy: Disable——不是说“内网”？——emmmm...今天查了查ip，发现是内网。。。
![default](https://user-images.githubusercontent.com/13290970/34725003-9fef1380-f58a-11e7-99b3-1480a53763ff.png)

**Comment by yurjane** [comment]
本地链接 IPv6 地址. . . . . . . . : fe80::e0b9:fa3a:ad63:287%17
IPv4 地址 . . . . . . . . . . . . : 192.168.2.238

**Comment by gjbg1989** [comment]
emmmm...今天查了查ip，发现是内网。。。这又不是我说的😂
gws-ip-num: total:0 ipv4:0 ipv6:0——多长时间了，仍旧是0，不正常

**Comment by gjbg1989** [comment]
如是 Wifi 网络，试试取消勾选网卡的 IPv6 协议

**Comment by yurjane** [comment]
如果插着网线呢。。

**Comment by yurjane** [comment]
还是不行。。
