### ISSUE TITLE
Mac OS 启动错误 No module named Foundation

### ISSUE THREAD

**Issue by sagexy** [XX-net/XX-Net#94]
launcher version: 1.2.0
Traceback (most recent call last):
  File "launcher/start.py", line 61, in <module>
    main()
  File "launcher/start.py", line 56, in main
    from start import main as launcher_main
  File "/Users/xy/Downloads/XX-Net-1.6.0/launcher/1.2.0/start.py", line 25, in <module>
    from mac_tray import sys_tray
  File "/Users/xy/Downloads/XX-Net-1.6.0/launcher/1.2.0/mac_tray.py", line 17, in <module>
    import rumps
  File "/Users/xy/Downloads/XX-Net-1.6.0/python27/1.0/lib/darwin/rumps/__init__.py", line 25, in <module>
    from .rumps import (separator, debug_mode, alert, notification, application_support, timers, quit_application, timer,
  File "/Users/xy/Downloads/XX-Net-1.6.0/python27/1.0/lib/darwin/rumps/rumps.py", line 15, in <module>
    from Foundation import (NSDate, NSTimer, NSRunLoop, NSDefaultRunLoopMode, NSSearchPathForDirectoriesInDomains,
ImportError: No module named Foundation
logout

以前1.2版本可以正常启动，用了一段时间 更新了1.5.5版本就出现如上启动错误，1.6版本同样也有这错误,
直接启动goagent是如下信息：
![image](https://cloud.githubusercontent.com/assets/4734448/6932584/f91dfc80-d84d-11e4-9f2a-dd0f61f6c997.png)

环境变量也配了
![9096562b-44ce-487e-a5e0-e25839f538fd](https://cloud.githubusercontent.com/assets/4734448/6932641/ea2430f4-d84e-11e4-8069-63253003ac60.png)

如何破！？

**Comment by xxnet** [comment]
有反馈 sudo export PYTHONPATH=......
然后启动 start.sh



ImportError: No module named Foundation
提示是因为找不到库。这个库应该在上面提到的位置中，你可以进去看看有没有存在。
如果找不到请告诉我。

google 这个错误，就是这么解决的。

我手上的Mac环境都没有出现这个问题，无法重新和调试。


2015-03-31 21:10 GMT-04:00 xy <notifications@github.com>:

**Comment by sagexy** [comment]
sudo pip install pyobjc

**Comment by xxnet** [comment]
收到，谢谢，我看看把pyobjc放入打包中试试

2015-04-02 1:41 GMT-04:00 xy <notifications@github.com>:

**Comment by xxnet** [comment]
有遇到同样问题未解决的朋友，请帮忙提供以下信息：
find /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/ 
把信息发出来，帮助分析。

如果内容太多，可以：
find /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/ > ~/ lib.txt
让后把用户目录下的lib.txt作为附件贴上来，或发我邮箱： xxnet.dev@gmail.com
谢谢

**Comment by xxnet** [comment]
1.8.1 发布
重构了Mac下的托盘实现，不再依赖 Foundation模块

请测试
