### ISSUE TITLE
python: "error: can't start new thread" && logs: create ssl timeout fail

### ISSUE THREAD

**Issue by Reeeeeemi** [XX-net/XX-Net#948]
xx-net 运行在树莓派上，同时还运行了cntlm供其他几台台式机通过树莓派代理上网。
统计了一下，大概平均15小时会出现一次python不能开启新的thread的问题，重启xx-net问题可以解决。请问如何永久解决该问题？

Logs:
Sep 7 12:01:10 - [DEBUG] GAE CONNECT GET https://www.google.com/省略...

Sep 7 12:01:25 - [DEBUG] create ssl timeout fail.

Sep 7 12:01:40 - [DEBUG] create ssl timeout fail.

Terminal:
Exception happened during processing of request from ('127.0.0.1', 41986)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 604, in process_request
    t.start()
  File "/usr/lib/python2.7/threading.py", line 495, in start
    _start_new_thread(self.__bootstrap, ())
error: can't start new thread

**Comment by xxnet** [comment]
XX-Net是哪个版本？

用ps H 进程号
看看启动了多少线程。

2015-09-07 20:14 GMT+08:00 Reeeeeemi <notifications@github.com>:

**Comment by Reeeeeemi** [comment]
自动升级“检查最新版本”一直在检查状态，刷新时显示“发生未知错误，请刷新页面重试”，有其他查询版本的方式吗？上次部署是2.1.2，自动升级选择了长期稳定版所以版本应该还是2.1.2 
刚重启...下一次出现问题再来提交详细信息...

**Comment by Reeeeeemi** [comment]
检查版本失败
Terminal:
Sep  7 12:37:26 - [ERROR] download https://raw.githubusercontent.com/XX-net/XX-Net/master/README.md to /home/pi/Remi/XX-Net-2.1.2/data/downloads/README.md fail:URLError(error(104, 'Connection reset by peer'),)

**Comment by Reeeeeemi** [comment]
重启之后可以更新了...

**Comment by xxnet** [comment]
无法翻墙，导致无法升级。这个问题新版已经解决。

请手动到github下载 2.3.0

2015-09-07 20:40 GMT+08:00 Reeeeeemi <notifications@github.com>:

**Comment by Reeeeeemi** [comment]
python: "error: can't start new thread" again 
XX-Net 2.3.0
ps -H
  PID TTY      STAT   TIME COMMAND
 3352 tty1     Ss+    0:00 /sbin/getty --noclear 38400 tty1
 3353 tty2     Ss+    0:00 /sbin/getty 38400 tty2
 3354 tty3     Ss+    0:00 /sbin/getty 38400 tty3
 3355 tty4     Ss+    0:00 /sbin/getty 38400 tty4
 3356 tty5     Ss+    0:00 /sbin/getty 38400 tty5
 3357 tty6     Ss+    0:00 /sbin/getty 38400 tty6
 3358 ttyAMA0  Ss+    0:00 /sbin/getty -L ttyAMA0 115200 vt100
 3511 pts/0    Ss     0:00 /bin/bash
 3515 pts/0    S+     0:10 mentohust
 4347 pts/1    Ss     0:00 /bin/bash
 4588 pts/2    Ss     0:00 /bin/bash
 4745 pts/1    S+     0:00 /bin/bash ./start.sh
 4747 pts/1    Sl+    0:01 python2 launcher/start.py
 4747 pts/1    Sl+    0:46 python2 launcher/start.py
 4747 pts/1    Sl+    0:48 python2 launcher/start.py
 4747 pts/1    Sl+    0:45 python2 launcher/start.py
 4747 pts/1    Sl+    0:49 python2 launcher/start.py
 4747 pts/1    Sl+    0:49 python2 launcher/start.py
 4747 pts/1    Sl+    0:48 python2 launcher/start.py
 4747 pts/1    Sl+    0:45 python2 launcher/start.py
 4747 pts/1    Sl+    0:42 python2 launcher/start.py
 4747 pts/1    Sl+    0:46 python2 launcher/start.py
 4747 pts/1    Sl+    0:52 python2 launcher/start.py
 4747 pts/1    Sl+    0:49 python2 launcher/start.py
 4747 pts/1    Sl+    0:47 python2 launcher/start.py
 4747 pts/1    Sl+    0:46 python2 launcher/start.py
 4747 pts/1    Sl+    0:42 python2 launcher/start.py
 4747 pts/1    Sl+    0:46 python2 launcher/start.py
 4747 pts/1    Sl+    0:47 python2 launcher/start.py
 4747 pts/1    Sl+    0:52 python2 launcher/start.py
 4747 pts/1    Sl+    0:43 python2 launcher/start.py
 4747 pts/1    Sl+    0:47 python2 launcher/start.py
 4747 pts/1    Sl+    0:45 python2 launcher/start.py
 4747 pts/1    Sl+    0:48 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:10 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:05 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:18 python2 launcher/start.py
 4747 pts/1    Sl+    0:47 python2 launcher/start.py
 4747 pts/1    Sl+    0:44 python2 launcher/start.py
 4747 pts/1    Sl+    0:51 python2 launcher/start.py
 4747 pts/1    Sl+    0:37 python2 launcher/start.py
 4747 pts/1    Sl+    0:40 python2 launcher/start.py
 4747 pts/1    Sl+    0:50 python2 launcher/start.py
 4747 pts/1    Sl+    0:50 python2 launcher/start.py
 4747 pts/1    Sl+    0:50 python2 launcher/start.py
 4747 pts/1    Sl+    0:40 python2 launcher/start.py
 4747 pts/1    Sl+    0:38 python2 launcher/start.py
 4747 pts/1    Sl+    0:47 python2 launcher/start.py
 4747 pts/1    Sl+    0:43 python2 launcher/start.py
 4747 pts/1    Sl+    0:31 python2 launcher/start.py
 4747 pts/1    Sl+    0:46 python2 launcher/start.py
 4747 pts/1    Sl+    0:48 python2 launcher/start.py
 4747 pts/1    Sl+    0:48 python2 launcher/start.py
 4747 pts/1    Sl+    0:50 python2 launcher/start.py
 4747 pts/1    Sl+    0:40 python2 launcher/start.py
 4747 pts/1    Sl+    0:33 python2 launcher/start.py
 4747 pts/1    Sl+    0:06 python2 launcher/start.py
 4747 pts/1    Sl+    0:30 python2 launcher/start.py
 4747 pts/1    Sl+    0:23 python2 launcher/start.py
 4747 pts/1    Sl+    0:23 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 4747 pts/1    Sl+    0:00 python2 launcher/start.py
 5491 pts/2    Sl+    0:06 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
 5491 pts/2    Sl+    0:00 cntlm -f
14101 pts/3    Ss     0:00 /bin/bash
14121 pts/3    R+     0:00 ps H

**Comment by Reeeeeemi** [comment]
XX-Net listens on port 8087, How to configure it to carry all connections, i.e.,  be system wide. [No Chinese Input Method, sorry...]

**Comment by xxnet** [comment]
1. how many scan thread you set?
  set less scan thread. I count you have 240 thread in XX-Net process.
2. > XX-Net listens on port 8087, How to configure it to carry all
connections, i.e., be system wide
  You means provide proxy for other PC?
      you need to change the bind ip. read the wiki and edit
gae_proxylocal/proxy.ini



2015-09-13 10:26 GMT+08:00 Reeeeeemi <notifications@github.com>:
