### ISSUE TITLE
升级3.9.6失败，start文件无法打开程序

### ISSUE THREAD

**Issue by WuMoKunTian** [XX-net/XX-Net#9503]
系统：MAC OS X 10.12.6
XX-NET程序内设置成“自动升级”
=====================
1月12日，程序自动升级3.9.6，完成后一直没能启动成功。于是，手动关闭。
结果悲剧了……重启后，bash无法通过start打开程序，文件夹里双击start也无效。

后来，在github上手动重新下载，同样无法打开。

求解决方案

**Comment by x86nat** [comment]
同样问题，升级后 管理界面都打不开了。
XX-Net version:3.9.6
Jan 17 11:42:30.997 [launcher][INFO] use build-in openssl lib
Jan 17 11:42:31.033 [launcher][INFO] start XX-Net 3.9.6
Jan 17 11:42:31.033 [launcher][DEBUG] start confirm_xxnet_exit
Jan 17 11:42:31.036 [launcher][DEBUG] good, xxnet:8085 clear!
Jan 17 11:42:31.036 [launcher][DEBUG] finished confirm_xxnet_exit
Jan 17 11:42:31.069 [gae_proxy][DEBUG] config use_ipv6 1 upgrade to auto
Jan 17 11:42:31.155 [gae_proxy][INFO] SSL use version:TLSv1_2
Jan 17 11:42:31.160 [gae_proxy][INFO] OpenSSL support alpn
Jan 17 11:42:31.162 [gae_proxy][INFO] load ip range file:/home/leo/Work/prog/XX-Net-3.3.1/code/3.9.6/gae_proxy/local/ip_range.txt
Jan 17 11:42:31.390 [gae_proxy][DEBUG] network IPv4 is ok, cost:316 ms
Jan 17 11:42:31.461 [gae_proxy][INFO] load google ip_list num:6000, gws num:6000
Jan 17 11:42:31.518 [gae_proxy][DEBUG] config use_ipv6 1 upgrade to auto
Jan 17 11:42:31.519 [gae_proxy][DEBUG] ## GAEProxy set keep_running: True
Jan 17 11:42:31.519 [gae_proxy][INFO] ------------------------------------------------------
Jan 17 11:42:31.519 [gae_proxy][INFO] Python Version     : 2.7.12
Jan 17 11:42:31.519 [gae_proxy][INFO] OS                 : Dist:Ubuntu; Version:16.04; ID:xenial
Jan 17 11:42:31.519 [gae_proxy][INFO] Listen Address     : 127.0.0.1:8087
Jan 17 11:42:31.519 [gae_proxy][INFO] GAE APPID          :
 ------------------------------ ------------------------------ ------------------------------
Jan 17 11:42:31.519 [gae_proxy][INFO] ------------------------------------------------------
Jan 17 11:42:31.548 [gae_proxy][DEBUG] Importing CA
Jan 17 11:42:31.644 [gae_proxy][INFO] Database $HOME/.pki/nssdb cert exist
Jan 17 11:42:31.644 [gae_proxy][DEBUG] Begin importing CA to Firefox
Jan 17 11:42:31.644 [gae_proxy][INFO] Removing old cert to Firefox in /home/leo/.mozilla/firefox/v2flu09z.default
GoAgent XX-Net - GoAgent                                     C,,  
Jan 17 11:42:31.663 [gae_proxy][INFO] Add new cert to Firefox in /home/leo/.mozilla/firefox/v2flu09z.default
Jan 17 11:42:31.671 [gae_proxy][ERROR] bind to 127.0.0.1:8087 fail:error(98, '\xe5\x9c\xb0\xe5\x9d\x80\xe5\xb7\xb2\xe5\x9c\xa8\xe4\xbd\xbf\xe7\x94\xa8')
Exception in thread Thread-20:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/leo/Work/prog/XX-Net-3.3.1/code/3.9.6/gae_proxy/start.py", line 18, in main
    client.main(args)
  File "/home/leo/Work/prog/XX-Net-3.3.1/code/3.9.6/gae_proxy/local/proxy.py", line 147, in main
    proxy_daemon = simple_http_server.HTTPServer((listen_ip, config.LISTEN_PORT), proxy_handler.GAEProxyHandler, logger=xlog)
  File "/home/leo/Work/prog/XX-Net-3.3.1/code/3.9.6/python27/1.0/lib/noarch/simple_http_server.py", line 382, in __init__
    self.init_socket()
  File "/home/leo/Work/prog/XX-Net-3.3.1/code/3.9.6/python27/1.0/lib/noarch/simple_http_server.py", line 392, in init_socket
    self.add_listen(addr)
  File "/home/leo/Work/prog/XX-Net-3.3.1/code/3.9.6/python27/1.0/lib/noarch/simple_http_server.py", line 406, in add_listen
    raise Exception(err_string)
Exception: bind to 127.0.0.1:8087 fail:error(98, '\xe5\x9c\xb0\xe5\x9d\x80\xe5\xb7\xb2\xe5\x9c\xa8\xe4\xbd\xbf\xe7\x94\xa8')

**Comment by rarest** [comment]
mac 下3.9.6  ./start 无法启动

**Comment by SeaHOH** [comment]
@rarest 进程没有完全退出，先杀一下。

**Comment by NARUTONBM** [comment]
同样的问题，我重启后，删除xx_net，重新下载解压，双击start也打不开了
