### ISSUE TITLE
3.9.6打不开XX-net管理界面？试过http://127.0.0.1:8085 http://127.0.0.1:8086  http://127.0.0.1:8087 都不行

### ISSUE THREAD

**Issue by x86nat** [XX-net/XX-Net#9543]
XX-Net version:3.9.6
Jan 19 12:05:42.181 [launcher][INFO] use build-in openssl lib
Jan 19 12:05:42.181 [launcher][INFO] start XX-Net 3.9.6
Jan 19 12:05:42.181 [launcher][DEBUG] start confirm_xxnet_exit
Jan 19 12:05:42.182 [launcher][DEBUG] good, xxnet:8085 clear!
Jan 19 12:05:42.182 [launcher][DEBUG] finished confirm_xxnet_exit
Jan 19 12:05:42.187 [gae_proxy][DEBUG] config use_ipv6 1 upgrade to auto
Jan 19 12:05:42.250 [gae_proxy][INFO] SSL use version:TLSv1_2
Jan 19 12:05:42.251 [gae_proxy][INFO] OpenSSL support alpn
Jan 19 12:05:42.252 [gae_proxy][INFO] load ip range file:/home/leo/Work/prog/XX-Net-3.3.1/code/3.9.6/gae_proxy/local/ip_range.txt
Jan 19 12:05:42.354 [gae_proxy][INFO] load google ip_list num:6000, gws num:6000
Jan 19 12:05:42.377 [gae_proxy][DEBUG] config use_ipv6 1 upgrade to auto
Jan 19 12:05:42.377 [gae_proxy][DEBUG] ## GAEProxy set keep_running: True
Jan 19 12:05:42.378 [gae_proxy][INFO] ------------------------------------------------------
Jan 19 12:05:42.378 [gae_proxy][INFO] Python Version     : 2.7.12
Jan 19 12:05:42.378 [gae_proxy][INFO] OS                 : Dist:Ubuntu; Version:16.04; ID:xenial
Jan 19 12:05:42.378 [gae_proxy][INFO] Listen Address     : 127.0.0.1:8087

**Comment by fengzhichu** [comment]
我也遇到了同样的问题，我用命令启动时，抛出了一个异常：

```c
Exception in thread Thread-20:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/hummer/Documents/GitHub/XX-Net/code/default/gae_proxy/start.py", line 18, in main
    client.main(args)
  File "/Users/hummer/Documents/GitHub/XX-Net/code/default/gae_proxy/local/proxy.py", line 139, in main
    CertUtil.init_ca()
  File "/Users/hummer/Documents/GitHub/XX-Net/code/default/gae_proxy/local/cert_util.py", line 606, in init_ca
    CertUtil.ca_privatekey = OpenSSL.crypto.load_privatekey(OpenSSL.crypto.FILETYPE_PEM, content)
  File "/Users/hummer/Documents/GitHub/XX-Net/code/default/python27/1.0/lib/noarch/OpenSSL/crypto.py", line 2483, in load_privatekey
    _raise_current_error()
  File "/Users/hummer/Documents/GitHub/XX-Net/code/default/python27/1.0/lib/noarch/OpenSSL/_util.py", line 48, in exception_from_error_queue
    raise exception_type(errors)
Error: []
```

系统版本：macOS 10.12.6

切换到3.8.5后，一切正常。

不过我发现一个问题，第一次打开3.8.5的时候，系统提示需要输入用户密码，但是3.9.6没有提示。

**Comment by wooowooo** [comment]
提示输入密码可能是要导入证书到系统。我猜的

**Comment by Lancenas** [comment]
查查端口是否有冲突

**Comment by xxnet** [comment]
@SeaHOH 
  看看是不是平台有关的问题，怎么处理比较好

**Comment by lchong649cn** [comment]
3.8.6遇到同样问题，切回3.8.5问题同堂存在

**Comment by xxnet** [comment]
​Mac 什么版本？

**Comment by x86nat** [comment]
@xxnet  
Ubuntu 16.04
好像没有开启8085端口，去哪里让启动起来?

leo@leo-K46CB:~/Work/prog/XX-Net-3.3.1$ netstat -an |grep 8085
leo@leo-K46CB:~/Work/prog/XX-Net-3.3.1$ netstat -an |grep 8086
leo@leo-K46CB:~/Work/prog/XX-Net-3.3.1$ netstat -an |grep 8087
tcp        0      0 127.0.0.1:8087          0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.1:8087          127.0.0.1:45366         ESTABLISHED
tcp        0      0 127.0.0.1:45366         127.0.0.1:8087          ESTABLISHED
leo@leo-K46CB:~/Work/prog/XX-Net-3.3.1$

**Comment by SeaHOH** [comment]
@fengzhichu @xxnet 不好意思才注意到。

怀疑是权限不够，没有生成 `CAkey.pem`？
或者是文件损坏，删除 `CAkey.pem` 试试？

**Comment by xxnet** [comment]
​@x86nat
  试试
  rm -rf /Users/hummer/Documents/GitHub/XX-Net/code/default/
python27/1.0/lib/noarch/OpenSSL
把内置的OpenSSL 库删除掉看看

**Comment by xxnet** [comment]
@x86nat 
   启动之后没有更多的日志了吗？
  试试重新下载一个版本。

@fengzhichu 
  试试
  rm -rf /Users/hummer/Documents/GitHub/XX-Net/code/default/
python27/1.0/lib/noarch/OpenSSL
把内置的OpenSSL 库删除掉看看

**Comment by fengzhichu** [comment]
@SeaHOH 
@xxnet 

谢谢各位，今天下载了最新版(3.9.6)，直接就可以正常使用了。
🙏🙏🙏

**Comment by x86nat** [comment]
hi,all,
XX-Net 3.9.6, Everything is OK. Welcome to the FREE Internet.
可以打开管理界面了，原因是文件夹"/XX-Net-3.3.1/data/smart_router"没有写入权限。

但是又出来新问题，"Jan 29 15:12:23.284 - [INFO] dns_server stop "
需要root运行吗？

Smart Router Log:

Jan 29 15:12:23.191 - [INFO] Load file:/home/leo/Work/prog/XX-Net-3.3.1/code/3.9.6/smart_router/local/gfw_black_list.txt
Jan 29 15:12:23.204 - [INFO] Load file:/home/leo/Work/prog/XX-Net-3.3.1/code/3.9.6/smart_router/local/gfw_white_list.txt
Jan 29 15:12:23.280 - [DEBUG] include IP range number：3608
Jan 29 15:12:23.280 - [DEBUG] save to file:/home/leo/Work/prog/XX-Net-3.3.1/data/smart_router/cn_ipdb.dat
Jan 29 15:12:23.282 - [DEBUG] use local DNS server:127.0.1.1
Jan 29 15:12:23.282 - [DEBUG] use local DNS server:114.114.114.114
Jan 29 15:12:23.282 - [DEBUG] use local DNS server:180.76.76.76
Jan 29 15:12:23.282 - [DEBUG] use local DNS server:198.15.67.245
Jan 29 15:12:23.282 - [DEBUG] use local DNS server:202.46.32.19
Jan 29 15:12:23.282 - [DEBUG] use local DNS server:64.214.116.84
Jan 29 15:12:23.283 - [INFO] server 127.0.0.1:8086 started.
Jan 29 15:12:23.284 - [INFO] Proxy server listen:127.0.0.1:8086.
**Jan 29 15:12:23.284 - [WARNING] bind DNS 127.0.0.1:53 fail
Jan 29 15:12:23.284 - [WARNING] You can try: install libcap2-bin
Jan 29 15:12:23.284 - [WARNING] Then: sudo setcap 'cap_net_bind_service=+ep' /usr/bin/python2.7
Jan 29 15:12:23.284 - [WARNING] Or run XX-Net as root
Jan 29 15:12:23.284 - [INFO] dns_server stop**
Jan 29 15:14:10.742 - [DEBUG] Web_control 127.0.0.1:50052 POST /config
Jan 29 15:14:14.533 - [DEBUG] Web_control 127.0.0.1:50052 POST /rules
Jan 29 15:14:15.448 - [DEBUG] Web_control 127.0.0.1:50052 POST /cache
Jan 29 15:15:08.219 - [DEBUG] Web_control 127.0.0.1:50052 POST /config

**Comment by xxnet** [comment]
​@x86nat
   DNS fail 不影响使用，除非要提供DNS服务
