### ISSUE TITLE
3.9.6 版的两个bug

### ISSUE THREAD

**Issue by XndroidDev** [XX-net/XX-Net#9621]
1. 访问 https://youtube.com

```
Jan 26 11:32:03.303 - [INFO] domain www.youtube.com:443 gae
Jan 26 11:32:03.371 - [DEBUG] host:www.youtube.com:443 do gae
Jan 26 11:32:03.467 - [ERROR] domain host:www.youtube.com:443 rule:gae except:AttributeError("'NoneType' object has no attribute 'group'",)
Jan 26 11:32:03.496 - [ERROR] Except stack:Traceback (most recent call last): File "/data/user/0/net.xndroid/files/xndroid_files/xxnet/code/3.9.6/smart_router/local/smart_route.py", line 297, in try_loop do_gae(sock, host, port, client_address, left_buf) File "/data/user/0/net.xndroid/files/xndroid_files/xxnet/code/3.9.6/smart_router/local/smart_route.py", line 266, in do_gae req.do_METHOD() File "/data/user/0/net.xndroid/files/xndroid_files/xxnet/code/3.9.6/gae_proxy/local/proxy_handler.py", line 223, in do_METHOD return self.do_AGENT() File "/data/user/0/net.xndroid/files/xndroid_files/xxnet/code/3.9.6/gae_proxy/local/proxy_handler.py", line 271, in do_AGENT gae_handler.handler(self.command, self.path, request_headers, payload, self.wfile) File "/data/user/0/net.xndroid/files/xndroid_files/xxnet/code/3.9.6/gae_proxy/local/gae_handler.py", line 525, in handler r'bytes (\d+)-(\d+)/(\d+)', content_range).group(1, 2, 3)) AttributeError: 'NoneType' object has no attribute 'group'
Jan 26 11:32:03.543 - [INFO] domain www.youtube.com:443 socks
Jan 26 11:32:03.544 - [DEBUG] domain socks to www.youtube.com:443 except:XTunnelNotRunning()
Jan 26 11:32:03.795 - [DEBUG] recev 6 from:('114.114.114.114', 53) domain:www.youtube.com. org:www.youtube.com
Jan 26 11:32:04.010 - [INFO] domain www.google.com:443 gae
Jan 26 11:32:04.016 - [INFO] domain www.google.com:443 gae
Jan 26 11:32:04.047 - [INFO] domain www.youtube.com:443 socks
Jan 26 11:32:04.047 - [DEBUG] domain socks to www.youtube.com:443 except:XTunnelNotRunning()
```
其中 content_range的值为:
```
bytes */439979
```
https://github.com/XX-net/XX-Net/pull/9620

2. 访问http://google.com
```
Jan 26 11:59:15.629 - [DEBUG] http ('10.1.2.3', 33200) connect to google.com:80 GET /
Jan 26 11:59:15.636 - [DEBUG] domain domain:google.com get sni fail
Jan 26 11:59:15.636 - [INFO] domain google.com:80 socks
Jan 26 11:59:15.644 - [DEBUG] domain socks to google.com:80 except:XTunnelNotRunning()
Jan 26 11:59:15.941 - [DEBUG] recev 1 from:('114.114.114.114', 53) domain:google.com. org:google.com
```
https的访问正常

另外, 刚刚看了一下br编码相关的代码, 认为可能是因为youtube中有的请求使用br编码, 有的请求使用gz编码. @xxnet 
![image](https://user-images.githubusercontent.com/32808859/35427401-283f0b3e-02a4-11e8-8454-503b69af3aaa.png)

**Comment by xxnet** [comment]
​已经合并fix
