### ISSUE TITLE
这是什么错误，一段时间后就不行了。

### ISSUE THREAD

**Issue by excellenttank** [XX-net/XX-Net#9655]
Jan 30 21:47:34.655 - [ERROR] ssl_timeout_cb except:error("can't start new thread",)

Jan 30 21:47:34.655 - [ERROR] Except stack:Traceback (most recent call last): File "G:\Tools\Google\XX-Net-3.7.16\code\3.9.6\gae_proxy\local\connect_manager.py", line 230, in keep_alive_thread self.ssl_timeout_cb(ssl_sock) File "G:\Tools\Google\XX-Net-3.7.16\code\3.9.6\gae_proxy\local\http_dispatcher.py", line 81, in on_ssl_created_cb worker = HTTP1_worker(ssl_sock, self.close_cb, self.retry_task_cb, self._on_worker_idle_cb, self.log_debug_data) File "G:\Tools\Google\XX-Net-3.7.16\code\3.9.6\gae_proxy\local\http1.py", line 28, in __init__ threading.Thread(target=self.work_loop).start() File "G:\Tools\Google\XX-Net-3.7.16\code\3.9.6\python27\1.0\lib\threading.py", line 736, in start _start_new_thread(self.__bootstrap, ()) error: can't start new thread

**Comment by excellenttank** [comment]
然后状态是“请检查浏览器代理设置。”

**Comment by excellenttank** [comment]
我现在就是3.9.6

**Comment by gjbg1989** [comment]
3.9.6正常路过

**Comment by xxnet** [comment]
​无法启动新线程

**Comment by gjbg1989** [comment]
线程开太多？

**Comment by excellenttank** [comment]
嗯，我也知道是无法启动新线程，是网站请求的资源过多导致的么？ @xxnet

**Comment by GoodSake** [comment]
不。
