### ISSUE TITLE
3.10.2x-tunnel连接服务器失败：AttributeError("'str' object has no attribute 'error'",)

### ISSUE THREAD

**Issue by lkhtty** [XX-net/XX-Net#9774]
x-tunnel登陆页面不间断出现这个提示连接服务器失败：AttributeError("'str' object has no attribute 'error'",)，但是过一会就会又登陆上，能用，一会又出现这个提示服务器登出，出现这个提示时候就不能用了，有大神解决下吗？3.9.6一切正常，3.10.2  SWITCHYOMEGA代理设置需要更新吗？

**Comment by gjbg1989** [comment]
是有报错，刷新即好，貌似没：一会又出现这个提示服务器登出，出现这个提示时候就不能用了
？也没：SWITCHYOMEGA代理设置需要更新😱

**Comment by lkhtty** [comment]
这一阵正常了，有10分钟就一直是这样，报错，账号登出登入

**Comment by bolaparte** [comment]
正常

**Comment by xxnet** [comment]
​有日志发现异常吗？

或者浏览器里，按F12看控制台，有没有日志

**Comment by gjbg1989** [comment]
![default](https://user-images.githubusercontent.com/13290970/36308357-4e3fa678-135b-11e8-997d-e6088e5658e8.png)

**Comment by gjbg1989** [comment]
@xxnet 3.10.3 无数"[DEBUG] create ssl timeout fail. "依旧😂

**Comment by 23Ben** [comment]
Feb 17 09:29:06.483 - [INFO] xxnet_version:3.10.3

Feb 17 09:29:06.483 - [INFO] server 127.0.0.1:1080 started.

Feb 17 09:29:06.483 - [INFO] Socks5 server listen:127.0.0.1:1080.

Feb 17 09:29:11.485 - [WARNING] start report_stat

Feb 17 09:29:16.548 - [WARNING] front retry center.xx-net.net/report_stat

Feb 17 09:29:23.586 - [WARNING] front retry center.xx-net.net/report_stat

Feb 17 09:29:30.630 - [WARNING] front retry center.xx-net.net/report_stat

Feb 17 09:29:37.684 - [WARNING] front retry center.xx-net.net/report_stat

Feb 17 09:29:44.728 - [WARNING] front retry center.xx-net.net/report_stat

Feb 17 09:29:46.730 - [WARNING] api:/report_stat fail:status:602 t:35

Feb 17 09:29:46.730 - [WARNING] report fail.

Feb 17 09:30:46.731 - [WARNING] start report_stat

Feb 17 09:30:51.811 - [WARNING] front retry center.xx-net.net/report_stat

Feb 17 09:30:58.859 - [WARNING] front retry center.xx-net.net/report_stat

Feb 17 09:31:05.911 - [WARNING] front retry center.xx-net.net/report_stat

Feb 17 09:31:12.956 - [WARNING] front retry center.xx-net.net/report_stat

Feb 17 09:31:20.004 - [WARNING] front retry center.xx-net.net/report_stat

Feb 17 09:31:22.006 - [WARNING] api:/report_stat fail:status:602 t:35

Feb 17 09:31:22.006 - [WARNING] report fail.

Feb 17 09:32:22.007 - [WARNING] start report_stat

Feb 17 09:32:27.075 - [WARNING] front retry center.xx-net.net/report_stat

Feb 17 09:32:34.125 - [ERROR] order e:AttributeError("'str' object has no attribute 'error'",)

Feb 17 09:32:34.126 - [ERROR] Except stack:Traceback (most recent call last): File "D:\tool\XX-Net-3.1.0\code\3.10.3\x_tunnel\local\proxy_session.py", line 725, in call_api data=upload_post_data, timeout=5) File "D:\tool\XX-Net-3.1.0\code\3.10.3\x_tunnel\local\front_dispatcher.py", line 83, in request method, host=host, path=path, headers=dict(headers), data=data, timeout=timeout) File "D:\tool\XX-Net-3.1.0\code\3.10.3\x_tunnel\local\heroku_front\front.py", line 176, in request request_headers, request_body, timeout) File "D:\tool\XX-Net-3.1.0\code\3.10.3\x_tunnel\local\heroku_front\front.py", line 146, in _request xlog.exception("front request undefined undefinedundefined fail:%r", method, host, path, e) File "D:\tool\XX-Net-3.1.0\code\3.10.3\python27\1.0\lib\noarch\xlog.py", line 297, in exception self.error(fmt, *args, **kwargs) AttributeError: 'str' object has no attribute 'error'

Feb 17 09:32:34.126 - [WARNING] report fail.

Feb 17 09:32:50.697 - [DEBUG] x_tunnel force update info

Feb 17 09:32:51.065 - [INFO] api:/login success t:367

Feb 17 09:32:51.065 - [INFO] update xt_server v13.xx-net.net:443

Feb 17 09:32:51.065 - [INFO] request_balance host:v13.xx-net.net port:443 balance:0.000000 quota:1161382570264.000000

Feb 17 11:19:11.802 - [DEBUG] x_tunnel force update info

Feb 17 11:19:16.848 - [WARNING] front retry center.xx-net.net/login

Feb 17 11:19:19.201 - [INFO] api:/login success t:7398

Feb 17 11:19:19.201 - [INFO] request_balance host:v13.xx-net.net port:443 balance:0.000000 quota:1161382570264.000000

Feb 17 11:19:52.540 - [INFO] Close Socks5 server

Feb 17 11:19:52.540 - [INFO] Stopping session

Feb 17 11:19:52.540 - [WARNING] socket accept fail(errno: 9).

Feb 17 11:19:52.641 - [INFO] use config_path:D:\tool\XX-Net-3.1.0\data\x_tunnel\client.json

Feb 17 11:19:52.642 - [INFO] X-Tunnel window:16777216

Feb 17 11:19:52.642 - [INFO] xxnet_version:3.10.3

Feb 17 11:19:52.642 - [INFO] server 127.0.0.1:1080 started.

Feb 17 11:19:52.642 - [INFO] Socks5 server listen:127.0.0.1:1080.

Feb 17 11:19:57.643 - [WARNING] start report_stat

Feb 17 11:20:27.658 - [WARNING] api:/report_stat fail:status:602 t:30

Feb 17 11:20:27.658 - [WARNING] report fail.

Feb 17 11:21:27.659 - [WARNING] start report_stat

Feb 17 11:21:57.678 - [WARNING] api:/report_stat fail:status:602 t:30

Feb 17 11:21:57.678 - [WARNING] report fail.

Feb 17 11:22:57.679 - [WARNING] start report_stat

Feb 17 11:23:27.700 - [WARNING] api:/report_stat fail:status:602 t:30

Feb 17 11:23:27.700 - [WARNING] report fail.

Feb 17 11:24:27.702 - [WARNING] start report_stat

Feb 17 11:24:30.217 - [INFO] api:/report_stat success t:2515

Feb 17 11:25:30.218 - [WARNING] start report_stat

Feb 17 11:25:35.305 - [WARNING] front retry center.xx-net.net/report_stat

Feb 17 11:25:37.609 - [INFO] api:/report_stat success t:7391

**Comment by 23Ben** [comment]
Feb 17 09:29:06.437 - [INFO] SSL use version:TLSv1_2

Feb 17 09:29:06.439 - [INFO] OpenSSL support alpn

Feb 17 09:29:06.439 - [INFO] load ip range file:D:\tool\XX-Net-3.1.0\code\3.10.3\x_tunnel\local\cloudflare_front\ip_range.txt

Feb 17 09:29:06.442 - [INFO] load ip_list num:100, target num:100

Feb 17 09:29:07.239 - [INFO] updated cloudflare front domains from github.

Feb 17 09:29:17.652 - [DEBUG] create_ssl update ip:190.93.247.123 time:5163 h2:1 sni:idmcracks.com, host:mostlygood.ga

Feb 17 09:29:23.653 - [DEBUG] connect 104.19.128.160 fail:error("conn fail, sni:my-sub-shop.site, top:flar.tk e:timeout('timed out',)",)

Feb 17 09:29:23.653 - [DEBUG] report_connect_fail:104.19.128.160

Feb 17 09:29:26.357 - [DEBUG] create_ssl update ip:141.101.114.208 time:703 h2:1 sni:gearinguptolose.com, host:superx.gq

Feb 17 09:29:26.384 - [DEBUG] WindowUpdateFrame 2147418112

Feb 17 09:29:34.192 - [DEBUG] http2 190.93.247.123 send error:SysCallError(10054, 'WSAECONNRESET')

Feb 17 09:29:34.192 - [DEBUG] 190.93.247.123 worker close:send fail:SysCallError(10054, 'WSAECONNRESET')

Feb 17 09:29:34.192 - [DEBUG] 190.93.247.123 _consume_single_frame:SysCallError(10054, 'WSAECONNRESET'), inactive time:22

Feb 17 09:29:34.192 - [DEBUG] 190.93.247.123 close:send fail:SysCallError(10054, 'WSAECONNRESET')

Feb 17 09:29:34.192 - [DEBUG] 190.93.247.123 worker close:disconnect:SysCallError(10054, 'WSAECONNRESET')

Feb 17 09:29:34.192 - [DEBUG] 190.93.247.123 close:disconnect:SysCallError(10054, 'WSAECONNRESET')

Feb 17 09:32:51.065 - [DEBUG] POST superx.gq/login status:200 trace:0:start_request,0:get_task(219),0:get_worker(0):141.101.114.208,0:h2_req,6:start send header,1:start send left body,0:end send left body,357:h2_get_head,0:get_response,:1

Feb 17 09:36:51.266 - [DEBUG] 141.101.114.208 _consume_single_frame:ConnectionResetError(), inactive time:240

Feb 17 09:36:51.266 - [DEBUG] 141.101.114.208 worker close:disconnect:ConnectionResetError()

Feb 17 09:36:51.266 - [DEBUG] 141.101.114.208 close:disconnect:ConnectionResetError()

Feb 17 09:36:53.317 - [DEBUG] create_ssl update ip:104.16.172.76 time:782 h2:1 sni:drafabianamello.com, host:flar.tk

Feb 17 09:36:53.359 - [DEBUG] WindowUpdateFrame 2147418112

Feb 17 09:40:53.841 - [DEBUG] 104.16.172.76 _consume_single_frame:ConnectionResetError(), inactive time:240

Feb 17 09:40:53.841 - [DEBUG] 104.16.172.76 worker close:disconnect:ConnectionResetError()

Feb 17 09:40:53.841 - [DEBUG] 104.16.172.76 close:disconnect:ConnectionResetError()

Feb 17 09:40:59.826 - [DEBUG] create_ssl update ip:190.93.244.171 time:5289 h2:1 sni:elccc.mx, host:gotoworld.tk

Feb 17 09:41:06.158 - [DEBUG] create_ssl update ip:104.16.55.95 time:5329 h2:1 sni:bayliff.law, host:mostlygood.ga

Feb 17 09:41:07.637 - [DEBUG] connect 198.41.221.229 fail:error("conn fail, sni:rhinofitnessco.com, top:flar.tk e:Error([('SSL routines', 'SSL3_GET_RECORD', 'wrong version number')],)",)

Feb 17 09:41:07.637 - [DEBUG] report_connect_fail:198.41.221.229

Feb 17 09:41:09.900 - [DEBUG] http2 190.93.244.171 send error:Error([('SSL routines', 'ssl3_write_bytes', 'ssl handshake failure')],)

Feb 17 09:41:09.900 - [DEBUG] 190.93.244.171 _consume_single_frame:Error([('SSL routines', 'ssl3_read_bytes', 'ssl handshake failure')],), inactive time:16

Feb 17 09:41:09.901 - [DEBUG] 190.93.244.171 worker close:send fail:Error([('SSL routines', 'ssl3_write_bytes', 'ssl handshake failure')],)

Feb 17 09:41:09.901 - [DEBUG] 190.93.244.171 close:send fail:Error([('SSL routines', 'ssl3_write_bytes', 'ssl handshake failure')],)

Feb 17 09:41:09.901 - [DEBUG] 190.93.244.171 worker close:disconnect:Error([('SSL routines', 'ssl3_read_bytes', 'ssl handshake failure')],)

Feb 17 09:41:09.901 - [DEBUG] 190.93.244.171 close:disconnect:Error([('SSL routines', 'ssl3_read_bytes', 'ssl handshake failure')],)

Feb 17 09:41:10.133 - [DEBUG] create_ssl update ip:104.18.54.33 time:491 h2:1 sni:audiodim.me, host:c-term.tk

Feb 17 09:41:10.160 - [DEBUG] WindowUpdateFrame 2147418112

Feb 17 09:41:16.277 - [DEBUG] http2 104.16.55.95 send error:Error([('SSL routines', 'ssl3_write_bytes', 'ssl handshake failure')],)

Feb 17 09:41:16.277 - [DEBUG] 104.16.55.95 worker close:send fail:Error([('SSL routines', 'ssl3_write_bytes', 'ssl handshake failure')],)

Feb 17 09:41:16.277 - [DEBUG] 104.16.55.95 _consume_single_frame:Error([('SSL routines', 'ssl3_read_bytes', 'ssl handshake failure')],), inactive time:16

Feb 17 09:41:16.277 - [DEBUG] 104.16.55.95 close:send fail:Error([('SSL routines', 'ssl3_write_bytes', 'ssl handshake failure')],)

Feb 17 09:41:16.277 - [DEBUG] 104.16.55.95 worker close:disconnect:Error([('SSL routines', 'ssl3_read_bytes', 'ssl handshake failure')],)

Feb 17 09:41:16.277 - [DEBUG] 104.16.55.95 close:disconnect:Error([('SSL routines', 'ssl3_read_bytes', 'ssl handshake failure')],)

Feb 17 09:45:10.541 - [DEBUG] 104.18.54.33 _consume_single_frame:ConnectionResetError(), inactive time:240

Feb 17 09:45:10.541 - [DEBUG] 104.18.54.33 worker close:disconnect:ConnectionResetError()

Feb 17 09:45:10.541 - [DEBUG] 104.18.54.33 close:disconnect:ConnectionResetError()

Feb 17 09:45:12.157 - [DEBUG] create_ssl update ip:190.93.246.98 time:695 h2:1 sni:aasthavihar.com, host:superx.gq

Feb 17 09:45:12.192 - [DEBUG] WindowUpdateFrame 2147418112

Feb 17 09:49:12.641 - [DEBUG] 190.93.246.98 _consume_single_frame:ConnectionResetError(), inactive time:240

Feb 17 09:49:12.641 - [DEBUG] 190.93.246.98 worker close:disconnect:ConnectionResetError()

Feb 17 09:49:12.641 - [DEBUG] 190.93.246.98 close:disconnect:ConnectionResetError()

Feb 17 11:19:12.462 - [DEBUG] create_ssl update ip:104.24.187.159 time:649 h2:1 sni:hippohosting.tk, host:sawfish.tk

Feb 17 11:19:12.487 - [DEBUG] WindowUpdateFrame 2147418112

Feb 17 11:19:19.201 - [DEBUG] POST sawfish.tk/login status:200 trace:0:start_request,0:get_task(6388),0:get_worker(0):104.24.187.159,0:h2_req,1:start send header,0:start send left body,0:end send left body,348:h2_get_head,0:get_response,:0

Feb 17 11:19:52.537 - [INFO] terminate

Feb 17 11:19:52.537 - [DEBUG] 104.24.187.159 _consume_single_frame:ConnectionResetError(), inactive time:33

Feb 17 11:19:52.537 - [DEBUG] 104.24.187.159 worker close:stop

Feb 17 11:19:52.538 - [DEBUG] 104.24.187.159 close:stop

Feb 17 11:19:52.538 - [DEBUG] 104.24.187.159 worker close:disconnect:ConnectionResetError()

Feb 17 11:19:52.539 - [DEBUG] 104.24.187.159 close:disconnect:ConnectionResetError()

**Comment by 23Ben** [comment]
Feb 17 09:29:06.458 - [INFO] SSL use version:TLSv1_2

Feb 17 09:29:06.459 - [INFO] OpenSSL support alpn

Feb 17 09:30:11.504 - [DEBUG] create ssl timeout fail.

Feb 17 09:31:46.757 - [DEBUG] create ssl timeout fail.

Feb 17 09:33:22.034 - [DEBUG] create ssl timeout fail.

Feb 17 09:34:40.824 - [DEBUG] create ssl timeout fail.

Feb 17 09:35:42.541 - [DEBUG] create ssl timeout fail.

Feb 17 09:36:44.541 - [DEBUG] create ssl timeout fail.

Feb 17 09:37:46.562 - [DEBUG] create ssl timeout fail.

Feb 17 09:38:48.549 - [DEBUG] create ssl timeout fail.

Feb 17 09:39:50.564 - [DEBUG] create ssl timeout fail.

Feb 17 09:40:52.553 - [DEBUG] create ssl timeout fail.

Feb 17 09:41:54.557 - [DEBUG] create ssl timeout fail.

Feb 17 09:42:56.553 - [DEBUG] create ssl timeout fail.

Feb 17 09:43:58.557 - [DEBUG] create ssl timeout fail.

Feb 17 09:45:00.563 - [DEBUG] create ssl timeout fail.

Feb 17 09:46:02.563 - [DEBUG] create ssl timeout fail.

Feb 17 11:19:52.539 - [INFO] terminate

Feb 17 11:25:37.611 - [INFO] set_ips:144.202.7.153

**Comment by xxnet** [comment]
​发布 3.10.4了，修复上面的问题，请测试反馈
https://github.com/XX-net/XX-Net/archive/3.10.4.zip
