### ISSUE TITLE
[3.10.4]在macos上遇到问题的日志输出,在win10上没有问题

### ISSUE THREAD

**Issue by rainplus** [XX-net/XX-Net#9833]
```
Feb 24 13:53:56.929 - [ERROR] recv fail:AttributeError("'str' object has no attribute 'tobytes'",)

Feb 24 13:53:56.929 - [ERROR] Except stack:Traceback (most recent call last): File "/Users/user/XX_Net/code/default/python27/1.0/lib/noarch/front_base/http2_connection.py", line 205, in recv_loop self._consume_single_frame() File "/Users/user/XX_Net/code/default/python27/1.0/lib/noarch/front_base/http2_connection.py", line 321, in _consume_single_frame self._consume_frame_payload(frame, data.tobytes()) File "/Users/user/XX_Net/code/default/python27/1.0/lib/noarch/front_base/http2_connection.py", line 344, in _consume_frame_payload frame.parse_body(data) File "/Users/user/XX_Net/code/default/python27/1.0/lib/noarch/hyper/packages/hyperframe/frame.py", line 548, in parse_body self.data = data[priority_data_length:len(data)-self.total_padding].tobytes() AttributeError: 'str' object has no attribute 'tobytes'
```

**Comment by xxnet** [comment]
​下载 release版，先不要用master分支上的代码

**Comment by rainplus** [comment]
@xxnet 还有一个问题是git clone 出来的旧版本，无法使用sh start进行再启动，最新版本可以。是保存的数据文件格式不一致了么？

**Comment by xxnet** [comment]
​tag的release节点应该是可以的，中间有些版本无法运行是有可能的。

**Comment by rainplus** [comment]
@xxnet 我尝试了tag 3.9.0-3.10.4，通过git checkout 出来的代码，只有3.10.4能通过sh start 启动成功

**Comment by rainplus** [comment]
@xxnet 通过git checkout 不能通过sh start 启动的问题。 原因是之前我使用过sudo xx_net.sh start 启动，导致data下面的某些文件的所有者为root。
