### ISSUE TITLE
3.10.4 无法部署，且状态为一切正常却不能翻墙

### ISSUE THREAD

**Issue by noritor** [XX-net/XX-Net#9834]
以下为诊断信息：
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.16299
os-system: Windows
os-version: 10.0.16299
os-release: 10
os-detail: Version:10-0; Build:16299; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3343.4 Safari/537.36
xxnet-version: 3.10.4
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:208 ipv4:0 ipv6:2
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:0
worker: h1:2 h2:0
scan-ip-thread-num: 10
ip-quality: 1227
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

另外部署时显示如下语句：
2018-02-24 13:59:36,805 - root - ERROR - upload fail:ValidationError("Value '600' for response_code is out of range 100 - 599",)
Traceback (most recent call last):
File "D:\Program Files\XX-Net\code\3.10.4\gae_proxy\server\uploader.py", line 70, in upload
result = appcfg.AppCfgApp(['appcfg', 'rollback', dirname ]).Run()
File "D:\Program Files\XX-Net\code\3.10.4\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 2951, in Run
self.action(self)
File "D:\Program Files\XX-Net\code\3.10.4\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 5044, in __call__
return method()
File "D:\Program Files\XX-Net\code\3.10.4\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 4397, in Rollback
self._Rollback()
File "D:\Program Files\XX-Net\code\3.10.4\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 4442, in _Rollback
appversion.Rollback(force_rollback)
File "D:\Program Files\XX-Net\code\3.10.4\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 2362, in Rollback
force_rollback='1' if force_rollback else '0')
File "D:\Program Files\XX-Net\code\3.10.4\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 1702, in Send
request_size_bytes)
File "D:\Program Files\XX-Net\code\3.10.4\gae_proxy\server\lib\google\appengine\tools\appcfg.py", line 1723, in _RegisterReqestForLogging
request_size_bytes=request_size_bytes))
File "D:\Program Files\XX-Net\code\3.10.4\gae_proxy\server\lib\google\appengine\api\validation.py", line 273, in __init__
self.SetMultiple(attributes)
File "D:\Program Files\XX-Net\code\3.10.4\gae_proxy\server\lib\google\appengine\api\validation.py", line 177, in SetMultiple
self.Set(key, value)
File "D:\Program Files\XX-Net\code\3.10.4\gae_proxy\server\lib\google\appengine\api\validation.py", line 305, in Set
setattr(self, key, value)
File "D:\Program Files\XX-Net\code\3.10.4\gae_proxy\server\lib\google\appengine\api\validation.py", line 361, in __setattr__
value = self.GetValidator(key)(value, key)
File "D:\Program Files\XX-Net\code\3.10.4\gae_proxy\server\lib\google\appengine\api\validation.py", line 599, in __call__
return self.Validate(value, key)
File "D:\Program Files\XX-Net\code\3.10.4\gae_proxy\server\lib\google\appengine\api\validation.py", line 1157, in Validate
% (value, key, self.minimum, self.maximum))
ValidationError: **Value '600' for response_code is out of range 100 - 599**

**Comment by liangliangge521** [comment]
可以把你上一个版本的xxnet/data/gae_proxy文件夹复制到你新下载的xxnet里的同名文件夹覆盖，这样就不用从新部署了，直接就部署上传完成了，(前提是你上个版本的xxnet必须是部署成功的)

**Comment by noritor** [comment]
刚换了CHROME 64 版本 64.0.3282.140
SwitchyOmega 导入原XXNET文件夹内的备份设置，用全局GAE，且GAE自动切换。
IP模式 仅用IPv6。
昨晚能上香港讨论区几分钟。但是后来上不了，连GOOGLE也不行。

隧道参数如下：

类型                    : client
服务器名称              : teredo2.remlab.net
客户端刷新间隔          : 30 秒
客户端端口                : unspecified
状态                    : offline
错误                   : 客户端位于托管网络中

**Comment by gjbg1989** [comment]
😱用全局GAE，且GAE自动切换——XX-Net 自身代理与浏览器代理插件不匹配😂
XX-Net 取消全局代理匹配插件各代理
XX-Net 任一全局代理匹配插件“系统代理”或禁用该插件

**Comment by gjbg1989** [comment]
试试：无线网络属性内取消勾选 IPv6 协议
出问题：多次刷新或重载控制页，或换服务器，或（结束进程pythonw.exe、）禁用再启用网络。。。
#8915 tertdo.bat自动或手动优选服务器（文件解压放在 XX-Net 程序的根目录）
使用ping超时的微软服务器或许更稳定！(win7除外？)结束进程 pythonw.exe，管理权限运行 
netsh int ipv6 set teredo natawareclient default default 3544
（开机）启动XX-Net前即运行以下bat（内容）可观察变化过程，状态dormant即已正常。
:loop
netsh int teredo show state
ping 127.0.0.1 > null
goto loop

**Comment by noritor** [comment]
谢谢 @gjbg1989 ，你说的昨晚都做过一次了。今天也不知道怎么样，再试一次，问题解决了。
