### ISSUE TITLE
WIN7 下管理员权限执行start.bat, 命令行一闪而过, 看不到出了什么错误

### ISSUE THREAD

**Issue by NetWilliam** [XX-net/XX-Net#9843]
* 是否试过最新的测试版本？
  很多问题在最新测试版中已解决。
  

* 是否看过webUI `系统` - `状态` - `公告`？
  请查看[公告](http://localhost:8085/?module=launcher&menu=status)有无类似的问题。
  

* 是否看过Issues区最近的讨论？
  请在 (https://github.com/XX-net/XX-Net/issues) 搜索有无类似的问题。
  

* 是否查看过Wiki（https://github.com/XX-net/XX-Net/wiki）
  请阅读[故障速查手册](https://github.com/XX-net/XX-Net/wiki/故障速查手册)，大部分问题都能在这里找到答案。

* 简单描述遇到的问题：
用管理员权限运行start.bat, 命令行弹出来一下就退出了, 不知道错误在什么地方

* 做过哪些尝试：
直接执行code/version/default/launch/start.py, 但是还是出错

* 请贴出对应模块的状态页
错误状态:
```
Feb 25 02:54:36.951 [launcher][INFO] import build-in openssl fail:AttributeError("'module' object has no attribute 'SSL_
ST_INIT'",)
Feb 25 02:54:37.068 [launcher][INFO] start XX-Net 3.10.4
Feb 25 02:54:37.071 [launcher][DEBUG] start confirm_xxnet_exit
Feb 25 02:54:38.071 [launcher][DEBUG] good, xxnet:8085 clear!
Feb 25 02:54:38.071 [launcher][DEBUG] finished confirm_xxnet_exit
Feb 25 02:54:38.864 [gae_proxy][INFO] SSL use version:TLSv1_2
Feb 25 02:54:38.877 [gae_proxy][INFO] OpenSSL support alpn
Feb 25 02:54:39.054 [gae_proxy][INFO] load ip range file:C:\Users\NWmLWB\Downloads\ChromeDownload\XX-Net-3.10.4\XX-Net-3
.10.4\code\default\gae_proxy\local\ip_range.txt
Feb 25 02:54:39.207 [launcher][ERROR] start module gae_proxy fail:[Errno 2] No such file or directory: 'C:\\Users\\NWmLW
B\\Downloads\\ChromeDownload\\XX-Net-3.10.4\\XX-Net-3.10.4\\code\\default\\gae_proxy\\local\\good_ip.txt'
Feb 25 02:54:39.212 [launcher][ERROR] Except stack:Traceback (most recent call last):
  File "C:\Users\NWmLWB\Downloads\ChromeDownload\XX-Net-3.10.4\XX-Net-3.10.4\code\default\launcher\module_init.py", line
 40, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "C:\Users\NWmLWB\Downloads\ChromeDownload\XX-Net-3.10.4\XX-Net-3.10.4\code\default\gae_proxy\start.py", line 13,
in <module>
    import local.proxy as client
  File "C:\Users\NWmLWB\Downloads\ChromeDownload\XX-Net-3.10.4\XX-Net-3.10.4\code\default\gae_proxy\local\proxy.py", lin
e 95, in <module>
    import proxy_handler
  File "C:\Users\NWmLWB\Downloads\ChromeDownload\XX-Net-3.10.4\XX-Net-3.10.4\code\default\gae_proxy\local\proxy_handler.
py", line 55, in <module>
    import gae_handler
  File "C:\Users\NWmLWB\Downloads\ChromeDownload\XX-Net-3.10.4\XX-Net-3.10.4\code\default\gae_proxy\local\gae_handler.py
", line 79, in <module>
    from google_ip import google_ip
  File "C:\Users\NWmLWB\Downloads\ChromeDownload\XX-Net-3.10.4\XX-Net-3.10.4\code\default\gae_proxy\local\google_ip.py",
 line 732, in <module>
    google_ip = IpManager()
  File "C:\Users\NWmLWB\Downloads\ChromeDownload\XX-Net-3.10.4\XX-Net-3.10.4\code\default\gae_proxy\local\google_ip.py",
 line 67, in __init__
    self.reset()
  File "C:\Users\NWmLWB\Downloads\ChromeDownload\XX-Net-3.10.4\XX-Net-3.10.4\code\default\gae_proxy\local\google_ip.py",
 line 108, in reset
    self.load_ip()
  File "C:\Users\NWmLWB\Downloads\ChromeDownload\XX-Net-3.10.4\XX-Net-3.10.4\code\default\gae_proxy\local\google_ip.py",
 line 137, in load_ip
    with open(file_path, "r") as fd:
IOError: [Errno 2] No such file or directory: 'C:\\Users\\NWmLWB\\Downloads\\ChromeDownload\\XX-Net-3.10.4\\XX-Net-3.10.
4\\code\\default\\gae_proxy\\local\\good_ip.txt'

Feb 25 02:54:39.214 [launcher][ERROR] launcher except:IOError(2, 'No such file or directory')
Feb 25 02:54:39.219 [launcher][ERROR] Except stack:Traceback (most recent call last):
  File "C:\Users\NWmLWB\Downloads\ChromeDownload\XX-Net-3.10.4\XX-Net-3.10.4\code\default\launcher\start.py", line 230,
in <module>
    main()
  File "C:\Users\NWmLWB\Downloads\ChromeDownload\XX-Net-3.10.4\XX-Net-3.10.4\code\default\launcher\start.py", line 207,
in main
    module_init.start_all_auto()
  File "C:\Users\NWmLWB\Downloads\ChromeDownload\XX-Net-3.10.4\XX-Net-3.10.4\code\default\launcher\module_init.py", line
 113, in start_all_auto
    start(module)
  File "C:\Users\NWmLWB\Downloads\ChromeDownload\XX-Net-3.10.4\XX-Net-3.10.4\code\default\launcher\module_init.py", line
 40, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "C:\Users\NWmLWB\Downloads\ChromeDownload\XX-Net-3.10.4\XX-Net-3.10.4\code\default\gae_proxy\start.py", line 13,
in <module>
    import local.proxy as client
  File "C:\Users\NWmLWB\Downloads\ChromeDownload\XX-Net-3.10.4\XX-Net-3.10.4\code\default\gae_proxy\local\proxy.py", lin
e 95, in <module>
    import proxy_handler
  File "C:\Users\NWmLWB\Downloads\ChromeDownload\XX-Net-3.10.4\XX-Net-3.10.4\code\default\gae_proxy\local\proxy_handler.
py", line 55, in <module>
    import gae_handler
  File "C:\Users\NWmLWB\Downloads\ChromeDownload\XX-Net-3.10.4\XX-Net-3.10.4\code\default\gae_proxy\local\gae_handler.py
", line 79, in <module>
    from google_ip import google_ip
  File "C:\Users\NWmLWB\Downloads\ChromeDownload\XX-Net-3.10.4\XX-Net-3.10.4\code\default\gae_proxy\local\google_ip.py",
 line 732, in <module>
    google_ip = IpManager()
  File "C:\Users\NWmLWB\Downloads\ChromeDownload\XX-Net-3.10.4\XX-Net-3.10.4\code\default\gae_proxy\local\google_ip.py",
 line 67, in __init__
    self.reset()
  File "C:\Users\NWmLWB\Downloads\ChromeDownload\XX-Net-3.10.4\XX-Net-3.10.4\code\default\gae_proxy\local\google_ip.py",
 line 108, in reset
    self.load_ip()
  File "C:\Users\NWmLWB\Downloads\ChromeDownload\XX-Net-3.10.4\XX-Net-3.10.4\code\default\gae_proxy\local\google_ip.py",
 line 137, in load_ip
    with open(file_path, "r") as fd:
IOError: [Errno 2] No such file or directory: 'C:\\Users\\NWmLWB\\Downloads\\ChromeDownload\\XX-Net-3.10.4\\XX-Net-3.10.
4\\code\\default\\gae_proxy\\local\\good_ip.txt'

Press Enter to continue...Feb 25 02:54:41.449 [gae_proxy][DEBUG] network IPv4 is ok, cost:3284 ms
Feb 25 02:54:42.209 [gae_proxy][WARNING] network IPv6 fail

Stopping all modules before exit!
Feb 25 02:54:52.725 [launcher][ERROR] stop module gae_proxy fail:'imp'
Feb 25 02:54:52.730 [launcher][ERROR] Except stack:Traceback (most recent call last):
  File "C:\Users\NWmLWB\Downloads\ChromeDownload\XX-Net-3.10.4\XX-Net-3.10.4\code\default\launcher\module_init.py", line
 74, in stop
    _start = proc_handler[module]["imp"].start
KeyError: 'imp'

Feb 25 02:54:52.733 [launcher][INFO] begin to exit web control
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "C:\Python27\lib\atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "C:\Users\NWmLWB\Downloads\ChromeDownload\XX-Net-3.10.4\XX-Net-3.10.4\code\default\launcher\start.py", line 175,
in exit_handler
    web_control.stop()
  File "C:\Users\NWmLWB\Downloads\ChromeDownload\XX-Net-3.10.4\XX-Net-3.10.4\code\default\launcher\web_control.py", line
 693, in stop
    server.shutdown()
AttributeError: 'NoneType' object has no attribute 'shutdown'
Error in sys.exitfunc:
('uncaught Exception:', <type 'exceptions.AttributeError'>, AttributeError("'NoneType' object has no attribute 'shutdown
'",), <traceback object at 0x0000000002666A88>)
Feb 25 02:54:52.768 [launcher][ERROR] uncaught Exception, type=<type 'exceptions.AttributeError'> value='NoneType' objec
t has no attribute 'shutdown' traceback:<traceback object at 0x0000000002666A88>
```

* 请贴出相关的日志

## 常见问题：  
* 扫描不到GAE的ip  
   请尝试启用IPv6，参考  
   https://github.com/XX-net/XX-Net/wiki/%E5%A6%82%E4%BD%95%E5%BC%80%E5%90%AFIPv6    
   
   或者试试X-Tunnel 模块  
   https://github.com/XX-net/XX-Net/wiki/x-tunnel%E4%BD%BF%E7%94%A8%E6%95%99%E7%A8%8B  
   
* X-tunnel 无法连接  
  如果能够登录，请确认代理端口为1080.
  如果速度不稳定或无法登录，请贴出X-Tunnel 的Status页面。

**Comment by gjbg1989** [comment]
#9783 win7&10 32位😂开机及唤醒几乎秒秒均正常的非组策略😂经验

**Comment by xxnet** [comment]
​似乎是安装包下载不完全，请重新下载解压

**Comment by g8up** [comment]
```
用管理员权限运行start.bat, 命令行弹出来一下就退出了
```
这个问题可以换个方式，就能看到返回的信息。
- 打开 cmd 窗口，将要执行的 bat 文件拖放到 cmd 窗口中回车。
> 如何打开 cmd 窗口：windows 开始菜单中搜索： cmd
