### ISSUE TITLE
ubuntu无法展示127.0.0.1:8085

### ISSUE THREAD

**Issue by ZhangAllen98** [XX-net/XX-Net#9857]
版本3.10.4
原先没有原生ipv6,所以通过 install miredo来开启, ubuntu+firefox配置
现在突然有了原生的ipv6,但是看不到127.0.0.1:8085的配置界面了,
而chrome可以浏览google.com.hk并搜索, 但是访问不了youtube,而firefox则都不能,
请问这是什么情况?

**Comment by xxnet** [comment]
​netstat -napt |grep LIST 看看8085端口有没有

有的话,试试
wget http://127.0.0.1:8085/ 看看是否成功

**Comment by ZhangAllen98** [comment]
@xxnet 没有8085,倒是有8087,
然后应该如何做呢

**Comment by xxnet** [comment]
​把启动的日志贴来看

**Comment by ZhangAllen98** [comment]
Lenovo-Product:~/XXnet$ ./start 
XX-Net version:default
 2月 28 11:41:48.9 [launcher][INFO] import build-in openssl fail:ImportError('No module named pycparser',)
 2月 28 11:41:48.9 [launcher][INFO] start XX-Net 3.10.4
 2月 28 11:41:48.9 [launcher][DEBUG] start confirm_xxnet_exit
 2月 28 11:41:48.9 [launcher][DEBUG] good, xxnet:8085 clear!
 2月 28 11:41:48.9 [launcher][DEBUG] finished confirm_xxnet_exit
 2月 28 11:41:48.9 [gae_proxy][DEBUG] config use_ipv6 1 upgrade to auto
 2月 28 11:41:48.9 [gae_proxy][INFO] SSL use version:TLSv1
 2月 28 11:41:48.9 [gae_proxy][INFO] OpenSSL dont't support npn/alpn, no HTTP/2 supported.
 2月 28 11:41:48.9 [gae_proxy][INFO] load ip range file:/XXnet/code/default/gae_proxy/local/ip_range.txt
 2月 28 11:41:48.9 [gae_proxy][INFO] load google ip_list num:6000, gws num:6000
 2月 28 11:41:49.0 [gae_proxy][DEBUG] config use_ipv6 1 upgrade to auto
 2月 28 11:41:49.0 [gae_proxy][DEBUG] ## GAEProxy set keep_running: True
 2月 28 11:41:49.0 [gae_proxy][INFO] ------------------------------------------------------
 2月 28 11:41:49.0 [gae_proxy][INFO] Python Version     : 2.7.6
 2月 28 11:41:49.0 [gae_proxy][INFO] OS                 : Dist:Ubuntu; Version:14.04; ID:trusty
 2月 28 11:41:49.0 [gae_proxy][INFO] Listen Address     : 127.0.0.1:8087
 2月 28 11:41:49.0 [gae_proxy][INFO] GAE APPID          : ((略))
 2月 28 11:41:49.0 [gae_proxy][INFO] ------------------------------------------------------
 2月 28 11:41:49.0 [gae_proxy][DEBUG] Importing CA
 2月 28 11:41:49.0 [gae_proxy][INFO] Database $HOME/.pki/nssdb cert exist
 2月 28 11:41:49.0 [gae_proxy][DEBUG] Begin importing CA to Firefox
 2月 28 11:41:49.0 [gae_proxy][INFO] Removing old cert to Firefox in /.mozilla/firefox/4w2mkjnq.default
GoAgent XX-Net - GoAgent                                     C,,  
 2月 28 11:41:49.1 [gae_proxy][INFO] Add new cert to Firefox in /.mozilla/firefox/4w2mkjnq.default
 2月 28 11:41:49.1 [gae_proxy][ERROR] bind to 127.0.0.1:8087 fail:error(98,** '\xe5\x9c\xb0\xe5\x9d\x80\xe5\xb7\xb2\xe5\x9c\xa8\xe4\xbd\xbf\xe7\x94\xa8')
Exception in thread Thread-510:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/XXnet/code/default/gae_proxy/start.py", line 18, in main
    client.main(args)
  File "/XXnet/code/default/gae_proxy/local/proxy.py", line 147, in main
    proxy_daemon = simple_http_server.HTTPServer((listen_ip, config.LISTEN_PORT), proxy_handler.GAEProxyHandler, logger=xlog)
  File "/XXnet/code/default/python27/1.0/lib/noarch/simple_http_server.py", line 403, in __init__
    self.init_socket()
  File "/XXnet/code/default/python27/1.0/lib/noarch/simple_http_server.py", line 413, in init_socket
    self.add_listen(addr)
  File "/XXnet/code/default/python27/1.0/lib/noarch/simple_http_server.py", line 427, in add_listen
    raise Exception(err_string)
Exception: bind to 127.0.0.1:8087 fail:error(98, '\xe5\x9c\xb0\xe5\x9d\x80\xe5\xb7\xb2\xe5\x9c\xa8\xe4\xbd\xbf\xe7\x94\xa8')

 2月 28 11:41:49.2 [gae_proxy][DEBUG] network IPv4 is ok, cost:343 ms
 2月 28 11:41:49.5 [gae_proxy][DEBUG] network IPv6 is ok, cost:637 ms
 2月 28 11:41:49.7 [gae_proxy][DEBUG] create_ssl update ip:2607:f8b0:400a:3::19 time:396 h2:0
 2月 28 11:41:49.8 [gae_proxy][DEBUG] create_ssl update ip:2607:f8b0:400a:1::e time:406 h2:0
 2月 28 11:41:50.2 [gae_proxy][DEBUG] create_ssl update ip:2607:f8b0:400a::12 time:458 h2:0
 2月 28 11:41:50.3 [gae_proxy][DEBUG] create_ssl update ip:2607:f8b0:400a:3::16 time:433 h2:0
 2月 28 11:41:50.7 [gae_proxy][DEBUG] create_ssl update ip:2607:f8b0:400a:8::6 time:456 h2:0
 2月 28 11:41:51.0 [gae_proxy][DEBUG] create_ssl update ip:2607:f8b0:400a:3::e time:452 h2:0
 2月 28 11:41:51.2 [gae_proxy][DEBUG] create_ssl update ip:2607:f8b0:400a:c::8 time:443 h2:0
 2月 28 11:41:51.4 [gae_proxy][DEBUG] create_ssl update ip:2607:f8b0:400a:f::c time:410 h2:0
 2月 28 11:41:51.6 [gae_proxy][DEBUG] create_ssl update ip:2607:f8b0:400a:12::c time:412 h2:0
 2月 28 11:41:51.7 [gae_proxy][DEBUG] create_ssl update ip:2607:f8b0:401c:b::b time:469 h2:0
 2月 28 11:41:52.0 [gae_proxy][DEBUG] create_ssl update ip:2607:f8b0:4012:b::8 time:494 h2:0
 2月 28 11:41:52.1 [gae_proxy][DEBUG] create_ssl update ip:2607:f8b0:400a:e::b time:415 h2:0
 2月 28 11:41:52.5 [gae_proxy][DEBUG] create_ssl update ip:2607:f8b0:4013:4::a time:551 h2:0
 2月 28 11:41:52.5 [gae_proxy][DEBUG] create_ssl update ip:2607:f8b0:4016:1b::b time:572 h2:0
 2月 28 11:41:52.8 [gae_proxy][DEBUG] create_ssl update ip:2607:f8b0:4002:17::6 time:563 h2:0
 2月 28 11:41:53.0 [gae_proxy][DEBUG] create_ssl update ip:2607:f8b0:4002:1c::13 time:547 h2:0
 2月 28 11:41:53.1 [gae_proxy][DEBUG] create_ssl update ip:2607:f8b0:400a:f::b time:389 h2:0
 2月 28 11:41:53.2 [gae_proxy][DEBUG] create_ssl update ip:2607:f8b0:4009:2d::c time:498 h2:0
 2月 28 11:41:53.2 [gae_proxy][DEBUG] create_ssl update ip:2607:f8b0:400a:c::e time:399 h2:0
 2月 28 11:41:53.3 [gae_proxy][DEBUG] create_ssl update ip:2607:f8b0:4002:10::b time:528 h2:0
 2月 28 11:41:53.6 [gae_proxy][DEBUG] create_ssl update ip:2607:f8b0:400a:8::18 time:436 h2:0
 2月 28 11:41:53.7 [gae_proxy][DEBUG] create_ssl update ip:2607:f8b0:401a:5::7 time:513 h2:0
 2月 28 11:41:53.7 [gae_proxy][DEBUG] create_ssl update ip:2607:f8b0:400a:e::6 time:428 h2:0
 2月 28 11:41:53.8 [gae_proxy][DEBUG] create_ssl update ip:2607:f8b0:401d:1e::a time:464 h2:0
 2月 28 11:41:54.3 [gae_proxy][DEBUG] create_ssl update ip:2607:f8b0:4002:17::b time:535 h2:0
 2月 28 11:41:57.5 [gae_proxy][DEBUG] connect 2607:f8b0:4016:13::f fail:timeout('timed out',)
 2月 28 11:41:57.5 [gae_proxy][DEBUG] report_connect_fail:2607:f8b0:4016:13::f
 2月 28 11:42:12.5 [gae_proxy][DEBUG] ip:2607:f8b0:4016:13::f real fail
2月 28 11:45:15.3 [gae_proxy][DEBUG] 2607:f8b0:400a:3::19 worker close:idle timeout
 2月 28 11:45:15.5 [gae_proxy][DEBUG] 2607:f8b0:400a::12 worker close:idle timeout
 2月 28 11:45:15.6 [gae_proxy][DEBUG] 2607:f8b0:400a:3::16 worker close:idle timeout
 2月 28 11:45:16.0 [gae_proxy][DEBUG] 2607:f8b0:400a:8::6 worker close:idle timeout
 2月 28 11:45:16.3 [gae_proxy][DEBUG] 2607:f8b0:400a:3::e worker close:idle timeout
 2月 28 11:45:16.4 [gae_proxy][DEBUG] 2607:f8b0:400a:c::8 worker close:idle timeout
 2月 28 11:45:16.7 [gae_proxy][DEBUG] 2607:f8b0:400a:f::c worker close:idle timeout
 2月 28 11:45:16.9 [gae_proxy][DEBUG] 2607:f8b0:400a:12::c worker close:idle timeou

~$ sudo netstat -napt | grep LIST
tcp        0      0 0.0.0.0:139             0.0.0.0:*               LISTEN      717/smbd        
tcp        0      0 127.0.1.1:53            0.0.0.0:*               LISTEN      2663/dnsmasq    
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1235/sshd       
tcp        0      0 127.0.0.1:631           0.0.0.0:*               LISTEN      2324/cupsd      
tcp        0      0 127.0.0.1:8087          0.0.0.0:*               LISTEN      1433/python     
tcp        0      0 0.0.0.0:445             0.0.0.0:*               LISTEN      717/smbd        
tcp6       0      0 :::139                  :::*                    LISTEN      717/smbd        
tcp6       0      0 :::22                   :::*                    LISTEN      1235/sshd       
tcp6       0      0 ::1:631                 :::*                    LISTEN      2324/cupsd      
tcp6       0      0 :::445                  :::*                    LISTEN      717/smbd 

@xxnet 麻烦您了

**Comment by xxnet** [comment]
​8087 端口被占用了？

tcp 0 0 127.0.0.1:8087 0.0.0.0:* LISTEN 1433/python

试试 kill 1433
再试试

**Comment by ZhangAllen98** [comment]
@xxnet 
kill掉之后,墙外的网站好像都正常,但是墙内的不能浏览.(用的是GAE模块)
同时尽管会出现状态栏图标,但是点击并没有反应...不能出配置界面

**Comment by xxnet** [comment]
​1. 操作失败时，看看日志有什么异常输出。
2. 配置界面，可以直接用浏览器访问 127.0.0.1:8085

**Comment by ZhangAllen98** [comment]
= =就是用浏览器访问不了127.0.0.1:8085

**Comment by xxnet** [comment]
​请贴出日志分析

**Comment by ZhangAllen98** [comment]
已正常工作.
先sudo apt-get install python-pycparser后,
重新安装xxnet之后解决
