### ISSUE TITLE
xx net 3.10.4 其他网页正常能打开，但无法打开youtube

### ISSUE THREAD

**Issue by zhengyqy** [XX-net/XX-Net#9862]
XX-Net Status:

sys-platform: AMD64, Windows-10-10.0.15063
os-system: Windows
os-version: 10.0.15063
os-release: 10
os-detail: Version:10-0; Build:15063; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36
xxnet-version: 3.10.4
python-version: 2.7.13
openssl-version: 16.0.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:47 ipv4:0 ipv6:47
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:0
worker: h1:32 h2:0
scan-ip-thread-num: 200
ip-quality: 365
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

显示错误：
Feb 27 17:00:26.718 [simple_http_server][ERROR] Except stack:Traceback (most recent call last):
  File "C:\myself\fanqiang\XX-Net-3.3.1\XX-Net-3.3.1\code\3.10.4\python27\1.0\lib\noarch\simple_http_server.py", line 166, in handle_one_request
    self.do_CONNECT()
  File "C:\myself\fanqiang\XX-Net-3.3.1\XX-Net-3.3.1\code\3.10.4\gae_proxy\local\proxy_handler.py", line 289, in do_CONNECT
    return self.do_CONNECT_AGENT()
  File "C:\myself\fanqiang\XX-Net-3.3.1\XX-Net-3.3.1\code\3.10.4\gae_proxy\local\proxy_handler.py", line 296, in do_CONNECT_AGENT
    certfile = CertUtil.get_cert(host)
  File "C:\myself\fanqiang\XX-Net-3.3.1\XX-Net-3.3.1\code\3.10.4\gae_proxy\local\cert_util.py", line 292, in get_cert
    certfile = CertUtil._get_old_cert(commonname)
  File "C:\myself\fanqiang\XX-Net-3.3.1\XX-Net-3.3.1\code\3.10.4\gae_proxy\local\cert_util.py", line 277, in _get_old_cert
    cert = OpenSSL.crypto.load_certificate(OpenSSL.crypto.FILETYPE_PEM, fp.read())
  File "C:\myself\fanqiang\XX-Net-3.3.1\XX-Net-3.3.1\code\3.10.4\python27\1.0\lib\noarch\OpenSSL\crypto.py", line 1608, in load_certificate
    _raise_current_error()
  File "C:\myself\fanqiang\XX-Net-3.3.1\XX-Net-3.3.1\code\3.10.4\python27\1.0\lib\noarch\OpenSSL\_util.py", line 48, in exception_from_error_queue
    raise exception_type(errors)
Error: [('PEM routines', 'PEM_read_bio', 'no start line')]

Feb 27 17:00:26.928 [simple_http_server][ERROR] handler:Error([('PEM routines', 'PEM_read_bio', 'no start line')],) cmd:CONNECT path:www.youtube.com:443 from:127.0.0.1:59011
Feb 27 17:00:26.932 [simple_http_server][ERROR] Except stack:Traceback (most recent call last):
  File "C:\myself\fanqiang\XX-Net-3.3.1\XX-Net-3.3.1\code\3.10.4\python27\1.0\lib\noarch\simple_http_server.py", line 166, in handle_one_request
    self.do_CONNECT()
  File "C:\myself\fanqiang\XX-Net-3.3.1\XX-Net-3.3.1\code\3.10.4\gae_proxy\local\proxy_handler.py", line 289, in do_CONNECT
    return self.do_CONNECT_AGENT()
  File "C:\myself\fanqiang\XX-Net-3.3.1\XX-Net-3.3.1\code\3.10.4\gae_proxy\local\proxy_handler.py", line 296, in do_CONNECT_AGENT
    certfile = CertUtil.get_cert(host)
  File "C:\myself\fanqiang\XX-Net-3.3.1\XX-Net-3.3.1\code\3.10.4\gae_proxy\local\cert_util.py", line 292, in get_cert
    certfile = CertUtil._get_old_cert(commonname)
  File "C:\myself\fanqiang\XX-Net-3.3.1\XX-Net-3.3.1\code\3.10.4\gae_proxy\local\cert_util.py", line 277, in _get_old_cert
    cert = OpenSSL.crypto.load_certificate(OpenSSL.crypto.FILETYPE_PEM, fp.read())
  File "C:\myself\fanqiang\XX-Net-3.3.1\XX-Net-3.3.1\code\3.10.4\python27\1.0\lib\noarch\OpenSSL\crypto.py", line 1608, in load_certificate
    _raise_current_error()
  File "C:\myself\fanqiang\XX-Net-3.3.1\XX-Net-3.3.1\code\3.10.4\python27\1.0\lib\noarch\OpenSSL\_util.py", line 48, in exception_from_error_queue
    raise exception_type(errors)
Error: [('PEM routines', 'PEM_read_bio', 'no start line')]

**Comment by zhishuixue** [comment]
同样的问题，都不能打开YOUTUBE！！

**Comment by xxnet** [comment]
​把 data/gae_proxy/certs/下的文件都删了 试试

**Comment by dahai058** [comment]
一直用的挺好但今晚上11点多钟突然也打不开youtube了。其它网站正常。data/gae_proxy/certs/下的文件删了也不行。我的是3.9.6版

**Comment by gjbg1989** [comment]
![default](https://user-images.githubusercontent.com/13290970/36800308-2e68600e-1cea-11e8-96f1-ed338092ea3f.png)

**Comment by gjbg1989** [comment]
![default](https://user-images.githubusercontent.com/13290970/36800659-017379fc-1ceb-11e8-8294-4c92b2ccd8b6.png)
既然：超过则剔除延时高的IP
貌似系统值现6000没有原3000合适？ @xxnet

**Comment by xxnet** [comment]
​后面会改成100，IPv6时代，不需要保留那么多的Ip了

**Comment by dahai058** [comment]
智能路由模式改为pac模式正常了。不知何原因？

**Comment by gjbg1989** [comment]
😂智能路由模式哪版强？当然是3.10.4（强过3.9.6）
