### ISSUE TITLE
ubuntu 14.04 无法展示127.0.0.1:8085，8087端口未占用。无法在浏览器中展示配置页面。

### ISSUE THREAD

**Issue by 1MarsTom** [XX-net/XX-Net#9872]
@xxnet 
//root 日志
Feb 28 01:49:39.505 - [INFO] import build-in openssl fail:ImportError('No module named pycparser',)
Feb 28 01:49:39.508 - [INFO] start XX-Net 3.10.4
Feb 28 01:49:39.508 - [DEBUG] start confirm_xxnet_exit
Feb 28 01:49:39.509 - [DEBUG] good, xxnet:8085 clear!
Feb 28 01:49:39.510 - [DEBUG] finished confirm_xxnet_exit
Feb 28 01:50:16.216 - [INFO] import build-in openssl fail:ImportError('No module named pycparser',)
Feb 28 01:50:16.218 - [INFO] start XX-Net 3.10.4
Feb 28 01:50:16.218 - [DEBUG] start confirm_xxnet_exit
Feb 28 01:50:16.220 - [DEBUG] good, xxnet:8085 clear!
Feb 28 01:50:16.220 - [DEBUG] finished confirm_xxnet_exit
Feb 28 01:50:16.414 - [INFO] module gae_proxy started
Feb 28 01:50:16.415 - [INFO] start gae_proxy time cost:194 ms
Feb 28 01:50:16.422 - [ERROR] start module x_tunnel fail:Context() takes at most 1 argument (2 given)
Feb 28 01:50:16.422 - [ERROR] Except stack:Traceback (most recent call last):
  File "/home/bing/XX-Net-3.10.4/code/default/launcher/module_init.py", line 40, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "/home/bing/XX-Net-3.10.4/code/default/x_tunnel/start.py", line 14, in <module>
    import local.client as client
  File "/home/bing/XX-Net-3.10.4/code/default/x_tunnel/local/client.py", line 44, in <module>
    import web_control
  File "/home/bing/XX-Net-3.10.4/code/default/x_tunnel/local/web_control.py", line 17, in <module>
    from cloudflare_front import web_control as cloudflare_web
  File "/home/bing/XX-Net-3.10.4/code/default/x_tunnel/local/cloudflare_front/__init__.py", line 2, in <module>
    import apis
  File "/home/bing/XX-Net-3.10.4/code/default/x_tunnel/local/cloudflare_front/apis.py", line 2, in <module>
    from front import front
  File "/home/bing/XX-Net-3.10.4/code/default/x_tunnel/local/cloudflare_front/front.py", line 213, in <module>
    front = Front()
  File "/home/bing/XX-Net-3.10.4/code/default/x_tunnel/local/cloudflare_front/front.py", line 45, in __init__
    openssl_context = SSLContext(logger, ca_certs=ca_certs)
TypeError: Context() takes at most 1 argument (2 given)

Feb 28 01:50:16.422 - [ERROR] launcher except:TypeError('Context() takes at most 1 argument (2 given)',)
Feb 28 01:50:16.423 - [ERROR] Except stack:Traceback (most recent call last):
  File "/home/bing/XX-Net-3.10.4/code/default/launcher/start.py", line 230, in <module>
    main()
  File "/home/bing/XX-Net-3.10.4/code/default/launcher/start.py", line 207, in main
    module_init.start_all_auto()
  File "/home/bing/XX-Net-3.10.4/code/default/launcher/module_init.py", line 113, in start_all_auto
    start(module)
  File "/home/bing/XX-Net-3.10.4/code/default/launcher/module_init.py", line 40, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "/home/bing/XX-Net-3.10.4/code/default/x_tunnel/start.py", line 14, in <module>
    import local.client as client
  File "/home/bing/XX-Net-3.10.4/code/default/x_tunnel/local/client.py", line 44, in <module>
    import web_control
  File "/home/bing/XX-Net-3.10.4/code/default/x_tunnel/local/web_control.py", line 17, in <module>
    from cloudflare_front import web_control as cloudflare_web
  File "/home/bing/XX-Net-3.10.4/code/default/x_tunnel/local/cloudflare_front/__init__.py", line 2, in <module>
    import apis
  File "/home/bing/XX-Net-3.10.4/code/default/x_tunnel/local/cloudflare_front/apis.py", line 2, in <module>
    from front import front
  File "/home/bing/XX-Net-3.10.4/code/default/x_tunnel/local/cloudflare_front/front.py", line 213, in <module>
    front = Front()
  File "/home/bing/XX-Net-3.10.4/code/default/x_tunnel/local/cloudflare_front/front.py", line 45, in __init__
    openssl_context = SSLContext(logger, ca_certs=ca_certs)
TypeError: Context() takes at most 1 argument (2 given)

//普通用户日志
Feb 28 01:24:19.132 - [INFO] import build-in openssl fail:ImportError('No module named pycparser',)
Feb 28 01:24:19.135 - [INFO] start XX-Net 3.10.4
Feb 28 01:24:19.135 - [DEBUG] start confirm_xxnet_exit
Feb 28 01:24:19.138 - [DEBUG] good, xxnet:8085 clear!
Feb 28 01:24:19.138 - [DEBUG] finished confirm_xxnet_exit
Feb 28 01:24:19.348 - [INFO] module gae_proxy started
Feb 28 01:24:19.348 - [INFO] start gae_proxy time cost:210 ms
Feb 28 01:24:19.355 - [ERROR] start module x_tunnel fail:Context() takes at most 1 argument (2 given)
Feb 28 01:24:19.356 - [ERROR] Except stack:Traceback (most recent call last):
  File "/home/bing/XX-Net-3.10.4/code/default/launcher/module_init.py", line 40, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "/home/bing/XX-Net-3.10.4/code/default/x_tunnel/start.py", line 14, in <module>
    import local.client as client
  File "/home/bing/XX-Net-3.10.4/code/default/x_tunnel/local/client.py", line 44, in <module>
    import web_control
  File "/home/bing/XX-Net-3.10.4/code/default/x_tunnel/local/web_control.py", line 17, in <module>
    from cloudflare_front import web_control as cloudflare_web
  File "/home/bing/XX-Net-3.10.4/code/default/x_tunnel/local/cloudflare_front/__init__.py", line 2, in <module>
    import apis
  File "/home/bing/XX-Net-3.10.4/code/default/x_tunnel/local/cloudflare_front/apis.py", line 2, in <module>
    from front import front
  File "/home/bing/XX-Net-3.10.4/code/default/x_tunnel/local/cloudflare_front/front.py", line 213, in <module>
    front = Front()
  File "/home/bing/XX-Net-3.10.4/code/default/x_tunnel/local/cloudflare_front/front.py", line 45, in __init__
    openssl_context = SSLContext(logger, ca_certs=ca_certs)
TypeError: Context() takes at most 1 argument (2 given)

Feb 28 01:24:19.356 - [ERROR] launcher except:TypeError('Context() takes at most 1 argument (2 given)',)
Feb 28 01:24:19.356 - [ERROR] Except stack:Traceback (most recent call last):
  File "code/default/launcher/start.py", line 230, in <module>
  File "code/default/launcher/start.py", line 207, in main
  File "/home/bing/XX-Net-3.10.4/code/default/launcher/module_init.py", line 113, in start_all_auto
    start(module)
  File "/home/bing/XX-Net-3.10.4/code/default/launcher/module_init.py", line 40, in start
    proc_handler[module]["imp"] = __import__(module, globals(), locals(), ['local', 'start'], -1)
  File "/home/bing/XX-Net-3.10.4/code/default/x_tunnel/start.py", line 14, in <module>
    import local.client as client
  File "/home/bing/XX-Net-3.10.4/code/default/x_tunnel/local/client.py", line 44, in <module>
    import web_control
  File "/home/bing/XX-Net-3.10.4/code/default/x_tunnel/local/web_control.py", line 17, in <module>
    from cloudflare_front import web_control as cloudflare_web
  File "/home/bing/XX-Net-3.10.4/code/default/x_tunnel/local/cloudflare_front/__init__.py", line 2, in <module>
    import apis
  File "/home/bing/XX-Net-3.10.4/code/default/x_tunnel/local/cloudflare_front/apis.py", line 2, in <module>
    from front import front
  File "/home/bing/XX-Net-3.10.4/code/default/x_tunnel/local/cloudflare_front/front.py", line 213, in <module>
    front = Front()
  File "/home/bing/XX-Net-3.10.4/code/default/x_tunnel/local/cloudflare_front/front.py", line 45, in __init__
    openssl_context = SSLContext(logger, ca_certs=ca_certs)
TypeError: Context() takes at most 1 argument (2 given)

谢谢！！！

**Comment by xxnet** [comment]
​试试 sudo apt-get install python-pycparser

**Comment by hanwei2008** [comment]
已解决。

1、关掉XX-Net；

2、修改一行代码。找到XX-Net目录下code/default/python27/1.0/lib/noarch/front_base/openssl_wrap.py python脚本第216行。 将

`class SSLContext(OpenSSL.SSL.Context):`

修改为：

`class SSLContext():`

3、重新启动XX-Net

**Comment by xxnet** [comment]
​gae_proxy的状态页贴来看看，是什么系统会这样

**Comment by 1MarsTom** [comment]
@xxnet gae_proxy状态页是启动时的状态吗？

系统是Ubuntu 14.04，当初用的是XX_3.10.4版本。改用Windows虚拟机中对应的data替换之后就可以出现浏览器配置界面了。现在能够顺利运行。
