### ISSUE TITLE
GAE Get IP 异常

### ISSUE THREAD

**Issue by wangxvhu** [XX-net/XX-Net#9967]
升级3.10.8出现下面问题，还请大神帮看看是什么原因。

Mar 12 08:27:32.755 - [INFO] GAE t:567 s:493 POST https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=18BSyd/cTuMO7xomNExnSg%3D%3D 0:start_request,0:get_task(0),0:get_worker(0):183.91.238.117,0:h2_req,0:start send header,0:start send left body,0:end send left body,551:h2_get_head,0:get_response,:16

Mar 12 08:27:33.876 - [WARNING] get_public_appid fail

Mar 12 08:27:39.854 - [WARNING] get_public_appid fail

Mar 12 08:27:39.854 - [WARNING] get_public_appid fail

Mar 12 08:27:41.282 - [WARNING] get_public_appid fail

Mar 12 08:27:42.299 - [WARNING] get_slice fail

Mar 12 08:27:42.299 - [ERROR] google_ip.runJob fail:Exception()

Mar 12 08:27:42.299 - [ERROR] Except stack:Traceback (most recent call last): File "C:\Disk D\XX-Net-3.9.6\code\3.10.8\python27\1.0\lib\noarch\front_base\ip_manager.py", line 639, in scan_ip_worker ip = self.ip_source.get_ip() File "C:\Disk D\XX-Net-3.9.6\code\3.10.8\python27\1.0\lib\noarch\front_base\ip_source.py", line 238, in get_ip return self.ipv6_source.get_ip() File "C:\Disk D\XX-Net-3.9.6\code\3.10.8\python27\1.0\lib\noarch\front_base\ip_source.py", line 211, in get_ip line = self.get_slice() File "C:\Disk D\XX-Net-3.9.6\code\3.10.8\python27\1.0\lib\noarch\front_base\ip_source.py", line 204, in get_slice raise Exception() Exception

Mar 12 08:27:45.097 - [WARNING] get_public_appid fail

Mar 12 08:27:46.741 - [WARNING] get_public_appid fail

Mar 12 08:27:46.741 - [WARNING] get_public_appid fail

Mar 12 08:27:48.224 - [WARNING] get_public_appid fail

Mar 12 08:27:48.225 - [WARNING] get_public_appid fail

**Comment by SeaHOH** [comment]
感觉更新不完整，检查下 code\3.10.8\gae_proxy\local 的 txt 文件
